// @ts-nocheck
import {
  workdayListWorkers,
  workdayGetWorker,
  workdayGetWorkerOrganizations,
  workdayGetWorkerSupervisoryOrgs,
  workdayGetWorkerReports,
  workdayGetWorkerHistory,
  workdayGetBusinessTitleChanges,
  workdayCreateBusinessTitleChange,
  workdayCreateJobChange,
  workdayGetPaySlips,
} from './workers.js';
import {
  workdayListOrganizations,
  workdayGetOrganization,
  workdayListSupervisoryOrganizations,
  workdayGetSupervisoryOrganization,
  workdayListSupervisoryOrgWorkers,
  workdayListOrganizationTypes,
} from './organizations.js';
import {
  workdayListPositions,
  workdayGetPosition,
  workdayListJobProfiles,
  workdayGetJobProfile,
} from './staffing.js';
import {
  workdayListJobPostings,
  workdayGetJobPosting,
  workdayGetProspectEducations,
  workdayGetProspectExperiences,
  workdayCreateProspectExperience,
  workdayGetProspectResumeAttachments,
  workdayGetProspectSkills,
  workdayListTalentPools,
  workdayGetInterviewFeedback,
} from './recruiting.js';
import {
  workdayRequestTimeOff,
  workdayGetValidTimeOffDates,
  workdayGetWorkerLeaves,
  workdayGetWorkerLeave,
} from './absence.js';
import { workdayRunWqlQuery, workdayRunCustomReport } from './insights.js';

export {
  workdayListWorkers,
  workdayGetWorker,
  workdayGetWorkerOrganizations,
  workdayGetWorkerSupervisoryOrgs,
  workdayGetWorkerReports,
  workdayGetWorkerHistory,
  workdayGetBusinessTitleChanges,
  workdayCreateBusinessTitleChange,
  workdayCreateJobChange,
  workdayGetPaySlips,
  workdayListOrganizations,
  workdayGetOrganization,
  workdayListSupervisoryOrganizations,
  workdayGetSupervisoryOrganization,
  workdayListSupervisoryOrgWorkers,
  workdayListOrganizationTypes,
  workdayListPositions,
  workdayGetPosition,
  workdayListJobProfiles,
  workdayGetJobProfile,
  workdayListJobPostings,
  workdayGetJobPosting,
  workdayGetProspectEducations,
  workdayGetProspectExperiences,
  workdayCreateProspectExperience,
  workdayGetProspectResumeAttachments,
  workdayGetProspectSkills,
  workdayListTalentPools,
  workdayGetInterviewFeedback,
  workdayRequestTimeOff,
  workdayGetValidTimeOffDates,
  workdayGetWorkerLeaves,
  workdayGetWorkerLeave,
  workdayRunWqlQuery,
  workdayRunCustomReport,
};

const AUTH = 'workdayCredentials' as const;

export const workdayTools = [
  {
    name: 'workdayListWorkers',
    description: 'List workers (employees and contingent workers) with search.',
    tool: workdayListWorkers,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['employees', 'staff', 'directory'],
  },
  {
    name: 'workdayGetWorker',
    description: 'Get detailed worker profile by Workday ID.',
    tool: workdayGetWorker,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['employee', 'profile', 'fetch'],
  },
  {
    name: 'workdayGetWorkerOrganizations',
    description: 'Get organizations a worker belongs to.',
    tool: workdayGetWorkerOrganizations,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['employee', 'teams', 'departments'],
  },
  {
    name: 'workdayGetWorkerSupervisoryOrgs',
    description: 'Get supervisory organizations of a worker.',
    tool: workdayGetWorkerSupervisoryOrgs,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['employee', 'manager', 'chain'],
  },
  {
    name: 'workdayGetWorkerReports',
    description: 'Get direct reports of a manager.',
    tool: workdayGetWorkerReports,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['team', 'subordinates', 'org-chart'],
  },
  {
    name: 'workdayGetWorkerHistory',
    description: 'Get worker history events (hires, transfers, changes).',
    tool: workdayGetWorkerHistory,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['employee', 'timeline', 'events'],
  },
  {
    name: 'workdayGetBusinessTitleChanges',
    description: 'List business title changes for a worker.',
    tool: workdayGetBusinessTitleChanges,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['promotion', 'title', 'history'],
  },
  {
    name: 'workdayCreateBusinessTitleChange',
    description: 'Propose a new business title effective on a date.',
    tool: workdayCreateBusinessTitleChange,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['promotion', 'title', 'retitle'],
  },
  {
    name: 'workdayCreateJobChange',
    description: 'Initiate a transfer, promotion, or position move.',
    tool: workdayCreateJobChange,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['transfer', 'promotion', 'move'],
  },
  {
    name: 'workdayGetPaySlips',
    description: 'Get payslips with gross and net pay per period.',
    tool: workdayGetPaySlips,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['payroll', 'salary', 'payslip'],
  },
  {
    name: 'workdayListOrganizations',
    description: 'List organizations with search and pagination.',
    tool: workdayListOrganizations,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['company', 'departments', 'units'],
  },
  {
    name: 'workdayGetOrganization',
    description: 'Get a single organization by ID.',
    tool: workdayGetOrganization,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['company', 'fetch', 'unit'],
  },
  {
    name: 'workdayListSupervisoryOrganizations',
    description: 'List supervisory organizations with search.',
    tool: workdayListSupervisoryOrganizations,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['managers', 'hierarchy', 'teams'],
  },
  {
    name: 'workdayGetSupervisoryOrganization',
    description: 'Get a supervisory organization with manager info.',
    tool: workdayGetSupervisoryOrganization,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['manager', 'fetch', 'team'],
  },
  {
    name: 'workdayListSupervisoryOrgWorkers',
    description: 'List workers in a supervisory organization.',
    tool: workdayListSupervisoryOrgWorkers,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['team', 'members', 'staff'],
  },
  {
    name: 'workdayListOrganizationTypes',
    description: 'List organization types in the tenant.',
    tool: workdayListOrganizationTypes,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['categories', 'kinds'],
  },
  {
    name: 'workdayListPositions',
    description: 'List staffing positions.',
    tool: workdayListPositions,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['jobs', 'roles', 'headcount'],
  },
  {
    name: 'workdayGetPosition',
    description: 'Get a single position by ID.',
    tool: workdayGetPosition,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['job', 'role', 'fetch'],
  },
  {
    name: 'workdayListJobProfiles',
    description: 'List job profiles from the job catalog.',
    tool: workdayListJobProfiles,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['jobs', 'catalog', 'roles'],
  },
  {
    name: 'workdayGetJobProfile',
    description: 'Get a single job profile by ID.',
    tool: workdayGetJobProfile,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['job', 'fetch', 'description'],
  },
  {
    name: 'workdayListJobPostings',
    description: 'List open job postings for recruiting.',
    tool: workdayListJobPostings,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['requisitions', 'openings', 'hiring'],
  },
  {
    name: 'workdayGetJobPosting',
    description: 'Get a single job posting by ID.',
    tool: workdayGetJobPosting,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['requisition', 'fetch', 'opening'],
  },
  {
    name: 'workdayGetProspectEducations',
    description: 'Get education history of a prospect.',
    tool: workdayGetProspectEducations,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['candidate', 'degrees', 'schools'],
  },
  {
    name: 'workdayGetProspectExperiences',
    description: 'Get work experience of a prospect.',
    tool: workdayGetProspectExperiences,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['candidate', 'resume', 'career'],
  },
  {
    name: 'workdayCreateProspectExperience',
    description: 'Add a work experience record to a prospect.',
    tool: workdayCreateProspectExperience,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['candidate', 'resume', 'add'],
  },
  {
    name: 'workdayGetProspectResumeAttachments',
    description: 'List resume attachments of a prospect.',
    tool: workdayGetProspectResumeAttachments,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['candidate', 'cv', 'files'],
  },
  {
    name: 'workdayGetProspectSkills',
    description: 'Get skills of a recruiting prospect.',
    tool: workdayGetProspectSkills,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['candidate', 'competencies'],
  },
  {
    name: 'workdayListTalentPools',
    description: 'List talent pools for pipelining candidates.',
    tool: workdayListTalentPools,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['pipeline', 'candidates', 'bench'],
  },
  {
    name: 'workdayGetInterviewFeedback',
    description: 'Get interview feedback for an interview.',
    tool: workdayGetInterviewFeedback,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['hiring', 'review', 'scorecard'],
  },
  {
    name: 'workdayRequestTimeOff',
    description: 'Submit a time-off request with absence type and days.',
    tool: workdayRequestTimeOff,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['vacation', 'leave', 'pto', 'absence'],
  },
  {
    name: 'workdayGetValidTimeOffDates',
    description: 'Get valid time-off dates in a range.',
    tool: workdayGetValidTimeOffDates,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['vacation', 'calendar', 'availability'],
  },
  {
    name: 'workdayGetWorkerLeaves',
    description: 'List leaves of absence for a worker.',
    tool: workdayGetWorkerLeaves,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['loa', 'absence', 'leave'],
  },
  {
    name: 'workdayGetWorkerLeave',
    description: 'Get a single leave of absence record.',
    tool: workdayGetWorkerLeave,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['loa', 'fetch', 'absence'],
  },
  {
    name: 'workdayRunWqlQuery',
    description: 'Run an ad-hoc WQL query for HR data.',
    tool: workdayRunWqlQuery,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['sql', 'query', 'analytics', 'report'],
  },
  {
    name: 'workdayRunCustomReport',
    description: 'Execute a RaaS custom report web service as JSON/CSV.',
    tool: workdayRunCustomReport,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['raas', 'report', 'export'],
  },
];
