// @ts-nocheck
import {
  makeListScenarios,
  makeGetScenario,
  makeDeleteScenario,
  makeUpdateScenario,
  makeGetScenarioBlueprint,
  makeGetScenarioInterface,
  makeUpdateScenarioInterface,
  makeGetScenarioLogs,
  makeGetScenarioTriggers,
  makeListIncompleteExecutions,
} from './scenarios.js';
import {
  makeCreateHook,
  makeGetHook,
  makeGetHookIncomingActivity,
  makeGetHookLog,
  makeListHookLogs,
} from './hooks.js';
import {
  makeCreateOrganization,
  makeGetOrganization,
  makeListOrganizations,
  makeGetOperations,
  makeGetTeam,
  makeListTeams,
} from './organizations.js';
import {
  makeGetConnection,
  makeListConnections,
  makeGetCurrentUser,
  makeGetCurrentAuthorization,
  makeCreatePasswordResetDemand,
  makePing,
  makeSetSdkConnectionApi,
} from './connections.js';
import {
  makeGetAppsReviewStatuses,
  makeGetImtRegions,
  makeGetImtZones,
  makeGetLlmModels,
  makeGetModuleTypes,
  makeGetOrganizationFeatures,
  makeGetUserApiTokenScopes,
  makeGetUserEmailNotifications,
  makeGetUserFeatures,
  makeGetVariableTypes,
  makeListCountries,
  makeListLanguages,
  makeListLlmBuiltinTiers,
  makeListLocales,
  makeListTimezones,
} from './enums.js';
import {
  makeGetCashierPrice,
  makeGetCashierProducts,
  makeListPublicTemplates,
  makeGetPublicTemplateBlueprint,
} from './catalog.js';

export {
  makeListScenarios,
  makeGetScenario,
  makeDeleteScenario,
  makeUpdateScenario,
  makeGetScenarioBlueprint,
  makeGetScenarioInterface,
  makeUpdateScenarioInterface,
  makeGetScenarioLogs,
  makeGetScenarioTriggers,
  makeListIncompleteExecutions,
  makeCreateHook,
  makeGetHook,
  makeGetHookIncomingActivity,
  makeGetHookLog,
  makeListHookLogs,
  makeCreateOrganization,
  makeGetOrganization,
  makeListOrganizations,
  makeGetOperations,
  makeGetTeam,
  makeListTeams,
  makeGetConnection,
  makeListConnections,
  makeGetCurrentUser,
  makeGetCurrentAuthorization,
  makeCreatePasswordResetDemand,
  makePing,
  makeSetSdkConnectionApi,
  makeGetAppsReviewStatuses,
  makeGetImtRegions,
  makeGetImtZones,
  makeGetLlmModels,
  makeGetModuleTypes,
  makeGetOrganizationFeatures,
  makeGetUserApiTokenScopes,
  makeGetUserEmailNotifications,
  makeGetUserFeatures,
  makeGetVariableTypes,
  makeListCountries,
  makeListLanguages,
  makeListLlmBuiltinTiers,
  makeListLocales,
  makeListTimezones,
  makeGetCashierPrice,
  makeGetCashierProducts,
  makeListPublicTemplates,
  makeGetPublicTemplateBlueprint,
};

const AUTH = 'makeCredentials' as const;

export const makeTools = [
  {
    name: 'makeListScenarios',
    description: 'List Make scenarios for a team with filters.',
    tool: makeListScenarios,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['automations', 'workflows', 'routines'],
  },
  {
    name: 'makeGetScenario',
    description: 'Retrieve one Make scenario by ID.',
    tool: makeGetScenario,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['automation', 'workflow', 'fetch'],
  },
  {
    name: 'makeDeleteScenario',
    description: 'Move a Make scenario to trash (recoverable 30 days).',
    tool: makeDeleteScenario,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['remove', 'trash', 'automation'],
  },
  {
    name: 'makeUpdateScenario',
    description: 'Update a Make scenario: name, blueprint, scheduling, folder.',
    tool: makeUpdateScenario,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['edit', 'rename', 'reschedule'],
  },
  {
    name: 'makeGetScenarioBlueprint',
    description: 'Retrieve current, draft, or historical scenario blueprint.',
    tool: makeGetScenarioBlueprint,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['definition', 'modules', 'draft'],
  },
  {
    name: 'makeGetScenarioInterface',
    description: "Retrieve a scenario's input/output interface.",
    tool: makeGetScenarioInterface,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['inputs', 'outputs', 'parameters'],
  },
  {
    name: 'makeUpdateScenarioInterface',
    description: 'Update a scenario inputs specification.',
    tool: makeUpdateScenarioInterface,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['inputs', 'parameters', 'on-demand'],
  },
  {
    name: 'makeGetScenarioLogs',
    description: 'List scenario or module logs, or one execution log.',
    tool: makeGetScenarioLogs,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['executions', 'runs', 'history'],
  },
  {
    name: 'makeGetScenarioTriggers',
    description: 'Retrieve safe trigger details of a scenario.',
    tool: makeGetScenarioTriggers,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['trigger', 'webhook', 'schedule'],
  },
  {
    name: 'makeListIncompleteExecutions',
    description: 'List incomplete (DLQ) executions of a scenario.',
    tool: makeListIncompleteExecutions,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['failures', 'errors', 'retry', 'dlq'],
  },
  {
    name: 'makeCreateHook',
    description: 'Create a Make webhook or mailhook for a team.',
    tool: makeCreateHook,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['webhook', 'mailhook', 'endpoint'],
  },
  {
    name: 'makeGetHook',
    description: 'Retrieve a Make hook by ID.',
    tool: makeGetHook,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['webhook', 'fetch'],
  },
  {
    name: 'makeGetHookIncomingActivity',
    description: 'Get webhook queue stats or one incoming event metadata.',
    tool: makeGetHookIncomingActivity,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['webhook', 'queue', 'payload'],
  },
  {
    name: 'makeGetHookLog',
    description: 'Retrieve diagnostics for one webhook execution log.',
    tool: makeGetHookLog,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['webhook', 'execution', 'diagnostics'],
  },
  {
    name: 'makeListHookLogs',
    description: 'List execution logs of a webhook with time filters.',
    tool: makeListHookLogs,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['webhook', 'runs', 'history'],
  },
  {
    name: 'makeCreateOrganization',
    description: 'Create a new Make organization.',
    tool: makeCreateOrganization,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['workspace', 'account', 'setup'],
  },
  {
    name: 'makeGetOrganization',
    description: 'Retrieve one Make organization by ID.',
    tool: makeGetOrganization,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['workspace', 'fetch'],
  },
  {
    name: 'makeListOrganizations',
    description: 'List Make organizations with pagination.',
    tool: makeListOrganizations,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['workspaces', 'accounts'],
  },
  {
    name: 'makeGetOperations',
    description: 'Retrieve 30-day operations usage for an organization.',
    tool: makeGetOperations,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['usage', 'billing', 'credits'],
  },
  {
    name: 'makeGetTeam',
    description: 'Retrieve detailed info about a Make team.',
    tool: makeGetTeam,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['members', 'usage', 'license'],
  },
  {
    name: 'makeListTeams',
    description: 'List Make teams in an organization.',
    tool: makeListTeams,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['groups', 'members'],
  },
  {
    name: 'makeGetConnection',
    description: 'Retrieve one Make connection by ID.',
    tool: makeGetConnection,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['integration', 'credential', 'fetch'],
  },
  {
    name: 'makeListConnections',
    description: 'List connections belonging to a team.',
    tool: makeListConnections,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['integrations', 'credentials'],
  },
  {
    name: 'makeGetCurrentUser',
    description: 'Retrieve the current authenticated Make user.',
    tool: makeGetCurrentUser,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['profile', 'me', 'account'],
  },
  {
    name: 'makeGetCurrentAuthorization',
    description: 'Retrieve current token scopes and auth method.',
    tool: makeGetCurrentAuthorization,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['permissions', 'scopes', 'token'],
  },
  {
    name: 'makeCreatePasswordResetDemand',
    description: 'Trigger a password reset email for a user.',
    tool: makeCreatePasswordResetDemand,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['password', 'reset', 'email'],
  },
  {
    name: 'makePing',
    description: 'Verify Make API connectivity and token validity.',
    tool: makePing,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['health', 'connectivity', 'status'],
  },
  {
    name: 'makeSetSdkConnectionApi',
    description: 'Set the API section of a custom-app SDK connection.',
    tool: makeSetSdkConnectionApi,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['custom-app', 'oauth', 'authorization'],
  },
  {
    name: 'makeGetAppsReviewStatuses',
    description: 'Retrieve available app review statuses.',
    tool: makeGetAppsReviewStatuses,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['approval', 'review'],
  },
  {
    name: 'makeGetImtRegions',
    description: 'Retrieve Make regions and region IDs.',
    tool: makeGetImtRegions,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['datacenters', 'zones'],
  },
  {
    name: 'makeGetImtZones',
    description: 'Retrieve available Make IMT zones.',
    tool: makeGetImtZones,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['instances', 'zones'],
  },
  {
    name: 'makeGetLlmModels',
    description: 'Retrieve available large language models.',
    tool: makeGetLlmModels,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['ai', 'models', 'providers'],
  },
  {
    name: 'makeGetModuleTypes',
    description: 'Retrieve available module types.',
    tool: makeGetModuleTypes,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['trigger', 'action', 'transformer'],
  },
  {
    name: 'makeGetOrganizationFeatures',
    description: 'Retrieve available organization features.',
    tool: makeGetOrganizationFeatures,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['capabilities', 'flags'],
  },
  {
    name: 'makeGetUserApiTokenScopes',
    description: 'Retrieve all available API token scopes.',
    tool: makeGetUserApiTokenScopes,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['permissions', 'scopes'],
  },
  {
    name: 'makeGetUserEmailNotifications',
    description: 'Retrieve available user email notification types.',
    tool: makeGetUserEmailNotifications,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['alerts', 'preferences'],
  },
  {
    name: 'makeGetUserFeatures',
    description: 'Retrieve all existing user features.',
    tool: makeGetUserFeatures,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['capabilities', 'flags'],
  },
  {
    name: 'makeGetVariableTypes',
    description: 'Retrieve available variable types.',
    tool: makeGetVariableTypes,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['datatypes', 'variables'],
  },
  {
    name: 'makeListCountries',
    description: 'Retrieve all supported countries with ISO codes.',
    tool: makeListCountries,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['nations', 'iso'],
  },
  {
    name: 'makeListLanguages',
    description: 'Retrieve all supported languages.',
    tool: makeListLanguages,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['locales', 'i18n'],
  },
  {
    name: 'makeListLlmBuiltinTiers',
    description: 'Retrieve built-in LLM tiers.',
    tool: makeListLlmBuiltinTiers,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['ai', 'plans', 'tiers'],
  },
  {
    name: 'makeListLocales',
    description: 'Retrieve all supported locales.',
    tool: makeListLocales,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['regions', 'languages'],
  },
  {
    name: 'makeListTimezones',
    description: 'Retrieve all supported timezones.',
    tool: makeListTimezones,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['zones', 'time', 'offsets'],
  },
  {
    name: 'makeGetCashierPrice',
    description: 'Retrieve a cashier price by ID.',
    tool: makeGetCashierPrice,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['pricing', 'billing', 'plan'],
  },
  {
    name: 'makeGetCashierProducts',
    description: 'Retrieve available cashier products (plans, add-ons).',
    tool: makeGetCashierProducts,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['pricing', 'subscriptions', 'plans'],
  },
  {
    name: 'makeListPublicTemplates',
    description: 'List public approved Make templates.',
    tool: makeListPublicTemplates,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['blueprints', 'examples', 'gallery'],
  },
  {
    name: 'makeGetPublicTemplateBlueprint',
    description: 'Retrieve a public template blueprint.',
    tool: makeGetPublicTemplateBlueprint,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['blueprint', 'template', 'clone'],
  },
];
