// @ts-nocheck
import {
  asanaAddFollowersToTask,
  asanaAddProjectToTask,
  asanaAddTagToTask,
  asanaAddTaskDependencies,
  asanaCreateSubtask,
  asanaCreateTask,
  asanaDeleteTask,
  asanaDuplicateTask,
  asanaGetProjectsForTask,
  asanaGetTagsForTask,
  asanaGetTask,
  asanaGetTaskSubtasks,
  asanaGetTaskTemplates,
  asanaListTasks,
  asanaRemoveFollowersFromTask,
  asanaRemoveProjectFromTask,
  asanaRemoveTagFromTask,
  asanaSearchTasks,
  asanaSetTaskParent,
  asanaUpdateTask,
} from './tasks.js';
import {
  asanaAddFollowersToProject,
  asanaAddMembersToProject,
  asanaCreateProject,
  asanaCreateProjectForTeam,
  asanaCreateProjectForWorkspace,
  asanaCreateSectionInProject,
  asanaDeleteProject,
  asanaDuplicateProject,
  asanaGetCustomTypes,
  asanaGetProject,
  asanaGetProjectMembership,
  asanaGetProjectMemberships,
  asanaGetProjectsForTeam,
  asanaGetProjectTemplates,
  asanaGetProjectTemplatesForTeam,
  asanaGetSectionsInProject,
  asanaGetTaskCountsForProject,
  asanaGetTasksFromProject,
  asanaGetWorkspaceProjects,
  asanaInsertSectionForProject,
  asanaInstantiateProjectTemplate,
  asanaListProjects,
  asanaRemoveFollowersForProject,
  asanaRemoveMembersForProject,
  asanaUpdateProject,
} from './projects.js';
import {
  asanaAddUserToTeam,
  asanaAddUserToWorkspace,
  asanaGetAUserTaskList,
  asanaGetCurrentUser,
  asanaGetFavoritesForUser,
  asanaGetTasksForUserTaskList,
  asanaGetTeamMembershipsForUser,
  asanaGetTeamsForUser,
  asanaGetUser,
  asanaGetUserForWorkspace,
  asanaGetUsersForTeam,
  asanaGetUsersForWorkspace,
  asanaGetUserTaskList,
  asanaGetWorkspaceMembershipsForUser,
  asanaListUsers,
  asanaRemoveUserForTeam,
  asanaRemoveUserForWorkspace,
  asanaUpdateUser,
  asanaUpdateUserForWorkspace,
} from './users.js';
import {
  asanaCreateMembership,
  asanaCreateTeam,
  asanaDeleteMembership,
  asanaGetMembership,
  asanaGetMemberships,
  asanaGetTeam,
  asanaGetTeamMembership,
  asanaGetTeamMemberships,
  asanaGetTeamMembershipsForTeam,
  asanaGetTeamsInWorkspace,
  asanaGetWorkspaceMembership,
  asanaGetWorkspaceMemberships,
  asanaUpdateTeam,
} from './teams.js';
import {
  asanaCreateTag,
  asanaCreateTagInWorkspace,
  asanaDeleteTag,
  asanaGetEvents,
  asanaGetTag,
  asanaGetTags,
  asanaGetTagsForWorkspace,
  asanaGetTasksForTag,
  asanaGetTypeaheadObjects,
  asanaGetWorkspace,
  asanaListWorkspaces,
  asanaUpdateTag,
} from './workspaces.js';
import {
  asanaCreateTaskComment,
  asanaDeleteStory,
  asanaGetReactions,
  asanaGetStoriesForTask,
  asanaGetStory,
  asanaUpdateStory,
} from './stories.js';
import {
  asanaCreateAttachmentForObject,
  asanaCreateAttachmentForTask,
  asanaDeleteAttachment,
  asanaGetAttachment,
  asanaGetTaskAttachments,
} from './attachments.js';
import {
  asanaCreateCustomField,
  asanaCreateEnumOptionForCustomField,
  asanaDeleteCustomField,
  asanaGetCustomField,
  asanaGetCustomFieldsForWorkspace,
  asanaInsertEnumOptionForCustomField,
  asanaUpdateCustomField,
  asanaUpdateEnumOption,
} from './customfields.js';
import {
  asanaAddTaskToSection,
  asanaDeleteSection,
  asanaGetSection,
  asanaGetTasksFromSection,
  asanaUpdateSection,
} from './sections.js';
import {
  asanaAddItemToPortfolio,
  asanaGetPortfolio,
  asanaGetPortfolioItems,
  asanaGetPortfolioMemberships,
  asanaGetPortfolios,
  asanaRemoveItemFromPortfolio,
} from './portfolios.js';
import {
  asanaAddSupportingRelationship,
  asanaGetGoal,
  asanaGetGoalRelationships,
  asanaGetGoals,
} from './goals.js';
import {
  asanaCreateProjectBrief,
  asanaCreateProjectStatusUpdate,
  asanaCreateStatusForObject,
  asanaDeleteProjectBrief,
  asanaDeleteProjectStatus,
  asanaDeleteStatusUpdate,
  asanaGetProjectBrief,
  asanaGetProjectStatus,
  asanaGetProjectStatusUpdates,
  asanaGetStatusUpdate,
  asanaGetStatusUpdates,
  asanaUpdateProjectBrief,
} from './status.js';
import {
  asanaApproveAccessRequest,
  asanaCreateAccessRequest,
  asanaCreateAllocation,
  asanaDeleteAllocation,
  asanaGetAccessRequests,
  asanaGetAllocation,
  asanaGetAllocations,
  asanaGetAuditLogEvents,
  asanaGetJob,
  asanaGetTimePeriod,
  asanaGetTimePeriods,
  asanaGetTimeTrackingEntries,
  asanaGetTimeTrackingEntriesForTask,
  asanaGetWebhooks,
  asanaRejectAccessRequest,
  asanaSubmitParallelRequests,
  asanaUpdateAllocation,
  asanaUpdateWebhook,
} from './advanced.js';

export {
  asanaAddFollowersToTask,
  asanaAddProjectToTask,
  asanaAddTagToTask,
  asanaAddTaskDependencies,
  asanaCreateSubtask,
  asanaCreateTask,
  asanaDeleteTask,
  asanaDuplicateTask,
  asanaGetProjectsForTask,
  asanaGetTagsForTask,
  asanaGetTask,
  asanaGetTaskSubtasks,
  asanaGetTaskTemplates,
  asanaListTasks,
  asanaRemoveFollowersFromTask,
  asanaRemoveProjectFromTask,
  asanaRemoveTagFromTask,
  asanaSearchTasks,
  asanaSetTaskParent,
  asanaUpdateTask,
  asanaAddFollowersToProject,
  asanaAddMembersToProject,
  asanaCreateProject,
  asanaCreateProjectForTeam,
  asanaCreateProjectForWorkspace,
  asanaCreateSectionInProject,
  asanaDeleteProject,
  asanaDuplicateProject,
  asanaGetCustomTypes,
  asanaGetProject,
  asanaGetProjectMembership,
  asanaGetProjectMemberships,
  asanaGetProjectsForTeam,
  asanaGetProjectTemplates,
  asanaGetProjectTemplatesForTeam,
  asanaGetSectionsInProject,
  asanaGetTaskCountsForProject,
  asanaGetTasksFromProject,
  asanaGetWorkspaceProjects,
  asanaInsertSectionForProject,
  asanaInstantiateProjectTemplate,
  asanaListProjects,
  asanaRemoveFollowersForProject,
  asanaRemoveMembersForProject,
  asanaUpdateProject,
  asanaAddUserToTeam,
  asanaAddUserToWorkspace,
  asanaGetAUserTaskList,
  asanaGetCurrentUser,
  asanaGetFavoritesForUser,
  asanaGetTasksForUserTaskList,
  asanaGetTeamMembershipsForUser,
  asanaGetTeamsForUser,
  asanaGetUser,
  asanaGetUserForWorkspace,
  asanaGetUsersForTeam,
  asanaGetUsersForWorkspace,
  asanaGetUserTaskList,
  asanaGetWorkspaceMembershipsForUser,
  asanaListUsers,
  asanaRemoveUserForTeam,
  asanaRemoveUserForWorkspace,
  asanaUpdateUser,
  asanaUpdateUserForWorkspace,
  asanaCreateMembership,
  asanaCreateTeam,
  asanaDeleteMembership,
  asanaGetMembership,
  asanaGetMemberships,
  asanaGetTeam,
  asanaGetTeamMembership,
  asanaGetTeamMemberships,
  asanaGetTeamMembershipsForTeam,
  asanaGetTeamsInWorkspace,
  asanaGetWorkspaceMembership,
  asanaGetWorkspaceMemberships,
  asanaUpdateTeam,
  asanaCreateTag,
  asanaCreateTagInWorkspace,
  asanaDeleteTag,
  asanaGetEvents,
  asanaGetTag,
  asanaGetTags,
  asanaGetTagsForWorkspace,
  asanaGetTasksForTag,
  asanaGetTypeaheadObjects,
  asanaGetWorkspace,
  asanaListWorkspaces,
  asanaUpdateTag,
  asanaCreateTaskComment,
  asanaDeleteStory,
  asanaGetReactions,
  asanaGetStoriesForTask,
  asanaGetStory,
  asanaUpdateStory,
  asanaCreateAttachmentForObject,
  asanaCreateAttachmentForTask,
  asanaDeleteAttachment,
  asanaGetAttachment,
  asanaGetTaskAttachments,
  asanaCreateCustomField,
  asanaCreateEnumOptionForCustomField,
  asanaDeleteCustomField,
  asanaGetCustomField,
  asanaGetCustomFieldsForWorkspace,
  asanaInsertEnumOptionForCustomField,
  asanaUpdateCustomField,
  asanaUpdateEnumOption,
  asanaAddTaskToSection,
  asanaDeleteSection,
  asanaGetSection,
  asanaGetTasksFromSection,
  asanaUpdateSection,
  asanaAddItemToPortfolio,
  asanaGetPortfolio,
  asanaGetPortfolioItems,
  asanaGetPortfolioMemberships,
  asanaGetPortfolios,
  asanaRemoveItemFromPortfolio,
  asanaAddSupportingRelationship,
  asanaGetGoal,
  asanaGetGoalRelationships,
  asanaGetGoals,
  asanaCreateProjectBrief,
  asanaCreateProjectStatusUpdate,
  asanaCreateStatusForObject,
  asanaDeleteProjectBrief,
  asanaDeleteProjectStatus,
  asanaDeleteStatusUpdate,
  asanaGetProjectBrief,
  asanaGetProjectStatus,
  asanaGetProjectStatusUpdates,
  asanaGetStatusUpdate,
  asanaGetStatusUpdates,
  asanaUpdateProjectBrief,
  asanaApproveAccessRequest,
  asanaCreateAccessRequest,
  asanaCreateAllocation,
  asanaDeleteAllocation,
  asanaGetAccessRequests,
  asanaGetAllocation,
  asanaGetAllocations,
  asanaGetAuditLogEvents,
  asanaGetJob,
  asanaGetTimePeriod,
  asanaGetTimePeriods,
  asanaGetTimeTrackingEntries,
  asanaGetTimeTrackingEntriesForTask,
  asanaGetWebhooks,
  asanaRejectAccessRequest,
  asanaSubmitParallelRequests,
  asanaUpdateAllocation,
  asanaUpdateWebhook,
};

const auth = 'asanaToken' as const;

type Scope = 'read' | 'write' | 'delete';
function entry(
  name: string,
  description: string,
  toolRef: any,
  scope: Scope,
  keywords: string[],
): {
  name: string;
  description: string;
  tool: any;
  requiredAuth: typeof auth;
  scope: Scope;
  keywords: string[];
} {
  return { name, description, tool: toolRef, requiredAuth: auth, scope, keywords };
}

export const asanaTools = [
  entry(
    'asanaGetTask',
    'Get a single task by GID with its name, assignee, dates, projects, and notes.',
    asanaGetTask,
    'read',
    ['todo', 'item', 'details'],
  ),
  entry(
    'asanaListTasks',
    'List tasks filtered by project, section, tag, assignee, or workspace.',
    asanaListTasks,
    'read',
    ['todos', 'browse', 'backlog'],
  ),
  entry(
    'asanaCreateTask',
    'Create a task in a workspace (and optionally projects/sections).',
    asanaCreateTask,
    'write',
    ['new todo', 'add item'],
  ),
  entry(
    'asanaUpdateTask',
    'Update a task name, notes, assignee, dates, completion, or custom fields.',
    asanaUpdateTask,
    'write',
    ['edit todo', 'complete', 'reassign'],
  ),
  entry(
    'asanaDeleteTask',
    'Permanently delete a task and remove it from all projects.',
    asanaDeleteTask,
    'delete',
    ['remove todo', 'trash'],
  ),
  entry(
    'asanaDuplicateTask',
    'Duplicate a task, optionally including attachments, subtasks, and followers.',
    asanaDuplicateTask,
    'write',
    ['clone', 'copy todo'],
  ),
  entry(
    'asanaAddProjectToTask',
    'Add a task to a project, optionally positioning it within a section.',
    asanaAddProjectToTask,
    'write',
    ['assign project', 'file todo'],
  ),
  entry(
    'asanaRemoveProjectFromTask',
    'Remove a task from a project (the task itself is kept).',
    asanaRemoveProjectFromTask,
    'write',
    ['unfile', 'detach project'],
  ),
  entry(
    'asanaAddFollowersToTask',
    'Add followers to a task so they are notified of updates.',
    asanaAddFollowersToTask,
    'write',
    ['watch', 'subscribe', 'notify'],
  ),
  entry(
    'asanaRemoveFollowersFromTask',
    'Remove followers from a task.',
    asanaRemoveFollowersFromTask,
    'write',
    ['unwatch', 'unsubscribe'],
  ),
  entry('asanaAddTagToTask', 'Attach an existing tag to a task.', asanaAddTagToTask, 'write', [
    'label',
    'categorize',
  ]),
  entry('asanaRemoveTagFromTask', 'Detach a tag from a task.', asanaRemoveTagFromTask, 'write', [
    'unlabel',
  ]),
  entry(
    'asanaAddTaskDependencies',
    'Mark other tasks as dependencies that must finish before this task.',
    asanaAddTaskDependencies,
    'write',
    ['blocked by', 'prerequisite', 'gantt'],
  ),
  entry(
    'asanaSetTaskParent',
    'Make a task a subtask of another task.',
    asanaSetTaskParent,
    'write',
    ['nest', 'indent', 'child task'],
  ),
  entry('asanaGetTaskSubtasks', 'List the subtasks of a task.', asanaGetTaskSubtasks, 'read', [
    'children',
    'nested',
  ]),
  entry(
    'asanaCreateSubtask',
    'Create a subtask under an existing task.',
    asanaCreateSubtask,
    'write',
    ['child', 'nested todo'],
  ),
  entry(
    'asanaGetProjectsForTask',
    'List the projects a task belongs to.',
    asanaGetProjectsForTask,
    'read',
    ['membership', 'filed under'],
  ),
  entry('asanaGetTagsForTask', 'List the tags attached to a task.', asanaGetTagsForTask, 'read', [
    'labels',
  ]),
  entry(
    'asanaSearchTasks',
    'Search tasks in a workspace by text, assignees, projects, or subtypes.',
    asanaSearchTasks,
    'read',
    ['find', 'query', 'lookup'],
  ),
  entry(
    'asanaGetTaskTemplates',
    'List task templates available in a workspace or project.',
    asanaGetTaskTemplates,
    'read',
    ['blueprint', 'boilerplate'],
  ),
  entry(
    'asanaGetProject',
    'Get a project by GID with its settings, members, dates, and status.',
    asanaGetProject,
    'read',
    ['details', 'board', 'list view'],
  ),
  entry(
    'asanaListProjects',
    'List projects in a workspace or team, optionally including archived ones.',
    asanaListProjects,
    'read',
    ['boards', 'all projects'],
  ),
  entry(
    'asanaCreateProject',
    'Create a project from scratch with a full data payload.',
    asanaCreateProject,
    'write',
    ['new board', 'start project'],
  ),
  entry(
    'asanaCreateProjectForTeam',
    'Create a project owned by a specific team.',
    asanaCreateProjectForTeam,
    'write',
    ['team board'],
  ),
  entry(
    'asanaCreateProjectForWorkspace',
    'Create a project directly in a workspace (no team owner).',
    asanaCreateProjectForWorkspace,
    'write',
    ['workspace board'],
  ),
  entry(
    'asanaUpdateProject',
    'Update project name, notes, color, dates, owner, privacy, or archive state.',
    asanaUpdateProject,
    'write',
    ['edit board', 'rename', 'archive'],
  ),
  entry(
    'asanaDeleteProject',
    'Permanently delete a project and its unassigned tasks.',
    asanaDeleteProject,
    'delete',
    ['remove board'],
  ),
  entry(
    'asanaDuplicateProject',
    'Duplicate a project, optionally shifting dates and including tasks.',
    asanaDuplicateProject,
    'write',
    ['clone board', 'copy project'],
  ),
  entry('asanaGetTasksFromProject', 'List tasks in a project.', asanaGetTasksFromProject, 'read', [
    'board cards',
    'project todos',
  ]),
  entry(
    'asanaGetTaskCountsForProject',
    'Get incomplete/completed/milestone task counts for a project.',
    asanaGetTaskCountsForProject,
    'read',
    ['progress', 'stats', 'burndown'],
  ),
  entry(
    'asanaGetSectionsInProject',
    'List the sections (columns) of a project.',
    asanaGetSectionsInProject,
    'read',
    ['columns', 'lanes', 'stages'],
  ),
  entry(
    'asanaCreateSectionInProject',
    'Create a section (list/board column) in a project.',
    asanaCreateSectionInProject,
    'write',
    ['new column', 'new lane'],
  ),
  entry(
    'asanaInsertSectionForProject',
    'Move an existing section to a new position within its project.',
    asanaInsertSectionForProject,
    'write',
    ['reorder columns'],
  ),
  entry(
    'asanaAddMembersToProject',
    'Add members to a project.',
    asanaAddMembersToProject,
    'write',
    ['invite', 'share board'],
  ),
  entry(
    'asanaRemoveMembersForProject',
    'Remove members from a project.',
    asanaRemoveMembersForProject,
    'write',
    ['unshare', 'kick'],
  ),
  entry(
    'asanaAddFollowersToProject',
    'Add followers to a project so they are notified when tasks are added.',
    asanaAddFollowersToProject,
    'write',
    ['watch board'],
  ),
  entry(
    'asanaRemoveFollowersForProject',
    'Remove followers from a project.',
    asanaRemoveFollowersForProject,
    'write',
    ['unwatch board'],
  ),
  entry(
    'asanaGetProjectMemberships',
    'List project memberships (who has access and at what level).',
    asanaGetProjectMemberships,
    'read',
    ['permissions', 'access list'],
  ),
  entry(
    'asanaGetProjectMembership',
    'Get a single project membership by GID.',
    asanaGetProjectMembership,
    'read',
    ['permission details'],
  ),
  entry(
    'asanaGetProjectsForTeam',
    'List projects owned by a team.',
    asanaGetProjectsForTeam,
    'read',
    ['team boards'],
  ),
  entry(
    'asanaGetWorkspaceProjects',
    'List all projects in a workspace.',
    asanaGetWorkspaceProjects,
    'read',
    ['workspace boards'],
  ),
  entry(
    'asanaGetProjectTemplates',
    'List project templates available in a workspace or team.',
    asanaGetProjectTemplates,
    'read',
    ['starter', 'blueprints'],
  ),
  entry(
    'asanaGetProjectTemplatesForTeam',
    'List project templates owned by a team.',
    asanaGetProjectTemplatesForTeam,
    'read',
    ['team starters'],
  ),
  entry(
    'asanaInstantiateProjectTemplate',
    'Create a project from a project template with dates and roles.',
    asanaInstantiateProjectTemplate,
    'write',
    ['use template', 'spin up'],
  ),
  entry(
    'asanaGetCustomTypes',
    'List custom task types available on a project or workspace.',
    asanaGetCustomTypes,
    'read',
    ['milestone type', 'approval type'],
  ),
  entry(
    'asanaGetCurrentUser',
    'Get the currently authenticated user.',
    asanaGetCurrentUser,
    'read',
    ['me', 'whoami', 'profile'],
  ),
  entry(
    'asanaGetUser',
    'Get a user by GID with name, email, photo, and workspaces.',
    asanaGetUser,
    'read',
    ['teammate', 'profile details'],
  ),
  entry('asanaListUsers', 'List users in a workspace or team.', asanaListUsers, 'read', [
    'directory',
    'people',
    'roster',
  ]),
  entry('asanaGetUsersForTeam', 'List members of a team.', asanaGetUsersForTeam, 'read', [
    'team roster',
  ]),
  entry(
    'asanaGetUsersForWorkspace',
    'List users in a workspace.',
    asanaGetUsersForWorkspace,
    'read',
    ['workspace directory'],
  ),
  entry(
    'asanaGetUserForWorkspace',
    'Get a workspace-scoped view of a user.',
    asanaGetUserForWorkspace,
    'read',
    ['member role'],
  ),
  entry(
    'asanaUpdateUser',
    'Update user-level custom field values for a user.',
    asanaUpdateUser,
    'write',
    ['edit profile fields'],
  ),
  entry(
    'asanaUpdateUserForWorkspace',
    'Update workspace-scoped attributes for a user.',
    asanaUpdateUserForWorkspace,
    'write',
    ['edit member fields'],
  ),
  entry(
    'asanaAddUserToTeam',
    'Add a user to a team by GID, email, or "me".',
    asanaAddUserToTeam,
    'write',
    ['join team', 'invite teammate'],
  ),
  entry('asanaRemoveUserForTeam', 'Remove a user from a team.', asanaRemoveUserForTeam, 'write', [
    'leave team',
  ]),
  entry(
    'asanaAddUserToWorkspace',
    'Invite a user to a workspace by GID or email.',
    asanaAddUserToWorkspace,
    'write',
    ['invite', 'onboard'],
  ),
  entry(
    'asanaRemoveUserForWorkspace',
    'Remove (deprovision) a user from a workspace.',
    asanaRemoveUserForWorkspace,
    'write',
    ['offboard', 'deprovision'],
  ),
  entry(
    'asanaGetTeamsForUser',
    'List teams a user belongs to within an organization.',
    asanaGetTeamsForUser,
    'read',
    ['my teams'],
  ),
  entry(
    'asanaGetUserTaskList',
    'Get a user task list (My Tasks) by its GID.',
    asanaGetUserTaskList,
    'read',
    ['my tasks view'],
  ),
  entry(
    'asanaGetAUserTaskList',
    'Get the user task list for a user in a workspace.',
    asanaGetAUserTaskList,
    'read',
    ['my tasks', 'assignee view'],
  ),
  entry(
    'asanaGetTasksForUserTaskList',
    'List tasks assigned to a user via their task list.',
    asanaGetTasksForUserTaskList,
    'read',
    ['assigned to me', 'my todos'],
  ),
  entry(
    'asanaGetFavoritesForUser',
    'List starred/favorite projects, portfolios, and dashboards.',
    asanaGetFavoritesForUser,
    'read',
    ['starred', 'pinned', 'bookmarks'],
  ),
  entry(
    'asanaGetTeamMembershipsForUser',
    'List team memberships for a user in a workspace.',
    asanaGetTeamMembershipsForUser,
    'read',
    ['memberships'],
  ),
  entry(
    'asanaGetWorkspaceMembershipsForUser',
    'List workspace memberships for a user.',
    asanaGetWorkspaceMembershipsForUser,
    'read',
    ['org roles'],
  ),
  entry(
    'asanaGetTeam',
    'Get a team by GID with its organization and member count.',
    asanaGetTeam,
    'read',
    ['group details'],
  ),
  entry('asanaCreateTeam', 'Create a team in an organization.', asanaCreateTeam, 'write', [
    'new group',
  ]),
  entry('asanaUpdateTeam', 'Update a team name or description.', asanaUpdateTeam, 'write', [
    'rename group',
  ]),
  entry(
    'asanaGetTeamsInWorkspace',
    'List teams in a workspace/organization.',
    asanaGetTeamsInWorkspace,
    'read',
    ['all groups'],
  ),
  entry(
    'asanaGetTeamMemberships',
    'List team memberships filtered by team, user, or workspace.',
    asanaGetTeamMemberships,
    'read',
    ['team roles'],
  ),
  entry('asanaGetTeamMembership', 'Get a team membership by GID.', asanaGetTeamMembership, 'read', [
    'role details',
  ]),
  entry(
    'asanaGetTeamMembershipsForTeam',
    'List memberships of a team.',
    asanaGetTeamMembershipsForTeam,
    'read',
    ['team members roles'],
  ),
  entry(
    'asanaCreateMembership',
    'Grant a member access to a goal, portfolio, or project.',
    asanaCreateMembership,
    'write',
    ['grant access', 'share'],
  ),
  entry(
    'asanaGetMemberships',
    'List memberships filtered by member and/or parent resource.',
    asanaGetMemberships,
    'read',
    ['access grants'],
  ),
  entry('asanaGetMembership', 'Get a membership by GID.', asanaGetMembership, 'read', [
    'grant details',
  ]),
  entry(
    'asanaDeleteMembership',
    'Revoke a membership, removing access to the parent resource.',
    asanaDeleteMembership,
    'delete',
    ['revoke access'],
  ),
  entry(
    'asanaGetWorkspaceMembership',
    'Get a workspace membership by GID.',
    asanaGetWorkspaceMembership,
    'read',
    ['org membership'],
  ),
  entry(
    'asanaGetWorkspaceMemberships',
    'List memberships of a workspace.',
    asanaGetWorkspaceMemberships,
    'read',
    ['org members'],
  ),
  entry(
    'asanaListWorkspaces',
    'List workspaces and organizations visible to the user.',
    asanaListWorkspaces,
    'read',
    ['orgs', 'accounts'],
  ),
  entry('asanaGetWorkspace', 'Get a workspace by GID.', asanaGetWorkspace, 'read', ['org details']),
  entry('asanaGetTags', 'List tags in a workspace.', asanaGetTags, 'read', ['labels list']),
  entry(
    'asanaGetTagsForWorkspace',
    'List tags defined in a workspace.',
    asanaGetTagsForWorkspace,
    'read',
    ['workspace labels'],
  ),
  entry('asanaGetTag', 'Get a tag by GID with its color and workspace.', asanaGetTag, 'read', [
    'label details',
  ]),
  entry('asanaCreateTag', 'Create a tag with a full data payload.', asanaCreateTag, 'write', [
    'new label',
  ]),
  entry(
    'asanaCreateTagInWorkspace',
    'Create a tag in a specific workspace.',
    asanaCreateTagInWorkspace,
    'write',
    ['workspace label'],
  ),
  entry('asanaUpdateTag', 'Update a tag name, color, or notes.', asanaUpdateTag, 'write', [
    'rename label',
    'recolor',
  ]),
  entry('asanaDeleteTag', 'Permanently delete a tag.', asanaDeleteTag, 'delete', ['remove label']),
  entry('asanaGetTasksForTag', 'List tasks carrying a tag.', asanaGetTasksForTag, 'read', [
    'labeled tasks',
  ]),
  entry(
    'asanaGetTypeaheadObjects',
    'Typeahead search across tasks, users, projects, and more.',
    asanaGetTypeaheadObjects,
    'read',
    ['autocomplete', 'quick find'],
  ),
  entry(
    'asanaGetEvents',
    'Poll events (changes) on a task, project, or other resource.',
    asanaGetEvents,
    'read',
    ['changelog', 'activity feed', 'sync'],
  ),
  entry(
    'asanaGetStoriesForTask',
    'List comments and activity stories on a task.',
    asanaGetStoriesForTask,
    'read',
    ['comments', 'discussion', 'history'],
  ),
  entry(
    'asanaGetStory',
    'Get a story (comment or activity record) by GID.',
    asanaGetStory,
    'read',
    ['comment details'],
  ),
  entry('asanaCreateTaskComment', 'Post a comment on a task.', asanaCreateTaskComment, 'write', [
    'reply',
    'discuss',
    'annotate',
  ]),
  entry('asanaUpdateStory', 'Edit a comment story text.', asanaUpdateStory, 'write', [
    'edit comment',
  ]),
  entry('asanaDeleteStory', 'Delete a story (comment) from a task.', asanaDeleteStory, 'delete', [
    'remove comment',
  ]),
  entry(
    'asanaGetReactions',
    'List emoji reactions on a task, story, or other object.',
    asanaGetReactions,
    'read',
    ['likes', 'emoji', 'votes'],
  ),
  entry(
    'asanaGetAttachment',
    'Get attachment metadata (name, URL, host, size) by GID.',
    asanaGetAttachment,
    'read',
    ['file info'],
  ),
  entry('asanaDeleteAttachment', 'Delete an attachment.', asanaDeleteAttachment, 'delete', [
    'remove file',
  ]),
  entry('asanaGetTaskAttachments', 'List attachments on a task.', asanaGetTaskAttachments, 'read', [
    'files',
    'documents',
  ]),
  entry(
    'asanaCreateAttachmentForTask',
    'Upload a file attachment to a task.',
    asanaCreateAttachmentForTask,
    'write',
    ['upload file', 'attach document'],
  ),
  entry(
    'asanaCreateAttachmentForObject',
    'Attach a URL link or upload a file to any object.',
    asanaCreateAttachmentForObject,
    'write',
    ['link file', 'attach url'],
  ),
  entry(
    'asanaGetCustomFieldsForWorkspace',
    'List custom fields defined in a workspace.',
    asanaGetCustomFieldsForWorkspace,
    'read',
    ['fields catalog'],
  ),
  entry(
    'asanaGetCustomField',
    'Get a custom field definition by GID.',
    asanaGetCustomField,
    'read',
    ['field details'],
  ),
  entry(
    'asanaCreateCustomField',
    'Create an organization-wide custom field.',
    asanaCreateCustomField,
    'write',
    ['new field', 'dropdown field'],
  ),
  entry(
    'asanaUpdateCustomField',
    'Update a custom field name, description, or display value.',
    asanaUpdateCustomField,
    'write',
    ['rename field'],
  ),
  entry(
    'asanaDeleteCustomField',
    'Delete a custom field everywhere it is used.',
    asanaDeleteCustomField,
    'delete',
    ['remove field'],
  ),
  entry(
    'asanaCreateEnumOptionForCustomField',
    'Append an enum option to an enum custom field.',
    asanaCreateEnumOptionForCustomField,
    'write',
    ['add dropdown value'],
  ),
  entry(
    'asanaInsertEnumOptionForCustomField',
    'Insert an enum option at a specific position.',
    asanaInsertEnumOptionForCustomField,
    'write',
    ['position option'],
  ),
  entry(
    'asanaUpdateEnumOption',
    'Update an enum option name, color, or enabled state.',
    asanaUpdateEnumOption,
    'write',
    ['rename option'],
  ),
  entry(
    'asanaGetSection',
    'Get a section by GID with its project and name.',
    asanaGetSection,
    'read',
    ['column details'],
  ),
  entry('asanaGetTasksFromSection', 'List tasks in a section.', asanaGetTasksFromSection, 'read', [
    'column cards',
  ]),
  entry('asanaAddTaskToSection', 'Move a task into a section.', asanaAddTaskToSection, 'write', [
    'move card',
    'kanban',
  ]),
  entry('asanaUpdateSection', 'Rename a section.', asanaUpdateSection, 'write', ['rename column']),
  entry(
    'asanaDeleteSection',
    'Delete a section (tasks are kept, unsectioned).',
    asanaDeleteSection,
    'delete',
    ['remove column'],
  ),
  entry(
    'asanaGetPortfolios',
    'List portfolios in a workspace owned by a user.',
    asanaGetPortfolios,
    'read',
    ['initiatives', 'programs'],
  ),
  entry('asanaGetPortfolio', 'Get a portfolio by GID.', asanaGetPortfolio, 'read', [
    'program details',
  ]),
  entry(
    'asanaGetPortfolioItems',
    'List projects and other items in a portfolio.',
    asanaGetPortfolioItems,
    'read',
    ['program contents'],
  ),
  entry(
    'asanaAddItemToPortfolio',
    'Add a project (or other item) to a portfolio.',
    asanaAddItemToPortfolio,
    'write',
    ['track project'],
  ),
  entry(
    'asanaRemoveItemFromPortfolio',
    'Remove an item from a portfolio.',
    asanaRemoveItemFromPortfolio,
    'write',
    ['untrack project'],
  ),
  entry(
    'asanaGetPortfolioMemberships',
    'List portfolio memberships.',
    asanaGetPortfolioMemberships,
    'read',
    ['program access'],
  ),
  entry(
    'asanaGetGoals',
    'List goals filtered by workspace, team, project, portfolio, or time period.',
    asanaGetGoals,
    'read',
    ['okrs', 'objectives', 'targets'],
  ),
  entry(
    'asanaGetGoal',
    'Get a goal by GID with progress, owner, and time period.',
    asanaGetGoal,
    'read',
    ['okr details'],
  ),
  entry(
    'asanaGetGoalRelationships',
    'List supporting/contributing relationships of a goal.',
    asanaGetGoalRelationships,
    'read',
    ['linked work', 'subgoals'],
  ),
  entry(
    'asanaAddSupportingRelationship',
    'Link a project, task, portfolio, or goal as supporting work under a goal.',
    asanaAddSupportingRelationship,
    'write',
    ['link okr', 'contribute'],
  ),
  entry(
    'asanaGetProjectStatus',
    'Get a project status update by GID.',
    asanaGetProjectStatus,
    'read',
    ['health check'],
  ),
  entry(
    'asanaGetProjectStatusUpdates',
    'List status updates posted on a project.',
    asanaGetProjectStatusUpdates,
    'read',
    ['health history', 'rag'],
  ),
  entry(
    'asanaCreateProjectStatusUpdate',
    'Post a status update (on track, at risk, off track) on a project.',
    asanaCreateProjectStatusUpdate,
    'write',
    ['rag update', 'health report'],
  ),
  entry(
    'asanaDeleteProjectStatus',
    'Delete a project status update.',
    asanaDeleteProjectStatus,
    'delete',
    ['remove status'],
  ),
  entry(
    'asanaGetStatusUpdate',
    'Get a status update on any object by GID.',
    asanaGetStatusUpdate,
    'read',
    ['update details'],
  ),
  entry(
    'asanaGetStatusUpdates',
    'List status updates on a project, portfolio, or goal.',
    asanaGetStatusUpdates,
    'read',
    ['updates feed'],
  ),
  entry(
    'asanaCreateStatusForObject',
    'Post a status update on a project, portfolio, or goal.',
    asanaCreateStatusForObject,
    'write',
    ['post update'],
  ),
  entry('asanaDeleteStatusUpdate', 'Delete a status update.', asanaDeleteStatusUpdate, 'delete', [
    'retract update',
  ]),
  entry(
    'asanaCreateProjectBrief',
    'Create the project brief (overview document) for a project.',
    asanaCreateProjectBrief,
    'write',
    ['charter', 'overview doc'],
  ),
  entry('asanaGetProjectBrief', 'Get a project brief by GID.', asanaGetProjectBrief, 'read', [
    'charter details',
  ]),
  entry(
    'asanaUpdateProjectBrief',
    'Update project brief content.',
    asanaUpdateProjectBrief,
    'write',
    ['edit charter'],
  ),
  entry('asanaDeleteProjectBrief', 'Delete a project brief.', asanaDeleteProjectBrief, 'delete', [
    'remove charter',
  ]),
  entry(
    'asanaGetWebhooks',
    'List webhooks in a workspace, optionally filtered by resource.',
    asanaGetWebhooks,
    'read',
    ['subscriptions', 'callbacks'],
  ),
  entry(
    'asanaUpdateWebhook',
    'Update webhook filters (which events trigger delivery).',
    asanaUpdateWebhook,
    'write',
    ['edit subscription'],
  ),
  entry(
    'asanaGetJob',
    'Poll an async job (e.g. from duplicating a project) for completion.',
    asanaGetJob,
    'read',
    ['background task', 'async status'],
  ),
  entry(
    'asanaSubmitParallelRequests',
    'Run up to 10 independent API calls in one batch request.',
    asanaSubmitParallelRequests,
    'write',
    ['bulk', 'batch', 'multiplex'],
  ),
  entry(
    'asanaGetAuditLogEvents',
    'Query the audit log for security and compliance events.',
    asanaGetAuditLogEvents,
    'read',
    ['compliance', 'security log'],
  ),
  entry(
    'asanaGetAllocations',
    'List capacity allocations filtered by workspace, assignee, or parent.',
    asanaGetAllocations,
    'read',
    ['staffing', 'resourcing', 'workload'],
  ),
  entry('asanaGetAllocation', 'Get a capacity allocation by GID.', asanaGetAllocation, 'read', [
    'staffing details',
  ]),
  entry(
    'asanaCreateAllocation',
    'Allocate capacity (effort over a date range) to a user on a project.',
    asanaCreateAllocation,
    'write',
    ['staff', 'assign capacity'],
  ),
  entry(
    'asanaUpdateAllocation',
    'Update a capacity allocation dates, effort, or notes.',
    asanaUpdateAllocation,
    'write',
    ['replan staffing'],
  ),
  entry('asanaDeleteAllocation', 'Delete a capacity allocation.', asanaDeleteAllocation, 'delete', [
    'unstaff',
  ]),
  entry(
    'asanaGetTimePeriods',
    'List time periods (quarters, halves, years) in a workspace.',
    asanaGetTimePeriods,
    'read',
    ['quarters', 'fiscal', 'cycles'],
  ),
  entry('asanaGetTimePeriod', 'Get a time period by GID.', asanaGetTimePeriod, 'read', [
    'quarter details',
  ]),
  entry(
    'asanaGetTimeTrackingEntries',
    'List time tracking entries filtered by task, user, or dates.',
    asanaGetTimeTrackingEntries,
    'read',
    ['timesheets', 'logged hours'],
  ),
  entry(
    'asanaGetTimeTrackingEntriesForTask',
    'List time entries logged on a task.',
    asanaGetTimeTrackingEntriesForTask,
    'read',
    ['task hours'],
  ),
  entry(
    'asanaGetAccessRequests',
    'List access requests to a project or portfolio.',
    asanaGetAccessRequests,
    'read',
    ['pending approvals', 'join requests'],
  ),
  entry(
    'asanaCreateAccessRequest',
    'Request access to a project or portfolio you cannot see.',
    asanaCreateAccessRequest,
    'write',
    ['ask access', 'request join'],
  ),
  entry(
    'asanaApproveAccessRequest',
    'Approve a pending access request.',
    asanaApproveAccessRequest,
    'write',
    ['grant join', 'accept request'],
  ),
  entry(
    'asanaRejectAccessRequest',
    'Reject a pending access request.',
    asanaRejectAccessRequest,
    'write',
    ['deny join', 'decline request'],
  ),
];
