// @ts-nocheck
import {
    createOrganization,
    deleteOrganization,
    getOrganization,
    listOrganizations,
    updateOrganization,
    createProject,
    deleteProject,
    getProject,
    listProjects,
    updateProject,
    getCurrentUser,
    listUsers,
    listAuditEvents,
} from './platform.js';
import {
    createPipeline,
    deletePipeline,
    getPipeline,
    getPipelineSummary,
    listPipelines,
    updatePipeline,
} from './pipelines.js';
import {
    abortExecution,
    getExecution,
    listExecutions,
    retryExecution,
    runPipeline,
} from './executions.js';
import {
    createService,
    deleteService,
    getService,
    listServices,
    updateService,
    createEnvironment,
    deleteEnvironment,
    getEnvironment,
    listEnvironments,
    updateEnvironment,
} from './services.js';
import {
    createConnector,
    deleteConnector,
    getConnector,
    listConnectors,
    updateConnector,
    createSecret,
    deleteSecret,
    getSecret,
    listSecrets,
    updateSecret,
} from './integrations.js';
import {
    createInputSet,
    deleteInputSet,
    getInputSet,
    listInputSets,
    updateInputSet,
    createTrigger,
    deleteTrigger,
    getTrigger,
    updateTrigger,
} from './automation.js';
import {
    getFeatureFlag,
    getSLO,
    listCIBuilds,
    listFeatureFlags,
    listSLOs,
} from './insights.js';

export {
    listOrganizations,
    getOrganization,
    createOrganization,
    updateOrganization,
    deleteOrganization,
    listProjects,
    getProject,
    createProject,
    updateProject,
    deleteProject,
    getCurrentUser,
    listUsers,
    listAuditEvents,
    listPipelines,
    getPipeline,
    getPipelineSummary,
    createPipeline,
    updatePipeline,
    deletePipeline,
    runPipeline,
    getExecution,
    listExecutions,
    abortExecution,
    retryExecution,
    listServices,
    getService,
    createService,
    updateService,
    deleteService,
    listEnvironments,
    getEnvironment,
    createEnvironment,
    updateEnvironment,
    deleteEnvironment,
    listConnectors,
    getConnector,
    createConnector,
    updateConnector,
    deleteConnector,
    listSecrets,
    getSecret,
    createSecret,
    updateSecret,
    deleteSecret,
    listInputSets,
    getInputSet,
    createInputSet,
    updateInputSet,
    deleteInputSet,
    getTrigger,
    createTrigger,
    updateTrigger,
    deleteTrigger,
    listFeatureFlags,
    getFeatureFlag,
    listSLOs,
    getSLO,
    listCIBuilds,
};

const auth = 'harnessCredentials' as const;

type Scope = 'read' | 'write' | 'delete';
function entry(
    name: string,
    description: string,
    toolRef: any,
    scope: Scope,
): { name: string; description: string; tool: any; requiredAuth: typeof auth; scope: Scope } {
    return { name, description, tool: toolRef, requiredAuth: auth, scope };
}

export const harnessTools = [
    entry('harnessListOrganizations', 'List organizations in a Harness account. Use first to discover org identifiers.', listOrganizations, 'read'),
    entry('harnessGetOrganization', 'Get a single Harness organization by identifier.', getOrganization, 'read'),
    entry('harnessCreateOrganization', 'Create a Harness organization under an account.', createOrganization, 'write'),
    entry('harnessUpdateOrganization', 'Update a Harness organization with a full organization object.', updateOrganization, 'write'),
    entry('harnessDeleteOrganization', 'Delete a Harness organization and everything under it.', deleteOrganization, 'delete'),
    entry('harnessListProjects', 'List Harness projects, optionally scoped to an organization.', listProjects, 'read'),
    entry('harnessGetProject', 'Get a single Harness project by identifier.', getProject, 'read'),
    entry('harnessCreateProject', 'Create a Harness project under an organization.', createProject, 'write'),
    entry('harnessUpdateProject', 'Update a Harness project with a full project object.', updateProject, 'write'),
    entry('harnessDeleteProject', 'Delete a Harness project and all resources under it.', deleteProject, 'delete'),
    entry('harnessGetCurrentUser', 'Get the Harness user the API token belongs to. Use to verify a token.', getCurrentUser, 'read'),
    entry('harnessListUsers', 'List users in a Harness account with names, emails and groups.', listUsers, 'read'),
    entry('harnessListAuditEvents', 'List Harness audit trail events: who changed what resource and when.', listAuditEvents, 'read'),
    entry('harnessListPipelines', 'List pipelines in a Harness project. Use first to discover pipeline identifiers.', listPipelines, 'read'),
    entry('harnessGetPipeline', 'Get a Harness pipeline definition including its YAML.', getPipeline, 'read'),
    entry('harnessGetPipelineSummary', 'Get a compact summary of a Harness pipeline with last execution status.', getPipelineSummary, 'read'),
    entry('harnessCreatePipeline', 'Create a Harness pipeline from a YAML document.', createPipeline, 'write'),
    entry('harnessUpdatePipeline', 'Update a Harness pipeline by replacing its YAML.', updatePipeline, 'write'),
    entry('harnessDeletePipeline', 'Delete a Harness pipeline.', deletePipeline, 'delete'),
    entry('harnessRunPipeline', 'Run a Harness pipeline with optional runtime inputs YAML. Returns the plan execution ID.', runPipeline, 'write'),
    entry('harnessGetExecution', 'Get status and details of a pipeline execution by plan execution ID.', getExecution, 'read'),
    entry('harnessListExecutions', 'List pipeline executions with status, trigger info and timing.', listExecutions, 'read'),
    entry('harnessAbortExecution', 'Abort a running Harness pipeline execution.', abortExecution, 'write'),
    entry('harnessRetryExecution', 'Retry a failed Harness pipeline execution from its failed stages.', retryExecution, 'write'),
    entry('harnessListServices', 'List services in a Harness project.', listServices, 'read'),
    entry('harnessGetService', 'Get a single Harness service definition by identifier.', getService, 'read'),
    entry('harnessCreateService', 'Create a Harness service from its service YAML.', createService, 'write'),
    entry('harnessUpdateService', 'Update a Harness service by replacing its service YAML.', updateService, 'write'),
    entry('harnessDeleteService', 'Delete a Harness service.', deleteService, 'delete'),
    entry('harnessListEnvironments', 'List environments in a Harness project.', listEnvironments, 'read'),
    entry('harnessGetEnvironment', 'Get a single Harness environment definition by identifier.', getEnvironment, 'read'),
    entry('harnessCreateEnvironment', 'Create a Harness environment from its environment YAML.', createEnvironment, 'write'),
    entry('harnessUpdateEnvironment', 'Update a Harness environment by replacing its environment YAML.', updateEnvironment, 'write'),
    entry('harnessDeleteEnvironment', 'Delete a Harness environment.', deleteEnvironment, 'delete'),
    entry('harnessListConnectors', 'List Harness connectors with type and connection status.', listConnectors, 'read'),
    entry('harnessGetConnector', 'Get a single Harness connector configuration by identifier.', getConnector, 'read'),
    entry('harnessCreateConnector', 'Create a Harness connector (cloud, registry, repo, secret manager).', createConnector, 'write'),
    entry('harnessUpdateConnector', 'Update a Harness connector with a full connector object.', updateConnector, 'write'),
    entry('harnessDeleteConnector', 'Delete a Harness connector.', deleteConnector, 'delete'),
    entry('harnessListSecrets', 'List Harness secrets (metadata only — values are never returned).', listSecrets, 'read'),
    entry('harnessGetSecret', 'Get Harness secret metadata by identifier.', getSecret, 'read'),
    entry('harnessCreateSecret', 'Create a Harness text secret (write-only value).', createSecret, 'write'),
    entry('harnessUpdateSecret', 'Update a Harness secret value or metadata.', updateSecret, 'write'),
    entry('harnessDeleteSecret', 'Delete a Harness secret.', deleteSecret, 'delete'),
    entry('harnessListInputSets', 'List input sets of a Harness pipeline.', listInputSets, 'read'),
    entry('harnessGetInputSet', 'Get a single Harness input set including its YAML values.', getInputSet, 'read'),
    entry('harnessCreateInputSet', 'Create a Harness input set from an input-set YAML document.', createInputSet, 'write'),
    entry('harnessUpdateInputSet', 'Update a Harness input set by replacing its YAML.', updateInputSet, 'write'),
    entry('harnessDeleteInputSet', 'Delete a Harness input set.', deleteInputSet, 'delete'),
    entry('harnessGetTrigger', 'Get a Harness trigger: event source, pipeline target and input bindings.', getTrigger, 'read'),
    entry('harnessCreateTrigger', 'Create a Harness trigger (webhook, schedule, artifact) from trigger YAML.', createTrigger, 'write'),
    entry('harnessUpdateTrigger', 'Update a Harness trigger by replacing its YAML.', updateTrigger, 'write'),
    entry('harnessDeleteTrigger', 'Delete a Harness trigger.', deleteTrigger, 'delete'),
    entry('harnessListFeatureFlags', 'List Harness Feature Flags with state and targeting.', listFeatureFlags, 'read'),
    entry('harnessGetFeatureFlag', 'Get a single Harness feature flag with variations and targeting rules.', getFeatureFlag, 'read'),
    entry('harnessListSLOs', 'List Harness SRM SLOs with error budgets and burn rates.', listSLOs, 'read'),
    entry('harnessGetSLO', 'Get a single Harness SLO with objectives and health sources.', getSLO, 'read'),
    entry('harnessListCIBuilds', 'List Harness CI builds with branch, commit, status and timing.', listCIBuilds, 'read'),
];
