// @ts-nocheck
import {
  bitbucketApprovePullRequest,
  bitbucketCreatePullRequest,
  bitbucketDeclinePullRequest,
  bitbucketMergePullRequest,
  bitbucketRequestPullRequestChanges,
  bitbucketUpdatePullRequest,
  bitbucketGetPullRequest,
  bitbucketListPullRequests,
  bitbucketListPullRequestTasks,
  bitbucketListPullRequestCommits,
  bitbucketGetPullRequestDiff,
  bitbucketGetPullRequestDiffstat,
  bitbucketListPullRequestActivity,
  bitbucketListPullRequestComments,
  bitbucketGetPullRequestComment,
  bitbucketCreatePullRequestComment,
  bitbucketDeletePullRequestComment,
  bitbucketResolvePullRequestComment,
  bitbucketListPullRequestStatuses,
  bitbucketGetWorkspacePullRequestsByUser,
} from './pull-requests.js';
import {
  bitbucketCreateIssue,
  bitbucketUpdateIssue,
  bitbucketDeleteIssue,
  bitbucketListIssues,
  bitbucketCreateIssueComment,
  bitbucketCheckIssueVote,
  bitbucketListVersions,
} from './issues.js';
import {
  bitbucketGetCommit,
  bitbucketListCommits,
  bitbucketListCommitsFromRevision,
  bitbucketListCommitsOnMaster,
  bitbucketListCommitsFromRevisionPost,
  bitbucketListCommitComments,
  bitbucketGetCommitComment,
  bitbucketUpdateCommitComment,
  bitbucketDeleteCommitComment,
  bitbucketGetCommitDiff,
  bitbucketGetCommitChanges,
  bitbucketGetCommitBuildStatus,
  bitbucketListCommitStatuses,
  bitbucketGetFileHistory,
  bitbucketGetMergeBase,
  bitbucketGetRepositoryPatch,
} from './commits.js';
import {
  bitbucketCreateCommitReportAnnotations,
  bitbucketGetCommitReport,
  bitbucketListCommitReports,
  bitbucketGetCommitReportAnnotation,
  bitbucketDeleteCommitReportAnnotation,
  bitbucketUpdateCommitReportAnnotation,
  bitbucketUpdateCommitInsightReport,
} from './reports.js';
import {
  bitbucketCreateRepository,
  bitbucketDeleteRepository,
  bitbucketGetRepository,
  bitbucketListWorkspaceRepositories,
  bitbucketListRepositories,
  bitbucketListRepositoryForks,
  bitbucketListRepositoryWatchers,
  bitbucketGetRepositorySrc,
  bitbucketBrowseRepositoryPath,
  bitbucketListRepositoryPaths,
  bitbucketGetFileFromRepository,
  bitbucketListBranches,
  bitbucketGetBranch,
  bitbucketCreateBranch,
  bitbucketListTags,
  bitbucketGetTag,
  bitbucketListRefs,
  bitbucketGetBranchingModel,
  bitbucketGetEffectiveBranchingModel,
} from './repositories.js';
import {
  bitbucketListPipelines,
  bitbucketGetPipeline,
  bitbucketListPipelineSteps,
  bitbucketStopPipeline,
  bitbucketListPipelineSchedules,
  bitbucketListPipelineCaches,
  bitbucketListPipelineRunners,
  bitbucketListPipelineSshKnownHosts,
  bitbucketListRepositoryPipelineVariables,
  bitbucketCreateTeamPipelineVariable,
  bitbucketUpdateTeamPipelineVariable,
  bitbucketCreateUserPipelineVariable,
  bitbucketUpdateUserPipelineVariable,
  bitbucketDeleteUserPipelineVariable,
  bitbucketListDeployments,
  bitbucketListRepositoryEnvironments,
  bitbucketGetRepositoryEnvironment,
  bitbucketListDeploymentEnvironmentVariables,
  bitbucketGetOpenidConfiguration,
} from './pipelines.js';
import {
  bitbucketGetSnippet,
  bitbucketListSnippets,
  bitbucketCreateSnippetComment,
  bitbucketGetSnippetWatchStatus,
  bitbucketDeleteSnippetWatch,
} from './snippets.js';
import {
  bitbucketGetCurrentUser,
  bitbucketGetUser,
  bitbucketGetUserEmails,
  bitbucketGetUserEmailDetails,
  bitbucketListUserSshKeys,
  bitbucketListUserRepositoryPermissions,
  bitbucketListUserWorkspacePermissions,
  bitbucketListUserWorkspaces,
  bitbucketListWorkspaceMembers,
  bitbucketListWorkspaceProjects,
  bitbucketGetWorkspace,
  bitbucketListWorkspaces,
  bitbucketListHookEvents,
} from './users-workspaces.js';
import { bitbucketSearchWorkspaceCode, bitbucketSearchUserCode } from './search.js';

export {
  bitbucketApprovePullRequest,
  bitbucketCreatePullRequest,
  bitbucketDeclinePullRequest,
  bitbucketMergePullRequest,
  bitbucketRequestPullRequestChanges,
  bitbucketUpdatePullRequest,
  bitbucketGetPullRequest,
  bitbucketListPullRequests,
  bitbucketListPullRequestTasks,
  bitbucketListPullRequestCommits,
  bitbucketGetPullRequestDiff,
  bitbucketGetPullRequestDiffstat,
  bitbucketListPullRequestActivity,
  bitbucketListPullRequestComments,
  bitbucketGetPullRequestComment,
  bitbucketCreatePullRequestComment,
  bitbucketDeletePullRequestComment,
  bitbucketResolvePullRequestComment,
  bitbucketListPullRequestStatuses,
  bitbucketGetWorkspacePullRequestsByUser,
  bitbucketCreateIssue,
  bitbucketUpdateIssue,
  bitbucketDeleteIssue,
  bitbucketListIssues,
  bitbucketCreateIssueComment,
  bitbucketCheckIssueVote,
  bitbucketListVersions,
  bitbucketGetCommit,
  bitbucketListCommits,
  bitbucketListCommitsFromRevision,
  bitbucketListCommitsOnMaster,
  bitbucketListCommitsFromRevisionPost,
  bitbucketListCommitComments,
  bitbucketGetCommitComment,
  bitbucketUpdateCommitComment,
  bitbucketDeleteCommitComment,
  bitbucketGetCommitDiff,
  bitbucketGetCommitChanges,
  bitbucketGetCommitBuildStatus,
  bitbucketListCommitStatuses,
  bitbucketGetFileHistory,
  bitbucketGetMergeBase,
  bitbucketGetRepositoryPatch,
  bitbucketCreateCommitReportAnnotations,
  bitbucketGetCommitReport,
  bitbucketListCommitReports,
  bitbucketGetCommitReportAnnotation,
  bitbucketDeleteCommitReportAnnotation,
  bitbucketUpdateCommitReportAnnotation,
  bitbucketUpdateCommitInsightReport,
  bitbucketCreateRepository,
  bitbucketDeleteRepository,
  bitbucketGetRepository,
  bitbucketListWorkspaceRepositories,
  bitbucketListRepositories,
  bitbucketListRepositoryForks,
  bitbucketListRepositoryWatchers,
  bitbucketGetRepositorySrc,
  bitbucketBrowseRepositoryPath,
  bitbucketListRepositoryPaths,
  bitbucketGetFileFromRepository,
  bitbucketListBranches,
  bitbucketGetBranch,
  bitbucketCreateBranch,
  bitbucketListTags,
  bitbucketGetTag,
  bitbucketListRefs,
  bitbucketGetBranchingModel,
  bitbucketGetEffectiveBranchingModel,
  bitbucketListPipelines,
  bitbucketGetPipeline,
  bitbucketListPipelineSteps,
  bitbucketStopPipeline,
  bitbucketListPipelineSchedules,
  bitbucketListPipelineCaches,
  bitbucketListPipelineRunners,
  bitbucketListPipelineSshKnownHosts,
  bitbucketListRepositoryPipelineVariables,
  bitbucketCreateTeamPipelineVariable,
  bitbucketUpdateTeamPipelineVariable,
  bitbucketCreateUserPipelineVariable,
  bitbucketUpdateUserPipelineVariable,
  bitbucketDeleteUserPipelineVariable,
  bitbucketListDeployments,
  bitbucketListRepositoryEnvironments,
  bitbucketGetRepositoryEnvironment,
  bitbucketListDeploymentEnvironmentVariables,
  bitbucketGetOpenidConfiguration,
  bitbucketGetSnippet,
  bitbucketListSnippets,
  bitbucketCreateSnippetComment,
  bitbucketGetSnippetWatchStatus,
  bitbucketDeleteSnippetWatch,
  bitbucketGetCurrentUser,
  bitbucketGetUser,
  bitbucketGetUserEmails,
  bitbucketGetUserEmailDetails,
  bitbucketListUserSshKeys,
  bitbucketListUserRepositoryPermissions,
  bitbucketListUserWorkspacePermissions,
  bitbucketListUserWorkspaces,
  bitbucketListWorkspaceMembers,
  bitbucketListWorkspaceProjects,
  bitbucketGetWorkspace,
  bitbucketListWorkspaces,
  bitbucketListHookEvents,
  bitbucketSearchWorkspaceCode,
  bitbucketSearchUserCode,
};

export const bitbucketTools = [
  {
    name: 'bitbucketApprovePullRequest',
    description: bitbucketApprovePullRequest.description!,
    tool: bitbucketApprovePullRequest,
    requiredAuth: 'bitbucketToken' as const,
    scope: 'write' as const,
    keywords: ['pr', 'lgtm'],
  },
  {
    name: 'bitbucketCreatePullRequest',
    description: bitbucketCreatePullRequest.description!,
    tool: bitbucketCreatePullRequest,
    requiredAuth: 'bitbucketToken' as const,
    scope: 'write' as const,
    keywords: ['pr', 'merge'],
  },
  {
    name: 'bitbucketDeclinePullRequest',
    description: bitbucketDeclinePullRequest.description!,
    tool: bitbucketDeclinePullRequest,
    requiredAuth: 'bitbucketToken' as const,
    scope: 'write' as const,
    keywords: ['pr', 'reject'],
  },
  {
    name: 'bitbucketMergePullRequest',
    description: bitbucketMergePullRequest.description!,
    tool: bitbucketMergePullRequest,
    requiredAuth: 'bitbucketToken' as const,
    scope: 'write' as const,
    keywords: ['pr'],
  },
  {
    name: 'bitbucketRequestPullRequestChanges',
    description: bitbucketRequestPullRequestChanges.description!,
    tool: bitbucketRequestPullRequestChanges,
    requiredAuth: 'bitbucketToken' as const,
    scope: 'write' as const,
    keywords: ['pr', 'review'],
  },
  {
    name: 'bitbucketUpdatePullRequest',
    description: bitbucketUpdatePullRequest.description!,
    tool: bitbucketUpdatePullRequest,
    requiredAuth: 'bitbucketToken' as const,
    scope: 'write' as const,
    keywords: ['pr'],
  },
  {
    name: 'bitbucketGetPullRequest',
    description: bitbucketGetPullRequest.description!,
    tool: bitbucketGetPullRequest,
    requiredAuth: 'bitbucketToken' as const,
    scope: 'read' as const,
    keywords: ['pr', 'diff'],
  },
  {
    name: 'bitbucketListPullRequests',
    description: bitbucketListPullRequests.description!,
    tool: bitbucketListPullRequests,
    requiredAuth: 'bitbucketToken' as const,
    scope: 'read' as const,
    keywords: ['pr', 'prs', 'review'],
  },
  {
    name: 'bitbucketListPullRequestTasks',
    description: bitbucketListPullRequestTasks.description!,
    tool: bitbucketListPullRequestTasks,
    requiredAuth: 'bitbucketToken' as const,
    scope: 'read' as const,
    keywords: ['pr', 'todo'],
  },
  {
    name: 'bitbucketListPullRequestCommits',
    description: bitbucketListPullRequestCommits.description!,
    tool: bitbucketListPullRequestCommits,
    requiredAuth: 'bitbucketToken' as const,
    scope: 'read' as const,
    keywords: ['pr', 'history'],
  },
  {
    name: 'bitbucketGetPullRequestDiff',
    description: bitbucketGetPullRequestDiff.description!,
    tool: bitbucketGetPullRequestDiff,
    requiredAuth: 'bitbucketToken' as const,
    scope: 'read' as const,
    keywords: ['pr', 'changes', 'patch'],
  },
  {
    name: 'bitbucketGetPullRequestDiffstat',
    description: bitbucketGetPullRequestDiffstat.description!,
    tool: bitbucketGetPullRequestDiffstat,
    requiredAuth: 'bitbucketToken' as const,
    scope: 'read' as const,
    keywords: ['pr', 'changes'],
  },
  {
    name: 'bitbucketListPullRequestActivity',
    description: bitbucketListPullRequestActivity.description!,
    tool: bitbucketListPullRequestActivity,
    requiredAuth: 'bitbucketToken' as const,
    scope: 'read' as const,
    keywords: ['pr', 'history'],
  },
  {
    name: 'bitbucketListPullRequestComments',
    description: bitbucketListPullRequestComments.description!,
    tool: bitbucketListPullRequestComments,
    requiredAuth: 'bitbucketToken' as const,
    scope: 'read' as const,
    keywords: ['pr', 'thread', 'review'],
  },
  {
    name: 'bitbucketGetPullRequestComment',
    description: bitbucketGetPullRequestComment.description!,
    tool: bitbucketGetPullRequestComment,
    requiredAuth: 'bitbucketToken' as const,
    scope: 'read' as const,
    keywords: ['pr', 'thread'],
  },
  {
    name: 'bitbucketCreatePullRequestComment',
    description: bitbucketCreatePullRequestComment.description!,
    tool: bitbucketCreatePullRequestComment,
    requiredAuth: 'bitbucketToken' as const,
    scope: 'write' as const,
    keywords: ['pr', 'thread', 'reply'],
  },
  {
    name: 'bitbucketDeletePullRequestComment',
    description: bitbucketDeletePullRequestComment.description!,
    tool: bitbucketDeletePullRequestComment,
    requiredAuth: 'bitbucketToken' as const,
    scope: 'delete' as const,
    keywords: ['pr', 'thread', 'remove'],
  },
  {
    name: 'bitbucketResolvePullRequestComment',
    description: bitbucketResolvePullRequestComment.description!,
    tool: bitbucketResolvePullRequestComment,
    requiredAuth: 'bitbucketToken' as const,
    scope: 'write' as const,
    keywords: ['pr', 'thread'],
  },
  {
    name: 'bitbucketListPullRequestStatuses',
    description: bitbucketListPullRequestStatuses.description!,
    tool: bitbucketListPullRequestStatuses,
    requiredAuth: 'bitbucketToken' as const,
    scope: 'read' as const,
    keywords: ['pr', 'checks', 'ci', 'build'],
  },
  {
    name: 'bitbucketGetWorkspacePullRequestsByUser',
    description: bitbucketGetWorkspacePullRequestsByUser.description!,
    tool: bitbucketGetWorkspacePullRequestsByUser,
    requiredAuth: 'bitbucketToken' as const,
    scope: 'read' as const,
    keywords: ['pr', 'prs', 'author'],
  },
  {
    name: 'bitbucketCreateIssue',
    description: bitbucketCreateIssue.description!,
    tool: bitbucketCreateIssue,
    requiredAuth: 'bitbucketToken' as const,
    scope: 'write' as const,
    keywords: ['ticket', 'tickets', 'bug'],
  },
  {
    name: 'bitbucketUpdateIssue',
    description: bitbucketUpdateIssue.description!,
    tool: bitbucketUpdateIssue,
    requiredAuth: 'bitbucketToken' as const,
    scope: 'write' as const,
    keywords: ['ticket', 'bug'],
  },
  {
    name: 'bitbucketDeleteIssue',
    description: bitbucketDeleteIssue.description!,
    tool: bitbucketDeleteIssue,
    requiredAuth: 'bitbucketToken' as const,
    scope: 'delete' as const,
    keywords: ['ticket', 'remove'],
  },
  {
    name: 'bitbucketListIssues',
    description: bitbucketListIssues.description!,
    tool: bitbucketListIssues,
    requiredAuth: 'bitbucketToken' as const,
    scope: 'read' as const,
    keywords: ['ticket', 'tickets', 'bug'],
  },
  {
    name: 'bitbucketCreateIssueComment',
    description: bitbucketCreateIssueComment.description!,
    tool: bitbucketCreateIssueComment,
    requiredAuth: 'bitbucketToken' as const,
    scope: 'write' as const,
    keywords: ['ticket', 'reply'],
  },
  {
    name: 'bitbucketCheckIssueVote',
    description: bitbucketCheckIssueVote.description!,
    tool: bitbucketCheckIssueVote,
    requiredAuth: 'bitbucketToken' as const,
    scope: 'read' as const,
    keywords: ['ticket', 'upvote'],
  },
  {
    name: 'bitbucketListVersions',
    description: bitbucketListVersions.description!,
    tool: bitbucketListVersions,
    requiredAuth: 'bitbucketToken' as const,
    scope: 'read' as const,
    keywords: ['milestone', 'release'],
  },
  {
    name: 'bitbucketGetCommit',
    description: bitbucketGetCommit.description!,
    tool: bitbucketGetCommit,
    requiredAuth: 'bitbucketToken' as const,
    scope: 'read' as const,
    keywords: ['sha', 'hash'],
  },
  {
    name: 'bitbucketListCommits',
    description: bitbucketListCommits.description!,
    tool: bitbucketListCommits,
    requiredAuth: 'bitbucketToken' as const,
    scope: 'read' as const,
    keywords: ['sha', 'history'],
  },
  {
    name: 'bitbucketListCommitsFromRevision',
    description: bitbucketListCommitsFromRevision.description!,
    tool: bitbucketListCommitsFromRevision,
    requiredAuth: 'bitbucketToken' as const,
    scope: 'read' as const,
    keywords: ['sha', 'history'],
  },
  {
    name: 'bitbucketListCommitsOnMaster',
    description: bitbucketListCommitsOnMaster.description!,
    tool: bitbucketListCommitsOnMaster,
    requiredAuth: 'bitbucketToken' as const,
    scope: 'read' as const,
    keywords: ['history', 'main'],
  },
  {
    name: 'bitbucketListCommitsFromRevisionPost',
    description: bitbucketListCommitsFromRevisionPost.description!,
    tool: bitbucketListCommitsFromRevisionPost,
    requiredAuth: 'bitbucketToken' as const,
    scope: 'read' as const,
    keywords: ['sha', 'history'],
  },
  {
    name: 'bitbucketListCommitComments',
    description: bitbucketListCommitComments.description!,
    tool: bitbucketListCommitComments,
    requiredAuth: 'bitbucketToken' as const,
    scope: 'read' as const,
    keywords: [],
  },
  {
    name: 'bitbucketGetCommitComment',
    description: bitbucketGetCommitComment.description!,
    tool: bitbucketGetCommitComment,
    requiredAuth: 'bitbucketToken' as const,
    scope: 'read' as const,
    keywords: [],
  },
  {
    name: 'bitbucketUpdateCommitComment',
    description: bitbucketUpdateCommitComment.description!,
    tool: bitbucketUpdateCommitComment,
    requiredAuth: 'bitbucketToken' as const,
    scope: 'write' as const,
    keywords: [],
  },
  {
    name: 'bitbucketDeleteCommitComment',
    description: bitbucketDeleteCommitComment.description!,
    tool: bitbucketDeleteCommitComment,
    requiredAuth: 'bitbucketToken' as const,
    scope: 'delete' as const,
    keywords: [],
  },
  {
    name: 'bitbucketGetCommitDiff',
    description: bitbucketGetCommitDiff.description!,
    tool: bitbucketGetCommitDiff,
    requiredAuth: 'bitbucketToken' as const,
    scope: 'read' as const,
    keywords: ['patch', 'changes'],
  },
  {
    name: 'bitbucketGetCommitChanges',
    description: bitbucketGetCommitChanges.description!,
    tool: bitbucketGetCommitChanges,
    requiredAuth: 'bitbucketToken' as const,
    scope: 'read' as const,
    keywords: ['patch'],
  },
  {
    name: 'bitbucketGetCommitBuildStatus',
    description: bitbucketGetCommitBuildStatus.description!,
    tool: bitbucketGetCommitBuildStatus,
    requiredAuth: 'bitbucketToken' as const,
    scope: 'read' as const,
    keywords: [],
  },
  {
    name: 'bitbucketListCommitStatuses',
    description: bitbucketListCommitStatuses.description!,
    tool: bitbucketListCommitStatuses,
    requiredAuth: 'bitbucketToken' as const,
    scope: 'read' as const,
    keywords: [],
  },
  {
    name: 'bitbucketGetFileHistory',
    description: bitbucketGetFileHistory.description!,
    tool: bitbucketGetFileHistory,
    requiredAuth: 'bitbucketToken' as const,
    scope: 'read' as const,
    keywords: [],
  },
  {
    name: 'bitbucketGetMergeBase',
    description: bitbucketGetMergeBase.description!,
    tool: bitbucketGetMergeBase,
    requiredAuth: 'bitbucketToken' as const,
    scope: 'read' as const,
    keywords: [],
  },
  {
    name: 'bitbucketGetRepositoryPatch',
    description: bitbucketGetRepositoryPatch.description!,
    tool: bitbucketGetRepositoryPatch,
    requiredAuth: 'bitbucketToken' as const,
    scope: 'read' as const,
    keywords: ['diff'],
  },
  {
    name: 'bitbucketCreateCommitReportAnnotations',
    description: bitbucketCreateCommitReportAnnotations.description!,
    tool: bitbucketCreateCommitReportAnnotations,
    requiredAuth: 'bitbucketToken' as const,
    scope: 'write' as const,
    keywords: ['vulnerabilities', 'insights'],
  },
  {
    name: 'bitbucketGetCommitReport',
    description: bitbucketGetCommitReport.description!,
    tool: bitbucketGetCommitReport,
    requiredAuth: 'bitbucketToken' as const,
    scope: 'read' as const,
    keywords: ['insights', 'coverage'],
  },
  {
    name: 'bitbucketListCommitReports',
    description: bitbucketListCommitReports.description!,
    tool: bitbucketListCommitReports,
    requiredAuth: 'bitbucketToken' as const,
    scope: 'read' as const,
    keywords: ['insights', 'coverage', 'scan'],
  },
  {
    name: 'bitbucketGetCommitReportAnnotation',
    description: bitbucketGetCommitReportAnnotation.description!,
    tool: bitbucketGetCommitReportAnnotation,
    requiredAuth: 'bitbucketToken' as const,
    scope: 'read' as const,
    keywords: ['vulnerabilities', 'insights'],
  },
  {
    name: 'bitbucketDeleteCommitReportAnnotation',
    description: bitbucketDeleteCommitReportAnnotation.description!,
    tool: bitbucketDeleteCommitReportAnnotation,
    requiredAuth: 'bitbucketToken' as const,
    scope: 'delete' as const,
    keywords: ['vulnerabilities', 'remove'],
  },
  {
    name: 'bitbucketUpdateCommitReportAnnotation',
    description: bitbucketUpdateCommitReportAnnotation.description!,
    tool: bitbucketUpdateCommitReportAnnotation,
    requiredAuth: 'bitbucketToken' as const,
    scope: 'write' as const,
    keywords: ['vulnerabilities'],
  },
  {
    name: 'bitbucketUpdateCommitInsightReport',
    description: bitbucketUpdateCommitInsightReport.description!,
    tool: bitbucketUpdateCommitInsightReport,
    requiredAuth: 'bitbucketToken' as const,
    scope: 'write' as const,
    keywords: ['insights', 'coverage'],
  },
  {
    name: 'bitbucketCreateRepository',
    description: bitbucketCreateRepository.description!,
    tool: bitbucketCreateRepository,
    requiredAuth: 'bitbucketToken' as const,
    scope: 'write' as const,
    keywords: ['repo', 'repos', 'git', 'new'],
  },
  {
    name: 'bitbucketDeleteRepository',
    description: bitbucketDeleteRepository.description!,
    tool: bitbucketDeleteRepository,
    requiredAuth: 'bitbucketToken' as const,
    scope: 'delete' as const,
    keywords: ['repo', 'repos', 'remove'],
  },
  {
    name: 'bitbucketGetRepository',
    description: bitbucketGetRepository.description!,
    tool: bitbucketGetRepository,
    requiredAuth: 'bitbucketToken' as const,
    scope: 'read' as const,
    keywords: ['repo', 'repos'],
  },
  {
    name: 'bitbucketListWorkspaceRepositories',
    description: bitbucketListWorkspaceRepositories.description!,
    tool: bitbucketListWorkspaceRepositories,
    requiredAuth: 'bitbucketToken' as const,
    scope: 'read' as const,
    keywords: ['repo', 'repos', 'browse'],
  },
  {
    name: 'bitbucketListRepositories',
    description: bitbucketListRepositories.description!,
    tool: bitbucketListRepositories,
    requiredAuth: 'bitbucketToken' as const,
    scope: 'read' as const,
    keywords: ['repo', 'repos', 'discover'],
  },
  {
    name: 'bitbucketListRepositoryForks',
    description: bitbucketListRepositoryForks.description!,
    tool: bitbucketListRepositoryForks,
    requiredAuth: 'bitbucketToken' as const,
    scope: 'read' as const,
    keywords: ['repo', 'clone'],
  },
  {
    name: 'bitbucketListRepositoryWatchers',
    description: bitbucketListRepositoryWatchers.description!,
    tool: bitbucketListRepositoryWatchers,
    requiredAuth: 'bitbucketToken' as const,
    scope: 'read' as const,
    keywords: ['subscribe', 'follow', 'star'],
  },
  {
    name: 'bitbucketGetRepositorySrc',
    description: bitbucketGetRepositorySrc.description!,
    tool: bitbucketGetRepositorySrc,
    requiredAuth: 'bitbucketToken' as const,
    scope: 'read' as const,
    keywords: ['repo', 'browse', 'files'],
  },
  {
    name: 'bitbucketBrowseRepositoryPath',
    description: bitbucketBrowseRepositoryPath.description!,
    tool: bitbucketBrowseRepositoryPath,
    requiredAuth: 'bitbucketToken' as const,
    scope: 'read' as const,
    keywords: ['browse', 'ls', 'files'],
  },
  {
    name: 'bitbucketListRepositoryPaths',
    description: bitbucketListRepositoryPaths.description!,
    tool: bitbucketListRepositoryPaths,
    requiredAuth: 'bitbucketToken' as const,
    scope: 'read' as const,
    keywords: ['browse', 'ls'],
  },
  {
    name: 'bitbucketGetFileFromRepository',
    description: bitbucketGetFileFromRepository.description!,
    tool: bitbucketGetFileFromRepository,
    requiredAuth: 'bitbucketToken' as const,
    scope: 'read' as const,
    keywords: ['download', 'cat'],
  },
  {
    name: 'bitbucketListBranches',
    description: bitbucketListBranches.description!,
    tool: bitbucketListBranches,
    requiredAuth: 'bitbucketToken' as const,
    scope: 'read' as const,
    keywords: [],
  },
  {
    name: 'bitbucketGetBranch',
    description: bitbucketGetBranch.description!,
    tool: bitbucketGetBranch,
    requiredAuth: 'bitbucketToken' as const,
    scope: 'read' as const,
    keywords: [],
  },
  {
    name: 'bitbucketCreateBranch',
    description: bitbucketCreateBranch.description!,
    tool: bitbucketCreateBranch,
    requiredAuth: 'bitbucketToken' as const,
    scope: 'write' as const,
    keywords: [],
  },
  {
    name: 'bitbucketListTags',
    description: bitbucketListTags.description!,
    tool: bitbucketListTags,
    requiredAuth: 'bitbucketToken' as const,
    scope: 'read' as const,
    keywords: [],
  },
  {
    name: 'bitbucketGetTag',
    description: bitbucketGetTag.description!,
    tool: bitbucketGetTag,
    requiredAuth: 'bitbucketToken' as const,
    scope: 'read' as const,
    keywords: [],
  },
  {
    name: 'bitbucketListRefs',
    description: bitbucketListRefs.description!,
    tool: bitbucketListRefs,
    requiredAuth: 'bitbucketToken' as const,
    scope: 'read' as const,
    keywords: [],
  },
  {
    name: 'bitbucketGetBranchingModel',
    description: bitbucketGetBranchingModel.description!,
    tool: bitbucketGetBranchingModel,
    requiredAuth: 'bitbucketToken' as const,
    scope: 'read' as const,
    keywords: ['gitflow', 'strategy'],
  },
  {
    name: 'bitbucketGetEffectiveBranchingModel',
    description: bitbucketGetEffectiveBranchingModel.description!,
    tool: bitbucketGetEffectiveBranchingModel,
    requiredAuth: 'bitbucketToken' as const,
    scope: 'read' as const,
    keywords: ['gitflow', 'strategy'],
  },
  {
    name: 'bitbucketListPipelines',
    description: bitbucketListPipelines.description!,
    tool: bitbucketListPipelines,
    requiredAuth: 'bitbucketToken' as const,
    scope: 'read' as const,
    keywords: ['ci', 'build', 'deploy', 'run'],
  },
  {
    name: 'bitbucketGetPipeline',
    description: bitbucketGetPipeline.description!,
    tool: bitbucketGetPipeline,
    requiredAuth: 'bitbucketToken' as const,
    scope: 'read' as const,
    keywords: ['ci', 'build', 'status'],
  },
  {
    name: 'bitbucketListPipelineSteps',
    description: bitbucketListPipelineSteps.description!,
    tool: bitbucketListPipelineSteps,
    requiredAuth: 'bitbucketToken' as const,
    scope: 'read' as const,
    keywords: ['job', 'jobs', 'stage', 'ci'],
  },
  {
    name: 'bitbucketStopPipeline',
    description: bitbucketStopPipeline.description!,
    tool: bitbucketStopPipeline,
    requiredAuth: 'bitbucketToken' as const,
    scope: 'write' as const,
    keywords: ['cancel', 'ci'],
  },
  {
    name: 'bitbucketListPipelineSchedules',
    description: bitbucketListPipelineSchedules.description!,
    tool: bitbucketListPipelineSchedules,
    requiredAuth: 'bitbucketToken' as const,
    scope: 'read' as const,
    keywords: [],
  },
  {
    name: 'bitbucketListPipelineCaches',
    description: bitbucketListPipelineCaches.description!,
    tool: bitbucketListPipelineCaches,
    requiredAuth: 'bitbucketToken' as const,
    scope: 'read' as const,
    keywords: [],
  },
  {
    name: 'bitbucketListPipelineRunners',
    description: bitbucketListPipelineRunners.description!,
    tool: bitbucketListPipelineRunners,
    requiredAuth: 'bitbucketToken' as const,
    scope: 'read' as const,
    keywords: [],
  },
  {
    name: 'bitbucketListPipelineSshKnownHosts',
    description: bitbucketListPipelineSshKnownHosts.description!,
    tool: bitbucketListPipelineSshKnownHosts,
    requiredAuth: 'bitbucketToken' as const,
    scope: 'read' as const,
    keywords: [],
  },
  {
    name: 'bitbucketListRepositoryPipelineVariables',
    description: bitbucketListRepositoryPipelineVariables.description!,
    tool: bitbucketListRepositoryPipelineVariables,
    requiredAuth: 'bitbucketToken' as const,
    scope: 'read' as const,
    keywords: [],
  },
  {
    name: 'bitbucketCreateTeamPipelineVariable',
    description: bitbucketCreateTeamPipelineVariable.description!,
    tool: bitbucketCreateTeamPipelineVariable,
    requiredAuth: 'bitbucketToken' as const,
    scope: 'write' as const,
    keywords: ['env', 'secret', 'secrets'],
  },
  {
    name: 'bitbucketUpdateTeamPipelineVariable',
    description: bitbucketUpdateTeamPipelineVariable.description!,
    tool: bitbucketUpdateTeamPipelineVariable,
    requiredAuth: 'bitbucketToken' as const,
    scope: 'write' as const,
    keywords: ['env', 'secret'],
  },
  {
    name: 'bitbucketCreateUserPipelineVariable',
    description: bitbucketCreateUserPipelineVariable.description!,
    tool: bitbucketCreateUserPipelineVariable,
    requiredAuth: 'bitbucketToken' as const,
    scope: 'write' as const,
    keywords: ['env', 'secret'],
  },
  {
    name: 'bitbucketUpdateUserPipelineVariable',
    description: bitbucketUpdateUserPipelineVariable.description!,
    tool: bitbucketUpdateUserPipelineVariable,
    requiredAuth: 'bitbucketToken' as const,
    scope: 'write' as const,
    keywords: ['env', 'secret'],
  },
  {
    name: 'bitbucketDeleteUserPipelineVariable',
    description: bitbucketDeleteUserPipelineVariable.description!,
    tool: bitbucketDeleteUserPipelineVariable,
    requiredAuth: 'bitbucketToken' as const,
    scope: 'delete' as const,
    keywords: ['env', 'remove'],
  },
  {
    name: 'bitbucketListDeployments',
    description: bitbucketListDeployments.description!,
    tool: bitbucketListDeployments,
    requiredAuth: 'bitbucketToken' as const,
    scope: 'read' as const,
    keywords: ['release', 'deploy'],
  },
  {
    name: 'bitbucketListRepositoryEnvironments',
    description: bitbucketListRepositoryEnvironments.description!,
    tool: bitbucketListRepositoryEnvironments,
    requiredAuth: 'bitbucketToken' as const,
    scope: 'read' as const,
    keywords: ['deploy'],
  },
  {
    name: 'bitbucketGetRepositoryEnvironment',
    description: bitbucketGetRepositoryEnvironment.description!,
    tool: bitbucketGetRepositoryEnvironment,
    requiredAuth: 'bitbucketToken' as const,
    scope: 'read' as const,
    keywords: ['deploy'],
  },
  {
    name: 'bitbucketListDeploymentEnvironmentVariables',
    description: bitbucketListDeploymentEnvironmentVariables.description!,
    tool: bitbucketListDeploymentEnvironmentVariables,
    requiredAuth: 'bitbucketToken' as const,
    scope: 'read' as const,
    keywords: ['env', 'secret', 'secrets'],
  },
  {
    name: 'bitbucketGetOpenidConfiguration',
    description: bitbucketGetOpenidConfiguration.description!,
    tool: bitbucketGetOpenidConfiguration,
    requiredAuth: 'bitbucketToken' as const,
    scope: 'read' as const,
    keywords: [],
  },
  {
    name: 'bitbucketGetSnippet',
    description: bitbucketGetSnippet.description!,
    tool: bitbucketGetSnippet,
    requiredAuth: 'bitbucketToken' as const,
    scope: 'read' as const,
    keywords: ['gist', 'gists', 'paste'],
  },
  {
    name: 'bitbucketListSnippets',
    description: bitbucketListSnippets.description!,
    tool: bitbucketListSnippets,
    requiredAuth: 'bitbucketToken' as const,
    scope: 'read' as const,
    keywords: ['gist', 'gists', 'browse'],
  },
  {
    name: 'bitbucketCreateSnippetComment',
    description: bitbucketCreateSnippetComment.description!,
    tool: bitbucketCreateSnippetComment,
    requiredAuth: 'bitbucketToken' as const,
    scope: 'write' as const,
    keywords: ['gist', 'reply'],
  },
  {
    name: 'bitbucketGetSnippetWatchStatus',
    description: bitbucketGetSnippetWatchStatus.description!,
    tool: bitbucketGetSnippetWatchStatus,
    requiredAuth: 'bitbucketToken' as const,
    scope: 'read' as const,
    keywords: ['subscribe', 'follow'],
  },
  {
    name: 'bitbucketDeleteSnippetWatch',
    description: bitbucketDeleteSnippetWatch.description!,
    tool: bitbucketDeleteSnippetWatch,
    requiredAuth: 'bitbucketToken' as const,
    scope: 'delete' as const,
    keywords: ['unsubscribe', 'remove'],
  },
  {
    name: 'bitbucketGetCurrentUser',
    description: bitbucketGetCurrentUser.description!,
    tool: bitbucketGetCurrentUser,
    requiredAuth: 'bitbucketToken' as const,
    scope: 'read' as const,
    keywords: ['profile', 'account'],
  },
  {
    name: 'bitbucketGetUser',
    description: bitbucketGetUser.description!,
    tool: bitbucketGetUser,
    requiredAuth: 'bitbucketToken' as const,
    scope: 'read' as const,
    keywords: ['profile'],
  },
  {
    name: 'bitbucketGetUserEmails',
    description: bitbucketGetUserEmails.description!,
    tool: bitbucketGetUserEmails,
    requiredAuth: 'bitbucketToken' as const,
    scope: 'read' as const,
    keywords: [],
  },
  {
    name: 'bitbucketGetUserEmailDetails',
    description: bitbucketGetUserEmailDetails.description!,
    tool: bitbucketGetUserEmailDetails,
    requiredAuth: 'bitbucketToken' as const,
    scope: 'read' as const,
    keywords: [],
  },
  {
    name: 'bitbucketListUserSshKeys',
    description: bitbucketListUserSshKeys.description!,
    tool: bitbucketListUserSshKeys,
    requiredAuth: 'bitbucketToken' as const,
    scope: 'read' as const,
    keywords: [],
  },
  {
    name: 'bitbucketListUserRepositoryPermissions',
    description: bitbucketListUserRepositoryPermissions.description!,
    tool: bitbucketListUserRepositoryPermissions,
    requiredAuth: 'bitbucketToken' as const,
    scope: 'read' as const,
    keywords: ['access', 'repo'],
  },
  {
    name: 'bitbucketListUserWorkspacePermissions',
    description: bitbucketListUserWorkspacePermissions.description!,
    tool: bitbucketListUserWorkspacePermissions,
    requiredAuth: 'bitbucketToken' as const,
    scope: 'read' as const,
    keywords: ['access', 'team'],
  },
  {
    name: 'bitbucketListUserWorkspaces',
    description: bitbucketListUserWorkspaces.description!,
    tool: bitbucketListUserWorkspaces,
    requiredAuth: 'bitbucketToken' as const,
    scope: 'read' as const,
    keywords: ['team', 'browse'],
  },
  {
    name: 'bitbucketListWorkspaceMembers',
    description: bitbucketListWorkspaceMembers.description!,
    tool: bitbucketListWorkspaceMembers,
    requiredAuth: 'bitbucketToken' as const,
    scope: 'read' as const,
    keywords: ['team'],
  },
  {
    name: 'bitbucketListWorkspaceProjects',
    description: bitbucketListWorkspaceProjects.description!,
    tool: bitbucketListWorkspaceProjects,
    requiredAuth: 'bitbucketToken' as const,
    scope: 'read' as const,
    keywords: ['team'],
  },
  {
    name: 'bitbucketGetWorkspace',
    description: bitbucketGetWorkspace.description!,
    tool: bitbucketGetWorkspace,
    requiredAuth: 'bitbucketToken' as const,
    scope: 'read' as const,
    keywords: ['team'],
  },
  {
    name: 'bitbucketListWorkspaces',
    description: bitbucketListWorkspaces.description!,
    tool: bitbucketListWorkspaces,
    requiredAuth: 'bitbucketToken' as const,
    scope: 'read' as const,
    keywords: ['team', 'browse'],
  },
  {
    name: 'bitbucketListHookEvents',
    description: bitbucketListHookEvents.description!,
    tool: bitbucketListHookEvents,
    requiredAuth: 'bitbucketToken' as const,
    scope: 'read' as const,
    keywords: ['webhook', 'trigger'],
  },
  {
    name: 'bitbucketSearchWorkspaceCode',
    description: bitbucketSearchWorkspaceCode.description!,
    tool: bitbucketSearchWorkspaceCode,
    requiredAuth: 'bitbucketToken' as const,
    scope: 'read' as const,
    keywords: ['grep', 'find'],
  },
  {
    name: 'bitbucketSearchUserCode',
    description: bitbucketSearchUserCode.description!,
    tool: bitbucketSearchUserCode,
    requiredAuth: 'bitbucketToken' as const,
    scope: 'read' as const,
    keywords: ['grep', 'find'],
  },
];
