import { defineToolkit, defineTool } from '../../core/define.js';
import { GMAIL_ICON } from './icon.js';
import {
  listMessages,
  getMessage,
  sendMessage,
  createDraft,
  listDrafts,
  getDraft,
  sendDraft,
  deleteDraft,
  listThreads,
  getThread,
  replyToThread,
  listLabels,
  modifyMessageLabels,
  trashMessage,
  untrashMessage,
  batchDeleteMessages,
  batchModifyMessages,
  createFilter,
  createLabel,
  deleteFilter,
  deleteLabel,
  deleteMessage,
  deleteThread,
  forwardMessage,
  getAttachment,
  getAutoForwarding,
  getContacts,
  getFilter,
  fetchEmails,
  getLabel,
  getLanguageSettings,
  getPeople,
  getProfile,
  getVacationSettings,
  importMessage,
  insertMessage,
  listCseIdentities,
  listCseKeypairs,
  listFilters,
  listForwardingAddresses,
  listHistory,
  listSendAs,
  listSmimeInfo,
  modifyThreadLabels,
  moveThreadToTrash,
  patchLabel,
  patchSendAs,
  searchPeople,
  settingsGetImap,
  settingsGetPop,
  settingsSendAsGet,
  stopWatch,
  untrashThread,
  updateDraft,
  updateImapSettings,
  updateLabel,
  updateLanguageSettings,
  updatePopSettings,
  updateSendAs,
  updateVacationSettings,
  whoAmI,
} from './tools/index.js';

export default defineToolkit({
  id: 'gmail',
  displayName: 'Gmail',
  shortDescription: 'Read, search, draft, send, and organize emails and threads.',
  category: 'Collaboration & Communication',
  icon: GMAIL_ICON,
  auth: {
    type: 'oauth2',
    tokenField: 'gmailToken',
    provider: {
      slug: 'gmail',
      env: { clientId: 'GOOGLE_GMAIL_CLIENT_ID', clientSecret: 'GOOGLE_GMAIL_CLIENT_SECRET' },
      authorizeUrl: 'https://accounts.google.com/o/oauth2/v2/auth',
      tokenUrl: 'https://oauth2.googleapis.com/token',
      scopes: [
        'https://www.googleapis.com/auth/gmail.readonly',
        'https://www.googleapis.com/auth/gmail.send',
        'https://www.googleapis.com/auth/gmail.compose',
        'https://www.googleapis.com/auth/gmail.modify',
        'https://www.googleapis.com/auth/gmail.labels',
        'https://www.googleapis.com/auth/gmail.settings.basic',
        'https://www.googleapis.com/auth/gmail.settings.sharing',
        'https://www.googleapis.com/auth/gmail.insert',
        'https://www.googleapis.com/auth/contacts.readonly',
        'https://www.googleapis.com/auth/contacts.other.readonly',
        'openid',
        'https://www.googleapis.com/auth/userinfo.email',
      ],
      exchangeStyle: 'form',
      extraAuthParams: { access_type: 'offline', prompt: 'consent' },
      connectDescription:
        'Connect Gmail to read, draft, send, search, and organize emails and conversation threads.',
      callbackPath: '/api/auth/gmail/callback',
      stateCookie: 'google_oauth_state',
    },
  },
  allowedHosts: ['gmail.googleapis.com', 'www.googleapis.com', 'people.googleapis.com'],
  tools: [
    defineTool({
      name: 'gmailListMessages',
      tool: listMessages,
      requiredAuth: 'gmailToken',
      scope: 'read',
    }),
    defineTool({
      name: 'gmailGetMessage',
      tool: getMessage,
      requiredAuth: 'gmailToken',
      scope: 'read',
    }),
    defineTool({
      name: 'gmailSendMessage',
      tool: sendMessage,
      requiredAuth: 'gmailToken',
      scope: 'write',
    }),
    defineTool({
      name: 'gmailCreateDraft',
      tool: createDraft,
      requiredAuth: 'gmailToken',
      scope: 'write',
    }),
    defineTool({
      name: 'gmailListDrafts',
      tool: listDrafts,
      requiredAuth: 'gmailToken',
      scope: 'read',
    }),
    defineTool({
      name: 'gmailGetDraft',
      tool: getDraft,
      requiredAuth: 'gmailToken',
      scope: 'read',
    }),
    defineTool({
      name: 'gmailSendDraft',
      tool: sendDraft,
      requiredAuth: 'gmailToken',
      scope: 'write',
    }),
    defineTool({
      name: 'gmailDeleteDraft',
      tool: deleteDraft,
      requiredAuth: 'gmailToken',
      scope: 'delete',
    }),
    defineTool({
      name: 'gmailListThreads',
      tool: listThreads,
      requiredAuth: 'gmailToken',
      scope: 'read',
    }),
    defineTool({
      name: 'gmailGetThread',
      tool: getThread,
      requiredAuth: 'gmailToken',
      scope: 'read',
    }),
    defineTool({
      name: 'gmailReplyToThread',
      tool: replyToThread,
      requiredAuth: 'gmailToken',
      scope: 'write',
    }),
    defineTool({
      name: 'gmailListLabels',
      tool: listLabels,
      requiredAuth: 'gmailToken',
      scope: 'read',
    }),
    defineTool({
      name: 'gmailModifyMessageLabels',
      tool: modifyMessageLabels,
      requiredAuth: 'gmailToken',
      scope: 'write',
    }),
    defineTool({
      name: 'gmailTrashMessage',
      tool: trashMessage,
      requiredAuth: 'gmailToken',
      scope: 'delete',
    }),
    defineTool({
      name: 'gmailUntrashMessage',
      tool: untrashMessage,
      requiredAuth: 'gmailToken',
      scope: 'write',
    }),
    defineTool({
      name: 'gmailBatchDeleteMessages',
      tool: batchDeleteMessages,
      requiredAuth: 'gmailToken',
      scope: 'delete',
    }),
    defineTool({
      name: 'gmailBatchModifyMessages',
      tool: batchModifyMessages,
      requiredAuth: 'gmailToken',
      scope: 'write',
    }),
    defineTool({
      name: 'gmailCreateFilter',
      tool: createFilter,
      requiredAuth: 'gmailToken',
      scope: 'write',
    }),
    defineTool({
      name: 'gmailCreateLabel',
      tool: createLabel,
      requiredAuth: 'gmailToken',
      scope: 'write',
    }),
    defineTool({
      name: 'gmailDeleteFilter',
      tool: deleteFilter,
      requiredAuth: 'gmailToken',
      scope: 'delete',
    }),
    defineTool({
      name: 'gmailDeleteLabel',
      tool: deleteLabel,
      requiredAuth: 'gmailToken',
      scope: 'delete',
    }),
    defineTool({
      name: 'gmailDeleteMessage',
      tool: deleteMessage,
      requiredAuth: 'gmailToken',
      scope: 'delete',
    }),
    defineTool({
      name: 'gmailDeleteThread',
      tool: deleteThread,
      requiredAuth: 'gmailToken',
      scope: 'delete',
    }),
    defineTool({
      name: 'gmailForwardMessage',
      tool: forwardMessage,
      requiredAuth: 'gmailToken',
      scope: 'write',
    }),
    defineTool({
      name: 'gmailGetAttachment',
      tool: getAttachment,
      requiredAuth: 'gmailToken',
      scope: 'read',
    }),
    defineTool({
      name: 'gmailGetAutoForwarding',
      tool: getAutoForwarding,
      requiredAuth: 'gmailToken',
      scope: 'read',
    }),
    defineTool({
      name: 'gmailGetContacts',
      tool: getContacts,
      requiredAuth: 'gmailToken',
      scope: 'read',
    }),
    defineTool({
      name: 'gmailGetFilter',
      tool: getFilter,
      requiredAuth: 'gmailToken',
      scope: 'read',
    }),
    defineTool({
      name: 'gmailFetchEmails',
      tool: fetchEmails,
      requiredAuth: 'gmailToken',
      scope: 'read',
    }),
    defineTool({
      name: 'gmailGetLabel',
      tool: getLabel,
      requiredAuth: 'gmailToken',
      scope: 'read',
    }),
    defineTool({
      name: 'gmailGetLanguageSettings',
      tool: getLanguageSettings,
      requiredAuth: 'gmailToken',
      scope: 'read',
    }),
    defineTool({
      name: 'gmailGetPeople',
      tool: getPeople,
      requiredAuth: 'gmailToken',
      scope: 'read',
    }),
    defineTool({
      name: 'gmailGetProfile',
      tool: getProfile,
      requiredAuth: 'gmailToken',
      scope: 'read',
    }),
    defineTool({
      name: 'gmailGetVacationSettings',
      tool: getVacationSettings,
      requiredAuth: 'gmailToken',
      scope: 'read',
    }),
    defineTool({
      name: 'gmailImportMessage',
      tool: importMessage,
      requiredAuth: 'gmailToken',
      scope: 'write',
    }),
    defineTool({
      name: 'gmailInsertMessage',
      tool: insertMessage,
      requiredAuth: 'gmailToken',
      scope: 'write',
    }),
    defineTool({
      name: 'gmailListCseIdentities',
      tool: listCseIdentities,
      requiredAuth: 'gmailToken',
      scope: 'read',
    }),
    defineTool({
      name: 'gmailListCseKeypairs',
      tool: listCseKeypairs,
      requiredAuth: 'gmailToken',
      scope: 'read',
    }),
    defineTool({
      name: 'gmailListFilters',
      tool: listFilters,
      requiredAuth: 'gmailToken',
      scope: 'read',
    }),
    defineTool({
      name: 'gmailListForwardingAddresses',
      tool: listForwardingAddresses,
      requiredAuth: 'gmailToken',
      scope: 'read',
    }),
    defineTool({
      name: 'gmailListHistory',
      tool: listHistory,
      requiredAuth: 'gmailToken',
      scope: 'read',
    }),
    defineTool({
      name: 'gmailListSendAs',
      tool: listSendAs,
      requiredAuth: 'gmailToken',
      scope: 'read',
    }),
    defineTool({
      name: 'gmailListSmimeInfo',
      tool: listSmimeInfo,
      requiredAuth: 'gmailToken',
      scope: 'read',
    }),
    defineTool({
      name: 'gmailModifyThreadLabels',
      tool: modifyThreadLabels,
      requiredAuth: 'gmailToken',
      scope: 'write',
    }),
    defineTool({
      name: 'gmailMoveThreadToTrash',
      tool: moveThreadToTrash,
      requiredAuth: 'gmailToken',
      scope: 'delete',
    }),
    defineTool({
      name: 'gmailPatchLabel',
      tool: patchLabel,
      requiredAuth: 'gmailToken',
      scope: 'write',
    }),
    defineTool({
      name: 'gmailPatchSendAs',
      tool: patchSendAs,
      requiredAuth: 'gmailToken',
      scope: 'write',
    }),
    defineTool({
      name: 'gmailSearchPeople',
      tool: searchPeople,
      requiredAuth: 'gmailToken',
      scope: 'read',
    }),
    defineTool({
      name: 'gmailSettingsGetImap',
      tool: settingsGetImap,
      requiredAuth: 'gmailToken',
      scope: 'read',
    }),
    defineTool({
      name: 'gmailSettingsGetPop',
      tool: settingsGetPop,
      requiredAuth: 'gmailToken',
      scope: 'read',
    }),
    defineTool({
      name: 'gmailSettingsSendAsGet',
      tool: settingsSendAsGet,
      requiredAuth: 'gmailToken',
      scope: 'read',
    }),
    defineTool({
      name: 'gmailStopWatch',
      tool: stopWatch,
      requiredAuth: 'gmailToken',
      scope: 'delete',
    }),
    defineTool({
      name: 'gmailUntrashThread',
      tool: untrashThread,
      requiredAuth: 'gmailToken',
      scope: 'write',
    }),
    defineTool({
      name: 'gmailUpdateDraft',
      tool: updateDraft,
      requiredAuth: 'gmailToken',
      scope: 'write',
    }),
    defineTool({
      name: 'gmailUpdateImapSettings',
      tool: updateImapSettings,
      requiredAuth: 'gmailToken',
      scope: 'write',
    }),
    defineTool({
      name: 'gmailUpdateLabel',
      tool: updateLabel,
      requiredAuth: 'gmailToken',
      scope: 'write',
    }),
    defineTool({
      name: 'gmailUpdateLanguageSettings',
      tool: updateLanguageSettings,
      requiredAuth: 'gmailToken',
      scope: 'write',
    }),
    defineTool({
      name: 'gmailUpdatePopSettings',
      tool: updatePopSettings,
      requiredAuth: 'gmailToken',
      scope: 'write',
    }),
    defineTool({
      name: 'gmailUpdateSendAs',
      tool: updateSendAs,
      requiredAuth: 'gmailToken',
      scope: 'write',
    }),
    defineTool({
      name: 'gmailUpdateVacationSettings',
      tool: updateVacationSettings,
      requiredAuth: 'gmailToken',
      scope: 'write',
    }),
    defineTool({
      name: 'gmailWhoAmI',
      tool: whoAmI,
      requiredAuth: 'gmailToken',
      scope: 'read',
    }),
  ],
  meta: { since: '0.0.1' },
});
