// @ts-nocheck
import {
  devToCreateArticle,
  devToGetArticle,
  devToGetArticleByPath,
  devToListArticles,
  devToListLatestArticles,
  devToListUserArticles,
  devToListUserPublishedArticles,
  devToListUserUnpublishedArticles,
  devToListUserAllArticles,
  devToListOrganizationArticles,
  devToUpdateArticle,
} from './articles.js';
import {
  devToGetComment,
  devToListComments,
  devToGetCurrentUser,
  devToGetUser,
  devToGetOrganization,
  devToListOrganizationUsers,
  devToGetProfileImage,
  devToListTags,
  devToListFollowedTags,
  devToListFollowers,
  devToListPodcastEpisodes,
  devToListReadingList,
  devToListVideos,
} from './community.js';
import {
  devToGetListing,
  devToListListings,
  devToListListingsByCategory,
  devToUpdateListing,
} from './listings.js';

export {
  devToCreateArticle,
  devToGetArticle,
  devToGetArticleByPath,
  devToListArticles,
  devToListLatestArticles,
  devToListUserArticles,
  devToListUserPublishedArticles,
  devToListUserUnpublishedArticles,
  devToListUserAllArticles,
  devToListOrganizationArticles,
  devToUpdateArticle,
  devToGetComment,
  devToListComments,
  devToGetCurrentUser,
  devToGetUser,
  devToGetOrganization,
  devToListOrganizationUsers,
  devToGetProfileImage,
  devToListTags,
  devToListFollowedTags,
  devToListFollowers,
  devToListPodcastEpisodes,
  devToListReadingList,
  devToListVideos,
  devToGetListing,
  devToListListings,
  devToListListingsByCategory,
  devToUpdateListing,
};

const authed = 'devToApiKey' as const;

export const devToTools = [
  { name: 'devToCreateArticle', description: devToCreateArticle.description!, tool: devToCreateArticle, requiredAuth: authed, scope: 'write' as const },
  { name: 'devToGetArticle', description: devToGetArticle.description!, tool: devToGetArticle, scope: 'read' as const },
  { name: 'devToGetArticleByPath', description: devToGetArticleByPath.description!, tool: devToGetArticleByPath, scope: 'read' as const },
  { name: 'devToListArticles', description: devToListArticles.description!, tool: devToListArticles, scope: 'read' as const },
  { name: 'devToListLatestArticles', description: devToListLatestArticles.description!, tool: devToListLatestArticles, scope: 'read' as const },
  { name: 'devToListUserArticles', description: devToListUserArticles.description!, tool: devToListUserArticles, requiredAuth: authed, scope: 'read' as const },
  { name: 'devToListUserPublishedArticles', description: devToListUserPublishedArticles.description!, tool: devToListUserPublishedArticles, requiredAuth: authed, scope: 'read' as const },
  { name: 'devToListUserUnpublishedArticles', description: devToListUserUnpublishedArticles.description!, tool: devToListUserUnpublishedArticles, requiredAuth: authed, scope: 'read' as const },
  { name: 'devToListUserAllArticles', description: devToListUserAllArticles.description!, tool: devToListUserAllArticles, requiredAuth: authed, scope: 'read' as const },
  { name: 'devToListOrganizationArticles', description: devToListOrganizationArticles.description!, tool: devToListOrganizationArticles, scope: 'read' as const },
  { name: 'devToUpdateArticle', description: devToUpdateArticle.description!, tool: devToUpdateArticle, requiredAuth: authed, scope: 'write' as const },
  { name: 'devToGetComment', description: devToGetComment.description!, tool: devToGetComment, scope: 'read' as const },
  { name: 'devToListComments', description: devToListComments.description!, tool: devToListComments, scope: 'read' as const },
  { name: 'devToGetCurrentUser', description: devToGetCurrentUser.description!, tool: devToGetCurrentUser, requiredAuth: authed, scope: 'read' as const },
  { name: 'devToGetUser', description: devToGetUser.description!, tool: devToGetUser, scope: 'read' as const },
  { name: 'devToGetOrganization', description: devToGetOrganization.description!, tool: devToGetOrganization, scope: 'read' as const },
  { name: 'devToListOrganizationUsers', description: devToListOrganizationUsers.description!, tool: devToListOrganizationUsers, scope: 'read' as const },
  { name: 'devToGetProfileImage', description: devToGetProfileImage.description!, tool: devToGetProfileImage, scope: 'read' as const },
  { name: 'devToListTags', description: devToListTags.description!, tool: devToListTags, scope: 'read' as const },
  { name: 'devToListFollowedTags', description: devToListFollowedTags.description!, tool: devToListFollowedTags, requiredAuth: authed, scope: 'read' as const },
  { name: 'devToListFollowers', description: devToListFollowers.description!, tool: devToListFollowers, requiredAuth: authed, scope: 'read' as const },
  { name: 'devToListPodcastEpisodes', description: devToListPodcastEpisodes.description!, tool: devToListPodcastEpisodes, scope: 'read' as const },
  { name: 'devToListReadingList', description: devToListReadingList.description!, tool: devToListReadingList, requiredAuth: authed, scope: 'read' as const },
  { name: 'devToListVideos', description: devToListVideos.description!, tool: devToListVideos, scope: 'read' as const },
  { name: 'devToGetListing', description: devToGetListing.description!, tool: devToGetListing, scope: 'read' as const },
  { name: 'devToListListings', description: devToListListings.description!, tool: devToListListings, scope: 'read' as const },
  { name: 'devToListListingsByCategory', description: devToListListingsByCategory.description!, tool: devToListListingsByCategory, scope: 'read' as const },
  { name: 'devToUpdateListing', description: devToUpdateListing.description!, tool: devToUpdateListing, requiredAuth: authed, scope: 'write' as const },
];
