// @ts-nocheck
import {
  devToCreateArticle,
  devToGetArticle,
  devToGetArticleByPath,
  devToListArticles,
  devToListLatestArticles,
  devToListUserArticles,
  devToListUserPublishedArticles,
  devToListUserUnpublishedArticles,
  devToListUserAllArticles,
  devToListOrganizationArticles,
  devToUpdateArticle,
} from './articles.js';
import {
  devToGetComment,
  devToListComments,
  devToGetCurrentUser,
  devToGetUser,
  devToGetOrganization,
  devToListOrganizationUsers,
  devToGetProfileImage,
  devToListTags,
  devToListFollowedTags,
  devToListFollowers,
  devToListPodcastEpisodes,
  devToListReadingList,
  devToListVideos,
} from './community.js';
import {
  devToGetListing,
  devToListListings,
  devToListListingsByCategory,
  devToUpdateListing,
} from './listings.js';

export {
  devToCreateArticle,
  devToGetArticle,
  devToGetArticleByPath,
  devToListArticles,
  devToListLatestArticles,
  devToListUserArticles,
  devToListUserPublishedArticles,
  devToListUserUnpublishedArticles,
  devToListUserAllArticles,
  devToListOrganizationArticles,
  devToUpdateArticle,
  devToGetComment,
  devToListComments,
  devToGetCurrentUser,
  devToGetUser,
  devToGetOrganization,
  devToListOrganizationUsers,
  devToGetProfileImage,
  devToListTags,
  devToListFollowedTags,
  devToListFollowers,
  devToListPodcastEpisodes,
  devToListReadingList,
  devToListVideos,
  devToGetListing,
  devToListListings,
  devToListListingsByCategory,
  devToUpdateListing,
};

const authed = 'devToApiKey' as const;

export const devToTools = [
  {
    name: 'devToCreateArticle',
    description: devToCreateArticle.description!,
    tool: devToCreateArticle,
    requiredAuth: authed,
    scope: 'write' as const,
    keywords: ['post', 'blog'],
  },
  {
    name: 'devToGetArticle',
    description: devToGetArticle.description!,
    tool: devToGetArticle,
    scope: 'read' as const,
    keywords: ['post', 'blog'],
  },
  {
    name: 'devToGetArticleByPath',
    description: devToGetArticleByPath.description!,
    tool: devToGetArticleByPath,
    scope: 'read' as const,
    keywords: ['post', 'slug'],
  },
  {
    name: 'devToListArticles',
    description: devToListArticles.description!,
    tool: devToListArticles,
    scope: 'read' as const,
    keywords: ['posts', 'blog'],
  },
  {
    name: 'devToListLatestArticles',
    description: devToListLatestArticles.description!,
    tool: devToListLatestArticles,
    scope: 'read' as const,
    keywords: ['recent', 'newest', 'posts'],
  },
  {
    name: 'devToListUserArticles',
    description: devToListUserArticles.description!,
    tool: devToListUserArticles,
    requiredAuth: authed,
    scope: 'read' as const,
    keywords: ['posts'],
  },
  {
    name: 'devToListUserPublishedArticles',
    description: devToListUserPublishedArticles.description!,
    tool: devToListUserPublishedArticles,
    requiredAuth: authed,
    scope: 'read' as const,
    keywords: ['posts'],
  },
  {
    name: 'devToListUserUnpublishedArticles',
    description: devToListUserUnpublishedArticles.description!,
    tool: devToListUserUnpublishedArticles,
    requiredAuth: authed,
    scope: 'read' as const,
    keywords: ['drafts', 'posts'],
  },
  {
    name: 'devToListUserAllArticles',
    description: devToListUserAllArticles.description!,
    tool: devToListUserAllArticles,
    requiredAuth: authed,
    scope: 'read' as const,
    keywords: ['posts', 'drafts'],
  },
  {
    name: 'devToListOrganizationArticles',
    description: devToListOrganizationArticles.description!,
    tool: devToListOrganizationArticles,
    scope: 'read' as const,
    keywords: ['posts', 'org'],
  },
  {
    name: 'devToUpdateArticle',
    description: devToUpdateArticle.description!,
    tool: devToUpdateArticle,
    requiredAuth: authed,
    scope: 'write' as const,
    keywords: ['post', 'edit'],
  },
  {
    name: 'devToGetComment',
    description: devToGetComment.description!,
    tool: devToGetComment,
    scope: 'read' as const,
    keywords: ['reply'],
  },
  {
    name: 'devToListComments',
    description: devToListComments.description!,
    tool: devToListComments,
    scope: 'read' as const,
    keywords: ['thread', 'replies'],
  },
  {
    name: 'devToGetCurrentUser',
    description: devToGetCurrentUser.description!,
    tool: devToGetCurrentUser,
    requiredAuth: authed,
    scope: 'read' as const,
    keywords: ['whoami', 'account'],
  },
  {
    name: 'devToGetUser',
    description: devToGetUser.description!,
    tool: devToGetUser,
    scope: 'read' as const,
    keywords: ['profile'],
  },
  {
    name: 'devToGetOrganization',
    description: devToGetOrganization.description!,
    tool: devToGetOrganization,
    scope: 'read' as const,
    keywords: ['org'],
  },
  {
    name: 'devToListOrganizationUsers',
    description: devToListOrganizationUsers.description!,
    tool: devToListOrganizationUsers,
    scope: 'read' as const,
    keywords: ['member', 'org', 'team'],
  },
  {
    name: 'devToGetProfileImage',
    description: devToGetProfileImage.description!,
    tool: devToGetProfileImage,
    scope: 'read' as const,
    keywords: ['avatar', 'photo', 'picture'],
  },
  {
    name: 'devToListTags',
    description: devToListTags.description!,
    tool: devToListTags,
    scope: 'read' as const,
    keywords: ['topics', 'hashtag'],
  },
  {
    name: 'devToListFollowedTags',
    description: devToListFollowedTags.description!,
    tool: devToListFollowedTags,
    requiredAuth: authed,
    scope: 'read' as const,
    keywords: ['following', 'topics'],
  },
  {
    name: 'devToListFollowers',
    description: devToListFollowers.description!,
    tool: devToListFollowers,
    requiredAuth: authed,
    scope: 'read' as const,
    keywords: ['follower'],
  },
  {
    name: 'devToListPodcastEpisodes',
    description: devToListPodcastEpisodes.description!,
    tool: devToListPodcastEpisodes,
    scope: 'read' as const,
    keywords: ['episode', 'audio'],
  },
  {
    name: 'devToListReadingList',
    description: devToListReadingList.description!,
    tool: devToListReadingList,
    requiredAuth: authed,
    scope: 'read' as const,
    keywords: ['bookmarks', 'bookmark'],
  },
  {
    name: 'devToListVideos',
    description: devToListVideos.description!,
    tool: devToListVideos,
    scope: 'read' as const,
    keywords: ['video'],
  },
  {
    name: 'devToGetListing',
    description: devToGetListing.description!,
    tool: devToGetListing,
    scope: 'read' as const,
    keywords: ['classified', 'ad'],
  },
  {
    name: 'devToListListings',
    description: devToListListings.description!,
    tool: devToListListings,
    scope: 'read' as const,
    keywords: ['classified', 'jobs'],
  },
  {
    name: 'devToListListingsByCategory',
    description: devToListListingsByCategory.description!,
    tool: devToListListingsByCategory,
    scope: 'read' as const,
    keywords: ['classified'],
  },
  {
    name: 'devToUpdateListing',
    description: devToUpdateListing.description!,
    tool: devToUpdateListing,
    requiredAuth: authed,
    scope: 'write' as const,
    keywords: ['classified'],
  },
];
