// @ts-nocheck
import { notionAppendBlockChildren } from './append-block-children.js';
import {
  notionAddMultiplePageContent,
  notionAppendCodeBlocks,
  notionAppendLayoutBlocks,
  notionAppendMediaBlocks,
  notionAppendTableBlocks,
  notionAppendTaskBlocks,
  notionAppendTextBlocks,
  notionDeleteBlock,
  notionFetchAllBlockContents,
  notionFetchBlockContents,
  notionFetchBlockMetadata,
  notionReplacePageContent,
  notionUpdateBlock,
} from './blocks.js';
import { notionCreateComment, notionFetchComments, notionRetrieveComment } from './comments.js';
import { notionCreatePage } from './create-page.js';
import {
  notionCreateDatabase,
  notionFetchData,
  notionInsertDatabaseRow,
  notionListDataSourceTemplates,
  notionQueryDataSource,
  notionQueryDatabaseWithFilter,
  notionRetrieveDatabaseProperty,
  notionUpdateDatabaseRow,
  notionUpdateDatabaseSchema,
  notionUpsertDatabaseRows,
} from './databases.js';
import {
  notionCreateFileUpload,
  notionListFileUploads,
  notionRetrieveFileUpload,
  notionSendFileUpload,
} from './file-uploads.js';
import { notionGetDatabase } from './get-database.js';
import { notionGetPage } from './get-page.js';
import { notionListDatabases } from './list-databases.js';
import {
  notionArchivePage,
  notionCreateNotionPage,
  notionDuplicatePage,
  notionFetchRow,
  notionGetPageMarkdown,
  notionGetPageProperty,
  notionInsertRowFromNL,
  notionMovePage,
} from './pages.js';
import { notionQueryDatabase } from './query-database.js';
import { notionSearch } from './search.js';
import { notionUpdatePage } from './update-page.js';
import { notionGetAboutUser, notionListUsers, notionWhoAmI } from './users.js';
import {
  notionCreateView,
  notionCreateViewQuery,
  notionDeleteView,
  notionDeleteViewQuery,
  notionGetViewQueryResults,
  notionListViews,
  notionRetrieveView,
  notionUpdateView,
} from './views.js';

export {
  notionSearch,
  notionListDatabases,
  notionQueryDatabase,
  notionQueryDatabaseWithFilter,
  notionQueryDataSource,
  notionGetPage,
  notionFetchRow,
  notionGetPageMarkdown,
  notionGetPageProperty,
  notionCreatePage,
  notionCreateNotionPage,
  notionInsertRowFromNL,
  notionUpdatePage,
  notionArchivePage,
  notionMovePage,
  notionDuplicatePage,
  notionAppendBlockChildren,
  notionAddMultiplePageContent,
  notionAppendTextBlocks,
  notionAppendCodeBlocks,
  notionAppendTaskBlocks,
  notionAppendMediaBlocks,
  notionAppendLayoutBlocks,
  notionAppendTableBlocks,
  notionReplacePageContent,
  notionDeleteBlock,
  notionUpdateBlock,
  notionFetchBlockContents,
  notionFetchAllBlockContents,
  notionFetchBlockMetadata,
  notionGetDatabase,
  notionCreateDatabase,
  notionUpdateDatabaseSchema,
  notionInsertDatabaseRow,
  notionUpdateDatabaseRow,
  notionUpsertDatabaseRows,
  notionRetrieveDatabaseProperty,
  notionListDataSourceTemplates,
  notionFetchData,
  notionCreateComment,
  notionFetchComments,
  notionRetrieveComment,
  notionListUsers,
  notionGetAboutUser,
  notionWhoAmI,
  notionCreateFileUpload,
  notionListFileUploads,
  notionRetrieveFileUpload,
  notionSendFileUpload,
  notionCreateView,
  notionListViews,
  notionRetrieveView,
  notionUpdateView,
  notionDeleteView,
  notionCreateViewQuery,
  notionGetViewQueryResults,
  notionDeleteViewQuery,
};

type Scope = 'read' | 'write' | 'delete';

function entry(
  name: string,
  description: string,
  toolRef: any,
  scope: Scope,
  keywords: string[] = [],
) {
  return {
    name,
    description,
    tool: toolRef,
    requiredAuth: 'notionToken' as const,
    scope,
    keywords,
  };
}

export const notionTools = [
  entry('notionSearch', notionSearch.description!, notionSearch, 'read', [
    'find',
    'lookup',
    'doc',
    'page',
    'pages',
  ]),
  entry('notionListDatabases', notionListDatabases.description!, notionListDatabases, 'read', [
    'tables',
  ]),
  entry('notionQueryDatabase', notionQueryDatabase.description!, notionQueryDatabase, 'read', [
    'filter',
    'search',
    'table',
    'rows',
  ]),
  entry(
    'notionQueryDatabaseWithFilter',
    notionQueryDatabaseWithFilter.description!,
    notionQueryDatabaseWithFilter,
    'read',
    ['filter', 'table'],
  ),
  entry(
    'notionQueryDataSource',
    notionQueryDataSource.description!,
    notionQueryDataSource,
    'read',
    ['filter', 'table'],
  ),
  entry('notionFetchData', notionFetchData.description!, notionFetchData, 'read', [
    'browse',
    'explore',
  ]),
  entry('notionGetPage', notionGetPage.description!, notionGetPage, 'read', [
    'read',
    'doc',
    'view',
  ]),
  entry('notionFetchRow', notionFetchRow.description!, notionFetchRow, 'read', ['record', 'read']),
  entry(
    'notionGetPageMarkdown',
    notionGetPageMarkdown.description!,
    notionGetPageMarkdown,
    'read',
    ['export', 'md', 'read', 'download'],
  ),
  entry(
    'notionGetPageProperty',
    notionGetPageProperty.description!,
    notionGetPageProperty,
    'read',
    ['field', 'column', 'value'],
  ),
  entry('notionCreatePage', notionCreatePage.description!, notionCreatePage, 'write', [
    'new',
    'doc',
    'note',
  ]),
  entry(
    'notionCreateNotionPage',
    notionCreateNotionPage.description!,
    notionCreateNotionPage,
    'write',
    ['new', 'doc'],
  ),
  entry(
    'notionInsertRowFromNL',
    notionInsertRowFromNL.description!,
    notionInsertRowFromNL,
    'write',
    ['add', 'record', 'table'],
  ),
  entry('notionUpdatePage', notionUpdatePage.description!, notionUpdatePage, 'write', ['edit']),
  entry('notionArchivePage', notionArchivePage.description!, notionArchivePage, 'delete', [
    'delete',
    'trash',
    'remove',
    'restore',
  ]),
  entry('notionMovePage', notionMovePage.description!, notionMovePage, 'write', []),
  entry('notionDuplicatePage', notionDuplicatePage.description!, notionDuplicatePage, 'write', [
    'copy',
    'clone',
  ]),
  entry(
    'notionAppendBlockChildren',
    notionAppendBlockChildren.description!,
    notionAppendBlockChildren,
    'write',
    ['add', 'content'],
  ),
  entry(
    'notionAddMultiplePageContent',
    notionAddMultiplePageContent.description!,
    notionAddMultiplePageContent,
    'write',
    ['bulk', 'add'],
  ),
  entry(
    'notionAppendTextBlocks',
    notionAppendTextBlocks.description!,
    notionAppendTextBlocks,
    'write',
    ['paragraph', 'heading', 'write', 'add'],
  ),
  entry(
    'notionAppendCodeBlocks',
    notionAppendCodeBlocks.description!,
    notionAppendCodeBlocks,
    'write',
    ['snippet', 'add'],
  ),
  entry(
    'notionAppendTaskBlocks',
    notionAppendTaskBlocks.description!,
    notionAppendTaskBlocks,
    'write',
    ['todo', 'checklist', 'add', 'create'],
  ),
  entry(
    'notionAppendMediaBlocks',
    notionAppendMediaBlocks.description!,
    notionAppendMediaBlocks,
    'write',
    ['image', 'video', 'embed', 'add'],
  ),
  entry(
    'notionAppendLayoutBlocks',
    notionAppendLayoutBlocks.description!,
    notionAppendLayoutBlocks,
    'write',
    ['columns', 'add'],
  ),
  entry(
    'notionAppendTableBlocks',
    notionAppendTableBlocks.description!,
    notionAppendTableBlocks,
    'write',
    ['add'],
  ),
  entry(
    'notionReplacePageContent',
    notionReplacePageContent.description!,
    notionReplacePageContent,
    'write',
    ['overwrite', 'rewrite', 'edit'],
  ),
  entry('notionDeleteBlock', notionDeleteBlock.description!, notionDeleteBlock, 'delete', [
    'remove',
    'trash',
  ]),
  entry('notionUpdateBlock', notionUpdateBlock.description!, notionUpdateBlock, 'write', ['edit']),
  entry(
    'notionFetchBlockContents',
    notionFetchBlockContents.description!,
    notionFetchBlockContents,
    'read',
    ['children', 'list', 'read'],
  ),
  entry(
    'notionFetchAllBlockContents',
    notionFetchAllBlockContents.description!,
    notionFetchAllBlockContents,
    'read',
    ['children', 'recursive', 'read'],
  ),
  entry(
    'notionFetchBlockMetadata',
    notionFetchBlockMetadata.description!,
    notionFetchBlockMetadata,
    'read',
    ['info'],
  ),
  entry('notionGetDatabase', notionGetDatabase.description!, notionGetDatabase, 'read', [
    'table',
    'schema',
    'info',
  ]),
  entry('notionCreateDatabase', notionCreateDatabase.description!, notionCreateDatabase, 'write', [
    'table',
    'new',
  ]),
  entry(
    'notionUpdateDatabaseSchema',
    notionUpdateDatabaseSchema.description!,
    notionUpdateDatabaseSchema,
    'write',
    ['columns', 'edit', 'table'],
  ),
  entry(
    'notionInsertDatabaseRow',
    notionInsertDatabaseRow.description!,
    notionInsertDatabaseRow,
    'write',
    ['add', 'record', 'table'],
  ),
  entry(
    'notionUpdateDatabaseRow',
    notionUpdateDatabaseRow.description!,
    notionUpdateDatabaseRow,
    'write',
    ['edit', 'record', 'table'],
  ),
  entry(
    'notionUpsertDatabaseRows',
    notionUpsertDatabaseRows.description!,
    notionUpsertDatabaseRows,
    'write',
    ['sync', 'record', 'table'],
  ),
  entry(
    'notionRetrieveDatabaseProperty',
    notionRetrieveDatabaseProperty.description!,
    notionRetrieveDatabaseProperty,
    'read',
    ['column', 'field', 'schema'],
  ),
  entry(
    'notionListDataSourceTemplates',
    notionListDataSourceTemplates.description!,
    notionListDataSourceTemplates,
    'read',
    ['templates'],
  ),
  entry('notionCreateComment', notionCreateComment.description!, notionCreateComment, 'write', [
    'discussion',
    'reply',
    'feedback',
    'add',
  ]),
  entry('notionFetchComments', notionFetchComments.description!, notionFetchComments, 'read', [
    'discussion',
    'unresolved',
  ]),
  entry(
    'notionRetrieveComment',
    notionRetrieveComment.description!,
    notionRetrieveComment,
    'read',
    ['discussion'],
  ),
  entry('notionListUsers', notionListUsers.description!, notionListUsers, 'read', [
    'members',
    'workspace',
  ]),
  entry('notionGetAboutUser', notionGetAboutUser.description!, notionGetAboutUser, 'read', [
    'profile',
  ]),
  entry('notionWhoAmI', notionWhoAmI.description!, notionWhoAmI, 'read', ['identity', 'bot']),
  entry(
    'notionCreateFileUpload',
    notionCreateFileUpload.description!,
    notionCreateFileUpload,
    'write',
    ['attach', 'upload', 'file'],
  ),
  entry(
    'notionListFileUploads',
    notionListFileUploads.description!,
    notionListFileUploads,
    'read',
    ['attachments'],
  ),
  entry(
    'notionRetrieveFileUpload',
    notionRetrieveFileUpload.description!,
    notionRetrieveFileUpload,
    'read',
    ['attachment'],
  ),
  entry('notionSendFileUpload', notionSendFileUpload.description!, notionSendFileUpload, 'write', [
    'attach',
  ]),
  entry('notionCreateView', notionCreateView.description!, notionCreateView, 'write', [
    'board',
    'kanban',
    'table-view',
    'gallery',
  ]),
  entry('notionListViews', notionListViews.description!, notionListViews, 'read', ['board']),
  entry('notionRetrieveView', notionRetrieveView.description!, notionRetrieveView, 'read', []),
  entry('notionUpdateView', notionUpdateView.description!, notionUpdateView, 'write', ['edit']),
  entry('notionDeleteView', notionDeleteView.description!, notionDeleteView, 'delete', ['remove']),
  entry(
    'notionCreateViewQuery',
    notionCreateViewQuery.description!,
    notionCreateViewQuery,
    'read',
    ['filter', 'query'],
  ),
  entry(
    'notionGetViewQueryResults',
    notionGetViewQueryResults.description!,
    notionGetViewQueryResults,
    'read',
    ['filter', 'results'],
  ),
  entry(
    'notionDeleteViewQuery',
    notionDeleteViewQuery.description!,
    notionDeleteViewQuery,
    'delete',
    ['remove'],
  ),
];
