// @ts-nocheck
import { notionAppendBlockChildren } from './append-block-children.js';
import {
    notionAddMultiplePageContent,
    notionAppendCodeBlocks,
    notionAppendLayoutBlocks,
    notionAppendMediaBlocks,
    notionAppendTableBlocks,
    notionAppendTaskBlocks,
    notionAppendTextBlocks,
    notionDeleteBlock,
    notionFetchAllBlockContents,
    notionFetchBlockContents,
    notionFetchBlockMetadata,
    notionReplacePageContent,
    notionUpdateBlock,
} from './blocks.js';
import { notionCreateComment, notionFetchComments, notionRetrieveComment } from './comments.js';
import { notionCreatePage } from './create-page.js';
import {
    notionCreateDatabase,
    notionFetchData,
    notionInsertDatabaseRow,
    notionListDataSourceTemplates,
    notionQueryDataSource,
    notionQueryDatabaseWithFilter,
    notionRetrieveDatabaseProperty,
    notionUpdateDatabaseRow,
    notionUpdateDatabaseSchema,
    notionUpsertDatabaseRows,
} from './databases.js';
import {
    notionCreateFileUpload,
    notionListFileUploads,
    notionRetrieveFileUpload,
    notionSendFileUpload,
} from './file-uploads.js';
import { notionGetDatabase } from './get-database.js';
import { notionGetPage } from './get-page.js';
import { notionListDatabases } from './list-databases.js';
import {
    notionArchivePage,
    notionCreateNotionPage,
    notionDuplicatePage,
    notionFetchRow,
    notionGetPageMarkdown,
    notionGetPageProperty,
    notionInsertRowFromNL,
    notionMovePage,
} from './pages.js';
import { notionQueryDatabase } from './query-database.js';
import { notionSearch } from './search.js';
import { notionUpdatePage } from './update-page.js';
import { notionGetAboutUser, notionListUsers, notionWhoAmI } from './users.js';
import {
    notionCreateView,
    notionCreateViewQuery,
    notionDeleteView,
    notionDeleteViewQuery,
    notionGetViewQueryResults,
    notionListViews,
    notionRetrieveView,
    notionUpdateView,
} from './views.js';

export {
    notionSearch,
    notionListDatabases,
    notionQueryDatabase,
    notionQueryDatabaseWithFilter,
    notionQueryDataSource,
    notionGetPage,
    notionFetchRow,
    notionGetPageMarkdown,
    notionGetPageProperty,
    notionCreatePage,
    notionCreateNotionPage,
    notionInsertRowFromNL,
    notionUpdatePage,
    notionArchivePage,
    notionMovePage,
    notionDuplicatePage,
    notionAppendBlockChildren,
    notionAddMultiplePageContent,
    notionAppendTextBlocks,
    notionAppendCodeBlocks,
    notionAppendTaskBlocks,
    notionAppendMediaBlocks,
    notionAppendLayoutBlocks,
    notionAppendTableBlocks,
    notionReplacePageContent,
    notionDeleteBlock,
    notionUpdateBlock,
    notionFetchBlockContents,
    notionFetchAllBlockContents,
    notionFetchBlockMetadata,
    notionGetDatabase,
    notionCreateDatabase,
    notionUpdateDatabaseSchema,
    notionInsertDatabaseRow,
    notionUpdateDatabaseRow,
    notionUpsertDatabaseRows,
    notionRetrieveDatabaseProperty,
    notionListDataSourceTemplates,
    notionFetchData,
    notionCreateComment,
    notionFetchComments,
    notionRetrieveComment,
    notionListUsers,
    notionGetAboutUser,
    notionWhoAmI,
    notionCreateFileUpload,
    notionListFileUploads,
    notionRetrieveFileUpload,
    notionSendFileUpload,
    notionCreateView,
    notionListViews,
    notionRetrieveView,
    notionUpdateView,
    notionDeleteView,
    notionCreateViewQuery,
    notionGetViewQueryResults,
    notionDeleteViewQuery,
};

type Scope = 'read' | 'write' | 'delete';

function entry(name: string, description: string, toolRef: any, scope: Scope) {
    return { name, description, tool: toolRef, requiredAuth: 'notionToken' as const, scope };
}

export const notionTools = [
    entry('notionSearch', notionSearch.description!, notionSearch, 'read'),
    entry('notionListDatabases', notionListDatabases.description!, notionListDatabases, 'read'),
    entry('notionQueryDatabase', notionQueryDatabase.description!, notionQueryDatabase, 'read'),
    entry('notionQueryDatabaseWithFilter', notionQueryDatabaseWithFilter.description!, notionQueryDatabaseWithFilter, 'read'),
    entry('notionQueryDataSource', notionQueryDataSource.description!, notionQueryDataSource, 'read'),
    entry('notionFetchData', notionFetchData.description!, notionFetchData, 'read'),
    entry('notionGetPage', notionGetPage.description!, notionGetPage, 'read'),
    entry('notionFetchRow', notionFetchRow.description!, notionFetchRow, 'read'),
    entry('notionGetPageMarkdown', notionGetPageMarkdown.description!, notionGetPageMarkdown, 'read'),
    entry('notionGetPageProperty', notionGetPageProperty.description!, notionGetPageProperty, 'read'),
    entry('notionCreatePage', notionCreatePage.description!, notionCreatePage, 'write'),
    entry('notionCreateNotionPage', notionCreateNotionPage.description!, notionCreateNotionPage, 'write'),
    entry('notionInsertRowFromNL', notionInsertRowFromNL.description!, notionInsertRowFromNL, 'write'),
    entry('notionUpdatePage', notionUpdatePage.description!, notionUpdatePage, 'write'),
    entry('notionArchivePage', notionArchivePage.description!, notionArchivePage, 'delete'),
    entry('notionMovePage', notionMovePage.description!, notionMovePage, 'write'),
    entry('notionDuplicatePage', notionDuplicatePage.description!, notionDuplicatePage, 'write'),
    entry('notionAppendBlockChildren', notionAppendBlockChildren.description!, notionAppendBlockChildren, 'write'),
    entry('notionAddMultiplePageContent', notionAddMultiplePageContent.description!, notionAddMultiplePageContent, 'write'),
    entry('notionAppendTextBlocks', notionAppendTextBlocks.description!, notionAppendTextBlocks, 'write'),
    entry('notionAppendCodeBlocks', notionAppendCodeBlocks.description!, notionAppendCodeBlocks, 'write'),
    entry('notionAppendTaskBlocks', notionAppendTaskBlocks.description!, notionAppendTaskBlocks, 'write'),
    entry('notionAppendMediaBlocks', notionAppendMediaBlocks.description!, notionAppendMediaBlocks, 'write'),
    entry('notionAppendLayoutBlocks', notionAppendLayoutBlocks.description!, notionAppendLayoutBlocks, 'write'),
    entry('notionAppendTableBlocks', notionAppendTableBlocks.description!, notionAppendTableBlocks, 'write'),
    entry('notionReplacePageContent', notionReplacePageContent.description!, notionReplacePageContent, 'write'),
    entry('notionDeleteBlock', notionDeleteBlock.description!, notionDeleteBlock, 'delete'),
    entry('notionUpdateBlock', notionUpdateBlock.description!, notionUpdateBlock, 'write'),
    entry('notionFetchBlockContents', notionFetchBlockContents.description!, notionFetchBlockContents, 'read'),
    entry('notionFetchAllBlockContents', notionFetchAllBlockContents.description!, notionFetchAllBlockContents, 'read'),
    entry('notionFetchBlockMetadata', notionFetchBlockMetadata.description!, notionFetchBlockMetadata, 'read'),
    entry('notionGetDatabase', notionGetDatabase.description!, notionGetDatabase, 'read'),
    entry('notionCreateDatabase', notionCreateDatabase.description!, notionCreateDatabase, 'write'),
    entry('notionUpdateDatabaseSchema', notionUpdateDatabaseSchema.description!, notionUpdateDatabaseSchema, 'write'),
    entry('notionInsertDatabaseRow', notionInsertDatabaseRow.description!, notionInsertDatabaseRow, 'write'),
    entry('notionUpdateDatabaseRow', notionUpdateDatabaseRow.description!, notionUpdateDatabaseRow, 'write'),
    entry('notionUpsertDatabaseRows', notionUpsertDatabaseRows.description!, notionUpsertDatabaseRows, 'write'),
    entry('notionRetrieveDatabaseProperty', notionRetrieveDatabaseProperty.description!, notionRetrieveDatabaseProperty, 'read'),
    entry('notionListDataSourceTemplates', notionListDataSourceTemplates.description!, notionListDataSourceTemplates, 'read'),
    entry('notionCreateComment', notionCreateComment.description!, notionCreateComment, 'write'),
    entry('notionFetchComments', notionFetchComments.description!, notionFetchComments, 'read'),
    entry('notionRetrieveComment', notionRetrieveComment.description!, notionRetrieveComment, 'read'),
    entry('notionListUsers', notionListUsers.description!, notionListUsers, 'read'),
    entry('notionGetAboutUser', notionGetAboutUser.description!, notionGetAboutUser, 'read'),
    entry('notionWhoAmI', notionWhoAmI.description!, notionWhoAmI, 'read'),
    entry('notionCreateFileUpload', notionCreateFileUpload.description!, notionCreateFileUpload, 'write'),
    entry('notionListFileUploads', notionListFileUploads.description!, notionListFileUploads, 'read'),
    entry('notionRetrieveFileUpload', notionRetrieveFileUpload.description!, notionRetrieveFileUpload, 'read'),
    entry('notionSendFileUpload', notionSendFileUpload.description!, notionSendFileUpload, 'write'),
    entry('notionCreateView', notionCreateView.description!, notionCreateView, 'write'),
    entry('notionListViews', notionListViews.description!, notionListViews, 'read'),
    entry('notionRetrieveView', notionRetrieveView.description!, notionRetrieveView, 'read'),
    entry('notionUpdateView', notionUpdateView.description!, notionUpdateView, 'write'),
    entry('notionDeleteView', notionDeleteView.description!, notionDeleteView, 'delete'),
    entry('notionCreateViewQuery', notionCreateViewQuery.description!, notionCreateViewQuery, 'read'),
    entry('notionGetViewQueryResults', notionGetViewQueryResults.description!, notionGetViewQueryResults, 'read'),
    entry('notionDeleteViewQuery', notionDeleteViewQuery.description!, notionDeleteViewQuery, 'delete'),
];
