// @ts-nocheck
import { coinbaseGetAssetDetails, coinbaseGetSupportedNetworks, coinbaseListAssets } from './intx-assets.js';
import {
  coinbaseGetDailyTradingVolume,
  coinbaseGetInstrumentDetails,
  coinbaseGetInstrumentFunding,
  coinbaseGetInstrumentQuote,
  coinbaseListInstrumentCandles,
  coinbaseListInstruments,
} from './intx-instruments.js';
import {
  coinbaseGetExchangeCurrency,
  coinbaseGetWrappedAssetConversionRate,
  coinbaseListCurrencies,
  coinbaseListLoanAssets,
  coinbaseListWrappedAssets,
} from './exchange-reference.js';
import {
  coinbaseGetProductBook,
  coinbaseGetProductDetails,
  coinbaseGetProductTicker,
  coinbaseGetProductsVolumeSummary,
  coinbaseListExchangeProducts,
  coinbaseListProductStats,
  coinbaseListProductTrades,
  coinbaseListProductsCandles,
} from './exchange-products.js';
import {
  coinbaseGetMarketProductBook,
  coinbaseGetPublicMarketTrades,
  coinbaseGetServerTime,
  coinbaseListMarketProducts,
  coinbaseListProductCandles,
} from './advanced-trade.js';
import { coinbaseListWallets } from './wallets.js';

export {
  coinbaseGetAssetDetails,
  coinbaseGetSupportedNetworks,
  coinbaseListAssets,
  coinbaseGetDailyTradingVolume,
  coinbaseGetInstrumentDetails,
  coinbaseGetInstrumentFunding,
  coinbaseGetInstrumentQuote,
  coinbaseListInstrumentCandles,
  coinbaseListInstruments,
  coinbaseGetExchangeCurrency,
  coinbaseGetWrappedAssetConversionRate,
  coinbaseListCurrencies,
  coinbaseListLoanAssets,
  coinbaseListWrappedAssets,
  coinbaseGetProductBook,
  coinbaseGetProductDetails,
  coinbaseGetProductTicker,
  coinbaseGetProductsVolumeSummary,
  coinbaseListExchangeProducts,
  coinbaseListProductStats,
  coinbaseListProductTrades,
  coinbaseListProductsCandles,
  coinbaseGetMarketProductBook,
  coinbaseGetPublicMarketTrades,
  coinbaseGetServerTime,
  coinbaseListMarketProducts,
  coinbaseListProductCandles,
  coinbaseListWallets,
};

const authed = { requiredAuth: 'coinbaseCredentials' as const };

export const coinbaseTools = [
  {
    name: 'coinbaseListAssets',
    description: coinbaseListAssets.description!,
    tool: coinbaseListAssets,
    scope: 'read' as const,
    keywords: ['collateral', 'borrowable assets'],
  },
  {
    name: 'coinbaseGetAssetDetails',
    description: coinbaseGetAssetDetails.description!,
    tool: coinbaseGetAssetDetails,
    scope: 'read' as const,
    keywords: ['collateral weight'],
  },
  {
    name: 'coinbaseGetSupportedNetworks',
    description: coinbaseGetSupportedNetworks.description!,
    tool: coinbaseGetSupportedNetworks,
    scope: 'read' as const,
    keywords: ['deposit networks', 'withdrawal networks', 'blockchain'],
  },
  {
    name: 'coinbaseListInstruments',
    description: coinbaseListInstruments.description!,
    tool: coinbaseListInstruments,
    scope: 'read' as const,
    keywords: ['perpetuals', 'perps', 'futures', 'trading pairs'],
  },
  {
    name: 'coinbaseGetInstrumentDetails',
    description: coinbaseGetInstrumentDetails.description!,
    tool: coinbaseGetInstrumentDetails,
    scope: 'read' as const,
    keywords: ['trading parameters'],
  },
  {
    name: 'coinbaseGetInstrumentQuote',
    description: coinbaseGetInstrumentQuote.description!,
    tool: coinbaseGetInstrumentQuote,
    scope: 'read' as const,
    keywords: ['bid ask', 'mark price', 'spot price'],
  },
  {
    name: 'coinbaseGetInstrumentFunding',
    description: coinbaseGetInstrumentFunding.description!,
    tool: coinbaseGetInstrumentFunding,
    scope: 'read' as const,
    keywords: ['funding rate history', 'perp funding'],
  },
  {
    name: 'coinbaseListInstrumentCandles',
    description: coinbaseListInstrumentCandles.description!,
    tool: coinbaseListInstrumentCandles,
    scope: 'read' as const,
    keywords: ['ohlcv', 'price history', 'candlesticks', 'chart data'],
  },
  {
    name: 'coinbaseGetDailyTradingVolume',
    description: coinbaseGetDailyTradingVolume.description!,
    tool: coinbaseGetDailyTradingVolume,
    scope: 'read' as const,
    keywords: ['volume history'],
  },
  {
    name: 'coinbaseGetExchangeCurrency',
    description: coinbaseGetExchangeCurrency.description!,
    tool: coinbaseGetExchangeCurrency,
    scope: 'read' as const,
    keywords: [],
  },
  {
    name: 'coinbaseListCurrencies',
    description: coinbaseListCurrencies.description!,
    tool: coinbaseListCurrencies,
    scope: 'read' as const,
    keywords: ['fiat', 'cryptocurrencies'],
  },
  {
    name: 'coinbaseListLoanAssets',
    description: coinbaseListLoanAssets.description!,
    tool: coinbaseListLoanAssets,
    ...authed,
    scope: 'read' as const,
    keywords: ['borrow', 'collateral', 'lending'],
  },
  {
    name: 'coinbaseListWrappedAssets',
    description: coinbaseListWrappedAssets.description!,
    tool: coinbaseListWrappedAssets,
    scope: 'read' as const,
    keywords: ['cbeth'],
  },
  {
    name: 'coinbaseGetWrappedAssetConversionRate',
    description: coinbaseGetWrappedAssetConversionRate.description!,
    tool: coinbaseGetWrappedAssetConversionRate,
    scope: 'read' as const,
    keywords: ['cbeth price', 'exchange ratio'],
  },
  {
    name: 'coinbaseListExchangeProducts',
    description: coinbaseListExchangeProducts.description!,
    tool: coinbaseListExchangeProducts,
    scope: 'read' as const,
    keywords: ['trading pairs', 'markets'],
  },
  {
    name: 'coinbaseGetProductDetails',
    description: coinbaseGetProductDetails.description!,
    tool: coinbaseGetProductDetails,
    scope: 'read' as const,
    keywords: ['pair info'],
  },
  {
    name: 'coinbaseGetProductBook',
    description: coinbaseGetProductBook.description!,
    tool: coinbaseGetProductBook,
    scope: 'read' as const,
    keywords: ['orderbook', 'market depth', 'bids asks'],
  },
  {
    name: 'coinbaseGetProductTicker',
    description: coinbaseGetProductTicker.description!,
    tool: coinbaseGetProductTicker,
    scope: 'read' as const,
    keywords: ['last price', 'quote'],
  },
  {
    name: 'coinbaseListProductStats',
    description: coinbaseListProductStats.description!,
    tool: coinbaseListProductStats,
    scope: 'read' as const,
    keywords: ['24h stats', 'high low'],
  },
  {
    name: 'coinbaseListProductTrades',
    description: coinbaseListProductTrades.description!,
    tool: coinbaseListProductTrades,
    scope: 'read' as const,
    keywords: ['trade history'],
  },
  {
    name: 'coinbaseListProductsCandles',
    description: coinbaseListProductsCandles.description!,
    tool: coinbaseListProductsCandles,
    scope: 'read' as const,
    keywords: ['ohlc', 'chart'],
  },
  {
    name: 'coinbaseGetProductsVolumeSummary',
    description: coinbaseGetProductsVolumeSummary.description!,
    tool: coinbaseGetProductsVolumeSummary,
    scope: 'read' as const,
    keywords: ['volumes'],
  },
  {
    name: 'coinbaseGetServerTime',
    description: coinbaseGetServerTime.description!,
    tool: coinbaseGetServerTime,
    scope: 'read' as const,
    keywords: ['clock', 'timestamp', 'epoch'],
  },
  {
    name: 'coinbaseListMarketProducts',
    description: coinbaseListMarketProducts.description!,
    tool: coinbaseListMarketProducts,
    scope: 'read' as const,
    keywords: ['advanced trade'],
  },
  {
    name: 'coinbaseGetMarketProductBook',
    description: coinbaseGetMarketProductBook.description!,
    tool: coinbaseGetMarketProductBook,
    scope: 'read' as const,
    keywords: ['advanced trade orderbook'],
  },
  {
    name: 'coinbaseGetPublicMarketTrades',
    description: coinbaseGetPublicMarketTrades.description!,
    tool: coinbaseGetPublicMarketTrades,
    scope: 'read' as const,
    keywords: ['recent trades'],
  },
  {
    name: 'coinbaseListProductCandles',
    description: coinbaseListProductCandles.description!,
    tool: coinbaseListProductCandles,
    scope: 'read' as const,
    keywords: ['candlesticks'],
  },
  {
    name: 'coinbaseListWallets',
    description: coinbaseListWallets.description!,
    tool: coinbaseListWallets,
    ...authed,
    scope: 'read' as const,
    keywords: ['accounts', 'balances', 'portfolio'],
  },
];
