// @ts-nocheck
import {
  xCreatePost,
  xDeletePost,
  xLookupPost,
  xLookupPosts,
  xRecentSearch,
  xFullArchiveSearch,
  xRecentCounts,
  xFullArchiveCounts,
  xPostAnalytics,
  xPostUsage,
  xHideReply,
  xQuotePosts,
  xStreamLabels,
} from './posts.js';
import {
  xLikePost,
  xUnlikePost,
  xListLikers,
  xLikedPosts,
  xRetweetPost,
  xUnretweetPost,
  xReposters,
  xReposts,
  xFollowUser,
  xUnfollowUser,
  xFollowers,
  xFollowing,
  xBlockedUsers,
  xMutedUsers,
  xMuteUser,
  xUnmuteUser,
} from './interactions.js';
import {
  xGetUserById,
  xGetUsersByIds,
  xLookupUserByUsername,
  xLookupUsersByUsernames,
  xLookupMe,
  xHomeTimeline,
} from './users.js';
import { xGetBookmarks, xAddBookmark, xRemoveBookmark } from './bookmarks.js';
import {
  xCreateList,
  xGetList,
  xUpdateList,
  xDeleteList,
  xAddListMember,
  xRemoveListMember,
  xListMembers,
  xListFollowers,
  xFollowList,
  xUnfollowList,
  xPinList,
  xUnpinList,
  xOwnedLists,
  xFollowedLists,
  xListMemberships,
  xPinnedLists,
  xListTimeline,
} from './lists.js';
import {
  xGetSpace,
  xGetSpacesByIds,
  xSpacesByCreators,
  xSearchSpaces,
  xSpaceBuyers,
  xSpacePosts,
} from './spaces.js';
import {
  xCreateDmConversation,
  xSendDmToConversation,
  xSendDmToUser,
  xDmEventsByParticipant,
  xDmEventsByConversation,
  xRecentDmEvents,
  xGetDmEvent,
  xDeleteDm,
} from './dms.js';
import {
  xInitMediaUpload,
  xAppendMediaUpload,
  xMediaUploadStatus,
  xUploadMedia,
  xUploadLargeMedia,
} from './media.js';
import { xCreateComplianceJob, xGetComplianceJob, xListComplianceJobs } from './compliance.js';
import { xCreateActivitySubscription, xGetOpenApiSpec } from './misc.js';

export {
  xCreatePost,
  xDeletePost,
  xLookupPost,
  xLookupPosts,
  xRecentSearch,
  xFullArchiveSearch,
  xRecentCounts,
  xFullArchiveCounts,
  xPostAnalytics,
  xPostUsage,
  xHideReply,
  xQuotePosts,
  xStreamLabels,
  xLikePost,
  xUnlikePost,
  xListLikers,
  xLikedPosts,
  xRetweetPost,
  xUnretweetPost,
  xReposters,
  xReposts,
  xFollowUser,
  xUnfollowUser,
  xFollowers,
  xFollowing,
  xBlockedUsers,
  xMutedUsers,
  xMuteUser,
  xUnmuteUser,
  xGetUserById,
  xGetUsersByIds,
  xLookupUserByUsername,
  xLookupUsersByUsernames,
  xLookupMe,
  xHomeTimeline,
  xGetBookmarks,
  xAddBookmark,
  xRemoveBookmark,
  xCreateList,
  xGetList,
  xUpdateList,
  xDeleteList,
  xAddListMember,
  xRemoveListMember,
  xListMembers,
  xListFollowers,
  xFollowList,
  xUnfollowList,
  xPinList,
  xUnpinList,
  xOwnedLists,
  xFollowedLists,
  xListMemberships,
  xPinnedLists,
  xListTimeline,
  xGetSpace,
  xGetSpacesByIds,
  xSpacesByCreators,
  xSearchSpaces,
  xSpaceBuyers,
  xSpacePosts,
  xCreateDmConversation,
  xSendDmToConversation,
  xSendDmToUser,
  xDmEventsByParticipant,
  xDmEventsByConversation,
  xRecentDmEvents,
  xGetDmEvent,
  xDeleteDm,
  xInitMediaUpload,
  xAppendMediaUpload,
  xMediaUploadStatus,
  xUploadMedia,
  xUploadLargeMedia,
  xCreateComplianceJob,
  xGetComplianceJob,
  xListComplianceJobs,
  xCreateActivitySubscription,
  xGetOpenApiSpec,
};

const AUTH = 'xToken' as const;

export const xTools = [
  {
    name: 'xCreatePost',
    description: 'Create a new post (tweet) on X: text, polls, media, quotes, replies, geo.',
    tool: xCreatePost,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['tweet', 'publish', 'share', 'compose'],
  },
  {
    name: 'xDeletePost',
    description: 'Delete a post owned by the authenticated user by post ID.',
    tool: xDeletePost,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['tweet', 'remove', 'destroy'],
  },
  {
    name: 'xLookupPost',
    description: 'Look up a single post by ID with expansions and field selections.',
    tool: xLookupPost,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['tweet', 'fetch', 'retrieve'],
  },
  {
    name: 'xLookupPosts',
    description: 'Look up up to 100 posts by IDs in one request.',
    tool: xLookupPosts,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['tweets', 'batch', 'bulk'],
  },
  {
    name: 'xRecentSearch',
    description: 'Search posts from the last 7 days: conversations, mentions, hashtags.',
    tool: xRecentSearch,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['tweets', 'query', 'find'],
  },
  {
    name: 'xFullArchiveSearch',
    description: 'Search the full archive of public posts by query.',
    tool: xFullArchiveSearch,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['tweets', 'history', 'query'],
  },
  {
    name: 'xRecentCounts',
    description: 'Count posts from the last 7 days matching a query over time.',
    tool: xRecentCounts,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['tweets', 'volume', 'timeseries'],
  },
  {
    name: 'xFullArchiveCounts',
    description: 'Count posts across the full archive matching a query over time.',
    tool: xFullArchiveCounts,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['tweets', 'volume', 'history'],
  },
  {
    name: 'xPostAnalytics',
    description: 'Engagement analytics for posts over a time range: impressions, likes, replies.',
    tool: xPostAnalytics,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['tweets', 'metrics', 'insights', 'engagement'],
  },
  {
    name: 'xPostUsage',
    description: 'X API tweet usage stats for the project: consumption, caps, daily breakdowns.',
    tool: xPostUsage,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['tweets', 'limits', 'quota', 'usage'],
  },
  {
    name: 'xHideReply',
    description: 'Hide or unhide a reply to your own conversation (tweet.moderate.write).',
    tool: xHideReply,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['tweet', 'moderate', 'conceal'],
  },
  {
    name: 'xQuotePosts',
    description: 'Get posts that quote a specific post.',
    tool: xQuotePosts,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['tweets', 'quoting', 'citations'],
  },
  {
    name: 'xStreamLabels',
    description: 'Stream labeling events applied to posts (compliance label stream).',
    tool: xStreamLabels,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['tweets', 'compliance', 'moderation'],
  },
  {
    name: 'xLikePost',
    description: 'Like a post on behalf of the authenticated user.',
    tool: xLikePost,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['tweet', 'favorite', 'heart'],
  },
  {
    name: 'xUnlikePost',
    description: 'Unlike a post on behalf of the authenticated user.',
    tool: xUnlikePost,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['tweet', 'unfavorite', 'remove'],
  },
  {
    name: 'xListLikers',
    description: 'Get users who liked a specific post.',
    tool: xListLikers,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['tweet', 'liking users', 'fans'],
  },
  {
    name: 'xLikedPosts',
    description: 'Get posts liked by a user ID.',
    tool: xLikedPosts,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['tweets', 'favorites', 'likes'],
  },
  {
    name: 'xRetweetPost',
    description: 'Repost (retweet) a post on behalf of the authenticated user.',
    tool: xRetweetPost,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['tweet', 'repost', 'share'],
  },
  {
    name: 'xUnretweetPost',
    description: 'Undo a repost by source post ID.',
    tool: xUnretweetPost,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['tweet', 'remove', 'undo'],
  },
  {
    name: 'xReposters',
    description: 'Get users who reposted a specific post.',
    tool: xReposters,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['tweet', 'retweeters', 'sharers'],
  },
  {
    name: 'xReposts',
    description: 'Get reposts of a specific post with post objects.',
    tool: xReposts,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['tweet', 'retweets', 'shares'],
  },
  {
    name: 'xFollowUser',
    description: 'Follow a user on behalf of the authenticated user.',
    tool: xFollowUser,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['subscribe', 'add'],
  },
  {
    name: 'xUnfollowUser',
    description: 'Unfollow a user on behalf of the authenticated user.',
    tool: xUnfollowUser,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['remove', 'leave'],
  },
  {
    name: 'xFollowers',
    description: 'Get followers of a user by user ID.',
    tool: xFollowers,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['fans', 'audience', 'subscribers'],
  },
  {
    name: 'xFollowing',
    description: 'Get accounts a user is following by user ID.',
    tool: xFollowing,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['followees', 'friends', 'subscriptions'],
  },
  {
    name: 'xBlockedUsers',
    description: 'Get accounts blocked by the authenticated user.',
    tool: xBlockedUsers,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['blocklist', 'banned'],
  },
  {
    name: 'xMutedUsers',
    description: 'Get accounts muted by the authenticated user.',
    tool: xMutedUsers,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['mutelist', 'silenced'],
  },
  {
    name: 'xMuteUser',
    description: 'Mute a user on behalf of the authenticated user.',
    tool: xMuteUser,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['silence', 'hide'],
  },
  {
    name: 'xUnmuteUser',
    description: 'Unmute a user on behalf of the authenticated user.',
    tool: xUnmuteUser,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['unsilence', 'restore'],
  },
  {
    name: 'xGetUserById',
    description: 'Get a user profile by user ID.',
    tool: xGetUserById,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['account', 'profile', 'fetch'],
  },
  {
    name: 'xLookupUserByUsername',
    description: 'Get a user profile by username (without @).',
    tool: xLookupUserByUsername,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['account', 'handle', 'profile'],
  },
  {
    name: 'xGetUsersByIds',
    description: 'Get up to 100 user profiles by IDs in one request.',
    tool: xGetUsersByIds,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['accounts', 'batch', 'bulk'],
  },
  {
    name: 'xLookupUsersByUsernames',
    description: 'Get up to 100 user profiles by usernames in one request.',
    tool: xLookupUsersByUsernames,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['accounts', 'handles', 'batch'],
  },
  {
    name: 'xLookupMe',
    description: 'Get the authenticated user profile and ID.',
    tool: xLookupMe,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['account', 'myself', 'whoami'],
  },
  {
    name: 'xHomeTimeline',
    description: 'Reverse-chronological home timeline of the authenticated user.',
    tool: xHomeTimeline,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['feed', 'tweets', 'timeline'],
  },
  {
    name: 'xGetBookmarks',
    description: 'Get posts bookmarked by the authenticated user.',
    tool: xGetBookmarks,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['tweets', 'saved', 'favorites'],
  },
  {
    name: 'xAddBookmark',
    description: 'Add a post to the authenticated user bookmarks.',
    tool: xAddBookmark,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['tweet', 'save'],
  },
  {
    name: 'xRemoveBookmark',
    description: 'Remove a post from the authenticated user bookmarks.',
    tool: xRemoveBookmark,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['tweet', 'unsave'],
  },
  {
    name: 'xCreateList',
    description: 'Create a new List owned by the authenticated user.',
    tool: xCreateList,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['twitter list', 'curate'],
  },
  {
    name: 'xGetList',
    description: 'Get a List by ID.',
    tool: xGetList,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['twitter list', 'fetch'],
  },
  {
    name: 'xUpdateList',
    description: 'Update a List name, description, or privacy.',
    tool: xUpdateList,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['twitter list', 'edit', 'rename'],
  },
  {
    name: 'xDeleteList',
    description: 'Delete a List owned by the authenticated user.',
    tool: xDeleteList,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['twitter list', 'remove'],
  },
  {
    name: 'xAddListMember',
    description: 'Add a user to a List you own.',
    tool: xAddListMember,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['twitter list', 'member', 'invite'],
  },
  {
    name: 'xRemoveListMember',
    description: 'Remove a user from a List you own.',
    tool: xRemoveListMember,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['twitter list', 'member', 'kick'],
  },
  {
    name: 'xListMembers',
    description: 'Get members of a List.',
    tool: xListMembers,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['twitter list', 'membership'],
  },
  {
    name: 'xListFollowers',
    description: 'Get followers of a List.',
    tool: xListFollowers,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['twitter list', 'subscribers'],
  },
  {
    name: 'xFollowList',
    description: 'Follow a List on behalf of the authenticated user.',
    tool: xFollowList,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['twitter list', 'subscribe'],
  },
  {
    name: 'xUnfollowList',
    description: 'Unfollow a List on behalf of the authenticated user.',
    tool: xUnfollowList,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['twitter list', 'unsubscribe'],
  },
  {
    name: 'xPinList',
    description: 'Pin a List to the authenticated user profile.',
    tool: xPinList,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['twitter list', 'feature'],
  },
  {
    name: 'xUnpinList',
    description: 'Unpin a List from the authenticated user profile.',
    tool: xUnpinList,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['twitter list', 'unfeature'],
  },
  {
    name: 'xOwnedLists',
    description: 'Get Lists owned by a user.',
    tool: xOwnedLists,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['twitter lists', 'created'],
  },
  {
    name: 'xFollowedLists',
    description: 'Get Lists followed by a user.',
    tool: xFollowedLists,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['twitter lists', 'subscriptions'],
  },
  {
    name: 'xListMemberships',
    description: 'Get Lists a user is a member of.',
    tool: xListMemberships,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['twitter lists', 'membership'],
  },
  {
    name: 'xPinnedLists',
    description: 'Get Lists pinned by a user.',
    tool: xPinnedLists,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['twitter lists', 'featured'],
  },
  {
    name: 'xListTimeline',
    description: 'Get the timeline of posts from a List by List ID.',
    tool: xListTimeline,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['twitter list', 'tweets', 'feed'],
  },
  {
    name: 'xGetSpace',
    description: 'Get a Space by ID.',
    tool: xGetSpace,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['audio', 'live', 'fetch'],
  },
  {
    name: 'xGetSpacesByIds',
    description: 'Get up to 100 Spaces by IDs in one request.',
    tool: xGetSpacesByIds,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['audio', 'batch'],
  },
  {
    name: 'xSpacesByCreators',
    description: 'Get Spaces created by given user IDs.',
    tool: xSpacesByCreators,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['audio', 'hosts', 'creators'],
  },
  {
    name: 'xSearchSpaces',
    description: 'Search live or scheduled Spaces by keyword.',
    tool: xSearchSpaces,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['audio', 'find', 'discover'],
  },
  {
    name: 'xSpaceBuyers',
    description: 'Get users who bought tickets for a ticketed Space.',
    tool: xSpaceBuyers,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['audio', 'tickets', 'attendees'],
  },
  {
    name: 'xSpacePosts',
    description: 'Get posts shared in a Space.',
    tool: xSpacePosts,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['audio', 'tweets'],
  },
  {
    name: 'xCreateDmConversation',
    description: 'Create a group DM conversation with an opening message.',
    tool: xCreateDmConversation,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['direct message', 'chat', 'group'],
  },
  {
    name: 'xSendDmToConversation',
    description: 'Send a message to an existing DM conversation.',
    tool: xSendDmToConversation,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['direct message', 'chat', 'reply'],
  },
  {
    name: 'xSendDmToUser',
    description: 'Send a new one-to-one DM to a user by user ID.',
    tool: xSendDmToUser,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['direct message', 'chat', 'new'],
  },
  {
    name: 'xDmEventsByParticipant',
    description: 'Get DM events for the one-to-one conversation with a user.',
    tool: xDmEventsByParticipant,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['direct messages', 'chat', 'history'],
  },
  {
    name: 'xDmEventsByConversation',
    description: 'Get DM events for a conversation by conversation ID.',
    tool: xDmEventsByConversation,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['direct messages', 'chat', 'history'],
  },
  {
    name: 'xRecentDmEvents',
    description: 'Get recent DM events across all conversations (30 days).',
    tool: xRecentDmEvents,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['direct messages', 'chat', 'inbox'],
  },
  {
    name: 'xGetDmEvent',
    description: 'Get a single DM event by event ID.',
    tool: xGetDmEvent,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['direct message', 'fetch'],
  },
  {
    name: 'xDeleteDm',
    description: 'Delete a DM event you sent by event ID.',
    tool: xDeleteDm,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['direct message', 'remove'],
  },
  {
    name: 'xInitMediaUpload',
    description: 'Initialize a chunked media upload session for videos, GIFs, large files.',
    tool: xInitMediaUpload,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['photo', 'video', 'chunked'],
  },
  {
    name: 'xAppendMediaUpload',
    description: 'Append a base64 media chunk to an upload session.',
    tool: xAppendMediaUpload,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['photo', 'video', 'chunk'],
  },
  {
    name: 'xMediaUploadStatus',
    description: 'Poll media processing status until succeeded before posting.',
    tool: xMediaUploadStatus,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['photo', 'video', 'processing'],
  },
  {
    name: 'xUploadMedia',
    description: 'Upload a small media file in one request (base64).',
    tool: xUploadMedia,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['photo', 'image', 'picture'],
  },
  {
    name: 'xUploadLargeMedia',
    description: 'Upload a large media file via initialize, append, finalize in one call.',
    tool: xUploadLargeMedia,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['photo', 'video', 'gif'],
  },
  {
    name: 'xCreateComplianceJob',
    description: 'Create a compliance job for post or user IDs.',
    tool: xCreateComplianceJob,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['moderation', 'batch', 'status'],
  },
  {
    name: 'xGetComplianceJob',
    description: 'Get a compliance job by ID.',
    tool: xGetComplianceJob,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['moderation', 'fetch'],
  },
  {
    name: 'xListComplianceJobs',
    description: 'List compliance jobs by type and status.',
    tool: xListComplianceJobs,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['moderation', 'jobs'],
  },
  {
    name: 'xCreateActivitySubscription',
    description: 'Subscribe to X activity events: follows, profile updates, spaces, news.',
    tool: xCreateActivitySubscription,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['webhook', 'monitor', 'events'],
  },
  {
    name: 'xGetOpenApiSpec',
    description: 'Fetch the official X API v2 OpenAPI spec summary and operations.',
    tool: xGetOpenApiSpec,
    scope: 'read' as const,
    keywords: ['schema', 'endpoints', 'reference', 'docs'],
  },
];
