// @ts-nocheck
import {
  clickupGetAccessToken,
} from './auth.js';
import {
  clickupCreateChatChannel,
  clickupCreateChatMessage,
  clickupCreateChatReaction,
  clickupCreateDirectMessageChannel,
  clickupCreateLocationChatChannel,
  clickupCreateReplyMessage,
  clickupDeleteChatChannel,
  clickupDeleteChatMessage,
  clickupDeleteChatReaction,
  clickupGetChatChannel,
  clickupGetChatChannelFollowers,
  clickupGetChatChannelMembers,
  clickupGetChatChannels,
  clickupGetChatMessageReactions,
  clickupGetChatMessageReplies,
  clickupGetChatMessages,
  clickupGetChatMessageTaggedUsers,
  clickupGetSubtypes,
  clickupUpdateChatChannel,
  clickupUpdateChatMessage,
  clickupUpdateWorkspaceAcl,
} from './chat.js';
import {
  clickupCreateChecklist,
  clickupCreateChecklistItem,
  clickupDeleteChecklist,
  clickupDeleteChecklistItem,
  clickupUpdateChecklist,
  clickupUpdateChecklistItem,
} from './checklists.js';
import {
  clickupCreateChatViewComment,
  clickupCreateListComment,
  clickupCreateTaskComment,
  clickupCreateThreadedComment,
  clickupDeleteComment,
  clickupGetChatViewComments,
  clickupGetListComments,
  clickupGetTaskComments,
  clickupGetThreadedComments,
  clickupUpdateComment,
} from './comments.js';
import {
  clickupClickUpUpdateDocPage,
  clickupCreateDoc,
  clickupCreateDocPage,
  clickupGetDocContent,
  clickupGetDocPageContent,
  clickupGetDocPageListing,
  clickupGetDocPagesPublic,
  clickupSearchDocs,
} from './docs.js';
import {
  clickupAttachmentsUploadFileToTaskAsAttachment,
  clickupCreateTaskAttachment,
} from './files.js';
import {
  clickupCreateFolder,
  clickupDeleteFolder,
  clickupGetFolder,
  clickupGetFolders,
  clickupUpdateFolder,
} from './folders.js';
import {
  clickupCreateGoal,
  clickupCreateKeyResult,
  clickupDeleteGoal,
  clickupDeleteKeyResult,
  clickupGetGoal,
  clickupGetGoals,
  clickupUpdateGoal,
  clickupUpdateKeyResult,
} from './goals.js';
import {
  clickupCreateFolderlessList,
  clickupCreateList,
  clickupCreateListFromTemplate,
  clickupDeleteList,
  clickupGetFolderlessLists,
  clickupGetList,
  clickupGetListMembers,
  clickupGetLists,
  clickupUpdateList,
} from './lists.js';
import {
  clickupCreateSpace,
  clickupCreateSpaceTag,
  clickupDeleteSpace,
  clickupDeleteSpaceTag,
  clickupGetSpace,
  clickupGetSpaces,
  clickupGetSpaceTags,
  clickupUpdateSpace,
  clickupUpdateSpaceTag,
} from './spaces.js';
import {
  clickupAddDependency,
  clickupAddTagToTask,
  clickupAddTaskLink,
  clickupAddTaskToList,
  clickupCreateTask,
  clickupCreateTaskFromTemplate,
  clickupDeleteDependency,
  clickupDeleteTask,
  clickupDeleteTaskLink,
  clickupGetAccessibleCustomFields,
  clickupGetBulkTasksTimeInStatus,
  clickupGetCustomTaskTypes,
  clickupGetFilteredTeamTasks,
  clickupGetFolderAvailableFields,
  clickupGetSpaceAvailableFields,
  clickupGetTask,
  clickupGetTaskMembers,
  clickupGetTasks,
  clickupGetTaskTemplates,
  clickupGetTaskTimeInStatus,
  clickupGetTeamAvailableFields,
  clickupMoveTaskToHomeList,
  clickupRemoveCustomFieldValue,
  clickupRemoveTagFromTask,
  clickupRemoveTaskFromList,
  clickupSetCustomFieldValue,
  clickupUpdateTask,
} from './tasks.js';
import {
  clickupAddTagsToTimeEntries,
  clickupCreateATimeEntry,
  clickupDeleteTimeEntry,
  clickupDeleteTimeTracked,
  clickupGetAllTagsFromTimeEntries,
  clickupGetRunningTimeEntry,
  clickupGetTimeEntriesInDateRange,
  clickupGetTimeEntry,
  clickupGetTimeEntryHistory,
  clickupGetTrackedTime,
  clickupRemoveTagsFromTimeEntries,
  clickupStartTimeEntry,
  clickupStopTimeEntry,
  clickupTrackTime,
  clickupUpdateTimeEntry,
  clickupUpdateTimeEntryTag,
  clickupUpdateTimeTracked,
} from './time.js';
import {
  clickupAddGuestToFolder,
  clickupAddGuestToList,
  clickupAddGuestToTask,
  clickupAuthorizationGetWorkSpaceList,
  clickupCreateTeam,
  clickupDeleteTeam,
  clickupGetAuthorizedTeamsWorkspaces,
  clickupGetAuthorizedUser,
  clickupGetCustomRoles,
  clickupGetGuest,
  clickupGetSharedHierarchy,
  clickupGetTeams,
  clickupGetUser,
  clickupGetWorkspacePlan,
  clickupGetWorkspaceSeats,
  clickupInviteGuestToWorkspace,
  clickupInviteUserToWorkspace,
  clickupRemoveGuestFromFolder,
  clickupRemoveGuestFromList,
  clickupRemoveGuestFromTask,
  clickupRemoveGuestFromWorkspace,
  clickupRemoveUserFromWorkspace,
  clickupUpdateGuestOnWorkspace,
  clickupUpdateTeam,
  clickupUpdateUserOnWorkspace,
} from './users.js';
import {
  clickupCreateFolderView,
  clickupCreateListView,
  clickupCreateSpaceView,
  clickupCreateWorkspaceEverythingLevelView,
  clickupDeleteView,
  clickupGetFolderViews,
  clickupGetListViews,
  clickupGetSpaceViews,
  clickupGetView,
  clickupGetViewTasks,
  clickupGetWorkspaceEverythingLevelViews,
  clickupUpdateView,
} from './views.js';
import {
  clickupCreateWebhook,
  clickupDeleteWebhook,
  clickupGetWebhooks,
  clickupUpdateWebhook,
} from './webhooks.js';

export { clickupGetAccessToken } from './auth.js';
export { clickupCreateChatChannel, clickupCreateChatMessage, clickupCreateChatReaction, clickupCreateDirectMessageChannel, clickupCreateLocationChatChannel, clickupCreateReplyMessage, clickupDeleteChatChannel, clickupDeleteChatMessage, clickupDeleteChatReaction, clickupGetChatChannel, clickupGetChatChannelFollowers, clickupGetChatChannelMembers, clickupGetChatChannels, clickupGetChatMessageReactions, clickupGetChatMessageReplies, clickupGetChatMessages, clickupGetChatMessageTaggedUsers, clickupGetSubtypes, clickupUpdateChatChannel, clickupUpdateChatMessage, clickupUpdateWorkspaceAcl } from './chat.js';
export { clickupCreateChecklist, clickupCreateChecklistItem, clickupDeleteChecklist, clickupDeleteChecklistItem, clickupUpdateChecklist, clickupUpdateChecklistItem } from './checklists.js';
export { clickupCreateChatViewComment, clickupCreateListComment, clickupCreateTaskComment, clickupCreateThreadedComment, clickupDeleteComment, clickupGetChatViewComments, clickupGetListComments, clickupGetTaskComments, clickupGetThreadedComments, clickupUpdateComment } from './comments.js';
export { clickupClickUpUpdateDocPage, clickupCreateDoc, clickupCreateDocPage, clickupGetDocContent, clickupGetDocPageContent, clickupGetDocPageListing, clickupGetDocPagesPublic, clickupSearchDocs } from './docs.js';
export { clickupAttachmentsUploadFileToTaskAsAttachment, clickupCreateTaskAttachment } from './files.js';
export { clickupCreateFolder, clickupDeleteFolder, clickupGetFolder, clickupGetFolders, clickupUpdateFolder } from './folders.js';
export { clickupCreateGoal, clickupCreateKeyResult, clickupDeleteGoal, clickupDeleteKeyResult, clickupGetGoal, clickupGetGoals, clickupUpdateGoal, clickupUpdateKeyResult } from './goals.js';
export { clickupCreateFolderlessList, clickupCreateList, clickupCreateListFromTemplate, clickupDeleteList, clickupGetFolderlessLists, clickupGetList, clickupGetListMembers, clickupGetLists, clickupUpdateList } from './lists.js';
export { clickupCreateSpace, clickupCreateSpaceTag, clickupDeleteSpace, clickupDeleteSpaceTag, clickupGetSpace, clickupGetSpaces, clickupGetSpaceTags, clickupUpdateSpace, clickupUpdateSpaceTag } from './spaces.js';
export { clickupAddDependency, clickupAddTagToTask, clickupAddTaskLink, clickupAddTaskToList, clickupCreateTask, clickupCreateTaskFromTemplate, clickupDeleteDependency, clickupDeleteTask, clickupDeleteTaskLink, clickupGetAccessibleCustomFields, clickupGetBulkTasksTimeInStatus, clickupGetCustomTaskTypes, clickupGetFilteredTeamTasks, clickupGetFolderAvailableFields, clickupGetSpaceAvailableFields, clickupGetTask, clickupGetTaskMembers, clickupGetTasks, clickupGetTaskTemplates, clickupGetTaskTimeInStatus, clickupGetTeamAvailableFields, clickupMoveTaskToHomeList, clickupRemoveCustomFieldValue, clickupRemoveTagFromTask, clickupRemoveTaskFromList, clickupSetCustomFieldValue, clickupUpdateTask } from './tasks.js';
export { clickupAddTagsToTimeEntries, clickupCreateATimeEntry, clickupDeleteTimeEntry, clickupDeleteTimeTracked, clickupGetAllTagsFromTimeEntries, clickupGetRunningTimeEntry, clickupGetTimeEntriesInDateRange, clickupGetTimeEntry, clickupGetTimeEntryHistory, clickupGetTrackedTime, clickupRemoveTagsFromTimeEntries, clickupStartTimeEntry, clickupStopTimeEntry, clickupTrackTime, clickupUpdateTimeEntry, clickupUpdateTimeEntryTag, clickupUpdateTimeTracked } from './time.js';
export { clickupAddGuestToFolder, clickupAddGuestToList, clickupAddGuestToTask, clickupAuthorizationGetWorkSpaceList, clickupCreateTeam, clickupDeleteTeam, clickupGetAuthorizedTeamsWorkspaces, clickupGetAuthorizedUser, clickupGetCustomRoles, clickupGetGuest, clickupGetSharedHierarchy, clickupGetTeams, clickupGetUser, clickupGetWorkspacePlan, clickupGetWorkspaceSeats, clickupInviteGuestToWorkspace, clickupInviteUserToWorkspace, clickupRemoveGuestFromFolder, clickupRemoveGuestFromList, clickupRemoveGuestFromTask, clickupRemoveGuestFromWorkspace, clickupRemoveUserFromWorkspace, clickupUpdateGuestOnWorkspace, clickupUpdateTeam, clickupUpdateUserOnWorkspace } from './users.js';
export { clickupCreateFolderView, clickupCreateListView, clickupCreateSpaceView, clickupCreateWorkspaceEverythingLevelView, clickupDeleteView, clickupGetFolderViews, clickupGetListViews, clickupGetSpaceViews, clickupGetView, clickupGetViewTasks, clickupGetWorkspaceEverythingLevelViews, clickupUpdateView } from './views.js';
export { clickupCreateWebhook, clickupDeleteWebhook, clickupGetWebhooks, clickupUpdateWebhook } from './webhooks.js';

const auth = 'clickupToken' as const;

export const clickupTools = [
  { name: 'clickupGetAccessToken', description: clickupGetAccessToken.description!, tool: clickupGetAccessToken, scope: 'write' as const, keywords: ["exchanges", "oauth", "authorization", "code", "obtained"] },
  { name: 'clickupCreateChatChannel', description: clickupCreateChatChannel.description!, tool: clickupCreateChatChannel, requiredAuth: auth, scope: 'write' as const, keywords: ["tool", "create", "communication", "team", "collaboration"] },
  { name: 'clickupCreateChatMessage', description: clickupCreateChatMessage.description!, tool: clickupCreateChatMessage, requiredAuth: auth, scope: 'write' as const, keywords: ["tool", "send", "post", "team", "channels"] },
  { name: 'clickupCreateChatReaction', description: clickupCreateChatReaction.description!, tool: clickupCreateChatReaction, requiredAuth: auth, scope: 'write' as const, keywords: ["tool", "reaction", "react", "emoji"] },
  { name: 'clickupCreateDirectMessageChannel', description: clickupCreateDirectMessageChannel.description!, tool: clickupCreateDirectMessageChannel, requiredAuth: auth, scope: 'write' as const, keywords: ["tool", "create", "direct", "start", "conversation"] },
  { name: 'clickupCreateLocationChatChannel', description: clickupCreateLocationChatChannel.description!, tool: clickupCreateLocationChatChannel, requiredAuth: auth, scope: 'write' as const, keywords: ["tool", "create", "location-based"] },
  { name: 'clickupCreateReplyMessage', description: clickupCreateReplyMessage.description!, tool: clickupCreateReplyMessage, requiredAuth: auth, scope: 'write' as const, keywords: ["tool", "create", "reply", "replying", "requires"] },
  { name: 'clickupDeleteChatChannel', description: clickupDeleteChatChannel.description!, tool: clickupDeleteChatChannel, requiredAuth: auth, scope: 'delete' as const, keywords: ["tool", "delete", "permanently", "remove"] },
  { name: 'clickupDeleteChatMessage', description: clickupDeleteChatMessage.description!, tool: clickupDeleteChatMessage, requiredAuth: auth, scope: 'delete' as const, keywords: ["tool", "delete", "permanently", "remove"] },
  { name: 'clickupDeleteChatReaction', description: clickupDeleteChatReaction.description!, tool: clickupDeleteChatReaction, requiredAuth: auth, scope: 'delete' as const, keywords: ["tool", "delete", "reaction", "remove", "emoji"] },
  { name: 'clickupGetChatChannel', description: clickupGetChatChannel.description!, tool: clickupGetChatChannel, requiredAuth: auth, scope: 'read' as const, keywords: ["retrieves", "about", "particular"] },
  { name: 'clickupGetChatChannelFollowers', description: clickupGetChatChannelFollowers.description!, tool: clickupGetChatChannelFollowers, requiredAuth: auth, scope: 'read' as const, keywords: ["tool", "retrieve", "followers"] },
  { name: 'clickupGetChatChannelMembers', description: clickupGetChatChannelMembers.description!, tool: clickupGetChatChannelMembers, requiredAuth: auth, scope: 'read' as const, keywords: ["tool", "members", "retrieve"] },
  { name: 'clickupGetChatChannels', description: clickupGetChatChannels.description!, tool: clickupGetChatChannels, requiredAuth: auth, scope: 'read' as const, keywords: ["tool", "retrieve", "channels", "available", "group"] },
  { name: 'clickupGetChatMessageReactions', description: clickupGetChatMessageReactions.description!, tool: clickupGetChatMessageReactions, requiredAuth: auth, scope: 'read' as const, keywords: ["tool", "retrieve", "reactions", "reacted", "emoji"] },
  { name: 'clickupGetChatMessageReplies', description: clickupGetChatMessageReplies.description!, tool: clickupGetChatMessageReplies, requiredAuth: auth, scope: 'read' as const, keywords: ["retrieves", "replies", "fetch", "responses"] },
  { name: 'clickupGetChatMessages', description: clickupGetChatMessages.description!, tool: clickupGetChatMessages, requiredAuth: auth, scope: 'read' as const, keywords: ["tool", "retrieve", "fetch"] },
  { name: 'clickupGetChatMessageTaggedUsers', description: clickupGetChatMessageTaggedUsers.description!, tool: clickupGetChatMessageTaggedUsers, requiredAuth: auth, scope: 'read' as const, keywords: ["tool", "retrieve", "tagged", "mentioned"] },
  { name: 'clickupGetSubtypes', description: clickupGetSubtypes.description!, tool: clickupGetSubtypes, requiredAuth: auth, scope: 'read' as const, keywords: ["tool", "retrieve", "post", "subtype", "announcement"] },
  { name: 'clickupUpdateChatChannel', description: clickupUpdateChatChannel.description!, tool: clickupUpdateChatChannel, requiredAuth: auth, scope: 'write' as const, keywords: ["tool", "update", "properties", "including", "name"] },
  { name: 'clickupUpdateChatMessage', description: clickupUpdateChatMessage.description!, tool: clickupUpdateChatMessage, requiredAuth: auth, scope: 'write' as const, keywords: ["tool", "update", "content", "assignee", "resolved"] },
  { name: 'clickupUpdateWorkspaceAcl', description: clickupUpdateWorkspaceAcl.description!, tool: clickupUpdateWorkspaceAcl, requiredAuth: auth, scope: 'write' as const, keywords: ["updates", "privacy", "access", "control", "permissions"] },
  { name: 'clickupCreateChecklist', description: clickupCreateChecklist.description!, tool: clickupCreateChecklist, requiredAuth: auth, scope: 'write' as const, keywords: ["creates", "checklist", "specified", "name", "identified"] },
  { name: 'clickupCreateChecklistItem', description: clickupCreateChecklistItem.description!, tool: clickupCreateChecklistItem, requiredAuth: auth, scope: 'write' as const, keywords: ["creates", "checklist", "item", "specified", "optionally"] },
  { name: 'clickupDeleteChecklist', description: clickupDeleteChecklist.description!, tool: clickupDeleteChecklist, requiredAuth: auth, scope: 'delete' as const, keywords: ["permanently", "deletes", "checklist", "identified"] },
  { name: 'clickupDeleteChecklistItem', description: clickupDeleteChecklistItem.description!, tool: clickupDeleteChecklistItem, requiredAuth: auth, scope: 'delete' as const, keywords: ["permanently", "deletes", "item", "identified", "checklist"] },
  { name: 'clickupUpdateChecklist', description: clickupUpdateChecklist.description!, tool: clickupUpdateChecklist, requiredAuth: auth, scope: 'write' as const, keywords: ["updates", "checklist", "name", "position", "identified"] },
  { name: 'clickupUpdateChecklistItem', description: clickupUpdateChecklistItem.description!, tool: clickupUpdateChecklistItem, requiredAuth: auth, scope: 'write' as const, keywords: ["updates", "checklist", "item", "allowing", "modification"] },
  { name: 'clickupCreateChatViewComment', description: clickupCreateChatViewComment.description!, tool: clickupCreateChatViewComment, requiredAuth: auth, scope: 'write' as const, keywords: ["posts", "specified", "correspond", "accessible"] },
  { name: 'clickupCreateListComment', description: clickupCreateListComment.description!, tool: clickupCreateListComment, requiredAuth: auth, scope: 'write' as const, keywords: ["adds", "text", "accessible", "assigns", "sets"] },
  { name: 'clickupCreateTaskComment', description: clickupCreateTaskComment.description!, tool: clickupCreateTaskComment, requiredAuth: auth, scope: 'write' as const, keywords: ["adds", "team", "required", "true"] },
  { name: 'clickupCreateThreadedComment', description: clickupCreateThreadedComment.description!, tool: clickupCreateThreadedComment, requiredAuth: auth, scope: 'write' as const, keywords: ["tool", "create", "threaded", "reply", "respond"] },
  { name: 'clickupDeleteComment', description: clickupDeleteComment.description!, tool: clickupDeleteComment, requiredAuth: auth, scope: 'delete' as const, keywords: ["deletes"] },
  { name: 'clickupGetChatViewComments', description: clickupGetChatViewComments.description!, tool: clickupGetChatViewComments, requiredAuth: auth, scope: 'read' as const, keywords: ["retrieves", "specified", "supporting", "pagination", "start"] },
  { name: 'clickupGetListComments', description: clickupGetListComments.description!, tool: clickupGetListComments, requiredAuth: auth, scope: 'read' as const, keywords: ["retrieves", "supporting", "pagination", "start", "timestamp"] },
  { name: 'clickupGetTaskComments', description: clickupGetTaskComments.description!, tool: clickupGetTaskComments, requiredAuth: auth, scope: 'read' as const, keywords: ["retrieves", "specified", "supporting", "pagination", "start"] },
  { name: 'clickupGetThreadedComments', description: clickupGetThreadedComments.description!, tool: clickupGetThreadedComments, requiredAuth: auth, scope: 'read' as const, keywords: ["retrieves", "threaded", "replies", "parent", "fetch"] },
  { name: 'clickupUpdateComment', description: clickupUpdateComment.description!, tool: clickupUpdateComment, requiredAuth: auth, scope: 'write' as const, keywords: ["updates", "text", "assignee", "valid", "member"] },
  { name: 'clickupClickUpUpdateDocPage', description: clickupClickUpUpdateDocPage.description!, tool: clickupClickUpUpdateDocPage, requiredAuth: auth, scope: 'write' as const, keywords: ["tool", "update/edit", "title", "and/or", "content"] },
  { name: 'clickupCreateDoc', description: clickupCreateDoc.description!, tool: clickupCreateDoc, requiredAuth: auth, scope: 'write' as const, keywords: ["tool", "create", "return", "follow-up", "page/content"] },
  { name: 'clickupCreateDocPage', description: clickupCreateDocPage.description!, tool: clickupCreateDocPage, requiredAuth: auth, scope: 'write' as const, keywords: ["tool", "create", "document", "root", "sub-page"] },
  { name: 'clickupGetDocContent', description: clickupGetDocContent.description!, tool: clickupGetDocContent, requiredAuth: auth, scope: 'read' as const, keywords: ["tool", "fetch", "full", "content", "including"] },
  { name: 'clickupGetDocPageContent', description: clickupGetDocPageContent.description!, tool: clickupGetDocPageContent, requiredAuth: auth, scope: 'read' as const, keywords: ["tool", "fetch", "content", "metadata", "read"] },
  { name: 'clickupGetDocPageListing', description: clickupGetDocPageListing.description!, tool: clickupGetDocPageListing, requiredAuth: auth, scope: 'read' as const, keywords: ["tool", "fetch", "listing", "structure", "discover"] },
  { name: 'clickupGetDocPagesPublic', description: clickupGetDocPagesPublic.description!, tool: clickupGetDocPagesPublic, requiredAuth: auth, scope: 'read' as const, keywords: ["tool", "fetch", "belonging", "their", "content"] },
  { name: 'clickupSearchDocs', description: clickupSearchDocs.description!, tool: clickupSearchDocs, requiredAuth: auth, scope: 'read' as const, keywords: ["tool", "metadata", "confirming", "quickly", "locate"] },
  { name: 'clickupAttachmentsUploadFileToTaskAsAttachment', description: clickupAttachmentsUploadFileToTaskAsAttachment.description!, tool: clickupAttachmentsUploadFileToTaskAsAttachment, requiredAuth: auth, scope: 'write' as const, keywords: ["deprecated", "create", "attachment", "upload", "file"] },
  { name: 'clickupCreateTaskAttachment', description: clickupCreateTaskAttachment.description!, tool: clickupCreateTaskAttachment, requiredAuth: auth, scope: 'write' as const, keywords: ["uploads", "file", "attachment", "specified", "multipart/form-data"] },
  { name: 'clickupCreateFolder', description: clickupCreateFolder.description!, tool: clickupCreateFolder, requiredAuth: auth, scope: 'write' as const, keywords: ["creates", "specified", "exist", "accessible"] },
  { name: 'clickupDeleteFolder', description: clickupDeleteFolder.description!, tool: clickupDeleteFolder, requiredAuth: auth, scope: 'delete' as const, keywords: ["permanently", "irreversibly", "deletes", "specified", "contents"] },
  { name: 'clickupGetFolder', description: clickupGetFolder.description!, tool: clickupGetFolder, requiredAuth: auth, scope: 'read' as const, keywords: ["retrieves", "detailed", "about"] },
  { name: 'clickupGetFolders', description: clickupGetFolders.description!, tool: clickupGetFolders, requiredAuth: auth, scope: 'read' as const, keywords: ["retrieves", "folders", "specified", "ensuring", "valid"] },
  { name: 'clickupUpdateFolder', description: clickupUpdateFolder.description!, tool: clickupUpdateFolder, requiredAuth: auth, scope: 'write' as const, keywords: ["updates", "name"] },
  { name: 'clickupCreateGoal', description: clickupCreateGoal.description!, tool: clickupCreateGoal, requiredAuth: auth, scope: 'write' as const, keywords: ["creates", "team"] },
  { name: 'clickupCreateKeyResult', description: clickupCreateKeyResult.description!, tool: clickupCreateKeyResult, requiredAuth: auth, scope: 'write' as const, keywords: ["creates", "result", "target", "specified", "define"] },
  { name: 'clickupDeleteGoal', description: clickupDeleteGoal.description!, tool: clickupDeleteGoal, requiredAuth: auth, scope: 'delete' as const, keywords: ["permanently", "removes", "identified"] },
  { name: 'clickupDeleteKeyResult', description: clickupDeleteKeyResult.description!, tool: clickupDeleteKeyResult, requiredAuth: auth, scope: 'delete' as const, keywords: ["deletes", "result", "referred", "target", "identified"] },
  { name: 'clickupGetGoal', description: clickupGetGoal.description!, tool: clickupGetGoal, requiredAuth: auth, scope: 'read' as const, keywords: ["retrieves", "detailed", "specified", "unique"] },
  { name: 'clickupGetGoals', description: clickupGetGoals.description!, tool: clickupGetGoals, requiredAuth: auth, scope: 'read' as const, keywords: ["retrieves", "specified", "team", "valid", "accessible"] },
  { name: 'clickupUpdateGoal', description: clickupUpdateGoal.description!, tool: clickupUpdateGoal, requiredAuth: auth, scope: 'write' as const, keywords: ["updates", "attributes", "identified"] },
  { name: 'clickupUpdateKeyResult', description: clickupUpdateKeyResult.description!, tool: clickupUpdateKeyResult, requiredAuth: auth, scope: 'write' as const, keywords: ["updates", "result", "progress", "note", "measures"] },
  { name: 'clickupCreateFolderlessList', description: clickupCreateFolderlessList.description!, tool: clickupCreateFolderlessList, requiredAuth: auth, scope: 'write' as const, keywords: ["creates", "folderless", "part", "directly", "specified"] },
  { name: 'clickupCreateList', description: clickupCreateList.description!, tool: clickupCreateList, requiredAuth: auth, scope: 'write' as const, keywords: ["creates", "action", "requires", "lists", "cannot"] },
  { name: 'clickupCreateListFromTemplate', description: clickupCreateListFromTemplate.description!, tool: clickupCreateListFromTemplate, requiredAuth: auth, scope: 'write' as const, keywords: ["creates", "template", "specified", "instantiate", "structure"] },
  { name: 'clickupDeleteList', description: clickupDeleteList.description!, tool: clickupDeleteList, requiredAuth: auth, scope: 'delete' as const, keywords: ["permanently", "deletes", "contents", "action", "destructive"] },
  { name: 'clickupGetFolderlessLists', description: clickupGetFolderlessLists.description!, tool: clickupGetFolderlessLists, requiredAuth: auth, scope: 'read' as const, keywords: ["retrieves", "lists", "specified", "located"] },
  { name: 'clickupGetList', description: clickupGetList.description!, tool: clickupGetList, requiredAuth: auth, scope: 'read' as const, keywords: ["retrieves", "detailed", "identified", "unique"] },
  { name: 'clickupGetListMembers', description: clickupGetListMembers.description!, tool: clickupGetListMembers, requiredAuth: auth, scope: 'read' as const, keywords: ["retrieves", "members"] },
  { name: 'clickupGetLists', description: clickupGetLists.description!, tool: clickupGetLists, requiredAuth: auth, scope: 'read' as const, keywords: ["retrieves", "lists", "specified", "optionally", "filtering"] },
  { name: 'clickupUpdateList', description: clickupUpdateList.description!, tool: clickupUpdateList, requiredAuth: auth, scope: 'write' as const, keywords: ["updates", "attributes", "name", "content", "date"] },
  { name: 'clickupCreateSpace', description: clickupCreateSpace.description!, tool: clickupCreateSpace, requiredAuth: auth, scope: 'write' as const, keywords: ["creates", "specified", "allowing", "feature", "configuration"] },
  { name: 'clickupCreateSpaceTag', description: clickupCreateSpaceTag.description!, tool: clickupCreateSpaceTag, requiredAuth: auth, scope: 'write' as const, keywords: ["creates", "name", "foreground", "color", "background"] },
  { name: 'clickupDeleteSpace', description: clickupDeleteSpace.description!, tool: clickupDeleteSpace, requiredAuth: auth, scope: 'delete' as const, keywords: ["permanently", "deletes", "specified", "action", "irreversible"] },
  { name: 'clickupDeleteSpaceTag', description: clickupDeleteSpaceTag.description!, tool: clickupDeleteSpaceTag, requiredAuth: auth, scope: 'delete' as const, keywords: ["deletes", "identified", "name", "path", "precise"] },
  { name: 'clickupGetSpace', description: clickupGetSpace.description!, tool: clickupGetSpace, requiredAuth: auth, scope: 'read' as const, keywords: ["retrieves", "detailed", "identified", "unique"] },
  { name: 'clickupGetSpaces', description: clickupGetSpaces.description!, tool: clickupGetSpaces, requiredAuth: auth, scope: 'read' as const, keywords: ["retrieves", "spaces", "team", "member", "private"] },
  { name: 'clickupGetSpaceTags', description: clickupGetSpaceTags.description!, tool: clickupGetSpaceTags, requiredAuth: auth, scope: 'read' as const, keywords: ["retrieves", "specified", "requiring", "valid"] },
  { name: 'clickupUpdateSpace', description: clickupUpdateSpace.description!, tool: clickupUpdateSpace, requiredAuth: auth, scope: 'write' as const, keywords: ["updates", "allowing", "modification", "name", "color"] },
  { name: 'clickupUpdateSpaceTag', description: clickupUpdateSpaceTag.description!, tool: clickupUpdateSpaceTag, requiredAuth: auth, scope: 'write' as const, keywords: ["updates", "name", "colors", "requires", "identification"] },
  { name: 'clickupAddDependency', description: clickupAddDependency.description!, tool: clickupAddDependency, requiredAuth: auth, scope: 'write' as const, keywords: ["adds", "waiting", "blocking", "dependency", "requiring"] },
  { name: 'clickupAddTagToTask', description: clickupAddTagToTask.description!, tool: clickupAddTagToTask, requiredAuth: auth, scope: 'write' as const, keywords: ["adds", "specified", "team", "required", "true"] },
  { name: 'clickupAddTaskLink', description: clickupAddTaskLink.description!, tool: clickupAddTaskLink, requiredAuth: auth, scope: 'write' as const, keywords: ["links", "accessible", "identified", "source", "target"] },
  { name: 'clickupAddTaskToList', description: clickupAddTaskToList.description!, tool: clickupAddTaskToList, requiredAuth: auth, scope: 'write' as const, keywords: ["adds", "additional", "lists", "clickapp", "enabled"] },
  { name: 'clickupCreateTask', description: clickupCreateTask.description!, tool: clickupCreateTask, requiredAuth: auth, scope: 'write' as const, keywords: ["creates", "optionally", "subtask", "parent", "cannot"] },
  { name: 'clickupCreateTaskFromTemplate', description: clickupCreateTaskFromTemplate.description!, tool: clickupCreateTaskFromTemplate, requiredAuth: auth, scope: 'write' as const, keywords: ["creates", "specified", "template", "provided", "name"] },
  { name: 'clickupDeleteDependency', description: clickupDeleteDependency.description!, tool: clickupDeleteDependency, requiredAuth: auth, scope: 'delete' as const, keywords: ["removes", "dependency", "relationship", "provide", "exactly"] },
  { name: 'clickupDeleteTask', description: clickupDeleteTask.description!, tool: clickupDeleteTask, requiredAuth: auth, scope: 'delete' as const, keywords: ["permanently", "deletes", "requires", "true", "team"] },
  { name: 'clickupDeleteTaskLink', description: clickupDeleteTaskLink.description!, tool: clickupDeleteTaskLink, requiredAuth: auth, scope: 'delete' as const, keywords: ["deletes", "link", "effectively", "dependency", "relationship"] },
  { name: 'clickupGetAccessibleCustomFields', description: clickupGetAccessibleCustomFields.description!, tool: clickupGetAccessibleCustomFields, requiredAuth: auth, scope: 'read' as const, keywords: ["retrieves", "accessible", "definitions", "specified"] },
  { name: 'clickupGetBulkTasksTimeInStatus', description: clickupGetBulkTasksTimeInStatus.description!, tool: clickupGetBulkTasksTimeInStatus, requiredAuth: auth, scope: 'read' as const, keywords: ["retrieves", "spent", "status", "requires", "total"] },
  { name: 'clickupGetCustomTaskTypes', description: clickupGetCustomTaskTypes.description!, tool: clickupGetCustomTaskTypes, requiredAuth: auth, scope: 'read' as const, keywords: ["retrieves", "types", "available", "specified", "team"] },
  { name: 'clickupGetFilteredTeamTasks', description: clickupGetFilteredTeamTasks.description!, tool: clickupGetFilteredTeamTasks, requiredAuth: auth, scope: 'read' as const, keywords: ["retrieves", "paginated", "specified", "various", "filter"] },
  { name: 'clickupGetFolderAvailableFields', description: clickupGetFolderAvailableFields.description!, tool: clickupGetFolderAvailableFields, requiredAuth: auth, scope: 'read' as const, keywords: ["tool", "available", "discover", "working", "returns"] },
  { name: 'clickupGetSpaceAvailableFields', description: clickupGetSpaceAvailableFields.description!, tool: clickupGetSpaceAvailableFields, requiredAuth: auth, scope: 'read' as const, keywords: ["retrieves", "available", "identified", "returns", "space-level"] },
  { name: 'clickupGetTask', description: clickupGetTask.description!, tool: clickupGetTask, requiredAuth: auth, scope: 'read' as const, keywords: ["retrieves", "comprehensive", "supporting", "requires", "team"] },
  { name: 'clickupGetTaskMembers', description: clickupGetTaskMembers.description!, tool: clickupGetTaskMembers, requiredAuth: auth, scope: 'read' as const, keywords: ["retrieves", "explicit", "access", "directly", "assigned"] },
  { name: 'clickupGetTasks', description: clickupGetTasks.description!, tool: clickupGetTasks, requiredAuth: auth, scope: 'read' as const, keywords: ["retrieves", "specified", "whose", "home", "given"] },
  { name: 'clickupGetTaskTemplates', description: clickupGetTaskTemplates.description!, tool: clickupGetTaskTemplates, requiredAuth: auth, scope: 'read' as const, keywords: ["retrieves", "templates", "specified", "team", "supporting"] },
  { name: 'clickupGetTaskTimeInStatus', description: clickupGetTaskTimeInStatus.description!, tool: clickupGetTaskTimeInStatus, requiredAuth: auth, scope: 'read' as const, keywords: ["retrieves", "duration", "spent", "status", "provided"] },
  { name: 'clickupGetTeamAvailableFields', description: clickupGetTeamAvailableFields.description!, tool: clickupGetTeamAvailableFields, requiredAuth: auth, scope: 'read' as const, keywords: ["retrieves", "available", "team", "identified", "returns"] },
  { name: 'clickupMoveTaskToHomeList', description: clickupMoveTaskToHomeList.description!, tool: clickupMoveTaskToHomeList, requiredAuth: auth, scope: 'write' as const, keywords: ["tool", "move", "home", "public", "change"] },
  { name: 'clickupRemoveCustomFieldValue', description: clickupRemoveCustomFieldValue.description!, tool: clickupRemoveCustomFieldValue, requiredAuth: auth, scope: 'delete' as const, keywords: ["removes", "does", "delete", "definition", "predefined"] },
  { name: 'clickupRemoveTagFromTask', description: clickupRemoveTagFromTask.description!, tool: clickupRemoveTagFromTask, requiredAuth: auth, scope: 'delete' as const, keywords: ["removes", "specified", "disassociating", "does", "delete"] },
  { name: 'clickupRemoveTaskFromList', description: clickupRemoveTaskFromList.description!, tool: clickupRemoveTaskFromList, requiredAuth: auth, scope: 'delete' as const, keywords: ["removes", "extra", "home", "lists", "clickapp"] },
  { name: 'clickupSetCustomFieldValue', description: clickupSetCustomFieldValue.description!, tool: clickupSetCustomFieldValue, requiredAuth: auth, scope: 'write' as const, keywords: ["sets", "updates", "type-dependent", "structure", "text"] },
  { name: 'clickupUpdateTask', description: clickupUpdateTask.description!, tool: clickupUpdateTask, requiredAuth: auth, scope: 'write' as const, keywords: ["updates", "attributes", "team", "required", "true"] },
  { name: 'clickupAddTagsToTimeEntries', description: clickupAddTagsToTimeEntries.description!, tool: clickupAddTagsToTimeEntries, requiredAuth: auth, scope: 'write' as const, keywords: ["associates", "specified", "given", "team"] },
  { name: 'clickupCreateATimeEntry', description: clickupCreateATimeEntry.description!, tool: clickupCreateATimeEntry, requiredAuth: auth, scope: 'write' as const, keywords: ["creates", "specified", "team"] },
  { name: 'clickupDeleteTimeEntry', description: clickupDeleteTimeEntry.description!, tool: clickupDeleteTimeEntry, requiredAuth: auth, scope: 'delete' as const, keywords: ["deletes", "specified", "timer", "identified", "team"] },
  { name: 'clickupDeleteTimeTracked', description: clickupDeleteTimeTracked.description!, tool: clickupDeleteTimeTracked, requiredAuth: auth, scope: 'delete' as const, keywords: ["deletes", "time-tracked", "interval", "legacy", "endpoint"] },
  { name: 'clickupGetAllTagsFromTimeEntries', description: clickupGetAllTagsFromTimeEntries.description!, tool: clickupGetAllTagsFromTimeEntries, requiredAuth: auth, scope: 'read' as const, keywords: ["retrieves", "unique", "applied", "specified", "team"] },
  { name: 'clickupGetRunningTimeEntry', description: clickupGetRunningTimeEntry.description!, tool: clickupGetRunningTimeEntry, requiredAuth: auth, scope: 'read' as const, keywords: ["retrieves", "currently", "active", "negative", "duration"] },
  { name: 'clickupGetTimeEntriesInDateRange', description: clickupGetTimeEntriesInDateRange.description!, tool: clickupGetTimeEntriesInDateRange, requiredAuth: auth, scope: 'read' as const, keywords: ["retrieves", "specified", "team", "date", "range"] },
  { name: 'clickupGetTimeEntry', description: clickupGetTimeEntry.description!, tool: clickupGetTimeEntry, requiredAuth: auth, scope: 'read' as const, keywords: ["fetches", "given", "team", "negative", "duration"] },
  { name: 'clickupGetTimeEntryHistory', description: clickupGetTimeEntryHistory.description!, tool: clickupGetTimeEntryHistory, requiredAuth: auth, scope: 'read' as const, keywords: ["retrieves", "modification", "history", "team"] },
  { name: 'clickupGetTrackedTime', description: clickupGetTrackedTime.description!, tool: clickupGetTrackedTime, requiredAuth: auth, scope: 'read' as const, keywords: ["retrieves", "tracked", "legacy", "endpoint", "prefer"] },
  { name: 'clickupRemoveTagsFromTimeEntries', description: clickupRemoveTagsFromTimeEntries.description!, tool: clickupRemoveTagsFromTimeEntries, requiredAuth: auth, scope: 'delete' as const, keywords: ["removes", "specified", "team", "deleting"] },
  { name: 'clickupStartTimeEntry', description: clickupStartTimeEntry.description!, tool: clickupStartTimeEntry, requiredAuth: auth, scope: 'write' as const, keywords: ["starts", "timer", "specified", "team", "optionally"] },
  { name: 'clickupStopTimeEntry', description: clickupStopTimeEntry.description!, tool: clickupStopTimeEntry, requiredAuth: auth, scope: 'write' as const, keywords: ["stops", "authenticated", "currently", "active", "specified"] },
  { name: 'clickupTrackTime', description: clickupTrackTime.description!, tool: clickupTrackTime, requiredAuth: auth, scope: 'write' as const, keywords: ["legacy", "tracking", "system", "newer", "endpoints"] },
  { name: 'clickupUpdateTimeEntry', description: clickupUpdateTimeEntry.description!, tool: clickupUpdateTimeEntry, requiredAuth: auth, scope: 'write' as const, keywords: ["updates", "requires", "team", "timer", "optional"] },
  { name: 'clickupUpdateTimeEntryTag', description: clickupUpdateTimeEntryTag.description!, tool: clickupUpdateTimeEntryTag, requiredAuth: auth, scope: 'write' as const, keywords: ["updates", "name", "background", "color", "and/or"] },
  { name: 'clickupUpdateTimeTracked', description: clickupUpdateTimeTracked.description!, tool: clickupUpdateTimeTracked, requiredAuth: auth, scope: 'write' as const, keywords: ["edits", "legacy", "time-tracked", "interval", "identified"] },
  { name: 'clickupAddGuestToFolder', description: clickupAddGuestToFolder.description!, tool: clickupAddGuestToFolder, requiredAuth: auth, scope: 'write' as const, keywords: ["adds", "guest", "specified", "permissions", "requires"] },
  { name: 'clickupAddGuestToList', description: clickupAddGuestToList.description!, tool: clickupAddGuestToList, requiredAuth: auth, scope: 'write' as const, keywords: ["shares", "guest", "granting", "them", "specified"] },
  { name: 'clickupAddGuestToTask', description: clickupAddGuestToTask.description!, tool: clickupAddGuestToTask, requiredAuth: auth, scope: 'write' as const, keywords: ["assigns", "guest", "specified", "permissions", "requires"] },
  { name: 'clickupAuthorizationGetWorkSpaceList', description: clickupAuthorizationGetWorkSpaceList.description!, tool: clickupAuthorizationGetWorkSpaceList, requiredAuth: auth, scope: 'read' as const, keywords: ["deprecated", "authorized", "teams", "workspaces", "instead"] },
  { name: 'clickupCreateTeam', description: clickupCreateTeam.description!, tool: clickupCreateTeam, requiredAuth: auth, scope: 'write' as const, keywords: ["creates", "team", "group", "specified", "members"] },
  { name: 'clickupDeleteTeam', description: clickupDeleteTeam.description!, tool: clickupDeleteTeam, requiredAuth: auth, scope: 'delete' as const, keywords: ["permanently", "deletes", "team", "group"] },
  { name: 'clickupGetAuthorizedTeamsWorkspaces', description: clickupGetAuthorizedTeamsWorkspaces.description!, tool: clickupGetAuthorizedTeamsWorkspaces, requiredAuth: auth, scope: 'read' as const, keywords: ["retrieves", "workspaces", "teams", "authenticated", "access"] },
  { name: 'clickupGetAuthorizedUser', description: clickupGetAuthorizedUser.description!, tool: clickupGetAuthorizedUser, requiredAuth: auth, scope: 'read' as const, keywords: ["retrieves", "currently", "authenticated"] },
  { name: 'clickupGetCustomRoles', description: clickupGetCustomRoles.description!, tool: clickupGetCustomRoles, requiredAuth: auth, scope: 'read' as const, keywords: ["retrieves", "roles", "allow", "granular", "permission"] },
  { name: 'clickupGetGuest', description: clickupGetGuest.description!, tool: clickupGetGuest, requiredAuth: auth, scope: 'read' as const, keywords: ["call", "retrieve", "detailed", "guest", "team"] },
  { name: 'clickupGetSharedHierarchy', description: clickupGetSharedHierarchy.description!, tool: clickupGetSharedHierarchy, requiredAuth: auth, scope: 'read' as const, keywords: ["retrieves", "hierarchy", "lists", "folders", "shared"] },
  { name: 'clickupGetTeams', description: clickupGetTeams.description!, tool: clickupGetTeams, requiredAuth: auth, scope: 'read' as const, keywords: ["retrieves", "groups", "teams", "typically", "requiring"] },
  { name: 'clickupGetUser', description: clickupGetUser.description!, tool: clickupGetUser, requiredAuth: auth, scope: 'read' as const, keywords: ["retrieves", "detailed", "team", "available", "workspaces"] },
  { name: 'clickupGetWorkspacePlan', description: clickupGetWorkspacePlan.description!, tool: clickupGetWorkspacePlan, requiredAuth: auth, scope: 'read' as const, keywords: ["retrieves", "subscription", "plan", "specified"] },
  { name: 'clickupGetWorkspaceSeats', description: clickupGetWorkspaceSeats.description!, tool: clickupGetWorkspaceSeats, requiredAuth: auth, scope: 'read' as const, keywords: ["retrieves", "seat", "utilization", "total", "available"] },
  { name: 'clickupInviteGuestToWorkspace', description: clickupInviteGuestToWorkspace.description!, tool: clickupInviteGuestToWorkspace, requiredAuth: auth, scope: 'write' as const, keywords: ["invites", "guest", "email", "team", "enterprise"] },
  { name: 'clickupInviteUserToWorkspace', description: clickupInviteUserToWorkspace.description!, tool: clickupInviteUserToWorkspace, requiredAuth: auth, scope: 'write' as const, keywords: ["invites", "email", "team", "optionally", "granting"] },
  { name: 'clickupRemoveGuestFromFolder', description: clickupRemoveGuestFromFolder.description!, tool: clickupRemoveGuestFromFolder, requiredAuth: auth, scope: 'delete' as const, keywords: ["revokes", "guest", "access", "optionally", "unsharing"] },
  { name: 'clickupRemoveGuestFromList', description: clickupRemoveGuestFromList.description!, tool: clickupRemoveGuestFromList, requiredAuth: auth, scope: 'delete' as const, keywords: ["revokes", "guest", "access", "provided", "currently"] },
  { name: 'clickupRemoveGuestFromTask', description: clickupRemoveGuestFromTask.description!, tool: clickupRemoveGuestFromTask, requiredAuth: auth, scope: 'delete' as const, keywords: ["revokes", "guest", "access", "available", "workspaces"] },
  { name: 'clickupRemoveGuestFromWorkspace', description: clickupRemoveGuestFromWorkspace.description!, tool: clickupRemoveGuestFromWorkspace, requiredAuth: auth, scope: 'delete' as const, keywords: ["permanently", "removes", "guest", "specified", "revoking"] },
  { name: 'clickupRemoveUserFromWorkspace', description: clickupRemoveUserFromWorkspace.description!, tool: clickupRemoveUserFromWorkspace, requiredAuth: auth, scope: 'delete' as const, keywords: ["deactivates", "specified", "revoking", "their", "access"] },
  { name: 'clickupUpdateGuestOnWorkspace', description: clickupUpdateGuestOnWorkspace.description!, tool: clickupUpdateGuestOnWorkspace, requiredAuth: auth, scope: 'write' as const, keywords: ["modifies", "permissions", "guest"] },
  { name: 'clickupUpdateTeam', description: clickupUpdateTeam.description!, tool: clickupUpdateTeam, requiredAuth: auth, scope: 'write' as const, keywords: ["updates", "group", "team", "note", "adding"] },
  { name: 'clickupUpdateUserOnWorkspace', description: clickupUpdateUserOnWorkspace.description!, tool: clickupUpdateUserOnWorkspace, requiredAuth: auth, scope: 'write' as const, keywords: ["updates", "username", "admin", "status", "role"] },
  { name: 'clickupCreateFolderView', description: clickupCreateFolderView.description!, tool: clickupCreateFolderView, requiredAuth: auth, scope: 'write' as const, keywords: ["creates", "highly", "customizable"] },
  { name: 'clickupCreateListView', description: clickupCreateListView.description!, tool: clickupCreateListView, requiredAuth: auth, scope: 'write' as const, keywords: ["creates", "customizable", "board", "calendar", "specified"] },
  { name: 'clickupCreateSpaceView', description: clickupCreateSpaceView.description!, tool: clickupCreateSpaceView, requiredAuth: auth, scope: 'write' as const, keywords: ["creates", "customizable", "board", "gantt", "specified"] },
  { name: 'clickupCreateWorkspaceEverythingLevelView', description: clickupCreateWorkspaceEverythingLevelView.description!, tool: clickupCreateWorkspaceEverythingLevelView, requiredAuth: auth, scope: 'write' as const, keywords: ["creates", "customizable", "board", "everything", "level"] },
  { name: 'clickupDeleteView', description: clickupDeleteView.description!, tool: clickupDeleteView, requiredAuth: auth, scope: 'delete' as const, keywords: ["permanently", "irreversibly", "deletes", "identified"] },
  { name: 'clickupGetFolderViews', description: clickupGetFolderViews.description!, tool: clickupGetFolderViews, requiredAuth: auth, scope: 'read' as const, keywords: ["retrieves", "configured", "views", "board", "calendar"] },
  { name: 'clickupGetListViews', description: clickupGetListViews.description!, tool: clickupGetListViews, requiredAuth: auth, scope: 'read' as const, keywords: ["retrieves", "views", "specified", "accessible"] },
  { name: 'clickupGetSpaceViews', description: clickupGetSpaceViews.description!, tool: clickupGetSpaceViews, requiredAuth: auth, scope: 'read' as const, keywords: ["retrieves", "views", "specified"] },
  { name: 'clickupGetView', description: clickupGetView.description!, tool: clickupGetView, requiredAuth: auth, scope: 'read' as const, keywords: ["fetches", "identified", "exist"] },
  { name: 'clickupGetViewTasks', description: clickupGetViewTasks.description!, tool: clickupGetViewTasks, requiredAuth: auth, scope: 'read' as const, keywords: ["retrieves", "visible", "specified", "respecting", "applied"] },
  { name: 'clickupGetWorkspaceEverythingLevelViews', description: clickupGetWorkspaceEverythingLevelViews.description!, tool: clickupGetWorkspaceEverythingLevelViews, requiredAuth: auth, scope: 'read' as const, keywords: ["retrieves", "views", "everything", "level", "comprehensive"] },
  { name: 'clickupUpdateView', description: clickupUpdateView.description!, tool: clickupUpdateView, requiredAuth: auth, scope: 'write' as const, keywords: ["updates", "settings", "name", "type", "grouping"] },
  { name: 'clickupCreateWebhook', description: clickupCreateWebhook.description!, tool: clickupCreateWebhook, requiredAuth: auth, scope: 'write' as const, keywords: ["creates", "team", "notify", "public", "specified"] },
  { name: 'clickupDeleteWebhook', description: clickupDeleteWebhook.description!, tool: clickupDeleteWebhook, requiredAuth: auth, scope: 'delete' as const, keywords: ["permanently", "removes", "specified", "thereby", "ceasing"] },
  { name: 'clickupGetWebhooks', description: clickupGetWebhooks.description!, tool: clickupGetWebhooks, requiredAuth: auth, scope: 'read' as const, keywords: ["fetches", "team", "returning", "created", "authenticated"] },
  { name: 'clickupUpdateWebhook', description: clickupUpdateWebhook.description!, tool: clickupUpdateWebhook, requiredAuth: auth, scope: 'write' as const, keywords: ["updates", "endpoint", "monitored", "events", "status"] },
];
