// @ts-nocheck
import {
  teamsListJoinedTeams,
  teamsListAllTeams,
  teamsGetTeam,
  teamsCreateTeam,
  teamsUpdateTeam,
  teamsDeleteTeam,
  teamsArchiveTeam,
  teamsUnarchiveTeam,
  teamsCloneTeam,
  teamsListChannels,
  teamsGetChannel,
  teamsCreateChannel,
  teamsUpdateChannel,
  teamsDeleteChannel,
  teamsListTeamMembers,
  teamsAddTeamMember,
  teamsRemoveTeamMember,
  teamsUpdateTeamMember,
  teamsListChannelMembers,
  teamsAddChannelMember,
  teamsRemoveChannelMember,
  teamsListTags,
  teamsCreateTag,
  teamsDeleteTag,
  teamsListTabs,
  teamsAddTab,
  teamsUpdateTab,
  teamsDeleteTab,
  teamsListInstalledApps,
  teamsInstallApp,
  teamsUninstallApp,
  teamsSendActivityNotification,
} from './teams.js';
import {
  teamsListChannelMessages,
  teamsGetChannelMessage,
  teamsSendChannelMessage,
  teamsReplyChannelMessage,
  teamsListMessageReplies,
  teamsUpdateChannelMessage,
  teamsDeleteChannelMessage,
  teamsUndoDeleteChannelMessage,
  teamsListChats,
  teamsGetChat,
  teamsCreateChat,
  teamsUpdateChat,
  teamsDeleteChat,
  teamsListChatMessages,
  teamsGetChatMessage,
  teamsSendChatMessage,
  teamsUpdateChatMessage,
  teamsDeleteChatMessage,
  teamsListChatMembers,
  teamsAddChatMember,
  teamsRemoveChatMember,
  teamsListPinnedMessages,
  teamsPinChatMessage,
  teamsUnpinChatMessage,
} from './messages.js';
import {
  teamsCreateOnlineMeeting,
  teamsGetOnlineMeeting,
  teamsUpdateOnlineMeeting,
  teamsDeleteOnlineMeeting,
  teamsListAttendanceReports,
  teamsListAttendanceRecords,
  teamsListMeetingRecordings,
  teamsGetMeetingRecording,
  teamsGetPresence,
  teamsSetPresence,
} from './meetings.js';

export {
  teamsListJoinedTeams,
  teamsListAllTeams,
  teamsGetTeam,
  teamsCreateTeam,
  teamsUpdateTeam,
  teamsDeleteTeam,
  teamsArchiveTeam,
  teamsUnarchiveTeam,
  teamsCloneTeam,
  teamsListChannels,
  teamsGetChannel,
  teamsCreateChannel,
  teamsUpdateChannel,
  teamsDeleteChannel,
  teamsListTeamMembers,
  teamsAddTeamMember,
  teamsRemoveTeamMember,
  teamsUpdateTeamMember,
  teamsListChannelMembers,
  teamsAddChannelMember,
  teamsRemoveChannelMember,
  teamsListTags,
  teamsCreateTag,
  teamsDeleteTag,
  teamsListTabs,
  teamsAddTab,
  teamsUpdateTab,
  teamsDeleteTab,
  teamsListInstalledApps,
  teamsInstallApp,
  teamsUninstallApp,
  teamsSendActivityNotification,
  teamsListChannelMessages,
  teamsGetChannelMessage,
  teamsSendChannelMessage,
  teamsReplyChannelMessage,
  teamsListMessageReplies,
  teamsUpdateChannelMessage,
  teamsDeleteChannelMessage,
  teamsUndoDeleteChannelMessage,
  teamsListChats,
  teamsGetChat,
  teamsCreateChat,
  teamsUpdateChat,
  teamsDeleteChat,
  teamsListChatMessages,
  teamsGetChatMessage,
  teamsSendChatMessage,
  teamsUpdateChatMessage,
  teamsDeleteChatMessage,
  teamsListChatMembers,
  teamsAddChatMember,
  teamsRemoveChatMember,
  teamsListPinnedMessages,
  teamsPinChatMessage,
  teamsUnpinChatMessage,
  teamsCreateOnlineMeeting,
  teamsGetOnlineMeeting,
  teamsUpdateOnlineMeeting,
  teamsDeleteOnlineMeeting,
  teamsListAttendanceReports,
  teamsListAttendanceRecords,
  teamsListMeetingRecordings,
  teamsGetMeetingRecording,
  teamsGetPresence,
  teamsSetPresence,
};

const AUTH = 'teamsToken' as const;

export const teamsTools = [
  {
    name: 'teamsListJoinedTeams',
    description: 'List teams the user is a member of.',
    tool: teamsListJoinedTeams,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['groups', 'memberships'],
  },
  {
    name: 'teamsListAllTeams',
    description: 'List all teams in the organization.',
    tool: teamsListAllTeams,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['directory', 'groups'],
  },
  {
    name: 'teamsGetTeam',
    description: 'Get one team.',
    tool: teamsGetTeam,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['group', 'fetch'],
  },
  {
    name: 'teamsCreateTeam',
    description: 'Create a team from a template with owners/members.',
    tool: teamsCreateTeam,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['group', 'provision'],
  },
  {
    name: 'teamsUpdateTeam',
    description: 'Update a team name or settings.',
    tool: teamsUpdateTeam,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['group', 'rename'],
  },
  {
    name: 'teamsDeleteTeam',
    description: 'Delete a team and its group.',
    tool: teamsDeleteTeam,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['group', 'remove'],
  },
  {
    name: 'teamsArchiveTeam',
    description: 'Archive a team (read-only).',
    tool: teamsArchiveTeam,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['freeze', 'deactivate'],
  },
  {
    name: 'teamsUnarchiveTeam',
    description: 'Restore an archived team.',
    tool: teamsUnarchiveTeam,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['restore', 'activate'],
  },
  {
    name: 'teamsCloneTeam',
    description: 'Clone a team with selected parts.',
    tool: teamsCloneTeam,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['duplicate', 'copy'],
  },
  {
    name: 'teamsListChannels',
    description: 'List channels in a team.',
    tool: teamsListChannels,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['rooms', 'topics'],
  },
  {
    name: 'teamsGetChannel',
    description: 'Get one channel.',
    tool: teamsGetChannel,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['room', 'fetch'],
  },
  {
    name: 'teamsCreateChannel',
    description: 'Create a standard/private/shared channel.',
    tool: teamsCreateChannel,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['room', 'new'],
  },
  {
    name: 'teamsUpdateChannel',
    description: 'Update a channel.',
    tool: teamsUpdateChannel,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['room', 'rename'],
  },
  {
    name: 'teamsDeleteChannel',
    description: 'Delete a channel.',
    tool: teamsDeleteChannel,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['room', 'remove'],
  },
  {
    name: 'teamsListTeamMembers',
    description: 'List team members with roles.',
    tool: teamsListTeamMembers,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['people', 'owners'],
  },
  {
    name: 'teamsAddTeamMember',
    description: 'Add a member or owner to a team.',
    tool: teamsAddTeamMember,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['invite', 'join'],
  },
  {
    name: 'teamsRemoveTeamMember',
    description: 'Remove a member from a team.',
    tool: teamsRemoveTeamMember,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['kick', 'leave'],
  },
  {
    name: 'teamsUpdateTeamMember',
    description: 'Promote/demote a team member.',
    tool: teamsUpdateTeamMember,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['owner', 'role'],
  },
  {
    name: 'teamsListChannelMembers',
    description: 'List members with channel access.',
    tool: teamsListChannelMembers,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['people', 'access'],
  },
  {
    name: 'teamsAddChannelMember',
    description: 'Add a member to a private/shared channel.',
    tool: teamsAddChannelMember,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['invite', 'private'],
  },
  {
    name: 'teamsRemoveChannelMember',
    description: 'Remove a channel member.',
    tool: teamsRemoveChannelMember,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['kick'],
  },
  {
    name: 'teamsListTags',
    description: 'List teamwork tags in a team.',
    tool: teamsListTags,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['labels', 'mentions'],
  },
  {
    name: 'teamsCreateTag',
    description: 'Create a tag for group @mentions.',
    tool: teamsCreateTag,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['label', 'mention'],
  },
  {
    name: 'teamsDeleteTag',
    description: 'Delete a teamwork tag.',
    tool: teamsDeleteTag,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['label', 'remove'],
  },
  {
    name: 'teamsListTabs',
    description: 'List tabs pinned to a channel.',
    tool: teamsListTabs,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['apps', 'pins'],
  },
  {
    name: 'teamsAddTab',
    description: 'Pin an app tab to a channel.',
    tool: teamsAddTab,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['app', 'embed'],
  },
  {
    name: 'teamsUpdateTab',
    description: 'Update a channel tab.',
    tool: teamsUpdateTab,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['app', 'edit'],
  },
  {
    name: 'teamsDeleteTab',
    description: 'Remove a tab from a channel.',
    tool: teamsDeleteTab,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['app', 'remove'],
  },
  {
    name: 'teamsListInstalledApps',
    description: 'List apps installed in a team.',
    tool: teamsListInstalledApps,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['integrations'],
  },
  {
    name: 'teamsInstallApp',
    description: 'Install a catalog app into a team.',
    tool: teamsInstallApp,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['integration', 'add'],
  },
  {
    name: 'teamsUninstallApp',
    description: 'Remove an installed app.',
    tool: teamsUninstallApp,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['integration', 'remove'],
  },
  {
    name: 'teamsSendActivityNotification',
    description: 'Send an activity feed notification.',
    tool: teamsSendActivityNotification,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['alert', 'notify', 'feed'],
  },
  {
    name: 'teamsListChannelMessages',
    description: 'List top-level channel messages.',
    tool: teamsListChannelMessages,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['posts', 'history'],
  },
  {
    name: 'teamsGetChannelMessage',
    description: 'Get one channel message.',
    tool: teamsGetChannelMessage,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['post', 'fetch'],
  },
  {
    name: 'teamsSendChannelMessage',
    description: 'Post a message to a channel.',
    tool: teamsSendChannelMessage,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['post', 'announce'],
  },
  {
    name: 'teamsReplyChannelMessage',
    description: 'Reply in a channel thread.',
    tool: teamsReplyChannelMessage,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['thread', 'respond'],
  },
  {
    name: 'teamsListMessageReplies',
    description: 'List replies to a channel message.',
    tool: teamsListMessageReplies,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['thread', 'responses'],
  },
  {
    name: 'teamsUpdateChannelMessage',
    description: 'Edit a channel message.',
    tool: teamsUpdateChannelMessage,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['post', 'edit'],
  },
  {
    name: 'teamsDeleteChannelMessage',
    description: 'Soft-delete a channel message.',
    tool: teamsDeleteChannelMessage,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['post', 'remove'],
  },
  {
    name: 'teamsUndoDeleteChannelMessage',
    description: 'Restore a deleted channel message.',
    tool: teamsUndoDeleteChannelMessage,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['post', 'recover'],
  },
  {
    name: 'teamsListChats',
    description: 'List 1:1, group, and meeting chats.',
    tool: teamsListChats,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['dm', 'conversations'],
  },
  {
    name: 'teamsGetChat',
    description: 'Get one chat.',
    tool: teamsGetChat,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['dm', 'fetch'],
  },
  {
    name: 'teamsCreateChat',
    description: 'Start a 1:1 or group chat.',
    tool: teamsCreateChat,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['dm', 'new'],
  },
  {
    name: 'teamsUpdateChat',
    description: 'Update a group chat topic.',
    tool: teamsUpdateChat,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['dm', 'rename'],
  },
  {
    name: 'teamsDeleteChat',
    description: 'Delete a chat.',
    tool: teamsDeleteChat,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['dm', 'remove'],
  },
  {
    name: 'teamsListChatMessages',
    description: 'List messages in a chat.',
    tool: teamsListChatMessages,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['dm', 'history'],
  },
  {
    name: 'teamsGetChatMessage',
    description: 'Get one chat message.',
    tool: teamsGetChatMessage,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['dm', 'fetch'],
  },
  {
    name: 'teamsSendChatMessage',
    description: 'Send a message in a chat.',
    tool: teamsSendChatMessage,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['dm', 'im'],
  },
  {
    name: 'teamsUpdateChatMessage',
    description: 'Edit a chat message.',
    tool: teamsUpdateChatMessage,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['dm', 'edit'],
  },
  {
    name: 'teamsDeleteChatMessage',
    description: 'Delete a chat message.',
    tool: teamsDeleteChatMessage,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['dm', 'remove'],
  },
  {
    name: 'teamsListChatMembers',
    description: 'List chat members.',
    tool: teamsListChatMembers,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['participants'],
  },
  {
    name: 'teamsAddChatMember',
    description: 'Add a member to a group chat.',
    tool: teamsAddChatMember,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['invite', 'participant'],
  },
  {
    name: 'teamsRemoveChatMember',
    description: 'Remove a chat member.',
    tool: teamsRemoveChatMember,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['kick'],
  },
  {
    name: 'teamsListPinnedMessages',
    description: 'List pinned chat messages.',
    tool: teamsListPinnedMessages,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['highlights'],
  },
  {
    name: 'teamsPinChatMessage',
    description: 'Pin a chat message.',
    tool: teamsPinChatMessage,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['highlight'],
  },
  {
    name: 'teamsUnpinChatMessage',
    description: 'Unpin a chat message.',
    tool: teamsUnpinChatMessage,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['unhighlight'],
  },
  {
    name: 'teamsCreateOnlineMeeting',
    description: 'Create a Teams online meeting.',
    tool: teamsCreateOnlineMeeting,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['call', 'video', 'schedule'],
  },
  {
    name: 'teamsGetOnlineMeeting',
    description: 'Get one online meeting.',
    tool: teamsGetOnlineMeeting,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['call', 'fetch', 'link'],
  },
  {
    name: 'teamsUpdateOnlineMeeting',
    description: 'Update an online meeting.',
    tool: teamsUpdateOnlineMeeting,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['call', 'reschedule'],
  },
  {
    name: 'teamsDeleteOnlineMeeting',
    description: 'Delete an online meeting.',
    tool: teamsDeleteOnlineMeeting,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['call', 'cancel'],
  },
  {
    name: 'teamsListAttendanceReports',
    description: 'List meeting attendance reports.',
    tool: teamsListAttendanceReports,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['attendees', 'register'],
  },
  {
    name: 'teamsListAttendanceRecords',
    description: 'List per-attendee attendance records.',
    tool: teamsListAttendanceRecords,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['attendees', 'duration'],
  },
  {
    name: 'teamsListMeetingRecordings',
    description: 'List meeting recordings.',
    tool: teamsListMeetingRecordings,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['videos', 'playback'],
  },
  {
    name: 'teamsGetMeetingRecording',
    description: 'Get one meeting recording metadata.',
    tool: teamsGetMeetingRecording,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['video', 'fetch'],
  },
  {
    name: 'teamsGetPresence',
    description: 'Get user presence.',
    tool: teamsGetPresence,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['status', 'availability'],
  },
  {
    name: 'teamsSetPresence',
    description: 'Set user presence.',
    tool: teamsSetPresence,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['status', 'busy', 'away'],
  },
];
