// @ts-nocheck
import { nasaBrowseNeo, nasaGetNeoLookup, nasaSearchNearEarthObjects } from './neo.js';
import { nasaGetApod, nasaGetMarsRoverPhotos, nasaGetInsightWeather, nasaGetEpicNatural, nasaGetEpicNaturalDate, nasaGetEpicEnhanced, nasaGetEpicEnhancedDate, nasaGetEpicAerosol, nasaGetEpicAerosolDate, nasaGetEpicCloud, nasaGetEpicCloudDate, nasaListEpicNaturalDates, nasaListEpicEnhancedDates, nasaListEpicAerosolDates, nasaListEpicCloudDates } from './planetary.js';
import { nasaGetDonkiCme, nasaGetDonkiCmeAnalysis, nasaGetDonkiGst, nasaGetDonkiHss, nasaGetDonkiIps, nasaGetDonkiMpc, nasaGetDonkiNotifications, nasaGetDonkiRbe, nasaGetDonkiSep, nasaGetDonkiSolarFlares, nasaGetDonkiWsaEnlil } from './donki.js';
import { nasaGetTechportProject, nasaQueryExoplanetArchive, nasaSearchTechtransferSoftware, nasaGetImageAsset, nasaGetImageMetadata, nasaGetVideoCaptions, nasaSearchSvsVisualizations } from './imagery.js';
import { nasaGetEonetCategories, nasaGetEonetCategoryEvents, nasaGetEonetEvent, nasaGetEonetEvents, nasaGetEonetEventsAtom, nasaGetEonetEventsGeojson, nasaGetEonetEventsRss, nasaGetEonetLayers, nasaGetEonetMagnitudes, nasaGetEonetSources } from './eonet.js';
import { nasaGetCmrCollections, nasaGetCmrGranules, nasaGetLandingPage, nasaQueryCitation, nasaQueryCitations, nasaQueryCmrCollection, nasaQueryCmrCollections, nasaQueryCmrGranule, nasaQueryCmrGranules, nasaQueryCmrGrids, nasaQueryCmrService, nasaQueryCmrServices, nasaQueryCmrSubscription, nasaQueryCmrSubscriptions, nasaQueryCmrTool, nasaQueryCmrTools, nasaQueryCmrVariable, nasaQueryCollectionDraft, nasaQueryDataQualitySummaries, nasaQueryDataQualitySummary, nasaQueryOrderOption, nasaQueryOrderOptions, nasaQueryPermissions, nasaQueryProviders, nasaQueryTagDefinitions, nasaQueryToolDraft, nasaQueryVisualization, nasaQueryVisualizations, nasaDeleteAssociation, nasaDeleteCmrAcl, nasaRestoreCitationRevision, nasaRestoreCollectionRevision, nasaRestoreVisualizationRevision } from './cmr.js';
import { nasaGetCitation, nasaGetCitationDownloads, nasaDownloadCitationDocument, nasaGetCitationRevisionId, nasaGetCitationsAutocomplete, nasaGetCitationsRedistributions, nasaSearchCitations, nasaSearchPubspaceDocuments } from './ntrs.js';
import { nasaGetAgageData, nasaGetAgageDataByFileName, nasaGetAgageDataJsonForGraph, nasaGetAgageDataDownload, nasaGetAgageDataVersions, nasaGetCompounds, nasaGetStations, nasaGetDataFrequencies, nasaGetProcessingTypes } from './agage.js';
import { nasaGetDataByFileName, nasaGetTolnetDataJson, nasaGetTolnetDataJsonForGraph, nasaGetDocument, nasaGetDocumentDownload, nasaGetDocuments, nasaGetTolnetData, nasaGetTolnetDataCalendar, nasaGetFileTypes, nasaGetInstrumentGroups, nasaGetProductTypes } from './tolnet.js';
import { nasaGetOsdrBiospecimen, nasaListOsdrBiospecimens, nasaGetOsdrExperiment, nasaListOsdrExperiments, nasaGetOsdrHardware, nasaListOsdrHardware, nasaGetOsdrMetadata, nasaGetOsdrMission, nasaListOsdrMissions, nasaGetOsdrPayload, nasaListOsdrPayloads, nasaGetOsdrSubject, nasaListOsdrSubjects, nasaGetOsdrVehicle, nasaListOsdrVehicles, nasaGetGldsFiles, nasaSearchOsdr } from './osdr.js';
import { nasaCreateGraphRequest, nasaGetSatelliteLocations, nasaListGroundStations, nasaListObservatories, nasaListLocationsGseGeo } from './ssc.js';
import { nasaGetPowerClimatology, nasaGetPowerDaily, nasaGetPowerDailyRegional, nasaGetPowerMonthly, nasaGetPowerTemporalHourly } from './power.js';
import { nasaGetIcesat2Tracks, nasaGetLevel3Data } from './icesat2.js';

export {
    nasaBrowseNeo,
    nasaGetNeoLookup,
    nasaSearchNearEarthObjects,
    nasaGetApod,
    nasaGetMarsRoverPhotos,
    nasaGetInsightWeather,
    nasaGetEpicNatural,
    nasaGetEpicNaturalDate,
    nasaGetEpicEnhanced,
    nasaGetEpicEnhancedDate,
    nasaGetEpicAerosol,
    nasaGetEpicAerosolDate,
    nasaGetEpicCloud,
    nasaGetEpicCloudDate,
    nasaListEpicNaturalDates,
    nasaListEpicEnhancedDates,
    nasaListEpicAerosolDates,
    nasaListEpicCloudDates,
    nasaGetDonkiCme,
    nasaGetDonkiCmeAnalysis,
    nasaGetDonkiGst,
    nasaGetDonkiHss,
    nasaGetDonkiIps,
    nasaGetDonkiMpc,
    nasaGetDonkiNotifications,
    nasaGetDonkiRbe,
    nasaGetDonkiSep,
    nasaGetDonkiSolarFlares,
    nasaGetDonkiWsaEnlil,
    nasaGetTechportProject,
    nasaQueryExoplanetArchive,
    nasaSearchTechtransferSoftware,
    nasaGetImageAsset,
    nasaGetImageMetadata,
    nasaGetVideoCaptions,
    nasaSearchSvsVisualizations,
    nasaGetEonetCategories,
    nasaGetEonetCategoryEvents,
    nasaGetEonetEvent,
    nasaGetEonetEvents,
    nasaGetEonetEventsAtom,
    nasaGetEonetEventsGeojson,
    nasaGetEonetEventsRss,
    nasaGetEonetLayers,
    nasaGetEonetMagnitudes,
    nasaGetEonetSources,
    nasaGetCmrCollections,
    nasaGetCmrGranules,
    nasaGetLandingPage,
    nasaQueryCitation,
    nasaQueryCitations,
    nasaQueryCmrCollection,
    nasaQueryCmrCollections,
    nasaQueryCmrGranule,
    nasaQueryCmrGranules,
    nasaQueryCmrGrids,
    nasaQueryCmrService,
    nasaQueryCmrServices,
    nasaQueryCmrSubscription,
    nasaQueryCmrSubscriptions,
    nasaQueryCmrTool,
    nasaQueryCmrTools,
    nasaQueryCmrVariable,
    nasaQueryCollectionDraft,
    nasaQueryDataQualitySummaries,
    nasaQueryDataQualitySummary,
    nasaQueryOrderOption,
    nasaQueryOrderOptions,
    nasaQueryPermissions,
    nasaQueryProviders,
    nasaQueryTagDefinitions,
    nasaQueryToolDraft,
    nasaQueryVisualization,
    nasaQueryVisualizations,
    nasaDeleteAssociation,
    nasaDeleteCmrAcl,
    nasaRestoreCitationRevision,
    nasaRestoreCollectionRevision,
    nasaRestoreVisualizationRevision,
    nasaGetCitation,
    nasaGetCitationDownloads,
    nasaDownloadCitationDocument,
    nasaGetCitationRevisionId,
    nasaGetCitationsAutocomplete,
    nasaGetCitationsRedistributions,
    nasaSearchCitations,
    nasaSearchPubspaceDocuments,
    nasaGetAgageData,
    nasaGetAgageDataByFileName,
    nasaGetAgageDataJsonForGraph,
    nasaGetAgageDataDownload,
    nasaGetAgageDataVersions,
    nasaGetCompounds,
    nasaGetStations,
    nasaGetDataFrequencies,
    nasaGetProcessingTypes,
    nasaGetDataByFileName,
    nasaGetTolnetDataJson,
    nasaGetTolnetDataJsonForGraph,
    nasaGetDocument,
    nasaGetDocumentDownload,
    nasaGetDocuments,
    nasaGetTolnetData,
    nasaGetTolnetDataCalendar,
    nasaGetFileTypes,
    nasaGetInstrumentGroups,
    nasaGetProductTypes,
    nasaGetOsdrBiospecimen,
    nasaListOsdrBiospecimens,
    nasaGetOsdrExperiment,
    nasaListOsdrExperiments,
    nasaGetOsdrHardware,
    nasaListOsdrHardware,
    nasaGetOsdrMetadata,
    nasaGetOsdrMission,
    nasaListOsdrMissions,
    nasaGetOsdrPayload,
    nasaListOsdrPayloads,
    nasaGetOsdrSubject,
    nasaListOsdrSubjects,
    nasaGetOsdrVehicle,
    nasaListOsdrVehicles,
    nasaGetGldsFiles,
    nasaSearchOsdr,
    nasaCreateGraphRequest,
    nasaGetSatelliteLocations,
    nasaListGroundStations,
    nasaListObservatories,
    nasaListLocationsGseGeo,
    nasaGetPowerClimatology,
    nasaGetPowerDaily,
    nasaGetPowerDailyRegional,
    nasaGetPowerMonthly,
    nasaGetPowerTemporalHourly,
    nasaGetIcesat2Tracks,
    nasaGetLevel3Data,
};

export const nasaTools = [
    {
        name: "nasaBrowseNeo",
        description: nasaBrowseNeo.description!,
        requiredAuth: 'nasaApiKey' as const,
        tool: nasaBrowseNeo,
        scope: "read" as const,
    },
    {
        name: "nasaGetNeoLookup",
        description: nasaGetNeoLookup.description!,
        requiredAuth: 'nasaApiKey' as const,
        tool: nasaGetNeoLookup,
        scope: "read" as const,
    },
    {
        name: "nasaSearchNearEarthObjects",
        description: nasaSearchNearEarthObjects.description!,
        requiredAuth: 'nasaApiKey' as const,
        tool: nasaSearchNearEarthObjects,
        scope: "read" as const,
    },
    {
        name: "nasaGetApod",
        description: nasaGetApod.description!,
        requiredAuth: 'nasaApiKey' as const,
        tool: nasaGetApod,
        scope: "read" as const,
    },
    {
        name: "nasaGetMarsRoverPhotos",
        description: nasaGetMarsRoverPhotos.description!,
        requiredAuth: 'nasaApiKey' as const,
        tool: nasaGetMarsRoverPhotos,
        scope: "read" as const,
    },
    {
        name: "nasaGetInsightWeather",
        description: nasaGetInsightWeather.description!,
        requiredAuth: 'nasaApiKey' as const,
        tool: nasaGetInsightWeather,
        scope: "read" as const,
    },
    {
        name: "nasaGetEpicNatural",
        description: nasaGetEpicNatural.description!,
        requiredAuth: 'nasaApiKey' as const,
        tool: nasaGetEpicNatural,
        scope: "read" as const,
    },
    {
        name: "nasaGetEpicNaturalDate",
        description: nasaGetEpicNaturalDate.description!,
        requiredAuth: 'nasaApiKey' as const,
        tool: nasaGetEpicNaturalDate,
        scope: "read" as const,
    },
    {
        name: "nasaGetEpicEnhanced",
        description: nasaGetEpicEnhanced.description!,
        requiredAuth: 'nasaApiKey' as const,
        tool: nasaGetEpicEnhanced,
        scope: "read" as const,
    },
    {
        name: "nasaGetEpicEnhancedDate",
        description: nasaGetEpicEnhancedDate.description!,
        requiredAuth: 'nasaApiKey' as const,
        tool: nasaGetEpicEnhancedDate,
        scope: "read" as const,
    },
    {
        name: "nasaGetEpicAerosol",
        description: nasaGetEpicAerosol.description!,
        requiredAuth: 'nasaApiKey' as const,
        tool: nasaGetEpicAerosol,
        scope: "read" as const,
    },
    {
        name: "nasaGetEpicAerosolDate",
        description: nasaGetEpicAerosolDate.description!,
        requiredAuth: 'nasaApiKey' as const,
        tool: nasaGetEpicAerosolDate,
        scope: "read" as const,
    },
    {
        name: "nasaGetEpicCloud",
        description: nasaGetEpicCloud.description!,
        requiredAuth: 'nasaApiKey' as const,
        tool: nasaGetEpicCloud,
        scope: "read" as const,
    },
    {
        name: "nasaGetEpicCloudDate",
        description: nasaGetEpicCloudDate.description!,
        requiredAuth: 'nasaApiKey' as const,
        tool: nasaGetEpicCloudDate,
        scope: "read" as const,
    },
    {
        name: "nasaListEpicNaturalDates",
        description: nasaListEpicNaturalDates.description!,
        requiredAuth: 'nasaApiKey' as const,
        tool: nasaListEpicNaturalDates,
        scope: "read" as const,
    },
    {
        name: "nasaListEpicEnhancedDates",
        description: nasaListEpicEnhancedDates.description!,
        requiredAuth: 'nasaApiKey' as const,
        tool: nasaListEpicEnhancedDates,
        scope: "read" as const,
    },
    {
        name: "nasaListEpicAerosolDates",
        description: nasaListEpicAerosolDates.description!,
        requiredAuth: 'nasaApiKey' as const,
        tool: nasaListEpicAerosolDates,
        scope: "read" as const,
    },
    {
        name: "nasaListEpicCloudDates",
        description: nasaListEpicCloudDates.description!,
        requiredAuth: 'nasaApiKey' as const,
        tool: nasaListEpicCloudDates,
        scope: "read" as const,
    },
    {
        name: "nasaGetDonkiCme",
        description: nasaGetDonkiCme.description!,
        requiredAuth: 'nasaApiKey' as const,
        tool: nasaGetDonkiCme,
        scope: "read" as const,
    },
    {
        name: "nasaGetDonkiCmeAnalysis",
        description: nasaGetDonkiCmeAnalysis.description!,
        requiredAuth: 'nasaApiKey' as const,
        tool: nasaGetDonkiCmeAnalysis,
        scope: "read" as const,
    },
    {
        name: "nasaGetDonkiGst",
        description: nasaGetDonkiGst.description!,
        requiredAuth: 'nasaApiKey' as const,
        tool: nasaGetDonkiGst,
        scope: "read" as const,
    },
    {
        name: "nasaGetDonkiHss",
        description: nasaGetDonkiHss.description!,
        requiredAuth: 'nasaApiKey' as const,
        tool: nasaGetDonkiHss,
        scope: "read" as const,
    },
    {
        name: "nasaGetDonkiIps",
        description: nasaGetDonkiIps.description!,
        requiredAuth: 'nasaApiKey' as const,
        tool: nasaGetDonkiIps,
        scope: "read" as const,
    },
    {
        name: "nasaGetDonkiMpc",
        description: nasaGetDonkiMpc.description!,
        requiredAuth: 'nasaApiKey' as const,
        tool: nasaGetDonkiMpc,
        scope: "read" as const,
    },
    {
        name: "nasaGetDonkiNotifications",
        description: nasaGetDonkiNotifications.description!,
        requiredAuth: 'nasaApiKey' as const,
        tool: nasaGetDonkiNotifications,
        scope: "read" as const,
    },
    {
        name: "nasaGetDonkiRbe",
        description: nasaGetDonkiRbe.description!,
        requiredAuth: 'nasaApiKey' as const,
        tool: nasaGetDonkiRbe,
        scope: "read" as const,
    },
    {
        name: "nasaGetDonkiSep",
        description: nasaGetDonkiSep.description!,
        requiredAuth: 'nasaApiKey' as const,
        tool: nasaGetDonkiSep,
        scope: "read" as const,
    },
    {
        name: "nasaGetDonkiSolarFlares",
        description: nasaGetDonkiSolarFlares.description!,
        requiredAuth: 'nasaApiKey' as const,
        tool: nasaGetDonkiSolarFlares,
        scope: "read" as const,
    },
    {
        name: "nasaGetDonkiWsaEnlil",
        description: nasaGetDonkiWsaEnlil.description!,
        requiredAuth: 'nasaApiKey' as const,
        tool: nasaGetDonkiWsaEnlil,
        scope: "read" as const,
    },
    {
        name: "nasaGetTechportProject",
        description: nasaGetTechportProject.description!,
        requiredAuth: 'nasaApiKey' as const,
        tool: nasaGetTechportProject,
        scope: "read" as const,
    },
    {
        name: "nasaQueryExoplanetArchive",
        description: nasaQueryExoplanetArchive.description!,
        tool: nasaQueryExoplanetArchive,
        scope: "read" as const,
    },
    {
        name: "nasaSearchTechtransferSoftware",
        description: nasaSearchTechtransferSoftware.description!,
        requiredAuth: 'nasaApiKey' as const,
        tool: nasaSearchTechtransferSoftware,
        scope: "read" as const,
    },
    {
        name: "nasaGetImageAsset",
        description: nasaGetImageAsset.description!,
        tool: nasaGetImageAsset,
        scope: "read" as const,
    },
    {
        name: "nasaGetImageMetadata",
        description: nasaGetImageMetadata.description!,
        tool: nasaGetImageMetadata,
        scope: "read" as const,
    },
    {
        name: "nasaGetVideoCaptions",
        description: nasaGetVideoCaptions.description!,
        tool: nasaGetVideoCaptions,
        scope: "read" as const,
    },
    {
        name: "nasaSearchSvsVisualizations",
        description: nasaSearchSvsVisualizations.description!,
        tool: nasaSearchSvsVisualizations,
        scope: "read" as const,
    },
    {
        name: "nasaGetEonetCategories",
        description: nasaGetEonetCategories.description!,
        tool: nasaGetEonetCategories,
        scope: "read" as const,
    },
    {
        name: "nasaGetEonetCategoryEvents",
        description: nasaGetEonetCategoryEvents.description!,
        tool: nasaGetEonetCategoryEvents,
        scope: "read" as const,
    },
    {
        name: "nasaGetEonetEvent",
        description: nasaGetEonetEvent.description!,
        tool: nasaGetEonetEvent,
        scope: "read" as const,
    },
    {
        name: "nasaGetEonetEvents",
        description: nasaGetEonetEvents.description!,
        tool: nasaGetEonetEvents,
        scope: "read" as const,
    },
    {
        name: "nasaGetEonetEventsAtom",
        description: nasaGetEonetEventsAtom.description!,
        tool: nasaGetEonetEventsAtom,
        scope: "read" as const,
    },
    {
        name: "nasaGetEonetEventsGeojson",
        description: nasaGetEonetEventsGeojson.description!,
        tool: nasaGetEonetEventsGeojson,
        scope: "read" as const,
    },
    {
        name: "nasaGetEonetEventsRss",
        description: nasaGetEonetEventsRss.description!,
        tool: nasaGetEonetEventsRss,
        scope: "read" as const,
    },
    {
        name: "nasaGetEonetLayers",
        description: nasaGetEonetLayers.description!,
        tool: nasaGetEonetLayers,
        scope: "read" as const,
    },
    {
        name: "nasaGetEonetMagnitudes",
        description: nasaGetEonetMagnitudes.description!,
        tool: nasaGetEonetMagnitudes,
        scope: "read" as const,
    },
    {
        name: "nasaGetEonetSources",
        description: nasaGetEonetSources.description!,
        tool: nasaGetEonetSources,
        scope: "read" as const,
    },
    {
        name: "nasaGetCmrCollections",
        description: nasaGetCmrCollections.description!,
        tool: nasaGetCmrCollections,
        scope: "read" as const,
    },
    {
        name: "nasaGetCmrGranules",
        description: nasaGetCmrGranules.description!,
        tool: nasaGetCmrGranules,
        scope: "read" as const,
    },
    {
        name: "nasaGetLandingPage",
        description: nasaGetLandingPage.description!,
        tool: nasaGetLandingPage,
        scope: "read" as const,
    },
    {
        name: "nasaQueryCitation",
        description: nasaQueryCitation.description!,
        tool: nasaQueryCitation,
        scope: "read" as const,
    },
    {
        name: "nasaQueryCitations",
        description: nasaQueryCitations.description!,
        tool: nasaQueryCitations,
        scope: "read" as const,
    },
    {
        name: "nasaQueryCmrCollection",
        description: nasaQueryCmrCollection.description!,
        tool: nasaQueryCmrCollection,
        scope: "read" as const,
    },
    {
        name: "nasaQueryCmrCollections",
        description: nasaQueryCmrCollections.description!,
        tool: nasaQueryCmrCollections,
        scope: "read" as const,
    },
    {
        name: "nasaQueryCmrGranule",
        description: nasaQueryCmrGranule.description!,
        tool: nasaQueryCmrGranule,
        scope: "read" as const,
    },
    {
        name: "nasaQueryCmrGranules",
        description: nasaQueryCmrGranules.description!,
        tool: nasaQueryCmrGranules,
        scope: "read" as const,
    },
    {
        name: "nasaQueryCmrGrids",
        description: nasaQueryCmrGrids.description!,
        tool: nasaQueryCmrGrids,
        scope: "read" as const,
    },
    {
        name: "nasaQueryCmrService",
        description: nasaQueryCmrService.description!,
        tool: nasaQueryCmrService,
        scope: "read" as const,
    },
    {
        name: "nasaQueryCmrServices",
        description: nasaQueryCmrServices.description!,
        tool: nasaQueryCmrServices,
        scope: "read" as const,
    },
    {
        name: "nasaQueryCmrSubscription",
        description: nasaQueryCmrSubscription.description!,
        tool: nasaQueryCmrSubscription,
        scope: "read" as const,
    },
    {
        name: "nasaQueryCmrSubscriptions",
        description: nasaQueryCmrSubscriptions.description!,
        tool: nasaQueryCmrSubscriptions,
        scope: "read" as const,
    },
    {
        name: "nasaQueryCmrTool",
        description: nasaQueryCmrTool.description!,
        tool: nasaQueryCmrTool,
        scope: "read" as const,
    },
    {
        name: "nasaQueryCmrTools",
        description: nasaQueryCmrTools.description!,
        tool: nasaQueryCmrTools,
        scope: "read" as const,
    },
    {
        name: "nasaQueryCmrVariable",
        description: nasaQueryCmrVariable.description!,
        tool: nasaQueryCmrVariable,
        scope: "read" as const,
    },
    {
        name: "nasaQueryCollectionDraft",
        description: nasaQueryCollectionDraft.description!,
        tool: nasaQueryCollectionDraft,
        scope: "read" as const,
    },
    {
        name: "nasaQueryDataQualitySummaries",
        description: nasaQueryDataQualitySummaries.description!,
        tool: nasaQueryDataQualitySummaries,
        scope: "read" as const,
    },
    {
        name: "nasaQueryDataQualitySummary",
        description: nasaQueryDataQualitySummary.description!,
        tool: nasaQueryDataQualitySummary,
        scope: "read" as const,
    },
    {
        name: "nasaQueryOrderOption",
        description: nasaQueryOrderOption.description!,
        tool: nasaQueryOrderOption,
        scope: "read" as const,
    },
    {
        name: "nasaQueryOrderOptions",
        description: nasaQueryOrderOptions.description!,
        tool: nasaQueryOrderOptions,
        scope: "read" as const,
    },
    {
        name: "nasaQueryPermissions",
        description: nasaQueryPermissions.description!,
        tool: nasaQueryPermissions,
        scope: "read" as const,
    },
    {
        name: "nasaQueryProviders",
        description: nasaQueryProviders.description!,
        tool: nasaQueryProviders,
        scope: "read" as const,
    },
    {
        name: "nasaQueryTagDefinitions",
        description: nasaQueryTagDefinitions.description!,
        tool: nasaQueryTagDefinitions,
        scope: "read" as const,
    },
    {
        name: "nasaQueryToolDraft",
        description: nasaQueryToolDraft.description!,
        tool: nasaQueryToolDraft,
        scope: "read" as const,
    },
    {
        name: "nasaQueryVisualization",
        description: nasaQueryVisualization.description!,
        tool: nasaQueryVisualization,
        scope: "read" as const,
    },
    {
        name: "nasaQueryVisualizations",
        description: nasaQueryVisualizations.description!,
        tool: nasaQueryVisualizations,
        scope: "read" as const,
    },
    {
        name: "nasaDeleteAssociation",
        description: nasaDeleteAssociation.description!,
        tool: nasaDeleteAssociation,
        scope: "delete" as const,
    },
    {
        name: "nasaDeleteCmrAcl",
        description: nasaDeleteCmrAcl.description!,
        tool: nasaDeleteCmrAcl,
        scope: "delete" as const,
    },
    {
        name: "nasaRestoreCitationRevision",
        description: nasaRestoreCitationRevision.description!,
        tool: nasaRestoreCitationRevision,
        scope: "write" as const,
    },
    {
        name: "nasaRestoreCollectionRevision",
        description: nasaRestoreCollectionRevision.description!,
        tool: nasaRestoreCollectionRevision,
        scope: "write" as const,
    },
    {
        name: "nasaRestoreVisualizationRevision",
        description: nasaRestoreVisualizationRevision.description!,
        tool: nasaRestoreVisualizationRevision,
        scope: "write" as const,
    },
    {
        name: "nasaGetCitation",
        description: nasaGetCitation.description!,
        tool: nasaGetCitation,
        scope: "read" as const,
    },
    {
        name: "nasaGetCitationDownloads",
        description: nasaGetCitationDownloads.description!,
        tool: nasaGetCitationDownloads,
        scope: "read" as const,
    },
    {
        name: "nasaDownloadCitationDocument",
        description: nasaDownloadCitationDocument.description!,
        tool: nasaDownloadCitationDocument,
        scope: "read" as const,
    },
    {
        name: "nasaGetCitationRevisionId",
        description: nasaGetCitationRevisionId.description!,
        tool: nasaGetCitationRevisionId,
        scope: "read" as const,
    },
    {
        name: "nasaGetCitationsAutocomplete",
        description: nasaGetCitationsAutocomplete.description!,
        tool: nasaGetCitationsAutocomplete,
        scope: "read" as const,
    },
    {
        name: "nasaGetCitationsRedistributions",
        description: nasaGetCitationsRedistributions.description!,
        tool: nasaGetCitationsRedistributions,
        scope: "read" as const,
    },
    {
        name: "nasaSearchCitations",
        description: nasaSearchCitations.description!,
        tool: nasaSearchCitations,
        scope: "read" as const,
    },
    {
        name: "nasaSearchPubspaceDocuments",
        description: nasaSearchPubspaceDocuments.description!,
        tool: nasaSearchPubspaceDocuments,
        scope: "read" as const,
    },
    {
        name: "nasaGetAgageData",
        description: nasaGetAgageData.description!,
        tool: nasaGetAgageData,
        scope: "read" as const,
    },
    {
        name: "nasaGetAgageDataByFileName",
        description: nasaGetAgageDataByFileName.description!,
        tool: nasaGetAgageDataByFileName,
        scope: "read" as const,
    },
    {
        name: "nasaGetAgageDataJsonForGraph",
        description: nasaGetAgageDataJsonForGraph.description!,
        tool: nasaGetAgageDataJsonForGraph,
        scope: "read" as const,
    },
    {
        name: "nasaGetAgageDataDownload",
        description: nasaGetAgageDataDownload.description!,
        tool: nasaGetAgageDataDownload,
        scope: "read" as const,
    },
    {
        name: "nasaGetAgageDataVersions",
        description: nasaGetAgageDataVersions.description!,
        tool: nasaGetAgageDataVersions,
        scope: "read" as const,
    },
    {
        name: "nasaGetCompounds",
        description: nasaGetCompounds.description!,
        tool: nasaGetCompounds,
        scope: "read" as const,
    },
    {
        name: "nasaGetStations",
        description: nasaGetStations.description!,
        tool: nasaGetStations,
        scope: "read" as const,
    },
    {
        name: "nasaGetDataFrequencies",
        description: nasaGetDataFrequencies.description!,
        tool: nasaGetDataFrequencies,
        scope: "read" as const,
    },
    {
        name: "nasaGetProcessingTypes",
        description: nasaGetProcessingTypes.description!,
        tool: nasaGetProcessingTypes,
        scope: "read" as const,
    },
    {
        name: "nasaGetDataByFileName",
        description: nasaGetDataByFileName.description!,
        tool: nasaGetDataByFileName,
        scope: "read" as const,
    },
    {
        name: "nasaGetTolnetDataJson",
        description: nasaGetTolnetDataJson.description!,
        tool: nasaGetTolnetDataJson,
        scope: "read" as const,
    },
    {
        name: "nasaGetTolnetDataJsonForGraph",
        description: nasaGetTolnetDataJsonForGraph.description!,
        tool: nasaGetTolnetDataJsonForGraph,
        scope: "read" as const,
    },
    {
        name: "nasaGetDocument",
        description: nasaGetDocument.description!,
        tool: nasaGetDocument,
        scope: "read" as const,
    },
    {
        name: "nasaGetDocumentDownload",
        description: nasaGetDocumentDownload.description!,
        tool: nasaGetDocumentDownload,
        scope: "read" as const,
    },
    {
        name: "nasaGetDocuments",
        description: nasaGetDocuments.description!,
        tool: nasaGetDocuments,
        scope: "read" as const,
    },
    {
        name: "nasaGetTolnetData",
        description: nasaGetTolnetData.description!,
        tool: nasaGetTolnetData,
        scope: "read" as const,
    },
    {
        name: "nasaGetTolnetDataCalendar",
        description: nasaGetTolnetDataCalendar.description!,
        tool: nasaGetTolnetDataCalendar,
        scope: "read" as const,
    },
    {
        name: "nasaGetFileTypes",
        description: nasaGetFileTypes.description!,
        tool: nasaGetFileTypes,
        scope: "read" as const,
    },
    {
        name: "nasaGetInstrumentGroups",
        description: nasaGetInstrumentGroups.description!,
        tool: nasaGetInstrumentGroups,
        scope: "read" as const,
    },
    {
        name: "nasaGetProductTypes",
        description: nasaGetProductTypes.description!,
        tool: nasaGetProductTypes,
        scope: "read" as const,
    },
    {
        name: "nasaGetOsdrBiospecimen",
        description: nasaGetOsdrBiospecimen.description!,
        tool: nasaGetOsdrBiospecimen,
        scope: "read" as const,
    },
    {
        name: "nasaListOsdrBiospecimens",
        description: nasaListOsdrBiospecimens.description!,
        tool: nasaListOsdrBiospecimens,
        scope: "read" as const,
    },
    {
        name: "nasaGetOsdrExperiment",
        description: nasaGetOsdrExperiment.description!,
        tool: nasaGetOsdrExperiment,
        scope: "read" as const,
    },
    {
        name: "nasaListOsdrExperiments",
        description: nasaListOsdrExperiments.description!,
        tool: nasaListOsdrExperiments,
        scope: "read" as const,
    },
    {
        name: "nasaGetOsdrHardware",
        description: nasaGetOsdrHardware.description!,
        tool: nasaGetOsdrHardware,
        scope: "read" as const,
    },
    {
        name: "nasaListOsdrHardware",
        description: nasaListOsdrHardware.description!,
        tool: nasaListOsdrHardware,
        scope: "read" as const,
    },
    {
        name: "nasaGetOsdrMetadata",
        description: nasaGetOsdrMetadata.description!,
        tool: nasaGetOsdrMetadata,
        scope: "read" as const,
    },
    {
        name: "nasaGetOsdrMission",
        description: nasaGetOsdrMission.description!,
        tool: nasaGetOsdrMission,
        scope: "read" as const,
    },
    {
        name: "nasaListOsdrMissions",
        description: nasaListOsdrMissions.description!,
        tool: nasaListOsdrMissions,
        scope: "read" as const,
    },
    {
        name: "nasaGetOsdrPayload",
        description: nasaGetOsdrPayload.description!,
        tool: nasaGetOsdrPayload,
        scope: "read" as const,
    },
    {
        name: "nasaListOsdrPayloads",
        description: nasaListOsdrPayloads.description!,
        tool: nasaListOsdrPayloads,
        scope: "read" as const,
    },
    {
        name: "nasaGetOsdrSubject",
        description: nasaGetOsdrSubject.description!,
        tool: nasaGetOsdrSubject,
        scope: "read" as const,
    },
    {
        name: "nasaListOsdrSubjects",
        description: nasaListOsdrSubjects.description!,
        tool: nasaListOsdrSubjects,
        scope: "read" as const,
    },
    {
        name: "nasaGetOsdrVehicle",
        description: nasaGetOsdrVehicle.description!,
        tool: nasaGetOsdrVehicle,
        scope: "read" as const,
    },
    {
        name: "nasaListOsdrVehicles",
        description: nasaListOsdrVehicles.description!,
        tool: nasaListOsdrVehicles,
        scope: "read" as const,
    },
    {
        name: "nasaGetGldsFiles",
        description: nasaGetGldsFiles.description!,
        tool: nasaGetGldsFiles,
        scope: "read" as const,
    },
    {
        name: "nasaSearchOsdr",
        description: nasaSearchOsdr.description!,
        tool: nasaSearchOsdr,
        scope: "read" as const,
    },
    {
        name: "nasaCreateGraphRequest",
        description: nasaCreateGraphRequest.description!,
        tool: nasaCreateGraphRequest,
        scope: "write" as const,
    },
    {
        name: "nasaGetSatelliteLocations",
        description: nasaGetSatelliteLocations.description!,
        tool: nasaGetSatelliteLocations,
        scope: "read" as const,
    },
    {
        name: "nasaListGroundStations",
        description: nasaListGroundStations.description!,
        tool: nasaListGroundStations,
        scope: "read" as const,
    },
    {
        name: "nasaListObservatories",
        description: nasaListObservatories.description!,
        tool: nasaListObservatories,
        scope: "read" as const,
    },
    {
        name: "nasaListLocationsGseGeo",
        description: nasaListLocationsGseGeo.description!,
        tool: nasaListLocationsGseGeo,
        scope: "read" as const,
    },
    {
        name: "nasaGetPowerClimatology",
        description: nasaGetPowerClimatology.description!,
        tool: nasaGetPowerClimatology,
        scope: "read" as const,
    },
    {
        name: "nasaGetPowerDaily",
        description: nasaGetPowerDaily.description!,
        tool: nasaGetPowerDaily,
        scope: "read" as const,
    },
    {
        name: "nasaGetPowerDailyRegional",
        description: nasaGetPowerDailyRegional.description!,
        tool: nasaGetPowerDailyRegional,
        scope: "read" as const,
    },
    {
        name: "nasaGetPowerMonthly",
        description: nasaGetPowerMonthly.description!,
        tool: nasaGetPowerMonthly,
        scope: "read" as const,
    },
    {
        name: "nasaGetPowerTemporalHourly",
        description: nasaGetPowerTemporalHourly.description!,
        tool: nasaGetPowerTemporalHourly,
        scope: "read" as const,
    },
    {
        name: "nasaGetIcesat2Tracks",
        description: nasaGetIcesat2Tracks.description!,
        tool: nasaGetIcesat2Tracks,
        scope: "read" as const,
    },
    {
        name: "nasaGetLevel3Data",
        description: nasaGetLevel3Data.description!,
        tool: nasaGetLevel3Data,
        scope: "read" as const,
    },
];
