// @ts-nocheck
import {
  salesforceAccountCreationWithContentTypeOption,
  salesforceCreateAccount,
  salesforceDeleteAccount,
  salesforceFetchAccountByIdWithQuery,
  salesforceGetAccount,
  salesforceListAccounts,
  salesforceRemoveAccountByUniqueIdentifier,
  salesforceRetrieveAccountDataAndErrorResponses,
  salesforceUpdateAccount,
  salesforceUpdateAccountObjectById,
} from './accounts.js';
import {
  salesforceExecuteGlobalQuickAction,
  salesforceExecuteInvocableAction,
  salesforceExecuteSobjectQuickAction,
  salesforceGetQuickActions,
  salesforceGetSObjectQuickActionDefaultValues,
  salesforceGetSobjectQuickActionDefaultValues,
  salesforceHeadActionsCustom,
  salesforceHeadActionsStandard,
  salesforceHeadAppmenuSalesforce1,
  salesforceHeadProcessRulesSObject,
  salesforceHeadQuickActions,
  salesforceHeadSobjectQuickActionDefaultValues,
  salesforceHeadSobjectsGlobalDescribeLayouts,
  salesforceHeadSobjectsQuickAction,
  salesforceListCustomInvocableActions,
  salesforceListStandardInvocableActions,
} from './actions.js';
import {
  salesforceCreateNote,
  salesforceCreateNoteRecordWithContentTypeHeader,
  salesforceCreateTask,
  salesforceDeleteNote,
  salesforceGetNote,
  salesforceGetNoteByIdWithFields,
  salesforceListNotes,
  salesforceLogCall,
  salesforceLogEmailActivity,
  salesforceRemoveNoteObjectById,
  salesforceUpdateNote,
  salesforceUpdateSpecificNoteById,
  salesforceUpdateTask,
} from './activities.js';
import {
  salesforceCloseOrAbortJob,
  salesforceCreateBulkIngestJob,
  salesforceCreateBulkQueryJob,
  salesforceDeleteJobQuery,
  salesforceGetJobFailedRecordResults,
  salesforceGetJobSuccessfulRecordResults,
  salesforceGetJobUnprocessedRecordResults,
  salesforceGetQueryJobInfo,
  salesforceGetQueryJobResults,
  salesforceUploadJobData,
} from './bulk.js';
import {
  salesforceAddContactToCampaign,
  salesforceAddLeadToCampaign,
  salesforceCreateCampaign,
  salesforceCreateCampaignRecordViaPost,
  salesforceDeleteCampaign,
  salesforceGetCampaign,
  salesforceListCampaigns,
  salesforceRemoveCampaignObjectById,
  salesforceRetrieveCampaignDataWithErrorHandling,
  salesforceRetrieveSpecificCampaignObjectDetails,
  salesforceUpdateCampaign,
  salesforceUpdateCampaignByIdWithJson,
} from './campaigns.js';
import {
  salesforceAssociateContactToAccount,
  salesforceCreateContact,
  salesforceCreateNewContactWithJsonHeader,
  salesforceDeleteContact,
  salesforceGetContact,
  salesforceGetContactById,
  salesforceListContacts,
  salesforceQueryContactsByName,
  salesforceRemoveASpecificContactById,
  salesforceRetrieveContactInfoWithStandardResponses,
  salesforceRetrieveSpecificContactById,
  salesforceUpdateContact,
  salesforceUpdateContactById,
} from './contacts.js';
import {
  salesforceSendEmail,
  salesforceSendEmailFromTemplate,
  salesforceSendMassEmail,
} from './custom-actions.js';
import { salesforceGetFileContent, salesforceUploadFile } from './custom-files.js';
import {
  salesforceGetAllCustomObjects,
  salesforceGetListViewMetadataBatch,
  salesforceGetUserInfo,
  salesforceWhoAmI,
  salesforceSetUserPassword,
} from './custom-platform.js';
import {
  salesforceCloneRecord,
  salesforceCloneOpportunityWithProducts,
  salesforceRemoveFromCampaign,
  salesforceMassTransferOwnership,
  salesforceCompleteTask,
  salesforceApplyLeadAssignmentRules,
} from './custom-records.js';
import {
  salesforceParameterizedSearch,
  salesforceSearchAccounts,
  salesforceSearchContacts,
  salesforceSearchLeads,
  salesforceSearchCampaigns,
  salesforceSearchOpportunities,
  salesforceSearchNotes,
  salesforceSearchTasks,
  salesforceListEmailTemplates,
} from './custom-search.js';
import {
  salesforceGetListViewResults,
  salesforceGetSobjectListView,
  salesforceGetSobjectListViews,
  salesforceRetrieveNoteObjectInformation,
} from './describe.js';
import {
  salesforceCreateLead,
  salesforceCreateLeadWithSpecifiedContentType,
  salesforceDeleteALeadObjectByItsId,
  salesforceDeleteLead,
  salesforceGetLead,
  salesforceListLeads,
  salesforceRetrieveLeadById,
  salesforceRetrieveLeadDataWithVariousResponses,
  salesforceUpdateLead,
  salesforceUpdateLeadByIdWithJsonPayload,
} from './leads.js';
import { salesforceCreateCustomField, salesforceCreateCustomObject } from './metadata.js';
import {
  salesforceAddOpportunityLineItem,
  salesforceCreateOpportunity,
  salesforceCreateOpportunityRecord,
  salesforceDeleteOpportunity,
  salesforceGetOpportunity,
  salesforceListOpportunities,
  salesforceListPricebookEntries,
  salesforceListPricebooks,
  salesforceRemoveOpportunityById,
  salesforceRetrieveOpportunitiesData,
  salesforceRetrieveOpportunityByIdWithOptionalFields,
  salesforceUpdateOpportunity,
  salesforceUpdateOpportunityById,
} from './opportunities.js';
import {
  salesforceDeleteFile,
  salesforceGetApi,
  salesforceGetChatterResources,
  salesforceGetConsentAction,
  salesforceGetFileInformation,
  salesforceGetFileShares,
  salesforceGetOrgLimits,
  salesforceGetRecordCounts,
  salesforceGetSearchLayout,
  salesforceGetSearchSuggestions,
  salesforceGetSupport,
  salesforceGetSupportKnowledgeArticles,
  salesforceGetTheme,
  salesforceHeadSobjectsUserPassword,
  salesforceSearchKnowledgeArticles,
  salesforceSobjectUserPassword,
  salesforceUpdateFavorite,
} from './platform.js';
import {
  salesforceExecuteSoqlQuery,
  salesforceExecuteSoslSearch,
  salesforcePostParameterizedSearch,
  salesforceQuery,
  salesforceQueryAll,
  salesforceQueryMore,
  salesforceRunSoqlQuery,
  salesforceSearch,
  salesforceToolingQuery,
} from './query.js';
import {
  salesforceGetDashboard,
  salesforceGetReport,
  salesforceGetReportInstance,
  salesforceListAnalyticsTemplates,
  salesforceListDashboards,
  salesforceListReports,
  salesforceQueryReport,
  salesforceRunReport,
  salesforceRunReportAsync,
} from './reports.js';
import {
  salesforceCompositeGraphAction,
  salesforceCreateSObjectRecord,
  salesforceCreateSobjectTree,
  salesforceDeleteSobject,
  salesforceDeleteSobjectCollections,
  salesforceGetCompositeResources,
  salesforceGetCompositeSobjects,
  salesforceGetSobjectByExternalId,
  salesforceGetSobjectCollections,
  salesforceGetSObjectRecord,
  salesforceGetSobjectRelationship,
  salesforceGetSObjectsUpdated,
  salesforcePatchCompositeSobjects,
  salesforcePostCompositeGraph,
  salesforcePostCompositeSobjects,
  salesforceSobjectRowsUpdate,
  salesforceUpsertSobjectByExternalId,
} from './sobjects.js';
import {
  salesforceCreateARecord,
  salesforceGetABatchOfRecords,
  salesforceGetAllFieldsForObject,
  salesforceGetAllNavigationItems,
  salesforceGetApp,
  salesforceGetApps,
  salesforceGetChildRecords,
  salesforceGetCompactLayouts,
  salesforceGetGlobalActions,
  salesforceGetLastSelectedApp,
  salesforceGetListViewActions,
  salesforceGetListViewMetadataByName,
  salesforceGetListViewRecordsById,
  salesforceGetListViewRecordsByName,
  salesforceGetLookupFieldSuggestions,
  salesforceGetLookupSuggestionsCaseContact,
  salesforceGetMruListViewMetadata,
  salesforceGetMruListViewRecords,
  salesforceGetObjectListViews,
  salesforceGetPhotoActions,
  salesforceGetPicklistValuesByRecordType,
  salesforceGetRecordEditPageActions,
  salesforceGetRelatedListActions,
  salesforceGetRelatedListPreferencesBatch,
  salesforceGetRelatedListRecordsContacts,
  salesforceGetSobjectPlatformaction,
  salesforceGetSObjectsDescribeLayoutsRecordTypeId,
  salesforceGetSobjectsSobjectDescribeApprovallayouts,
  salesforceGetSupportedObjectsDirectory,
  salesforceGetUiApiActionsLookupAccount,
  salesforceGetUiapiActionsMruListAccount,
  salesforceGetUiApiActionsRecordRelatedList,
  salesforceGetUiApiAppsUserNavItems,
  salesforceGetUiapiListInfoAccountAllAccounts,
  salesforceGetUiapiListInfoAccountRecent,
  salesforceGetUiapiListInfoAccountSearchResult,
  salesforceGetUiApiListInfoRecent,
  salesforceGetUiapimruListInfoAccount,
  salesforceGetUiApiMruListRecordsAccount,
  salesforceGetUiApiRecordUi,
  salesforceGetUiapiRelatedListPreferences,
  salesforceUpdateListViewPreferences,
  salesforceUpdateRecord,
  salesforceUpdateRelatedListPreferences,
} from './uiapi.js';

export {
  salesforceAccountCreationWithContentTypeOption,
  salesforceCreateAccount,
  salesforceDeleteAccount,
  salesforceFetchAccountByIdWithQuery,
  salesforceGetAccount,
  salesforceListAccounts,
  salesforceRemoveAccountByUniqueIdentifier,
  salesforceRetrieveAccountDataAndErrorResponses,
  salesforceUpdateAccount,
  salesforceUpdateAccountObjectById,
} from './accounts.js';
export {
  salesforceExecuteGlobalQuickAction,
  salesforceExecuteInvocableAction,
  salesforceExecuteSobjectQuickAction,
  salesforceGetQuickActions,
  salesforceGetSObjectQuickActionDefaultValues,
  salesforceGetSobjectQuickActionDefaultValues,
  salesforceHeadActionsCustom,
  salesforceHeadActionsStandard,
  salesforceHeadAppmenuSalesforce1,
  salesforceHeadProcessRulesSObject,
  salesforceHeadQuickActions,
  salesforceHeadSobjectQuickActionDefaultValues,
  salesforceHeadSobjectsGlobalDescribeLayouts,
  salesforceHeadSobjectsQuickAction,
  salesforceListCustomInvocableActions,
  salesforceListStandardInvocableActions,
} from './actions.js';
export {
  salesforceCreateNote,
  salesforceCreateNoteRecordWithContentTypeHeader,
  salesforceCreateTask,
  salesforceDeleteNote,
  salesforceGetNote,
  salesforceGetNoteByIdWithFields,
  salesforceListNotes,
  salesforceLogCall,
  salesforceLogEmailActivity,
  salesforceRemoveNoteObjectById,
  salesforceUpdateNote,
  salesforceUpdateSpecificNoteById,
  salesforceUpdateTask,
} from './activities.js';
export {
  salesforceCloseOrAbortJob,
  salesforceCreateBulkIngestJob,
  salesforceCreateBulkQueryJob,
  salesforceDeleteJobQuery,
  salesforceGetJobFailedRecordResults,
  salesforceGetJobSuccessfulRecordResults,
  salesforceGetJobUnprocessedRecordResults,
  salesforceGetQueryJobInfo,
  salesforceGetQueryJobResults,
  salesforceUploadJobData,
} from './bulk.js';
export {
  salesforceAddContactToCampaign,
  salesforceAddLeadToCampaign,
  salesforceCreateCampaign,
  salesforceCreateCampaignRecordViaPost,
  salesforceDeleteCampaign,
  salesforceGetCampaign,
  salesforceListCampaigns,
  salesforceRemoveCampaignObjectById,
  salesforceRetrieveCampaignDataWithErrorHandling,
  salesforceRetrieveSpecificCampaignObjectDetails,
  salesforceUpdateCampaign,
  salesforceUpdateCampaignByIdWithJson,
} from './campaigns.js';
export {
  salesforceAssociateContactToAccount,
  salesforceCreateContact,
  salesforceCreateNewContactWithJsonHeader,
  salesforceDeleteContact,
  salesforceGetContact,
  salesforceGetContactById,
  salesforceListContacts,
  salesforceQueryContactsByName,
  salesforceRemoveASpecificContactById,
  salesforceRetrieveContactInfoWithStandardResponses,
  salesforceRetrieveSpecificContactById,
  salesforceUpdateContact,
  salesforceUpdateContactById,
} from './contacts.js';
export {
  salesforceSendEmail,
  salesforceSendEmailFromTemplate,
  salesforceSendMassEmail,
} from './custom-actions.js';
export { salesforceGetFileContent, salesforceUploadFile } from './custom-files.js';
export {
  salesforceGetAllCustomObjects,
  salesforceGetListViewMetadataBatch,
  salesforceGetUserInfo,
  salesforceWhoAmI,
  salesforceSetUserPassword,
} from './custom-platform.js';
export {
  salesforceCloneRecord,
  salesforceCloneOpportunityWithProducts,
  salesforceRemoveFromCampaign,
  salesforceMassTransferOwnership,
  salesforceCompleteTask,
  salesforceApplyLeadAssignmentRules,
} from './custom-records.js';
export {
  salesforceParameterizedSearch,
  salesforceSearchAccounts,
  salesforceSearchContacts,
  salesforceSearchLeads,
  salesforceSearchCampaigns,
  salesforceSearchOpportunities,
  salesforceSearchNotes,
  salesforceSearchTasks,
  salesforceListEmailTemplates,
} from './custom-search.js';
export {
  salesforceGetListViewResults,
  salesforceGetSobjectListView,
  salesforceGetSobjectListViews,
  salesforceRetrieveNoteObjectInformation,
} from './describe.js';
export {
  salesforceCreateLead,
  salesforceCreateLeadWithSpecifiedContentType,
  salesforceDeleteALeadObjectByItsId,
  salesforceDeleteLead,
  salesforceGetLead,
  salesforceListLeads,
  salesforceRetrieveLeadById,
  salesforceRetrieveLeadDataWithVariousResponses,
  salesforceUpdateLead,
  salesforceUpdateLeadByIdWithJsonPayload,
} from './leads.js';
export { salesforceCreateCustomField, salesforceCreateCustomObject } from './metadata.js';
export {
  salesforceAddOpportunityLineItem,
  salesforceCreateOpportunity,
  salesforceCreateOpportunityRecord,
  salesforceDeleteOpportunity,
  salesforceGetOpportunity,
  salesforceListOpportunities,
  salesforceListPricebookEntries,
  salesforceListPricebooks,
  salesforceRemoveOpportunityById,
  salesforceRetrieveOpportunitiesData,
  salesforceRetrieveOpportunityByIdWithOptionalFields,
  salesforceUpdateOpportunity,
  salesforceUpdateOpportunityById,
} from './opportunities.js';
export {
  salesforceDeleteFile,
  salesforceGetApi,
  salesforceGetChatterResources,
  salesforceGetConsentAction,
  salesforceGetFileInformation,
  salesforceGetFileShares,
  salesforceGetOrgLimits,
  salesforceGetRecordCounts,
  salesforceGetSearchLayout,
  salesforceGetSearchSuggestions,
  salesforceGetSupport,
  salesforceGetSupportKnowledgeArticles,
  salesforceGetTheme,
  salesforceHeadSobjectsUserPassword,
  salesforceSearchKnowledgeArticles,
  salesforceSobjectUserPassword,
  salesforceUpdateFavorite,
} from './platform.js';
export {
  salesforceExecuteSoqlQuery,
  salesforceExecuteSoslSearch,
  salesforcePostParameterizedSearch,
  salesforceQuery,
  salesforceQueryAll,
  salesforceQueryMore,
  salesforceRunSoqlQuery,
  salesforceSearch,
  salesforceToolingQuery,
} from './query.js';
export {
  salesforceGetDashboard,
  salesforceGetReport,
  salesforceGetReportInstance,
  salesforceListAnalyticsTemplates,
  salesforceListDashboards,
  salesforceListReports,
  salesforceQueryReport,
  salesforceRunReport,
  salesforceRunReportAsync,
} from './reports.js';
export {
  salesforceCompositeGraphAction,
  salesforceCreateSObjectRecord,
  salesforceCreateSobjectTree,
  salesforceDeleteSobject,
  salesforceDeleteSobjectCollections,
  salesforceGetCompositeResources,
  salesforceGetCompositeSobjects,
  salesforceGetSobjectByExternalId,
  salesforceGetSobjectCollections,
  salesforceGetSObjectRecord,
  salesforceGetSobjectRelationship,
  salesforceGetSObjectsUpdated,
  salesforcePatchCompositeSobjects,
  salesforcePostCompositeGraph,
  salesforcePostCompositeSobjects,
  salesforceSobjectRowsUpdate,
  salesforceUpsertSobjectByExternalId,
} from './sobjects.js';
export {
  salesforceCreateARecord,
  salesforceGetABatchOfRecords,
  salesforceGetAllFieldsForObject,
  salesforceGetAllNavigationItems,
  salesforceGetApp,
  salesforceGetApps,
  salesforceGetChildRecords,
  salesforceGetCompactLayouts,
  salesforceGetGlobalActions,
  salesforceGetLastSelectedApp,
  salesforceGetListViewActions,
  salesforceGetListViewMetadataByName,
  salesforceGetListViewRecordsById,
  salesforceGetListViewRecordsByName,
  salesforceGetLookupFieldSuggestions,
  salesforceGetLookupSuggestionsCaseContact,
  salesforceGetMruListViewMetadata,
  salesforceGetMruListViewRecords,
  salesforceGetObjectListViews,
  salesforceGetPhotoActions,
  salesforceGetPicklistValuesByRecordType,
  salesforceGetRecordEditPageActions,
  salesforceGetRelatedListActions,
  salesforceGetRelatedListPreferencesBatch,
  salesforceGetRelatedListRecordsContacts,
  salesforceGetSobjectPlatformaction,
  salesforceGetSObjectsDescribeLayoutsRecordTypeId,
  salesforceGetSobjectsSobjectDescribeApprovallayouts,
  salesforceGetSupportedObjectsDirectory,
  salesforceGetUiApiActionsLookupAccount,
  salesforceGetUiapiActionsMruListAccount,
  salesforceGetUiApiActionsRecordRelatedList,
  salesforceGetUiApiAppsUserNavItems,
  salesforceGetUiapiListInfoAccountAllAccounts,
  salesforceGetUiapiListInfoAccountRecent,
  salesforceGetUiapiListInfoAccountSearchResult,
  salesforceGetUiApiListInfoRecent,
  salesforceGetUiapimruListInfoAccount,
  salesforceGetUiApiMruListRecordsAccount,
  salesforceGetUiApiRecordUi,
  salesforceGetUiapiRelatedListPreferences,
  salesforceUpdateListViewPreferences,
  salesforceUpdateRecord,
  salesforceUpdateRelatedListPreferences,
} from './uiapi.js';

const auth = 'salesforceCredentials' as const;

export const salesforceTools = [
  {
    name: 'salesforceAccountCreationWithContentTypeOption',
    description: salesforceAccountCreationWithContentTypeOption.description!,
    tool: salesforceAccountCreationWithContentTypeOption,
    requiredAuth: auth,
    scope: 'write' as const,
    keywords: ['deprecated', 'creates', 'json', 'request', 'requiring'],
  },
  {
    name: 'salesforceCreateAccount',
    description: salesforceCreateAccount.description!,
    tool: salesforceCreateAccount,
    requiredAuth: auth,
    scope: 'write' as const,
    keywords: ['creates', 'specified', 'returns', 'created', 'response'],
  },
  {
    name: 'salesforceDeleteAccount',
    description: salesforceDeleteAccount.description!,
    tool: salesforceDeleteAccount,
    requiredAuth: auth,
    scope: 'delete' as const,
    keywords: ['permanently', 'deletes', 'cannot', 'undone'],
  },
  {
    name: 'salesforceFetchAccountByIdWithQuery',
    description: salesforceFetchAccountByIdWithQuery.description!,
    tool: salesforceFetchAccountByIdWithQuery,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['deprecated', 'unique', 'valid', 'optionally', 'specify'],
  },
  {
    name: 'salesforceGetAccount',
    description: salesforceGetAccount.description!,
    tool: salesforceGetAccount,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['retrieves', 'returning', 'available'],
  },
  {
    name: 'salesforceListAccounts',
    description: salesforceListAccounts.description!,
    tool: salesforceListAccounts,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['lists', 'accounts', 'soql', 'allowing', 'flexible'],
  },
  {
    name: 'salesforceRemoveAccountByUniqueIdentifier',
    description: salesforceRemoveAccountByUniqueIdentifier.description!,
    tool: salesforceRemoveAccountByUniqueIdentifier,
    requiredAuth: auth,
    scope: 'delete' as const,
    keywords: ['deprecated', 'deletes', 'unique', 'returning', 'empty'],
  },
  {
    name: 'salesforceRetrieveAccountDataAndErrorResponses',
    description: salesforceRetrieveAccountDataAndErrorResponses.description!,
    tool: salesforceRetrieveAccountDataAndErrorResponses,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['deprecated', 'retrieves', 'comprehensive', 'metadata', 'detailing'],
  },
  {
    name: 'salesforceUpdateAccount',
    description: salesforceUpdateAccount.description!,
    tool: salesforceUpdateAccount,
    requiredAuth: auth,
    scope: 'write' as const,
    keywords: ['updates', 'specified', 'changes', 'provided', 'updated'],
  },
  {
    name: 'salesforceUpdateAccountObjectById',
    description: salesforceUpdateAccountObjectById.description!,
    tool: salesforceUpdateAccountObjectById,
    requiredAuth: auth,
    scope: 'write' as const,
    keywords: ['deprecated', 'updates', 'specified', 'identified', 'unique'],
  },
  {
    name: 'salesforceExecuteGlobalQuickAction',
    description: salesforceExecuteGlobalQuickAction.description!,
    tool: salesforceExecuteGlobalQuickAction,
    requiredAuth: auth,
    scope: 'write' as const,
    keywords: ['non-object-specific', 'quick', 'quickactions', 'actionname', 'lists'],
  },
  {
    name: 'salesforceExecuteInvocableAction',
    description: salesforceExecuteInvocableAction.description!,
    tool: salesforceExecuteInvocableAction,
    requiredAuth: auth,
    scope: 'write' as const,
    keywords: ['invoke', 'invocable', 'name', 'actions/standard', 'actions/custom'],
  },
  {
    name: 'salesforceExecuteSobjectQuickAction',
    description: salesforceExecuteSobjectQuickAction.description!,
    tool: salesforceExecuteSobjectQuickAction,
    requiredAuth: auth,
    scope: 'write' as const,
    keywords: ['tool', 'quick', 'pre-configured', 'defaults', 'leverage'],
  },
  {
    name: 'salesforceGetQuickActions',
    description: salesforceGetQuickActions.description!,
    tool: salesforceGetQuickActions,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['tool', 'object-specific', 'quick', 'available', 'organization'],
  },
  {
    name: 'salesforceGetSObjectQuickActionDefaultValues',
    description: salesforceGetSObjectQuickActionDefaultValues.description!,
    tool: salesforceGetSObjectQuickActionDefaultValues,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['retrieves', 'quick', 'context', 'pre-populate', 'creating'],
  },
  {
    name: 'salesforceGetSobjectQuickActionDefaultValues',
    description: salesforceGetSobjectQuickActionDefaultValues.description!,
    tool: salesforceGetSobjectQuickActionDefaultValues,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['retrieves', 'quick', 'understand', 'automatically', 'populated'],
  },
  {
    name: 'salesforceHeadActionsCustom',
    description: salesforceHeadActionsCustom.description!,
    tool: salesforceHeadActionsCustom,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['tool', 'return', 'http', 'headers', 'invocable'],
  },
  {
    name: 'salesforceHeadActionsStandard',
    description: salesforceHeadActionsStandard.description!,
    tool: salesforceHeadActionsStandard,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['tool', 'return', 'http', 'headers', 'invocable'],
  },
  {
    name: 'salesforceHeadAppmenuSalesforce1',
    description: salesforceHeadAppmenuSalesforce1.description!,
    tool: salesforceHeadAppmenuSalesforce1,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['tool', 'return', 'http', 'headers', 'appmenu'],
  },
  {
    name: 'salesforceHeadProcessRulesSObject',
    description: salesforceHeadProcessRulesSObject.description!,
    tool: salesforceHeadProcessRulesSObject,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['tool', 'return', 'http', 'headers', 'process'],
  },
  {
    name: 'salesforceHeadQuickActions',
    description: salesforceHeadQuickActions.description!,
    tool: salesforceHeadQuickActions,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['tool', 'return', 'http', 'headers', 'quick'],
  },
  {
    name: 'salesforceHeadSobjectQuickActionDefaultValues',
    description: salesforceHeadSobjectQuickActionDefaultValues.description!,
    tool: salesforceHeadSobjectQuickActionDefaultValues,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['tool', 'return', 'http', 'headers', 'quick'],
  },
  {
    name: 'salesforceHeadSobjectsGlobalDescribeLayouts',
    description: salesforceHeadSobjectsGlobalDescribeLayouts.description!,
    tool: salesforceHeadSobjectsGlobalDescribeLayouts,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['tool', 'return', 'http', 'headers', 'publisher'],
  },
  {
    name: 'salesforceHeadSobjectsQuickAction',
    description: salesforceHeadSobjectsQuickAction.description!,
    tool: salesforceHeadSobjectsQuickAction,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['tool', 'return', 'http', 'headers', 'quick'],
  },
  {
    name: 'salesforceListCustomInvocableActions',
    description: salesforceListCustomInvocableActions.description!,
    tool: salesforceListCustomInvocableActions,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['retrieves', 'including', 'flow', 'apex', 'invocable'],
  },
  {
    name: 'salesforceListStandardInvocableActions',
    description: salesforceListStandardInvocableActions.description!,
    tool: salesforceListStandardInvocableActions,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['retrieves', 'statically', 'invoked', 'discover', 'available'],
  },
  {
    name: 'salesforceCreateNote',
    description: salesforceCreateNote.description!,
    tool: salesforceCreateNote,
    requiredAuth: auth,
    scope: 'write' as const,
    keywords: ['creates', 'attached', 'specified', 'title', 'content'],
  },
  {
    name: 'salesforceCreateNoteRecordWithContentTypeHeader',
    description: salesforceCreateNoteRecordWithContentTypeHeader.description!,
    tool: salesforceCreateNoteRecordWithContentTypeHeader,
    requiredAuth: auth,
    scope: 'write' as const,
    keywords: ['deprecated', 'creates', 'associated', 'parentid', 'automatically'],
  },
  {
    name: 'salesforceCreateTask',
    description: salesforceCreateTask.description!,
    tool: salesforceCreateTask,
    requiredAuth: auth,
    scope: 'write' as const,
    keywords: ['creates', 'track', 'activities', 'to-dos', 'follow-ups'],
  },
  {
    name: 'salesforceDeleteNote',
    description: salesforceDeleteNote.description!,
    tool: salesforceDeleteNote,
    requiredAuth: auth,
    scope: 'delete' as const,
    keywords: ['permanently', 'deletes', 'cannot', 'undone'],
  },
  {
    name: 'salesforceGetNote',
    description: salesforceGetNote.description!,
    tool: salesforceGetNote,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['retrieves', 'returning', 'available', 'notes', 'isprivate'],
  },
  {
    name: 'salesforceGetNoteByIdWithFields',
    description: salesforceGetNoteByIdWithFields.description!,
    tool: salesforceGetNoteByIdWithFields,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['deprecated', 'retrieves', 'optionally', 'specifying', 'return'],
  },
  {
    name: 'salesforceListNotes',
    description: salesforceListNotes.description!,
    tool: salesforceListNotes,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['lists', 'notes', 'soql', 'allowing', 'flexible'],
  },
  {
    name: 'salesforceLogCall',
    description: salesforceLogCall.description!,
    tool: salesforceLogCall,
    requiredAuth: auth,
    scope: 'write' as const,
    keywords: ['logs', 'completed', 'phone', 'call', 'call-specific'],
  },
  {
    name: 'salesforceLogEmailActivity',
    description: salesforceLogEmailActivity.description!,
    tool: salesforceLogEmailActivity,
    requiredAuth: auth,
    scope: 'write' as const,
    keywords: ['creates', 'emailmessage', 'email', 'activity', 'associating'],
  },
  {
    name: 'salesforceRemoveNoteObjectById',
    description: salesforceRemoveNoteObjectById.description!,
    tool: salesforceRemoveNoteObjectById,
    requiredAuth: auth,
    scope: 'delete' as const,
    keywords: ['deprecated', 'permanently', 'deletes', 'identified', 'unique'],
  },
  {
    name: 'salesforceUpdateNote',
    description: salesforceUpdateNote.description!,
    tool: salesforceUpdateNote,
    requiredAuth: auth,
    scope: 'write' as const,
    keywords: ['updates', 'specified', 'changes', 'provided', 'updated'],
  },
  {
    name: 'salesforceUpdateSpecificNoteById',
    description: salesforceUpdateSpecificNoteById.description!,
    tool: salesforceUpdateSpecificNoteById,
    requiredAuth: auth,
    scope: 'write' as const,
    keywords: ['deprecated', 'instead', 'updates', 'specified', 'identified'],
  },
  {
    name: 'salesforceUpdateTask',
    description: salesforceUpdateTask.description!,
    tool: salesforceUpdateTask,
    requiredAuth: auth,
    scope: 'write' as const,
    keywords: ['updates', 'provided', 'updated'],
  },
  {
    name: 'salesforceCloseOrAbortJob',
    description: salesforceCloseOrAbortJob.description!,
    tool: salesforceCloseOrAbortJob,
    requiredAuth: auth,
    scope: 'write' as const,
    keywords: ['tool', 'close', 'abort', 'ingest', 'finalize'],
  },
  {
    name: 'salesforceCreateBulkIngestJob',
    description: salesforceCreateBulkIngestJob.description!,
    tool: salesforceCreateBulkIngestJob,
    requiredAuth: auth,
    scope: 'write' as const,
    keywords: ['ingest', 'jobs/ingest', 'returns', 'open', 'state'],
  },
  {
    name: 'salesforceCreateBulkQueryJob',
    description: salesforceCreateBulkQueryJob.description!,
    tool: salesforceCreateBulkQueryJob,
    requiredAuth: auth,
    scope: 'write' as const,
    keywords: ['jobs/query', 'soql', 'large', 'result', 'returns'],
  },
  {
    name: 'salesforceDeleteJobQuery',
    description: salesforceDeleteJobQuery.description!,
    tool: salesforceDeleteJobQuery,
    requiredAuth: auth,
    scope: 'delete' as const,
    keywords: ['tool', 'permanently', 'remove', 'associated', 'created'],
  },
  {
    name: 'salesforceGetJobFailedRecordResults',
    description: salesforceGetJobFailedRecordResults.description!,
    tool: salesforceGetJobFailedRecordResults,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['tool', 'failed', 'ingest', 'operation', 'including'],
  },
  {
    name: 'salesforceGetJobSuccessfulRecordResults',
    description: salesforceGetJobSuccessfulRecordResults.description!,
    tool: salesforceGetJobSuccessfulRecordResults,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['tool', 'successfully', 'processed', 'ingest', 'were'],
  },
  {
    name: 'salesforceGetJobUnprocessedRecordResults',
    description: salesforceGetJobUnprocessedRecordResults.description!,
    tool: salesforceGetJobUnprocessedRecordResults,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['tool', 'unprocessed', 'ingest', 'were', 'processed'],
  },
  {
    name: 'salesforceGetQueryJobInfo',
    description: salesforceGetQueryJobInfo.description!,
    tool: salesforceGetQueryJobInfo,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['tool', 'about', 'check', 'status'],
  },
  {
    name: 'salesforceGetQueryJobResults',
    description: salesforceGetQueryJobResults.description!,
    tool: salesforceGetQueryJobResults,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['retrieves', 'results', 'completed', 'format', 'supports'],
  },
  {
    name: 'salesforceUploadJobData',
    description: salesforceUploadJobData.description!,
    tool: salesforceUploadJobData,
    requiredAuth: auth,
    scope: 'write' as const,
    keywords: ['tool', 'upload', 'ingest', 'creating', 'closing'],
  },
  {
    name: 'salesforceAddContactToCampaign',
    description: salesforceAddContactToCampaign.description!,
    tool: salesforceAddContactToCampaign,
    requiredAuth: auth,
    scope: 'write' as const,
    keywords: ['adds', 'creating', 'campaignmember', 'track', 'engagement'],
  },
  {
    name: 'salesforceAddLeadToCampaign',
    description: salesforceAddLeadToCampaign.description!,
    tool: salesforceAddLeadToCampaign,
    requiredAuth: auth,
    scope: 'write' as const,
    keywords: ['adds', 'creating', 'campaignmember', 'allowing', 'track'],
  },
  {
    name: 'salesforceCreateCampaign',
    description: salesforceCreateCampaign.description!,
    tool: salesforceCreateCampaign,
    requiredAuth: auth,
    scope: 'write' as const,
    keywords: ['creates', 'name', 'universally', 'required', 'org-level'],
  },
  {
    name: 'salesforceCreateCampaignRecordViaPost',
    description: salesforceCreateCampaignRecordViaPost.description!,
    tool: salesforceCreateCampaignRecordViaPost,
    requiredAuth: auth,
    scope: 'write' as const,
    keywords: ['deprecated', 'creates', 'parentid', 'provided', 'valid'],
  },
  {
    name: 'salesforceDeleteCampaign',
    description: salesforceDeleteCampaign.description!,
    tool: salesforceDeleteCampaign,
    requiredAuth: auth,
    scope: 'delete' as const,
    keywords: ['permanently', 'deletes', 'cannot', 'undone'],
  },
  {
    name: 'salesforceGetCampaign',
    description: salesforceGetCampaign.description!,
    tool: salesforceGetCampaign,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['retrieves', 'returning', 'available'],
  },
  {
    name: 'salesforceListCampaigns',
    description: salesforceListCampaigns.description!,
    tool: salesforceListCampaigns,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['lists', 'campaigns', 'soql', 'allowing', 'flexible'],
  },
  {
    name: 'salesforceRemoveCampaignObjectById',
    description: salesforceRemoveCampaignObjectById.description!,
    tool: salesforceRemoveCampaignObjectById,
    requiredAuth: auth,
    scope: 'delete' as const,
    keywords: ['deprecated', 'permanently', 'deletes', 'unique'],
  },
  {
    name: 'salesforceRetrieveCampaignDataWithErrorHandling',
    description: salesforceRetrieveCampaignDataWithErrorHandling.description!,
    tool: salesforceRetrieveCampaignDataWithErrorHandling,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['deprecated', 'retrieves', 'comprehensive', 'metadata', 'provided'],
  },
  {
    name: 'salesforceRetrieveSpecificCampaignObjectDetails',
    description: salesforceRetrieveSpecificCampaignObjectDetails.description!,
    tool: salesforceRetrieveSpecificCampaignObjectDetails,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['deprecated', 'retrieves', 'optionally', 'limiting', 'specified'],
  },
  {
    name: 'salesforceUpdateCampaign',
    description: salesforceUpdateCampaign.description!,
    tool: salesforceUpdateCampaign,
    requiredAuth: auth,
    scope: 'write' as const,
    keywords: ['updates', 'specified', 'changes', 'provided', 'updated'],
  },
  {
    name: 'salesforceUpdateCampaignByIdWithJson',
    description: salesforceUpdateCampaignByIdWithJson.description!,
    tool: salesforceUpdateCampaignByIdWithJson,
    requiredAuth: auth,
    scope: 'write' as const,
    keywords: ['deprecated', 'updates', 'identified', 'unique', 'already'],
  },
  {
    name: 'salesforceAssociateContactToAccount',
    description: salesforceAssociateContactToAccount.description!,
    tool: salesforceAssociateContactToAccount,
    requiredAuth: auth,
    scope: 'write' as const,
    keywords: ['associates', 'updating', 'accountid', 'overwrites', 'broader'],
  },
  {
    name: 'salesforceCreateContact',
    description: salesforceCreateContact.description!,
    tool: salesforceCreateContact,
    requiredAuth: auth,
    scope: 'write' as const,
    keywords: ['creates', 'specified', 'writes', 'live', 'obtain'],
  },
  {
    name: 'salesforceCreateNewContactWithJsonHeader',
    description: salesforceCreateNewContactWithJsonHeader.description!,
    tool: salesforceCreateNewContactWithJsonHeader,
    requiredAuth: auth,
    scope: 'write' as const,
    keywords: ['deprecated', 'creates', 'lastname', 'required', 'accountid'],
  },
  {
    name: 'salesforceDeleteContact',
    description: salesforceDeleteContact.description!,
    tool: salesforceDeleteContact,
    requiredAuth: auth,
    scope: 'delete' as const,
    keywords: ['permanently', 'deletes', 'cannot', 'undone', 'associated'],
  },
  {
    name: 'salesforceGetContact',
    description: salesforceGetContact.description!,
    tool: salesforceGetContact,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['retrieves', 'returning', 'available'],
  },
  {
    name: 'salesforceGetContactById',
    description: salesforceGetContactById.description!,
    tool: salesforceGetContactById,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['retrieves', 'unique', 'correspond'],
  },
  {
    name: 'salesforceListContacts',
    description: salesforceListContacts.description!,
    tool: salesforceListContacts,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['lists', 'contacts', 'soql', 'allowing', 'flexible'],
  },
  {
    name: 'salesforceQueryContactsByName',
    description: salesforceQueryContactsByName.description!,
    tool: salesforceQueryContactsByName,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['deprecated', 'finds', 'name', 'case-insensitive'],
  },
  {
    name: 'salesforceRemoveASpecificContactById',
    description: salesforceRemoveASpecificContactById.description!,
    tool: salesforceRemoveASpecificContactById,
    requiredAuth: auth,
    scope: 'delete' as const,
    keywords: ['deprecated', 'permanently', 'deletes', 'unique', 'correspond'],
  },
  {
    name: 'salesforceRetrieveContactInfoWithStandardResponses',
    description: salesforceRetrieveContactInfoWithStandardResponses.description!,
    tool: salesforceRetrieveContactInfoWithStandardResponses,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['deprecated', 'retrieves', 'comprehensive', 'metadata', 'types'],
  },
  {
    name: 'salesforceRetrieveSpecificContactById',
    description: salesforceRetrieveSpecificContactById.description!,
    tool: salesforceRetrieveSpecificContactById,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['deprecated', 'retrieves', 'unique', 'correspond'],
  },
  {
    name: 'salesforceUpdateContact',
    description: salesforceUpdateContact.description!,
    tool: salesforceUpdateContact,
    requiredAuth: auth,
    scope: 'write' as const,
    keywords: ['updates', 'specified', 'changes', 'provided', 'updated'],
  },
  {
    name: 'salesforceUpdateContactById',
    description: salesforceUpdateContactById.description!,
    tool: salesforceUpdateContactById,
    requiredAuth: auth,
    scope: 'write' as const,
    keywords: ['deprecated', 'updates', 'specified', 'least', 'provided'],
  },
  {
    name: 'salesforceSendEmail',
    description: salesforceSendEmail.description!,
    tool: salesforceSendEmail,
    requiredAuth: auth,
    scope: 'write' as const,
    keywords: ['mail'],
  },
  {
    name: 'salesforceSendEmailFromTemplate',
    description: salesforceSendEmailFromTemplate.description!,
    tool: salesforceSendEmailFromTemplate,
    requiredAuth: auth,
    scope: 'write' as const,
    keywords: ['mail', 'merge'],
  },
  {
    name: 'salesforceSendMassEmail',
    description: salesforceSendMassEmail.description!,
    tool: salesforceSendMassEmail,
    requiredAuth: auth,
    scope: 'write' as const,
    keywords: ['bulk', 'mail'],
  },
  {
    name: 'salesforceGetFileContent',
    description: salesforceGetFileContent.description!,
    tool: salesforceGetFileContent,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['download'],
  },
  {
    name: 'salesforceUploadFile',
    description: salesforceUploadFile.description!,
    tool: salesforceUploadFile,
    requiredAuth: auth,
    scope: 'write' as const,
    keywords: ['attach'],
  },
  {
    name: 'salesforceGetAllCustomObjects',
    description: salesforceGetAllCustomObjects.description!,
    tool: salesforceGetAllCustomObjects,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['metadata', 'describe'],
  },
  {
    name: 'salesforceGetListViewMetadataBatch',
    description: salesforceGetListViewMetadataBatch.description!,
    tool: salesforceGetListViewMetadataBatch,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['batch'],
  },
  {
    name: 'salesforceGetUserInfo',
    description: salesforceGetUserInfo.description!,
    tool: salesforceGetUserInfo,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['profile', 'me'],
  },
  {
    name: 'salesforceWhoAmI',
    description: salesforceWhoAmI.description!,
    tool: salesforceWhoAmI,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['identity', 'me'],
  },
  {
    name: 'salesforceSetUserPassword',
    description: salesforceSetUserPassword.description!,
    tool: salesforceSetUserPassword,
    requiredAuth: auth,
    scope: 'write' as const,
    keywords: ['reset'],
  },
  {
    name: 'salesforceCloneRecord',
    description: salesforceCloneRecord.description!,
    tool: salesforceCloneRecord,
    requiredAuth: auth,
    scope: 'write' as const,
    keywords: ['duplicate', 'copy'],
  },
  {
    name: 'salesforceCloneOpportunityWithProducts',
    description: salesforceCloneOpportunityWithProducts.description!,
    tool: salesforceCloneOpportunityWithProducts,
    requiredAuth: auth,
    scope: 'write' as const,
    keywords: ['duplicate'],
  },
  {
    name: 'salesforceRemoveFromCampaign',
    description: salesforceRemoveFromCampaign.description!,
    tool: salesforceRemoveFromCampaign,
    requiredAuth: auth,
    scope: 'delete' as const,
    keywords: ['campaign member'],
  },
  {
    name: 'salesforceMassTransferOwnership',
    description: salesforceMassTransferOwnership.description!,
    tool: salesforceMassTransferOwnership,
    requiredAuth: auth,
    scope: 'write' as const,
    keywords: ['owner', 'reassign'],
  },
  {
    name: 'salesforceCompleteTask',
    description: salesforceCompleteTask.description!,
    tool: salesforceCompleteTask,
    requiredAuth: auth,
    scope: 'write' as const,
    keywords: ['finish'],
  },
  {
    name: 'salesforceApplyLeadAssignmentRules',
    description: salesforceApplyLeadAssignmentRules.description!,
    tool: salesforceApplyLeadAssignmentRules,
    requiredAuth: auth,
    scope: 'write' as const,
    keywords: ['assign', 'route'],
  },
  {
    name: 'salesforceParameterizedSearch',
    description: salesforceParameterizedSearch.description!,
    tool: salesforceParameterizedSearch,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['sosl', 'parameterized'],
  },
  {
    name: 'salesforceSearchAccounts',
    description: salesforceSearchAccounts.description!,
    tool: salesforceSearchAccounts,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['soql'],
  },
  {
    name: 'salesforceSearchContacts',
    description: salesforceSearchContacts.description!,
    tool: salesforceSearchContacts,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['soql'],
  },
  {
    name: 'salesforceSearchLeads',
    description: salesforceSearchLeads.description!,
    tool: salesforceSearchLeads,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['soql'],
  },
  {
    name: 'salesforceSearchCampaigns',
    description: salesforceSearchCampaigns.description!,
    tool: salesforceSearchCampaigns,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['soql'],
  },
  {
    name: 'salesforceSearchOpportunities',
    description: salesforceSearchOpportunities.description!,
    tool: salesforceSearchOpportunities,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['soql'],
  },
  {
    name: 'salesforceSearchNotes',
    description: salesforceSearchNotes.description!,
    tool: salesforceSearchNotes,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['soql', 'sosl'],
  },
  {
    name: 'salesforceSearchTasks',
    description: salesforceSearchTasks.description!,
    tool: salesforceSearchTasks,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['soql'],
  },
  {
    name: 'salesforceListEmailTemplates',
    description: salesforceListEmailTemplates.description!,
    tool: salesforceListEmailTemplates,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['soql'],
  },
  {
    name: 'salesforceGetListViewResults',
    description: salesforceGetListViewResults.description!,
    tool: salesforceGetListViewResults,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['retrieves', 'results', 'specified', 'returns', 'column'],
  },
  {
    name: 'salesforceGetSobjectListView',
    description: salesforceGetSobjectListView.description!,
    tool: salesforceGetSobjectListView,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['tool', 'basic', 'about', 'metadata', 'including'],
  },
  {
    name: 'salesforceGetSobjectListViews',
    description: salesforceGetSobjectListViews.description!,
    tool: salesforceGetSobjectListViews,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['tool', 'views', 'specified', 'discover', 'available'],
  },
  {
    name: 'salesforceRetrieveNoteObjectInformation',
    description: salesforceRetrieveNoteObjectInformation.description!,
    tool: salesforceRetrieveNoteObjectInformation,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['deprecated', 'retrieves', 'comprehensive', 'metadata', 'enabled'],
  },
  {
    name: 'salesforceCreateLead',
    description: salesforceCreateLead.description!,
    tool: salesforceCreateLead,
    requiredAuth: auth,
    scope: 'write' as const,
    keywords: ['creates', 'lastname', 'company', 'required', 'org-level'],
  },
  {
    name: 'salesforceCreateLeadWithSpecifiedContentType',
    description: salesforceCreateLeadWithSpecifiedContentType.description!,
    tool: salesforceCreateLeadWithSpecifiedContentType,
    requiredAuth: auth,
    scope: 'write' as const,
    keywords: ['deprecated', 'creates', 'requiring', 'lastname', 'company'],
  },
  {
    name: 'salesforceDeleteALeadObjectByItsId',
    description: salesforceDeleteALeadObjectByItsId.description!,
    tool: salesforceDeleteALeadObjectByItsId,
    requiredAuth: auth,
    scope: 'delete' as const,
    keywords: ['deprecated', 'permanently', 'deletes', 'unique'],
  },
  {
    name: 'salesforceDeleteLead',
    description: salesforceDeleteLead.description!,
    tool: salesforceDeleteLead,
    requiredAuth: auth,
    scope: 'delete' as const,
    keywords: ['permanently', 'deletes', 'cannot', 'undone'],
  },
  {
    name: 'salesforceGetLead',
    description: salesforceGetLead.description!,
    tool: salesforceGetLead,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['retrieves', 'returning', 'available'],
  },
  {
    name: 'salesforceListLeads',
    description: salesforceListLeads.description!,
    tool: salesforceListLeads,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['lists', 'leads', 'soql', 'allowing', 'flexible'],
  },
  {
    name: 'salesforceRetrieveLeadById',
    description: salesforceRetrieveLeadById.description!,
    tool: salesforceRetrieveLeadById,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['retrieves', 'specified', 'exist'],
  },
  {
    name: 'salesforceRetrieveLeadDataWithVariousResponses',
    description: salesforceRetrieveLeadDataWithVariousResponses.description!,
    tool: salesforceRetrieveLeadDataWithVariousResponses,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['deprecated', 'retrieves', 'recently', 'viewed', 'leads'],
  },
  {
    name: 'salesforceUpdateLead',
    description: salesforceUpdateLead.description!,
    tool: salesforceUpdateLead,
    requiredAuth: auth,
    scope: 'write' as const,
    keywords: ['updates', 'specified', 'changes', 'provided', 'updated'],
  },
  {
    name: 'salesforceUpdateLeadByIdWithJsonPayload',
    description: salesforceUpdateLeadByIdWithJsonPayload.description!,
    tool: salesforceUpdateLeadByIdWithJsonPayload,
    requiredAuth: auth,
    scope: 'write' as const,
    keywords: ['deprecated', 'updates', 'specified', 'unique', 'path'],
  },
  {
    name: 'salesforceCreateCustomField',
    description: salesforceCreateCustomField.description!,
    tool: salesforceCreateCustomField,
    requiredAuth: auth,
    scope: 'write' as const,
    keywords: ['tool', 'tooling', 'text', 'number', 'checkbox'],
  },
  {
    name: 'salesforceCreateCustomObject',
    description: salesforceCreateCustomObject.description!,
    tool: salesforceCreateCustomObject,
    requiredAuth: auth,
    scope: 'write' as const,
    keywords: ['tool', 'metadata', 'dynamically', 'types', 'tables'],
  },
  {
    name: 'salesforceAddOpportunityLineItem',
    description: salesforceAddOpportunityLineItem.description!,
    tool: salesforceAddOpportunityLineItem,
    requiredAuth: auth,
    scope: 'write' as const,
    keywords: ['adds', 'product', 'line', 'item', 'exist'],
  },
  {
    name: 'salesforceCreateOpportunity',
    description: salesforceCreateOpportunity.description!,
    tool: salesforceCreateOpportunity,
    requiredAuth: auth,
    scope: 'write' as const,
    keywords: ['creates', 'specified'],
  },
  {
    name: 'salesforceCreateOpportunityRecord',
    description: salesforceCreateOpportunityRecord.description!,
    tool: salesforceCreateOpportunityRecord,
    requiredAuth: auth,
    scope: 'write' as const,
    keywords: ['deprecated', 'creates', 'name', 'stagename', 'closedate'],
  },
  {
    name: 'salesforceDeleteOpportunity',
    description: salesforceDeleteOpportunity.description!,
    tool: salesforceDeleteOpportunity,
    requiredAuth: auth,
    scope: 'delete' as const,
    keywords: ['permanently', 'deletes', 'cannot', 'undone'],
  },
  {
    name: 'salesforceGetOpportunity',
    description: salesforceGetOpportunity.description!,
    tool: salesforceGetOpportunity,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['retrieves', 'returning', 'available'],
  },
  {
    name: 'salesforceListOpportunities',
    description: salesforceListOpportunities.description!,
    tool: salesforceListOpportunities,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['lists', 'opportunities', 'soql', 'allowing', 'flexible'],
  },
  {
    name: 'salesforceListPricebookEntries',
    description: salesforceListPricebookEntries.description!,
    tool: salesforceListPricebookEntries,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['lists', 'pricebook', 'entries', 'soql', 'allowing'],
  },
  {
    name: 'salesforceListPricebooks',
    description: salesforceListPricebooks.description!,
    tool: salesforceListPricebooks,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['lists', 'pricebooks', 'soql', 'allowing', 'flexible'],
  },
  {
    name: 'salesforceRemoveOpportunityById',
    description: salesforceRemoveOpportunityById.description!,
    tool: salesforceRemoveOpportunityById,
    requiredAuth: auth,
    scope: 'delete' as const,
    keywords: ['deprecated', 'permanently', 'deletes', 'does', 'exist'],
  },
  {
    name: 'salesforceRetrieveOpportunitiesData',
    description: salesforceRetrieveOpportunitiesData.description!,
    tool: salesforceRetrieveOpportunitiesData,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['retrieves', 'available', 'representing', 'potential', 'revenue-generating'],
  },
  {
    name: 'salesforceRetrieveOpportunityByIdWithOptionalFields',
    description: salesforceRetrieveOpportunityByIdWithOptionalFields.description!,
    tool: salesforceRetrieveOpportunityByIdWithOptionalFields,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['deprecated', 'retrieves', 'exist'],
  },
  {
    name: 'salesforceUpdateOpportunity',
    description: salesforceUpdateOpportunity.description!,
    tool: salesforceUpdateOpportunity,
    requiredAuth: auth,
    scope: 'write' as const,
    keywords: ['updates', 'specified', 'changes', 'provided', 'updated'],
  },
  {
    name: 'salesforceUpdateOpportunityById',
    description: salesforceUpdateOpportunityById.description!,
    tool: salesforceUpdateOpportunityById,
    requiredAuth: auth,
    scope: 'write' as const,
    keywords: ['deprecated', 'updates', 'specified', 'exist', 'some'],
  },
  {
    name: 'salesforceDeleteFile',
    description: salesforceDeleteFile.description!,
    tool: salesforceDeleteFile,
    requiredAuth: auth,
    scope: 'delete' as const,
    keywords: ['tool', 'permanently', 'remove', 'content', 'operation'],
  },
  {
    name: 'salesforceGetApi',
    description: salesforceGetApi.description!,
    tool: salesforceGetApi,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['tool', 'discover', 'available', 'rest', 'resources'],
  },
  {
    name: 'salesforceGetChatterResources',
    description: salesforceGetChatterResources.description!,
    tool: salesforceGetChatterResources,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['tool', 'access', 'resources', 'directory', 'discover'],
  },
  {
    name: 'salesforceGetConsentAction',
    description: salesforceGetConsentAction.description!,
    tool: salesforceGetConsentAction,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['tool', 'check', 'preferences', 'email', 'track'],
  },
  {
    name: 'salesforceGetFileInformation',
    description: salesforceGetFileInformation.description!,
    tool: salesforceGetFileInformation,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['tool', 'comprehensive', 'metadata', 'about', 'specified'],
  },
  {
    name: 'salesforceGetFileShares',
    description: salesforceGetFileShares.description!,
    tool: salesforceGetFileShares,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['returns', 'about', 'specified', 'been', 'shared'],
  },
  {
    name: 'salesforceGetOrgLimits',
    description: salesforceGetOrgLimits.description!,
    tool: salesforceGetOrgLimits,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['tool', 'organization', 'limits', 'remaining', 'allocations'],
  },
  {
    name: 'salesforceGetRecordCounts',
    description: salesforceGetRecordCounts.description!,
    tool: salesforceGetRecordCounts,
    requiredAuth: auth,
    scope: 'write' as const,
    keywords: ['tool', 'total', 'counts', 'specified', 'check'],
  },
  {
    name: 'salesforceGetSearchLayout',
    description: salesforceGetSearchLayout.description!,
    tool: salesforceGetSearchLayout,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['retrieves', 'result', 'layout', 'specified', 'understand'],
  },
  {
    name: 'salesforceGetSearchSuggestions',
    description: salesforceGetSearchSuggestions.description!,
    tool: salesforceGetSearchSuggestions,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['returns', 'suggested', 'searches', 'string', 'want'],
  },
  {
    name: 'salesforceGetSupport',
    description: salesforceGetSupport.description!,
    tool: salesforceGetSupport,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['retrieves', 'root', 'knowledge', 'rest', 'access'],
  },
  {
    name: 'salesforceGetSupportKnowledgeArticles',
    description: salesforceGetSupportKnowledgeArticles.description!,
    tool: salesforceGetSupportKnowledgeArticles,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['retrieves', 'visible', 'knowledge', 'articles', 'categories'],
  },
  {
    name: 'salesforceGetTheme',
    description: salesforceGetTheme.description!,
    tool: salesforceGetTheme,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['tool', 'icons', 'colors', 'themes', 'organization'],
  },
  {
    name: 'salesforceHeadSobjectsUserPassword',
    description: salesforceHeadSobjectsUserPassword.description!,
    tool: salesforceHeadSobjectsUserPassword,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['tool', 'return', 'http', 'headers', 'password'],
  },
  {
    name: 'salesforceSearchKnowledgeArticles',
    description: salesforceSearchKnowledgeArticles.description!,
    tool: salesforceSearchKnowledgeArticles,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['knowledge', 'articles', 'titles', 'matching', 'returns'],
  },
  {
    name: 'salesforceSobjectUserPassword',
    description: salesforceSobjectUserPassword.description!,
    tool: salesforceSobjectUserPassword,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['tool', 'check', 'password', 'expired', 'verify'],
  },
  {
    name: 'salesforceUpdateFavorite',
    description: salesforceUpdateFavorite.description!,
    tool: salesforceUpdateFavorite,
    requiredAuth: auth,
    scope: 'write' as const,
    keywords: ['tool', 'favorite', 'properties', 'reorder', 'favorites'],
  },
  {
    name: 'salesforceExecuteSoqlQuery',
    description: salesforceExecuteSoqlQuery.description!,
    tool: salesforceExecuteSoqlQuery,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['deprecated', 'soql', 'instead', 'executes', 'provided'],
  },
  {
    name: 'salesforceExecuteSoslSearch',
    description: salesforceExecuteSoslSearch.description!,
    tool: salesforceExecuteSoslSearch,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['sosl', 'text', 'types', 'simultaneously'],
  },
  {
    name: 'salesforcePostParameterizedSearch',
    description: salesforcePostParameterizedSearch.description!,
    tool: salesforcePostParameterizedSearch,
    requiredAuth: auth,
    scope: 'write' as const,
    keywords: ['tool', 'parameterized', 'advanced', 'filtering', 'terms'],
  },
  {
    name: 'salesforceQuery',
    description: salesforceQuery.description!,
    tool: salesforceQuery,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['deprecated', 'soql', 'instead', 'tool', 'queries'],
  },
  {
    name: 'salesforceQueryAll',
    description: salesforceQueryAll.description!,
    tool: salesforceQueryAll,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['tool', 'soql', 'queries', 'including', 'soft-deleted'],
  },
  {
    name: 'salesforceQueryMore',
    description: salesforceQueryMore.description!,
    tool: salesforceQueryMore,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['page', 'soql', 'results', 'locator', 'querylocator'],
  },
  {
    name: 'salesforceRunSoqlQuery',
    description: salesforceRunSoqlQuery.description!,
    tool: salesforceRunSoqlQuery,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['executes', 'soql', 'against', 'returns', 'matching'],
  },
  {
    name: 'salesforceSearch',
    description: salesforceSearch.description!,
    tool: salesforceSearch,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['deprecated', 'sosl', 'instead', 'executes', 'text'],
  },
  {
    name: 'salesforceToolingQuery',
    description: salesforceToolingQuery.description!,
    tool: salesforceToolingQuery,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['tool', 'soql', 'queries', 'against', 'tooling'],
  },
  {
    name: 'salesforceGetDashboard',
    description: salesforceGetDashboard.description!,
    tool: salesforceGetDashboard,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['gets', 'detailed', 'metadata', 'including', 'components'],
  },
  {
    name: 'salesforceGetReport',
    description: salesforceGetReport.description!,
    tool: salesforceGetReport,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['gets', 'detailed', 'metadata', 'including', 'structure'],
  },
  {
    name: 'salesforceGetReportInstance',
    description: salesforceGetReportInstance.description!,
    tool: salesforceGetReportInstance,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['gets', 'results', 'instance', 'created', 'running'],
  },
  {
    name: 'salesforceListAnalyticsTemplates',
    description: salesforceListAnalyticsTemplates.description!,
    tool: salesforceListAnalyticsTemplates,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['tool', 'analytics', 'templates', 'available', 'discover'],
  },
  {
    name: 'salesforceListDashboards',
    description: salesforceListDashboards.description!,
    tool: salesforceListDashboards,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['lists', 'dashboards', 'basic', 'metadata', 'including'],
  },
  {
    name: 'salesforceListReports',
    description: salesforceListReports.description!,
    tool: salesforceListReports,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['lists', 'reports', 'basic', 'metadata', 'including'],
  },
  {
    name: 'salesforceQueryReport',
    description: salesforceQueryReport.description!,
    tool: salesforceQueryReport,
    requiredAuth: auth,
    scope: 'write' as const,
    keywords: ['deprecated', 'executes', 'synchronously', 'reporttype', 'optionally'],
  },
  {
    name: 'salesforceRunReport',
    description: salesforceRunReport.description!,
    tool: salesforceRunReport,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['runs', 'synchronously', 'analytics/reports', 'includedetails', 'true'],
  },
  {
    name: 'salesforceRunReportAsync',
    description: salesforceRunReportAsync.description!,
    tool: salesforceRunReportAsync,
    requiredAuth: auth,
    scope: 'write' as const,
    keywords: ['asynchronously', 'analytics/reports', 'instances', 'returns', 'instance'],
  },
  {
    name: 'salesforceCompositeGraphAction',
    description: salesforceCompositeGraphAction.description!,
    tool: salesforceCompositeGraphAction,
    requiredAuth: auth,
    scope: 'write' as const,
    keywords: ['deprecated', 'composite', 'graph', 'instead', 'tool'],
  },
  {
    name: 'salesforceCreateSObjectRecord',
    description: salesforceCreateSObjectRecord.description!,
    tool: salesforceCreateSObjectRecord,
    requiredAuth: auth,
    scope: 'write' as const,
    keywords: ['tool', 'type', 'specifying'],
  },
  {
    name: 'salesforceCreateSobjectTree',
    description: salesforceCreateSobjectTree.description!,
    tool: salesforceCreateSobjectTree,
    requiredAuth: auth,
    scope: 'write' as const,
    keywords: ['tool', 'trees', 'root', 'specified', 'type'],
  },
  {
    name: 'salesforceDeleteSobject',
    description: salesforceDeleteSobject.description!,
    tool: salesforceDeleteSobject,
    requiredAuth: auth,
    scope: 'delete' as const,
    keywords: ['tool', 'permanently', 'remove', 'operation', 'idempotent'],
  },
  {
    name: 'salesforceDeleteSobjectCollections',
    description: salesforceDeleteSobjectCollections.description!,
    tool: salesforceDeleteSobjectCollections,
    requiredAuth: auth,
    scope: 'delete' as const,
    keywords: ['tool', 'request', 'optional', 'rollback', 'efficiently'],
  },
  {
    name: 'salesforceGetCompositeResources',
    description: salesforceGetCompositeResources.description!,
    tool: salesforceGetCompositeResources,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['tool', 'available', 'composite', 'resources', 'discover'],
  },
  {
    name: 'salesforceGetCompositeSobjects',
    description: salesforceGetCompositeSobjects.description!,
    tool: salesforceGetCompositeSobjects,
    requiredAuth: auth,
    scope: 'write' as const,
    keywords: ['retrieves', 'same', 'type', 'request', 'body'],
  },
  {
    name: 'salesforceGetSobjectByExternalId',
    description: salesforceGetSobjectByExternalId.description!,
    tool: salesforceGetSobjectByExternalId,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['tool', 'matching', 'external', 'find', 'identifier'],
  },
  {
    name: 'salesforceGetSobjectCollections',
    description: salesforceGetSobjectCollections.description!,
    tool: salesforceGetSobjectCollections,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['tool', 'same', 'type', 'call', 'their'],
  },
  {
    name: 'salesforceGetSObjectRecord',
    description: salesforceGetSObjectRecord.description!,
    tool: salesforceGetSObjectRecord,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['tool', 'type', 'detailed', 'about'],
  },
  {
    name: 'salesforceGetSobjectRelationship',
    description: salesforceGetSobjectRelationship.description!,
    tool: salesforceGetSobjectRelationship,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['retrieves', 'traversing', 'relationships', 'friendly', 'urls'],
  },
  {
    name: 'salesforceGetSObjectsUpdated',
    description: salesforceGetSObjectsUpdated.description!,
    tool: salesforceGetSObjectsUpdated,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['tool', 'have', 'been', 'updated', 'given'],
  },
  {
    name: 'salesforcePatchCompositeSobjects',
    description: salesforcePatchCompositeSobjects.description!,
    tool: salesforcePatchCompositeSobjects,
    requiredAuth: auth,
    scope: 'write' as const,
    keywords: ['tool', 'upsert', 'external', 'matching', 'efficiently'],
  },
  {
    name: 'salesforcePostCompositeGraph',
    description: salesforcePostCompositeGraph.description!,
    tool: salesforcePostCompositeGraph,
    requiredAuth: auth,
    scope: 'write' as const,
    keywords: ['tool', 'rest', 'requests', 'transactional', 'call'],
  },
  {
    name: 'salesforcePostCompositeSobjects',
    description: salesforcePostCompositeSobjects.description!,
    tool: salesforcePostCompositeSobjects,
    requiredAuth: auth,
    scope: 'write' as const,
    keywords: ['tool', 'request', 'collections', 'potentially', 'different'],
  },
  {
    name: 'salesforceSobjectRowsUpdate',
    description: salesforceSobjectRowsUpdate.description!,
    tool: salesforceSobjectRowsUpdate,
    requiredAuth: auth,
    scope: 'write' as const,
    keywords: ['tool', 'modify', 'affecting'],
  },
  {
    name: 'salesforceUpsertSobjectByExternalId',
    description: salesforceUpsertSobjectByExternalId.description!,
    tool: salesforceUpsertSobjectByExternalId,
    requiredAuth: auth,
    scope: 'write' as const,
    keywords: ['tool', 'upsert', 'rows', 'external', 'creates'],
  },
  {
    name: 'salesforceCreateARecord',
    description: salesforceCreateARecord.description!,
    tool: salesforceCreateARecord,
    requiredAuth: auth,
    scope: 'write' as const,
    keywords: ['tool', 'type', 'layout', 'metadata', 'formatted'],
  },
  {
    name: 'salesforceGetABatchOfRecords',
    description: salesforceGetABatchOfRecords.description!,
    tool: salesforceGetABatchOfRecords,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['tool', 'request', 'customizable', 'selection', 'once'],
  },
  {
    name: 'salesforceGetAllFieldsForObject',
    description: salesforceGetAllFieldsForObject.description!,
    tool: salesforceGetAllFieldsForObject,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['retrieves', 'complete', 'metadata', 'including', 'types'],
  },
  {
    name: 'salesforceGetAllNavigationItems',
    description: salesforceGetAllNavigationItems.description!,
    tool: salesforceGetAllNavigationItems,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['gets', 'navigation', 'items', 'tabs', 'access'],
  },
  {
    name: 'salesforceGetApp',
    description: salesforceGetApp.description!,
    tool: salesforceGetApp,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['tool', 'metadata', 'about', 'configuration', 'navigation'],
  },
  {
    name: 'salesforceGetApps',
    description: salesforceGetApps.description!,
    tool: salesforceGetApps,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['tool', 'metadata', 'access', 'available', 'applications'],
  },
  {
    name: 'salesforceGetChildRecords',
    description: salesforceGetChildRecords.description!,
    tool: salesforceGetChildRecords,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['tool', 'specified', 'relationship', 'name', 'parent-child'],
  },
  {
    name: 'salesforceGetCompactLayouts',
    description: salesforceGetCompactLayouts.description!,
    tool: salesforceGetCompactLayouts,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['tool', 'compact', 'layout', 'display', 'form'],
  },
  {
    name: 'salesforceGetGlobalActions',
    description: salesforceGetGlobalActions.description!,
    tool: salesforceGetGlobalActions,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['tool', 'displayed', 'menu', 'metadata', 'discover'],
  },
  {
    name: 'salesforceGetLastSelectedApp',
    description: salesforceGetLastSelectedApp.description!,
    tool: salesforceGetLastSelectedApp,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['retrieves', 'last', 'selected', 'sees', 'determine'],
  },
  {
    name: 'salesforceGetListViewActions',
    description: salesforceGetListViewActions.description!,
    tool: salesforceGetListViewActions,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['tool', 'header', 'views', 'available', 'buttons'],
  },
  {
    name: 'salesforceGetListViewMetadataByName',
    description: salesforceGetListViewMetadataByName.description!,
    tool: salesforceGetListViewMetadataByName,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['returns', 'metadata', 'name', 'complete', 'including'],
  },
  {
    name: 'salesforceGetListViewRecordsById',
    description: salesforceGetListViewRecordsById.description!,
    tool: salesforceGetListViewRecordsById,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['returns'],
  },
  {
    name: 'salesforceGetListViewRecordsByName',
    description: salesforceGetListViewRecordsByName.description!,
    tool: salesforceGetListViewRecordsByName,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['retrieves', 'paginated', 'specified', 'names', 'match'],
  },
  {
    name: 'salesforceGetLookupFieldSuggestions',
    description: salesforceGetLookupFieldSuggestions.description!,
    tool: salesforceGetLookupFieldSuggestions,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['tool', 'suggestions', 'editing', 'filtering', 'searching'],
  },
  {
    name: 'salesforceGetLookupSuggestionsCaseContact',
    description: salesforceGetLookupSuggestionsCaseContact.description!,
    tool: salesforceGetLookupSuggestionsCaseContact,
    requiredAuth: auth,
    scope: 'write' as const,
    keywords: ['tool', 'suggestions', 'request', 'editing', 'dependent'],
  },
  {
    name: 'salesforceGetMruListViewMetadata',
    description: salesforceGetMruListViewMetadata.description!,
    tool: salesforceGetMruListViewMetadata,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['tool', 'metadata', 'understand', 'structure', 'configuration'],
  },
  {
    name: 'salesforceGetMruListViewRecords',
    description: salesforceGetMruListViewRecords.description!,
    tool: salesforceGetMruListViewRecords,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['tool', 'recently', 'accessed', 'type'],
  },
  {
    name: 'salesforceGetObjectListViews',
    description: salesforceGetObjectListViews.description!,
    tool: salesforceGetObjectListViews,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['returns', 'collection', 'views', 'associated', 'discover'],
  },
  {
    name: 'salesforceGetPhotoActions',
    description: salesforceGetPhotoActions.description!,
    tool: salesforceGetPhotoActions,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['tool', 'available', 'photo', 'pages', 'management'],
  },
  {
    name: 'salesforceGetPicklistValuesByRecordType',
    description: salesforceGetPicklistValuesByRecordType.description!,
    tool: salesforceGetPicklistValuesByRecordType,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['tool', 'picklist', 'type', 'including', 'dependent'],
  },
  {
    name: 'salesforceGetRecordEditPageActions',
    description: salesforceGetRecordEditPageActions.description!,
    tool: salesforceGetRecordEditPageActions,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['tool', 'available', 'edit', 'pages', 'metadata'],
  },
  {
    name: 'salesforceGetRelatedListActions',
    description: salesforceGetRelatedListActions.description!,
    tool: salesforceGetRelatedListActions,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['tool', 'lists', 'detail', 'pages', 'metadata'],
  },
  {
    name: 'salesforceGetRelatedListPreferencesBatch',
    description: salesforceGetRelatedListPreferencesBatch.description!,
    tool: salesforceGetRelatedListPreferencesBatch,
    requiredAuth: auth,
    scope: 'write' as const,
    keywords: ['tool', 'preferences', 'retrieving', 'display', 'column'],
  },
  {
    name: 'salesforceGetRelatedListRecordsContacts',
    description: salesforceGetRelatedListRecordsContacts.description!,
    tool: salesforceGetRelatedListRecordsContacts,
    requiredAuth: auth,
    scope: 'write' as const,
    keywords: ['tool', 'request', 'body', 'parameters', 'filtering'],
  },
  {
    name: 'salesforceGetSobjectPlatformaction',
    description: salesforceGetSobjectPlatformaction.description!,
    tool: salesforceGetSobjectPlatformaction,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['retrieves', 'metadata', 'description', 'platformaction', 'understand'],
  },
  {
    name: 'salesforceGetSObjectsDescribeLayoutsRecordTypeId',
    description: salesforceGetSObjectsDescribeLayoutsRecordTypeId.description!,
    tool: salesforceGetSObjectsDescribeLayoutsRecordTypeId,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['tool', 'layout', 'metadata', 'type', 'detailed'],
  },
  {
    name: 'salesforceGetSobjectsSobjectDescribeApprovallayouts',
    description: salesforceGetSobjectsSobjectDescribeApprovallayouts.description!,
    tool: salesforceGetSobjectsSobjectDescribeApprovallayouts,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['retrieves', 'approval', 'layouts', 'specified', 'understand'],
  },
  {
    name: 'salesforceGetSupportedObjectsDirectory',
    description: salesforceGetSupportedObjectsDirectory.description!,
    tool: salesforceGetSupportedObjectsDirectory,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['tool', 'active', 'directory', 'supported', 'discover'],
  },
  {
    name: 'salesforceGetUiApiActionsLookupAccount',
    description: salesforceGetUiApiActionsLookupAccount.description!,
    tool: salesforceGetUiApiActionsLookupAccount,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['tool', 'available', 'type'],
  },
  {
    name: 'salesforceGetUiapiActionsMruListAccount',
    description: salesforceGetUiapiActionsMruListAccount.description!,
    tool: salesforceGetUiapiActionsMruListAccount,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['tool', 'header', 'available', 'recently', 'specified'],
  },
  {
    name: 'salesforceGetUiApiActionsRecordRelatedList',
    description: salesforceGetUiApiActionsRecordRelatedList.description!,
    tool: salesforceGetUiApiActionsRecordRelatedList,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['tool', 'available', 'lists', 'detail', 'page'],
  },
  {
    name: 'salesforceGetUiApiAppsUserNavItems',
    description: salesforceGetUiApiAppsUserNavItems.description!,
    tool: salesforceGetUiApiAppsUserNavItems,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['tool', 'personalized', 'navigation', 'items', 'tabs'],
  },
  {
    name: 'salesforceGetUiapiListInfoAccountAllAccounts',
    description: salesforceGetUiapiListInfoAccountAllAccounts.description!,
    tool: salesforceGetUiapiListInfoAccountAllAccounts,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['retrieves', 'metadata', 'allaccounts', 'understand', 'structure'],
  },
  {
    name: 'salesforceGetUiapiListInfoAccountRecent',
    description: salesforceGetUiapiListInfoAccountRecent.description!,
    tool: salesforceGetUiapiListInfoAccountRecent,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['tool', 'metadata', 'configuration', 'including', 'columns'],
  },
  {
    name: 'salesforceGetUiapiListInfoAccountSearchResult',
    description: salesforceGetUiapiListInfoAccountSearchResult.description!,
    tool: salesforceGetUiapiListInfoAccountSearchResult,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['retrieves', 'metadata', 'searchresult', 'understand', 'structure'],
  },
  {
    name: 'salesforceGetUiApiListInfoRecent',
    description: salesforceGetUiApiListInfoRecent.description!,
    tool: salesforceGetUiApiListInfoRecent,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['tool', 'views', 'available', 'options', 'filter'],
  },
  {
    name: 'salesforceGetUiapimruListInfoAccount',
    description: salesforceGetUiapimruListInfoAccount.description!,
    tool: salesforceGetUiapimruListInfoAccount,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['tool', 'recently', 'metadata', 'settings', 'display'],
  },
  {
    name: 'salesforceGetUiApiMruListRecordsAccount',
    description: salesforceGetUiApiMruListRecordsAccount.description!,
    tool: salesforceGetUiApiMruListRecordsAccount,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['tool', 'recently', 'accessed', 'endpoint', 'deprecated'],
  },
  {
    name: 'salesforceGetUiApiRecordUi',
    description: salesforceGetUiApiRecordUi.description!,
    tool: salesforceGetUiApiRecordUi,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['tool', 'layout', 'metadata', 'response', 'comprehensive'],
  },
  {
    name: 'salesforceGetUiapiRelatedListPreferences',
    description: salesforceGetUiapiRelatedListPreferences.description!,
    tool: salesforceGetUiapiRelatedListPreferences,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['tool', 'preferences', 'display', 'settings', 'column'],
  },
  {
    name: 'salesforceUpdateListViewPreferences',
    description: salesforceUpdateListViewPreferences.description!,
    tool: salesforceUpdateListViewPreferences,
    requiredAuth: auth,
    scope: 'write' as const,
    keywords: ['tool', 'preferences', 'including', 'column', 'widths'],
  },
  {
    name: 'salesforceUpdateRecord',
    description: salesforceUpdateRecord.description!,
    tool: salesforceUpdateRecord,
    requiredAuth: auth,
    scope: 'write' as const,
    keywords: ['tool', 'modify', 'validation', 'rules', 'enforced'],
  },
  {
    name: 'salesforceUpdateRelatedListPreferences',
    description: salesforceUpdateRelatedListPreferences.description!,
    tool: salesforceUpdateRelatedListPreferences,
    requiredAuth: auth,
    scope: 'write' as const,
    keywords: ['tool', 'preferences', 'customizing', 'display', 'settings'],
  },
];
