// @ts-nocheck
import {
    configureCloudIntegration,
    createApiAccessKeys,
    createServiceLevel,
    createUser,
    deleteApiAccessKeys,
    deleteUserManagementUser,
    deleteWorkload,
    disableCloudIntegration,
    duplicateWorkload,
    linkCloudAccount,
    renameCloudAccount,
    revokeAuthorizationAccess,
    updateAccount,
    updateApiAccessKeys,
    updateServiceLevel,
    updateUser,
    updateWorkload,
} from './admin.js';
import {
    getAppMetricData,
    getAppMetricsNames,
    getApplications,
    getBrowserApplications,
    getLookupTable,
    getMobileApplication,
    getMobileApplicationMetrics,
    getMobileMetricData,
    getSecureCredential,
    listDeployments,
    listKeyTransactions,
    listLookupTables,
    listMobileApplications,
    listSecureCredentials,
    createLookupTable,
    createSecureCredential,
    deleteLookupTable,
    deleteSecureCredential,
    updateLookupTable,
    updateSecureCredential,
} from './apm.js';
import {
    addNotificationChannelsToPolicy,
    createAlertPolicy,
    createAlertPolicyGraphql,
    deleteAlertPolicy,
    deleteAlertPolicyGraphql,
    deleteAlertsCondition,
    deletePolicyChannel,
    getAlertPolicies,
    removeNotificationChannelsFromPolicy,
    updateAlertPolicy,
    updateAlertPolicyRest,
    updateCrossAccountElections,
    updatePolicyChannels,
} from './alert-policies.js';
import {
    createDeploymentMarker,
    createEntityRelationship,
    createExampleBrowserApplication,
    createExampleMobileApplication,
    deleteAgentApplication,
    deleteEntity,
    deleteEntityRelationshipUserDefined,
    addTagsToEntity,
    deleteTagValuesFromEntity,
    overrideEntityGoldenMetrics,
    overrideEntityGoldenTags,
    replaceTagsOnEntity,
    resetEntityGoldenMetrics,
    resetEntityGoldenTags,
    updateAgentApplicationSettings,
    updateBrowserSettings,
    updateMobileSettingsExample,
} from './entities.js';
import {
    createBrokenLinksMonitor,
    createMonitor,
    createScriptedMonitor,
    createSyntheticsPrivateLocation,
    createSyntheticsSecureCredential,
    createSyntheticsSimpleMonitor,
    deleteMonitor,
    deleteSyntheticsMonitorGraphql,
    deleteSyntheticsPrivateLocation,
    deleteSyntheticsSecureCredential,
    getSynthMonitor,
    listLocations,
    listMonitors,
    patchMonitor,
    updateMonitorScript,
    updateScriptedMonitor,
    updateSynthMonitor,
    updateSyntheticsSimpleMonitor,
} from './synthetics.js';
import {
    createAiNotificationsChannel,
    createAiNotificationsDestination,
    createAiWorkflow,
    createAlertChannel,
    deleteAiNotificationsChannel,
    deleteAiNotificationsDestination,
    deleteAlertChannel,
    getAlertChannels,
    testAiNotificationDestinationById,
    testAiNotificationsChannel,
    testAiNotificationsDestination,
    testNotificationChannel,
    updateAiNotificationsChannel,
    updateAiNotificationsDestination,
    updateAlertChannel,
    updateWorkflow,
} from './notifications.js';
import {
    createExternalServiceCondition,
    createInfraCondition,
    createLocationFailureCondition,
    createSyntheticsAlertCondition,
    deleteExternalServiceCondition,
    deleteInfraCondition,
    deleteLocationFailureCondition,
    deleteSyntheticsCondition,
    getAlertConditions,
    getAlertsViolations,
    getInfraCondition,
    listExternalServiceConditions,
    listInfraConditions,
    listLocationFailureConditions,
    listSyntheticsConditions,
    removeEntityCondition,
    updateExternalServiceCondition,
    updateInfraCondition,
    updateLocationFailureCondition,
    updateSyntheticsAlertCondition,
} from './conditions.js';
import {
    createDashboard,
    addWidgetsToDashboardPage,
    createDashboardSnapshotUrl,
    deleteDashboard,
    getDashboardEntity,
    undeleteDashboard,
    updateDashboard,
    updateDashboardLiveUrlCreationPolicies,
    updateDashboardPage,
    updateDashboardWidgetsInPage,
} from './dashboards.js';
import {
    createLogDataPartitionRule,
    createMetricNormalizationRule,
    deleteDataPartitionRule,
    disableMetricNormalizationRule,
    editMetricNormalizationRule,
    enableMetricNormalizationRule,
    fetchBrowserConfiguration,
    fetchBrowserJavaScriptSnippet,
    fetchMobileApplicationToken,
    updateDataPartitionRule,
} from './config.js';
import {
    createNrqlBaselineCondition,
    createNrqlCondition,
    createStaticNrqlCondition,
    deleteNrqlCondition,
    listNrqlConditions,
    updateNrqlBaselineCondition,
    updateNrqlCondition,
    updateStaticNrqlCondition,
} from './nrql-conditions.js';
import {
    executeNrqlQuery,
    fetchRulesCollection,
    fetchYourOrgId,
    queryCloudProviders,
    queryError,
    queryExampleReadQuery,
    searchEntities,
} from './nrql.js';
import { sendEvents, sendTraces } from './ingest.js';

export {
    executeNrqlQuery, queryError, queryExampleReadQuery, searchEntities, fetchRulesCollection,
    fetchYourOrgId, queryCloudProviders,
    createAlertPolicy, getAlertPolicies, updateAlertPolicyRest, deleteAlertPolicy,
    createAlertPolicyGraphql, updateAlertPolicy, deleteAlertPolicyGraphql, deleteAlertsCondition,
    updateCrossAccountElections, addNotificationChannelsToPolicy, removeNotificationChannelsFromPolicy,
    updatePolicyChannels, deletePolicyChannel,
    createStaticNrqlCondition, updateStaticNrqlCondition, createNrqlBaselineCondition,
    updateNrqlBaselineCondition, createNrqlCondition, updateNrqlCondition, deleteNrqlCondition,
    listNrqlConditions,
    createExternalServiceCondition, updateExternalServiceCondition, deleteExternalServiceCondition,
    listExternalServiceConditions, createSyntheticsAlertCondition, updateSyntheticsAlertCondition,
    deleteSyntheticsCondition, listSyntheticsConditions, createLocationFailureCondition,
    updateLocationFailureCondition, deleteLocationFailureCondition, listLocationFailureConditions,
    createInfraCondition, getInfraCondition, listInfraConditions, updateInfraCondition,
    deleteInfraCondition, getAlertConditions, removeEntityCondition, getAlertsViolations,
    createAiNotificationsChannel, updateAiNotificationsChannel, deleteAiNotificationsChannel,
    testAiNotificationsChannel, testNotificationChannel, createAiNotificationsDestination,
    updateAiNotificationsDestination, deleteAiNotificationsDestination, testAiNotificationsDestination,
    testAiNotificationDestinationById, createAiWorkflow, updateWorkflow,
    createAlertChannel, getAlertChannels, updateAlertChannel, deleteAlertChannel,
    createDashboard, updateDashboard, deleteDashboard, undeleteDashboard, createDashboardSnapshotUrl,
    getDashboardEntity, addWidgetsToDashboardPage, updateDashboardPage, updateDashboardWidgetsInPage,
    updateDashboardLiveUrlCreationPolicies,
    createMonitor, getSynthMonitor, listMonitors, patchMonitor, updateSynthMonitor, deleteMonitor,
    updateMonitorScript, listLocations, createSyntheticsSimpleMonitor, updateSyntheticsSimpleMonitor,
    createScriptedMonitor, updateScriptedMonitor, createBrokenLinksMonitor,
    createSyntheticsPrivateLocation, deleteSyntheticsPrivateLocation, deleteSyntheticsMonitorGraphql,
    createSyntheticsSecureCredential, deleteSyntheticsSecureCredential,
    getApplications, getAppMetricsNames, getAppMetricData, listDeployments, listKeyTransactions,
    getBrowserApplications, listMobileApplications, getMobileApplication, getMobileApplicationMetrics,
    getMobileMetricData, createSecureCredential, getSecureCredential, listSecureCredentials,
    updateSecureCredential, deleteSecureCredential, createLookupTable, getLookupTable,
    listLookupTables, updateLookupTable, deleteLookupTable,
    createUser, updateUser, deleteUserManagementUser, updateAccount, revokeAuthorizationAccess,
    createApiAccessKeys, updateApiAccessKeys, deleteApiAccessKeys, linkCloudAccount, renameCloudAccount,
    configureCloudIntegration, disableCloudIntegration, createServiceLevel, updateServiceLevel,
    updateWorkload, duplicateWorkload, deleteWorkload,
    deleteEntity, createEntityRelationship, deleteEntityRelationshipUserDefined, addTagsToEntity,
    deleteTagValuesFromEntity, replaceTagsOnEntity, overrideEntityGoldenMetrics, resetEntityGoldenMetrics,
    overrideEntityGoldenTags, resetEntityGoldenTags, createDeploymentMarker,
    createExampleBrowserApplication, createExampleMobileApplication, deleteAgentApplication,
    updateAgentApplicationSettings, updateBrowserSettings, updateMobileSettingsExample,
    createMetricNormalizationRule, editMetricNormalizationRule, enableMetricNormalizationRule,
    disableMetricNormalizationRule, createLogDataPartitionRule, updateDataPartitionRule,
    deleteDataPartitionRule, fetchBrowserConfiguration, fetchBrowserJavaScriptSnippet,
    fetchMobileApplicationToken, sendEvents, sendTraces,
};

const auth = 'newRelicApiKey' as const;

type Scope = 'read' | 'write' | 'delete';
function entry(name: string, description: string, toolRef: any, scope: Scope, noAuth = false): { name: string; description: string; tool: any; requiredAuth?: typeof auth; scope: Scope } {
    return noAuth ? { name, description, tool: toolRef, scope } : { name, description, tool: toolRef, requiredAuth: auth, scope };
}

export const newRelicTools = [
    entry('newRelicExecuteNrqlQuery', 'Executes a NRQL query against telemetry data (sync or async).', executeNrqlQuery, 'read'),
    entry('newRelicQueryError', 'Queries error data with a custom NRQL query.', queryError, 'read'),
    entry('newRelicQueryExampleReadQuery', 'Executes any raw GraphQL read query against NerdGraph.', queryExampleReadQuery, 'read'),
    entry('newRelicSearchEntities', 'Searches entities by name/type/domain; returns GUIDs (200/page).', searchEntities, 'read'),
    entry('newRelicFetchRulesCollection', 'Fetches rules from a Scorecard collection with pagination.', fetchRulesCollection, 'read'),
    entry('newRelicFetchYourOrgId', 'Returns the organization ID and name for the API key.', fetchYourOrgId, 'read'),
    entry('newRelicQueryCloudProviders', 'Lists cloud providers configured for an account.', queryCloudProviders, 'read'),
    entry('newRelicCreateAlertPolicy', 'Creates an alert policy via REST API v2.', createAlertPolicy, 'write'),
    entry('newRelicGetAlertPolicies', 'Lists alert policies with filters and pagination.', getAlertPolicies, 'read'),
    entry('newRelicUpdateAlertPolicyRest', 'Updates a policy name/incident preference via REST.', updateAlertPolicyRest, 'write'),
    entry('newRelicDeleteAlertPolicy', 'Deletes an alert policy via REST.', deleteAlertPolicy, 'delete'),
    entry('newRelicCreateAlertsPolicyGraphql', 'Creates an alert policy via NerdGraph.', createAlertPolicyGraphql, 'write'),
    entry('newRelicUpdateAlertPolicy', 'Updates a policy via NerdGraph.', updateAlertPolicy, 'write'),
    entry('newRelicDeleteAlertsPolicyViaGraphql', 'Deletes an alert policy via NerdGraph.', deleteAlertPolicyGraphql, 'delete'),
    entry('newRelicDeleteAlertsCondition', 'Deletes any alert condition type via NerdGraph.', deleteAlertsCondition, 'delete'),
    entry('newRelicUpdateCrossAccountElections', 'Enables/disables cross-account alerting for up to 20 accounts.', updateCrossAccountElections, 'write'),
    entry('newRelicAddNotificationChannelsToPolicy', 'Associates notification channels with a policy via NerdGraph.', addNotificationChannelsToPolicy, 'write'),
    entry('newRelicRemoveNotificationChannelsFromPolicy', 'Detaches notification channels from a policy via NerdGraph.', removeNotificationChannelsFromPolicy, 'write'),
    entry('newRelicUpdatePolicyChannels', 'Replaces all channel associations on a policy via REST.', updatePolicyChannels, 'write'),
    entry('newRelicDeletePolicyChannel', 'Removes one channel from a policy via REST.', deletePolicyChannel, 'delete'),
    entry('newRelicCreateAlertsNrqlConditionStatic', 'Creates a static NRQL alert condition via NerdGraph.', createStaticNrqlCondition, 'write'),
    entry('newRelicUpdateNrqlStaticCondition', 'Updates a static NRQL condition via NerdGraph.', updateStaticNrqlCondition, 'write'),
    entry('newRelicCreateNrqlBaselineCondition', 'Creates a baseline (anomaly) NRQL condition via NerdGraph.', createNrqlBaselineCondition, 'write'),
    entry('newRelicUpdateNrqlBaselineCondition', 'Updates a baseline NRQL condition via NerdGraph.', updateNrqlBaselineCondition, 'write'),
    entry('newRelicCreateNrqlCondition', 'Creates a NRQL condition via REST API v2.', createNrqlCondition, 'write'),
    entry('newRelicUpdateNrqlCondition', 'Updates a NRQL condition via REST API v2.', updateNrqlCondition, 'write'),
    entry('newRelicDeleteNrqlCondition', 'Deletes a NRQL condition via REST.', deleteNrqlCondition, 'delete'),
    entry('newRelicListNrqlConditions', 'Lists NRQL conditions for a policy via REST.', listNrqlConditions, 'read'),
    entry('newRelicCreateExternalServiceCondition', 'Creates an external-service condition via REST.', createExternalServiceCondition, 'write'),
    entry('newRelicUpdateExternalServiceCondition', 'Updates an external-service condition via REST.', updateExternalServiceCondition, 'write'),
    entry('newRelicDeleteExternalServiceCondition', 'Deletes an external-service condition via REST.', deleteExternalServiceCondition, 'delete'),
    entry('newRelicListExternalServiceConditions', 'Lists external-service conditions for a policy.', listExternalServiceConditions, 'read'),
    entry('newRelicCreateSyntheticsAlertCondition', 'Creates a synthetics condition via REST.', createSyntheticsAlertCondition, 'write'),
    entry('newRelicUpdateSyntheticsAlertCondition', 'Updates a synthetics condition via REST.', updateSyntheticsAlertCondition, 'write'),
    entry('newRelicDeleteSyntheticsCondition', 'Deletes a synthetics condition via REST.', deleteSyntheticsCondition, 'delete'),
    entry('newRelicListSyntheticsConditions', 'Lists synthetics conditions for a policy.', listSyntheticsConditions, 'read'),
    entry('newRelicCreateLocationFailureCondition', 'Creates a multi-location failure condition via REST.', createLocationFailureCondition, 'write'),
    entry('newRelicUpdateLocationFailureCondition', 'Updates a location-failure condition via REST.', updateLocationFailureCondition, 'write'),
    entry('newRelicDeleteLocationFailureCondition', 'Deletes a location-failure condition via REST.', deleteLocationFailureCondition, 'delete'),
    entry('newRelicListLocationFailureConditions', 'Lists location-failure conditions for a policy.', listLocationFailureConditions, 'read'),
    entry('newRelicCreateInfraCondition', 'Creates an infrastructure condition via the Infrastructure API.', createInfraCondition, 'write'),
    entry('newRelicGetInfraCondition', 'Reads one infrastructure condition by ID.', getInfraCondition, 'read'),
    entry('newRelicListInfraConditions', 'Lists infrastructure conditions for a policy (limit/offset).', listInfraConditions, 'read'),
    entry('newRelicUpdateInfraCondition', 'Updates an infrastructure condition.', updateInfraCondition, 'write'),
    entry('newRelicDeleteInfraCondition', 'Deletes an infrastructure condition.', deleteInfraCondition, 'delete'),
    entry('newRelicGetAlertConditions', 'Lists APM/browser/mobile conditions for a policy.', getAlertConditions, 'read'),
    entry('newRelicRemoveEntityCondition', 'Removes an entity from an alert condition.', removeEntityCondition, 'delete'),
    entry('newRelicGetAlertsViolations', 'Lists alert violations with date/open filters.', getAlertsViolations, 'read'),
    entry('newRelicCreateAiNotificationsChannel', 'Creates an AI Notifications channel.', createAiNotificationsChannel, 'write'),
    entry('newRelicUpdateAiNotificationsChannel', 'Updates an AI channel name/active status.', updateAiNotificationsChannel, 'write'),
    entry('newRelicDeleteAiNotificationsChannel', 'Deletes an AI notifications channel.', deleteAiNotificationsChannel, 'delete'),
    entry('newRelicTestAiNotificationsChannel', 'Tests an AI channel configuration before saving.', testAiNotificationsChannel, 'read'),
    entry('newRelicTestNotificationChannel', 'Sends a test notification through an AI channel.', testNotificationChannel, 'read'),
    entry('newRelicCreateAiNotificationsDestination', 'Creates an AI notifications destination.', createAiNotificationsDestination, 'write'),
    entry('newRelicUpdateAiNotificationsDestination', 'Renames an AI destination.', updateAiNotificationsDestination, 'write'),
    entry('newRelicDeleteAiNotificationsDestination', 'Deletes an AI notifications destination.', deleteAiNotificationsDestination, 'delete'),
    entry('newRelicTestAiNotificationsDestination', 'Validates a destination configuration.', testAiNotificationsDestination, 'read'),
    entry('newRelicTestAiNotificationDestinationById', 'Tests an existing destination by UUID.', testAiNotificationDestinationById, 'read'),
    entry('newRelicCreateAiWorkflow', 'Creates an AI workflow routing issues to channels.', createAiWorkflow, 'write'),
    entry('newRelicUpdateWorkflow', 'Updates an AI workflow.', updateWorkflow, 'write'),
    entry('newRelicCreateAlertChannel', 'Registers a legacy alert channel endpoint.', createAlertChannel, 'write'),
    entry('newRelicGetAlertChannels', 'Lists legacy alert channels.', getAlertChannels, 'read'),
    entry('newRelicUpdateAlertChannel', 'Updates a legacy alert channel.', updateAlertChannel, 'write'),
    entry('newRelicDeleteAlertChannel', 'Deletes a legacy alert channel.', deleteAlertChannel, 'delete'),
    entry('newRelicCreateDashboard', 'Creates a dashboard with pages and widgets.', createDashboard, 'write'),
    entry('newRelicUpdateDashboard', 'Updates a dashboard (pages/widgets replacement).', updateDashboard, 'write'),
    entry('newRelicDeleteDashboard', 'Permanently deletes a dashboard.', deleteDashboard, 'delete'),
    entry('newRelicUndeleteDashboard', 'Recovers a deleted dashboard.', undeleteDashboard, 'write'),
    entry('newRelicCreateDashboardSnapshotUrl', 'Generates a shareable dashboard snapshot URL.', createDashboardSnapshotUrl, 'read'),
    entry('newRelicGetDashboardEntityQuery', 'Reads full dashboard configuration by GUID.', getDashboardEntity, 'read'),
    entry('newRelicAddWidgetsToDashboardPage', 'Adds widgets to a dashboard page.', addWidgetsToDashboardPage, 'write'),
    entry('newRelicUpdateDashboardPage', 'Updates a dashboard page and its widgets.', updateDashboardPage, 'write'),
    entry('newRelicUpdateDashboardWidgetsInPage', 'Updates widgets within a dashboard page.', updateDashboardWidgetsInPage, 'write'),
    entry('newRelicUpdateDashboardLiveUrlCreationPolicies', 'Enables/disables public live-URL creation per account.', updateDashboardLiveUrlCreationPolicies, 'write'),
    entry('newRelicCreateMonitor', 'Creates a legacy synthetic monitor via REST v3.', createMonitor, 'write'),
    entry('newRelicGetSynthMonitor', 'Reads one synthetic monitor by UUID.', getSynthMonitor, 'read'),
    entry('newRelicListMonitors', 'Lists synthetic monitors (limit/offset).', listMonitors, 'read'),
    entry('newRelicPatchMonitor', 'Partially updates a synthetic monitor.', patchMonitor, 'write'),
    entry('newRelicUpdateSynthMonitor', 'Fully replaces a synthetic monitor via PUT.', updateSynthMonitor, 'write'),
    entry('newRelicDeleteMonitor', 'Permanently deletes a synthetic monitor.', deleteMonitor, 'delete'),
    entry('newRelicUpdateMonitorScript', 'Updates a scripted monitor script (base64).', updateMonitorScript, 'write'),
    entry('newRelicListLocations', 'Lists valid synthetic monitor locations.', listLocations, 'read'),
    entry('newRelicCreateSyntheticsSimpleMonitor', 'Creates a ping monitor via NerdGraph.', createSyntheticsSimpleMonitor, 'write'),
    entry('newRelicUpdateSyntheticsSimpleMonitor', 'Updates a ping monitor via NerdGraph.', updateSyntheticsSimpleMonitor, 'write'),
    entry('newRelicCreateScriptedMonitor', 'Creates a scripted browser/API monitor via NerdGraph.', createScriptedMonitor, 'write'),
    entry('newRelicUpdateScriptedMonitor', 'Updates a scripted monitor via NerdGraph.', updateScriptedMonitor, 'write'),
    entry('newRelicCreateBrokenLinksMonitor', 'Creates a broken-links monitor via NerdGraph.', createBrokenLinksMonitor, 'write'),
    entry('newRelicCreateSyntheticsPrivateLocation', 'Creates a private location for synthetics.', createSyntheticsPrivateLocation, 'write'),
    entry('newRelicDeleteSyntheticsPrivateLocation', 'Deletes a private location.', deleteSyntheticsPrivateLocation, 'delete'),
    entry('newRelicDeleteSyntheticsMonitorGraphql', 'Deletes a monitor by GUID via NerdGraph.', deleteSyntheticsMonitorGraphql, 'delete'),
    entry('newRelicCreateSyntheticsSecureCredential', 'Stores a synthetics credential via NerdGraph.', createSyntheticsSecureCredential, 'write'),
    entry('newRelicDeleteSyntheticsSecureCredential', 'Deletes a synthetics credential via NerdGraph.', deleteSyntheticsSecureCredential, 'delete'),
    entry('newRelicGetApplications', 'Lists APM applications with health and Apdex.', getApplications, 'read'),
    entry('newRelicGetAppMetricsNames', 'Lists available metric names for an app.', getAppMetricsNames, 'read'),
    entry('newRelicGetAppMetricData', 'Fetches app metric timeslice data.', getAppMetricData, 'read'),
    entry('newRelicListDeployments', 'Lists deployment markers for an app.', listDeployments, 'read'),
    entry('newRelicListKeyTransactions', 'Lists key transactions.', listKeyTransactions, 'read'),
    entry('newRelicGetBrowserApplications', 'Lists browser applications.', getBrowserApplications, 'read'),
    entry('newRelicListMobileApplications', 'Lists mobile applications.', listMobileApplications, 'read'),
    entry('newRelicGetMobileApplication', 'Reads one mobile app with crash metrics.', getMobileApplication, 'read'),
    entry('newRelicGetMobileApplicationMetrics', 'Lists metric names for a mobile app.', getMobileApplicationMetrics, 'read'),
    entry('newRelicGetMobileMetricData', 'Fetches mobile metric timeslices.', getMobileMetricData, 'read'),
    entry('newRelicCreateSecureCredential', 'Stores a credential via REST v3.', createSecureCredential, 'write'),
    entry('newRelicGetSecureCredential', 'Reads credential metadata (no secret value).', getSecureCredential, 'read'),
    entry('newRelicListSecureCredentials', 'Lists credential metadata for auditing.', listSecureCredentials, 'read'),
    entry('newRelicUpdateSecureCredential', 'Rotates a credential value/description.', updateSecureCredential, 'write'),
    entry('newRelicDeleteSecureCredential', 'Deletes a stored credential.', deleteSecureCredential, 'delete'),
    entry('newRelicCreateLookupTable', 'Uploads a lookup table for NRQL enrichment.', createLookupTable, 'write'),
    entry('newRelicGetLookupTable', 'Downloads a lookup table.', getLookupTable, 'read'),
    entry('newRelicListLookupTables', 'Lists lookup tables for an account.', listLookupTables, 'read'),
    entry('newRelicUpdateLookupTable', 'Fully replaces a lookup table.', updateLookupTable, 'write'),
    entry('newRelicDeleteLookupTable', 'Deletes a lookup table (irreversible).', deleteLookupTable, 'delete'),
    entry('newRelicCreateUser', 'Adds a user with an access tier.', createUser, 'write'),
    entry('newRelicUpdateUser', 'Updates user email/access tier.', updateUser, 'write'),
    entry('newRelicDeleteUserManagementUser', 'Removes a user.', deleteUserManagementUser, 'delete'),
    entry('newRelicUpdateAccount', 'Renames a managed account.', updateAccount, 'write'),
    entry('newRelicRevokeAuthorizationAccess', 'Revokes role grants from a group.', revokeAuthorizationAccess, 'write'),
    entry('newRelicCreateApiAccessKeys', 'Generates user/ingest API keys.', createApiAccessKeys, 'write'),
    entry('newRelicUpdateApiAccessKeys', 'Renames/re-notes API keys.', updateApiAccessKeys, 'write'),
    entry('newRelicDeleteApiAccessKeys', 'Permanently deletes API keys.', deleteApiAccessKeys, 'delete'),
    entry('newRelicLinkCloudAccount', 'Links AWS/Azure/GCP accounts for monitoring.', linkCloudAccount, 'write'),
    entry('newRelicRenameCloudAccount', 'Renames linked cloud accounts.', renameCloudAccount, 'write'),
    entry('newRelicConfigureCloudIntegration', 'Enables service monitoring on linked accounts.', configureCloudIntegration, 'write'),
    entry('newRelicDisableCloudIntegration', 'Stops one cloud-service integration.', disableCloudIntegration, 'delete'),
    entry('newRelicCreateServiceLevel', 'Creates an SLI with optional SLO targets.', createServiceLevel, 'write'),
    entry('newRelicUpdateServiceLevel', 'Updates an SLI/objectives.', updateServiceLevel, 'write'),
    entry('newRelicUpdateWorkload', 'Updates a workload configuration.', updateWorkload, 'write'),
    entry('newRelicDuplicateWorkload', 'Clones a workload.', duplicateWorkload, 'write'),
    entry('newRelicDeleteWorkload', 'Permanently deletes a workload.', deleteWorkload, 'delete'),
    entry('newRelicDeleteEntity', 'Deletes APM/EXT-SERVICE/REF-REPOSITORY entities.', deleteEntity, 'delete'),
    entry('newRelicCreateEntityRelationship', 'Creates/replaces a custom entity relationship.', createEntityRelationship, 'write'),
    entry('newRelicDeleteEntityRelationshipUserDefined', 'Removes custom entity relationships.', deleteEntityRelationshipUserDefined, 'delete'),
    entry('newRelicAddTagsToEntity', 'Adds tags to an entity.', addTagsToEntity, 'write'),
    entry('newRelicDeleteTagValuesFromEntity', 'Removes specific tag values.', deleteTagValuesFromEntity, 'delete'),
    entry('newRelicReplaceTagsOnEntity', 'Replaces the entire tag set.', replaceTagsOnEntity, 'write'),
    entry('newRelicOverrideEntityGoldenMetrics', 'Sets custom golden metrics for an entity type.', overrideEntityGoldenMetrics, 'write'),
    entry('newRelicResetEntityGoldenMetrics', 'Restores default golden metrics.', resetEntityGoldenMetrics, 'write'),
    entry('newRelicOverrideEntityGoldenTags', 'Sets golden tags for an entity type.', overrideEntityGoldenTags, 'write'),
    entry('newRelicResetEntityGoldenTags', 'Restores default golden tags.', resetEntityGoldenTags, 'write'),
    entry('newRelicCreateDeploymentMarker', 'Records a deployment marker on an entity.', createDeploymentMarker, 'write'),
    entry('newRelicCreateExampleBrowserApplication', 'Creates a browser application.', createExampleBrowserApplication, 'write'),
    entry('newRelicCreateExampleMobileApplication', 'Creates a mobile application.', createExampleMobileApplication, 'write'),
    entry('newRelicDeleteAgentApplication', 'Deletes an APM application (silent 12h+).', deleteAgentApplication, 'delete'),
    entry('newRelicUpdateAgentApplicationSettings', 'Toggles server-side config for an APM app.', updateAgentApplicationSettings, 'write'),
    entry('newRelicUpdateBrowserSettings', 'Updates browser agent settings.', updateBrowserSettings, 'write'),
    entry('newRelicUpdateMobileSettingsExample', 'Updates mobile crash/network settings.', updateMobileSettingsExample, 'write'),
    entry('newRelicCreateMetricNormalizationRule', 'Creates a metric normalization rule.', createMetricNormalizationRule, 'write'),
    entry('newRelicEditMetricNormalizationRule', 'Edits a metric normalization rule.', editMetricNormalizationRule, 'write'),
    entry('newRelicEnableMetricNormalizationRule', 'Reactivates a normalization rule.', enableMetricNormalizationRule, 'write'),
    entry('newRelicDisableMetricNormalizationRule', 'Deactivates a normalization rule.', disableMetricNormalizationRule, 'write'),
    entry('newRelicCreateLogDataPartitionRule', 'Creates a log data partition rule.', createLogDataPartitionRule, 'write'),
    entry('newRelicUpdateDataPartitionRule', 'Updates a log data partition rule.', updateDataPartitionRule, 'write'),
    entry('newRelicDeleteDataPartitionRule', 'Deletes a log data partition rule.', deleteDataPartitionRule, 'delete'),
    entry('newRelicFetchBrowserConfiguration', 'Reads browser app JS config.', fetchBrowserConfiguration, 'read'),
    entry('newRelicFetchBrowserJavaScriptSnippet', 'Reads the browser loader snippet.', fetchBrowserJavaScriptSnippet, 'read'),
    entry('newRelicFetchMobileApplicationToken', 'Reads the mobile application token.', fetchMobileApplicationToken, 'read'),
    entry('newRelicSendEvents', 'Sends custom events (Insights insert key).', sendEvents, 'write', true),
    entry('newRelicSendTraces', 'Sends distributed-trace spans (ingest key).', sendTraces, 'write', true),
];
