// @ts-nocheck
import {
    createReportTask,
    getReportTask,
    listReportTasks,
    queryReportTask,
    batchRunPivotReports,
    batchRunReports,
    checkCompatibility,
    getMetadata,
    runFunnelReport,
    runPivotReport,
    runRealtimeReport,
    runReport,
} from './reports.js';
import {
    createAudienceExport,
    createAudienceList,
    createRecurringAudienceList,
    getAudience,
    getAudienceExport,
    getAudienceList,
    getRecurringAudienceList,
    listAudienceExports,
    listAudienceLists,
    listAudiences,
    listRecurringAudienceLists,
    queryAudienceExport,
    queryAudienceList,
} from './audiences.js';
import {
    createRollupProperty,
    getAccount,
    getAttributionSettings,
    getDataRetentionSettings,
    getDataSharingSettings,
    getGoogleSignalsSettings,
    getProperty,
    getPropertyQuotasSnapshot,
    listAccountSummaries,
    listAccountsV1Beta,
    listPropertiesFiltered,
    provisionAccountTicket,
    updateProperty,
} from './admin.js';
import {
    archiveCustomDimension,
    createCustomDimension,
    createCustomMetric,
    createExpandedDataSet,
    getCustomDimension,
    listCalculatedMetrics,
    listCustomDimensions,
    listCustomMetrics,
    listExpandedDataSets,
} from './custom-definitions.js';
import {
    getKeyEvent,
    listAdsenseLinks,
    listBigqueryLinks,
    listChannelGroups,
    listConversionEvents,
    listDataStreams,
    listDv360AdLinks,
    listDv360LinkProposals,
    listEventCreateRules,
    listFirebaseLinks,
    listGoogleAdsLinks,
    listKeyEvents,
    listMeasurementProtocolSecrets,
    listReportingDataAnnotations,
    listSearchAds360Links,
    listSkAdNetworkSchemas,
    listSubpropertyEventFilters,
    listSubpropertySyncConfigs,
} from './links.js';
import { sendEvents, validateEvents } from './measurement.js';

export {
    runReport,
    batchRunReports,
    runPivotReport,
    batchRunPivotReports,
    runRealtimeReport,
    runFunnelReport,
    checkCompatibility,
    getMetadata,
    createReportTask,
    getReportTask,
    listReportTasks,
    queryReportTask,
    getAudience,
    listAudiences,
    createAudienceExport,
    getAudienceExport,
    listAudienceExports,
    queryAudienceExport,
    createAudienceList,
    getAudienceList,
    listAudienceLists,
    queryAudienceList,
    createRecurringAudienceList,
    getRecurringAudienceList,
    listRecurringAudienceLists,
    getAccount,
    listAccountsV1Beta,
    listAccountSummaries,
    provisionAccountTicket,
    getProperty,
    listPropertiesFiltered,
    updateProperty,
    createRollupProperty,
    getPropertyQuotasSnapshot,
    getAttributionSettings,
    getDataRetentionSettings,
    getDataSharingSettings,
    getGoogleSignalsSettings,
    createCustomDimension,
    getCustomDimension,
    listCustomDimensions,
    archiveCustomDimension,
    createCustomMetric,
    listCustomMetrics,
    listCalculatedMetrics,
    createExpandedDataSet,
    listExpandedDataSets,
    listAdsenseLinks,
    listBigqueryLinks,
    listChannelGroups,
    listConversionEvents,
    listKeyEvents,
    getKeyEvent,
    listDataStreams,
    listDv360AdLinks,
    listDv360LinkProposals,
    listEventCreateRules,
    listFirebaseLinks,
    listGoogleAdsLinks,
    listMeasurementProtocolSecrets,
    listSearchAds360Links,
    listSkAdNetworkSchemas,
    listSubpropertyEventFilters,
    listSubpropertySyncConfigs,
    listReportingDataAnnotations,
    sendEvents,
    validateEvents,
};

const auth = 'googleAnalyticsToken' as const;

function entry(name: string, description: string, toolRef: any, scope: 'read' | 'write' | 'delete', opts?: { noAuth?: boolean }): { name: string; description: string; tool: any; requiredAuth?: typeof auth; scope: 'read' | 'write' | 'delete' } {
    return {
        name,
        description,
        tool: toolRef,
        ...(opts?.noAuth ? {} : { requiredAuth: auth }),
        scope,
    };
}

export const googleAnalyticsTools = [
    entry('googleAnalyticsRunReport', 'Runs a standard GA4 report (dimensions x metrics over date ranges).', runReport, 'read'),
    entry('googleAnalyticsBatchRunReports', 'Runs multiple standard reports for one property in a single call.', batchRunReports, 'read'),
    entry('googleAnalyticsRunPivotReport', 'Runs a GA4 pivot-table report.', runPivotReport, 'read'),
    entry('googleAnalyticsBatchRunPivotReports', 'Runs multiple pivot reports for one property in a single call.', batchRunPivotReports, 'read'),
    entry('googleAnalyticsRunRealtimeReport', 'Runs a realtime report over the last 30 minutes of activity.', runRealtimeReport, 'read'),
    entry('googleAnalyticsRunFunnelReport', 'Runs a funnel analysis report.', runFunnelReport, 'read'),
    entry('googleAnalyticsCheckCompatibility', 'Lists dimensions/metrics compatible with a report request.', checkCompatibility, 'read'),
    entry('googleAnalyticsGetMetadata', 'Gets report metadata (available dimensions, metrics, comparisons).', getMetadata, 'read'),
    entry('googleAnalyticsCreateReportTask', 'Creates an async report task for large/complex reports.', createReportTask, 'write'),
    entry('googleAnalyticsGetReportTask', 'Gets report-task metadata and processing state.', getReportTask, 'read'),
    entry('googleAnalyticsListReportTasks', 'Lists report tasks for a property.', listReportTasks, 'read'),
    entry('googleAnalyticsQueryReportTask', 'Retrieves rows from an ACTIVE report task.', queryReportTask, 'read'),
    entry('googleAnalyticsGetAudience', 'Gets a single audience configuration.', getAudience, 'read'),
    entry('googleAnalyticsListAudiences', 'Lists audience configurations on a property.', listAudiences, 'read'),
    entry('googleAnalyticsCreateAudienceExport', 'Exports a snapshot of users in an audience (async).', createAudienceExport, 'write'),
    entry('googleAnalyticsGetAudienceExport', 'Gets audience-export metadata/state.', getAudienceExport, 'read'),
    entry('googleAnalyticsListAudienceExports', 'Lists audience exports for a property.', listAudienceExports, 'read'),
    entry('googleAnalyticsQueryAudienceExport', 'Retrieves rows from an audience export.', queryAudienceExport, 'read'),
    entry('googleAnalyticsCreateAudienceList', 'Creates an audience list snapshot (async).', createAudienceList, 'write'),
    entry('googleAnalyticsGetAudienceList', 'Gets audience-list metadata/state.', getAudienceList, 'read'),
    entry('googleAnalyticsListAudienceLists', 'Lists audience lists for a property.', listAudienceLists, 'read'),
    entry('googleAnalyticsQueryAudienceList', 'Retrieves rows from an audience list.', queryAudienceList, 'read'),
    entry('googleAnalyticsCreateRecurringAudienceList', 'Creates a recurring (daily) audience list.', createRecurringAudienceList, 'write'),
    entry('googleAnalyticsGetRecurringAudienceList', 'Gets a recurring audience list and its latest generated list.', getRecurringAudienceList, 'read'),
    entry('googleAnalyticsListRecurringAudienceLists', 'Lists recurring audience lists for a property.', listRecurringAudienceLists, 'read'),
    entry('googleAnalyticsGetAccount', 'Gets a single account by resource name.', getAccount, 'read'),
    entry('googleAnalyticsListAccountsV1Beta', 'Lists all accessible accounts (v1beta).', listAccountsV1Beta, 'read'),
    entry('googleAnalyticsListAccountSummaries', 'Lists high-level summaries of all accessible accounts.', listAccountSummaries, 'read'),
    entry('googleAnalyticsProvisionAccountTicket', 'Provisions an account ticket for creating a new account.', provisionAccountTicket, 'write'),
    entry('googleAnalyticsGetProperty', 'Gets a single GA4 property by resource name.', getProperty, 'read'),
    entry('googleAnalyticsListPropertiesFiltered', 'Lists GA4 properties by filter expression.', listPropertiesFiltered, 'read'),
    entry('googleAnalyticsUpdateProperty', 'Updates a property (displayName, timeZone, currencyCode).', updateProperty, 'write'),
    entry('googleAnalyticsCreateRollupProperty', 'Creates a roll-up property aggregating source properties.', createRollupProperty, 'write'),
    entry('googleAnalyticsGetPropertyQuotasSnapshot', 'Gets property quota usage by category.', getPropertyQuotasSnapshot, 'read'),
    entry('googleAnalyticsGetAttributionSettings', 'Gets attribution configuration for a property.', getAttributionSettings, 'read'),
    entry('googleAnalyticsGetDataRetentionSettings', 'Gets data retention configuration for a property.', getDataRetentionSettings, 'read'),
    entry('googleAnalyticsGetDataSharingSettings', 'Gets data-sharing configuration for an account.', getDataSharingSettings, 'read'),
    entry('googleAnalyticsGetGoogleSignalsSettings', 'Gets Google Signals configuration for a property.', getGoogleSignalsSettings, 'read'),
    entry('googleAnalyticsCreateCustomDimension', 'Creates a custom dimension (EVENT, USER, or ITEM scope).', createCustomDimension, 'write'),
    entry('googleAnalyticsGetCustomDimension', 'Gets a single custom dimension by resource name.', getCustomDimension, 'read'),
    entry('googleAnalyticsListCustomDimensions', 'Lists custom dimensions on a property.', listCustomDimensions, 'read'),
    entry('googleAnalyticsArchiveCustomDimension', 'Archives a custom dimension (removes from active use).', archiveCustomDimension, 'write'),
    entry('googleAnalyticsCreateCustomMetric', 'Creates an event-scoped custom metric.', createCustomMetric, 'write'),
    entry('googleAnalyticsListCustomMetrics', 'Lists custom metrics on a property.', listCustomMetrics, 'read'),
    entry('googleAnalyticsListCalculatedMetrics', 'Lists calculated metrics on a property.', listCalculatedMetrics, 'read'),
    entry('googleAnalyticsCreateExpandedDataSet', 'Creates an expanded data set (dimensions + metrics).', createExpandedDataSet, 'write'),
    entry('googleAnalyticsListExpandedDataSets', 'Lists expanded data sets on a property.', listExpandedDataSets, 'read'),
    entry('googleAnalyticsListAdsenseLinks', 'Lists AdSense links on a property.', listAdsenseLinks, 'read'),
    entry('googleAnalyticsListBigqueryLinks', 'Lists BigQuery links on a property.', listBigqueryLinks, 'read'),
    entry('googleAnalyticsListChannelGroups', 'Lists channel groups on a property.', listChannelGroups, 'read'),
    entry('googleAnalyticsListConversionEvents', 'Lists conversion events on a property.', listConversionEvents, 'read'),
    entry('googleAnalyticsListKeyEvents', 'Lists key events on a property.', listKeyEvents, 'read'),
    entry('googleAnalyticsGetKeyEvent', 'Gets a single key event by resource name.', getKeyEvent, 'read'),
    entry('googleAnalyticsListDataStreams', 'Lists data streams on a property.', listDataStreams, 'read'),
    entry('googleAnalyticsListDv360AdLinks', 'Lists DV360 advertiser links on a property.', listDv360AdLinks, 'read'),
    entry('googleAnalyticsListDv360LinkProposals', 'Lists DV360 link proposals on a property.', listDv360LinkProposals, 'read'),
    entry('googleAnalyticsListEventCreateRules', 'Lists event-create rules on a property.', listEventCreateRules, 'read'),
    entry('googleAnalyticsListFirebaseLinks', 'Lists Firebase links on a property.', listFirebaseLinks, 'read'),
    entry('googleAnalyticsListGoogleAdsLinks', 'Lists Google Ads links on a property.', listGoogleAdsLinks, 'read'),
    entry('googleAnalyticsListMeasurementProtocolSecrets', 'Lists Measurement Protocol secrets on a property.', listMeasurementProtocolSecrets, 'read'),
    entry('googleAnalyticsListSearchAds360Links', 'Lists Search Ads 360 links on a property.', listSearchAds360Links, 'read'),
    entry('googleAnalyticsListSkAdNetworkSchemas', 'Lists SKAdNetwork schemas for an iOS data stream.', listSkAdNetworkSchemas, 'read'),
    entry('googleAnalyticsListSubpropertyEventFilters', 'Lists subproperty event filters on a property.', listSubpropertyEventFilters, 'read'),
    entry('googleAnalyticsListSubpropertySyncConfigs', 'Lists subproperty sync configs on a property.', listSubpropertySyncConfigs, 'read'),
    entry('googleAnalyticsListReportingDataAnnotations', 'Lists reporting data annotations on a property.', listReportingDataAnnotations, 'read'),
    entry('googleAnalyticsSendEvents', 'Sends server-side events via Measurement Protocol (API-secret auth).', sendEvents, 'write', { noAuth: true }),
    entry('googleAnalyticsValidateEvents', 'Validates Measurement Protocol events without recording them.', validateEvents, 'read', { noAuth: true }),
];
