import { defineToolkit, defineTool } from '../../core/define.js';
import { inferToolScope } from '../../core/scope.js';
import { SLACK_ICON } from './icon.js';
import { slackTools } from './tools/index.js';

export default defineToolkit({
  id: 'slack',
  displayName: 'Slack',
  shortDescription: 'Messages, channels, users, files, calls, and admin.',
  category: 'Collaboration & Communication',
  icon: SLACK_ICON,
  auth: {
    type: 'oauth2',
    tokenField: 'slackToken',
    provider: {
      slug: 'slack',
      env: { clientId: 'SLACK_CLIENT_ID', clientSecret: 'SLACK_CLIENT_SECRET' },
      authorizeUrl: 'https://slack.com/oauth/v2/authorize',
      tokenUrl: 'https://slack.com/api/oauth.v2.access',
      scopes: [
        'channels:read',
        'channels:write',
        'groups:read',
        'groups:write',
        'im:read',
        'im:write',
        'mpim:read',
        'mpim:write',
        'chat:write',
        'users:read',
        'users:read.email',
        'users:write',
        'users.profile:read',
        'users.profile:write',
        'files:read',
        'files:write',
        'reactions:read',
        'reactions:write',
        'pins:read',
        'pins:write',
        'stars:read',
        'stars:write',
        'reminders:read',
        'reminders:write',
        'search:read',
        'team:read',
        'usergroups:read',
        'usergroups:write',
        'emoji:read',
        'dnd:read',
        'dnd:write',
        'calls:read',
        'calls:write',
        'canvases:read',
        'canvases:write',
        'lists:read',
        'lists:write',
        'remote_files:read',
        'remote_files:share',
        'links:write',
        'admin.teams:read',
        'admin.teams:write',
        'admin.users:read',
        'admin.users:write',
        'admin.conversations:read',
        'admin.conversations:write',
        'admin.apps:read',
        'admin.apps:write',
        'admin.invites:read',
        'auditlogs:read',
      ],
      scopeSeparator: ',',
      exchangeStyle: 'form',
      connectDescription:
        'Connect Slack to send messages, manage channels and users, search content, and administer workspaces. Admin and Enterprise Grid methods need a user token with admin scopes.',
      callbackPath: '/api/auth/slack/callback',
      stateCookie: 'slack_oauth_state',
    },
  },
  allowedHosts: ['slack.com', 'api.slack.com', 'files.slack.com'],
  tools: slackTools.map((entry) =>
    defineTool({
      name: entry.name,
      description: entry.description,
      tool: entry.tool,
      requiredAuth: entry.requiredAuth,
      scope: (entry as any).scope ?? inferToolScope(entry.name),
    }),
  ),
  meta: {
    since: '0.0.9',
    homepage: 'https://slack.com',
    docsUrl: 'https://docs.slack.dev/',
    apiDocsUrl: 'https://docs.slack.dev/reference/methods/',
  },
});
