// @ts-nocheck
import {
  jiraAddAttachment,
  jiraAddComment,
  jiraAddWatcherToIssue,
  jiraAddWorklog,
  jiraAssignIssue,
  jiraBulkCreateIssue,
  jiraCreateIssue,
  jiraCreateIssueLink,
  jiraDeleteAttachment,
  jiraDeleteComment,
  jiraDeleteIssue,
  jiraDeleteWorklog,
  jiraEditIssue,
  jiraFetchBulkIssues,
  jiraGetAttachment,
  jiraGetComment,
  jiraGetIssue,
  jiraGetIssueEditMetadata,
  jiraGetIssueLinkTypes,
  jiraGetIssuePickerSuggestions,
  jiraGetIssueProperty,
  jiraGetIssueWatchers,
  jiraGetIssueWorklogs,
  jiraGetRemoteIssueLinks,
  jiraGetTransitions,
  jiraGetVotes,
  jiraGetWorklog,
  jiraListComments,
  jiraListIssueComments,
  jiraRemoveWatcherFromIssue,
  jiraSendNotificationForIssue,
  jiraTransitionIssue,
  jiraUpdateComment,
} from './issues.js';
export {
  jiraAddAttachment,
  jiraAddComment,
  jiraAddWatcherToIssue,
  jiraAddWorklog,
  jiraAssignIssue,
  jiraBulkCreateIssue,
  jiraCreateIssue,
  jiraCreateIssueLink,
  jiraDeleteAttachment,
  jiraDeleteComment,
  jiraDeleteIssue,
  jiraDeleteWorklog,
  jiraEditIssue,
  jiraFetchBulkIssues,
  jiraGetAttachment,
  jiraGetComment,
  jiraGetIssue,
  jiraGetIssueEditMetadata,
  jiraGetIssueLinkTypes,
  jiraGetIssuePickerSuggestions,
  jiraGetIssueProperty,
  jiraGetIssueWatchers,
  jiraGetIssueWorklogs,
  jiraGetRemoteIssueLinks,
  jiraGetTransitions,
  jiraGetVotes,
  jiraGetWorklog,
  jiraListComments,
  jiraListIssueComments,
  jiraRemoveWatcherFromIssue,
  jiraSendNotificationForIssue,
  jiraTransitionIssue,
  jiraUpdateComment,
};
import {
  jiraAddUsersToProjectRole,
  jiraCreateProject,
  jiraCreateVersion,
  jiraDeleteVersion,
  jiraGetAllIssueTypeSchemes,
  jiraGetAllProjects,
  jiraGetComponents,
  jiraGetProject,
  jiraGetProjectRoles,
  jiraGetProjectTemplates,
  jiraGetProjectType,
  jiraGetProjectVersions,
  jiraGetRecentProjects,
  jiraListAllProjects,
  jiraListProjectTypes,
  jiraRemoveUserFromProjectRole,
} from './projects.js';
export {
  jiraAddUsersToProjectRole,
  jiraCreateProject,
  jiraCreateVersion,
  jiraDeleteVersion,
  jiraGetAllIssueTypeSchemes,
  jiraGetAllProjects,
  jiraGetComponents,
  jiraGetProject,
  jiraGetProjectRoles,
  jiraGetProjectTemplates,
  jiraGetProjectType,
  jiraGetProjectVersions,
  jiraGetRecentProjects,
  jiraListAllProjects,
  jiraListProjectTypes,
  jiraRemoveUserFromProjectRole,
};
import {
  jiraAddUserToGroup,
  jiraCreateGroup,
  jiraFindUsers,
  jiraFindUsers2,
  jiraFindUsersForPicker,
  jiraGetAllGroups,
  jiraGetAllUsers,
  jiraGetCurrentUser,
  jiraGetGroup,
  jiraGetMypreferencesLocale,
  jiraGetUserGroups,
  jiraListGroupsPicker,
  jiraRemoveUserFromGroup,
  jiraWhoAmI,
} from './users.js';
export {
  jiraAddUserToGroup,
  jiraCreateGroup,
  jiraFindUsers,
  jiraFindUsers2,
  jiraFindUsersForPicker,
  jiraGetAllGroups,
  jiraGetAllUsers,
  jiraGetCurrentUser,
  jiraGetGroup,
  jiraGetMypreferencesLocale,
  jiraGetUserGroups,
  jiraListGroupsPicker,
  jiraRemoveUserFromGroup,
  jiraWhoAmI,
};
import {
  jiraAnalyseExpression,
  jiraCreateJqlAutocompletedata,
  jiraEvaluateJiraExpression,
  jiraGetJqlAutocompletedata,
  jiraGetJqlAutocompletedataSuggestions,
  jiraParseJqlQueries,
  jiraSearchApproximateCount,
  jiraSearchForIssuesUsingJqlGet,
  jiraSearchForIssuesUsingJqlPost,
  jiraSearchIssues,
} from './search.js';
export {
  jiraAnalyseExpression,
  jiraCreateJqlAutocompletedata,
  jiraEvaluateJiraExpression,
  jiraGetJqlAutocompletedata,
  jiraGetJqlAutocompletedataSuggestions,
  jiraParseJqlQueries,
  jiraSearchApproximateCount,
  jiraSearchForIssuesUsingJqlGet,
  jiraSearchForIssuesUsingJqlPost,
  jiraSearchIssues,
};
import {
  jiraCheckPermissions,
  jiraGetAllStatuses,
  jiraGetAttachmentMeta,
  jiraGetCreateMetadataIssueTypeFields,
  jiraGetDashboards,
  jiraGetFavoriteFilters,
  jiraGetFields,
  jiraGetFieldsPaginated,
  jiraGetFilter,
  jiraGetInfo,
  jiraGetIssueCreateMetadata,
  jiraGetIssueResolutions,
  jiraGetIssueTypes,
  jiraGetMyPermissions,
  jiraGetPermissions,
  jiraGetPermittedProjects,
  jiraGetServerInfo,
  jiraGetServiceDeskRequestTypeFields,
  jiraGetSystemAvatars,
  jiraGetUniversalAvatarTypeOwner,
  jiraGetUniversalAvatarViewType,
  jiraGetViewTypeAvatar,
  jiraListFilters,
  jiraSearchDashboards,
} from './meta.js';
export {
  jiraCheckPermissions,
  jiraGetAllStatuses,
  jiraGetAttachmentMeta,
  jiraGetCreateMetadataIssueTypeFields,
  jiraGetDashboards,
  jiraGetFavoriteFilters,
  jiraGetFields,
  jiraGetFieldsPaginated,
  jiraGetFilter,
  jiraGetInfo,
  jiraGetIssueCreateMetadata,
  jiraGetIssueResolutions,
  jiraGetIssueTypes,
  jiraGetMyPermissions,
  jiraGetPermissions,
  jiraGetPermittedProjects,
  jiraGetServerInfo,
  jiraGetServiceDeskRequestTypeFields,
  jiraGetSystemAvatars,
  jiraGetUniversalAvatarTypeOwner,
  jiraGetUniversalAvatarViewType,
  jiraGetViewTypeAvatar,
  jiraListFilters,
  jiraSearchDashboards,
};
import {
  jiraCreateBoard,
  jiraCreateSprint,
  jiraGetSprint,
  jiraListBoards,
  jiraListSprints,
  jiraMoveIssueToSprint,
} from './boards.js';
export {
  jiraCreateBoard,
  jiraCreateSprint,
  jiraGetSprint,
  jiraListBoards,
  jiraListSprints,
  jiraMoveIssueToSprint,
};

export const jiraTools = [
  {
    name: 'JiraAddAttachment',
    description: jiraAddAttachment.description!,
    tool: jiraAddAttachment,
    requiredAuth: 'jiraToken' as const,
    scope: 'write' as const,
    keywords: ['upload', 'file', 'vulnerabilities'],
  },
  {
    name: 'JiraAddComment',
    description: jiraAddComment.description!,
    tool: jiraAddComment,
    requiredAuth: 'jiraToken' as const,
    scope: 'write' as const,
    keywords: ['reply', 'note'],
  },
  {
    name: 'JiraAddUsersToProjectRole',
    description: jiraAddUsersToProjectRole.description!,
    tool: jiraAddUsersToProjectRole,
    requiredAuth: 'jiraToken' as const,
    scope: 'write' as const,
    keywords: ['permissions', 'member'],
  },
  {
    name: 'JiraAddUserToGroup',
    description: jiraAddUserToGroup.description!,
    tool: jiraAddUserToGroup,
    requiredAuth: 'jiraToken' as const,
    scope: 'write' as const,
    keywords: ['member'],
  },
  {
    name: 'JiraAddWatcherToIssue',
    description: jiraAddWatcherToIssue.description!,
    tool: jiraAddWatcherToIssue,
    requiredAuth: 'jiraToken' as const,
    scope: 'write' as const,
    keywords: ['watch', 'subscribe', 'follow'],
  },
  {
    name: 'JiraAddWorklog',
    description: jiraAddWorklog.description!,
    tool: jiraAddWorklog,
    requiredAuth: 'jiraToken' as const,
    scope: 'write' as const,
    keywords: ['time', 'log-time', 'track'],
  },
  {
    name: 'JiraAnalyseExpression',
    description: jiraAnalyseExpression.description!,
    tool: jiraAnalyseExpression,
    requiredAuth: 'jiraToken' as const,
    scope: 'read' as const,
    keywords: [],
  },
  {
    name: 'JiraAssignIssue',
    description: jiraAssignIssue.description!,
    tool: jiraAssignIssue,
    requiredAuth: 'jiraToken' as const,
    scope: 'write' as const,
    keywords: ['assignee'],
  },
  {
    name: 'JiraBulkCreateIssue',
    description: jiraBulkCreateIssue.description!,
    tool: jiraBulkCreateIssue,
    requiredAuth: 'jiraToken' as const,
    scope: 'write' as const,
    keywords: ['bulk', 'batch', 'many'],
  },
  {
    name: 'JiraCheckPermissions',
    description: jiraCheckPermissions.description!,
    tool: jiraCheckPermissions,
    requiredAuth: 'jiraToken' as const,
    scope: 'read' as const,
    keywords: ['access'],
  },
  {
    name: 'JiraCreateBoard',
    description: jiraCreateBoard.description!,
    tool: jiraCreateBoard,
    requiredAuth: 'jiraToken' as const,
    scope: 'write' as const,
    keywords: ['kanban', 'scrum', 'new'],
  },
  {
    name: 'JiraCreateGroup',
    description: jiraCreateGroup.description!,
    tool: jiraCreateGroup,
    requiredAuth: 'jiraToken' as const,
    scope: 'write' as const,
    keywords: [],
  },
  {
    name: 'JiraCreateIssue',
    description: jiraCreateIssue.description!,
    tool: jiraCreateIssue,
    requiredAuth: 'jiraToken' as const,
    scope: 'write' as const,
    keywords: ['new', 'ticket', 'bug', 'task', 'story'],
  },
  {
    name: 'JiraCreateIssueLink',
    description: jiraCreateIssueLink.description!,
    tool: jiraCreateIssueLink,
    requiredAuth: 'jiraToken' as const,
    scope: 'write' as const,
    keywords: ['link', 'relate', 'blocks'],
  },
  {
    name: 'JiraCreateJqlAutocompletedata',
    description: jiraCreateJqlAutocompletedata.description!,
    tool: jiraCreateJqlAutocompletedata,
    requiredAuth: 'jiraToken' as const,
    scope: 'write' as const,
    keywords: ['jql', 'help'],
  },
  {
    name: 'JiraCreateProject',
    description: jiraCreateProject.description!,
    tool: jiraCreateProject,
    requiredAuth: 'jiraToken' as const,
    scope: 'write' as const,
    keywords: ['new'],
  },
  {
    name: 'JiraCreateSprint',
    description: jiraCreateSprint.description!,
    tool: jiraCreateSprint,
    requiredAuth: 'jiraToken' as const,
    scope: 'write' as const,
    keywords: ['new', 'scrum'],
  },
  {
    name: 'JiraCreateVersion',
    description: jiraCreateVersion.description!,
    tool: jiraCreateVersion,
    requiredAuth: 'jiraToken' as const,
    scope: 'write' as const,
    keywords: ['release', 'milestone', 'new'],
  },
  {
    name: 'JiraDeleteAttachment',
    description: jiraDeleteAttachment.description!,
    tool: jiraDeleteAttachment,
    requiredAuth: 'jiraToken' as const,
    scope: 'delete' as const,
    keywords: ['remove', 'file'],
  },
  {
    name: 'JiraDeleteComment',
    description: jiraDeleteComment.description!,
    tool: jiraDeleteComment,
    requiredAuth: 'jiraToken' as const,
    scope: 'delete' as const,
    keywords: ['remove'],
  },
  {
    name: 'JiraDeleteIssue',
    description: jiraDeleteIssue.description!,
    tool: jiraDeleteIssue,
    requiredAuth: 'jiraToken' as const,
    scope: 'delete' as const,
    keywords: ['remove', 'ticket'],
  },
  {
    name: 'JiraDeleteVersion',
    description: jiraDeleteVersion.description!,
    tool: jiraDeleteVersion,
    requiredAuth: 'jiraToken' as const,
    scope: 'delete' as const,
    keywords: ['remove', 'release'],
  },
  {
    name: 'JiraDeleteWorklog',
    description: jiraDeleteWorklog.description!,
    tool: jiraDeleteWorklog,
    requiredAuth: 'jiraToken' as const,
    scope: 'delete' as const,
    keywords: ['remove', 'time'],
  },
  {
    name: 'JiraEditIssue',
    description: jiraEditIssue.description!,
    tool: jiraEditIssue,
    requiredAuth: 'jiraToken' as const,
    scope: 'write' as const,
    keywords: ['update', 'ticket'],
  },
  {
    name: 'JiraEvaluateJiraExpression',
    description: jiraEvaluateJiraExpression.description!,
    tool: jiraEvaluateJiraExpression,
    requiredAuth: 'jiraToken' as const,
    scope: 'read' as const,
    keywords: [],
  },
  {
    name: 'JiraFetchBulkIssues',
    description: jiraFetchBulkIssues.description!,
    tool: jiraFetchBulkIssues,
    requiredAuth: 'jiraToken' as const,
    scope: 'read' as const,
    keywords: ['batch', 'many'],
  },
  {
    name: 'JiraFindUsers',
    description: jiraFindUsers.description!,
    tool: jiraFindUsers,
    requiredAuth: 'jiraToken' as const,
    scope: 'read' as const,
    keywords: ['search', 'lookup'],
  },
  {
    name: 'JiraFindUsers2',
    description: jiraFindUsers2.description!,
    tool: jiraFindUsers2,
    requiredAuth: 'jiraToken' as const,
    scope: 'read' as const,
    keywords: ['search'],
  },
  {
    name: 'JiraFindUsersForPicker',
    description: jiraFindUsersForPicker.description!,
    tool: jiraFindUsersForPicker,
    requiredAuth: 'jiraToken' as const,
    scope: 'read' as const,
    keywords: ['assign'],
  },
  {
    name: 'JiraGetAllGroups',
    description: jiraGetAllGroups.description!,
    tool: jiraGetAllGroups,
    requiredAuth: 'jiraToken' as const,
    scope: 'read' as const,
    keywords: [],
  },
  {
    name: 'JiraGetAllIssueTypeSchemes',
    description: jiraGetAllIssueTypeSchemes.description!,
    tool: jiraGetAllIssueTypeSchemes,
    requiredAuth: 'jiraToken' as const,
    scope: 'read' as const,
    keywords: ['types'],
  },
  {
    name: 'JiraGetAllProjects',
    description: jiraGetAllProjects.description!,
    tool: jiraGetAllProjects,
    requiredAuth: 'jiraToken' as const,
    scope: 'read' as const,
    keywords: ['browse'],
  },
  {
    name: 'JiraGetAllStatuses',
    description: jiraGetAllStatuses.description!,
    tool: jiraGetAllStatuses,
    requiredAuth: 'jiraToken' as const,
    scope: 'read' as const,
    keywords: ['status', 'workflow'],
  },
  {
    name: 'JiraGetAllUsers',
    description: jiraGetAllUsers.description!,
    tool: jiraGetAllUsers,
    requiredAuth: 'jiraToken' as const,
    scope: 'read' as const,
    keywords: ['browse', 'directory'],
  },
  {
    name: 'JiraGetAttachment',
    description: jiraGetAttachment.description!,
    tool: jiraGetAttachment,
    requiredAuth: 'jiraToken' as const,
    scope: 'read' as const,
    keywords: ['download', 'file'],
  },
  {
    name: 'JiraGetAttachmentMeta',
    description: jiraGetAttachmentMeta.description!,
    tool: jiraGetAttachmentMeta,
    requiredAuth: 'jiraToken' as const,
    scope: 'read' as const,
    keywords: ['limits', 'settings'],
  },
  {
    name: 'JiraGetComment',
    description: jiraGetComment.description!,
    tool: jiraGetComment,
    requiredAuth: 'jiraToken' as const,
    scope: 'read' as const,
    keywords: [],
  },
  {
    name: 'JiraGetComponents',
    description: jiraGetComponents.description!,
    tool: jiraGetComponents,
    requiredAuth: 'jiraToken' as const,
    scope: 'read' as const,
    keywords: [],
  },
  {
    name: 'JiraGetCreateMetadataIssueTypeFields',
    description: jiraGetCreateMetadataIssueTypeFields.description!,
    tool: jiraGetCreateMetadataIssueTypeFields,
    requiredAuth: 'jiraToken' as const,
    scope: 'read' as const,
    keywords: ['fields', 'required', 'form'],
  },
  {
    name: 'JiraGetCurrentUser',
    description: jiraGetCurrentUser.description!,
    tool: jiraGetCurrentUser,
    requiredAuth: 'jiraToken' as const,
    scope: 'read' as const,
    keywords: ['me', 'profile'],
  },
  {
    name: 'JiraGetDashboards',
    description: jiraGetDashboards.description!,
    tool: jiraGetDashboards,
    requiredAuth: 'jiraToken' as const,
    scope: 'read' as const,
    keywords: ['browse', 'reports'],
  },
  {
    name: 'JiraGetFavoriteFilters',
    description: jiraGetFavoriteFilters.description!,
    tool: jiraGetFavoriteFilters,
    requiredAuth: 'jiraToken' as const,
    scope: 'read' as const,
    keywords: ['saved', 'jql'],
  },
  {
    name: 'JiraGetFields',
    description: jiraGetFields.description!,
    tool: jiraGetFields,
    requiredAuth: 'jiraToken' as const,
    scope: 'read' as const,
    keywords: ['custom-fields', 'schema'],
  },
  {
    name: 'JiraGetFieldsPaginated',
    description: jiraGetFieldsPaginated.description!,
    tool: jiraGetFieldsPaginated,
    requiredAuth: 'jiraToken' as const,
    scope: 'read' as const,
    keywords: [],
  },
  {
    name: 'JiraGetFilter',
    description: jiraGetFilter.description!,
    tool: jiraGetFilter,
    requiredAuth: 'jiraToken' as const,
    scope: 'read' as const,
    keywords: ['saved-search', 'jql'],
  },
  {
    name: 'JiraGetGroup',
    description: jiraGetGroup.description!,
    tool: jiraGetGroup,
    requiredAuth: 'jiraToken' as const,
    scope: 'read' as const,
    keywords: [],
  },
  {
    name: 'JiraGetInfo',
    description: jiraGetInfo.description!,
    tool: jiraGetInfo,
    requiredAuth: 'jiraToken' as const,
    scope: 'read' as const,
    keywords: ['version', 'server'],
  },
  {
    name: 'JiraGetIssue',
    description: jiraGetIssue.description!,
    tool: jiraGetIssue,
    requiredAuth: 'jiraToken' as const,
    scope: 'read' as const,
    keywords: ['ticket'],
  },
  {
    name: 'JiraGetIssueCreateMetadata',
    description: jiraGetIssueCreateMetadata.description!,
    tool: jiraGetIssueCreateMetadata,
    requiredAuth: 'jiraToken' as const,
    scope: 'read' as const,
    keywords: [],
  },
  {
    name: 'JiraGetIssueEditMetadata',
    description: jiraGetIssueEditMetadata.description!,
    tool: jiraGetIssueEditMetadata,
    requiredAuth: 'jiraToken' as const,
    scope: 'read' as const,
    keywords: ['fields', 'edit'],
  },
  {
    name: 'JiraGetIssueLinkTypes',
    description: jiraGetIssueLinkTypes.description!,
    tool: jiraGetIssueLinkTypes,
    requiredAuth: 'jiraToken' as const,
    scope: 'read' as const,
    keywords: ['link-types'],
  },
  {
    name: 'JiraGetIssuePickerSuggestions',
    description: jiraGetIssuePickerSuggestions.description!,
    tool: jiraGetIssuePickerSuggestions,
    requiredAuth: 'jiraToken' as const,
    scope: 'read' as const,
    keywords: ['autocomplete', 'search'],
  },
  {
    name: 'JiraGetIssueProperty',
    description: jiraGetIssueProperty.description!,
    tool: jiraGetIssueProperty,
    requiredAuth: 'jiraToken' as const,
    scope: 'read' as const,
    keywords: [],
  },
  {
    name: 'JiraGetIssueResolutions',
    description: jiraGetIssueResolutions.description!,
    tool: jiraGetIssueResolutions,
    requiredAuth: 'jiraToken' as const,
    scope: 'read' as const,
    keywords: ['status', 'done'],
  },
  {
    name: 'JiraGetIssueTypes',
    description: jiraGetIssueTypes.description!,
    tool: jiraGetIssueTypes,
    requiredAuth: 'jiraToken' as const,
    scope: 'read' as const,
    keywords: ['bug', 'task', 'story', 'epic', 'types'],
  },
  {
    name: 'JiraGetIssueWatchers',
    description: jiraGetIssueWatchers.description!,
    tool: jiraGetIssueWatchers,
    requiredAuth: 'jiraToken' as const,
    scope: 'read' as const,
    keywords: ['watchers'],
  },
  {
    name: 'JiraGetIssueWorklogs',
    description: jiraGetIssueWorklogs.description!,
    tool: jiraGetIssueWorklogs,
    requiredAuth: 'jiraToken' as const,
    scope: 'read' as const,
    keywords: ['time', 'logged'],
  },
  {
    name: 'JiraGetJqlAutocompletedata',
    description: jiraGetJqlAutocompletedata.description!,
    tool: jiraGetJqlAutocompletedata,
    requiredAuth: 'jiraToken' as const,
    scope: 'read' as const,
    keywords: ['jql', 'fields', 'help'],
  },
  {
    name: 'JiraGetJqlAutocompletedataSuggestions',
    description: jiraGetJqlAutocompletedataSuggestions.description!,
    tool: jiraGetJqlAutocompletedataSuggestions,
    requiredAuth: 'jiraToken' as const,
    scope: 'read' as const,
    keywords: ['jql', 'autocomplete'],
  },
  {
    name: 'JiraGetMyPermissions',
    description: jiraGetMyPermissions.description!,
    tool: jiraGetMyPermissions,
    requiredAuth: 'jiraToken' as const,
    scope: 'read' as const,
    keywords: ['access'],
  },
  {
    name: 'JiraGetMypreferencesLocale',
    description: jiraGetMypreferencesLocale.description!,
    tool: jiraGetMypreferencesLocale,
    requiredAuth: 'jiraToken' as const,
    scope: 'read' as const,
    keywords: ['language', 'locale'],
  },
  {
    name: 'JiraGetPermissions',
    description: jiraGetPermissions.description!,
    tool: jiraGetPermissions,
    requiredAuth: 'jiraToken' as const,
    scope: 'read' as const,
    keywords: [],
  },
  {
    name: 'JiraGetPermittedProjects',
    description: jiraGetPermittedProjects.description!,
    tool: jiraGetPermittedProjects,
    requiredAuth: 'jiraToken' as const,
    scope: 'read' as const,
    keywords: ['access'],
  },
  {
    name: 'JiraGetProject',
    description: jiraGetProject.description!,
    tool: jiraGetProject,
    requiredAuth: 'jiraToken' as const,
    scope: 'read' as const,
    keywords: [],
  },
  {
    name: 'JiraGetProjectRoles',
    description: jiraGetProjectRoles.description!,
    tool: jiraGetProjectRoles,
    requiredAuth: 'jiraToken' as const,
    scope: 'read' as const,
    keywords: ['permissions'],
  },
  {
    name: 'JiraGetProjectTemplates',
    description: jiraGetProjectTemplates.description!,
    tool: jiraGetProjectTemplates,
    requiredAuth: 'jiraToken' as const,
    scope: 'read' as const,
    keywords: ['template', 'new'],
  },
  {
    name: 'JiraGetProjectType',
    description: jiraGetProjectType.description!,
    tool: jiraGetProjectType,
    requiredAuth: 'jiraToken' as const,
    scope: 'read' as const,
    keywords: [],
  },
  {
    name: 'JiraGetProjectVersions',
    description: jiraGetProjectVersions.description!,
    tool: jiraGetProjectVersions,
    requiredAuth: 'jiraToken' as const,
    scope: 'read' as const,
    keywords: ['releases'],
  },
  {
    name: 'JiraGetRecentProjects',
    description: jiraGetRecentProjects.description!,
    tool: jiraGetRecentProjects,
    requiredAuth: 'jiraToken' as const,
    scope: 'read' as const,
    keywords: ['recent'],
  },
  {
    name: 'JiraGetRemoteIssueLinks',
    description: jiraGetRemoteIssueLinks.description!,
    tool: jiraGetRemoteIssueLinks,
    requiredAuth: 'jiraToken' as const,
    scope: 'read' as const,
    keywords: ['links', 'external'],
  },
  {
    name: 'JiraGetServerInfo',
    description: jiraGetServerInfo.description!,
    tool: jiraGetServerInfo,
    requiredAuth: 'jiraToken' as const,
    scope: 'read' as const,
    keywords: ['version'],
  },
  {
    name: 'JiraGetServiceDeskRequestTypeFields',
    description: jiraGetServiceDeskRequestTypeFields.description!,
    tool: jiraGetServiceDeskRequestTypeFields,
    requiredAuth: 'jiraToken' as const,
    scope: 'read' as const,
    keywords: ['fields', 'form'],
  },
  {
    name: 'JiraGetSprint',
    description: jiraGetSprint.description!,
    tool: jiraGetSprint,
    requiredAuth: 'jiraToken' as const,
    scope: 'read' as const,
    keywords: [],
  },
  {
    name: 'JiraGetSystemAvatars',
    description: jiraGetSystemAvatars.description!,
    tool: jiraGetSystemAvatars,
    requiredAuth: 'jiraToken' as const,
    scope: 'read' as const,
    keywords: ['icons'],
  },
  {
    name: 'JiraGetTransitions',
    description: jiraGetTransitions.description!,
    tool: jiraGetTransitions,
    requiredAuth: 'jiraToken' as const,
    scope: 'read' as const,
    keywords: ['status', 'workflow', 'move'],
  },
  {
    name: 'JiraGetUniversalAvatarTypeOwner',
    description: jiraGetUniversalAvatarTypeOwner.description!,
    tool: jiraGetUniversalAvatarTypeOwner,
    requiredAuth: 'jiraToken' as const,
    scope: 'read' as const,
    keywords: [],
  },
  {
    name: 'JiraGetUniversalAvatarViewType',
    description: jiraGetUniversalAvatarViewType.description!,
    tool: jiraGetUniversalAvatarViewType,
    requiredAuth: 'jiraToken' as const,
    scope: 'read' as const,
    keywords: [],
  },
  {
    name: 'JiraGetUserGroups',
    description: jiraGetUserGroups.description!,
    tool: jiraGetUserGroups,
    requiredAuth: 'jiraToken' as const,
    scope: 'read' as const,
    keywords: ['memberships'],
  },
  {
    name: 'JiraGetViewTypeAvatar',
    description: jiraGetViewTypeAvatar.description!,
    tool: jiraGetViewTypeAvatar,
    requiredAuth: 'jiraToken' as const,
    scope: 'read' as const,
    keywords: [],
  },
  {
    name: 'JiraGetVotes',
    description: jiraGetVotes.description!,
    tool: jiraGetVotes,
    requiredAuth: 'jiraToken' as const,
    scope: 'read' as const,
    keywords: ['vote'],
  },
  {
    name: 'JiraGetWorklog',
    description: jiraGetWorklog.description!,
    tool: jiraGetWorklog,
    requiredAuth: 'jiraToken' as const,
    scope: 'read' as const,
    keywords: ['time'],
  },
  {
    name: 'JiraListAllProjects',
    description: jiraListAllProjects.description!,
    tool: jiraListAllProjects,
    requiredAuth: 'jiraToken' as const,
    scope: 'read' as const,
    keywords: [],
  },
  {
    name: 'JiraListBoards',
    description: jiraListBoards.description!,
    tool: jiraListBoards,
    requiredAuth: 'jiraToken' as const,
    scope: 'read' as const,
    keywords: ['kanban', 'scrum', 'browse'],
  },
  {
    name: 'JiraListComments',
    description: jiraListComments.description!,
    tool: jiraListComments,
    requiredAuth: 'jiraToken' as const,
    scope: 'read' as const,
    keywords: [],
  },
  {
    name: 'JiraListFilters',
    description: jiraListFilters.description!,
    tool: jiraListFilters,
    requiredAuth: 'jiraToken' as const,
    scope: 'read' as const,
    keywords: ['saved-searches', 'jql'],
  },
  {
    name: 'JiraListGroupsPicker',
    description: jiraListGroupsPicker.description!,
    tool: jiraListGroupsPicker,
    requiredAuth: 'jiraToken' as const,
    scope: 'read' as const,
    keywords: ['autocomplete'],
  },
  {
    name: 'JiraListIssueComments',
    description: jiraListIssueComments.description!,
    tool: jiraListIssueComments,
    requiredAuth: 'jiraToken' as const,
    scope: 'read' as const,
    keywords: [],
  },
  {
    name: 'JiraListProjectTypes',
    description: jiraListProjectTypes.description!,
    tool: jiraListProjectTypes,
    requiredAuth: 'jiraToken' as const,
    scope: 'read' as const,
    keywords: [],
  },
  {
    name: 'JiraListSprints',
    description: jiraListSprints.description!,
    tool: jiraListSprints,
    requiredAuth: 'jiraToken' as const,
    scope: 'read' as const,
    keywords: [],
  },
  {
    name: 'JiraMoveIssueToSprint',
    description: jiraMoveIssueToSprint.description!,
    tool: jiraMoveIssueToSprint,
    requiredAuth: 'jiraToken' as const,
    scope: 'write' as const,
    keywords: ['sprint', 'scrum', 'plan'],
  },
  {
    name: 'JiraParseJqlQueries',
    description: jiraParseJqlQueries.description!,
    tool: jiraParseJqlQueries,
    requiredAuth: 'jiraToken' as const,
    scope: 'read' as const,
    keywords: ['validate', 'jql', 'syntax'],
  },
  {
    name: 'JiraRemoveUserFromGroup',
    description: jiraRemoveUserFromGroup.description!,
    tool: jiraRemoveUserFromGroup,
    requiredAuth: 'jiraToken' as const,
    scope: 'write' as const,
    keywords: ['remove'],
  },
  {
    name: 'JiraRemoveUserFromProjectRole',
    description: jiraRemoveUserFromProjectRole.description!,
    tool: jiraRemoveUserFromProjectRole,
    requiredAuth: 'jiraToken' as const,
    scope: 'write' as const,
    keywords: ['remove', 'permissions'],
  },
  {
    name: 'JiraRemoveWatcherFromIssue',
    description: jiraRemoveWatcherFromIssue.description!,
    tool: jiraRemoveWatcherFromIssue,
    requiredAuth: 'jiraToken' as const,
    scope: 'write' as const,
    keywords: ['unwatch', 'unfollow', 'remove'],
  },
  {
    name: 'JiraSearchApproximateCount',
    description: jiraSearchApproximateCount.description!,
    tool: jiraSearchApproximateCount,
    requiredAuth: 'jiraToken' as const,
    scope: 'read' as const,
    keywords: ['count', 'jql'],
  },
  {
    name: 'JiraSearchDashboards',
    description: jiraSearchDashboards.description!,
    tool: jiraSearchDashboards,
    requiredAuth: 'jiraToken' as const,
    scope: 'read' as const,
    keywords: ['find'],
  },
  {
    name: 'JiraSearchForIssuesUsingJqlGet',
    description: jiraSearchForIssuesUsingJqlGet.description!,
    tool: jiraSearchForIssuesUsingJqlGet,
    requiredAuth: 'jiraToken' as const,
    scope: 'read' as const,
    keywords: ['jql', 'find'],
  },
  {
    name: 'JiraSearchForIssuesUsingJqlPost',
    description: jiraSearchForIssuesUsingJqlPost.description!,
    tool: jiraSearchForIssuesUsingJqlPost,
    requiredAuth: 'jiraToken' as const,
    scope: 'read' as const,
    keywords: ['jql', 'find'],
  },
  {
    name: 'JiraSearchIssues',
    description: jiraSearchIssues.description!,
    tool: jiraSearchIssues,
    requiredAuth: 'jiraToken' as const,
    scope: 'read' as const,
    keywords: ['jql', 'find', 'ticket'],
  },
  {
    name: 'JiraSendNotificationForIssue',
    description: jiraSendNotificationForIssue.description!,
    tool: jiraSendNotificationForIssue,
    requiredAuth: 'jiraToken' as const,
    scope: 'write' as const,
    keywords: ['email', 'notify'],
  },
  {
    name: 'JiraTransitionIssue',
    description: jiraTransitionIssue.description!,
    tool: jiraTransitionIssue,
    requiredAuth: 'jiraToken' as const,
    scope: 'write' as const,
    keywords: ['status', 'move', 'workflow', 'close', 'reopen'],
  },
  {
    name: 'JiraUpdateComment',
    description: jiraUpdateComment.description!,
    tool: jiraUpdateComment,
    requiredAuth: 'jiraToken' as const,
    scope: 'write' as const,
    keywords: ['edit'],
  },
  {
    name: 'JiraWhoAmI',
    description: jiraWhoAmI.description!,
    tool: jiraWhoAmI,
    requiredAuth: 'jiraToken' as const,
    scope: 'read' as const,
    keywords: ['identity', 'sites'],
  },
];
