// @ts-nocheck
import { jiraAddAttachment, jiraAddComment, jiraAddWatcherToIssue, jiraAddWorklog, jiraAssignIssue, jiraBulkCreateIssue, jiraCreateIssue, jiraCreateIssueLink, jiraDeleteAttachment, jiraDeleteComment, jiraDeleteIssue, jiraDeleteWorklog, jiraEditIssue, jiraFetchBulkIssues, jiraGetAttachment, jiraGetComment, jiraGetIssue, jiraGetIssueEditMetadata, jiraGetIssueLinkTypes, jiraGetIssuePickerSuggestions, jiraGetIssueProperty, jiraGetIssueWatchers, jiraGetIssueWorklogs, jiraGetRemoteIssueLinks, jiraGetTransitions, jiraGetVotes, jiraGetWorklog, jiraListComments, jiraListIssueComments, jiraRemoveWatcherFromIssue, jiraSendNotificationForIssue, jiraTransitionIssue, jiraUpdateComment } from './issues.js';
export { jiraAddAttachment, jiraAddComment, jiraAddWatcherToIssue, jiraAddWorklog, jiraAssignIssue, jiraBulkCreateIssue, jiraCreateIssue, jiraCreateIssueLink, jiraDeleteAttachment, jiraDeleteComment, jiraDeleteIssue, jiraDeleteWorklog, jiraEditIssue, jiraFetchBulkIssues, jiraGetAttachment, jiraGetComment, jiraGetIssue, jiraGetIssueEditMetadata, jiraGetIssueLinkTypes, jiraGetIssuePickerSuggestions, jiraGetIssueProperty, jiraGetIssueWatchers, jiraGetIssueWorklogs, jiraGetRemoteIssueLinks, jiraGetTransitions, jiraGetVotes, jiraGetWorklog, jiraListComments, jiraListIssueComments, jiraRemoveWatcherFromIssue, jiraSendNotificationForIssue, jiraTransitionIssue, jiraUpdateComment };
import { jiraAddUsersToProjectRole, jiraCreateProject, jiraCreateVersion, jiraDeleteVersion, jiraGetAllIssueTypeSchemes, jiraGetAllProjects, jiraGetComponents, jiraGetProject, jiraGetProjectRoles, jiraGetProjectTemplates, jiraGetProjectType, jiraGetProjectVersions, jiraGetRecentProjects, jiraListAllProjects, jiraListProjectTypes, jiraRemoveUserFromProjectRole } from './projects.js';
export { jiraAddUsersToProjectRole, jiraCreateProject, jiraCreateVersion, jiraDeleteVersion, jiraGetAllIssueTypeSchemes, jiraGetAllProjects, jiraGetComponents, jiraGetProject, jiraGetProjectRoles, jiraGetProjectTemplates, jiraGetProjectType, jiraGetProjectVersions, jiraGetRecentProjects, jiraListAllProjects, jiraListProjectTypes, jiraRemoveUserFromProjectRole };
import { jiraAddUserToGroup, jiraCreateGroup, jiraFindUsers, jiraFindUsers2, jiraFindUsersForPicker, jiraGetAllGroups, jiraGetAllUsers, jiraGetCurrentUser, jiraGetGroup, jiraGetMypreferencesLocale, jiraGetUserGroups, jiraListGroupsPicker, jiraRemoveUserFromGroup, jiraWhoAmI } from './users.js';
export { jiraAddUserToGroup, jiraCreateGroup, jiraFindUsers, jiraFindUsers2, jiraFindUsersForPicker, jiraGetAllGroups, jiraGetAllUsers, jiraGetCurrentUser, jiraGetGroup, jiraGetMypreferencesLocale, jiraGetUserGroups, jiraListGroupsPicker, jiraRemoveUserFromGroup, jiraWhoAmI };
import { jiraAnalyseExpression, jiraCreateJqlAutocompletedata, jiraEvaluateJiraExpression, jiraGetJqlAutocompletedata, jiraGetJqlAutocompletedataSuggestions, jiraParseJqlQueries, jiraSearchApproximateCount, jiraSearchForIssuesUsingJqlGet, jiraSearchForIssuesUsingJqlPost, jiraSearchIssues } from './search.js';
export { jiraAnalyseExpression, jiraCreateJqlAutocompletedata, jiraEvaluateJiraExpression, jiraGetJqlAutocompletedata, jiraGetJqlAutocompletedataSuggestions, jiraParseJqlQueries, jiraSearchApproximateCount, jiraSearchForIssuesUsingJqlGet, jiraSearchForIssuesUsingJqlPost, jiraSearchIssues };
import { jiraCheckPermissions, jiraGetAllStatuses, jiraGetAttachmentMeta, jiraGetCreateMetadataIssueTypeFields, jiraGetDashboards, jiraGetFavoriteFilters, jiraGetFields, jiraGetFieldsPaginated, jiraGetFilter, jiraGetInfo, jiraGetIssueCreateMetadata, jiraGetIssueResolutions, jiraGetIssueTypes, jiraGetMyPermissions, jiraGetPermissions, jiraGetPermittedProjects, jiraGetServerInfo, jiraGetServiceDeskRequestTypeFields, jiraGetSystemAvatars, jiraGetUniversalAvatarTypeOwner, jiraGetUniversalAvatarViewType, jiraGetViewTypeAvatar, jiraListFilters, jiraSearchDashboards } from './meta.js';
export { jiraCheckPermissions, jiraGetAllStatuses, jiraGetAttachmentMeta, jiraGetCreateMetadataIssueTypeFields, jiraGetDashboards, jiraGetFavoriteFilters, jiraGetFields, jiraGetFieldsPaginated, jiraGetFilter, jiraGetInfo, jiraGetIssueCreateMetadata, jiraGetIssueResolutions, jiraGetIssueTypes, jiraGetMyPermissions, jiraGetPermissions, jiraGetPermittedProjects, jiraGetServerInfo, jiraGetServiceDeskRequestTypeFields, jiraGetSystemAvatars, jiraGetUniversalAvatarTypeOwner, jiraGetUniversalAvatarViewType, jiraGetViewTypeAvatar, jiraListFilters, jiraSearchDashboards };
import { jiraCreateBoard, jiraCreateSprint, jiraGetSprint, jiraListBoards, jiraListSprints, jiraMoveIssueToSprint } from './boards.js';
export { jiraCreateBoard, jiraCreateSprint, jiraGetSprint, jiraListBoards, jiraListSprints, jiraMoveIssueToSprint };

export const jiraTools = [
    { name: 'JiraAddAttachment', description: jiraAddAttachment.description!, tool: jiraAddAttachment, requiredAuth: 'jiraToken' as const, scope: 'write' as const },
    { name: 'JiraAddComment', description: jiraAddComment.description!, tool: jiraAddComment, requiredAuth: 'jiraToken' as const, scope: 'write' as const },
    { name: 'JiraAddUsersToProjectRole', description: jiraAddUsersToProjectRole.description!, tool: jiraAddUsersToProjectRole, requiredAuth: 'jiraToken' as const, scope: 'write' as const },
    { name: 'JiraAddUserToGroup', description: jiraAddUserToGroup.description!, tool: jiraAddUserToGroup, requiredAuth: 'jiraToken' as const, scope: 'write' as const },
    { name: 'JiraAddWatcherToIssue', description: jiraAddWatcherToIssue.description!, tool: jiraAddWatcherToIssue, requiredAuth: 'jiraToken' as const, scope: 'write' as const },
    { name: 'JiraAddWorklog', description: jiraAddWorklog.description!, tool: jiraAddWorklog, requiredAuth: 'jiraToken' as const, scope: 'write' as const },
    { name: 'JiraAnalyseExpression', description: jiraAnalyseExpression.description!, tool: jiraAnalyseExpression, requiredAuth: 'jiraToken' as const, scope: 'read' as const },
    { name: 'JiraAssignIssue', description: jiraAssignIssue.description!, tool: jiraAssignIssue, requiredAuth: 'jiraToken' as const, scope: 'write' as const },
    { name: 'JiraBulkCreateIssue', description: jiraBulkCreateIssue.description!, tool: jiraBulkCreateIssue, requiredAuth: 'jiraToken' as const, scope: 'write' as const },
    { name: 'JiraCheckPermissions', description: jiraCheckPermissions.description!, tool: jiraCheckPermissions, requiredAuth: 'jiraToken' as const, scope: 'read' as const },
    { name: 'JiraCreateBoard', description: jiraCreateBoard.description!, tool: jiraCreateBoard, requiredAuth: 'jiraToken' as const, scope: 'write' as const },
    { name: 'JiraCreateGroup', description: jiraCreateGroup.description!, tool: jiraCreateGroup, requiredAuth: 'jiraToken' as const, scope: 'write' as const },
    { name: 'JiraCreateIssue', description: jiraCreateIssue.description!, tool: jiraCreateIssue, requiredAuth: 'jiraToken' as const, scope: 'write' as const },
    { name: 'JiraCreateIssueLink', description: jiraCreateIssueLink.description!, tool: jiraCreateIssueLink, requiredAuth: 'jiraToken' as const, scope: 'write' as const },
    { name: 'JiraCreateJqlAutocompletedata', description: jiraCreateJqlAutocompletedata.description!, tool: jiraCreateJqlAutocompletedata, requiredAuth: 'jiraToken' as const, scope: 'write' as const },
    { name: 'JiraCreateProject', description: jiraCreateProject.description!, tool: jiraCreateProject, requiredAuth: 'jiraToken' as const, scope: 'write' as const },
    { name: 'JiraCreateSprint', description: jiraCreateSprint.description!, tool: jiraCreateSprint, requiredAuth: 'jiraToken' as const, scope: 'write' as const },
    { name: 'JiraCreateVersion', description: jiraCreateVersion.description!, tool: jiraCreateVersion, requiredAuth: 'jiraToken' as const, scope: 'write' as const },
    { name: 'JiraDeleteAttachment', description: jiraDeleteAttachment.description!, tool: jiraDeleteAttachment, requiredAuth: 'jiraToken' as const, scope: 'delete' as const },
    { name: 'JiraDeleteComment', description: jiraDeleteComment.description!, tool: jiraDeleteComment, requiredAuth: 'jiraToken' as const, scope: 'delete' as const },
    { name: 'JiraDeleteIssue', description: jiraDeleteIssue.description!, tool: jiraDeleteIssue, requiredAuth: 'jiraToken' as const, scope: 'delete' as const },
    { name: 'JiraDeleteVersion', description: jiraDeleteVersion.description!, tool: jiraDeleteVersion, requiredAuth: 'jiraToken' as const, scope: 'delete' as const },
    { name: 'JiraDeleteWorklog', description: jiraDeleteWorklog.description!, tool: jiraDeleteWorklog, requiredAuth: 'jiraToken' as const, scope: 'delete' as const },
    { name: 'JiraEditIssue', description: jiraEditIssue.description!, tool: jiraEditIssue, requiredAuth: 'jiraToken' as const, scope: 'write' as const },
    { name: 'JiraEvaluateJiraExpression', description: jiraEvaluateJiraExpression.description!, tool: jiraEvaluateJiraExpression, requiredAuth: 'jiraToken' as const, scope: 'read' as const },
    { name: 'JiraFetchBulkIssues', description: jiraFetchBulkIssues.description!, tool: jiraFetchBulkIssues, requiredAuth: 'jiraToken' as const, scope: 'read' as const },
    { name: 'JiraFindUsers', description: jiraFindUsers.description!, tool: jiraFindUsers, requiredAuth: 'jiraToken' as const, scope: 'read' as const },
    { name: 'JiraFindUsers2', description: jiraFindUsers2.description!, tool: jiraFindUsers2, requiredAuth: 'jiraToken' as const, scope: 'read' as const },
    { name: 'JiraFindUsersForPicker', description: jiraFindUsersForPicker.description!, tool: jiraFindUsersForPicker, requiredAuth: 'jiraToken' as const, scope: 'read' as const },
    { name: 'JiraGetAllGroups', description: jiraGetAllGroups.description!, tool: jiraGetAllGroups, requiredAuth: 'jiraToken' as const, scope: 'read' as const },
    { name: 'JiraGetAllIssueTypeSchemes', description: jiraGetAllIssueTypeSchemes.description!, tool: jiraGetAllIssueTypeSchemes, requiredAuth: 'jiraToken' as const, scope: 'read' as const },
    { name: 'JiraGetAllProjects', description: jiraGetAllProjects.description!, tool: jiraGetAllProjects, requiredAuth: 'jiraToken' as const, scope: 'read' as const },
    { name: 'JiraGetAllStatuses', description: jiraGetAllStatuses.description!, tool: jiraGetAllStatuses, requiredAuth: 'jiraToken' as const, scope: 'read' as const },
    { name: 'JiraGetAllUsers', description: jiraGetAllUsers.description!, tool: jiraGetAllUsers, requiredAuth: 'jiraToken' as const, scope: 'read' as const },
    { name: 'JiraGetAttachment', description: jiraGetAttachment.description!, tool: jiraGetAttachment, requiredAuth: 'jiraToken' as const, scope: 'read' as const },
    { name: 'JiraGetAttachmentMeta', description: jiraGetAttachmentMeta.description!, tool: jiraGetAttachmentMeta, requiredAuth: 'jiraToken' as const, scope: 'read' as const },
    { name: 'JiraGetComment', description: jiraGetComment.description!, tool: jiraGetComment, requiredAuth: 'jiraToken' as const, scope: 'read' as const },
    { name: 'JiraGetComponents', description: jiraGetComponents.description!, tool: jiraGetComponents, requiredAuth: 'jiraToken' as const, scope: 'read' as const },
    { name: 'JiraGetCreateMetadataIssueTypeFields', description: jiraGetCreateMetadataIssueTypeFields.description!, tool: jiraGetCreateMetadataIssueTypeFields, requiredAuth: 'jiraToken' as const, scope: 'read' as const },
    { name: 'JiraGetCurrentUser', description: jiraGetCurrentUser.description!, tool: jiraGetCurrentUser, requiredAuth: 'jiraToken' as const, scope: 'read' as const },
    { name: 'JiraGetDashboards', description: jiraGetDashboards.description!, tool: jiraGetDashboards, requiredAuth: 'jiraToken' as const, scope: 'read' as const },
    { name: 'JiraGetFavoriteFilters', description: jiraGetFavoriteFilters.description!, tool: jiraGetFavoriteFilters, requiredAuth: 'jiraToken' as const, scope: 'read' as const },
    { name: 'JiraGetFields', description: jiraGetFields.description!, tool: jiraGetFields, requiredAuth: 'jiraToken' as const, scope: 'read' as const },
    { name: 'JiraGetFieldsPaginated', description: jiraGetFieldsPaginated.description!, tool: jiraGetFieldsPaginated, requiredAuth: 'jiraToken' as const, scope: 'read' as const },
    { name: 'JiraGetFilter', description: jiraGetFilter.description!, tool: jiraGetFilter, requiredAuth: 'jiraToken' as const, scope: 'read' as const },
    { name: 'JiraGetGroup', description: jiraGetGroup.description!, tool: jiraGetGroup, requiredAuth: 'jiraToken' as const, scope: 'read' as const },
    { name: 'JiraGetInfo', description: jiraGetInfo.description!, tool: jiraGetInfo, requiredAuth: 'jiraToken' as const, scope: 'read' as const },
    { name: 'JiraGetIssue', description: jiraGetIssue.description!, tool: jiraGetIssue, requiredAuth: 'jiraToken' as const, scope: 'read' as const },
    { name: 'JiraGetIssueCreateMetadata', description: jiraGetIssueCreateMetadata.description!, tool: jiraGetIssueCreateMetadata, requiredAuth: 'jiraToken' as const, scope: 'read' as const },
    { name: 'JiraGetIssueEditMetadata', description: jiraGetIssueEditMetadata.description!, tool: jiraGetIssueEditMetadata, requiredAuth: 'jiraToken' as const, scope: 'read' as const },
    { name: 'JiraGetIssueLinkTypes', description: jiraGetIssueLinkTypes.description!, tool: jiraGetIssueLinkTypes, requiredAuth: 'jiraToken' as const, scope: 'read' as const },
    { name: 'JiraGetIssuePickerSuggestions', description: jiraGetIssuePickerSuggestions.description!, tool: jiraGetIssuePickerSuggestions, requiredAuth: 'jiraToken' as const, scope: 'read' as const },
    { name: 'JiraGetIssueProperty', description: jiraGetIssueProperty.description!, tool: jiraGetIssueProperty, requiredAuth: 'jiraToken' as const, scope: 'read' as const },
    { name: 'JiraGetIssueResolutions', description: jiraGetIssueResolutions.description!, tool: jiraGetIssueResolutions, requiredAuth: 'jiraToken' as const, scope: 'read' as const },
    { name: 'JiraGetIssueTypes', description: jiraGetIssueTypes.description!, tool: jiraGetIssueTypes, requiredAuth: 'jiraToken' as const, scope: 'read' as const },
    { name: 'JiraGetIssueWatchers', description: jiraGetIssueWatchers.description!, tool: jiraGetIssueWatchers, requiredAuth: 'jiraToken' as const, scope: 'read' as const },
    { name: 'JiraGetIssueWorklogs', description: jiraGetIssueWorklogs.description!, tool: jiraGetIssueWorklogs, requiredAuth: 'jiraToken' as const, scope: 'read' as const },
    { name: 'JiraGetJqlAutocompletedata', description: jiraGetJqlAutocompletedata.description!, tool: jiraGetJqlAutocompletedata, requiredAuth: 'jiraToken' as const, scope: 'read' as const },
    { name: 'JiraGetJqlAutocompletedataSuggestions', description: jiraGetJqlAutocompletedataSuggestions.description!, tool: jiraGetJqlAutocompletedataSuggestions, requiredAuth: 'jiraToken' as const, scope: 'read' as const },
    { name: 'JiraGetMyPermissions', description: jiraGetMyPermissions.description!, tool: jiraGetMyPermissions, requiredAuth: 'jiraToken' as const, scope: 'read' as const },
    { name: 'JiraGetMypreferencesLocale', description: jiraGetMypreferencesLocale.description!, tool: jiraGetMypreferencesLocale, requiredAuth: 'jiraToken' as const, scope: 'read' as const },
    { name: 'JiraGetPermissions', description: jiraGetPermissions.description!, tool: jiraGetPermissions, requiredAuth: 'jiraToken' as const, scope: 'read' as const },
    { name: 'JiraGetPermittedProjects', description: jiraGetPermittedProjects.description!, tool: jiraGetPermittedProjects, requiredAuth: 'jiraToken' as const, scope: 'read' as const },
    { name: 'JiraGetProject', description: jiraGetProject.description!, tool: jiraGetProject, requiredAuth: 'jiraToken' as const, scope: 'read' as const },
    { name: 'JiraGetProjectRoles', description: jiraGetProjectRoles.description!, tool: jiraGetProjectRoles, requiredAuth: 'jiraToken' as const, scope: 'read' as const },
    { name: 'JiraGetProjectTemplates', description: jiraGetProjectTemplates.description!, tool: jiraGetProjectTemplates, requiredAuth: 'jiraToken' as const, scope: 'read' as const },
    { name: 'JiraGetProjectType', description: jiraGetProjectType.description!, tool: jiraGetProjectType, requiredAuth: 'jiraToken' as const, scope: 'read' as const },
    { name: 'JiraGetProjectVersions', description: jiraGetProjectVersions.description!, tool: jiraGetProjectVersions, requiredAuth: 'jiraToken' as const, scope: 'read' as const },
    { name: 'JiraGetRecentProjects', description: jiraGetRecentProjects.description!, tool: jiraGetRecentProjects, requiredAuth: 'jiraToken' as const, scope: 'read' as const },
    { name: 'JiraGetRemoteIssueLinks', description: jiraGetRemoteIssueLinks.description!, tool: jiraGetRemoteIssueLinks, requiredAuth: 'jiraToken' as const, scope: 'read' as const },
    { name: 'JiraGetServerInfo', description: jiraGetServerInfo.description!, tool: jiraGetServerInfo, requiredAuth: 'jiraToken' as const, scope: 'read' as const },
    { name: 'JiraGetServiceDeskRequestTypeFields', description: jiraGetServiceDeskRequestTypeFields.description!, tool: jiraGetServiceDeskRequestTypeFields, requiredAuth: 'jiraToken' as const, scope: 'read' as const },
    { name: 'JiraGetSprint', description: jiraGetSprint.description!, tool: jiraGetSprint, requiredAuth: 'jiraToken' as const, scope: 'read' as const },
    { name: 'JiraGetSystemAvatars', description: jiraGetSystemAvatars.description!, tool: jiraGetSystemAvatars, requiredAuth: 'jiraToken' as const, scope: 'read' as const },
    { name: 'JiraGetTransitions', description: jiraGetTransitions.description!, tool: jiraGetTransitions, requiredAuth: 'jiraToken' as const, scope: 'read' as const },
    { name: 'JiraGetUniversalAvatarTypeOwner', description: jiraGetUniversalAvatarTypeOwner.description!, tool: jiraGetUniversalAvatarTypeOwner, requiredAuth: 'jiraToken' as const, scope: 'read' as const },
    { name: 'JiraGetUniversalAvatarViewType', description: jiraGetUniversalAvatarViewType.description!, tool: jiraGetUniversalAvatarViewType, requiredAuth: 'jiraToken' as const, scope: 'read' as const },
    { name: 'JiraGetUserGroups', description: jiraGetUserGroups.description!, tool: jiraGetUserGroups, requiredAuth: 'jiraToken' as const, scope: 'read' as const },
    { name: 'JiraGetViewTypeAvatar', description: jiraGetViewTypeAvatar.description!, tool: jiraGetViewTypeAvatar, requiredAuth: 'jiraToken' as const, scope: 'read' as const },
    { name: 'JiraGetVotes', description: jiraGetVotes.description!, tool: jiraGetVotes, requiredAuth: 'jiraToken' as const, scope: 'read' as const },
    { name: 'JiraGetWorklog', description: jiraGetWorklog.description!, tool: jiraGetWorklog, requiredAuth: 'jiraToken' as const, scope: 'read' as const },
    { name: 'JiraListAllProjects', description: jiraListAllProjects.description!, tool: jiraListAllProjects, requiredAuth: 'jiraToken' as const, scope: 'read' as const },
    { name: 'JiraListBoards', description: jiraListBoards.description!, tool: jiraListBoards, requiredAuth: 'jiraToken' as const, scope: 'read' as const },
    { name: 'JiraListComments', description: jiraListComments.description!, tool: jiraListComments, requiredAuth: 'jiraToken' as const, scope: 'read' as const },
    { name: 'JiraListFilters', description: jiraListFilters.description!, tool: jiraListFilters, requiredAuth: 'jiraToken' as const, scope: 'read' as const },
    { name: 'JiraListGroupsPicker', description: jiraListGroupsPicker.description!, tool: jiraListGroupsPicker, requiredAuth: 'jiraToken' as const, scope: 'read' as const },
    { name: 'JiraListIssueComments', description: jiraListIssueComments.description!, tool: jiraListIssueComments, requiredAuth: 'jiraToken' as const, scope: 'read' as const },
    { name: 'JiraListProjectTypes', description: jiraListProjectTypes.description!, tool: jiraListProjectTypes, requiredAuth: 'jiraToken' as const, scope: 'read' as const },
    { name: 'JiraListSprints', description: jiraListSprints.description!, tool: jiraListSprints, requiredAuth: 'jiraToken' as const, scope: 'read' as const },
    { name: 'JiraMoveIssueToSprint', description: jiraMoveIssueToSprint.description!, tool: jiraMoveIssueToSprint, requiredAuth: 'jiraToken' as const, scope: 'write' as const },
    { name: 'JiraParseJqlQueries', description: jiraParseJqlQueries.description!, tool: jiraParseJqlQueries, requiredAuth: 'jiraToken' as const, scope: 'read' as const },
    { name: 'JiraRemoveUserFromGroup', description: jiraRemoveUserFromGroup.description!, tool: jiraRemoveUserFromGroup, requiredAuth: 'jiraToken' as const, scope: 'write' as const },
    { name: 'JiraRemoveUserFromProjectRole', description: jiraRemoveUserFromProjectRole.description!, tool: jiraRemoveUserFromProjectRole, requiredAuth: 'jiraToken' as const, scope: 'write' as const },
    { name: 'JiraRemoveWatcherFromIssue', description: jiraRemoveWatcherFromIssue.description!, tool: jiraRemoveWatcherFromIssue, requiredAuth: 'jiraToken' as const, scope: 'write' as const },
    { name: 'JiraSearchApproximateCount', description: jiraSearchApproximateCount.description!, tool: jiraSearchApproximateCount, requiredAuth: 'jiraToken' as const, scope: 'read' as const },
    { name: 'JiraSearchDashboards', description: jiraSearchDashboards.description!, tool: jiraSearchDashboards, requiredAuth: 'jiraToken' as const, scope: 'read' as const },
    { name: 'JiraSearchForIssuesUsingJqlGet', description: jiraSearchForIssuesUsingJqlGet.description!, tool: jiraSearchForIssuesUsingJqlGet, requiredAuth: 'jiraToken' as const, scope: 'read' as const },
    { name: 'JiraSearchForIssuesUsingJqlPost', description: jiraSearchForIssuesUsingJqlPost.description!, tool: jiraSearchForIssuesUsingJqlPost, requiredAuth: 'jiraToken' as const, scope: 'read' as const },
    { name: 'JiraSearchIssues', description: jiraSearchIssues.description!, tool: jiraSearchIssues, requiredAuth: 'jiraToken' as const, scope: 'read' as const },
    { name: 'JiraSendNotificationForIssue', description: jiraSendNotificationForIssue.description!, tool: jiraSendNotificationForIssue, requiredAuth: 'jiraToken' as const, scope: 'write' as const },
    { name: 'JiraTransitionIssue', description: jiraTransitionIssue.description!, tool: jiraTransitionIssue, requiredAuth: 'jiraToken' as const, scope: 'write' as const },
    { name: 'JiraUpdateComment', description: jiraUpdateComment.description!, tool: jiraUpdateComment, requiredAuth: 'jiraToken' as const, scope: 'write' as const },
    { name: 'JiraWhoAmI', description: jiraWhoAmI.description!, tool: jiraWhoAmI, requiredAuth: 'jiraToken' as const, scope: 'read' as const },
];
