// @ts-nocheck
import {
  databricksListClusters,
  databricksGetCluster,
  databricksCreateCluster,
  databricksEditCluster,
  databricksStartCluster,
  databricksRestartCluster,
  databricksResizeCluster,
  databricksTerminateCluster,
  databricksPermanentlyDeleteCluster,
  databricksGetClusterEvents,
  databricksListSparkVersions,
  databricksListNodeTypes,
  databricksListZones,
  databricksGetClusterLibraryStatus,
  databricksInstallLibraries,
  databricksUninstallLibraries,
} from './clusters.js';
import {
  databricksListJobs,
  databricksGetJob,
  databricksCreateJob,
  databricksUpdateJob,
  databricksResetJob,
  databricksDeleteJob,
  databricksRunJobNow,
  databricksSubmitRun,
  databricksListJobRuns,
  databricksGetJobRun,
  databricksGetRunOutput,
  databricksCancelJobRun,
  databricksRepairJobRun,
  databricksDeleteJobRun,
} from './jobs.js';
import {
  databricksListWorkspace,
  databricksGetWorkspaceStatus,
  databricksMakeWorkspaceDirectory,
  databricksDeleteWorkspaceObject,
  databricksExportWorkspaceFile,
  databricksImportWorkspaceFile,
  databricksGetDbfsStatus,
  databricksListDbfs,
  databricksMakeDbfsDirectory,
  databricksReadDbfsFile,
  databricksWriteDbfsFile,
  databricksMoveDbfsObject,
  databricksDeleteDbfsObject,
} from './files.js';
import {
  databricksListWarehouses,
  databricksGetWarehouse,
  databricksCreateWarehouse,
  databricksEditWarehouse,
  databricksDeleteWarehouse,
  databricksStartWarehouse,
  databricksStopWarehouse,
  databricksExecuteStatement,
  databricksGetStatement,
  databricksGetStatementResultChunk,
  databricksCancelStatement,
  databricksListQueries,
  databricksGetQuery,
  databricksCreateQuery,
  databricksUpdateQuery,
  databricksDeleteQuery,
  databricksListAlerts,
  databricksGetAlert,
  databricksListDashboards,
  databricksGetDashboard,
} from './sql.js';
import {
  databricksListCatalogs,
  databricksGetCatalog,
  databricksCreateCatalog,
  databricksUpdateCatalog,
  databricksDeleteCatalog,
  databricksListSchemas,
  databricksCreateSchema,
  databricksDeleteSchema,
  databricksListTables,
  databricksGetTable,
  databricksDeleteTable,
  databricksListVolumes,
  databricksGetGrants,
  databricksUpdateGrants,
} from './unity.js';
import {
  databricksListPipelines,
  databricksGetPipeline,
  databricksCreatePipeline,
  databricksEditPipeline,
  databricksDeletePipeline,
  databricksStartPipeline,
  databricksStopPipeline,
  databricksListPipelineUpdates,
  databricksGetPipelineUpdate,
  databricksListRepos,
  databricksGetRepo,
  databricksCreateRepo,
  databricksUpdateRepo,
  databricksDeleteRepo,
} from './pipelines.js';
import {
  databricksListClusterPolicies,
  databricksGetClusterPolicy,
  databricksCreateClusterPolicy,
  databricksEditClusterPolicy,
  databricksDeleteClusterPolicy,
  databricksListInstancePools,
  databricksGetInstancePool,
  databricksCreateInstancePool,
  databricksEditInstancePool,
  databricksDeleteInstancePool,
  databricksListInitScripts,
  databricksGetInitScript,
  databricksCreateInitScript,
  databricksUpdateInitScript,
  databricksDeleteInitScript,
} from './compute.js';
import {
  databricksListSecretScopes,
  databricksCreateSecretScope,
  databricksDeleteSecretScope,
  databricksPutSecret,
  databricksDeleteSecret,
  databricksListSecrets,
  databricksListSecretAcls,
  databricksPutSecretAcl,
  databricksDeleteSecretAcl,
  databricksListScimUsers,
  databricksGetScimUser,
  databricksCreateScimUser,
  databricksUpdateScimUser,
  databricksDeleteScimUser,
  databricksListScimGroups,
  databricksGetScimGroup,
  databricksCreateScimGroup,
  databricksDeleteScimGroup,
  databricksGetScimMe,
  databricksListTokens,
  databricksCreateToken,
  databricksUpdateToken,
  databricksRevokeToken,
} from './admin.js';
import {
  databricksListModels,
  databricksGetModel,
  databricksCreateModel,
  databricksDeleteModel,
  databricksListModelVersions,
  databricksCreateModelVersion,
  databricksListServingEndpoints,
  databricksGetServingEndpoint,
  databricksQueryServingEndpoint,
} from './ml.js';

export {
  databricksListClusters,
  databricksGetCluster,
  databricksCreateCluster,
  databricksEditCluster,
  databricksStartCluster,
  databricksRestartCluster,
  databricksResizeCluster,
  databricksTerminateCluster,
  databricksPermanentlyDeleteCluster,
  databricksGetClusterEvents,
  databricksListSparkVersions,
  databricksListNodeTypes,
  databricksListZones,
  databricksGetClusterLibraryStatus,
  databricksInstallLibraries,
  databricksUninstallLibraries,
  databricksListJobs,
  databricksGetJob,
  databricksCreateJob,
  databricksUpdateJob,
  databricksResetJob,
  databricksDeleteJob,
  databricksRunJobNow,
  databricksSubmitRun,
  databricksListJobRuns,
  databricksGetJobRun,
  databricksGetRunOutput,
  databricksCancelJobRun,
  databricksRepairJobRun,
  databricksDeleteJobRun,
  databricksListWorkspace,
  databricksGetWorkspaceStatus,
  databricksMakeWorkspaceDirectory,
  databricksDeleteWorkspaceObject,
  databricksExportWorkspaceFile,
  databricksImportWorkspaceFile,
  databricksGetDbfsStatus,
  databricksListDbfs,
  databricksMakeDbfsDirectory,
  databricksReadDbfsFile,
  databricksWriteDbfsFile,
  databricksMoveDbfsObject,
  databricksDeleteDbfsObject,
  databricksListWarehouses,
  databricksGetWarehouse,
  databricksCreateWarehouse,
  databricksEditWarehouse,
  databricksDeleteWarehouse,
  databricksStartWarehouse,
  databricksStopWarehouse,
  databricksExecuteStatement,
  databricksGetStatement,
  databricksGetStatementResultChunk,
  databricksCancelStatement,
  databricksListQueries,
  databricksGetQuery,
  databricksCreateQuery,
  databricksUpdateQuery,
  databricksDeleteQuery,
  databricksListAlerts,
  databricksGetAlert,
  databricksListDashboards,
  databricksGetDashboard,
  databricksListCatalogs,
  databricksGetCatalog,
  databricksCreateCatalog,
  databricksUpdateCatalog,
  databricksDeleteCatalog,
  databricksListSchemas,
  databricksCreateSchema,
  databricksDeleteSchema,
  databricksListTables,
  databricksGetTable,
  databricksDeleteTable,
  databricksListVolumes,
  databricksGetGrants,
  databricksUpdateGrants,
  databricksListPipelines,
  databricksGetPipeline,
  databricksCreatePipeline,
  databricksEditPipeline,
  databricksDeletePipeline,
  databricksStartPipeline,
  databricksStopPipeline,
  databricksListPipelineUpdates,
  databricksGetPipelineUpdate,
  databricksListRepos,
  databricksGetRepo,
  databricksCreateRepo,
  databricksUpdateRepo,
  databricksDeleteRepo,
  databricksListClusterPolicies,
  databricksGetClusterPolicy,
  databricksCreateClusterPolicy,
  databricksEditClusterPolicy,
  databricksDeleteClusterPolicy,
  databricksListInstancePools,
  databricksGetInstancePool,
  databricksCreateInstancePool,
  databricksEditInstancePool,
  databricksDeleteInstancePool,
  databricksListInitScripts,
  databricksGetInitScript,
  databricksCreateInitScript,
  databricksUpdateInitScript,
  databricksDeleteInitScript,
  databricksListSecretScopes,
  databricksCreateSecretScope,
  databricksDeleteSecretScope,
  databricksPutSecret,
  databricksDeleteSecret,
  databricksListSecrets,
  databricksListSecretAcls,
  databricksPutSecretAcl,
  databricksDeleteSecretAcl,
  databricksListScimUsers,
  databricksGetScimUser,
  databricksCreateScimUser,
  databricksUpdateScimUser,
  databricksDeleteScimUser,
  databricksListScimGroups,
  databricksGetScimGroup,
  databricksCreateScimGroup,
  databricksDeleteScimGroup,
  databricksGetScimMe,
  databricksListTokens,
  databricksCreateToken,
  databricksUpdateToken,
  databricksRevokeToken,
  databricksListModels,
  databricksGetModel,
  databricksCreateModel,
  databricksDeleteModel,
  databricksListModelVersions,
  databricksCreateModelVersion,
  databricksListServingEndpoints,
  databricksGetServingEndpoint,
  databricksQueryServingEndpoint,
};

const AUTH = 'databricksCredentials' as const;

export const databricksTools = [
  {
    name: 'databricksListClusters',
    description: 'List pinned, active, and recently terminated clusters.',
    tool: databricksListClusters,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['compute', 'spark', 'nodes'],
  },
  {
    name: 'databricksGetCluster',
    description: 'Get full details of one cluster.',
    tool: databricksGetCluster,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['compute', 'fetch', 'state'],
  },
  {
    name: 'databricksCreateCluster',
    description: 'Create a new Spark cluster.',
    tool: databricksCreateCluster,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['compute', 'provision', 'spark'],
  },
  {
    name: 'databricksEditCluster',
    description: 'Edit a cluster configuration.',
    tool: databricksEditCluster,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['compute', 'reconfigure'],
  },
  {
    name: 'databricksStartCluster',
    description: 'Start a terminated cluster.',
    tool: databricksStartCluster,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['compute', 'launch', 'resume'],
  },
  {
    name: 'databricksRestartCluster',
    description: 'Restart a running cluster.',
    tool: databricksRestartCluster,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['compute', 'reboot'],
  },
  {
    name: 'databricksResizeCluster',
    description: 'Resize a cluster by size or autoscale bounds.',
    tool: databricksResizeCluster,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['compute', 'scale', 'workers'],
  },
  {
    name: 'databricksTerminateCluster',
    description: 'Terminate a cluster (recoverable 30 days).',
    tool: databricksTerminateCluster,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['compute', 'stop', 'shutdown'],
  },
  {
    name: 'databricksPermanentlyDeleteCluster',
    description: 'Permanently delete a terminated cluster.',
    tool: databricksPermanentlyDeleteCluster,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['compute', 'remove'],
  },
  {
    name: 'databricksGetClusterEvents',
    description: 'Get cluster lifecycle events for debugging.',
    tool: databricksGetClusterEvents,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['logs', 'audit', 'history'],
  },
  {
    name: 'databricksListSparkVersions',
    description: 'List available Databricks Runtime versions.',
    tool: databricksListSparkVersions,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['runtime', 'dbr', 'versions'],
  },
  {
    name: 'databricksListNodeTypes',
    description: 'List available VM node types.',
    tool: databricksListNodeTypes,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['vm', 'instance', 'sizes'],
  },
  {
    name: 'databricksListZones',
    description: 'List availability zones for clusters.',
    tool: databricksListZones,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['az', 'region'],
  },
  {
    name: 'databricksGetClusterLibraryStatus',
    description: 'Get library installation statuses on a cluster.',
    tool: databricksGetClusterLibraryStatus,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['packages', 'pypi', 'maven'],
  },
  {
    name: 'databricksInstallLibraries',
    description: 'Install libraries on a running cluster.',
    tool: databricksInstallLibraries,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['packages', 'pypi', 'pip'],
  },
  {
    name: 'databricksUninstallLibraries',
    description: 'Uninstall libraries from a cluster.',
    tool: databricksUninstallLibraries,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['packages', 'remove'],
  },
  {
    name: 'databricksListJobs',
    description: 'List jobs with name filter and pagination.',
    tool: databricksListJobs,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['workflows', 'schedules', 'etl'],
  },
  {
    name: 'databricksGetJob',
    description: 'Get full settings of one job.',
    tool: databricksGetJob,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['workflow', 'fetch', 'definition'],
  },
  {
    name: 'databricksCreateJob',
    description: 'Create a single- or multi-task job.',
    tool: databricksCreateJob,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['workflow', 'schedule', 'etl'],
  },
  {
    name: 'databricksUpdateJob',
    description: 'Partially update job settings.',
    tool: databricksUpdateJob,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['workflow', 'edit', 'patch'],
  },
  {
    name: 'databricksResetJob',
    description: 'Overwrite all settings of a job.',
    tool: databricksResetJob,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['workflow', 'replace'],
  },
  {
    name: 'databricksDeleteJob',
    description: 'Delete a job and terminate active runs.',
    tool: databricksDeleteJob,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['workflow', 'remove'],
  },
  {
    name: 'databricksRunJobNow',
    description: 'Trigger an immediate job run with overrides.',
    tool: databricksRunJobNow,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['trigger', 'execute', 'run'],
  },
  {
    name: 'databricksSubmitRun',
    description: 'Submit a one-time ad-hoc run.',
    tool: databricksSubmitRun,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['adhoc', 'notebook', 'execute'],
  },
  {
    name: 'databricksListJobRuns',
    description: 'List job runs newest-first with filters.',
    tool: databricksListJobRuns,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['executions', 'history', 'runs'],
  },
  {
    name: 'databricksGetJobRun',
    description: 'Get full details of one job run.',
    tool: databricksGetJobRun,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['execution', 'fetch', 'status'],
  },
  {
    name: 'databricksGetRunOutput',
    description: 'Get notebook output or error of a run.',
    tool: databricksGetRunOutput,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['results', 'logs', 'output'],
  },
  {
    name: 'databricksCancelJobRun',
    description: 'Cancel an active job run.',
    tool: databricksCancelJobRun,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['stop', 'kill', 'abort'],
  },
  {
    name: 'databricksRepairJobRun',
    description: 'Re-run failed tasks of a job run.',
    tool: databricksRepairJobRun,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['retry', 'rerun', 'fix'],
  },
  {
    name: 'databricksDeleteJobRun',
    description: 'Delete a finished job run.',
    tool: databricksDeleteJobRun,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['history', 'remove'],
  },
  {
    name: 'databricksListWorkspace',
    description: 'List notebooks, folders, and files in workspace.',
    tool: databricksListWorkspace,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['browse', 'notebooks', 'directory'],
  },
  {
    name: 'databricksGetWorkspaceStatus',
    description: 'Get object type of a workspace path.',
    tool: databricksGetWorkspaceStatus,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['notebook', 'inspect'],
  },
  {
    name: 'databricksMakeWorkspaceDirectory',
    description: 'Create a workspace directory.',
    tool: databricksMakeWorkspaceDirectory,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['folder', 'mkdir'],
  },
  {
    name: 'databricksDeleteWorkspaceObject',
    description: 'Delete a notebook, file, or directory.',
    tool: databricksDeleteWorkspaceObject,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['notebook', 'remove'],
  },
  {
    name: 'databricksExportWorkspaceFile',
    description: 'Export a notebook or file as base64.',
    tool: databricksExportWorkspaceFile,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['notebook', 'download'],
  },
  {
    name: 'databricksImportWorkspaceFile',
    description: 'Import a notebook or file from base64.',
    tool: databricksImportWorkspaceFile,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['notebook', 'upload'],
  },
  {
    name: 'databricksGetDbfsStatus',
    description: 'Get DBFS storage status.',
    tool: databricksGetDbfsStatus,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['storage', 'capacity'],
  },
  {
    name: 'databricksListDbfs',
    description: 'List files in a DBFS directory.',
    tool: databricksListDbfs,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['storage', 'browse', 'files'],
  },
  {
    name: 'databricksMakeDbfsDirectory',
    description: 'Create a DBFS directory.',
    tool: databricksMakeDbfsDirectory,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['storage', 'mkdir'],
  },
  {
    name: 'databricksReadDbfsFile',
    description: 'Read a slice of a DBFS file as base64.',
    tool: databricksReadDbfsFile,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['storage', 'download'],
  },
  {
    name: 'databricksWriteDbfsFile',
    description: 'Write a small text file to DBFS.',
    tool: databricksWriteDbfsFile,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['storage', 'upload'],
  },
  {
    name: 'databricksMoveDbfsObject',
    description: 'Move (rename) a DBFS file or directory.',
    tool: databricksMoveDbfsObject,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['storage', 'rename'],
  },
  {
    name: 'databricksDeleteDbfsObject',
    description: 'Delete a DBFS file or directory.',
    tool: databricksDeleteDbfsObject,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['storage', 'remove'],
  },
  {
    name: 'databricksListWarehouses',
    description: 'List SQL warehouses.',
    tool: databricksListWarehouses,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['sql', 'endpoints', 'compute'],
  },
  {
    name: 'databricksGetWarehouse',
    description: 'Get one SQL warehouse config and state.',
    tool: databricksGetWarehouse,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['sql', 'fetch'],
  },
  {
    name: 'databricksCreateWarehouse',
    description: 'Create a SQL warehouse.',
    tool: databricksCreateWarehouse,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['sql', 'provision'],
  },
  {
    name: 'databricksEditWarehouse',
    description: 'Edit a SQL warehouse config.',
    tool: databricksEditWarehouse,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['sql', 'resize'],
  },
  {
    name: 'databricksDeleteWarehouse',
    description: 'Delete a SQL warehouse.',
    tool: databricksDeleteWarehouse,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['sql', 'remove'],
  },
  {
    name: 'databricksStartWarehouse',
    description: 'Start a stopped SQL warehouse.',
    tool: databricksStartWarehouse,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['sql', 'launch'],
  },
  {
    name: 'databricksStopWarehouse',
    description: 'Stop a SQL warehouse to save cost.',
    tool: databricksStopWarehouse,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['sql', 'pause'],
  },
  {
    name: 'databricksExecuteStatement',
    description: 'Run a SQL statement on a warehouse.',
    tool: databricksExecuteStatement,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['query', 'analytics', 'run'],
  },
  {
    name: 'databricksGetStatement',
    description: 'Get status and results of a statement.',
    tool: databricksGetStatement,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['query', 'results', 'poll'],
  },
  {
    name: 'databricksGetStatementResultChunk',
    description: 'Fetch one result chunk of a statement.',
    tool: databricksGetStatementResultChunk,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['query', 'pagination'],
  },
  {
    name: 'databricksCancelStatement',
    description: 'Cancel a running SQL statement.',
    tool: databricksCancelStatement,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['query', 'stop'],
  },
  {
    name: 'databricksListQueries',
    description: 'List saved SQL queries.',
    tool: databricksListQueries,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['saved', 'reports'],
  },
  {
    name: 'databricksGetQuery',
    description: 'Get one saved SQL query.',
    tool: databricksGetQuery,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['saved', 'fetch'],
  },
  {
    name: 'databricksCreateQuery',
    description: 'Save a new SQL query.',
    tool: databricksCreateQuery,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['saved', 'report'],
  },
  {
    name: 'databricksUpdateQuery',
    description: 'Update a saved SQL query.',
    tool: databricksUpdateQuery,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['saved', 'edit'],
  },
  {
    name: 'databricksDeleteQuery',
    description: 'Delete a saved SQL query.',
    tool: databricksDeleteQuery,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['saved', 'remove'],
  },
  {
    name: 'databricksListAlerts',
    description: 'List SQL alerts.',
    tool: databricksListAlerts,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['monitors', 'notifications'],
  },
  {
    name: 'databricksGetAlert',
    description: 'Get one SQL alert.',
    tool: databricksGetAlert,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['monitor', 'fetch'],
  },
  {
    name: 'databricksListDashboards',
    description: 'List legacy SQL dashboards.',
    tool: databricksListDashboards,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['bi', 'reports'],
  },
  {
    name: 'databricksGetDashboard',
    description: 'Get one legacy SQL dashboard.',
    tool: databricksGetDashboard,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['bi', 'fetch'],
  },
  {
    name: 'databricksListCatalogs',
    description: 'List Unity Catalog catalogs.',
    tool: databricksListCatalogs,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['data', 'domains'],
  },
  {
    name: 'databricksGetCatalog',
    description: 'Get one Unity Catalog catalog.',
    tool: databricksGetCatalog,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['data', 'fetch'],
  },
  {
    name: 'databricksCreateCatalog',
    description: 'Create a Unity Catalog catalog.',
    tool: databricksCreateCatalog,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['data', 'governance'],
  },
  {
    name: 'databricksUpdateCatalog',
    description: 'Update a Unity Catalog catalog.',
    tool: databricksUpdateCatalog,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['data', 'rename'],
  },
  {
    name: 'databricksDeleteCatalog',
    description: 'Delete a Unity Catalog catalog.',
    tool: databricksDeleteCatalog,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['data', 'remove'],
  },
  {
    name: 'databricksListSchemas',
    description: 'List schemas in a catalog.',
    tool: databricksListSchemas,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['databases', 'namespaces'],
  },
  {
    name: 'databricksCreateSchema',
    description: 'Create a schema in a catalog.',
    tool: databricksCreateSchema,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['database', 'namespace'],
  },
  {
    name: 'databricksDeleteSchema',
    description: 'Delete a schema.',
    tool: databricksDeleteSchema,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['database', 'remove'],
  },
  {
    name: 'databricksListTables',
    description: 'List tables and views in a schema.',
    tool: databricksListTables,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['datasets', 'delta'],
  },
  {
    name: 'databricksGetTable',
    description: 'Get one table with columns and storage.',
    tool: databricksGetTable,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['dataset', 'schema', 'fetch'],
  },
  {
    name: 'databricksDeleteTable',
    description: 'Delete a table.',
    tool: databricksDeleteTable,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['dataset', 'drop'],
  },
  {
    name: 'databricksListVolumes',
    description: 'List Unity Catalog volumes in a schema.',
    tool: databricksListVolumes,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['files', 'storage'],
  },
  {
    name: 'databricksGetGrants',
    description: 'Get privilege grants on a securable.',
    tool: databricksGetGrants,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['permissions', 'audit', 'acl'],
  },
  {
    name: 'databricksUpdateGrants',
    description: 'Grant or revoke privileges on a securable.',
    tool: databricksUpdateGrants,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['permissions', 'rbac', 'share'],
  },
  {
    name: 'databricksListPipelines',
    description: 'List Delta Live Tables pipelines.',
    tool: databricksListPipelines,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['dlt', 'streaming', 'etl'],
  },
  {
    name: 'databricksGetPipeline',
    description: 'Get one pipeline with full spec.',
    tool: databricksGetPipeline,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['dlt', 'fetch'],
  },
  {
    name: 'databricksCreatePipeline',
    description: 'Create a Delta Live Tables pipeline.',
    tool: databricksCreatePipeline,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['dlt', 'streaming'],
  },
  {
    name: 'databricksEditPipeline',
    description: 'Edit a pipeline spec.',
    tool: databricksEditPipeline,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['dlt', 'update'],
  },
  {
    name: 'databricksDeletePipeline',
    description: 'Delete a pipeline.',
    tool: databricksDeletePipeline,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['dlt', 'remove'],
  },
  {
    name: 'databricksStartPipeline',
    description: 'Start a pipeline update.',
    tool: databricksStartPipeline,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['dlt', 'run', 'refresh'],
  },
  {
    name: 'databricksStopPipeline',
    description: 'Stop the active pipeline update.',
    tool: databricksStopPipeline,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['dlt', 'cancel'],
  },
  {
    name: 'databricksListPipelineUpdates',
    description: 'List updates (runs) of a pipeline.',
    tool: databricksListPipelineUpdates,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['dlt', 'runs', 'history'],
  },
  {
    name: 'databricksGetPipelineUpdate',
    description: 'Get one pipeline update.',
    tool: databricksGetPipelineUpdate,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['dlt', 'run', 'fetch'],
  },
  {
    name: 'databricksListRepos',
    description: 'List Git-linked repos.',
    tool: databricksListRepos,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['git', 'folders'],
  },
  {
    name: 'databricksGetRepo',
    description: 'Get one repo with branch and commit.',
    tool: databricksGetRepo,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['git', 'fetch'],
  },
  {
    name: 'databricksCreateRepo',
    description: 'Link a Git repository into the workspace.',
    tool: databricksCreateRepo,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['git', 'clone', 'checkout'],
  },
  {
    name: 'databricksUpdateRepo',
    description: 'Checkout a branch or tag in a repo.',
    tool: databricksUpdateRepo,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['git', 'pull', 'branch'],
  },
  {
    name: 'databricksDeleteRepo',
    description: 'Unlink a Git repo checkout.',
    tool: databricksDeleteRepo,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['git', 'remove'],
  },
  {
    name: 'databricksListClusterPolicies',
    description: 'List cluster policies.',
    tool: databricksListClusterPolicies,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['governance', 'guardrails'],
  },
  {
    name: 'databricksGetClusterPolicy',
    description: 'Get one cluster policy with rules.',
    tool: databricksGetClusterPolicy,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['governance', 'fetch'],
  },
  {
    name: 'databricksCreateClusterPolicy',
    description: 'Create a cluster policy.',
    tool: databricksCreateClusterPolicy,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['governance', 'compliance'],
  },
  {
    name: 'databricksEditClusterPolicy',
    description: 'Edit a cluster policy.',
    tool: databricksEditClusterPolicy,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['governance', 'update'],
  },
  {
    name: 'databricksDeleteClusterPolicy',
    description: 'Delete a cluster policy.',
    tool: databricksDeleteClusterPolicy,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['governance', 'remove'],
  },
  {
    name: 'databricksListInstancePools',
    description: 'List instance pools.',
    tool: databricksListInstancePools,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['vms', 'warm', 'fleet'],
  },
  {
    name: 'databricksGetInstancePool',
    description: 'Get one instance pool.',
    tool: databricksGetInstancePool,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['vms', 'fetch'],
  },
  {
    name: 'databricksCreateInstancePool',
    description: 'Create an instance pool.',
    tool: databricksCreateInstancePool,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['vms', 'provision'],
  },
  {
    name: 'databricksEditInstancePool',
    description: 'Edit an instance pool.',
    tool: databricksEditInstancePool,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['vms', 'resize'],
  },
  {
    name: 'databricksDeleteInstancePool',
    description: 'Delete an idle instance pool.',
    tool: databricksDeleteInstancePool,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['vms', 'remove'],
  },
  {
    name: 'databricksListInitScripts',
    description: 'List global init scripts.',
    tool: databricksListInitScripts,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['bootstrap', 'startup'],
  },
  {
    name: 'databricksGetInitScript',
    description: 'Get one global init script.',
    tool: databricksGetInitScript,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['bootstrap', 'fetch'],
  },
  {
    name: 'databricksCreateInitScript',
    description: 'Create a global init script.',
    tool: databricksCreateInitScript,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['bootstrap', 'startup'],
  },
  {
    name: 'databricksUpdateInitScript',
    description: 'Update a global init script.',
    tool: databricksUpdateInitScript,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['bootstrap', 'edit'],
  },
  {
    name: 'databricksDeleteInitScript',
    description: 'Delete a global init script.',
    tool: databricksDeleteInitScript,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['bootstrap', 'remove'],
  },
  {
    name: 'databricksListSecretScopes',
    description: 'List secret scopes.',
    tool: databricksListSecretScopes,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['credentials', 'vault'],
  },
  {
    name: 'databricksCreateSecretScope',
    description: 'Create a secret scope.',
    tool: databricksCreateSecretScope,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['credentials', 'vault'],
  },
  {
    name: 'databricksDeleteSecretScope',
    description: 'Delete a secret scope and secrets.',
    tool: databricksDeleteSecretScope,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['credentials', 'remove'],
  },
  {
    name: 'databricksPutSecret',
    description: 'Store a secret value (write-only).',
    tool: databricksPutSecret,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['credentials', 'password'],
  },
  {
    name: 'databricksDeleteSecret',
    description: 'Delete one secret key.',
    tool: databricksDeleteSecret,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['credentials', 'remove'],
  },
  {
    name: 'databricksListSecrets',
    description: 'List secret keys (metadata only).',
    tool: databricksListSecrets,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['credentials', 'keys'],
  },
  {
    name: 'databricksListSecretAcls',
    description: 'List ACLs on a secret scope.',
    tool: databricksListSecretAcls,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['permissions', 'audit'],
  },
  {
    name: 'databricksPutSecretAcl',
    description: 'Grant a principal scope permission.',
    tool: databricksPutSecretAcl,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['permissions', 'share'],
  },
  {
    name: 'databricksDeleteSecretAcl',
    description: 'Remove a principal scope permission.',
    tool: databricksDeleteSecretAcl,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['permissions', 'revoke'],
  },
  {
    name: 'databricksListScimUsers',
    description: 'List workspace users via SCIM.',
    tool: databricksListScimUsers,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['identity', 'provisioning'],
  },
  {
    name: 'databricksGetScimUser',
    description: 'Get one SCIM user.',
    tool: databricksGetScimUser,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['identity', 'fetch'],
  },
  {
    name: 'databricksCreateScimUser',
    description: 'Provision a workspace user.',
    tool: databricksCreateScimUser,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['identity', 'onboard'],
  },
  {
    name: 'databricksUpdateScimUser',
    description: 'Replace a SCIM user resource.',
    tool: databricksUpdateScimUser,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['identity', 'edit'],
  },
  {
    name: 'databricksDeleteScimUser',
    description: 'Deprovision a workspace user.',
    tool: databricksDeleteScimUser,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['identity', 'offboard'],
  },
  {
    name: 'databricksListScimGroups',
    description: 'List workspace groups via SCIM.',
    tool: databricksListScimGroups,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['teams', 'identity'],
  },
  {
    name: 'databricksGetScimGroup',
    description: 'Get one SCIM group.',
    tool: databricksGetScimGroup,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['team', 'fetch'],
  },
  {
    name: 'databricksCreateScimGroup',
    description: 'Create a workspace group.',
    tool: databricksCreateScimGroup,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['team', 'provision'],
  },
  {
    name: 'databricksDeleteScimGroup',
    description: 'Delete a workspace group.',
    tool: databricksDeleteScimGroup,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['team', 'remove'],
  },
  {
    name: 'databricksGetScimMe',
    description: 'Get caller identity; verifies the token.',
    tool: databricksGetScimMe,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['identity', 'whoami', 'health'],
  },
  {
    name: 'databricksListTokens',
    description: 'List valid tokens (metadata only).',
    tool: databricksListTokens,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['pat', 'audit'],
  },
  {
    name: 'databricksCreateToken',
    description: 'Create a personal access token.',
    tool: databricksCreateToken,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['pat', 'generate'],
  },
  {
    name: 'databricksUpdateToken',
    description: 'Update a token comment or scopes.',
    tool: databricksUpdateToken,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['pat', 'edit'],
  },
  {
    name: 'databricksRevokeToken',
    description: 'Revoke a personal access token.',
    tool: databricksRevokeToken,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['pat', 'delete'],
  },
  {
    name: 'databricksListModels',
    description: 'List MLflow registered models.',
    tool: databricksListModels,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['ml', 'registry'],
  },
  {
    name: 'databricksGetModel',
    description: 'Get one registered model.',
    tool: databricksGetModel,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['ml', 'fetch'],
  },
  {
    name: 'databricksCreateModel',
    description: 'Create a registered model entry.',
    tool: databricksCreateModel,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['ml', 'register'],
  },
  {
    name: 'databricksDeleteModel',
    description: 'Delete a registered model.',
    tool: databricksDeleteModel,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['ml', 'remove'],
  },
  {
    name: 'databricksListModelVersions',
    description: 'List versions of a model.',
    tool: databricksListModelVersions,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['ml', 'releases'],
  },
  {
    name: 'databricksCreateModelVersion',
    description: 'Create a model version from a run.',
    tool: databricksCreateModelVersion,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['ml', 'publish'],
  },
  {
    name: 'databricksListServingEndpoints',
    description: 'List model serving endpoints.',
    tool: databricksListServingEndpoints,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['deploy', 'inference', 'llm'],
  },
  {
    name: 'databricksGetServingEndpoint',
    description: 'Get one serving endpoint.',
    tool: databricksGetServingEndpoint,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['deploy', 'fetch'],
  },
  {
    name: 'databricksQueryServingEndpoint',
    description: 'Invoke a serving endpoint for predictions.',
    tool: databricksQueryServingEndpoint,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['deploy', 'inference', 'chat'],
  },
];
