// @ts-nocheck
import {
  cloudinaryCreateAssetRelationsByAssetId,
  cloudinaryCreateAssetRelationsByPublicId,
  cloudinaryDeleteAssetRelationsByAssetId,
  cloudinaryDeleteAssetRelationsByPublicId,
  cloudinaryDeleteDerivedResources,
  cloudinaryDeleteResourcesByAssetId,
  cloudinaryDeleteResourcesByPublicId,
  cloudinaryDeleteResourcesByTags,
  cloudinaryDestroyAsset,
  cloudinaryDestroyAssetById,
  cloudinaryExplicitResource,
  cloudinaryGetResourceByAssetId,
  cloudinaryGetResourceByPublicId,
  cloudinaryGetResourcesByAssetFolder,
  cloudinaryGetResourcesByContext,
  cloudinaryGetResourcesInModeration,
  cloudinaryGetTags,
  cloudinaryListImages,
  cloudinaryListRawFiles,
  cloudinaryListResourceTypes,
  cloudinaryListResourcesByAssetIds,
  cloudinaryListResourcesByExternalIds,
  cloudinaryListResourcesByTag,
  cloudinaryListResourcesByType,
  cloudinaryListVideos,
  cloudinaryManageContext,
  cloudinaryPublishResources,
  cloudinaryRenameResource,
  cloudinaryRestoreResources,
  cloudinaryRestoreResourcesByAssetIds,
  cloudinaryUpdateAssetMetadata,
  cloudinaryUpdateResourceByAssetId,
  cloudinaryUpdateResourceByPublicId,
  cloudinaryUpdateResourceTags,
} from './resources.js';
import {
  cloudinaryCreateImageFromText,
  cloudinaryCreateMultiResource,
  cloudinaryCreateSlideshow,
  cloudinaryExplodeResource,
  cloudinaryGenerateArchive,
  cloudinaryGenerateSprite,
  cloudinaryUploadAsset,
  cloudinaryUploadChunk,
  cloudinaryUploadFileAutoDetect,
} from './upload.js';
import {
  cloudinaryCreateFolder,
  cloudinaryDeleteFolder,
  cloudinaryGetRootFolders,
  cloudinarySearchFolders,
  cloudinaryShowFolder,
  cloudinaryUpdateFolder,
} from './folders.js';
import { cloudinarySearchAssets, cloudinarySearchVisualAssets } from './search.js';
import {
  cloudinaryCreateMetadataField,
  cloudinaryCreateMetadataRule,
  cloudinaryDeleteMetadataField,
  cloudinaryDeleteMetadataFieldDatasourceEntries,
  cloudinaryDeleteMetadataRule,
  cloudinaryGetMetadataFieldById,
  cloudinaryListMetadataFields,
  cloudinaryListMetadataRules,
  cloudinaryOrderMetadataFieldDatasource,
  cloudinaryReorderMetadataField,
  cloudinaryReorderMetadataFields,
  cloudinaryRestoreMetadataFieldDatasourceEntries,
  cloudinarySearchDatasourceInMetadataField,
  cloudinarySearchMetadataFieldDatasource,
  cloudinaryUpdateMetadataField,
  cloudinaryUpdateMetadataFieldDatasource,
  cloudinaryUpdateMetadataRule,
} from './metadata.js';
import {
  cloudinaryCreateStreamingProfile,
  cloudinaryCreateTransformation,
  cloudinaryDeleteStreamingProfile,
  cloudinaryDeleteTransformation,
  cloudinaryGetStreamingProfileDetails,
  cloudinaryGetStreamingProfiles,
  cloudinaryGetTransformation,
  cloudinaryGetTransformations,
  cloudinaryUpdateStreamingProfile,
  cloudinaryUpdateTransformation,
} from './transformations.js';
import {
  cloudinaryCreateTrigger,
  cloudinaryCreateUploadMapping,
  cloudinaryCreateUploadPreset,
  cloudinaryDeleteTrigger,
  cloudinaryDeleteUploadMapping,
  cloudinaryDeleteUploadPreset,
  cloudinaryGetAnalysisTaskStatus,
  cloudinaryGetConfig,
  cloudinaryGetTriggers,
  cloudinaryGetUploadMappingDetails,
  cloudinaryGetUploadMappings,
  cloudinaryGetUploadPreset,
  cloudinaryGetUsage,
  cloudinaryGetVideoViews,
  cloudinaryListUploadPresets,
  cloudinaryPing,
  cloudinaryUpdateTrigger,
  cloudinaryUpdateUploadMapping,
  cloudinaryUpdateUploadPreset,
} from './config.js';
import {
  cloudinaryActivateLiveStream,
  cloudinaryCreateLiveStream,
  cloudinaryCreateLiveStreamOutput,
  cloudinaryDeleteLiveStream,
  cloudinaryDeleteLiveStreamOutput,
  cloudinaryGetLiveStream,
  cloudinaryGetLiveStreamOutput,
  cloudinaryGetLiveStreamOutputs,
  cloudinaryGetLiveStreams,
  cloudinaryIdleLiveStream,
  cloudinaryUpdateLiveStream,
  cloudinaryUpdateLiveStreamOutput,
} from './livestreams.js';

export {
  cloudinaryCreateAssetRelationsByAssetId,
  cloudinaryCreateAssetRelationsByPublicId,
  cloudinaryDeleteAssetRelationsByAssetId,
  cloudinaryDeleteAssetRelationsByPublicId,
  cloudinaryDeleteDerivedResources,
  cloudinaryDeleteResourcesByAssetId,
  cloudinaryDeleteResourcesByPublicId,
  cloudinaryDeleteResourcesByTags,
  cloudinaryDestroyAsset,
  cloudinaryDestroyAssetById,
  cloudinaryExplicitResource,
  cloudinaryGetResourceByAssetId,
  cloudinaryGetResourceByPublicId,
  cloudinaryGetResourcesByAssetFolder,
  cloudinaryGetResourcesByContext,
  cloudinaryGetResourcesInModeration,
  cloudinaryGetTags,
  cloudinaryListImages,
  cloudinaryListRawFiles,
  cloudinaryListResourceTypes,
  cloudinaryListResourcesByAssetIds,
  cloudinaryListResourcesByExternalIds,
  cloudinaryListResourcesByTag,
  cloudinaryListResourcesByType,
  cloudinaryListVideos,
  cloudinaryManageContext,
  cloudinaryPublishResources,
  cloudinaryRenameResource,
  cloudinaryRestoreResources,
  cloudinaryRestoreResourcesByAssetIds,
  cloudinaryUpdateAssetMetadata,
  cloudinaryUpdateResourceByAssetId,
  cloudinaryUpdateResourceByPublicId,
  cloudinaryUpdateResourceTags,
  cloudinaryCreateImageFromText,
  cloudinaryCreateMultiResource,
  cloudinaryCreateSlideshow,
  cloudinaryExplodeResource,
  cloudinaryGenerateArchive,
  cloudinaryGenerateSprite,
  cloudinaryUploadAsset,
  cloudinaryUploadChunk,
  cloudinaryUploadFileAutoDetect,
  cloudinaryCreateFolder,
  cloudinaryDeleteFolder,
  cloudinaryGetRootFolders,
  cloudinarySearchFolders,
  cloudinaryShowFolder,
  cloudinaryUpdateFolder,
  cloudinarySearchAssets,
  cloudinarySearchVisualAssets,
  cloudinaryCreateMetadataField,
  cloudinaryCreateMetadataRule,
  cloudinaryDeleteMetadataField,
  cloudinaryDeleteMetadataFieldDatasourceEntries,
  cloudinaryDeleteMetadataRule,
  cloudinaryGetMetadataFieldById,
  cloudinaryListMetadataFields,
  cloudinaryListMetadataRules,
  cloudinaryOrderMetadataFieldDatasource,
  cloudinaryReorderMetadataField,
  cloudinaryReorderMetadataFields,
  cloudinaryRestoreMetadataFieldDatasourceEntries,
  cloudinarySearchDatasourceInMetadataField,
  cloudinarySearchMetadataFieldDatasource,
  cloudinaryUpdateMetadataField,
  cloudinaryUpdateMetadataFieldDatasource,
  cloudinaryUpdateMetadataRule,
  cloudinaryCreateStreamingProfile,
  cloudinaryCreateTransformation,
  cloudinaryDeleteStreamingProfile,
  cloudinaryDeleteTransformation,
  cloudinaryGetStreamingProfileDetails,
  cloudinaryGetStreamingProfiles,
  cloudinaryGetTransformation,
  cloudinaryGetTransformations,
  cloudinaryUpdateStreamingProfile,
  cloudinaryUpdateTransformation,
  cloudinaryCreateTrigger,
  cloudinaryCreateUploadMapping,
  cloudinaryCreateUploadPreset,
  cloudinaryDeleteTrigger,
  cloudinaryDeleteUploadMapping,
  cloudinaryDeleteUploadPreset,
  cloudinaryGetAnalysisTaskStatus,
  cloudinaryGetConfig,
  cloudinaryGetTriggers,
  cloudinaryGetUploadMappingDetails,
  cloudinaryGetUploadMappings,
  cloudinaryGetUploadPreset,
  cloudinaryGetUsage,
  cloudinaryGetVideoViews,
  cloudinaryListUploadPresets,
  cloudinaryPing,
  cloudinaryUpdateTrigger,
  cloudinaryUpdateUploadMapping,
  cloudinaryUpdateUploadPreset,
  cloudinaryActivateLiveStream,
  cloudinaryCreateLiveStream,
  cloudinaryCreateLiveStreamOutput,
  cloudinaryDeleteLiveStream,
  cloudinaryDeleteLiveStreamOutput,
  cloudinaryGetLiveStream,
  cloudinaryGetLiveStreamOutput,
  cloudinaryGetLiveStreamOutputs,
  cloudinaryGetLiveStreams,
  cloudinaryIdleLiveStream,
  cloudinaryUpdateLiveStream,
  cloudinaryUpdateLiveStreamOutput,
};

const auth = 'cloudinaryCredentials' as const;

type Scope = 'read' | 'write' | 'delete';
function entry(
  name: string,
  description: string,
  toolRef: any,
  scope: Scope,
  keywords: string[],
): {
  name: string;
  description: string;
  tool: any;
  requiredAuth: typeof auth;
  scope: Scope;
  keywords: string[];
} {
  return { name, description, tool: toolRef, requiredAuth: auth, scope, keywords };
}

export const cloudinaryTools = [
  entry(
    'cloudinaryGetResourceByAssetId',
    'Get full details of an asset by its immutable asset ID.',
    cloudinaryGetResourceByAssetId,
    'read',
    ['lookup', 'details', 'derived'],
  ),
  entry(
    'cloudinaryGetResourceByPublicId',
    'Get details of a single asset by public ID.',
    cloudinaryGetResourceByPublicId,
    'read',
    ['lookup', 'details'],
  ),
  entry(
    'cloudinaryGetResourcesByAssetFolder',
    'List assets stored directly in an asset folder.',
    cloudinaryGetResourcesByAssetFolder,
    'read',
    ['directory', 'browse'],
  ),
  entry(
    'cloudinaryGetResourcesByContext',
    'Find assets by contextual metadata key/value.',
    cloudinaryGetResourcesByContext,
    'read',
    ['filter', 'alt text', 'caption'],
  ),
  entry(
    'cloudinaryGetResourcesInModeration',
    'List assets in a moderation queue by kind and status.',
    cloudinaryGetResourcesInModeration,
    'read',
    ['pending review', 'approval queue'],
  ),
  entry('cloudinaryGetTags', 'List all tags used by a resource type.', cloudinaryGetTags, 'read', [
    'labels',
    'tag list',
  ]),
  entry(
    'cloudinaryListImages',
    'List image assets with prefix, tag, or date filtering.',
    cloudinaryListImages,
    'read',
    ['photos', 'pictures', 'browse'],
  ),
  entry(
    'cloudinaryListVideos',
    'List video and audio assets with filtering.',
    cloudinaryListVideos,
    'read',
    ['movies', 'clips', 'media'],
  ),
  entry(
    'cloudinaryListRawFiles',
    'List raw (non-media file) assets with filtering.',
    cloudinaryListRawFiles,
    'read',
    ['documents', 'pdfs', 'files'],
  ),
  entry(
    'cloudinaryListResourcesByAssetIds',
    'Fetch up to 100 assets by immutable asset IDs.',
    cloudinaryListResourcesByAssetIds,
    'read',
    ['bulk fetch', 'batch lookup'],
  ),
  entry(
    'cloudinaryListResourcesByExternalIds',
    'Fetch assets by external IDs assigned at upload.',
    cloudinaryListResourcesByExternalIds,
    'read',
    ['bulk fetch', 'foreign keys'],
  ),
  entry(
    'cloudinaryListResourcesByTag',
    'List assets carrying a specific tag.',
    cloudinaryListResourcesByTag,
    'read',
    ['labeled', 'tagged media'],
  ),
  entry(
    'cloudinaryListResourcesByType',
    'List all assets of a resource and delivery type.',
    cloudinaryListResourcesByType,
    'read',
    ['inventory', 'catalog'],
  ),
  entry(
    'cloudinaryListResourceTypes',
    'List resource types available in the environment.',
    cloudinaryListResourceTypes,
    'read',
    ['kinds', 'categories'],
  ),
  entry(
    'cloudinaryUpdateResourceByPublicId',
    'Update tags, context, metadata, or moderation on an asset by public ID.',
    cloudinaryUpdateResourceByPublicId,
    'write',
    ['edit', 'annotate', 'moderate'],
  ),
  entry(
    'cloudinaryUpdateResourceByAssetId',
    'Update an asset by immutable asset ID.',
    cloudinaryUpdateResourceByAssetId,
    'write',
    ['edit', 'annotate'],
  ),
  entry(
    'cloudinaryUpdateResourceTags',
    'Add, remove, replace, or clear tags on assets.',
    cloudinaryUpdateResourceTags,
    'write',
    ['label', 'retag'],
  ),
  entry(
    'cloudinaryManageContext',
    'Add/update or remove all contextual metadata on assets.',
    cloudinaryManageContext,
    'write',
    ['alt text', 'captions'],
  ),
  entry(
    'cloudinaryUpdateAssetMetadata',
    'Set structured metadata field values on assets.',
    cloudinaryUpdateAssetMetadata,
    'write',
    ['custom fields', 'attributes'],
  ),
  entry(
    'cloudinaryRenameResource',
    'Rename an asset public ID (reorganize without re-uploading).',
    cloudinaryRenameResource,
    'write',
    ['move', 'relocate', 'repath'],
  ),
  entry(
    'cloudinaryDestroyAsset',
    'Permanently destroy one asset by public ID.',
    cloudinaryDestroyAsset,
    'delete',
    ['remove', 'erase'],
  ),
  entry(
    'cloudinaryDestroyAssetById',
    'Permanently delete one asset by immutable asset ID.',
    cloudinaryDestroyAssetById,
    'delete',
    ['remove', 'erase'],
  ),
  entry(
    'cloudinaryDeleteResourcesByPublicId',
    'Bulk delete assets by IDs, prefix, or all of a type.',
    cloudinaryDeleteResourcesByPublicId,
    'delete',
    ['bulk remove', 'purge', 'wipe'],
  ),
  entry(
    'cloudinaryDeleteResourcesByAssetId',
    'Bulk delete up to 100 assets by asset IDs.',
    cloudinaryDeleteResourcesByAssetId,
    'delete',
    ['bulk remove'],
  ),
  entry(
    'cloudinaryDeleteResourcesByTags',
    'Delete all assets carrying a tag.',
    cloudinaryDeleteResourcesByTags,
    'delete',
    ['purge label'],
  ),
  entry(
    'cloudinaryDeleteDerivedResources',
    'Delete derived (transformed) assets by derived IDs.',
    cloudinaryDeleteDerivedResources,
    'delete',
    ['clear variants', 'thumbnails'],
  ),
  entry(
    'cloudinaryRestoreResources',
    'Restore deleted assets with backups by public ID.',
    cloudinaryRestoreResources,
    'write',
    ['undelete', 'recover', 'backup'],
  ),
  entry(
    'cloudinaryRestoreResourcesByAssetIds',
    'Restore backed-up assets by asset IDs.',
    cloudinaryRestoreResourcesByAssetIds,
    'write',
    ['undelete', 'recover'],
  ),
  entry(
    'cloudinaryPublishResources',
    'Make private/authenticated assets publicly accessible.',
    cloudinaryPublishResources,
    'write',
    ['unprivate', 'release', 'go public'],
  ),
  entry(
    'cloudinaryExplicitResource',
    'Update an asset and eagerly generate transformations (not rate-limited).',
    cloudinaryExplicitResource,
    'write',
    ['pregenerate', 'warm cache'],
  ),
  entry(
    'cloudinaryCreateAssetRelationsByPublicId',
    'Relate up to 10 assets to a primary asset by public ID.',
    cloudinaryCreateAssetRelationsByPublicId,
    'write',
    ['link', 'associate', 'bundle'],
  ),
  entry(
    'cloudinaryCreateAssetRelationsByAssetId',
    'Relate up to 10 assets by immutable asset IDs.',
    cloudinaryCreateAssetRelationsByAssetId,
    'write',
    ['link', 'associate'],
  ),
  entry(
    'cloudinaryDeleteAssetRelationsByPublicId',
    'Unrelate assets from a primary asset by public ID.',
    cloudinaryDeleteAssetRelationsByPublicId,
    'delete',
    ['unlink', 'detach'],
  ),
  entry(
    'cloudinaryDeleteAssetRelationsByAssetId',
    'Unrelate assets by immutable asset IDs.',
    cloudinaryDeleteAssetRelationsByAssetId,
    'delete',
    ['unlink', 'detach'],
  ),
  entry(
    'cloudinaryUploadAsset',
    'Upload an image, video, or raw file from URL or base64.',
    cloudinaryUploadAsset,
    'write',
    ['add media', 'ingest', 'import'],
  ),
  entry(
    'cloudinaryUploadFileAutoDetect',
    'Upload any file with automatic type detection and full options.',
    cloudinaryUploadFileAutoDetect,
    'write',
    ['ingest', 'import file'],
  ),
  entry(
    'cloudinaryUploadChunk',
    'Upload one chunk of a large file (resumable uploads).',
    cloudinaryUploadChunk,
    'write',
    ['multipart', 'large file', 'resume'],
  ),
  entry(
    'cloudinaryCreateImageFromText',
    'Generate a styled text image (banners, captions).',
    cloudinaryCreateImageFromText,
    'write',
    ['typography', 'title card', 'banner'],
  ),
  entry(
    'cloudinaryCreateMultiResource',
    'Combine images into animated GIF/MP4 or PDF.',
    cloudinaryCreateMultiResource,
    'write',
    ['animation', 'slideshow gif'],
  ),
  entry(
    'cloudinaryCreateSlideshow',
    'Generate a video slideshow from assets via manifest JSON.',
    cloudinaryCreateSlideshow,
    'write',
    ['montage', 'presentation video'],
  ),
  entry(
    'cloudinaryGenerateSprite',
    'Merge images into a CSS sprite sheet (deprecated upstream).',
    cloudinaryGenerateSprite,
    'write',
    ['spritesheet', 'css icons'],
  ),
  entry(
    'cloudinaryGenerateArchive',
    'Bundle assets into a ZIP/TGZ archive.',
    cloudinaryGenerateArchive,
    'write',
    ['download bundle', 'export zip', 'backup'],
  ),
  entry(
    'cloudinaryExplodeResource',
    'Split a multi-page PDF/PSD/TIFF/GIF into per-page images.',
    cloudinaryExplodeResource,
    'write',
    ['extract pages', 'burst pdf'],
  ),
  entry(
    'cloudinaryGetRootFolders',
    'List top-level asset folders.',
    cloudinaryGetRootFolders,
    'read',
    ['directories', 'top folders'],
  ),
  entry('cloudinaryShowFolder', 'List subfolders inside a folder.', cloudinaryShowFolder, 'read', [
    'explore',
    'children',
    'nested',
  ]),
  entry(
    'cloudinaryCreateFolder',
    'Create a new asset folder path.',
    cloudinaryCreateFolder,
    'write',
    ['new directory', 'mkdir'],
  ),
  entry(
    'cloudinaryUpdateFolder',
    'Rename or move an asset folder.',
    cloudinaryUpdateFolder,
    'write',
    ['relocate directory'],
  ),
  entry(
    'cloudinaryDeleteFolder',
    'Delete a folder (must be empty).',
    cloudinaryDeleteFolder,
    'delete',
    ['remove directory', 'rmdir'],
  ),
  entry(
    'cloudinarySearchFolders',
    'Search folders by name, path, or creation date.',
    cloudinarySearchFolders,
    'read',
    ['find directory'],
  ),
  entry(
    'cloudinarySearchAssets',
    'Search assets with Lucene-like expressions.',
    cloudinarySearchAssets,
    'read',
    ['find media', 'query', 'filter'],
  ),
  entry(
    'cloudinarySearchVisualAssets',
    'Find visually similar images by example or text.',
    cloudinarySearchVisualAssets,
    'read',
    ['reverse image', 'similar photos', 'semantic'],
  ),
  entry(
    'cloudinaryListMetadataFields',
    'List structured metadata field definitions.',
    cloudinaryListMetadataFields,
    'read',
    ['schema', 'custom fields'],
  ),
  entry(
    'cloudinaryGetMetadataFieldById',
    'Get one metadata field definition by external ID.',
    cloudinaryGetMetadataFieldById,
    'read',
    ['field details', 'schema info'],
  ),
  entry(
    'cloudinaryCreateMetadataField',
    'Create a structured metadata field.',
    cloudinaryCreateMetadataField,
    'write',
    ['new attribute', 'schema field'],
  ),
  entry(
    'cloudinaryUpdateMetadataField',
    'Partially update a metadata field definition.',
    cloudinaryUpdateMetadataField,
    'write',
    ['edit schema'],
  ),
  entry(
    'cloudinaryDeleteMetadataField',
    'Delete a metadata field definition.',
    cloudinaryDeleteMetadataField,
    'delete',
    ['remove attribute'],
  ),
  entry(
    'cloudinaryUpdateMetadataFieldDatasource',
    'Update enum/set datasource entries.',
    cloudinaryUpdateMetadataFieldDatasource,
    'write',
    ['dropdown values', 'options'],
  ),
  entry(
    'cloudinaryDeleteMetadataFieldDatasourceEntries',
    'Soft-delete datasource entries (inactivate).',
    cloudinaryDeleteMetadataFieldDatasourceEntries,
    'delete',
    ['disable options'],
  ),
  entry(
    'cloudinaryRestoreMetadataFieldDatasourceEntries',
    'Reactivate soft-deleted datasource entries.',
    cloudinaryRestoreMetadataFieldDatasourceEntries,
    'write',
    ['reenable options'],
  ),
  entry(
    'cloudinaryOrderMetadataFieldDatasource',
    'Sort an enum/set datasource by value.',
    cloudinaryOrderMetadataFieldDatasource,
    'write',
    ['alphabetize options'],
  ),
  entry(
    'cloudinarySearchDatasourceInMetadataField',
    'Search values inside one field datasource.',
    cloudinarySearchDatasourceInMetadataField,
    'read',
    ['find option'],
  ),
  entry(
    'cloudinarySearchMetadataFieldDatasource',
    'Search datasource values across all fields.',
    cloudinarySearchMetadataFieldDatasource,
    'read',
    ['global option lookup'],
  ),
  entry(
    'cloudinaryReorderMetadataField',
    'Move one metadata field to a new position.',
    cloudinaryReorderMetadataField,
    'write',
    ['rearrange schema'],
  ),
  entry(
    'cloudinaryReorderMetadataFields',
    'Reorder all metadata fields by label, date, or ID.',
    cloudinaryReorderMetadataFields,
    'write',
    ['sort schema'],
  ),
  entry(
    'cloudinaryListMetadataRules',
    'List conditional metadata rules.',
    cloudinaryListMetadataRules,
    'read',
    ['autofill rules', 'dependencies'],
  ),
  entry(
    'cloudinaryCreateMetadataRule',
    'Create a conditional metadata auto-fill rule.',
    cloudinaryCreateMetadataRule,
    'write',
    ['automation', 'dependency'],
  ),
  entry(
    'cloudinaryUpdateMetadataRule',
    'Update a conditional metadata rule.',
    cloudinaryUpdateMetadataRule,
    'write',
    ['edit automation'],
  ),
  entry(
    'cloudinaryDeleteMetadataRule',
    'Delete a conditional metadata rule.',
    cloudinaryDeleteMetadataRule,
    'delete',
    ['remove automation'],
  ),
  entry(
    'cloudinaryGetTransformations',
    'List named and unnamed transformations.',
    cloudinaryGetTransformations,
    'read',
    ['presets list', 'effects catalog'],
  ),
  entry(
    'cloudinaryGetTransformation',
    'Get a transformation definition and usage.',
    cloudinaryGetTransformation,
    'read',
    ['effect details'],
  ),
  entry(
    'cloudinaryCreateTransformation',
    'Save a reusable named transformation.',
    cloudinaryCreateTransformation,
    'write',
    ['new effect', 'saved resize'],
  ),
  entry(
    'cloudinaryUpdateTransformation',
    'Update a named transformation definition.',
    cloudinaryUpdateTransformation,
    'write',
    ['edit effect'],
  ),
  entry(
    'cloudinaryDeleteTransformation',
    'Delete a named transformation.',
    cloudinaryDeleteTransformation,
    'delete',
    ['remove effect'],
  ),
  entry(
    'cloudinaryGetStreamingProfiles',
    'List adaptive streaming profiles for HLS/DASH.',
    cloudinaryGetStreamingProfiles,
    'read',
    ['abr', 'renditions'],
  ),
  entry(
    'cloudinaryGetStreamingProfileDetails',
    'Inspect one streaming profile configuration.',
    cloudinaryGetStreamingProfileDetails,
    'read',
    ['abr details'],
  ),
  entry(
    'cloudinaryCreateStreamingProfile',
    'Create a custom adaptive-bitrate profile.',
    cloudinaryCreateStreamingProfile,
    'write',
    ['new abr', 'quality ladder'],
  ),
  entry(
    'cloudinaryUpdateStreamingProfile',
    'Update a streaming profile renditions.',
    cloudinaryUpdateStreamingProfile,
    'write',
    ['edit abr'],
  ),
  entry(
    'cloudinaryDeleteStreamingProfile',
    'Delete a custom streaming profile.',
    cloudinaryDeleteStreamingProfile,
    'delete',
    ['remove abr'],
  ),
  entry(
    'cloudinaryPing',
    'Ping Cloudinary to verify credentials and reachability.',
    cloudinaryPing,
    'read',
    ['health check', 'connectivity', 'auth test'],
  ),
  entry(
    'cloudinaryGetUsage',
    'Get storage, bandwidth, and quota usage vs limits.',
    cloudinaryGetUsage,
    'read',
    ['quotas', 'billing', 'limits', 'credits'],
  ),
  entry(
    'cloudinaryGetConfig',
    'Get environment config including folder mode.',
    cloudinaryGetConfig,
    'read',
    ['settings', 'environment info'],
  ),
  entry(
    'cloudinaryGetTriggers',
    'List webhook triggers by event type.',
    cloudinaryGetTriggers,
    'read',
    ['webhooks', 'notifications', 'subscriptions'],
  ),
  entry(
    'cloudinaryCreateTrigger',
    'Create a webhook trigger for an event type.',
    cloudinaryCreateTrigger,
    'write',
    ['subscribe', 'notify url'],
  ),
  entry(
    'cloudinaryUpdateTrigger',
    'Change a trigger notification URL.',
    cloudinaryUpdateTrigger,
    'write',
    ['edit webhook'],
  ),
  entry('cloudinaryDeleteTrigger', 'Delete a webhook trigger.', cloudinaryDeleteTrigger, 'delete', [
    'unsubscribe',
  ]),
  entry(
    'cloudinaryListUploadPresets',
    'List upload presets with sorting and pagination.',
    cloudinaryListUploadPresets,
    'read',
    ['preset catalog'],
  ),
  entry(
    'cloudinaryGetUploadPreset',
    'Get one upload preset configuration.',
    cloudinaryGetUploadPreset,
    'read',
    ['preset details'],
  ),
  entry(
    'cloudinaryCreateUploadPreset',
    'Create an upload preset with centralized defaults.',
    cloudinaryCreateUploadPreset,
    'write',
    ['new preset', 'upload defaults'],
  ),
  entry(
    'cloudinaryUpdateUploadPreset',
    'Update an upload preset settings.',
    cloudinaryUpdateUploadPreset,
    'write',
    ['edit preset'],
  ),
  entry(
    'cloudinaryDeleteUploadPreset',
    'Delete an upload preset.',
    cloudinaryDeleteUploadPreset,
    'delete',
    ['remove preset'],
  ),
  entry(
    'cloudinaryGetUploadMappings',
    'List URL-prefix to folder upload mappings.',
    cloudinaryGetUploadMappings,
    'read',
    ['fetch mappings'],
  ),
  entry(
    'cloudinaryGetUploadMappingDetails',
    'Get the URL template mapped to one folder.',
    cloudinaryGetUploadMappingDetails,
    'read',
    ['mapping info'],
  ),
  entry(
    'cloudinaryCreateUploadMapping',
    'Map an external URL prefix to a folder.',
    cloudinaryCreateUploadMapping,
    'write',
    ['new mapping', 'fetch prefix'],
  ),
  entry(
    'cloudinaryUpdateUploadMapping',
    'Change a mapping URL template.',
    cloudinaryUpdateUploadMapping,
    'write',
    ['edit mapping'],
  ),
  entry(
    'cloudinaryDeleteUploadMapping',
    'Delete a folder upload mapping.',
    cloudinaryDeleteUploadMapping,
    'delete',
    ['remove mapping'],
  ),
  entry(
    'cloudinaryGetVideoViews',
    'Get video player analytics views and engagement.',
    cloudinaryGetVideoViews,
    'read',
    ['watch stats', 'viewer metrics', 'analytics'],
  ),
  entry(
    'cloudinaryGetAnalysisTaskStatus',
    'Poll an async AI analysis task to completion.',
    cloudinaryGetAnalysisTaskStatus,
    'read',
    ['job status', 'ai results'],
  ),
  entry('cloudinaryGetLiveStreams', 'List all live streams.', cloudinaryGetLiveStreams, 'read', [
    'broadcasts',
    'channels',
  ]),
  entry(
    'cloudinaryGetLiveStream',
    'Get one live stream configuration and status.',
    cloudinaryGetLiveStream,
    'read',
    ['broadcast details'],
  ),
  entry(
    'cloudinaryCreateLiveStream',
    'Create an RTMP live stream (returns ingest URI and key).',
    cloudinaryCreateLiveStream,
    'write',
    ['go live', 'new broadcast', 'rtmp'],
  ),
  entry(
    'cloudinaryUpdateLiveStream',
    'Update a live stream name or timeouts.',
    cloudinaryUpdateLiveStream,
    'write',
    ['edit broadcast'],
  ),
  entry(
    'cloudinaryDeleteLiveStream',
    'Permanently delete a live stream.',
    cloudinaryDeleteLiveStream,
    'delete',
    ['remove broadcast', 'end channel'],
  ),
  entry(
    'cloudinaryActivateLiveStream',
    'Manually activate an idle live stream.',
    cloudinaryActivateLiveStream,
    'write',
    ['start broadcast'],
  ),
  entry(
    'cloudinaryIdleLiveStream',
    'Park an active live stream in idle state.',
    cloudinaryIdleLiveStream,
    'write',
    ['pause broadcast', 'standby'],
  ),
  entry(
    'cloudinaryGetLiveStreamOutputs',
    'List outputs configured on a live stream.',
    cloudinaryGetLiveStreamOutputs,
    'read',
    ['destinations', 'simulcasts'],
  ),
  entry(
    'cloudinaryGetLiveStreamOutput',
    'Get one live stream output configuration.',
    cloudinaryGetLiveStreamOutput,
    'read',
    ['destination details'],
  ),
  entry(
    'cloudinaryCreateLiveStreamOutput',
    'Add HLS/archive/simulcast output to a stream.',
    cloudinaryCreateLiveStreamOutput,
    'write',
    ['multistream', 'restream'],
  ),
  entry(
    'cloudinaryUpdateLiveStreamOutput',
    'Update a custom simulcast output.',
    cloudinaryUpdateLiveStreamOutput,
    'write',
    ['edit destination'],
  ),
  entry(
    'cloudinaryDeleteLiveStreamOutput',
    'Remove an output from a live stream.',
    cloudinaryDeleteLiveStreamOutput,
    'delete',
    ['remove destination'],
  ),
];
