// @ts-nocheck
import {
  zendeskListTickets,
  zendeskGetTicket,
  zendeskCreateTicket,
  zendeskUpdateTicket,
  zendeskDeleteTicket,
  zendeskCreateManyTickets,
  zendeskUpdateManyTickets,
  zendeskDeleteManyTickets,
  zendeskMergeTickets,
  zendeskImportTicket,
  zendeskImportManyTickets,
  zendeskListTicketComments,
  zendeskRedactComment,
  zendeskListTicketAudits,
  zendeskGetTicketAudit,
  zendeskTrustTicketAudit,
  zendeskGetTicketMetrics,
  zendeskCountTickets,
  zendeskListTicketFields,
  zendeskGetTicketField,
  zendeskCreateTicketField,
  zendeskUpdateTicketField,
  zendeskDeleteTicketField,
  zendeskListTicketForms,
  zendeskGetTicketForm,
  zendeskCreateTicketForm,
  zendeskUpdateTicketForm,
  zendeskDeleteTicketForm,
  zendeskSearch,
  zendeskExportSearch,
} from './tickets.js';
import {
  zendeskListUsers,
  zendeskGetUser,
  zendeskGetCurrentUser,
  zendeskCreateUser,
  zendeskUpdateUser,
  zendeskDeleteUser,
  zendeskCreateManyUsers,
  zendeskUpdateManyUsers,
  zendeskDeleteManyUsers,
  zendeskSearchUsers,
  zendeskShowManyUsers,
  zendeskListUserTickets,
  zendeskListUserIdentities,
  zendeskCreateUserIdentity,
  zendeskMakeIdentityPrimary,
  zendeskVerifyUserIdentity,
  zendeskDeleteUserIdentity,
  zendeskListUserGroupMemberships,
  zendeskAssignUserToGroup,
  zendeskMakeGroupMembershipDefault,
  zendeskDeleteGroupMembership,
} from './users.js';
import {
  zendeskListOrganizations,
  zendeskGetOrganization,
  zendeskCreateOrganization,
  zendeskUpdateOrganization,
  zendeskDeleteOrganization,
  zendeskCreateManyOrganizations,
  zendeskUpdateManyOrganizations,
  zendeskDeleteManyOrganizations,
  zendeskListOrganizationMemberships,
  zendeskCreateOrganizationMembership,
  zendeskMakeOrganizationMembershipDefault,
  zendeskDeleteOrganizationMembership,
  zendeskListOrganizationTags,
  zendeskSetOrganizationTags,
  zendeskAddOrganizationTags,
  zendeskRemoveOrganizationTags,
  zendeskListGroups,
  zendeskListAssignableGroups,
  zendeskGetGroup,
  zendeskCreateGroup,
  zendeskUpdateGroup,
  zendeskDeleteGroup,
} from './orgs.js';
import {
  zendeskListViews,
  zendeskListActiveViews,
  zendeskGetView,
  zendeskCreateView,
  zendeskUpdateView,
  zendeskDeleteView,
  zendeskExecuteView,
  zendeskPreviewView,
  zendeskCountViews,
  zendeskListMacros,
  zendeskGetMacro,
  zendeskCreateMacro,
  zendeskUpdateMacro,
  zendeskDeleteMacro,
  zendeskApplyMacro,
  zendeskListMacroCategories,
  zendeskListTriggers,
  zendeskGetTrigger,
  zendeskCreateTrigger,
  zendeskUpdateTrigger,
  zendeskDeleteTrigger,
  zendeskReorderTriggers,
  zendeskGetTriggerDefinitions,
  zendeskListAutomations,
  zendeskGetAutomation,
  zendeskCreateAutomation,
  zendeskUpdateAutomation,
  zendeskDeleteAutomation,
  zendeskReorderAutomations,
  zendeskGetAutomationDefinitions,
} from './rules.js';
import {
  zendeskListSatisfactionRatings,
  zendeskGetSatisfactionRating,
  zendeskListSatisfactionReasons,
  zendeskUploadAttachment,
  zendeskDeleteUpload,
  zendeskListJobStatuses,
  zendeskGetJobStatus,
  zendeskListLocales,
  zendeskListBrands,
  zendeskGetBrand,
  zendeskListSlaPolicies,
  zendeskGetSlaPolicy,
  zendeskListWebhooks,
  zendeskGetWebhook,
  zendeskCreateWebhook,
  zendeskUpdateWebhook,
  zendeskDeleteWebhook,
  zendeskTestWebhook,
  zendeskListWebhookInvocations,
  zendeskGetWebhookSigningSecret,
  zendeskResetWebhookSigningSecret,
} from './support.js';

export {
  zendeskListTickets,
  zendeskGetTicket,
  zendeskCreateTicket,
  zendeskUpdateTicket,
  zendeskDeleteTicket,
  zendeskCreateManyTickets,
  zendeskUpdateManyTickets,
  zendeskDeleteManyTickets,
  zendeskMergeTickets,
  zendeskImportTicket,
  zendeskImportManyTickets,
  zendeskListTicketComments,
  zendeskRedactComment,
  zendeskListTicketAudits,
  zendeskGetTicketAudit,
  zendeskTrustTicketAudit,
  zendeskGetTicketMetrics,
  zendeskCountTickets,
  zendeskListTicketFields,
  zendeskGetTicketField,
  zendeskCreateTicketField,
  zendeskUpdateTicketField,
  zendeskDeleteTicketField,
  zendeskListTicketForms,
  zendeskGetTicketForm,
  zendeskCreateTicketForm,
  zendeskUpdateTicketForm,
  zendeskDeleteTicketForm,
  zendeskSearch,
  zendeskExportSearch,
  zendeskListUsers,
  zendeskGetUser,
  zendeskGetCurrentUser,
  zendeskCreateUser,
  zendeskUpdateUser,
  zendeskDeleteUser,
  zendeskCreateManyUsers,
  zendeskUpdateManyUsers,
  zendeskDeleteManyUsers,
  zendeskSearchUsers,
  zendeskShowManyUsers,
  zendeskListUserTickets,
  zendeskListUserIdentities,
  zendeskCreateUserIdentity,
  zendeskMakeIdentityPrimary,
  zendeskVerifyUserIdentity,
  zendeskDeleteUserIdentity,
  zendeskListUserGroupMemberships,
  zendeskAssignUserToGroup,
  zendeskMakeGroupMembershipDefault,
  zendeskDeleteGroupMembership,
  zendeskListOrganizations,
  zendeskGetOrganization,
  zendeskCreateOrganization,
  zendeskUpdateOrganization,
  zendeskDeleteOrganization,
  zendeskCreateManyOrganizations,
  zendeskUpdateManyOrganizations,
  zendeskDeleteManyOrganizations,
  zendeskListOrganizationMemberships,
  zendeskCreateOrganizationMembership,
  zendeskMakeOrganizationMembershipDefault,
  zendeskDeleteOrganizationMembership,
  zendeskListOrganizationTags,
  zendeskSetOrganizationTags,
  zendeskAddOrganizationTags,
  zendeskRemoveOrganizationTags,
  zendeskListGroups,
  zendeskListAssignableGroups,
  zendeskGetGroup,
  zendeskCreateGroup,
  zendeskUpdateGroup,
  zendeskDeleteGroup,
  zendeskListViews,
  zendeskListActiveViews,
  zendeskGetView,
  zendeskCreateView,
  zendeskUpdateView,
  zendeskDeleteView,
  zendeskExecuteView,
  zendeskPreviewView,
  zendeskCountViews,
  zendeskListMacros,
  zendeskGetMacro,
  zendeskCreateMacro,
  zendeskUpdateMacro,
  zendeskDeleteMacro,
  zendeskApplyMacro,
  zendeskListMacroCategories,
  zendeskListTriggers,
  zendeskGetTrigger,
  zendeskCreateTrigger,
  zendeskUpdateTrigger,
  zendeskDeleteTrigger,
  zendeskReorderTriggers,
  zendeskGetTriggerDefinitions,
  zendeskListAutomations,
  zendeskGetAutomation,
  zendeskCreateAutomation,
  zendeskUpdateAutomation,
  zendeskDeleteAutomation,
  zendeskReorderAutomations,
  zendeskGetAutomationDefinitions,
  zendeskListSatisfactionRatings,
  zendeskGetSatisfactionRating,
  zendeskListSatisfactionReasons,
  zendeskUploadAttachment,
  zendeskDeleteUpload,
  zendeskListJobStatuses,
  zendeskGetJobStatus,
  zendeskListLocales,
  zendeskListBrands,
  zendeskGetBrand,
  zendeskListSlaPolicies,
  zendeskGetSlaPolicy,
  zendeskListWebhooks,
  zendeskGetWebhook,
  zendeskCreateWebhook,
  zendeskUpdateWebhook,
  zendeskDeleteWebhook,
  zendeskTestWebhook,
  zendeskListWebhookInvocations,
  zendeskGetWebhookSigningSecret,
  zendeskResetWebhookSigningSecret,
};

const AUTH = 'zendeskCredentials' as const;

export const zendeskTools = [
  {
    name: 'zendeskListTickets',
    description: 'List tickets with pagination.',
    tool: zendeskListTickets,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['support', 'queue', 'cases'],
  },
  {
    name: 'zendeskGetTicket',
    description: 'Get one ticket.',
    tool: zendeskGetTicket,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['support', 'case', 'fetch'],
  },
  {
    name: 'zendeskCreateTicket',
    description: 'Create a ticket.',
    tool: zendeskCreateTicket,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['support', 'case', 'open'],
  },
  {
    name: 'zendeskUpdateTicket',
    description: 'Update a ticket or add a comment.',
    tool: zendeskUpdateTicket,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['support', 'reply', 'assign'],
  },
  {
    name: 'zendeskDeleteTicket',
    description: 'Delete a ticket.',
    tool: zendeskDeleteTicket,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['support', 'remove'],
  },
  {
    name: 'zendeskCreateManyTickets',
    description: 'Create up to 100 tickets.',
    tool: zendeskCreateManyTickets,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['bulk', 'migrate'],
  },
  {
    name: 'zendeskUpdateManyTickets',
    description: 'Update up to 100 tickets.',
    tool: zendeskUpdateManyTickets,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['bulk', 'batch'],
  },
  {
    name: 'zendeskDeleteManyTickets',
    description: 'Delete up to 100 tickets.',
    tool: zendeskDeleteManyTickets,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['bulk', 'purge'],
  },
  {
    name: 'zendeskMergeTickets',
    description: 'Merge tickets into a target.',
    tool: zendeskMergeTickets,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['combine', 'duplicates'],
  },
  {
    name: 'zendeskImportTicket',
    description: 'Import a ticket with history.',
    tool: zendeskImportTicket,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['migrate', 'archive'],
  },
  {
    name: 'zendeskImportManyTickets',
    description: 'Bulk import tickets.',
    tool: zendeskImportManyTickets,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['migrate', 'bulk'],
  },
  {
    name: 'zendeskListTicketComments',
    description: 'List ticket comments.',
    tool: zendeskListTicketComments,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['replies', 'notes', 'thread'],
  },
  {
    name: 'zendeskRedactComment',
    description: 'Redact sensitive text in a comment.',
    tool: zendeskRedactComment,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['pii', 'gdpr', 'mask'],
  },
  {
    name: 'zendeskListTicketAudits',
    description: 'List ticket change history.',
    tool: zendeskListTicketAudits,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['timeline', 'changelog'],
  },
  {
    name: 'zendeskGetTicketAudit',
    description: 'Get one ticket audit.',
    tool: zendeskGetTicketAudit,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['history', 'fetch'],
  },
  {
    name: 'zendeskTrustTicketAudit',
    description: 'Mark an audit as trusted.',
    tool: zendeskTrustTicketAudit,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['verify'],
  },
  {
    name: 'zendeskGetTicketMetrics',
    description: 'Get SLA metrics of a ticket.',
    tool: zendeskGetTicketMetrics,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['sla', 'response', 'resolution'],
  },
  {
    name: 'zendeskCountTickets',
    description: 'Count tickets.',
    tool: zendeskCountTickets,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['total', 'stats'],
  },
  {
    name: 'zendeskListTicketFields',
    description: 'List ticket fields.',
    tool: zendeskListTicketFields,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['custom', 'schema'],
  },
  {
    name: 'zendeskGetTicketField',
    description: 'Get one ticket field.',
    tool: zendeskGetTicketField,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['custom', 'fetch'],
  },
  {
    name: 'zendeskCreateTicketField',
    description: 'Create a custom ticket field.',
    tool: zendeskCreateTicketField,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['custom', 'schema'],
  },
  {
    name: 'zendeskUpdateTicketField',
    description: 'Update a ticket field.',
    tool: zendeskUpdateTicketField,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['custom', 'edit'],
  },
  {
    name: 'zendeskDeleteTicketField',
    description: 'Delete a ticket field.',
    tool: zendeskDeleteTicketField,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['custom', 'remove'],
  },
  {
    name: 'zendeskListTicketForms',
    description: 'List ticket forms.',
    tool: zendeskListTicketForms,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['intake', 'templates'],
  },
  {
    name: 'zendeskGetTicketForm',
    description: 'Get one ticket form.',
    tool: zendeskGetTicketForm,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['intake', 'fetch'],
  },
  {
    name: 'zendeskCreateTicketForm',
    description: 'Create a ticket form.',
    tool: zendeskCreateTicketForm,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['intake', 'template'],
  },
  {
    name: 'zendeskUpdateTicketForm',
    description: 'Update a ticket form.',
    tool: zendeskUpdateTicketForm,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['intake', 'edit'],
  },
  {
    name: 'zendeskDeleteTicketForm',
    description: 'Delete a ticket form.',
    tool: zendeskDeleteTicketForm,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['intake', 'remove'],
  },
  {
    name: 'zendeskSearch',
    description: 'Search across Zendesk with query syntax.',
    tool: zendeskSearch,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['find', 'query', 'lookup'],
  },
  {
    name: 'zendeskExportSearch',
    description: 'Export large search results.',
    tool: zendeskExportSearch,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['bulk', 'dump'],
  },
  {
    name: 'zendeskListUsers',
    description: 'List users.',
    tool: zendeskListUsers,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['customers', 'agents', 'contacts'],
  },
  {
    name: 'zendeskGetUser',
    description: 'Get one user.',
    tool: zendeskGetUser,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['customer', 'fetch'],
  },
  {
    name: 'zendeskGetCurrentUser',
    description: 'Get the authenticated user.',
    tool: zendeskGetCurrentUser,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['whoami', 'health', 'verify'],
  },
  {
    name: 'zendeskCreateUser',
    description: 'Create a user.',
    tool: zendeskCreateUser,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['customer', 'provision'],
  },
  {
    name: 'zendeskUpdateUser',
    description: 'Update a user.',
    tool: zendeskUpdateUser,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['customer', 'edit'],
  },
  {
    name: 'zendeskDeleteUser',
    description: 'Delete a user.',
    tool: zendeskDeleteUser,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['customer', 'remove'],
  },
  {
    name: 'zendeskCreateManyUsers',
    description: 'Create up to 100 users.',
    tool: zendeskCreateManyUsers,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['bulk', 'migrate'],
  },
  {
    name: 'zendeskUpdateManyUsers',
    description: 'Update up to 100 users.',
    tool: zendeskUpdateManyUsers,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['bulk'],
  },
  {
    name: 'zendeskDeleteManyUsers',
    description: 'Delete up to 100 users.',
    tool: zendeskDeleteManyUsers,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['bulk', 'purge'],
  },
  {
    name: 'zendeskSearchUsers',
    description: 'Search users.',
    tool: zendeskSearchUsers,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['find', 'lookup'],
  },
  {
    name: 'zendeskShowManyUsers',
    description: 'Fetch up to 100 users by ID.',
    tool: zendeskShowManyUsers,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['batch', 'fetch'],
  },
  {
    name: 'zendeskListUserTickets',
    description: 'List tickets by user relation.',
    tool: zendeskListUserTickets,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['requested', 'assigned', 'history'],
  },
  {
    name: 'zendeskListUserIdentities',
    description: 'List user login identities.',
    tool: zendeskListUserIdentities,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['logins', 'emails'],
  },
  {
    name: 'zendeskCreateUserIdentity',
    description: 'Add a login identity.',
    tool: zendeskCreateUserIdentity,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['email', 'sso'],
  },
  {
    name: 'zendeskMakeIdentityPrimary',
    description: 'Make an identity primary.',
    tool: zendeskMakeIdentityPrimary,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['login', 'default'],
  },
  {
    name: 'zendeskVerifyUserIdentity',
    description: 'Verify a user identity.',
    tool: zendeskVerifyUserIdentity,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['confirm'],
  },
  {
    name: 'zendeskDeleteUserIdentity',
    description: 'Delete a secondary identity.',
    tool: zendeskDeleteUserIdentity,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['login', 'remove'],
  },
  {
    name: 'zendeskListUserGroupMemberships',
    description: 'List user group memberships.',
    tool: zendeskListUserGroupMemberships,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['teams'],
  },
  {
    name: 'zendeskAssignUserToGroup',
    description: 'Add a user to a group.',
    tool: zendeskAssignUserToGroup,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['team', 'join'],
  },
  {
    name: 'zendeskMakeGroupMembershipDefault',
    description: 'Set default group.',
    tool: zendeskMakeGroupMembershipDefault,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['team', 'primary'],
  },
  {
    name: 'zendeskDeleteGroupMembership',
    description: 'Remove a user from a group.',
    tool: zendeskDeleteGroupMembership,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['team', 'leave'],
  },
  {
    name: 'zendeskListOrganizations',
    description: 'List organizations.',
    tool: zendeskListOrganizations,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['companies', 'accounts'],
  },
  {
    name: 'zendeskGetOrganization',
    description: 'Get one organization.',
    tool: zendeskGetOrganization,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['company', 'fetch'],
  },
  {
    name: 'zendeskCreateOrganization',
    description: 'Create an organization.',
    tool: zendeskCreateOrganization,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['company', 'account'],
  },
  {
    name: 'zendeskUpdateOrganization',
    description: 'Update an organization.',
    tool: zendeskUpdateOrganization,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['company', 'edit'],
  },
  {
    name: 'zendeskDeleteOrganization',
    description: 'Delete an organization.',
    tool: zendeskDeleteOrganization,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['company', 'remove'],
  },
  {
    name: 'zendeskCreateManyOrganizations',
    description: 'Create up to 100 organizations.',
    tool: zendeskCreateManyOrganizations,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['bulk', 'migrate'],
  },
  {
    name: 'zendeskUpdateManyOrganizations',
    description: 'Update up to 100 organizations.',
    tool: zendeskUpdateManyOrganizations,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['bulk'],
  },
  {
    name: 'zendeskDeleteManyOrganizations',
    description: 'Delete up to 100 organizations.',
    tool: zendeskDeleteManyOrganizations,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['bulk'],
  },
  {
    name: 'zendeskListOrganizationMemberships',
    description: 'List org memberships.',
    tool: zendeskListOrganizationMemberships,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['members'],
  },
  {
    name: 'zendeskCreateOrganizationMembership',
    description: 'Add a user to an org.',
    tool: zendeskCreateOrganizationMembership,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['member', 'join'],
  },
  {
    name: 'zendeskMakeOrganizationMembershipDefault',
    description: 'Set default org.',
    tool: zendeskMakeOrganizationMembershipDefault,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['primary'],
  },
  {
    name: 'zendeskDeleteOrganizationMembership',
    description: 'Remove a user from an org.',
    tool: zendeskDeleteOrganizationMembership,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['member', 'leave'],
  },
  {
    name: 'zendeskListOrganizationTags',
    description: 'List org tags.',
    tool: zendeskListOrganizationTags,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['labels'],
  },
  {
    name: 'zendeskSetOrganizationTags',
    description: 'Replace org tags.',
    tool: zendeskSetOrganizationTags,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['labels', 'overwrite'],
  },
  {
    name: 'zendeskAddOrganizationTags',
    description: 'Add org tags.',
    tool: zendeskAddOrganizationTags,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['labels', 'append'],
  },
  {
    name: 'zendeskRemoveOrganizationTags',
    description: 'Remove org tags.',
    tool: zendeskRemoveOrganizationTags,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['labels', 'untag'],
  },
  {
    name: 'zendeskListGroups',
    description: 'List agent groups.',
    tool: zendeskListGroups,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['teams', 'queues'],
  },
  {
    name: 'zendeskListAssignableGroups',
    description: 'List assignable groups.',
    tool: zendeskListAssignableGroups,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['teams', 'route'],
  },
  {
    name: 'zendeskGetGroup',
    description: 'Get one group.',
    tool: zendeskGetGroup,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['team', 'fetch'],
  },
  {
    name: 'zendeskCreateGroup',
    description: 'Create an agent group.',
    tool: zendeskCreateGroup,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['team', 'queue'],
  },
  {
    name: 'zendeskUpdateGroup',
    description: 'Rename a group.',
    tool: zendeskUpdateGroup,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['team', 'rename'],
  },
  {
    name: 'zendeskDeleteGroup',
    description: 'Delete a group.',
    tool: zendeskDeleteGroup,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['team', 'remove'],
  },
  {
    name: 'zendeskListViews',
    description: 'List views.',
    tool: zendeskListViews,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['queues', 'filters'],
  },
  {
    name: 'zendeskListActiveViews',
    description: 'List active views compactly.',
    tool: zendeskListActiveViews,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['queues'],
  },
  {
    name: 'zendeskGetView',
    description: 'Get one view.',
    tool: zendeskGetView,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['queue', 'fetch'],
  },
  {
    name: 'zendeskCreateView',
    description: 'Create a view.',
    tool: zendeskCreateView,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['queue', 'filter'],
  },
  {
    name: 'zendeskUpdateView',
    description: 'Update a view.',
    tool: zendeskUpdateView,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['queue', 'edit'],
  },
  {
    name: 'zendeskDeleteView',
    description: 'Delete a view.',
    tool: zendeskDeleteView,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['queue', 'remove'],
  },
  {
    name: 'zendeskExecuteView',
    description: 'Run a view, return tickets.',
    tool: zendeskExecuteView,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['queue', 'run'],
  },
  {
    name: 'zendeskPreviewView',
    description: 'Preview ad-hoc view conditions.',
    tool: zendeskPreviewView,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['queue', 'test'],
  },
  {
    name: 'zendeskCountViews',
    description: 'Count tickets across views.',
    tool: zendeskCountViews,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['queue', 'stats'],
  },
  {
    name: 'zendeskListMacros',
    description: 'List macros.',
    tool: zendeskListMacros,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['canned', 'replies'],
  },
  {
    name: 'zendeskGetMacro',
    description: 'Get one macro.',
    tool: zendeskGetMacro,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['canned', 'fetch'],
  },
  {
    name: 'zendeskCreateMacro',
    description: 'Create a macro.',
    tool: zendeskCreateMacro,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['canned', 'template'],
  },
  {
    name: 'zendeskUpdateMacro',
    description: 'Update a macro.',
    tool: zendeskUpdateMacro,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['canned', 'edit'],
  },
  {
    name: 'zendeskDeleteMacro',
    description: 'Delete a macro.',
    tool: zendeskDeleteMacro,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['canned', 'remove'],
  },
  {
    name: 'zendeskApplyMacro',
    description: 'Apply a macro to a ticket.',
    tool: zendeskApplyMacro,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['canned', 'preview'],
  },
  {
    name: 'zendeskListMacroCategories',
    description: 'List macro categories.',
    tool: zendeskListMacroCategories,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['organize'],
  },
  {
    name: 'zendeskListTriggers',
    description: 'List triggers.',
    tool: zendeskListTriggers,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['automation', 'rules'],
  },
  {
    name: 'zendeskGetTrigger',
    description: 'Get one trigger.',
    tool: zendeskGetTrigger,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['rule', 'fetch'],
  },
  {
    name: 'zendeskCreateTrigger',
    description: 'Create a trigger.',
    tool: zendeskCreateTrigger,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['rule', 'automate'],
  },
  {
    name: 'zendeskUpdateTrigger',
    description: 'Update a trigger.',
    tool: zendeskUpdateTrigger,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['rule', 'edit'],
  },
  {
    name: 'zendeskDeleteTrigger',
    description: 'Delete a trigger.',
    tool: zendeskDeleteTrigger,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['rule', 'remove'],
  },
  {
    name: 'zendeskReorderTriggers',
    description: 'Reorder triggers.',
    tool: zendeskReorderTriggers,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['priority', 'order'],
  },
  {
    name: 'zendeskGetTriggerDefinitions',
    description: 'Get trigger field definitions.',
    tool: zendeskGetTriggerDefinitions,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['schema', 'builder'],
  },
  {
    name: 'zendeskListAutomations',
    description: 'List automations.',
    tool: zendeskListAutomations,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['time-based', 'rules'],
  },
  {
    name: 'zendeskGetAutomation',
    description: 'Get one automation.',
    tool: zendeskGetAutomation,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['rule', 'fetch'],
  },
  {
    name: 'zendeskCreateAutomation',
    description: 'Create an automation.',
    tool: zendeskCreateAutomation,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['rule', 'schedule'],
  },
  {
    name: 'zendeskUpdateAutomation',
    description: 'Update an automation.',
    tool: zendeskUpdateAutomation,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['rule', 'edit'],
  },
  {
    name: 'zendeskDeleteAutomation',
    description: 'Delete an automation.',
    tool: zendeskDeleteAutomation,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['rule', 'remove'],
  },
  {
    name: 'zendeskReorderAutomations',
    description: 'Reorder automations.',
    tool: zendeskReorderAutomations,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['priority', 'order'],
  },
  {
    name: 'zendeskGetAutomationDefinitions',
    description: 'Get automation field definitions.',
    tool: zendeskGetAutomationDefinitions,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['schema', 'builder'],
  },
  {
    name: 'zendeskListSatisfactionRatings',
    description: 'List CSAT ratings.',
    tool: zendeskListSatisfactionRatings,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['csat', 'nps', 'feedback'],
  },
  {
    name: 'zendeskGetSatisfactionRating',
    description: 'Get one CSAT rating.',
    tool: zendeskGetSatisfactionRating,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['csat', 'fetch'],
  },
  {
    name: 'zendeskListSatisfactionReasons',
    description: 'List CSAT reasons.',
    tool: zendeskListSatisfactionReasons,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['csat', 'drivers'],
  },
  {
    name: 'zendeskUploadAttachment',
    description: 'Upload a file, get a token.',
    tool: zendeskUploadAttachment,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['file', 'attach'],
  },
  {
    name: 'zendeskDeleteUpload',
    description: 'Delete an unused upload.',
    tool: zendeskDeleteUpload,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['file', 'discard'],
  },
  {
    name: 'zendeskListJobStatuses',
    description: 'List background jobs.',
    tool: zendeskListJobStatuses,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['bulk', 'imports'],
  },
  {
    name: 'zendeskGetJobStatus',
    description: 'Get one job status.',
    tool: zendeskGetJobStatus,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['bulk', 'poll'],
  },
  {
    name: 'zendeskListLocales',
    description: 'List locales.',
    tool: zendeskListLocales,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['languages', 'i18n'],
  },
  {
    name: 'zendeskListBrands',
    description: 'List brands.',
    tool: zendeskListBrands,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['multi-brand'],
  },
  {
    name: 'zendeskGetBrand',
    description: 'Get one brand.',
    tool: zendeskGetBrand,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['fetch'],
  },
  {
    name: 'zendeskListSlaPolicies',
    description: 'List SLA policies.',
    tool: zendeskListSlaPolicies,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['targets', 'breach'],
  },
  {
    name: 'zendeskGetSlaPolicy',
    description: 'Get one SLA policy.',
    tool: zendeskGetSlaPolicy,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['target', 'fetch'],
  },
  {
    name: 'zendeskListWebhooks',
    description: 'List event webhooks.',
    tool: zendeskListWebhooks,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['events', 'integrations'],
  },
  {
    name: 'zendeskGetWebhook',
    description: 'Get one webhook.',
    tool: zendeskGetWebhook,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['event', 'fetch'],
  },
  {
    name: 'zendeskCreateWebhook',
    description: 'Create a webhook.',
    tool: zendeskCreateWebhook,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['events', 'subscribe'],
  },
  {
    name: 'zendeskUpdateWebhook',
    description: 'Update a webhook.',
    tool: zendeskUpdateWebhook,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['events', 'edit'],
  },
  {
    name: 'zendeskDeleteWebhook',
    description: 'Delete a webhook.',
    tool: zendeskDeleteWebhook,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['events', 'remove'],
  },
  {
    name: 'zendeskTestWebhook',
    description: 'Test a webhook endpoint.',
    tool: zendeskTestWebhook,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['events', 'ping'],
  },
  {
    name: 'zendeskListWebhookInvocations',
    description: 'List webhook deliveries.',
    tool: zendeskListWebhookInvocations,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['events', 'logs'],
  },
  {
    name: 'zendeskGetWebhookSigningSecret',
    description: 'Get webhook signing secret.',
    tool: zendeskGetWebhookSigningSecret,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['verify', 'hmac'],
  },
  {
    name: 'zendeskResetWebhookSigningSecret',
    description: 'Rotate webhook signing secret.',
    tool: zendeskResetWebhookSigningSecret,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['rotate', 'hmac'],
  },
];
