// @ts-nocheck
import { azureListSubscriptions } from './subscriptions.js';
import {
  azureListResourceGroups,
  azureGetResourceGroup,
  azureCreateResourceGroup,
  azureDeleteResourceGroup,
} from './resource-groups.js';
import { azureListResources } from './resources.js';
import {
  azureListVirtualMachines,
  azureGetVirtualMachine,
  azureStartVirtualMachine,
  azureDeallocateVirtualMachine,
  azureRestartVirtualMachine,
  azureListVmScaleSets,
  azureRunVmCommand,
} from './virtual-machines.js';
import { azureListManagedDisks, azureGetManagedDisk, azureListSnapshots } from './disks.js';
import {
  azureListStorageAccounts,
  azureGetStorageAccount,
  azureListStorageAccountKeys,
  azureListBlobContainers,
  azureListFileShares,
  azureRegenerateStorageAccountKey,
} from './storage.js';
import {
  azureListVirtualNetworks,
  azureGetVirtualNetwork,
  azureListPublicIpAddresses,
  azureListNetworkSecurityGroups,
  azureListLoadBalancers,
  azureListDnsZones,
} from './network.js';
import {
  azureListWebApps,
  azureGetWebApp,
  azureRestartWebApp,
  azureListAppServicePlans,
  azureListFunctionApps,
  azureGetWebAppSettings,
} from './web-apps.js';
import {
  azureListSqlServers,
  azureListSqlDatabases,
  azureGetSqlDatabase,
  azureListCosmosDbAccounts,
  azureListContainerRegistries,
  azureListContainerGroups,
  azureGetKubernetesCluster,
  azureListAgentPools,
  azureListKubernetesClusters,
  azureListKeyVaults,
} from './data-platform.js';
import {
  azureQueryMonitorMetrics,
  azureListActivityLogs,
  azureListMetricAlerts,
  azureListLogAnalyticsWorkspaces,
  azureListMonitorMetricDefinitions,
} from './monitor.js';
import {
  azureListRoleAssignments,
  azureQueryCostManagement,
  azureListAdvisorRecommendations,
} from './governance.js';

export {
  azureListSubscriptions,
  azureListResourceGroups,
  azureGetResourceGroup,
  azureCreateResourceGroup,
  azureDeleteResourceGroup,
  azureListResources,
  azureListVirtualMachines,
  azureGetVirtualMachine,
  azureStartVirtualMachine,
  azureDeallocateVirtualMachine,
  azureRestartVirtualMachine,
  azureListVmScaleSets,
  azureRunVmCommand,
  azureListManagedDisks,
  azureGetManagedDisk,
  azureListSnapshots,
  azureListStorageAccounts,
  azureGetStorageAccount,
  azureListStorageAccountKeys,
  azureListBlobContainers,
  azureListFileShares,
  azureRegenerateStorageAccountKey,
  azureListVirtualNetworks,
  azureGetVirtualNetwork,
  azureListPublicIpAddresses,
  azureListNetworkSecurityGroups,
  azureListLoadBalancers,
  azureListDnsZones,
  azureListWebApps,
  azureGetWebApp,
  azureRestartWebApp,
  azureListAppServicePlans,
  azureListFunctionApps,
  azureGetWebAppSettings,
  azureListSqlServers,
  azureListSqlDatabases,
  azureGetSqlDatabase,
  azureListCosmosDbAccounts,
  azureListContainerRegistries,
  azureListContainerGroups,
  azureGetKubernetesCluster,
  azureListAgentPools,
  azureListKubernetesClusters,
  azureListKeyVaults,
  azureQueryMonitorMetrics,
  azureListActivityLogs,
  azureListMetricAlerts,
  azureListLogAnalyticsWorkspaces,
  azureListMonitorMetricDefinitions,
  azureListRoleAssignments,
  azureQueryCostManagement,
  azureListAdvisorRecommendations,
};

const auth = 'azureCredentials' as const;

export const azureTools = [
  { name: 'azureListSubscriptions', description: 'List Azure subscriptions visible to the connected service principal. Use to discover subscription IDs before other calls.', tool: azureListSubscriptions, requiredAuth: auth, scope: 'read' as const },
  { name: 'azureListResourceGroups', description: 'List resource groups in an Azure subscription. Use to discover where VMs, storage and apps live.', tool: azureListResourceGroups, requiredAuth: auth, scope: 'read' as const },
  { name: 'azureGetResourceGroup', description: 'Get details of a single Azure resource group including location, tags and provisioning state.', tool: azureGetResourceGroup, requiredAuth: auth, scope: 'read' as const },
  { name: 'azureCreateResourceGroup', description: 'Create a new Azure resource group in a subscription and location. Use before deploying new workloads.', tool: azureCreateResourceGroup, requiredAuth: auth, scope: 'write' as const },
  { name: 'azureDeleteResourceGroup', description: 'Delete an Azure resource group and all resources it contains. Irreversible — confirm with the user first.', tool: azureDeleteResourceGroup, requiredAuth: auth, scope: 'delete' as const },
  { name: 'azureListResources', description: 'List ARM resources in a subscription or resource group, optionally filtered by resource type. Use for inventory across VMs, storage, web apps and more.', tool: azureListResources, requiredAuth: auth, scope: 'read' as const },
  { name: 'azureListVirtualMachines', description: 'List virtual machines in a subscription or resource group. Returns name, size, OS, provisioning and power state.', tool: azureListVirtualMachines, requiredAuth: auth, scope: 'read' as const },
  { name: 'azureGetVirtualMachine', description: 'Get details of a virtual machine, optionally including instanceView for live power and provisioning status.', tool: azureGetVirtualMachine, requiredAuth: auth, scope: 'read' as const },
  { name: 'azureStartVirtualMachine', description: 'Start a stopped Azure virtual machine. Use to bring a dev/test or production VM back online.', tool: azureStartVirtualMachine, requiredAuth: auth, scope: 'write' as const },
  { name: 'azureDeallocateVirtualMachine', description: 'Stop and deallocate an Azure virtual machine to stop compute billing. Use to save cost on idle VMs.', tool: azureDeallocateVirtualMachine, requiredAuth: auth, scope: 'write' as const },
  { name: 'azureRestartVirtualMachine', description: 'Restart an Azure virtual machine. Use after config changes or to recover an unresponsive VM.', tool: azureRestartVirtualMachine, requiredAuth: auth, scope: 'write' as const },
  { name: 'azureListVmScaleSets', description: 'List virtual machine scale sets in a subscription or resource group. Returns SKU, capacity, upgrade policy and orchestration mode.', tool: azureListVmScaleSets, requiredAuth: auth, scope: 'read' as const },
  { name: 'azureRunVmCommand', description: 'Run a shell or PowerShell script on a VM via the VM agent (RunShellScript for Linux, RunPowerShellScript for Windows). The call is async — a 202 means accepted for processing.', tool: azureRunVmCommand, requiredAuth: auth, scope: 'write' as const },
  { name: 'azureListManagedDisks', description: 'List managed disks in a subscription or resource group. Returns size, SKU, OS type, attachment state and encryption.', tool: azureListManagedDisks, requiredAuth: auth, scope: 'read' as const },
  { name: 'azureGetManagedDisk', description: 'Get details of a managed disk including size, SKU, encryption, network access and attached VM.', tool: azureGetManagedDisk, requiredAuth: auth, scope: 'read' as const },
  { name: 'azureListSnapshots', description: 'List managed disk snapshots in a subscription or resource group. Use to find backup/restore points before disk recovery.', tool: azureListSnapshots, requiredAuth: auth, scope: 'read' as const },
  { name: 'azureListStorageAccounts', description: 'List storage accounts in a subscription or resource group. Returns name, SKU, kind, location and access tier.', tool: azureListStorageAccounts, requiredAuth: auth, scope: 'read' as const },
  { name: 'azureGetStorageAccount', description: 'Get properties of a storage account including endpoints, encryption, network rules and status.', tool: azureGetStorageAccount, requiredAuth: auth, scope: 'read' as const },
  { name: 'azureListStorageAccountKeys', description: 'List access keys for a storage account. Handle as sensitive — use for connection strings and rotation checks.', tool: azureListStorageAccountKeys, requiredAuth: auth, scope: 'read' as const },
  { name: 'azureListBlobContainers', description: 'List blob containers in a storage account. Returns name, public access level and last-modified time.', tool: azureListBlobContainers, requiredAuth: auth, scope: 'read' as const },
  { name: 'azureListFileShares', description: 'List file shares in a storage account. Returns name, quota, provisioned size and access tier.', tool: azureListFileShares, requiredAuth: auth, scope: 'read' as const },
  { name: 'azureRegenerateStorageAccountKey', description: 'Regenerate (rotate) a storage account access key. Pass keyName key1 or key2 — rotate the standby key first to avoid downtime.', tool: azureRegenerateStorageAccountKey, requiredAuth: auth, scope: 'write' as const },
  { name: 'azureListVirtualNetworks', description: 'List virtual networks in a subscription or resource group. Returns address spaces, subnets and peering state.', tool: azureListVirtualNetworks, requiredAuth: auth, scope: 'read' as const },
  { name: 'azureGetVirtualNetwork', description: 'Get a virtual network including address spaces, subnets, DNS servers and peering status.', tool: azureGetVirtualNetwork, requiredAuth: auth, scope: 'read' as const },
  { name: 'azureListPublicIpAddresses', description: 'List public IP addresses in a subscription or resource group. Returns address, allocation method, SKU and association.', tool: azureListPublicIpAddresses, requiredAuth: auth, scope: 'read' as const },
  { name: 'azureListNetworkSecurityGroups', description: 'List network security groups with their security rules. Use to audit open ports and access controls.', tool: azureListNetworkSecurityGroups, requiredAuth: auth, scope: 'read' as const },
  { name: 'azureListLoadBalancers', description: 'List load balancers in a subscription or resource group. Returns SKU, frontend IPs, backend pools and rules.', tool: azureListLoadBalancers, requiredAuth: auth, scope: 'read' as const },
  { name: 'azureListDnsZones', description: 'List Azure DNS zones in a subscription or resource group. Returns name, record count and name servers.', tool: azureListDnsZones, requiredAuth: auth, scope: 'read' as const },
  { name: 'azureListWebApps', description: 'List App Service web apps in a subscription or resource group. Returns hostname, state, runtime stack and app plan.', tool: azureListWebApps, requiredAuth: auth, scope: 'read' as const },
  { name: 'azureGetWebApp', description: 'Get configuration of an App Service web app including app settings, bindings and site config.', tool: azureGetWebApp, requiredAuth: auth, scope: 'read' as const },
  { name: 'azureRestartWebApp', description: 'Restart an App Service web app. Use after deployments or config changes, or to recover a stuck app.', tool: azureRestartWebApp, requiredAuth: auth, scope: 'write' as const },
  { name: 'azureListAppServicePlans', description: 'List App Service plans in a subscription or resource group. Returns SKU, worker count, OS kind and hosting status.', tool: azureListAppServicePlans, requiredAuth: auth, scope: 'read' as const },
  { name: 'azureListFunctionApps', description: 'List Function Apps in a subscription or resource group. Returns hostname, state and runtime info for serverless workloads.', tool: azureListFunctionApps, requiredAuth: auth, scope: 'read' as const },
  { name: 'azureGetWebAppSettings', description: 'List app settings (environment variables) of a web app. Handle as sensitive — values may include secrets and connection strings.', tool: azureGetWebAppSettings, requiredAuth: auth, scope: 'read' as const },
  { name: 'azureListSqlServers', description: 'List Azure SQL logical servers in a subscription. Returns name, location, version and admin login.', tool: azureListSqlServers, requiredAuth: auth, scope: 'read' as const },
  { name: 'azureListSqlDatabases', description: 'List databases on an Azure SQL logical server. Returns name, SKU, status, collation and max size.', tool: azureListSqlDatabases, requiredAuth: auth, scope: 'read' as const },
  { name: 'azureGetSqlDatabase', description: 'Get details of an Azure SQL database including SKU, status, collation, max size and zone redundancy.', tool: azureGetSqlDatabase, requiredAuth: auth, scope: 'read' as const },
  { name: 'azureListCosmosDbAccounts', description: 'List Azure Cosmos DB accounts in a subscription or resource group. Returns API kind, locations, consistency and endpoints.', tool: azureListCosmosDbAccounts, requiredAuth: auth, scope: 'read' as const },
  { name: 'azureListContainerRegistries', description: 'List Azure Container Registry (ACR) registries. Returns login server, SKU and admin-user status for image hosting.', tool: azureListContainerRegistries, requiredAuth: auth, scope: 'read' as const },
  { name: 'azureListContainerGroups', description: 'List Azure Container Instances (serverless containers). Returns state, IP, container image and restart policy.', tool: azureListContainerGroups, requiredAuth: auth, scope: 'read' as const },
  { name: 'azureGetKubernetesCluster', description: 'Get an AKS cluster including Kubernetes version, DNS prefix, node pool profiles, network profile and power state.', tool: azureGetKubernetesCluster, requiredAuth: auth, scope: 'read' as const },
  { name: 'azureListAgentPools', description: 'List node pools (agent pools) of an AKS cluster. Returns VM size, count, OS, mode and autoscaling config.', tool: azureListAgentPools, requiredAuth: auth, scope: 'read' as const },
  { name: 'azureListKubernetesClusters', description: 'List Azure Kubernetes Service (AKS) managed clusters. Returns name, location, Kubernetes version and node pools.', tool: azureListKubernetesClusters, requiredAuth: auth, scope: 'read' as const },
  { name: 'azureListKeyVaults', description: 'List Key Vaults in a subscription. Returns name, location, SKU and vault URI for secrets management.', tool: azureListKeyVaults, requiredAuth: auth, scope: 'read' as const },
  { name: 'azureQueryMonitorMetrics', description: 'Query Azure Monitor metrics for any resource (VM CPU, storage latency, app requests). Use to check health and performance.', tool: azureQueryMonitorMetrics, requiredAuth: auth, scope: 'read' as const },
  { name: 'azureListActivityLogs', description: 'List Azure Activity Log events for a subscription. Use to audit who created, updated or deleted resources and when.', tool: azureListActivityLogs, requiredAuth: auth, scope: 'read' as const },
  { name: 'azureListMetricAlerts', description: 'List Azure Monitor metric alert rules in a subscription or resource group. Returns severity, condition, scopes and actions.', tool: azureListMetricAlerts, requiredAuth: auth, scope: 'read' as const },
  { name: 'azureListLogAnalyticsWorkspaces', description: 'List Log Analytics workspaces. Returns retention, SKU, provisioning state and customer ID for log queries.', tool: azureListLogAnalyticsWorkspaces, requiredAuth: auth, scope: 'read' as const },
  { name: 'azureListMonitorMetricDefinitions', description: 'List available metric definitions for a resource. Use to discover valid metricNames before calling azureQueryMonitorMetrics.', tool: azureListMonitorMetricDefinitions, requiredAuth: auth, scope: 'read' as const },
  { name: 'azureListRoleAssignments', description: 'List RBAC role assignments in a subscription or resource group. Use to audit who has access to what.', tool: azureListRoleAssignments, requiredAuth: auth, scope: 'read' as const },
  { name: 'azureQueryCostManagement', description: 'Query Azure Cost Management for actual cost grouped by service, resource group or location. Use to answer spend and billing questions.', tool: azureQueryCostManagement, requiredAuth: auth, scope: 'read' as const },
  { name: 'azureListAdvisorRecommendations', description: 'List Azure Advisor recommendations for cost, security, reliability and performance. Use to find savings and best-practice fixes.', tool: azureListAdvisorRecommendations, requiredAuth: auth, scope: 'read' as const },
];
