// @ts-nocheck
import {
  copyJob,
  createJob,
  deleteJob,
  disableJob,
  enableJob,
  getJob,
  getJobConfig,
  listJobs,
  updateJobConfig,
} from './jobs.js';
import {
  deleteBuild,
  getBuild,
  getConsoleLog,
  getLastBuild,
  getProgressiveLog,
  getTestReport,
  listBuilds,
  stopBuild,
  triggerBuild,
  triggerParameterizedBuild,
} from './builds.js';
import {
  cancelQueueItem,
  cancelQuietDown,
  getCurrentUser,
  getNode,
  getQueueItem,
  getServerInfo,
  getView,
  listNodes,
  listPlugins,
  listQueue,
  listViews,
  quietDown,
  safeRestart,
} from './system.js';

export {
  listJobs,
  getJob,
  getJobConfig,
  createJob,
  copyJob,
  updateJobConfig,
  enableJob,
  disableJob,
  deleteJob,
  listBuilds,
  getBuild,
  getLastBuild,
  getConsoleLog,
  getProgressiveLog,
  getTestReport,
  triggerBuild,
  triggerParameterizedBuild,
  stopBuild,
  deleteBuild,
  getServerInfo,
  listQueue,
  getQueueItem,
  cancelQueueItem,
  listNodes,
  getNode,
  listViews,
  getView,
  listPlugins,
  getCurrentUser,
  quietDown,
  cancelQuietDown,
  safeRestart,
};

const auth = 'jenkinsCredentials' as const;

type Scope = 'read' | 'write' | 'delete';
function entry(
  name: string,
  description: string,
  toolRef: any,
  scope: Scope,
  keywords: string[] = [],
): {
  name: string;
  description: string;
  tool: any;
  requiredAuth: typeof auth;
  scope: Scope;
  keywords: string[];
} {
  return { name, description, tool: toolRef, requiredAuth: auth, scope, keywords };
}

export const jenkinsTools = [
  entry(
    'jenkinsListJobs',
    'List jobs on the Jenkins controller with name, status color and build state. Use first to discover job names.',
    listJobs,
    'read',
    ['pipeline', 'pipelines'],
  ),
  entry(
    'jenkinsGetJob',
    'Get details of a Jenkins job: description, disabled state, health reports and recent builds.',
    getJob,
    'read',
  ),
  entry(
    'jenkinsGetJobConfig',
    'Get the raw config.xml of a Jenkins job to read SCM, triggers and builder configuration.',
    getJobConfig,
    'read',
    ['configuration'],
  ),
  entry(
    'jenkinsCreateJob',
    'Create a new Jenkins job from a config.xml document.',
    createJob,
    'write',
    ['pipeline'],
  ),
  entry(
    'jenkinsCopyJob',
    'Copy an existing Jenkins job to a new name instead of hand-writing config.xml.',
    copyJob,
    'write',
    ['clone', 'duplicate'],
  ),
  entry(
    'jenkinsUpdateJobConfig',
    'Update a Jenkins job by replacing its config.xml with a full replacement document.',
    updateJobConfig,
    'write',
    ['configuration'],
  ),
  entry(
    'jenkinsEnableJob',
    'Enable a disabled Jenkins job so it can be built and triggered again.',
    enableJob,
    'write',
  ),
  entry(
    'jenkinsDisableJob',
    'Disable a Jenkins job so no new builds are scheduled (running builds continue).',
    disableJob,
    'write',
  ),
  entry(
    'jenkinsDeleteJob',
    'Permanently delete a Jenkins job and all of its builds and artifacts.',
    deleteJob,
    'delete',
    ['remove'],
  ),
  entry(
    'jenkinsListBuilds',
    'List recent builds of a Jenkins job with number, result, building state and duration.',
    listBuilds,
    'read',
    ['run', 'runs'],
  ),
  entry(
    'jenkinsGetBuild',
    'Get details of a single Jenkins build: result, duration, artifacts, change sets and culprits.',
    getBuild,
    'read',
    ['run'],
  ),
  entry(
    'jenkinsGetLastBuild',
    'Get a symbolic build of a job (lastBuild, lastSuccessfulBuild, lastFailedBuild, lastCompletedBuild, lastStableBuild) without knowing its number.',
    getLastBuild,
    'read',
    ['latest'],
  ),
  entry(
    'jenkinsGetConsoleLog',
    'Get the full console output of a Jenkins build to diagnose failures.',
    getConsoleLog,
    'read',
    ['logs'],
  ),
  entry(
    'jenkinsGetProgressiveLog',
    'Page through a Jenkins build log with the progressiveText API; also works for live-tailing running builds.',
    getProgressiveLog,
    'read',
    ['tail', 'stream', 'logs'],
  ),
  entry(
    'jenkinsGetTestReport',
    'Get the aggregated JUnit test report of a Jenkins build with pass/fail/skip counts.',
    getTestReport,
    'read',
    ['tests'],
  ),
  entry(
    'jenkinsTriggerBuild',
    'Trigger a new build of a Jenkins job without parameters. Returns the queue item URL for tracking.',
    triggerBuild,
    'write',
    ['start', 'run', 'launch'],
  ),
  entry(
    'jenkinsTriggerParameterizedBuild',
    'Trigger a new build of a parameterized Jenkins job with a key-value parameter map.',
    triggerParameterizedBuild,
    'write',
    ['start', 'parameters'],
  ),
  entry(
    'jenkinsStopBuild',
    'Abort a running Jenkins build (marked ABORTED, kept in history).',
    stopBuild,
    'write',
    ['cancel', 'kill'],
  ),
  entry(
    'jenkinsDeleteBuild',
    'Permanently delete a single Jenkins build with its log, artifacts and test results.',
    deleteBuild,
    'delete',
    ['remove'],
  ),
  entry(
    'jenkinsGetServerInfo',
    'Get Jenkins controller info: version, jobs/views overview and executor counts. Use to verify connectivity.',
    getServerInfo,
    'read',
    ['health', 'status'],
  ),
  entry(
    'jenkinsListQueue',
    'List items waiting in the Jenkins build queue with reason, ETA and task.',
    listQueue,
    'read',
  ),
  entry(
    'jenkinsGetQueueItem',
    'Get a single Jenkins queue item: wait reason, ETA and the started build URL once assigned.',
    getQueueItem,
    'read',
  ),
  entry(
    'jenkinsCancelQueueItem',
    'Cancel a waiting Jenkins build queue item so it never starts.',
    cancelQueueItem,
    'write',
  ),
  entry(
    'jenkinsListNodes',
    'List Jenkins agents/nodes with offline state, executor counts and load statistics.',
    listNodes,
    'read',
    ['agent', 'agents'],
  ),
  entry(
    'jenkinsGetNode',
    'Get details of a single Jenkins agent: executors, monitor data and offline cause.',
    getNode,
    'read',
    ['agent'],
  ),
  entry(
    'jenkinsListViews',
    'List views (tabs) configured on the Jenkins controller.',
    listViews,
    'read',
  ),
  entry(
    'jenkinsGetView',
    'Get a Jenkins view with the jobs it contains and their status colors.',
    getView,
    'read',
  ),
  entry(
    'jenkinsListPlugins',
    'List plugins installed on the Jenkins controller with version and enabled state.',
    listPlugins,
    'read',
    ['plugin', 'extension', 'extensions'],
  ),
  entry(
    'jenkinsGetCurrentUser',
    'Get the Jenkins user the credentials authenticate as. Use to verify an API token.',
    getCurrentUser,
    'read',
    ['whoami'],
  ),
  entry(
    'jenkinsQuietDown',
    'Put Jenkins into quiet-down mode: running builds finish, no new builds start.',
    quietDown,
    'write',
    ['maintenance'],
  ),
  entry(
    'jenkinsCancelQuietDown',
    'Cancel quiet-down mode so Jenkins accepts new builds again.',
    cancelQuietDown,
    'write',
  ),
  entry(
    'jenkinsSafeRestart',
    'Safely restart Jenkins after running jobs finish.',
    safeRestart,
    'write',
    ['reboot'],
  ),
];
