// @ts-nocheck
import {
    discordGetMyUser,
    discordGetUser,
    discordGetOpenIdUserinfo,
    discordGetMyOAuth2Authorization,
    discordGetPublicKeys,
    discordListMyConnections,
    discordGetMyGuildMember,
} from './users.js';
import {
    discordListMyGuilds,
    discordGetGuildTemplate,
    discordGetGuildWidget,
    discordGetGuildWidgetPng,
    discordResolveInvite,
} from './guilds.js';
import {
    discordEditCommandPermissions,
    discordGetCommandPermissions,
    discordGetBatchCommandPermissions,
    discordGetMyEntitlements,
    discordGetRoleConnection,
    discordUpdateRoleConnection,
    discordDeleteRoleConnection,
    discordGetSkuSubscription,
    discordListSkuSubscriptions,
} from './applications.js';
import { discordGetGateway, discordListStickerPacks } from './misc.js';

export {
    discordGetMyUser,
    discordGetUser,
    discordGetOpenIdUserinfo,
    discordGetMyOAuth2Authorization,
    discordGetPublicKeys,
    discordListMyConnections,
    discordGetMyGuildMember,
    discordListMyGuilds,
    discordGetGuildTemplate,
    discordGetGuildWidget,
    discordGetGuildWidgetPng,
    discordResolveInvite,
    discordEditCommandPermissions,
    discordGetCommandPermissions,
    discordGetBatchCommandPermissions,
    discordGetMyEntitlements,
    discordGetRoleConnection,
    discordUpdateRoleConnection,
    discordDeleteRoleConnection,
    discordGetSkuSubscription,
    discordListSkuSubscriptions,
    discordGetGateway,
    discordListStickerPacks,
};

export const discordTools = [
    {
        name: 'discordGetMyUser',
        description: discordGetMyUser.description!,
        tool: discordGetMyUser,
        requiredAuth: 'discordToken' as const,
        scope: 'read' as const,
    },
    {
        name: 'discordGetUser',
        description: discordGetUser.description!,
        tool: discordGetUser,
        requiredAuth: 'discordToken' as const,
        scope: 'read' as const,
    },
    {
        name: 'discordGetOpenIdUserinfo',
        description: discordGetOpenIdUserinfo.description!,
        tool: discordGetOpenIdUserinfo,
        requiredAuth: 'discordToken' as const,
        scope: 'read' as const,
    },
    {
        name: 'discordGetMyOAuth2Authorization',
        description: discordGetMyOAuth2Authorization.description!,
        tool: discordGetMyOAuth2Authorization,
        requiredAuth: 'discordToken' as const,
        scope: 'read' as const,
    },
    {
        name: 'discordGetPublicKeys',
        description: discordGetPublicKeys.description!,
        tool: discordGetPublicKeys,
        requiredAuth: 'discordToken' as const,
        scope: 'read' as const,
    },
    {
        name: 'discordListMyConnections',
        description: discordListMyConnections.description!,
        tool: discordListMyConnections,
        requiredAuth: 'discordToken' as const,
        scope: 'read' as const,
    },
    {
        name: 'discordGetMyGuildMember',
        description: discordGetMyGuildMember.description!,
        tool: discordGetMyGuildMember,
        requiredAuth: 'discordToken' as const,
        scope: 'read' as const,
    },
    {
        name: 'discordListMyGuilds',
        description: discordListMyGuilds.description!,
        tool: discordListMyGuilds,
        requiredAuth: 'discordToken' as const,
        scope: 'read' as const,
    },
    {
        name: 'discordGetGuildTemplate',
        description: discordGetGuildTemplate.description!,
        tool: discordGetGuildTemplate,
        requiredAuth: 'discordToken' as const,
        scope: 'read' as const,
    },
    {
        name: 'discordGetGuildWidget',
        description: discordGetGuildWidget.description!,
        tool: discordGetGuildWidget,
        requiredAuth: 'discordToken' as const,
        scope: 'read' as const,
    },
    {
        name: 'discordGetGuildWidgetPng',
        description: discordGetGuildWidgetPng.description!,
        tool: discordGetGuildWidgetPng,
        requiredAuth: 'discordToken' as const,
        scope: 'read' as const,
    },
    {
        name: 'discordResolveInvite',
        description: discordResolveInvite.description!,
        tool: discordResolveInvite,
        requiredAuth: 'discordToken' as const,
        scope: 'read' as const,
    },
    {
        name: 'discordEditCommandPermissions',
        description: discordEditCommandPermissions.description!,
        tool: discordEditCommandPermissions,
        requiredAuth: 'discordToken' as const,
        scope: 'write' as const,
    },
    {
        name: 'discordGetCommandPermissions',
        description: discordGetCommandPermissions.description!,
        tool: discordGetCommandPermissions,
        requiredAuth: 'discordToken' as const,
        scope: 'read' as const,
    },
    {
        name: 'discordGetBatchCommandPermissions',
        description: discordGetBatchCommandPermissions.description!,
        tool: discordGetBatchCommandPermissions,
        requiredAuth: 'discordToken' as const,
        scope: 'read' as const,
    },
    {
        name: 'discordGetMyEntitlements',
        description: discordGetMyEntitlements.description!,
        tool: discordGetMyEntitlements,
        requiredAuth: 'discordToken' as const,
        scope: 'read' as const,
    },
    {
        name: 'discordGetRoleConnection',
        description: discordGetRoleConnection.description!,
        tool: discordGetRoleConnection,
        requiredAuth: 'discordToken' as const,
        scope: 'read' as const,
    },
    {
        name: 'discordUpdateRoleConnection',
        description: discordUpdateRoleConnection.description!,
        tool: discordUpdateRoleConnection,
        requiredAuth: 'discordToken' as const,
        scope: 'write' as const,
    },
    {
        name: 'discordDeleteRoleConnection',
        description: discordDeleteRoleConnection.description!,
        tool: discordDeleteRoleConnection,
        requiredAuth: 'discordToken' as const,
        scope: 'delete' as const,
    },
    {
        name: 'discordGetSkuSubscription',
        description: discordGetSkuSubscription.description!,
        tool: discordGetSkuSubscription,
        requiredAuth: 'discordToken' as const,
        scope: 'read' as const,
    },
    {
        name: 'discordListSkuSubscriptions',
        description: discordListSkuSubscriptions.description!,
        tool: discordListSkuSubscriptions,
        requiredAuth: 'discordToken' as const,
        scope: 'read' as const,
    },
    {
        name: 'discordGetGateway',
        description: discordGetGateway.description!,
        tool: discordGetGateway,
        requiredAuth: 'discordToken' as const,
        scope: 'read' as const,
    },
    {
        name: 'discordListStickerPacks',
        description: discordListStickerPacks.description!,
        tool: discordListStickerPacks,
        requiredAuth: 'discordToken' as const,
        scope: 'read' as const,
    },
];
