// @ts-nocheck
import {
  discordGetMyUser,
  discordGetUser,
  discordGetOpenIdUserinfo,
  discordGetMyOAuth2Authorization,
  discordGetPublicKeys,
  discordListMyConnections,
  discordGetMyGuildMember,
} from './users.js';
import {
  discordListMyGuilds,
  discordGetGuildTemplate,
  discordGetGuildWidget,
  discordGetGuildWidgetPng,
  discordResolveInvite,
} from './guilds.js';
import {
  discordEditCommandPermissions,
  discordGetCommandPermissions,
  discordGetBatchCommandPermissions,
  discordGetMyEntitlements,
  discordGetRoleConnection,
  discordUpdateRoleConnection,
  discordDeleteRoleConnection,
  discordGetSkuSubscription,
  discordListSkuSubscriptions,
} from './applications.js';
import { discordGetGateway, discordListStickerPacks } from './misc.js';

export {
  discordGetMyUser,
  discordGetUser,
  discordGetOpenIdUserinfo,
  discordGetMyOAuth2Authorization,
  discordGetPublicKeys,
  discordListMyConnections,
  discordGetMyGuildMember,
  discordListMyGuilds,
  discordGetGuildTemplate,
  discordGetGuildWidget,
  discordGetGuildWidgetPng,
  discordResolveInvite,
  discordEditCommandPermissions,
  discordGetCommandPermissions,
  discordGetBatchCommandPermissions,
  discordGetMyEntitlements,
  discordGetRoleConnection,
  discordUpdateRoleConnection,
  discordDeleteRoleConnection,
  discordGetSkuSubscription,
  discordListSkuSubscriptions,
  discordGetGateway,
  discordListStickerPacks,
};

export const discordTools = [
  {
    name: 'discordGetMyUser',
    description: discordGetMyUser.description!,
    tool: discordGetMyUser,
    requiredAuth: 'discordToken' as const,
    scope: 'read' as const,
    keywords: ['whoami', 'profile'],
  },
  {
    name: 'discordGetUser',
    description: discordGetUser.description!,
    tool: discordGetUser,
    requiredAuth: 'discordToken' as const,
    scope: 'read' as const,
    keywords: ['profile'],
  },
  {
    name: 'discordGetOpenIdUserinfo',
    description: discordGetOpenIdUserinfo.description!,
    tool: discordGetOpenIdUserinfo,
    requiredAuth: 'discordToken' as const,
    scope: 'read' as const,
    keywords: ['openid', 'oidc'],
  },
  {
    name: 'discordGetMyOAuth2Authorization',
    description: discordGetMyOAuth2Authorization.description!,
    tool: discordGetMyOAuth2Authorization,
    requiredAuth: 'discordToken' as const,
    scope: 'read' as const,
    keywords: ['auth', 'token'],
  },
  {
    name: 'discordGetPublicKeys',
    description: discordGetPublicKeys.description!,
    tool: discordGetPublicKeys,
    requiredAuth: 'discordToken' as const,
    scope: 'read' as const,
    keywords: ['jwks', 'key', 'jwt'],
  },
  {
    name: 'discordListMyConnections',
    description: discordListMyConnections.description!,
    tool: discordListMyConnections,
    requiredAuth: 'discordToken' as const,
    scope: 'read' as const,
    keywords: ['linked', 'account'],
  },
  {
    name: 'discordGetMyGuildMember',
    description: discordGetMyGuildMember.description!,
    tool: discordGetMyGuildMember,
    requiredAuth: 'discordToken' as const,
    scope: 'read' as const,
    keywords: ['server', 'role'],
  },
  {
    name: 'discordListMyGuilds',
    description: discordListMyGuilds.description!,
    tool: discordListMyGuilds,
    requiredAuth: 'discordToken' as const,
    scope: 'read' as const,
    keywords: ['server', 'servers'],
  },
  {
    name: 'discordGetGuildTemplate',
    description: discordGetGuildTemplate.description!,
    tool: discordGetGuildTemplate,
    requiredAuth: 'discordToken' as const,
    scope: 'read' as const,
    keywords: ['server', 'blueprint', 'clone'],
  },
  {
    name: 'discordGetGuildWidget',
    description: discordGetGuildWidget.description!,
    tool: discordGetGuildWidget,
    requiredAuth: 'discordToken' as const,
    scope: 'read' as const,
    keywords: ['server', 'online'],
  },
  {
    name: 'discordGetGuildWidgetPng',
    description: discordGetGuildWidgetPng.description!,
    tool: discordGetGuildWidgetPng,
    requiredAuth: 'discordToken' as const,
    scope: 'read' as const,
    keywords: ['server', 'widget', 'image'],
  },
  {
    name: 'discordResolveInvite',
    description: discordResolveInvite.description!,
    tool: discordResolveInvite,
    requiredAuth: 'discordToken' as const,
    scope: 'read' as const,
    keywords: ['server', 'join', 'code'],
  },
  {
    name: 'discordEditCommandPermissions',
    description: discordEditCommandPermissions.description!,
    tool: discordEditCommandPermissions,
    requiredAuth: 'discordToken' as const,
    scope: 'write' as const,
    keywords: ['slash', 'permission', 'server'],
  },
  {
    name: 'discordGetCommandPermissions',
    description: discordGetCommandPermissions.description!,
    tool: discordGetCommandPermissions,
    requiredAuth: 'discordToken' as const,
    scope: 'read' as const,
    keywords: ['slash', 'permission', 'server'],
  },
  {
    name: 'discordGetBatchCommandPermissions',
    description: discordGetBatchCommandPermissions.description!,
    tool: discordGetBatchCommandPermissions,
    requiredAuth: 'discordToken' as const,
    scope: 'read' as const,
    keywords: ['slash', 'permission', 'server'],
  },
  {
    name: 'discordGetMyEntitlements',
    description: discordGetMyEntitlements.description!,
    tool: discordGetMyEntitlements,
    requiredAuth: 'discordToken' as const,
    scope: 'read' as const,
    keywords: ['entitlement', 'subscription', 'premium'],
  },
  {
    name: 'discordGetRoleConnection',
    description: discordGetRoleConnection.description!,
    tool: discordGetRoleConnection,
    requiredAuth: 'discordToken' as const,
    scope: 'read' as const,
    keywords: ['linked', 'role'],
  },
  {
    name: 'discordUpdateRoleConnection',
    description: discordUpdateRoleConnection.description!,
    tool: discordUpdateRoleConnection,
    requiredAuth: 'discordToken' as const,
    scope: 'write' as const,
    keywords: ['linked', 'role'],
  },
  {
    name: 'discordDeleteRoleConnection',
    description: discordDeleteRoleConnection.description!,
    tool: discordDeleteRoleConnection,
    requiredAuth: 'discordToken' as const,
    scope: 'delete' as const,
    keywords: ['role', 'unlink', 'remove'],
  },
  {
    name: 'discordGetSkuSubscription',
    description: discordGetSkuSubscription.description!,
    tool: discordGetSkuSubscription,
    requiredAuth: 'discordToken' as const,
    scope: 'read' as const,
    keywords: ['subscription', 'premium'],
  },
  {
    name: 'discordListSkuSubscriptions',
    description: discordListSkuSubscriptions.description!,
    tool: discordListSkuSubscriptions,
    requiredAuth: 'discordToken' as const,
    scope: 'read' as const,
    keywords: ['subscription', 'premium'],
  },
  {
    name: 'discordGetGateway',
    description: discordGetGateway.description!,
    tool: discordGetGateway,
    requiredAuth: 'discordToken' as const,
    scope: 'read' as const,
    keywords: ['websocket', 'realtime', 'bot'],
  },
  {
    name: 'discordListStickerPacks',
    description: discordListStickerPacks.description!,
    tool: discordListStickerPacks,
    requiredAuth: 'discordToken' as const,
    scope: 'read' as const,
    keywords: ['sticker', 'emoji'],
  },
];
