// @ts-nocheck
import {
  mongodbListDatabases,
  mongodbPingServer,
  mongodbListCollections,
  mongodbDatabaseStats,
  mongodbCollectionStats,
  mongodbCreateCollection,
  mongodbDropCollection,
  mongodbRenameCollection,
} from './databases.js';
import {
  mongodbFindDocuments,
  mongodbFindOne,
  mongodbInsertOne,
  mongodbInsertMany,
  mongodbUpdateOne,
  mongodbUpdateMany,
  mongodbReplaceOne,
  mongodbDeleteOne,
  mongodbDeleteMany,
  mongodbFindOneAndUpdate,
  mongodbFindOneAndDelete,
  mongodbBulkWrite,
} from './documents.js';
import {
  mongodbAggregate,
  mongodbCountDocuments,
  mongodbEstimatedDocumentCount,
  mongodbDistinct,
} from './aggregation.js';
import { mongodbCreateIndex, mongodbListIndexes, mongodbDropIndex } from './indexes.js';

export {
  mongodbListDatabases,
  mongodbPingServer,
  mongodbListCollections,
  mongodbDatabaseStats,
  mongodbCollectionStats,
  mongodbCreateCollection,
  mongodbDropCollection,
  mongodbRenameCollection,
  mongodbFindDocuments,
  mongodbFindOne,
  mongodbInsertOne,
  mongodbInsertMany,
  mongodbUpdateOne,
  mongodbUpdateMany,
  mongodbReplaceOne,
  mongodbDeleteOne,
  mongodbDeleteMany,
  mongodbFindOneAndUpdate,
  mongodbFindOneAndDelete,
  mongodbBulkWrite,
  mongodbAggregate,
  mongodbCountDocuments,
  mongodbEstimatedDocumentCount,
  mongodbDistinct,
  mongodbCreateIndex,
  mongodbListIndexes,
  mongodbDropIndex,
};

const auth = 'mongodbCredentials' as const;

export const mongodbTools = [
  { name: 'mongodbListDatabases', description: 'List databases on the MongoDB server with sizes. Use to discover what data is available before querying.', tool: mongodbListDatabases, requiredAuth: auth, scope: 'read' as const },
  { name: 'mongodbPingServer', description: 'Ping the MongoDB server to verify connectivity and get server hello metadata. Use to validate the connection.', tool: mongodbPingServer, requiredAuth: auth, scope: 'read' as const },
  { name: 'mongodbListCollections', description: 'List collections (and views) in a database with their types. Use to discover queryable collections.', tool: mongodbListCollections, requiredAuth: auth, scope: 'read' as const },
  { name: 'mongodbDatabaseStats', description: 'Get database storage stats: data size, index size, collection and object counts. Use for capacity review.', tool: mongodbDatabaseStats, requiredAuth: auth, scope: 'read' as const },
  { name: 'mongodbCollectionStats', description: 'Get collection stats: document count, sizes, index details and shard info. Use to inspect a collection before heavy queries.', tool: mongodbCollectionStats, requiredAuth: auth, scope: 'read' as const },
  { name: 'mongodbCreateCollection', description: 'Create a new collection, optionally capped or with a JSON-schema validator. Use before inserting into a fresh namespace.', tool: mongodbCreateCollection, requiredAuth: auth, scope: 'write' as const },
  { name: 'mongodbDropCollection', description: 'Drop a collection and all its documents and indexes. Irreversible — confirm with the user first.', tool: mongodbDropCollection, requiredAuth: auth, scope: 'delete' as const },
  { name: 'mongodbRenameCollection', description: 'Rename a collection within its database. Updates the namespace; indexes move with it.', tool: mongodbRenameCollection, requiredAuth: auth, scope: 'write' as const },
  { name: 'mongodbFindDocuments', description: 'Find documents with filter, projection, sort, skip and limit. Defaults to 50 docs (max 1000). Use for reads and exploration.', tool: mongodbFindDocuments, requiredAuth: auth, scope: 'read' as const },
  { name: 'mongodbFindOne', description: 'Find the first document matching a filter. Use for fetching a single record by id or unique key.', tool: mongodbFindOne, requiredAuth: auth, scope: 'read' as const },
  { name: 'mongodbInsertOne', description: 'Insert a single document into a collection. Returns the generated _id.', tool: mongodbInsertOne, requiredAuth: auth, scope: 'write' as const },
  { name: 'mongodbInsertMany', description: 'Insert multiple documents in one batch (max 1000 per call). Returns inserted ids.', tool: mongodbInsertMany, requiredAuth: auth, scope: 'write' as const },
  { name: 'mongodbUpdateOne', description: 'Update the first document matching a filter with $set/$inc/etc. Supports upsert.', tool: mongodbUpdateOne, requiredAuth: auth, scope: 'write' as const },
  { name: 'mongodbUpdateMany', description: 'Update all documents matching a filter. Use for bulk status changes and migrations.', tool: mongodbUpdateMany, requiredAuth: auth, scope: 'write' as const },
  { name: 'mongodbReplaceOne', description: 'Replace a whole document (keeping _id) with a new one. Supports upsert.', tool: mongodbReplaceOne, requiredAuth: auth, scope: 'write' as const },
  { name: 'mongodbDeleteOne', description: 'Delete the first document matching a filter.', tool: mongodbDeleteOne, requiredAuth: auth, scope: 'delete' as const },
  { name: 'mongodbDeleteMany', description: 'Delete all documents matching a filter. Returns the deleted count — confirm scope with the user first on broad filters.', tool: mongodbDeleteMany, requiredAuth: auth, scope: 'delete' as const },
  { name: 'mongodbFindOneAndUpdate', description: 'Atomically update one document and return it (before or after the change). Use for counters, reservations and read-modify-write.', tool: mongodbFindOneAndUpdate, requiredAuth: auth, scope: 'write' as const },
  { name: 'mongodbFindOneAndDelete', description: 'Atomically delete one document and return it. Use for queue-style claim-and-remove patterns.', tool: mongodbFindOneAndDelete, requiredAuth: auth, scope: 'write' as const },
  { name: 'mongodbBulkWrite', description: 'Run mixed insert/update/delete operations in one batch for efficiency.', tool: mongodbBulkWrite, requiredAuth: auth, scope: 'write' as const },
  { name: 'mongodbAggregate', description: 'Run an aggregation pipeline ($match, $group, $lookup, $unwind, …) for analytics and reports.', tool: mongodbAggregate, requiredAuth: auth, scope: 'read' as const },
  { name: 'mongodbCountDocuments', description: 'Count documents matching a filter exactly (scans the collection). Use for filtered totals.', tool: mongodbCountDocuments, requiredAuth: auth, scope: 'read' as const },
  { name: 'mongodbEstimatedDocumentCount', description: 'Fast estimated collection size from metadata (no filter). Use for quick size checks on large collections.', tool: mongodbEstimatedDocumentCount, requiredAuth: auth, scope: 'read' as const },
  { name: 'mongodbDistinct', description: 'List distinct values of a field, optionally filtered. Use for dropdowns, facets and cardinality checks.', tool: mongodbDistinct, requiredAuth: auth, scope: 'read' as const },
  { name: 'mongodbCreateIndex', description: 'Create an index (single, compound, text, geospatial, TTL) to speed queries and enforce uniqueness.', tool: mongodbCreateIndex, requiredAuth: auth, scope: 'write' as const },
  { name: 'mongodbListIndexes', description: 'List indexes on a collection with keys, uniqueness and sizes. Use to review query coverage.', tool: mongodbListIndexes, requiredAuth: auth, scope: 'read' as const },
  { name: 'mongodbDropIndex', description: 'Drop an index by name (use "*" for all non-_id indexes). Use to remove unused or blocking indexes.', tool: mongodbDropIndex, requiredAuth: auth, scope: 'delete' as const },
];
