// @ts-nocheck
import {
  firebaseCreateUser,
  firebaseDeleteUser,
  firebaseListUsers,
  firebaseLookupUser,
  firebaseUpdateUser,
} from './auth.js';
import {
  firebaseCreateDocument,
  firebaseDeleteDocument,
  firebaseGetDocument,
  firebaseListDatabases,
  firebaseListDocuments,
  firebaseRunQuery,
  firebaseUpdateDocument,
} from './firestore.js';
import {
  firebaseAddFirebase,
  firebaseCreateAndroidApp,
  firebaseCreateIosApp,
  firebaseCreateWebApp,
  firebaseGetAdminSdkConfig,
  firebaseGetProject,
  firebaseGetWebAppConfig,
  firebaseListAndroidApps,
  firebaseListAvailableProjects,
  firebaseListIosApps,
  firebaseListProjects,
  firebaseListWebApps,
  firebaseSearchApps,
  firebaseUpdateProject,
} from './management.js';
import { firebaseSendMessage } from './messaging.js';
import {
  firebaseGetRemoteConfig,
  firebaseListRemoteConfigVersions,
  firebasePublishRemoteConfig,
  firebaseRollbackRemoteConfig,
} from './remote-config.js';
import {
  firebaseRtdbDelete,
  firebaseRtdbGet,
  firebaseRtdbGetRules,
  firebaseRtdbPush,
  firebaseRtdbSet,
  firebaseRtdbUpdate,
} from './rtdb.js';

export {
  firebaseListProjects,
  firebaseGetProject,
  firebaseListAvailableProjects,
  firebaseAddFirebase,
  firebaseUpdateProject,
  firebaseGetAdminSdkConfig,
  firebaseSearchApps,
  firebaseListAndroidApps,
  firebaseCreateAndroidApp,
  firebaseListIosApps,
  firebaseCreateIosApp,
  firebaseListWebApps,
  firebaseCreateWebApp,
  firebaseGetWebAppConfig,
  firebaseListDatabases,
  firebaseGetDocument,
  firebaseCreateDocument,
  firebaseUpdateDocument,
  firebaseDeleteDocument,
  firebaseListDocuments,
  firebaseRunQuery,
  firebaseRtdbGet,
  firebaseRtdbSet,
  firebaseRtdbUpdate,
  firebaseRtdbPush,
  firebaseRtdbDelete,
  firebaseRtdbGetRules,
  firebaseSendMessage,
  firebaseCreateUser,
  firebaseLookupUser,
  firebaseListUsers,
  firebaseUpdateUser,
  firebaseDeleteUser,
  firebaseGetRemoteConfig,
  firebasePublishRemoteConfig,
  firebaseListRemoteConfigVersions,
  firebaseRollbackRemoteConfig,
};

type Scope = 'read' | 'write' | 'delete';
function entry(
  name: string,
  description: string,
  toolRef: any,
  scope: Scope,
  keywords: string[] = [],
): {
  name: string;
  description: string;
  tool: any;
  requiredAuth: 'firebaseCredentials';
  scope: Scope;
  keywords: string[];
} {
  return { name, description, tool: toolRef, requiredAuth: 'firebaseCredentials', scope, keywords };
}

export const firebaseTools = [
  entry(
    'firebaseListProjects',
    'List Firebase projects accessible to the service account.',
    firebaseListProjects,
    'read',
    ['project', 'projects'],
  ),
  entry(
    'firebaseGetProject',
    'Get a Firebase project by ID, including project number and resources.',
    firebaseGetProject,
    'read',
    ['project details', 'project info'],
  ),
  entry(
    'firebaseListAvailableProjects',
    'List Google Cloud projects that can have Firebase services enabled.',
    firebaseListAvailableProjects,
    'read',
    ['available', 'onboardable'],
  ),
  entry(
    'firebaseAddFirebase',
    'Enable Firebase services on an existing Google Cloud project.',
    firebaseAddFirebase,
    'write',
    ['enable firebase', 'onboard'],
  ),
  entry(
    'firebaseUpdateProject',
    'Update a Firebase project display name.',
    firebaseUpdateProject,
    'write',
    ['rename project'],
  ),
  entry(
    'firebaseGetAdminSdkConfig',
    'Get the Admin SDK config for a project to initialize server SDKs.',
    firebaseGetAdminSdkConfig,
    'read',
    ['sdk config', 'server config'],
  ),
  entry(
    'firebaseSearchApps',
    'List all apps (Android, iOS, web) in a Firebase project in one call.',
    firebaseSearchApps,
    'read',
    ['apps', 'applications'],
  ),
  entry(
    'firebaseListAndroidApps',
    'List Android apps in a Firebase project.',
    firebaseListAndroidApps,
    'read',
    ['android applications'],
  ),
  entry(
    'firebaseCreateAndroidApp',
    'Register a new Android app in a Firebase project.',
    firebaseCreateAndroidApp,
    'write',
    ['register android', 'package name'],
  ),
  entry(
    'firebaseListIosApps',
    'List iOS apps in a Firebase project.',
    firebaseListIosApps,
    'read',
    ['ios applications', 'apple'],
  ),
  entry(
    'firebaseCreateIosApp',
    'Register a new iOS app in a Firebase project.',
    firebaseCreateIosApp,
    'write',
    ['register ios', 'bundle id'],
  ),
  entry(
    'firebaseListWebApps',
    'List web apps in a Firebase project.',
    firebaseListWebApps,
    'read',
    ['web applications'],
  ),
  entry(
    'firebaseCreateWebApp',
    'Register a new web app in a Firebase project.',
    firebaseCreateWebApp,
    'write',
    ['register web'],
  ),
  entry(
    'firebaseGetWebAppConfig',
    'Get the firebaseConfig for a web app to initialize client SDKs.',
    firebaseGetWebAppConfig,
    'read',
    ['firebase config', 'web config', 'api key'],
  ),
  entry(
    'firebaseListDatabases',
    'List Firestore databases in the project.',
    firebaseListDatabases,
    'read',
    ['firestore instances'],
  ),
  entry(
    'firebaseGetDocument',
    'Get a Firestore document by path with plain-JSON fields.',
    firebaseGetDocument,
    'read',
    ['read document', 'fetch doc'],
  ),
  entry(
    'firebaseCreateDocument',
    'Create a Firestore document in a collection with plain-JSON data.',
    firebaseCreateDocument,
    'write',
    ['add document', 'write doc'],
  ),
  entry(
    'firebaseUpdateDocument',
    'Update (or set) fields on a Firestore document, optionally masked.',
    firebaseUpdateDocument,
    'write',
    ['patch document', 'edit doc'],
  ),
  entry(
    'firebaseDeleteDocument',
    'Delete a Firestore document by path.',
    firebaseDeleteDocument,
    'delete',
    ['remove document'],
  ),
  entry(
    'firebaseListDocuments',
    'List documents in a Firestore collection with plain-JSON fields.',
    firebaseListDocuments,
    'read',
    ['collection', 'list docs'],
  ),
  entry(
    'firebaseRunQuery',
    'Run a Firestore structured query (filters, ordering, limit).',
    firebaseRunQuery,
    'read',
    ['query collection', 'filter documents', 'where'],
  ),
  entry(
    'firebaseRtdbGet',
    'Read data from a Realtime Database path, with optional query filters.',
    firebaseRtdbGet,
    'read',
    ['realtime database read', 'rtdb fetch'],
  ),
  entry(
    'firebaseRtdbSet',
    'Write (overwrite) data at a Realtime Database path.',
    firebaseRtdbSet,
    'write',
    ['realtime database write'],
  ),
  entry(
    'firebaseRtdbUpdate',
    'Update specific children at a Realtime Database path.',
    firebaseRtdbUpdate,
    'write',
    ['realtime database patch', 'merge'],
  ),
  entry(
    'firebaseRtdbPush',
    'Append data to a Realtime Database list with an auto push key.',
    firebaseRtdbPush,
    'write',
    ['realtime database append', 'push key'],
  ),
  entry(
    'firebaseRtdbDelete',
    'Delete data at a Realtime Database path.',
    firebaseRtdbDelete,
    'delete',
    ['realtime database remove'],
  ),
  entry(
    'firebaseRtdbGetRules',
    'Read the Realtime Database security rules.',
    firebaseRtdbGetRules,
    'read',
    ['security rules', 'permissions'],
  ),
  entry(
    'firebaseSendMessage',
    'Send an FCM push notification or data message to a token, topic, or condition.',
    firebaseSendMessage,
    'write',
    ['push notification', 'cloud messaging', 'fcm send'],
  ),
  entry(
    'firebaseCreateUser',
    'Create a Firebase Auth user (email, phone, or anonymous).',
    firebaseCreateUser,
    'write',
    ['signup', 'register user', 'authentication'],
  ),
  entry(
    'firebaseLookupUser',
    'Look up Firebase Auth users by UID, email, or phone.',
    firebaseLookupUser,
    'read',
    ['find user', 'get user'],
  ),
  entry('firebaseListUsers', 'Download Firebase Auth users in pages.', firebaseListUsers, 'read', [
    'all users',
  ]),
  entry(
    'firebaseUpdateUser',
    'Update a Firebase Auth user (email, password, disable, claims).',
    firebaseUpdateUser,
    'write',
    ['edit user', 'disable user'],
  ),
  entry('firebaseDeleteUser', 'Delete a Firebase Auth user by UID.', firebaseDeleteUser, 'delete', [
    'remove user',
  ]),
  entry(
    'firebaseGetRemoteConfig',
    'Get the active Remote Config template and ETag.',
    firebaseGetRemoteConfig,
    'read',
    ['remote configuration', 'feature flags'],
  ),
  entry(
    'firebasePublishRemoteConfig',
    'Publish a Remote Config template with ETag concurrency control.',
    firebasePublishRemoteConfig,
    'write',
    ['update remote configuration', 'deploy flags'],
  ),
  entry(
    'firebaseListRemoteConfigVersions',
    'List published Remote Config template versions.',
    firebaseListRemoteConfigVersions,
    'read',
    ['config history'],
  ),
  entry(
    'firebaseRollbackRemoteConfig',
    'Roll back the Remote Config template to a previous version.',
    firebaseRollbackRemoteConfig,
    'write',
    ['revert config'],
  ),
];
