// @ts-nocheck
import {
  outlookListMessages,
  outlookGetMessage,
  outlookSendMail,
  outlookCreateDraft,
  outlookUpdateDraft,
  outlookSendDraft,
  outlookDeleteMessage,
  outlookReplyMessage,
  outlookReplyAllMessage,
  outlookForwardMessage,
  outlookCreateReplyDraft,
  outlookCreateForwardDraft,
  outlookSetMessageReadStatus,
  outlookMoveMessage,
  outlookCopyMessage,
  outlookListMailFolders,
  outlookGetMailFolder,
  outlookCreateMailFolder,
  outlookUpdateMailFolder,
  outlookDeleteMailFolder,
  outlookListFolderMessages,
  outlookListAttachments,
  outlookGetAttachment,
  outlookAddAttachment,
  outlookDeleteAttachment,
  outlookListMessageRules,
  outlookCreateMessageRule,
  outlookUpdateMessageRule,
  outlookDeleteMessageRule,
  outlookListCategories,
  outlookCreateCategory,
  outlookUpdateCategory,
  outlookDeleteCategory,
  outlookListFocusedOverrides,
  outlookCreateFocusedOverride,
  outlookDeleteFocusedOverride,
} from './mail.js';
import {
  outlookListCalendars,
  outlookGetCalendar,
  outlookCreateCalendar,
  outlookUpdateCalendar,
  outlookDeleteCalendar,
  outlookListEvents,
  outlookListCalendarView,
  outlookGetEvent,
  outlookCreateEvent,
  outlookUpdateEvent,
  outlookDeleteEvent,
  outlookCancelEvent,
  outlookAcceptEvent,
  outlookTentativelyAcceptEvent,
  outlookDeclineEvent,
  outlookGetSchedule,
  outlookSnoozeReminder,
  outlookDismissReminder,
  outlookListEventAttachments,
  outlookAddEventAttachment,
  outlookDeleteEventAttachment,
} from './calendar.js';
import {
  outlookListContacts,
  outlookGetContact,
  outlookCreateContact,
  outlookUpdateContact,
  outlookDeleteContact,
  outlookListContactFolders,
  outlookCreateContactFolder,
  outlookUpdateContactFolder,
  outlookDeleteContactFolder,
  outlookListFolderContacts,
  outlookSearchPeople,
  outlookGetMe,
  outlookGetMyPhoto,
  outlookListSubscriptions,
  outlookGetSubscription,
  outlookCreateSubscription,
  outlookRenewSubscription,
  outlookDeleteSubscription,
} from './contacts.js';

export {
  outlookListMessages,
  outlookGetMessage,
  outlookSendMail,
  outlookCreateDraft,
  outlookUpdateDraft,
  outlookSendDraft,
  outlookDeleteMessage,
  outlookReplyMessage,
  outlookReplyAllMessage,
  outlookForwardMessage,
  outlookCreateReplyDraft,
  outlookCreateForwardDraft,
  outlookSetMessageReadStatus,
  outlookMoveMessage,
  outlookCopyMessage,
  outlookListMailFolders,
  outlookGetMailFolder,
  outlookCreateMailFolder,
  outlookUpdateMailFolder,
  outlookDeleteMailFolder,
  outlookListFolderMessages,
  outlookListAttachments,
  outlookGetAttachment,
  outlookAddAttachment,
  outlookDeleteAttachment,
  outlookListMessageRules,
  outlookCreateMessageRule,
  outlookUpdateMessageRule,
  outlookDeleteMessageRule,
  outlookListCategories,
  outlookCreateCategory,
  outlookUpdateCategory,
  outlookDeleteCategory,
  outlookListFocusedOverrides,
  outlookCreateFocusedOverride,
  outlookDeleteFocusedOverride,
  outlookListCalendars,
  outlookGetCalendar,
  outlookCreateCalendar,
  outlookUpdateCalendar,
  outlookDeleteCalendar,
  outlookListEvents,
  outlookListCalendarView,
  outlookGetEvent,
  outlookCreateEvent,
  outlookUpdateEvent,
  outlookDeleteEvent,
  outlookCancelEvent,
  outlookAcceptEvent,
  outlookTentativelyAcceptEvent,
  outlookDeclineEvent,
  outlookGetSchedule,
  outlookSnoozeReminder,
  outlookDismissReminder,
  outlookListEventAttachments,
  outlookAddEventAttachment,
  outlookDeleteEventAttachment,
  outlookListContacts,
  outlookGetContact,
  outlookCreateContact,
  outlookUpdateContact,
  outlookDeleteContact,
  outlookListContactFolders,
  outlookCreateContactFolder,
  outlookUpdateContactFolder,
  outlookDeleteContactFolder,
  outlookListFolderContacts,
  outlookSearchPeople,
  outlookGetMe,
  outlookGetMyPhoto,
  outlookListSubscriptions,
  outlookGetSubscription,
  outlookCreateSubscription,
  outlookRenewSubscription,
  outlookDeleteSubscription,
};

const AUTH = 'outlookToken' as const;

export const outlookTools = [
  {
    name: 'outlookListMessages',
    description: 'List or search inbox messages.',
    tool: outlookListMessages,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['email', 'emails', 'inbox'],
  },
  {
    name: 'outlookGetMessage',
    description: 'Get one message with body and headers.',
    tool: outlookGetMessage,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['email', 'fetch'],
  },
  {
    name: 'outlookSendMail',
    description: 'Send an email in one call.',
    tool: outlookSendMail,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['mail', 'compose'],
  },
  {
    name: 'outlookCreateDraft',
    description: 'Create a draft message.',
    tool: outlookCreateDraft,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['compose', 'unsent'],
  },
  {
    name: 'outlookUpdateDraft',
    description: 'Update a draft message.',
    tool: outlookUpdateDraft,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['edit', 'compose'],
  },
  {
    name: 'outlookSendDraft',
    description: 'Send an existing draft.',
    tool: outlookSendDraft,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['dispatch'],
  },
  {
    name: 'outlookDeleteMessage',
    description: 'Delete a message.',
    tool: outlookDeleteMessage,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['email', 'remove'],
  },
  {
    name: 'outlookReplyMessage',
    description: 'Reply to a message.',
    tool: outlookReplyMessage,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['respond', 'answer'],
  },
  {
    name: 'outlookReplyAllMessage',
    description: 'Reply-all to a message.',
    tool: outlookReplyAllMessage,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['respond'],
  },
  {
    name: 'outlookForwardMessage',
    description: 'Forward a message.',
    tool: outlookForwardMessage,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['redirect', 'share'],
  },
  {
    name: 'outlookCreateReplyDraft',
    description: 'Create a reply draft.',
    tool: outlookCreateReplyDraft,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['respond', 'later'],
  },
  {
    name: 'outlookCreateForwardDraft',
    description: 'Create a forward draft.',
    tool: outlookCreateForwardDraft,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['share', 'later'],
  },
  {
    name: 'outlookSetMessageReadStatus',
    description: 'Mark a message read or unread.',
    tool: outlookSetMessageReadStatus,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['seen', 'unseen'],
  },
  {
    name: 'outlookMoveMessage',
    description: 'Move a message to another folder.',
    tool: outlookMoveMessage,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['organize', 'archive'],
  },
  {
    name: 'outlookCopyMessage',
    description: 'Copy a message to another folder.',
    tool: outlookCopyMessage,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['duplicate'],
  },
  {
    name: 'outlookListMailFolders',
    description: 'List mail folders with counts.',
    tool: outlookListMailFolders,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['directories', 'labels'],
  },
  {
    name: 'outlookGetMailFolder',
    description: 'Get one mail folder.',
    tool: outlookGetMailFolder,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['directory', 'fetch'],
  },
  {
    name: 'outlookCreateMailFolder',
    description: 'Create a mail folder.',
    tool: outlookCreateMailFolder,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['directory', 'organize'],
  },
  {
    name: 'outlookUpdateMailFolder',
    description: 'Rename a mail folder.',
    tool: outlookUpdateMailFolder,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['directory', 'rename'],
  },
  {
    name: 'outlookDeleteMailFolder',
    description: 'Delete a mail folder.',
    tool: outlookDeleteMailFolder,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['directory', 'remove'],
  },
  {
    name: 'outlookListFolderMessages',
    description: 'List messages in one folder.',
    tool: outlookListFolderMessages,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['emails', 'browse'],
  },
  {
    name: 'outlookListAttachments',
    description: 'List attachments of a message.',
    tool: outlookListAttachments,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['files', 'download'],
  },
  {
    name: 'outlookGetAttachment',
    description: 'Get one attachment metadata/content.',
    tool: outlookGetAttachment,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['file', 'fetch'],
  },
  {
    name: 'outlookAddAttachment',
    description: 'Attach a file to a draft.',
    tool: outlookAddAttachment,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['file', 'upload'],
  },
  {
    name: 'outlookDeleteAttachment',
    description: 'Delete a draft attachment.',
    tool: outlookDeleteAttachment,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['file', 'remove'],
  },
  {
    name: 'outlookListMessageRules',
    description: 'List inbox message rules.',
    tool: outlookListMessageRules,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['filters', 'automation'],
  },
  {
    name: 'outlookCreateMessageRule',
    description: 'Create an inbox rule.',
    tool: outlookCreateMessageRule,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['filter', 'automate'],
  },
  {
    name: 'outlookUpdateMessageRule',
    description: 'Update an inbox rule.',
    tool: outlookUpdateMessageRule,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['filter', 'edit'],
  },
  {
    name: 'outlookDeleteMessageRule',
    description: 'Delete an inbox rule.',
    tool: outlookDeleteMessageRule,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['filter', 'remove'],
  },
  {
    name: 'outlookListCategories',
    description: 'List master categories.',
    tool: outlookListCategories,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['labels', 'colors'],
  },
  {
    name: 'outlookCreateCategory',
    description: 'Create a master category.',
    tool: outlookCreateCategory,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['label', 'tag'],
  },
  {
    name: 'outlookUpdateCategory',
    description: 'Update a master category.',
    tool: outlookUpdateCategory,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['label', 'rename'],
  },
  {
    name: 'outlookDeleteCategory',
    description: 'Delete a master category.',
    tool: outlookDeleteCategory,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['label', 'remove'],
  },
  {
    name: 'outlookListFocusedOverrides',
    description: 'List Focused Inbox overrides.',
    tool: outlookListFocusedOverrides,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['priority', 'senders'],
  },
  {
    name: 'outlookCreateFocusedOverride',
    description: 'Classify a sender as focused/other.',
    tool: outlookCreateFocusedOverride,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['priority', 'sender'],
  },
  {
    name: 'outlookDeleteFocusedOverride',
    description: 'Delete a focused override.',
    tool: outlookDeleteFocusedOverride,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['priority', 'remove'],
  },
  {
    name: 'outlookListCalendars',
    description: 'List calendars.',
    tool: outlookListCalendars,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['schedules'],
  },
  {
    name: 'outlookGetCalendar',
    description: 'Get one calendar.',
    tool: outlookGetCalendar,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['schedule', 'fetch'],
  },
  {
    name: 'outlookCreateCalendar',
    description: 'Create a calendar.',
    tool: outlookCreateCalendar,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['schedule', 'new'],
  },
  {
    name: 'outlookUpdateCalendar',
    description: 'Update a calendar.',
    tool: outlookUpdateCalendar,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['schedule', 'edit'],
  },
  {
    name: 'outlookDeleteCalendar',
    description: 'Delete a calendar.',
    tool: outlookDeleteCalendar,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['schedule', 'remove'],
  },
  {
    name: 'outlookListEvents',
    description: 'List events with filter and paging.',
    tool: outlookListEvents,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['meetings', 'appointments'],
  },
  {
    name: 'outlookListCalendarView',
    description: 'List occurrences in a time window.',
    tool: outlookListCalendarView,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['agenda', 'meetings'],
  },
  {
    name: 'outlookGetEvent',
    description: 'Get one event.',
    tool: outlookGetEvent,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['meeting', 'fetch'],
  },
  {
    name: 'outlookCreateEvent',
    description: 'Create a meeting/event.',
    tool: outlookCreateEvent,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['meeting', 'schedule', 'invite'],
  },
  {
    name: 'outlookUpdateEvent',
    description: 'Update an event.',
    tool: outlookUpdateEvent,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['meeting', 'reschedule'],
  },
  {
    name: 'outlookDeleteEvent',
    description: 'Delete an event.',
    tool: outlookDeleteEvent,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['meeting', 'remove'],
  },
  {
    name: 'outlookCancelEvent',
    description: 'Cancel a meeting with notification.',
    tool: outlookCancelEvent,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['meeting', 'notify'],
  },
  {
    name: 'outlookAcceptEvent',
    description: 'Accept a meeting invitation.',
    tool: outlookAcceptEvent,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['rsvp', 'yes'],
  },
  {
    name: 'outlookTentativelyAcceptEvent',
    description: 'Tentatively accept a meeting.',
    tool: outlookTentativelyAcceptEvent,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['rsvp', 'maybe'],
  },
  {
    name: 'outlookDeclineEvent',
    description: 'Decline a meeting invitation.',
    tool: outlookDeclineEvent,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['rsvp', 'no'],
  },
  {
    name: 'outlookGetSchedule',
    description: 'Get free/busy schedule for attendees.',
    tool: outlookGetSchedule,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['availability', 'freebusy'],
  },
  {
    name: 'outlookSnoozeReminder',
    description: 'Snooze an event reminder.',
    tool: outlookSnoozeReminder,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['later', 'remind'],
  },
  {
    name: 'outlookDismissReminder',
    description: 'Dismiss an event reminder.',
    tool: outlookDismissReminder,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['clear'],
  },
  {
    name: 'outlookListEventAttachments',
    description: 'List event attachments.',
    tool: outlookListEventAttachments,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['files', 'meeting'],
  },
  {
    name: 'outlookAddEventAttachment',
    description: 'Attach a file to an event.',
    tool: outlookAddEventAttachment,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['file', 'upload'],
  },
  {
    name: 'outlookDeleteEventAttachment',
    description: 'Delete an event attachment.',
    tool: outlookDeleteEventAttachment,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['file', 'remove'],
  },
  {
    name: 'outlookListContacts',
    description: 'List personal contacts.',
    tool: outlookListContacts,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['address-book', 'people'],
  },
  {
    name: 'outlookGetContact',
    description: 'Get one contact.',
    tool: outlookGetContact,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['address-book', 'fetch'],
  },
  {
    name: 'outlookCreateContact',
    description: 'Create a contact.',
    tool: outlookCreateContact,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['address-book', 'add'],
  },
  {
    name: 'outlookUpdateContact',
    description: 'Update a contact.',
    tool: outlookUpdateContact,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['address-book', 'edit'],
  },
  {
    name: 'outlookDeleteContact',
    description: 'Delete a contact.',
    tool: outlookDeleteContact,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['address-book', 'remove'],
  },
  {
    name: 'outlookListContactFolders',
    description: 'List contact folders.',
    tool: outlookListContactFolders,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['groups', 'directories'],
  },
  {
    name: 'outlookCreateContactFolder',
    description: 'Create a contact folder.',
    tool: outlookCreateContactFolder,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['group', 'organize'],
  },
  {
    name: 'outlookUpdateContactFolder',
    description: 'Rename a contact folder.',
    tool: outlookUpdateContactFolder,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['group', 'rename'],
  },
  {
    name: 'outlookDeleteContactFolder',
    description: 'Delete a contact folder.',
    tool: outlookDeleteContactFolder,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['group', 'remove'],
  },
  {
    name: 'outlookListFolderContacts',
    description: 'List contacts in a folder.',
    tool: outlookListFolderContacts,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['group', 'browse'],
  },
  {
    name: 'outlookSearchPeople',
    description: 'Fuzzy-search relevant people.',
    tool: outlookSearchPeople,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['directory', 'autocomplete', 'lookup'],
  },
  {
    name: 'outlookGetMe',
    description: 'Get signed-in user profile.',
    tool: outlookGetMe,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['profile', 'account', 'whoami'],
  },
  {
    name: 'outlookGetMyPhoto',
    description: 'Get profile photo as base64.',
    tool: outlookGetMyPhoto,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['avatar', 'picture'],
  },
  {
    name: 'outlookListSubscriptions',
    description: 'List change-notification subscriptions.',
    tool: outlookListSubscriptions,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['webhooks', 'notifications'],
  },
  {
    name: 'outlookGetSubscription',
    description: 'Get one subscription.',
    tool: outlookGetSubscription,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['webhook', 'fetch'],
  },
  {
    name: 'outlookCreateSubscription',
    description: 'Subscribe to change notifications.',
    tool: outlookCreateSubscription,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['webhook', 'watch'],
  },
  {
    name: 'outlookRenewSubscription',
    description: 'Extend a subscription expiry.',
    tool: outlookRenewSubscription,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['webhook', 'extend'],
  },
  {
    name: 'outlookDeleteSubscription',
    description: 'Delete a subscription.',
    tool: outlookDeleteSubscription,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['webhook', 'remove'],
  },
];
