// @ts-nocheck
import {
  mermaidFlowchartGuide,
  mermaidSequenceGuide,
  mermaidClassGuide,
  mermaidStateGuide,
  mermaidErGuide,
  mermaidJourneyGuide,
  mermaidGanttGuide,
  mermaidPieGuide,
  mermaidQuadrantGuide,
  mermaidRequirementGuide,
  mermaidGitGraphGuide,
  mermaidC4Guide,
  mermaidMindmapGuide,
  mermaidTimelineGuide,
  mermaidZenUmlGuide,
  mermaidSankeyGuide,
  mermaidXyChartGuide,
  mermaidBlockGuide,
  mermaidPacketGuide,
  mermaidKanbanGuide,
  mermaidArchitectureGuide,
  mermaidRadarGuide,
  mermaidTreemapGuide,
  mermaidVennGuide,
  mermaidIshikawaGuide,
  mermaidInfoGuide,
  mermaidListDiagramTypes,
  mermaidDirectivesGuide,
  mermaidValidateDiagram,
  mermaidBuildRenderUrl,
} from './tools.js';

export {
  mermaidFlowchartGuide,
  mermaidSequenceGuide,
  mermaidClassGuide,
  mermaidStateGuide,
  mermaidErGuide,
  mermaidJourneyGuide,
  mermaidGanttGuide,
  mermaidPieGuide,
  mermaidQuadrantGuide,
  mermaidRequirementGuide,
  mermaidGitGraphGuide,
  mermaidC4Guide,
  mermaidMindmapGuide,
  mermaidTimelineGuide,
  mermaidZenUmlGuide,
  mermaidSankeyGuide,
  mermaidXyChartGuide,
  mermaidBlockGuide,
  mermaidPacketGuide,
  mermaidKanbanGuide,
  mermaidArchitectureGuide,
  mermaidRadarGuide,
  mermaidTreemapGuide,
  mermaidVennGuide,
  mermaidIshikawaGuide,
  mermaidInfoGuide,
  mermaidListDiagramTypes,
  mermaidDirectivesGuide,
  mermaidValidateDiagram,
  mermaidBuildRenderUrl,
};

export const mermaidTools = [
  {
    name: 'mermaidFlowchartGuide',
    description: 'Flowchart syntax guide.',
    tool: mermaidFlowchartGuide,
    scope: 'read' as const,
    keywords: ['graph', 'workflow', 'process', 'diagram'],
  },
  {
    name: 'mermaidSequenceGuide',
    description: 'Sequence diagram guide.',
    tool: mermaidSequenceGuide,
    scope: 'read' as const,
    keywords: ['interactions', 'messages', 'api'],
  },
  {
    name: 'mermaidClassGuide',
    description: 'Class diagram guide.',
    tool: mermaidClassGuide,
    scope: 'read' as const,
    keywords: ['uml', 'model', 'objects'],
  },
  {
    name: 'mermaidStateGuide',
    description: 'State diagram guide.',
    tool: mermaidStateGuide,
    scope: 'read' as const,
    keywords: ['lifecycle', 'statemachine', 'uml'],
  },
  {
    name: 'mermaidErGuide',
    description: 'Entity-relationship guide.',
    tool: mermaidErGuide,
    scope: 'read' as const,
    keywords: ['database', 'schema', 'erd'],
  },
  {
    name: 'mermaidJourneyGuide',
    description: 'User journey guide.',
    tool: mermaidJourneyGuide,
    scope: 'read' as const,
    keywords: ['experience', 'ux', 'map'],
  },
  {
    name: 'mermaidGanttGuide',
    description: 'Gantt chart guide.',
    tool: mermaidGanttGuide,
    scope: 'read' as const,
    keywords: ['timeline', 'project', 'roadmap'],
  },
  {
    name: 'mermaidPieGuide',
    description: 'Pie chart guide.',
    tool: mermaidPieGuide,
    scope: 'read' as const,
    keywords: ['proportion', 'share'],
  },
  {
    name: 'mermaidQuadrantGuide',
    description: 'Quadrant chart guide.',
    tool: mermaidQuadrantGuide,
    scope: 'read' as const,
    keywords: ['2x2', 'priority', 'matrix'],
  },
  {
    name: 'mermaidRequirementGuide',
    description: 'Requirement diagram guide.',
    tool: mermaidRequirementGuide,
    scope: 'read' as const,
    keywords: ['systems', 'traceability'],
  },
  {
    name: 'mermaidGitGraphGuide',
    description: 'Git graph guide.',
    tool: mermaidGitGraphGuide,
    scope: 'read' as const,
    keywords: ['branches', 'git', 'history'],
  },
  {
    name: 'mermaidC4Guide',
    description: 'C4 architecture guide.',
    tool: mermaidC4Guide,
    scope: 'read' as const,
    keywords: ['software', 'containers', 'plantuml'],
  },
  {
    name: 'mermaidMindmapGuide',
    description: 'Mindmap guide.',
    tool: mermaidMindmapGuide,
    scope: 'read' as const,
    keywords: ['brainstorm', 'ideas', 'tree'],
  },
  {
    name: 'mermaidTimelineGuide',
    description: 'Timeline guide.',
    tool: mermaidTimelineGuide,
    scope: 'read' as const,
    keywords: ['chronology', 'history', 'eras'],
  },
  {
    name: 'mermaidZenUmlGuide',
    description: 'ZenUML guide.',
    tool: mermaidZenUmlGuide,
    scope: 'read' as const,
    keywords: ['sequence', 'code'],
  },
  {
    name: 'mermaidSankeyGuide',
    description: 'Sankey flow guide.',
    tool: mermaidSankeyGuide,
    scope: 'read' as const,
    keywords: ['flows', 'funnel', 'energy'],
  },
  {
    name: 'mermaidXyChartGuide',
    description: 'XY chart guide.',
    tool: mermaidXyChartGuide,
    scope: 'read' as const,
    keywords: ['bar', 'line', 'metrics'],
  },
  {
    name: 'mermaidBlockGuide',
    description: 'Block diagram guide.',
    tool: mermaidBlockGuide,
    scope: 'read' as const,
    keywords: ['layout', 'grid', 'system'],
  },
  {
    name: 'mermaidPacketGuide',
    description: 'Packet bit-layout guide.',
    tool: mermaidPacketGuide,
    scope: 'read' as const,
    keywords: ['bits', 'network', 'register'],
  },
  {
    name: 'mermaidKanbanGuide',
    description: 'Kanban board guide.',
    tool: mermaidKanbanGuide,
    scope: 'read' as const,
    keywords: ['board', 'tasks', 'workflow'],
  },
  {
    name: 'mermaidArchitectureGuide',
    description: 'Architecture diagram guide.',
    tool: mermaidArchitectureGuide,
    scope: 'read' as const,
    keywords: ['cloud', 'infra', 'topology', 'icons'],
  },
  {
    name: 'mermaidRadarGuide',
    description: 'Radar chart guide.',
    tool: mermaidRadarGuide,
    scope: 'read' as const,
    keywords: ['spider', 'comparison', 'scores'],
  },
  {
    name: 'mermaidTreemapGuide',
    description: 'Treemap guide.',
    tool: mermaidTreemapGuide,
    scope: 'read' as const,
    keywords: ['hierarchy', 'budget', 'nested'],
  },
  {
    name: 'mermaidVennGuide',
    description: 'Venn diagram guide.',
    tool: mermaidVennGuide,
    scope: 'read' as const,
    keywords: ['sets', 'overlap'],
  },
  {
    name: 'mermaidIshikawaGuide',
    description: 'Ishikawa fishbone guide.',
    tool: mermaidIshikawaGuide,
    scope: 'read' as const,
    keywords: ['fishbone', 'root-cause', 'quality'],
  },
  {
    name: 'mermaidInfoGuide',
    description: 'Info box guide.',
    tool: mermaidInfoGuide,
    scope: 'read' as const,
    keywords: ['version', 'metadata'],
  },
  {
    name: 'mermaidListDiagramTypes',
    description: 'List every diagram type.',
    tool: mermaidListDiagramTypes,
    scope: 'read' as const,
    keywords: ['catalog', 'picker', 'which'],
  },
  {
    name: 'mermaidDirectivesGuide',
    description: 'Config/frontmatter/theming guide.',
    tool: mermaidDirectivesGuide,
    scope: 'read' as const,
    keywords: ['config', 'theme', 'frontmatter'],
  },
  {
    name: 'mermaidValidateDiagram',
    description: 'Static-check Mermaid code.',
    tool: mermaidValidateDiagram,
    scope: 'read' as const,
    keywords: ['lint', 'check', 'syntax', 'debug'],
  },
  {
    name: 'mermaidBuildRenderUrl',
    description: 'Build a mermaid.ink render URL.',
    tool: mermaidBuildRenderUrl,
    scope: 'read' as const,
    keywords: ['preview', 'image', 'svg', 'embed'],
  },
];
