// @ts-nocheck
import {
  confluenceCreatePage,
  confluenceGetPageById,
  confluenceUpdatePage,
  confluenceDeletePage,
  confluenceGetPages,
  confluenceSearchPages,
  confluenceGetChildPages,
  confluenceGetPageAncestors,
  confluenceGetPageVersions,
  confluenceGetPageLikeCount,
  confluenceFindTextSelections,
} from './pages.js';
import {
  confluenceCreateBlogpost,
  confluenceGetBlogpostById,
  confluenceGetBlogPosts,
  confluenceUpdateBlogpost,
  confluenceDeleteBlogpost,
  confluenceGetBlogpostLabels,
  confluenceGetBlogpostLikeCount,
  confluenceGetBlogpostOperations,
  confluenceGetBlogpostVersions,
  confluenceGetBlogpostVersionDetails,
  confluenceGetBlogPostContentProperties,
  confluenceCreateBlogpostProperty,
  confluenceUpdateBlogpostProperty,
  confluenceDeleteBlogpostProperty,
  confluenceGetBlogPostInlineComments,
  confluenceGetBlogPostsForLabel,
} from './blogposts.js';
import {
  confluenceCreateSpace,
  confluenceCreatePrivateSpace,
  confluenceGetSpaceById,
  confluenceGetSpaces,
  confluenceListSpaces,
  confluenceGetSpaceContents,
  confluenceDeleteSpace,
  confluenceGetSpaceLabels,
  confluenceGetSpaceContentLabels,
  confluenceGetSpaceProperties,
  confluenceCreateSpaceProperty,
  confluenceUpdateSpaceProperty,
  confluenceDeleteSpaceProperty,
} from './spaces.js';
import {
  confluenceCreateFooterComment,
  confluenceCreateInlineComment,
  confluenceGetPageFooterComments,
  confluenceGetPageInlineComments,
} from './comments.js';
import {
  confluenceAddContentLabel,
  confluenceGetLabels,
  confluenceGetPageLabels,
} from './labels.js';
import {
  confluenceGetAttachments,
  confluenceDownloadAttachment,
  confluenceGetAttachmentLabels,
} from './attachments.js';
import {
  confluenceCqlSearch,
  confluenceSearchContent,
  confluenceSearchSpaces,
  confluenceSearchUsers,
} from './search.js';
import {
  confluenceGetPageContentProperties,
  confluenceCreatePageProperty,
  confluenceUpdatePageContentProperty,
  confluenceDeletePageContentProperty,
  confluenceCreateWhiteboardProperty,
  confluenceUpdateWhiteboardContentProperty,
  confluenceDeleteWhiteboardContentProperty,
} from './properties.js';
import { confluenceCreateWhiteboard } from './whiteboards.js';
import { confluenceGetTasks, confluenceUpdateTask } from './tasks.js';
import {
  confluenceGetCurrentUser,
  confluenceGetAnonymousUser,
  confluenceValidateCredential,
  confluenceWhoAmI,
} from './users.js';
import { confluenceGetAuditLogs, confluenceGetContentRestrictions } from './misc.js';

export {
  confluenceCreatePage,
  confluenceGetPageById,
  confluenceUpdatePage,
  confluenceDeletePage,
  confluenceGetPages,
  confluenceSearchPages,
  confluenceGetChildPages,
  confluenceGetPageAncestors,
  confluenceGetPageVersions,
  confluenceGetPageLikeCount,
  confluenceFindTextSelections,
  confluenceCreateBlogpost,
  confluenceGetBlogpostById,
  confluenceGetBlogPosts,
  confluenceUpdateBlogpost,
  confluenceDeleteBlogpost,
  confluenceGetBlogpostLabels,
  confluenceGetBlogpostLikeCount,
  confluenceGetBlogpostOperations,
  confluenceGetBlogpostVersions,
  confluenceGetBlogpostVersionDetails,
  confluenceGetBlogPostContentProperties,
  confluenceCreateBlogpostProperty,
  confluenceUpdateBlogpostProperty,
  confluenceDeleteBlogpostProperty,
  confluenceGetBlogPostInlineComments,
  confluenceGetBlogPostsForLabel,
  confluenceCreateSpace,
  confluenceCreatePrivateSpace,
  confluenceGetSpaceById,
  confluenceGetSpaces,
  confluenceListSpaces,
  confluenceGetSpaceContents,
  confluenceDeleteSpace,
  confluenceGetSpaceLabels,
  confluenceGetSpaceContentLabels,
  confluenceGetSpaceProperties,
  confluenceCreateSpaceProperty,
  confluenceUpdateSpaceProperty,
  confluenceDeleteSpaceProperty,
  confluenceCreateFooterComment,
  confluenceCreateInlineComment,
  confluenceGetPageFooterComments,
  confluenceGetPageInlineComments,
  confluenceAddContentLabel,
  confluenceGetLabels,
  confluenceGetPageLabels,
  confluenceGetAttachments,
  confluenceDownloadAttachment,
  confluenceGetAttachmentLabels,
  confluenceCqlSearch,
  confluenceSearchContent,
  confluenceSearchSpaces,
  confluenceSearchUsers,
  confluenceGetPageContentProperties,
  confluenceCreatePageProperty,
  confluenceUpdatePageContentProperty,
  confluenceDeletePageContentProperty,
  confluenceCreateWhiteboardProperty,
  confluenceUpdateWhiteboardContentProperty,
  confluenceDeleteWhiteboardContentProperty,
  confluenceCreateWhiteboard,
  confluenceGetTasks,
  confluenceUpdateTask,
  confluenceGetCurrentUser,
  confluenceGetAnonymousUser,
  confluenceValidateCredential,
  confluenceWhoAmI,
  confluenceGetAuditLogs,
  confluenceGetContentRestrictions,
};

const auth = 'confluenceToken' as const;

export const confluenceTools = [
  {
    name: 'confluenceAddContentLabel',
    description: 'Tag a page or blog post with metadata labels for organization and search.',
    tool: confluenceAddContentLabel,
    requiredAuth: auth,
    scope: 'write' as const,
    keywords: ['tag'],
  },
  {
    name: 'confluenceCqlSearch',
    description:
      'Full CQL search across Confluence: full-text, title, label, space, type, creator and date filters.',
    tool: confluenceCqlSearch,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['find', 'search', 'cql', 'query'],
  },
  {
    name: 'confluenceCreateBlogpost',
    description: 'Publish a blog post (or draft) in a space.',
    tool: confluenceCreateBlogpost,
    requiredAuth: auth,
    scope: 'write' as const,
    keywords: ['new', 'post', 'article'],
  },
  {
    name: 'confluenceCreateBlogpostProperty',
    description: 'Add a custom metadata key-value property to a blog post.',
    tool: confluenceCreateBlogpostProperty,
    requiredAuth: auth,
    scope: 'write' as const,
    keywords: ['metadata'],
  },
  {
    name: 'confluenceCreateWhiteboardProperty',
    description: 'Attach custom metadata to a whiteboard.',
    tool: confluenceCreateWhiteboardProperty,
    requiredAuth: auth,
    scope: 'write' as const,
    keywords: ['metadata'],
  },
  {
    name: 'confluenceCreateFooterComment',
    description: 'Add a page-level comment (or a reply) without editing the body.',
    tool: confluenceCreateFooterComment,
    requiredAuth: auth,
    scope: 'write' as const,
    keywords: ['reply', 'discuss'],
  },
  {
    name: 'confluenceCreateInlineComment',
    description: 'Comment on highlighted page/blog text, or reply to an inline comment.',
    tool: confluenceCreateInlineComment,
    requiredAuth: auth,
    scope: 'write' as const,
    keywords: ['annotate', 'reply'],
  },
  {
    name: 'confluenceCreatePage',
    description: 'Create a new Confluence page in a space, optionally as a child page.',
    tool: confluenceCreatePage,
    requiredAuth: auth,
    scope: 'write' as const,
    keywords: ['new', 'doc', 'wiki'],
  },
  {
    name: 'confluenceCreatePageProperty',
    description: 'Add a custom metadata key-value property to a page.',
    tool: confluenceCreatePageProperty,
    requiredAuth: auth,
    scope: 'write' as const,
    keywords: ['metadata'],
  },
  {
    name: 'confluenceCreatePrivateSpace',
    description: 'Create a private space visible only to its creator.',
    tool: confluenceCreatePrivateSpace,
    requiredAuth: auth,
    scope: 'write' as const,
    keywords: ['new', 'personal'],
  },
  {
    name: 'confluenceCreateSpace',
    description: 'Create a new global or personal space for a knowledge area.',
    tool: confluenceCreateSpace,
    requiredAuth: auth,
    scope: 'write' as const,
    keywords: ['new', 'area', 'wiki'],
  },
  {
    name: 'confluenceCreateSpaceProperty',
    description: 'Add a custom metadata property to a space.',
    tool: confluenceCreateSpaceProperty,
    requiredAuth: auth,
    scope: 'write' as const,
    keywords: ['metadata'],
  },
  {
    name: 'confluenceCreateWhiteboard',
    description: 'Start a collaborative whiteboard in a space.',
    tool: confluenceCreateWhiteboard,
    requiredAuth: auth,
    scope: 'write' as const,
    keywords: ['new', 'board', 'draw'],
  },
  {
    name: 'confluenceDeleteBlogpost',
    description: 'Move a blog post to trash (or purge permanently).',
    tool: confluenceDeleteBlogpost,
    requiredAuth: auth,
    scope: 'delete' as const,
    keywords: ['trash', 'remove'],
  },
  {
    name: 'confluenceDeleteBlogpostProperty',
    description: 'Delete a custom metadata property from a blog post.',
    tool: confluenceDeleteBlogpostProperty,
    requiredAuth: auth,
    scope: 'delete' as const,
    keywords: ['remove'],
  },
  {
    name: 'confluenceDeletePageContentProperty',
    description: 'Delete a custom metadata property from a page.',
    tool: confluenceDeletePageContentProperty,
    requiredAuth: auth,
    scope: 'delete' as const,
    keywords: ['remove'],
  },
  {
    name: 'confluenceDeleteWhiteboardContentProperty',
    description: 'Delete a custom metadata property from a whiteboard.',
    tool: confluenceDeleteWhiteboardContentProperty,
    requiredAuth: auth,
    scope: 'delete' as const,
    keywords: ['remove'],
  },
  {
    name: 'confluenceDeletePage',
    description: 'Move a Confluence page to trash (recoverable).',
    tool: confluenceDeletePage,
    requiredAuth: auth,
    scope: 'delete' as const,
    keywords: ['trash', 'remove'],
  },
  {
    name: 'confluenceDeleteSpace',
    description: 'Permanently delete a space by key (async — reports completion status).',
    tool: confluenceDeleteSpace,
    requiredAuth: auth,
    scope: 'delete' as const,
    keywords: ['remove', 'permanent'],
  },
  {
    name: 'confluenceDeleteSpaceProperty',
    description: 'Delete a custom metadata property from a space.',
    tool: confluenceDeleteSpaceProperty,
    requiredAuth: auth,
    scope: 'delete' as const,
    keywords: ['remove'],
  },
  {
    name: 'confluenceDownloadAttachment',
    description: 'Download a page attachment as base64 (max ~4MB).',
    tool: confluenceDownloadAttachment,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['save', 'export', 'file'],
  },
  {
    name: 'confluenceFindTextSelections',
    description:
      'Find text occurrences in a page body with offsets and context for inline comments.',
    tool: confluenceFindTextSelections,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['find-in-page', 'offsets'],
  },
  {
    name: 'confluenceGetAttachmentLabels',
    description: 'List labels on an attachment.',
    tool: confluenceGetAttachmentLabels,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['tags'],
  },
  {
    name: 'confluenceGetAttachments',
    description: 'List attachments on a page with filenames, MIME types and versions.',
    tool: confluenceGetAttachments,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['files'],
  },
  {
    name: 'confluenceGetAuditLogs',
    description: 'Fetch Confluence audit records for compliance or troubleshooting.',
    tool: confluenceGetAuditLogs,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['audit', 'logs', 'compliance'],
  },
  {
    name: 'confluenceGetBlogpostById',
    description: 'Get a blog post by ID with metadata and body.',
    tool: confluenceGetBlogpostById,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: [],
  },
  {
    name: 'confluenceGetBlogpostLabels',
    description: 'List labels on a blog post.',
    tool: confluenceGetBlogpostLabels,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['tags'],
  },
  {
    name: 'confluenceGetBlogpostLikeCount',
    description: 'Get the total like count of a blog post.',
    tool: confluenceGetBlogpostLikeCount,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['likes'],
  },
  {
    name: 'confluenceGetBlogpostOperations',
    description: 'List permitted operations on a blog post.',
    tool: confluenceGetBlogpostOperations,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['permissions'],
  },
  {
    name: 'confluenceGetBlogPosts',
    description: 'List blog posts with pagination.',
    tool: confluenceGetBlogPosts,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['browse', 'articles'],
  },
  {
    name: 'confluenceGetBlogPostsForLabel',
    description: 'List blog posts carrying a given label ID.',
    tool: confluenceGetBlogPostsForLabel,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['tag'],
  },
  {
    name: 'confluenceGetBlogpostVersionDetails',
    description: 'Get metadata of a specific blog post version.',
    tool: confluenceGetBlogpostVersionDetails,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['history'],
  },
  {
    name: 'confluenceGetBlogpostVersions',
    description: 'List version history of a blog post.',
    tool: confluenceGetBlogpostVersions,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['history'],
  },
  {
    name: 'confluenceGetChildPages',
    description: 'List direct child pages of a parent page.',
    tool: confluenceGetChildPages,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['subpages', 'children', 'hierarchy'],
  },
  {
    name: 'confluenceGetBlogPostContentProperties',
    description: 'List custom metadata properties on a blog post.',
    tool: confluenceGetBlogPostContentProperties,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['metadata'],
  },
  {
    name: 'confluenceGetPageContentProperties',
    description: 'List custom metadata properties on a page.',
    tool: confluenceGetPageContentProperties,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['metadata'],
  },
  {
    name: 'confluenceGetContentRestrictions',
    description: 'Show view/edit restrictions on a page or blog post.',
    tool: confluenceGetContentRestrictions,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['permissions', 'access'],
  },
  {
    name: 'confluenceGetCurrentUser',
    description: 'Get the authenticated user (accountId, displayName, email).',
    tool: confluenceGetCurrentUser,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['me', 'profile'],
  },
  {
    name: 'confluenceGetBlogPostInlineComments',
    description: 'List inline comments on a blog post.',
    tool: confluenceGetBlogPostInlineComments,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['discussion'],
  },
  {
    name: 'confluenceGetLabels',
    description: 'Browse all site labels for discovery and paging.',
    tool: confluenceGetLabels,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['tags', 'browse'],
  },
  {
    name: 'confluenceGetPageLabels',
    description: 'List labels on a page.',
    tool: confluenceGetPageLabels,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['tags'],
  },
  {
    name: 'confluenceGetSpaceLabels',
    description: 'List labels on a space.',
    tool: confluenceGetSpaceLabels,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['tags'],
  },
  {
    name: 'confluenceGetSpaceContentLabels',
    description: 'List labels applied to content inside a space.',
    tool: confluenceGetSpaceContentLabels,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['tags'],
  },
  {
    name: 'confluenceGetPageAncestors',
    description: 'Get the ancestor chain of a page from root to parent.',
    tool: confluenceGetPageAncestors,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['parents', 'hierarchy', 'breadcrumb'],
  },
  {
    name: 'confluenceGetPageById',
    description: 'Get a Confluence page by ID with metadata and body.',
    tool: confluenceGetPageById,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: [],
  },
  {
    name: 'confluenceGetPageFooterComments',
    description: 'List root-level (footer) comments on a page.',
    tool: confluenceGetPageFooterComments,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['discussion'],
  },
  {
    name: 'confluenceGetPageInlineComments',
    description: 'List inline (text-anchored) comments on a page.',
    tool: confluenceGetPageInlineComments,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['annotations', 'discussion'],
  },
  {
    name: 'confluenceGetPageLikeCount',
    description: 'Get the total like count of a page.',
    tool: confluenceGetPageLikeCount,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['likes'],
  },
  {
    name: 'confluenceGetPages',
    description: 'List pages with space, status, title and subtype filters.',
    tool: confluenceGetPages,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['browse'],
  },
  {
    name: 'confluenceGetPageVersions',
    description: 'List version history of a page (get latest number before updating).',
    tool: confluenceGetPageVersions,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['history'],
  },
  {
    name: 'confluenceGetSpaceById',
    description: 'Get a space by numeric ID.',
    tool: confluenceGetSpaceById,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: [],
  },
  {
    name: 'confluenceGetSpaceContents',
    description: 'List pages or blog posts inside a space by space key.',
    tool: confluenceGetSpaceContents,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['browse'],
  },
  {
    name: 'confluenceGetSpaceProperties',
    description: 'List custom metadata properties on a space.',
    tool: confluenceGetSpaceProperties,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['metadata'],
  },
  {
    name: 'confluenceGetSpaces',
    description: 'List spaces with keys, type, status and label filters.',
    tool: confluenceGetSpaces,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['browse', 'areas'],
  },
  {
    name: 'confluenceGetTasks',
    description: 'List tasks (action items) with status, page, space and assignee filters.',
    tool: confluenceGetTasks,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['todos', 'action-items'],
  },
  {
    name: 'confluenceGetAnonymousUser',
    description: 'Get guest (anonymous) user details.',
    tool: confluenceGetAnonymousUser,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['guest'],
  },
  {
    name: 'confluenceListSpaces',
    description: 'List spaces visible to you with simple pagination.',
    tool: confluenceListSpaces,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['browse'],
  },
  {
    name: 'confluenceSearchContent',
    description: 'Title search over pages with relevance ranking.',
    tool: confluenceSearchContent,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['find'],
  },
  {
    name: 'confluenceSearchPages',
    description: 'Search pages by exact title, space and status filters.',
    tool: confluenceSearchPages,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['find', 'title'],
  },
  {
    name: 'confluenceSearchSpaces',
    description: 'Find spaces by partial name/key match plus attribute filters.',
    tool: confluenceSearchSpaces,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['find'],
  },
  {
    name: 'confluenceSearchUsers',
    description: 'Look up a user by account ID, or browse users.',
    tool: confluenceSearchUsers,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['find', 'lookup'],
  },
  {
    name: 'confluenceUpdateBlogpost',
    description: 'Update a blog post title and/or body.',
    tool: confluenceUpdateBlogpost,
    requiredAuth: auth,
    scope: 'write' as const,
    keywords: ['edit'],
  },
  {
    name: 'confluenceUpdateBlogpostProperty',
    description: 'Update a blog post property value.',
    tool: confluenceUpdateBlogpostProperty,
    requiredAuth: auth,
    scope: 'write' as const,
    keywords: ['edit'],
  },
  {
    name: 'confluenceUpdatePageContentProperty',
    description: 'Update a page property value.',
    tool: confluenceUpdatePageContentProperty,
    requiredAuth: auth,
    scope: 'write' as const,
    keywords: ['edit'],
  },
  {
    name: 'confluenceUpdateWhiteboardContentProperty',
    description: 'Update a whiteboard property value.',
    tool: confluenceUpdateWhiteboardContentProperty,
    requiredAuth: auth,
    scope: 'write' as const,
    keywords: ['edit'],
  },
  {
    name: 'confluenceUpdatePage',
    description: 'Update a page title and/or full body (version auto-detects).',
    tool: confluenceUpdatePage,
    requiredAuth: auth,
    scope: 'write' as const,
    keywords: ['edit'],
  },
  {
    name: 'confluenceUpdateSpaceProperty',
    description: 'Update a space property value.',
    tool: confluenceUpdateSpaceProperty,
    requiredAuth: auth,
    scope: 'write' as const,
    keywords: ['edit'],
  },
  {
    name: 'confluenceUpdateTask',
    description: 'Mark a task complete or incomplete.',
    tool: confluenceUpdateTask,
    requiredAuth: auth,
    scope: 'write' as const,
    keywords: ['complete', 'check', 'done'],
  },
  {
    name: 'confluenceValidateCredential',
    description: 'Verify the connection by loading the current user.',
    tool: confluenceValidateCredential,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['test', 'ping'],
  },
  {
    name: 'confluenceWhoAmI',
    description: 'Show accessible Atlassian sites plus the connected account identity.',
    tool: confluenceWhoAmI,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['identity', 'sites'],
  },
];
