// @ts-nocheck
import {
  pagerdutyGetIncidentMetricsAll,
  pagerdutyGetIncidentMetricsByService,
  pagerdutyGetIncidentMetricsByTeam,
  pagerdutyGetIncidentMetricsByEscalationPolicy,
  pagerdutyGetResponderMetrics,
  pagerdutyGetResponderMetricsByTeam,
  pagerdutyGetUserMetrics,
  pagerdutyGetRawIncidents,
  pagerdutyGetRawIncidentResponses,
  pagerdutyGetRawUsers,
  pagerdutyGetPausedIncidentAlerts,
  pagerdutyGetPausedIncidentCounts,
} from './analytics.js';
import {
  pagerdutyListAutomationActions,
  pagerdutyGetAutomationAction,
  pagerdutyCreateAutomationAction,
  pagerdutyUpdateAutomationAction,
  pagerdutyDeleteAutomationAction,
  pagerdutyInvokeAutomationAction,
  pagerdutyListAutomationInvocations,
  pagerdutyGetAutomationInvocation,
  pagerdutyListActionServices,
  pagerdutyAssociateActionService,
  pagerdutyRemoveActionService,
  pagerdutyListActionTeams,
  pagerdutyAssociateActionTeam,
  pagerdutyRemoveActionTeam,
  pagerdutyListAutomationRunners,
  pagerdutyGetAutomationRunner,
  pagerdutyCreateAutomationRunner,
  pagerdutyUpdateAutomationRunner,
  pagerdutyDeleteAutomationRunner,
  pagerdutyListRunnerTeams,
  pagerdutyAssociateRunnerTeam,
  pagerdutyRemoveRunnerTeam,
} from './automation.js';
import {
  pagerdutyListBusinessServices,
  pagerdutyGetBusinessService,
  pagerdutyCreateBusinessService,
  pagerdutyUpdateBusinessService,
  pagerdutyDeleteBusinessService,
  pagerdutyListBusinessServiceSubscribers,
  pagerdutyAddBusinessServiceSubscribers,
  pagerdutyRemoveBusinessServiceSubscriber,
  pagerdutyGetBusinessServiceImpacts,
  pagerdutyGetBusinessServiceImpactors,
  pagerdutyGetSupportingServiceImpacts,
  pagerdutyGetPriorityThresholds,
  pagerdutySetGlobalPriorityThreshold,
  pagerdutyDeletePriorityThresholds,
  pagerdutyAssociateServiceDependencies,
  pagerdutyDisassociateServiceDependencies,
  pagerdutyGetBusinessServiceDependencies,
  pagerdutyGetTechnicalServiceDependencies,
} from './business-services.js';
import {
  pagerdutyListChangeEvents,
  pagerdutyCreateChangeEvent,
  pagerdutyGetChangeEvent,
  pagerdutyUpdateChangeEvent,
  pagerdutyListAuditRecords,
  pagerdutyListLogEntries,
  pagerdutyGetLogEntry,
  pagerdutyUpdateLogEntryChannel,
  pagerdutyListStandards,
  pagerdutyGetStandardScores,
  pagerdutyUpdateStandard,
} from './change-audit.js';
import {
  pagerdutyListEscalationPolicies,
  pagerdutyGetEscalationPolicy,
  pagerdutyCreateEscalationPolicy,
  pagerdutyUpdateEscalationPolicy,
  pagerdutyDeleteEscalationPolicy,
  pagerdutyGetEscalationPolicyAudit,
  pagerdutyListTeams,
  pagerdutyGetTeam,
  pagerdutyCreateTeam,
  pagerdutyUpdateTeam,
  pagerdutyDeleteTeam,
  pagerdutyListTeamMembers,
  pagerdutyAddUserToTeam,
  pagerdutyRemoveUserFromTeam,
  pagerdutyAddEscalationPolicyToTeam,
  pagerdutyRemoveEscalationPolicyFromTeam,
  pagerdutyListTeamNotificationSubscriptions,
  pagerdutyCreateTeamNotificationSubscription,
  pagerdutyUnsubscribeTeamNotifications,
} from './escalation-teams.js';
import {
  pagerdutyListIncidentNotes,
  pagerdutyCreateIncidentNote,
  pagerdutyUpdateIncidentNote,
  pagerdutyDeleteIncidentNote,
  pagerdutyListIncidentAlerts,
  pagerdutyGetIncidentAlert,
  pagerdutyUpdateIncidentAlert,
  pagerdutyBulkUpdateIncidentAlerts,
  pagerdutyListIncidentLogEntries,
  pagerdutyRequestResponders,
  pagerdutyCancelResponderRequest,
  pagerdutyPostIncidentStatusUpdate,
  pagerdutyListStatusUpdateSubscribers,
  pagerdutyAddStatusUpdateSubscribers,
  pagerdutyRemoveStatusUpdateSubscribers,
} from './incident-items.js';
import {
  pagerdutyListIncidentTypes,
  pagerdutyGetIncidentType,
  pagerdutyCreateIncidentType,
  pagerdutyUpdateIncidentType,
  pagerdutyListIncidentCustomFields,
  pagerdutyCreateIncidentCustomField,
  pagerdutyGetIncidentCustomField,
  pagerdutyUpdateIncidentCustomField,
  pagerdutyDeleteIncidentCustomField,
  pagerdutyListIncidentFieldOptions,
  pagerdutyCreateIncidentFieldOption,
  pagerdutyUpdateIncidentFieldOption,
  pagerdutyDeleteIncidentFieldOption,
  pagerdutyGetIncidentCustomFieldValues,
  pagerdutyUpdateIncidentCustomFieldValues,
  pagerdutyListTypeCustomFields,
  pagerdutyCreateTypeCustomField,
} from './incident-meta.js';
import {
  pagerdutyListIncidents,
  pagerdutyGetIncident,
  pagerdutyCreateIncident,
  pagerdutyUpdateIncident,
  pagerdutyMergeIncidents,
  pagerdutySnoozeIncident,
  pagerdutyGetIncidentOutlier,
  pagerdutyGetPastIncidents,
  pagerdutyGetRelatedIncidents,
  pagerdutyGetRelatedChangeEvents,
  pagerdutyGetIncidentBusinessImpacts,
  pagerdutySetIncidentBusinessImpact,
} from './incidents.js';
import {
  pagerdutyListMaintenanceWindows,
  pagerdutyGetMaintenanceWindow,
  pagerdutyCreateMaintenanceWindow,
  pagerdutyUpdateMaintenanceWindow,
  pagerdutyDeleteMaintenanceWindow,
  pagerdutyListTags,
  pagerdutyCreateTag,
  pagerdutyGetTag,
  pagerdutyDeleteTag,
  pagerdutyListEntityTags,
  pagerdutySetEntityTags,
  pagerdutyListPriorities,
  pagerdutyListAbilities,
  pagerdutyGetAbility,
  pagerdutyListLicenses,
  pagerdutyListLicenseAllocations,
  pagerdutyListNotifications,
} from './maintenance.js';
import {
  pagerdutyListEventOrchestrations,
  pagerdutyGetEventOrchestration,
  pagerdutyCreateEventOrchestration,
  pagerdutyUpdateEventOrchestration,
  pagerdutyDeleteEventOrchestration,
  pagerdutyGetOrchestrationRouter,
  pagerdutyUpdateOrchestrationRouter,
  pagerdutyGetOrchestrationGlobal,
  pagerdutyUpdateOrchestrationGlobal,
  pagerdutyGetOrchestrationUnrouted,
  pagerdutyUpdateOrchestrationUnrouted,
  pagerdutyListOrchestrationIntegrations,
  pagerdutyCreateOrchestrationIntegration,
  pagerdutyGetOrchestrationIntegration,
  pagerdutyUpdateOrchestrationIntegration,
  pagerdutyDeleteOrchestrationIntegration,
  pagerdutyMigrateOrchestrationIntegration,
  pagerdutyGetServiceOrchestration,
  pagerdutyUpdateServiceOrchestration,
  pagerdutyGetServiceOrchestrationActive,
  pagerdutySetServiceOrchestrationActive,
} from './orchestration.js';
import {
  pagerdutyListRulesets,
  pagerdutyGetRuleset,
  pagerdutyCreateRuleset,
  pagerdutyUpdateRuleset,
  pagerdutyDeleteRuleset,
  pagerdutyListRulesetRules,
  pagerdutyGetRulesetRule,
  pagerdutyCreateRulesetRule,
  pagerdutyUpdateRulesetRule,
  pagerdutyDeleteRulesetRule,
  pagerdutyListWorkflows,
  pagerdutyGetWorkflow,
  pagerdutyCreateWorkflow,
  pagerdutyUpdateWorkflow,
  pagerdutyDeleteWorkflow,
  pagerdutyRunWorkflowInstance,
  pagerdutyListWorkflowActions,
  pagerdutyGetWorkflowAction,
  pagerdutyListWorkflowTriggers,
  pagerdutyGetWorkflowTrigger,
  pagerdutyCreateWorkflowTrigger,
  pagerdutyUpdateWorkflowTrigger,
  pagerdutyDeleteWorkflowTrigger,
  pagerdutyAddServiceToWorkflowTrigger,
  pagerdutyRemoveServiceFromWorkflowTrigger,
} from './rulesets-workflows.js';
import {
  pagerdutyListSchedules,
  pagerdutyGetSchedule,
  pagerdutyCreateSchedule,
  pagerdutyUpdateSchedule,
  pagerdutyDeleteSchedule,
  pagerdutyPreviewSchedule,
  pagerdutyListScheduleOverrides,
  pagerdutyCreateScheduleOverride,
  pagerdutyDeleteScheduleOverride,
  pagerdutyListScheduleUsers,
  pagerdutyListOncalls,
} from './schedules.js';
import {
  pagerdutyListServices,
  pagerdutyGetService,
  pagerdutyCreateService,
  pagerdutyUpdateService,
  pagerdutyDeleteService,
  pagerdutyCreateServiceIntegration,
  pagerdutyGetServiceIntegration,
  pagerdutyUpdateServiceIntegration,
  pagerdutyListServiceEventRules,
  pagerdutyGetServiceEventRule,
  pagerdutyCreateServiceEventRule,
  pagerdutyUpdateServiceEventRule,
  pagerdutyDeleteServiceEventRule,
  pagerdutyConvertServiceEventRule,
  pagerdutyListServiceChangeEvents,
  pagerdutyGetServiceAuditRecords,
} from './services.js';
import {
  pagerdutyListStatusPages,
  pagerdutyGetStatusPageImpacts,
  pagerdutyGetStatusPageImpact,
  pagerdutyListStatusPagePosts,
  pagerdutyGetStatusPagePost,
  pagerdutyCreateStatusPagePost,
  pagerdutyUpdateStatusPagePost,
  pagerdutyDeleteStatusPagePost,
  pagerdutyListPostUpdates,
  pagerdutyCreatePostUpdate,
  pagerdutyGetPostUpdate,
  pagerdutyUpdatePostUpdate,
  pagerdutyDeletePostUpdate,
  pagerdutyGetPostPostmortem,
  pagerdutyUpdatePostPostmortem,
  pagerdutyDeletePostPostmortem,
  pagerdutyListStatusPageSubscriptions,
  pagerdutyCreateStatusPageSubscription,
  pagerdutyDeleteStatusPageSubscription,
  pagerdutyListStatusPageSeverities,
  pagerdutyListStatusPageStatuses,
  pagerdutyListStatusPageServices,
  pagerdutyListStatusDashboards,
  pagerdutyGetStatusDashboard,
  pagerdutyGetStatusDashboardBySlug,
  pagerdutyGetDashboardServiceImpacts,
} from './status-pages.js';
import {
  pagerdutyListTemplates,
  pagerdutyGetTemplate,
  pagerdutyCreateTemplate,
  pagerdutyUpdateTemplate,
  pagerdutyDeleteTemplate,
  pagerdutyListTemplateFields,
  pagerdutyRenderTemplate,
  pagerdutyListGlobalCacheVariables,
  pagerdutyCreateGlobalCacheVariable,
  pagerdutyGetGlobalCacheVariable,
  pagerdutyUpdateGlobalCacheVariable,
  pagerdutyDeleteGlobalCacheVariable,
  pagerdutyListServiceCacheVariables,
  pagerdutyCreateServiceCacheVariable,
  pagerdutyGetServiceCacheVariable,
  pagerdutyUpdateServiceCacheVariable,
  pagerdutyDeleteServiceCacheVariable,
} from './templates-cache.js';
import {
  pagerdutyListHandoffNotificationRules,
  pagerdutyCreateHandoffNotificationRule,
  pagerdutyGetHandoffNotificationRule,
  pagerdutyUpdateHandoffNotificationRule,
  pagerdutyDeleteHandoffNotificationRule,
  pagerdutyListUserStatusUpdateRules,
  pagerdutyCreateUserStatusUpdateRule,
  pagerdutyGetUserStatusUpdateRule,
  pagerdutyUpdateUserStatusUpdateRule,
  pagerdutyDeleteUserStatusUpdateRule,
  pagerdutyListUserSessions,
  pagerdutyDeleteUserSession,
  pagerdutyListUserNotificationSubscriptions,
  pagerdutyCreateUserNotificationSubscription,
  pagerdutyUnsubscribeUserNotifications,
  pagerdutyGetUserAuditRecords,
} from './user-settings.js';
import {
  pagerdutyListUsers,
  pagerdutyGetCurrentUser,
  pagerdutyGetUser,
  pagerdutyCreateUser,
  pagerdutyUpdateUser,
  pagerdutyDeleteUser,
  pagerdutyGetUserLicense,
  pagerdutyListUserContactMethods,
  pagerdutyGetUserContactMethod,
  pagerdutyCreateUserContactMethod,
  pagerdutyUpdateUserContactMethod,
  pagerdutyDeleteUserContactMethod,
  pagerdutyListUserNotificationRules,
  pagerdutyGetUserNotificationRule,
  pagerdutyCreateUserNotificationRule,
  pagerdutyUpdateUserNotificationRule,
  pagerdutyDeleteUserNotificationRule,
} from './users.js';
import {
  pagerdutyListWebhookSubscriptions,
  pagerdutyGetWebhookSubscription,
  pagerdutyCreateWebhookSubscription,
  pagerdutyUpdateWebhookSubscription,
  pagerdutyDeleteWebhookSubscription,
  pagerdutyEnableWebhookSubscription,
  pagerdutyPingWebhookSubscription,
  pagerdutyListExtensions,
  pagerdutyGetExtension,
  pagerdutyCreateExtension,
  pagerdutyUpdateExtension,
  pagerdutyDeleteExtension,
  pagerdutyEnableExtension,
  pagerdutyListExtensionSchemas,
  pagerdutyGetExtensionSchema,
  pagerdutyListAddons,
  pagerdutyGetAddon,
  pagerdutyInstallAddon,
  pagerdutyUpdateAddon,
  pagerdutyDeleteAddon,
  pagerdutyListAlertGroupingSettings,
  pagerdutyGetAlertGroupingSetting,
  pagerdutyCreateAlertGroupingSetting,
  pagerdutyUpdateAlertGroupingSetting,
  pagerdutyDeleteAlertGroupingSetting,
} from './webhooks-extensions.js';

export {
  pagerdutyGetIncidentMetricsAll,
  pagerdutyGetIncidentMetricsByService,
  pagerdutyGetIncidentMetricsByTeam,
  pagerdutyGetIncidentMetricsByEscalationPolicy,
  pagerdutyGetResponderMetrics,
  pagerdutyGetResponderMetricsByTeam,
  pagerdutyGetUserMetrics,
  pagerdutyGetRawIncidents,
  pagerdutyGetRawIncidentResponses,
  pagerdutyGetRawUsers,
  pagerdutyGetPausedIncidentAlerts,
  pagerdutyGetPausedIncidentCounts,
  pagerdutyListAutomationActions,
  pagerdutyGetAutomationAction,
  pagerdutyCreateAutomationAction,
  pagerdutyUpdateAutomationAction,
  pagerdutyDeleteAutomationAction,
  pagerdutyInvokeAutomationAction,
  pagerdutyListAutomationInvocations,
  pagerdutyGetAutomationInvocation,
  pagerdutyListActionServices,
  pagerdutyAssociateActionService,
  pagerdutyRemoveActionService,
  pagerdutyListActionTeams,
  pagerdutyAssociateActionTeam,
  pagerdutyRemoveActionTeam,
  pagerdutyListAutomationRunners,
  pagerdutyGetAutomationRunner,
  pagerdutyCreateAutomationRunner,
  pagerdutyUpdateAutomationRunner,
  pagerdutyDeleteAutomationRunner,
  pagerdutyListRunnerTeams,
  pagerdutyAssociateRunnerTeam,
  pagerdutyRemoveRunnerTeam,
  pagerdutyListBusinessServices,
  pagerdutyGetBusinessService,
  pagerdutyCreateBusinessService,
  pagerdutyUpdateBusinessService,
  pagerdutyDeleteBusinessService,
  pagerdutyListBusinessServiceSubscribers,
  pagerdutyAddBusinessServiceSubscribers,
  pagerdutyRemoveBusinessServiceSubscriber,
  pagerdutyGetBusinessServiceImpacts,
  pagerdutyGetBusinessServiceImpactors,
  pagerdutyGetSupportingServiceImpacts,
  pagerdutyGetPriorityThresholds,
  pagerdutySetGlobalPriorityThreshold,
  pagerdutyDeletePriorityThresholds,
  pagerdutyAssociateServiceDependencies,
  pagerdutyDisassociateServiceDependencies,
  pagerdutyGetBusinessServiceDependencies,
  pagerdutyGetTechnicalServiceDependencies,
  pagerdutyListChangeEvents,
  pagerdutyCreateChangeEvent,
  pagerdutyGetChangeEvent,
  pagerdutyUpdateChangeEvent,
  pagerdutyListAuditRecords,
  pagerdutyListLogEntries,
  pagerdutyGetLogEntry,
  pagerdutyUpdateLogEntryChannel,
  pagerdutyListStandards,
  pagerdutyGetStandardScores,
  pagerdutyUpdateStandard,
  pagerdutyListEscalationPolicies,
  pagerdutyGetEscalationPolicy,
  pagerdutyCreateEscalationPolicy,
  pagerdutyUpdateEscalationPolicy,
  pagerdutyDeleteEscalationPolicy,
  pagerdutyGetEscalationPolicyAudit,
  pagerdutyListTeams,
  pagerdutyGetTeam,
  pagerdutyCreateTeam,
  pagerdutyUpdateTeam,
  pagerdutyDeleteTeam,
  pagerdutyListTeamMembers,
  pagerdutyAddUserToTeam,
  pagerdutyRemoveUserFromTeam,
  pagerdutyAddEscalationPolicyToTeam,
  pagerdutyRemoveEscalationPolicyFromTeam,
  pagerdutyListTeamNotificationSubscriptions,
  pagerdutyCreateTeamNotificationSubscription,
  pagerdutyUnsubscribeTeamNotifications,
  pagerdutyListIncidentNotes,
  pagerdutyCreateIncidentNote,
  pagerdutyUpdateIncidentNote,
  pagerdutyDeleteIncidentNote,
  pagerdutyListIncidentAlerts,
  pagerdutyGetIncidentAlert,
  pagerdutyUpdateIncidentAlert,
  pagerdutyBulkUpdateIncidentAlerts,
  pagerdutyListIncidentLogEntries,
  pagerdutyRequestResponders,
  pagerdutyCancelResponderRequest,
  pagerdutyPostIncidentStatusUpdate,
  pagerdutyListStatusUpdateSubscribers,
  pagerdutyAddStatusUpdateSubscribers,
  pagerdutyRemoveStatusUpdateSubscribers,
  pagerdutyListIncidentTypes,
  pagerdutyGetIncidentType,
  pagerdutyCreateIncidentType,
  pagerdutyUpdateIncidentType,
  pagerdutyListIncidentCustomFields,
  pagerdutyCreateIncidentCustomField,
  pagerdutyGetIncidentCustomField,
  pagerdutyUpdateIncidentCustomField,
  pagerdutyDeleteIncidentCustomField,
  pagerdutyListIncidentFieldOptions,
  pagerdutyCreateIncidentFieldOption,
  pagerdutyUpdateIncidentFieldOption,
  pagerdutyDeleteIncidentFieldOption,
  pagerdutyGetIncidentCustomFieldValues,
  pagerdutyUpdateIncidentCustomFieldValues,
  pagerdutyListTypeCustomFields,
  pagerdutyCreateTypeCustomField,
  pagerdutyListIncidents,
  pagerdutyGetIncident,
  pagerdutyCreateIncident,
  pagerdutyUpdateIncident,
  pagerdutyMergeIncidents,
  pagerdutySnoozeIncident,
  pagerdutyGetIncidentOutlier,
  pagerdutyGetPastIncidents,
  pagerdutyGetRelatedIncidents,
  pagerdutyGetRelatedChangeEvents,
  pagerdutyGetIncidentBusinessImpacts,
  pagerdutySetIncidentBusinessImpact,
  pagerdutyListMaintenanceWindows,
  pagerdutyGetMaintenanceWindow,
  pagerdutyCreateMaintenanceWindow,
  pagerdutyUpdateMaintenanceWindow,
  pagerdutyDeleteMaintenanceWindow,
  pagerdutyListTags,
  pagerdutyCreateTag,
  pagerdutyGetTag,
  pagerdutyDeleteTag,
  pagerdutyListEntityTags,
  pagerdutySetEntityTags,
  pagerdutyListPriorities,
  pagerdutyListAbilities,
  pagerdutyGetAbility,
  pagerdutyListLicenses,
  pagerdutyListLicenseAllocations,
  pagerdutyListNotifications,
  pagerdutyListEventOrchestrations,
  pagerdutyGetEventOrchestration,
  pagerdutyCreateEventOrchestration,
  pagerdutyUpdateEventOrchestration,
  pagerdutyDeleteEventOrchestration,
  pagerdutyGetOrchestrationRouter,
  pagerdutyUpdateOrchestrationRouter,
  pagerdutyGetOrchestrationGlobal,
  pagerdutyUpdateOrchestrationGlobal,
  pagerdutyGetOrchestrationUnrouted,
  pagerdutyUpdateOrchestrationUnrouted,
  pagerdutyListOrchestrationIntegrations,
  pagerdutyCreateOrchestrationIntegration,
  pagerdutyGetOrchestrationIntegration,
  pagerdutyUpdateOrchestrationIntegration,
  pagerdutyDeleteOrchestrationIntegration,
  pagerdutyMigrateOrchestrationIntegration,
  pagerdutyGetServiceOrchestration,
  pagerdutyUpdateServiceOrchestration,
  pagerdutyGetServiceOrchestrationActive,
  pagerdutySetServiceOrchestrationActive,
  pagerdutyListRulesets,
  pagerdutyGetRuleset,
  pagerdutyCreateRuleset,
  pagerdutyUpdateRuleset,
  pagerdutyDeleteRuleset,
  pagerdutyListRulesetRules,
  pagerdutyGetRulesetRule,
  pagerdutyCreateRulesetRule,
  pagerdutyUpdateRulesetRule,
  pagerdutyDeleteRulesetRule,
  pagerdutyListWorkflows,
  pagerdutyGetWorkflow,
  pagerdutyCreateWorkflow,
  pagerdutyUpdateWorkflow,
  pagerdutyDeleteWorkflow,
  pagerdutyRunWorkflowInstance,
  pagerdutyListWorkflowActions,
  pagerdutyGetWorkflowAction,
  pagerdutyListWorkflowTriggers,
  pagerdutyGetWorkflowTrigger,
  pagerdutyCreateWorkflowTrigger,
  pagerdutyUpdateWorkflowTrigger,
  pagerdutyDeleteWorkflowTrigger,
  pagerdutyAddServiceToWorkflowTrigger,
  pagerdutyRemoveServiceFromWorkflowTrigger,
  pagerdutyListSchedules,
  pagerdutyGetSchedule,
  pagerdutyCreateSchedule,
  pagerdutyUpdateSchedule,
  pagerdutyDeleteSchedule,
  pagerdutyPreviewSchedule,
  pagerdutyListScheduleOverrides,
  pagerdutyCreateScheduleOverride,
  pagerdutyDeleteScheduleOverride,
  pagerdutyListScheduleUsers,
  pagerdutyListOncalls,
  pagerdutyListServices,
  pagerdutyGetService,
  pagerdutyCreateService,
  pagerdutyUpdateService,
  pagerdutyDeleteService,
  pagerdutyCreateServiceIntegration,
  pagerdutyGetServiceIntegration,
  pagerdutyUpdateServiceIntegration,
  pagerdutyListServiceEventRules,
  pagerdutyGetServiceEventRule,
  pagerdutyCreateServiceEventRule,
  pagerdutyUpdateServiceEventRule,
  pagerdutyDeleteServiceEventRule,
  pagerdutyConvertServiceEventRule,
  pagerdutyListServiceChangeEvents,
  pagerdutyGetServiceAuditRecords,
  pagerdutyListStatusPages,
  pagerdutyGetStatusPageImpacts,
  pagerdutyGetStatusPageImpact,
  pagerdutyListStatusPagePosts,
  pagerdutyGetStatusPagePost,
  pagerdutyCreateStatusPagePost,
  pagerdutyUpdateStatusPagePost,
  pagerdutyDeleteStatusPagePost,
  pagerdutyListPostUpdates,
  pagerdutyCreatePostUpdate,
  pagerdutyGetPostUpdate,
  pagerdutyUpdatePostUpdate,
  pagerdutyDeletePostUpdate,
  pagerdutyGetPostPostmortem,
  pagerdutyUpdatePostPostmortem,
  pagerdutyDeletePostPostmortem,
  pagerdutyListStatusPageSubscriptions,
  pagerdutyCreateStatusPageSubscription,
  pagerdutyDeleteStatusPageSubscription,
  pagerdutyListStatusPageSeverities,
  pagerdutyListStatusPageStatuses,
  pagerdutyListStatusPageServices,
  pagerdutyListStatusDashboards,
  pagerdutyGetStatusDashboard,
  pagerdutyGetStatusDashboardBySlug,
  pagerdutyGetDashboardServiceImpacts,
  pagerdutyListTemplates,
  pagerdutyGetTemplate,
  pagerdutyCreateTemplate,
  pagerdutyUpdateTemplate,
  pagerdutyDeleteTemplate,
  pagerdutyListTemplateFields,
  pagerdutyRenderTemplate,
  pagerdutyListGlobalCacheVariables,
  pagerdutyCreateGlobalCacheVariable,
  pagerdutyGetGlobalCacheVariable,
  pagerdutyUpdateGlobalCacheVariable,
  pagerdutyDeleteGlobalCacheVariable,
  pagerdutyListServiceCacheVariables,
  pagerdutyCreateServiceCacheVariable,
  pagerdutyGetServiceCacheVariable,
  pagerdutyUpdateServiceCacheVariable,
  pagerdutyDeleteServiceCacheVariable,
  pagerdutyListHandoffNotificationRules,
  pagerdutyCreateHandoffNotificationRule,
  pagerdutyGetHandoffNotificationRule,
  pagerdutyUpdateHandoffNotificationRule,
  pagerdutyDeleteHandoffNotificationRule,
  pagerdutyListUserStatusUpdateRules,
  pagerdutyCreateUserStatusUpdateRule,
  pagerdutyGetUserStatusUpdateRule,
  pagerdutyUpdateUserStatusUpdateRule,
  pagerdutyDeleteUserStatusUpdateRule,
  pagerdutyListUserSessions,
  pagerdutyDeleteUserSession,
  pagerdutyListUserNotificationSubscriptions,
  pagerdutyCreateUserNotificationSubscription,
  pagerdutyUnsubscribeUserNotifications,
  pagerdutyGetUserAuditRecords,
  pagerdutyListUsers,
  pagerdutyGetCurrentUser,
  pagerdutyGetUser,
  pagerdutyCreateUser,
  pagerdutyUpdateUser,
  pagerdutyDeleteUser,
  pagerdutyGetUserLicense,
  pagerdutyListUserContactMethods,
  pagerdutyGetUserContactMethod,
  pagerdutyCreateUserContactMethod,
  pagerdutyUpdateUserContactMethod,
  pagerdutyDeleteUserContactMethod,
  pagerdutyListUserNotificationRules,
  pagerdutyGetUserNotificationRule,
  pagerdutyCreateUserNotificationRule,
  pagerdutyUpdateUserNotificationRule,
  pagerdutyDeleteUserNotificationRule,
  pagerdutyListWebhookSubscriptions,
  pagerdutyGetWebhookSubscription,
  pagerdutyCreateWebhookSubscription,
  pagerdutyUpdateWebhookSubscription,
  pagerdutyDeleteWebhookSubscription,
  pagerdutyEnableWebhookSubscription,
  pagerdutyPingWebhookSubscription,
  pagerdutyListExtensions,
  pagerdutyGetExtension,
  pagerdutyCreateExtension,
  pagerdutyUpdateExtension,
  pagerdutyDeleteExtension,
  pagerdutyEnableExtension,
  pagerdutyListExtensionSchemas,
  pagerdutyGetExtensionSchema,
  pagerdutyListAddons,
  pagerdutyGetAddon,
  pagerdutyInstallAddon,
  pagerdutyUpdateAddon,
  pagerdutyDeleteAddon,
  pagerdutyListAlertGroupingSettings,
  pagerdutyGetAlertGroupingSetting,
  pagerdutyCreateAlertGroupingSetting,
  pagerdutyUpdateAlertGroupingSetting,
  pagerdutyDeleteAlertGroupingSetting,
};

const auth = 'pagerdutyApiKey' as const;

type Scope = 'read' | 'write' | 'delete';
function entry(
  name: string,
  description: string,
  toolRef: any,
  scope: Scope,
  keywords: string[],
): {
  name: string;
  description: string;
  tool: any;
  requiredAuth: typeof auth;
  scope: Scope;
  keywords: string[];
} {
  return { name, description, tool: toolRef, requiredAuth: auth, scope, keywords };
}

export const pagerdutyTools = [
  entry(
    'pagerdutyGetIncidentMetricsAll',
    'Aggregate MTTA/MTTR, counts, and escalation stats across all incidents with filters. Use for operational reviews.',
    pagerdutyGetIncidentMetricsAll,
    'read',
    ['report', 'mtta', 'mttr'],
  ),
  entry(
    'pagerdutyGetIncidentMetricsByService',
    'Incident metrics broken down per service for reliability comparisons.',
    pagerdutyGetIncidentMetricsByService,
    'read',
    ['report', 'mtta', 'mttr', 'monitored endpoint'],
  ),
  entry(
    'pagerdutyGetIncidentMetricsByTeam',
    'Incident metrics broken down per team for ownership reviews.',
    pagerdutyGetIncidentMetricsByTeam,
    'read',
    ['report', 'mtta', 'mttr', 'squad', 'group'],
  ),
  entry(
    'pagerdutyGetIncidentMetricsByEscalationPolicy',
    'Incident metrics broken down per escalation policy for escalation-effectiveness analysis.',
    pagerdutyGetIncidentMetricsByEscalationPolicy,
    'read',
    ['escalation chain', 'paging order', 'report', 'mtta', 'mttr'],
  ),
  entry(
    'pagerdutyGetResponderMetrics',
    'Responder engagement metrics (who responded, how long engaged) across incidents.',
    pagerdutyGetResponderMetrics,
    'read',
    ['page someone', 'call in', 'report', 'mtta', 'mttr'],
  ),
  entry(
    'pagerdutyGetResponderMetricsByTeam',
    'Responder metrics broken down per team.',
    pagerdutyGetResponderMetricsByTeam,
    'read',
    ['page someone', 'call in', 'report', 'mtta', 'mttr'],
  ),
  entry(
    'pagerdutyGetUserMetrics',
    'Per-user analytics: interruptions, engaged time, and off-hours load for burnout review.',
    pagerdutyGetUserMetrics,
    'read',
    ['report', 'mtta', 'mttr', 'responder', 'member'],
  ),
  entry(
    'pagerdutyGetRawIncidents',
    'Raw per-incident analytics rows (engaged seconds, ack counts, escalations) for custom reporting.',
    pagerdutyGetRawIncidents,
    'read',
    ['report', 'mtta', 'mttr'],
  ),
  entry(
    'pagerdutyGetRawIncidentResponses',
    'Raw responder-engagement rows for one incident.',
    pagerdutyGetRawIncidentResponses,
    'read',
    ['report', 'mtta', 'mttr'],
  ),
  entry(
    'pagerdutyGetRawUsers',
    'Raw per-user analytics rows for custom on-call load reporting.',
    pagerdutyGetRawUsers,
    'read',
    ['report', 'mtta', 'mttr', 'responder', 'member'],
  ),
  entry(
    'pagerdutyGetPausedIncidentAlerts',
    'Alerts suppressed by auto-pause notification rules, for review.',
    pagerdutyGetPausedIncidentAlerts,
    'read',
    ['suppressed alerts', 'firing alert'],
  ),
  entry(
    'pagerdutyGetPausedIncidentCounts',
    'Counts of auto-paused incidents for suppression auditing.',
    pagerdutyGetPausedIncidentCounts,
    'read',
    ['suppressed alerts'],
  ),
  entry(
    'pagerdutyListAutomationActions',
    'List automation actions (runbook/script jobs) available for incidents.',
    pagerdutyListAutomationActions,
    'read',
    ['runbook', 'auto-remediation'],
  ),
  entry(
    'pagerdutyGetAutomationAction',
    'Get one automation action with its script/job configuration.',
    pagerdutyGetAutomationAction,
    'read',
    ['runbook', 'auto-remediation'],
  ),
  entry(
    'pagerdutyCreateAutomationAction',
    'Create an automation action (script or process-automation job) for incident response.',
    pagerdutyCreateAutomationAction,
    'write',
    ['runbook', 'auto-remediation', 'new'],
  ),
  entry(
    'pagerdutyUpdateAutomationAction',
    'Update an automation action configuration.',
    pagerdutyUpdateAutomationAction,
    'write',
    ['runbook', 'auto-remediation', 'edit'],
  ),
  entry(
    'pagerdutyDeleteAutomationAction',
    'Delete an automation action.',
    pagerdutyDeleteAutomationAction,
    'delete',
    ['runbook', 'auto-remediation', 'remove'],
  ),
  entry(
    'pagerdutyInvokeAutomationAction',
    'Run an automation action against an incident (optionally a specific alert).',
    pagerdutyInvokeAutomationAction,
    'write',
    ['runbook', 'auto-remediation'],
  ),
  entry(
    'pagerdutyListAutomationInvocations',
    'List automation action invocations with status, filterable by action or incident.',
    pagerdutyListAutomationInvocations,
    'read',
    ['runbook', 'auto-remediation'],
  ),
  entry(
    'pagerdutyGetAutomationInvocation',
    'Get one automation invocation with execution output and status.',
    pagerdutyGetAutomationInvocation,
    'read',
    ['runbook', 'auto-remediation'],
  ),
  entry(
    'pagerdutyListActionServices',
    'List services an automation action is associated with.',
    pagerdutyListActionServices,
    'read',
    ['monitored endpoint'],
  ),
  entry(
    'pagerdutyAssociateActionService',
    'Allow an automation action to run on incidents of a service.',
    pagerdutyAssociateActionService,
    'write',
    ['monitored endpoint'],
  ),
  entry(
    'pagerdutyRemoveActionService',
    'Remove a service association from an automation action.',
    pagerdutyRemoveActionService,
    'delete',
    ['monitored endpoint'],
  ),
  entry(
    'pagerdutyListActionTeams',
    'List teams allowed to use an automation action.',
    pagerdutyListActionTeams,
    'read',
    ['squad', 'group'],
  ),
  entry(
    'pagerdutyAssociateActionTeam',
    'Grant a team permission to use an automation action.',
    pagerdutyAssociateActionTeam,
    'write',
    ['squad', 'group'],
  ),
  entry(
    'pagerdutyRemoveActionTeam',
    'Revoke a team permission to use an automation action.',
    pagerdutyRemoveActionTeam,
    'delete',
    ['squad', 'group'],
  ),
  entry(
    'pagerdutyListAutomationRunners',
    'List automation runners (execution hosts: sidecar or runbook).',
    pagerdutyListAutomationRunners,
    'read',
    ['runbook', 'auto-remediation'],
  ),
  entry(
    'pagerdutyGetAutomationRunner',
    'Get one automation runner with status and type.',
    pagerdutyGetAutomationRunner,
    'read',
    ['runbook', 'auto-remediation'],
  ),
  entry(
    'pagerdutyCreateAutomationRunner',
    'Register an automation runner (sidecar agent or runbook host).',
    pagerdutyCreateAutomationRunner,
    'write',
    ['runbook', 'auto-remediation', 'new'],
  ),
  entry(
    'pagerdutyUpdateAutomationRunner',
    'Update an automation runner name or configuration.',
    pagerdutyUpdateAutomationRunner,
    'write',
    ['runbook', 'auto-remediation', 'edit'],
  ),
  entry(
    'pagerdutyDeleteAutomationRunner',
    'Delete an automation runner.',
    pagerdutyDeleteAutomationRunner,
    'delete',
    ['runbook', 'auto-remediation', 'remove'],
  ),
  entry(
    'pagerdutyListRunnerTeams',
    'List teams associated with an automation runner.',
    pagerdutyListRunnerTeams,
    'read',
    ['runbook', 'auto-remediation', 'squad', 'group'],
  ),
  entry(
    'pagerdutyAssociateRunnerTeam',
    'Associate a team with an automation runner.',
    pagerdutyAssociateRunnerTeam,
    'write',
    ['runbook', 'auto-remediation', 'squad', 'group'],
  ),
  entry(
    'pagerdutyRemoveRunnerTeam',
    'Remove a team association from an automation runner.',
    pagerdutyRemoveRunnerTeam,
    'delete',
    ['runbook', 'auto-remediation', 'squad', 'group'],
  ),
  entry(
    'pagerdutyListBusinessServices',
    'List business services (customer-facing capabilities composed of technical services).',
    pagerdutyListBusinessServices,
    'read',
    ['bmc', 'service map', 'monitored endpoint'],
  ),
  entry(
    'pagerdutyGetBusinessService',
    'Get one business service with subscribers and impact status.',
    pagerdutyGetBusinessService,
    'read',
    ['bmc', 'service map', 'monitored endpoint'],
  ),
  entry(
    'pagerdutyCreateBusinessService',
    'Create a business service owned by a team.',
    pagerdutyCreateBusinessService,
    'write',
    ['bmc', 'service map', 'monitored endpoint', 'new'],
  ),
  entry(
    'pagerdutyUpdateBusinessService',
    'Update a business service name, description, or ownership.',
    pagerdutyUpdateBusinessService,
    'write',
    ['bmc', 'service map', 'monitored endpoint', 'edit'],
  ),
  entry(
    'pagerdutyDeleteBusinessService',
    'Delete a business service and its subscriptions.',
    pagerdutyDeleteBusinessService,
    'delete',
    ['bmc', 'service map', 'monitored endpoint', 'remove'],
  ),
  entry(
    'pagerdutyListBusinessServiceSubscribers',
    'List subscribers notified about a business service impact.',
    pagerdutyListBusinessServiceSubscribers,
    'read',
    ['bmc', 'service map', 'monitored endpoint'],
  ),
  entry(
    'pagerdutyAddBusinessServiceSubscribers',
    'Subscribe users/teams to business service impact notifications.',
    pagerdutyAddBusinessServiceSubscribers,
    'write',
    ['bmc', 'service map', 'monitored endpoint'],
  ),
  entry(
    'pagerdutyRemoveBusinessServiceSubscriber',
    'Unsubscribe an entity from business service notifications.',
    pagerdutyRemoveBusinessServiceSubscriber,
    'delete',
    ['bmc', 'service map', 'monitored endpoint'],
  ),
  entry(
    'pagerdutyGetBusinessServiceImpacts',
    'Current impact state across business services.',
    pagerdutyGetBusinessServiceImpacts,
    'read',
    ['bmc', 'service map', 'monitored endpoint'],
  ),
  entry(
    'pagerdutyGetBusinessServiceImpactors',
    'Technical services currently impacting business services.',
    pagerdutyGetBusinessServiceImpactors,
    'read',
    ['bmc', 'service map', 'monitored endpoint'],
  ),
  entry(
    'pagerdutyGetSupportingServiceImpacts',
    'Business services impacted by one supporting (technical) service.',
    pagerdutyGetSupportingServiceImpacts,
    'read',
    ['monitored endpoint'],
  ),
  entry(
    'pagerdutyGetPriorityThresholds',
    'Get business-service priority thresholds driving severity mapping.',
    pagerdutyGetPriorityThresholds,
    'read',
    ['p1-p5', 'severity'],
  ),
  entry(
    'pagerdutySetGlobalPriorityThreshold',
    'Set the global priority threshold for business service impact calculation.',
    pagerdutySetGlobalPriorityThreshold,
    'write',
    ['p1-p5', 'severity'],
  ),
  entry(
    'pagerdutyDeletePriorityThresholds',
    'Delete business-service priority thresholds (revert to defaults).',
    pagerdutyDeletePriorityThresholds,
    'delete',
    ['p1-p5', 'severity', 'remove'],
  ),
  entry(
    'pagerdutyAssociateServiceDependencies',
    'Declare supporting-service → dependent-service dependencies for impact mapping.',
    pagerdutyAssociateServiceDependencies,
    'write',
    ['monitored endpoint'],
  ),
  entry(
    'pagerdutyDisassociateServiceDependencies',
    'Remove service dependency relationships.',
    pagerdutyDisassociateServiceDependencies,
    'delete',
    ['monitored endpoint'],
  ),
  entry(
    'pagerdutyGetBusinessServiceDependencies',
    'Dependency graph around one business service.',
    pagerdutyGetBusinessServiceDependencies,
    'read',
    ['bmc', 'service map', 'monitored endpoint'],
  ),
  entry(
    'pagerdutyGetTechnicalServiceDependencies',
    'Dependency graph around one technical service.',
    pagerdutyGetTechnicalServiceDependencies,
    'read',
    ['monitored endpoint'],
  ),
  entry(
    'pagerdutyListChangeEvents',
    'List change events (deploys, config changes) across services for correlation.',
    pagerdutyListChangeEvents,
    'read',
    ['deploy', 'release'],
  ),
  entry(
    'pagerdutyCreateChangeEvent',
    'Record a change event (deploy, release, config change) for incident correlation.',
    pagerdutyCreateChangeEvent,
    'write',
    ['deploy', 'release', 'new'],
  ),
  entry(
    'pagerdutyGetChangeEvent',
    'Get one change event with details.',
    pagerdutyGetChangeEvent,
    'read',
    ['deploy', 'release'],
  ),
  entry(
    'pagerdutyUpdateChangeEvent',
    'Update a change event summary or details.',
    pagerdutyUpdateChangeEvent,
    'write',
    ['deploy', 'release', 'edit'],
  ),
  entry(
    'pagerdutyListAuditRecords',
    'Account-wide audit trail of configuration changes.',
    pagerdutyListAuditRecords,
    'read',
    ['compliance history'],
  ),
  entry(
    'pagerdutyListLogEntries',
    'Account-wide incident log entries (triggers, acks, escalations) for timeline review.',
    pagerdutyListLogEntries,
    'read',
    ['timeline', 'audit trail'],
  ),
  entry('pagerdutyGetLogEntry', 'Get one log entry by ID.', pagerdutyGetLogEntry, 'read', [
    'timeline',
    'audit trail',
  ]),
  entry(
    'pagerdutyUpdateLogEntryChannel',
    'Update the channel info on a log entry (e.g. conference bridge details).',
    pagerdutyUpdateLogEntryChannel,
    'write',
    ['timeline', 'audit trail', 'edit'],
  ),
  entry(
    'pagerdutyListStandards',
    'List service standards (recommended configuration practices).',
    pagerdutyListStandards,
    'read',
    ['best practice', 'compliance score'],
  ),
  entry(
    'pagerdutyGetStandardScores',
    'Get standards compliance scores for services or teams.',
    pagerdutyGetStandardScores,
    'read',
    ['best practice', 'compliance score'],
  ),
  entry(
    'pagerdutyUpdateStandard',
    'Activate/deactivate a standard or adjust its scope and description.',
    pagerdutyUpdateStandard,
    'write',
    ['best practice', 'compliance score', 'edit'],
  ),
  entry(
    'pagerdutyListEscalationPolicies',
    'List escalation policies with optional team and name filters.',
    pagerdutyListEscalationPolicies,
    'read',
    ['escalation chain', 'paging order', 'all policies'],
  ),
  entry(
    'pagerdutyGetEscalationPolicy',
    'Get one escalation policy with its rules, targets, and services.',
    pagerdutyGetEscalationPolicy,
    'read',
    ['escalation chain', 'paging order'],
  ),
  entry(
    'pagerdutyCreateEscalationPolicy',
    'Create an escalation policy: ordered rules of users/schedules with delays and loop count.',
    pagerdutyCreateEscalationPolicy,
    'write',
    ['escalation chain', 'paging order', 'new'],
  ),
  entry(
    'pagerdutyUpdateEscalationPolicy',
    'Update an escalation policy name, rules, targets, or loop count.',
    pagerdutyUpdateEscalationPolicy,
    'write',
    ['escalation chain', 'paging order', 'edit'],
  ),
  entry(
    'pagerdutyDeleteEscalationPolicy',
    'Delete an escalation policy. Services using it must be reassigned first.',
    pagerdutyDeleteEscalationPolicy,
    'delete',
    ['escalation chain', 'paging order', 'remove'],
  ),
  entry(
    'pagerdutyGetEscalationPolicyAudit',
    'Audit history of changes to an escalation policy.',
    pagerdutyGetEscalationPolicyAudit,
    'read',
    ['escalation chain', 'paging order', 'compliance history'],
  ),
  entry(
    'pagerdutyListTeams',
    'List account teams with optional name filter.',
    pagerdutyListTeams,
    'read',
    ['squad', 'group'],
  ),
  entry(
    'pagerdutyGetTeam',
    'Get one team with its roles and contact details.',
    pagerdutyGetTeam,
    'read',
    ['squad', 'group'],
  ),
  entry(
    'pagerdutyCreateTeam',
    'Create a team with a name, description, and default roles.',
    pagerdutyCreateTeam,
    'write',
    ['squad', 'group', 'new'],
  ),
  entry(
    'pagerdutyUpdateTeam',
    'Rename or update a team description.',
    pagerdutyUpdateTeam,
    'write',
    ['squad', 'group', 'edit'],
  ),
  entry(
    'pagerdutyDeleteTeam',
    'Delete a team. Members and services are unlinked, not deleted.',
    pagerdutyDeleteTeam,
    'delete',
    ['squad', 'group', 'remove'],
  ),
  entry(
    'pagerdutyListTeamMembers',
    'List users belonging to a team with their roles.',
    pagerdutyListTeamMembers,
    'read',
    ['squad', 'group'],
  ),
  entry(
    'pagerdutyAddUserToTeam',
    'Add a user to a team with a responder-role assignment.',
    pagerdutyAddUserToTeam,
    'write',
    ['squad', 'group', 'responder', 'member'],
  ),
  entry(
    'pagerdutyRemoveUserFromTeam',
    'Remove a user from a team.',
    pagerdutyRemoveUserFromTeam,
    'delete',
    ['squad', 'group', 'responder', 'member'],
  ),
  entry(
    'pagerdutyAddEscalationPolicyToTeam',
    'Associate an escalation policy with a team.',
    pagerdutyAddEscalationPolicyToTeam,
    'write',
    ['escalation chain', 'paging order', 'squad', 'group'],
  ),
  entry(
    'pagerdutyRemoveEscalationPolicyFromTeam',
    'Disassociate an escalation policy from a team.',
    pagerdutyRemoveEscalationPolicyFromTeam,
    'delete',
    ['escalation chain', 'paging order', 'squad', 'group'],
  ),
  entry(
    'pagerdutyListTeamNotificationSubscriptions',
    'List what a team is subscribed to (services/incidents) for notifications.',
    pagerdutyListTeamNotificationSubscriptions,
    'read',
    ['squad', 'group', 'page', 'alert delivery'],
  ),
  entry(
    'pagerdutyCreateTeamNotificationSubscription',
    'Subscribe a team to notifications for a service or incident.',
    pagerdutyCreateTeamNotificationSubscription,
    'write',
    ['squad', 'group', 'page', 'alert delivery', 'new'],
  ),
  entry(
    'pagerdutyUnsubscribeTeamNotifications',
    'Unsubscribe a team from one or more notification subscriptions.',
    pagerdutyUnsubscribeTeamNotifications,
    'delete',
    ['squad', 'group', 'page', 'alert delivery'],
  ),
  entry(
    'pagerdutyListIncidentNotes',
    'List timeline notes on an incident.',
    pagerdutyListIncidentNotes,
    'read',
    ['timeline comment'],
  ),
  entry(
    'pagerdutyCreateIncidentNote',
    'Post a note to an incident timeline for responder coordination.',
    pagerdutyCreateIncidentNote,
    'write',
    ['timeline comment', 'new'],
  ),
  entry(
    'pagerdutyUpdateIncidentNote',
    'Edit an existing incident note.',
    pagerdutyUpdateIncidentNote,
    'write',
    ['timeline comment', 'edit'],
  ),
  entry(
    'pagerdutyDeleteIncidentNote',
    'Delete an incident note.',
    pagerdutyDeleteIncidentNote,
    'delete',
    ['timeline comment', 'remove'],
  ),
  entry(
    'pagerdutyListIncidentAlerts',
    'List alerts grouped under an incident, filterable by status.',
    pagerdutyListIncidentAlerts,
    'read',
    ['firing alert'],
  ),
  entry(
    'pagerdutyGetIncidentAlert',
    'Get details of one alert within an incident.',
    pagerdutyGetIncidentAlert,
    'read',
    ['firing alert'],
  ),
  entry(
    'pagerdutyUpdateIncidentAlert',
    'Acknowledge or resolve a single alert inside an incident.',
    pagerdutyUpdateIncidentAlert,
    'write',
    ['firing alert', 'edit'],
  ),
  entry(
    'pagerdutyBulkUpdateIncidentAlerts',
    'Acknowledge or resolve many alerts in one incident at once.',
    pagerdutyBulkUpdateIncidentAlerts,
    'write',
    ['firing alert', 'edit'],
  ),
  entry(
    'pagerdutyListIncidentLogEntries',
    'List the audit log entries (triggers, acks, escalations, resolves) on an incident.',
    pagerdutyListIncidentLogEntries,
    'read',
    ['timeline', 'audit trail'],
  ),
  entry(
    'pagerdutyRequestResponders',
    'Page additional responders (users or escalation policies) to join an incident.',
    pagerdutyRequestResponders,
    'write',
    ['page someone', 'call in'],
  ),
  entry(
    'pagerdutyCancelResponderRequest',
    'Cancel a pending responder request on an incident.',
    pagerdutyCancelResponderRequest,
    'write',
    ['page someone', 'call in'],
  ),
  entry(
    'pagerdutyPostIncidentStatusUpdate',
    'Publish a stakeholder status update on an incident (optionally custom HTML email).',
    pagerdutyPostIncidentStatusUpdate,
    'write',
    ['stakeholder comms', 'broadcast', 'edit'],
  ),
  entry(
    'pagerdutyListStatusUpdateSubscribers',
    'List users/teams subscribed to an incident status updates.',
    pagerdutyListStatusUpdateSubscribers,
    'read',
    ['stakeholder comms', 'broadcast', 'edit'],
  ),
  entry(
    'pagerdutyAddStatusUpdateSubscribers',
    'Subscribe users or teams to an incident status updates.',
    pagerdutyAddStatusUpdateSubscribers,
    'write',
    ['stakeholder comms', 'broadcast', 'edit'],
  ),
  entry(
    'pagerdutyRemoveStatusUpdateSubscribers',
    'Unsubscribe users or teams from an incident status updates.',
    pagerdutyRemoveStatusUpdateSubscribers,
    'delete',
    ['stakeholder comms', 'broadcast', 'edit'],
  ),
  entry(
    'pagerdutyListIncidentTypes',
    'List incident types (e.g. default, major) used to categorize incidents.',
    pagerdutyListIncidentTypes,
    'read',
    ['category', 'severity class'],
  ),
  entry(
    'pagerdutyGetIncidentType',
    'Get one incident type by ID or name.',
    pagerdutyGetIncidentType,
    'read',
    ['category', 'severity class'],
  ),
  entry(
    'pagerdutyCreateIncidentType',
    'Create a new incident type for categorization.',
    pagerdutyCreateIncidentType,
    'write',
    ['category', 'severity class', 'new'],
  ),
  entry(
    'pagerdutyUpdateIncidentType',
    'Rename, describe, or enable/disable an incident type.',
    pagerdutyUpdateIncidentType,
    'write',
    ['category', 'severity class', 'edit'],
  ),
  entry(
    'pagerdutyListIncidentCustomFields',
    'List global incident custom fields available across incident types.',
    pagerdutyListIncidentCustomFields,
    'read',
    ['ticket field', 'metadata'],
  ),
  entry(
    'pagerdutyCreateIncidentCustomField',
    'Create a global incident custom field (text, number, single/multi-select, URL, datetime).',
    pagerdutyCreateIncidentCustomField,
    'write',
    ['ticket field', 'metadata', 'new'],
  ),
  entry(
    'pagerdutyGetIncidentCustomField',
    'Get one global incident custom field definition.',
    pagerdutyGetIncidentCustomField,
    'read',
    ['ticket field', 'metadata'],
  ),
  entry(
    'pagerdutyUpdateIncidentCustomField',
    'Update a global incident custom field name, label, or display settings.',
    pagerdutyUpdateIncidentCustomField,
    'write',
    ['ticket field', 'metadata', 'edit'],
  ),
  entry(
    'pagerdutyDeleteIncidentCustomField',
    'Delete a global incident custom field.',
    pagerdutyDeleteIncidentCustomField,
    'delete',
    ['ticket field', 'metadata', 'remove'],
  ),
  entry(
    'pagerdutyListIncidentFieldOptions',
    'List selectable options for a global incident custom field.',
    pagerdutyListIncidentFieldOptions,
    'read',
    ['dropdown values', 'select options'],
  ),
  entry(
    'pagerdutyCreateIncidentFieldOption',
    'Add a selectable option to a global incident custom field.',
    pagerdutyCreateIncidentFieldOption,
    'write',
    ['new'],
  ),
  entry(
    'pagerdutyUpdateIncidentFieldOption',
    'Rename a global incident custom field option.',
    pagerdutyUpdateIncidentFieldOption,
    'write',
    ['edit'],
  ),
  entry(
    'pagerdutyDeleteIncidentFieldOption',
    'Delete an option from a global incident custom field.',
    pagerdutyDeleteIncidentFieldOption,
    'delete',
    ['remove'],
  ),
  entry(
    'pagerdutyGetIncidentCustomFieldValues',
    'Read the custom field values set on an incident.',
    pagerdutyGetIncidentCustomFieldValues,
    'read',
    ['ticket field', 'metadata'],
  ),
  entry(
    'pagerdutyUpdateIncidentCustomFieldValues',
    'Set custom field values on an incident (e.g. ticket link, customer impact).',
    pagerdutyUpdateIncidentCustomFieldValues,
    'write',
    ['ticket field', 'metadata', 'edit'],
  ),
  entry(
    'pagerdutyListTypeCustomFields',
    'List custom fields attached to a specific incident type.',
    pagerdutyListTypeCustomFields,
    'read',
    ['ticket field', 'metadata'],
  ),
  entry(
    'pagerdutyCreateTypeCustomField',
    'Attach a custom field to a specific incident type.',
    pagerdutyCreateTypeCustomField,
    'write',
    ['ticket field', 'metadata', 'new'],
  ),
  entry(
    'pagerdutyListIncidents',
    'List incidents with filters for status, urgency, service, team, assignee, and date range. Start here for incident triage and queue overviews.',
    pagerdutyListIncidents,
    'read',
    ['triage queue', 'open incidents', 'all incidents'],
  ),
  entry(
    'pagerdutyGetIncident',
    'Get full details of one incident by ID, with optional embedded relations.',
    pagerdutyGetIncident,
    'read',
    ['incident details', 'single incident'],
  ),
  entry(
    'pagerdutyCreateIncident',
    'Trigger a new incident on a service. Requires the acting user email (From header) and a service ID.',
    pagerdutyCreateIncident,
    'write',
    ['new'],
  ),
  entry(
    'pagerdutyUpdateIncident',
    'Acknowledge, resolve, reassign, escalate, or retitle an incident. Resolving accepts an optional resolution note.',
    pagerdutyUpdateIncident,
    'write',
    ['edit'],
  ),
  entry(
    'pagerdutyMergeIncidents',
    'Merge source incidents into a target incident; sources are resolved. Use for duplicate/alert-storm cleanup.',
    pagerdutyMergeIncidents,
    'write',
    ['combine', 'dedupe', 'duplicates'],
  ),
  entry(
    'pagerdutySnoozeIncident',
    'Snooze a triggered incident for a duration; it returns to triggered when the timer elapses.',
    pagerdutySnoozeIncident,
    'write',
    ['silence', 'pause alerts'],
  ),
  entry(
    'pagerdutyGetIncidentOutlier',
    'Get the outlier incident most similar to this one, useful for finding related past work.',
    pagerdutyGetIncidentOutlier,
    'read',
    ['similar', 'context'],
  ),
  entry(
    'pagerdutyGetPastIncidents',
    'List past incidents on the same service, useful for recurrence and context checks.',
    pagerdutyGetPastIncidents,
    'read',
    ['similar', 'context'],
  ),
  entry(
    'pagerdutyGetRelatedIncidents',
    'List incidents related to this one via alert grouping or recent-merge links.',
    pagerdutyGetRelatedIncidents,
    'read',
    ['similar', 'context'],
  ),
  entry(
    'pagerdutyGetRelatedChangeEvents',
    'List recent change events (deploys, config changes) related to an incident for blast-radius analysis.',
    pagerdutyGetRelatedChangeEvents,
    'read',
    ['deploy', 'release', 'similar', 'context'],
  ),
  entry(
    'pagerdutyGetIncidentBusinessImpacts',
    'Show which business services an incident is impacting.',
    pagerdutyGetIncidentBusinessImpacts,
    'read',
    ['impacted services', 'blast radius'],
  ),
  entry(
    'pagerdutySetIncidentBusinessImpact',
    'Mark a business service as impacted (or not) by an incident for status-page accuracy.',
    pagerdutySetIncidentBusinessImpact,
    'write',
    ['mark impacted', 'blast radius'],
  ),
  entry(
    'pagerdutyListMaintenanceWindows',
    'List maintenance windows (planned downtime suppressing notifications).',
    pagerdutyListMaintenanceWindows,
    'read',
    ['downtime', 'blackout'],
  ),
  entry(
    'pagerdutyGetMaintenanceWindow',
    'Get one maintenance window with its services and time range.',
    pagerdutyGetMaintenanceWindow,
    'read',
    ['downtime', 'blackout'],
  ),
  entry(
    'pagerdutyCreateMaintenanceWindow',
    'Schedule planned downtime on services to suppress notifications.',
    pagerdutyCreateMaintenanceWindow,
    'write',
    ['downtime', 'blackout', 'new'],
  ),
  entry(
    'pagerdutyUpdateMaintenanceWindow',
    'Reschedule or re-scope a maintenance window.',
    pagerdutyUpdateMaintenanceWindow,
    'write',
    ['downtime', 'blackout', 'edit'],
  ),
  entry(
    'pagerdutyDeleteMaintenanceWindow',
    'Delete a maintenance window, re-enabling notifications immediately.',
    pagerdutyDeleteMaintenanceWindow,
    'delete',
    ['downtime', 'blackout', 'remove'],
  ),
  entry(
    'pagerdutyListTags',
    'List tags used across services, teams, and policies.',
    pagerdutyListTags,
    'read',
    ['label'],
  ),
  entry('pagerdutyCreateTag', 'Create a new tag label.', pagerdutyCreateTag, 'write', [
    'label',
    'new',
  ]),
  entry('pagerdutyGetTag', 'Get a tag by ID.', pagerdutyGetTag, 'read', ['label']),
  entry(
    'pagerdutyDeleteTag',
    'Delete a tag label from the account.',
    pagerdutyDeleteTag,
    'delete',
    ['label', 'remove'],
  ),
  entry(
    'pagerdutyListEntityTags',
    'List tags on services, teams, or escalation policies.',
    pagerdutyListEntityTags,
    'read',
    ['label'],
  ),
  entry(
    'pagerdutySetEntityTags',
    'Replace all tags on services, teams, or escalation policies.',
    pagerdutySetEntityTags,
    'write',
    ['label'],
  ),
  entry(
    'pagerdutyListPriorities',
    'List incident priorities (P1-P5) with IDs needed for incident creation.',
    pagerdutyListPriorities,
    'read',
    ['p1-p5', 'severity levels'],
  ),
  entry(
    'pagerdutyListAbilities',
    'List account abilities/feature flags (e.g. SSO, audit, event orchestration).',
    pagerdutyListAbilities,
    'read',
    ['feature flags', 'plan capabilities'],
  ),
  entry(
    'pagerdutyGetAbility',
    'Check whether one ability is enabled on the account.',
    pagerdutyGetAbility,
    'read',
    ['feature flag'],
  ),
  entry(
    'pagerdutyListLicenses',
    'List license types available on the account.',
    pagerdutyListLicenses,
    'read',
    ['seat'],
  ),
  entry(
    'pagerdutyListLicenseAllocations',
    'List how licenses are allocated across the account.',
    pagerdutyListLicenseAllocations,
    'read',
    ['seat'],
  ),
  entry(
    'pagerdutyListNotifications',
    'List notifications sent to users (pages, emails, pushes) for review.',
    pagerdutyListNotifications,
    'read',
    ['page', 'alert delivery'],
  ),
  entry(
    'pagerdutyListEventOrchestrations',
    'List global event orchestrations that route events to services.',
    pagerdutyListEventOrchestrations,
    'read',
    ['event routing', 'enrichment'],
  ),
  entry(
    'pagerdutyGetEventOrchestration',
    'Get one event orchestration with routes and integrations summary.',
    pagerdutyGetEventOrchestration,
    'read',
    ['event routing', 'enrichment'],
  ),
  entry(
    'pagerdutyCreateEventOrchestration',
    'Create a global event orchestration for cross-service event routing.',
    pagerdutyCreateEventOrchestration,
    'write',
    ['event routing', 'enrichment', 'new'],
  ),
  entry(
    'pagerdutyUpdateEventOrchestration',
    'Rename or update an event orchestration.',
    pagerdutyUpdateEventOrchestration,
    'write',
    ['event routing', 'enrichment', 'edit'],
  ),
  entry(
    'pagerdutyDeleteEventOrchestration',
    'Delete a global event orchestration.',
    pagerdutyDeleteEventOrchestration,
    'delete',
    ['event routing', 'enrichment', 'remove'],
  ),
  entry(
    'pagerdutyGetOrchestrationRouter',
    'Get the router (ordered route rules) of an event orchestration.',
    pagerdutyGetOrchestrationRouter,
    'read',
    ['event routing', 'enrichment'],
  ),
  entry(
    'pagerdutyUpdateOrchestrationRouter',
    'Replace the router rules that decide which service receives an event.',
    pagerdutyUpdateOrchestrationRouter,
    'write',
    ['event routing', 'enrichment', 'edit'],
  ),
  entry(
    'pagerdutyGetOrchestrationGlobal',
    'Get the global ruleset applied to all events in an orchestration.',
    pagerdutyGetOrchestrationGlobal,
    'read',
    ['event routing', 'enrichment'],
  ),
  entry(
    'pagerdutyUpdateOrchestrationGlobal',
    'Replace the global ruleset of an orchestration (normalization, suppression).',
    pagerdutyUpdateOrchestrationGlobal,
    'write',
    ['event routing', 'enrichment', 'edit'],
  ),
  entry(
    'pagerdutyGetOrchestrationUnrouted',
    'Get the unrouted-catch-all rules for an orchestration.',
    pagerdutyGetOrchestrationUnrouted,
    'read',
    ['event routing', 'enrichment'],
  ),
  entry(
    'pagerdutyUpdateOrchestrationUnrouted',
    'Replace the unrouted rules handling events that match nothing.',
    pagerdutyUpdateOrchestrationUnrouted,
    'write',
    ['event routing', 'enrichment', 'edit'],
  ),
  entry(
    'pagerdutyListOrchestrationIntegrations',
    'List integrations feeding an event orchestration (with routing keys).',
    pagerdutyListOrchestrationIntegrations,
    'read',
    ['event routing', 'enrichment', 'api key', 'routing key'],
  ),
  entry(
    'pagerdutyCreateOrchestrationIntegration',
    'Create an integration key on an orchestration for event ingestion.',
    pagerdutyCreateOrchestrationIntegration,
    'write',
    ['event routing', 'enrichment', 'api key', 'routing key', 'new'],
  ),
  entry(
    'pagerdutyGetOrchestrationIntegration',
    'Get one orchestration integration with its routing key.',
    pagerdutyGetOrchestrationIntegration,
    'read',
    ['event routing', 'enrichment', 'api key', 'routing key'],
  ),
  entry(
    'pagerdutyUpdateOrchestrationIntegration',
    'Rename an orchestration integration.',
    pagerdutyUpdateOrchestrationIntegration,
    'write',
    ['event routing', 'enrichment', 'api key', 'routing key', 'edit'],
  ),
  entry(
    'pagerdutyDeleteOrchestrationIntegration',
    'Delete an orchestration integration. Events sent to its key will be rejected.',
    pagerdutyDeleteOrchestrationIntegration,
    'delete',
    ['event routing', 'enrichment', 'api key', 'routing key', 'remove'],
  ),
  entry(
    'pagerdutyMigrateOrchestrationIntegration',
    'Move an integration (and its key) from one orchestration to another.',
    pagerdutyMigrateOrchestrationIntegration,
    'write',
    ['event routing', 'enrichment', 'api key', 'routing key'],
  ),
  entry(
    'pagerdutyGetServiceOrchestration',
    'Get the service-level orchestration (rules applied after routing) for a service.',
    pagerdutyGetServiceOrchestration,
    'read',
    ['event routing', 'enrichment', 'monitored endpoint'],
  ),
  entry(
    'pagerdutyUpdateServiceOrchestration',
    'Replace the service-level orchestration rules for a service.',
    pagerdutyUpdateServiceOrchestration,
    'write',
    ['event routing', 'enrichment', 'monitored endpoint', 'edit'],
  ),
  entry(
    'pagerdutyGetServiceOrchestrationActive',
    'Show which orchestration version (rules vs orchestration) is active for a service.',
    pagerdutyGetServiceOrchestrationActive,
    'read',
    ['event routing', 'enrichment', 'monitored endpoint'],
  ),
  entry(
    'pagerdutySetServiceOrchestrationActive',
    'Switch a service between legacy event rules and the newer orchestration engine.',
    pagerdutySetServiceOrchestrationActive,
    'write',
    ['event routing', 'enrichment', 'monitored endpoint'],
  ),
  entry('pagerdutyListRulesets', 'List legacy event rulesets.', pagerdutyListRulesets, 'read', [
    'legacy rules',
  ]),
  entry(
    'pagerdutyGetRuleset',
    'Get one event ruleset with creator and team info.',
    pagerdutyGetRuleset,
    'read',
    ['legacy rules'],
  ),
  entry(
    'pagerdutyCreateRuleset',
    'Create a legacy event ruleset for a team.',
    pagerdutyCreateRuleset,
    'write',
    ['legacy rules', 'new'],
  ),
  entry(
    'pagerdutyUpdateRuleset',
    'Rename a legacy event ruleset.',
    pagerdutyUpdateRuleset,
    'write',
    ['legacy rules', 'edit'],
  ),
  entry(
    'pagerdutyDeleteRuleset',
    'Delete a legacy event ruleset and its rules.',
    pagerdutyDeleteRuleset,
    'delete',
    ['legacy rules', 'remove'],
  ),
  entry(
    'pagerdutyListRulesetRules',
    'List rules inside a legacy ruleset.',
    pagerdutyListRulesetRules,
    'read',
    ['legacy rules'],
  ),
  entry(
    'pagerdutyGetRulesetRule',
    'Get one legacy ruleset rule with conditions and actions.',
    pagerdutyGetRulesetRule,
    'read',
    ['legacy rules'],
  ),
  entry(
    'pagerdutyCreateRulesetRule',
    'Create a rule in a legacy ruleset with conditions and actions.',
    pagerdutyCreateRulesetRule,
    'write',
    ['legacy rules', 'new'],
  ),
  entry(
    'pagerdutyUpdateRulesetRule',
    'Update a legacy ruleset rule.',
    pagerdutyUpdateRulesetRule,
    'write',
    ['legacy rules', 'edit'],
  ),
  entry(
    'pagerdutyDeleteRulesetRule',
    'Delete a rule from a legacy ruleset.',
    pagerdutyDeleteRulesetRule,
    'delete',
    ['legacy rules', 'remove'],
  ),
  entry(
    'pagerdutyListWorkflows',
    'List incident workflows (automated multi-step responders for incidents).',
    pagerdutyListWorkflows,
    'read',
    ['playbook automation'],
  ),
  entry(
    'pagerdutyGetWorkflow',
    'Get one incident workflow with its steps.',
    pagerdutyGetWorkflow,
    'read',
    ['playbook automation'],
  ),
  entry(
    'pagerdutyCreateWorkflow',
    'Create an incident workflow with steps and team ownership.',
    pagerdutyCreateWorkflow,
    'write',
    ['playbook automation', 'new'],
  ),
  entry(
    'pagerdutyUpdateWorkflow',
    'Update an incident workflow name, steps, or enabled state.',
    pagerdutyUpdateWorkflow,
    'write',
    ['playbook automation', 'edit'],
  ),
  entry(
    'pagerdutyDeleteWorkflow',
    'Delete an incident workflow and its triggers.',
    pagerdutyDeleteWorkflow,
    'delete',
    ['playbook automation', 'remove'],
  ),
  entry(
    'pagerdutyRunWorkflowInstance',
    'Manually start an incident workflow on an incident.',
    pagerdutyRunWorkflowInstance,
    'write',
    ['playbook automation'],
  ),
  entry(
    'pagerdutyListWorkflowActions',
    'List reusable workflow actions available as incident workflow steps.',
    pagerdutyListWorkflowActions,
    'read',
    ['playbook automation'],
  ),
  entry(
    'pagerdutyGetWorkflowAction',
    'Get one reusable workflow action with its inputs.',
    pagerdutyGetWorkflowAction,
    'read',
    ['playbook automation'],
  ),
  entry(
    'pagerdutyListWorkflowTriggers',
    'List incident workflow triggers, filterable by workflow, service, or incident.',
    pagerdutyListWorkflowTriggers,
    'read',
    ['auto-start', 'firing condition', 'playbook automation'],
  ),
  entry(
    'pagerdutyGetWorkflowTrigger',
    'Get one incident workflow trigger with services and condition.',
    pagerdutyGetWorkflowTrigger,
    'read',
    ['auto-start', 'firing condition', 'playbook automation'],
  ),
  entry(
    'pagerdutyCreateWorkflowTrigger',
    'Create a trigger that starts a workflow manually, conditionally, or per incident type.',
    pagerdutyCreateWorkflowTrigger,
    'write',
    ['auto-start', 'firing condition', 'playbook automation', 'new'],
  ),
  entry(
    'pagerdutyUpdateWorkflowTrigger',
    'Update a workflow trigger condition, services, or permissions.',
    pagerdutyUpdateWorkflowTrigger,
    'write',
    ['auto-start', 'firing condition', 'playbook automation', 'edit'],
  ),
  entry(
    'pagerdutyDeleteWorkflowTrigger',
    'Delete an incident workflow trigger.',
    pagerdutyDeleteWorkflowTrigger,
    'delete',
    ['auto-start', 'firing condition', 'playbook automation', 'remove'],
  ),
  entry(
    'pagerdutyAddServiceToWorkflowTrigger',
    'Subscribe one more service to an existing workflow trigger.',
    pagerdutyAddServiceToWorkflowTrigger,
    'write',
    ['auto-start', 'firing condition', 'playbook automation', 'monitored endpoint'],
  ),
  entry(
    'pagerdutyRemoveServiceFromWorkflowTrigger',
    'Remove a service from a workflow trigger.',
    pagerdutyRemoveServiceFromWorkflowTrigger,
    'delete',
    ['auto-start', 'firing condition', 'playbook automation', 'monitored endpoint'],
  ),
  entry(
    'pagerdutyListSchedules',
    'List on-call schedules with optional name and time-zone handling.',
    pagerdutyListSchedules,
    'read',
    ['rota', 'rotation', 'roster'],
  ),
  entry(
    'pagerdutyGetSchedule',
    'Get a schedule with layers, rotations, and final-schedule entries for a window.',
    pagerdutyGetSchedule,
    'read',
    ['rota', 'rotation', 'roster'],
  ),
  entry(
    'pagerdutyCreateSchedule',
    'Create an on-call schedule with rotation layers.',
    pagerdutyCreateSchedule,
    'write',
    ['rota', 'rotation', 'roster', 'new'],
  ),
  entry(
    'pagerdutyUpdateSchedule',
    'Update a schedule name, zone, description, or rotation layers.',
    pagerdutyUpdateSchedule,
    'write',
    ['rota', 'rotation', 'roster', 'edit'],
  ),
  entry(
    'pagerdutyDeleteSchedule',
    'Delete a schedule. Remove it from escalation policies first.',
    pagerdutyDeleteSchedule,
    'delete',
    ['rota', 'rotation', 'roster', 'remove'],
  ),
  entry(
    'pagerdutyPreviewSchedule',
    'Preview how a schedule renders (final timetable) without saving it.',
    pagerdutyPreviewSchedule,
    'read',
    ['rota', 'rotation', 'roster'],
  ),
  entry(
    'pagerdutyListScheduleOverrides',
    'List overrides (OOO cover, swaps) on a schedule within a window.',
    pagerdutyListScheduleOverrides,
    'read',
    ['ooo cover', 'swap', 'out of office', 'rota', 'rotation'],
  ),
  entry(
    'pagerdutyCreateScheduleOverride',
    'Create schedule overrides for vacations, swaps, or temporary cover.',
    pagerdutyCreateScheduleOverride,
    'write',
    ['ooo cover', 'swap', 'out of office', 'rota', 'rotation'],
  ),
  entry(
    'pagerdutyDeleteScheduleOverride',
    'Delete a schedule override to restore the normal rotation.',
    pagerdutyDeleteScheduleOverride,
    'delete',
    ['ooo cover', 'swap', 'out of office', 'rota', 'rotation'],
  ),
  entry(
    'pagerdutyListScheduleUsers',
    'List all users participating in a schedule.',
    pagerdutyListScheduleUsers,
    'read',
    ['rota', 'rotation', 'roster', 'responder', 'member'],
  ),
  entry(
    'pagerdutyListOncalls',
    'Who is on call now (or in a window), filterable by user, schedule, policy, or team. Use for "who do I page" questions.',
    pagerdutyListOncalls,
    'read',
    ['who is on call', 'rota', 'shift'],
  ),
  entry(
    'pagerdutyListServices',
    'List monitored services with optional team, name, and status filters.',
    pagerdutyListServices,
    'read',
    ['monitored endpoint'],
  ),
  entry(
    'pagerdutyGetService',
    'Get one service with its escalation policy, integrations, and urgency rules.',
    pagerdutyGetService,
    'read',
    ['monitored endpoint'],
  ),
  entry(
    'pagerdutyCreateService',
    'Create a monitored service with an escalation policy and urgency rules.',
    pagerdutyCreateService,
    'write',
    ['monitored endpoint', 'new'],
  ),
  entry(
    'pagerdutyUpdateService',
    'Update a service name, policies, urgency rules, or team ownership.',
    pagerdutyUpdateService,
    'write',
    ['monitored endpoint', 'edit'],
  ),
  entry(
    'pagerdutyDeleteService',
    'Delete a service. Incidents on it become orphaned — reassign first if needed.',
    pagerdutyDeleteService,
    'delete',
    ['monitored endpoint', 'remove'],
  ),
  entry(
    'pagerdutyCreateServiceIntegration',
    'Add an inbound integration (Events API, email, monitoring tool) to a service. Returns routing/integration keys.',
    pagerdutyCreateServiceIntegration,
    'write',
    ['monitored endpoint', 'api key', 'routing key', 'new'],
  ),
  entry(
    'pagerdutyGetServiceIntegration',
    'Get one service integration including its keys and vendor details.',
    pagerdutyGetServiceIntegration,
    'read',
    ['monitored endpoint', 'api key', 'routing key'],
  ),
  entry(
    'pagerdutyUpdateServiceIntegration',
    'Rename or reconfigure a service integration.',
    pagerdutyUpdateServiceIntegration,
    'write',
    ['monitored endpoint', 'api key', 'routing key', 'edit'],
  ),
  entry(
    'pagerdutyListServiceEventRules',
    'List event rules that route/transform events for a service.',
    pagerdutyListServiceEventRules,
    'read',
    ['event rule', 'monitored endpoint'],
  ),
  entry(
    'pagerdutyGetServiceEventRule',
    'Get one service event rule with its conditions and actions.',
    pagerdutyGetServiceEventRule,
    'read',
    ['event rule', 'monitored endpoint'],
  ),
  entry(
    'pagerdutyCreateServiceEventRule',
    'Create a service event rule with conditions and routing/suppression actions.',
    pagerdutyCreateServiceEventRule,
    'write',
    ['event rule', 'monitored endpoint', 'new'],
  ),
  entry(
    'pagerdutyUpdateServiceEventRule',
    'Update a service event rule conditions, actions, or position.',
    pagerdutyUpdateServiceEventRule,
    'write',
    ['event rule', 'monitored endpoint', 'edit'],
  ),
  entry(
    'pagerdutyDeleteServiceEventRule',
    'Delete a service event rule.',
    pagerdutyDeleteServiceEventRule,
    'delete',
    ['event rule', 'monitored endpoint', 'remove'],
  ),
  entry(
    'pagerdutyConvertServiceEventRule',
    'Convert a service event ruleset to the newer event orchestration format.',
    pagerdutyConvertServiceEventRule,
    'write',
    ['event rule', 'monitored endpoint'],
  ),
  entry(
    'pagerdutyListServiceChangeEvents',
    'List change events (deploys, releases) recorded against a service.',
    pagerdutyListServiceChangeEvents,
    'read',
    ['deploy', 'release', 'monitored endpoint'],
  ),
  entry(
    'pagerdutyGetServiceAuditRecords',
    'Audit history of configuration changes on a service.',
    pagerdutyGetServiceAuditRecords,
    'read',
    ['compliance history', 'monitored endpoint'],
  ),
  entry(
    'pagerdutyListStatusPages',
    'List status pages for external stakeholder communication.',
    pagerdutyListStatusPages,
    'read',
    ['public status', 'external comms'],
  ),
  entry(
    'pagerdutyGetStatusPageImpacts',
    'Current incident impacts shown on a status page.',
    pagerdutyGetStatusPageImpacts,
    'read',
    ['public status', 'external comms'],
  ),
  entry(
    'pagerdutyGetStatusPageImpact',
    'Details of one impact entry on a status page.',
    pagerdutyGetStatusPageImpact,
    'read',
    ['public status', 'external comms'],
  ),
  entry(
    'pagerdutyListStatusPagePosts',
    'List public posts/updates published on a status page.',
    pagerdutyListStatusPagePosts,
    'read',
    ['public status', 'external comms'],
  ),
  entry(
    'pagerdutyGetStatusPagePost',
    'Get one status page post with its updates.',
    pagerdutyGetStatusPagePost,
    'read',
    ['public status', 'external comms'],
  ),
  entry(
    'pagerdutyCreateStatusPagePost',
    'Publish a new post on a status page about an ongoing event.',
    pagerdutyCreateStatusPagePost,
    'write',
    ['public status', 'external comms', 'new'],
  ),
  entry(
    'pagerdutyUpdateStatusPagePost',
    'Edit a status page post title, message, severity, or status.',
    pagerdutyUpdateStatusPagePost,
    'write',
    ['public status', 'external comms', 'edit'],
  ),
  entry(
    'pagerdutyDeleteStatusPagePost',
    'Delete a status page post.',
    pagerdutyDeleteStatusPagePost,
    'delete',
    ['public status', 'external comms', 'remove'],
  ),
  entry(
    'pagerdutyListPostUpdates',
    'List incremental updates appended to a status page post.',
    pagerdutyListPostUpdates,
    'read',
    ['edit'],
  ),
  entry(
    'pagerdutyCreatePostUpdate',
    'Append an update to a status page post as an event evolves.',
    pagerdutyCreatePostUpdate,
    'write',
    ['new', 'edit'],
  ),
  entry(
    'pagerdutyGetPostUpdate',
    'Get one status page post update.',
    pagerdutyGetPostUpdate,
    'read',
    ['edit'],
  ),
  entry(
    'pagerdutyUpdatePostUpdate',
    'Edit a status page post update.',
    pagerdutyUpdatePostUpdate,
    'write',
    ['edit'],
  ),
  entry(
    'pagerdutyDeletePostUpdate',
    'Delete a status page post update.',
    pagerdutyDeletePostUpdate,
    'delete',
    ['edit', 'remove'],
  ),
  entry(
    'pagerdutyGetPostPostmortem',
    'Get the postmortem attached to a status page post.',
    pagerdutyGetPostPostmortem,
    'read',
    ['retrospective', 'rca'],
  ),
  entry(
    'pagerdutyUpdatePostPostmortem',
    'Attach or update the postmortem on a status page post.',
    pagerdutyUpdatePostPostmortem,
    'write',
    ['retrospective', 'rca', 'edit'],
  ),
  entry(
    'pagerdutyDeletePostPostmortem',
    'Remove the postmortem from a status page post.',
    pagerdutyDeletePostPostmortem,
    'delete',
    ['retrospective', 'rca', 'remove'],
  ),
  entry(
    'pagerdutyListStatusPageSubscriptions',
    'List subscribers to a status page.',
    pagerdutyListStatusPageSubscriptions,
    'read',
    ['public status', 'external comms'],
  ),
  entry(
    'pagerdutyCreateStatusPageSubscription',
    'Subscribe an email/phone to status page notifications.',
    pagerdutyCreateStatusPageSubscription,
    'write',
    ['public status', 'external comms', 'new'],
  ),
  entry(
    'pagerdutyDeleteStatusPageSubscription',
    'Remove a status page subscription.',
    pagerdutyDeleteStatusPageSubscription,
    'delete',
    ['public status', 'external comms', 'remove'],
  ),
  entry(
    'pagerdutyListStatusPageSeverities',
    'List severity levels usable on a status page.',
    pagerdutyListStatusPageSeverities,
    'read',
    ['public status', 'external comms'],
  ),
  entry(
    'pagerdutyListStatusPageStatuses',
    'List incident statuses usable on a status page.',
    pagerdutyListStatusPageStatuses,
    'read',
    ['public status', 'external comms'],
  ),
  entry(
    'pagerdutyListStatusPageServices',
    'List services displayed on a status page.',
    pagerdutyListStatusPageServices,
    'read',
    ['monitored endpoint', 'public status', 'external comms'],
  ),
  entry(
    'pagerdutyListStatusDashboards',
    'List internal status dashboards.',
    pagerdutyListStatusDashboards,
    'read',
    ['internal status'],
  ),
  entry(
    'pagerdutyGetStatusDashboard',
    'Get one status dashboard by ID.',
    pagerdutyGetStatusDashboard,
    'read',
    ['internal status'],
  ),
  entry(
    'pagerdutyGetStatusDashboardBySlug',
    'Get a status dashboard by its URL slug.',
    pagerdutyGetStatusDashboardBySlug,
    'read',
    ['internal status'],
  ),
  entry(
    'pagerdutyGetDashboardServiceImpacts',
    'Service impacts shown on a status dashboard.',
    pagerdutyGetDashboardServiceImpacts,
    'read',
    ['monitored endpoint'],
  ),
  entry(
    'pagerdutyListTemplates',
    'List status-update templates for consistent stakeholder comms.',
    pagerdutyListTemplates,
    'read',
    ['canned message'],
  ),
  entry(
    'pagerdutyGetTemplate',
    'Get one status-update template with its body and subject.',
    pagerdutyGetTemplate,
    'read',
    ['canned message'],
  ),
  entry(
    'pagerdutyCreateTemplate',
    'Create a reusable status-update template.',
    pagerdutyCreateTemplate,
    'write',
    ['canned message', 'new'],
  ),
  entry(
    'pagerdutyUpdateTemplate',
    'Update a status-update template content.',
    pagerdutyUpdateTemplate,
    'write',
    ['canned message', 'edit'],
  ),
  entry(
    'pagerdutyDeleteTemplate',
    'Delete a status-update template.',
    pagerdutyDeleteTemplate,
    'delete',
    ['canned message', 'remove'],
  ),
  entry(
    'pagerdutyListTemplateFields',
    'List available template placeholder fields for rendering.',
    pagerdutyListTemplateFields,
    'read',
    ['canned message'],
  ),
  entry(
    'pagerdutyRenderTemplate',
    'Render a status-update template against an incident to preview the message.',
    pagerdutyRenderTemplate,
    'read',
    ['canned message'],
  ),
  entry(
    'pagerdutyListGlobalCacheVariables',
    'List cache variables on a global event orchestration.',
    pagerdutyListGlobalCacheVariables,
    'read',
    ['lookup table'],
  ),
  entry(
    'pagerdutyCreateGlobalCacheVariable',
    'Create a cache variable for orchestration rules (e.g. lookups, thresholds).',
    pagerdutyCreateGlobalCacheVariable,
    'write',
    ['lookup table', 'new'],
  ),
  entry(
    'pagerdutyGetGlobalCacheVariable',
    'Get one global orchestration cache variable.',
    pagerdutyGetGlobalCacheVariable,
    'read',
    ['lookup table'],
  ),
  entry(
    'pagerdutyUpdateGlobalCacheVariable',
    'Update a global orchestration cache variable.',
    pagerdutyUpdateGlobalCacheVariable,
    'write',
    ['lookup table', 'edit'],
  ),
  entry(
    'pagerdutyDeleteGlobalCacheVariable',
    'Delete a global orchestration cache variable.',
    pagerdutyDeleteGlobalCacheVariable,
    'delete',
    ['lookup table', 'remove'],
  ),
  entry(
    'pagerdutyListServiceCacheVariables',
    'List cache variables on a service-level orchestration.',
    pagerdutyListServiceCacheVariables,
    'read',
    ['monitored endpoint', 'lookup table'],
  ),
  entry(
    'pagerdutyCreateServiceCacheVariable',
    'Create a cache variable on a service-level orchestration.',
    pagerdutyCreateServiceCacheVariable,
    'write',
    ['monitored endpoint', 'lookup table', 'new'],
  ),
  entry(
    'pagerdutyGetServiceCacheVariable',
    'Get one service orchestration cache variable.',
    pagerdutyGetServiceCacheVariable,
    'read',
    ['monitored endpoint', 'lookup table'],
  ),
  entry(
    'pagerdutyUpdateServiceCacheVariable',
    'Update a service orchestration cache variable.',
    pagerdutyUpdateServiceCacheVariable,
    'write',
    ['monitored endpoint', 'lookup table', 'edit'],
  ),
  entry(
    'pagerdutyDeleteServiceCacheVariable',
    'Delete a service orchestration cache variable.',
    pagerdutyDeleteServiceCacheVariable,
    'delete',
    ['monitored endpoint', 'lookup table', 'remove'],
  ),
  entry(
    'pagerdutyListHandoffNotificationRules',
    'List a user on-call handoff notification rules.',
    pagerdutyListHandoffNotificationRules,
    'read',
    ['paging order', 'shift handover'],
  ),
  entry(
    'pagerdutyCreateHandoffNotificationRule',
    'Notify a user when an on-call handoff occurs on selected policies.',
    pagerdutyCreateHandoffNotificationRule,
    'write',
    ['paging order', 'shift handover', 'new'],
  ),
  entry(
    'pagerdutyGetHandoffNotificationRule',
    'Get one on-call handoff notification rule.',
    pagerdutyGetHandoffNotificationRule,
    'read',
    ['paging order', 'shift handover'],
  ),
  entry(
    'pagerdutyUpdateHandoffNotificationRule',
    'Update an on-call handoff notification rule contact method or scope.',
    pagerdutyUpdateHandoffNotificationRule,
    'write',
    ['paging order', 'shift handover', 'edit'],
  ),
  entry(
    'pagerdutyDeleteHandoffNotificationRule',
    'Delete an on-call handoff notification rule.',
    pagerdutyDeleteHandoffNotificationRule,
    'delete',
    ['paging order', 'shift handover', 'remove'],
  ),
  entry(
    'pagerdutyListUserStatusUpdateRules',
    'List a user incident status-update notification rules.',
    pagerdutyListUserStatusUpdateRules,
    'read',
    ['stakeholder comms', 'broadcast', 'responder', 'member', 'edit'],
  ),
  entry(
    'pagerdutyCreateUserStatusUpdateRule',
    'Add an incident status-update notification rule for a user.',
    pagerdutyCreateUserStatusUpdateRule,
    'write',
    ['stakeholder comms', 'broadcast', 'responder', 'member', 'new'],
  ),
  entry(
    'pagerdutyGetUserStatusUpdateRule',
    'Get one user status-update notification rule.',
    pagerdutyGetUserStatusUpdateRule,
    'read',
    ['stakeholder comms', 'broadcast', 'responder', 'member', 'edit'],
  ),
  entry(
    'pagerdutyUpdateUserStatusUpdateRule',
    'Change the contact method of a status-update notification rule.',
    pagerdutyUpdateUserStatusUpdateRule,
    'write',
    ['stakeholder comms', 'broadcast', 'responder', 'member', 'edit'],
  ),
  entry(
    'pagerdutyDeleteUserStatusUpdateRule',
    'Delete a user status-update notification rule.',
    pagerdutyDeleteUserStatusUpdateRule,
    'delete',
    ['stakeholder comms', 'broadcast', 'responder', 'member', 'edit'],
  ),
  entry(
    'pagerdutyListUserSessions',
    'List active sessions for a user (SSO/mobile) for security review.',
    pagerdutyListUserSessions,
    'read',
    ['responder', 'member', 'sso login'],
  ),
  entry(
    'pagerdutyDeleteUserSession',
    'Revoke one user session by type and ID.',
    pagerdutyDeleteUserSession,
    'delete',
    ['responder', 'member', 'sso login', 'remove'],
  ),
  entry(
    'pagerdutyListUserNotificationSubscriptions',
    'List what a user is subscribed to for notifications.',
    pagerdutyListUserNotificationSubscriptions,
    'read',
    ['responder', 'member', 'page', 'alert delivery'],
  ),
  entry(
    'pagerdutyCreateUserNotificationSubscription',
    'Subscribe a user to notifications for a service, team, or incident.',
    pagerdutyCreateUserNotificationSubscription,
    'write',
    ['responder', 'member', 'page', 'alert delivery', 'new'],
  ),
  entry(
    'pagerdutyUnsubscribeUserNotifications',
    'Unsubscribe a user from notification subscriptions.',
    pagerdutyUnsubscribeUserNotifications,
    'delete',
    ['responder', 'member', 'page', 'alert delivery'],
  ),
  entry(
    'pagerdutyGetUserAuditRecords',
    'Audit history of changes to a user.',
    pagerdutyGetUserAuditRecords,
    'read',
    ['compliance history', 'responder', 'member'],
  ),
  entry(
    'pagerdutyListUsers',
    'List account users with team and role filters.',
    pagerdutyListUsers,
    'read',
    ['responder', 'member'],
  ),
  entry(
    'pagerdutyGetCurrentUser',
    'Get the user owning the API token — useful for resolving the From email for writes.',
    pagerdutyGetCurrentUser,
    'read',
    ['responder', 'member'],
  ),
  entry(
    'pagerdutyGetUser',
    'Get one user with contact methods, teams, and notification settings.',
    pagerdutyGetUser,
    'read',
    ['responder', 'member'],
  ),
  entry(
    'pagerdutyCreateUser',
    'Invite/create a user with name, email, role, and time zone.',
    pagerdutyCreateUser,
    'write',
    ['responder', 'member', 'new'],
  ),
  entry(
    'pagerdutyUpdateUser',
    'Update a user name, role, time zone, or job title.',
    pagerdutyUpdateUser,
    'write',
    ['responder', 'member', 'edit'],
  ),
  entry(
    'pagerdutyDeleteUser',
    'Delete (offboard) a user. Their incidents must be reassigned first.',
    pagerdutyDeleteUser,
    'delete',
    ['responder', 'member', 'remove'],
  ),
  entry(
    'pagerdutyGetUserLicense',
    'Show the license type and allocations for a user.',
    pagerdutyGetUserLicense,
    'read',
    ['responder', 'member', 'seat'],
  ),
  entry(
    'pagerdutyListUserContactMethods',
    'List a user contact methods (email, phone, SMS, push).',
    pagerdutyListUserContactMethods,
    'read',
    ['responder', 'member', 'phone', 'sms', 'email'],
  ),
  entry(
    'pagerdutyGetUserContactMethod',
    'Get one contact method with its addresses and verification state.',
    pagerdutyGetUserContactMethod,
    'read',
    ['responder', 'member', 'phone', 'sms', 'email'],
  ),
  entry(
    'pagerdutyCreateUserContactMethod',
    'Add a contact method (email, phone, SMS, push) to a user.',
    pagerdutyCreateUserContactMethod,
    'write',
    ['responder', 'member', 'phone', 'sms', 'email'],
  ),
  entry(
    'pagerdutyUpdateUserContactMethod',
    'Update a contact method address, label, or notification flags.',
    pagerdutyUpdateUserContactMethod,
    'write',
    ['responder', 'member', 'phone', 'sms', 'email'],
  ),
  entry(
    'pagerdutyDeleteUserContactMethod',
    'Remove a contact method from a user.',
    pagerdutyDeleteUserContactMethod,
    'delete',
    ['responder', 'member', 'phone', 'sms', 'email'],
  ),
  entry(
    'pagerdutyListUserNotificationRules',
    'List how a user is notified per urgency (contact-method sequence).',
    pagerdutyListUserNotificationRules,
    'read',
    ['responder', 'member', 'paging order'],
  ),
  entry(
    'pagerdutyGetUserNotificationRule',
    'Get one user notification rule with its contact method and delay.',
    pagerdutyGetUserNotificationRule,
    'read',
    ['responder', 'member', 'paging order'],
  ),
  entry(
    'pagerdutyCreateUserNotificationRule',
    'Add a step to a user notification rule chain (contact method + delay).',
    pagerdutyCreateUserNotificationRule,
    'write',
    ['responder', 'member', 'paging order', 'new'],
  ),
  entry(
    'pagerdutyUpdateUserNotificationRule',
    'Change a notification rule delay or contact method.',
    pagerdutyUpdateUserNotificationRule,
    'write',
    ['responder', 'member', 'paging order', 'edit'],
  ),
  entry(
    'pagerdutyDeleteUserNotificationRule',
    'Remove a step from a user notification chain.',
    pagerdutyDeleteUserNotificationRule,
    'delete',
    ['responder', 'member', 'paging order', 'remove'],
  ),
  entry(
    'pagerdutyListWebhookSubscriptions',
    'List webhook subscriptions receiving event webhooks.',
    pagerdutyListWebhookSubscriptions,
    'read',
    ['outbound webhook', 'event push'],
  ),
  entry(
    'pagerdutyGetWebhookSubscription',
    'Get one webhook subscription with URL, events, and filter.',
    pagerdutyGetWebhookSubscription,
    'read',
    ['outbound webhook', 'event push'],
  ),
  entry(
    'pagerdutyCreateWebhookSubscription',
    'Subscribe a URL to PagerDuty event webhooks with type and optional filter.',
    pagerdutyCreateWebhookSubscription,
    'write',
    ['outbound webhook', 'event push', 'new'],
  ),
  entry(
    'pagerdutyUpdateWebhookSubscription',
    'Update a webhook subscription URL, events, or filter.',
    pagerdutyUpdateWebhookSubscription,
    'write',
    ['outbound webhook', 'event push', 'edit'],
  ),
  entry(
    'pagerdutyDeleteWebhookSubscription',
    'Delete a webhook subscription to stop event delivery.',
    pagerdutyDeleteWebhookSubscription,
    'delete',
    ['outbound webhook', 'event push', 'remove'],
  ),
  entry(
    'pagerdutyEnableWebhookSubscription',
    'Enable a paused webhook subscription.',
    pagerdutyEnableWebhookSubscription,
    'write',
    ['outbound webhook', 'event push'],
  ),
  entry(
    'pagerdutyPingWebhookSubscription',
    'Send a test ping event to verify a webhook endpoint.',
    pagerdutyPingWebhookSubscription,
    'read',
    ['outbound webhook', 'event push'],
  ),
  entry(
    'pagerdutyListExtensions',
    'List extensions (Slack, Jira, ServiceNow, etc.) attached to objects.',
    pagerdutyListExtensions,
    'read',
    ['slack', 'jira integration'],
  ),
  entry(
    'pagerdutyGetExtension',
    'Get one extension with its configuration.',
    pagerdutyGetExtension,
    'read',
    ['slack', 'jira integration'],
  ),
  entry(
    'pagerdutyCreateExtension',
    'Attach an extension (Slack channel, Jira project, webhook) to a service or object.',
    pagerdutyCreateExtension,
    'write',
    ['slack', 'jira integration', 'new'],
  ),
  entry(
    'pagerdutyUpdateExtension',
    'Update an extension name or configuration.',
    pagerdutyUpdateExtension,
    'write',
    ['slack', 'jira integration', 'edit'],
  ),
  entry('pagerdutyDeleteExtension', 'Delete an extension.', pagerdutyDeleteExtension, 'delete', [
    'slack',
    'jira integration',
    'remove',
  ]),
  entry(
    'pagerdutyEnableExtension',
    'Enable a temporarily disabled extension.',
    pagerdutyEnableExtension,
    'write',
    ['slack', 'jira integration'],
  ),
  entry(
    'pagerdutyListExtensionSchemas',
    'List available extension types (Slack, Jira, webhooks) with their schemas.',
    pagerdutyListExtensionSchemas,
    'read',
    ['slack', 'jira integration'],
  ),
  entry(
    'pagerdutyGetExtensionSchema',
    'Get one extension schema with its config requirements.',
    pagerdutyGetExtensionSchema,
    'read',
    ['slack', 'jira integration'],
  ),
  entry(
    'pagerdutyListAddons',
    'List legacy add-ons (incident action buttons) installed on the account.',
    pagerdutyListAddons,
    'read',
    ['legacy widget', 'add on'],
  ),
  entry(
    'pagerdutyGetAddon',
    'Get one add-on with its source URL template.',
    pagerdutyGetAddon,
    'read',
    ['legacy widget', 'add on'],
  ),
  entry(
    'pagerdutyInstallAddon',
    'Install a third-party add-on on a service or incident.',
    pagerdutyInstallAddon,
    'write',
    ['legacy widget', 'add on'],
  ),
  entry(
    'pagerdutyUpdateAddon',
    'Update an add-on name or source URL.',
    pagerdutyUpdateAddon,
    'write',
    ['legacy widget', 'add on', 'edit'],
  ),
  entry('pagerdutyDeleteAddon', 'Uninstall an add-on.', pagerdutyDeleteAddon, 'delete', [
    'legacy widget',
    'add on',
    'remove',
  ]),
  entry(
    'pagerdutyListAlertGroupingSettings',
    'List intelligent alert grouping configurations per service.',
    pagerdutyListAlertGroupingSettings,
    'read',
    ['dedupe rules', 'noise reduction', 'firing alert'],
  ),
  entry(
    'pagerdutyGetAlertGroupingSetting',
    'Get one alert grouping setting.',
    pagerdutyGetAlertGroupingSetting,
    'read',
    ['dedupe rules', 'noise reduction', 'firing alert'],
  ),
  entry(
    'pagerdutyCreateAlertGroupingSetting',
    'Configure intelligent alert grouping for services.',
    pagerdutyCreateAlertGroupingSetting,
    'write',
    ['dedupe rules', 'noise reduction', 'firing alert', 'new'],
  ),
  entry(
    'pagerdutyUpdateAlertGroupingSetting',
    'Update an alert grouping setting timeout or grouping type.',
    pagerdutyUpdateAlertGroupingSetting,
    'write',
    ['dedupe rules', 'noise reduction', 'firing alert', 'edit'],
  ),
  entry(
    'pagerdutyDeleteAlertGroupingSetting',
    'Delete an alert grouping setting (falls back to default grouping).',
    pagerdutyDeleteAlertGroupingSetting,
    'delete',
    ['dedupe rules', 'noise reduction', 'firing alert', 'remove'],
  ),
];
