// @ts-nocheck
import {
  onenoteListNotebooks,
  onenoteGetNotebook,
  onenoteCreateNotebook,
  onenoteUpdateNotebook,
  onenoteListNotebookSections,
  onenoteListNotebookSectionGroups,
  onenoteCopyNotebook,
  onenoteListSectionGroups,
  onenoteGetSectionGroup,
  onenoteCreateSectionGroup,
  onenoteUpdateSectionGroup,
  onenoteDeleteSectionGroup,
  onenoteListSectionGroupSections,
  onenoteCreateSectionInGroup,
  onenoteGetOperation,
} from './notebooks.js';
import {
  onenoteListSections,
  onenoteGetSection,
  onenoteCreateSection,
  onenoteUpdateSection,
  onenoteDeleteSection,
  onenoteListSectionPages,
  onenoteCopySectionToNotebook,
  onenoteCopySectionToSectionGroup,
  onenoteListPages,
  onenoteGetPage,
  onenoteGetPageContent,
  onenoteGetPagePreview,
  onenoteCreatePage,
  onenoteUpdatePageContent,
  onenoteDeletePage,
  onenoteCopyPageToSection,
  onenoteGetPageParentSection,
  onenoteGetPageParentNotebook,
  onenoteGetResource,
  onenoteGetResourceContent,
} from './content.js';

export {
  onenoteListNotebooks,
  onenoteGetNotebook,
  onenoteCreateNotebook,
  onenoteUpdateNotebook,
  onenoteListNotebookSections,
  onenoteListNotebookSectionGroups,
  onenoteCopyNotebook,
  onenoteListSectionGroups,
  onenoteGetSectionGroup,
  onenoteCreateSectionGroup,
  onenoteUpdateSectionGroup,
  onenoteDeleteSectionGroup,
  onenoteListSectionGroupSections,
  onenoteCreateSectionInGroup,
  onenoteGetOperation,
  onenoteListSections,
  onenoteGetSection,
  onenoteCreateSection,
  onenoteUpdateSection,
  onenoteDeleteSection,
  onenoteListSectionPages,
  onenoteCopySectionToNotebook,
  onenoteCopySectionToSectionGroup,
  onenoteListPages,
  onenoteGetPage,
  onenoteGetPageContent,
  onenoteGetPagePreview,
  onenoteCreatePage,
  onenoteUpdatePageContent,
  onenoteDeletePage,
  onenoteCopyPageToSection,
  onenoteGetPageParentSection,
  onenoteGetPageParentNotebook,
  onenoteGetResource,
  onenoteGetResourceContent,
};

const AUTH = 'onenoteToken' as const;

export const onenoteTools = [
  {
    name: 'onenoteListNotebooks',
    description: 'List OneNote notebooks.',
    tool: onenoteListNotebooks,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['notes', 'books'],
  },
  {
    name: 'onenoteGetNotebook',
    description: 'Get one notebook.',
    tool: onenoteGetNotebook,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['notes', 'fetch'],
  },
  {
    name: 'onenoteCreateNotebook',
    description: 'Create a notebook.',
    tool: onenoteCreateNotebook,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['notes', 'new'],
  },
  {
    name: 'onenoteUpdateNotebook',
    description: 'Rename a notebook.',
    tool: onenoteUpdateNotebook,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['notes', 'rename'],
  },
  {
    name: 'onenoteListNotebookSections',
    description: 'List sections under a notebook.',
    tool: onenoteListNotebookSections,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['tabs', 'divisions'],
  },
  {
    name: 'onenoteListNotebookSectionGroups',
    description: 'List section groups under a notebook.',
    tool: onenoteListNotebookSectionGroups,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['folders', 'groups'],
  },
  {
    name: 'onenoteCopyNotebook',
    description: 'Copy a notebook to a group.',
    tool: onenoteCopyNotebook,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['duplicate', 'clone'],
  },
  {
    name: 'onenoteListSectionGroups',
    description: 'List all section groups.',
    tool: onenoteListSectionGroups,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['folders'],
  },
  {
    name: 'onenoteGetSectionGroup',
    description: 'Get one section group.',
    tool: onenoteGetSectionGroup,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['folder', 'fetch'],
  },
  {
    name: 'onenoteCreateSectionGroup',
    description: 'Create a section group in a notebook.',
    tool: onenoteCreateSectionGroup,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['folder', 'new'],
  },
  {
    name: 'onenoteUpdateSectionGroup',
    description: 'Rename a section group.',
    tool: onenoteUpdateSectionGroup,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['folder', 'rename'],
  },
  {
    name: 'onenoteDeleteSectionGroup',
    description: 'Delete a section group.',
    tool: onenoteDeleteSectionGroup,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['folder', 'remove'],
  },
  {
    name: 'onenoteListSectionGroupSections',
    description: 'List sections in a section group.',
    tool: onenoteListSectionGroupSections,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['tabs', 'browse'],
  },
  {
    name: 'onenoteCreateSectionInGroup',
    description: 'Create a section in a group.',
    tool: onenoteCreateSectionInGroup,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['tab', 'new'],
  },
  {
    name: 'onenoteGetOperation',
    description: 'Get long-running operation status.',
    tool: onenoteGetOperation,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['copy', 'poll', 'status'],
  },
  {
    name: 'onenoteListSections',
    description: 'List all sections.',
    tool: onenoteListSections,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['tabs'],
  },
  {
    name: 'onenoteGetSection',
    description: 'Get one section.',
    tool: onenoteGetSection,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['tab', 'fetch'],
  },
  {
    name: 'onenoteCreateSection',
    description: 'Create a section in a notebook.',
    tool: onenoteCreateSection,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['tab', 'new'],
  },
  {
    name: 'onenoteUpdateSection',
    description: 'Rename a section.',
    tool: onenoteUpdateSection,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['tab', 'rename'],
  },
  {
    name: 'onenoteDeleteSection',
    description: 'Delete a section and its pages.',
    tool: onenoteDeleteSection,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['tab', 'remove'],
  },
  {
    name: 'onenoteListSectionPages',
    description: 'List page metadata in a section.',
    tool: onenoteListSectionPages,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['notes', 'browse'],
  },
  {
    name: 'onenoteCopySectionToNotebook',
    description: 'Copy a section to a notebook.',
    tool: onenoteCopySectionToNotebook,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['duplicate', 'move'],
  },
  {
    name: 'onenoteCopySectionToSectionGroup',
    description: 'Copy a section to a group.',
    tool: onenoteCopySectionToSectionGroup,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['duplicate', 'move'],
  },
  {
    name: 'onenoteListPages',
    description: 'List pages with full-text search.',
    tool: onenoteListPages,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['notes', 'search', 'find'],
  },
  {
    name: 'onenoteGetPage',
    description: 'Get one page metadata.',
    tool: onenoteGetPage,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['note', 'fetch'],
  },
  {
    name: 'onenoteGetPageContent',
    description: 'Get page HTML content.',
    tool: onenoteGetPageContent,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['note', 'html', 'read'],
  },
  {
    name: 'onenoteGetPagePreview',
    description: 'Get text/image preview of a page.',
    tool: onenoteGetPagePreview,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['note', 'skim', 'summary'],
  },
  {
    name: 'onenoteCreatePage',
    description: 'Create a page from HTML in a section.',
    tool: onenoteCreatePage,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['note', 'write', 'new'],
  },
  {
    name: 'onenoteUpdatePageContent',
    description: 'Update page content with change objects.',
    tool: onenoteUpdatePageContent,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['note', 'edit', 'append'],
  },
  {
    name: 'onenoteDeletePage',
    description: 'Delete a page.',
    tool: onenoteDeletePage,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['note', 'remove'],
  },
  {
    name: 'onenoteCopyPageToSection',
    description: 'Copy a page to another section.',
    tool: onenoteCopyPageToSection,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['note', 'duplicate', 'move'],
  },
  {
    name: 'onenoteGetPageParentSection',
    description: 'Get the parent section of a page.',
    tool: onenoteGetPageParentSection,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['hierarchy', 'location'],
  },
  {
    name: 'onenoteGetPageParentNotebook',
    description: 'Get the parent notebook of a page.',
    tool: onenoteGetPageParentNotebook,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['hierarchy', 'location'],
  },
  {
    name: 'onenoteGetResource',
    description: 'Get embedded resource metadata.',
    tool: onenoteGetResource,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['image', 'file', 'fetch'],
  },
  {
    name: 'onenoteGetResourceContent',
    description: 'Download embedded resource as base64.',
    tool: onenoteGetResourceContent,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['image', 'file', 'download'],
  },
];
