// @ts-nocheck
import {
  rabbitmqGetOverview,
  rabbitmqGetClusterName,
  rabbitmqSetClusterName,
  rabbitmqListNodes,
  rabbitmqGetNode,
  rabbitmqGetWhoAmI,
  rabbitmqAlivenessTest,
  rabbitmqHealthAlarms,
  rabbitmqHealthLocalAlarms,
  rabbitmqHealthCertificateExpiration,
  rabbitmqHealthPortListener,
  rabbitmqHealthProtocolListener,
  rabbitmqExportDefinitions,
  rabbitmqExportVhostDefinitions,
  rabbitmqImportDefinitions,
  rabbitmqListFeatureFlags,
  rabbitmqEnableFeatureFlag,
} from './overview.js';
import {
  rabbitmqListVhosts,
  rabbitmqGetVhost,
  rabbitmqCreateVhost,
  rabbitmqDeleteVhost,
  rabbitmqListVhostPermissions,
  rabbitmqListUsers,
  rabbitmqGetUser,
  rabbitmqCreateUser,
  rabbitmqDeleteUser,
  rabbitmqListUserPermissions,
  rabbitmqListPermissions,
  rabbitmqGetPermission,
  rabbitmqSetPermission,
  rabbitmqDeletePermission,
  rabbitmqListTopicPermissions,
  rabbitmqGetTopicPermission,
  rabbitmqSetTopicPermission,
  rabbitmqDeleteTopicPermission,
  rabbitmqListUserLimits,
  rabbitmqGetUserLimit,
  rabbitmqSetUserLimit,
  rabbitmqDeleteUserLimit,
} from './access.js';
import {
  rabbitmqListExchanges,
  rabbitmqListExchangesInVhost,
  rabbitmqGetExchange,
  rabbitmqDeclareExchange,
  rabbitmqDeleteExchange,
  rabbitmqListExchangeBindings,
  rabbitmqPublishMessage,
  rabbitmqListQueues,
  rabbitmqListQueuesInVhost,
  rabbitmqGetQueue,
  rabbitmqDeclareQueue,
  rabbitmqDeleteQueue,
  rabbitmqListQueueBindings,
  rabbitmqGetMessages,
  rabbitmqPurgeQueue,
  rabbitmqPauseQueue,
  rabbitmqResumeQueue,
  rabbitmqListBindings,
  rabbitmqListBindingsInVhost,
  rabbitmqCreateQueueBinding,
  rabbitmqDeleteQueueBinding,
  rabbitmqCreateExchangeBinding,
  rabbitmqDeleteExchangeBinding,
} from './messaging.js';
import {
  rabbitmqListConnections,
  rabbitmqGetConnection,
  rabbitmqListConnectionChannels,
  rabbitmqCloseConnection,
  rabbitmqListChannels,
  rabbitmqGetChannel,
  rabbitmqListConsumers,
  rabbitmqListConsumersInVhost,
  rabbitmqListPolicies,
  rabbitmqListPoliciesInVhost,
  rabbitmqGetPolicy,
  rabbitmqSetPolicy,
  rabbitmqDeletePolicy,
  rabbitmqListOperatorPolicies,
  rabbitmqGetOperatorPolicy,
  rabbitmqSetOperatorPolicy,
  rabbitmqDeleteOperatorPolicy,
  rabbitmqListParameters,
  rabbitmqListComponentParameters,
  rabbitmqGetParameter,
  rabbitmqSetParameter,
  rabbitmqDeleteParameter,
  rabbitmqListGlobalParameters,
  rabbitmqGetGlobalParameter,
  rabbitmqSetGlobalParameter,
  rabbitmqDeleteGlobalParameter,
} from './topology.js';

export {
  rabbitmqGetOverview,
  rabbitmqGetClusterName,
  rabbitmqSetClusterName,
  rabbitmqListNodes,
  rabbitmqGetNode,
  rabbitmqGetWhoAmI,
  rabbitmqAlivenessTest,
  rabbitmqHealthAlarms,
  rabbitmqHealthLocalAlarms,
  rabbitmqHealthCertificateExpiration,
  rabbitmqHealthPortListener,
  rabbitmqHealthProtocolListener,
  rabbitmqExportDefinitions,
  rabbitmqExportVhostDefinitions,
  rabbitmqImportDefinitions,
  rabbitmqListFeatureFlags,
  rabbitmqEnableFeatureFlag,
  rabbitmqListVhosts,
  rabbitmqGetVhost,
  rabbitmqCreateVhost,
  rabbitmqDeleteVhost,
  rabbitmqListVhostPermissions,
  rabbitmqListUsers,
  rabbitmqGetUser,
  rabbitmqCreateUser,
  rabbitmqDeleteUser,
  rabbitmqListUserPermissions,
  rabbitmqListPermissions,
  rabbitmqGetPermission,
  rabbitmqSetPermission,
  rabbitmqDeletePermission,
  rabbitmqListTopicPermissions,
  rabbitmqGetTopicPermission,
  rabbitmqSetTopicPermission,
  rabbitmqDeleteTopicPermission,
  rabbitmqListUserLimits,
  rabbitmqGetUserLimit,
  rabbitmqSetUserLimit,
  rabbitmqDeleteUserLimit,
  rabbitmqListExchanges,
  rabbitmqListExchangesInVhost,
  rabbitmqGetExchange,
  rabbitmqDeclareExchange,
  rabbitmqDeleteExchange,
  rabbitmqListExchangeBindings,
  rabbitmqPublishMessage,
  rabbitmqListQueues,
  rabbitmqListQueuesInVhost,
  rabbitmqGetQueue,
  rabbitmqDeclareQueue,
  rabbitmqDeleteQueue,
  rabbitmqListQueueBindings,
  rabbitmqGetMessages,
  rabbitmqPurgeQueue,
  rabbitmqPauseQueue,
  rabbitmqResumeQueue,
  rabbitmqListBindings,
  rabbitmqListBindingsInVhost,
  rabbitmqCreateQueueBinding,
  rabbitmqDeleteQueueBinding,
  rabbitmqCreateExchangeBinding,
  rabbitmqDeleteExchangeBinding,
  rabbitmqListConnections,
  rabbitmqGetConnection,
  rabbitmqListConnectionChannels,
  rabbitmqCloseConnection,
  rabbitmqListChannels,
  rabbitmqGetChannel,
  rabbitmqListConsumers,
  rabbitmqListConsumersInVhost,
  rabbitmqListPolicies,
  rabbitmqListPoliciesInVhost,
  rabbitmqGetPolicy,
  rabbitmqSetPolicy,
  rabbitmqDeletePolicy,
  rabbitmqListOperatorPolicies,
  rabbitmqGetOperatorPolicy,
  rabbitmqSetOperatorPolicy,
  rabbitmqDeleteOperatorPolicy,
  rabbitmqListParameters,
  rabbitmqListComponentParameters,
  rabbitmqGetParameter,
  rabbitmqSetParameter,
  rabbitmqDeleteParameter,
  rabbitmqListGlobalParameters,
  rabbitmqGetGlobalParameter,
  rabbitmqSetGlobalParameter,
  rabbitmqDeleteGlobalParameter,
};

const AUTH = 'rabbitmqCredentials' as const;

export const rabbitmqTools = [
  {
    name: 'rabbitmqGetOverview',
    description: 'Get broker overview: version, totals, rates.',
    tool: rabbitmqGetOverview,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['health', 'stats', 'dashboard'],
  },
  {
    name: 'rabbitmqGetClusterName',
    description: 'Get the cluster name.',
    tool: rabbitmqGetClusterName,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['cluster', 'fetch'],
  },
  {
    name: 'rabbitmqSetClusterName',
    description: 'Set the cluster name.',
    tool: rabbitmqSetClusterName,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['cluster', 'rename'],
  },
  {
    name: 'rabbitmqListNodes',
    description: 'List cluster nodes with memory and alarms.',
    tool: rabbitmqListNodes,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['servers', 'members'],
  },
  {
    name: 'rabbitmqGetNode',
    description: 'Get one node with detailed stats.',
    tool: rabbitmqGetNode,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['server', 'fetch'],
  },
  {
    name: 'rabbitmqGetWhoAmI',
    description: 'Get the authenticated user; verifies credentials.',
    tool: rabbitmqGetWhoAmI,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['identity', 'auth', 'health'],
  },
  {
    name: 'rabbitmqAlivenessTest',
    description: 'End-to-end aliveness test on a vhost.',
    tool: rabbitmqAlivenessTest,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['health', 'ping', 'smoke'],
  },
  {
    name: 'rabbitmqHealthAlarms',
    description: 'Health check: resource alarms.',
    tool: rabbitmqHealthAlarms,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['memory', 'disk'],
  },
  {
    name: 'rabbitmqHealthLocalAlarms',
    description: 'Health check: local node alarms.',
    tool: rabbitmqHealthLocalAlarms,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['memory', 'node'],
  },
  {
    name: 'rabbitmqHealthCertificateExpiration',
    description: 'Health check: expiring TLS certificates.',
    tool: rabbitmqHealthCertificateExpiration,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['tls', 'ssl', 'renewal'],
  },
  {
    name: 'rabbitmqHealthPortListener',
    description: 'Health check: TCP listener on a port.',
    tool: rabbitmqHealthPortListener,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['tcp', 'amqp'],
  },
  {
    name: 'rabbitmqHealthProtocolListener',
    description: 'Health check: protocol listener active.',
    tool: rabbitmqHealthProtocolListener,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['mqtt', 'stomp', 'amqp'],
  },
  {
    name: 'rabbitmqExportDefinitions',
    description: 'Export broker definitions JSON for backup.',
    tool: rabbitmqExportDefinitions,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['backup', 'migrate'],
  },
  {
    name: 'rabbitmqExportVhostDefinitions',
    description: 'Export definitions scoped to a vhost.',
    tool: rabbitmqExportVhostDefinitions,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['backup', 'vhost'],
  },
  {
    name: 'rabbitmqImportDefinitions',
    description: 'Import broker definitions JSON.',
    tool: rabbitmqImportDefinitions,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['restore', 'migrate'],
  },
  {
    name: 'rabbitmqListFeatureFlags',
    description: 'List feature flags and states.',
    tool: rabbitmqListFeatureFlags,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['upgrade', 'capabilities'],
  },
  {
    name: 'rabbitmqEnableFeatureFlag',
    description: 'Enable a feature flag cluster-wide.',
    tool: rabbitmqEnableFeatureFlag,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['upgrade', 'activate'],
  },
  {
    name: 'rabbitmqListVhosts',
    description: 'List virtual hosts.',
    tool: rabbitmqListVhosts,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['namespaces', 'tenants'],
  },
  {
    name: 'rabbitmqGetVhost',
    description: 'Get one vhost.',
    tool: rabbitmqGetVhost,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['namespace', 'fetch'],
  },
  {
    name: 'rabbitmqCreateVhost',
    description: 'Create a virtual host.',
    tool: rabbitmqCreateVhost,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['namespace', 'tenant'],
  },
  {
    name: 'rabbitmqDeleteVhost',
    description: 'Delete a vhost and everything inside.',
    tool: rabbitmqDeleteVhost,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['namespace', 'remove'],
  },
  {
    name: 'rabbitmqListVhostPermissions',
    description: 'List user permissions on a vhost.',
    tool: rabbitmqListVhostPermissions,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['access', 'audit'],
  },
  {
    name: 'rabbitmqListUsers',
    description: 'List users with tags.',
    tool: rabbitmqListUsers,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['accounts', 'members'],
  },
  {
    name: 'rabbitmqGetUser',
    description: 'Get one user.',
    tool: rabbitmqGetUser,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['account', 'fetch'],
  },
  {
    name: 'rabbitmqCreateUser',
    description: 'Create or update a user with password and tags.',
    tool: rabbitmqCreateUser,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['account', 'provision', 'password'],
  },
  {
    name: 'rabbitmqDeleteUser',
    description: 'Delete a user.',
    tool: rabbitmqDeleteUser,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['account', 'remove'],
  },
  {
    name: 'rabbitmqListUserPermissions',
    description: 'List all vhost permissions of a user.',
    tool: rabbitmqListUserPermissions,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['access', 'grants'],
  },
  {
    name: 'rabbitmqListPermissions',
    description: 'List all permissions.',
    tool: rabbitmqListPermissions,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['access', 'acl'],
  },
  {
    name: 'rabbitmqGetPermission',
    description: 'Get one user permission on a vhost.',
    tool: rabbitmqGetPermission,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['access', 'fetch'],
  },
  {
    name: 'rabbitmqSetPermission',
    description: 'Grant configure/write/read regex permissions.',
    tool: rabbitmqSetPermission,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['access', 'grant'],
  },
  {
    name: 'rabbitmqDeletePermission',
    description: 'Remove a user permission on a vhost.',
    tool: rabbitmqDeletePermission,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['access', 'revoke'],
  },
  {
    name: 'rabbitmqListTopicPermissions',
    description: 'List topic permissions.',
    tool: rabbitmqListTopicPermissions,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['routing', 'acl'],
  },
  {
    name: 'rabbitmqGetTopicPermission',
    description: 'Get one user topic permission.',
    tool: rabbitmqGetTopicPermission,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['routing', 'fetch'],
  },
  {
    name: 'rabbitmqSetTopicPermission',
    description: 'Grant topic (routing-key) permission.',
    tool: rabbitmqSetTopicPermission,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['routing', 'grant'],
  },
  {
    name: 'rabbitmqDeleteTopicPermission',
    description: 'Remove a topic permission.',
    tool: rabbitmqDeleteTopicPermission,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['routing', 'revoke'],
  },
  {
    name: 'rabbitmqListUserLimits',
    description: 'List per-user connection/channel limits.',
    tool: rabbitmqListUserLimits,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['quotas', 'throttle'],
  },
  {
    name: 'rabbitmqGetUserLimit',
    description: 'Get one user limit value.',
    tool: rabbitmqGetUserLimit,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['quota', 'fetch'],
  },
  {
    name: 'rabbitmqSetUserLimit',
    description: 'Set a per-user connection/channel limit.',
    tool: rabbitmqSetUserLimit,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['quota', 'throttle'],
  },
  {
    name: 'rabbitmqDeleteUserLimit',
    description: 'Clear a per-user limit.',
    tool: rabbitmqDeleteUserLimit,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['quota', 'remove'],
  },
  {
    name: 'rabbitmqListExchanges',
    description: 'List exchanges across vhosts.',
    tool: rabbitmqListExchanges,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['routers', 'topology'],
  },
  {
    name: 'rabbitmqListExchangesInVhost',
    description: 'List exchanges in one vhost.',
    tool: rabbitmqListExchangesInVhost,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['routers', 'topology'],
  },
  {
    name: 'rabbitmqGetExchange',
    description: 'Get one exchange.',
    tool: rabbitmqGetExchange,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['router', 'fetch'],
  },
  {
    name: 'rabbitmqDeclareExchange',
    description: 'Declare a direct/topic/fanout/headers exchange.',
    tool: rabbitmqDeclareExchange,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['router', 'create'],
  },
  {
    name: 'rabbitmqDeleteExchange',
    description: 'Delete an exchange.',
    tool: rabbitmqDeleteExchange,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['router', 'remove'],
  },
  {
    name: 'rabbitmqListExchangeBindings',
    description: 'List downstream bindings of an exchange.',
    tool: rabbitmqListExchangeBindings,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['routes', 'topology'],
  },
  {
    name: 'rabbitmqPublishMessage',
    description: 'Publish a message to an exchange over HTTP.',
    tool: rabbitmqPublishMessage,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['send', 'produce', 'event'],
  },
  {
    name: 'rabbitmqListQueues',
    description: 'List queues with depth and consumers.',
    tool: rabbitmqListQueues,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['backlog', 'buffers'],
  },
  {
    name: 'rabbitmqListQueuesInVhost',
    description: 'List queues in one vhost.',
    tool: rabbitmqListQueuesInVhost,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['backlog', 'buffers'],
  },
  {
    name: 'rabbitmqGetQueue',
    description: 'Get one queue with backlog details.',
    tool: rabbitmqGetQueue,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['backlog', 'fetch', 'depth'],
  },
  {
    name: 'rabbitmqDeclareQueue',
    description: 'Declare a queue with durability and arguments.',
    tool: rabbitmqDeclareQueue,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['buffer', 'create'],
  },
  {
    name: 'rabbitmqDeleteQueue',
    description: 'Delete a queue and its messages.',
    tool: rabbitmqDeleteQueue,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['buffer', 'remove', 'purge'],
  },
  {
    name: 'rabbitmqListQueueBindings',
    description: 'List upstream bindings of a queue.',
    tool: rabbitmqListQueueBindings,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['routes', 'sources'],
  },
  {
    name: 'rabbitmqGetMessages',
    description: 'Fetch (peek or consume) messages over HTTP.',
    tool: rabbitmqGetMessages,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['poll', 'consume', 'peek'],
  },
  {
    name: 'rabbitmqPurgeQueue',
    description: 'Drop all messages from a queue.',
    tool: rabbitmqPurgeQueue,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['clear', 'drain'],
  },
  {
    name: 'rabbitmqPauseQueue',
    description: 'Pause delivery on a quorum queue.',
    tool: rabbitmqPauseQueue,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['maintenance', 'halt'],
  },
  {
    name: 'rabbitmqResumeQueue',
    description: 'Resume delivery on a paused queue.',
    tool: rabbitmqResumeQueue,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['maintenance', 'unpause'],
  },
  {
    name: 'rabbitmqListBindings',
    description: 'List all bindings.',
    tool: rabbitmqListBindings,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['routes', 'topology'],
  },
  {
    name: 'rabbitmqListBindingsInVhost',
    description: 'List bindings in one vhost.',
    tool: rabbitmqListBindingsInVhost,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['routes', 'topology'],
  },
  {
    name: 'rabbitmqCreateQueueBinding',
    description: 'Bind a queue to an exchange.',
    tool: rabbitmqCreateQueueBinding,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['route', 'wire'],
  },
  {
    name: 'rabbitmqDeleteQueueBinding',
    description: 'Delete an exchange-to-queue binding.',
    tool: rabbitmqDeleteQueueBinding,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['route', 'unwire'],
  },
  {
    name: 'rabbitmqCreateExchangeBinding',
    description: 'Bind exchanges exchange-to-exchange.',
    tool: rabbitmqCreateExchangeBinding,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['route', 'federate'],
  },
  {
    name: 'rabbitmqDeleteExchangeBinding',
    description: 'Delete an exchange-to-exchange binding.',
    tool: rabbitmqDeleteExchangeBinding,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['route', 'unwire'],
  },
  {
    name: 'rabbitmqListConnections',
    description: 'List client connections.',
    tool: rabbitmqListConnections,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['clients', 'sockets'],
  },
  {
    name: 'rabbitmqGetConnection',
    description: 'Get one connection.',
    tool: rabbitmqGetConnection,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['client', 'fetch'],
  },
  {
    name: 'rabbitmqListConnectionChannels',
    description: 'List channels on a connection.',
    tool: rabbitmqListConnectionChannels,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['client', 'multiplex'],
  },
  {
    name: 'rabbitmqCloseConnection',
    description: 'Force-close a client connection.',
    tool: rabbitmqCloseConnection,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['kill', 'disconnect', 'evict'],
  },
  {
    name: 'rabbitmqListChannels',
    description: 'List channels with unacked counts.',
    tool: rabbitmqListChannels,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['sessions', 'unacked'],
  },
  {
    name: 'rabbitmqGetChannel',
    description: 'Get one channel.',
    tool: rabbitmqGetChannel,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['session', 'fetch'],
  },
  {
    name: 'rabbitmqListConsumers',
    description: 'List consumers with prefetch and ack mode.',
    tool: rabbitmqListConsumers,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['subscribers', 'workers'],
  },
  {
    name: 'rabbitmqListConsumersInVhost',
    description: 'List consumers in one vhost.',
    tool: rabbitmqListConsumersInVhost,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['subscribers', 'workers'],
  },
  {
    name: 'rabbitmqListPolicies',
    description: 'List classic policies.',
    tool: rabbitmqListPolicies,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['ha', 'mirroring', 'ttl'],
  },
  {
    name: 'rabbitmqListPoliciesInVhost',
    description: 'List policies in one vhost.',
    tool: rabbitmqListPoliciesInVhost,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['ha', 'ttl'],
  },
  {
    name: 'rabbitmqGetPolicy',
    description: 'Get one policy.',
    tool: rabbitmqGetPolicy,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['ha', 'fetch'],
  },
  {
    name: 'rabbitmqSetPolicy',
    description: 'Create or update a policy.',
    tool: rabbitmqSetPolicy,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['ha', 'mirroring', 'ttl'],
  },
  {
    name: 'rabbitmqDeletePolicy',
    description: 'Delete a policy.',
    tool: rabbitmqDeletePolicy,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['ha', 'remove'],
  },
  {
    name: 'rabbitmqListOperatorPolicies',
    description: 'List operator policy overrides.',
    tool: rabbitmqListOperatorPolicies,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['override', 'ops'],
  },
  {
    name: 'rabbitmqGetOperatorPolicy',
    description: 'Get one operator policy.',
    tool: rabbitmqGetOperatorPolicy,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['override', 'fetch'],
  },
  {
    name: 'rabbitmqSetOperatorPolicy',
    description: 'Create or update an operator policy.',
    tool: rabbitmqSetOperatorPolicy,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['override', 'ops'],
  },
  {
    name: 'rabbitmqDeleteOperatorPolicy',
    description: 'Delete an operator policy.',
    tool: rabbitmqDeleteOperatorPolicy,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['override', 'remove'],
  },
  {
    name: 'rabbitmqListParameters',
    description: 'List runtime parameters.',
    tool: rabbitmqListParameters,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['shovel', 'federation'],
  },
  {
    name: 'rabbitmqListComponentParameters',
    description: 'List parameters for one component.',
    tool: rabbitmqListComponentParameters,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['shovel', 'federation'],
  },
  {
    name: 'rabbitmqGetParameter',
    description: 'Get one runtime parameter.',
    tool: rabbitmqGetParameter,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['shovel', 'fetch'],
  },
  {
    name: 'rabbitmqSetParameter',
    description: 'Create or update a runtime parameter.',
    tool: rabbitmqSetParameter,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['shovel', 'federation'],
  },
  {
    name: 'rabbitmqDeleteParameter',
    description: 'Delete a runtime parameter.',
    tool: rabbitmqDeleteParameter,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['shovel', 'stop'],
  },
  {
    name: 'rabbitmqListGlobalParameters',
    description: 'List global runtime parameters.',
    tool: rabbitmqListGlobalParameters,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['global', 'settings'],
  },
  {
    name: 'rabbitmqGetGlobalParameter',
    description: 'Get one global parameter.',
    tool: rabbitmqGetGlobalParameter,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['global', 'fetch'],
  },
  {
    name: 'rabbitmqSetGlobalParameter',
    description: 'Create or update a global parameter.',
    tool: rabbitmqSetGlobalParameter,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['global', 'settings'],
  },
  {
    name: 'rabbitmqDeleteGlobalParameter',
    description: 'Delete a global parameter.',
    tool: rabbitmqDeleteGlobalParameter,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['global', 'remove'],
  },
];
