// @ts-nocheck
import { growwGetUserProfile } from './user.js';
import {
  growwPlaceOrder,
  growwModifyOrder,
  growwCancelOrder,
  growwGetTradesForOrder,
  growwGetOrderStatus,
  growwGetOrderStatusByReferenceId,
  growwListOrders,
  growwGetOrderDetail,
} from './orders.js';
import {
  growwCreateGttOrder,
  growwCreateOcoOrder,
  growwModifySmartOrder,
  growwCancelSmartOrder,
  growwGetSmartOrder,
  growwListSmartOrders,
} from './smart-orders.js';
import { growwGetHoldings, growwGetPositions, growwGetPositionForSymbol } from './portfolio.js';
import { growwGetUserMargin, growwGetRequiredMargin } from './margin.js';
import { growwGetQuote, growwGetLtp, growwGetOhlc, growwGetOptionChain, growwGetGreeks } from './live-data.js';
import {
  growwGetHistoricalCandles,
  growwGetHistoricalCandleRange,
  growwGetExpiries,
  growwGetContracts,
} from './historical.js';
import { growwSearchInstruments } from './instruments.js';

export {
  growwGetUserProfile,
  growwPlaceOrder,
  growwModifyOrder,
  growwCancelOrder,
  growwGetTradesForOrder,
  growwGetOrderStatus,
  growwGetOrderStatusByReferenceId,
  growwListOrders,
  growwGetOrderDetail,
  growwCreateGttOrder,
  growwCreateOcoOrder,
  growwModifySmartOrder,
  growwCancelSmartOrder,
  growwGetSmartOrder,
  growwListSmartOrders,
  growwGetHoldings,
  growwGetPositions,
  growwGetPositionForSymbol,
  growwGetUserMargin,
  growwGetRequiredMargin,
  growwGetQuote,
  growwGetLtp,
  growwGetOhlc,
  growwGetOptionChain,
  growwGetGreeks,
  growwGetHistoricalCandles,
  growwGetHistoricalCandleRange,
  growwGetExpiries,
  growwGetContracts,
  growwSearchInstruments,
};

export const growwTools = [
  {
    name: 'growwGetUserProfile',
    description: 'Get Groww user profile including UCC, enabled exchanges, DDPI status and active segments.',
    tool: growwGetUserProfile,
    requiredAuth: 'growwAccessToken' as const,
    scope: 'read' as const,
  },
  {
    name: 'growwPlaceOrder',
    description: 'Place a new equity or F&O order on Groww.',
    tool: growwPlaceOrder,
    requiredAuth: 'growwAccessToken' as const,
    scope: 'write' as const,
  },
  {
    name: 'growwModifyOrder',
    description: 'Modify a pending/open Groww order (quantity, price, trigger price, order type).',
    tool: growwModifyOrder,
    requiredAuth: 'growwAccessToken' as const,
    scope: 'write' as const,
  },
  {
    name: 'growwCancelOrder',
    description: 'Cancel a pending/open Groww order.',
    tool: growwCancelOrder,
    requiredAuth: 'growwAccessToken' as const,
    scope: 'delete' as const,
  },
  {
    name: 'growwGetTradesForOrder',
    description: 'Get all trades (fills) assigned to a Groww order ID.',
    tool: growwGetTradesForOrder,
    requiredAuth: 'growwAccessToken' as const,
    scope: 'read' as const,
  },
  {
    name: 'growwGetOrderStatus',
    description: 'Check status of a Groww order using its groww_order_id.',
    tool: growwGetOrderStatus,
    requiredAuth: 'growwAccessToken' as const,
    scope: 'read' as const,
  },
  {
    name: 'growwGetOrderStatusByReferenceId',
    description: 'Check status of a Groww order using your own order_reference_id.',
    tool: growwGetOrderStatusByReferenceId,
    requiredAuth: 'growwAccessToken' as const,
    scope: 'read' as const,
  },
  {
    name: 'growwListOrders',
    description: 'List today\u2019s Groww orders (open, pending and executed) with pagination.',
    tool: growwListOrders,
    requiredAuth: 'growwAccessToken' as const,
    scope: 'read' as const,
  },
  {
    name: 'growwGetOrderDetail',
    description: 'Get full details of a Groww order using its groww_order_id.',
    tool: growwGetOrderDetail,
    requiredAuth: 'growwAccessToken' as const,
    scope: 'read' as const,
  },
  {
    name: 'growwCreateGttOrder',
    description: 'Create a GTT (Good Till Triggered) smart order.',
    tool: growwCreateGttOrder,
    requiredAuth: 'growwAccessToken' as const,
    scope: 'write' as const,
  },
  {
    name: 'growwCreateOcoOrder',
    description: 'Create an OCO (One Cancels Other) smart order with target and stop-loss legs.',
    tool: growwCreateOcoOrder,
    requiredAuth: 'growwAccessToken' as const,
    scope: 'write' as const,
  },
  {
    name: 'growwModifySmartOrder',
    description: 'Modify an active GTT or OCO smart order.',
    tool: growwModifySmartOrder,
    requiredAuth: 'growwAccessToken' as const,
    scope: 'write' as const,
  },
  {
    name: 'growwCancelSmartOrder',
    description: 'Cancel an active GTT or OCO smart order.',
    tool: growwCancelSmartOrder,
    requiredAuth: 'growwAccessToken' as const,
    scope: 'delete' as const,
  },
  {
    name: 'growwGetSmartOrder',
    description: 'Get full details of a GTT or OCO smart order.',
    tool: growwGetSmartOrder,
    requiredAuth: 'growwAccessToken' as const,
    scope: 'read' as const,
  },
  {
    name: 'growwListSmartOrders',
    description: 'List smart orders filtered by segment, type, status and time window.',
    tool: growwListSmartOrders,
    requiredAuth: 'growwAccessToken' as const,
    scope: 'read' as const,
  },
  {
    name: 'growwGetHoldings',
    description: 'Get current DEMAT stock holdings.',
    tool: growwGetHoldings,
    requiredAuth: 'growwAccessToken' as const,
    scope: 'read' as const,
  },
  {
    name: 'growwGetPositions',
    description: 'Get all user positions with P&L.',
    tool: growwGetPositions,
    requiredAuth: 'growwAccessToken' as const,
    scope: 'read' as const,
  },
  {
    name: 'growwGetPositionForSymbol',
    description: 'Get user position for a particular trading symbol.',
    tool: growwGetPositionForSymbol,
    requiredAuth: 'growwAccessToken' as const,
    scope: 'read' as const,
  },
  {
    name: 'growwGetUserMargin',
    description: 'Get available user margin details.',
    tool: growwGetUserMargin,
    requiredAuth: 'growwAccessToken' as const,
    scope: 'read' as const,
  },
  {
    name: 'growwGetRequiredMargin',
    description: 'Calculate required margin for a single order or a basket of orders.',
    tool: growwGetRequiredMargin,
    requiredAuth: 'growwAccessToken' as const,
    scope: 'read' as const,
  },
  {
    name: 'growwGetQuote',
    description: 'Get full live snapshot for an instrument with depth, OHLC, volumes and OI.',
    tool: growwGetQuote,
    requiredAuth: 'growwAccessToken' as const,
    scope: 'read' as const,
  },
  {
    name: 'growwGetLtp',
    description: 'Get last traded price for up to 50 instruments.',
    tool: growwGetLtp,
    requiredAuth: 'growwAccessToken' as const,
    scope: 'read' as const,
  },
  {
    name: 'growwGetOhlc',
    description: 'Get real-time OHLC snapshot for up to 50 instruments.',
    tool: growwGetOhlc,
    requiredAuth: 'growwAccessToken' as const,
    scope: 'read' as const,
  },
  {
    name: 'growwGetOptionChain',
    description: 'Get full FNO option chain with Greeks, LTP, OI and volume.',
    tool: growwGetOptionChain,
    requiredAuth: 'growwAccessToken' as const,
    scope: 'read' as const,
  },
  {
    name: 'growwGetGreeks',
    description: 'Get Greeks for a single FNO contract.',
    tool: growwGetGreeks,
    requiredAuth: 'growwAccessToken' as const,
    scope: 'read' as const,
  },
  {
    name: 'growwGetHistoricalCandles',
    description: 'Get historical OHLCV candles (+OI for FNO) for backtesting using a Groww symbol.',
    tool: growwGetHistoricalCandles,
    requiredAuth: 'growwAccessToken' as const,
    scope: 'read' as const,
  },
  {
    name: 'growwGetHistoricalCandleRange',
    description: 'DEPRECATED by Groww. Get historical candles by trading symbol.',
    tool: growwGetHistoricalCandleRange,
    requiredAuth: 'growwAccessToken' as const,
    scope: 'read' as const,
  },
  {
    name: 'growwGetExpiries',
    description: 'List available FNO expiry dates for an underlying.',
    tool: growwGetExpiries,
    requiredAuth: 'growwAccessToken' as const,
    scope: 'read' as const,
  },
  {
    name: 'growwGetContracts',
    description: 'List Groww symbols of FNO contracts for an underlying and expiry.',
    tool: growwGetContracts,
    requiredAuth: 'growwAccessToken' as const,
    scope: 'read' as const,
  },
  {
    name: 'growwSearchInstruments',
    description: 'Search the Groww instruments master (no auth needed) to resolve trading and Groww symbols.',
    tool: growwSearchInstruments,
    scope: 'read' as const,
  },
];
