// @ts-nocheck
import { datadogAggregateLogs, datadogSearchLogs, datadogListLogIndexes } from './logs.js';
import { datadogListMetrics, datadogQueryMetrics, datadogSubmitMetrics } from './metrics.js';
import {
    datadogCreateMonitor,
    datadogGetMonitor,
    datadogListMonitors,
    datadogUpdateMonitor,
    datadogDeleteMonitor,
    datadogMuteMonitor,
    datadogUnmuteMonitor,
    datadogCreateDowntime,
} from './monitors.js';
import {
    datadogCreateDashboard,
    datadogGetDashboard,
    datadogUpdateDashboard,
    datadogDeleteDashboard,
    datadogListDashboards,
} from './dashboards.js';
import { datadogCreateEvent, datadogListEvents } from './events.js';
import {
    datadogListHosts,
    datadogGetHostTags,
    datadogListAllTags,
    datadogUpdateHostTags,
} from './hosts.js';
import {
    datadogListApmServices,
    datadogSearchTraces,
    datadogSearchSpansAnalytics,
} from './apm.js';
import {
    datadogCreateSyntheticApiTest,
    datadogListSynthetics,
    datadogGetSyntheticsLocations,
} from './synthetics.js';
import { datadogListIncidents } from './incidents.js';
import { datadogCreateSlo, datadogListSlos } from './slos.js';
import { datadogListUsers, datadogListRoles } from './users.js';
import { datadogGetUsageSummary } from './usage.js';
import { datadogListApiKeys } from './api-keys.js';
import { datadogListAwsIntegrations, datadogCreateWebhook } from './integrations.js';
import {
    datadogCreateEscalationPolicy,
    datadogGetEscalationPolicy,
    datadogUpdateEscalationPolicy,
    datadogDeleteEscalationPolicy,
} from './oncall-policies.js';
import {
    datadogCreateSchedule,
    datadogGetSchedule,
    datadogUpdateSchedule,
    datadogDeleteSchedule,
    datadogGetScheduledOnCallUser,
} from './oncall-schedules.js';
import {
    datadogCreateNotificationChannel,
    datadogGetNotificationChannel,
    datadogListNotificationChannels,
    datadogDeleteNotificationChannel,
    datadogCreateNotificationRule,
    datadogGetNotificationRule,
    datadogListNotificationRules,
    datadogUpdateNotificationRule,
    datadogDeleteNotificationRule,
} from './oncall-notifications.js';
import {
    datadogGetTeamOnCallUsers,
    datadogGetTeamRoutingRules,
    datadogSetTeamRoutingRules,
} from './oncall-teams.js';

export {
    datadogAggregateLogs,
    datadogSearchLogs,
    datadogListLogIndexes,
    datadogListMetrics,
    datadogQueryMetrics,
    datadogSubmitMetrics,
    datadogCreateMonitor,
    datadogGetMonitor,
    datadogListMonitors,
    datadogUpdateMonitor,
    datadogDeleteMonitor,
    datadogMuteMonitor,
    datadogUnmuteMonitor,
    datadogCreateDowntime,
    datadogCreateDashboard,
    datadogGetDashboard,
    datadogUpdateDashboard,
    datadogDeleteDashboard,
    datadogListDashboards,
    datadogCreateEvent,
    datadogListEvents,
    datadogListHosts,
    datadogGetHostTags,
    datadogListAllTags,
    datadogUpdateHostTags,
    datadogListApmServices,
    datadogSearchTraces,
    datadogSearchSpansAnalytics,
    datadogCreateSyntheticApiTest,
    datadogListSynthetics,
    datadogGetSyntheticsLocations,
    datadogListIncidents,
    datadogCreateSlo,
    datadogListSlos,
    datadogListUsers,
    datadogListRoles,
    datadogGetUsageSummary,
    datadogListApiKeys,
    datadogListAwsIntegrations,
    datadogCreateWebhook,
    datadogCreateEscalationPolicy,
    datadogGetEscalationPolicy,
    datadogUpdateEscalationPolicy,
    datadogDeleteEscalationPolicy,
    datadogCreateSchedule,
    datadogGetSchedule,
    datadogUpdateSchedule,
    datadogDeleteSchedule,
    datadogGetScheduledOnCallUser,
    datadogCreateNotificationChannel,
    datadogGetNotificationChannel,
    datadogListNotificationChannels,
    datadogDeleteNotificationChannel,
    datadogCreateNotificationRule,
    datadogGetNotificationRule,
    datadogListNotificationRules,
    datadogUpdateNotificationRule,
    datadogDeleteNotificationRule,
    datadogGetTeamOnCallUsers,
    datadogGetTeamRoutingRules,
    datadogSetTeamRoutingRules,
};

export const datadogTools = [
    {
        name: 'datadogAggregateLogs',
        description: datadogAggregateLogs.description!,
        tool: datadogAggregateLogs,
        requiredAuth: 'datadogCredentials' as const,
        scope: 'read' as const,
    },
    {
        name: 'datadogSearchLogs',
        description: datadogSearchLogs.description!,
        tool: datadogSearchLogs,
        requiredAuth: 'datadogCredentials' as const,
        scope: 'read' as const,
    },
    {
        name: 'datadogListLogIndexes',
        description: datadogListLogIndexes.description!,
        tool: datadogListLogIndexes,
        requiredAuth: 'datadogCredentials' as const,
        scope: 'read' as const,
    },
    {
        name: 'datadogListMetrics',
        description: datadogListMetrics.description!,
        tool: datadogListMetrics,
        requiredAuth: 'datadogCredentials' as const,
        scope: 'read' as const,
    },
    {
        name: 'datadogQueryMetrics',
        description: datadogQueryMetrics.description!,
        tool: datadogQueryMetrics,
        requiredAuth: 'datadogCredentials' as const,
        scope: 'read' as const,
    },
    {
        name: 'datadogSubmitMetrics',
        description: datadogSubmitMetrics.description!,
        tool: datadogSubmitMetrics,
        requiredAuth: 'datadogCredentials' as const,
        scope: 'write' as const,
    },
    {
        name: 'datadogCreateMonitor',
        description: datadogCreateMonitor.description!,
        tool: datadogCreateMonitor,
        requiredAuth: 'datadogCredentials' as const,
        scope: 'write' as const,
    },
    {
        name: 'datadogGetMonitor',
        description: datadogGetMonitor.description!,
        tool: datadogGetMonitor,
        requiredAuth: 'datadogCredentials' as const,
        scope: 'read' as const,
    },
    {
        name: 'datadogListMonitors',
        description: datadogListMonitors.description!,
        tool: datadogListMonitors,
        requiredAuth: 'datadogCredentials' as const,
        scope: 'read' as const,
    },
    {
        name: 'datadogUpdateMonitor',
        description: datadogUpdateMonitor.description!,
        tool: datadogUpdateMonitor,
        requiredAuth: 'datadogCredentials' as const,
        scope: 'write' as const,
    },
    {
        name: 'datadogDeleteMonitor',
        description: datadogDeleteMonitor.description!,
        tool: datadogDeleteMonitor,
        requiredAuth: 'datadogCredentials' as const,
        scope: 'delete' as const,
    },
    {
        name: 'datadogMuteMonitor',
        description: datadogMuteMonitor.description!,
        tool: datadogMuteMonitor,
        requiredAuth: 'datadogCredentials' as const,
        scope: 'write' as const,
    },
    {
        name: 'datadogUnmuteMonitor',
        description: datadogUnmuteMonitor.description!,
        tool: datadogUnmuteMonitor,
        requiredAuth: 'datadogCredentials' as const,
        scope: 'write' as const,
    },
    {
        name: 'datadogCreateDowntime',
        description: datadogCreateDowntime.description!,
        tool: datadogCreateDowntime,
        requiredAuth: 'datadogCredentials' as const,
        scope: 'write' as const,
    },
    {
        name: 'datadogCreateDashboard',
        description: datadogCreateDashboard.description!,
        tool: datadogCreateDashboard,
        requiredAuth: 'datadogCredentials' as const,
        scope: 'write' as const,
    },
    {
        name: 'datadogGetDashboard',
        description: datadogGetDashboard.description!,
        tool: datadogGetDashboard,
        requiredAuth: 'datadogCredentials' as const,
        scope: 'read' as const,
    },
    {
        name: 'datadogUpdateDashboard',
        description: datadogUpdateDashboard.description!,
        tool: datadogUpdateDashboard,
        requiredAuth: 'datadogCredentials' as const,
        scope: 'write' as const,
    },
    {
        name: 'datadogDeleteDashboard',
        description: datadogDeleteDashboard.description!,
        tool: datadogDeleteDashboard,
        requiredAuth: 'datadogCredentials' as const,
        scope: 'delete' as const,
    },
    {
        name: 'datadogListDashboards',
        description: datadogListDashboards.description!,
        tool: datadogListDashboards,
        requiredAuth: 'datadogCredentials' as const,
        scope: 'read' as const,
    },
    {
        name: 'datadogCreateEvent',
        description: datadogCreateEvent.description!,
        tool: datadogCreateEvent,
        requiredAuth: 'datadogCredentials' as const,
        scope: 'write' as const,
    },
    {
        name: 'datadogListEvents',
        description: datadogListEvents.description!,
        tool: datadogListEvents,
        requiredAuth: 'datadogCredentials' as const,
        scope: 'read' as const,
    },
    {
        name: 'datadogListHosts',
        description: datadogListHosts.description!,
        tool: datadogListHosts,
        requiredAuth: 'datadogCredentials' as const,
        scope: 'read' as const,
    },
    {
        name: 'datadogGetHostTags',
        description: datadogGetHostTags.description!,
        tool: datadogGetHostTags,
        requiredAuth: 'datadogCredentials' as const,
        scope: 'read' as const,
    },
    {
        name: 'datadogListAllTags',
        description: datadogListAllTags.description!,
        tool: datadogListAllTags,
        requiredAuth: 'datadogCredentials' as const,
        scope: 'read' as const,
    },
    {
        name: 'datadogUpdateHostTags',
        description: datadogUpdateHostTags.description!,
        tool: datadogUpdateHostTags,
        requiredAuth: 'datadogCredentials' as const,
        scope: 'write' as const,
    },
    {
        name: 'datadogListApmServices',
        description: datadogListApmServices.description!,
        tool: datadogListApmServices,
        requiredAuth: 'datadogCredentials' as const,
        scope: 'read' as const,
    },
    {
        name: 'datadogSearchTraces',
        description: datadogSearchTraces.description!,
        tool: datadogSearchTraces,
        requiredAuth: 'datadogCredentials' as const,
        scope: 'read' as const,
    },
    {
        name: 'datadogSearchSpansAnalytics',
        description: datadogSearchSpansAnalytics.description!,
        tool: datadogSearchSpansAnalytics,
        requiredAuth: 'datadogCredentials' as const,
        scope: 'read' as const,
    },
    {
        name: 'datadogCreateSyntheticApiTest',
        description: datadogCreateSyntheticApiTest.description!,
        tool: datadogCreateSyntheticApiTest,
        requiredAuth: 'datadogCredentials' as const,
        scope: 'write' as const,
    },
    {
        name: 'datadogListSynthetics',
        description: datadogListSynthetics.description!,
        tool: datadogListSynthetics,
        requiredAuth: 'datadogCredentials' as const,
        scope: 'read' as const,
    },
    {
        name: 'datadogGetSyntheticsLocations',
        description: datadogGetSyntheticsLocations.description!,
        tool: datadogGetSyntheticsLocations,
        requiredAuth: 'datadogCredentials' as const,
        scope: 'read' as const,
    },
    {
        name: 'datadogListIncidents',
        description: datadogListIncidents.description!,
        tool: datadogListIncidents,
        requiredAuth: 'datadogCredentials' as const,
        scope: 'read' as const,
    },
    {
        name: 'datadogCreateSlo',
        description: datadogCreateSlo.description!,
        tool: datadogCreateSlo,
        requiredAuth: 'datadogCredentials' as const,
        scope: 'write' as const,
    },
    {
        name: 'datadogListSlos',
        description: datadogListSlos.description!,
        tool: datadogListSlos,
        requiredAuth: 'datadogCredentials' as const,
        scope: 'read' as const,
    },
    {
        name: 'datadogListUsers',
        description: datadogListUsers.description!,
        tool: datadogListUsers,
        requiredAuth: 'datadogCredentials' as const,
        scope: 'read' as const,
    },
    {
        name: 'datadogListRoles',
        description: datadogListRoles.description!,
        tool: datadogListRoles,
        requiredAuth: 'datadogCredentials' as const,
        scope: 'read' as const,
    },
    {
        name: 'datadogGetUsageSummary',
        description: datadogGetUsageSummary.description!,
        tool: datadogGetUsageSummary,
        requiredAuth: 'datadogCredentials' as const,
        scope: 'read' as const,
    },
    {
        name: 'datadogListApiKeys',
        description: datadogListApiKeys.description!,
        tool: datadogListApiKeys,
        requiredAuth: 'datadogCredentials' as const,
        scope: 'read' as const,
    },
    {
        name: 'datadogListAwsIntegrations',
        description: datadogListAwsIntegrations.description!,
        tool: datadogListAwsIntegrations,
        requiredAuth: 'datadogCredentials' as const,
        scope: 'read' as const,
    },
    {
        name: 'datadogCreateWebhook',
        description: datadogCreateWebhook.description!,
        tool: datadogCreateWebhook,
        requiredAuth: 'datadogCredentials' as const,
        scope: 'write' as const,
    },
    {
        name: 'datadogCreateEscalationPolicy',
        description: datadogCreateEscalationPolicy.description!,
        tool: datadogCreateEscalationPolicy,
        requiredAuth: 'datadogCredentials' as const,
        scope: 'write' as const,
    },
    {
        name: 'datadogGetEscalationPolicy',
        description: datadogGetEscalationPolicy.description!,
        tool: datadogGetEscalationPolicy,
        requiredAuth: 'datadogCredentials' as const,
        scope: 'read' as const,
    },
    {
        name: 'datadogUpdateEscalationPolicy',
        description: datadogUpdateEscalationPolicy.description!,
        tool: datadogUpdateEscalationPolicy,
        requiredAuth: 'datadogCredentials' as const,
        scope: 'write' as const,
    },
    {
        name: 'datadogDeleteEscalationPolicy',
        description: datadogDeleteEscalationPolicy.description!,
        tool: datadogDeleteEscalationPolicy,
        requiredAuth: 'datadogCredentials' as const,
        scope: 'delete' as const,
    },
    {
        name: 'datadogCreateSchedule',
        description: datadogCreateSchedule.description!,
        tool: datadogCreateSchedule,
        requiredAuth: 'datadogCredentials' as const,
        scope: 'write' as const,
    },
    {
        name: 'datadogGetSchedule',
        description: datadogGetSchedule.description!,
        tool: datadogGetSchedule,
        requiredAuth: 'datadogCredentials' as const,
        scope: 'read' as const,
    },
    {
        name: 'datadogUpdateSchedule',
        description: datadogUpdateSchedule.description!,
        tool: datadogUpdateSchedule,
        requiredAuth: 'datadogCredentials' as const,
        scope: 'write' as const,
    },
    {
        name: 'datadogDeleteSchedule',
        description: datadogDeleteSchedule.description!,
        tool: datadogDeleteSchedule,
        requiredAuth: 'datadogCredentials' as const,
        scope: 'delete' as const,
    },
    {
        name: 'datadogGetScheduledOnCallUser',
        description: datadogGetScheduledOnCallUser.description!,
        tool: datadogGetScheduledOnCallUser,
        requiredAuth: 'datadogCredentials' as const,
        scope: 'read' as const,
    },
    {
        name: 'datadogCreateNotificationChannel',
        description: datadogCreateNotificationChannel.description!,
        tool: datadogCreateNotificationChannel,
        requiredAuth: 'datadogCredentials' as const,
        scope: 'write' as const,
    },
    {
        name: 'datadogGetNotificationChannel',
        description: datadogGetNotificationChannel.description!,
        tool: datadogGetNotificationChannel,
        requiredAuth: 'datadogCredentials' as const,
        scope: 'read' as const,
    },
    {
        name: 'datadogListNotificationChannels',
        description: datadogListNotificationChannels.description!,
        tool: datadogListNotificationChannels,
        requiredAuth: 'datadogCredentials' as const,
        scope: 'read' as const,
    },
    {
        name: 'datadogDeleteNotificationChannel',
        description: datadogDeleteNotificationChannel.description!,
        tool: datadogDeleteNotificationChannel,
        requiredAuth: 'datadogCredentials' as const,
        scope: 'delete' as const,
    },
    {
        name: 'datadogCreateNotificationRule',
        description: datadogCreateNotificationRule.description!,
        tool: datadogCreateNotificationRule,
        requiredAuth: 'datadogCredentials' as const,
        scope: 'write' as const,
    },
    {
        name: 'datadogGetNotificationRule',
        description: datadogGetNotificationRule.description!,
        tool: datadogGetNotificationRule,
        requiredAuth: 'datadogCredentials' as const,
        scope: 'read' as const,
    },
    {
        name: 'datadogListNotificationRules',
        description: datadogListNotificationRules.description!,
        tool: datadogListNotificationRules,
        requiredAuth: 'datadogCredentials' as const,
        scope: 'read' as const,
    },
    {
        name: 'datadogUpdateNotificationRule',
        description: datadogUpdateNotificationRule.description!,
        tool: datadogUpdateNotificationRule,
        requiredAuth: 'datadogCredentials' as const,
        scope: 'write' as const,
    },
    {
        name: 'datadogDeleteNotificationRule',
        description: datadogDeleteNotificationRule.description!,
        tool: datadogDeleteNotificationRule,
        requiredAuth: 'datadogCredentials' as const,
        scope: 'delete' as const,
    },
    {
        name: 'datadogGetTeamOnCallUsers',
        description: datadogGetTeamOnCallUsers.description!,
        tool: datadogGetTeamOnCallUsers,
        requiredAuth: 'datadogCredentials' as const,
        scope: 'read' as const,
    },
    {
        name: 'datadogGetTeamRoutingRules',
        description: datadogGetTeamRoutingRules.description!,
        tool: datadogGetTeamRoutingRules,
        requiredAuth: 'datadogCredentials' as const,
        scope: 'read' as const,
    },
    {
        name: 'datadogSetTeamRoutingRules',
        description: datadogSetTeamRoutingRules.description!,
        tool: datadogSetTeamRoutingRules,
        requiredAuth: 'datadogCredentials' as const,
        scope: 'write' as const,
    },
];
