// @ts-nocheck
import { datadogAggregateLogs, datadogSearchLogs, datadogListLogIndexes } from './logs.js';
import { datadogListMetrics, datadogQueryMetrics, datadogSubmitMetrics } from './metrics.js';
import {
  datadogCreateMonitor,
  datadogGetMonitor,
  datadogListMonitors,
  datadogUpdateMonitor,
  datadogDeleteMonitor,
  datadogMuteMonitor,
  datadogUnmuteMonitor,
  datadogCreateDowntime,
} from './monitors.js';
import {
  datadogCreateDashboard,
  datadogGetDashboard,
  datadogUpdateDashboard,
  datadogDeleteDashboard,
  datadogListDashboards,
} from './dashboards.js';
import { datadogCreateEvent, datadogListEvents } from './events.js';
import {
  datadogListHosts,
  datadogGetHostTags,
  datadogListAllTags,
  datadogUpdateHostTags,
} from './hosts.js';
import { datadogListApmServices, datadogSearchTraces, datadogSearchSpansAnalytics } from './apm.js';
import {
  datadogCreateSyntheticApiTest,
  datadogListSynthetics,
  datadogGetSyntheticsLocations,
} from './synthetics.js';
import { datadogListIncidents } from './incidents.js';
import { datadogCreateSlo, datadogListSlos } from './slos.js';
import { datadogListUsers, datadogListRoles } from './users.js';
import { datadogGetUsageSummary } from './usage.js';
import { datadogListApiKeys } from './api-keys.js';
import { datadogListAwsIntegrations, datadogCreateWebhook } from './integrations.js';
import {
  datadogCreateEscalationPolicy,
  datadogGetEscalationPolicy,
  datadogUpdateEscalationPolicy,
  datadogDeleteEscalationPolicy,
} from './oncall-policies.js';
import {
  datadogCreateSchedule,
  datadogGetSchedule,
  datadogUpdateSchedule,
  datadogDeleteSchedule,
  datadogGetScheduledOnCallUser,
} from './oncall-schedules.js';
import {
  datadogCreateNotificationChannel,
  datadogGetNotificationChannel,
  datadogListNotificationChannels,
  datadogDeleteNotificationChannel,
  datadogCreateNotificationRule,
  datadogGetNotificationRule,
  datadogListNotificationRules,
  datadogUpdateNotificationRule,
  datadogDeleteNotificationRule,
} from './oncall-notifications.js';
import {
  datadogGetTeamOnCallUsers,
  datadogGetTeamRoutingRules,
  datadogSetTeamRoutingRules,
} from './oncall-teams.js';

export {
  datadogAggregateLogs,
  datadogSearchLogs,
  datadogListLogIndexes,
  datadogListMetrics,
  datadogQueryMetrics,
  datadogSubmitMetrics,
  datadogCreateMonitor,
  datadogGetMonitor,
  datadogListMonitors,
  datadogUpdateMonitor,
  datadogDeleteMonitor,
  datadogMuteMonitor,
  datadogUnmuteMonitor,
  datadogCreateDowntime,
  datadogCreateDashboard,
  datadogGetDashboard,
  datadogUpdateDashboard,
  datadogDeleteDashboard,
  datadogListDashboards,
  datadogCreateEvent,
  datadogListEvents,
  datadogListHosts,
  datadogGetHostTags,
  datadogListAllTags,
  datadogUpdateHostTags,
  datadogListApmServices,
  datadogSearchTraces,
  datadogSearchSpansAnalytics,
  datadogCreateSyntheticApiTest,
  datadogListSynthetics,
  datadogGetSyntheticsLocations,
  datadogListIncidents,
  datadogCreateSlo,
  datadogListSlos,
  datadogListUsers,
  datadogListRoles,
  datadogGetUsageSummary,
  datadogListApiKeys,
  datadogListAwsIntegrations,
  datadogCreateWebhook,
  datadogCreateEscalationPolicy,
  datadogGetEscalationPolicy,
  datadogUpdateEscalationPolicy,
  datadogDeleteEscalationPolicy,
  datadogCreateSchedule,
  datadogGetSchedule,
  datadogUpdateSchedule,
  datadogDeleteSchedule,
  datadogGetScheduledOnCallUser,
  datadogCreateNotificationChannel,
  datadogGetNotificationChannel,
  datadogListNotificationChannels,
  datadogDeleteNotificationChannel,
  datadogCreateNotificationRule,
  datadogGetNotificationRule,
  datadogListNotificationRules,
  datadogUpdateNotificationRule,
  datadogDeleteNotificationRule,
  datadogGetTeamOnCallUsers,
  datadogGetTeamRoutingRules,
  datadogSetTeamRoutingRules,
};

export const datadogTools = [
  {
    name: 'datadogAggregateLogs',
    description: datadogAggregateLogs.description!,
    tool: datadogAggregateLogs,
    requiredAuth: 'datadogCredentials' as const,
    scope: 'read' as const,
    keywords: ['log', 'analytics'],
  },
  {
    name: 'datadogSearchLogs',
    description: datadogSearchLogs.description!,
    tool: datadogSearchLogs,
    requiredAuth: 'datadogCredentials' as const,
    scope: 'read' as const,
    keywords: ['log', 'grep'],
  },
  {
    name: 'datadogListLogIndexes',
    description: datadogListLogIndexes.description!,
    tool: datadogListLogIndexes,
    requiredAuth: 'datadogCredentials' as const,
    scope: 'read' as const,
    keywords: ['log'],
  },
  {
    name: 'datadogListMetrics',
    description: datadogListMetrics.description!,
    tool: datadogListMetrics,
    requiredAuth: 'datadogCredentials' as const,
    scope: 'read' as const,
    keywords: ['metric', 'browse'],
  },
  {
    name: 'datadogQueryMetrics',
    description: datadogQueryMetrics.description!,
    tool: datadogQueryMetrics,
    requiredAuth: 'datadogCredentials' as const,
    scope: 'read' as const,
    keywords: ['metric', 'graph', 'chart'],
  },
  {
    name: 'datadogSubmitMetrics',
    description: datadogSubmitMetrics.description!,
    tool: datadogSubmitMetrics,
    requiredAuth: 'datadogCredentials' as const,
    scope: 'write' as const,
    keywords: ['metric', 'statsd', 'custom'],
  },
  {
    name: 'datadogCreateMonitor',
    description: datadogCreateMonitor.description!,
    tool: datadogCreateMonitor,
    requiredAuth: 'datadogCredentials' as const,
    scope: 'write' as const,
    keywords: ['alert', 'alerts'],
  },
  {
    name: 'datadogGetMonitor',
    description: datadogGetMonitor.description!,
    tool: datadogGetMonitor,
    requiredAuth: 'datadogCredentials' as const,
    scope: 'read' as const,
    keywords: ['alert', 'alerts', 'status'],
  },
  {
    name: 'datadogListMonitors',
    description: datadogListMonitors.description!,
    tool: datadogListMonitors,
    requiredAuth: 'datadogCredentials' as const,
    scope: 'read' as const,
    keywords: ['alert', 'alerts', 'browse'],
  },
  {
    name: 'datadogUpdateMonitor',
    description: datadogUpdateMonitor.description!,
    tool: datadogUpdateMonitor,
    requiredAuth: 'datadogCredentials' as const,
    scope: 'write' as const,
    keywords: ['alert', 'alerts'],
  },
  {
    name: 'datadogDeleteMonitor',
    description: datadogDeleteMonitor.description!,
    tool: datadogDeleteMonitor,
    requiredAuth: 'datadogCredentials' as const,
    scope: 'delete' as const,
    keywords: ['alert', 'alerts', 'remove'],
  },
  {
    name: 'datadogMuteMonitor',
    description: datadogMuteMonitor.description!,
    tool: datadogMuteMonitor,
    requiredAuth: 'datadogCredentials' as const,
    scope: 'write' as const,
    keywords: ['alert', 'snooze', 'silence'],
  },
  {
    name: 'datadogUnmuteMonitor',
    description: datadogUnmuteMonitor.description!,
    tool: datadogUnmuteMonitor,
    requiredAuth: 'datadogCredentials' as const,
    scope: 'write' as const,
    keywords: ['alert', 'resume'],
  },
  {
    name: 'datadogCreateDowntime',
    description: datadogCreateDowntime.description!,
    tool: datadogCreateDowntime,
    requiredAuth: 'datadogCredentials' as const,
    scope: 'write' as const,
    keywords: ['schedule', 'maintenance', 'silence'],
  },
  {
    name: 'datadogCreateDashboard',
    description: datadogCreateDashboard.description!,
    tool: datadogCreateDashboard,
    requiredAuth: 'datadogCredentials' as const,
    scope: 'write' as const,
    keywords: ['widget', 'widgets', 'screenboard', 'timeboard'],
  },
  {
    name: 'datadogGetDashboard',
    description: datadogGetDashboard.description!,
    tool: datadogGetDashboard,
    requiredAuth: 'datadogCredentials' as const,
    scope: 'read' as const,
    keywords: ['widget', 'widgets'],
  },
  {
    name: 'datadogUpdateDashboard',
    description: datadogUpdateDashboard.description!,
    tool: datadogUpdateDashboard,
    requiredAuth: 'datadogCredentials' as const,
    scope: 'write' as const,
    keywords: ['widget', 'widgets'],
  },
  {
    name: 'datadogDeleteDashboard',
    description: datadogDeleteDashboard.description!,
    tool: datadogDeleteDashboard,
    requiredAuth: 'datadogCredentials' as const,
    scope: 'delete' as const,
    keywords: ['widget', 'remove'],
  },
  {
    name: 'datadogListDashboards',
    description: datadogListDashboards.description!,
    tool: datadogListDashboards,
    requiredAuth: 'datadogCredentials' as const,
    scope: 'read' as const,
    keywords: ['widget', 'widgets', 'browse'],
  },
  {
    name: 'datadogCreateEvent',
    description: datadogCreateEvent.description!,
    tool: datadogCreateEvent,
    requiredAuth: 'datadogCredentials' as const,
    scope: 'write' as const,
    keywords: ['deploy', 'annotation'],
  },
  {
    name: 'datadogListEvents',
    description: datadogListEvents.description!,
    tool: datadogListEvents,
    requiredAuth: 'datadogCredentials' as const,
    scope: 'read' as const,
    keywords: ['deploy', 'incident'],
  },
  {
    name: 'datadogListHosts',
    description: datadogListHosts.description!,
    tool: datadogListHosts,
    requiredAuth: 'datadogCredentials' as const,
    scope: 'read' as const,
    keywords: ['host', 'server', 'servers', 'agent'],
  },
  {
    name: 'datadogGetHostTags',
    description: datadogGetHostTags.description!,
    tool: datadogGetHostTags,
    requiredAuth: 'datadogCredentials' as const,
    scope: 'read' as const,
    keywords: ['host', 'tag'],
  },
  {
    name: 'datadogListAllTags',
    description: datadogListAllTags.description!,
    tool: datadogListAllTags,
    requiredAuth: 'datadogCredentials' as const,
    scope: 'read' as const,
    keywords: ['tag', 'label', 'labels'],
  },
  {
    name: 'datadogUpdateHostTags',
    description: datadogUpdateHostTags.description!,
    tool: datadogUpdateHostTags,
    requiredAuth: 'datadogCredentials' as const,
    scope: 'write' as const,
    keywords: ['host', 'tag', 'label'],
  },
  {
    name: 'datadogListApmServices',
    description: datadogListApmServices.description!,
    tool: datadogListApmServices,
    requiredAuth: 'datadogCredentials' as const,
    scope: 'read' as const,
    keywords: ['trace', 'profiling', 'service'],
  },
  {
    name: 'datadogSearchTraces',
    description: datadogSearchTraces.description!,
    tool: datadogSearchTraces,
    requiredAuth: 'datadogCredentials' as const,
    scope: 'read' as const,
    keywords: ['span', 'spans', 'apm'],
  },
  {
    name: 'datadogSearchSpansAnalytics',
    description: datadogSearchSpansAnalytics.description!,
    tool: datadogSearchSpansAnalytics,
    requiredAuth: 'datadogCredentials' as const,
    scope: 'read' as const,
    keywords: ['analytics', 'apm', 'errors'],
  },
  {
    name: 'datadogCreateSyntheticApiTest',
    description: datadogCreateSyntheticApiTest.description!,
    tool: datadogCreateSyntheticApiTest,
    requiredAuth: 'datadogCredentials' as const,
    scope: 'write' as const,
    keywords: ['uptime', 'ping', 'browser'],
  },
  {
    name: 'datadogListSynthetics',
    description: datadogListSynthetics.description!,
    tool: datadogListSynthetics,
    requiredAuth: 'datadogCredentials' as const,
    scope: 'read' as const,
    keywords: ['uptime', 'test'],
  },
  {
    name: 'datadogGetSyntheticsLocations',
    description: datadogGetSyntheticsLocations.description!,
    tool: datadogGetSyntheticsLocations,
    requiredAuth: 'datadogCredentials' as const,
    scope: 'read' as const,
    keywords: ['uptime', 'region'],
  },
  {
    name: 'datadogListIncidents',
    description: datadogListIncidents.description!,
    tool: datadogListIncidents,
    requiredAuth: 'datadogCredentials' as const,
    scope: 'read' as const,
    keywords: ['incident', 'outage', 'postmortem'],
  },
  {
    name: 'datadogCreateSlo',
    description: datadogCreateSlo.description!,
    tool: datadogCreateSlo,
    requiredAuth: 'datadogCredentials' as const,
    scope: 'write' as const,
    keywords: ['sli', 'reliability', 'error-budget'],
  },
  {
    name: 'datadogListSlos',
    description: datadogListSlos.description!,
    tool: datadogListSlos,
    requiredAuth: 'datadogCredentials' as const,
    scope: 'read' as const,
    keywords: ['sli', 'reliability'],
  },
  {
    name: 'datadogListUsers',
    description: datadogListUsers.description!,
    tool: datadogListUsers,
    requiredAuth: 'datadogCredentials' as const,
    scope: 'read' as const,
    keywords: [],
  },
  {
    name: 'datadogListRoles',
    description: datadogListRoles.description!,
    tool: datadogListRoles,
    requiredAuth: 'datadogCredentials' as const,
    scope: 'read' as const,
    keywords: [],
  },
  {
    name: 'datadogGetUsageSummary',
    description: datadogGetUsageSummary.description!,
    tool: datadogGetUsageSummary,
    requiredAuth: 'datadogCredentials' as const,
    scope: 'read' as const,
    keywords: ['billing', 'cost'],
  },
  {
    name: 'datadogListApiKeys',
    description: datadogListApiKeys.description!,
    tool: datadogListApiKeys,
    requiredAuth: 'datadogCredentials' as const,
    scope: 'read' as const,
    keywords: ['token', 'rotate', 'secret'],
  },
  {
    name: 'datadogListAwsIntegrations',
    description: datadogListAwsIntegrations.description!,
    tool: datadogListAwsIntegrations,
    requiredAuth: 'datadogCredentials' as const,
    scope: 'read' as const,
    keywords: [],
  },
  {
    name: 'datadogCreateWebhook',
    description: datadogCreateWebhook.description!,
    tool: datadogCreateWebhook,
    requiredAuth: 'datadogCredentials' as const,
    scope: 'write' as const,
    keywords: ['notify', 'slack', 'alerts'],
  },
  {
    name: 'datadogCreateEscalationPolicy',
    description: datadogCreateEscalationPolicy.description!,
    tool: datadogCreateEscalationPolicy,
    requiredAuth: 'datadogCredentials' as const,
    scope: 'write' as const,
    keywords: ['oncall', 'on-call', 'page', 'paging'],
  },
  {
    name: 'datadogGetEscalationPolicy',
    description: datadogGetEscalationPolicy.description!,
    tool: datadogGetEscalationPolicy,
    requiredAuth: 'datadogCredentials' as const,
    scope: 'read' as const,
    keywords: ['oncall', 'on-call', 'page'],
  },
  {
    name: 'datadogUpdateEscalationPolicy',
    description: datadogUpdateEscalationPolicy.description!,
    tool: datadogUpdateEscalationPolicy,
    requiredAuth: 'datadogCredentials' as const,
    scope: 'write' as const,
    keywords: ['oncall', 'on-call'],
  },
  {
    name: 'datadogDeleteEscalationPolicy',
    description: datadogDeleteEscalationPolicy.description!,
    tool: datadogDeleteEscalationPolicy,
    requiredAuth: 'datadogCredentials' as const,
    scope: 'delete' as const,
    keywords: ['oncall', 'remove'],
  },
  {
    name: 'datadogCreateSchedule',
    description: datadogCreateSchedule.description!,
    tool: datadogCreateSchedule,
    requiredAuth: 'datadogCredentials' as const,
    scope: 'write' as const,
    keywords: ['oncall', 'on-call', 'shift', 'rotation', 'rota'],
  },
  {
    name: 'datadogGetSchedule',
    description: datadogGetSchedule.description!,
    tool: datadogGetSchedule,
    requiredAuth: 'datadogCredentials' as const,
    scope: 'read' as const,
    keywords: ['oncall', 'on-call', 'shift'],
  },
  {
    name: 'datadogUpdateSchedule',
    description: datadogUpdateSchedule.description!,
    tool: datadogUpdateSchedule,
    requiredAuth: 'datadogCredentials' as const,
    scope: 'write' as const,
    keywords: ['oncall', 'on-call', 'shift'],
  },
  {
    name: 'datadogDeleteSchedule',
    description: datadogDeleteSchedule.description!,
    tool: datadogDeleteSchedule,
    requiredAuth: 'datadogCredentials' as const,
    scope: 'delete' as const,
    keywords: ['oncall', 'remove'],
  },
  {
    name: 'datadogGetScheduledOnCallUser',
    description: datadogGetScheduledOnCallUser.description!,
    tool: datadogGetScheduledOnCallUser,
    requiredAuth: 'datadogCredentials' as const,
    scope: 'read' as const,
    keywords: ['oncall', 'page', 'shift'],
  },
  {
    name: 'datadogCreateNotificationChannel',
    description: datadogCreateNotificationChannel.description!,
    tool: datadogCreateNotificationChannel,
    requiredAuth: 'datadogCredentials' as const,
    scope: 'write' as const,
    keywords: ['oncall', 'sms', 'page'],
  },
  {
    name: 'datadogGetNotificationChannel',
    description: datadogGetNotificationChannel.description!,
    tool: datadogGetNotificationChannel,
    requiredAuth: 'datadogCredentials' as const,
    scope: 'read' as const,
    keywords: ['oncall'],
  },
  {
    name: 'datadogListNotificationChannels',
    description: datadogListNotificationChannels.description!,
    tool: datadogListNotificationChannels,
    requiredAuth: 'datadogCredentials' as const,
    scope: 'read' as const,
    keywords: ['oncall', 'sms'],
  },
  {
    name: 'datadogDeleteNotificationChannel',
    description: datadogDeleteNotificationChannel.description!,
    tool: datadogDeleteNotificationChannel,
    requiredAuth: 'datadogCredentials' as const,
    scope: 'delete' as const,
    keywords: ['oncall', 'remove'],
  },
  {
    name: 'datadogCreateNotificationRule',
    description: datadogCreateNotificationRule.description!,
    tool: datadogCreateNotificationRule,
    requiredAuth: 'datadogCredentials' as const,
    scope: 'write' as const,
    keywords: ['oncall', 'page'],
  },
  {
    name: 'datadogGetNotificationRule',
    description: datadogGetNotificationRule.description!,
    tool: datadogGetNotificationRule,
    requiredAuth: 'datadogCredentials' as const,
    scope: 'read' as const,
    keywords: ['oncall'],
  },
  {
    name: 'datadogListNotificationRules',
    description: datadogListNotificationRules.description!,
    tool: datadogListNotificationRules,
    requiredAuth: 'datadogCredentials' as const,
    scope: 'read' as const,
    keywords: ['oncall'],
  },
  {
    name: 'datadogUpdateNotificationRule',
    description: datadogUpdateNotificationRule.description!,
    tool: datadogUpdateNotificationRule,
    requiredAuth: 'datadogCredentials' as const,
    scope: 'write' as const,
    keywords: ['oncall'],
  },
  {
    name: 'datadogDeleteNotificationRule',
    description: datadogDeleteNotificationRule.description!,
    tool: datadogDeleteNotificationRule,
    requiredAuth: 'datadogCredentials' as const,
    scope: 'delete' as const,
    keywords: ['oncall', 'remove'],
  },
  {
    name: 'datadogGetTeamOnCallUsers',
    description: datadogGetTeamOnCallUsers.description!,
    tool: datadogGetTeamOnCallUsers,
    requiredAuth: 'datadogCredentials' as const,
    scope: 'read' as const,
    keywords: ['oncall', 'page', 'responders'],
  },
  {
    name: 'datadogGetTeamRoutingRules',
    description: datadogGetTeamRoutingRules.description!,
    tool: datadogGetTeamRoutingRules,
    requiredAuth: 'datadogCredentials' as const,
    scope: 'read' as const,
    keywords: ['oncall', 'escalation'],
  },
  {
    name: 'datadogSetTeamRoutingRules',
    description: datadogSetTeamRoutingRules.description!,
    tool: datadogSetTeamRoutingRules,
    requiredAuth: 'datadogCredentials' as const,
    scope: 'write' as const,
    keywords: ['oncall', 'escalation'],
  },
];
