// @ts-nocheck
import {
  redisGetAccount,
  redisListPaymentMethods,
  redisListPlans,
  redisListRegions,
  redisListDataPersistences,
  redisListDatabaseModules,
  redisGetLogs,
  redisGetSessionLogs,
  redisListTasks,
  redisGetTask,
  redisCreateCostReport,
  redisGetCostReport,
} from './account.js';
import {
  redisListSubscriptions,
  redisGetSubscription,
  redisCreateSubscription,
  redisUpdateSubscription,
  redisDeleteSubscription,
  redisGetSubscriptionCidr,
  redisUpdateSubscriptionCidr,
  redisGetSubscriptionPricing,
  redisGetMaintenanceWindows,
  redisUpdateMaintenanceWindows,
  redisListDatabases,
  redisGetDatabase,
  redisCreateDatabase,
  redisUpdateDatabase,
  redisDeleteDatabase,
  redisListBackups,
  redisBackupDatabase,
  redisImportDatabase,
  redisFlushDatabase,
  redisGetDatabaseCertificate,
  redisGetSlowLog,
  redisGetDatabaseTags,
  redisUpdateDatabaseTags,
  redisDeleteDatabaseTag,
} from './subscriptions.js';
import {
  redisListFixedSubscriptions,
  redisGetFixedSubscription,
  redisCreateFixedSubscription,
  redisUpdateFixedSubscription,
  redisDeleteFixedSubscription,
  redisListFixedDatabases,
  redisGetFixedDatabase,
  redisCreateFixedDatabase,
  redisUpdateFixedDatabase,
  redisDeleteFixedDatabase,
  redisListFixedBackups,
  redisBackupFixedDatabase,
  redisImportFixedDatabase,
} from './essentials.js';
import {
  redisListPeerings,
  redisCreatePeering,
  redisUpdatePeering,
  redisDeletePeering,
  redisListRegionsInSubscription,
  redisCreateSubscriptionRegion,
  redisDeleteSubscriptionRegion,
  redisListTransitGateways,
  redisListTransitGatewayInvitations,
  redisAcceptTransitGatewayInvitation,
  redisRejectTransitGatewayInvitation,
  redisCreateTransitGatewayAttachment,
  redisUpdateTransitGatewayAttachment,
  redisDeleteTransitGatewayAttachment,
} from './network.js';
import {
  redisListRedisRules,
  redisCreateRedisRule,
  redisUpdateRedisRule,
  redisDeleteRedisRule,
  redisListAclRoles,
  redisCreateAclRole,
  redisUpdateAclRole,
  redisDeleteAclRole,
  redisListAclUsers,
  redisGetAclUser,
  redisCreateAclUser,
  redisUpdateAclUser,
  redisDeleteAclUser,
  redisListUsers,
  redisGetUser,
  redisUpdateUser,
  redisDeleteUser,
  redisListCloudAccounts,
  redisGetCloudAccount,
  redisCreateCloudAccount,
  redisUpdateCloudAccount,
  redisDeleteCloudAccount,
} from './admin.js';

export {
  redisGetAccount,
  redisListPaymentMethods,
  redisListPlans,
  redisListRegions,
  redisListDataPersistences,
  redisListDatabaseModules,
  redisGetLogs,
  redisGetSessionLogs,
  redisListTasks,
  redisGetTask,
  redisCreateCostReport,
  redisGetCostReport,
  redisListSubscriptions,
  redisGetSubscription,
  redisCreateSubscription,
  redisUpdateSubscription,
  redisDeleteSubscription,
  redisGetSubscriptionCidr,
  redisUpdateSubscriptionCidr,
  redisGetSubscriptionPricing,
  redisGetMaintenanceWindows,
  redisUpdateMaintenanceWindows,
  redisListDatabases,
  redisGetDatabase,
  redisCreateDatabase,
  redisUpdateDatabase,
  redisDeleteDatabase,
  redisListBackups,
  redisBackupDatabase,
  redisImportDatabase,
  redisFlushDatabase,
  redisGetDatabaseCertificate,
  redisGetSlowLog,
  redisGetDatabaseTags,
  redisUpdateDatabaseTags,
  redisDeleteDatabaseTag,
  redisListFixedSubscriptions,
  redisGetFixedSubscription,
  redisCreateFixedSubscription,
  redisUpdateFixedSubscription,
  redisDeleteFixedSubscription,
  redisListFixedDatabases,
  redisGetFixedDatabase,
  redisCreateFixedDatabase,
  redisUpdateFixedDatabase,
  redisDeleteFixedDatabase,
  redisListFixedBackups,
  redisBackupFixedDatabase,
  redisImportFixedDatabase,
  redisListPeerings,
  redisCreatePeering,
  redisUpdatePeering,
  redisDeletePeering,
  redisListRegionsInSubscription,
  redisCreateSubscriptionRegion,
  redisDeleteSubscriptionRegion,
  redisListTransitGateways,
  redisListTransitGatewayInvitations,
  redisAcceptTransitGatewayInvitation,
  redisRejectTransitGatewayInvitation,
  redisCreateTransitGatewayAttachment,
  redisUpdateTransitGatewayAttachment,
  redisDeleteTransitGatewayAttachment,
  redisListRedisRules,
  redisCreateRedisRule,
  redisUpdateRedisRule,
  redisDeleteRedisRule,
  redisListAclRoles,
  redisCreateAclRole,
  redisUpdateAclRole,
  redisDeleteAclRole,
  redisListAclUsers,
  redisGetAclUser,
  redisCreateAclUser,
  redisUpdateAclUser,
  redisDeleteAclUser,
  redisListUsers,
  redisGetUser,
  redisUpdateUser,
  redisDeleteUser,
  redisListCloudAccounts,
  redisGetCloudAccount,
  redisCreateCloudAccount,
  redisUpdateCloudAccount,
  redisDeleteCloudAccount,
};

const AUTH = 'redisCredentials' as const;

export const redisTools = [
  {
    name: 'redisGetAccount',
    description: 'Get current account info; verifies credentials.',
    tool: redisGetAccount,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['whoami', 'health', 'owner'],
  },
  {
    name: 'redisListPaymentMethods',
    description: 'List payment methods for billing.',
    tool: redisListPaymentMethods,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['billing', 'cards'],
  },
  {
    name: 'redisListPlans',
    description: 'List Essentials plans by provider.',
    tool: redisListPlans,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['pricing', 'tiers'],
  },
  {
    name: 'redisListRegions',
    description: 'List cloud regions for subscriptions.',
    tool: redisListRegions,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['datacenters', 'zones'],
  },
  {
    name: 'redisListDataPersistences',
    description: 'List data persistence options.',
    tool: redisListDataPersistences,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['aof', 'rdb', 'snapshots'],
  },
  {
    name: 'redisListDatabaseModules',
    description: 'List database modules (JSON, Search, ...).',
    tool: redisListDatabaseModules,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['redisjson', 'redisearch', 'extensions'],
  },
  {
    name: 'redisGetLogs',
    description: 'Get account system logs.',
    tool: redisGetLogs,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['audit', 'events'],
  },
  {
    name: 'redisGetSessionLogs',
    description: 'Get session (login) logs.',
    tool: redisGetSessionLogs,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['logins', 'audit'],
  },
  {
    name: 'redisListTasks',
    description: 'List async API tasks.',
    tool: redisListTasks,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['operations', 'status'],
  },
  {
    name: 'redisGetTask',
    description: 'Get one async task.',
    tool: redisGetTask,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['operation', 'poll'],
  },
  {
    name: 'redisCreateCostReport',
    description: 'Request a FOCUS cost report.',
    tool: redisCreateCostReport,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['billing', 'spend'],
  },
  {
    name: 'redisGetCostReport',
    description: 'Get a cost report status and link.',
    tool: redisGetCostReport,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['billing', 'download'],
  },
  {
    name: 'redisListSubscriptions',
    description: 'List Pro subscriptions.',
    tool: redisListSubscriptions,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['accounts', 'deployments'],
  },
  {
    name: 'redisGetSubscription',
    description: 'Get one Pro subscription.',
    tool: redisGetSubscription,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['deployment', 'fetch'],
  },
  {
    name: 'redisCreateSubscription',
    description: 'Create a Pro subscription with databases.',
    tool: redisCreateSubscription,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['provision', 'deploy'],
  },
  {
    name: 'redisUpdateSubscription',
    description: 'Update a Pro subscription.',
    tool: redisUpdateSubscription,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['rename', 'billing'],
  },
  {
    name: 'redisDeleteSubscription',
    description: 'Delete a subscription.',
    tool: redisDeleteSubscription,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['decommission', 'remove'],
  },
  {
    name: 'redisGetSubscriptionCidr',
    description: 'Get subscription CIDR whitelist.',
    tool: redisGetSubscriptionCidr,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['network', 'firewall'],
  },
  {
    name: 'redisUpdateSubscriptionCidr',
    description: 'Set subscription CIDR whitelist.',
    tool: redisUpdateSubscriptionCidr,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['network', 'firewall'],
  },
  {
    name: 'redisGetSubscriptionPricing',
    description: 'Get pricing estimate for a subscription.',
    tool: redisGetSubscriptionPricing,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['cost', 'estimate'],
  },
  {
    name: 'redisGetMaintenanceWindows',
    description: 'Get maintenance windows.',
    tool: redisGetMaintenanceWindows,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['upkeep', 'schedule'],
  },
  {
    name: 'redisUpdateMaintenanceWindows',
    description: 'Set maintenance windows.',
    tool: redisUpdateMaintenanceWindows,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['upkeep', 'schedule'],
  },
  {
    name: 'redisListDatabases',
    description: 'List databases in a subscription.',
    tool: redisListDatabases,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['instances', 'dbs'],
  },
  {
    name: 'redisGetDatabase',
    description: 'Get one database with endpoints and status.',
    tool: redisGetDatabase,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['instance', 'fetch', 'endpoint'],
  },
  {
    name: 'redisCreateDatabase',
    description: 'Create a database with memory and modules.',
    tool: redisCreateDatabase,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['provision', 'instance'],
  },
  {
    name: 'redisUpdateDatabase',
    description: 'Update database memory and settings.',
    tool: redisUpdateDatabase,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['resize', 'scale'],
  },
  {
    name: 'redisDeleteDatabase',
    description: 'Delete a database permanently.',
    tool: redisDeleteDatabase,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['drop', 'remove'],
  },
  {
    name: 'redisListBackups',
    description: 'List available database backups.',
    tool: redisListBackups,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['snapshots', 'restore'],
  },
  {
    name: 'redisBackupDatabase',
    description: 'Trigger a manual database backup.',
    tool: redisBackupDatabase,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['snapshot', 'export'],
  },
  {
    name: 'redisImportDatabase',
    description: 'Import data from backup URIs.',
    tool: redisImportDatabase,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['restore', 'migrate', 'rdb'],
  },
  {
    name: 'redisFlushDatabase',
    description: 'Flush all data from a database.',
    tool: redisFlushDatabase,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['clear', 'wipe'],
  },
  {
    name: 'redisGetDatabaseCertificate',
    description: 'Get database TLS certificate.',
    tool: redisGetDatabaseCertificate,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['tls', 'ssl'],
  },
  {
    name: 'redisGetSlowLog',
    description: 'Get database slow log.',
    tool: redisGetSlowLog,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['performance', 'latency'],
  },
  {
    name: 'redisGetDatabaseTags',
    description: 'Get resource tags of a database.',
    tool: redisGetDatabaseTags,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['labels', 'metadata'],
  },
  {
    name: 'redisUpdateDatabaseTags',
    description: 'Add or update database tags.',
    tool: redisUpdateDatabaseTags,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['labels', 'annotate'],
  },
  {
    name: 'redisDeleteDatabaseTag',
    description: 'Delete one database tag.',
    tool: redisDeleteDatabaseTag,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['labels', 'remove'],
  },
  {
    name: 'redisListFixedSubscriptions',
    description: 'List Essentials subscriptions.',
    tool: redisListFixedSubscriptions,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['fixed', 'plans'],
  },
  {
    name: 'redisGetFixedSubscription',
    description: 'Get one Essentials subscription.',
    tool: redisGetFixedSubscription,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['fixed', 'fetch'],
  },
  {
    name: 'redisCreateFixedSubscription',
    description: 'Create an Essentials subscription.',
    tool: redisCreateFixedSubscription,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['fixed', 'provision'],
  },
  {
    name: 'redisUpdateFixedSubscription',
    description: 'Update an Essentials subscription.',
    tool: redisUpdateFixedSubscription,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['fixed', 'edit'],
  },
  {
    name: 'redisDeleteFixedSubscription',
    description: 'Delete an Essentials subscription.',
    tool: redisDeleteFixedSubscription,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['fixed', 'remove'],
  },
  {
    name: 'redisListFixedDatabases',
    description: 'List Essentials databases.',
    tool: redisListFixedDatabases,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['fixed', 'instances'],
  },
  {
    name: 'redisGetFixedDatabase',
    description: 'Get one Essentials database.',
    tool: redisGetFixedDatabase,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['fixed', 'fetch'],
  },
  {
    name: 'redisCreateFixedDatabase',
    description: 'Create an Essentials database.',
    tool: redisCreateFixedDatabase,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['fixed', 'provision'],
  },
  {
    name: 'redisUpdateFixedDatabase',
    description: 'Update an Essentials database.',
    tool: redisUpdateFixedDatabase,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['fixed', 'edit'],
  },
  {
    name: 'redisDeleteFixedDatabase',
    description: 'Delete an Essentials database.',
    tool: redisDeleteFixedDatabase,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['fixed', 'remove'],
  },
  {
    name: 'redisListFixedBackups',
    description: 'List Essentials database backups.',
    tool: redisListFixedBackups,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['fixed', 'snapshots'],
  },
  {
    name: 'redisBackupFixedDatabase',
    description: 'Back up an Essentials database.',
    tool: redisBackupFixedDatabase,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['fixed', 'snapshot'],
  },
  {
    name: 'redisImportFixedDatabase',
    description: 'Import into an Essentials database.',
    tool: redisImportFixedDatabase,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['fixed', 'restore'],
  },
  {
    name: 'redisListPeerings',
    description: 'List VPC peerings.',
    tool: redisListPeerings,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['vpc', 'network'],
  },
  {
    name: 'redisCreatePeering',
    description: 'Create a VPC peering.',
    tool: redisCreatePeering,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['vpc', 'connect'],
  },
  {
    name: 'redisUpdatePeering',
    description: 'Update a VPC peering.',
    tool: redisUpdatePeering,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['vpc', 'edit'],
  },
  {
    name: 'redisDeletePeering',
    description: 'Delete a VPC peering.',
    tool: redisDeletePeering,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['vpc', 'remove'],
  },
  {
    name: 'redisListRegionsInSubscription',
    description: 'List regions of a subscription.',
    tool: redisListRegionsInSubscription,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['active-active', 'geo'],
  },
  {
    name: 'redisCreateSubscriptionRegion',
    description: 'Attach a region (Active-Active).',
    tool: redisCreateSubscriptionRegion,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['active-active', 'expand'],
  },
  {
    name: 'redisDeleteSubscriptionRegion',
    description: 'Detach a region.',
    tool: redisDeleteSubscriptionRegion,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['active-active', 'shrink'],
  },
  {
    name: 'redisListTransitGateways',
    description: 'List Transit Gateway attachments.',
    tool: redisListTransitGateways,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['aws', 'network'],
  },
  {
    name: 'redisListTransitGatewayInvitations',
    description: 'List TGW RAM invitations.',
    tool: redisListTransitGatewayInvitations,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['aws', 'ram'],
  },
  {
    name: 'redisAcceptTransitGatewayInvitation',
    description: 'Accept a TGW invitation.',
    tool: redisAcceptTransitGatewayInvitation,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['aws', 'approve'],
  },
  {
    name: 'redisRejectTransitGatewayInvitation',
    description: 'Reject a TGW invitation.',
    tool: redisRejectTransitGatewayInvitation,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['aws', 'decline'],
  },
  {
    name: 'redisCreateTransitGatewayAttachment',
    description: 'Create a TGW attachment.',
    tool: redisCreateTransitGatewayAttachment,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['aws', 'connect'],
  },
  {
    name: 'redisUpdateTransitGatewayAttachment',
    description: 'Update a TGW attachment.',
    tool: redisUpdateTransitGatewayAttachment,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['aws', 'edit'],
  },
  {
    name: 'redisDeleteTransitGatewayAttachment',
    description: 'Delete a TGW attachment.',
    tool: redisDeleteTransitGatewayAttachment,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['aws', 'remove'],
  },
  {
    name: 'redisListRedisRules',
    description: 'List ACL Redis rules.',
    tool: redisListRedisRules,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['permissions', 'commands'],
  },
  {
    name: 'redisCreateRedisRule',
    description: 'Create an ACL Redis rule.',
    tool: redisCreateRedisRule,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['permissions', 'grant'],
  },
  {
    name: 'redisUpdateRedisRule',
    description: 'Update an ACL Redis rule.',
    tool: redisUpdateRedisRule,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['permissions', 'edit'],
  },
  {
    name: 'redisDeleteRedisRule',
    description: 'Delete an ACL Redis rule.',
    tool: redisDeleteRedisRule,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['permissions', 'remove'],
  },
  {
    name: 'redisListAclRoles',
    description: 'List ACL roles.',
    tool: redisListAclRoles,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['rbac', 'permissions'],
  },
  {
    name: 'redisCreateAclRole',
    description: 'Create an ACL role.',
    tool: redisCreateAclRole,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['rbac', 'grant'],
  },
  {
    name: 'redisUpdateAclRole',
    description: 'Update an ACL role.',
    tool: redisUpdateAclRole,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['rbac', 'edit'],
  },
  {
    name: 'redisDeleteAclRole',
    description: 'Delete an ACL role.',
    tool: redisDeleteAclRole,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['rbac', 'remove'],
  },
  {
    name: 'redisListAclUsers',
    description: 'List database ACL users.',
    tool: redisListAclUsers,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['credentials', 'logins'],
  },
  {
    name: 'redisGetAclUser',
    description: 'Get one database ACL user.',
    tool: redisGetAclUser,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['credential', 'fetch'],
  },
  {
    name: 'redisCreateAclUser',
    description: 'Create a database user.',
    tool: redisCreateAclUser,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['credential', 'provision'],
  },
  {
    name: 'redisUpdateAclUser',
    description: 'Update user role or password.',
    tool: redisUpdateAclUser,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['credential', 'rotate'],
  },
  {
    name: 'redisDeleteAclUser',
    description: 'Delete a database ACL user.',
    tool: redisDeleteAclUser,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['credential', 'remove'],
  },
  {
    name: 'redisListUsers',
    description: 'List account (console) users.',
    tool: redisListUsers,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['team', 'members'],
  },
  {
    name: 'redisGetUser',
    description: 'Get one account user.',
    tool: redisGetUser,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['member', 'fetch'],
  },
  {
    name: 'redisUpdateUser',
    description: 'Update an account user.',
    tool: redisUpdateUser,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['member', 'edit'],
  },
  {
    name: 'redisDeleteUser',
    description: 'Delete an account user.',
    tool: redisDeleteUser,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['member', 'remove'],
  },
  {
    name: 'redisListCloudAccounts',
    description: 'List cloud provider accounts.',
    tool: redisListCloudAccounts,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['byoc', 'aws'],
  },
  {
    name: 'redisGetCloudAccount',
    description: 'Get one cloud account.',
    tool: redisGetCloudAccount,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['byoc', 'fetch'],
  },
  {
    name: 'redisCreateCloudAccount',
    description: 'Connect a cloud provider account.',
    tool: redisCreateCloudAccount,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['byoc', 'onboard'],
  },
  {
    name: 'redisUpdateCloudAccount',
    description: 'Update a cloud account.',
    tool: redisUpdateCloudAccount,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['byoc', 'edit'],
  },
  {
    name: 'redisDeleteCloudAccount',
    description: 'Delete a cloud account.',
    tool: redisDeleteCloudAccount,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['byoc', 'remove'],
  },
];
