// @ts-nocheck
import {
  kaggleCompetitionDownloadFiles,
  kaggleCompetitionSubmit,
  kaggleDownloadCompetitionFile,
  kaggleDownloadCompetitionLeaderboard,
  kaggleGenerateCompetitionSubmissionUrl,
  kaggleListCompetitionFiles,
  kaggleListCompetitions,
  kaggleViewCompetitionLeaderboard,
} from './competitions.js';
export {
  kaggleCompetitionDownloadFiles,
  kaggleCompetitionSubmit,
  kaggleDownloadCompetitionFile,
  kaggleDownloadCompetitionLeaderboard,
  kaggleGenerateCompetitionSubmissionUrl,
  kaggleListCompetitionFiles,
  kaggleListCompetitions,
  kaggleViewCompetitionLeaderboard,
};
import {
  kaggleConfigDir,
  kaggleConfigInit,
  kaggleConfigKeys,
  kaggleConfigPath,
  kaggleConfigReset,
  kaggleConfigSet,
  kaggleConfigUnset,
  kaggleConfigView,
} from './config.js';
export {
  kaggleConfigDir,
  kaggleConfigInit,
  kaggleConfigKeys,
  kaggleConfigPath,
  kaggleConfigReset,
  kaggleConfigSet,
  kaggleConfigUnset,
  kaggleConfigView,
};
import {
  kaggleDatasetCreate,
  kaggleDatasetInit,
  kaggleDatasetListFiles,
  kaggleDatasetStatus,
  kaggleDatasetVersion,
  kaggleDownloadDataset,
  kaggleDownloadDatasetFile,
  kaggleGetDatasetMetadata,
  kaggleListDatasets,
} from './datasets.js';
export {
  kaggleDatasetCreate,
  kaggleDatasetInit,
  kaggleDatasetListFiles,
  kaggleDatasetStatus,
  kaggleDatasetVersion,
  kaggleDownloadDataset,
  kaggleDownloadDatasetFile,
  kaggleGetDatasetMetadata,
  kaggleListDatasets,
};
import { kaggleGetModel, kaggleListModels } from './models.js';
export { kaggleGetModel, kaggleListModels };
import { kaggleGetModelInstance } from './model_instances.js';
export { kaggleGetModelInstance };
import {
  kaggleKernelInit,
  kaggleKernelOutput,
  kaggleKernelsStatus,
  kaggleListKernelOutputFiles,
  kaggleListKernels,
  kagglePullKernel,
} from './kernels.js';
export {
  kaggleKernelInit,
  kaggleKernelOutput,
  kaggleKernelsStatus,
  kaggleListKernelOutputFiles,
  kaggleListKernels,
  kagglePullKernel,
};
import { kaggleListModelInstanceVersionFiles } from './model_instance_files.js';
export { kaggleListModelInstanceVersionFiles };

export const kaggleTools = [
  {
    name: 'kaggleCompetitionDownloadFiles',
    keywords: ['competition', 'competitions', 'data', 'download', 'zip', 'dataset'],
    description: kaggleCompetitionDownloadFiles.description!,
    tool: kaggleCompetitionDownloadFiles,
    requiredAuth: 'kaggleCredentials' as const,
    scope: 'read' as const,
  },
  {
    name: 'kaggleCompetitionSubmit',
    keywords: ['competition', 'submission', 'submissions', 'submit', 'entry'],
    description: kaggleCompetitionSubmit.description!,
    tool: kaggleCompetitionSubmit,
    requiredAuth: 'kaggleCredentials' as const,
    scope: 'write' as const,
  },
  {
    name: 'kaggleConfigDir',
    keywords: ['config', 'credentials', 'path', 'setup'],
    description: kaggleConfigDir.description!,
    tool: kaggleConfigDir,
    requiredAuth: 'kaggleCredentials' as const,
    scope: 'read' as const,
  },
  {
    name: 'kaggleConfigInit',
    keywords: ['config', 'setup', 'credentials'],
    description: kaggleConfigInit.description!,
    tool: kaggleConfigInit,
    requiredAuth: 'kaggleCredentials' as const,
    scope: 'write' as const,
  },
  {
    name: 'kaggleConfigKeys',
    keywords: ['config', 'keys', 'settings'],
    description: kaggleConfigKeys.description!,
    tool: kaggleConfigKeys,
    requiredAuth: 'kaggleCredentials' as const,
    scope: 'read' as const,
  },
  {
    name: 'kaggleConfigPath',
    keywords: ['config', 'path', 'credentials'],
    description: kaggleConfigPath.description!,
    tool: kaggleConfigPath,
    requiredAuth: 'kaggleCredentials' as const,
    scope: 'read' as const,
  },
  {
    name: 'kaggleConfigReset',
    keywords: ['config', 'reset', 'defaults'],
    description: kaggleConfigReset.description!,
    tool: kaggleConfigReset,
    requiredAuth: 'kaggleCredentials' as const,
    scope: 'write' as const,
  },
  {
    name: 'kaggleConfigSet',
    keywords: ['config', 'set', 'setting'],
    description: kaggleConfigSet.description!,
    tool: kaggleConfigSet,
    requiredAuth: 'kaggleCredentials' as const,
    scope: 'write' as const,
  },
  {
    name: 'kaggleConfigUnset',
    keywords: ['config', 'unset', 'remove'],
    description: kaggleConfigUnset.description!,
    tool: kaggleConfigUnset,
    requiredAuth: 'kaggleCredentials' as const,
    scope: 'write' as const,
  },
  {
    name: 'kaggleConfigView',
    keywords: ['config', 'view', 'credentials', 'settings'],
    description: kaggleConfigView.description!,
    tool: kaggleConfigView,
    requiredAuth: 'kaggleCredentials' as const,
    scope: 'read' as const,
  },
  {
    name: 'kaggleDatasetCreate',
    keywords: ['datasets', 'dataset', 'upload', 'new'],
    description: kaggleDatasetCreate.description!,
    tool: kaggleDatasetCreate,
    requiredAuth: 'kaggleCredentials' as const,
    scope: 'write' as const,
  },
  {
    name: 'kaggleDatasetInit',
    keywords: ['dataset', 'metadata', 'init', 'upload'],
    description: kaggleDatasetInit.description!,
    tool: kaggleDatasetInit,
    requiredAuth: 'kaggleCredentials' as const,
    scope: 'write' as const,
  },
  {
    name: 'kaggleDatasetListFiles',
    keywords: ['dataset', 'datasets', 'file', 'files'],
    description: kaggleDatasetListFiles.description!,
    tool: kaggleDatasetListFiles,
    requiredAuth: 'kaggleCredentials' as const,
    scope: 'read' as const,
  },
  {
    name: 'kaggleDatasetStatus',
    keywords: ['dataset', 'status', 'processing', 'ready'],
    description: kaggleDatasetStatus.description!,
    tool: kaggleDatasetStatus,
    requiredAuth: 'kaggleCredentials' as const,
    scope: 'read' as const,
  },
  {
    name: 'kaggleDatasetVersion',
    keywords: ['dataset', 'version', 'versions', 'update', 'new'],
    description: kaggleDatasetVersion.description!,
    tool: kaggleDatasetVersion,
    requiredAuth: 'kaggleCredentials' as const,
    scope: 'write' as const,
  },
  {
    name: 'kaggleDownloadCompetitionFile',
    keywords: ['competition', 'file', 'download', 'data'],
    description: kaggleDownloadCompetitionFile.description!,
    tool: kaggleDownloadCompetitionFile,
    requiredAuth: 'kaggleCredentials' as const,
    scope: 'read' as const,
  },
  {
    name: 'kaggleDownloadCompetitionLeaderboard',
    keywords: ['competition', 'leaderboard', 'ranking', 'standings', 'csv', 'download'],
    description: kaggleDownloadCompetitionLeaderboard.description!,
    tool: kaggleDownloadCompetitionLeaderboard,
    requiredAuth: 'kaggleCredentials' as const,
    scope: 'read' as const,
  },
  {
    name: 'kaggleDownloadDataset',
    keywords: ['datasets', 'dataset', 'download', 'zip', 'data'],
    description: kaggleDownloadDataset.description!,
    tool: kaggleDownloadDataset,
    requiredAuth: 'kaggleCredentials' as const,
    scope: 'read' as const,
  },
  {
    name: 'kaggleDownloadDatasetFile',
    keywords: ['dataset', 'file', 'download', 'data'],
    description: kaggleDownloadDatasetFile.description!,
    tool: kaggleDownloadDatasetFile,
    requiredAuth: 'kaggleCredentials' as const,
    scope: 'read' as const,
  },
  {
    name: 'kaggleGenerateCompetitionSubmissionUrl',
    keywords: ['competition', 'submission', 'upload', 'url', 'submit'],
    description: kaggleGenerateCompetitionSubmissionUrl.description!,
    tool: kaggleGenerateCompetitionSubmissionUrl,
    requiredAuth: 'kaggleCredentials' as const,
    scope: 'write' as const,
  },
  {
    name: 'kaggleGetDatasetMetadata',
    keywords: ['dataset', 'datasets', 'metadata', 'info', 'details'],
    description: kaggleGetDatasetMetadata.description!,
    tool: kaggleGetDatasetMetadata,
    requiredAuth: 'kaggleCredentials' as const,
    scope: 'read' as const,
  },
  {
    name: 'kaggleGetModel',
    keywords: ['models', 'model', 'info', 'details'],
    description: kaggleGetModel.description!,
    tool: kaggleGetModel,
    requiredAuth: 'kaggleCredentials' as const,
    scope: 'read' as const,
  },
  {
    name: 'kaggleGetModelInstance',
    keywords: ['model', 'models', 'instance', 'variation', 'version'],
    description: kaggleGetModelInstance.description!,
    tool: kaggleGetModelInstance,
    requiredAuth: 'kaggleCredentials' as const,
    scope: 'read' as const,
  },
  {
    name: 'kaggleKernelInit',
    keywords: ['notebook', 'notebooks', 'kernel', 'metadata', 'init', 'template'],
    description: kaggleKernelInit.description!,
    tool: kaggleKernelInit,
    requiredAuth: 'kaggleCredentials' as const,
    scope: 'write' as const,
  },
  {
    name: 'kaggleKernelOutput',
    keywords: ['notebook', 'kernel', 'output', 'results', 'download'],
    description: kaggleKernelOutput.description!,
    tool: kaggleKernelOutput,
    requiredAuth: 'kaggleCredentials' as const,
    scope: 'read' as const,
  },
  {
    name: 'kaggleKernelsStatus',
    keywords: ['notebook', 'notebooks', 'kernel', 'status', 'running', 'execution'],
    description: kaggleKernelsStatus.description!,
    tool: kaggleKernelsStatus,
    requiredAuth: 'kaggleCredentials' as const,
    scope: 'read' as const,
  },
  {
    name: 'kaggleListCompetitionFiles',
    keywords: ['competition', 'competitions', 'file', 'files', 'data'],
    description: kaggleListCompetitionFiles.description!,
    tool: kaggleListCompetitionFiles,
    requiredAuth: 'kaggleCredentials' as const,
    scope: 'read' as const,
  },
  {
    name: 'kaggleListCompetitions',
    keywords: ['competition', 'browse', 'discover', 'search'],
    description: kaggleListCompetitions.description!,
    tool: kaggleListCompetitions,
    requiredAuth: 'kaggleCredentials' as const,
    scope: 'read' as const,
  },
  {
    name: 'kaggleListDatasets',
    keywords: ['dataset', 'browse', 'discover', 'search', 'data'],
    description: kaggleListDatasets.description!,
    tool: kaggleListDatasets,
    requiredAuth: 'kaggleCredentials' as const,
    scope: 'read' as const,
  },
  {
    name: 'kaggleListKernelOutputFiles',
    keywords: ['notebook', 'kernel', 'output', 'file', 'files', 'results'],
    description: kaggleListKernelOutputFiles.description!,
    tool: kaggleListKernelOutputFiles,
    requiredAuth: 'kaggleCredentials' as const,
    scope: 'read' as const,
  },
  {
    name: 'kaggleListKernels',
    keywords: ['notebook', 'notebooks', 'kernel', 'script', 'scripts', 'discover', 'search'],
    description: kaggleListKernels.description!,
    tool: kaggleListKernels,
    requiredAuth: 'kaggleCredentials' as const,
    scope: 'read' as const,
  },
  {
    name: 'kaggleListModelInstanceVersionFiles',
    keywords: ['model', 'instance', 'file', 'files', 'version'],
    description: kaggleListModelInstanceVersionFiles.description!,
    tool: kaggleListModelInstanceVersionFiles,
    requiredAuth: 'kaggleCredentials' as const,
    scope: 'read' as const,
  },
  {
    name: 'kaggleListModels',
    keywords: ['model', 'discover', 'search', 'browse'],
    description: kaggleListModels.description!,
    tool: kaggleListModels,
    requiredAuth: 'kaggleCredentials' as const,
    scope: 'read' as const,
  },
  {
    name: 'kagglePullKernel',
    keywords: ['notebook', 'kernel', 'download', 'source', 'code', 'pull'],
    description: kagglePullKernel.description!,
    tool: kagglePullKernel,
    requiredAuth: 'kaggleCredentials' as const,
    scope: 'read' as const,
  },
  {
    name: 'kaggleViewCompetitionLeaderboard',
    keywords: ['competition', 'leaderboard', 'ranking', 'rankings', 'standings', 'scores'],
    description: kaggleViewCompetitionLeaderboard.description!,
    tool: kaggleViewCompetitionLeaderboard,
    requiredAuth: 'kaggleCredentials' as const,
    scope: 'read' as const,
  },
];
