// @ts-nocheck
import {
  linkedinCreateArticleShare,
  linkedinCreatePost,
  linkedinCreateVideoPost,
  linkedinDeletePost,
  linkedinDeleteShare,
  linkedinDeleteUgcPost,
  linkedinGetPostContent,
} from './posts.js';
import { linkedinCreateComment, linkedinListReactions } from './comments.js';
import {
  linkedinGetImage,
  linkedinGetImages,
  linkedinGetVideos,
  linkedinInitializeImageUpload,
  linkedinRegisterImageUpload,
  linkedinUploadVideo,
} from './media.js';
import { linkedinGetMyInfo, linkedinGetPerson, linkedinWhoAmI } from './profile.js';
import {
  linkedinGetCompanyInfo,
  linkedinGetNetworkSize,
  linkedinGetOrgPageStats,
  linkedinGetShareStats,
} from './organizations.js';
import {
  linkedinGetAdTargetingFacets,
  linkedinGetAudienceCounts,
  linkedinSearchAdTargetingEntities,
} from './ads.js';

export {
  linkedinCreateArticleShare,
  linkedinCreatePost,
  linkedinCreateVideoPost,
  linkedinDeletePost,
  linkedinDeleteShare,
  linkedinDeleteUgcPost,
  linkedinGetPostContent,
  linkedinCreateComment,
  linkedinListReactions,
  linkedinGetImage,
  linkedinGetImages,
  linkedinGetVideos,
  linkedinInitializeImageUpload,
  linkedinRegisterImageUpload,
  linkedinUploadVideo,
  linkedinGetMyInfo,
  linkedinGetPerson,
  linkedinWhoAmI,
  linkedinGetCompanyInfo,
  linkedinGetNetworkSize,
  linkedinGetOrgPageStats,
  linkedinGetShareStats,
  linkedinGetAdTargetingFacets,
  linkedinGetAudienceCounts,
  linkedinSearchAdTargetingEntities,
};

const auth = { requiredAuth: 'linkedinToken' as const };

export const linkedinTools = [
  {
    name: 'linkedinCreatePost',
    description: linkedinCreatePost.description!,
    tool: linkedinCreatePost,
    ...auth,
    scope: 'write' as const,
    keywords: ['share update', 'publish status', 'new post', 'announcement'],
  },
  {
    name: 'linkedinCreateArticleShare',
    description: linkedinCreateArticleShare.description!,
    tool: linkedinCreateArticleShare,
    ...auth,
    scope: 'write' as const,
    keywords: ['share link', 'url share', 'link preview'],
  },
  {
    name: 'linkedinCreateVideoPost',
    description: linkedinCreateVideoPost.description!,
    tool: linkedinCreateVideoPost,
    ...auth,
    scope: 'write' as const,
    keywords: ['native video', 'video share', 'publish video'],
  },
  {
    name: 'linkedinGetPostContent',
    description: linkedinGetPostContent.description!,
    tool: linkedinGetPostContent,
    ...auth,
    scope: 'read' as const,
    keywords: ['fetch post', 'post details', 'ugc content'],
  },
  {
    name: 'linkedinDeletePost',
    description: linkedinDeletePost.description!,
    tool: linkedinDeletePost,
    ...auth,
    scope: 'delete' as const,
    keywords: ['remove post', 'delete share'],
  },
  {
    name: 'linkedinDeleteShare',
    description: linkedinDeleteShare.description!,
    tool: linkedinDeleteShare,
    ...auth,
    scope: 'delete' as const,
    keywords: ['remove share', 'delete by id'],
  },
  {
    name: 'linkedinDeleteUgcPost',
    description: linkedinDeleteUgcPost.description!,
    tool: linkedinDeleteUgcPost,
    ...auth,
    scope: 'delete' as const,
    keywords: ['remove ugc', 'delete ugcpost'],
  },
  {
    name: 'linkedinCreateComment',
    description: linkedinCreateComment.description!,
    tool: linkedinCreateComment,
    ...auth,
    scope: 'write' as const,
    keywords: ['reply', 'comment on share', 'mention'],
  },
  {
    name: 'linkedinListReactions',
    description: linkedinListReactions.description!,
    tool: linkedinListReactions,
    ...auth,
    scope: 'read' as const,
    keywords: ['likes', 'reactions list', 'who liked'],
  },
  {
    name: 'linkedinInitializeImageUpload',
    description: linkedinInitializeImageUpload.description!,
    tool: linkedinInitializeImageUpload,
    ...auth,
    scope: 'write' as const,
    keywords: ['image upload url', 'presigned upload', 'prepare image'],
  },
  {
    name: 'linkedinRegisterImageUpload',
    description: linkedinRegisterImageUpload.description!,
    tool: linkedinRegisterImageUpload,
    ...auth,
    scope: 'write' as const,
    keywords: ['register asset', 'digitalmedia asset', 'image upload legacy'],
  },
  {
    name: 'linkedinGetImage',
    description: linkedinGetImage.description!,
    tool: linkedinGetImage,
    ...auth,
    scope: 'read' as const,
    keywords: ['image metadata', 'image status', 'download url'],
  },
  {
    name: 'linkedinGetImages',
    description: linkedinGetImages.description!,
    tool: linkedinGetImages,
    ...auth,
    scope: 'read' as const,
    keywords: ['batch images', 'image library'],
  },
  {
    name: 'linkedinGetVideos',
    description: linkedinGetVideos.description!,
    tool: linkedinGetVideos,
    ...auth,
    scope: 'read' as const,
    keywords: ['video metadata', 'video status', 'batch videos'],
  },
  {
    name: 'linkedinUploadVideo',
    description: linkedinUploadVideo.description!,
    tool: linkedinUploadVideo,
    ...auth,
    scope: 'write' as const,
    keywords: ['mp4 upload', 'native video upload', 'video processing'],
  },
  {
    name: 'linkedinGetMyInfo',
    description: linkedinGetMyInfo.description!,
    tool: linkedinGetMyInfo,
    ...auth,
    scope: 'read' as const,
    keywords: ['my profile', 'current member', 'userinfo'],
  },
  {
    name: 'linkedinWhoAmI',
    description: linkedinWhoAmI.description!,
    tool: linkedinWhoAmI,
    ...auth,
    scope: 'read' as const,
    keywords: ['account identity', 'connected account', 'my email'],
  },
  {
    name: 'linkedinGetPerson',
    description: linkedinGetPerson.description!,
    tool: linkedinGetPerson,
    ...auth,
    scope: 'read' as const,
    keywords: ['member profile', 'lite profile', 'find member'],
  },
  {
    name: 'linkedinGetCompanyInfo',
    description: linkedinGetCompanyInfo.description!,
    tool: linkedinGetCompanyInfo,
    ...auth,
    scope: 'read' as const,
    keywords: ['organizations', 'company pages', 'page roles', 'admin orgs'],
  },
  {
    name: 'linkedinGetNetworkSize',
    description: linkedinGetNetworkSize.description!,
    tool: linkedinGetNetworkSize,
    ...auth,
    scope: 'read' as const,
    keywords: ['follower count', 'page followers', 'org reach'],
  },
  {
    name: 'linkedinGetOrgPageStats',
    description: linkedinGetOrgPageStats.description!,
    tool: linkedinGetOrgPageStats,
    ...auth,
    scope: 'read' as const,
    keywords: ['page views', 'page analytics', 'company metrics'],
  },
  {
    name: 'linkedinGetShareStats',
    description: linkedinGetShareStats.description!,
    tool: linkedinGetShareStats,
    ...auth,
    scope: 'read' as const,
    keywords: ['content analytics', 'impressions', 'engagement metrics'],
  },
  {
    name: 'linkedinGetAdTargetingFacets',
    description: linkedinGetAdTargetingFacets.description!,
    tool: linkedinGetAdTargetingFacets,
    ...auth,
    scope: 'read' as const,
    keywords: ['targeting options', 'ad facets', 'audience facets'],
  },
  {
    name: 'linkedinGetAudienceCounts',
    description: linkedinGetAudienceCounts.description!,
    tool: linkedinGetAudienceCounts,
    ...auth,
    scope: 'read' as const,
    keywords: ['reach estimate', 'audience size', 'campaign sizing'],
  },
  {
    name: 'linkedinSearchAdTargetingEntities',
    description: linkedinSearchAdTargetingEntities.description!,
    tool: linkedinSearchAdTargetingEntities,
    ...auth,
    scope: 'read' as const,
    keywords: ['typeahead', 'location lookup', 'title lookup'],
  },
];
