// @ts-nocheck
import {
  geocodeAddressWithQuery,
  geocodeDestinations,
  geocodePlace,
  geocodingApi,
  reverseGeocodeLocation,
} from './geocode.js';
import {
  embedGoogleMap,
  geolocateDevice,
  getTimeZone,
  lookupAerialVideo,
  renderAerialVideo,
} from './misc.js';
import {
  autocompletePlaces,
  getPlaceDetails,
  getPlacePhoto,
  nearbySearchPlaces,
  textSearchPlaces,
} from './places.js';
import { computeRouteMatrix, getRoute } from './routes.js';
import { createTilesSession, get2dTile, get3dTilesRoot } from './tiles.js';

export {
  autocompletePlaces,
  getPlaceDetails,
  textSearchPlaces,
  nearbySearchPlaces,
  getPlacePhoto,
  geocodeAddressWithQuery,
  geocodeDestinations,
  reverseGeocodeLocation,
  geocodePlace,
  geocodingApi,
  computeRouteMatrix,
  getRoute,
  createTilesSession,
  get2dTile,
  get3dTilesRoot,
  geolocateDevice,
  getTimeZone,
  embedGoogleMap,
  lookupAerialVideo,
  renderAerialVideo,
};

const auth = 'googleMapsToken' as const;

export const googleMapsTools = [
  {
    name: 'googleMapsAutocompletePlaces',
    description: 'Returns up to 5 as-you-type place/query predictions.',
    tool: autocompletePlaces,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['suggestions', 'search'],
  },
  {
    name: 'googleMapsGetPlaceDetails',
    description: 'Gets full details for a place ID with field selection.',
    tool: getPlaceDetails,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['info', 'place'],
  },
  {
    name: 'googleMapsTextSearchPlaces',
    description: 'Searches places by text query like "restaurants in London".',
    tool: textSearchPlaces,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['find'],
  },
  {
    name: 'googleMapsNearbySearchPlaces',
    description: 'Finds places in a circle by type filters.',
    tool: nearbySearchPlaces,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['near', 'around'],
  },
  {
    name: 'googleMapsGetPlacePhoto',
    description: 'Downloads a place photo by photo resource name.',
    tool: getPlacePhoto,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['picture', 'image'],
  },
  {
    name: 'googleMapsGeocodeAddressWithQuery',
    description: 'Converts a full address string to coordinates.',
    tool: geocodeAddressWithQuery,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['latitude', 'longitude', 'lat', 'lng'],
  },
  {
    name: 'googleMapsGeocodeDestinations',
    description: 'Returns rich destination data (places, entrances, navigation points).',
    tool: geocodeDestinations,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['destination', 'address'],
  },
  {
    name: 'googleMapsReverseGeocodeLocation',
    description: 'Converts coordinates to addresses.',
    tool: reverseGeocodeLocation,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['address', 'lookup'],
  },
  {
    name: 'googleMapsGeocodePlace',
    description: 'Looks up address and coordinates for a place ID.',
    tool: geocodePlace,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['address'],
  },
  {
    name: 'googleMapsGeocodingApi',
    description: 'Unified forward/reverse/place-ID geocoder (exactly one mode).',
    tool: geocodingApi,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['geocode', 'address'],
  },
  {
    name: 'googleMapsComputeRouteMatrix',
    description: 'Computes distance/duration for every origin×destination pair.',
    tool: computeRouteMatrix,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['eta', 'drive', 'distance'],
  },
  {
    name: 'googleMapsGetRoute',
    description: 'Computes routes with waypoints and travel preferences.',
    tool: getRoute,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['directions', 'route', 'drive'],
  },
  {
    name: 'googleMapsCreateTilesSession',
    description: 'Creates a session token for 2D tiles and Street View.',
    tool: createTilesSession,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['tile', 'streetview'],
  },
  {
    name: 'googleMapsGet2dTile',
    description: 'Downloads one 2D tile image by zoom/column/row.',
    tool: get2dTile,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['tile', 'map'],
  },
  {
    name: 'googleMapsGet3dTilesRoot',
    description: 'Gets the photorealistic 3D tileset root for renderers.',
    tool: get3dTilesRoot,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['tile', '3d'],
  },
  {
    name: 'googleMapsGeolocateDevice',
    description: 'Estimates device location from cell towers and WiFi.',
    tool: geolocateDevice,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['gps', 'locate', 'position'],
  },
  {
    name: 'googleMapsGetTimeZone',
    description: 'Gets DST-aware time zone info for coordinates.',
    tool: getTimeZone,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['timezone', 'local'],
  },
  {
    name: 'googleMapsEmbedGoogleMap',
    description: 'Builds a public Maps Embed URL + iframe (API key only, no call made).',
    tool: embedGoogleMap,
    scope: 'read' as const,
    keywords: ['iframe', 'widget'],
  },
  {
    name: 'googleMapsLookupAerialVideo',
    description: 'Looks up an aerial video by address or video ID.',
    tool: lookupAerialVideo,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['drone', 'flyover'],
  },
  {
    name: 'googleMapsRenderAerialVideo',
    description: 'Starts an aerial video render for a US address.',
    tool: renderAerialVideo,
    requiredAuth: auth,
    scope: 'write' as const,
    keywords: ['drone', 'cinematic'],
  },
];
