// @ts-nocheck
import { cleanTombstones, deleteSeries, reloadConfig, shutdownServer, snapshot } from './admin.js';
import {
  findSeries,
  labelNames,
  labelValues,
  metricMetadata,
  searchLabelNames,
  searchLabelValues,
  searchMetricNames,
  targetMetadata,
} from './discovery.js';
import { formatQuery, instantQuery, parseQuery, queryExemplars, rangeQuery } from './query.js';
import {
  alertmanagers,
  alerts,
  rules,
  scrapePools,
  targetRelabelSteps,
  targets,
} from './targets.js';
import {
  federate,
  healthy,
  listNotifications,
  liveNotifications,
  ready,
  statusBuildInfo,
  statusConfig,
  statusFlags,
  statusRuntimeInfo,
  statusSelfMetrics,
  statusTsdb,
  statusTsdbBlocks,
  statusWalReplay,
} from './status.js';

export {
  instantQuery,
  rangeQuery,
  formatQuery,
  parseQuery,
  queryExemplars,
  findSeries,
  labelNames,
  labelValues,
  searchMetricNames,
  searchLabelNames,
  searchLabelValues,
  targetMetadata,
  metricMetadata,
  scrapePools,
  targets,
  targetRelabelSteps,
  rules,
  alerts,
  alertmanagers,
  statusConfig,
  statusFlags,
  statusRuntimeInfo,
  statusBuildInfo,
  statusTsdb,
  statusTsdbBlocks,
  statusWalReplay,
  statusSelfMetrics,
  healthy,
  ready,
  federate,
  deleteSeries,
  cleanTombstones,
  snapshot,
  reloadConfig,
  shutdownServer,
  listNotifications,
  liveNotifications,
};

const auth = 'prometheusCredentials' as const;

type Scope = 'read' | 'write' | 'delete';
function entry(
  name: string,
  description: string,
  toolRef: any,
  scope: Scope,
  keywords: string[] = [],
): {
  name: string;
  description: string;
  tool: any;
  requiredAuth: typeof auth;
  scope: Scope;
  keywords: string[];
} {
  return { name, description, tool: toolRef, requiredAuth: auth, scope, keywords };
}

export const prometheusTools = [
  entry(
    'prometheusInstantQuery',
    'Evaluates a PromQL expression at one instant.',
    instantQuery,
    'read',
    ['promql', 'query', 'queries', 'metrics', 'instant'],
  ),
  entry(
    'prometheusRangeQuery',
    'Evaluates a PromQL expression over a time range.',
    rangeQuery,
    'read',
    ['promql', 'query', 'range', 'metrics', 'graph'],
  ),
  entry('prometheusFormatQuery', 'Prettifies a PromQL expression.', formatQuery, 'read', [
    'promql',
    'format',
    'pretty',
    'query',
  ]),
  entry(
    'prometheusParseQuery',
    'Parses PromQL into a JSON AST (experimental).',
    parseQuery,
    'read',
    ['promql', 'parse', 'ast', 'query'],
  ),
  entry(
    'prometheusQueryExemplars',
    'Returns exemplars for a query over a range (experimental).',
    queryExemplars,
    'read',
    ['promql', 'exemplar', 'trace', 'query'],
  ),
  entry('prometheusFindSeries', 'Lists series matching label selectors.', findSeries, 'read', [
    'series',
    'metric',
    'metrics',
    'label',
    'labels',
  ]),
  entry('prometheusLabelNames', 'Lists label names, optionally scoped.', labelNames, 'read', [
    'label',
    'metric',
    'metrics',
  ]),
  entry('prometheusLabelValues', 'Lists values for a label name.', labelValues, 'read', [
    'label',
    'value',
    'values',
    'metric',
  ]),
  entry(
    'prometheusSearchMetricNames',
    'Streams metric-name autocomplete (NDJSON, experimental).',
    searchMetricNames,
    'read',
    ['metric', 'autocomplete', 'search', 'promql'],
  ),
  entry(
    'prometheusSearchLabelNames',
    'Streams label-name autocomplete (NDJSON, experimental).',
    searchLabelNames,
    'read',
    ['label', 'autocomplete', 'search'],
  ),
  entry(
    'prometheusSearchLabelValues',
    'Streams label-value autocomplete (NDJSON, experimental).',
    searchLabelValues,
    'read',
    ['label', 'value', 'autocomplete', 'search'],
  ),
  entry(
    'prometheusTargetMetadata',
    'Returns metric metadata scraped from targets (experimental).',
    targetMetadata,
    'read',
    ['metric', 'target', 'targets', 'scrape', 'metadata'],
  ),
  entry(
    'prometheusMetricMetadata',
    'Returns metric metadata without target info (experimental).',
    metricMetadata,
    'read',
    ['metric', 'metrics', 'metadata', 'help', 'type'],
  ),
  entry('prometheusScrapePools', 'Lists configured scrape pool names.', scrapePools, 'read', [
    'scrape',
    'target',
    'targets',
    'pool',
  ]),
  entry('prometheusTargets', 'Returns scrape target discovery state.', targets, 'read', [
    'target',
    'scrape',
    'discovery',
    'monitor',
    'up',
  ]),
  entry(
    'prometheusTargetRelabelSteps',
    'Shows relabeling steps for a target label set (experimental).',
    targetRelabelSteps,
    'read',
    ['relabel', 'target', 'label', 'scrape'],
  ),
  entry('prometheusRules', 'Lists alerting/recording rules with active alerts.', rules, 'read', [
    'rule',
    'alert',
    'alerts',
    'alerting',
    'recording',
  ]),
  entry('prometheusAlerts', 'Lists all active alerts.', alerts, 'read', [
    'alert',
    'alerting',
    'firing',
    'rule',
  ]),
  entry('prometheusAlertmanagers', 'Returns Alertmanager discovery state.', alertmanagers, 'read', [
    'alertmanager',
    'alert',
    'alerts',
    'notify',
    'notification',
  ]),
  entry(
    'prometheusStatusConfig',
    'Returns the loaded server config as YAML.',
    statusConfig,
    'read',
    ['config', 'server', 'status'],
  ),
  entry('prometheusStatusFlags', 'Returns server startup flag values.', statusFlags, 'read', [
    'flag',
    'flags',
    'config',
    'server',
  ]),
  entry(
    'prometheusStatusRuntimeInfo',
    'Returns runtime info (uptime, series, retention).',
    statusRuntimeInfo,
    'read',
    ['status', 'uptime', 'server', 'runtime', 'retention'],
  ),
  entry(
    'prometheusStatusBuildInfo',
    'Returns build info (version, revision).',
    statusBuildInfo,
    'read',
    ['version', 'build', 'server', 'status'],
  ),
  entry('prometheusStatusTsdb', 'Returns TSDB cardinality stats.', statusTsdb, 'read', [
    'tsdb',
    'storage',
    'series',
    'status',
    'cardinality',
  ]),
  entry(
    'prometheusStatusTsdbBlocks',
    'Lists loaded TSDB blocks (experimental).',
    statusTsdbBlocks,
    'read',
    ['tsdb', 'block', 'blocks', 'storage'],
  ),
  entry('prometheusStatusWalReplay', 'Returns WAL replay progress.', statusWalReplay, 'read', [
    'wal',
    'replay',
    'storage',
    'status',
  ]),
  entry(
    'prometheusStatusSelfMetrics',
    'Returns internal metrics as JSON (experimental).',
    statusSelfMetrics,
    'read',
    ['metric', 'internal', 'status'],
  ),
  entry('prometheusHealthy', 'Liveness check (/-/healthy).', healthy, 'read', [
    'health',
    'healthy',
    'liveness',
    'up',
    'status',
  ]),
  entry('prometheusReady', 'Readiness check (/-/ready).', ready, 'read', [
    'health',
    'readiness',
    'ready',
    'up',
    'status',
  ]),
  entry(
    'prometheusFederate',
    'Federation endpoint returning series in exposition format.',
    federate,
    'read',
    ['federation', 'federate', 'scrape', 'metrics'],
  ),
  entry(
    'prometheusDeleteSeries',
    'Deletes series via tombstones (admin API flag required).',
    deleteSeries,
    'delete',
    ['series', 'delete', 'admin', 'metric', 'drop'],
  ),
  entry(
    'prometheusCleanTombstones',
    'Purges tombstoned data from disk (admin API flag required).',
    cleanTombstones,
    'delete',
    ['tombstone', 'admin', 'storage', 'cleanup'],
  ),
  entry(
    'prometheusSnapshot',
    'Creates a TSDB snapshot for backups (admin API flag required).',
    snapshot,
    'write',
    ['snapshot', 'backup', 'admin', 'tsdb'],
  ),
  entry(
    'prometheusListNotifications',
    'Lists current UI notifications.',
    listNotifications,
    'read',
    ['notification', 'notifications', 'ui', 'alert'],
  ),
  entry(
    'prometheusLiveNotifications',
    'Collects live UI notifications over SSE, time-boxed.',
    liveNotifications,
    'read',
    ['notification', 'ui', 'alert', 'sse'],
  ),
  entry(
    'prometheusReloadConfig',
    'Reloads config and rule files (lifecycle flag required).',
    reloadConfig,
    'write',
    ['reload', 'config', 'admin', 'sighup'],
  ),
  entry(
    'prometheusShutdownServer',
    'Graceful server shutdown (lifecycle flag required).',
    shutdownServer,
    'delete',
    ['shutdown', 'admin', 'stop', 'server'],
  ),
];
