// @ts-nocheck
import { cleanTombstones, deleteSeries, reloadConfig, shutdownServer, snapshot } from './admin.js';
import {
    findSeries,
    labelNames,
    labelValues,
    metricMetadata,
    searchLabelNames,
    searchLabelValues,
    searchMetricNames,
    targetMetadata,
} from './discovery.js';
import { formatQuery, instantQuery, parseQuery, queryExemplars, rangeQuery } from './query.js';
import {
    alertmanagers,
    alerts,
    rules,
    scrapePools,
    targetRelabelSteps,
    targets,
} from './targets.js';
import {
    federate,
    healthy,
    listNotifications,
    liveNotifications,
    ready,
    statusBuildInfo,
    statusConfig,
    statusFlags,
    statusRuntimeInfo,
    statusSelfMetrics,
    statusTsdb,
    statusTsdbBlocks,
    statusWalReplay,
} from './status.js';

export {
    instantQuery,
    rangeQuery,
    formatQuery,
    parseQuery,
    queryExemplars,
    findSeries,
    labelNames,
    labelValues,
    searchMetricNames,
    searchLabelNames,
    searchLabelValues,
    targetMetadata,
    metricMetadata,
    scrapePools,
    targets,
    targetRelabelSteps,
    rules,
    alerts,
    alertmanagers,
    statusConfig,
    statusFlags,
    statusRuntimeInfo,
    statusBuildInfo,
    statusTsdb,
    statusTsdbBlocks,
    statusWalReplay,
    statusSelfMetrics,
    healthy,
    ready,
    federate,
    deleteSeries,
    cleanTombstones,
    snapshot,
    reloadConfig,
    shutdownServer,
    listNotifications,
    liveNotifications,
};

const auth = 'prometheusCredentials' as const;

type Scope = 'read' | 'write' | 'delete';
function entry(name: string, description: string, toolRef: any, scope: Scope): { name: string; description: string; tool: any; requiredAuth: typeof auth; scope: Scope } {
    return { name, description, tool: toolRef, requiredAuth: auth, scope };
}

export const prometheusTools = [
    entry('prometheusInstantQuery', 'Evaluates a PromQL expression at one instant.', instantQuery, 'read'),
    entry('prometheusRangeQuery', 'Evaluates a PromQL expression over a time range.', rangeQuery, 'read'),
    entry('prometheusFormatQuery', 'Prettifies a PromQL expression.', formatQuery, 'read'),
    entry('prometheusParseQuery', 'Parses PromQL into a JSON AST (experimental).', parseQuery, 'read'),
    entry('prometheusQueryExemplars', 'Returns exemplars for a query over a range (experimental).', queryExemplars, 'read'),
    entry('prometheusFindSeries', 'Lists series matching label selectors.', findSeries, 'read'),
    entry('prometheusLabelNames', 'Lists label names, optionally scoped.', labelNames, 'read'),
    entry('prometheusLabelValues', 'Lists values for a label name.', labelValues, 'read'),
    entry('prometheusSearchMetricNames', 'Streams metric-name autocomplete (NDJSON, experimental).', searchMetricNames, 'read'),
    entry('prometheusSearchLabelNames', 'Streams label-name autocomplete (NDJSON, experimental).', searchLabelNames, 'read'),
    entry('prometheusSearchLabelValues', 'Streams label-value autocomplete (NDJSON, experimental).', searchLabelValues, 'read'),
    entry('prometheusTargetMetadata', 'Returns metric metadata scraped from targets (experimental).', targetMetadata, 'read'),
    entry('prometheusMetricMetadata', 'Returns metric metadata without target info (experimental).', metricMetadata, 'read'),
    entry('prometheusScrapePools', 'Lists configured scrape pool names.', scrapePools, 'read'),
    entry('prometheusTargets', 'Returns scrape target discovery state.', targets, 'read'),
    entry('prometheusTargetRelabelSteps', 'Shows relabeling steps for a target label set (experimental).', targetRelabelSteps, 'read'),
    entry('prometheusRules', 'Lists alerting/recording rules with active alerts.', rules, 'read'),
    entry('prometheusAlerts', 'Lists all active alerts.', alerts, 'read'),
    entry('prometheusAlertmanagers', 'Returns Alertmanager discovery state.', alertmanagers, 'read'),
    entry('prometheusStatusConfig', 'Returns the loaded server config as YAML.', statusConfig, 'read'),
    entry('prometheusStatusFlags', 'Returns server startup flag values.', statusFlags, 'read'),
    entry('prometheusStatusRuntimeInfo', 'Returns runtime info (uptime, series, retention).', statusRuntimeInfo, 'read'),
    entry('prometheusStatusBuildInfo', 'Returns build info (version, revision).', statusBuildInfo, 'read'),
    entry('prometheusStatusTsdb', 'Returns TSDB cardinality stats.', statusTsdb, 'read'),
    entry('prometheusStatusTsdbBlocks', 'Lists loaded TSDB blocks (experimental).', statusTsdbBlocks, 'read'),
    entry('prometheusStatusWalReplay', 'Returns WAL replay progress.', statusWalReplay, 'read'),
    entry('prometheusStatusSelfMetrics', 'Returns internal metrics as JSON (experimental).', statusSelfMetrics, 'read'),
    entry('prometheusHealthy', 'Liveness check (/-/healthy).', healthy, 'read'),
    entry('prometheusReady', 'Readiness check (/-/ready).', ready, 'read'),
    entry('prometheusFederate', 'Federation endpoint returning series in exposition format.', federate, 'read'),
    entry('prometheusDeleteSeries', 'Deletes series via tombstones (admin API flag required).', deleteSeries, 'delete'),
    entry('prometheusCleanTombstones', 'Purges tombstoned data from disk (admin API flag required).', cleanTombstones, 'delete'),
    entry('prometheusSnapshot', 'Creates a TSDB snapshot for backups (admin API flag required).', snapshot, 'write'),
    entry('prometheusListNotifications', 'Lists current UI notifications.', listNotifications, 'read'),
    entry('prometheusLiveNotifications', 'Collects live UI notifications over SSE, time-boxed.', liveNotifications, 'read'),
    entry('prometheusReloadConfig', 'Reloads config and rule files (lifecycle flag required).', reloadConfig, 'write'),
    entry('prometheusShutdownServer', 'Graceful server shutdown (lifecycle flag required).', shutdownServer, 'delete'),
];
