// @ts-nocheck
import {
  kafkaListClusters,
  kafkaGetCluster,
  kafkaListTopics,
  kafkaGetTopic,
  kafkaCreateTopic,
  kafkaIncreaseTopicPartitions,
  kafkaDeleteTopic,
  kafkaListTopicConfigs,
  kafkaGetTopicConfig,
  kafkaAlterTopicConfigs,
  kafkaUpdateTopicConfig,
  kafkaDeleteTopicConfig,
  kafkaListPartitions,
  kafkaGetPartition,
  kafkaGetPartitionOffsets,
  kafkaProduceRecord,
  kafkaProduceRecordsBatch,
  kafkaListBrokers,
  kafkaGetBroker,
  kafkaListBrokerConfigs,
  kafkaGetBrokerConfig,
  kafkaAlterBrokerConfigs,
} from './topics.js';
import {
  kafkaListConsumerGroups,
  kafkaGetConsumerGroup,
  kafkaListConsumers,
  kafkaGetConsumer,
  kafkaGetConsumerLagSummary,
  kafkaListConsumerLags,
  kafkaGetConsumerLag,
  kafkaListConsumerAssignments,
  kafkaGetConsumerAssignment,
  kafkaListAcls,
  kafkaCreateAcl,
  kafkaCreateAclsBatch,
  kafkaDeleteAcls,
} from './consumers.js';
import {
  kafkaListEnvironments,
  kafkaGetEnvironment,
  kafkaCreateEnvironment,
  kafkaUpdateEnvironment,
  kafkaDeleteEnvironment,
  kafkaListManagedClusters,
  kafkaGetManagedCluster,
  kafkaCreateManagedCluster,
  kafkaUpdateManagedCluster,
  kafkaDeleteManagedCluster,
  kafkaListApiKeys,
  kafkaGetApiKey,
  kafkaCreateApiKey,
  kafkaUpdateApiKey,
  kafkaDeleteApiKey,
  kafkaListServiceAccounts,
  kafkaGetServiceAccount,
  kafkaCreateServiceAccount,
  kafkaUpdateServiceAccount,
  kafkaDeleteServiceAccount,
} from './controlplane.js';
import {
  kafkaListSubjects,
  kafkaListSubjectVersions,
  kafkaGetSchemaVersion,
  kafkaGetSchemaById,
  kafkaRegisterSchema,
  kafkaLookupSchema,
  kafkaDeleteSubject,
  kafkaDeleteSchemaVersion,
  kafkaGetGlobalCompatibility,
  kafkaUpdateGlobalCompatibility,
  kafkaGetSubjectCompatibility,
  kafkaUpdateSubjectCompatibility,
  kafkaTestCompatibility,
} from './schemas.js';

export {
  kafkaListClusters,
  kafkaGetCluster,
  kafkaListTopics,
  kafkaGetTopic,
  kafkaCreateTopic,
  kafkaIncreaseTopicPartitions,
  kafkaDeleteTopic,
  kafkaListTopicConfigs,
  kafkaGetTopicConfig,
  kafkaAlterTopicConfigs,
  kafkaUpdateTopicConfig,
  kafkaDeleteTopicConfig,
  kafkaListPartitions,
  kafkaGetPartition,
  kafkaGetPartitionOffsets,
  kafkaProduceRecord,
  kafkaProduceRecordsBatch,
  kafkaListBrokers,
  kafkaGetBroker,
  kafkaListBrokerConfigs,
  kafkaGetBrokerConfig,
  kafkaAlterBrokerConfigs,
  kafkaListConsumerGroups,
  kafkaGetConsumerGroup,
  kafkaListConsumers,
  kafkaGetConsumer,
  kafkaGetConsumerLagSummary,
  kafkaListConsumerLags,
  kafkaGetConsumerLag,
  kafkaListConsumerAssignments,
  kafkaGetConsumerAssignment,
  kafkaListAcls,
  kafkaCreateAcl,
  kafkaCreateAclsBatch,
  kafkaDeleteAcls,
  kafkaListEnvironments,
  kafkaGetEnvironment,
  kafkaCreateEnvironment,
  kafkaUpdateEnvironment,
  kafkaDeleteEnvironment,
  kafkaListManagedClusters,
  kafkaGetManagedCluster,
  kafkaCreateManagedCluster,
  kafkaUpdateManagedCluster,
  kafkaDeleteManagedCluster,
  kafkaListApiKeys,
  kafkaGetApiKey,
  kafkaCreateApiKey,
  kafkaUpdateApiKey,
  kafkaDeleteApiKey,
  kafkaListServiceAccounts,
  kafkaGetServiceAccount,
  kafkaCreateServiceAccount,
  kafkaUpdateServiceAccount,
  kafkaDeleteServiceAccount,
  kafkaListSubjects,
  kafkaListSubjectVersions,
  kafkaGetSchemaVersion,
  kafkaGetSchemaById,
  kafkaRegisterSchema,
  kafkaLookupSchema,
  kafkaDeleteSubject,
  kafkaDeleteSchemaVersion,
  kafkaGetGlobalCompatibility,
  kafkaUpdateGlobalCompatibility,
  kafkaGetSubjectCompatibility,
  kafkaUpdateSubjectCompatibility,
  kafkaTestCompatibility,
};

const AUTH = 'kafkaCredentials' as const;

export const kafkaTools = [
  {
    name: 'kafkaListClusters',
    description: 'List Kafka clusters on the REST endpoint.',
    tool: kafkaListClusters,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['connectivity', 'health'],
  },
  {
    name: 'kafkaGetCluster',
    description: 'Get the Kafka cluster resource.',
    tool: kafkaGetCluster,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['fetch', 'info'],
  },
  {
    name: 'kafkaListTopics',
    description: 'List topics on the cluster.',
    tool: kafkaListTopics,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['streams', 'events'],
  },
  {
    name: 'kafkaGetTopic',
    description: 'Get one topic with partitions and configs.',
    tool: kafkaGetTopic,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['stream', 'fetch'],
  },
  {
    name: 'kafkaCreateTopic',
    description: 'Create a topic with partitions and configs.',
    tool: kafkaCreateTopic,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['stream', 'new'],
  },
  {
    name: 'kafkaIncreaseTopicPartitions',
    description: 'Increase a topic partition count.',
    tool: kafkaIncreaseTopicPartitions,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['scale', 'throughput'],
  },
  {
    name: 'kafkaDeleteTopic',
    description: 'Delete a topic and all its data.',
    tool: kafkaDeleteTopic,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['remove', 'purge'],
  },
  {
    name: 'kafkaListTopicConfigs',
    description: 'List all config parameters of a topic.',
    tool: kafkaListTopicConfigs,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['retention', 'settings'],
  },
  {
    name: 'kafkaGetTopicConfig',
    description: 'Get one topic config parameter.',
    tool: kafkaGetTopicConfig,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['retention', 'fetch'],
  },
  {
    name: 'kafkaAlterTopicConfigs',
    description: 'Set or delete topic configs in batch.',
    tool: kafkaAlterTopicConfigs,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['retention', 'tune'],
  },
  {
    name: 'kafkaUpdateTopicConfig',
    description: 'Set a single topic config value.',
    tool: kafkaUpdateTopicConfig,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['retention', 'edit'],
  },
  {
    name: 'kafkaDeleteTopicConfig',
    description: 'Reset a topic config to default.',
    tool: kafkaDeleteTopicConfig,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['retention', 'reset'],
  },
  {
    name: 'kafkaListPartitions',
    description: 'List partitions of a topic.',
    tool: kafkaListPartitions,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['shards', 'leaders'],
  },
  {
    name: 'kafkaGetPartition',
    description: 'Get one partition with leader and replicas.',
    tool: kafkaGetPartition,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['shard', 'fetch'],
  },
  {
    name: 'kafkaGetPartitionOffsets',
    description: 'Get beginning/end offsets of a partition.',
    tool: kafkaGetPartitionOffsets,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['backlog', 'watermarks'],
  },
  {
    name: 'kafkaProduceRecord',
    description: 'Produce a single record to a topic.',
    tool: kafkaProduceRecord,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['publish', 'send', 'event'],
  },
  {
    name: 'kafkaProduceRecordsBatch',
    description: 'Produce a batch of records to a topic.',
    tool: kafkaProduceRecordsBatch,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['publish', 'bulk', 'events'],
  },
  {
    name: 'kafkaListBrokers',
    description: 'List brokers of the cluster.',
    tool: kafkaListBrokers,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['nodes', 'servers'],
  },
  {
    name: 'kafkaGetBroker',
    description: 'Get one broker with host and rack.',
    tool: kafkaGetBroker,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['node', 'fetch'],
  },
  {
    name: 'kafkaListBrokerConfigs',
    description: 'List dynamic broker configs.',
    tool: kafkaListBrokerConfigs,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['settings', 'tune'],
  },
  {
    name: 'kafkaGetBrokerConfig',
    description: 'Get one dynamic broker config.',
    tool: kafkaGetBrokerConfig,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['setting', 'fetch'],
  },
  {
    name: 'kafkaAlterBrokerConfigs',
    description: 'Set or delete broker configs in batch.',
    tool: kafkaAlterBrokerConfigs,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['settings', 'tune'],
  },
  {
    name: 'kafkaListConsumerGroups',
    description: 'List consumer groups.',
    tool: kafkaListConsumerGroups,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['subscribers', 'readers'],
  },
  {
    name: 'kafkaGetConsumerGroup',
    description: 'Get one consumer group with state.',
    tool: kafkaGetConsumerGroup,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['subscriber', 'fetch'],
  },
  {
    name: 'kafkaListConsumers',
    description: 'List active consumers of a group.',
    tool: kafkaListConsumers,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['members', 'clients'],
  },
  {
    name: 'kafkaGetConsumer',
    description: 'Get one consumer member.',
    tool: kafkaGetConsumer,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['member', 'fetch'],
  },
  {
    name: 'kafkaGetConsumerLagSummary',
    description: 'Get lag summary of a group.',
    tool: kafkaGetConsumerLagSummary,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['behind', 'stuck', 'delay'],
  },
  {
    name: 'kafkaListConsumerLags',
    description: 'List per-topic lags of a group.',
    tool: kafkaListConsumerLags,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['behind', 'offsets'],
  },
  {
    name: 'kafkaGetConsumerLag',
    description: 'Get lag for one topic partition.',
    tool: kafkaGetConsumerLag,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['behind', 'offset'],
  },
  {
    name: 'kafkaListConsumerAssignments',
    description: 'List partition assignments of a consumer.',
    tool: kafkaListConsumerAssignments,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['partitions', 'rebalance'],
  },
  {
    name: 'kafkaGetConsumerAssignment',
    description: 'Get one partition assignment of a consumer.',
    tool: kafkaGetConsumerAssignment,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['partition', 'fetch'],
  },
  {
    name: 'kafkaListAcls',
    description: 'List ACLs with optional filters.',
    tool: kafkaListAcls,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['permissions', 'audit'],
  },
  {
    name: 'kafkaCreateAcl',
    description: 'Create one ACL entry.',
    tool: kafkaCreateAcl,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['permissions', 'grant'],
  },
  {
    name: 'kafkaCreateAclsBatch',
    description: 'Create multiple ACL entries.',
    tool: kafkaCreateAclsBatch,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['permissions', 'bulk'],
  },
  {
    name: 'kafkaDeleteAcls',
    description: 'Delete ACLs matching criteria.',
    tool: kafkaDeleteAcls,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['permissions', 'revoke'],
  },
  {
    name: 'kafkaListEnvironments',
    description: 'List Confluent Cloud environments.',
    tool: kafkaListEnvironments,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['workspaces', 'org'],
  },
  {
    name: 'kafkaGetEnvironment',
    description: 'Get one environment.',
    tool: kafkaGetEnvironment,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['workspace', 'fetch'],
  },
  {
    name: 'kafkaCreateEnvironment',
    description: 'Create a Confluent Cloud environment.',
    tool: kafkaCreateEnvironment,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['workspace', 'setup'],
  },
  {
    name: 'kafkaUpdateEnvironment',
    description: 'Rename an environment.',
    tool: kafkaUpdateEnvironment,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['workspace', 'rename'],
  },
  {
    name: 'kafkaDeleteEnvironment',
    description: 'Delete an empty environment.',
    tool: kafkaDeleteEnvironment,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['workspace', 'remove'],
  },
  {
    name: 'kafkaListManagedClusters',
    description: 'List managed Kafka clusters in an environment.',
    tool: kafkaListManagedClusters,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['provisioned', 'lkc'],
  },
  {
    name: 'kafkaGetManagedCluster',
    description: 'Get a managed cluster with endpoints.',
    tool: kafkaGetManagedCluster,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['provisioned', 'fetch'],
  },
  {
    name: 'kafkaCreateManagedCluster',
    description: 'Provision a Kafka cluster.',
    tool: kafkaCreateManagedCluster,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['provision', 'deploy'],
  },
  {
    name: 'kafkaUpdateManagedCluster',
    description: 'Rename, upgrade, or scale a cluster.',
    tool: kafkaUpdateManagedCluster,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['resize', 'upgrade'],
  },
  {
    name: 'kafkaDeleteManagedCluster',
    description: 'Delete a managed cluster.',
    tool: kafkaDeleteManagedCluster,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['decommission', 'remove'],
  },
  {
    name: 'kafkaListApiKeys',
    description: 'List API keys (metadata only).',
    tool: kafkaListApiKeys,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['credentials', 'audit'],
  },
  {
    name: 'kafkaGetApiKey',
    description: 'Get one API key metadata.',
    tool: kafkaGetApiKey,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['credential', 'fetch'],
  },
  {
    name: 'kafkaCreateApiKey',
    description: 'Create an API key (secret shown once).',
    tool: kafkaCreateApiKey,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['credential', 'generate'],
  },
  {
    name: 'kafkaUpdateApiKey',
    description: 'Update an API key description.',
    tool: kafkaUpdateApiKey,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['credential', 'edit'],
  },
  {
    name: 'kafkaDeleteApiKey',
    description: 'Delete (revoke) an API key.',
    tool: kafkaDeleteApiKey,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['credential', 'revoke'],
  },
  {
    name: 'kafkaListServiceAccounts',
    description: 'List service accounts.',
    tool: kafkaListServiceAccounts,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['principals', 'bots'],
  },
  {
    name: 'kafkaGetServiceAccount',
    description: 'Get one service account.',
    tool: kafkaGetServiceAccount,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['principal', 'fetch'],
  },
  {
    name: 'kafkaCreateServiceAccount',
    description: 'Create a service account.',
    tool: kafkaCreateServiceAccount,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['principal', 'provision'],
  },
  {
    name: 'kafkaUpdateServiceAccount',
    description: 'Update a service account.',
    tool: kafkaUpdateServiceAccount,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['principal', 'edit'],
  },
  {
    name: 'kafkaDeleteServiceAccount',
    description: 'Delete a service account.',
    tool: kafkaDeleteServiceAccount,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['principal', 'remove'],
  },
  {
    name: 'kafkaListSubjects',
    description: 'List Schema Registry subjects.',
    tool: kafkaListSubjects,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['schemas', 'avro'],
  },
  {
    name: 'kafkaListSubjectVersions',
    description: 'List versions under a subject.',
    tool: kafkaListSubjectVersions,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['schema', 'revisions'],
  },
  {
    name: 'kafkaGetSchemaVersion',
    description: 'Get one schema version.',
    tool: kafkaGetSchemaVersion,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['schema', 'fetch'],
  },
  {
    name: 'kafkaGetSchemaById',
    description: 'Get a schema by global ID.',
    tool: kafkaGetSchemaById,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['schema', 'lookup'],
  },
  {
    name: 'kafkaRegisterSchema',
    description: 'Register a schema version under a subject.',
    tool: kafkaRegisterSchema,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['avro', 'publish', 'evolution'],
  },
  {
    name: 'kafkaLookupSchema',
    description: 'Look up subject/version for a schema.',
    tool: kafkaLookupSchema,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['avro', 'find'],
  },
  {
    name: 'kafkaDeleteSubject',
    description: 'Soft-delete a subject.',
    tool: kafkaDeleteSubject,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['schema', 'remove'],
  },
  {
    name: 'kafkaDeleteSchemaVersion',
    description: 'Soft-delete one schema version.',
    tool: kafkaDeleteSchemaVersion,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['schema', 'remove'],
  },
  {
    name: 'kafkaGetGlobalCompatibility',
    description: 'Get global compatibility level.',
    tool: kafkaGetGlobalCompatibility,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['evolution', 'policy'],
  },
  {
    name: 'kafkaUpdateGlobalCompatibility',
    description: 'Set global compatibility level.',
    tool: kafkaUpdateGlobalCompatibility,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['evolution', 'policy'],
  },
  {
    name: 'kafkaGetSubjectCompatibility',
    description: 'Get subject compatibility level.',
    tool: kafkaGetSubjectCompatibility,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['evolution', 'fetch'],
  },
  {
    name: 'kafkaUpdateSubjectCompatibility',
    description: 'Set subject compatibility level.',
    tool: kafkaUpdateSubjectCompatibility,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['evolution', 'policy'],
  },
  {
    name: 'kafkaTestCompatibility',
    description: 'Test a candidate schema for compatibility.',
    tool: kafkaTestCompatibility,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['evolution', 'validate', 'dry-run'],
  },
];
