// @ts-nocheck
import {
    postmanCreateACollection,
    postmanGetAllCollections,
    postmanDeleteACollection,
    postmanDuplicateACollection,
    postmanGetDuplicationTaskStatus,
    postmanForkCollection,
    postmanGetCollectionForks,
    postmanGetAllForkedCollections,
    postmanPullSourceChangesIntoFork,
    postmanGetSourceCollectionStatus,
    postmanReplaceCollectionDataAsynchronously,
    postmanGetAsyncCollectionUpdateStatus,
    postmanTransferFolders,
    postmanTransformCollectionToOpenApi,
    postmanUpdateCollectionProperties,
    postmanGetCollectionRoles,
    postmanGetCollectionAccessKeys,
} from './collections.js';
import {
    postmanCreateAFolder,
    postmanGetFolderInformation,
    postmanUpdateAFolder,
    postmanDeleteAFolder,
    postmanCreateRequestInCollection,
    postmanGetRequestInformation,
    postmanUpdateRequestInCollection,
    postmanCreateAResponse,
    postmanGetResponseInformation,
    postmanUpdateAResponse,
    postmanDeleteAResponse,
} from './items.js';
import {
    postmanGetCollectionPullRequests,
    postmanCreateAPullRequest,
    postmanUpdateAPullRequest,
    postmanReviewAPullRequest,
} from './pull_requests.js';
import {
    postmanCreateACollectionComment,
    postmanGetCollectionComments,
    postmanDeleteACollectionsComment,
    postmanGetApiComments,
    postmanUpdateAnApisComment,
    postmanDeleteAnApisComment,
    postmanCreateAFolderComment,
    postmanGetFolderComments,
    postmanUpdateAFoldersComment,
    postmanDeleteAFoldersComment,
    postmanCreateARequestComment,
    postmanGetRequestComments,
    postmanUpdateARequestsComment,
    postmanDeleteARequestsComment,
    postmanCreateAResponseComment,
    postmanGetResponseComments,
    postmanUpdateAResponsesComment,
    postmanDeleteAResponsesComment,
    postmanResolveACommentThread,
} from './comments.js';
import {
    postmanCreateAnEnvironment,
    postmanGetAllEnvironments,
    postmanGetAnEnvironment,
    postmanDeleteAnEnvironment,
    postmanReplaceAnEnvironmentsData,
    postmanUpdateAnEnvironment,
    postmanCreateEnvironmentFork,
    postmanGetEnvironmentForks,
    postmanMergeAForkedEnvironment,
} from './environments.js';
import {
    postmanCreateAWorkspace,
    postmanGetAllWorkspaces,
    postmanGetWorkspaceDetails,
    postmanUpdateAWorkspace,
    postmanDeleteAWorkspace,
    postmanGetWorkspaceActivityFeed,
    postmanGetWorkspaceRoles,
    postmanGetWorkspaceGlobalVariables,
    postmanUpdateWorkspaceGlobalVariables,
} from './workspaces.js';
import {
    postmanCreateAnApi,
    postmanGetAllApis,
    postmanGetApiInformation,
    postmanUpdateAnApi,
    postmanDeleteAnApi,
    postmanGetAllApiVersions,
    postmanGetApiVersion,
    postmanCreateApiSchema,
    postmanGetApiSchema,
    postmanGetSchemaFiles,
    postmanGetSchemaFileContents,
    postmanCreateOrUpdateASchemaFile,
    postmanDeleteASchemaFile,
    postmanSyncCollectionWithSchema,
    postmanCreateApiVersionRelations,
    postmanGetAllLinkedRelations,
    postmanGetUnclassifiedRelations,
} from './designs_and_apis.js';
import {
    postmanCreateASpec,
    postmanGetAllApiSpecifications,
    postmanGetApiSpecification,
    postmanDeleteASpec,
    postmanUpdateSpecProperties,
    postmanCreateSpecFile,
    postmanGetSpecFileContents,
    postmanUpdateSpecFile,
    postmanDeleteSpecFile,
    postmanGetSpecificationFiles,
    postmanGetSpecDefinition,
    postmanGetSpecsGeneratedCollections,
    postmanGenerateCollectionFromSpec,
    postmanGenerateSpecFromCollection,
    postmanGetGeneratedSpec,
    postmanSyncCollectionWithSpec,
    postmanSyncSpecWithCollection,
    postmanImportOpenApiSpecification,
} from './specs.js';
import {
    postmanCreateAMockServer,
    postmanGetAllMockServers,
    postmanUpdateAMockServer,
    postmanPublishAMockServer,
    postmanCreateMockServerResponse,
    postmanUpdateAServerResponse,
    postmanDeleteMockServerResponse,
    postmanCreateAMonitor,
    postmanGetAllMonitors,
    postmanGetMonitorInformation,
    postmanUpdateAMonitor,
    postmanDeleteMonitor,
    postmanRunAMonitor,
} from './mocks_and_tests.js';
import {
    postmanGetAllTeamUsers,
    postmanGetATeamUser,
    postmanGetAuthenticatedUser,
    postmanGetAllGroups,
    postmanGetResourceTypes,
    postmanGetServiceProviderConfiguration,
    postmanGetBillingAccountDetails,
    postmanListAccountInvoices,
} from './scim_users_teams.js';
import { postmanCreateAWebhook } from './webhooks.js';

export {
    postmanCreateACollection,
    postmanGetAllCollections,
    postmanDeleteACollection,
    postmanDuplicateACollection,
    postmanGetDuplicationTaskStatus,
    postmanForkCollection,
    postmanGetCollectionForks,
    postmanGetAllForkedCollections,
    postmanPullSourceChangesIntoFork,
    postmanGetSourceCollectionStatus,
    postmanReplaceCollectionDataAsynchronously,
    postmanGetAsyncCollectionUpdateStatus,
    postmanTransferFolders,
    postmanTransformCollectionToOpenApi,
    postmanUpdateCollectionProperties,
    postmanGetCollectionRoles,
    postmanGetCollectionAccessKeys,
    postmanCreateAFolder,
    postmanGetFolderInformation,
    postmanUpdateAFolder,
    postmanDeleteAFolder,
    postmanCreateRequestInCollection,
    postmanGetRequestInformation,
    postmanUpdateRequestInCollection,
    postmanCreateAResponse,
    postmanGetResponseInformation,
    postmanUpdateAResponse,
    postmanDeleteAResponse,
    postmanGetCollectionPullRequests,
    postmanCreateAPullRequest,
    postmanUpdateAPullRequest,
    postmanReviewAPullRequest,
    postmanCreateACollectionComment,
    postmanGetCollectionComments,
    postmanDeleteACollectionsComment,
    postmanGetApiComments,
    postmanUpdateAnApisComment,
    postmanDeleteAnApisComment,
    postmanCreateAFolderComment,
    postmanGetFolderComments,
    postmanUpdateAFoldersComment,
    postmanDeleteAFoldersComment,
    postmanCreateARequestComment,
    postmanGetRequestComments,
    postmanUpdateARequestsComment,
    postmanDeleteARequestsComment,
    postmanCreateAResponseComment,
    postmanGetResponseComments,
    postmanUpdateAResponsesComment,
    postmanDeleteAResponsesComment,
    postmanResolveACommentThread,
    postmanCreateAnEnvironment,
    postmanGetAllEnvironments,
    postmanGetAnEnvironment,
    postmanDeleteAnEnvironment,
    postmanReplaceAnEnvironmentsData,
    postmanUpdateAnEnvironment,
    postmanCreateEnvironmentFork,
    postmanGetEnvironmentForks,
    postmanMergeAForkedEnvironment,
    postmanCreateAWorkspace,
    postmanGetAllWorkspaces,
    postmanGetWorkspaceDetails,
    postmanUpdateAWorkspace,
    postmanDeleteAWorkspace,
    postmanGetWorkspaceActivityFeed,
    postmanGetWorkspaceRoles,
    postmanGetWorkspaceGlobalVariables,
    postmanUpdateWorkspaceGlobalVariables,
    postmanCreateAnApi,
    postmanGetAllApis,
    postmanGetApiInformation,
    postmanUpdateAnApi,
    postmanDeleteAnApi,
    postmanGetAllApiVersions,
    postmanGetApiVersion,
    postmanCreateApiSchema,
    postmanGetApiSchema,
    postmanGetSchemaFiles,
    postmanGetSchemaFileContents,
    postmanCreateOrUpdateASchemaFile,
    postmanDeleteASchemaFile,
    postmanSyncCollectionWithSchema,
    postmanCreateApiVersionRelations,
    postmanGetAllLinkedRelations,
    postmanGetUnclassifiedRelations,
    postmanCreateASpec,
    postmanGetAllApiSpecifications,
    postmanGetApiSpecification,
    postmanDeleteASpec,
    postmanUpdateSpecProperties,
    postmanCreateSpecFile,
    postmanGetSpecFileContents,
    postmanUpdateSpecFile,
    postmanDeleteSpecFile,
    postmanGetSpecificationFiles,
    postmanGetSpecDefinition,
    postmanGetSpecsGeneratedCollections,
    postmanGenerateCollectionFromSpec,
    postmanGenerateSpecFromCollection,
    postmanGetGeneratedSpec,
    postmanSyncCollectionWithSpec,
    postmanSyncSpecWithCollection,
    postmanImportOpenApiSpecification,
    postmanCreateAMockServer,
    postmanGetAllMockServers,
    postmanUpdateAMockServer,
    postmanPublishAMockServer,
    postmanCreateMockServerResponse,
    postmanUpdateAServerResponse,
    postmanDeleteMockServerResponse,
    postmanCreateAMonitor,
    postmanGetAllMonitors,
    postmanGetMonitorInformation,
    postmanUpdateAMonitor,
    postmanDeleteMonitor,
    postmanRunAMonitor,
    postmanGetAllTeamUsers,
    postmanGetATeamUser,
    postmanGetAuthenticatedUser,
    postmanGetAllGroups,
    postmanGetResourceTypes,
    postmanGetServiceProviderConfiguration,
    postmanGetBillingAccountDetails,
    postmanListAccountInvoices,
    postmanCreateAWebhook,
};

const authed = (tool: any) => ({ requiredAuth: 'postmanApiKey' as const });

export const postmanTools = [
    { name: 'postmanCreateACollection', description: postmanCreateACollection.description!, tool: postmanCreateACollection, ...authed(0), scope: 'write' as const },
    { name: 'postmanGetAllCollections', description: postmanGetAllCollections.description!, tool: postmanGetAllCollections, ...authed(0), scope: 'read' as const },
    { name: 'postmanDeleteACollection', description: postmanDeleteACollection.description!, tool: postmanDeleteACollection, ...authed(0), scope: 'delete' as const },
    { name: 'postmanDuplicateACollection', description: postmanDuplicateACollection.description!, tool: postmanDuplicateACollection, ...authed(0), scope: 'write' as const },
    { name: 'postmanGetDuplicationTaskStatus', description: postmanGetDuplicationTaskStatus.description!, tool: postmanGetDuplicationTaskStatus, ...authed(0), scope: 'read' as const },
    { name: 'postmanForkCollection', description: postmanForkCollection.description!, tool: postmanForkCollection, ...authed(0), scope: 'write' as const },
    { name: 'postmanGetCollectionForks', description: postmanGetCollectionForks.description!, tool: postmanGetCollectionForks, ...authed(0), scope: 'read' as const },
    { name: 'postmanGetAllForkedCollections', description: postmanGetAllForkedCollections.description!, tool: postmanGetAllForkedCollections, ...authed(0), scope: 'read' as const },
    { name: 'postmanPullSourceChangesIntoFork', description: postmanPullSourceChangesIntoFork.description!, tool: postmanPullSourceChangesIntoFork, ...authed(0), scope: 'write' as const },
    { name: 'postmanGetSourceCollectionStatus', description: postmanGetSourceCollectionStatus.description!, tool: postmanGetSourceCollectionStatus, ...authed(0), scope: 'read' as const },
    { name: 'postmanReplaceCollectionDataAsynchronously', description: postmanReplaceCollectionDataAsynchronously.description!, tool: postmanReplaceCollectionDataAsynchronously, ...authed(0), scope: 'write' as const },
    { name: 'postmanGetAsyncCollectionUpdateStatus', description: postmanGetAsyncCollectionUpdateStatus.description!, tool: postmanGetAsyncCollectionUpdateStatus, ...authed(0), scope: 'read' as const },
    { name: 'postmanTransferFolders', description: postmanTransferFolders.description!, tool: postmanTransferFolders, ...authed(0), scope: 'write' as const },
    { name: 'postmanTransformCollectionToOpenApi', description: postmanTransformCollectionToOpenApi.description!, tool: postmanTransformCollectionToOpenApi, ...authed(0), scope: 'read' as const },
    { name: 'postmanUpdateCollectionProperties', description: postmanUpdateCollectionProperties.description!, tool: postmanUpdateCollectionProperties, ...authed(0), scope: 'write' as const },
    { name: 'postmanGetCollectionRoles', description: postmanGetCollectionRoles.description!, tool: postmanGetCollectionRoles, ...authed(0), scope: 'read' as const },
    { name: 'postmanGetCollectionAccessKeys', description: postmanGetCollectionAccessKeys.description!, tool: postmanGetCollectionAccessKeys, ...authed(0), scope: 'read' as const },
    { name: 'postmanCreateAFolder', description: postmanCreateAFolder.description!, tool: postmanCreateAFolder, ...authed(0), scope: 'write' as const },
    { name: 'postmanGetFolderInformation', description: postmanGetFolderInformation.description!, tool: postmanGetFolderInformation, ...authed(0), scope: 'read' as const },
    { name: 'postmanUpdateAFolder', description: postmanUpdateAFolder.description!, tool: postmanUpdateAFolder, ...authed(0), scope: 'write' as const },
    { name: 'postmanDeleteAFolder', description: postmanDeleteAFolder.description!, tool: postmanDeleteAFolder, ...authed(0), scope: 'delete' as const },
    { name: 'postmanCreateRequestInCollection', description: postmanCreateRequestInCollection.description!, tool: postmanCreateRequestInCollection, ...authed(0), scope: 'write' as const },
    { name: 'postmanGetRequestInformation', description: postmanGetRequestInformation.description!, tool: postmanGetRequestInformation, ...authed(0), scope: 'read' as const },
    { name: 'postmanUpdateRequestInCollection', description: postmanUpdateRequestInCollection.description!, tool: postmanUpdateRequestInCollection, ...authed(0), scope: 'write' as const },
    { name: 'postmanCreateAResponse', description: postmanCreateAResponse.description!, tool: postmanCreateAResponse, ...authed(0), scope: 'write' as const },
    { name: 'postmanGetResponseInformation', description: postmanGetResponseInformation.description!, tool: postmanGetResponseInformation, ...authed(0), scope: 'read' as const },
    { name: 'postmanUpdateAResponse', description: postmanUpdateAResponse.description!, tool: postmanUpdateAResponse, ...authed(0), scope: 'write' as const },
    { name: 'postmanDeleteAResponse', description: postmanDeleteAResponse.description!, tool: postmanDeleteAResponse, ...authed(0), scope: 'delete' as const },
    { name: 'postmanGetCollectionPullRequests', description: postmanGetCollectionPullRequests.description!, tool: postmanGetCollectionPullRequests, ...authed(0), scope: 'read' as const },
    { name: 'postmanCreateAPullRequest', description: postmanCreateAPullRequest.description!, tool: postmanCreateAPullRequest, ...authed(0), scope: 'write' as const },
    { name: 'postmanUpdateAPullRequest', description: postmanUpdateAPullRequest.description!, tool: postmanUpdateAPullRequest, ...authed(0), scope: 'write' as const },
    { name: 'postmanReviewAPullRequest', description: postmanReviewAPullRequest.description!, tool: postmanReviewAPullRequest, ...authed(0), scope: 'write' as const },
    { name: 'postmanCreateACollectionComment', description: postmanCreateACollectionComment.description!, tool: postmanCreateACollectionComment, ...authed(0), scope: 'write' as const },
    { name: 'postmanGetCollectionComments', description: postmanGetCollectionComments.description!, tool: postmanGetCollectionComments, ...authed(0), scope: 'read' as const },
    { name: 'postmanDeleteACollectionsComment', description: postmanDeleteACollectionsComment.description!, tool: postmanDeleteACollectionsComment, ...authed(0), scope: 'delete' as const },
    { name: 'postmanGetApiComments', description: postmanGetApiComments.description!, tool: postmanGetApiComments, ...authed(0), scope: 'read' as const },
    { name: 'postmanUpdateAnApisComment', description: postmanUpdateAnApisComment.description!, tool: postmanUpdateAnApisComment, ...authed(0), scope: 'write' as const },
    { name: 'postmanDeleteAnApisComment', description: postmanDeleteAnApisComment.description!, tool: postmanDeleteAnApisComment, ...authed(0), scope: 'delete' as const },
    { name: 'postmanCreateAFolderComment', description: postmanCreateAFolderComment.description!, tool: postmanCreateAFolderComment, ...authed(0), scope: 'write' as const },
    { name: 'postmanGetFolderComments', description: postmanGetFolderComments.description!, tool: postmanGetFolderComments, ...authed(0), scope: 'read' as const },
    { name: 'postmanUpdateAFoldersComment', description: postmanUpdateAFoldersComment.description!, tool: postmanUpdateAFoldersComment, ...authed(0), scope: 'write' as const },
    { name: 'postmanDeleteAFoldersComment', description: postmanDeleteAFoldersComment.description!, tool: postmanDeleteAFoldersComment, ...authed(0), scope: 'delete' as const },
    { name: 'postmanCreateARequestComment', description: postmanCreateARequestComment.description!, tool: postmanCreateARequestComment, ...authed(0), scope: 'write' as const },
    { name: 'postmanGetRequestComments', description: postmanGetRequestComments.description!, tool: postmanGetRequestComments, ...authed(0), scope: 'read' as const },
    { name: 'postmanUpdateARequestsComment', description: postmanUpdateARequestsComment.description!, tool: postmanUpdateARequestsComment, ...authed(0), scope: 'write' as const },
    { name: 'postmanDeleteARequestsComment', description: postmanDeleteARequestsComment.description!, tool: postmanDeleteARequestsComment, ...authed(0), scope: 'delete' as const },
    { name: 'postmanCreateAResponseComment', description: postmanCreateAResponseComment.description!, tool: postmanCreateAResponseComment, ...authed(0), scope: 'write' as const },
    { name: 'postmanGetResponseComments', description: postmanGetResponseComments.description!, tool: postmanGetResponseComments, ...authed(0), scope: 'read' as const },
    { name: 'postmanUpdateAResponsesComment', description: postmanUpdateAResponsesComment.description!, tool: postmanUpdateAResponsesComment, ...authed(0), scope: 'write' as const },
    { name: 'postmanDeleteAResponsesComment', description: postmanDeleteAResponsesComment.description!, tool: postmanDeleteAResponsesComment, ...authed(0), scope: 'delete' as const },
    { name: 'postmanResolveACommentThread', description: postmanResolveACommentThread.description!, tool: postmanResolveACommentThread, ...authed(0), scope: 'write' as const },
    { name: 'postmanCreateAnEnvironment', description: postmanCreateAnEnvironment.description!, tool: postmanCreateAnEnvironment, ...authed(0), scope: 'write' as const },
    { name: 'postmanGetAllEnvironments', description: postmanGetAllEnvironments.description!, tool: postmanGetAllEnvironments, ...authed(0), scope: 'read' as const },
    { name: 'postmanGetAnEnvironment', description: postmanGetAnEnvironment.description!, tool: postmanGetAnEnvironment, ...authed(0), scope: 'read' as const },
    { name: 'postmanDeleteAnEnvironment', description: postmanDeleteAnEnvironment.description!, tool: postmanDeleteAnEnvironment, ...authed(0), scope: 'delete' as const },
    { name: 'postmanReplaceAnEnvironmentsData', description: postmanReplaceAnEnvironmentsData.description!, tool: postmanReplaceAnEnvironmentsData, ...authed(0), scope: 'write' as const },
    { name: 'postmanUpdateAnEnvironment', description: postmanUpdateAnEnvironment.description!, tool: postmanUpdateAnEnvironment, ...authed(0), scope: 'write' as const },
    { name: 'postmanCreateEnvironmentFork', description: postmanCreateEnvironmentFork.description!, tool: postmanCreateEnvironmentFork, ...authed(0), scope: 'write' as const },
    { name: 'postmanGetEnvironmentForks', description: postmanGetEnvironmentForks.description!, tool: postmanGetEnvironmentForks, ...authed(0), scope: 'read' as const },
    { name: 'postmanMergeAForkedEnvironment', description: postmanMergeAForkedEnvironment.description!, tool: postmanMergeAForkedEnvironment, ...authed(0), scope: 'write' as const },
    { name: 'postmanCreateAWorkspace', description: postmanCreateAWorkspace.description!, tool: postmanCreateAWorkspace, ...authed(0), scope: 'write' as const },
    { name: 'postmanGetAllWorkspaces', description: postmanGetAllWorkspaces.description!, tool: postmanGetAllWorkspaces, ...authed(0), scope: 'read' as const },
    { name: 'postmanGetWorkspaceDetails', description: postmanGetWorkspaceDetails.description!, tool: postmanGetWorkspaceDetails, ...authed(0), scope: 'read' as const },
    { name: 'postmanUpdateAWorkspace', description: postmanUpdateAWorkspace.description!, tool: postmanUpdateAWorkspace, ...authed(0), scope: 'write' as const },
    { name: 'postmanDeleteAWorkspace', description: postmanDeleteAWorkspace.description!, tool: postmanDeleteAWorkspace, ...authed(0), scope: 'delete' as const },
    { name: 'postmanGetWorkspaceActivityFeed', description: postmanGetWorkspaceActivityFeed.description!, tool: postmanGetWorkspaceActivityFeed, ...authed(0), scope: 'read' as const },
    { name: 'postmanGetWorkspaceRoles', description: postmanGetWorkspaceRoles.description!, tool: postmanGetWorkspaceRoles, ...authed(0), scope: 'read' as const },
    { name: 'postmanGetWorkspaceGlobalVariables', description: postmanGetWorkspaceGlobalVariables.description!, tool: postmanGetWorkspaceGlobalVariables, ...authed(0), scope: 'read' as const },
    { name: 'postmanUpdateWorkspaceGlobalVariables', description: postmanUpdateWorkspaceGlobalVariables.description!, tool: postmanUpdateWorkspaceGlobalVariables, ...authed(0), scope: 'write' as const },
    { name: 'postmanCreateAnApi', description: postmanCreateAnApi.description!, tool: postmanCreateAnApi, ...authed(0), scope: 'write' as const },
    { name: 'postmanGetAllApis', description: postmanGetAllApis.description!, tool: postmanGetAllApis, ...authed(0), scope: 'read' as const },
    { name: 'postmanGetApiInformation', description: postmanGetApiInformation.description!, tool: postmanGetApiInformation, ...authed(0), scope: 'read' as const },
    { name: 'postmanUpdateAnApi', description: postmanUpdateAnApi.description!, tool: postmanUpdateAnApi, ...authed(0), scope: 'write' as const },
    { name: 'postmanDeleteAnApi', description: postmanDeleteAnApi.description!, tool: postmanDeleteAnApi, ...authed(0), scope: 'delete' as const },
    { name: 'postmanGetAllApiVersions', description: postmanGetAllApiVersions.description!, tool: postmanGetAllApiVersions, ...authed(0), scope: 'read' as const },
    { name: 'postmanGetApiVersion', description: postmanGetApiVersion.description!, tool: postmanGetApiVersion, ...authed(0), scope: 'read' as const },
    { name: 'postmanCreateApiSchema', description: postmanCreateApiSchema.description!, tool: postmanCreateApiSchema, ...authed(0), scope: 'write' as const },
    { name: 'postmanGetApiSchema', description: postmanGetApiSchema.description!, tool: postmanGetApiSchema, ...authed(0), scope: 'read' as const },
    { name: 'postmanGetSchemaFiles', description: postmanGetSchemaFiles.description!, tool: postmanGetSchemaFiles, ...authed(0), scope: 'read' as const },
    { name: 'postmanGetSchemaFileContents', description: postmanGetSchemaFileContents.description!, tool: postmanGetSchemaFileContents, ...authed(0), scope: 'read' as const },
    { name: 'postmanCreateOrUpdateASchemaFile', description: postmanCreateOrUpdateASchemaFile.description!, tool: postmanCreateOrUpdateASchemaFile, ...authed(0), scope: 'write' as const },
    { name: 'postmanDeleteASchemaFile', description: postmanDeleteASchemaFile.description!, tool: postmanDeleteASchemaFile, ...authed(0), scope: 'delete' as const },
    { name: 'postmanSyncCollectionWithSchema', description: postmanSyncCollectionWithSchema.description!, tool: postmanSyncCollectionWithSchema, ...authed(0), scope: 'write' as const },
    { name: 'postmanCreateApiVersionRelations', description: postmanCreateApiVersionRelations.description!, tool: postmanCreateApiVersionRelations, ...authed(0), scope: 'write' as const },
    { name: 'postmanGetAllLinkedRelations', description: postmanGetAllLinkedRelations.description!, tool: postmanGetAllLinkedRelations, ...authed(0), scope: 'read' as const },
    { name: 'postmanGetUnclassifiedRelations', description: postmanGetUnclassifiedRelations.description!, tool: postmanGetUnclassifiedRelations, ...authed(0), scope: 'read' as const },
    { name: 'postmanCreateASpec', description: postmanCreateASpec.description!, tool: postmanCreateASpec, ...authed(0), scope: 'write' as const },
    { name: 'postmanGetAllApiSpecifications', description: postmanGetAllApiSpecifications.description!, tool: postmanGetAllApiSpecifications, ...authed(0), scope: 'read' as const },
    { name: 'postmanGetApiSpecification', description: postmanGetApiSpecification.description!, tool: postmanGetApiSpecification, ...authed(0), scope: 'read' as const },
    { name: 'postmanDeleteASpec', description: postmanDeleteASpec.description!, tool: postmanDeleteASpec, ...authed(0), scope: 'delete' as const },
    { name: 'postmanUpdateSpecProperties', description: postmanUpdateSpecProperties.description!, tool: postmanUpdateSpecProperties, ...authed(0), scope: 'write' as const },
    { name: 'postmanCreateSpecFile', description: postmanCreateSpecFile.description!, tool: postmanCreateSpecFile, ...authed(0), scope: 'write' as const },
    { name: 'postmanGetSpecFileContents', description: postmanGetSpecFileContents.description!, tool: postmanGetSpecFileContents, ...authed(0), scope: 'read' as const },
    { name: 'postmanUpdateSpecFile', description: postmanUpdateSpecFile.description!, tool: postmanUpdateSpecFile, ...authed(0), scope: 'write' as const },
    { name: 'postmanDeleteSpecFile', description: postmanDeleteSpecFile.description!, tool: postmanDeleteSpecFile, ...authed(0), scope: 'delete' as const },
    { name: 'postmanGetSpecificationFiles', description: postmanGetSpecificationFiles.description!, tool: postmanGetSpecificationFiles, ...authed(0), scope: 'read' as const },
    { name: 'postmanGetSpecDefinition', description: postmanGetSpecDefinition.description!, tool: postmanGetSpecDefinition, ...authed(0), scope: 'read' as const },
    { name: 'postmanGetSpecsGeneratedCollections', description: postmanGetSpecsGeneratedCollections.description!, tool: postmanGetSpecsGeneratedCollections, ...authed(0), scope: 'read' as const },
    { name: 'postmanGenerateCollectionFromSpec', description: postmanGenerateCollectionFromSpec.description!, tool: postmanGenerateCollectionFromSpec, ...authed(0), scope: 'write' as const },
    { name: 'postmanGenerateSpecFromCollection', description: postmanGenerateSpecFromCollection.description!, tool: postmanGenerateSpecFromCollection, ...authed(0), scope: 'write' as const },
    { name: 'postmanGetGeneratedSpec', description: postmanGetGeneratedSpec.description!, tool: postmanGetGeneratedSpec, ...authed(0), scope: 'read' as const },
    { name: 'postmanSyncCollectionWithSpec', description: postmanSyncCollectionWithSpec.description!, tool: postmanSyncCollectionWithSpec, ...authed(0), scope: 'write' as const },
    { name: 'postmanSyncSpecWithCollection', description: postmanSyncSpecWithCollection.description!, tool: postmanSyncSpecWithCollection, ...authed(0), scope: 'write' as const },
    { name: 'postmanImportOpenApiSpecification', description: postmanImportOpenApiSpecification.description!, tool: postmanImportOpenApiSpecification, ...authed(0), scope: 'write' as const },
    { name: 'postmanCreateAMockServer', description: postmanCreateAMockServer.description!, tool: postmanCreateAMockServer, ...authed(0), scope: 'write' as const },
    { name: 'postmanGetAllMockServers', description: postmanGetAllMockServers.description!, tool: postmanGetAllMockServers, ...authed(0), scope: 'read' as const },
    { name: 'postmanUpdateAMockServer', description: postmanUpdateAMockServer.description!, tool: postmanUpdateAMockServer, ...authed(0), scope: 'write' as const },
    { name: 'postmanPublishAMockServer', description: postmanPublishAMockServer.description!, tool: postmanPublishAMockServer, ...authed(0), scope: 'write' as const },
    { name: 'postmanCreateMockServerResponse', description: postmanCreateMockServerResponse.description!, tool: postmanCreateMockServerResponse, ...authed(0), scope: 'write' as const },
    { name: 'postmanUpdateAServerResponse', description: postmanUpdateAServerResponse.description!, tool: postmanUpdateAServerResponse, ...authed(0), scope: 'write' as const },
    { name: 'postmanDeleteMockServerResponse', description: postmanDeleteMockServerResponse.description!, tool: postmanDeleteMockServerResponse, ...authed(0), scope: 'delete' as const },
    { name: 'postmanCreateAMonitor', description: postmanCreateAMonitor.description!, tool: postmanCreateAMonitor, ...authed(0), scope: 'write' as const },
    { name: 'postmanGetAllMonitors', description: postmanGetAllMonitors.description!, tool: postmanGetAllMonitors, ...authed(0), scope: 'read' as const },
    { name: 'postmanGetMonitorInformation', description: postmanGetMonitorInformation.description!, tool: postmanGetMonitorInformation, ...authed(0), scope: 'read' as const },
    { name: 'postmanUpdateAMonitor', description: postmanUpdateAMonitor.description!, tool: postmanUpdateAMonitor, ...authed(0), scope: 'write' as const },
    { name: 'postmanDeleteMonitor', description: postmanDeleteMonitor.description!, tool: postmanDeleteMonitor, ...authed(0), scope: 'delete' as const },
    { name: 'postmanRunAMonitor', description: postmanRunAMonitor.description!, tool: postmanRunAMonitor, ...authed(0), scope: 'write' as const },
    { name: 'postmanGetAllTeamUsers', description: postmanGetAllTeamUsers.description!, tool: postmanGetAllTeamUsers, ...authed(0), scope: 'read' as const },
    { name: 'postmanGetATeamUser', description: postmanGetATeamUser.description!, tool: postmanGetATeamUser, ...authed(0), scope: 'read' as const },
    { name: 'postmanGetAuthenticatedUser', description: postmanGetAuthenticatedUser.description!, tool: postmanGetAuthenticatedUser, ...authed(0), scope: 'read' as const },
    { name: 'postmanGetAllGroups', description: postmanGetAllGroups.description!, tool: postmanGetAllGroups, ...authed(0), scope: 'read' as const },
    { name: 'postmanGetResourceTypes', description: postmanGetResourceTypes.description!, tool: postmanGetResourceTypes, ...authed(0), scope: 'read' as const },
    { name: 'postmanGetServiceProviderConfiguration', description: postmanGetServiceProviderConfiguration.description!, tool: postmanGetServiceProviderConfiguration, ...authed(0), scope: 'read' as const },
    { name: 'postmanGetBillingAccountDetails', description: postmanGetBillingAccountDetails.description!, tool: postmanGetBillingAccountDetails, ...authed(0), scope: 'read' as const },
    { name: 'postmanListAccountInvoices', description: postmanListAccountInvoices.description!, tool: postmanListAccountInvoices, ...authed(0), scope: 'read' as const },
    { name: 'postmanCreateAWebhook', description: postmanCreateAWebhook.description!, tool: postmanCreateAWebhook, ...authed(0), scope: 'write' as const },
];
