// @ts-nocheck
import {
  postmanCreateACollection,
  postmanGetAllCollections,
  postmanDeleteACollection,
  postmanDuplicateACollection,
  postmanGetDuplicationTaskStatus,
  postmanForkCollection,
  postmanGetCollectionForks,
  postmanGetAllForkedCollections,
  postmanPullSourceChangesIntoFork,
  postmanGetSourceCollectionStatus,
  postmanReplaceCollectionDataAsynchronously,
  postmanGetAsyncCollectionUpdateStatus,
  postmanTransferFolders,
  postmanTransformCollectionToOpenApi,
  postmanUpdateCollectionProperties,
  postmanGetCollectionRoles,
  postmanGetCollectionAccessKeys,
} from './collections.js';
import {
  postmanCreateAFolder,
  postmanGetFolderInformation,
  postmanUpdateAFolder,
  postmanDeleteAFolder,
  postmanCreateRequestInCollection,
  postmanGetRequestInformation,
  postmanUpdateRequestInCollection,
  postmanCreateAResponse,
  postmanGetResponseInformation,
  postmanUpdateAResponse,
  postmanDeleteAResponse,
} from './items.js';
import {
  postmanGetCollectionPullRequests,
  postmanCreateAPullRequest,
  postmanUpdateAPullRequest,
  postmanReviewAPullRequest,
} from './pull_requests.js';
import {
  postmanCreateACollectionComment,
  postmanGetCollectionComments,
  postmanDeleteACollectionsComment,
  postmanGetApiComments,
  postmanUpdateAnApisComment,
  postmanDeleteAnApisComment,
  postmanCreateAFolderComment,
  postmanGetFolderComments,
  postmanUpdateAFoldersComment,
  postmanDeleteAFoldersComment,
  postmanCreateARequestComment,
  postmanGetRequestComments,
  postmanUpdateARequestsComment,
  postmanDeleteARequestsComment,
  postmanCreateAResponseComment,
  postmanGetResponseComments,
  postmanUpdateAResponsesComment,
  postmanDeleteAResponsesComment,
  postmanResolveACommentThread,
} from './comments.js';
import {
  postmanCreateAnEnvironment,
  postmanGetAllEnvironments,
  postmanGetAnEnvironment,
  postmanDeleteAnEnvironment,
  postmanReplaceAnEnvironmentsData,
  postmanUpdateAnEnvironment,
  postmanCreateEnvironmentFork,
  postmanGetEnvironmentForks,
  postmanMergeAForkedEnvironment,
} from './environments.js';
import {
  postmanCreateAWorkspace,
  postmanGetAllWorkspaces,
  postmanGetWorkspaceDetails,
  postmanUpdateAWorkspace,
  postmanDeleteAWorkspace,
  postmanGetWorkspaceActivityFeed,
  postmanGetWorkspaceRoles,
  postmanGetWorkspaceGlobalVariables,
  postmanUpdateWorkspaceGlobalVariables,
} from './workspaces.js';
import {
  postmanCreateAnApi,
  postmanGetAllApis,
  postmanGetApiInformation,
  postmanUpdateAnApi,
  postmanDeleteAnApi,
  postmanGetAllApiVersions,
  postmanGetApiVersion,
  postmanCreateApiSchema,
  postmanGetApiSchema,
  postmanGetSchemaFiles,
  postmanGetSchemaFileContents,
  postmanCreateOrUpdateASchemaFile,
  postmanDeleteASchemaFile,
  postmanSyncCollectionWithSchema,
  postmanCreateApiVersionRelations,
  postmanGetAllLinkedRelations,
  postmanGetUnclassifiedRelations,
} from './designs_and_apis.js';
import {
  postmanCreateASpec,
  postmanGetAllApiSpecifications,
  postmanGetApiSpecification,
  postmanDeleteASpec,
  postmanUpdateSpecProperties,
  postmanCreateSpecFile,
  postmanGetSpecFileContents,
  postmanUpdateSpecFile,
  postmanDeleteSpecFile,
  postmanGetSpecificationFiles,
  postmanGetSpecDefinition,
  postmanGetSpecsGeneratedCollections,
  postmanGenerateCollectionFromSpec,
  postmanGenerateSpecFromCollection,
  postmanGetGeneratedSpec,
  postmanSyncCollectionWithSpec,
  postmanSyncSpecWithCollection,
  postmanImportOpenApiSpecification,
} from './specs.js';
import {
  postmanCreateAMockServer,
  postmanGetAllMockServers,
  postmanUpdateAMockServer,
  postmanPublishAMockServer,
  postmanCreateMockServerResponse,
  postmanUpdateAServerResponse,
  postmanDeleteMockServerResponse,
  postmanCreateAMonitor,
  postmanGetAllMonitors,
  postmanGetMonitorInformation,
  postmanUpdateAMonitor,
  postmanDeleteMonitor,
  postmanRunAMonitor,
} from './mocks_and_tests.js';
import {
  postmanGetAllTeamUsers,
  postmanGetATeamUser,
  postmanGetAuthenticatedUser,
  postmanGetAllGroups,
  postmanGetResourceTypes,
  postmanGetServiceProviderConfiguration,
  postmanGetBillingAccountDetails,
  postmanListAccountInvoices,
} from './scim_users_teams.js';
import { postmanCreateAWebhook } from './webhooks.js';

export {
  postmanCreateACollection,
  postmanGetAllCollections,
  postmanDeleteACollection,
  postmanDuplicateACollection,
  postmanGetDuplicationTaskStatus,
  postmanForkCollection,
  postmanGetCollectionForks,
  postmanGetAllForkedCollections,
  postmanPullSourceChangesIntoFork,
  postmanGetSourceCollectionStatus,
  postmanReplaceCollectionDataAsynchronously,
  postmanGetAsyncCollectionUpdateStatus,
  postmanTransferFolders,
  postmanTransformCollectionToOpenApi,
  postmanUpdateCollectionProperties,
  postmanGetCollectionRoles,
  postmanGetCollectionAccessKeys,
  postmanCreateAFolder,
  postmanGetFolderInformation,
  postmanUpdateAFolder,
  postmanDeleteAFolder,
  postmanCreateRequestInCollection,
  postmanGetRequestInformation,
  postmanUpdateRequestInCollection,
  postmanCreateAResponse,
  postmanGetResponseInformation,
  postmanUpdateAResponse,
  postmanDeleteAResponse,
  postmanGetCollectionPullRequests,
  postmanCreateAPullRequest,
  postmanUpdateAPullRequest,
  postmanReviewAPullRequest,
  postmanCreateACollectionComment,
  postmanGetCollectionComments,
  postmanDeleteACollectionsComment,
  postmanGetApiComments,
  postmanUpdateAnApisComment,
  postmanDeleteAnApisComment,
  postmanCreateAFolderComment,
  postmanGetFolderComments,
  postmanUpdateAFoldersComment,
  postmanDeleteAFoldersComment,
  postmanCreateARequestComment,
  postmanGetRequestComments,
  postmanUpdateARequestsComment,
  postmanDeleteARequestsComment,
  postmanCreateAResponseComment,
  postmanGetResponseComments,
  postmanUpdateAResponsesComment,
  postmanDeleteAResponsesComment,
  postmanResolveACommentThread,
  postmanCreateAnEnvironment,
  postmanGetAllEnvironments,
  postmanGetAnEnvironment,
  postmanDeleteAnEnvironment,
  postmanReplaceAnEnvironmentsData,
  postmanUpdateAnEnvironment,
  postmanCreateEnvironmentFork,
  postmanGetEnvironmentForks,
  postmanMergeAForkedEnvironment,
  postmanCreateAWorkspace,
  postmanGetAllWorkspaces,
  postmanGetWorkspaceDetails,
  postmanUpdateAWorkspace,
  postmanDeleteAWorkspace,
  postmanGetWorkspaceActivityFeed,
  postmanGetWorkspaceRoles,
  postmanGetWorkspaceGlobalVariables,
  postmanUpdateWorkspaceGlobalVariables,
  postmanCreateAnApi,
  postmanGetAllApis,
  postmanGetApiInformation,
  postmanUpdateAnApi,
  postmanDeleteAnApi,
  postmanGetAllApiVersions,
  postmanGetApiVersion,
  postmanCreateApiSchema,
  postmanGetApiSchema,
  postmanGetSchemaFiles,
  postmanGetSchemaFileContents,
  postmanCreateOrUpdateASchemaFile,
  postmanDeleteASchemaFile,
  postmanSyncCollectionWithSchema,
  postmanCreateApiVersionRelations,
  postmanGetAllLinkedRelations,
  postmanGetUnclassifiedRelations,
  postmanCreateASpec,
  postmanGetAllApiSpecifications,
  postmanGetApiSpecification,
  postmanDeleteASpec,
  postmanUpdateSpecProperties,
  postmanCreateSpecFile,
  postmanGetSpecFileContents,
  postmanUpdateSpecFile,
  postmanDeleteSpecFile,
  postmanGetSpecificationFiles,
  postmanGetSpecDefinition,
  postmanGetSpecsGeneratedCollections,
  postmanGenerateCollectionFromSpec,
  postmanGenerateSpecFromCollection,
  postmanGetGeneratedSpec,
  postmanSyncCollectionWithSpec,
  postmanSyncSpecWithCollection,
  postmanImportOpenApiSpecification,
  postmanCreateAMockServer,
  postmanGetAllMockServers,
  postmanUpdateAMockServer,
  postmanPublishAMockServer,
  postmanCreateMockServerResponse,
  postmanUpdateAServerResponse,
  postmanDeleteMockServerResponse,
  postmanCreateAMonitor,
  postmanGetAllMonitors,
  postmanGetMonitorInformation,
  postmanUpdateAMonitor,
  postmanDeleteMonitor,
  postmanRunAMonitor,
  postmanGetAllTeamUsers,
  postmanGetATeamUser,
  postmanGetAuthenticatedUser,
  postmanGetAllGroups,
  postmanGetResourceTypes,
  postmanGetServiceProviderConfiguration,
  postmanGetBillingAccountDetails,
  postmanListAccountInvoices,
  postmanCreateAWebhook,
};

const authed = (tool: any) => ({ requiredAuth: 'postmanApiKey' as const });

export const postmanTools = [
  {
    name: 'postmanCreateACollection',
    description: postmanCreateACollection.description!,
    tool: postmanCreateACollection,
    ...authed(0),
    scope: 'write' as const,
    keywords: ['new'],
  },
  {
    name: 'postmanGetAllCollections',
    description: postmanGetAllCollections.description!,
    tool: postmanGetAllCollections,
    ...authed(0),
    scope: 'read' as const,
    keywords: [],
  },
  {
    name: 'postmanDeleteACollection',
    description: postmanDeleteACollection.description!,
    tool: postmanDeleteACollection,
    ...authed(0),
    scope: 'delete' as const,
    keywords: [],
  },
  {
    name: 'postmanDuplicateACollection',
    description: postmanDuplicateACollection.description!,
    tool: postmanDuplicateACollection,
    ...authed(0),
    scope: 'write' as const,
    keywords: ['clone', 'copy'],
  },
  {
    name: 'postmanGetDuplicationTaskStatus',
    description: postmanGetDuplicationTaskStatus.description!,
    tool: postmanGetDuplicationTaskStatus,
    ...authed(0),
    scope: 'read' as const,
    keywords: [],
  },
  {
    name: 'postmanForkCollection',
    description: postmanForkCollection.description!,
    tool: postmanForkCollection,
    ...authed(0),
    scope: 'write' as const,
    keywords: ['clone'],
  },
  {
    name: 'postmanGetCollectionForks',
    description: postmanGetCollectionForks.description!,
    tool: postmanGetCollectionForks,
    ...authed(0),
    scope: 'read' as const,
    keywords: ['clone'],
  },
  {
    name: 'postmanGetAllForkedCollections',
    description: postmanGetAllForkedCollections.description!,
    tool: postmanGetAllForkedCollections,
    ...authed(0),
    scope: 'read' as const,
    keywords: ['clone'],
  },
  {
    name: 'postmanPullSourceChangesIntoFork',
    description: postmanPullSourceChangesIntoFork.description!,
    tool: postmanPullSourceChangesIntoFork,
    ...authed(0),
    scope: 'write' as const,
    keywords: ['merge', 'sync'],
  },
  {
    name: 'postmanGetSourceCollectionStatus',
    description: postmanGetSourceCollectionStatus.description!,
    tool: postmanGetSourceCollectionStatus,
    ...authed(0),
    scope: 'read' as const,
    keywords: ['sync', 'diff'],
  },
  {
    name: 'postmanReplaceCollectionDataAsynchronously',
    description: postmanReplaceCollectionDataAsynchronously.description!,
    tool: postmanReplaceCollectionDataAsynchronously,
    ...authed(0),
    scope: 'write' as const,
    keywords: [],
  },
  {
    name: 'postmanGetAsyncCollectionUpdateStatus',
    description: postmanGetAsyncCollectionUpdateStatus.description!,
    tool: postmanGetAsyncCollectionUpdateStatus,
    ...authed(0),
    scope: 'read' as const,
    keywords: [],
  },
  {
    name: 'postmanTransferFolders',
    description: postmanTransferFolders.description!,
    tool: postmanTransferFolders,
    ...authed(0),
    scope: 'write' as const,
    keywords: [],
  },
  {
    name: 'postmanTransformCollectionToOpenApi',
    description: postmanTransformCollectionToOpenApi.description!,
    tool: postmanTransformCollectionToOpenApi,
    ...authed(0),
    scope: 'read' as const,
    keywords: ['swagger', 'export'],
  },
  {
    name: 'postmanUpdateCollectionProperties',
    description: postmanUpdateCollectionProperties.description!,
    tool: postmanUpdateCollectionProperties,
    ...authed(0),
    scope: 'write' as const,
    keywords: [],
  },
  {
    name: 'postmanGetCollectionRoles',
    description: postmanGetCollectionRoles.description!,
    tool: postmanGetCollectionRoles,
    ...authed(0),
    scope: 'read' as const,
    keywords: [],
  },
  {
    name: 'postmanGetCollectionAccessKeys',
    description: postmanGetCollectionAccessKeys.description!,
    tool: postmanGetCollectionAccessKeys,
    ...authed(0),
    scope: 'read' as const,
    keywords: [],
  },
  {
    name: 'postmanCreateAFolder',
    description: postmanCreateAFolder.description!,
    tool: postmanCreateAFolder,
    ...authed(0),
    scope: 'write' as const,
    keywords: ['directory'],
  },
  {
    name: 'postmanGetFolderInformation',
    description: postmanGetFolderInformation.description!,
    tool: postmanGetFolderInformation,
    ...authed(0),
    scope: 'read' as const,
    keywords: ['directory'],
  },
  {
    name: 'postmanUpdateAFolder',
    description: postmanUpdateAFolder.description!,
    tool: postmanUpdateAFolder,
    ...authed(0),
    scope: 'write' as const,
    keywords: ['directory', 'rename'],
  },
  {
    name: 'postmanDeleteAFolder',
    description: postmanDeleteAFolder.description!,
    tool: postmanDeleteAFolder,
    ...authed(0),
    scope: 'delete' as const,
    keywords: ['directory', 'remove'],
  },
  {
    name: 'postmanCreateRequestInCollection',
    description: postmanCreateRequestInCollection.description!,
    tool: postmanCreateRequestInCollection,
    ...authed(0),
    scope: 'write' as const,
    keywords: ['endpoint', 'http', 'rest'],
  },
  {
    name: 'postmanGetRequestInformation',
    description: postmanGetRequestInformation.description!,
    tool: postmanGetRequestInformation,
    ...authed(0),
    scope: 'read' as const,
    keywords: ['endpoint', 'http'],
  },
  {
    name: 'postmanUpdateRequestInCollection',
    description: postmanUpdateRequestInCollection.description!,
    tool: postmanUpdateRequestInCollection,
    ...authed(0),
    scope: 'write' as const,
    keywords: ['endpoint', 'http'],
  },
  {
    name: 'postmanCreateAResponse',
    description: postmanCreateAResponse.description!,
    tool: postmanCreateAResponse,
    ...authed(0),
    scope: 'write' as const,
    keywords: ['example', 'sample'],
  },
  {
    name: 'postmanGetResponseInformation',
    description: postmanGetResponseInformation.description!,
    tool: postmanGetResponseInformation,
    ...authed(0),
    scope: 'read' as const,
    keywords: ['example'],
  },
  {
    name: 'postmanUpdateAResponse',
    description: postmanUpdateAResponse.description!,
    tool: postmanUpdateAResponse,
    ...authed(0),
    scope: 'write' as const,
    keywords: ['example'],
  },
  {
    name: 'postmanDeleteAResponse',
    description: postmanDeleteAResponse.description!,
    tool: postmanDeleteAResponse,
    ...authed(0),
    scope: 'delete' as const,
    keywords: [],
  },
  {
    name: 'postmanGetCollectionPullRequests',
    description: postmanGetCollectionPullRequests.description!,
    tool: postmanGetCollectionPullRequests,
    ...authed(0),
    scope: 'read' as const,
    keywords: ['pr', 'prs', 'review'],
  },
  {
    name: 'postmanCreateAPullRequest',
    description: postmanCreateAPullRequest.description!,
    tool: postmanCreateAPullRequest,
    ...authed(0),
    scope: 'write' as const,
    keywords: ['pr', 'merge'],
  },
  {
    name: 'postmanUpdateAPullRequest',
    description: postmanUpdateAPullRequest.description!,
    tool: postmanUpdateAPullRequest,
    ...authed(0),
    scope: 'write' as const,
    keywords: ['pr'],
  },
  {
    name: 'postmanReviewAPullRequest',
    description: postmanReviewAPullRequest.description!,
    tool: postmanReviewAPullRequest,
    ...authed(0),
    scope: 'write' as const,
    keywords: ['pr', 'approve', 'merge'],
  },
  {
    name: 'postmanCreateACollectionComment',
    description: postmanCreateACollectionComment.description!,
    tool: postmanCreateACollectionComment,
    ...authed(0),
    scope: 'write' as const,
    keywords: ['feedback', 'reply'],
  },
  {
    name: 'postmanGetCollectionComments',
    description: postmanGetCollectionComments.description!,
    tool: postmanGetCollectionComments,
    ...authed(0),
    scope: 'read' as const,
    keywords: ['feedback'],
  },
  {
    name: 'postmanDeleteACollectionsComment',
    description: postmanDeleteACollectionsComment.description!,
    tool: postmanDeleteACollectionsComment,
    ...authed(0),
    scope: 'delete' as const,
    keywords: [],
  },
  {
    name: 'postmanGetApiComments',
    description: postmanGetApiComments.description!,
    tool: postmanGetApiComments,
    ...authed(0),
    scope: 'read' as const,
    keywords: ['feedback'],
  },
  {
    name: 'postmanUpdateAnApisComment',
    description: postmanUpdateAnApisComment.description!,
    tool: postmanUpdateAnApisComment,
    ...authed(0),
    scope: 'write' as const,
    keywords: [],
  },
  {
    name: 'postmanDeleteAnApisComment',
    description: postmanDeleteAnApisComment.description!,
    tool: postmanDeleteAnApisComment,
    ...authed(0),
    scope: 'delete' as const,
    keywords: [],
  },
  {
    name: 'postmanCreateAFolderComment',
    description: postmanCreateAFolderComment.description!,
    tool: postmanCreateAFolderComment,
    ...authed(0),
    scope: 'write' as const,
    keywords: ['feedback', 'reply'],
  },
  {
    name: 'postmanGetFolderComments',
    description: postmanGetFolderComments.description!,
    tool: postmanGetFolderComments,
    ...authed(0),
    scope: 'read' as const,
    keywords: ['feedback'],
  },
  {
    name: 'postmanUpdateAFoldersComment',
    description: postmanUpdateAFoldersComment.description!,
    tool: postmanUpdateAFoldersComment,
    ...authed(0),
    scope: 'write' as const,
    keywords: [],
  },
  {
    name: 'postmanDeleteAFoldersComment',
    description: postmanDeleteAFoldersComment.description!,
    tool: postmanDeleteAFoldersComment,
    ...authed(0),
    scope: 'delete' as const,
    keywords: [],
  },
  {
    name: 'postmanCreateARequestComment',
    description: postmanCreateARequestComment.description!,
    tool: postmanCreateARequestComment,
    ...authed(0),
    scope: 'write' as const,
    keywords: ['feedback', 'reply'],
  },
  {
    name: 'postmanGetRequestComments',
    description: postmanGetRequestComments.description!,
    tool: postmanGetRequestComments,
    ...authed(0),
    scope: 'read' as const,
    keywords: ['feedback'],
  },
  {
    name: 'postmanUpdateARequestsComment',
    description: postmanUpdateARequestsComment.description!,
    tool: postmanUpdateARequestsComment,
    ...authed(0),
    scope: 'write' as const,
    keywords: [],
  },
  {
    name: 'postmanDeleteARequestsComment',
    description: postmanDeleteARequestsComment.description!,
    tool: postmanDeleteARequestsComment,
    ...authed(0),
    scope: 'delete' as const,
    keywords: [],
  },
  {
    name: 'postmanCreateAResponseComment',
    description: postmanCreateAResponseComment.description!,
    tool: postmanCreateAResponseComment,
    ...authed(0),
    scope: 'write' as const,
    keywords: ['feedback', 'reply'],
  },
  {
    name: 'postmanGetResponseComments',
    description: postmanGetResponseComments.description!,
    tool: postmanGetResponseComments,
    ...authed(0),
    scope: 'read' as const,
    keywords: ['feedback'],
  },
  {
    name: 'postmanUpdateAResponsesComment',
    description: postmanUpdateAResponsesComment.description!,
    tool: postmanUpdateAResponsesComment,
    ...authed(0),
    scope: 'write' as const,
    keywords: [],
  },
  {
    name: 'postmanDeleteAResponsesComment',
    description: postmanDeleteAResponsesComment.description!,
    tool: postmanDeleteAResponsesComment,
    ...authed(0),
    scope: 'delete' as const,
    keywords: [],
  },
  {
    name: 'postmanResolveACommentThread',
    description: postmanResolveACommentThread.description!,
    tool: postmanResolveACommentThread,
    ...authed(0),
    scope: 'write' as const,
    keywords: ['close'],
  },
  {
    name: 'postmanCreateAnEnvironment',
    description: postmanCreateAnEnvironment.description!,
    tool: postmanCreateAnEnvironment,
    ...authed(0),
    scope: 'write' as const,
    keywords: ['env', 'envs', 'new'],
  },
  {
    name: 'postmanGetAllEnvironments',
    description: postmanGetAllEnvironments.description!,
    tool: postmanGetAllEnvironments,
    ...authed(0),
    scope: 'read' as const,
    keywords: ['env', 'envs'],
  },
  {
    name: 'postmanGetAnEnvironment',
    description: postmanGetAnEnvironment.description!,
    tool: postmanGetAnEnvironment,
    ...authed(0),
    scope: 'read' as const,
    keywords: ['env', 'envs'],
  },
  {
    name: 'postmanDeleteAnEnvironment',
    description: postmanDeleteAnEnvironment.description!,
    tool: postmanDeleteAnEnvironment,
    ...authed(0),
    scope: 'delete' as const,
    keywords: ['env', 'envs', 'remove'],
  },
  {
    name: 'postmanReplaceAnEnvironmentsData',
    description: postmanReplaceAnEnvironmentsData.description!,
    tool: postmanReplaceAnEnvironmentsData,
    ...authed(0),
    scope: 'write' as const,
    keywords: ['env', 'envs'],
  },
  {
    name: 'postmanUpdateAnEnvironment',
    description: postmanUpdateAnEnvironment.description!,
    tool: postmanUpdateAnEnvironment,
    ...authed(0),
    scope: 'write' as const,
    keywords: ['env', 'envs'],
  },
  {
    name: 'postmanCreateEnvironmentFork',
    description: postmanCreateEnvironmentFork.description!,
    tool: postmanCreateEnvironmentFork,
    ...authed(0),
    scope: 'write' as const,
    keywords: ['env', 'clone'],
  },
  {
    name: 'postmanGetEnvironmentForks',
    description: postmanGetEnvironmentForks.description!,
    tool: postmanGetEnvironmentForks,
    ...authed(0),
    scope: 'read' as const,
    keywords: ['env', 'clone'],
  },
  {
    name: 'postmanMergeAForkedEnvironment',
    description: postmanMergeAForkedEnvironment.description!,
    tool: postmanMergeAForkedEnvironment,
    ...authed(0),
    scope: 'write' as const,
    keywords: ['env', 'merge'],
  },
  {
    name: 'postmanCreateAWorkspace',
    description: postmanCreateAWorkspace.description!,
    tool: postmanCreateAWorkspace,
    ...authed(0),
    scope: 'write' as const,
    keywords: [],
  },
  {
    name: 'postmanGetAllWorkspaces',
    description: postmanGetAllWorkspaces.description!,
    tool: postmanGetAllWorkspaces,
    ...authed(0),
    scope: 'read' as const,
    keywords: [],
  },
  {
    name: 'postmanGetWorkspaceDetails',
    description: postmanGetWorkspaceDetails.description!,
    tool: postmanGetWorkspaceDetails,
    ...authed(0),
    scope: 'read' as const,
    keywords: [],
  },
  {
    name: 'postmanUpdateAWorkspace',
    description: postmanUpdateAWorkspace.description!,
    tool: postmanUpdateAWorkspace,
    ...authed(0),
    scope: 'write' as const,
    keywords: [],
  },
  {
    name: 'postmanDeleteAWorkspace',
    description: postmanDeleteAWorkspace.description!,
    tool: postmanDeleteAWorkspace,
    ...authed(0),
    scope: 'delete' as const,
    keywords: [],
  },
  {
    name: 'postmanGetWorkspaceActivityFeed',
    description: postmanGetWorkspaceActivityFeed.description!,
    tool: postmanGetWorkspaceActivityFeed,
    ...authed(0),
    scope: 'read' as const,
    keywords: ['audit', 'history', 'changelog'],
  },
  {
    name: 'postmanGetWorkspaceRoles',
    description: postmanGetWorkspaceRoles.description!,
    tool: postmanGetWorkspaceRoles,
    ...authed(0),
    scope: 'read' as const,
    keywords: [],
  },
  {
    name: 'postmanGetWorkspaceGlobalVariables',
    description: postmanGetWorkspaceGlobalVariables.description!,
    tool: postmanGetWorkspaceGlobalVariables,
    ...authed(0),
    scope: 'read' as const,
    keywords: ['env'],
  },
  {
    name: 'postmanUpdateWorkspaceGlobalVariables',
    description: postmanUpdateWorkspaceGlobalVariables.description!,
    tool: postmanUpdateWorkspaceGlobalVariables,
    ...authed(0),
    scope: 'write' as const,
    keywords: ['env'],
  },
  {
    name: 'postmanCreateAnApi',
    description: postmanCreateAnApi.description!,
    tool: postmanCreateAnApi,
    ...authed(0),
    scope: 'write' as const,
    keywords: [],
  },
  {
    name: 'postmanGetAllApis',
    description: postmanGetAllApis.description!,
    tool: postmanGetAllApis,
    ...authed(0),
    scope: 'read' as const,
    keywords: [],
  },
  {
    name: 'postmanGetApiInformation',
    description: postmanGetApiInformation.description!,
    tool: postmanGetApiInformation,
    ...authed(0),
    scope: 'read' as const,
    keywords: [],
  },
  {
    name: 'postmanUpdateAnApi',
    description: postmanUpdateAnApi.description!,
    tool: postmanUpdateAnApi,
    ...authed(0),
    scope: 'write' as const,
    keywords: [],
  },
  {
    name: 'postmanDeleteAnApi',
    description: postmanDeleteAnApi.description!,
    tool: postmanDeleteAnApi,
    ...authed(0),
    scope: 'delete' as const,
    keywords: [],
  },
  {
    name: 'postmanGetAllApiVersions',
    description: postmanGetAllApiVersions.description!,
    tool: postmanGetAllApiVersions,
    ...authed(0),
    scope: 'read' as const,
    keywords: ['release'],
  },
  {
    name: 'postmanGetApiVersion',
    description: postmanGetApiVersion.description!,
    tool: postmanGetApiVersion,
    ...authed(0),
    scope: 'read' as const,
    keywords: [],
  },
  {
    name: 'postmanCreateApiSchema',
    description: postmanCreateApiSchema.description!,
    tool: postmanCreateApiSchema,
    ...authed(0),
    scope: 'write' as const,
    keywords: ['swagger', 'protobuf', 'spec'],
  },
  {
    name: 'postmanGetApiSchema',
    description: postmanGetApiSchema.description!,
    tool: postmanGetApiSchema,
    ...authed(0),
    scope: 'read' as const,
    keywords: ['swagger', 'spec'],
  },
  {
    name: 'postmanGetSchemaFiles',
    description: postmanGetSchemaFiles.description!,
    tool: postmanGetSchemaFiles,
    ...authed(0),
    scope: 'read' as const,
    keywords: ['swagger'],
  },
  {
    name: 'postmanGetSchemaFileContents',
    description: postmanGetSchemaFileContents.description!,
    tool: postmanGetSchemaFileContents,
    ...authed(0),
    scope: 'read' as const,
    keywords: ['swagger'],
  },
  {
    name: 'postmanCreateOrUpdateASchemaFile',
    description: postmanCreateOrUpdateASchemaFile.description!,
    tool: postmanCreateOrUpdateASchemaFile,
    ...authed(0),
    scope: 'write' as const,
    keywords: ['swagger'],
  },
  {
    name: 'postmanDeleteASchemaFile',
    description: postmanDeleteASchemaFile.description!,
    tool: postmanDeleteASchemaFile,
    ...authed(0),
    scope: 'delete' as const,
    keywords: [],
  },
  {
    name: 'postmanSyncCollectionWithSchema',
    description: postmanSyncCollectionWithSchema.description!,
    tool: postmanSyncCollectionWithSchema,
    ...authed(0),
    scope: 'write' as const,
    keywords: [],
  },
  {
    name: 'postmanCreateApiVersionRelations',
    description: postmanCreateApiVersionRelations.description!,
    tool: postmanCreateApiVersionRelations,
    ...authed(0),
    scope: 'write' as const,
    keywords: [],
  },
  {
    name: 'postmanGetAllLinkedRelations',
    description: postmanGetAllLinkedRelations.description!,
    tool: postmanGetAllLinkedRelations,
    ...authed(0),
    scope: 'read' as const,
    keywords: [],
  },
  {
    name: 'postmanGetUnclassifiedRelations',
    description: postmanGetUnclassifiedRelations.description!,
    tool: postmanGetUnclassifiedRelations,
    ...authed(0),
    scope: 'read' as const,
    keywords: [],
  },
  {
    name: 'postmanCreateASpec',
    description: postmanCreateASpec.description!,
    tool: postmanCreateASpec,
    ...authed(0),
    scope: 'write' as const,
    keywords: ['openapi', 'asyncapi'],
  },
  {
    name: 'postmanGetAllApiSpecifications',
    description: postmanGetAllApiSpecifications.description!,
    tool: postmanGetAllApiSpecifications,
    ...authed(0),
    scope: 'read' as const,
    keywords: [],
  },
  {
    name: 'postmanGetApiSpecification',
    description: postmanGetApiSpecification.description!,
    tool: postmanGetApiSpecification,
    ...authed(0),
    scope: 'read' as const,
    keywords: [],
  },
  {
    name: 'postmanDeleteASpec',
    description: postmanDeleteASpec.description!,
    tool: postmanDeleteASpec,
    ...authed(0),
    scope: 'delete' as const,
    keywords: [],
  },
  {
    name: 'postmanUpdateSpecProperties',
    description: postmanUpdateSpecProperties.description!,
    tool: postmanUpdateSpecProperties,
    ...authed(0),
    scope: 'write' as const,
    keywords: [],
  },
  {
    name: 'postmanCreateSpecFile',
    description: postmanCreateSpecFile.description!,
    tool: postmanCreateSpecFile,
    ...authed(0),
    scope: 'write' as const,
    keywords: [],
  },
  {
    name: 'postmanGetSpecFileContents',
    description: postmanGetSpecFileContents.description!,
    tool: postmanGetSpecFileContents,
    ...authed(0),
    scope: 'read' as const,
    keywords: [],
  },
  {
    name: 'postmanUpdateSpecFile',
    description: postmanUpdateSpecFile.description!,
    tool: postmanUpdateSpecFile,
    ...authed(0),
    scope: 'write' as const,
    keywords: [],
  },
  {
    name: 'postmanDeleteSpecFile',
    description: postmanDeleteSpecFile.description!,
    tool: postmanDeleteSpecFile,
    ...authed(0),
    scope: 'delete' as const,
    keywords: [],
  },
  {
    name: 'postmanGetSpecificationFiles',
    description: postmanGetSpecificationFiles.description!,
    tool: postmanGetSpecificationFiles,
    ...authed(0),
    scope: 'read' as const,
    keywords: [],
  },
  {
    name: 'postmanGetSpecDefinition',
    description: postmanGetSpecDefinition.description!,
    tool: postmanGetSpecDefinition,
    ...authed(0),
    scope: 'read' as const,
    keywords: ['swagger', 'openapi'],
  },
  {
    name: 'postmanGetSpecsGeneratedCollections',
    description: postmanGetSpecsGeneratedCollections.description!,
    tool: postmanGetSpecsGeneratedCollections,
    ...authed(0),
    scope: 'read' as const,
    keywords: [],
  },
  {
    name: 'postmanGenerateCollectionFromSpec',
    description: postmanGenerateCollectionFromSpec.description!,
    tool: postmanGenerateCollectionFromSpec,
    ...authed(0),
    scope: 'write' as const,
    keywords: ['import', 'convert'],
  },
  {
    name: 'postmanGenerateSpecFromCollection',
    description: postmanGenerateSpecFromCollection.description!,
    tool: postmanGenerateSpecFromCollection,
    ...authed(0),
    scope: 'write' as const,
    keywords: ['export', 'convert'],
  },
  {
    name: 'postmanGetGeneratedSpec',
    description: postmanGetGeneratedSpec.description!,
    tool: postmanGetGeneratedSpec,
    ...authed(0),
    scope: 'read' as const,
    keywords: [],
  },
  {
    name: 'postmanSyncCollectionWithSpec',
    description: postmanSyncCollectionWithSpec.description!,
    tool: postmanSyncCollectionWithSpec,
    ...authed(0),
    scope: 'write' as const,
    keywords: [],
  },
  {
    name: 'postmanSyncSpecWithCollection',
    description: postmanSyncSpecWithCollection.description!,
    tool: postmanSyncSpecWithCollection,
    ...authed(0),
    scope: 'write' as const,
    keywords: [],
  },
  {
    name: 'postmanImportOpenApiSpecification',
    description: postmanImportOpenApiSpecification.description!,
    tool: postmanImportOpenApiSpecification,
    ...authed(0),
    scope: 'write' as const,
    keywords: ['swagger', 'import'],
  },
  {
    name: 'postmanCreateAMockServer',
    description: postmanCreateAMockServer.description!,
    tool: postmanCreateAMockServer,
    ...authed(0),
    scope: 'write' as const,
    keywords: ['fake', 'stub'],
  },
  {
    name: 'postmanGetAllMockServers',
    description: postmanGetAllMockServers.description!,
    tool: postmanGetAllMockServers,
    ...authed(0),
    scope: 'read' as const,
    keywords: ['fake', 'stub'],
  },
  {
    name: 'postmanUpdateAMockServer',
    description: postmanUpdateAMockServer.description!,
    tool: postmanUpdateAMockServer,
    ...authed(0),
    scope: 'write' as const,
    keywords: ['fake', 'stub'],
  },
  {
    name: 'postmanPublishAMockServer',
    description: postmanPublishAMockServer.description!,
    tool: postmanPublishAMockServer,
    ...authed(0),
    scope: 'write' as const,
    keywords: [],
  },
  {
    name: 'postmanCreateMockServerResponse',
    description: postmanCreateMockServerResponse.description!,
    tool: postmanCreateMockServerResponse,
    ...authed(0),
    scope: 'write' as const,
    keywords: ['fake', 'stub'],
  },
  {
    name: 'postmanUpdateAServerResponse',
    description: postmanUpdateAServerResponse.description!,
    tool: postmanUpdateAServerResponse,
    ...authed(0),
    scope: 'write' as const,
    keywords: [],
  },
  {
    name: 'postmanDeleteMockServerResponse',
    description: postmanDeleteMockServerResponse.description!,
    tool: postmanDeleteMockServerResponse,
    ...authed(0),
    scope: 'delete' as const,
    keywords: [],
  },
  {
    name: 'postmanCreateAMonitor',
    description: postmanCreateAMonitor.description!,
    tool: postmanCreateAMonitor,
    ...authed(0),
    scope: 'write' as const,
    keywords: ['uptime', 'schedule', 'cron'],
  },
  {
    name: 'postmanGetAllMonitors',
    description: postmanGetAllMonitors.description!,
    tool: postmanGetAllMonitors,
    ...authed(0),
    scope: 'read' as const,
    keywords: ['uptime'],
  },
  {
    name: 'postmanGetMonitorInformation',
    description: postmanGetMonitorInformation.description!,
    tool: postmanGetMonitorInformation,
    ...authed(0),
    scope: 'read' as const,
    keywords: ['uptime', 'status'],
  },
  {
    name: 'postmanUpdateAMonitor',
    description: postmanUpdateAMonitor.description!,
    tool: postmanUpdateAMonitor,
    ...authed(0),
    scope: 'write' as const,
    keywords: ['uptime'],
  },
  {
    name: 'postmanDeleteMonitor',
    description: postmanDeleteMonitor.description!,
    tool: postmanDeleteMonitor,
    ...authed(0),
    scope: 'delete' as const,
    keywords: ['uptime', 'remove'],
  },
  {
    name: 'postmanRunAMonitor',
    description: postmanRunAMonitor.description!,
    tool: postmanRunAMonitor,
    ...authed(0),
    scope: 'write' as const,
    keywords: ['trigger', 'now'],
  },
  {
    name: 'postmanGetAllTeamUsers',
    description: postmanGetAllTeamUsers.description!,
    tool: postmanGetAllTeamUsers,
    ...authed(0),
    scope: 'read' as const,
    keywords: ['member', 'members'],
  },
  {
    name: 'postmanGetATeamUser',
    description: postmanGetATeamUser.description!,
    tool: postmanGetATeamUser,
    ...authed(0),
    scope: 'read' as const,
    keywords: ['member'],
  },
  {
    name: 'postmanGetAuthenticatedUser',
    description: postmanGetAuthenticatedUser.description!,
    tool: postmanGetAuthenticatedUser,
    ...authed(0),
    scope: 'read' as const,
    keywords: ['profile', 'account'],
  },
  {
    name: 'postmanGetAllGroups',
    description: postmanGetAllGroups.description!,
    tool: postmanGetAllGroups,
    ...authed(0),
    scope: 'read' as const,
    keywords: ['member', 'members', 'sso'],
  },
  {
    name: 'postmanGetResourceTypes',
    description: postmanGetResourceTypes.description!,
    tool: postmanGetResourceTypes,
    ...authed(0),
    scope: 'read' as const,
    keywords: ['sso', 'scim'],
  },
  {
    name: 'postmanGetServiceProviderConfiguration',
    description: postmanGetServiceProviderConfiguration.description!,
    tool: postmanGetServiceProviderConfiguration,
    ...authed(0),
    scope: 'read' as const,
    keywords: ['sso', 'scim'],
  },
  {
    name: 'postmanGetBillingAccountDetails',
    description: postmanGetBillingAccountDetails.description!,
    tool: postmanGetBillingAccountDetails,
    ...authed(0),
    scope: 'read' as const,
    keywords: ['cost', 'payment', 'subscription'],
  },
  {
    name: 'postmanListAccountInvoices',
    description: postmanListAccountInvoices.description!,
    tool: postmanListAccountInvoices,
    ...authed(0),
    scope: 'read' as const,
    keywords: ['cost', 'payment', 'billing'],
  },
  {
    name: 'postmanCreateAWebhook',
    description: postmanCreateAWebhook.description!,
    tool: postmanCreateAWebhook,
    ...authed(0),
    scope: 'write' as const,
    keywords: ['ci', 'trigger'],
  },
];
