// @ts-nocheck
import {
    addProblemComment,
    closeProblem,
    deleteProblemComment,
    getProblem,
    getSecurityProblem,
    listProblemComments,
    listProblems,
    listSecurityProblems,
    updateProblemComment,
} from './problems.js';
import { deleteMetric, getMetric, ingestMetrics, listMetrics, queryMetrics } from './metrics.js';
import {
    addTags,
    deleteTag,
    getEntity,
    getEntityType,
    listEntities,
    listEntityTypes,
    listTags,
} from './entities.js';
import { getEvent, ingestEvent, listEventTypes, listEvents } from './events.js';
import { exportLogs, ingestLogs, queryGrail } from './logs.js';
import { createSLO, deleteSLO, getSLO, listSLOs, updateSLO } from './slo.js';
import {
    createSettingObject,
    deleteSettingObject,
    getSettingObject,
    listSettingObjects,
    listSettingSchemas,
    updateSettingObject,
} from './settings.js';
import {
    createApiToken,
    deleteApiToken,
    getApiToken,
    getAuditLog,
    listApiTokens,
    listAuditLogs,
    lookupApiToken,
    updateApiToken,
} from './admin.js';
import {
    deleteExtension,
    getExtension,
    getSyntheticMonitor,
    listExtensionVersions,
    listExtensions,
    listSyntheticMonitors,
} from './extensions.js';

export {
    listProblems,
    getProblem,
    closeProblem,
    listProblemComments,
    addProblemComment,
    updateProblemComment,
    deleteProblemComment,
    listSecurityProblems,
    getSecurityProblem,
    listMetrics,
    getMetric,
    queryMetrics,
    ingestMetrics,
    deleteMetric,
    listEntities,
    getEntity,
    listEntityTypes,
    getEntityType,
    listTags,
    addTags,
    deleteTag,
    listEvents,
    getEvent,
    listEventTypes,
    ingestEvent,
    exportLogs,
    ingestLogs,
    queryGrail,
    listSLOs,
    getSLO,
    createSLO,
    updateSLO,
    deleteSLO,
    listSettingSchemas,
    listSettingObjects,
    getSettingObject,
    createSettingObject,
    updateSettingObject,
    deleteSettingObject,
    listAuditLogs,
    getAuditLog,
    listApiTokens,
    getApiToken,
    createApiToken,
    updateApiToken,
    deleteApiToken,
    lookupApiToken,
    listExtensions,
    listExtensionVersions,
    getExtension,
    deleteExtension,
    listSyntheticMonitors,
    getSyntheticMonitor,
};

const auth = 'dynatraceCredentials' as const;

type Scope = 'read' | 'write' | 'delete';
function entry(
    name: string,
    description: string,
    toolRef: any,
    scope: Scope,
): { name: string; description: string; tool: any; requiredAuth: typeof auth; scope: Scope } {
    return { name, description, tool: toolRef, requiredAuth: auth, scope };
}

export const dynatraceTools = [
    entry('dynatraceListProblems', 'List Davis AI problems (open incidents) with severity, status and affected entities. Start here for triage.', listProblems, 'read'),
    entry('dynatraceGetProblem', 'Get a single Davis problem with evidence, root cause and comments.', getProblem, 'read'),
    entry('dynatraceCloseProblem', 'Manually close an open Davis problem with a closing comment.', closeProblem, 'write'),
    entry('dynatraceListProblemComments', 'List comments on a Davis problem.', listProblemComments, 'read'),
    entry('dynatraceAddProblemComment', 'Add a comment to a Davis problem.', addProblemComment, 'write'),
    entry('dynatraceUpdateProblemComment', 'Update a comment on a Davis problem.', updateProblemComment, 'write'),
    entry('dynatraceDeleteProblemComment', 'Delete a comment from a Davis problem.', deleteProblemComment, 'delete'),
    entry('dynatraceListSecurityProblems', 'List application-security vulnerabilities with risk scores and CVE references.', listSecurityProblems, 'read'),
    entry('dynatraceGetSecurityProblem', 'Get a single security problem with vulnerabilities and remediation.', getSecurityProblem, 'read'),
    entry('dynatraceListMetrics', 'List metric definitions. Use to discover metric keys before querying.', listMetrics, 'read'),
    entry('dynatraceGetMetric', 'Get one metric definition with unit, dimensions and aggregations.', getMetric, 'read'),
    entry('dynatraceQueryMetrics', 'Query metric datapoints with a metric selector expression.', queryMetrics, 'read'),
    entry('dynatraceIngestMetrics', 'Ingest custom metric datapoints in line protocol.', ingestMetrics, 'write'),
    entry('dynatraceDeleteMetric', 'Delete a custom metric definition and its data.', deleteMetric, 'delete'),
    entry('dynatraceListEntities', 'List monitored entities (Smartscape) with an entity selector. Use to resolve entity IDs.', listEntities, 'read'),
    entry('dynatraceGetEntity', 'Get one monitored entity with properties, tags and relations.', getEntity, 'read'),
    entry('dynatraceListEntityTypes', 'List all entity types known to the environment.', listEntityTypes, 'read'),
    entry('dynatraceGetEntityType', 'Get properties and capabilities of one entity type.', getEntityType, 'read'),
    entry('dynatraceListTags', 'List custom tags on entities matching a selector.', listTags, 'read'),
    entry('dynatraceAddTags', 'Add custom tags to entities matching a selector.', addTags, 'write'),
    entry('dynatraceDeleteTag', 'Delete a tag from entities matching a selector.', deleteTag, 'delete'),
    entry('dynatraceListEvents', 'List events (deployments, config changes, availability) in a timeframe.', listEvents, 'read'),
    entry('dynatraceGetEvent', 'Get a single event by ID.', getEvent, 'read'),
    entry('dynatraceListEventTypes', 'List event types (CUSTOM_DEPLOYMENT, CUSTOM_INFO, ...).', listEventTypes, 'read'),
    entry('dynatraceIngestEvent', 'Push a custom event (deployment markers, annotations) to Dynatrace.', ingestEvent, 'write'),
    entry('dynatraceExportLogs', 'Search/export log records with a log query.', exportLogs, 'read'),
    entry('dynatraceIngestLogs', 'Ingest log records into Dynatrace.', ingestLogs, 'write'),
    entry('dynatraceQueryGrail', 'Run a DQL query against Grail buckets (logs, spans, events) with polling to completion.', queryGrail, 'read'),
    entry('dynatraceListSLOs', 'List service-level objectives with targets and error budgets.', listSLOs, 'read'),
    entry('dynatraceGetSLO', 'Get a single SLO with objectives and error budget.', getSLO, 'read'),
    entry('dynatraceCreateSLO', 'Create a service-level objective.', createSLO, 'write'),
    entry('dynatraceUpdateSLO', 'Update a service-level objective.', updateSLO, 'write'),
    entry('dynatraceDeleteSLO', 'Delete a service-level objective.', deleteSLO, 'delete'),
    entry('dynatraceListSettingSchemas', 'List Settings 2.0 schemas. Use to find schema IDs.', listSettingSchemas, 'read'),
    entry('dynatraceListSettingObjects', 'List Settings 2.0 objects (alerting profiles, auto-tags, ...).', listSettingObjects, 'read'),
    entry('dynatraceGetSettingObject', 'Get one Settings 2.0 object with value and scope.', getSettingObject, 'read'),
    entry('dynatraceCreateSettingObject', 'Create Settings 2.0 object(s).', createSettingObject, 'write'),
    entry('dynatraceUpdateSettingObject', 'Update a Settings 2.0 object value.', updateSettingObject, 'write'),
    entry('dynatraceDeleteSettingObject', 'Delete a Settings 2.0 object.', deleteSettingObject, 'delete'),
    entry('dynatraceListAuditLogs', 'List environment audit log entries (who changed what).', listAuditLogs, 'read'),
    entry('dynatraceGetAuditLog', 'Get a single audit log entry by ID.', getAuditLog, 'read'),
    entry('dynatraceListApiTokens', 'List API tokens with owners, scopes and expiration.', listApiTokens, 'read'),
    entry('dynatraceGetApiToken', 'Get one API token metadata (never the secret).', getApiToken, 'read'),
    entry('dynatraceCreateApiToken', 'Create an API token with scopes (secret returned once).', createApiToken, 'write'),
    entry('dynatraceUpdateApiToken', 'Update an API token (name, enabled, scopes).', updateApiToken, 'write'),
    entry('dynatraceDeleteApiToken', 'Delete (revoke) an API token.', deleteApiToken, 'delete'),
    entry('dynatraceLookupApiToken', 'Look up what a token value belongs to (owner, scopes).', lookupApiToken, 'read'),
    entry('dynatraceListExtensions', 'List Extensions 2.0 in the environment.', listExtensions, 'read'),
    entry('dynatraceListExtensionVersions', 'List all uploaded versions of one extension.', listExtensionVersions, 'read'),
    entry('dynatraceGetExtension', 'Get one extension version with data sources and alerts.', getExtension, 'read'),
    entry('dynatraceDeleteExtension', 'Delete one extension version.', deleteExtension, 'delete'),
    entry('dynatraceListSyntheticMonitors', 'List synthetic monitors (browser, HTTP, clickpath).', listSyntheticMonitors, 'read'),
    entry('dynatraceGetSyntheticMonitor', 'Get the full configuration of one synthetic monitor.', getSyntheticMonitor, 'read'),
];
