import { defineToolkit, defineTool } from '../../core/define.js';
import { inferToolScope } from '../../core/scope.js';
import { HUBSPOT_ICON } from './icon.js';
import { hubspotTools } from './tools/index.js';

export default defineToolkit({
  id: 'hubspot',
  displayName: 'HubSpot',
  shortDescription:
    'CRM contacts, companies, deals, tickets, marketing emails, campaigns, workflows and timelines.',
  category: 'CRM',
  icon: HUBSPOT_ICON,
  auth: {
    type: 'oauth2',
    tokenField: 'hubspotToken',
    provider: {
      slug: 'hubspot',
      env: { clientId: 'HUBSPOT_CLIENT_ID', clientSecret: 'HUBSPOT_CLIENT_SECRET' },
      authorizeUrl: 'https://app.hubspot.com/oauth/authorize',
      tokenUrl: 'https://api.hubapi.com/oauth/v1/token',
      scopes: [
        'oauth',
        'content',
        'tickets',
        'e-commerce',
        'automation',
        'timeline',
        'contacts',
        'conversations.read',
        'sales-email-read',
        'crm.import',
        'crm.lists.read',
        'crm.lists.write',
        'crm.objects.contacts.read',
        'crm.objects.contacts.write',
        'crm.objects.companies.read',
        'crm.objects.companies.write',
        'crm.objects.deals.read',
        'crm.objects.deals.write',
        'crm.objects.emails.read',
        'crm.objects.emails.write',
        'crm.objects.feedback_submissions.read',
        'crm.objects.feedback_submissions.write',
        'crm.objects.line_items.read',
        'crm.objects.line_items.write',
        'crm.objects.owners.read',
        'crm.objects.calls.read',
        'crm.objects.calls.write',
        'crm.objects.meetings.read',
        'crm.objects.custom.read',
        'crm.objects.custom.write',
        'crm.objects.quotes.read',
        'crm.objects.quotes.write',
        'crm.schemas.contacts.read',
        'crm.schemas.contacts.write',
        'crm.schemas.companies.read',
        'crm.schemas.companies.write',
        'crm.schemas.deals.read',
        'crm.schemas.deals.write',
        'crm.schemas.custom.read',
        'crm.schemas.custom.write',
        'crm.schemas.quotes.read',
        'crm.schemas.line_items.read',
        'crm.segments.read',
        'crm.segments.write',
        'marketing.campaigns.read',
        'marketing.campaigns.write',
        'marketing-email',
        'transactional-email',
        'account-info.security.read',
        'automation.sequences.read',
        'developers-read',
        'developers-write',
      ],
      exchangeStyle: 'form',
      connectDescription:
        'Connect HubSpot with OAuth to manage CRM records, marketing emails, campaigns, workflows and timelines. Create a HubSpot app (App settings > Auth) to get a client ID and secret. Tokens are sent as Authorization: Bearer to api.hubapi.com. Scope availability depends on your HubSpot plan and app configuration.',
      callbackPath: '/api/auth/hubspot/callback',
      stateCookie: 'hubspot_oauth_state',
    },
  },
  allowedHosts: ['api.hubapi.com', 'app.hubspot.com'],
  tools: hubspotTools.map((entry) =>
    defineTool({
      name: entry.name,
      description: entry.description,
      tool: entry.tool,
      requiredAuth: entry.requiredAuth,
      scope: (entry as { scope?: 'read' | 'write' | 'delete' }).scope ?? inferToolScope(entry.name),
      keywords: (entry as { keywords?: string[] }).keywords ?? [],
    }),
  ),
  meta: {
    since: '0.0.13',
    homepage: 'https://www.hubspot.com',
    docsUrl: 'https://developers.hubspot.com/docs/api-reference',
    apiDocsUrl: 'https://developers.hubspot.com/docs/api-reference',
  },
});
