// @ts-nocheck
import {
  sentryCreateAnAlertForAnOrganization,
  sentryCreateOrganizationAlertRule,
  sentryCreateProjectRuleForAlerts,
  sentryDeleteAnAlert,
  sentryDeleteBulkAlerts,
  sentryDeleteOrganizationAlertRule,
  sentryDeleteOrgNotificationAction,
  sentryDeleteProjectRule,
  sentryFetchAlerts,
  sentryFetchAnAlert,
  sentryFetchOrganizationAlertRules,
  sentryGetActivationOfAlertRuleForOrganization,
  sentryGetAlerts,
  sentryGetProjectRuleDetails,
  sentryModifyOrganizationNotificationAction,
  sentryMutateAnOrganizationSAlerts,
  sentryRetrieveAlertRuleDetails,
  sentryRetrieveNotificationActionByOrgId,
  sentryRetrieveProjectRulesByOrgAndProjectId,
  sentrySubmitNotificationActionApiData,
  sentryUpdateAnAlertById,
  sentryUpdateOrganizationAlertRules,
  sentryUpdateProjectRuleById,
  sentryViewOrganizationNotificationActions,
} from './alerts.js';
import {
  sentryCreateDashboardWithWidgets,
  sentryDeleteOrganizationDashboard,
  sentryDeleteOrganizationDiscoverQuery,
  sentryListOrganizationDashboards,
  sentryRetrieveAggregatedTestResultMetrics,
  sentryRetrieveOrganizationDashboard,
  sentryRetrieveSavedDiscoverQueries,
  sentryRetrieveSavedDiscoverQueryForOrganization,
  sentrySaveOrganizationDiscoverQuery,
  sentryUpdateOrganizationDashboard,
  sentryUpdateSavedQueryForOrganization,
} from './dashboards.js';
import {
  sentryGetProjectEvents,
  sentryListAProjectsUserFeedback,
  sentryQueryExploreEventsInTimeseriesFormat,
  sentryRetrieveOrganizationEvents,
  sentryRetrieveProjectEventById,
  sentryRetrieveSourceMapDebugEvent,
  sentrySubmitUserFeedback,
} from './events.js';
import {
  sentryCreateProjectWebhookSubscription,
  sentryCreateSentryExternalIssueLink,
  sentryDeleteACustomIntegration,
  sentryDeleteExternalIssueByUuid,
  sentryDeleteOrganizationIntegration,
  sentryDeleteProjectHook,
  sentryGetIntegrationDetailsByOrg,
  sentryGetProjectHook,
  sentryGetSentryAppInstallationsForOrganization,
  sentryListSeerAiModels,
  sentryRetrieveACustomIntegrationByIdOrSlug,
  sentryRetrieveOrganizationIntegrationsList,
  sentryRetrieveOrgIntegrationConfig,
  sentryRetrieveProjectHooks,
  sentryRetrieveSeerIssueFixState,
  sentryRetrieveTheCustomIntegsCreatedByAnOrg,
  sentryStartSeerIssueFix,
  sentryUpdateAnExistingCustomIntegration,
  sentryUpdateWebhookConfigurationXp,
} from './integrations.js';
import {
  sentryBulkMutateAnOrganizationsIssues,
  sentryBulkRemoveAnOrganizationsIssues,
  sentryDeleteOrganizationIssue,
  sentryDeleteProjectIssues,
  sentryFetchIssueEventById,
  sentryFetchTagValuesForIssue,
  sentryGetOldestEvent,
  sentryGetOrganizationIssueDetails,
  sentryListAnOrganizationsIssues,
  sentryListATagsValuesForAnIssue,
  sentryRetrieveCustomIntegIssueLinksGivenSentryIssue,
  sentryRetrieveEventIdForOrganization,
  sentryRetrieveIssueEventsById,
  sentryRetrieveIssueHashesForOrganization,
  sentryRetrieveIssueTagDetails,
  sentryRetrieveProjectIssuesList,
  sentryRetrieveShortIdForOrganization,
  sentryUpdateIssueAttributesInOrganization,
  sentryUpdateProjectIssueStatusAndDetails,
} from './issues.js';
import {
  sentryAddOrganizationMemberViaEmail,
  sentryAddRemoveUserEmailById,
  sentryCreateExternalUserForOrganization,
  sentryCreateScimGroupForOrganization,
  sentryCreateUserForSamlIntegration,
  sentryDeleteExternalUserFromOrganization,
  sentryDeleteOrganizationMember,
  sentryDeleteTeamFromOrgScimV2,
  sentryDeleteUserEmailsById,
  sentryDeleteUserFromOrg,
  sentryGetScimGroupByTeamId,
  sentryListOrganizationMembers,
  sentryListOrganizationUserTeams,
  sentryListScimV2OrganizationUsers,
  sentryPatchScimGroupOperations,
  sentryPatchUserActiveStatusInOrganization,
  sentryRetrieveOrganizationMember,
  sentryRetrieveOrganizationScimGroups,
  sentryRetrieveUserEmailInformation,
  sentryRetrieveUserViaScimApi,
  sentryUpdateExternalUserForOrganization,
  sentryUpdateOrganizationMemberRole,
  sentryUpdateUserEmail,
} from './members.js';
import {
  sentryCreateOrganizationMonitor,
  sentryDeleteOrganizationMonitor,
  sentryDeleteProjectMonitor,
  sentryFetchAMonitor,
  sentryFetchAnOrganizationsMonitors,
  sentryGetProjectMonitorById,
  sentryMutateAnOrganizationsMonitors,
  sentryRetrieveAMonitor,
  sentryRetrieveMonitorCheckins,
  sentryRetrieveMonitorCheckinsByOrg,
  sentryRetrieveOrganizationMonitors,
  sentryUpdateAMonitor,
  sentryUpdateAMonitorById,
  sentryUpdateMonitorForProject,
} from './monitors.js';
import {
  sentryDisableSpikeProtection,
  sentryFetchOrganizationReleaseThresholdStatuses,
  sentryGetOrganizationByIdOrSlug,
  sentryGetOrganizationDetails,
  sentryGetOrganizationEnvironments,
  sentryGetOrganizationSessions,
  sentryGetOrganizationStatsSummary,
  sentryListAnOrganizationSClientKeys,
  sentryListOrganizations,
  sentryModifyOrganizationSettings,
  sentryPostSpikeProtectionForOrganization,
  sentryRetrieveDataForwardersForAnOrganization,
  sentryRetrieveOrganizationRelayUsage,
  sentryRetrieveOrganizationStatsV2,
  sentryValidateCredential,
} from './organizations.js';
import {
  sentryAccessProjectInformation,
  sentryAddASymbolSourceToAProject,
  sentryAddTeamToProject,
  sentryCreateProjectKeyWithOptionalRateLimiting,
  sentryCreateTeamProjectForOrganization,
  sentryDeleteDsymsForProject,
  sentryDeleteProjectById,
  sentryDeleteProjectKey,
  sentryDeleteProjectTeamAssociation,
  sentryDeleteSymbolSourceFromProject,
  sentryFetchProjectEnvironmentDetails,
  sentryFetchProjectOwnershipDetails,
  sentryGetProjectEventStats,
  sentryGetProjectList,
  sentryListProjectTags,
  sentryListProjectUsers,
  sentryRetrieveDsymFilesForProject,
  sentryRetrieveOrganizationProjects,
  sentryRetrieveProjectEnvironments,
  sentryRetrieveProjectFilterData,
  sentryRetrieveProjectKeyDetails,
  sentryRetrieveProjectKeysByOrgAndProject,
  sentryRetrieveProjectMembersList,
  sentryRetrieveProjectSymbolSources,
  sentryRetrieveProjectTagValues,
  sentryRetrieveProjectTeams,
  sentryToggleProjectFilterStatus,
  sentryUpdateAProjectsSymbolSource,
  sentryUpdateEnvironmentVisibility,
  sentryUpdateProjectDetails,
  sentryUpdateProjectKeyConfiguration,
  sentryUpdateProjectOwnershipSettings,
  sentryUploadDsymsFileToProject,
} from './projects.js';
import {
  sentryCreateReleaseDeployForOrg,
  sentryCreateReleaseForOrganization,
  sentryDeleteOrganizationRelease,
  sentryDeleteOrganizationReleaseFile,
  sentryDeleteReleaseFileById,
  sentryFetchProjectReleaseFiles,
  sentryGetOrganizationReleaseVersion,
  sentryListOrganizationReleases,
  sentryListOrganizationRepositories,
  sentryModifyReleaseFileAttributes,
  sentryRetrieveCommitFilesForRelease,
  sentryRetrieveCommitsForOrganizationRepo,
  sentryRetrieveFilesForRelease,
  sentryRetrieveOrganizationReleaseCommits,
  sentryRetrievePaginatedRepositoryTokens,
  sentryRetrieveProjectReleaseFileDetails,
  sentryRetrieveReleaseCommits,
  sentryRetrieveReleaseDeployments,
  sentryRetrieveReleaseFileById,
  sentryUpdateProjectReleaseFileDetails,
  sentryUpdateReleaseDetailsForOrganization,
  sentryUploadFileToProjectRelease,
  sentryUploadReleaseFileToOrganization,
} from './releases.js';
import {
  sentryDeleteProjectReplay,
  sentryFetchOrganizationReplayCount,
  sentryFetchOrganizationReplayDetails,
  sentryFetchOrganizationReplaySelectors,
  sentryFetchProjectReplayClicks,
  sentryFetchReplayRecordingSegment,
  sentryGetWhoViewedReplayByProject,
  sentryRetrieveOrganizationReplays,
  sentryRetrieveReplayRecordingSegments,
} from './replays.js';
import {
  sentryAddTeamMemberInOrganization,
  sentryCreateOrganizationTeam,
  sentryDeleteExternalTeamById,
  sentryDeleteMemberFromTeam,
  sentryDeleteTeamByOrganizationOrTeamSlug,
  sentryGetTeamMembersByIdOrSlug,
  sentryListTeamsInOrganization,
  sentryManageTeamExternalIntegrations,
  sentryRetrieveTeamInfoViaOrganizationIdOrSlug,
  sentryRetrieveTeamProjects,
  sentrySwitchTeamRoleForMember,
  sentryUpdateExternalTeamIntegration,
  sentryUpdateTeamInformationByOrganizationId,
} from './teams.js';
import { sentryIngestEventViaDsn } from './ingest.js';

export { sentryCreateAnAlertForAnOrganization, sentryCreateOrganizationAlertRule, sentryCreateProjectRuleForAlerts, sentryDeleteAnAlert, sentryDeleteBulkAlerts, sentryDeleteOrganizationAlertRule, sentryDeleteOrgNotificationAction, sentryDeleteProjectRule, sentryFetchAlerts, sentryFetchAnAlert, sentryFetchOrganizationAlertRules, sentryGetActivationOfAlertRuleForOrganization, sentryGetAlerts, sentryGetProjectRuleDetails, sentryModifyOrganizationNotificationAction, sentryMutateAnOrganizationSAlerts, sentryRetrieveAlertRuleDetails, sentryRetrieveNotificationActionByOrgId, sentryRetrieveProjectRulesByOrgAndProjectId, sentrySubmitNotificationActionApiData, sentryUpdateAnAlertById, sentryUpdateOrganizationAlertRules, sentryUpdateProjectRuleById, sentryViewOrganizationNotificationActions } from './alerts.js';
export { sentryCreateDashboardWithWidgets, sentryDeleteOrganizationDashboard, sentryDeleteOrganizationDiscoverQuery, sentryListOrganizationDashboards, sentryRetrieveAggregatedTestResultMetrics, sentryRetrieveOrganizationDashboard, sentryRetrieveSavedDiscoverQueries, sentryRetrieveSavedDiscoverQueryForOrganization, sentrySaveOrganizationDiscoverQuery, sentryUpdateOrganizationDashboard, sentryUpdateSavedQueryForOrganization } from './dashboards.js';
export { sentryGetProjectEvents, sentryListAProjectsUserFeedback, sentryQueryExploreEventsInTimeseriesFormat, sentryRetrieveOrganizationEvents, sentryRetrieveProjectEventById, sentryRetrieveSourceMapDebugEvent, sentrySubmitUserFeedback } from './events.js';
export { sentryCreateProjectWebhookSubscription, sentryCreateSentryExternalIssueLink, sentryDeleteACustomIntegration, sentryDeleteExternalIssueByUuid, sentryDeleteOrganizationIntegration, sentryDeleteProjectHook, sentryGetIntegrationDetailsByOrg, sentryGetProjectHook, sentryGetSentryAppInstallationsForOrganization, sentryListSeerAiModels, sentryRetrieveACustomIntegrationByIdOrSlug, sentryRetrieveOrganizationIntegrationsList, sentryRetrieveOrgIntegrationConfig, sentryRetrieveProjectHooks, sentryRetrieveSeerIssueFixState, sentryRetrieveTheCustomIntegsCreatedByAnOrg, sentryStartSeerIssueFix, sentryUpdateAnExistingCustomIntegration, sentryUpdateWebhookConfigurationXp } from './integrations.js';
export { sentryBulkMutateAnOrganizationsIssues, sentryBulkRemoveAnOrganizationsIssues, sentryDeleteOrganizationIssue, sentryDeleteProjectIssues, sentryFetchIssueEventById, sentryFetchTagValuesForIssue, sentryGetOldestEvent, sentryGetOrganizationIssueDetails, sentryListAnOrganizationsIssues, sentryListATagsValuesForAnIssue, sentryRetrieveCustomIntegIssueLinksGivenSentryIssue, sentryRetrieveEventIdForOrganization, sentryRetrieveIssueEventsById, sentryRetrieveIssueHashesForOrganization, sentryRetrieveIssueTagDetails, sentryRetrieveProjectIssuesList, sentryRetrieveShortIdForOrganization, sentryUpdateIssueAttributesInOrganization, sentryUpdateProjectIssueStatusAndDetails } from './issues.js';
export { sentryAddOrganizationMemberViaEmail, sentryAddRemoveUserEmailById, sentryCreateExternalUserForOrganization, sentryCreateScimGroupForOrganization, sentryCreateUserForSamlIntegration, sentryDeleteExternalUserFromOrganization, sentryDeleteOrganizationMember, sentryDeleteTeamFromOrgScimV2, sentryDeleteUserEmailsById, sentryDeleteUserFromOrg, sentryGetScimGroupByTeamId, sentryListOrganizationMembers, sentryListOrganizationUserTeams, sentryListScimV2OrganizationUsers, sentryPatchScimGroupOperations, sentryPatchUserActiveStatusInOrganization, sentryRetrieveOrganizationMember, sentryRetrieveOrganizationScimGroups, sentryRetrieveUserEmailInformation, sentryRetrieveUserViaScimApi, sentryUpdateExternalUserForOrganization, sentryUpdateOrganizationMemberRole, sentryUpdateUserEmail } from './members.js';
export { sentryCreateOrganizationMonitor, sentryDeleteOrganizationMonitor, sentryDeleteProjectMonitor, sentryFetchAMonitor, sentryFetchAnOrganizationsMonitors, sentryGetProjectMonitorById, sentryMutateAnOrganizationsMonitors, sentryRetrieveAMonitor, sentryRetrieveMonitorCheckins, sentryRetrieveMonitorCheckinsByOrg, sentryRetrieveOrganizationMonitors, sentryUpdateAMonitor, sentryUpdateAMonitorById, sentryUpdateMonitorForProject } from './monitors.js';
export { sentryDisableSpikeProtection, sentryFetchOrganizationReleaseThresholdStatuses, sentryGetOrganizationByIdOrSlug, sentryGetOrganizationDetails, sentryGetOrganizationEnvironments, sentryGetOrganizationSessions, sentryGetOrganizationStatsSummary, sentryListAnOrganizationSClientKeys, sentryListOrganizations, sentryModifyOrganizationSettings, sentryPostSpikeProtectionForOrganization, sentryRetrieveDataForwardersForAnOrganization, sentryRetrieveOrganizationRelayUsage, sentryRetrieveOrganizationStatsV2, sentryValidateCredential } from './organizations.js';
export { sentryAccessProjectInformation, sentryAddASymbolSourceToAProject, sentryAddTeamToProject, sentryCreateProjectKeyWithOptionalRateLimiting, sentryCreateTeamProjectForOrganization, sentryDeleteDsymsForProject, sentryDeleteProjectById, sentryDeleteProjectKey, sentryDeleteProjectTeamAssociation, sentryDeleteSymbolSourceFromProject, sentryFetchProjectEnvironmentDetails, sentryFetchProjectOwnershipDetails, sentryGetProjectEventStats, sentryGetProjectList, sentryListProjectTags, sentryListProjectUsers, sentryRetrieveDsymFilesForProject, sentryRetrieveOrganizationProjects, sentryRetrieveProjectEnvironments, sentryRetrieveProjectFilterData, sentryRetrieveProjectKeyDetails, sentryRetrieveProjectKeysByOrgAndProject, sentryRetrieveProjectMembersList, sentryRetrieveProjectSymbolSources, sentryRetrieveProjectTagValues, sentryRetrieveProjectTeams, sentryToggleProjectFilterStatus, sentryUpdateAProjectsSymbolSource, sentryUpdateEnvironmentVisibility, sentryUpdateProjectDetails, sentryUpdateProjectKeyConfiguration, sentryUpdateProjectOwnershipSettings, sentryUploadDsymsFileToProject } from './projects.js';
export { sentryCreateReleaseDeployForOrg, sentryCreateReleaseForOrganization, sentryDeleteOrganizationRelease, sentryDeleteOrganizationReleaseFile, sentryDeleteReleaseFileById, sentryFetchProjectReleaseFiles, sentryGetOrganizationReleaseVersion, sentryListOrganizationReleases, sentryListOrganizationRepositories, sentryModifyReleaseFileAttributes, sentryRetrieveCommitFilesForRelease, sentryRetrieveCommitsForOrganizationRepo, sentryRetrieveFilesForRelease, sentryRetrieveOrganizationReleaseCommits, sentryRetrievePaginatedRepositoryTokens, sentryRetrieveProjectReleaseFileDetails, sentryRetrieveReleaseCommits, sentryRetrieveReleaseDeployments, sentryRetrieveReleaseFileById, sentryUpdateProjectReleaseFileDetails, sentryUpdateReleaseDetailsForOrganization, sentryUploadFileToProjectRelease, sentryUploadReleaseFileToOrganization } from './releases.js';
export { sentryDeleteProjectReplay, sentryFetchOrganizationReplayCount, sentryFetchOrganizationReplayDetails, sentryFetchOrganizationReplaySelectors, sentryFetchProjectReplayClicks, sentryFetchReplayRecordingSegment, sentryGetWhoViewedReplayByProject, sentryRetrieveOrganizationReplays, sentryRetrieveReplayRecordingSegments } from './replays.js';
export { sentryAddTeamMemberInOrganization, sentryCreateOrganizationTeam, sentryDeleteExternalTeamById, sentryDeleteMemberFromTeam, sentryDeleteTeamByOrganizationOrTeamSlug, sentryGetTeamMembersByIdOrSlug, sentryListTeamsInOrganization, sentryManageTeamExternalIntegrations, sentryRetrieveTeamInfoViaOrganizationIdOrSlug, sentryRetrieveTeamProjects, sentrySwitchTeamRoleForMember, sentryUpdateExternalTeamIntegration, sentryUpdateTeamInformationByOrganizationId } from './teams.js';
export { sentryIngestEventViaDsn };

const auth = 'sentryToken' as const;

export const sentryTools = [
  { name: 'sentryCreateAnAlertForAnOrganization', description: sentryCreateAnAlertForAnOrganization.description!, tool: sentryCreateAnAlertForAnOrganization, requiredAuth: auth, scope: 'write' as const },
  { name: 'sentryCreateOrganizationAlertRule', description: sentryCreateOrganizationAlertRule.description!, tool: sentryCreateOrganizationAlertRule, requiredAuth: auth, scope: 'write' as const },
  { name: 'sentryCreateProjectRuleForAlerts', description: sentryCreateProjectRuleForAlerts.description!, tool: sentryCreateProjectRuleForAlerts, requiredAuth: auth, scope: 'write' as const },
  { name: 'sentryDeleteAnAlert', description: sentryDeleteAnAlert.description!, tool: sentryDeleteAnAlert, requiredAuth: auth, scope: 'delete' as const },
  { name: 'sentryDeleteBulkAlerts', description: sentryDeleteBulkAlerts.description!, tool: sentryDeleteBulkAlerts, requiredAuth: auth, scope: 'delete' as const },
  { name: 'sentryDeleteOrganizationAlertRule', description: sentryDeleteOrganizationAlertRule.description!, tool: sentryDeleteOrganizationAlertRule, requiredAuth: auth, scope: 'delete' as const },
  { name: 'sentryDeleteOrgNotificationAction', description: sentryDeleteOrgNotificationAction.description!, tool: sentryDeleteOrgNotificationAction, requiredAuth: auth, scope: 'delete' as const },
  { name: 'sentryDeleteProjectRule', description: sentryDeleteProjectRule.description!, tool: sentryDeleteProjectRule, requiredAuth: auth, scope: 'delete' as const },
  { name: 'sentryFetchAlerts', description: sentryFetchAlerts.description!, tool: sentryFetchAlerts, requiredAuth: auth, scope: 'read' as const },
  { name: 'sentryFetchAnAlert', description: sentryFetchAnAlert.description!, tool: sentryFetchAnAlert, requiredAuth: auth, scope: 'read' as const },
  { name: 'sentryFetchOrganizationAlertRules', description: sentryFetchOrganizationAlertRules.description!, tool: sentryFetchOrganizationAlertRules, requiredAuth: auth, scope: 'read' as const },
  { name: 'sentryGetActivationOfAlertRuleForOrganization', description: sentryGetActivationOfAlertRuleForOrganization.description!, tool: sentryGetActivationOfAlertRuleForOrganization, requiredAuth: auth, scope: 'read' as const },
  { name: 'sentryGetAlerts', description: sentryGetAlerts.description!, tool: sentryGetAlerts, requiredAuth: auth, scope: 'read' as const },
  { name: 'sentryGetProjectRuleDetails', description: sentryGetProjectRuleDetails.description!, tool: sentryGetProjectRuleDetails, requiredAuth: auth, scope: 'read' as const },
  { name: 'sentryModifyOrganizationNotificationAction', description: sentryModifyOrganizationNotificationAction.description!, tool: sentryModifyOrganizationNotificationAction, requiredAuth: auth, scope: 'write' as const },
  { name: 'sentryMutateAnOrganizationSAlerts', description: sentryMutateAnOrganizationSAlerts.description!, tool: sentryMutateAnOrganizationSAlerts, requiredAuth: auth, scope: 'write' as const },
  { name: 'sentryRetrieveAlertRuleDetails', description: sentryRetrieveAlertRuleDetails.description!, tool: sentryRetrieveAlertRuleDetails, requiredAuth: auth, scope: 'read' as const },
  { name: 'sentryRetrieveNotificationActionByOrgId', description: sentryRetrieveNotificationActionByOrgId.description!, tool: sentryRetrieveNotificationActionByOrgId, requiredAuth: auth, scope: 'read' as const },
  { name: 'sentryRetrieveProjectRulesByOrgAndProjectId', description: sentryRetrieveProjectRulesByOrgAndProjectId.description!, tool: sentryRetrieveProjectRulesByOrgAndProjectId, requiredAuth: auth, scope: 'read' as const },
  { name: 'sentrySubmitNotificationActionApiData', description: sentrySubmitNotificationActionApiData.description!, tool: sentrySubmitNotificationActionApiData, requiredAuth: auth, scope: 'write' as const },
  { name: 'sentryUpdateAnAlertById', description: sentryUpdateAnAlertById.description!, tool: sentryUpdateAnAlertById, requiredAuth: auth, scope: 'write' as const },
  { name: 'sentryUpdateOrganizationAlertRules', description: sentryUpdateOrganizationAlertRules.description!, tool: sentryUpdateOrganizationAlertRules, requiredAuth: auth, scope: 'write' as const },
  { name: 'sentryUpdateProjectRuleById', description: sentryUpdateProjectRuleById.description!, tool: sentryUpdateProjectRuleById, requiredAuth: auth, scope: 'write' as const },
  { name: 'sentryViewOrganizationNotificationActions', description: sentryViewOrganizationNotificationActions.description!, tool: sentryViewOrganizationNotificationActions, requiredAuth: auth, scope: 'read' as const },
  { name: 'sentryCreateDashboardWithWidgets', description: sentryCreateDashboardWithWidgets.description!, tool: sentryCreateDashboardWithWidgets, requiredAuth: auth, scope: 'write' as const },
  { name: 'sentryDeleteOrganizationDashboard', description: sentryDeleteOrganizationDashboard.description!, tool: sentryDeleteOrganizationDashboard, requiredAuth: auth, scope: 'delete' as const },
  { name: 'sentryDeleteOrganizationDiscoverQuery', description: sentryDeleteOrganizationDiscoverQuery.description!, tool: sentryDeleteOrganizationDiscoverQuery, requiredAuth: auth, scope: 'delete' as const },
  { name: 'sentryListOrganizationDashboards', description: sentryListOrganizationDashboards.description!, tool: sentryListOrganizationDashboards, requiredAuth: auth, scope: 'read' as const },
  { name: 'sentryRetrieveAggregatedTestResultMetrics', description: sentryRetrieveAggregatedTestResultMetrics.description!, tool: sentryRetrieveAggregatedTestResultMetrics, requiredAuth: auth, scope: 'read' as const },
  { name: 'sentryRetrieveOrganizationDashboard', description: sentryRetrieveOrganizationDashboard.description!, tool: sentryRetrieveOrganizationDashboard, requiredAuth: auth, scope: 'read' as const },
  { name: 'sentryRetrieveSavedDiscoverQueries', description: sentryRetrieveSavedDiscoverQueries.description!, tool: sentryRetrieveSavedDiscoverQueries, requiredAuth: auth, scope: 'read' as const },
  { name: 'sentryRetrieveSavedDiscoverQueryForOrganization', description: sentryRetrieveSavedDiscoverQueryForOrganization.description!, tool: sentryRetrieveSavedDiscoverQueryForOrganization, requiredAuth: auth, scope: 'read' as const },
  { name: 'sentrySaveOrganizationDiscoverQuery', description: sentrySaveOrganizationDiscoverQuery.description!, tool: sentrySaveOrganizationDiscoverQuery, requiredAuth: auth, scope: 'write' as const },
  { name: 'sentryUpdateOrganizationDashboard', description: sentryUpdateOrganizationDashboard.description!, tool: sentryUpdateOrganizationDashboard, requiredAuth: auth, scope: 'write' as const },
  { name: 'sentryUpdateSavedQueryForOrganization', description: sentryUpdateSavedQueryForOrganization.description!, tool: sentryUpdateSavedQueryForOrganization, requiredAuth: auth, scope: 'write' as const },
  { name: 'sentryGetProjectEvents', description: sentryGetProjectEvents.description!, tool: sentryGetProjectEvents, requiredAuth: auth, scope: 'read' as const },
  { name: 'sentryListAProjectsUserFeedback', description: sentryListAProjectsUserFeedback.description!, tool: sentryListAProjectsUserFeedback, requiredAuth: auth, scope: 'read' as const },
  { name: 'sentryQueryExploreEventsInTimeseriesFormat', description: sentryQueryExploreEventsInTimeseriesFormat.description!, tool: sentryQueryExploreEventsInTimeseriesFormat, requiredAuth: auth, scope: 'read' as const },
  { name: 'sentryRetrieveOrganizationEvents', description: sentryRetrieveOrganizationEvents.description!, tool: sentryRetrieveOrganizationEvents, requiredAuth: auth, scope: 'read' as const },
  { name: 'sentryRetrieveProjectEventById', description: sentryRetrieveProjectEventById.description!, tool: sentryRetrieveProjectEventById, requiredAuth: auth, scope: 'read' as const },
  { name: 'sentryRetrieveSourceMapDebugEvent', description: sentryRetrieveSourceMapDebugEvent.description!, tool: sentryRetrieveSourceMapDebugEvent, requiredAuth: auth, scope: 'read' as const },
  { name: 'sentrySubmitUserFeedback', description: sentrySubmitUserFeedback.description!, tool: sentrySubmitUserFeedback, requiredAuth: auth, scope: 'write' as const },
  { name: 'sentryCreateProjectWebhookSubscription', description: sentryCreateProjectWebhookSubscription.description!, tool: sentryCreateProjectWebhookSubscription, requiredAuth: auth, scope: 'write' as const },
  { name: 'sentryCreateSentryExternalIssueLink', description: sentryCreateSentryExternalIssueLink.description!, tool: sentryCreateSentryExternalIssueLink, requiredAuth: auth, scope: 'write' as const },
  { name: 'sentryDeleteACustomIntegration', description: sentryDeleteACustomIntegration.description!, tool: sentryDeleteACustomIntegration, requiredAuth: auth, scope: 'delete' as const },
  { name: 'sentryDeleteExternalIssueByUuid', description: sentryDeleteExternalIssueByUuid.description!, tool: sentryDeleteExternalIssueByUuid, requiredAuth: auth, scope: 'delete' as const },
  { name: 'sentryDeleteOrganizationIntegration', description: sentryDeleteOrganizationIntegration.description!, tool: sentryDeleteOrganizationIntegration, requiredAuth: auth, scope: 'delete' as const },
  { name: 'sentryDeleteProjectHook', description: sentryDeleteProjectHook.description!, tool: sentryDeleteProjectHook, requiredAuth: auth, scope: 'delete' as const },
  { name: 'sentryGetIntegrationDetailsByOrg', description: sentryGetIntegrationDetailsByOrg.description!, tool: sentryGetIntegrationDetailsByOrg, requiredAuth: auth, scope: 'read' as const },
  { name: 'sentryGetProjectHook', description: sentryGetProjectHook.description!, tool: sentryGetProjectHook, requiredAuth: auth, scope: 'read' as const },
  { name: 'sentryGetSentryAppInstallationsForOrganization', description: sentryGetSentryAppInstallationsForOrganization.description!, tool: sentryGetSentryAppInstallationsForOrganization, requiredAuth: auth, scope: 'read' as const },
  { name: 'sentryListSeerAiModels', description: sentryListSeerAiModels.description!, tool: sentryListSeerAiModels, requiredAuth: auth, scope: 'read' as const },
  { name: 'sentryRetrieveACustomIntegrationByIdOrSlug', description: sentryRetrieveACustomIntegrationByIdOrSlug.description!, tool: sentryRetrieveACustomIntegrationByIdOrSlug, requiredAuth: auth, scope: 'read' as const },
  { name: 'sentryRetrieveOrganizationIntegrationsList', description: sentryRetrieveOrganizationIntegrationsList.description!, tool: sentryRetrieveOrganizationIntegrationsList, requiredAuth: auth, scope: 'read' as const },
  { name: 'sentryRetrieveOrgIntegrationConfig', description: sentryRetrieveOrgIntegrationConfig.description!, tool: sentryRetrieveOrgIntegrationConfig, requiredAuth: auth, scope: 'read' as const },
  { name: 'sentryRetrieveProjectHooks', description: sentryRetrieveProjectHooks.description!, tool: sentryRetrieveProjectHooks, requiredAuth: auth, scope: 'read' as const },
  { name: 'sentryRetrieveSeerIssueFixState', description: sentryRetrieveSeerIssueFixState.description!, tool: sentryRetrieveSeerIssueFixState, requiredAuth: auth, scope: 'read' as const },
  { name: 'sentryRetrieveTheCustomIntegsCreatedByAnOrg', description: sentryRetrieveTheCustomIntegsCreatedByAnOrg.description!, tool: sentryRetrieveTheCustomIntegsCreatedByAnOrg, requiredAuth: auth, scope: 'read' as const },
  { name: 'sentryStartSeerIssueFix', description: sentryStartSeerIssueFix.description!, tool: sentryStartSeerIssueFix, requiredAuth: auth, scope: 'write' as const },
  { name: 'sentryUpdateAnExistingCustomIntegration', description: sentryUpdateAnExistingCustomIntegration.description!, tool: sentryUpdateAnExistingCustomIntegration, requiredAuth: auth, scope: 'write' as const },
  { name: 'sentryUpdateWebhookConfigurationXp', description: sentryUpdateWebhookConfigurationXp.description!, tool: sentryUpdateWebhookConfigurationXp, requiredAuth: auth, scope: 'write' as const },
  { name: 'sentryBulkMutateAnOrganizationsIssues', description: sentryBulkMutateAnOrganizationsIssues.description!, tool: sentryBulkMutateAnOrganizationsIssues, requiredAuth: auth, scope: 'write' as const },
  { name: 'sentryBulkRemoveAnOrganizationsIssues', description: sentryBulkRemoveAnOrganizationsIssues.description!, tool: sentryBulkRemoveAnOrganizationsIssues, requiredAuth: auth, scope: 'delete' as const },
  { name: 'sentryDeleteOrganizationIssue', description: sentryDeleteOrganizationIssue.description!, tool: sentryDeleteOrganizationIssue, requiredAuth: auth, scope: 'delete' as const },
  { name: 'sentryDeleteProjectIssues', description: sentryDeleteProjectIssues.description!, tool: sentryDeleteProjectIssues, requiredAuth: auth, scope: 'delete' as const },
  { name: 'sentryFetchIssueEventById', description: sentryFetchIssueEventById.description!, tool: sentryFetchIssueEventById, requiredAuth: auth, scope: 'read' as const },
  { name: 'sentryFetchTagValuesForIssue', description: sentryFetchTagValuesForIssue.description!, tool: sentryFetchTagValuesForIssue, requiredAuth: auth, scope: 'read' as const },
  { name: 'sentryGetOldestEvent', description: sentryGetOldestEvent.description!, tool: sentryGetOldestEvent, requiredAuth: auth, scope: 'read' as const },
  { name: 'sentryGetOrganizationIssueDetails', description: sentryGetOrganizationIssueDetails.description!, tool: sentryGetOrganizationIssueDetails, requiredAuth: auth, scope: 'read' as const },
  { name: 'sentryListAnOrganizationsIssues', description: sentryListAnOrganizationsIssues.description!, tool: sentryListAnOrganizationsIssues, requiredAuth: auth, scope: 'read' as const },
  { name: 'sentryListATagsValuesForAnIssue', description: sentryListATagsValuesForAnIssue.description!, tool: sentryListATagsValuesForAnIssue, requiredAuth: auth, scope: 'read' as const },
  { name: 'sentryRetrieveCustomIntegIssueLinksGivenSentryIssue', description: sentryRetrieveCustomIntegIssueLinksGivenSentryIssue.description!, tool: sentryRetrieveCustomIntegIssueLinksGivenSentryIssue, requiredAuth: auth, scope: 'read' as const },
  { name: 'sentryRetrieveEventIdForOrganization', description: sentryRetrieveEventIdForOrganization.description!, tool: sentryRetrieveEventIdForOrganization, requiredAuth: auth, scope: 'read' as const },
  { name: 'sentryRetrieveIssueEventsById', description: sentryRetrieveIssueEventsById.description!, tool: sentryRetrieveIssueEventsById, requiredAuth: auth, scope: 'read' as const },
  { name: 'sentryRetrieveIssueHashesForOrganization', description: sentryRetrieveIssueHashesForOrganization.description!, tool: sentryRetrieveIssueHashesForOrganization, requiredAuth: auth, scope: 'read' as const },
  { name: 'sentryRetrieveIssueTagDetails', description: sentryRetrieveIssueTagDetails.description!, tool: sentryRetrieveIssueTagDetails, requiredAuth: auth, scope: 'read' as const },
  { name: 'sentryRetrieveProjectIssuesList', description: sentryRetrieveProjectIssuesList.description!, tool: sentryRetrieveProjectIssuesList, requiredAuth: auth, scope: 'read' as const },
  { name: 'sentryRetrieveShortIdForOrganization', description: sentryRetrieveShortIdForOrganization.description!, tool: sentryRetrieveShortIdForOrganization, requiredAuth: auth, scope: 'read' as const },
  { name: 'sentryUpdateIssueAttributesInOrganization', description: sentryUpdateIssueAttributesInOrganization.description!, tool: sentryUpdateIssueAttributesInOrganization, requiredAuth: auth, scope: 'write' as const },
  { name: 'sentryUpdateProjectIssueStatusAndDetails', description: sentryUpdateProjectIssueStatusAndDetails.description!, tool: sentryUpdateProjectIssueStatusAndDetails, requiredAuth: auth, scope: 'write' as const },
  { name: 'sentryAddOrganizationMemberViaEmail', description: sentryAddOrganizationMemberViaEmail.description!, tool: sentryAddOrganizationMemberViaEmail, requiredAuth: auth, scope: 'write' as const },
  { name: 'sentryAddRemoveUserEmailById', description: sentryAddRemoveUserEmailById.description!, tool: sentryAddRemoveUserEmailById, requiredAuth: auth, scope: 'write' as const },
  { name: 'sentryCreateExternalUserForOrganization', description: sentryCreateExternalUserForOrganization.description!, tool: sentryCreateExternalUserForOrganization, requiredAuth: auth, scope: 'write' as const },
  { name: 'sentryCreateScimGroupForOrganization', description: sentryCreateScimGroupForOrganization.description!, tool: sentryCreateScimGroupForOrganization, requiredAuth: auth, scope: 'write' as const },
  { name: 'sentryCreateUserForSamlIntegration', description: sentryCreateUserForSamlIntegration.description!, tool: sentryCreateUserForSamlIntegration, requiredAuth: auth, scope: 'write' as const },
  { name: 'sentryDeleteExternalUserFromOrganization', description: sentryDeleteExternalUserFromOrganization.description!, tool: sentryDeleteExternalUserFromOrganization, requiredAuth: auth, scope: 'delete' as const },
  { name: 'sentryDeleteOrganizationMember', description: sentryDeleteOrganizationMember.description!, tool: sentryDeleteOrganizationMember, requiredAuth: auth, scope: 'delete' as const },
  { name: 'sentryDeleteTeamFromOrgScimV2', description: sentryDeleteTeamFromOrgScimV2.description!, tool: sentryDeleteTeamFromOrgScimV2, requiredAuth: auth, scope: 'delete' as const },
  { name: 'sentryDeleteUserEmailsById', description: sentryDeleteUserEmailsById.description!, tool: sentryDeleteUserEmailsById, requiredAuth: auth, scope: 'delete' as const },
  { name: 'sentryDeleteUserFromOrg', description: sentryDeleteUserFromOrg.description!, tool: sentryDeleteUserFromOrg, requiredAuth: auth, scope: 'delete' as const },
  { name: 'sentryGetScimGroupByTeamId', description: sentryGetScimGroupByTeamId.description!, tool: sentryGetScimGroupByTeamId, requiredAuth: auth, scope: 'read' as const },
  { name: 'sentryListOrganizationMembers', description: sentryListOrganizationMembers.description!, tool: sentryListOrganizationMembers, requiredAuth: auth, scope: 'read' as const },
  { name: 'sentryListOrganizationUserTeams', description: sentryListOrganizationUserTeams.description!, tool: sentryListOrganizationUserTeams, requiredAuth: auth, scope: 'read' as const },
  { name: 'sentryListScimV2OrganizationUsers', description: sentryListScimV2OrganizationUsers.description!, tool: sentryListScimV2OrganizationUsers, requiredAuth: auth, scope: 'read' as const },
  { name: 'sentryPatchScimGroupOperations', description: sentryPatchScimGroupOperations.description!, tool: sentryPatchScimGroupOperations, requiredAuth: auth, scope: 'write' as const },
  { name: 'sentryPatchUserActiveStatusInOrganization', description: sentryPatchUserActiveStatusInOrganization.description!, tool: sentryPatchUserActiveStatusInOrganization, requiredAuth: auth, scope: 'write' as const },
  { name: 'sentryRetrieveOrganizationMember', description: sentryRetrieveOrganizationMember.description!, tool: sentryRetrieveOrganizationMember, requiredAuth: auth, scope: 'read' as const },
  { name: 'sentryRetrieveOrganizationScimGroups', description: sentryRetrieveOrganizationScimGroups.description!, tool: sentryRetrieveOrganizationScimGroups, requiredAuth: auth, scope: 'read' as const },
  { name: 'sentryRetrieveUserEmailInformation', description: sentryRetrieveUserEmailInformation.description!, tool: sentryRetrieveUserEmailInformation, requiredAuth: auth, scope: 'read' as const },
  { name: 'sentryRetrieveUserViaScimApi', description: sentryRetrieveUserViaScimApi.description!, tool: sentryRetrieveUserViaScimApi, requiredAuth: auth, scope: 'read' as const },
  { name: 'sentryUpdateExternalUserForOrganization', description: sentryUpdateExternalUserForOrganization.description!, tool: sentryUpdateExternalUserForOrganization, requiredAuth: auth, scope: 'write' as const },
  { name: 'sentryUpdateOrganizationMemberRole', description: sentryUpdateOrganizationMemberRole.description!, tool: sentryUpdateOrganizationMemberRole, requiredAuth: auth, scope: 'write' as const },
  { name: 'sentryUpdateUserEmail', description: sentryUpdateUserEmail.description!, tool: sentryUpdateUserEmail, requiredAuth: auth, scope: 'write' as const },
  { name: 'sentryCreateOrganizationMonitor', description: sentryCreateOrganizationMonitor.description!, tool: sentryCreateOrganizationMonitor, requiredAuth: auth, scope: 'write' as const },
  { name: 'sentryDeleteOrganizationMonitor', description: sentryDeleteOrganizationMonitor.description!, tool: sentryDeleteOrganizationMonitor, requiredAuth: auth, scope: 'delete' as const },
  { name: 'sentryDeleteProjectMonitor', description: sentryDeleteProjectMonitor.description!, tool: sentryDeleteProjectMonitor, requiredAuth: auth, scope: 'delete' as const },
  { name: 'sentryFetchAMonitor', description: sentryFetchAMonitor.description!, tool: sentryFetchAMonitor, requiredAuth: auth, scope: 'read' as const },
  { name: 'sentryFetchAnOrganizationsMonitors', description: sentryFetchAnOrganizationsMonitors.description!, tool: sentryFetchAnOrganizationsMonitors, requiredAuth: auth, scope: 'read' as const },
  { name: 'sentryGetProjectMonitorById', description: sentryGetProjectMonitorById.description!, tool: sentryGetProjectMonitorById, requiredAuth: auth, scope: 'read' as const },
  { name: 'sentryMutateAnOrganizationsMonitors', description: sentryMutateAnOrganizationsMonitors.description!, tool: sentryMutateAnOrganizationsMonitors, requiredAuth: auth, scope: 'write' as const },
  { name: 'sentryRetrieveAMonitor', description: sentryRetrieveAMonitor.description!, tool: sentryRetrieveAMonitor, requiredAuth: auth, scope: 'read' as const },
  { name: 'sentryRetrieveMonitorCheckins', description: sentryRetrieveMonitorCheckins.description!, tool: sentryRetrieveMonitorCheckins, requiredAuth: auth, scope: 'read' as const },
  { name: 'sentryRetrieveMonitorCheckinsByOrg', description: sentryRetrieveMonitorCheckinsByOrg.description!, tool: sentryRetrieveMonitorCheckinsByOrg, requiredAuth: auth, scope: 'read' as const },
  { name: 'sentryRetrieveOrganizationMonitors', description: sentryRetrieveOrganizationMonitors.description!, tool: sentryRetrieveOrganizationMonitors, requiredAuth: auth, scope: 'read' as const },
  { name: 'sentryUpdateAMonitor', description: sentryUpdateAMonitor.description!, tool: sentryUpdateAMonitor, requiredAuth: auth, scope: 'write' as const },
  { name: 'sentryUpdateAMonitorById', description: sentryUpdateAMonitorById.description!, tool: sentryUpdateAMonitorById, requiredAuth: auth, scope: 'write' as const },
  { name: 'sentryUpdateMonitorForProject', description: sentryUpdateMonitorForProject.description!, tool: sentryUpdateMonitorForProject, requiredAuth: auth, scope: 'write' as const },
  { name: 'sentryDisableSpikeProtection', description: sentryDisableSpikeProtection.description!, tool: sentryDisableSpikeProtection, requiredAuth: auth, scope: 'delete' as const },
  { name: 'sentryFetchOrganizationReleaseThresholdStatuses', description: sentryFetchOrganizationReleaseThresholdStatuses.description!, tool: sentryFetchOrganizationReleaseThresholdStatuses, requiredAuth: auth, scope: 'read' as const },
  { name: 'sentryGetOrganizationByIdOrSlug', description: sentryGetOrganizationByIdOrSlug.description!, tool: sentryGetOrganizationByIdOrSlug, requiredAuth: auth, scope: 'read' as const },
  { name: 'sentryGetOrganizationDetails', description: sentryGetOrganizationDetails.description!, tool: sentryGetOrganizationDetails, requiredAuth: auth, scope: 'read' as const },
  { name: 'sentryGetOrganizationEnvironments', description: sentryGetOrganizationEnvironments.description!, tool: sentryGetOrganizationEnvironments, requiredAuth: auth, scope: 'read' as const },
  { name: 'sentryGetOrganizationSessions', description: sentryGetOrganizationSessions.description!, tool: sentryGetOrganizationSessions, requiredAuth: auth, scope: 'read' as const },
  { name: 'sentryGetOrganizationStatsSummary', description: sentryGetOrganizationStatsSummary.description!, tool: sentryGetOrganizationStatsSummary, requiredAuth: auth, scope: 'read' as const },
  { name: 'sentryListAnOrganizationSClientKeys', description: sentryListAnOrganizationSClientKeys.description!, tool: sentryListAnOrganizationSClientKeys, requiredAuth: auth, scope: 'read' as const },
  { name: 'sentryListOrganizations', description: sentryListOrganizations.description!, tool: sentryListOrganizations, requiredAuth: auth, scope: 'read' as const },
  { name: 'sentryModifyOrganizationSettings', description: sentryModifyOrganizationSettings.description!, tool: sentryModifyOrganizationSettings, requiredAuth: auth, scope: 'write' as const },
  { name: 'sentryPostSpikeProtectionForOrganization', description: sentryPostSpikeProtectionForOrganization.description!, tool: sentryPostSpikeProtectionForOrganization, requiredAuth: auth, scope: 'write' as const },
  { name: 'sentryRetrieveDataForwardersForAnOrganization', description: sentryRetrieveDataForwardersForAnOrganization.description!, tool: sentryRetrieveDataForwardersForAnOrganization, requiredAuth: auth, scope: 'read' as const },
  { name: 'sentryRetrieveOrganizationRelayUsage', description: sentryRetrieveOrganizationRelayUsage.description!, tool: sentryRetrieveOrganizationRelayUsage, requiredAuth: auth, scope: 'read' as const },
  { name: 'sentryRetrieveOrganizationStatsV2', description: sentryRetrieveOrganizationStatsV2.description!, tool: sentryRetrieveOrganizationStatsV2, requiredAuth: auth, scope: 'read' as const },
  { name: 'sentryValidateCredential', description: sentryValidateCredential.description!, tool: sentryValidateCredential, requiredAuth: auth, scope: 'read' as const },
  { name: 'sentryAccessProjectInformation', description: sentryAccessProjectInformation.description!, tool: sentryAccessProjectInformation, requiredAuth: auth, scope: 'read' as const },
  { name: 'sentryAddASymbolSourceToAProject', description: sentryAddASymbolSourceToAProject.description!, tool: sentryAddASymbolSourceToAProject, requiredAuth: auth, scope: 'write' as const },
  { name: 'sentryAddTeamToProject', description: sentryAddTeamToProject.description!, tool: sentryAddTeamToProject, requiredAuth: auth, scope: 'write' as const },
  { name: 'sentryCreateProjectKeyWithOptionalRateLimiting', description: sentryCreateProjectKeyWithOptionalRateLimiting.description!, tool: sentryCreateProjectKeyWithOptionalRateLimiting, requiredAuth: auth, scope: 'write' as const },
  { name: 'sentryCreateTeamProjectForOrganization', description: sentryCreateTeamProjectForOrganization.description!, tool: sentryCreateTeamProjectForOrganization, requiredAuth: auth, scope: 'write' as const },
  { name: 'sentryDeleteDsymsForProject', description: sentryDeleteDsymsForProject.description!, tool: sentryDeleteDsymsForProject, requiredAuth: auth, scope: 'delete' as const },
  { name: 'sentryDeleteProjectById', description: sentryDeleteProjectById.description!, tool: sentryDeleteProjectById, requiredAuth: auth, scope: 'delete' as const },
  { name: 'sentryDeleteProjectKey', description: sentryDeleteProjectKey.description!, tool: sentryDeleteProjectKey, requiredAuth: auth, scope: 'delete' as const },
  { name: 'sentryDeleteProjectTeamAssociation', description: sentryDeleteProjectTeamAssociation.description!, tool: sentryDeleteProjectTeamAssociation, requiredAuth: auth, scope: 'delete' as const },
  { name: 'sentryDeleteSymbolSourceFromProject', description: sentryDeleteSymbolSourceFromProject.description!, tool: sentryDeleteSymbolSourceFromProject, requiredAuth: auth, scope: 'delete' as const },
  { name: 'sentryFetchProjectEnvironmentDetails', description: sentryFetchProjectEnvironmentDetails.description!, tool: sentryFetchProjectEnvironmentDetails, requiredAuth: auth, scope: 'read' as const },
  { name: 'sentryFetchProjectOwnershipDetails', description: sentryFetchProjectOwnershipDetails.description!, tool: sentryFetchProjectOwnershipDetails, requiredAuth: auth, scope: 'read' as const },
  { name: 'sentryGetProjectEventStats', description: sentryGetProjectEventStats.description!, tool: sentryGetProjectEventStats, requiredAuth: auth, scope: 'read' as const },
  { name: 'sentryGetProjectList', description: sentryGetProjectList.description!, tool: sentryGetProjectList, requiredAuth: auth, scope: 'read' as const },
  { name: 'sentryListProjectTags', description: sentryListProjectTags.description!, tool: sentryListProjectTags, requiredAuth: auth, scope: 'read' as const },
  { name: 'sentryListProjectUsers', description: sentryListProjectUsers.description!, tool: sentryListProjectUsers, requiredAuth: auth, scope: 'read' as const },
  { name: 'sentryRetrieveDsymFilesForProject', description: sentryRetrieveDsymFilesForProject.description!, tool: sentryRetrieveDsymFilesForProject, requiredAuth: auth, scope: 'read' as const },
  { name: 'sentryRetrieveOrganizationProjects', description: sentryRetrieveOrganizationProjects.description!, tool: sentryRetrieveOrganizationProjects, requiredAuth: auth, scope: 'read' as const },
  { name: 'sentryRetrieveProjectEnvironments', description: sentryRetrieveProjectEnvironments.description!, tool: sentryRetrieveProjectEnvironments, requiredAuth: auth, scope: 'read' as const },
  { name: 'sentryRetrieveProjectFilterData', description: sentryRetrieveProjectFilterData.description!, tool: sentryRetrieveProjectFilterData, requiredAuth: auth, scope: 'read' as const },
  { name: 'sentryRetrieveProjectKeyDetails', description: sentryRetrieveProjectKeyDetails.description!, tool: sentryRetrieveProjectKeyDetails, requiredAuth: auth, scope: 'read' as const },
  { name: 'sentryRetrieveProjectKeysByOrgAndProject', description: sentryRetrieveProjectKeysByOrgAndProject.description!, tool: sentryRetrieveProjectKeysByOrgAndProject, requiredAuth: auth, scope: 'read' as const },
  { name: 'sentryRetrieveProjectMembersList', description: sentryRetrieveProjectMembersList.description!, tool: sentryRetrieveProjectMembersList, requiredAuth: auth, scope: 'read' as const },
  { name: 'sentryRetrieveProjectSymbolSources', description: sentryRetrieveProjectSymbolSources.description!, tool: sentryRetrieveProjectSymbolSources, requiredAuth: auth, scope: 'read' as const },
  { name: 'sentryRetrieveProjectTagValues', description: sentryRetrieveProjectTagValues.description!, tool: sentryRetrieveProjectTagValues, requiredAuth: auth, scope: 'read' as const },
  { name: 'sentryRetrieveProjectTeams', description: sentryRetrieveProjectTeams.description!, tool: sentryRetrieveProjectTeams, requiredAuth: auth, scope: 'read' as const },
  { name: 'sentryToggleProjectFilterStatus', description: sentryToggleProjectFilterStatus.description!, tool: sentryToggleProjectFilterStatus, requiredAuth: auth, scope: 'write' as const },
  { name: 'sentryUpdateAProjectsSymbolSource', description: sentryUpdateAProjectsSymbolSource.description!, tool: sentryUpdateAProjectsSymbolSource, requiredAuth: auth, scope: 'write' as const },
  { name: 'sentryUpdateEnvironmentVisibility', description: sentryUpdateEnvironmentVisibility.description!, tool: sentryUpdateEnvironmentVisibility, requiredAuth: auth, scope: 'write' as const },
  { name: 'sentryUpdateProjectDetails', description: sentryUpdateProjectDetails.description!, tool: sentryUpdateProjectDetails, requiredAuth: auth, scope: 'write' as const },
  { name: 'sentryUpdateProjectKeyConfiguration', description: sentryUpdateProjectKeyConfiguration.description!, tool: sentryUpdateProjectKeyConfiguration, requiredAuth: auth, scope: 'write' as const },
  { name: 'sentryUpdateProjectOwnershipSettings', description: sentryUpdateProjectOwnershipSettings.description!, tool: sentryUpdateProjectOwnershipSettings, requiredAuth: auth, scope: 'write' as const },
  { name: 'sentryUploadDsymsFileToProject', description: sentryUploadDsymsFileToProject.description!, tool: sentryUploadDsymsFileToProject, requiredAuth: auth, scope: 'write' as const },
  { name: 'sentryCreateReleaseDeployForOrg', description: sentryCreateReleaseDeployForOrg.description!, tool: sentryCreateReleaseDeployForOrg, requiredAuth: auth, scope: 'write' as const },
  { name: 'sentryCreateReleaseForOrganization', description: sentryCreateReleaseForOrganization.description!, tool: sentryCreateReleaseForOrganization, requiredAuth: auth, scope: 'write' as const },
  { name: 'sentryDeleteOrganizationRelease', description: sentryDeleteOrganizationRelease.description!, tool: sentryDeleteOrganizationRelease, requiredAuth: auth, scope: 'delete' as const },
  { name: 'sentryDeleteOrganizationReleaseFile', description: sentryDeleteOrganizationReleaseFile.description!, tool: sentryDeleteOrganizationReleaseFile, requiredAuth: auth, scope: 'delete' as const },
  { name: 'sentryDeleteReleaseFileById', description: sentryDeleteReleaseFileById.description!, tool: sentryDeleteReleaseFileById, requiredAuth: auth, scope: 'delete' as const },
  { name: 'sentryFetchProjectReleaseFiles', description: sentryFetchProjectReleaseFiles.description!, tool: sentryFetchProjectReleaseFiles, requiredAuth: auth, scope: 'read' as const },
  { name: 'sentryGetOrganizationReleaseVersion', description: sentryGetOrganizationReleaseVersion.description!, tool: sentryGetOrganizationReleaseVersion, requiredAuth: auth, scope: 'read' as const },
  { name: 'sentryListOrganizationReleases', description: sentryListOrganizationReleases.description!, tool: sentryListOrganizationReleases, requiredAuth: auth, scope: 'read' as const },
  { name: 'sentryListOrganizationRepositories', description: sentryListOrganizationRepositories.description!, tool: sentryListOrganizationRepositories, requiredAuth: auth, scope: 'read' as const },
  { name: 'sentryModifyReleaseFileAttributes', description: sentryModifyReleaseFileAttributes.description!, tool: sentryModifyReleaseFileAttributes, requiredAuth: auth, scope: 'write' as const },
  { name: 'sentryRetrieveCommitFilesForRelease', description: sentryRetrieveCommitFilesForRelease.description!, tool: sentryRetrieveCommitFilesForRelease, requiredAuth: auth, scope: 'read' as const },
  { name: 'sentryRetrieveCommitsForOrganizationRepo', description: sentryRetrieveCommitsForOrganizationRepo.description!, tool: sentryRetrieveCommitsForOrganizationRepo, requiredAuth: auth, scope: 'read' as const },
  { name: 'sentryRetrieveFilesForRelease', description: sentryRetrieveFilesForRelease.description!, tool: sentryRetrieveFilesForRelease, requiredAuth: auth, scope: 'read' as const },
  { name: 'sentryRetrieveOrganizationReleaseCommits', description: sentryRetrieveOrganizationReleaseCommits.description!, tool: sentryRetrieveOrganizationReleaseCommits, requiredAuth: auth, scope: 'read' as const },
  { name: 'sentryRetrievePaginatedRepositoryTokens', description: sentryRetrievePaginatedRepositoryTokens.description!, tool: sentryRetrievePaginatedRepositoryTokens, requiredAuth: auth, scope: 'read' as const },
  { name: 'sentryRetrieveProjectReleaseFileDetails', description: sentryRetrieveProjectReleaseFileDetails.description!, tool: sentryRetrieveProjectReleaseFileDetails, requiredAuth: auth, scope: 'read' as const },
  { name: 'sentryRetrieveReleaseCommits', description: sentryRetrieveReleaseCommits.description!, tool: sentryRetrieveReleaseCommits, requiredAuth: auth, scope: 'read' as const },
  { name: 'sentryRetrieveReleaseDeployments', description: sentryRetrieveReleaseDeployments.description!, tool: sentryRetrieveReleaseDeployments, requiredAuth: auth, scope: 'read' as const },
  { name: 'sentryRetrieveReleaseFileById', description: sentryRetrieveReleaseFileById.description!, tool: sentryRetrieveReleaseFileById, requiredAuth: auth, scope: 'read' as const },
  { name: 'sentryUpdateProjectReleaseFileDetails', description: sentryUpdateProjectReleaseFileDetails.description!, tool: sentryUpdateProjectReleaseFileDetails, requiredAuth: auth, scope: 'write' as const },
  { name: 'sentryUpdateReleaseDetailsForOrganization', description: sentryUpdateReleaseDetailsForOrganization.description!, tool: sentryUpdateReleaseDetailsForOrganization, requiredAuth: auth, scope: 'write' as const },
  { name: 'sentryUploadFileToProjectRelease', description: sentryUploadFileToProjectRelease.description!, tool: sentryUploadFileToProjectRelease, requiredAuth: auth, scope: 'write' as const },
  { name: 'sentryUploadReleaseFileToOrganization', description: sentryUploadReleaseFileToOrganization.description!, tool: sentryUploadReleaseFileToOrganization, requiredAuth: auth, scope: 'write' as const },
  { name: 'sentryDeleteProjectReplay', description: sentryDeleteProjectReplay.description!, tool: sentryDeleteProjectReplay, requiredAuth: auth, scope: 'delete' as const },
  { name: 'sentryFetchOrganizationReplayCount', description: sentryFetchOrganizationReplayCount.description!, tool: sentryFetchOrganizationReplayCount, requiredAuth: auth, scope: 'read' as const },
  { name: 'sentryFetchOrganizationReplayDetails', description: sentryFetchOrganizationReplayDetails.description!, tool: sentryFetchOrganizationReplayDetails, requiredAuth: auth, scope: 'read' as const },
  { name: 'sentryFetchOrganizationReplaySelectors', description: sentryFetchOrganizationReplaySelectors.description!, tool: sentryFetchOrganizationReplaySelectors, requiredAuth: auth, scope: 'read' as const },
  { name: 'sentryFetchProjectReplayClicks', description: sentryFetchProjectReplayClicks.description!, tool: sentryFetchProjectReplayClicks, requiredAuth: auth, scope: 'read' as const },
  { name: 'sentryFetchReplayRecordingSegment', description: sentryFetchReplayRecordingSegment.description!, tool: sentryFetchReplayRecordingSegment, requiredAuth: auth, scope: 'read' as const },
  { name: 'sentryGetWhoViewedReplayByProject', description: sentryGetWhoViewedReplayByProject.description!, tool: sentryGetWhoViewedReplayByProject, requiredAuth: auth, scope: 'read' as const },
  { name: 'sentryRetrieveOrganizationReplays', description: sentryRetrieveOrganizationReplays.description!, tool: sentryRetrieveOrganizationReplays, requiredAuth: auth, scope: 'read' as const },
  { name: 'sentryRetrieveReplayRecordingSegments', description: sentryRetrieveReplayRecordingSegments.description!, tool: sentryRetrieveReplayRecordingSegments, requiredAuth: auth, scope: 'read' as const },
  { name: 'sentryAddTeamMemberInOrganization', description: sentryAddTeamMemberInOrganization.description!, tool: sentryAddTeamMemberInOrganization, requiredAuth: auth, scope: 'write' as const },
  { name: 'sentryCreateOrganizationTeam', description: sentryCreateOrganizationTeam.description!, tool: sentryCreateOrganizationTeam, requiredAuth: auth, scope: 'write' as const },
  { name: 'sentryDeleteExternalTeamById', description: sentryDeleteExternalTeamById.description!, tool: sentryDeleteExternalTeamById, requiredAuth: auth, scope: 'delete' as const },
  { name: 'sentryDeleteMemberFromTeam', description: sentryDeleteMemberFromTeam.description!, tool: sentryDeleteMemberFromTeam, requiredAuth: auth, scope: 'delete' as const },
  { name: 'sentryDeleteTeamByOrganizationOrTeamSlug', description: sentryDeleteTeamByOrganizationOrTeamSlug.description!, tool: sentryDeleteTeamByOrganizationOrTeamSlug, requiredAuth: auth, scope: 'delete' as const },
  { name: 'sentryGetTeamMembersByIdOrSlug', description: sentryGetTeamMembersByIdOrSlug.description!, tool: sentryGetTeamMembersByIdOrSlug, requiredAuth: auth, scope: 'read' as const },
  { name: 'sentryListTeamsInOrganization', description: sentryListTeamsInOrganization.description!, tool: sentryListTeamsInOrganization, requiredAuth: auth, scope: 'read' as const },
  { name: 'sentryManageTeamExternalIntegrations', description: sentryManageTeamExternalIntegrations.description!, tool: sentryManageTeamExternalIntegrations, requiredAuth: auth, scope: 'write' as const },
  { name: 'sentryRetrieveTeamInfoViaOrganizationIdOrSlug', description: sentryRetrieveTeamInfoViaOrganizationIdOrSlug.description!, tool: sentryRetrieveTeamInfoViaOrganizationIdOrSlug, requiredAuth: auth, scope: 'read' as const },
  { name: 'sentryRetrieveTeamProjects', description: sentryRetrieveTeamProjects.description!, tool: sentryRetrieveTeamProjects, requiredAuth: auth, scope: 'read' as const },
  { name: 'sentrySwitchTeamRoleForMember', description: sentrySwitchTeamRoleForMember.description!, tool: sentrySwitchTeamRoleForMember, requiredAuth: auth, scope: 'write' as const },
  { name: 'sentryUpdateExternalTeamIntegration', description: sentryUpdateExternalTeamIntegration.description!, tool: sentryUpdateExternalTeamIntegration, requiredAuth: auth, scope: 'write' as const },
  { name: 'sentryUpdateTeamInformationByOrganizationId', description: sentryUpdateTeamInformationByOrganizationId.description!, tool: sentryUpdateTeamInformationByOrganizationId, requiredAuth: auth, scope: 'write' as const },
  { name: 'sentryIngestEventViaDsn', description: sentryIngestEventViaDsn.description!, tool: sentryIngestEventViaDsn, scope: 'write' as const },
];
