// @ts-nocheck
import {
  pineconeListIndexes,
  pineconeDescribeIndex,
  pineconeCreateIndex,
  pineconeCreateIndexForModel,
  pineconeDeleteIndex,
  pineconeConfigureIndex,
  pineconeListCollections,
  pineconeDescribeCollection,
  pineconeCreateCollection,
  pineconeDeleteCollection,
  pineconeListIndexBackups,
  pineconeCreateBackup,
  pineconeListBackups,
  pineconeDescribeBackup,
  pineconeDeleteBackup,
  pineconeRestoreFromBackup,
  pineconeListRestoreJobs,
  pineconeDescribeRestoreJob,
} from './indexes.js';
import {
  pineconeDescribeIndexStats,
  pineconeUpsertVectors,
  pineconeUpdateVector,
  pineconeFetchVectors,
  pineconeFetchByMetadata,
  pineconeDeleteVectors,
  pineconeListVectorIds,
  pineconeQueryVectors,
  pineconeUpsertRecords,
  pineconeSearchRecords,
  pineconeListNamespaces,
  pineconeCreateNamespace,
  pineconeDescribeNamespace,
  pineconeListImports,
  pineconeStartImport,
  pineconeDescribeImport,
} from './vectors.js';
import {
  pineconeEmbed,
  pineconeRerank,
  pineconeListModels,
  pineconeGetModel,
  pineconeListProjects,
  pineconeCreateProject,
  pineconeGetProject,
  pineconeUpdateProject,
  pineconeDeleteProject,
  pineconeListOrganizations,
  pineconeGetOrganization,
  pineconeUpdateOrganization,
  pineconeDeleteOrganization,
  pineconeListProjectApiKeys,
  pineconeCreateApiKey,
  pineconeGetApiKey,
  pineconeUpdateApiKey,
  pineconeDeleteApiKey,
} from './platform.js';

export {
  pineconeListIndexes,
  pineconeDescribeIndex,
  pineconeCreateIndex,
  pineconeCreateIndexForModel,
  pineconeDeleteIndex,
  pineconeConfigureIndex,
  pineconeListCollections,
  pineconeDescribeCollection,
  pineconeCreateCollection,
  pineconeDeleteCollection,
  pineconeListIndexBackups,
  pineconeCreateBackup,
  pineconeListBackups,
  pineconeDescribeBackup,
  pineconeDeleteBackup,
  pineconeRestoreFromBackup,
  pineconeListRestoreJobs,
  pineconeDescribeRestoreJob,
  pineconeDescribeIndexStats,
  pineconeUpsertVectors,
  pineconeUpdateVector,
  pineconeFetchVectors,
  pineconeFetchByMetadata,
  pineconeDeleteVectors,
  pineconeListVectorIds,
  pineconeQueryVectors,
  pineconeUpsertRecords,
  pineconeSearchRecords,
  pineconeListNamespaces,
  pineconeCreateNamespace,
  pineconeDescribeNamespace,
  pineconeListImports,
  pineconeStartImport,
  pineconeDescribeImport,
  pineconeEmbed,
  pineconeRerank,
  pineconeListModels,
  pineconeGetModel,
  pineconeListProjects,
  pineconeCreateProject,
  pineconeGetProject,
  pineconeUpdateProject,
  pineconeDeleteProject,
  pineconeListOrganizations,
  pineconeGetOrganization,
  pineconeUpdateOrganization,
  pineconeDeleteOrganization,
  pineconeListProjectApiKeys,
  pineconeCreateApiKey,
  pineconeGetApiKey,
  pineconeUpdateApiKey,
  pineconeDeleteApiKey,
};

const AUTH = 'pineconeApiKey' as const;

export const pineconeTools = [
  {
    name: 'pineconeListIndexes',
    description: 'List all indexes.',
    tool: pineconeListIndexes,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['databases', 'collections'],
  },
  {
    name: 'pineconeDescribeIndex',
    description: 'Describe an index with host and status.',
    tool: pineconeDescribeIndex,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['fetch', 'endpoint'],
  },
  {
    name: 'pineconeCreateIndex',
    description: 'Create a serverless or pod index.',
    tool: pineconeCreateIndex,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['provision', 'database'],
  },
  {
    name: 'pineconeCreateIndexForModel',
    description: 'Create an integrated-embedding index for a model.',
    tool: pineconeCreateIndexForModel,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['provision', 'embeddings'],
  },
  {
    name: 'pineconeDeleteIndex',
    description: 'Delete an index and its data.',
    tool: pineconeDeleteIndex,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['drop', 'remove'],
  },
  {
    name: 'pineconeConfigureIndex',
    description: 'Scale a pod index.',
    tool: pineconeConfigureIndex,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['replicas', 'resize'],
  },
  {
    name: 'pineconeListCollections',
    description: 'List collections.',
    tool: pineconeListCollections,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['snapshots', 'copies'],
  },
  {
    name: 'pineconeDescribeCollection',
    description: 'Get one collection.',
    tool: pineconeDescribeCollection,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['fetch'],
  },
  {
    name: 'pineconeCreateCollection',
    description: 'Create a collection from an index.',
    tool: pineconeCreateCollection,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['snapshot', 'archive'],
  },
  {
    name: 'pineconeDeleteCollection',
    description: 'Delete a collection.',
    tool: pineconeDeleteCollection,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['remove'],
  },
  {
    name: 'pineconeListIndexBackups',
    description: 'List backups of an index.',
    tool: pineconeListIndexBackups,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['snapshots'],
  },
  {
    name: 'pineconeCreateBackup',
    description: 'Back up an index.',
    tool: pineconeCreateBackup,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['snapshot', 'save'],
  },
  {
    name: 'pineconeListBackups',
    description: 'List all project backups.',
    tool: pineconeListBackups,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['snapshots'],
  },
  {
    name: 'pineconeDescribeBackup',
    description: 'Get one backup.',
    tool: pineconeDescribeBackup,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['fetch'],
  },
  {
    name: 'pineconeDeleteBackup',
    description: 'Delete a backup.',
    tool: pineconeDeleteBackup,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['prune'],
  },
  {
    name: 'pineconeRestoreFromBackup',
    description: 'Create an index from a backup.',
    tool: pineconeRestoreFromBackup,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['recover', 'clone'],
  },
  {
    name: 'pineconeListRestoreJobs',
    description: 'List restore jobs.',
    tool: pineconeListRestoreJobs,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['progress'],
  },
  {
    name: 'pineconeDescribeRestoreJob',
    description: 'Get one restore job.',
    tool: pineconeDescribeRestoreJob,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['poll'],
  },
  {
    name: 'pineconeDescribeIndexStats',
    description: 'Get vector counts and fullness.',
    tool: pineconeDescribeIndexStats,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['size', 'namespaces'],
  },
  {
    name: 'pineconeUpsertVectors',
    description: 'Upsert up to 1000 vectors.',
    tool: pineconeUpsertVectors,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['insert', 'embeddings', 'ingest'],
  },
  {
    name: 'pineconeUpdateVector',
    description: 'Update one vector values/metadata.',
    tool: pineconeUpdateVector,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['patch', 'edit'],
  },
  {
    name: 'pineconeFetchVectors',
    description: 'Fetch vectors by ID.',
    tool: pineconeFetchVectors,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['lookup', 'retrieve'],
  },
  {
    name: 'pineconeFetchByMetadata',
    description: 'Fetch vectors by metadata filter.',
    tool: pineconeFetchByMetadata,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['filter', 'scan'],
  },
  {
    name: 'pineconeDeleteVectors',
    description: 'Delete vectors by ID/filter/all.',
    tool: pineconeDeleteVectors,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['remove', 'purge'],
  },
  {
    name: 'pineconeListVectorIds',
    description: 'List vector IDs with pagination.',
    tool: pineconeListVectorIds,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['enumerate', 'browse'],
  },
  {
    name: 'pineconeQueryVectors',
    description: 'Semantic search by vector.',
    tool: pineconeQueryVectors,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['similarity', 'nearest', 'rag'],
  },
  {
    name: 'pineconeUpsertRecords',
    description: 'Upsert text records (server-side embedding).',
    tool: pineconeUpsertRecords,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['documents', 'chunks', 'ingest'],
  },
  {
    name: 'pineconeSearchRecords',
    description: 'Text search with rerank support.',
    tool: pineconeSearchRecords,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['rag', 'documents', 'hybrid'],
  },
  {
    name: 'pineconeListNamespaces',
    description: 'List namespaces.',
    tool: pineconeListNamespaces,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['partitions', 'tenants'],
  },
  {
    name: 'pineconeCreateNamespace',
    description: 'Create a namespace with schema.',
    tool: pineconeCreateNamespace,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['partition', 'tenant'],
  },
  {
    name: 'pineconeDescribeNamespace',
    description: 'Describe a namespace.',
    tool: pineconeDescribeNamespace,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['fetch', 'stats'],
  },
  {
    name: 'pineconeListImports',
    description: 'List bulk import jobs.',
    tool: pineconeListImports,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['ingestion', 's3'],
  },
  {
    name: 'pineconeStartImport',
    description: 'Start a bulk S3 import.',
    tool: pineconeStartImport,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['ingestion', 'parquet', 'bulk'],
  },
  {
    name: 'pineconeDescribeImport',
    description: 'Get an import job.',
    tool: pineconeDescribeImport,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['poll', 'progress'],
  },
  {
    name: 'pineconeEmbed',
    description: 'Generate embeddings with a hosted model.',
    tool: pineconeEmbed,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['vectors', 'encode', 'e5'],
  },
  {
    name: 'pineconeRerank',
    description: 'Rerank documents against a query.',
    tool: pineconeRerank,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['reorder', 'bge', 'cohere'],
  },
  {
    name: 'pineconeListModels',
    description: 'List hosted models.',
    tool: pineconeListModels,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['embeddings', 'catalog'],
  },
  {
    name: 'pineconeGetModel',
    description: 'Get one hosted model.',
    tool: pineconeGetModel,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['fetch', 'params'],
  },
  {
    name: 'pineconeListProjects',
    description: 'List projects.',
    tool: pineconeListProjects,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['workspaces'],
  },
  {
    name: 'pineconeCreateProject',
    description: 'Create a project.',
    tool: pineconeCreateProject,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['workspace', 'provision'],
  },
  {
    name: 'pineconeGetProject',
    description: 'Get one project.',
    tool: pineconeGetProject,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['workspace', 'fetch'],
  },
  {
    name: 'pineconeUpdateProject',
    description: 'Rename a project.',
    tool: pineconeUpdateProject,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['workspace', 'rename'],
  },
  {
    name: 'pineconeDeleteProject',
    description: 'Delete a project.',
    tool: pineconeDeleteProject,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['workspace', 'remove'],
  },
  {
    name: 'pineconeListOrganizations',
    description: 'List organizations.',
    tool: pineconeListOrganizations,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['tenants'],
  },
  {
    name: 'pineconeGetOrganization',
    description: 'Get one organization.',
    tool: pineconeGetOrganization,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['tenant', 'fetch'],
  },
  {
    name: 'pineconeUpdateOrganization',
    description: 'Rename an organization.',
    tool: pineconeUpdateOrganization,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['tenant', 'rename'],
  },
  {
    name: 'pineconeDeleteOrganization',
    description: 'Delete an organization.',
    tool: pineconeDeleteOrganization,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['tenant', 'remove'],
  },
  {
    name: 'pineconeListProjectApiKeys',
    description: 'List project API keys.',
    tool: pineconeListProjectApiKeys,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['credentials', 'audit'],
  },
  {
    name: 'pineconeCreateApiKey',
    description: 'Create a project API key.',
    tool: pineconeCreateApiKey,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['credential', 'generate'],
  },
  {
    name: 'pineconeGetApiKey',
    description: 'Get one API key metadata.',
    tool: pineconeGetApiKey,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['credential', 'fetch'],
  },
  {
    name: 'pineconeUpdateApiKey',
    description: 'Update an API key.',
    tool: pineconeUpdateApiKey,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['credential', 'rotate'],
  },
  {
    name: 'pineconeDeleteApiKey',
    description: 'Revoke an API key.',
    tool: pineconeDeleteApiKey,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['credential', 'revoke'],
  },
];
