// @ts-nocheck
import {
  synkListOrgs,
  synkGetOrg,
  synkUpdateOrg,
  synkCreateOrgMembership,
  synkListOrgMemberships,
  synkUpdateOrgMembership,
  synkDeleteOrgMembership,
  synkListGroups,
  synkGetGroup,
  synkListGroupOrgs,
  synkCreateGroupMembership,
  synkListGroupMemberships,
  synkUpdateGroupMembership,
  synkDeleteGroupMembership,
  synkGetOrgUser,
} from './orgs.js';
import {
  synkListProjects,
  synkGetProject,
  synkUpdateProject,
  synkDeleteProject,
  synkBulkDeleteProjects,
  synkListTargets,
  synkGetTarget,
  synkDeleteTarget,
  synkCreateCollection,
  synkListCollections,
  synkGetCollection,
  synkUpdateCollection,
  synkDeleteCollection,
  synkAddProjectsToCollection,
  synkListCollectionProjects,
  synkRemoveProjectsFromCollection,
} from './projects.js';
import {
  synkListOrgIssues,
  synkGetOrgIssue,
  synkListGroupIssues,
  synkGetGroupIssue,
  synkListPackageIssues,
  synkListIssuesForPackages,
  synkGetProjectSbom,
  synkCreateSbomTest,
  synkGetSbomTest,
  synkGetSbomTestResults,
  synkListContainerImages,
  synkGetContainerImage,
  synkListImageTargetRefs,
  synkCreateTest,
  synkGetTest,
  synkGetTestJob,
  synkListTestFindings,
} from './issues.js';
import {
  synkInviteUser,
  synkListInvites,
  synkCancelInvite,
  synkSearchOrgAuditLogs,
  synkSearchGroupAuditLogs,
  synkListServiceAccounts,
  synkCreateServiceAccount,
  synkGetServiceAccount,
  synkUpdateServiceAccount,
  synkDeleteServiceAccount,
  synkCreateServiceAccountSecret,
  synkListOrgApps,
  synkListOrgInstalls,
  synkInstallOrgApp,
  synkRevokeOrgAppInstall,
  synkGetSelf,
  synkListPersonalAccessTokens,
  synkDeletePersonalAccessToken,
} from './admin.js';
import {
  synkV1ListOrgs,
  synkV1CreateOrg,
  synkV1DeleteOrg,
  synkV1GetOrgSettings,
  synkV1UpdateOrgSettings,
  synkV1ListMembers,
  synkV1UpdateMember,
  synkV1RemoveMember,
  synkV1InviteUser,
  synkV1ListIntegrations,
  synkV1AddIntegration,
  synkV1UpdateIntegration,
  synkV1GetIntegrationSettings,
  synkV1UpdateIntegrationSettings,
  synkV1ImportTargets,
  synkV1GetImportJob,
  synkV1ListIgnores,
  synkV1AddIgnore,
  synkV1GetIgnore,
  synkV1DeleteIgnore,
  synkV1GetProject,
  synkV1UpdateProject,
  synkV1DeleteProject,
  synkV1AddProjectTag,
  synkV1RemoveProjectTag,
  synkV1ListAggregatedIssues,
  synkV1TestPackage,
  synkV1ListJiraIssues,
  synkV1CreateJiraIssue,
  synkV1ListWebhooks,
  synkV1CreateWebhook,
  synkV1GetWebhook,
  synkV1DeleteWebhook,
  synkV1PingWebhook,
  synkV1ListEntitlements,
  synkV1GetEntitlement,
  synkV1ListDependencies,
  synkV1ListGroupTags,
  synkV1DeleteGroupTag,
} from './v1.js';

export {
  synkListOrgs,
  synkGetOrg,
  synkUpdateOrg,
  synkCreateOrgMembership,
  synkListOrgMemberships,
  synkUpdateOrgMembership,
  synkDeleteOrgMembership,
  synkListGroups,
  synkGetGroup,
  synkListGroupOrgs,
  synkCreateGroupMembership,
  synkListGroupMemberships,
  synkUpdateGroupMembership,
  synkDeleteGroupMembership,
  synkGetOrgUser,
  synkListProjects,
  synkGetProject,
  synkUpdateProject,
  synkDeleteProject,
  synkBulkDeleteProjects,
  synkListTargets,
  synkGetTarget,
  synkDeleteTarget,
  synkCreateCollection,
  synkListCollections,
  synkGetCollection,
  synkUpdateCollection,
  synkDeleteCollection,
  synkAddProjectsToCollection,
  synkListCollectionProjects,
  synkRemoveProjectsFromCollection,
  synkListOrgIssues,
  synkGetOrgIssue,
  synkListGroupIssues,
  synkGetGroupIssue,
  synkListPackageIssues,
  synkListIssuesForPackages,
  synkGetProjectSbom,
  synkCreateSbomTest,
  synkGetSbomTest,
  synkGetSbomTestResults,
  synkListContainerImages,
  synkGetContainerImage,
  synkListImageTargetRefs,
  synkCreateTest,
  synkGetTest,
  synkGetTestJob,
  synkListTestFindings,
  synkInviteUser,
  synkListInvites,
  synkCancelInvite,
  synkSearchOrgAuditLogs,
  synkSearchGroupAuditLogs,
  synkListServiceAccounts,
  synkCreateServiceAccount,
  synkGetServiceAccount,
  synkUpdateServiceAccount,
  synkDeleteServiceAccount,
  synkCreateServiceAccountSecret,
  synkListOrgApps,
  synkListOrgInstalls,
  synkInstallOrgApp,
  synkRevokeOrgAppInstall,
  synkGetSelf,
  synkListPersonalAccessTokens,
  synkDeletePersonalAccessToken,
  synkV1ListOrgs,
  synkV1CreateOrg,
  synkV1DeleteOrg,
  synkV1GetOrgSettings,
  synkV1UpdateOrgSettings,
  synkV1ListMembers,
  synkV1UpdateMember,
  synkV1RemoveMember,
  synkV1InviteUser,
  synkV1ListIntegrations,
  synkV1AddIntegration,
  synkV1UpdateIntegration,
  synkV1GetIntegrationSettings,
  synkV1UpdateIntegrationSettings,
  synkV1ImportTargets,
  synkV1GetImportJob,
  synkV1ListIgnores,
  synkV1AddIgnore,
  synkV1GetIgnore,
  synkV1DeleteIgnore,
  synkV1GetProject,
  synkV1UpdateProject,
  synkV1DeleteProject,
  synkV1AddProjectTag,
  synkV1RemoveProjectTag,
  synkV1ListAggregatedIssues,
  synkV1TestPackage,
  synkV1ListJiraIssues,
  synkV1CreateJiraIssue,
  synkV1ListWebhooks,
  synkV1CreateWebhook,
  synkV1GetWebhook,
  synkV1DeleteWebhook,
  synkV1PingWebhook,
  synkV1ListEntitlements,
  synkV1GetEntitlement,
  synkV1ListDependencies,
  synkV1ListGroupTags,
  synkV1DeleteGroupTag,
};

const AUTH = 'synkCredentials' as const;

export const synkTools = [
  {
    name: 'synkListOrgs',
    description: 'List accessible organizations.',
    tool: synkListOrgs,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['workspaces', 'tenants'],
  },
  {
    name: 'synkGetOrg',
    description: 'Get one organization.',
    tool: synkGetOrg,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['workspace', 'fetch'],
  },
  {
    name: 'synkUpdateOrg',
    description: 'Update organization attributes.',
    tool: synkUpdateOrg,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['workspace', 'rename'],
  },
  {
    name: 'synkCreateOrgMembership',
    description: 'Create an org membership with a role.',
    tool: synkCreateOrgMembership,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['member', 'invite', 'rbac'],
  },
  {
    name: 'synkListOrgMemberships',
    description: 'List org memberships.',
    tool: synkListOrgMemberships,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['members', 'roles'],
  },
  {
    name: 'synkUpdateOrgMembership',
    description: 'Update an org membership role.',
    tool: synkUpdateOrgMembership,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['member', 'role'],
  },
  {
    name: 'synkDeleteOrgMembership',
    description: 'Remove an org membership.',
    tool: synkDeleteOrgMembership,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['member', 'remove'],
  },
  {
    name: 'synkListGroups',
    description: 'List groups.',
    tool: synkListGroups,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['collections', 'tenants'],
  },
  {
    name: 'synkGetGroup',
    description: 'Get one group.',
    tool: synkGetGroup,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['fetch'],
  },
  {
    name: 'synkListGroupOrgs',
    description: 'List organizations in a group.',
    tool: synkListGroupOrgs,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['workspaces'],
  },
  {
    name: 'synkCreateGroupMembership',
    description: 'Create a group membership.',
    tool: synkCreateGroupMembership,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['member', 'rbac'],
  },
  {
    name: 'synkListGroupMemberships',
    description: 'List group memberships.',
    tool: synkListGroupMemberships,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['members'],
  },
  {
    name: 'synkUpdateGroupMembership',
    description: 'Update a group membership role.',
    tool: synkUpdateGroupMembership,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['member', 'role'],
  },
  {
    name: 'synkDeleteGroupMembership',
    description: 'Remove a group membership.',
    tool: synkDeleteGroupMembership,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['member', 'remove'],
  },
  {
    name: 'synkGetOrgUser',
    description: 'Get one org user.',
    tool: synkGetOrgUser,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['member', 'fetch'],
  },
  {
    name: 'synkListProjects',
    description: 'List projects with filters and counts.',
    tool: synkListProjects,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['repos', 'scans', 'targets'],
  },
  {
    name: 'synkGetProject',
    description: 'Get one project.',
    tool: synkGetProject,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['repo', 'fetch'],
  },
  {
    name: 'synkUpdateProject',
    description: 'Patch project attributes.',
    tool: synkUpdateProject,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['repo', 'tag', 'criticality'],
  },
  {
    name: 'synkDeleteProject',
    description: 'Delete a project.',
    tool: synkDeleteProject,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['repo', 'remove'],
  },
  {
    name: 'synkBulkDeleteProjects',
    description: 'Delete up to 100 projects.',
    tool: synkBulkDeleteProjects,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['repos', 'bulk', 'cleanup'],
  },
  {
    name: 'synkListTargets',
    description: 'List scan targets.',
    tool: synkListTargets,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['repos', 'images', 'sources'],
  },
  {
    name: 'synkGetTarget',
    description: 'Get one target.',
    tool: synkGetTarget,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['repo', 'fetch'],
  },
  {
    name: 'synkDeleteTarget',
    description: 'Delete a target and its projects.',
    tool: synkDeleteTarget,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['repo', 'remove'],
  },
  {
    name: 'synkCreateCollection',
    description: 'Create a project collection.',
    tool: synkCreateCollection,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['grouping', 'insights'],
  },
  {
    name: 'synkListCollections',
    description: 'List project collections.',
    tool: synkListCollections,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['groupings'],
  },
  {
    name: 'synkGetCollection',
    description: 'Get one collection.',
    tool: synkGetCollection,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['grouping', 'fetch'],
  },
  {
    name: 'synkUpdateCollection',
    description: 'Edit a collection.',
    tool: synkUpdateCollection,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['grouping', 'rename'],
  },
  {
    name: 'synkDeleteCollection',
    description: 'Delete a collection.',
    tool: synkDeleteCollection,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['grouping', 'remove'],
  },
  {
    name: 'synkAddProjectsToCollection',
    description: 'Add projects to a collection.',
    tool: synkAddProjectsToCollection,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['grouping', 'associate'],
  },
  {
    name: 'synkListCollectionProjects',
    description: 'List projects in a collection.',
    tool: synkListCollectionProjects,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['grouping', 'members'],
  },
  {
    name: 'synkRemoveProjectsFromCollection',
    description: 'Remove projects from a collection.',
    tool: synkRemoveProjectsFromCollection,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['grouping', 'disassociate'],
  },
  {
    name: 'synkListOrgIssues',
    description: 'List issues in an org.',
    tool: synkListOrgIssues,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['vulnerabilities', 'cves', 'findings'],
  },
  {
    name: 'synkGetOrgIssue',
    description: 'Get one org issue.',
    tool: synkGetOrgIssue,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['vulnerability', 'cve', 'fetch'],
  },
  {
    name: 'synkListGroupIssues',
    description: 'List issues across a group.',
    tool: synkListGroupIssues,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['vulnerabilities', 'findings'],
  },
  {
    name: 'synkGetGroupIssue',
    description: 'Get one group issue.',
    tool: synkGetGroupIssue,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['vulnerability', 'fetch'],
  },
  {
    name: 'synkListPackageIssues',
    description: 'List issues for one package URL.',
    tool: synkListPackageIssues,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['dependency', 'purl', 'cve'],
  },
  {
    name: 'synkListIssuesForPackages',
    description: 'List issues for a batch of packages.',
    tool: synkListIssuesForPackages,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['dependencies', 'bulk'],
  },
  {
    name: 'synkGetProjectSbom',
    description: 'Generate a project SBOM document.',
    tool: synkGetProjectSbom,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['cyclonedx', 'spdx', 'inventory'],
  },
  {
    name: 'synkCreateSbomTest',
    description: 'Test an SBOM for vulnerabilities (async).',
    tool: synkCreateSbomTest,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['scan', 'cyclonedx'],
  },
  {
    name: 'synkGetSbomTest',
    description: 'Get SBOM test status.',
    tool: synkGetSbomTest,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['scan', 'poll'],
  },
  {
    name: 'synkGetSbomTestResults',
    description: 'Get SBOM test results.',
    tool: synkGetSbomTestResults,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['scan', 'findings'],
  },
  {
    name: 'synkListContainerImages',
    description: 'List monitored container images.',
    tool: synkListContainerImages,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['docker', 'registry'],
  },
  {
    name: 'synkGetContainerImage',
    description: 'Get one container image.',
    tool: synkGetContainerImage,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['docker', 'fetch'],
  },
  {
    name: 'synkListImageTargetRefs',
    description: 'List image tags/digests.',
    tool: synkListImageTargetRefs,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['docker', 'tags'],
  },
  {
    name: 'synkCreateTest',
    description: 'Start an async unmanaged test run.',
    tool: synkCreateTest,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['scan', 'depgraph'],
  },
  {
    name: 'synkGetTest',
    description: 'Get one async test.',
    tool: synkGetTest,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['scan', 'fetch'],
  },
  {
    name: 'synkGetTestJob',
    description: 'Get async test job status.',
    tool: synkGetTestJob,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['scan', 'poll'],
  },
  {
    name: 'synkListTestFindings',
    description: 'List findings of a test.',
    tool: synkListTestFindings,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['scan', 'results'],
  },
  {
    name: 'synkInviteUser',
    description: 'Invite a user to an org.',
    tool: synkInviteUser,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['onboard', 'email'],
  },
  {
    name: 'synkListInvites',
    description: 'List pending org invitations.',
    tool: synkListInvites,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['pending', 'onboarding'],
  },
  {
    name: 'synkCancelInvite',
    description: 'Cancel a pending invitation.',
    tool: synkCancelInvite,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['revoke', 'withdraw'],
  },
  {
    name: 'synkSearchOrgAuditLogs',
    description: 'Search org audit logs.',
    tool: synkSearchOrgAuditLogs,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['compliance', 'forensics', 'activity'],
  },
  {
    name: 'synkSearchGroupAuditLogs',
    description: 'Search group audit logs.',
    tool: synkSearchGroupAuditLogs,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['compliance', 'activity'],
  },
  {
    name: 'synkListServiceAccounts',
    description: 'List org service accounts.',
    tool: synkListServiceAccounts,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['bots', 'automation'],
  },
  {
    name: 'synkCreateServiceAccount',
    description: 'Create a service account.',
    tool: synkCreateServiceAccount,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['bot', 'ci', 'provision'],
  },
  {
    name: 'synkGetServiceAccount',
    description: 'Get one service account.',
    tool: synkGetServiceAccount,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['bot', 'fetch'],
  },
  {
    name: 'synkUpdateServiceAccount',
    description: 'Update a service account.',
    tool: synkUpdateServiceAccount,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['bot', 'edit'],
  },
  {
    name: 'synkDeleteServiceAccount',
    description: 'Delete a service account.',
    tool: synkDeleteServiceAccount,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['bot', 'remove'],
  },
  {
    name: 'synkCreateServiceAccountSecret',
    description: 'Create a service account secret.',
    tool: synkCreateServiceAccountSecret,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['bot', 'credential', 'rotate'],
  },
  {
    name: 'synkListOrgApps',
    description: 'List apps created by an org.',
    tool: synkListOrgApps,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['integrations', 'oauth'],
  },
  {
    name: 'synkListOrgInstalls',
    description: 'List apps installed in an org.',
    tool: synkListOrgInstalls,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['integrations'],
  },
  {
    name: 'synkInstallOrgApp',
    description: 'Install an app into an org.',
    tool: synkInstallOrgApp,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['integration', 'enable'],
  },
  {
    name: 'synkRevokeOrgAppInstall',
    description: 'Revoke an app installation.',
    tool: synkRevokeOrgAppInstall,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['integration', 'disable'],
  },
  {
    name: 'synkGetSelf',
    description: 'Get token owner identity.',
    tool: synkGetSelf,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['whoami', 'health', 'verify'],
  },
  {
    name: 'synkListPersonalAccessTokens',
    description: 'List personal access tokens.',
    tool: synkListPersonalAccessTokens,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['pat', 'audit'],
  },
  {
    name: 'synkDeletePersonalAccessToken',
    description: 'Revoke a personal access token.',
    tool: synkDeletePersonalAccessToken,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['pat', 'revoke'],
  },
  {
    name: 'synkV1ListOrgs',
    description: 'List user organizations (V1).',
    tool: synkV1ListOrgs,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['workspaces', 'legacy'],
  },
  {
    name: 'synkV1CreateOrg',
    description: 'Create an organization (V1).',
    tool: synkV1CreateOrg,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['workspace', 'provision'],
  },
  {
    name: 'synkV1DeleteOrg',
    description: 'Remove an organization (V1).',
    tool: synkV1DeleteOrg,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['workspace', 'remove'],
  },
  {
    name: 'synkV1GetOrgSettings',
    description: 'View org settings (V1).',
    tool: synkV1GetOrgSettings,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['config', 'fetch'],
  },
  {
    name: 'synkV1UpdateOrgSettings',
    description: 'Update org settings (V1).',
    tool: synkV1UpdateOrgSettings,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['config', 'access'],
  },
  {
    name: 'synkV1ListMembers',
    description: 'List org members (V1).',
    tool: synkV1ListMembers,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['users', 'roles'],
  },
  {
    name: 'synkV1UpdateMember',
    description: 'Update a member role (V1).',
    tool: synkV1UpdateMember,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['user', 'role'],
  },
  {
    name: 'synkV1RemoveMember',
    description: 'Remove an org member (V1).',
    tool: synkV1RemoveMember,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['user', 'kick'],
  },
  {
    name: 'synkV1InviteUser',
    description: 'Invite a user by email (V1).',
    tool: synkV1InviteUser,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['onboard', 'email'],
  },
  {
    name: 'synkV1ListIntegrations',
    description: 'List org integrations (V1).',
    tool: synkV1ListIntegrations,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['github', 'scm', 'broker'],
  },
  {
    name: 'synkV1AddIntegration',
    description: 'Add an integration (V1).',
    tool: synkV1AddIntegration,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['github', 'connect'],
  },
  {
    name: 'synkV1UpdateIntegration',
    description: 'Update integration credentials (V1).',
    tool: synkV1UpdateIntegration,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['broker', 'rotate', 'token'],
  },
  {
    name: 'synkV1GetIntegrationSettings',
    description: 'Get integration settings (V1).',
    tool: synkV1GetIntegrationSettings,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['config', 'fetch'],
  },
  {
    name: 'synkV1UpdateIntegrationSettings',
    description: 'Update integration settings (V1).',
    tool: synkV1UpdateIntegrationSettings,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['config', 'checks'],
  },
  {
    name: 'synkV1ImportTargets',
    description: 'Import repos via integration (V1).',
    tool: synkV1ImportTargets,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['onboard', 'repos', 'scan'],
  },
  {
    name: 'synkV1GetImportJob',
    description: 'Poll import job status (V1).',
    tool: synkV1GetImportJob,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['onboard', 'poll'],
  },
  {
    name: 'synkV1ListIgnores',
    description: 'List project ignores (V1).',
    tool: synkV1ListIgnores,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['suppress', 'wontfix'],
  },
  {
    name: 'synkV1AddIgnore',
    description: 'Ignore an issue (V1).',
    tool: synkV1AddIgnore,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['suppress', 'accept-risk'],
  },
  {
    name: 'synkV1GetIgnore',
    description: 'Get an issue ignore record (V1).',
    tool: synkV1GetIgnore,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['suppress', 'fetch'],
  },
  {
    name: 'synkV1DeleteIgnore',
    description: 'Un-ignore an issue (V1).',
    tool: synkV1DeleteIgnore,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['unsuppress', 'reopen'],
  },
  {
    name: 'synkV1GetProject',
    description: 'Get a project (V1).',
    tool: synkV1GetProject,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['repo', 'legacy'],
  },
  {
    name: 'synkV1UpdateProject',
    description: 'Update a project (V1).',
    tool: synkV1UpdateProject,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['repo', 'edit'],
  },
  {
    name: 'synkV1DeleteProject',
    description: 'Delete a project (V1).',
    tool: synkV1DeleteProject,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['repo', 'remove'],
  },
  {
    name: 'synkV1AddProjectTag',
    description: 'Tag a project (V1).',
    tool: synkV1AddProjectTag,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['label', 'group'],
  },
  {
    name: 'synkV1RemoveProjectTag',
    description: 'Remove a project tag (V1).',
    tool: synkV1RemoveProjectTag,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['label', 'untag'],
  },
  {
    name: 'synkV1ListAggregatedIssues',
    description: 'List aggregated project issues (V1, legacy regions).',
    tool: synkV1ListAggregatedIssues,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['vulnerabilities', 'legacy'],
  },
  {
    name: 'synkV1TestPackage',
    description: 'Test a package version for vulns (V1).',
    tool: synkV1TestPackage,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['audit', 'dependency', 'check'],
  },
  {
    name: 'synkV1ListJiraIssues',
    description: 'List Jira issues for a project (V1).',
    tool: synkV1ListJiraIssues,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['tickets'],
  },
  {
    name: 'synkV1CreateJiraIssue',
    description: 'File a Jira issue from a Snyk issue (V1).',
    tool: synkV1CreateJiraIssue,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['ticket', 'escalate'],
  },
  {
    name: 'synkV1ListWebhooks',
    description: 'List org webhooks (V1).',
    tool: synkV1ListWebhooks,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['events', 'notifications'],
  },
  {
    name: 'synkV1CreateWebhook',
    description: 'Create an org webhook (V1).',
    tool: synkV1CreateWebhook,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['events', 'subscribe'],
  },
  {
    name: 'synkV1GetWebhook',
    description: 'Get one webhook (V1).',
    tool: synkV1GetWebhook,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['event', 'fetch'],
  },
  {
    name: 'synkV1DeleteWebhook',
    description: 'Delete a webhook (V1).',
    tool: synkV1DeleteWebhook,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['event', 'remove'],
  },
  {
    name: 'synkV1PingWebhook',
    description: 'Ping a webhook endpoint (V1).',
    tool: synkV1PingWebhook,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['event', 'test'],
  },
  {
    name: 'synkV1ListEntitlements',
    description: 'List org entitlements (V1).',
    tool: synkV1ListEntitlements,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['features', 'plan'],
  },
  {
    name: 'synkV1GetEntitlement',
    description: 'Get one entitlement value (V1).',
    tool: synkV1GetEntitlement,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['feature', 'fetch'],
  },
  {
    name: 'synkV1ListDependencies',
    description: 'List project dependencies (V1).',
    tool: synkV1ListDependencies,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['sbom', 'packages'],
  },
  {
    name: 'synkV1ListGroupTags',
    description: 'List project tags in a group (V1).',
    tool: synkV1ListGroupTags,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['labels'],
  },
  {
    name: 'synkV1DeleteGroupTag',
    description: 'Delete a group project tag (V1).',
    tool: synkV1DeleteGroupTag,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['label', 'remove'],
  },
];
