// @ts-nocheck
import {
  whatsappSendMessage,
  whatsappSendTemplateMessage,
  whatsappSendMedia,
  whatsappSendMediaById,
  whatsappSendLocation,
  whatsappSendContacts,
  whatsappSendInteractiveButtons,
  whatsappSendInteractiveList,
} from './messages.js';
import {
  whatsappCreateTemplate,
  whatsappGetTemplates,
  whatsappDeleteTemplate,
  whatsappGetTemplateStatus,
  whatsappGetTemplateLibrary,
  whatsappUpsertTemplate,
} from './templates.js';
import {
  whatsappUploadMedia,
  whatsappCreateUploadSession,
  whatsappGetMediaInfo,
  whatsappDeleteMedia,
} from './media.js';
import {
  whatsappGetPhoneNumbers,
  whatsappGetPhoneNumber,
  whatsappRegisterPhone,
  whatsappDeregisterPhone,
  whatsappVerifyCode,
  whatsappSetTwoStepPin,
  whatsappGetBusinessProfile,
  whatsappUpdateBusinessProfile,
  whatsappBlockUsers,
  whatsappGetCommerceSettings,
  whatsappUpdateCommerceSettings,
  whatsappGetComplianceInfo,
  whatsappGetEncryption,
  whatsappGetSettings,
  whatsappUpdateSettings,
  whatsappConfigureAutomation,
  whatsappGetMessageHistory,
  whatsappCreateQrCode,
  whatsappListQrCodes,
  whatsappDeleteQrCode,
  whatsappListGroups,
  whatsappGetJoinRequests,
} from './phone.js';
import {
  whatsappCreateFlow,
  whatsappListFlows,
  whatsappUpdateFlowMeta,
  whatsappPublishFlow,
  whatsappGetFlowAssets,
  whatsappUpdateFlowJson,
} from './flows.js';
import {
  whatsappGetBusinessAccountDetails,
  whatsappGetActivities,
  whatsappGetSubscribedApps,
  whatsappSubscribeApp,
  whatsappUnsubscribeApp,
  whatsappRemoveAssignedUser,
  whatsappGetOwnedAccounts,
  whatsappGetClientAccounts,
  whatsappGetSchedules,
  whatsappGetSolutions,
  whatsappCreateMaxPriceAgreement,
  whatsappWhoAmI,
} from './waba.js';

export {
  whatsappSendMessage,
  whatsappSendTemplateMessage,
  whatsappSendMedia,
  whatsappSendMediaById,
  whatsappSendLocation,
  whatsappSendContacts,
  whatsappSendInteractiveButtons,
  whatsappSendInteractiveList,
  whatsappCreateTemplate,
  whatsappGetTemplates,
  whatsappDeleteTemplate,
  whatsappGetTemplateStatus,
  whatsappGetTemplateLibrary,
  whatsappUpsertTemplate,
  whatsappUploadMedia,
  whatsappCreateUploadSession,
  whatsappGetMediaInfo,
  whatsappDeleteMedia,
  whatsappGetPhoneNumbers,
  whatsappGetPhoneNumber,
  whatsappRegisterPhone,
  whatsappDeregisterPhone,
  whatsappVerifyCode,
  whatsappSetTwoStepPin,
  whatsappGetBusinessProfile,
  whatsappUpdateBusinessProfile,
  whatsappBlockUsers,
  whatsappGetCommerceSettings,
  whatsappUpdateCommerceSettings,
  whatsappGetComplianceInfo,
  whatsappGetEncryption,
  whatsappGetSettings,
  whatsappUpdateSettings,
  whatsappConfigureAutomation,
  whatsappGetMessageHistory,
  whatsappCreateQrCode,
  whatsappListQrCodes,
  whatsappDeleteQrCode,
  whatsappListGroups,
  whatsappGetJoinRequests,
  whatsappCreateFlow,
  whatsappListFlows,
  whatsappUpdateFlowMeta,
  whatsappPublishFlow,
  whatsappGetFlowAssets,
  whatsappUpdateFlowJson,
  whatsappGetBusinessAccountDetails,
  whatsappGetActivities,
  whatsappGetSubscribedApps,
  whatsappSubscribeApp,
  whatsappUnsubscribeApp,
  whatsappRemoveAssignedUser,
  whatsappGetOwnedAccounts,
  whatsappGetClientAccounts,
  whatsappGetSchedules,
  whatsappGetSolutions,
  whatsappCreateMaxPriceAgreement,
  whatsappWhoAmI,
};

const AUTH = 'whatsappCredentials' as const;

export const whatsappTools = [
  {
    name: 'whatsappSendMessage',
    description: 'Send a text message. Works inside the 24-hour window; otherwise use a template.',
    tool: whatsappSendMessage,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['text', 'sms', 'chat'],
  },
  {
    name: 'whatsappSendTemplateMessage',
    description: 'Send an approved template message. Required for first contact outside 24 hours.',
    tool: whatsappSendTemplateMessage,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['template', 'notification', 'marketing'],
  },
  {
    name: 'whatsappSendMedia',
    description: 'Send image, video, audio, document, or sticker by public URL.',
    tool: whatsappSendMedia,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['photo', 'video', 'file', 'attachment'],
  },
  {
    name: 'whatsappSendMediaById',
    description: 'Send previously uploaded media by media ID. Faster than by URL.',
    tool: whatsappSendMediaById,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['photo', 'video', 'file', 'upload'],
  },
  {
    name: 'whatsappSendLocation',
    description: 'Share coordinates with name and address. 24-hour window only.',
    tool: whatsappSendLocation,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['map', 'address', 'gps', 'pin'],
  },
  {
    name: 'whatsappSendContacts',
    description: 'Send contact cards (vCards) to a user or group.',
    tool: whatsappSendContacts,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['vcard', 'address-book', 'share'],
  },
  {
    name: 'whatsappSendInteractiveButtons',
    description: 'Send up to 3 quick-reply buttons. 24-hour window only.',
    tool: whatsappSendInteractiveButtons,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['buttons', 'cta', 'menu', 'choice'],
  },
  {
    name: 'whatsappSendInteractiveList',
    description: 'Send a sectioned option menu (up to 10 sections, 10 rows each).',
    tool: whatsappSendInteractiveList,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['menu', 'options', 'catalog', 'choice'],
  },
  {
    name: 'whatsappCreateTemplate',
    description:
      'Create a message template for approval. Needed for outbound marketing and 24h+ messages.',
    tool: whatsappCreateTemplate,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['template', 'notification', 'new'],
  },
  {
    name: 'whatsappGetTemplates',
    description: 'List message templates with status, category, and language filters.',
    tool: whatsappGetTemplates,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['template', 'browse', 'approved'],
  },
  {
    name: 'whatsappDeleteTemplate',
    description:
      'Delete templates by name (all languages) or one variant via hsm_id. Irreversible.',
    tool: whatsappDeleteTemplate,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['template', 'remove'],
  },
  {
    name: 'whatsappGetTemplateStatus',
    description: 'Check approval status and details of one template by ID.',
    tool: whatsappGetTemplateStatus,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['template', 'approved', 'rejected'],
  },
  {
    name: 'whatsappGetTemplateLibrary',
    description:
      'Browse pre-built Meta template library by topic, use case, industry, or language.',
    tool: whatsappGetTemplateLibrary,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['template', 'gallery', 'examples'],
  },
  {
    name: 'whatsappUpsertTemplate',
    description: 'Create a template or update the same-name one. Supports FOOTER and OTP buttons.',
    tool: whatsappUpsertTemplate,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['template', 'update', 'create'],
  },
  {
    name: 'whatsappUploadMedia',
    description: 'Upload media bytes for later sending. Returns a 30-day media ID.',
    tool: whatsappUploadMedia,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['upload', 'photo', 'file'],
  },
  {
    name: 'whatsappCreateUploadSession',
    description:
      'Start a resumable upload session for large files. Upload chunks to the session next.',
    tool: whatsappCreateUploadSession,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['upload', 'large', 'chunked'],
  },
  {
    name: 'whatsappGetMediaInfo',
    description: 'Get media metadata and a 5-minute download URL by media ID.',
    tool: whatsappGetMediaInfo,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['file', 'download', 'url'],
  },
  {
    name: 'whatsappDeleteMedia',
    description: 'Permanently delete uploaded media before its 30-day expiry.',
    tool: whatsappDeleteMedia,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['file', 'remove'],
  },
  {
    name: 'whatsappGetPhoneNumbers',
    description:
      'List registered phone numbers with IDs, quality, and throughput. Start here for IDs.',
    tool: whatsappGetPhoneNumbers,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['numbers', 'list', 'ids'],
  },
  {
    name: 'whatsappGetPhoneNumber',
    description:
      'Get verification status, quality rating, throughput, and webhook config for a number.',
    tool: whatsappGetPhoneNumber,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['number', 'status', 'details'],
  },
  {
    name: 'whatsappRegisterPhone',
    description: 'Register a verified number for Cloud API with a 6-digit two-step PIN.',
    tool: whatsappRegisterPhone,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['activate', 'onboard', 'setup'],
  },
  {
    name: 'whatsappDeregisterPhone',
    description:
      'Deregister a number to stop messaging, migrate, or retire it. Re-register to resume.',
    tool: whatsappDeregisterPhone,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['deactivate', 'remove', 'offboard'],
  },
  {
    name: 'whatsappVerifyCode',
    description: 'Submit the 6-digit SMS/voice OTP to verify a number.',
    tool: whatsappVerifyCode,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['otp', 'confirm', 'activate'],
  },
  {
    name: 'whatsappSetTwoStepPin',
    description: 'Set or reset the two-step verification PIN on a registered number.',
    tool: whatsappSetTwoStepPin,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['pin', 'password', 'security'],
  },
  {
    name: 'whatsappGetBusinessProfile',
    description: 'Get about, address, email, websites, and vertical for a number.',
    tool: whatsappGetBusinessProfile,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['profile', 'bio', 'details'],
  },
  {
    name: 'whatsappUpdateBusinessProfile',
    description: 'Update about, address, email, websites, vertical, or profile picture.',
    tool: whatsappUpdateBusinessProfile,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['profile', 'edit', 'bio'],
  },
  {
    name: 'whatsappBlockUsers',
    description: 'Block up to 100 users who messaged you in the last 24 hours.',
    tool: whatsappBlockUsers,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['ban', 'spam', 'mute'],
  },
  {
    name: 'whatsappGetCommerceSettings',
    description: 'Check cart and catalog visibility for a number.',
    tool: whatsappGetCommerceSettings,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['shop', 'cart', 'catalog', 'store'],
  },
  {
    name: 'whatsappUpdateCommerceSettings',
    description: 'Enable or disable cart and catalog visibility.',
    tool: whatsappUpdateCommerceSettings,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['shop', 'cart', 'catalog', 'store'],
  },
  {
    name: 'whatsappGetComplianceInfo',
    description: 'Get entity registration, grievance officer, and customer care details.',
    tool: whatsappGetComplianceInfo,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['legal', 'grievance', 'registration'],
  },
  {
    name: 'whatsappGetEncryption',
    description: 'Get the end-to-end encryption public key and signature status.',
    tool: whatsappGetEncryption,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['security', 'key', 'e2ee'],
  },
  {
    name: 'whatsappGetSettings',
    description: 'Get calling, storage, and payload encryption settings.',
    tool: whatsappGetSettings,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['config', 'calling', 'storage'],
  },
  {
    name: 'whatsappUpdateSettings',
    description:
      'Update exactly one setting group: calling, encryption, storage, or identity check.',
    tool: whatsappUpdateSettings,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['config', 'calling', 'storage'],
  },
  {
    name: 'whatsappConfigureAutomation',
    description: 'Set welcome messages, ice-breaker prompts, and bot commands.',
    tool: whatsappConfigureAutomation,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['greeting', 'bot', 'commands', 'icebreaker'],
  },
  {
    name: 'whatsappGetMessageHistory',
    description: 'Track delivery status events per message with pagination.',
    tool: whatsappGetMessageHistory,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['status', 'delivered', 'read', 'audit'],
  },
  {
    name: 'whatsappCreateQrCode',
    description: 'Create a scannable QR code with a prefilled greeting, optionally as PNG/SVG.',
    tool: whatsappCreateQrCode,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['qr', 'scan', 'link'],
  },
  {
    name: 'whatsappListQrCodes',
    description: 'List message QR codes with pagination and optional code filter.',
    tool: whatsappListQrCodes,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['qr', 'scan', 'browse'],
  },
  {
    name: 'whatsappDeleteQrCode',
    description: 'Permanently delete a QR code. Irreversible.',
    tool: whatsappDeleteQrCode,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['qr', 'remove'],
  },
  {
    name: 'whatsappListGroups',
    description: 'List groups a business number belongs to. Official Business Accounts only.',
    tool: whatsappListGroups,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['group', 'chat', 'community'],
  },
  {
    name: 'whatsappGetJoinRequests',
    description: 'List pending group join requests for moderation.',
    tool: whatsappGetJoinRequests,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['group', 'approve', 'members'],
  },
  {
    name: 'whatsappCreateFlow',
    description: 'Create an interactive Flow in DRAFT. Configure JSON next, then publish.',
    tool: whatsappCreateFlow,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['flow', 'form', 'survey', 'new'],
  },
  {
    name: 'whatsappListFlows',
    description: 'List flows with status and validation errors.',
    tool: whatsappListFlows,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['flow', 'browse'],
  },
  {
    name: 'whatsappUpdateFlowMeta',
    description: 'Update Flow name, categories, or endpoint URI.',
    tool: whatsappUpdateFlowMeta,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['flow', 'edit', 'rename'],
  },
  {
    name: 'whatsappPublishFlow',
    description: 'Publish a validated DRAFT flow. Irreversible; version to change.',
    tool: whatsappPublishFlow,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['flow', 'release', 'deploy'],
  },
  {
    name: 'whatsappGetFlowAssets',
    description: 'List flow assets like flow.json with short-lived download URLs.',
    tool: whatsappGetFlowAssets,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['flow', 'json', 'download'],
  },
  {
    name: 'whatsappUpdateFlowJson',
    description: 'Upload flow.json content to a Flow. Fails with validation errors when invalid.',
    tool: whatsappUpdateFlowJson,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['flow', 'json', 'upload'],
  },
  {
    name: 'whatsappGetBusinessAccountDetails',
    description: 'Get WABA review status, verification, timezone, and ownership.',
    tool: whatsappGetBusinessAccountDetails,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['account', 'status', 'audit'],
  },
  {
    name: 'whatsappGetActivities',
    description: 'Audit admin actions like verifications and user additions.',
    tool: whatsappGetActivities,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['audit', 'log', 'history'],
  },
  {
    name: 'whatsappGetSubscribedApps',
    description: 'List apps subscribed to WABA webhooks.',
    tool: whatsappGetSubscribedApps,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['webhook', 'apps', 'integrations'],
  },
  {
    name: 'whatsappSubscribeApp',
    description: 'Subscribe your app to WABA webhooks with callback URL and verify token.',
    tool: whatsappSubscribeApp,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['webhook', 'register', 'events'],
  },
  {
    name: 'whatsappUnsubscribeApp',
    description: 'Stop webhook delivery for your app. Irreversible without resubscribing.',
    tool: whatsappUnsubscribeApp,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['webhook', 'remove', 'stop'],
  },
  {
    name: 'whatsappRemoveAssignedUser',
    description: 'Revoke a user access from the WABA immediately. Irreversible.',
    tool: whatsappRemoveAssignedUser,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['user', 'access', 'revoke'],
  },
  {
    name: 'whatsappGetOwnedAccounts',
    description: 'List WABAs directly owned by a business portfolio.',
    tool: whatsappGetOwnedAccounts,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['accounts', 'portfolio', 'owned'],
  },
  {
    name: 'whatsappGetClientAccounts',
    description: 'List client WABAs shared with a business portfolio. For agencies.',
    tool: whatsappGetClientAccounts,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['accounts', 'clients', 'agency'],
  },
  {
    name: 'whatsappGetSchedules',
    description: 'List campaign schedules with status and recurrence.',
    tool: whatsappGetSchedules,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['campaigns', 'scheduled', 'calendar'],
  },
  {
    name: 'whatsappGetSolutions',
    description: 'List multi-partner solutions linked to the WABA.',
    tool: whatsappGetSolutions,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['partners', 'apps', 'integrations'],
  },
  {
    name: 'whatsappCreateMaxPriceAgreement',
    description:
      'Sign the max-price beta agreement for a business. Per-message ceilings live on templates.',
    tool: whatsappCreateMaxPriceAgreement,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['pricing', 'billing', 'beta'],
  },
  {
    name: 'whatsappWhoAmI',
    description: 'Return the connected Meta account id and name.',
    tool: whatsappWhoAmI,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['identity', 'account', 'me'],
  },
];
