// @ts-nocheck
import { tool } from 'ai';
import { z } from 'zod';
import { vercelFetch } from './client.js';

export const vercelCheckCacheArtifactExists = tool({
    description: 'Tool to check if a cache artifact exists by its hash. Use when verifying whether a cache artifact is already stored before upload or when validating artifact availability.',
    inputSchema: z.object({
        vercelToken: z.string().describe('Vercel access token (Bearer).'),
        hash: z.string().describe('The artifact hash to check for existence.'),
        slug: z.string().optional().describe('The Team slug to perform the request on behalf of.'),
        teamId: z.string().optional().describe('The Team identifier to perform the request on behalf of.'),
    }),
    execute: async (params) => {
        const { vercelToken, teamId, slug, ...rest } = params as any;
        if (!vercelToken) return { error: 'Vercel token is required. Connect Vercel first.' };
        try {
            const path = (() => { const p: any = rest; return `/v8/artifacts/${p.hash}`; })();
            const res = await vercelFetch(path, { vercelToken, method: 'HEAD', teamId, slug, body: undefined, query: undefined });
            if (!res.ok) return { error: 'Check Artifact Exists failed', details: res.data };
            return res.data;
        } catch (e) { return { error: 'Error in vercelCheckCacheArtifactExists', message: e instanceof Error ? e.message : 'Unknown error' }; }
    },
});

export const vercelDeleteDataCachePurgeAll = tool({
    description: 'Tool to purge all data cache entries for a specific project. Use when you need to clear the entire data cache for a project.',
    inputSchema: z.object({
        vercelToken: z.string().describe('Vercel access token (Bearer).'),
        teamId: z.string().optional().describe('Optional team identifier to perform the request on behalf of.'),
        projectIdOrName: z.string().describe('The project ID or name for which to purge all data cache entries.'),
    }),
    execute: async (params) => {
        const { vercelToken, teamId, slug, ...rest } = params as any;
        if (!vercelToken) return { error: 'Vercel token is required. Connect Vercel first.' };
        try {
            const path = (() => { const p: any = rest; return `/v1/projects/${p.projectIdOrName}/data-cache`; })();
            const res = await vercelFetch(path, { vercelToken, method: 'DELETE', teamId, slug, body: rest, query: undefined });
            if (!res.ok) return { error: 'Purge All Data Cache failed', details: res.data };
            return res.data;
        } catch (e) { return { error: 'Error in vercelDeleteDataCachePurgeAll', message: e instanceof Error ? e.message : 'Unknown error' }; }
    },
});

export const vercelDownloadArtifact = tool({
    description: 'Download a cache artifact from Vercel\'s Remote Cache by its hash. Use this to retrieve previously cached build artifacts generated by Turborepo or other build systems. Remote Caching must be enabled for the team. Returns a tar.gz compressed file.',
    inputSchema: z.object({
        vercelToken: z.string().describe('Vercel access token (Bearer).'),
        hash: z.string().describe('The unique artifact hash identifier generated by the build system (e.g., Turborepo). This hash uniquely identifies the cached build artifact to download.'),
        slug: z.string().optional().describe('The Team URL slug to perform the request on behalf of. Can be used as an alternative to teamId.'),
        teamId: z.string().optional().describe('The Team identifier to perform the request on behalf of. Required to access team-level cached artifacts.'),
        xArtifactClientCi: z.string().optional().describe('The CI/CD environment where this artifact is being downloaded (e.g., \'VERCEL\', \'GITHUB_ACTIONS\', \'CIRCLECI\'). Max 50 characters.'),
        xArtifactClientInteractive: z.number().optional().describe('Indicates if the client is an interactive shell. Set to 1 for interactive, 0 for non-interactive (CI environments).'),
    }),
    execute: async (params) => {
        const { vercelToken, teamId, slug, ...rest } = params as any;
        if (!vercelToken) return { error: 'Vercel token is required. Connect Vercel first.' };
        try {
            const path = (() => { const p: any = rest; return `/v8/artifacts/${p.hash}`; })();
            const res = await vercelFetch(path, { vercelToken, method: 'GET', teamId, slug, body: undefined, query: rest });
            if (!res.ok) return { error: 'Download Cache Artifact failed', details: res.data };
            return res.data;
        } catch (e) { return { error: 'Error in vercelDownloadArtifact', message: e instanceof Error ? e.message : 'Unknown error' }; }
    },
});

export const vercelGetArtifactInfo = tool({
    description: 'Tool to query information about artifacts by their hashes. Use when you need to retrieve metadata about one or more artifacts, including size, processing duration, and tags.',
    inputSchema: z.object({
        vercelToken: z.string().describe('Vercel access token (Bearer).'),
        slug: z.string().optional().describe('The Team slug to perform the request on behalf of'),
        hashes: z.array(z.string()).describe('List of artifact hashes to query information for'),
        teamId: z.string().optional().describe('The Team identifier to perform the request on behalf of'),
    }),
    execute: async (params) => {
        const { vercelToken, teamId, slug, ...rest } = params as any;
        if (!vercelToken) return { error: 'Vercel token is required. Connect Vercel first.' };
        try {
            const path = (() => { const p: any = rest; return `/v8/artifacts`; })();
            const res = await vercelFetch(path, { vercelToken, method: 'GET', teamId, slug, body: undefined, query: rest });
            if (!res.ok) return { error: 'Query Artifact Information failed', details: res.data };
            return res.data;
        } catch (e) { return { error: 'Error in vercelGetArtifactInfo', message: e instanceof Error ? e.message : 'Unknown error' }; }
    },
});

export const vercelGetCacheStatus = tool({
    description: 'Tool to get the status of Remote Caching for the principal. Use when you need to check if Remote Caching is enabled, disabled, over limit, or paused.',
    inputSchema: z.object({
        vercelToken: z.string().describe('Vercel access token (Bearer).'),
        slug: z.string().optional().describe('The Team slug to perform the request on behalf of.'),
        teamId: z.string().optional().describe('The Team identifier to perform the request on behalf of.'),
    }),
    execute: async (params) => {
        const { vercelToken, teamId, slug, ...rest } = params as any;
        if (!vercelToken) return { error: 'Vercel token is required. Connect Vercel first.' };
        try {
            const path = (() => { const p: any = rest; return `/v1/cache/status`; })();
            const res = await vercelFetch(path, { vercelToken, method: 'GET', teamId, slug, body: undefined, query: rest });
            if (!res.ok) return { error: 'Get Remote Caching Status failed', details: res.data };
            return res.data;
        } catch (e) { return { error: 'Error in vercelGetCacheStatus', message: e instanceof Error ? e.message : 'Unknown error' }; }
    },
});

export const vercelInvalidateCacheBySrcImages = tool({
    description: 'Tool to invalidate edge cache by source image URLs. Use when you need to mark cached images as stale for specific source images. Invalidated images are revalidated in the background on the next request, ensuring zero latency impact for users.',
    inputSchema: z.object({
        vercelToken: z.string().describe('Vercel access token (Bearer).'),
        slug: z.string().optional().describe('The Team slug to perform the request on behalf of.'),
        teamId: z.string().optional().describe('The Team identifier to perform the request on behalf of.'),
        srcImages: z.array(z.string()).describe('List of source image URLs to invalidate from edge cache. Must contain 1-8 URLs, each up to 8192 characters. Invalidated images will be revalidated in the background on next request.'),
        projectIdOrName: z.string().describe('The project ID or name to invalidate cache for. This is required and must be a valid project identifier.'),
    }),
    execute: async (params) => {
        const { vercelToken, teamId, slug, ...rest } = params as any;
        if (!vercelToken) return { error: 'Vercel token is required. Connect Vercel first.' };
        try {
            const path = (() => { const p: any = rest; return `/v1/projects/${p.projectIdOrName}/cache/invalidate/images`; })();
            const res = await vercelFetch(path, { vercelToken, method: 'POST', teamId, slug, body: rest, query: undefined });
            if (!res.ok) return { error: 'Invalidate Cache By Source Images failed', details: res.data };
            return res.data;
        } catch (e) { return { error: 'Error in vercelInvalidateCacheBySrcImages', message: e instanceof Error ? e.message : 'Unknown error' }; }
    },
});

export const vercelInvalidateCacheByTags = tool({
    description: 'Tool to invalidate edge cache by tags. Use when you need to mark cached content as stale for specific cache tags. Invalidated content is revalidated in the background on the next request, ensuring zero latency impact for users.',
    inputSchema: z.object({
        vercelToken: z.string().describe('Vercel access token (Bearer).'),
        slug: z.string().optional().describe('The Team slug to perform the request on behalf of.'),
        tags: z.string().describe('Cache tags to invalidate. Can be a single tag string or a list of tag strings (1-16 elements, max 256 chars per tag). Invalidated content will be revalidated in the background on next request.'),
        target: z.string().optional().describe('Target environment to invalidate cache from. Either \'production\' or \'preview\'.'),
        teamId: z.string().optional().describe('The Team identifier to perform the request on behalf of.'),
        projectIdOrName: z.string().describe('The project ID or name to invalidate cache for. This is required and must be a valid project identifier.'),
    }),
    execute: async (params) => {
        const { vercelToken, teamId, slug, ...rest } = params as any;
        if (!vercelToken) return { error: 'Vercel token is required. Connect Vercel first.' };
        try {
            const path = (() => { const p: any = rest; return `/v1/projects/${p.projectIdOrName}/cache/invalidate/tags`; })();
            const res = await vercelFetch(path, { vercelToken, method: 'POST', teamId, slug, body: rest, query: undefined });
            if (!res.ok) return { error: 'Invalidate Cache By Tags failed', details: res.data };
            return res.data;
        } catch (e) { return { error: 'Error in vercelInvalidateCacheByTags', message: e instanceof Error ? e.message : 'Unknown error' }; }
    },
});

export const vercelUploadArtifact = tool({
    description: 'Tool to upload a cache artifact to Vercel. Use when you need to store build artifacts in Vercel\'s remote cache.',
    inputSchema: z.object({
        vercelToken: z.string().describe('Vercel access token (Bearer).'),
        hash: z.string().describe('The artifact hash identifier'),
        slug: z.string().optional().describe('Team slug to perform the request on behalf of'),
        teamId: z.string().optional().describe('Team identifier to perform the request on behalf of'),
        artifact: z.record(z.any()).describe('The artifact file to upload.'),
        xArtifactTag: z.string().optional().describe('The base64 encoded tag for this artifact.'),
        xArtifactDuration: z.number().optional().describe('The time taken to generate the uploaded artifact in milliseconds'),
        xArtifactClientCi: z.string().optional().describe('The continuous integration or delivery environment where this artifact was generated'),
        xArtifactClientInteractive: z.number().optional().describe('1 if the client is an interactive shell, otherwise 0'),
    }),
    execute: async (params) => {
        const { vercelToken, teamId, slug, ...rest } = params as any;
        if (!vercelToken) return { error: 'Vercel token is required. Connect Vercel first.' };
        try {
            const path = (() => { const p: any = rest; return `/v8/artifacts/${p.hash}`; })();
            const res = await vercelFetch(path, { vercelToken, method: 'POST', teamId, slug, body: rest, query: undefined });
            if (!res.ok) return { error: 'Upload Cache Artifact failed', details: res.data };
            return res.data;
        } catch (e) { return { error: 'Error in vercelUploadArtifact', message: e instanceof Error ? e.message : 'Unknown error' }; }
    },
});
