// @ts-nocheck
import {
  huggingFaceChangeDiscussionsStatus,
  huggingFaceCreateDiscussions,
  huggingFaceCreateDiscussionsComment,
  huggingFaceCreateDiscussionsPin,
  huggingFaceDeleteDiscussions,
  huggingFaceGetDiscussion,
  huggingFaceListDiscussions,
  huggingFaceUpdateDiscussionsTitle,
} from './discussions.js';
export {
  huggingFaceChangeDiscussionsStatus,
  huggingFaceCreateDiscussions,
  huggingFaceCreateDiscussionsComment,
  huggingFaceCreateDiscussionsPin,
  huggingFaceDeleteDiscussions,
  huggingFaceGetDiscussion,
  huggingFaceListDiscussions,
  huggingFaceUpdateDiscussionsTitle,
};
import {
  huggingFaceCheckDatasetValidity,
  huggingFaceFilterDatasetRows,
  huggingFaceGetDatasetCroissant,
  huggingFaceGetDatasetFirstRows,
  huggingFaceGetDatasetInfo,
  huggingFaceGetDatasetRows,
  huggingFaceGetDatasetSize,
  huggingFaceGetDatasetStatistics,
  huggingFaceListDatasetParquetFiles,
  huggingFaceListDatasetSplits,
  huggingFaceSearchDataset,
} from './datasets-viewer.js';
export {
  huggingFaceCheckDatasetValidity,
  huggingFaceFilterDatasetRows,
  huggingFaceGetDatasetCroissant,
  huggingFaceGetDatasetFirstRows,
  huggingFaceGetDatasetInfo,
  huggingFaceGetDatasetRows,
  huggingFaceGetDatasetSize,
  huggingFaceGetDatasetStatistics,
  huggingFaceListDatasetParquetFiles,
  huggingFaceListDatasetSplits,
  huggingFaceSearchDataset,
};
import {
  huggingFaceCheckModelsUploadMethod,
  huggingFaceCreateModelsBranch,
  huggingFaceCreateModelsCommit,
  huggingFaceCreateModelsTag,
  huggingFaceGetModelInfo,
  huggingFaceGetModelsCompare,
  huggingFaceGetModelsJwt,
  huggingFaceGetModelsNotebook,
  huggingFaceGetModelsScan,
  huggingFaceGetModelsTreesize,
  huggingFaceGetModelsXetReadToken,
  huggingFaceGetResolveCacheModels,
  huggingFaceListModelsCommits,
  huggingFaceListModelsPathsInfo,
  huggingFaceListModelsRefs,
  huggingFaceUpdateModelsSettings,
} from './models.js';
export {
  huggingFaceCheckModelsUploadMethod,
  huggingFaceCreateModelsBranch,
  huggingFaceCreateModelsCommit,
  huggingFaceCreateModelsTag,
  huggingFaceGetModelInfo,
  huggingFaceGetModelsCompare,
  huggingFaceGetModelsJwt,
  huggingFaceGetModelsNotebook,
  huggingFaceGetModelsScan,
  huggingFaceGetModelsTreesize,
  huggingFaceGetModelsXetReadToken,
  huggingFaceGetResolveCacheModels,
  huggingFaceListModelsCommits,
  huggingFaceListModelsPathsInfo,
  huggingFaceListModelsRefs,
  huggingFaceUpdateModelsSettings,
};
import {
  huggingFaceCheckSpacesUploadMethod,
  huggingFaceCreateSpacesBranch,
  huggingFaceCreateSpacesCommit,
  huggingFaceCreateSpacesSecrets,
  huggingFaceCreateSpacesTag,
  huggingFaceCreateSpacesVariables,
  huggingFaceDeleteSpacesBranch,
  huggingFaceDeleteSpacesSecrets,
  huggingFaceDeleteSpacesTag,
  huggingFaceDeleteSpacesVariables,
  huggingFaceGetResolveCacheSpaces,
  huggingFaceGetSpaceInfo,
  huggingFaceGetSpacesCompare,
  huggingFaceGetSpacesEvents,
  huggingFaceGetSpacesJwt,
  huggingFaceGetSpacesMetrics,
  huggingFaceGetSpacesNotebook,
  huggingFaceGetSpacesResolve,
  huggingFaceGetSpacesScan,
  huggingFaceGetSpacesTreesize,
  huggingFaceGetSpacesXetReadToken,
  huggingFaceGetSpacesXetWriteToken,
  huggingFaceListSpacesCommits,
  huggingFaceListSpacesHardware,
  huggingFaceListSpacesLfsFiles,
  huggingFaceListSpacesPathsInfo,
  huggingFaceListSpacesRefs,
  huggingFaceSquashSpacesCommits,
  huggingFaceUpdateSpacesSettings,
} from './spaces.js';
export {
  huggingFaceCheckSpacesUploadMethod,
  huggingFaceCreateSpacesBranch,
  huggingFaceCreateSpacesCommit,
  huggingFaceCreateSpacesSecrets,
  huggingFaceCreateSpacesTag,
  huggingFaceCreateSpacesVariables,
  huggingFaceDeleteSpacesBranch,
  huggingFaceDeleteSpacesSecrets,
  huggingFaceDeleteSpacesTag,
  huggingFaceDeleteSpacesVariables,
  huggingFaceGetResolveCacheSpaces,
  huggingFaceGetSpaceInfo,
  huggingFaceGetSpacesCompare,
  huggingFaceGetSpacesEvents,
  huggingFaceGetSpacesJwt,
  huggingFaceGetSpacesMetrics,
  huggingFaceGetSpacesNotebook,
  huggingFaceGetSpacesResolve,
  huggingFaceGetSpacesScan,
  huggingFaceGetSpacesTreesize,
  huggingFaceGetSpacesXetReadToken,
  huggingFaceGetSpacesXetWriteToken,
  huggingFaceListSpacesCommits,
  huggingFaceListSpacesHardware,
  huggingFaceListSpacesLfsFiles,
  huggingFaceListSpacesPathsInfo,
  huggingFaceListSpacesRefs,
  huggingFaceSquashSpacesCommits,
  huggingFaceUpdateSpacesSettings,
};
import {
  huggingFaceClaimSettingsPapersClaim,
  huggingFaceCreatePapersComment,
  huggingFaceCreatePapersCommentReply,
  huggingFaceCreatePapersIndex,
  huggingFaceGetDailyPapers,
  huggingFaceSearchPapers,
} from './papers.js';
export {
  huggingFaceClaimSettingsPapersClaim,
  huggingFaceCreatePapersComment,
  huggingFaceCreatePapersCommentReply,
  huggingFaceCreatePapersIndex,
  huggingFaceGetDailyPapers,
  huggingFaceSearchPapers,
};
import {
  huggingFaceCreateAskAccess,
  huggingFaceCreateCollection,
  huggingFaceCreateRepo,
  huggingFaceGetDatasetsTagsByType,
  huggingFaceGetModelTagsByType,
  huggingFaceGetResolve,
  huggingFaceGetTrending,
  huggingFaceListCollections,
  huggingFaceListDatasets,
  huggingFaceListDocs,
  huggingFaceListRepoFiles,
  huggingFaceListSpaces,
  huggingFaceSearchDocs,
} from './repos.js';
export {
  huggingFaceCreateAskAccess,
  huggingFaceCreateCollection,
  huggingFaceCreateRepo,
  huggingFaceGetDatasetsTagsByType,
  huggingFaceGetModelTagsByType,
  huggingFaceGetResolve,
  huggingFaceGetTrending,
  huggingFaceListCollections,
  huggingFaceListDatasets,
  huggingFaceListDocs,
  huggingFaceListRepoFiles,
  huggingFaceListSpaces,
  huggingFaceSearchDocs,
};
import {
  huggingFaceCreateDatasetsBranch,
  huggingFaceCreateDatasetsCommit,
  huggingFaceCreateDatasetsPreupload,
  huggingFaceCreateDatasetsTag,
  huggingFaceDeleteDatasetsBranch,
  huggingFaceDeleteDatasetsTag,
  huggingFaceGetDatasetRepoInfo,
  huggingFaceGetDatasetsCompare,
  huggingFaceGetDatasetsJwt,
  huggingFaceGetDatasetsLeaderboard,
  huggingFaceGetDatasetsNotebook,
  huggingFaceGetDatasetsResolve,
  huggingFaceGetDatasetsScan,
  huggingFaceGetDatasetsTreesize,
  huggingFaceGetDatasetsXetReadToken,
  huggingFaceGetResolveCacheDatasets,
  huggingFaceHandleDatasetsUserAccessRequest,
  huggingFaceListDatasetPathsInfo,
  huggingFaceListDatasetsCommits,
  huggingFaceListDatasetsRefs,
  huggingFaceListDatasetsUserAccessRequest,
  huggingFaceSquashDatasetCommits,
  huggingFaceUpdateDatasetsSettings,
} from './datasets.js';
export {
  huggingFaceCreateDatasetsBranch,
  huggingFaceCreateDatasetsCommit,
  huggingFaceCreateDatasetsPreupload,
  huggingFaceCreateDatasetsTag,
  huggingFaceDeleteDatasetsBranch,
  huggingFaceDeleteDatasetsTag,
  huggingFaceGetDatasetRepoInfo,
  huggingFaceGetDatasetsCompare,
  huggingFaceGetDatasetsJwt,
  huggingFaceGetDatasetsLeaderboard,
  huggingFaceGetDatasetsNotebook,
  huggingFaceGetDatasetsResolve,
  huggingFaceGetDatasetsScan,
  huggingFaceGetDatasetsTreesize,
  huggingFaceGetDatasetsXetReadToken,
  huggingFaceGetResolveCacheDatasets,
  huggingFaceHandleDatasetsUserAccessRequest,
  huggingFaceListDatasetPathsInfo,
  huggingFaceListDatasetsCommits,
  huggingFaceListDatasetsRefs,
  huggingFaceListDatasetsUserAccessRequest,
  huggingFaceSquashDatasetCommits,
  huggingFaceUpdateDatasetsSettings,
};
import { huggingFaceCreateSqlConsoleEmbed, huggingFaceUpdateSqlConsoleEmbed } from './sql.js';
export { huggingFaceCreateSqlConsoleEmbed, huggingFaceUpdateSqlConsoleEmbed };
import {
  huggingFaceCreateWebhook,
  huggingFaceDeleteSettingsWebhooks,
  huggingFaceGetSettingsWebhooks,
  huggingFaceListSettingsWebhooks,
  huggingFaceUpdateSettingsWebhooks,
  huggingFaceUpdateWebhookStatus,
} from './webhooks.js';
export {
  huggingFaceCreateWebhook,
  huggingFaceDeleteSettingsWebhooks,
  huggingFaceGetSettingsWebhooks,
  huggingFaceListSettingsWebhooks,
  huggingFaceUpdateSettingsWebhooks,
  huggingFaceUpdateWebhookStatus,
};
import {
  huggingFaceDeleteNetworkCidrList,
  huggingFaceGenerateChatCompletion,
  huggingFaceGenerateEmbeddings,
  huggingFaceListEndpoints,
  huggingFaceListVendors,
} from './inference.js';
export {
  huggingFaceDeleteNetworkCidrList,
  huggingFaceGenerateChatCompletion,
  huggingFaceGenerateEmbeddings,
  huggingFaceListEndpoints,
  huggingFaceListVendors,
};
import {
  huggingFaceDeleteNotifications,
  huggingFaceGetOrganizationsAvatar,
  huggingFaceGetOrganizationsMembers,
  huggingFaceGetOrganizationsSocials,
  huggingFaceGetUsersAvatar,
  huggingFaceGetUsersOverview,
  huggingFaceGetUsersSocials,
  huggingFaceGetWhoami,
  huggingFaceListNotifications,
} from './users.js';
export {
  huggingFaceDeleteNotifications,
  huggingFaceGetOrganizationsAvatar,
  huggingFaceGetOrganizationsMembers,
  huggingFaceGetOrganizationsSocials,
  huggingFaceGetUsersAvatar,
  huggingFaceGetUsersOverview,
  huggingFaceGetUsersSocials,
  huggingFaceGetWhoami,
  huggingFaceListNotifications,
};
import {
  huggingFaceGetJobsHardware,
  huggingFaceGetSettingsBillingUsageJobs,
  huggingFaceGetSettingsBillingUsageLive,
  huggingFaceGetSettingsBillingUsageV2,
  huggingFaceGetSettingsMcp,
  huggingFaceUpdateSettingsNotifications,
  huggingFaceUpdateSettingsWatch,
} from './settings.js';
export {
  huggingFaceGetJobsHardware,
  huggingFaceGetSettingsBillingUsageJobs,
  huggingFaceGetSettingsBillingUsageLive,
  huggingFaceGetSettingsBillingUsageV2,
  huggingFaceGetSettingsMcp,
  huggingFaceUpdateSettingsNotifications,
  huggingFaceUpdateSettingsWatch,
};

export const huggingFaceTools = [
  {
    name: 'HuggingFaceChangeDiscussionsStatus',
    description: huggingFaceChangeDiscussionsStatus.description!,
    tool: huggingFaceChangeDiscussionsStatus,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'write' as const,
    keywords: ['thread', 'reopen'],
  },
  {
    name: 'HuggingFaceCheckDatasetValidity',
    description: huggingFaceCheckDatasetValidity.description!,
    tool: huggingFaceCheckDatasetValidity,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'read' as const,
    keywords: ['preview', 'viewer'],
  },
  {
    name: 'HuggingFaceCheckModelsUploadMethod',
    description: huggingFaceCheckModelsUploadMethod.description!,
    tool: huggingFaceCheckModelsUploadMethod,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'read' as const,
    keywords: ['lfs'],
  },
  {
    name: 'HuggingFaceCheckSpacesUploadMethod',
    description: huggingFaceCheckSpacesUploadMethod.description!,
    tool: huggingFaceCheckSpacesUploadMethod,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'read' as const,
    keywords: ['lfs'],
  },
  {
    name: 'HuggingFaceClaimSettingsPapersClaim',
    description: huggingFaceClaimSettingsPapersClaim.description!,
    tool: huggingFaceClaimSettingsPapersClaim,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'write' as const,
    keywords: ['authorship', 'author'],
  },
  {
    name: 'HuggingFaceCreateAskAccess',
    description: huggingFaceCreateAskAccess.description!,
    tool: huggingFaceCreateAskAccess,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'write' as const,
    keywords: ['gated', 'approval', 'permission'],
  },
  {
    name: 'HuggingFaceCreateCollection',
    description: huggingFaceCreateCollection.description!,
    tool: huggingFaceCreateCollection,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'write' as const,
    keywords: ['curate', 'organize'],
  },
  {
    name: 'HuggingFaceCreateDatasetsBranch',
    description: huggingFaceCreateDatasetsBranch.description!,
    tool: huggingFaceCreateDatasetsBranch,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'write' as const,
    keywords: ['version'],
  },
  {
    name: 'HuggingFaceCreateDatasetsCommit',
    description: huggingFaceCreateDatasetsCommit.description!,
    tool: huggingFaceCreateDatasetsCommit,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'write' as const,
    keywords: ['push', 'upload'],
  },
  {
    name: 'HuggingFaceCreateDatasetsPreupload',
    description: huggingFaceCreateDatasetsPreupload.description!,
    tool: huggingFaceCreateDatasetsPreupload,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'write' as const,
    keywords: ['lfs'],
  },
  {
    name: 'HuggingFaceCreateDatasetsTag',
    description: huggingFaceCreateDatasetsTag.description!,
    tool: huggingFaceCreateDatasetsTag,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'write' as const,
    keywords: ['release'],
  },
  {
    name: 'HuggingFaceCreateDiscussions',
    description: huggingFaceCreateDiscussions.description!,
    tool: huggingFaceCreateDiscussions,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'write' as const,
    keywords: ['thread', 'issue', 'pr'],
  },
  {
    name: 'HuggingFaceCreateDiscussionsComment',
    description: huggingFaceCreateDiscussionsComment.description!,
    tool: huggingFaceCreateDiscussionsComment,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'write' as const,
    keywords: ['thread', 'reply'],
  },
  {
    name: 'HuggingFaceCreateDiscussionsPin',
    description: huggingFaceCreateDiscussionsPin.description!,
    tool: huggingFaceCreateDiscussionsPin,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'write' as const,
    keywords: ['thread', 'highlight'],
  },
  {
    name: 'HuggingFaceCreateModelsBranch',
    description: huggingFaceCreateModelsBranch.description!,
    tool: huggingFaceCreateModelsBranch,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'write' as const,
    keywords: ['version'],
  },
  {
    name: 'HuggingFaceCreateModelsCommit',
    description: huggingFaceCreateModelsCommit.description!,
    tool: huggingFaceCreateModelsCommit,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'write' as const,
    keywords: ['push', 'upload', 'weights'],
  },
  {
    name: 'HuggingFaceCreateModelsTag',
    description: huggingFaceCreateModelsTag.description!,
    tool: huggingFaceCreateModelsTag,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'write' as const,
    keywords: ['release', 'version'],
  },
  {
    name: 'HuggingFaceCreatePapersComment',
    description: huggingFaceCreatePapersComment.description!,
    tool: huggingFaceCreatePapersComment,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'write' as const,
    keywords: ['review', 'feedback'],
  },
  {
    name: 'HuggingFaceCreatePapersCommentReply',
    description: huggingFaceCreatePapersCommentReply.description!,
    tool: huggingFaceCreatePapersCommentReply,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'write' as const,
    keywords: ['review', 'reply'],
  },
  {
    name: 'HuggingFaceCreatePapersIndex',
    description: huggingFaceCreatePapersIndex.description!,
    tool: huggingFaceCreatePapersIndex,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'write' as const,
    keywords: ['arxiv', 'submit', 'publish'],
  },
  {
    name: 'HuggingFaceCreateRepo',
    description: huggingFaceCreateRepo.description!,
    tool: huggingFaceCreateRepo,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'write' as const,
    keywords: ['repos', 'repository', 'new'],
  },
  {
    name: 'HuggingFaceCreateSpacesBranch',
    description: huggingFaceCreateSpacesBranch.description!,
    tool: huggingFaceCreateSpacesBranch,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'write' as const,
    keywords: ['version'],
  },
  {
    name: 'HuggingFaceCreateSpacesCommit',
    description: huggingFaceCreateSpacesCommit.description!,
    tool: huggingFaceCreateSpacesCommit,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'write' as const,
    keywords: ['push', 'deploy'],
  },
  {
    name: 'HuggingFaceCreateSpacesSecrets',
    description: huggingFaceCreateSpacesSecrets.description!,
    tool: huggingFaceCreateSpacesSecrets,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'write' as const,
    keywords: ['env', 'credentials'],
  },
  {
    name: 'HuggingFaceCreateSpacesTag',
    description: huggingFaceCreateSpacesTag.description!,
    tool: huggingFaceCreateSpacesTag,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'write' as const,
    keywords: ['release'],
  },
  {
    name: 'HuggingFaceCreateSpacesVariables',
    description: huggingFaceCreateSpacesVariables.description!,
    tool: huggingFaceCreateSpacesVariables,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'write' as const,
    keywords: ['env'],
  },
  {
    name: 'HuggingFaceCreateSqlConsoleEmbed',
    description: huggingFaceCreateSqlConsoleEmbed.description!,
    tool: huggingFaceCreateSqlConsoleEmbed,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'write' as const,
    keywords: ['duckdb', 'share'],
  },
  {
    name: 'HuggingFaceCreateWebhook',
    description: huggingFaceCreateWebhook.description!,
    tool: huggingFaceCreateWebhook,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'write' as const,
    keywords: ['notification', 'callback'],
  },
  {
    name: 'HuggingFaceDeleteDatasetsBranch',
    description: huggingFaceDeleteDatasetsBranch.description!,
    tool: huggingFaceDeleteDatasetsBranch,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'delete' as const,
    keywords: [],
  },
  {
    name: 'HuggingFaceDeleteDatasetsTag',
    description: huggingFaceDeleteDatasetsTag.description!,
    tool: huggingFaceDeleteDatasetsTag,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'delete' as const,
    keywords: [],
  },
  {
    name: 'HuggingFaceDeleteDiscussions',
    description: huggingFaceDeleteDiscussions.description!,
    tool: huggingFaceDeleteDiscussions,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'delete' as const,
    keywords: [],
  },
  {
    name: 'HuggingFaceDeleteNetworkCidrList',
    description: huggingFaceDeleteNetworkCidrList.description!,
    tool: huggingFaceDeleteNetworkCidrList,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'delete' as const,
    keywords: ['firewall', 'allowlist', 'ip'],
  },
  {
    name: 'HuggingFaceDeleteNotifications',
    description: huggingFaceDeleteNotifications.description!,
    tool: huggingFaceDeleteNotifications,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'delete' as const,
    keywords: ['notification', 'inbox', 'alert'],
  },
  {
    name: 'HuggingFaceDeleteSettingsWebhooks',
    description: huggingFaceDeleteSettingsWebhooks.description!,
    tool: huggingFaceDeleteSettingsWebhooks,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'delete' as const,
    keywords: ['notification', 'callback'],
  },
  {
    name: 'HuggingFaceDeleteSpacesBranch',
    description: huggingFaceDeleteSpacesBranch.description!,
    tool: huggingFaceDeleteSpacesBranch,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'delete' as const,
    keywords: [],
  },
  {
    name: 'HuggingFaceDeleteSpacesSecrets',
    description: huggingFaceDeleteSpacesSecrets.description!,
    tool: huggingFaceDeleteSpacesSecrets,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'delete' as const,
    keywords: ['env'],
  },
  {
    name: 'HuggingFaceDeleteSpacesTag',
    description: huggingFaceDeleteSpacesTag.description!,
    tool: huggingFaceDeleteSpacesTag,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'delete' as const,
    keywords: [],
  },
  {
    name: 'HuggingFaceDeleteSpacesVariables',
    description: huggingFaceDeleteSpacesVariables.description!,
    tool: huggingFaceDeleteSpacesVariables,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'delete' as const,
    keywords: ['env'],
  },
  {
    name: 'HuggingFaceFilterDatasetRows',
    description: huggingFaceFilterDatasetRows.description!,
    tool: huggingFaceFilterDatasetRows,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'read' as const,
    keywords: ['where'],
  },
  {
    name: 'HuggingFaceGenerateChatCompletion',
    description: huggingFaceGenerateChatCompletion.description!,
    tool: huggingFaceGenerateChatCompletion,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'write' as const,
    keywords: ['llm', 'inference', 'chatbot'],
  },
  {
    name: 'HuggingFaceGenerateEmbeddings',
    description: huggingFaceGenerateEmbeddings.description!,
    tool: huggingFaceGenerateEmbeddings,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'write' as const,
    keywords: ['embedding', 'vector'],
  },
  {
    name: 'HuggingFaceGetDailyPapers',
    description: huggingFaceGetDailyPapers.description!,
    tool: huggingFaceGetDailyPapers,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'read' as const,
    keywords: ['arxiv', 'trending'],
  },
  {
    name: 'HuggingFaceGetDatasetCroissant',
    description: huggingFaceGetDatasetCroissant.description!,
    tool: huggingFaceGetDatasetCroissant,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'read' as const,
    keywords: [],
  },
  {
    name: 'HuggingFaceGetDatasetFirstRows',
    description: huggingFaceGetDatasetFirstRows.description!,
    tool: huggingFaceGetDatasetFirstRows,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'read' as const,
    keywords: [],
  },
  {
    name: 'HuggingFaceGetDatasetInfo',
    description: huggingFaceGetDatasetInfo.description!,
    tool: huggingFaceGetDatasetInfo,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'read' as const,
    keywords: ['schema', 'metadata'],
  },
  {
    name: 'HuggingFaceGetDatasetRepoInfo',
    description: huggingFaceGetDatasetRepoInfo.description!,
    tool: huggingFaceGetDatasetRepoInfo,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'read' as const,
    keywords: ['metadata', 'downloads', 'likes'],
  },
  {
    name: 'HuggingFaceGetDatasetRows',
    description: huggingFaceGetDatasetRows.description!,
    tool: huggingFaceGetDatasetRows,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'read' as const,
    keywords: [],
  },
  {
    name: 'HuggingFaceGetDatasetsCompare',
    description: huggingFaceGetDatasetsCompare.description!,
    tool: huggingFaceGetDatasetsCompare,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'read' as const,
    keywords: ['diff'],
  },
  {
    name: 'HuggingFaceGetDatasetSize',
    description: huggingFaceGetDatasetSize.description!,
    tool: huggingFaceGetDatasetSize,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'read' as const,
    keywords: [],
  },
  {
    name: 'HuggingFaceGetDatasetsJwt',
    description: huggingFaceGetDatasetsJwt.description!,
    tool: huggingFaceGetDatasetsJwt,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'read' as const,
    keywords: ['token', 'auth'],
  },
  {
    name: 'HuggingFaceGetDatasetsLeaderboard',
    description: huggingFaceGetDatasetsLeaderboard.description!,
    tool: huggingFaceGetDatasetsLeaderboard,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'read' as const,
    keywords: ['ranking', 'benchmark', 'eval'],
  },
  {
    name: 'HuggingFaceGetDatasetsNotebook',
    description: huggingFaceGetDatasetsNotebook.description!,
    tool: huggingFaceGetDatasetsNotebook,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'read' as const,
    keywords: ['colab', 'jupyter'],
  },
  {
    name: 'HuggingFaceGetDatasetsResolve',
    description: huggingFaceGetDatasetsResolve.description!,
    tool: huggingFaceGetDatasetsResolve,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'read' as const,
    keywords: ['download'],
  },
  {
    name: 'HuggingFaceGetDatasetsScan',
    description: huggingFaceGetDatasetsScan.description!,
    tool: huggingFaceGetDatasetsScan,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'read' as const,
    keywords: [],
  },
  {
    name: 'HuggingFaceGetDatasetsTagsByType',
    description: huggingFaceGetDatasetsTagsByType.description!,
    tool: huggingFaceGetDatasetsTagsByType,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'read' as const,
    keywords: ['taxonomy', 'filter'],
  },
  {
    name: 'HuggingFaceGetDatasetStatistics',
    description: huggingFaceGetDatasetStatistics.description!,
    tool: huggingFaceGetDatasetStatistics,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'read' as const,
    keywords: ['stats'],
  },
  {
    name: 'HuggingFaceGetDatasetsTreesize',
    description: huggingFaceGetDatasetsTreesize.description!,
    tool: huggingFaceGetDatasetsTreesize,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'read' as const,
    keywords: [],
  },
  {
    name: 'HuggingFaceGetDatasetsXetReadToken',
    description: huggingFaceGetDatasetsXetReadToken.description!,
    tool: huggingFaceGetDatasetsXetReadToken,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'read' as const,
    keywords: ['token'],
  },
  {
    name: 'HuggingFaceGetDiscussion',
    description: huggingFaceGetDiscussion.description!,
    tool: huggingFaceGetDiscussion,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'read' as const,
    keywords: ['thread', 'pr', 'diff'],
  },
  {
    name: 'HuggingFaceGetJobsHardware',
    description: huggingFaceGetJobsHardware.description!,
    tool: huggingFaceGetJobsHardware,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'read' as const,
    keywords: ['gpu', 'compute'],
  },
  {
    name: 'HuggingFaceGetModelInfo',
    description: huggingFaceGetModelInfo.description!,
    tool: huggingFaceGetModelInfo,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'read' as const,
    keywords: ['metadata', 'downloads', 'weights'],
  },
  {
    name: 'HuggingFaceGetModelsCompare',
    description: huggingFaceGetModelsCompare.description!,
    tool: huggingFaceGetModelsCompare,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'read' as const,
    keywords: ['diff'],
  },
  {
    name: 'HuggingFaceGetModelsJwt',
    description: huggingFaceGetModelsJwt.description!,
    tool: huggingFaceGetModelsJwt,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'read' as const,
    keywords: ['token', 'auth'],
  },
  {
    name: 'HuggingFaceGetModelsNotebook',
    description: huggingFaceGetModelsNotebook.description!,
    tool: huggingFaceGetModelsNotebook,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'read' as const,
    keywords: ['colab', 'jupyter'],
  },
  {
    name: 'HuggingFaceGetModelsScan',
    description: huggingFaceGetModelsScan.description!,
    tool: huggingFaceGetModelsScan,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'read' as const,
    keywords: ['security', 'malware'],
  },
  {
    name: 'HuggingFaceGetModelsTreesize',
    description: huggingFaceGetModelsTreesize.description!,
    tool: huggingFaceGetModelsTreesize,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'read' as const,
    keywords: [],
  },
  {
    name: 'HuggingFaceGetModelsXetReadToken',
    description: huggingFaceGetModelsXetReadToken.description!,
    tool: huggingFaceGetModelsXetReadToken,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'read' as const,
    keywords: ['token', 'weights'],
  },
  {
    name: 'HuggingFaceGetModelTagsByType',
    description: huggingFaceGetModelTagsByType.description!,
    tool: huggingFaceGetModelTagsByType,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'read' as const,
    keywords: ['taxonomy', 'filter'],
  },
  {
    name: 'HuggingFaceGetOrganizationsAvatar',
    description: huggingFaceGetOrganizationsAvatar.description!,
    tool: huggingFaceGetOrganizationsAvatar,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'read' as const,
    keywords: ['logo', 'picture'],
  },
  {
    name: 'HuggingFaceGetOrganizationsMembers',
    description: huggingFaceGetOrganizationsMembers.description!,
    tool: huggingFaceGetOrganizationsMembers,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'read' as const,
    keywords: ['org', 'team'],
  },
  {
    name: 'HuggingFaceGetOrganizationsSocials',
    description: huggingFaceGetOrganizationsSocials.description!,
    tool: huggingFaceGetOrganizationsSocials,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'read' as const,
    keywords: ['github', 'twitter'],
  },
  {
    name: 'HuggingFaceGetResolve',
    description: huggingFaceGetResolve.description!,
    tool: huggingFaceGetResolve,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'read' as const,
    keywords: ['download'],
  },
  {
    name: 'HuggingFaceGetResolveCacheDatasets',
    description: huggingFaceGetResolveCacheDatasets.description!,
    tool: huggingFaceGetResolveCacheDatasets,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'read' as const,
    keywords: [],
  },
  {
    name: 'HuggingFaceGetResolveCacheModels',
    description: huggingFaceGetResolveCacheModels.description!,
    tool: huggingFaceGetResolveCacheModels,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'read' as const,
    keywords: [],
  },
  {
    name: 'HuggingFaceGetResolveCacheSpaces',
    description: huggingFaceGetResolveCacheSpaces.description!,
    tool: huggingFaceGetResolveCacheSpaces,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'read' as const,
    keywords: [],
  },
  {
    name: 'HuggingFaceGetSettingsBillingUsageJobs',
    description: huggingFaceGetSettingsBillingUsageJobs.description!,
    tool: huggingFaceGetSettingsBillingUsageJobs,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'read' as const,
    keywords: ['cost', 'credits'],
  },
  {
    name: 'HuggingFaceGetSettingsBillingUsageLive',
    description: huggingFaceGetSettingsBillingUsageLive.description!,
    tool: huggingFaceGetSettingsBillingUsageLive,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'read' as const,
    keywords: ['cost', 'credits', 'limits'],
  },
  {
    name: 'HuggingFaceGetSettingsBillingUsageV2',
    description: huggingFaceGetSettingsBillingUsageV2.description!,
    tool: huggingFaceGetSettingsBillingUsageV2,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'read' as const,
    keywords: ['cost', 'credits'],
  },
  {
    name: 'HuggingFaceGetSettingsMcp',
    description: huggingFaceGetSettingsMcp.description!,
    tool: huggingFaceGetSettingsMcp,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'read' as const,
    keywords: ['agent', 'claude'],
  },
  {
    name: 'HuggingFaceGetSettingsWebhooks',
    description: huggingFaceGetSettingsWebhooks.description!,
    tool: huggingFaceGetSettingsWebhooks,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'read' as const,
    keywords: ['notification'],
  },
  {
    name: 'HuggingFaceGetSpaceInfo',
    description: huggingFaceGetSpaceInfo.description!,
    tool: huggingFaceGetSpaceInfo,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'read' as const,
    keywords: ['status', 'hardware', 'app'],
  },
  {
    name: 'HuggingFaceGetSpacesCompare',
    description: huggingFaceGetSpacesCompare.description!,
    tool: huggingFaceGetSpacesCompare,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'read' as const,
    keywords: ['diff'],
  },
  {
    name: 'HuggingFaceGetSpacesEvents',
    description: huggingFaceGetSpacesEvents.description!,
    tool: huggingFaceGetSpacesEvents,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'read' as const,
    keywords: ['logs', 'status'],
  },
  {
    name: 'HuggingFaceGetSpacesJwt',
    description: huggingFaceGetSpacesJwt.description!,
    tool: huggingFaceGetSpacesJwt,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'read' as const,
    keywords: ['token', 'auth'],
  },
  {
    name: 'HuggingFaceGetSpacesMetrics',
    description: huggingFaceGetSpacesMetrics.description!,
    tool: huggingFaceGetSpacesMetrics,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'read' as const,
    keywords: ['logs', 'gpu'],
  },
  {
    name: 'HuggingFaceGetSpacesNotebook',
    description: huggingFaceGetSpacesNotebook.description!,
    tool: huggingFaceGetSpacesNotebook,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'read' as const,
    keywords: ['colab', 'jupyter'],
  },
  {
    name: 'HuggingFaceGetSpacesResolve',
    description: huggingFaceGetSpacesResolve.description!,
    tool: huggingFaceGetSpacesResolve,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'read' as const,
    keywords: [],
  },
  {
    name: 'HuggingFaceGetSpacesScan',
    description: huggingFaceGetSpacesScan.description!,
    tool: huggingFaceGetSpacesScan,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'read' as const,
    keywords: [],
  },
  {
    name: 'HuggingFaceGetSpacesTreesize',
    description: huggingFaceGetSpacesTreesize.description!,
    tool: huggingFaceGetSpacesTreesize,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'read' as const,
    keywords: [],
  },
  {
    name: 'HuggingFaceGetSpacesXetReadToken',
    description: huggingFaceGetSpacesXetReadToken.description!,
    tool: huggingFaceGetSpacesXetReadToken,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'read' as const,
    keywords: [],
  },
  {
    name: 'HuggingFaceGetSpacesXetWriteToken',
    description: huggingFaceGetSpacesXetWriteToken.description!,
    tool: huggingFaceGetSpacesXetWriteToken,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'read' as const,
    keywords: [],
  },
  {
    name: 'HuggingFaceGetTrending',
    description: huggingFaceGetTrending.description!,
    tool: huggingFaceGetTrending,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'read' as const,
    keywords: ['popular', 'discover'],
  },
  {
    name: 'HuggingFaceGetUsersAvatar',
    description: huggingFaceGetUsersAvatar.description!,
    tool: huggingFaceGetUsersAvatar,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'read' as const,
    keywords: ['logo', 'picture'],
  },
  {
    name: 'HuggingFaceGetUsersOverview',
    description: huggingFaceGetUsersOverview.description!,
    tool: huggingFaceGetUsersOverview,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'read' as const,
    keywords: [],
  },
  {
    name: 'HuggingFaceGetUsersSocials',
    description: huggingFaceGetUsersSocials.description!,
    tool: huggingFaceGetUsersSocials,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'read' as const,
    keywords: ['github', 'twitter'],
  },
  {
    name: 'HuggingFaceGetWhoami',
    description: huggingFaceGetWhoami.description!,
    tool: huggingFaceGetWhoami,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'read' as const,
    keywords: ['profile', 'username'],
  },
  {
    name: 'HuggingFaceHandleDatasetsUserAccessRequest',
    description: huggingFaceHandleDatasetsUserAccessRequest.description!,
    tool: huggingFaceHandleDatasetsUserAccessRequest,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'write' as const,
    keywords: ['approve', 'deny'],
  },
  {
    name: 'HuggingFaceListCollections',
    description: huggingFaceListCollections.description!,
    tool: huggingFaceListCollections,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'read' as const,
    keywords: ['curate', 'discover'],
  },
  {
    name: 'HuggingFaceListDatasetParquetFiles',
    description: huggingFaceListDatasetParquetFiles.description!,
    tool: huggingFaceListDatasetParquetFiles,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'read' as const,
    keywords: ['export', 'download'],
  },
  {
    name: 'HuggingFaceListDatasetPathsInfo',
    description: huggingFaceListDatasetPathsInfo.description!,
    tool: huggingFaceListDatasetPathsInfo,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'read' as const,
    keywords: [],
  },
  {
    name: 'HuggingFaceListDatasets',
    description: huggingFaceListDatasets.description!,
    tool: huggingFaceListDatasets,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'read' as const,
    keywords: ['discover', 'browse'],
  },
  {
    name: 'HuggingFaceListDatasetsCommits',
    description: huggingFaceListDatasetsCommits.description!,
    tool: huggingFaceListDatasetsCommits,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'read' as const,
    keywords: [],
  },
  {
    name: 'HuggingFaceListDatasetSplits',
    description: huggingFaceListDatasetSplits.description!,
    tool: huggingFaceListDatasetSplits,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'read' as const,
    keywords: [],
  },
  {
    name: 'HuggingFaceListDatasetsRefs',
    description: huggingFaceListDatasetsRefs.description!,
    tool: huggingFaceListDatasetsRefs,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'read' as const,
    keywords: [],
  },
  {
    name: 'HuggingFaceListDatasetsUserAccessRequest',
    description: huggingFaceListDatasetsUserAccessRequest.description!,
    tool: huggingFaceListDatasetsUserAccessRequest,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'read' as const,
    keywords: ['approve', 'gated'],
  },
  {
    name: 'HuggingFaceListDiscussions',
    description: huggingFaceListDiscussions.description!,
    tool: huggingFaceListDiscussions,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'read' as const,
    keywords: ['thread', 'prs'],
  },
  {
    name: 'HuggingFaceListDocs',
    description: huggingFaceListDocs.description!,
    tool: huggingFaceListDocs,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'read' as const,
    keywords: ['guide', 'help', 'manual'],
  },
  {
    name: 'HuggingFaceListEndpoints',
    description: huggingFaceListEndpoints.description!,
    tool: huggingFaceListEndpoints,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'read' as const,
    keywords: ['endpoint', 'deploy', 'serverless'],
  },
  {
    name: 'HuggingFaceListModelsCommits',
    description: huggingFaceListModelsCommits.description!,
    tool: huggingFaceListModelsCommits,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'read' as const,
    keywords: ['history'],
  },
  {
    name: 'HuggingFaceListModelsPathsInfo',
    description: huggingFaceListModelsPathsInfo.description!,
    tool: huggingFaceListModelsPathsInfo,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'read' as const,
    keywords: [],
  },
  {
    name: 'HuggingFaceListModelsRefs',
    description: huggingFaceListModelsRefs.description!,
    tool: huggingFaceListModelsRefs,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'read' as const,
    keywords: ['version'],
  },
  {
    name: 'HuggingFaceListNotifications',
    description: huggingFaceListNotifications.description!,
    tool: huggingFaceListNotifications,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'read' as const,
    keywords: ['notification', 'inbox', 'alert'],
  },
  {
    name: 'HuggingFaceListRepoFiles',
    description: huggingFaceListRepoFiles.description!,
    tool: huggingFaceListRepoFiles,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'read' as const,
    keywords: ['repository', 'repos', 'browse'],
  },
  {
    name: 'HuggingFaceListSettingsWebhooks',
    description: huggingFaceListSettingsWebhooks.description!,
    tool: huggingFaceListSettingsWebhooks,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'read' as const,
    keywords: ['notification'],
  },
  {
    name: 'HuggingFaceListSpaces',
    description: huggingFaceListSpaces.description!,
    tool: huggingFaceListSpaces,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'read' as const,
    keywords: ['app', 'apps', 'demo', 'gradio', 'streamlit'],
  },
  {
    name: 'HuggingFaceListSpacesCommits',
    description: huggingFaceListSpacesCommits.description!,
    tool: huggingFaceListSpacesCommits,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'read' as const,
    keywords: [],
  },
  {
    name: 'HuggingFaceListSpacesHardware',
    description: huggingFaceListSpacesHardware.description!,
    tool: huggingFaceListSpacesHardware,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'read' as const,
    keywords: ['gpu', 'cpu'],
  },
  {
    name: 'HuggingFaceListSpacesLfsFiles',
    description: huggingFaceListSpacesLfsFiles.description!,
    tool: huggingFaceListSpacesLfsFiles,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'read' as const,
    keywords: [],
  },
  {
    name: 'HuggingFaceListSpacesPathsInfo',
    description: huggingFaceListSpacesPathsInfo.description!,
    tool: huggingFaceListSpacesPathsInfo,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'read' as const,
    keywords: [],
  },
  {
    name: 'HuggingFaceListSpacesRefs',
    description: huggingFaceListSpacesRefs.description!,
    tool: huggingFaceListSpacesRefs,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'read' as const,
    keywords: ['version'],
  },
  {
    name: 'HuggingFaceListVendors',
    description: huggingFaceListVendors.description!,
    tool: huggingFaceListVendors,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'read' as const,
    keywords: ['gpu', 'hardware', 'deploy'],
  },
  {
    name: 'HuggingFaceSearchDataset',
    description: huggingFaceSearchDataset.description!,
    tool: huggingFaceSearchDataset,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'read' as const,
    keywords: ['find'],
  },
  {
    name: 'HuggingFaceSearchDocs',
    description: huggingFaceSearchDocs.description!,
    tool: huggingFaceSearchDocs,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'read' as const,
    keywords: ['guide', 'help'],
  },
  {
    name: 'HuggingFaceSearchPapers',
    description: huggingFaceSearchPapers.description!,
    tool: huggingFaceSearchPapers,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'read' as const,
    keywords: ['arxiv', 'semantic'],
  },
  {
    name: 'HuggingFaceSquashDatasetCommits',
    description: huggingFaceSquashDatasetCommits.description!,
    tool: huggingFaceSquashDatasetCommits,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'write' as const,
    keywords: ['rebase'],
  },
  {
    name: 'HuggingFaceSquashSpacesCommits',
    description: huggingFaceSquashSpacesCommits.description!,
    tool: huggingFaceSquashSpacesCommits,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'write' as const,
    keywords: ['rebase'],
  },
  {
    name: 'HuggingFaceUpdateDatasetsSettings',
    description: huggingFaceUpdateDatasetsSettings.description!,
    tool: huggingFaceUpdateDatasetsSettings,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'write' as const,
    keywords: [],
  },
  {
    name: 'HuggingFaceUpdateDiscussionsTitle',
    description: huggingFaceUpdateDiscussionsTitle.description!,
    tool: huggingFaceUpdateDiscussionsTitle,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'write' as const,
    keywords: ['thread', 'rename'],
  },
  {
    name: 'HuggingFaceUpdateModelsSettings',
    description: huggingFaceUpdateModelsSettings.description!,
    tool: huggingFaceUpdateModelsSettings,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'write' as const,
    keywords: [],
  },
  {
    name: 'HuggingFaceUpdateSettingsNotifications',
    description: huggingFaceUpdateSettingsNotifications.description!,
    tool: huggingFaceUpdateSettingsNotifications,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'write' as const,
    keywords: ['notification', 'alert'],
  },
  {
    name: 'HuggingFaceUpdateSettingsWatch',
    description: huggingFaceUpdateSettingsWatch.description!,
    tool: huggingFaceUpdateSettingsWatch,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'write' as const,
    keywords: ['subscribe', 'follow'],
  },
  {
    name: 'HuggingFaceUpdateSettingsWebhooks',
    description: huggingFaceUpdateSettingsWebhooks.description!,
    tool: huggingFaceUpdateSettingsWebhooks,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'write' as const,
    keywords: ['notification', 'callback'],
  },
  {
    name: 'HuggingFaceUpdateSpacesSettings',
    description: huggingFaceUpdateSpacesSettings.description!,
    tool: huggingFaceUpdateSpacesSettings,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'write' as const,
    keywords: [],
  },
  {
    name: 'HuggingFaceUpdateSqlConsoleEmbed',
    description: huggingFaceUpdateSqlConsoleEmbed.description!,
    tool: huggingFaceUpdateSqlConsoleEmbed,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'write' as const,
    keywords: [],
  },
  {
    name: 'HuggingFaceUpdateWebhookStatus',
    description: huggingFaceUpdateWebhookStatus.description!,
    tool: huggingFaceUpdateWebhookStatus,
    requiredAuth: 'huggingFaceToken' as const,
    scope: 'write' as const,
    keywords: ['notification', 'enable', 'disable'],
  },
];
