// @ts-nocheck
import { tool } from 'ai';
import { z } from 'zod';
import { argoCdRequest, failedResult, toArgoCdError } from './client.js';

const credentialsField = z
  .string()
  .describe(
    'Argo CD credentials JSON with baseUrl (argocd-server URL) plus token, or username+password for local login',
  );

export const argoCdListApplicationSets = tool({
  description: 'List ApplicationSets with generators and template status.',
  inputSchema: z.object({
    argoCdCredentials: credentialsField,
  }),
  execute: async ({ argoCdCredentials }) => {
    try {
      const result = await argoCdRequest(argoCdCredentials, '/applicationsets');
      if (!result.ok) return failedResult('Failed to list ApplicationSets', result);
      return result.data;
    } catch (error) {
      return toArgoCdError(error, 'Error listing ApplicationSets');
    }
  },
});

export const argoCdGetApplicationSet = tool({
  description: 'Get one ApplicationSet with generators and status.',
  inputSchema: z.object({
    argoCdCredentials: credentialsField,
    appsetName: z.string().describe('ApplicationSet name'),
  }),
  execute: async ({ argoCdCredentials, appsetName }) => {
    try {
      const result = await argoCdRequest(argoCdCredentials, `/applicationsets/${appsetName}`);
      if (!result.ok) return failedResult('Failed to get ApplicationSet', result);
      return result.data;
    } catch (error) {
      return toArgoCdError(error, 'Error getting ApplicationSet');
    }
  },
});

export const argoCdCreateApplicationSet = tool({
  description:
    'Create an ApplicationSet (generators: list/git/cluster/matrix/merge/pull-request; template with app spec).',
  inputSchema: z.object({
    argoCdCredentials: credentialsField,
    applicationset: z
      .record(z.string(), z.any())
      .describe(
        'ApplicationSet object: metadata {name}, spec {generators [], template {metadata, spec}}',
      ),
  }),
  execute: async ({ argoCdCredentials, applicationset }) => {
    try {
      const result = await argoCdRequest(argoCdCredentials, '/applicationsets', {
        method: 'POST',
        body: applicationset,
      });
      if (!result.ok) return failedResult('Failed to create ApplicationSet', result);
      return result.data;
    } catch (error) {
      return toArgoCdError(error, 'Error creating ApplicationSet');
    }
  },
});

export const argoCdDeleteApplicationSet = tool({
  description: 'Delete an ApplicationSet, optionally deleting generated apps too.',
  inputSchema: z.object({
    argoCdCredentials: credentialsField,
    appsetName: z.string().describe('ApplicationSet name'),
  }),
  execute: async ({ argoCdCredentials, appsetName }) => {
    try {
      const result = await argoCdRequest(argoCdCredentials, `/applicationsets/${appsetName}`, {
        method: 'DELETE',
      });
      if (!result.ok) return failedResult('Failed to delete ApplicationSet', result);
      return result.data;
    } catch (error) {
      return toArgoCdError(error, 'Error deleting ApplicationSet');
    }
  },
});

export const argoCdGenerateApplicationSet = tool({
  description: 'Dry-run generate apps from an ApplicationSet spec without persisting.',
  inputSchema: z.object({
    argoCdCredentials: credentialsField,
    applicationset: z
      .record(z.string(), z.any())
      .describe('ApplicationSet object to generate from'),
  }),
  execute: async ({ argoCdCredentials, applicationset }) => {
    try {
      const result = await argoCdRequest(argoCdCredentials, '/applicationsets/generate', {
        method: 'POST',
        body: applicationset,
      });
      if (!result.ok) return failedResult('Failed to generate ApplicationSet', result);
      return result.data;
    } catch (error) {
      return toArgoCdError(error, 'Error generating ApplicationSet');
    }
  },
});

export const argoCdGetApplicationSetEvents = tool({
  description: 'List Kubernetes events for an ApplicationSet. Use to debug generation.',
  inputSchema: z.object({
    argoCdCredentials: credentialsField,
    appsetName: z.string().describe('ApplicationSet name'),
  }),
  execute: async ({ argoCdCredentials, appsetName }) => {
    try {
      const result = await argoCdRequest(
        argoCdCredentials,
        `/applicationsets/${appsetName}/events`,
      );
      if (!result.ok) return failedResult('Failed to get ApplicationSet events', result);
      return result.data;
    } catch (error) {
      return toArgoCdError(error, 'Error getting ApplicationSet events');
    }
  },
});

export const argoCdGetApplicationSetResourceTree = tool({
  description: 'Get the resource tree of apps generated by an ApplicationSet.',
  inputSchema: z.object({
    argoCdCredentials: credentialsField,
    appsetName: z.string().describe('ApplicationSet name'),
  }),
  execute: async ({ argoCdCredentials, appsetName }) => {
    try {
      const result = await argoCdRequest(
        argoCdCredentials,
        `/applicationsets/${appsetName}/resource-tree`,
      );
      if (!result.ok) return failedResult('Failed to get ApplicationSet resource tree', result);
      return result.data;
    } catch (error) {
      return toArgoCdError(error, 'Error getting ApplicationSet resource tree');
    }
  },
});

export const argoCdListClusters = tool({
  description: 'List connected Kubernetes clusters (in-cluster plus external).',
  inputSchema: z.object({
    argoCdCredentials: credentialsField,
  }),
  execute: async ({ argoCdCredentials }) => {
    try {
      const result = await argoCdRequest(argoCdCredentials, '/clusters');
      if (!result.ok) return failedResult('Failed to list clusters', result);
      return result.data;
    } catch (error) {
      return toArgoCdError(error, 'Error listing clusters');
    }
  },
});

export const argoCdGetCluster = tool({
  description: 'Get one cluster by server URL with connection state and namespaces.',
  inputSchema: z.object({
    argoCdCredentials: credentialsField,
    server: z.string().describe('Cluster API server URL, e.g. https://kubernetes.default.svc'),
  }),
  execute: async ({ argoCdCredentials, server }) => {
    try {
      const result = await argoCdRequest(
        argoCdCredentials,
        `/clusters/${encodeURIComponent(server)}`,
      );
      if (!result.ok) return failedResult('Failed to get cluster', result);
      return result.data;
    } catch (error) {
      return toArgoCdError(error, 'Error getting cluster');
    }
  },
});

export const argoCdCreateCluster = tool({
  description:
    'Connect a cluster: server URL, name, bearer token or exec/TLS config, namespaces. Upsert to replace.',
  inputSchema: z.object({
    argoCdCredentials: credentialsField,
    cluster: z
      .record(z.string(), z.any())
      .describe(
        'Cluster: server, name, config {bearerToken | tlsClientConfig, awsAuthConfig, execProviderConfig}, namespaces, clusterResources',
      ),
    upsert: z.boolean().optional().describe('Replace an existing cluster entry'),
  }),
  execute: async ({ argoCdCredentials, cluster, upsert }) => {
    try {
      const result = await argoCdRequest(argoCdCredentials, '/clusters', {
        method: 'POST',
        query: { upsert: upsert === true ? true : undefined },
        body: cluster,
      });
      if (!result.ok) return failedResult('Failed to create cluster', result);
      return result.data;
    } catch (error) {
      return toArgoCdError(error, 'Error creating cluster');
    }
  },
});

export const argoCdUpdateCluster = tool({
  description: 'Update a connected cluster credentials or namespaces.',
  inputSchema: z.object({
    argoCdCredentials: credentialsField,
    server: z.string().describe('Cluster API server URL identifying the entry'),
    cluster: z.record(z.string(), z.any()).describe('Cluster fields to update'),
  }),
  execute: async ({ argoCdCredentials, server, cluster }) => {
    try {
      const result = await argoCdRequest(
        argoCdCredentials,
        `/clusters/${encodeURIComponent(server)}`,
        {
          method: 'PUT',
          body: cluster,
        },
      );
      if (!result.ok) return failedResult('Failed to update cluster', result);
      return result.data;
    } catch (error) {
      return toArgoCdError(error, 'Error updating cluster');
    }
  },
});

export const argoCdDeleteCluster = tool({
  description: 'Remove a cluster connection (apps targeting it become orphaned).',
  inputSchema: z.object({
    argoCdCredentials: credentialsField,
    server: z.string().describe('Cluster API server URL'),
  }),
  execute: async ({ argoCdCredentials, server }) => {
    try {
      const result = await argoCdRequest(
        argoCdCredentials,
        `/clusters/${encodeURIComponent(server)}`,
        {
          method: 'DELETE',
        },
      );
      if (!result.ok) return failedResult('Failed to delete cluster', result);
      return result.data;
    } catch (error) {
      return toArgoCdError(error, 'Error deleting cluster');
    }
  },
});

export const argoCdInvalidateClusterCache = tool({
  description: 'Invalidate cached cluster connection/data to force a fresh discovery.',
  inputSchema: z.object({
    argoCdCredentials: credentialsField,
    server: z.string().describe('Cluster API server URL'),
  }),
  execute: async ({ argoCdCredentials, server }) => {
    try {
      const result = await argoCdRequest(
        argoCdCredentials,
        `/clusters/${encodeURIComponent(server)}/invalidate-cache`,
        { method: 'POST' },
      );
      if (!result.ok) return failedResult('Failed to invalidate cluster cache', result);
      return result.data;
    } catch (error) {
      return toArgoCdError(error, 'Error invalidating cluster cache');
    }
  },
});

export const argoCdRotateClusterAuth = tool({
  description: 'Rotate cluster auth (e.g. refresh exec-provider tokens).',
  inputSchema: z.object({
    argoCdCredentials: credentialsField,
    server: z.string().describe('Cluster API server URL'),
  }),
  execute: async ({ argoCdCredentials, server }) => {
    try {
      const result = await argoCdRequest(
        argoCdCredentials,
        `/clusters/${encodeURIComponent(server)}/rotate-auth`,
        { method: 'POST' },
      );
      if (!result.ok) return failedResult('Failed to rotate cluster auth', result);
      return result.data;
    } catch (error) {
      return toArgoCdError(error, 'Error rotating cluster auth');
    }
  },
});

export const argoCdListRepositories = tool({
  description: 'List connected git/helm/OCI repositories with connection status.',
  inputSchema: z.object({
    argoCdCredentials: credentialsField,
  }),
  execute: async ({ argoCdCredentials }) => {
    try {
      const result = await argoCdRequest(argoCdCredentials, '/repositories');
      if (!result.ok) return failedResult('Failed to list repositories', result);
      return result.data;
    } catch (error) {
      return toArgoCdError(error, 'Error listing repositories');
    }
  },
});

export const argoCdGetRepository = tool({
  description: 'Get one repository connection with status.',
  inputSchema: z.object({
    argoCdCredentials: credentialsField,
    repoUrl: z.string().describe('Repository URL'),
  }),
  execute: async ({ argoCdCredentials, repoUrl }) => {
    try {
      const result = await argoCdRequest(
        argoCdCredentials,
        `/repositories/${encodeURIComponent(repoUrl)}`,
      );
      if (!result.ok) return failedResult('Failed to get repository', result);
      return result.data;
    } catch (error) {
      return toArgoCdError(error, 'Error getting repository');
    }
  },
});

export const argoCdCreateRepository = tool({
  description:
    'Connect a repository: URL, credentials (username/password, SSH key, GitHub App), type (git/helm/oci). Upsert to replace.',
  inputSchema: z.object({
    argoCdCredentials: credentialsField,
    repository: z
      .record(z.string(), z.any())
      .describe(
        'Repository: repo URL, type, name, username/password or sshPrivateKey, tlsClientConfig, githubApp*, enableOCI, proxy',
      ),
    upsert: z.boolean().optional().describe('Replace an existing entry'),
    credsOnly: z.boolean().optional().describe('Operate on credential set instead of repository'),
  }),
  execute: async ({ argoCdCredentials, repository, upsert, credsOnly }) => {
    try {
      const result = await argoCdRequest(argoCdCredentials, '/repositories', {
        method: 'POST',
        query: {
          upsert: upsert === true ? true : undefined,
          credsOnly: credsOnly === true ? true : undefined,
        },
        body: repository,
      });
      if (!result.ok) return failedResult('Failed to create repository', result);
      return result.data;
    } catch (error) {
      return toArgoCdError(error, 'Error creating repository');
    }
  },
});

export const argoCdUpdateRepository = tool({
  description: 'Update a repository connection (credentials, URL settings).',
  inputSchema: z.object({
    argoCdCredentials: credentialsField,
    repoUrl: z.string().describe('Repository URL identifying the entry'),
    repository: z.record(z.string(), z.any()).describe('Repository fields to update'),
  }),
  execute: async ({ argoCdCredentials, repoUrl, repository }) => {
    try {
      const result = await argoCdRequest(
        argoCdCredentials,
        `/repositories/${encodeURIComponent(repoUrl)}`,
        {
          method: 'PUT',
          body: repository,
        },
      );
      if (!result.ok) return failedResult('Failed to update repository', result);
      return result.data;
    } catch (error) {
      return toArgoCdError(error, 'Error updating repository');
    }
  },
});

export const argoCdDeleteRepository = tool({
  description: 'Remove a repository connection.',
  inputSchema: z.object({
    argoCdCredentials: credentialsField,
    repoUrl: z.string().describe('Repository URL'),
  }),
  execute: async ({ argoCdCredentials, repoUrl }) => {
    try {
      const result = await argoCdRequest(
        argoCdCredentials,
        `/repositories/${encodeURIComponent(repoUrl)}`,
        {
          method: 'DELETE',
        },
      );
      if (!result.ok) return failedResult('Failed to delete repository', result);
      return result.data;
    } catch (error) {
      return toArgoCdError(error, 'Error deleting repository');
    }
  },
});

export const argoCdValidateRepository = tool({
  description: 'Validate repository access and credentials without persisting.',
  inputSchema: z.object({
    argoCdCredentials: credentialsField,
    repoUrl: z.string().describe('Repository URL'),
  }),
  execute: async ({ argoCdCredentials, repoUrl }) => {
    try {
      const result = await argoCdRequest(
        argoCdCredentials,
        `/repositories/${encodeURIComponent(repoUrl)}/validate`,
        { method: 'POST' },
      );
      if (!result.ok) return failedResult('Failed to validate repository', result);
      return result.data;
    } catch (error) {
      return toArgoCdError(error, 'Error validating repository');
    }
  },
});

export const argoCdListRepoApps = tool({
  description: 'List installable apps (paths with app kind) detected in a repository revision.',
  inputSchema: z.object({
    argoCdCredentials: credentialsField,
    repoUrl: z.string().describe('Repository URL'),
    revision: z.string().optional().describe('Revision (default HEAD)'),
    appName: z.string().optional().describe('Filter by app name'),
  }),
  execute: async ({ argoCdCredentials, repoUrl, revision, appName }) => {
    try {
      const result = await argoCdRequest(
        argoCdCredentials,
        `/repositories/${encodeURIComponent(repoUrl)}/apps`,
        { query: { revision, appName } },
      );
      if (!result.ok) return failedResult('Failed to list repo apps', result);
      return result.data;
    } catch (error) {
      return toArgoCdError(error, 'Error listing repo apps');
    }
  },
});

export const argoCdListRepoHelmCharts = tool({
  description: 'List Helm charts available in a Helm repository.',
  inputSchema: z.object({
    argoCdCredentials: credentialsField,
    repoUrl: z.string().describe('Helm repository URL'),
  }),
  execute: async ({ argoCdCredentials, repoUrl }) => {
    try {
      const result = await argoCdRequest(
        argoCdCredentials,
        `/repositories/${encodeURIComponent(repoUrl)}/helmcharts`,
      );
      if (!result.ok) return failedResult('Failed to list Helm charts', result);
      return result.data;
    } catch (error) {
      return toArgoCdError(error, 'Error listing Helm charts');
    }
  },
});

export const argoCdListRepoRefs = tool({
  description: 'List branches and tags of a git repository.',
  inputSchema: z.object({
    argoCdCredentials: credentialsField,
    repoUrl: z.string().describe('Repository URL'),
  }),
  execute: async ({ argoCdCredentials, repoUrl }) => {
    try {
      const result = await argoCdRequest(
        argoCdCredentials,
        `/repositories/${encodeURIComponent(repoUrl)}/refs`,
      );
      if (!result.ok) return failedResult('Failed to list repo refs', result);
      return result.data;
    } catch (error) {
      return toArgoCdError(error, 'Error listing repo refs');
    }
  },
});

export const argoCdListRepoOciTags = tool({
  description: 'List OCI image tags in an OCI repository.',
  inputSchema: z.object({
    argoCdCredentials: credentialsField,
    repoUrl: z.string().describe('OCI repository URL'),
  }),
  execute: async ({ argoCdCredentials, repoUrl }) => {
    try {
      const result = await argoCdRequest(
        argoCdCredentials,
        `/repositories/${encodeURIComponent(repoUrl)}/oci-tags`,
      );
      if (!result.ok) return failedResult('Failed to list OCI tags', result);
      return result.data;
    } catch (error) {
      return toArgoCdError(error, 'Error listing OCI tags');
    }
  },
});

export const argoCdGetRepoAppDetails = tool({
  description: 'Resolve app details (kind, path, values files) for a repo path at a revision.',
  inputSchema: z.object({
    argoCdCredentials: credentialsField,
    repoUrl: z.string().describe('Repository URL'),
    appPath: z.string().optional().describe('App path in the repo'),
    revision: z.string().optional().describe('Revision (default HEAD)'),
  }),
  execute: async ({ argoCdCredentials, repoUrl, appPath, revision }) => {
    try {
      const result = await argoCdRequest(
        argoCdCredentials,
        `/repositories/${encodeURIComponent(repoUrl)}/appdetails`,
        {
          method: 'POST',
          body: {
            ...(appPath !== undefined ? { appPath } : {}),
            ...(revision !== undefined ? { revision } : {}),
          },
        },
      );
      if (!result.ok) return failedResult('Failed to get repo app details', result);
      return result.data;
    } catch (error) {
      return toArgoCdError(error, 'Error getting repo app details');
    }
  },
});

export const argoCdListRepoCreds = tool({
  description: 'List repository credential templates (URL patterns with shared creds).',
  inputSchema: z.object({
    argoCdCredentials: credentialsField,
  }),
  execute: async ({ argoCdCredentials }) => {
    try {
      const result = await argoCdRequest(argoCdCredentials, '/repocreds');
      if (!result.ok) return failedResult('Failed to list repo creds', result);
      return result.data;
    } catch (error) {
      return toArgoCdError(error, 'Error listing repo creds');
    }
  },
});

export const argoCdCreateRepoCreds = tool({
  description: 'Create a repository credential template for URL patterns.',
  inputSchema: z.object({
    argoCdCredentials: credentialsField,
    creds: z
      .record(z.string(), z.any())
      .describe('Creds: url pattern, username/password or sshPrivateKey, type, githubApp*'),
  }),
  execute: async ({ argoCdCredentials, creds }) => {
    try {
      const result = await argoCdRequest(argoCdCredentials, '/repocreds', {
        method: 'POST',
        body: creds,
      });
      if (!result.ok) return failedResult('Failed to create repo creds', result);
      return result.data;
    } catch (error) {
      return toArgoCdError(error, 'Error creating repo creds');
    }
  },
});

export const argoCdUpdateRepoCreds = tool({
  description: 'Update a repository credential template by URL pattern.',
  inputSchema: z.object({
    argoCdCredentials: credentialsField,
    url: z.string().describe('URL pattern identifying the entry'),
    creds: z.record(z.string(), z.any()).describe('Creds fields to update'),
  }),
  execute: async ({ argoCdCredentials, url, creds }) => {
    try {
      const result = await argoCdRequest(
        argoCdCredentials,
        `/repocreds/${encodeURIComponent(url)}`,
        {
          method: 'PUT',
          body: creds,
        },
      );
      if (!result.ok) return failedResult('Failed to update repo creds', result);
      return result.data;
    } catch (error) {
      return toArgoCdError(error, 'Error updating repo creds');
    }
  },
});

export const argoCdDeleteRepoCreds = tool({
  description: 'Delete a repository credential template.',
  inputSchema: z.object({
    argoCdCredentials: credentialsField,
    url: z.string().describe('URL pattern'),
  }),
  execute: async ({ argoCdCredentials, url }) => {
    try {
      const result = await argoCdRequest(
        argoCdCredentials,
        `/repocreds/${encodeURIComponent(url)}`,
        {
          method: 'DELETE',
        },
      );
      if (!result.ok) return failedResult('Failed to delete repo creds', result);
      return result.data;
    } catch (error) {
      return toArgoCdError(error, 'Error deleting repo creds');
    }
  },
});
