// @ts-nocheck
import {
  argoCdLogin,
  argoCdGetUserInfo,
  argoCdLogout,
  argoCdGetVersion,
  argoCdGetSettings,
  argoCdGetSettingsPlugins,
  argoCdListNotificationServices,
  argoCdListNotificationTemplates,
  argoCdListNotificationTriggers,
  argoCdListApplications,
  argoCdGetApplication,
  argoCdCreateApplication,
  argoCdUpdateApplication,
  argoCdPatchApplication,
  argoCdDeleteApplication,
  argoCdSyncApplication,
  argoCdTerminateSyncOperation,
  argoCdRollbackApplication,
  argoCdGetResourceTree,
  argoCdGetManagedResources,
  argoCdGetManifests,
  argoCdGetServerSideDiff,
  argoCdGetAppEvents,
  argoCdGetAppLinks,
  argoCdGetAppLogs,
  argoCdGetAppSyncWindows,
  argoCdGetResource,
  argoCdListResourceActions,
  argoCdRunResourceAction,
} from './applications.js';
import {
  argoCdListApplicationSets,
  argoCdGetApplicationSet,
  argoCdCreateApplicationSet,
  argoCdDeleteApplicationSet,
  argoCdGenerateApplicationSet,
  argoCdGetApplicationSetEvents,
  argoCdGetApplicationSetResourceTree,
  argoCdListClusters,
  argoCdGetCluster,
  argoCdCreateCluster,
  argoCdUpdateCluster,
  argoCdDeleteCluster,
  argoCdInvalidateClusterCache,
  argoCdRotateClusterAuth,
  argoCdListRepositories,
  argoCdGetRepository,
  argoCdCreateRepository,
  argoCdUpdateRepository,
  argoCdDeleteRepository,
  argoCdValidateRepository,
  argoCdListRepoApps,
  argoCdListRepoHelmCharts,
  argoCdListRepoRefs,
  argoCdListRepoOciTags,
  argoCdGetRepoAppDetails,
  argoCdListRepoCreds,
  argoCdCreateRepoCreds,
  argoCdUpdateRepoCreds,
  argoCdDeleteRepoCreds,
} from './gitops.js';
import {
  argoCdListProjects,
  argoCdGetProject,
  argoCdGetProjectDetailed,
  argoCdCreateProject,
  argoCdUpdateProject,
  argoCdDeleteProject,
  argoCdGetProjectEvents,
  argoCdGetProjectSyncWindows,
  argoCdGetProjectLinks,
  argoCdCreateProjectToken,
  argoCdDeleteProjectToken,
  argoCdListAccounts,
  argoCdGetAccount,
  argoCdCheckPermission,
  argoCdUpdatePassword,
  argoCdCreateAccountToken,
  argoCdDeleteAccountToken,
  argoCdListCertificates,
  argoCdCreateCertificates,
  argoCdDeleteCertificates,
  argoCdListGpgKeys,
  argoCdGetGpgKey,
  argoCdCreateGpgKeys,
  argoCdDeleteGpgKeys,
} from './projects.js';

export {
  argoCdLogin,
  argoCdGetUserInfo,
  argoCdLogout,
  argoCdGetVersion,
  argoCdGetSettings,
  argoCdGetSettingsPlugins,
  argoCdListNotificationServices,
  argoCdListNotificationTemplates,
  argoCdListNotificationTriggers,
  argoCdListApplications,
  argoCdGetApplication,
  argoCdCreateApplication,
  argoCdUpdateApplication,
  argoCdPatchApplication,
  argoCdDeleteApplication,
  argoCdSyncApplication,
  argoCdTerminateSyncOperation,
  argoCdRollbackApplication,
  argoCdGetResourceTree,
  argoCdGetManagedResources,
  argoCdGetManifests,
  argoCdGetServerSideDiff,
  argoCdGetAppEvents,
  argoCdGetAppLinks,
  argoCdGetAppLogs,
  argoCdGetAppSyncWindows,
  argoCdGetResource,
  argoCdListResourceActions,
  argoCdRunResourceAction,
  argoCdListApplicationSets,
  argoCdGetApplicationSet,
  argoCdCreateApplicationSet,
  argoCdDeleteApplicationSet,
  argoCdGenerateApplicationSet,
  argoCdGetApplicationSetEvents,
  argoCdGetApplicationSetResourceTree,
  argoCdListClusters,
  argoCdGetCluster,
  argoCdCreateCluster,
  argoCdUpdateCluster,
  argoCdDeleteCluster,
  argoCdInvalidateClusterCache,
  argoCdRotateClusterAuth,
  argoCdListRepositories,
  argoCdGetRepository,
  argoCdCreateRepository,
  argoCdUpdateRepository,
  argoCdDeleteRepository,
  argoCdValidateRepository,
  argoCdListRepoApps,
  argoCdListRepoHelmCharts,
  argoCdListRepoRefs,
  argoCdListRepoOciTags,
  argoCdGetRepoAppDetails,
  argoCdListRepoCreds,
  argoCdCreateRepoCreds,
  argoCdUpdateRepoCreds,
  argoCdDeleteRepoCreds,
  argoCdListProjects,
  argoCdGetProject,
  argoCdGetProjectDetailed,
  argoCdCreateProject,
  argoCdUpdateProject,
  argoCdDeleteProject,
  argoCdGetProjectEvents,
  argoCdGetProjectSyncWindows,
  argoCdGetProjectLinks,
  argoCdCreateProjectToken,
  argoCdDeleteProjectToken,
  argoCdListAccounts,
  argoCdGetAccount,
  argoCdCheckPermission,
  argoCdUpdatePassword,
  argoCdCreateAccountToken,
  argoCdDeleteAccountToken,
  argoCdListCertificates,
  argoCdCreateCertificates,
  argoCdDeleteCertificates,
  argoCdListGpgKeys,
  argoCdGetGpgKey,
  argoCdCreateGpgKeys,
  argoCdDeleteGpgKeys,
};

const AUTH = 'argoCdCredentials' as const;

export const argoCdTools = [
  {
    name: 'argoCdLogin',
    description: 'Log in with username/password and get a JWT.',
    tool: argoCdLogin,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['auth', 'authenticate', 'session'],
  },
  {
    name: 'argoCdGetUserInfo',
    description: 'Get logged-in account info; verifies the token.',
    tool: argoCdGetUserInfo,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['whoami', 'identity', 'health'],
  },
  {
    name: 'argoCdLogout',
    description: 'Delete the current session.',
    tool: argoCdLogout,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['signout', 'session'],
  },
  {
    name: 'argoCdGetVersion',
    description: 'Get server version and build info.',
    tool: argoCdGetVersion,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['build', 'release'],
  },
  {
    name: 'argoCdGetSettings',
    description: 'Get server settings.',
    tool: argoCdGetSettings,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['config'],
  },
  {
    name: 'argoCdGetSettingsPlugins',
    description: 'List config-management plugins.',
    tool: argoCdGetSettingsPlugins,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['cmp', 'config'],
  },
  {
    name: 'argoCdListNotificationServices',
    description: 'List notification services.',
    tool: argoCdListNotificationServices,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['alerts', 'slack'],
  },
  {
    name: 'argoCdListNotificationTemplates',
    description: 'List notification templates.',
    tool: argoCdListNotificationTemplates,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['alerts', 'templates'],
  },
  {
    name: 'argoCdListNotificationTriggers',
    description: 'List notification triggers.',
    tool: argoCdListNotificationTriggers,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['alerts', 'conditions'],
  },
  {
    name: 'argoCdListApplications',
    description: 'List applications with sync/health.',
    tool: argoCdListApplications,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['apps', 'deploys', 'gitops'],
  },
  {
    name: 'argoCdGetApplication',
    description: 'Get one application.',
    tool: argoCdGetApplication,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['app', 'fetch', 'status'],
  },
  {
    name: 'argoCdCreateApplication',
    description: 'Create an application from a spec.',
    tool: argoCdCreateApplication,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['app', 'deploy', 'onboard'],
  },
  {
    name: 'argoCdUpdateApplication',
    description: 'Update an application spec.',
    tool: argoCdUpdateApplication,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['app', 'edit'],
  },
  {
    name: 'argoCdPatchApplication',
    description: 'Patch an application.',
    tool: argoCdPatchApplication,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['app', 'merge'],
  },
  {
    name: 'argoCdDeleteApplication',
    description: 'Delete an application, optionally cascading.',
    tool: argoCdDeleteApplication,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['app', 'remove', 'prune'],
  },
  {
    name: 'argoCdSyncApplication',
    description: 'Sync an app to target state (deploy).',
    tool: argoCdSyncApplication,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['deploy', 'release', 'prune'],
  },
  {
    name: 'argoCdTerminateSyncOperation',
    description: 'Terminate an in-progress operation.',
    tool: argoCdTerminateSyncOperation,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['cancel', 'abort'],
  },
  {
    name: 'argoCdRollbackApplication',
    description: 'Roll back to a history ID.',
    tool: argoCdRollbackApplication,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['revert', 'downgrade'],
  },
  {
    name: 'argoCdGetResourceTree',
    description: 'Get live resource tree.',
    tool: argoCdGetResourceTree,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['topology', 'health'],
  },
  {
    name: 'argoCdGetManagedResources',
    description: 'List managed resources.',
    tool: argoCdGetManagedResources,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['inventory', 'k8s'],
  },
  {
    name: 'argoCdGetManifests',
    description: 'Get rendered manifests.',
    tool: argoCdGetManifests,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['yaml', 'render'],
  },
  {
    name: 'argoCdGetServerSideDiff',
    description: 'Dry-run server-side diff.',
    tool: argoCdGetServerSideDiff,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['drift', 'preview'],
  },
  {
    name: 'argoCdGetAppEvents',
    description: 'List app Kubernetes events.',
    tool: argoCdGetAppEvents,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['debug', 'warnings'],
  },
  {
    name: 'argoCdGetAppLinks',
    description: 'Get app deep links.',
    tool: argoCdGetAppLinks,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['dashboards', 'urls'],
  },
  {
    name: 'argoCdGetAppLogs',
    description: 'Get app pod logs.',
    tool: argoCdGetAppLogs,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['logs', 'debug', 'tail'],
  },
  {
    name: 'argoCdGetAppSyncWindows',
    description: 'List sync windows for an app.',
    tool: argoCdGetAppSyncWindows,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['schedule', 'freeze'],
  },
  {
    name: 'argoCdGetResource',
    description: 'Get live state of one resource.',
    tool: argoCdGetResource,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['k8s', 'fetch'],
  },
  {
    name: 'argoCdListResourceActions',
    description: 'List resource actions.',
    tool: argoCdListResourceActions,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['restart', 'operations'],
  },
  {
    name: 'argoCdRunResourceAction',
    description: 'Run a resource action (restart...).',
    tool: argoCdRunResourceAction,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['restart', 'rollout'],
  },
  {
    name: 'argoCdListApplicationSets',
    description: 'List ApplicationSets.',
    tool: argoCdListApplicationSets,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['generators', 'fleet'],
  },
  {
    name: 'argoCdGetApplicationSet',
    description: 'Get one ApplicationSet.',
    tool: argoCdGetApplicationSet,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['generator', 'fetch'],
  },
  {
    name: 'argoCdCreateApplicationSet',
    description: 'Create an ApplicationSet.',
    tool: argoCdCreateApplicationSet,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['fleet', 'matrix'],
  },
  {
    name: 'argoCdDeleteApplicationSet',
    description: 'Delete an ApplicationSet.',
    tool: argoCdDeleteApplicationSet,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['fleet', 'remove'],
  },
  {
    name: 'argoCdGenerateApplicationSet',
    description: 'Dry-run generate apps from a spec.',
    tool: argoCdGenerateApplicationSet,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['preview', 'render'],
  },
  {
    name: 'argoCdGetApplicationSetEvents',
    description: 'List ApplicationSet events.',
    tool: argoCdGetApplicationSetEvents,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['debug'],
  },
  {
    name: 'argoCdGetApplicationSetResourceTree',
    description: 'Get generated apps resource tree.',
    tool: argoCdGetApplicationSetResourceTree,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['topology'],
  },
  {
    name: 'argoCdListClusters',
    description: 'List connected clusters.',
    tool: argoCdListClusters,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['kubernetes', 'targets'],
  },
  {
    name: 'argoCdGetCluster',
    description: 'Get one cluster.',
    tool: argoCdGetCluster,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['kubernetes', 'fetch'],
  },
  {
    name: 'argoCdCreateCluster',
    description: 'Connect a cluster.',
    tool: argoCdCreateCluster,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['kubernetes', 'onboard'],
  },
  {
    name: 'argoCdUpdateCluster',
    description: 'Update a cluster connection.',
    tool: argoCdUpdateCluster,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['kubernetes', 'credentials'],
  },
  {
    name: 'argoCdDeleteCluster',
    description: 'Remove a cluster connection.',
    tool: argoCdDeleteCluster,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['kubernetes', 'remove'],
  },
  {
    name: 'argoCdInvalidateClusterCache',
    description: 'Invalidate cluster cache.',
    tool: argoCdInvalidateClusterCache,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['refresh', 'discovery'],
  },
  {
    name: 'argoCdRotateClusterAuth',
    description: 'Rotate cluster auth.',
    tool: argoCdRotateClusterAuth,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['credentials', 'refresh'],
  },
  {
    name: 'argoCdListRepositories',
    description: 'List connected repositories.',
    tool: argoCdListRepositories,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['git', 'helm', 'oci'],
  },
  {
    name: 'argoCdGetRepository',
    description: 'Get one repository.',
    tool: argoCdGetRepository,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['git', 'fetch'],
  },
  {
    name: 'argoCdCreateRepository',
    description: 'Connect a repository.',
    tool: argoCdCreateRepository,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['git', 'onboard'],
  },
  {
    name: 'argoCdUpdateRepository',
    description: 'Update a repository connection.',
    tool: argoCdUpdateRepository,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['git', 'credentials'],
  },
  {
    name: 'argoCdDeleteRepository',
    description: 'Remove a repository connection.',
    tool: argoCdDeleteRepository,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['git', 'remove'],
  },
  {
    name: 'argoCdValidateRepository',
    description: 'Validate repository access.',
    tool: argoCdValidateRepository,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['git', 'check'],
  },
  {
    name: 'argoCdListRepoApps',
    description: 'List installable apps in a repo.',
    tool: argoCdListRepoApps,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['paths', 'discover'],
  },
  {
    name: 'argoCdListRepoHelmCharts',
    description: 'List Helm charts in a repo.',
    tool: argoCdListRepoHelmCharts,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['charts'],
  },
  {
    name: 'argoCdListRepoRefs',
    description: 'List branches and tags.',
    tool: argoCdListRepoRefs,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['git', 'branches'],
  },
  {
    name: 'argoCdListRepoOciTags',
    description: 'List OCI image tags.',
    tool: argoCdListRepoOciTags,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['oci', 'versions'],
  },
  {
    name: 'argoCdGetRepoAppDetails',
    description: 'Resolve app details for a repo path.',
    tool: argoCdGetRepoAppDetails,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['kind', 'values'],
  },
  {
    name: 'argoCdListRepoCreds',
    description: 'List repo credential templates.',
    tool: argoCdListRepoCreds,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['credentials', 'patterns'],
  },
  {
    name: 'argoCdCreateRepoCreds',
    description: 'Create a repo credential template.',
    tool: argoCdCreateRepoCreds,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['credentials', 'shared'],
  },
  {
    name: 'argoCdUpdateRepoCreds',
    description: 'Update a repo credential template.',
    tool: argoCdUpdateRepoCreds,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['credentials', 'rotate'],
  },
  {
    name: 'argoCdDeleteRepoCreds',
    description: 'Delete a repo credential template.',
    tool: argoCdDeleteRepoCreds,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['credentials', 'remove'],
  },
  {
    name: 'argoCdListProjects',
    description: 'List AppProjects.',
    tool: argoCdListProjects,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['rbac', 'tenants'],
  },
  {
    name: 'argoCdGetProject',
    description: 'Get one AppProject.',
    tool: argoCdGetProject,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['rbac', 'fetch'],
  },
  {
    name: 'argoCdGetProjectDetailed',
    description: 'Get project with app counts.',
    tool: argoCdGetProjectDetailed,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['stats', 'status'],
  },
  {
    name: 'argoCdCreateProject',
    description: 'Create an AppProject.',
    tool: argoCdCreateProject,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['rbac', 'tenant'],
  },
  {
    name: 'argoCdUpdateProject',
    description: 'Update an AppProject.',
    tool: argoCdUpdateProject,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['rbac', 'edit'],
  },
  {
    name: 'argoCdDeleteProject',
    description: 'Delete an AppProject.',
    tool: argoCdDeleteProject,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['rbac', 'remove'],
  },
  {
    name: 'argoCdGetProjectEvents',
    description: 'List project events.',
    tool: argoCdGetProjectEvents,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['debug'],
  },
  {
    name: 'argoCdGetProjectSyncWindows',
    description: 'List project sync windows.',
    tool: argoCdGetProjectSyncWindows,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['schedule', 'freeze'],
  },
  {
    name: 'argoCdGetProjectLinks',
    description: 'Get project deep links.',
    tool: argoCdGetProjectLinks,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['urls'],
  },
  {
    name: 'argoCdCreateProjectToken',
    description: 'Create a project role token.',
    tool: argoCdCreateProjectToken,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['ci', 'automation', 'jwt'],
  },
  {
    name: 'argoCdDeleteProjectToken',
    description: 'Revoke a project role token.',
    tool: argoCdDeleteProjectToken,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['ci', 'revoke'],
  },
  {
    name: 'argoCdListAccounts',
    description: 'List local accounts.',
    tool: argoCdListAccounts,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['users', 'rbac'],
  },
  {
    name: 'argoCdGetAccount',
    description: 'Get one account.',
    tool: argoCdGetAccount,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['user', 'fetch'],
  },
  {
    name: 'argoCdCheckPermission',
    description: 'RBAC can-i permission check.',
    tool: argoCdCheckPermission,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['rbac', 'authorize', 'preflight'],
  },
  {
    name: 'argoCdUpdatePassword',
    description: 'Change account password.',
    tool: argoCdUpdatePassword,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['credentials', 'rotate'],
  },
  {
    name: 'argoCdCreateAccountToken',
    description: 'Create an account token.',
    tool: argoCdCreateAccountToken,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['ci', 'jwt', 'automation'],
  },
  {
    name: 'argoCdDeleteAccountToken',
    description: 'Revoke an account token.',
    tool: argoCdDeleteAccountToken,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['revoke'],
  },
  {
    name: 'argoCdListCertificates',
    description: 'List repo TLS certificates.',
    tool: argoCdListCertificates,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['tls', 'expiry'],
  },
  {
    name: 'argoCdCreateCertificates',
    description: 'Add repo TLS certificates.',
    tool: argoCdCreateCertificates,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['tls', 'pem'],
  },
  {
    name: 'argoCdDeleteCertificates',
    description: 'Delete repo TLS certificates.',
    tool: argoCdDeleteCertificates,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['tls', 'remove'],
  },
  {
    name: 'argoCdListGpgKeys',
    description: 'List GPG public keys.',
    tool: argoCdListGpgKeys,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['signing', 'verify'],
  },
  {
    name: 'argoCdGetGpgKey',
    description: 'Get one GPG key.',
    tool: argoCdGetGpgKey,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['signing', 'fetch'],
  },
  {
    name: 'argoCdCreateGpgKeys',
    description: 'Add GPG public keys.',
    tool: argoCdCreateGpgKeys,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['signing', 'import'],
  },
  {
    name: 'argoCdDeleteGpgKeys',
    description: 'Delete GPG public keys.',
    tool: argoCdDeleteGpgKeys,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['signing', 'remove'],
  },
];
