// @ts-nocheck
import {
  neonAcceptProjectsTransferRequests,
  neonAccessProjectDetailsById,
  neonAddNewJwksToProjectEndpoint,
  neonAddProjectEmailPermission,
  neonCreateProjectsTransferRequests,
  neonCreateProjectWithQuotaAndSettings,
  neonCreateVpcEndpointLabel,
  neonDeleteProjectById,
  neonDeleteProjectJwksById,
  neonDeleteProjectPermission,
  neonDeleteVpcEndpointByProjectId,
  neonGetAvailablePreloadLibraries,
  neonGetConsumptionHistoryProjects,
  neonGetProjectConnectionUri,
  neonGetProjectEndpointInformation,
  neonGetProjectOperationById,
  neonListSharedProjects,
  neonRetrieveJwksForProject,
  neonRetrieveProjectOperations,
  neonRetrieveProjectPermissions,
  neonRetrieveProjectsList,
  neonRetrieveVpcEndpointsForProject,
  neonUpdateProjectSettingsById,
} from './projects.js';
export {
  neonAcceptProjectsTransferRequests,
  neonAccessProjectDetailsById,
  neonAddNewJwksToProjectEndpoint,
  neonAddProjectEmailPermission,
  neonCreateProjectsTransferRequests,
  neonCreateProjectWithQuotaAndSettings,
  neonCreateVpcEndpointLabel,
  neonDeleteProjectById,
  neonDeleteProjectJwksById,
  neonDeleteProjectPermission,
  neonDeleteVpcEndpointByProjectId,
  neonGetAvailablePreloadLibraries,
  neonGetConsumptionHistoryProjects,
  neonGetProjectConnectionUri,
  neonGetProjectEndpointInformation,
  neonGetProjectOperationById,
  neonListSharedProjects,
  neonRetrieveJwksForProject,
  neonRetrieveProjectOperations,
  neonRetrieveProjectPermissions,
  neonRetrieveProjectsList,
  neonRetrieveVpcEndpointsForProject,
  neonUpdateProjectSettingsById,
};
import {
  neonAddRoleToBranch,
  neonCountProjectBranches,
  neonCreateBranchDatabase,
  neonCreateBranchesSnapshot,
  neonCreateNewProjectBranch,
  neonCreateProjectBranchAnonymized,
  neonDeleteDatabaseFromBranch,
  neonDeleteProjectBranchById,
  neonDeleteProjectBranchRole,
  neonFetchDatabaseForBranch,
  neonFinalizeBranchRestore,
  neonGetBranchesAnonymizedStatus,
  neonGetBranchesBackupSchedule,
  neonGetBranchesForProject,
  neonGetBranchesMaskingRules,
  neonGetBranchRolesForProject,
  neonGetProjectBranches,
  neonGetProjectBranchRole,
  neonGetProjectBranchSchemaComparison,
  neonGetSchemaForProjectBranch,
  neonModifyBranchDetailsInProject,
  neonPatchBranchDatabaseInformation,
  neonResetRolePasswordForBranch,
  neonRestoreProjectBranch,
  neonRetrieveBranchDatabaseDetails,
  neonRetrieveBranchEndpoints,
  neonRevealRolePasswordInBranch,
  neonSetBranchAsDefault,
  neonStartBranchAnonymization,
  neonUpdateBranchesMaskingRules,
} from './branches.js';
export {
  neonAddRoleToBranch,
  neonCountProjectBranches,
  neonCreateBranchDatabase,
  neonCreateBranchesSnapshot,
  neonCreateNewProjectBranch,
  neonCreateProjectBranchAnonymized,
  neonDeleteDatabaseFromBranch,
  neonDeleteProjectBranchById,
  neonDeleteProjectBranchRole,
  neonFetchDatabaseForBranch,
  neonFinalizeBranchRestore,
  neonGetBranchesAnonymizedStatus,
  neonGetBranchesBackupSchedule,
  neonGetBranchesForProject,
  neonGetBranchesMaskingRules,
  neonGetBranchRolesForProject,
  neonGetProjectBranches,
  neonGetProjectBranchRole,
  neonGetProjectBranchSchemaComparison,
  neonGetSchemaForProjectBranch,
  neonModifyBranchDetailsInProject,
  neonPatchBranchDatabaseInformation,
  neonResetRolePasswordForBranch,
  neonRestoreProjectBranch,
  neonRetrieveBranchDatabaseDetails,
  neonRetrieveBranchEndpoints,
  neonRevealRolePasswordInBranch,
  neonSetBranchAsDefault,
  neonStartBranchAnonymization,
  neonUpdateBranchesMaskingRules,
};
import {
  neonCreateApiKeyForOrganization,
  neonCreateNewApiKey,
  neonCreateVpcEndpointWithLabel,
  neonDeleteApiKeyById,
  neonDeleteOrganizationApiKey,
  neonDeleteOrganizationMember,
  neonDeleteVpcEndpointByIds,
  neonFetchOrganizationMembersById,
  neonFetchVpcendpointDetailsById,
  neonGetCurrentUserInformation,
  neonGetOrganizationApiKeys,
  neonGetUserOrganizations,
  neonGetVpcRegionEndpoints,
  neonListApiKeys,
  neonListVpcVpcEndpoints,
  neonRetrieveAccountConsumptionHistory,
  neonRetrieveOrganizationById,
  neonRetrieveOrganizationInvitations,
  neonRetrieveOrganizationMemberInfo,
  neonSendOrganizationInvitations,
  neonTransferProjectsBetweenOrganizations,
  neonTransferUserProjectsToOrganization,
  neonUpdateOrganizationMemberRole,
} from './orgs.js';
export {
  neonCreateApiKeyForOrganization,
  neonCreateNewApiKey,
  neonCreateVpcEndpointWithLabel,
  neonDeleteApiKeyById,
  neonDeleteOrganizationApiKey,
  neonDeleteOrganizationMember,
  neonDeleteVpcEndpointByIds,
  neonFetchOrganizationMembersById,
  neonFetchVpcendpointDetailsById,
  neonGetCurrentUserInformation,
  neonGetOrganizationApiKeys,
  neonGetUserOrganizations,
  neonGetVpcRegionEndpoints,
  neonListApiKeys,
  neonListVpcVpcEndpoints,
  neonRetrieveAccountConsumptionHistory,
  neonRetrieveOrganizationById,
  neonRetrieveOrganizationInvitations,
  neonRetrieveOrganizationMemberInfo,
  neonSendOrganizationInvitations,
  neonTransferProjectsBetweenOrganizations,
  neonTransferUserProjectsToOrganization,
  neonUpdateOrganizationMemberRole,
};
import {
  neonCreateAuthKeys,
  neonCreateAuthUser,
  neonCreateBranchesAuth,
  neonDeleteAuthDomainFromProject,
  neonDeleteAuthDomains,
  neonDeleteAuthOauthProvider,
  neonDeleteAuthUser,
  neonDisableBranchesAuth,
  neonGetAuth,
  neonGetAuthAllowLocalhost,
  neonGetAuthEmailProvider,
  neonListAuthDomains,
  neonListAuthOauthProviders,
  neonListAuthOauthProviders2,
  neonSendAuthTestEmail,
  neonUpdateAuthAllowLocalhost,
  neonUpdateAuthEmailProvider,
  neonUpdateAuthOauthProviders,
} from './auth.js';
export {
  neonCreateAuthKeys,
  neonCreateAuthUser,
  neonCreateBranchesAuth,
  neonDeleteAuthDomainFromProject,
  neonDeleteAuthDomains,
  neonDeleteAuthOauthProvider,
  neonDeleteAuthUser,
  neonDisableBranchesAuth,
  neonGetAuth,
  neonGetAuthAllowLocalhost,
  neonGetAuthEmailProvider,
  neonListAuthDomains,
  neonListAuthOauthProviders,
  neonListAuthOauthProviders2,
  neonSendAuthTestEmail,
  neonUpdateAuthAllowLocalhost,
  neonUpdateAuthEmailProvider,
  neonUpdateAuthOauthProviders,
};
import {
  neonCreateBranchesDataApi,
  neonDeleteBranchDataApi,
  neonGetBranchesDataApi,
  neonUpdateBranchesDataApi,
} from './dataapi.js';
export {
  neonCreateBranchesDataApi,
  neonDeleteBranchDataApi,
  neonGetBranchesDataApi,
  neonUpdateBranchesDataApi,
};
import {
  neonCreateComputeEndpoint,
  neonDeleteProjectEndpoint,
  neonRestartProjectEndpoint,
  neonRetrieveProjectEndpointDetails,
  neonStartEndpointForProject,
  neonSuspendProjectEndpointById,
  neonUpdateProjectComputeEndpointSettings,
} from './endpoints.js';
export {
  neonCreateComputeEndpoint,
  neonDeleteProjectEndpoint,
  neonRestartProjectEndpoint,
  neonRetrieveProjectEndpointDetails,
  neonStartEndpointForProject,
  neonSuspendProjectEndpointById,
  neonUpdateProjectComputeEndpointSettings,
};
import {
  neonDeleteProjectSnapshot,
  neonListProjectsSnapshots,
  neonRestoreSnapshot,
  neonUpdateProjectsSnapshots,
} from './snapshots.js';
export {
  neonDeleteProjectSnapshot,
  neonListProjectsSnapshots,
  neonRestoreSnapshot,
  neonUpdateProjectsSnapshots,
};
import { neonRetrieveAllRegions } from './meta.js';
export { neonRetrieveAllRegions };

export const neonTools = [
  {
    name: 'NeonAcceptProjectsTransferRequests',
    description: neonAcceptProjectsTransferRequests.description!,
    tool: neonAcceptProjectsTransferRequests,
    requiredAuth: 'neonApiKey' as const,
    scope: 'write' as const,
    keywords: ['move', 'ownership'],
  },
  {
    name: 'NeonAccessProjectDetailsById',
    description: neonAccessProjectDetailsById.description!,
    tool: neonAccessProjectDetailsById,
    requiredAuth: 'neonApiKey' as const,
    scope: 'write' as const,
    keywords: ['postgres', 'database', 'settings'],
  },
  {
    name: 'NeonAddNewJwksToProjectEndpoint',
    description: neonAddNewJwksToProjectEndpoint.description!,
    tool: neonAddNewJwksToProjectEndpoint,
    requiredAuth: 'neonApiKey' as const,
    scope: 'write' as const,
    keywords: [],
  },
  {
    name: 'NeonAddProjectEmailPermission',
    description: neonAddProjectEmailPermission.description!,
    tool: neonAddProjectEmailPermission,
    requiredAuth: 'neonApiKey' as const,
    scope: 'write' as const,
    keywords: [],
  },
  {
    name: 'NeonAddRoleToBranch',
    description: neonAddRoleToBranch.description!,
    tool: neonAddRoleToBranch,
    requiredAuth: 'neonApiKey' as const,
    scope: 'write' as const,
    keywords: ['user', 'login', 'credentials'],
  },
  {
    name: 'NeonCountProjectBranches',
    description: neonCountProjectBranches.description!,
    tool: neonCountProjectBranches,
    requiredAuth: 'neonApiKey' as const,
    scope: 'read' as const,
    keywords: ['postgres'],
  },
  {
    name: 'NeonCreateApiKeyForOrganization',
    description: neonCreateApiKeyForOrganization.description!,
    tool: neonCreateApiKeyForOrganization,
    requiredAuth: 'neonApiKey' as const,
    scope: 'write' as const,
    keywords: ['token', 'secret', 'credentials'],
  },
  {
    name: 'NeonCreateAuthKeys',
    description: neonCreateAuthKeys.description!,
    tool: neonCreateAuthKeys,
    requiredAuth: 'neonApiKey' as const,
    scope: 'write' as const,
    keywords: [],
  },
  {
    name: 'NeonCreateAuthUser',
    description: neonCreateAuthUser.description!,
    tool: neonCreateAuthUser,
    requiredAuth: 'neonApiKey' as const,
    scope: 'write' as const,
    keywords: ['signup', 'login'],
  },
  {
    name: 'NeonCreateBranchDatabase',
    description: neonCreateBranchDatabase.description!,
    tool: neonCreateBranchDatabase,
    requiredAuth: 'neonApiKey' as const,
    scope: 'write' as const,
    keywords: ['schema', 'postgres'],
  },
  {
    name: 'NeonCreateBranchesAuth',
    description: neonCreateBranchesAuth.description!,
    tool: neonCreateBranchesAuth,
    requiredAuth: 'neonApiKey' as const,
    scope: 'write' as const,
    keywords: ['login', 'sso', 'oauth'],
  },
  {
    name: 'NeonCreateBranchesDataApi',
    description: neonCreateBranchesDataApi.description!,
    tool: neonCreateBranchesDataApi,
    requiredAuth: 'neonApiKey' as const,
    scope: 'write' as const,
    keywords: ['rest', 'http'],
  },
  {
    name: 'NeonCreateBranchesSnapshot',
    description: neonCreateBranchesSnapshot.description!,
    tool: neonCreateBranchesSnapshot,
    requiredAuth: 'neonApiKey' as const,
    scope: 'write' as const,
    keywords: ['backup', 'checkpoint'],
  },
  {
    name: 'NeonCreateComputeEndpoint',
    description: neonCreateComputeEndpoint.description!,
    tool: neonCreateComputeEndpoint,
    requiredAuth: 'neonApiKey' as const,
    scope: 'write' as const,
    keywords: ['instance', 'host', 'postgres'],
  },
  {
    name: 'NeonCreateNewApiKey',
    description: neonCreateNewApiKey.description!,
    tool: neonCreateNewApiKey,
    requiredAuth: 'neonApiKey' as const,
    scope: 'write' as const,
    keywords: ['token', 'secret', 'ci'],
  },
  {
    name: 'NeonCreateNewProjectBranch',
    description: neonCreateNewProjectBranch.description!,
    tool: neonCreateNewProjectBranch,
    requiredAuth: 'neonApiKey' as const,
    scope: 'write' as const,
    keywords: ['clone', 'copy', 'dev', 'staging'],
  },
  {
    name: 'NeonCreateProjectBranchAnonymized',
    description: neonCreateProjectBranchAnonymized.description!,
    tool: neonCreateProjectBranchAnonymized,
    requiredAuth: 'neonApiKey' as const,
    scope: 'write' as const,
    keywords: ['mask', 'pii', 'gdpr'],
  },
  {
    name: 'NeonCreateProjectsTransferRequests',
    description: neonCreateProjectsTransferRequests.description!,
    tool: neonCreateProjectsTransferRequests,
    requiredAuth: 'neonApiKey' as const,
    scope: 'write' as const,
    keywords: ['move', 'ownership'],
  },
  {
    name: 'NeonCreateProjectWithQuotaAndSettings',
    description: neonCreateProjectWithQuotaAndSettings.description!,
    tool: neonCreateProjectWithQuotaAndSettings,
    requiredAuth: 'neonApiKey' as const,
    scope: 'write' as const,
    keywords: ['postgres', 'database', 'new'],
  },
  {
    name: 'NeonCreateVpcEndpointLabel',
    description: neonCreateVpcEndpointLabel.description!,
    tool: neonCreateVpcEndpointLabel,
    requiredAuth: 'neonApiKey' as const,
    scope: 'write' as const,
    keywords: [],
  },
  {
    name: 'NeonCreateVpcEndpointWithLabel',
    description: neonCreateVpcEndpointWithLabel.description!,
    tool: neonCreateVpcEndpointWithLabel,
    requiredAuth: 'neonApiKey' as const,
    scope: 'write' as const,
    keywords: [],
  },
  {
    name: 'NeonDeleteApiKeyById',
    description: neonDeleteApiKeyById.description!,
    tool: neonDeleteApiKeyById,
    requiredAuth: 'neonApiKey' as const,
    scope: 'delete' as const,
    keywords: ['token', 'revoke'],
  },
  {
    name: 'NeonDeleteAuthDomainFromProject',
    description: neonDeleteAuthDomainFromProject.description!,
    tool: neonDeleteAuthDomainFromProject,
    requiredAuth: 'neonApiKey' as const,
    scope: 'delete' as const,
    keywords: [],
  },
  {
    name: 'NeonDeleteAuthDomains',
    description: neonDeleteAuthDomains.description!,
    tool: neonDeleteAuthDomains,
    requiredAuth: 'neonApiKey' as const,
    scope: 'delete' as const,
    keywords: [],
  },
  {
    name: 'NeonDeleteAuthOauthProvider',
    description: neonDeleteAuthOauthProvider.description!,
    tool: neonDeleteAuthOauthProvider,
    requiredAuth: 'neonApiKey' as const,
    scope: 'delete' as const,
    keywords: [],
  },
  {
    name: 'NeonDeleteAuthUser',
    description: neonDeleteAuthUser.description!,
    tool: neonDeleteAuthUser,
    requiredAuth: 'neonApiKey' as const,
    scope: 'delete' as const,
    keywords: [],
  },
  {
    name: 'NeonDeleteBranchDataApi',
    description: neonDeleteBranchDataApi.description!,
    tool: neonDeleteBranchDataApi,
    requiredAuth: 'neonApiKey' as const,
    scope: 'delete' as const,
    keywords: ['rest'],
  },
  {
    name: 'NeonDeleteDatabaseFromBranch',
    description: neonDeleteDatabaseFromBranch.description!,
    tool: neonDeleteDatabaseFromBranch,
    requiredAuth: 'neonApiKey' as const,
    scope: 'delete' as const,
    keywords: ['postgres', 'remove'],
  },
  {
    name: 'NeonDeleteOrganizationApiKey',
    description: neonDeleteOrganizationApiKey.description!,
    tool: neonDeleteOrganizationApiKey,
    requiredAuth: 'neonApiKey' as const,
    scope: 'delete' as const,
    keywords: ['token', 'revoke', 'rotate'],
  },
  {
    name: 'NeonDeleteOrganizationMember',
    description: neonDeleteOrganizationMember.description!,
    tool: neonDeleteOrganizationMember,
    requiredAuth: 'neonApiKey' as const,
    scope: 'delete' as const,
    keywords: ['remove', 'team'],
  },
  {
    name: 'NeonDeleteProjectBranchById',
    description: neonDeleteProjectBranchById.description!,
    tool: neonDeleteProjectBranchById,
    requiredAuth: 'neonApiKey' as const,
    scope: 'delete' as const,
    keywords: ['remove'],
  },
  {
    name: 'NeonDeleteProjectBranchRole',
    description: neonDeleteProjectBranchRole.description!,
    tool: neonDeleteProjectBranchRole,
    requiredAuth: 'neonApiKey' as const,
    scope: 'delete' as const,
    keywords: ['user', 'revoke'],
  },
  {
    name: 'NeonDeleteProjectById',
    description: neonDeleteProjectById.description!,
    tool: neonDeleteProjectById,
    requiredAuth: 'neonApiKey' as const,
    scope: 'delete' as const,
    keywords: ['postgres', 'database', 'remove'],
  },
  {
    name: 'NeonDeleteProjectEndpoint',
    description: neonDeleteProjectEndpoint.description!,
    tool: neonDeleteProjectEndpoint,
    requiredAuth: 'neonApiKey' as const,
    scope: 'delete' as const,
    keywords: ['instance', 'remove'],
  },
  {
    name: 'NeonDeleteProjectJwksById',
    description: neonDeleteProjectJwksById.description!,
    tool: neonDeleteProjectJwksById,
    requiredAuth: 'neonApiKey' as const,
    scope: 'delete' as const,
    keywords: [],
  },
  {
    name: 'NeonDeleteProjectPermission',
    description: neonDeleteProjectPermission.description!,
    tool: neonDeleteProjectPermission,
    requiredAuth: 'neonApiKey' as const,
    scope: 'delete' as const,
    keywords: [],
  },
  {
    name: 'NeonDeleteProjectSnapshot',
    description: neonDeleteProjectSnapshot.description!,
    tool: neonDeleteProjectSnapshot,
    requiredAuth: 'neonApiKey' as const,
    scope: 'delete' as const,
    keywords: ['backup', 'remove'],
  },
  {
    name: 'NeonDeleteVpcEndpointByIds',
    description: neonDeleteVpcEndpointByIds.description!,
    tool: neonDeleteVpcEndpointByIds,
    requiredAuth: 'neonApiKey' as const,
    scope: 'delete' as const,
    keywords: [],
  },
  {
    name: 'NeonDeleteVpcEndpointByProjectId',
    description: neonDeleteVpcEndpointByProjectId.description!,
    tool: neonDeleteVpcEndpointByProjectId,
    requiredAuth: 'neonApiKey' as const,
    scope: 'delete' as const,
    keywords: [],
  },
  {
    name: 'NeonDisableBranchesAuth',
    description: neonDisableBranchesAuth.description!,
    tool: neonDisableBranchesAuth,
    requiredAuth: 'neonApiKey' as const,
    scope: 'delete' as const,
    keywords: [],
  },
  {
    name: 'NeonFetchDatabaseForBranch',
    description: neonFetchDatabaseForBranch.description!,
    tool: neonFetchDatabaseForBranch,
    requiredAuth: 'neonApiKey' as const,
    scope: 'read' as const,
    keywords: ['postgres', 'inventory'],
  },
  {
    name: 'NeonFetchOrganizationMembersById',
    description: neonFetchOrganizationMembersById.description!,
    tool: neonFetchOrganizationMembersById,
    requiredAuth: 'neonApiKey' as const,
    scope: 'read' as const,
    keywords: ['team'],
  },
  {
    name: 'NeonFetchVpcendpointDetailsById',
    description: neonFetchVpcendpointDetailsById.description!,
    tool: neonFetchVpcendpointDetailsById,
    requiredAuth: 'neonApiKey' as const,
    scope: 'read' as const,
    keywords: [],
  },
  {
    name: 'NeonFinalizeBranchRestore',
    description: neonFinalizeBranchRestore.description!,
    tool: neonFinalizeBranchRestore,
    requiredAuth: 'neonApiKey' as const,
    scope: 'write' as const,
    keywords: [],
  },
  {
    name: 'NeonGetAuth',
    description: neonGetAuth.description!,
    tool: neonGetAuth,
    requiredAuth: 'neonApiKey' as const,
    scope: 'read' as const,
    keywords: [],
  },
  {
    name: 'NeonGetAuthAllowLocalhost',
    description: neonGetAuthAllowLocalhost.description!,
    tool: neonGetAuthAllowLocalhost,
    requiredAuth: 'neonApiKey' as const,
    scope: 'read' as const,
    keywords: ['login'],
  },
  {
    name: 'NeonGetAuthEmailProvider',
    description: neonGetAuthEmailProvider.description!,
    tool: neonGetAuthEmailProvider,
    requiredAuth: 'neonApiKey' as const,
    scope: 'read' as const,
    keywords: ['smtp'],
  },
  {
    name: 'NeonGetAvailablePreloadLibraries',
    description: neonGetAvailablePreloadLibraries.description!,
    tool: neonGetAvailablePreloadLibraries,
    requiredAuth: 'neonApiKey' as const,
    scope: 'read' as const,
    keywords: ['extension', 'postgis', 'pgvector'],
  },
  {
    name: 'NeonGetBranchesAnonymizedStatus',
    description: neonGetBranchesAnonymizedStatus.description!,
    tool: neonGetBranchesAnonymizedStatus,
    requiredAuth: 'neonApiKey' as const,
    scope: 'read' as const,
    keywords: ['mask', 'pii'],
  },
  {
    name: 'NeonGetBranchesBackupSchedule',
    description: neonGetBranchesBackupSchedule.description!,
    tool: neonGetBranchesBackupSchedule,
    requiredAuth: 'neonApiKey' as const,
    scope: 'read' as const,
    keywords: ['retention', 'pitr'],
  },
  {
    name: 'NeonGetBranchesDataApi',
    description: neonGetBranchesDataApi.description!,
    tool: neonGetBranchesDataApi,
    requiredAuth: 'neonApiKey' as const,
    scope: 'read' as const,
    keywords: ['rest', 'url'],
  },
  {
    name: 'NeonGetBranchesForProject',
    description: neonGetBranchesForProject.description!,
    tool: neonGetBranchesForProject,
    requiredAuth: 'neonApiKey' as const,
    scope: 'read' as const,
    keywords: ['postgres'],
  },
  {
    name: 'NeonGetBranchesMaskingRules',
    description: neonGetBranchesMaskingRules.description!,
    tool: neonGetBranchesMaskingRules,
    requiredAuth: 'neonApiKey' as const,
    scope: 'read' as const,
    keywords: ['mask', 'pii'],
  },
  {
    name: 'NeonGetBranchRolesForProject',
    description: neonGetBranchRolesForProject.description!,
    tool: neonGetBranchRolesForProject,
    requiredAuth: 'neonApiKey' as const,
    scope: 'read' as const,
    keywords: ['user', 'permissions'],
  },
  {
    name: 'NeonGetConsumptionHistoryProjects',
    description: neonGetConsumptionHistoryProjects.description!,
    tool: neonGetConsumptionHistoryProjects,
    requiredAuth: 'neonApiKey' as const,
    scope: 'read' as const,
    keywords: ['billing', 'cost', 'usage'],
  },
  {
    name: 'NeonGetCurrentUserInformation',
    description: neonGetCurrentUserInformation.description!,
    tool: neonGetCurrentUserInformation,
    requiredAuth: 'neonApiKey' as const,
    scope: 'read' as const,
    keywords: ['profile', 'account'],
  },
  {
    name: 'NeonGetOrganizationApiKeys',
    description: neonGetOrganizationApiKeys.description!,
    tool: neonGetOrganizationApiKeys,
    requiredAuth: 'neonApiKey' as const,
    scope: 'read' as const,
    keywords: ['token', 'audit'],
  },
  {
    name: 'NeonGetProjectBranches',
    description: neonGetProjectBranches.description!,
    tool: neonGetProjectBranches,
    requiredAuth: 'neonApiKey' as const,
    scope: 'read' as const,
    keywords: ['postgres'],
  },
  {
    name: 'NeonGetProjectBranchRole',
    description: neonGetProjectBranchRole.description!,
    tool: neonGetProjectBranchRole,
    requiredAuth: 'neonApiKey' as const,
    scope: 'read' as const,
    keywords: ['user', 'permissions'],
  },
  {
    name: 'NeonGetProjectBranchSchemaComparison',
    description: neonGetProjectBranchSchemaComparison.description!,
    tool: neonGetProjectBranchSchemaComparison,
    requiredAuth: 'neonApiKey' as const,
    scope: 'read' as const,
    keywords: ['diff', 'migration'],
  },
  {
    name: 'NeonGetProjectConnectionUri',
    description: neonGetProjectConnectionUri.description!,
    tool: neonGetProjectConnectionUri,
    requiredAuth: 'neonApiKey' as const,
    scope: 'read' as const,
    keywords: ['string', 'url', 'connect', 'credentials'],
  },
  {
    name: 'NeonGetProjectEndpointInformation',
    description: neonGetProjectEndpointInformation.description!,
    tool: neonGetProjectEndpointInformation,
    requiredAuth: 'neonApiKey' as const,
    scope: 'read' as const,
    keywords: ['instance', 'host', 'connect'],
  },
  {
    name: 'NeonGetProjectOperationById',
    description: neonGetProjectOperationById.description!,
    tool: neonGetProjectOperationById,
    requiredAuth: 'neonApiKey' as const,
    scope: 'read' as const,
    keywords: ['task', 'job', 'progress', 'status'],
  },
  {
    name: 'NeonGetSchemaForProjectBranch',
    description: neonGetSchemaForProjectBranch.description!,
    tool: neonGetSchemaForProjectBranch,
    requiredAuth: 'neonApiKey' as const,
    scope: 'read' as const,
    keywords: ['migration', 'migrate', 'diff'],
  },
  {
    name: 'NeonGetUserOrganizations',
    description: neonGetUserOrganizations.description!,
    tool: neonGetUserOrganizations,
    requiredAuth: 'neonApiKey' as const,
    scope: 'read' as const,
    keywords: ['team'],
  },
  {
    name: 'NeonGetVpcRegionEndpoints',
    description: neonGetVpcRegionEndpoints.description!,
    tool: neonGetVpcRegionEndpoints,
    requiredAuth: 'neonApiKey' as const,
    scope: 'read' as const,
    keywords: [],
  },
  {
    name: 'NeonListApiKeys',
    description: neonListApiKeys.description!,
    tool: neonListApiKeys,
    requiredAuth: 'neonApiKey' as const,
    scope: 'read' as const,
    keywords: ['token', 'audit'],
  },
  {
    name: 'NeonListAuthDomains',
    description: neonListAuthDomains.description!,
    tool: neonListAuthDomains,
    requiredAuth: 'neonApiKey' as const,
    scope: 'read' as const,
    keywords: [],
  },
  {
    name: 'NeonListAuthOauthProviders',
    description: neonListAuthOauthProviders.description!,
    tool: neonListAuthOauthProviders,
    requiredAuth: 'neonApiKey' as const,
    scope: 'read' as const,
    keywords: [],
  },
  {
    name: 'NeonListAuthOauthProviders2',
    description: neonListAuthOauthProviders2.description!,
    tool: neonListAuthOauthProviders2,
    requiredAuth: 'neonApiKey' as const,
    scope: 'read' as const,
    keywords: [],
  },
  {
    name: 'NeonListProjectsSnapshots',
    description: neonListProjectsSnapshots.description!,
    tool: neonListProjectsSnapshots,
    requiredAuth: 'neonApiKey' as const,
    scope: 'read' as const,
    keywords: ['backup', 'restore'],
  },
  {
    name: 'NeonListSharedProjects',
    description: neonListSharedProjects.description!,
    tool: neonListSharedProjects,
    requiredAuth: 'neonApiKey' as const,
    scope: 'read' as const,
    keywords: ['collaboration', 'team', 'postgres'],
  },
  {
    name: 'NeonListVpcVpcEndpoints',
    description: neonListVpcVpcEndpoints.description!,
    tool: neonListVpcVpcEndpoints,
    requiredAuth: 'neonApiKey' as const,
    scope: 'read' as const,
    keywords: [],
  },
  {
    name: 'NeonModifyBranchDetailsInProject',
    description: neonModifyBranchDetailsInProject.description!,
    tool: neonModifyBranchDetailsInProject,
    requiredAuth: 'neonApiKey' as const,
    scope: 'write' as const,
    keywords: ['rename'],
  },
  {
    name: 'NeonPatchBranchDatabaseInformation',
    description: neonPatchBranchDatabaseInformation.description!,
    tool: neonPatchBranchDatabaseInformation,
    requiredAuth: 'neonApiKey' as const,
    scope: 'write' as const,
    keywords: ['rename', 'schema'],
  },
  {
    name: 'NeonResetRolePasswordForBranch',
    description: neonResetRolePasswordForBranch.description!,
    tool: neonResetRolePasswordForBranch,
    requiredAuth: 'neonApiKey' as const,
    scope: 'write' as const,
    keywords: ['rotate', 'credentials'],
  },
  {
    name: 'NeonRestartProjectEndpoint',
    description: neonRestartProjectEndpoint.description!,
    tool: neonRestartProjectEndpoint,
    requiredAuth: 'neonApiKey' as const,
    scope: 'write' as const,
    keywords: ['reboot', 'instance'],
  },
  {
    name: 'NeonRestoreProjectBranch',
    description: neonRestoreProjectBranch.description!,
    tool: neonRestoreProjectBranch,
    requiredAuth: 'neonApiKey' as const,
    scope: 'write' as const,
    keywords: ['rollback', 'pitr', 'recover'],
  },
  {
    name: 'NeonRestoreSnapshot',
    description: neonRestoreSnapshot.description!,
    tool: neonRestoreSnapshot,
    requiredAuth: 'neonApiKey' as const,
    scope: 'write' as const,
    keywords: ['rollback', 'recover', 'backup'],
  },
  {
    name: 'NeonRetrieveAccountConsumptionHistory',
    description: neonRetrieveAccountConsumptionHistory.description!,
    tool: neonRetrieveAccountConsumptionHistory,
    requiredAuth: 'neonApiKey' as const,
    scope: 'read' as const,
    keywords: ['billing', 'cost', 'usage'],
  },
  {
    name: 'NeonRetrieveAllRegions',
    description: neonRetrieveAllRegions.description!,
    tool: neonRetrieveAllRegions,
    requiredAuth: 'neonApiKey' as const,
    scope: 'read' as const,
    keywords: ['location'],
  },
  {
    name: 'NeonRetrieveBranchDatabaseDetails',
    description: neonRetrieveBranchDatabaseDetails.description!,
    tool: neonRetrieveBranchDatabaseDetails,
    requiredAuth: 'neonApiKey' as const,
    scope: 'read' as const,
    keywords: ['postgres', 'schema'],
  },
  {
    name: 'NeonRetrieveBranchEndpoints',
    description: neonRetrieveBranchEndpoints.description!,
    tool: neonRetrieveBranchEndpoints,
    requiredAuth: 'neonApiKey' as const,
    scope: 'read' as const,
    keywords: ['instance', 'host', 'connect'],
  },
  {
    name: 'NeonRetrieveJwksForProject',
    description: neonRetrieveJwksForProject.description!,
    tool: neonRetrieveJwksForProject,
    requiredAuth: 'neonApiKey' as const,
    scope: 'read' as const,
    keywords: [],
  },
  {
    name: 'NeonRetrieveOrganizationById',
    description: neonRetrieveOrganizationById.description!,
    tool: neonRetrieveOrganizationById,
    requiredAuth: 'neonApiKey' as const,
    scope: 'read' as const,
    keywords: ['team'],
  },
  {
    name: 'NeonRetrieveOrganizationInvitations',
    description: neonRetrieveOrganizationInvitations.description!,
    tool: neonRetrieveOrganizationInvitations,
    requiredAuth: 'neonApiKey' as const,
    scope: 'read' as const,
    keywords: ['invite', 'team'],
  },
  {
    name: 'NeonRetrieveOrganizationMemberInfo',
    description: neonRetrieveOrganizationMemberInfo.description!,
    tool: neonRetrieveOrganizationMemberInfo,
    requiredAuth: 'neonApiKey' as const,
    scope: 'read' as const,
    keywords: ['team', 'permissions'],
  },
  {
    name: 'NeonRetrieveProjectEndpointDetails',
    description: neonRetrieveProjectEndpointDetails.description!,
    tool: neonRetrieveProjectEndpointDetails,
    requiredAuth: 'neonApiKey' as const,
    scope: 'read' as const,
    keywords: ['instance', 'host', 'connect'],
  },
  {
    name: 'NeonRetrieveProjectOperations',
    description: neonRetrieveProjectOperations.description!,
    tool: neonRetrieveProjectOperations,
    requiredAuth: 'neonApiKey' as const,
    scope: 'read' as const,
    keywords: ['task', 'history'],
  },
  {
    name: 'NeonRetrieveProjectPermissions',
    description: neonRetrieveProjectPermissions.description!,
    tool: neonRetrieveProjectPermissions,
    requiredAuth: 'neonApiKey' as const,
    scope: 'read' as const,
    keywords: ['access', 'acl'],
  },
  {
    name: 'NeonRetrieveProjectsList',
    description: neonRetrieveProjectsList.description!,
    tool: neonRetrieveProjectsList,
    requiredAuth: 'neonApiKey' as const,
    scope: 'read' as const,
    keywords: ['postgres', 'database', 'browse'],
  },
  {
    name: 'NeonRetrieveVpcEndpointsForProject',
    description: neonRetrieveVpcEndpointsForProject.description!,
    tool: neonRetrieveVpcEndpointsForProject,
    requiredAuth: 'neonApiKey' as const,
    scope: 'read' as const,
    keywords: [],
  },
  {
    name: 'NeonRevealRolePasswordInBranch',
    description: neonRevealRolePasswordInBranch.description!,
    tool: neonRevealRolePasswordInBranch,
    requiredAuth: 'neonApiKey' as const,
    scope: 'write' as const,
    keywords: ['credentials'],
  },
  {
    name: 'NeonSendAuthTestEmail',
    description: neonSendAuthTestEmail.description!,
    tool: neonSendAuthTestEmail,
    requiredAuth: 'neonApiKey' as const,
    scope: 'write' as const,
    keywords: [],
  },
  {
    name: 'NeonSendOrganizationInvitations',
    description: neonSendOrganizationInvitations.description!,
    tool: neonSendOrganizationInvitations,
    requiredAuth: 'neonApiKey' as const,
    scope: 'write' as const,
    keywords: ['invite', 'team', 'member'],
  },
  {
    name: 'NeonSetBranchAsDefault',
    description: neonSetBranchAsDefault.description!,
    tool: neonSetBranchAsDefault,
    requiredAuth: 'neonApiKey' as const,
    scope: 'write' as const,
    keywords: ['main', 'primary'],
  },
  {
    name: 'NeonStartBranchAnonymization',
    description: neonStartBranchAnonymization.description!,
    tool: neonStartBranchAnonymization,
    requiredAuth: 'neonApiKey' as const,
    scope: 'write' as const,
    keywords: ['mask'],
  },
  {
    name: 'NeonStartEndpointForProject',
    description: neonStartEndpointForProject.description!,
    tool: neonStartEndpointForProject,
    requiredAuth: 'neonApiKey' as const,
    scope: 'write' as const,
    keywords: ['wake', 'resume', 'instance'],
  },
  {
    name: 'NeonSuspendProjectEndpointById',
    description: neonSuspendProjectEndpointById.description!,
    tool: neonSuspendProjectEndpointById,
    requiredAuth: 'neonApiKey' as const,
    scope: 'write' as const,
    keywords: ['sleep', 'pause'],
  },
  {
    name: 'NeonTransferProjectsBetweenOrganizations',
    description: neonTransferProjectsBetweenOrganizations.description!,
    tool: neonTransferProjectsBetweenOrganizations,
    requiredAuth: 'neonApiKey' as const,
    scope: 'write' as const,
    keywords: ['move', 'ownership'],
  },
  {
    name: 'NeonTransferUserProjectsToOrganization',
    description: neonTransferUserProjectsToOrganization.description!,
    tool: neonTransferUserProjectsToOrganization,
    requiredAuth: 'neonApiKey' as const,
    scope: 'write' as const,
    keywords: ['move', 'ownership'],
  },
  {
    name: 'NeonUpdateAuthAllowLocalhost',
    description: neonUpdateAuthAllowLocalhost.description!,
    tool: neonUpdateAuthAllowLocalhost,
    requiredAuth: 'neonApiKey' as const,
    scope: 'write' as const,
    keywords: [],
  },
  {
    name: 'NeonUpdateAuthEmailProvider',
    description: neonUpdateAuthEmailProvider.description!,
    tool: neonUpdateAuthEmailProvider,
    requiredAuth: 'neonApiKey' as const,
    scope: 'write' as const,
    keywords: ['smtp'],
  },
  {
    name: 'NeonUpdateAuthOauthProviders',
    description: neonUpdateAuthOauthProviders.description!,
    tool: neonUpdateAuthOauthProviders,
    requiredAuth: 'neonApiKey' as const,
    scope: 'write' as const,
    keywords: [],
  },
  {
    name: 'NeonUpdateBranchesDataApi',
    description: neonUpdateBranchesDataApi.description!,
    tool: neonUpdateBranchesDataApi,
    requiredAuth: 'neonApiKey' as const,
    scope: 'write' as const,
    keywords: ['rest'],
  },
  {
    name: 'NeonUpdateBranchesMaskingRules',
    description: neonUpdateBranchesMaskingRules.description!,
    tool: neonUpdateBranchesMaskingRules,
    requiredAuth: 'neonApiKey' as const,
    scope: 'write' as const,
    keywords: ['mask'],
  },
  {
    name: 'NeonUpdateOrganizationMemberRole',
    description: neonUpdateOrganizationMemberRole.description!,
    tool: neonUpdateOrganizationMemberRole,
    requiredAuth: 'neonApiKey' as const,
    scope: 'write' as const,
    keywords: ['permissions', 'admin'],
  },
  {
    name: 'NeonUpdateProjectComputeEndpointSettings',
    description: neonUpdateProjectComputeEndpointSettings.description!,
    tool: neonUpdateProjectComputeEndpointSettings,
    requiredAuth: 'neonApiKey' as const,
    scope: 'write' as const,
    keywords: ['pooler', 'autoscale', 'scale'],
  },
  {
    name: 'NeonUpdateProjectSettingsById',
    description: neonUpdateProjectSettingsById.description!,
    tool: neonUpdateProjectSettingsById,
    requiredAuth: 'neonApiKey' as const,
    scope: 'write' as const,
    keywords: ['quotas', 'limits'],
  },
  {
    name: 'NeonUpdateProjectsSnapshots',
    description: neonUpdateProjectsSnapshots.description!,
    tool: neonUpdateProjectsSnapshots,
    requiredAuth: 'neonApiKey' as const,
    scope: 'write' as const,
    keywords: ['rename'],
  },
];
