// @ts-nocheck
import {
  elasticGetInfo,
  elasticGetHealth,
  elasticGetHealthReport,
  elasticGetStats,
  elasticGetState,
  elasticGetSettings,
  elasticUpdateSettings,
  elasticGetPendingTasks,
  elasticReroute,
  elasticExplainAllocation,
  elasticGetRemoteInfo,
  elasticGetNodes,
  elasticGetNodesStats,
  elasticListTasks,
  elasticGetTask,
  elasticCancelTask,
  elasticCatHealth,
  elasticCatIndices,
  elasticCatNodes,
  elasticCatShards,
  elasticCatAliases,
} from './cluster.js';
import {
  elasticGetIndex,
  elasticCreateIndex,
  elasticDeleteIndex,
  elasticGetIndexStats,
  elasticRefreshIndex,
  elasticFlushIndex,
  elasticForceMergeIndex,
  elasticOpenIndex,
  elasticCloseIndex,
  elasticGetMapping,
  elasticPutMapping,
  elasticGetIndexSettings,
  elasticUpdateIndexSettings,
  elasticGetAliases,
  elasticUpdateAliases,
  elasticCloneIndex,
  elasticListDataStreams,
  elasticCreateDataStream,
  elasticDeleteDataStream,
  elasticListIndexTemplates,
  elasticPutIndexTemplate,
  elasticDeleteIndexTemplate,
  elasticListIlmPolicies,
  elasticGetIlmPolicy,
  elasticPutIlmPolicy,
  elasticDeleteIlmPolicy,
  elasticExplainIlm,
  elasticRetryIlm,
} from './indices.js';
import {
  elasticIndexDocument,
  elasticCreateDocument,
  elasticGetDocument,
  elasticUpdateDocument,
  elasticDeleteDocument,
  elasticBulk,
  elasticMultiGet,
  elasticCount,
  elasticSearch,
  elasticMultiSearch,
  elasticScrollSearch,
  elasticClearScroll,
  elasticDeleteByQuery,
  elasticUpdateByQuery,
  elasticReindex,
  elasticExplainDocument,
  elasticFieldCaps,
  elasticSqlQuery,
  elasticSqlTranslate,
  elasticEqlSearch,
  elasticSubmitAsyncSearch,
  elasticGetAsyncSearch,
  elasticDeleteAsyncSearch,
  elasticOpenPointInTime,
  elasticClosePointInTime,
} from './documents.js';
import {
  elasticListSnapshotRepos,
  elasticGetSnapshotRepo,
  elasticCreateSnapshotRepo,
  elasticDeleteSnapshotRepo,
  elasticVerifySnapshotRepo,
  elasticListSnapshots,
  elasticGetSnapshot,
  elasticCreateSnapshot,
  elasticDeleteSnapshot,
  elasticRestoreSnapshot,
  elasticGetSnapshotStatus,
  elasticCreateApiKey,
  elasticGetApiKey,
  elasticQueryApiKeys,
  elasticUpdateApiKey,
  elasticInvalidateApiKeys,
  elasticListUsers,
  elasticGetUser,
  elasticCreateUser,
  elasticDeleteUser,
  elasticAuthenticate,
  elasticListRoles,
  elasticGetRole,
  elasticCreateRole,
  elasticDeleteRole,
  elasticListRoleMappings,
  elasticCreateRoleMapping,
  elasticDeleteRoleMapping,
  elasticGetToken,
  elasticInvalidateToken,
  elasticListIngestPipelines,
  elasticGetIngestPipeline,
  elasticPutIngestPipeline,
  elasticDeleteIngestPipeline,
  elasticSimulatePipeline,
} from './admin.js';

export {
  elasticGetInfo,
  elasticGetHealth,
  elasticGetHealthReport,
  elasticGetStats,
  elasticGetState,
  elasticGetSettings,
  elasticUpdateSettings,
  elasticGetPendingTasks,
  elasticReroute,
  elasticExplainAllocation,
  elasticGetRemoteInfo,
  elasticGetNodes,
  elasticGetNodesStats,
  elasticListTasks,
  elasticGetTask,
  elasticCancelTask,
  elasticCatHealth,
  elasticCatIndices,
  elasticCatNodes,
  elasticCatShards,
  elasticCatAliases,
  elasticGetIndex,
  elasticCreateIndex,
  elasticDeleteIndex,
  elasticGetIndexStats,
  elasticRefreshIndex,
  elasticFlushIndex,
  elasticForceMergeIndex,
  elasticOpenIndex,
  elasticCloseIndex,
  elasticGetMapping,
  elasticPutMapping,
  elasticGetIndexSettings,
  elasticUpdateIndexSettings,
  elasticGetAliases,
  elasticUpdateAliases,
  elasticCloneIndex,
  elasticListDataStreams,
  elasticCreateDataStream,
  elasticDeleteDataStream,
  elasticListIndexTemplates,
  elasticPutIndexTemplate,
  elasticDeleteIndexTemplate,
  elasticListIlmPolicies,
  elasticGetIlmPolicy,
  elasticPutIlmPolicy,
  elasticDeleteIlmPolicy,
  elasticExplainIlm,
  elasticRetryIlm,
  elasticIndexDocument,
  elasticCreateDocument,
  elasticGetDocument,
  elasticUpdateDocument,
  elasticDeleteDocument,
  elasticBulk,
  elasticMultiGet,
  elasticCount,
  elasticSearch,
  elasticMultiSearch,
  elasticScrollSearch,
  elasticClearScroll,
  elasticDeleteByQuery,
  elasticUpdateByQuery,
  elasticReindex,
  elasticExplainDocument,
  elasticFieldCaps,
  elasticSqlQuery,
  elasticSqlTranslate,
  elasticEqlSearch,
  elasticSubmitAsyncSearch,
  elasticGetAsyncSearch,
  elasticDeleteAsyncSearch,
  elasticOpenPointInTime,
  elasticClosePointInTime,
  elasticListSnapshotRepos,
  elasticGetSnapshotRepo,
  elasticCreateSnapshotRepo,
  elasticDeleteSnapshotRepo,
  elasticVerifySnapshotRepo,
  elasticListSnapshots,
  elasticGetSnapshot,
  elasticCreateSnapshot,
  elasticDeleteSnapshot,
  elasticRestoreSnapshot,
  elasticGetSnapshotStatus,
  elasticCreateApiKey,
  elasticGetApiKey,
  elasticQueryApiKeys,
  elasticUpdateApiKey,
  elasticInvalidateApiKeys,
  elasticListUsers,
  elasticGetUser,
  elasticCreateUser,
  elasticDeleteUser,
  elasticAuthenticate,
  elasticListRoles,
  elasticGetRole,
  elasticCreateRole,
  elasticDeleteRole,
  elasticListRoleMappings,
  elasticCreateRoleMapping,
  elasticDeleteRoleMapping,
  elasticGetToken,
  elasticInvalidateToken,
  elasticListIngestPipelines,
  elasticGetIngestPipeline,
  elasticPutIngestPipeline,
  elasticDeleteIngestPipeline,
  elasticSimulatePipeline,
};

const AUTH = 'elasticCredentials' as const;

export const elasticTools = [
  {
    name: 'elasticGetInfo',
    description: 'Get cluster info and version; verifies connectivity.',
    tool: elasticGetInfo,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['health', 'ping', 'status'],
  },
  {
    name: 'elasticGetHealth',
    description: 'Get cluster health (green/yellow/red).',
    tool: elasticGetHealth,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['status', 'shards'],
  },
  {
    name: 'elasticGetHealthReport',
    description: 'Get health report with diagnoses.',
    tool: elasticGetHealthReport,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['diagnose', 'indicators'],
  },
  {
    name: 'elasticGetStats',
    description: 'Get cluster-wide stats.',
    tool: elasticGetStats,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['metrics', 'capacity'],
  },
  {
    name: 'elasticGetState',
    description: 'Get cluster state metadata.',
    tool: elasticGetState,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['routing', 'metadata'],
  },
  {
    name: 'elasticGetSettings',
    description: 'Get cluster settings.',
    tool: elasticGetSettings,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['config'],
  },
  {
    name: 'elasticUpdateSettings',
    description: 'Update persistent/transient settings.',
    tool: elasticUpdateSettings,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['config', 'tune'],
  },
  {
    name: 'elasticGetPendingTasks',
    description: 'List pending cluster tasks.',
    tool: elasticGetPendingTasks,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['queue', 'stuck'],
  },
  {
    name: 'elasticReroute',
    description: 'Manually reroute shards.',
    tool: elasticReroute,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['allocate', 'move'],
  },
  {
    name: 'elasticExplainAllocation',
    description: 'Explain unassigned shards.',
    tool: elasticExplainAllocation,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['deciders', 'debug'],
  },
  {
    name: 'elasticGetRemoteInfo',
    description: 'Get remote clusters for CCS/CCR.',
    tool: elasticGetRemoteInfo,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['cross-cluster', 'federation'],
  },
  {
    name: 'elasticGetNodes',
    description: 'Get node info.',
    tool: elasticGetNodes,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['servers', 'roles'],
  },
  {
    name: 'elasticGetNodesStats',
    description: 'Get node stats (JVM, OS, pools).',
    tool: elasticGetNodesStats,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['metrics', 'jvm'],
  },
  {
    name: 'elasticListTasks',
    description: 'List running tasks.',
    tool: elasticListTasks,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['jobs', 'operations'],
  },
  {
    name: 'elasticGetTask',
    description: 'Get one task.',
    tool: elasticGetTask,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['job', 'fetch'],
  },
  {
    name: 'elasticCancelTask',
    description: 'Cancel a running task.',
    tool: elasticCancelTask,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['kill', 'abort'],
  },
  {
    name: 'elasticCatHealth',
    description: 'Compact health table.',
    tool: elasticCatHealth,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['overview'],
  },
  {
    name: 'elasticCatIndices',
    description: 'Compact index table with sizes.',
    tool: elasticCatIndices,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['storage', 'audit'],
  },
  {
    name: 'elasticCatNodes',
    description: 'Compact node table.',
    tool: elasticCatNodes,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['servers'],
  },
  {
    name: 'elasticCatShards',
    description: 'Compact shard table.',
    tool: elasticCatShards,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['unassigned', 'rebalance'],
  },
  {
    name: 'elasticCatAliases',
    description: 'Compact alias table.',
    tool: elasticCatAliases,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['pointers'],
  },
  {
    name: 'elasticGetIndex',
    description: 'Get index settings and mappings.',
    tool: elasticGetIndex,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['fetch', 'config'],
  },
  {
    name: 'elasticCreateIndex',
    description: 'Create an index.',
    tool: elasticCreateIndex,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['new', 'schema'],
  },
  {
    name: 'elasticDeleteIndex',
    description: 'Delete indices.',
    tool: elasticDeleteIndex,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['drop', 'purge'],
  },
  {
    name: 'elasticGetIndexStats',
    description: 'Get index stats.',
    tool: elasticGetIndexStats,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['metrics', 'docs'],
  },
  {
    name: 'elasticRefreshIndex',
    description: 'Refresh indices.',
    tool: elasticRefreshIndex,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['searchable', 'flush'],
  },
  {
    name: 'elasticFlushIndex',
    description: 'Flush indices.',
    tool: elasticFlushIndex,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['fsync', 'translog'],
  },
  {
    name: 'elasticForceMergeIndex',
    description: 'Force-merge segments.',
    tool: elasticForceMergeIndex,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['optimize', 'compact'],
  },
  {
    name: 'elasticOpenIndex',
    description: 'Open a closed index.',
    tool: elasticOpenIndex,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['enable'],
  },
  {
    name: 'elasticCloseIndex',
    description: 'Close an index.',
    tool: elasticCloseIndex,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['disable', 'freeze'],
  },
  {
    name: 'elasticGetMapping',
    description: 'Get field mappings.',
    tool: elasticGetMapping,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['schema', 'fields'],
  },
  {
    name: 'elasticPutMapping',
    description: 'Add fields to a mapping.',
    tool: elasticPutMapping,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['schema', 'extend'],
  },
  {
    name: 'elasticGetIndexSettings',
    description: 'Get live index settings.',
    tool: elasticGetIndexSettings,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['config', 'replicas'],
  },
  {
    name: 'elasticUpdateIndexSettings',
    description: 'Update dynamic index settings.',
    tool: elasticUpdateIndexSettings,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['replicas', 'tune'],
  },
  {
    name: 'elasticGetAliases',
    description: 'Get aliases.',
    tool: elasticGetAliases,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['pointers'],
  },
  {
    name: 'elasticUpdateAliases',
    description: 'Atomic alias add/remove.',
    tool: elasticUpdateAliases,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['swap', 'reindex', 'cutover'],
  },
  {
    name: 'elasticCloneIndex',
    description: 'Clone an index.',
    tool: elasticCloneIndex,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['duplicate', 'copy'],
  },
  {
    name: 'elasticListDataStreams',
    description: 'List data streams.',
    tool: elasticListDataStreams,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['logs', 'timeseries'],
  },
  {
    name: 'elasticCreateDataStream',
    description: 'Create a data stream.',
    tool: elasticCreateDataStream,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['logs', 'append'],
  },
  {
    name: 'elasticDeleteDataStream',
    description: 'Delete data streams.',
    tool: elasticDeleteDataStream,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['logs', 'remove'],
  },
  {
    name: 'elasticListIndexTemplates',
    description: 'List index templates.',
    tool: elasticListIndexTemplates,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['patterns', 'defaults'],
  },
  {
    name: 'elasticPutIndexTemplate',
    description: 'Create/update an index template.',
    tool: elasticPutIndexTemplate,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['patterns', 'schema'],
  },
  {
    name: 'elasticDeleteIndexTemplate',
    description: 'Delete an index template.',
    tool: elasticDeleteIndexTemplate,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['patterns', 'remove'],
  },
  {
    name: 'elasticListIlmPolicies',
    description: 'List ILM policies.',
    tool: elasticListIlmPolicies,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['lifecycle', 'retention'],
  },
  {
    name: 'elasticGetIlmPolicy',
    description: 'Get one ILM policy.',
    tool: elasticGetIlmPolicy,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['lifecycle', 'fetch'],
  },
  {
    name: 'elasticPutIlmPolicy',
    description: 'Create/update an ILM policy.',
    tool: elasticPutIlmPolicy,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['lifecycle', 'rollover'],
  },
  {
    name: 'elasticDeleteIlmPolicy',
    description: 'Delete an ILM policy.',
    tool: elasticDeleteIlmPolicy,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['lifecycle', 'remove'],
  },
  {
    name: 'elasticExplainIlm',
    description: 'Explain ILM state of an index.',
    tool: elasticExplainIlm,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['lifecycle', 'stuck', 'phase'],
  },
  {
    name: 'elasticRetryIlm',
    description: 'Retry a failed ILM step.',
    tool: elasticRetryIlm,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['lifecycle', 'recover'],
  },
  {
    name: 'elasticIndexDocument',
    description: 'Index a document with an ID.',
    tool: elasticIndexDocument,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['insert', 'upsert'],
  },
  {
    name: 'elasticCreateDocument',
    description: 'Create a document (auto ID or 409).',
    tool: elasticCreateDocument,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['insert', 'new'],
  },
  {
    name: 'elasticGetDocument',
    description: 'Get a document by ID.',
    tool: elasticGetDocument,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['fetch', 'retrieve'],
  },
  {
    name: 'elasticUpdateDocument',
    description: 'Partially update a document.',
    tool: elasticUpdateDocument,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['patch', 'merge'],
  },
  {
    name: 'elasticDeleteDocument',
    description: 'Delete a document.',
    tool: elasticDeleteDocument,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['remove'],
  },
  {
    name: 'elasticBulk',
    description: 'Bulk index/update/delete.',
    tool: elasticBulk,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['batch', 'ingest', 'import'],
  },
  {
    name: 'elasticMultiGet',
    description: 'Fetch multiple documents.',
    tool: elasticMultiGet,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['batch', 'fetch'],
  },
  {
    name: 'elasticCount',
    description: 'Count matching documents.',
    tool: elasticCount,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['total', 'stats'],
  },
  {
    name: 'elasticSearch',
    description: 'Full Query DSL search with aggs.',
    tool: elasticSearch,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['query', 'find', 'fulltext'],
  },
  {
    name: 'elasticMultiSearch',
    description: 'Run multiple searches.',
    tool: elasticMultiSearch,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['batch', 'parallel'],
  },
  {
    name: 'elasticScrollSearch',
    description: 'Deep-paginate with scroll.',
    tool: elasticScrollSearch,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['export', 'dump', 'paginate'],
  },
  {
    name: 'elasticClearScroll',
    description: 'Release scroll contexts.',
    tool: elasticClearScroll,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['cleanup'],
  },
  {
    name: 'elasticDeleteByQuery',
    description: 'Delete documents by query.',
    tool: elasticDeleteByQuery,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['purge', 'bulk'],
  },
  {
    name: 'elasticUpdateByQuery',
    description: 'Update documents by query.',
    tool: elasticUpdateByQuery,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['bulk', 'migrate'],
  },
  {
    name: 'elasticReindex',
    description: 'Copy documents between indices.',
    tool: elasticReindex,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['migrate', 'copy'],
  },
  {
    name: 'elasticExplainDocument',
    description: 'Explain query scoring.',
    tool: elasticExplainDocument,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['relevance', 'debug'],
  },
  {
    name: 'elasticFieldCaps',
    description: 'Get field capabilities.',
    tool: elasticFieldCaps,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['schema', 'types'],
  },
  {
    name: 'elasticSqlQuery',
    description: 'Run SQL analytics.',
    tool: elasticSqlQuery,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['jdbc', 'select', 'aggregate'],
  },
  {
    name: 'elasticSqlTranslate',
    description: 'Translate SQL to DSL.',
    tool: elasticSqlTranslate,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['debug', 'learn'],
  },
  {
    name: 'elasticEqlSearch',
    description: 'Run EQL event sequences.',
    tool: elasticEqlSearch,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['timeline', 'security', 'logs'],
  },
  {
    name: 'elasticSubmitAsyncSearch',
    description: 'Submit async search.',
    tool: elasticSubmitAsyncSearch,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['long', 'background'],
  },
  {
    name: 'elasticGetAsyncSearch',
    description: 'Get async search results.',
    tool: elasticGetAsyncSearch,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['poll'],
  },
  {
    name: 'elasticDeleteAsyncSearch',
    description: 'Delete async search.',
    tool: elasticDeleteAsyncSearch,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['cleanup'],
  },
  {
    name: 'elasticOpenPointInTime',
    description: 'Open a PIT reader.',
    tool: elasticOpenPointInTime,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['consistent', 'snapshot'],
  },
  {
    name: 'elasticClosePointInTime',
    description: 'Close a PIT reader.',
    tool: elasticClosePointInTime,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['cleanup'],
  },
  {
    name: 'elasticListSnapshotRepos',
    description: 'List snapshot repositories.',
    tool: elasticListSnapshotRepos,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['backups', 's3'],
  },
  {
    name: 'elasticGetSnapshotRepo',
    description: 'Get one snapshot repo.',
    tool: elasticGetSnapshotRepo,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['backup', 'fetch'],
  },
  {
    name: 'elasticCreateSnapshotRepo',
    description: 'Create a snapshot repo.',
    tool: elasticCreateSnapshotRepo,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['backup', 's3', 'configure'],
  },
  {
    name: 'elasticDeleteSnapshotRepo',
    description: 'Delete a snapshot repo.',
    tool: elasticDeleteSnapshotRepo,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['backup', 'remove'],
  },
  {
    name: 'elasticVerifySnapshotRepo',
    description: 'Verify snapshot storage access.',
    tool: elasticVerifySnapshotRepo,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['backup', 'check'],
  },
  {
    name: 'elasticListSnapshots',
    description: 'List snapshots.',
    tool: elasticListSnapshots,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['backups'],
  },
  {
    name: 'elasticGetSnapshot',
    description: 'Get one snapshot.',
    tool: elasticGetSnapshot,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['backup', 'fetch'],
  },
  {
    name: 'elasticCreateSnapshot',
    description: 'Take a snapshot.',
    tool: elasticCreateSnapshot,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['backup', 'save'],
  },
  {
    name: 'elasticDeleteSnapshot',
    description: 'Delete snapshots.',
    tool: elasticDeleteSnapshot,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['backup', 'prune'],
  },
  {
    name: 'elasticRestoreSnapshot',
    description: 'Restore indices from a snapshot.',
    tool: elasticRestoreSnapshot,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['backup', 'recover'],
  },
  {
    name: 'elasticGetSnapshotStatus',
    description: 'Get snapshot progress.',
    tool: elasticGetSnapshotStatus,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['backup', 'progress'],
  },
  {
    name: 'elasticCreateApiKey',
    description: 'Create an API key.',
    tool: elasticCreateApiKey,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['credential', 'generate'],
  },
  {
    name: 'elasticGetApiKey',
    description: 'Get API key metadata.',
    tool: elasticGetApiKey,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['credential', 'audit'],
  },
  {
    name: 'elasticQueryApiKeys',
    description: 'Query API keys.',
    tool: elasticQueryApiKeys,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['credential', 'filter'],
  },
  {
    name: 'elasticUpdateApiKey',
    description: 'Update an API key.',
    tool: elasticUpdateApiKey,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['credential', 'rotate'],
  },
  {
    name: 'elasticInvalidateApiKeys',
    description: 'Invalidate API keys.',
    tool: elasticInvalidateApiKeys,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['credential', 'revoke'],
  },
  {
    name: 'elasticListUsers',
    description: 'List native users.',
    tool: elasticListUsers,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['accounts'],
  },
  {
    name: 'elasticGetUser',
    description: 'Get one user.',
    tool: elasticGetUser,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['account', 'fetch'],
  },
  {
    name: 'elasticCreateUser',
    description: 'Create/update a native user.',
    tool: elasticCreateUser,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['account', 'provision'],
  },
  {
    name: 'elasticDeleteUser',
    description: 'Delete a native user.',
    tool: elasticDeleteUser,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['account', 'remove'],
  },
  {
    name: 'elasticAuthenticate',
    description: 'Authenticate credentials; show roles.',
    tool: elasticAuthenticate,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['whoami', 'verify'],
  },
  {
    name: 'elasticListRoles',
    description: 'List roles.',
    tool: elasticListRoles,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['rbac', 'privileges'],
  },
  {
    name: 'elasticGetRole',
    description: 'Get one role.',
    tool: elasticGetRole,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['rbac', 'fetch'],
  },
  {
    name: 'elasticCreateRole',
    description: 'Create/update a role.',
    tool: elasticCreateRole,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['rbac', 'grant'],
  },
  {
    name: 'elasticDeleteRole',
    description: 'Delete a role.',
    tool: elasticDeleteRole,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['rbac', 'remove'],
  },
  {
    name: 'elasticListRoleMappings',
    description: 'List role mappings.',
    tool: elasticListRoleMappings,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['ldap', 'sso', 'groups'],
  },
  {
    name: 'elasticCreateRoleMapping',
    description: 'Create/update a role mapping.',
    tool: elasticCreateRoleMapping,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['ldap', 'sso'],
  },
  {
    name: 'elasticDeleteRoleMapping',
    description: 'Delete a role mapping.',
    tool: elasticDeleteRoleMapping,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['ldap', 'remove'],
  },
  {
    name: 'elasticGetToken',
    description: 'Get an OAuth2 bearer token.',
    tool: elasticGetToken,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['oauth', 'login'],
  },
  {
    name: 'elasticInvalidateToken',
    description: 'Invalidate OAuth2 tokens.',
    tool: elasticInvalidateToken,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['oauth', 'logout'],
  },
  {
    name: 'elasticListIngestPipelines',
    description: 'List ingest pipelines.',
    tool: elasticListIngestPipelines,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['etl', 'processors'],
  },
  {
    name: 'elasticGetIngestPipeline',
    description: 'Get one ingest pipeline.',
    tool: elasticGetIngestPipeline,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['etl', 'fetch'],
  },
  {
    name: 'elasticPutIngestPipeline',
    description: 'Create/update an ingest pipeline.',
    tool: elasticPutIngestPipeline,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['etl', 'grok', 'transform'],
  },
  {
    name: 'elasticDeleteIngestPipeline',
    description: 'Delete an ingest pipeline.',
    tool: elasticDeleteIngestPipeline,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['etl', 'remove'],
  },
  {
    name: 'elasticSimulatePipeline',
    description: 'Simulate a pipeline on sample docs.',
    tool: elasticSimulatePipeline,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['etl', 'debug', 'test'],
  },
];
