// @ts-nocheck
import { createCourseAlias, deleteCourseAlias, listCourseAliases } from './aliases.js';
import {
  createAnnouncement,
  deleteAnnouncement,
  getAnnouncement,
  listAnnouncements,
  modifyAnnouncementAssignees,
  patchAnnouncement,
} from './announcements.js';
import {
  deleteAnnouncementAddOnAttachment,
  getAnnouncementAddOnAttachment,
  getAnnouncementAddOnContext,
  listAnnouncementAddOnAttachments,
} from './announcement-addons.js';
import {
  createCourse,
  deleteCourse,
  getCourse,
  getGradingPeriodSettings,
  listCourseStudentGroups,
  listCourses,
  patchCourse,
  updateCourse,
} from './courses.js';
import {
  createCourseWork,
  deleteCourseWork,
  getCourseWork,
  listCourseWork,
  listCourseWorkRubrics,
  listStudentSubmissions,
  modifyCourseWorkAssignees,
  patchCourseWork,
  reclaimStudentSubmission,
} from './coursework.js';
import {
  deleteCourseWorkAddOnAttachment,
  getCourseWorkAddOnAttachment,
  getCourseWorkAddOnContext,
  listCourseWorkAddOnAttachments,
} from './coursework-addons.js';
import {
  createInvitation,
  deleteInvitation,
  getInvitation,
  listInvitations,
} from './invitations.js';
import {
  createCourseWorkMaterial,
  deleteCourseWorkMaterial,
  getCourseWorkMaterial,
  listCourseWorkMaterials,
  patchCourseWorkMaterial,
} from './materials.js';
import {
  getCourseWorkMaterialAddOnContext,
  listCourseWorkMaterialAddOnAttachments,
} from './materials-addons.js';
import { createRegistration, getUserProfile } from './misc.js';
import { getPostAddOnContext, listPostAddOnAttachments } from './posts-addons.js';
import {
  addStudentToCourse,
  deleteCourseStudent,
  deleteCourseTeacher,
  getCourseStudent,
  getTeacher,
  listCourseStudents,
  listCourseTeachers,
  listStudentGuardians,
} from './roster.js';
import {
  createCourseTopic,
  deleteCourseTopic,
  getCourseTopic,
  listCourseTopics,
  patchCourseTopic,
} from './topics.js';

export {
  createCourseAlias,
  deleteCourseAlias,
  listCourseAliases,
  createAnnouncement,
  deleteAnnouncement,
  getAnnouncement,
  listAnnouncements,
  modifyAnnouncementAssignees,
  patchAnnouncement,
  deleteAnnouncementAddOnAttachment,
  getAnnouncementAddOnAttachment,
  getAnnouncementAddOnContext,
  listAnnouncementAddOnAttachments,
  createCourse,
  deleteCourse,
  getCourse,
  getGradingPeriodSettings,
  listCourseStudentGroups,
  listCourses,
  patchCourse,
  updateCourse,
  createCourseWork,
  deleteCourseWork,
  getCourseWork,
  listCourseWork,
  listCourseWorkRubrics,
  listStudentSubmissions,
  modifyCourseWorkAssignees,
  patchCourseWork,
  reclaimStudentSubmission,
  deleteCourseWorkAddOnAttachment,
  getCourseWorkAddOnAttachment,
  getCourseWorkAddOnContext,
  listCourseWorkAddOnAttachments,
  createInvitation,
  deleteInvitation,
  getInvitation,
  listInvitations,
  createCourseWorkMaterial,
  deleteCourseWorkMaterial,
  getCourseWorkMaterial,
  listCourseWorkMaterials,
  patchCourseWorkMaterial,
  getCourseWorkMaterialAddOnContext,
  listCourseWorkMaterialAddOnAttachments,
  createRegistration,
  getUserProfile,
  getPostAddOnContext,
  listPostAddOnAttachments,
  addStudentToCourse,
  deleteCourseStudent,
  deleteCourseTeacher,
  getCourseStudent,
  getTeacher,
  listCourseStudents,
  listCourseTeachers,
  listStudentGuardians,
  createCourseTopic,
  deleteCourseTopic,
  getCourseTopic,
  listCourseTopics,
  patchCourseTopic,
};

const auth = 'googleClassroomToken' as const;

export const googleClassroomTools = [
  {
    name: 'googleClassroomCreateCourse',
    description: 'Creates a course before enrollment.',
    tool: createCourse,
    requiredAuth: auth,
    scope: 'write' as const,
    keywords: ['class', 'classes', 'new'],
  },
  {
    name: 'googleClassroomDeleteCourse',
    description: 'Deletes a course. Confirm the ID first.',
    tool: deleteCourse,
    requiredAuth: auth,
    scope: 'delete' as const,
    keywords: ['class', 'classes', 'remove'],
  },
  {
    name: 'googleClassroomGetCourse',
    description: 'Gets full course details by ID or alias.',
    tool: getCourse,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['class', 'classes'],
  },
  {
    name: 'googleClassroomListCourses',
    description: 'Lists your courses with filters and pagination.',
    tool: listCourses,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['class', 'classes', 'browse'],
  },
  {
    name: 'googleClassroomPatchCourse',
    description: 'Partially updates a course via updateMask.',
    tool: patchCourse,
    requiredAuth: auth,
    scope: 'write' as const,
    keywords: ['class', 'classes', 'rename'],
  },
  {
    name: 'googleClassroomUpdateCourse',
    description: 'Fully replaces a course (PUT).',
    tool: updateCourse,
    requiredAuth: auth,
    scope: 'write' as const,
    keywords: ['class', 'classes'],
  },
  {
    name: 'googleClassroomGetGradingPeriodSettings',
    description: 'Gets grading periods configured for a course.',
    tool: getGradingPeriodSettings,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['grade', 'grades', 'term', 'semester'],
  },
  {
    name: 'googleClassroomListCourseStudentGroups',
    description: 'Lists student groups in a course.',
    tool: listCourseStudentGroups,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['section'],
  },
  {
    name: 'googleClassroomCreateCourseAlias',
    description: 'Adds an alternative identifier to a course.',
    tool: createCourseAlias,
    requiredAuth: auth,
    scope: 'write' as const,
    keywords: ['code'],
  },
  {
    name: 'googleClassroomDeleteCourseAlias',
    description: 'Removes an alias from a course.',
    tool: deleteCourseAlias,
    requiredAuth: auth,
    scope: 'delete' as const,
    keywords: ['code', 'remove'],
  },
  {
    name: 'googleClassroomListCourseAliases',
    description: 'Lists all aliases for a course.',
    tool: listCourseAliases,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['code'],
  },
  {
    name: 'googleClassroomCreateAnnouncement',
    description: 'Creates a draft, published, or scheduled announcement.',
    tool: createAnnouncement,
    requiredAuth: auth,
    scope: 'write' as const,
    keywords: ['post', 'posts', 'notice'],
  },
  {
    name: 'googleClassroomDeleteAnnouncement',
    description: 'Deletes an announcement.',
    tool: deleteAnnouncement,
    requiredAuth: auth,
    scope: 'delete' as const,
    keywords: ['post', 'posts', 'remove'],
  },
  {
    name: 'googleClassroomGetAnnouncement',
    description: 'Fetches an announcement by course and announcement ID.',
    tool: getAnnouncement,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['post', 'posts'],
  },
  {
    name: 'googleClassroomListAnnouncements',
    description: 'Pages through course announcements.',
    tool: listAnnouncements,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['post', 'posts', 'feed'],
  },
  {
    name: 'googleClassroomModifyAnnouncementAssignees',
    description: 'Changes announcement visibility (all vs individual students).',
    tool: modifyAnnouncementAssignees,
    requiredAuth: auth,
    scope: 'write' as const,
    keywords: ['assign', 'post'],
  },
  {
    name: 'googleClassroomPatchAnnouncement',
    description: 'Updates announcement fields via updateMask.',
    tool: patchAnnouncement,
    requiredAuth: auth,
    scope: 'write' as const,
    keywords: ['post', 'posts'],
  },
  {
    name: 'googleClassroomGetAnnouncementAddOnContext',
    description: 'Gets add-on iframe metadata for an announcement.',
    tool: getAnnouncementAddOnContext,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: [],
  },
  {
    name: 'googleClassroomDeleteAnnouncementAddOnAttachment',
    description: 'Deletes an add-on attachment from an announcement.',
    tool: deleteAnnouncementAddOnAttachment,
    requiredAuth: auth,
    scope: 'delete' as const,
    keywords: [],
  },
  {
    name: 'googleClassroomGetAnnouncementAddOnAttachment',
    description: 'Gets an add-on attachment from an announcement.',
    tool: getAnnouncementAddOnAttachment,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: [],
  },
  {
    name: 'googleClassroomListAnnouncementAddOnAttachments',
    description: 'Lists add-on attachments on an announcement.',
    tool: listAnnouncementAddOnAttachments,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: [],
  },
  {
    name: 'googleClassroomCreateCourseWork',
    description: 'Creates an assignment or question, published, drafted, or scheduled.',
    tool: createCourseWork,
    requiredAuth: auth,
    scope: 'write' as const,
    keywords: ['assignment', 'assignments', 'homework'],
  },
  {
    name: 'googleClassroomDeleteCourseWork',
    description: 'Deletes coursework.',
    tool: deleteCourseWork,
    requiredAuth: auth,
    scope: 'delete' as const,
    keywords: ['assignment', 'assignments', 'remove'],
  },
  {
    name: 'googleClassroomGetCourseWork',
    description: 'Gets coursework details.',
    tool: getCourseWork,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['assignment', 'assignments'],
  },
  {
    name: 'googleClassroomListCourseWork',
    description: 'Lists coursework with state filter and ordering.',
    tool: listCourseWork,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['assignment', 'assignments', 'browse'],
  },
  {
    name: 'googleClassroomPatchCourseWork',
    description: 'Updates coursework fields via updateMask.',
    tool: patchCourseWork,
    requiredAuth: auth,
    scope: 'write' as const,
    keywords: ['assignment', 'assignments'],
  },
  {
    name: 'googleClassroomModifyCourseWorkAssignees',
    description: 'Changes coursework visibility (all vs individual students).',
    tool: modifyCourseWorkAssignees,
    requiredAuth: auth,
    scope: 'write' as const,
    keywords: ['assign', 'assignment'],
  },
  {
    name: 'googleClassroomListCourseWorkRubrics',
    description: 'Lists grading rubrics for coursework.',
    tool: listCourseWorkRubrics,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['grade', 'grades', 'criteria'],
  },
  {
    name: 'googleClassroomListStudentSubmissions',
    description: 'Lists submissions for coursework with student/state/lateness filters.',
    tool: listStudentSubmissions,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['grade', 'grades', 'turn-in'],
  },
  {
    name: 'googleClassroomReclaimStudentSubmission',
    description: 'Reclaims a turned-in submission for editing.',
    tool: reclaimStudentSubmission,
    requiredAuth: auth,
    scope: 'write' as const,
    keywords: ['return', 'unsubmit'],
  },
  {
    name: 'googleClassroomDeleteCourseWorkAddOnAttachment',
    description: 'Deletes an add-on attachment from coursework.',
    tool: deleteCourseWorkAddOnAttachment,
    requiredAuth: auth,
    scope: 'delete' as const,
    keywords: [],
  },
  {
    name: 'googleClassroomGetCourseWorkAddOnAttachment',
    description: 'Gets an add-on attachment from coursework.',
    tool: getCourseWorkAddOnAttachment,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: [],
  },
  {
    name: 'googleClassroomListCourseWorkAddOnAttachments',
    description: 'Lists add-on attachments on coursework.',
    tool: listCourseWorkAddOnAttachments,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: [],
  },
  {
    name: 'googleClassroomGetCourseWorkAddOnContext',
    description: 'Gets add-on iframe metadata for coursework.',
    tool: getCourseWorkAddOnContext,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: [],
  },
  {
    name: 'googleClassroomCreateCourseWorkMaterial',
    description: 'Creates a coursework material (resources/notes).',
    tool: createCourseWorkMaterial,
    requiredAuth: auth,
    scope: 'write' as const,
    keywords: ['handout', 'resource'],
  },
  {
    name: 'googleClassroomGetCourseWorkMaterial',
    description: 'Gets a coursework material.',
    tool: getCourseWorkMaterial,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['handout', 'resource'],
  },
  {
    name: 'googleClassroomListCourseWorkMaterials',
    description: 'Pages through coursework materials.',
    tool: listCourseWorkMaterials,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['handout', 'resource', 'resources', 'browse'],
  },
  {
    name: 'googleClassroomDeleteCourseWorkMaterial',
    description: 'Deletes a coursework material.',
    tool: deleteCourseWorkMaterial,
    requiredAuth: auth,
    scope: 'delete' as const,
    keywords: ['handout', 'remove'],
  },
  {
    name: 'googleClassroomPatchCourseWorkMaterial',
    description: 'Updates a coursework material via updateMask.',
    tool: patchCourseWorkMaterial,
    requiredAuth: auth,
    scope: 'write' as const,
    keywords: ['handout'],
  },
  {
    name: 'googleClassroomListCourseWorkMaterialAddOnAttachments',
    description: 'Lists add-on attachments on a coursework material.',
    tool: listCourseWorkMaterialAddOnAttachments,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: [],
  },
  {
    name: 'googleClassroomGetCourseWorkMaterialAddOnContext',
    description: 'Gets add-on iframe metadata for a coursework material.',
    tool: getCourseWorkMaterialAddOnContext,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: [],
  },
  {
    name: 'googleClassroomListPostAddOnAttachments',
    description: 'Lists add-on attachments on a post.',
    tool: listPostAddOnAttachments,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: [],
  },
  {
    name: 'googleClassroomGetPostAddOnContext',
    description: 'Gets add-on iframe metadata for a post.',
    tool: getPostAddOnContext,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: [],
  },
  {
    name: 'googleClassroomAddStudentToCourse',
    description: 'Enrolls a user as a student.',
    tool: addStudentToCourse,
    requiredAuth: auth,
    scope: 'write' as const,
    keywords: ['enroll', 'roster'],
  },
  {
    name: 'googleClassroomDeleteCourseStudent',
    description: 'Removes a student enrollment.',
    tool: deleteCourseStudent,
    requiredAuth: auth,
    scope: 'delete' as const,
    keywords: ['unenroll', 'remove', 'roster'],
  },
  {
    name: 'googleClassroomGetCourseStudent',
    description: 'Gets a student enrollment with profile details.',
    tool: getCourseStudent,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['roster'],
  },
  {
    name: 'googleClassroomListCourseStudents',
    description: 'Pages through enrolled students.',
    tool: listCourseStudents,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['roster', 'pupil'],
  },
  {
    name: 'googleClassroomListStudentGuardians',
    description: 'Lists guardians linked to a student.',
    tool: listStudentGuardians,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['parent', 'parents'],
  },
  {
    name: 'googleClassroomDeleteCourseTeacher',
    description: 'Removes a teacher enrollment.',
    tool: deleteCourseTeacher,
    requiredAuth: auth,
    scope: 'delete' as const,
    keywords: ['instructor', 'remove'],
  },
  {
    name: 'googleClassroomGetTeacher',
    description: 'Gets a teacher enrollment with profile details.',
    tool: getTeacher,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['instructor'],
  },
  {
    name: 'googleClassroomListCourseTeachers',
    description: 'Pages through enrolled teachers.',
    tool: listCourseTeachers,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['instructor'],
  },
  {
    name: 'googleClassroomCreateCourseTopic',
    description: 'Creates a topic section in a course.',
    tool: createCourseTopic,
    requiredAuth: auth,
    scope: 'write' as const,
    keywords: ['unit', 'units', 'module'],
  },
  {
    name: 'googleClassroomDeleteCourseTopic',
    description: 'Deletes a course topic.',
    tool: deleteCourseTopic,
    requiredAuth: auth,
    scope: 'delete' as const,
    keywords: ['unit', 'remove'],
  },
  {
    name: 'googleClassroomGetCourseTopic',
    description: 'Gets a course topic.',
    tool: getCourseTopic,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['unit'],
  },
  {
    name: 'googleClassroomListCourseTopics',
    description: 'Lists topics in a course.',
    tool: listCourseTopics,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['unit', 'units', 'browse'],
  },
  {
    name: 'googleClassroomPatchCourseTopic',
    description: 'Renames a course topic.',
    tool: patchCourseTopic,
    requiredAuth: auth,
    scope: 'write' as const,
    keywords: ['rename', 'unit'],
  },
  {
    name: 'googleClassroomCreateInvitation',
    description: 'Invites a user to a course as student or teacher.',
    tool: createInvitation,
    requiredAuth: auth,
    scope: 'write' as const,
    keywords: ['invite', 'invites', 'enroll'],
  },
  {
    name: 'googleClassroomDeleteInvitation',
    description: 'Deletes an invitation.',
    tool: deleteInvitation,
    requiredAuth: auth,
    scope: 'delete' as const,
    keywords: ['invite', 'revoke'],
  },
  {
    name: 'googleClassroomGetInvitation',
    description: 'Gets an invitation by ID.',
    tool: getInvitation,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['invite'],
  },
  {
    name: 'googleClassroomListInvitations',
    description: 'Lists invitations filtered by user and/or course.',
    tool: listInvitations,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['invite', 'invites'],
  },
  {
    name: 'googleClassroomCreateRegistration',
    description: 'Subscribes a Pub/Sub topic to Classroom push notifications.',
    tool: createRegistration,
    requiredAuth: auth,
    scope: 'write' as const,
    keywords: ['webhook', 'subscribe'],
  },
  {
    name: 'googleClassroomGetUserProfile',
    description: 'Gets a user profile by ID, email, or me.',
    tool: getUserProfile,
    requiredAuth: auth,
    scope: 'read' as const,
    keywords: ['account'],
  },
];
