// @ts-nocheck
import { createCourseAlias, deleteCourseAlias, listCourseAliases } from './aliases.js';
import {
    createAnnouncement,
    deleteAnnouncement,
    getAnnouncement,
    listAnnouncements,
    modifyAnnouncementAssignees,
    patchAnnouncement,
} from './announcements.js';
import {
    deleteAnnouncementAddOnAttachment,
    getAnnouncementAddOnAttachment,
    getAnnouncementAddOnContext,
    listAnnouncementAddOnAttachments,
} from './announcement-addons.js';
import {
    createCourse,
    deleteCourse,
    getCourse,
    getGradingPeriodSettings,
    listCourseStudentGroups,
    listCourses,
    patchCourse,
    updateCourse,
} from './courses.js';
import {
    createCourseWork,
    deleteCourseWork,
    getCourseWork,
    listCourseWork,
    listCourseWorkRubrics,
    listStudentSubmissions,
    modifyCourseWorkAssignees,
    patchCourseWork,
    reclaimStudentSubmission,
} from './coursework.js';
import {
    deleteCourseWorkAddOnAttachment,
    getCourseWorkAddOnAttachment,
    getCourseWorkAddOnContext,
    listCourseWorkAddOnAttachments,
} from './coursework-addons.js';
import { createInvitation, deleteInvitation, getInvitation, listInvitations } from './invitations.js';
import {
    createCourseWorkMaterial,
    deleteCourseWorkMaterial,
    getCourseWorkMaterial,
    listCourseWorkMaterials,
    patchCourseWorkMaterial,
} from './materials.js';
import {
    getCourseWorkMaterialAddOnContext,
    listCourseWorkMaterialAddOnAttachments,
} from './materials-addons.js';
import { createRegistration, getUserProfile } from './misc.js';
import { getPostAddOnContext, listPostAddOnAttachments } from './posts-addons.js';
import {
    addStudentToCourse,
    deleteCourseStudent,
    deleteCourseTeacher,
    getCourseStudent,
    getTeacher,
    listCourseStudents,
    listCourseTeachers,
    listStudentGuardians,
} from './roster.js';
import {
    createCourseTopic,
    deleteCourseTopic,
    getCourseTopic,
    listCourseTopics,
    patchCourseTopic,
} from './topics.js';

export {
    createCourseAlias,
    deleteCourseAlias,
    listCourseAliases,
    createAnnouncement,
    deleteAnnouncement,
    getAnnouncement,
    listAnnouncements,
    modifyAnnouncementAssignees,
    patchAnnouncement,
    deleteAnnouncementAddOnAttachment,
    getAnnouncementAddOnAttachment,
    getAnnouncementAddOnContext,
    listAnnouncementAddOnAttachments,
    createCourse,
    deleteCourse,
    getCourse,
    getGradingPeriodSettings,
    listCourseStudentGroups,
    listCourses,
    patchCourse,
    updateCourse,
    createCourseWork,
    deleteCourseWork,
    getCourseWork,
    listCourseWork,
    listCourseWorkRubrics,
    listStudentSubmissions,
    modifyCourseWorkAssignees,
    patchCourseWork,
    reclaimStudentSubmission,
    deleteCourseWorkAddOnAttachment,
    getCourseWorkAddOnAttachment,
    getCourseWorkAddOnContext,
    listCourseWorkAddOnAttachments,
    createInvitation,
    deleteInvitation,
    getInvitation,
    listInvitations,
    createCourseWorkMaterial,
    deleteCourseWorkMaterial,
    getCourseWorkMaterial,
    listCourseWorkMaterials,
    patchCourseWorkMaterial,
    getCourseWorkMaterialAddOnContext,
    listCourseWorkMaterialAddOnAttachments,
    createRegistration,
    getUserProfile,
    getPostAddOnContext,
    listPostAddOnAttachments,
    addStudentToCourse,
    deleteCourseStudent,
    deleteCourseTeacher,
    getCourseStudent,
    getTeacher,
    listCourseStudents,
    listCourseTeachers,
    listStudentGuardians,
    createCourseTopic,
    deleteCourseTopic,
    getCourseTopic,
    listCourseTopics,
    patchCourseTopic,
};

const auth = 'googleClassroomToken' as const;

export const googleClassroomTools = [
    { name: 'googleClassroomCreateCourse', description: 'Creates a course before enrollment.', tool: createCourse, requiredAuth: auth, scope: 'write' as const },
    { name: 'googleClassroomDeleteCourse', description: 'Deletes a course. Confirm the ID first.', tool: deleteCourse, requiredAuth: auth, scope: 'delete' as const },
    { name: 'googleClassroomGetCourse', description: 'Gets full course details by ID or alias.', tool: getCourse, requiredAuth: auth, scope: 'read' as const },
    { name: 'googleClassroomListCourses', description: 'Lists your courses with filters and pagination.', tool: listCourses, requiredAuth: auth, scope: 'read' as const },
    { name: 'googleClassroomPatchCourse', description: 'Partially updates a course via updateMask.', tool: patchCourse, requiredAuth: auth, scope: 'write' as const },
    { name: 'googleClassroomUpdateCourse', description: 'Fully replaces a course (PUT).', tool: updateCourse, requiredAuth: auth, scope: 'write' as const },
    { name: 'googleClassroomGetGradingPeriodSettings', description: 'Gets grading periods configured for a course.', tool: getGradingPeriodSettings, requiredAuth: auth, scope: 'read' as const },
    { name: 'googleClassroomListCourseStudentGroups', description: 'Lists student groups in a course.', tool: listCourseStudentGroups, requiredAuth: auth, scope: 'read' as const },
    { name: 'googleClassroomCreateCourseAlias', description: 'Adds an alternative identifier to a course.', tool: createCourseAlias, requiredAuth: auth, scope: 'write' as const },
    { name: 'googleClassroomDeleteCourseAlias', description: 'Removes an alias from a course.', tool: deleteCourseAlias, requiredAuth: auth, scope: 'delete' as const },
    { name: 'googleClassroomListCourseAliases', description: 'Lists all aliases for a course.', tool: listCourseAliases, requiredAuth: auth, scope: 'read' as const },
    { name: 'googleClassroomCreateAnnouncement', description: 'Creates a draft, published, or scheduled announcement.', tool: createAnnouncement, requiredAuth: auth, scope: 'write' as const },
    { name: 'googleClassroomDeleteAnnouncement', description: 'Deletes an announcement.', tool: deleteAnnouncement, requiredAuth: auth, scope: 'delete' as const },
    { name: 'googleClassroomGetAnnouncement', description: 'Fetches an announcement by course and announcement ID.', tool: getAnnouncement, requiredAuth: auth, scope: 'read' as const },
    { name: 'googleClassroomListAnnouncements', description: 'Pages through course announcements.', tool: listAnnouncements, requiredAuth: auth, scope: 'read' as const },
    { name: 'googleClassroomModifyAnnouncementAssignees', description: 'Changes announcement visibility (all vs individual students).', tool: modifyAnnouncementAssignees, requiredAuth: auth, scope: 'write' as const },
    { name: 'googleClassroomPatchAnnouncement', description: 'Updates announcement fields via updateMask.', tool: patchAnnouncement, requiredAuth: auth, scope: 'write' as const },
    { name: 'googleClassroomGetAnnouncementAddOnContext', description: 'Gets add-on iframe metadata for an announcement.', tool: getAnnouncementAddOnContext, requiredAuth: auth, scope: 'read' as const },
    { name: 'googleClassroomDeleteAnnouncementAddOnAttachment', description: 'Deletes an add-on attachment from an announcement.', tool: deleteAnnouncementAddOnAttachment, requiredAuth: auth, scope: 'delete' as const },
    { name: 'googleClassroomGetAnnouncementAddOnAttachment', description: 'Gets an add-on attachment from an announcement.', tool: getAnnouncementAddOnAttachment, requiredAuth: auth, scope: 'read' as const },
    { name: 'googleClassroomListAnnouncementAddOnAttachments', description: 'Lists add-on attachments on an announcement.', tool: listAnnouncementAddOnAttachments, requiredAuth: auth, scope: 'read' as const },
    { name: 'googleClassroomCreateCourseWork', description: 'Creates an assignment or question, published, drafted, or scheduled.', tool: createCourseWork, requiredAuth: auth, scope: 'write' as const },
    { name: 'googleClassroomDeleteCourseWork', description: 'Deletes coursework.', tool: deleteCourseWork, requiredAuth: auth, scope: 'delete' as const },
    { name: 'googleClassroomGetCourseWork', description: 'Gets coursework details.', tool: getCourseWork, requiredAuth: auth, scope: 'read' as const },
    { name: 'googleClassroomListCourseWork', description: 'Lists coursework with state filter and ordering.', tool: listCourseWork, requiredAuth: auth, scope: 'read' as const },
    { name: 'googleClassroomPatchCourseWork', description: 'Updates coursework fields via updateMask.', tool: patchCourseWork, requiredAuth: auth, scope: 'write' as const },
    { name: 'googleClassroomModifyCourseWorkAssignees', description: 'Changes coursework visibility (all vs individual students).', tool: modifyCourseWorkAssignees, requiredAuth: auth, scope: 'write' as const },
    { name: 'googleClassroomListCourseWorkRubrics', description: 'Lists grading rubrics for coursework.', tool: listCourseWorkRubrics, requiredAuth: auth, scope: 'read' as const },
    { name: 'googleClassroomListStudentSubmissions', description: 'Lists submissions for coursework with student/state/lateness filters.', tool: listStudentSubmissions, requiredAuth: auth, scope: 'read' as const },
    { name: 'googleClassroomReclaimStudentSubmission', description: 'Reclaims a turned-in submission for editing.', tool: reclaimStudentSubmission, requiredAuth: auth, scope: 'write' as const },
    { name: 'googleClassroomDeleteCourseWorkAddOnAttachment', description: 'Deletes an add-on attachment from coursework.', tool: deleteCourseWorkAddOnAttachment, requiredAuth: auth, scope: 'delete' as const },
    { name: 'googleClassroomGetCourseWorkAddOnAttachment', description: 'Gets an add-on attachment from coursework.', tool: getCourseWorkAddOnAttachment, requiredAuth: auth, scope: 'read' as const },
    { name: 'googleClassroomListCourseWorkAddOnAttachments', description: 'Lists add-on attachments on coursework.', tool: listCourseWorkAddOnAttachments, requiredAuth: auth, scope: 'read' as const },
    { name: 'googleClassroomGetCourseWorkAddOnContext', description: 'Gets add-on iframe metadata for coursework.', tool: getCourseWorkAddOnContext, requiredAuth: auth, scope: 'read' as const },
    { name: 'googleClassroomCreateCourseWorkMaterial', description: 'Creates a coursework material (resources/notes).', tool: createCourseWorkMaterial, requiredAuth: auth, scope: 'write' as const },
    { name: 'googleClassroomGetCourseWorkMaterial', description: 'Gets a coursework material.', tool: getCourseWorkMaterial, requiredAuth: auth, scope: 'read' as const },
    { name: 'googleClassroomListCourseWorkMaterials', description: 'Pages through coursework materials.', tool: listCourseWorkMaterials, requiredAuth: auth, scope: 'read' as const },
    { name: 'googleClassroomDeleteCourseWorkMaterial', description: 'Deletes a coursework material.', tool: deleteCourseWorkMaterial, requiredAuth: auth, scope: 'delete' as const },
    { name: 'googleClassroomPatchCourseWorkMaterial', description: 'Updates a coursework material via updateMask.', tool: patchCourseWorkMaterial, requiredAuth: auth, scope: 'write' as const },
    { name: 'googleClassroomListCourseWorkMaterialAddOnAttachments', description: 'Lists add-on attachments on a coursework material.', tool: listCourseWorkMaterialAddOnAttachments, requiredAuth: auth, scope: 'read' as const },
    { name: 'googleClassroomGetCourseWorkMaterialAddOnContext', description: 'Gets add-on iframe metadata for a coursework material.', tool: getCourseWorkMaterialAddOnContext, requiredAuth: auth, scope: 'read' as const },
    { name: 'googleClassroomListPostAddOnAttachments', description: 'Lists add-on attachments on a post.', tool: listPostAddOnAttachments, requiredAuth: auth, scope: 'read' as const },
    { name: 'googleClassroomGetPostAddOnContext', description: 'Gets add-on iframe metadata for a post.', tool: getPostAddOnContext, requiredAuth: auth, scope: 'read' as const },
    { name: 'googleClassroomAddStudentToCourse', description: 'Enrolls a user as a student.', tool: addStudentToCourse, requiredAuth: auth, scope: 'write' as const },
    { name: 'googleClassroomDeleteCourseStudent', description: 'Removes a student enrollment.', tool: deleteCourseStudent, requiredAuth: auth, scope: 'delete' as const },
    { name: 'googleClassroomGetCourseStudent', description: 'Gets a student enrollment with profile details.', tool: getCourseStudent, requiredAuth: auth, scope: 'read' as const },
    { name: 'googleClassroomListCourseStudents', description: 'Pages through enrolled students.', tool: listCourseStudents, requiredAuth: auth, scope: 'read' as const },
    { name: 'googleClassroomListStudentGuardians', description: 'Lists guardians linked to a student.', tool: listStudentGuardians, requiredAuth: auth, scope: 'read' as const },
    { name: 'googleClassroomDeleteCourseTeacher', description: 'Removes a teacher enrollment.', tool: deleteCourseTeacher, requiredAuth: auth, scope: 'delete' as const },
    { name: 'googleClassroomGetTeacher', description: 'Gets a teacher enrollment with profile details.', tool: getTeacher, requiredAuth: auth, scope: 'read' as const },
    { name: 'googleClassroomListCourseTeachers', description: 'Pages through enrolled teachers.', tool: listCourseTeachers, requiredAuth: auth, scope: 'read' as const },
    { name: 'googleClassroomCreateCourseTopic', description: 'Creates a topic section in a course.', tool: createCourseTopic, requiredAuth: auth, scope: 'write' as const },
    { name: 'googleClassroomDeleteCourseTopic', description: 'Deletes a course topic.', tool: deleteCourseTopic, requiredAuth: auth, scope: 'delete' as const },
    { name: 'googleClassroomGetCourseTopic', description: 'Gets a course topic.', tool: getCourseTopic, requiredAuth: auth, scope: 'read' as const },
    { name: 'googleClassroomListCourseTopics', description: 'Lists topics in a course.', tool: listCourseTopics, requiredAuth: auth, scope: 'read' as const },
    { name: 'googleClassroomPatchCourseTopic', description: 'Renames a course topic.', tool: patchCourseTopic, requiredAuth: auth, scope: 'write' as const },
    { name: 'googleClassroomCreateInvitation', description: 'Invites a user to a course as student or teacher.', tool: createInvitation, requiredAuth: auth, scope: 'write' as const },
    { name: 'googleClassroomDeleteInvitation', description: 'Deletes an invitation.', tool: deleteInvitation, requiredAuth: auth, scope: 'delete' as const },
    { name: 'googleClassroomGetInvitation', description: 'Gets an invitation by ID.', tool: getInvitation, requiredAuth: auth, scope: 'read' as const },
    { name: 'googleClassroomListInvitations', description: 'Lists invitations filtered by user and/or course.', tool: listInvitations, requiredAuth: auth, scope: 'read' as const },
    { name: 'googleClassroomCreateRegistration', description: 'Subscribes a Pub/Sub topic to Classroom push notifications.', tool: createRegistration, requiredAuth: auth, scope: 'write' as const },
    { name: 'googleClassroomGetUserProfile', description: 'Gets a user profile by ID, email, or me.', tool: getUserProfile, requiredAuth: auth, scope: 'read' as const },
];
