// @ts-nocheck
import {
  createOrganization,
  deleteOrganization,
  getOrganization,
  getOrganizationEntitlements,
  listOrganizations,
  updateOrganization,
} from './organizations.js';
import {
  createProject,
  deleteProject,
  getProject,
  listProjects,
  updateProject,
} from './projects.js';
import {
  createWorkspace,
  deleteWorkspace,
  forceUnlockWorkspace,
  getWorkspace,
  getWorkspaceByName,
  listWorkspaceRuns,
  listWorkspaces,
  lockWorkspace,
  safeDeleteWorkspace,
  unlockWorkspace,
  updateWorkspace,
} from './workspaces.js';
import {
  applyRun,
  cancelRun,
  createRun,
  discardRun,
  forceCancelRun,
  forceExecuteRun,
  getRun,
  listOrganizationRuns,
} from './runs.js';
import { getApply, getCostEstimate, getPlan, getPlanJsonOutput } from './plans.js';
import {
  createStateVersion,
  getCurrentStateVersion,
  getCurrentStateVersionOutputs,
  getStateVersion,
  getStateVersionOutputs,
  listStateVersions,
} from './state.js';
import {
  createConfigurationVersion,
  getConfigurationVersion,
  uploadConfigurationVersion,
} from './configurations.js';
import {
  createVariable,
  deleteVariable,
  getVariable,
  listVariables,
  updateVariable,
} from './variables.js';
import {
  attachVariableSetWorkspaces,
  createVariableSet,
  deleteVariableSet,
  detachVariableSetWorkspaces,
  getVariableSet,
  listVariableSetVars,
  listVariableSets,
  updateVariableSet,
} from './variableSets.js';
import {
  createTeam,
  createTeamToken,
  deleteTeam,
  deleteTeamToken,
  getTeam,
  getTeamToken,
  listTeamTokens,
  listTeams,
  updateTeam,
} from './teams.js';
import {
  createTeamAccess,
  deleteTeamAccess,
  getTeamAccess,
  listTeamAccess,
  updateTeamAccess,
} from './access.js';
import {
  createPolicy,
  createPolicySet,
  deletePolicy,
  deletePolicySet,
  getPolicy,
  getPolicyCheck,
  getPolicySet,
  listPolicies,
  listPolicySets,
  overridePolicyCheck,
  updatePolicy,
  updatePolicySet,
} from './policies.js';
import { deleteRegistryModuleVersion, getRegistryModule, listRegistryModules } from './registry.js';
import {
  createNotificationConfig,
  createRunTrigger,
  deleteNotificationConfig,
  deleteRunTrigger,
  getAgentPool,
  getNotificationConfig,
  getOAuthClient,
  getRunTrigger,
  listAgentPools,
  listNotificationConfigs,
  listOAuthClients,
  listRunTriggers,
  updateNotificationConfig,
  verifyNotificationConfig,
} from './integrations.js';

export {
  listOrganizations,
  getOrganization,
  createOrganization,
  updateOrganization,
  deleteOrganization,
  getOrganizationEntitlements,
  listProjects,
  getProject,
  createProject,
  updateProject,
  deleteProject,
  listWorkspaces,
  getWorkspace,
  getWorkspaceByName,
  createWorkspace,
  updateWorkspace,
  deleteWorkspace,
  safeDeleteWorkspace,
  lockWorkspace,
  unlockWorkspace,
  forceUnlockWorkspace,
  listWorkspaceRuns,
  createRun,
  getRun,
  listOrganizationRuns,
  applyRun,
  discardRun,
  cancelRun,
  forceCancelRun,
  forceExecuteRun,
  getPlan,
  getPlanJsonOutput,
  getApply,
  getCostEstimate,
  listStateVersions,
  getStateVersion,
  getCurrentStateVersion,
  getCurrentStateVersionOutputs,
  getStateVersionOutputs,
  createStateVersion,
  createConfigurationVersion,
  getConfigurationVersion,
  uploadConfigurationVersion,
  listVariables,
  createVariable,
  getVariable,
  updateVariable,
  deleteVariable,
  listVariableSets,
  getVariableSet,
  createVariableSet,
  updateVariableSet,
  deleteVariableSet,
  listVariableSetVars,
  attachVariableSetWorkspaces,
  detachVariableSetWorkspaces,
  listTeams,
  getTeam,
  createTeam,
  updateTeam,
  deleteTeam,
  listTeamTokens,
  getTeamToken,
  createTeamToken,
  deleteTeamToken,
  listTeamAccess,
  getTeamAccess,
  createTeamAccess,
  updateTeamAccess,
  deleteTeamAccess,
  listPolicies,
  getPolicy,
  createPolicy,
  updatePolicy,
  deletePolicy,
  listPolicySets,
  getPolicySet,
  createPolicySet,
  updatePolicySet,
  deletePolicySet,
  getPolicyCheck,
  overridePolicyCheck,
  listRegistryModules,
  getRegistryModule,
  deleteRegistryModuleVersion,
  listAgentPools,
  getAgentPool,
  listOAuthClients,
  getOAuthClient,
  listNotificationConfigs,
  getNotificationConfig,
  createNotificationConfig,
  updateNotificationConfig,
  deleteNotificationConfig,
  verifyNotificationConfig,
  listRunTriggers,
  getRunTrigger,
  createRunTrigger,
  deleteRunTrigger,
};

const auth = 'terraformToken' as const;

type Scope = 'read' | 'write' | 'delete';
function entry(
  name: string,
  description: string,
  toolRef: any,
  scope: Scope,
  keywords: string[],
): {
  name: string;
  description: string;
  tool: any;
  requiredAuth: typeof auth;
  scope: Scope;
  keywords: string[];
} {
  return { name, description, tool: toolRef, requiredAuth: auth, scope, keywords };
}

export const terraformTools = [
  entry(
    'terraformListOrganizations',
    'List HCP Terraform organizations visible to the token.',
    listOrganizations,
    'read',
    ['orgs', 'accounts'],
  ),
  entry(
    'terraformGetOrganization',
    'Get an organization with permissions, plan, and feature flags.',
    getOrganization,
    'read',
    ['org details', 'org settings'],
  ),
  entry(
    'terraformCreateOrganization',
    'Create a new HCP Terraform organization with an owner email.',
    createOrganization,
    'write',
    ['new org', 'org signup'],
  ),
  entry(
    'terraformUpdateOrganization',
    'Update organization settings such as name, email, or execution mode defaults.',
    updateOrganization,
    'write',
    ['rename org', 'org config'],
  ),
  entry(
    'terraformDeleteOrganization',
    'Permanently delete an organization and everything in it.',
    deleteOrganization,
    'delete',
    ['remove org', 'destroy org'],
  ),
  entry(
    'terraformGetOrganizationEntitlements',
    'Get organization feature entitlements (agents, SSO, Sentinel, limits).',
    getOrganizationEntitlements,
    'read',
    ['features', 'plan limits', 'tiers'],
  ),
  entry(
    'terraformListProjects',
    'List projects in an organization. Projects group workspaces for access scoping.',
    listProjects,
    'read',
    ['project list'],
  ),
  entry(
    'terraformGetProject',
    'Get a project by ID with workspace/team counts and permissions.',
    getProject,
    'read',
    ['project details'],
  ),
  entry(
    'terraformCreateProject',
    'Create a project in an organization to group workspaces.',
    createProject,
    'write',
    ['new project'],
  ),
  entry('terraformUpdateProject', 'Update a project name or description.', updateProject, 'write', [
    'rename project',
    'edit project',
  ]),
  entry('terraformDeleteProject', 'Delete an empty project.', deleteProject, 'delete', [
    'remove project',
  ]),
  entry(
    'terraformListWorkspaces',
    'List workspaces in an organization with lock state and run status.',
    listWorkspaces,
    'read',
    ['workspaces list', 'all workspaces'],
  ),
  entry(
    'terraformGetWorkspace',
    'Get a workspace by ID with settings, permissions, and current run.',
    getWorkspace,
    'read',
    ['workspace details', 'ws info'],
  ),
  entry(
    'terraformGetWorkspaceByName',
    'Get a workspace by organization and name (human-friendly lookup).',
    getWorkspaceByName,
    'read',
    ['find workspace', 'lookup workspace'],
  ),
  entry(
    'terraformCreateWorkspace',
    'Create a workspace with execution settings, optionally in a project.',
    createWorkspace,
    'write',
    ['new workspace', 'provision workspace'],
  ),
  entry(
    'terraformUpdateWorkspace',
    'Update workspace settings such as auto-apply, execution mode, or Terraform version.',
    updateWorkspace,
    'write',
    ['edit workspace', 'workspace config', 'rename workspace'],
  ),
  entry(
    'terraformDeleteWorkspace',
    'Delete a workspace and its runs, state, and variables.',
    deleteWorkspace,
    'delete',
    ['remove workspace', 'destroy workspace'],
  ),
  entry(
    'terraformSafeDeleteWorkspace',
    'Safely delete a workspace only if it has no managed resources.',
    safeDeleteWorkspace,
    'delete',
    ['safe destroy', 'empty workspace'],
  ),
  entry(
    'terraformLockWorkspace',
    'Lock a workspace to prevent new runs, with an explanatory reason.',
    lockWorkspace,
    'write',
    ['freeze workspace', 'pause runs'],
  ),
  entry(
    'terraformUnlockWorkspace',
    'Unlock a workspace so runs can be queued again.',
    unlockWorkspace,
    'write',
    ['unfreeze workspace', 'resume runs'],
  ),
  entry(
    'terraformForceUnlockWorkspace',
    'Force-unlock a workspace stuck locked by a crashed run.',
    forceUnlockWorkspace,
    'write',
    ['stuck lock', 'break lock'],
  ),
  entry(
    'terraformListWorkspaceRuns',
    'List runs in a workspace with status/operation filters.',
    listWorkspaceRuns,
    'read',
    ['run history', 'workspace runs list'],
  ),
  entry(
    'terraformCreateRun',
    'Queue a plan/apply run in a workspace (or destroy/refresh-only/plan-only).',
    createRun,
    'write',
    ['trigger run', 'queue plan', 'start apply', 'new run'],
  ),
  entry(
    'terraformGetRun',
    'Get run details: status, plan/apply state, permissions, timestamps.',
    getRun,
    'read',
    ['run status', 'run details', 'check run'],
  ),
  entry(
    'terraformListOrganizationRuns',
    'List runs across an organization with status and workspace filters.',
    listOrganizationRuns,
    'read',
    ['all runs', 'org runs', 'recent runs'],
  ),
  entry(
    'terraformApplyRun',
    'Confirm and apply a run paused for confirmation.',
    applyRun,
    'write',
    ['approve run', 'confirm apply'],
  ),
  entry(
    'terraformDiscardRun',
    'Discard a run waiting for confirmation so later runs can proceed.',
    discardRun,
    'write',
    ['cancel confirmation', 'skip run'],
  ),
  entry('terraformCancelRun', 'Gracefully cancel a planning or applying run.', cancelRun, 'write', [
    'stop run',
    'abort run',
  ]),
  entry(
    'terraformForceCancelRun',
    'Immediately terminate a run and unlock the workspace.',
    forceCancelRun,
    'write',
    ['kill run', 'force stop'],
  ),
  entry(
    'terraformForceExecuteRun',
    'Execute a pending run now, discarding blocking prior runs.',
    forceExecuteRun,
    'write',
    ['run now', 'prioritize run'],
  ),
  entry(
    'terraformGetPlan',
    'Get a plan with resource change summary and status.',
    getPlan,
    'read',
    ['plan details', 'changeset'],
  ),
  entry(
    'terraformGetPlanJsonOutput',
    'Download the machine-readable JSON output of a plan.',
    getPlanJsonOutput,
    'read',
    ['plan json', 'structured plan'],
  ),
  entry(
    'terraformGetApply',
    'Get an apply with status, timestamps, and log readout URL.',
    getApply,
    'read',
    ['apply status', 'apply details'],
  ),
  entry(
    'terraformGetCostEstimate',
    'Get a run cost estimate with proposed monthly cost delta.',
    getCostEstimate,
    'read',
    ['costs', 'pricing estimate', 'infracost'],
  ),
  entry(
    'terraformListStateVersions',
    'List state versions of a workspace, newest first.',
    listStateVersions,
    'read',
    ['state history', 'tfstate versions'],
  ),
  entry(
    'terraformGetStateVersion',
    'Get a state version by ID with download URL and lineage.',
    getStateVersion,
    'read',
    ['state details'],
  ),
  entry(
    'terraformGetCurrentStateVersion',
    "Get the workspace's current state version.",
    getCurrentStateVersion,
    'read',
    ['latest state', 'current tfstate'],
  ),
  entry(
    'terraformGetCurrentStateVersionOutputs',
    "Get output values of the workspace's current state.",
    getCurrentStateVersionOutputs,
    'read',
    ['outputs', 'output values', 'tf outputs'],
  ),
  entry(
    'terraformGetStateVersionOutputs',
    'Get output values of a specific state version.',
    getStateVersionOutputs,
    'read',
    ['historic outputs'],
  ),
  entry(
    'terraformCreateStateVersion',
    'Upload a new state version for local-execution workspaces.',
    createStateVersion,
    'write',
    ['push state', 'upload tfstate'],
  ),
  entry(
    'terraformCreateConfigurationVersion',
    'Create a configuration version on a workspace (API-driven run step 1).',
    createConfigurationVersion,
    'write',
    ['new config version', 'upload slot'],
  ),
  entry(
    'terraformGetConfigurationVersion',
    'Get a configuration version with source and upload status.',
    getConfigurationVersion,
    'read',
    ['config details'],
  ),
  entry(
    'terraformUploadConfigurationVersion',
    'Upload a .tar.gz configuration bundle to a configuration version.',
    uploadConfigurationVersion,
    'write',
    ['push code', 'upload bundle', 'tarball'],
  ),
  entry('terraformListVariables', 'List variables for a workspace.', listVariables, 'read', [
    'vars',
    'env vars',
    'tfvars',
  ]),
  entry(
    'terraformCreateVariable',
    'Create a Terraform or environment variable on a workspace.',
    createVariable,
    'write',
    ['new var', 'add secret', 'set variable'],
  ),
  entry(
    'terraformGetVariable',
    'Get a variable by ID (sensitive values never returned).',
    getVariable,
    'read',
    ['var details'],
  ),
  entry(
    'terraformUpdateVariable',
    'Update a variable key, value, description, or flags.',
    updateVariable,
    'write',
    ['edit var', 'rotate secret'],
  ),
  entry(
    'terraformDeleteVariable',
    'Delete a variable from a workspace.',
    deleteVariable,
    'delete',
    ['remove var'],
  ),
  entry(
    'terraformListVariableSets',
    'List variable sets for sharing variables across workspaces.',
    listVariableSets,
    'read',
    ['varsets', 'shared vars'],
  ),
  entry(
    'terraformGetVariableSet',
    'Get a variable set by ID with scope and attachments.',
    getVariableSet,
    'read',
    ['varset details'],
  ),
  entry(
    'terraformCreateVariableSet',
    'Create a variable set scoped globally, to projects, or workspaces.',
    createVariableSet,
    'write',
    ['new varset', 'shared credentials'],
  ),
  entry(
    'terraformUpdateVariableSet',
    'Update a variable set name, description, scope, or priority.',
    updateVariableSet,
    'write',
    ['edit varset'],
  ),
  entry(
    'terraformDeleteVariableSet',
    'Delete a variable set and its variables.',
    deleteVariableSet,
    'delete',
    ['remove varset'],
  ),
  entry(
    'terraformListVariableSetVars',
    'List variables inside a variable set.',
    listVariableSetVars,
    'read',
    ['varset contents'],
  ),
  entry(
    'terraformAttachVariableSetWorkspaces',
    'Attach a variable set to workspaces.',
    attachVariableSetWorkspaces,
    'write',
    ['link varset', 'assign varset'],
  ),
  entry(
    'terraformDetachVariableSetWorkspaces',
    'Detach a variable set from workspaces.',
    detachVariableSetWorkspaces,
    'write',
    ['unlink varset'],
  ),
  entry(
    'terraformListTeams',
    'List teams in an organization with member counts.',
    listTeams,
    'read',
    ['team list', 'groups'],
  ),
  entry(
    'terraformGetTeam',
    'Get a team by ID with permissions and member count.',
    getTeam,
    'read',
    ['team details'],
  ),
  entry(
    'terraformCreateTeam',
    'Create a team with organization-level permissions.',
    createTeam,
    'write',
    ['new team'],
  ),
  entry(
    'terraformUpdateTeam',
    'Update team name, visibility, or organization permissions.',
    updateTeam,
    'write',
    ['edit team', 'rename team'],
  ),
  entry(
    'terraformDeleteTeam',
    'Delete a team (workspace access through it is revoked).',
    deleteTeam,
    'delete',
    ['remove team'],
  ),
  entry(
    'terraformListTeamTokens',
    'List team API tokens in an organization (metadata only).',
    listTeamTokens,
    'read',
    ['tokens list', 'api tokens'],
  ),
  entry(
    'terraformGetTeamToken',
    'Get team token metadata by token ID (secret never returned).',
    getTeamToken,
    'read',
    ['token details'],
  ),
  entry(
    'terraformCreateTeamToken',
    'Generate a team API token. Secret returned once — store immediately.',
    createTeamToken,
    'write',
    ['new token', 'generate token', 'ci token'],
  ),
  entry(
    'terraformDeleteTeamToken',
    'Revoke a team API token by token ID.',
    deleteTeamToken,
    'delete',
    ['revoke token', 'remove token'],
  ),
  entry(
    'terraformListTeamAccess',
    'List team-to-workspace access grants.',
    listTeamAccess,
    'read',
    ['permissions list', 'access grants', 'team workspaces'],
  ),
  entry('terraformGetTeamAccess', 'Get one team access grant by ID.', getTeamAccess, 'read', [
    'grant details',
  ]),
  entry(
    'terraformCreateTeamAccess',
    'Grant a team access to a workspace (fixed or custom permissions).',
    createTeamAccess,
    'write',
    ['grant access', 'share workspace'],
  ),
  entry(
    'terraformUpdateTeamAccess',
    'Change the permission level of a team access grant.',
    updateTeamAccess,
    'write',
    ['edit grant', 'change access'],
  ),
  entry(
    'terraformDeleteTeamAccess',
    'Revoke a team access grant from a workspace.',
    deleteTeamAccess,
    'delete',
    ['remove grant', 'unshare workspace'],
  ),
  entry(
    'terraformListPolicies',
    'List Sentinel policies in an organization.',
    listPolicies,
    'read',
    ['sentinel list', 'policy list'],
  ),
  entry(
    'terraformGetPolicy',
    'Get a Sentinel policy by ID with enforcement mode.',
    getPolicy,
    'read',
    ['policy details', 'sentinel details'],
  ),
  entry(
    'terraformCreatePolicy',
    'Create a Sentinel policy (code uploaded separately).',
    createPolicy,
    'write',
    ['new policy', 'add guardrail'],
  ),
  entry(
    'terraformUpdatePolicy',
    'Update a Sentinel policy name, description, or enforcement.',
    updatePolicy,
    'write',
    ['edit policy'],
  ),
  entry('terraformDeletePolicy', 'Delete a Sentinel policy.', deletePolicy, 'delete', [
    'remove policy',
  ]),
  entry(
    'terraformListPolicySets',
    'List policy sets with workspace attachments.',
    listPolicySets,
    'read',
    ['policyset list', 'sentinel sets'],
  ),
  entry(
    'terraformGetPolicySet',
    'Get a policy set by ID with policies and VCS settings.',
    getPolicySet,
    'read',
    ['policyset details'],
  ),
  entry(
    'terraformCreatePolicySet',
    'Create a policy set, optionally attached to workspaces.',
    createPolicySet,
    'write',
    ['new policyset'],
  ),
  entry(
    'terraformUpdatePolicySet',
    'Update a policy set name, description, scope, or attachments.',
    updatePolicySet,
    'write',
    ['edit policyset'],
  ),
  entry('terraformDeletePolicySet', 'Delete a policy set.', deletePolicySet, 'delete', [
    'remove policyset',
  ]),
  entry('terraformGetPolicyCheck', 'Get a policy check result for a run.', getPolicyCheck, 'read', [
    'check result',
    'sentinel result',
  ]),
  entry(
    'terraformOverridePolicyCheck',
    'Override soft-failed policies so the run can be applied.',
    overridePolicyCheck,
    'write',
    ['approve policies', 'bypass guardrail'],
  ),
  entry(
    'terraformListRegistryModules',
    'List private registry modules with versions.',
    listRegistryModules,
    'read',
    ['modules list', 'private modules'],
  ),
  entry(
    'terraformGetRegistryModule',
    'Get a registry module with versions and VCS repo.',
    getRegistryModule,
    'read',
    ['module details'],
  ),
  entry(
    'terraformDeleteRegistryModuleVersion',
    'Delete one version of a private registry module.',
    deleteRegistryModuleVersion,
    'delete',
    ['remove module version', 'unpublish'],
  ),
  entry(
    'terraformListAgentPools',
    'List agent pools for remote execution via agents.',
    listAgentPools,
    'read',
    ['agents list', 'pools'],
  ),
  entry('terraformGetAgentPool', 'Get an agent pool by ID.', getAgentPool, 'read', [
    'pool details',
    'agent details',
  ]),
  entry(
    'terraformListOAuthClients',
    'List VCS OAuth clients (GitHub, GitLab, Bitbucket, Azure DevOps).',
    listOAuthClients,
    'read',
    ['vcs connections', 'git connections'],
  ),
  entry('terraformGetOAuthClient', 'Get a VCS OAuth client by ID.', getOAuthClient, 'read', [
    'vcs details',
  ]),
  entry(
    'terraformListNotificationConfigs',
    'List notification configurations on a workspace.',
    listNotificationConfigs,
    'read',
    ['webhooks list', 'alerts list', 'slack config'],
  ),
  entry(
    'terraformGetNotificationConfig',
    'Get a notification configuration by ID.',
    getNotificationConfig,
    'read',
    ['webhook details', 'alert details'],
  ),
  entry(
    'terraformCreateNotificationConfig',
    'Create a workspace notification for run events.',
    createNotificationConfig,
    'write',
    ['new webhook', 'add alert', 'slack alerts'],
  ),
  entry(
    'terraformUpdateNotificationConfig',
    'Update a notification configuration.',
    updateNotificationConfig,
    'write',
    ['edit webhook', 'edit alert'],
  ),
  entry(
    'terraformDeleteNotificationConfig',
    'Delete a notification configuration.',
    deleteNotificationConfig,
    'delete',
    ['remove webhook', 'remove alert'],
  ),
  entry(
    'terraformVerifyNotificationConfig',
    'Send a test notification to verify delivery.',
    verifyNotificationConfig,
    'write',
    ['test webhook', 'test alert'],
  ),
  entry(
    'terraformListRunTriggers',
    'List run triggers that queue runs when a source workspace applies.',
    listRunTriggers,
    'read',
    ['triggers list', 'chained runs'],
  ),
  entry('terraformGetRunTrigger', 'Get a run trigger by ID.', getRunTrigger, 'read', [
    'trigger details',
  ]),
  entry(
    'terraformCreateRunTrigger',
    'Create a run trigger so source applies queue runs here.',
    createRunTrigger,
    'write',
    ['chain workspaces', 'link workspaces'],
  ),
  entry(
    'terraformDeleteRunTrigger',
    'Delete a run trigger to stop cross-workspace chaining.',
    deleteRunTrigger,
    'delete',
    ['unchain', 'remove trigger'],
  ),
];
