// @ts-nocheck
import {
  getLinkedQuestions,
  getQuestion,
  getQuestionAnswers,
  getQuestionComments,
  getQuestionTimeline,
  getQuestions,
  getSimilarQuestions,
  searchQuestions,
  searchQuestionsByTitle,
  getRelatedQuestions,
} from './questions.js';
import {
  getAnswerComments,
  getAnswers,
  getComments,
  getPost,
  getPostComments,
  getPostRevisions,
} from './posts.js';
import {
  getUser,
  getUserAnswers,
  getUserBadges,
  getUserQuestions,
  getUserReputationHistory,
  getUserTags,
  searchUsers,
} from './users.js';
import {
  getTagInfo,
  getTagRelated,
  getTagSynonyms,
  getTagWikis,
  getTopAnswerers,
  getTopAskers,
  searchTags,
} from './tags.js';
import { createFilter, getBadgeRecipients, getBadges, getSiteInfo, listSites } from './meta.js';

export {
  searchQuestions,
  searchQuestionsByTitle,
  getSimilarQuestions,
  getQuestions,
  getQuestion,
  getQuestionAnswers,
  getQuestionComments,
  getLinkedQuestions,
  getRelatedQuestions,
  getQuestionTimeline,
  getAnswers,
  getAnswerComments,
  getPost,
  getPostComments,
  getPostRevisions,
  getComments,
  searchUsers,
  getUser,
  getUserQuestions,
  getUserAnswers,
  getUserTags,
  getUserReputationHistory,
  getUserBadges,
  searchTags,
  getTagInfo,
  getTagWikis,
  getTagRelated,
  getTopAnswerers,
  getTopAskers,
  getTagSynonyms,
  getSiteInfo,
  listSites,
  getBadges,
  getBadgeRecipients,
  createFilter,
};

const auth = 'stackOverflowApiKey' as const;

type Scope = 'read' | 'write' | 'delete';
function entry(
  name: string,
  description: string,
  toolRef: any,
  scope: Scope,
  requiredAuth?: typeof auth,
  keywords: string[] = [],
): {
  name: string;
  description: string;
  tool: any;
  requiredAuth?: typeof auth;
  scope: Scope;
  keywords: string[];
} {
  return requiredAuth
    ? { name, description, tool: toolRef, requiredAuth, scope, keywords }
    : { name, description, tool: toolRef, scope, keywords };
}

export const stackOverflowTools = [
  entry(
    'stackOverflowSearchQuestions',
    'Advanced search over questions: text, tags, votes, accepted/closed status.',
    searchQuestions,
    'read',
    auth,
    ['question', 'query', 'find', 'lookup'],
  ),
  entry(
    'stackOverflowSearchQuestionsByTitle',
    'Search questions by title text.',
    searchQuestionsByTitle,
    'read',
    auth,
    ['question', 'questions', 'title', 'duplicate'],
  ),
  entry(
    'stackOverflowGetSimilarQuestions',
    'Find questions similar to a draft title (duplicate check).',
    getSimilarQuestions,
    'read',
    auth,
    ['question', 'duplicate', 'duplicates', 'related'],
  ),
  entry(
    'stackOverflowGetQuestions',
    'Browse questions: hot, week/month rankings, or by tag.',
    getQuestions,
    'read',
    auth,
    ['question', 'hot', 'browse', 'trending'],
  ),
  entry(
    'stackOverflowGetQuestion',
    'Get full question(s) by ID, with bodies via filter.',
    getQuestion,
    'read',
    auth,
    ['questions', 'question', 'post', 'detail'],
  ),
  entry(
    'stackOverflowGetQuestionAnswers',
    'Get answers on question(s), sortable by votes.',
    getQuestionAnswers,
    'read',
    auth,
    ['answer', 'solution', 'solutions'],
  ),
  entry(
    'stackOverflowGetQuestionComments',
    'Get comments on question(s).',
    getQuestionComments,
    'read',
    auth,
    ['comment', 'comments', 'discussion'],
  ),
  entry(
    'stackOverflowGetLinkedQuestions',
    'Get questions linked from the given question(s).',
    getLinkedQuestions,
    'read',
    auth,
    ['question', 'questions', 'linked', 'duplicate'],
  ),
  entry(
    'stackOverflowGetRelatedQuestions',
    'Get algorithmically related questions.',
    getRelatedQuestions,
    'read',
    auth,
    ['question', 'questions', 'related', 'similar'],
  ),
  entry(
    'stackOverflowGetQuestionTimeline',
    'Get the event timeline of question(s).',
    getQuestionTimeline,
    'read',
    auth,
    ['question', 'history', 'timeline', 'event'],
  ),
  entry(
    'stackOverflowGetAnswers',
    'Get answer(s) by ID, with bodies via filter.',
    getAnswers,
    'read',
    auth,
    ['answer', 'solution', 'post'],
  ),
  entry(
    'stackOverflowGetAnswerComments',
    'Get comments on answer(s).',
    getAnswerComments,
    'read',
    auth,
    ['comment', 'comments', 'answer', 'discussion'],
  ),
  entry('stackOverflowGetPost', 'Get any post (question or answer) by ID.', getPost, 'read', auth, [
    'question',
    'answer',
    'post',
  ]),
  entry(
    'stackOverflowGetPostComments',
    'Get comments on any post(s).',
    getPostComments,
    'read',
    auth,
    ['comment', 'comments', 'discussion'],
  ),
  entry(
    'stackOverflowGetPostRevisions',
    'Get edit/revision history of post(s).',
    getPostRevisions,
    'read',
    auth,
    ['edit', 'edits', 'history', 'revision', 'diff'],
  ),
  entry('stackOverflowGetComments', 'Get comment(s) by ID.', getComments, 'read', auth, [
    'comment',
    'discussion',
  ]),
  entry('stackOverflowSearchUsers', 'Find users by display-name text.', searchUsers, 'read', auth, [
    'user',
    'profile',
    'author',
    'reputation',
  ]),
  entry(
    'stackOverflowGetUser',
    'Get user profile(s): reputation, badges, acceptance rate.',
    getUser,
    'read',
    auth,
    ['users', 'profile', 'reputation', 'karma'],
  ),
  entry(
    'stackOverflowGetUserQuestions',
    'Get questions asked by user(s).',
    getUserQuestions,
    'read',
    auth,
    ['user', 'question', 'questions', 'asked'],
  ),
  entry(
    'stackOverflowGetUserAnswers',
    'Get answers posted by user(s).',
    getUserAnswers,
    'read',
    auth,
    ['user', 'answer', 'answers', 'solutions'],
  ),
  entry(
    'stackOverflowGetUserTags',
    'Get tags a user is active in — fastest read on expertise.',
    getUserTags,
    'read',
    auth,
    ['user', 'tag', 'expertise', 'top'],
  ),
  entry(
    'stackOverflowGetUserReputationHistory',
    'Get reputation-change history of user(s).',
    getUserReputationHistory,
    'read',
    auth,
    ['user', 'reputation', 'rep', 'karma', 'history'],
  ),
  entry(
    'stackOverflowGetUserBadges',
    'Get badges earned by user(s).',
    getUserBadges,
    'read',
    auth,
    ['user', 'badge', 'achievement'],
  ),
  entry(
    'stackOverflowSearchTags',
    'Find tags by name, sorted by popularity.',
    searchTags,
    'read',
    auth,
    ['tag', 'find', 'popular', 'trending'],
  ),
  entry(
    'stackOverflowGetTagInfo',
    'Get tag details: counts, excerpts, synonyms.',
    getTagInfo,
    'read',
    auth,
    ['tags', 'tag', 'wiki', 'synonym'],
  ),
  entry(
    'stackOverflowGetTagWikis',
    'Get tag wiki excerpts and usage guidance.',
    getTagWikis,
    'read',
    auth,
    ['tag', 'tags', 'wiki', 'docs', 'guidance'],
  ),
  entry(
    'stackOverflowGetTagRelated',
    'Get tags most correlated with a tag (search expansion).',
    getTagRelated,
    'read',
    auth,
    ['tag', 'tags', 'related', 'similar'],
  ),
  entry(
    'stackOverflowGetTopAnswerers',
    'Get top answerers in a tag (all-time or month).',
    getTopAnswerers,
    'read',
    auth,
    ['answer', 'answerers', 'expert', 'experts', 'tag', 'leaderboard'],
  ),
  entry(
    'stackOverflowGetTopAskers',
    'Get top askers in a tag (all-time or month).',
    getTopAskers,
    'read',
    auth,
    ['asker', 'question', 'tag', 'leaderboard'],
  ),
  entry(
    'stackOverflowGetTagSynonyms',
    'Get synonym mappings for tag(s).',
    getTagSynonyms,
    'read',
    auth,
    ['tag', 'tags', 'synonym', 'alias'],
  ),
  entry(
    'stackOverflowGetSiteInfo',
    'Get site statistics plus current API quota.',
    getSiteInfo,
    'read',
    auth,
    ['site', 'stats', 'statistics', 'quota'],
  ),
  entry(
    'stackOverflowListSites',
    'List all Stack Exchange network sites and API slugs.',
    listSites,
    'read',
    auth,
    ['site', 'sites', 'network', 'stackexchange'],
  ),
  entry('stackOverflowGetBadges', 'List badges on a site.', getBadges, 'read', auth, [
    'badge',
    'achievements',
  ]),
  entry(
    'stackOverflowGetBadgeRecipients',
    'Get recent recipients of badge(s).',
    getBadgeRecipients,
    'read',
    auth,
    ['badge', 'badges', 'user', 'users', 'leaderboard'],
  ),
  entry(
    'stackOverflowCreateFilter',
    'Create a custom result filter for slimming payloads.',
    createFilter,
    'read',
    auth,
    ['filter', 'custom', 'fields', 'slim'],
  ),
];
