// @ts-nocheck
import {
    getLinkedQuestions,
    getQuestion,
    getQuestionAnswers,
    getQuestionComments,
    getQuestionTimeline,
    getQuestions,
    getSimilarQuestions,
    searchQuestions,
    searchQuestionsByTitle,
    getRelatedQuestions,
} from './questions.js';
import {
    getAnswerComments,
    getAnswers,
    getComments,
    getPost,
    getPostComments,
    getPostRevisions,
} from './posts.js';
import {
    getUser,
    getUserAnswers,
    getUserBadges,
    getUserQuestions,
    getUserReputationHistory,
    getUserTags,
    searchUsers,
} from './users.js';
import {
    getTagInfo,
    getTagRelated,
    getTagSynonyms,
    getTagWikis,
    getTopAnswerers,
    getTopAskers,
    searchTags,
} from './tags.js';
import { createFilter, getBadgeRecipients, getBadges, getSiteInfo, listSites } from './meta.js';

export {
    searchQuestions,
    searchQuestionsByTitle,
    getSimilarQuestions,
    getQuestions,
    getQuestion,
    getQuestionAnswers,
    getQuestionComments,
    getLinkedQuestions,
    getRelatedQuestions,
    getQuestionTimeline,
    getAnswers,
    getAnswerComments,
    getPost,
    getPostComments,
    getPostRevisions,
    getComments,
    searchUsers,
    getUser,
    getUserQuestions,
    getUserAnswers,
    getUserTags,
    getUserReputationHistory,
    getUserBadges,
    searchTags,
    getTagInfo,
    getTagWikis,
    getTagRelated,
    getTopAnswerers,
    getTopAskers,
    getTagSynonyms,
    getSiteInfo,
    listSites,
    getBadges,
    getBadgeRecipients,
    createFilter,
};

const auth = 'stackOverflowApiKey' as const;

type Scope = 'read' | 'write' | 'delete';
function entry(
    name: string,
    description: string,
    toolRef: any,
    scope: Scope,
    requiredAuth?: typeof auth,
): { name: string; description: string; tool: any; requiredAuth?: typeof auth; scope: Scope } {
    return requiredAuth ? { name, description, tool: toolRef, requiredAuth, scope } : { name, description, tool: toolRef, scope };
}

export const stackOverflowTools = [
    entry('stackOverflowSearchQuestions', 'Advanced search over questions: text, tags, votes, accepted/closed status.', searchQuestions, 'read', auth),
    entry('stackOverflowSearchQuestionsByTitle', 'Search questions by title text.', searchQuestionsByTitle, 'read', auth),
    entry('stackOverflowGetSimilarQuestions', 'Find questions similar to a draft title (duplicate check).', getSimilarQuestions, 'read', auth),
    entry('stackOverflowGetQuestions', 'Browse questions: hot, week/month rankings, or by tag.', getQuestions, 'read', auth),
    entry('stackOverflowGetQuestion', 'Get full question(s) by ID, with bodies via filter.', getQuestion, 'read', auth),
    entry('stackOverflowGetQuestionAnswers', 'Get answers on question(s), sortable by votes.', getQuestionAnswers, 'read', auth),
    entry('stackOverflowGetQuestionComments', 'Get comments on question(s).', getQuestionComments, 'read', auth),
    entry('stackOverflowGetLinkedQuestions', 'Get questions linked from the given question(s).', getLinkedQuestions, 'read', auth),
    entry('stackOverflowGetRelatedQuestions', 'Get algorithmically related questions.', getRelatedQuestions, 'read', auth),
    entry('stackOverflowGetQuestionTimeline', 'Get the event timeline of question(s).', getQuestionTimeline, 'read', auth),
    entry('stackOverflowGetAnswers', 'Get answer(s) by ID, with bodies via filter.', getAnswers, 'read', auth),
    entry('stackOverflowGetAnswerComments', 'Get comments on answer(s).', getAnswerComments, 'read', auth),
    entry('stackOverflowGetPost', 'Get any post (question or answer) by ID.', getPost, 'read', auth),
    entry('stackOverflowGetPostComments', 'Get comments on any post(s).', getPostComments, 'read', auth),
    entry('stackOverflowGetPostRevisions', 'Get edit/revision history of post(s).', getPostRevisions, 'read', auth),
    entry('stackOverflowGetComments', 'Get comment(s) by ID.', getComments, 'read', auth),
    entry('stackOverflowSearchUsers', 'Find users by display-name text.', searchUsers, 'read', auth),
    entry('stackOverflowGetUser', 'Get user profile(s): reputation, badges, acceptance rate.', getUser, 'read', auth),
    entry('stackOverflowGetUserQuestions', 'Get questions asked by user(s).', getUserQuestions, 'read', auth),
    entry('stackOverflowGetUserAnswers', 'Get answers posted by user(s).', getUserAnswers, 'read', auth),
    entry('stackOverflowGetUserTags', "Get tags a user is active in — fastest read on expertise.", getUserTags, 'read', auth),
    entry('stackOverflowGetUserReputationHistory', 'Get reputation-change history of user(s).', getUserReputationHistory, 'read', auth),
    entry('stackOverflowGetUserBadges', 'Get badges earned by user(s).', getUserBadges, 'read', auth),
    entry('stackOverflowSearchTags', 'Find tags by name, sorted by popularity.', searchTags, 'read', auth),
    entry('stackOverflowGetTagInfo', 'Get tag details: counts, excerpts, synonyms.', getTagInfo, 'read', auth),
    entry('stackOverflowGetTagWikis', 'Get tag wiki excerpts and usage guidance.', getTagWikis, 'read', auth),
    entry('stackOverflowGetTagRelated', 'Get tags most correlated with a tag (search expansion).', getTagRelated, 'read', auth),
    entry('stackOverflowGetTopAnswerers', 'Get top answerers in a tag (all-time or month).', getTopAnswerers, 'read', auth),
    entry('stackOverflowGetTopAskers', 'Get top askers in a tag (all-time or month).', getTopAskers, 'read', auth),
    entry('stackOverflowGetTagSynonyms', 'Get synonym mappings for tag(s).', getTagSynonyms, 'read', auth),
    entry('stackOverflowGetSiteInfo', 'Get site statistics plus current API quota.', getSiteInfo, 'read', auth),
    entry('stackOverflowListSites', 'List all Stack Exchange network sites and API slugs.', listSites, 'read', auth),
    entry('stackOverflowGetBadges', 'List badges on a site.', getBadges, 'read', auth),
    entry('stackOverflowGetBadgeRecipients', 'Get recent recipients of badge(s).', getBadgeRecipients, 'read', auth),
    entry('stackOverflowCreateFilter', 'Create a custom result filter for slimming payloads.', createFilter, 'read', auth),
];
