// @ts-nocheck
import {
  opsgenieCreateAlert,
  opsgenieListAlerts,
  opsgenieGetAlert,
  opsgenieDeleteAlert,
  opsgenieCountAlerts,
  opsgenieAcknowledgeAlert,
  opsgenieUnacknowledgeAlert,
  opsgenieSnoozeAlert,
  opsgenieCloseAlert,
  opsgenieAssignAlert,
  opsgenieEscalateAlert,
  opsgenieAddAlertNote,
  opsgenieListAlertNotes,
  opsgenieAddTags,
  opsgenieRemoveTags,
  opsgenieAddDetails,
  opsgenieRemoveDetails,
  opsgenieAddResponder,
  opsgenieAddTeam,
  opsgenieUpdatePriority,
  opsgenieUpdateMessage,
  opsgenieUpdateDescription,
  opsgenieExecuteCustomAction,
  opsgenieListAlertLogs,
  opsgenieListAlertRecipients,
  opsgenieListAlertAttachments,
  opsgenieDeleteAlertAttachment,
  opsgenieGetAlertRequestStatus,
  opsgenieCreateSavedSearch,
  opsgenieListSavedSearches,
  opsgenieGetSavedSearch,
  opsgenieUpdateSavedSearch,
  opsgenieDeleteSavedSearch,
} from './alerts.js';
import {
  opsgenieCreateIncident,
  opsgenieListIncidents,
  opsgenieGetIncident,
  opsgenieDeleteIncident,
  opsgenieCloseIncident,
  opsgenieResolveIncident,
  opsgenieGetIncidentRequestStatus,
  opsgenieListSchedules,
  opsgenieGetSchedule,
  opsgenieCreateSchedule,
  opsgenieUpdateSchedule,
  opsgenieDeleteSchedule,
  opsgenieGetScheduleTimeline,
  opsgenieListRotations,
  opsgenieCreateRotation,
  opsgenieGetRotation,
  opsgenieUpdateRotation,
  opsgenieDeleteRotation,
  opsgenieListOverrides,
  opsgenieCreateOverride,
  opsgenieGetOverride,
  opsgenieUpdateOverride,
  opsgenieDeleteOverride,
  opsgenieGetOnCalls,
  opsgenieListOnCalls,
  opsgenieGetNextOnCalls,
  opsgenieExportSchedule,
} from './schedules.js';
import {
  opsgenieListTeams,
  opsgenieGetTeam,
  opsgenieCreateTeam,
  opsgenieUpdateTeam,
  opsgenieDeleteTeam,
  opsgenieListTeamMembers,
  opsgenieAddTeamMember,
  opsgenieRemoveTeamMember,
  opsgenieGetTeamLogs,
  opsgenieListTeamRoles,
  opsgenieCreateTeamRole,
  opsgenieGetTeamRole,
  opsgenieUpdateTeamRole,
  opsgenieDeleteTeamRole,
  opsgenieListRoutingRules,
  opsgenieCreateRoutingRule,
  opsgenieGetRoutingRule,
  opsgenieUpdateRoutingRule,
  opsgenieDeleteRoutingRule,
  opsgenieChangeRoutingRuleOrder,
} from './teams.js';
import {
  opsgenieListUsers,
  opsgenieGetUser,
  opsgenieCreateUser,
  opsgenieUpdateUser,
  opsgenieDeleteUser,
  opsgenieListUserEscalations,
  opsgenieListUserTeams,
  opsgenieListUserSchedules,
  opsgenieListContacts,
  opsgenieCreateContact,
  opsgenieGetContact,
  opsgenieUpdateContact,
  opsgenieDeleteContact,
  opsgenieEnableContact,
  opsgenieDisableContact,
  opsgenieListNotificationRules,
  opsgenieCreateNotificationRule,
  opsgenieGetNotificationRule,
  opsgenieUpdateNotificationRule,
  opsgenieDeleteNotificationRule,
  opsgenieEnableNotificationRule,
  opsgenieDisableNotificationRule,
  opsgenieChangeNotificationRuleOrder,
  opsgenieListNotificationRuleSteps,
  opsgenieCreateNotificationRuleStep,
  opsgenieGetNotificationRuleStep,
  opsgenieUpdateNotificationRuleStep,
  opsgenieDeleteNotificationRuleStep,
  opsgenieEnableNotificationRuleStep,
  opsgenieDisableNotificationRuleStep,
  opsgenieListCustomRoles,
  opsgenieCreateCustomRole,
  opsgenieGetCustomRole,
  opsgenieUpdateCustomRole,
  opsgenieDeleteCustomRole,
  opsgenieListForwardingRules,
  opsgenieCreateForwardingRule,
  opsgenieGetForwardingRule,
  opsgenieUpdateForwardingRule,
  opsgenieDeleteForwardingRule,
} from './users.js';
import {
  opsgenieListEscalations,
  opsgenieGetEscalation,
  opsgenieCreateEscalation,
  opsgenieUpdateEscalation,
  opsgenieDeleteEscalation,
  opsgenieListIntegrations,
  opsgenieGetIntegration,
  opsgenieCreateIntegration,
  opsgenieUpdateIntegration,
  opsgenieDeleteIntegration,
  opsgenieEnableIntegration,
  opsgenieDisableIntegration,
  opsgenieAuthenticateIntegration,
  opsgenieListMaintenance,
  opsgenieGetMaintenance,
  opsgenieCreateMaintenance,
  opsgenieUpdateMaintenance,
  opsgenieDeleteMaintenance,
  opsgenieCancelMaintenance,
  opsgenieListServices,
  opsgenieGetService,
  opsgenieCreateService,
  opsgenieUpdateService,
  opsgenieDeleteService,
  opsgenieListAlertPolicies,
  opsgenieListNotificationPolicies,
  opsgenieCreatePolicy,
  opsgenieGetPolicy,
  opsgenieUpdatePolicy,
  opsgenieDeletePolicy,
  opsgenieEnablePolicy,
  opsgenieDisablePolicy,
  opsgenieChangePolicyOrder,
  opsgenieListHeartbeats,
  opsgenieGetHeartbeat,
  opsgenieCreateHeartbeat,
  opsgenieUpdateHeartbeat,
  opsgenieDeleteHeartbeat,
  opsgeniePingHeartbeat,
  opsgenieEnableHeartbeat,
  opsgenieDisableHeartbeat,
  opsgenieGetAccountInfo,
} from './admin.js';

export {
  opsgenieCreateAlert,
  opsgenieListAlerts,
  opsgenieGetAlert,
  opsgenieDeleteAlert,
  opsgenieCountAlerts,
  opsgenieAcknowledgeAlert,
  opsgenieUnacknowledgeAlert,
  opsgenieSnoozeAlert,
  opsgenieCloseAlert,
  opsgenieAssignAlert,
  opsgenieEscalateAlert,
  opsgenieAddAlertNote,
  opsgenieListAlertNotes,
  opsgenieAddTags,
  opsgenieRemoveTags,
  opsgenieAddDetails,
  opsgenieRemoveDetails,
  opsgenieAddResponder,
  opsgenieAddTeam,
  opsgenieUpdatePriority,
  opsgenieUpdateMessage,
  opsgenieUpdateDescription,
  opsgenieExecuteCustomAction,
  opsgenieListAlertLogs,
  opsgenieListAlertRecipients,
  opsgenieListAlertAttachments,
  opsgenieDeleteAlertAttachment,
  opsgenieGetAlertRequestStatus,
  opsgenieCreateSavedSearch,
  opsgenieListSavedSearches,
  opsgenieGetSavedSearch,
  opsgenieUpdateSavedSearch,
  opsgenieDeleteSavedSearch,
  opsgenieCreateIncident,
  opsgenieListIncidents,
  opsgenieGetIncident,
  opsgenieDeleteIncident,
  opsgenieCloseIncident,
  opsgenieResolveIncident,
  opsgenieGetIncidentRequestStatus,
  opsgenieListSchedules,
  opsgenieGetSchedule,
  opsgenieCreateSchedule,
  opsgenieUpdateSchedule,
  opsgenieDeleteSchedule,
  opsgenieGetScheduleTimeline,
  opsgenieListRotations,
  opsgenieCreateRotation,
  opsgenieGetRotation,
  opsgenieUpdateRotation,
  opsgenieDeleteRotation,
  opsgenieListOverrides,
  opsgenieCreateOverride,
  opsgenieGetOverride,
  opsgenieUpdateOverride,
  opsgenieDeleteOverride,
  opsgenieGetOnCalls,
  opsgenieListOnCalls,
  opsgenieGetNextOnCalls,
  opsgenieExportSchedule,
  opsgenieListTeams,
  opsgenieGetTeam,
  opsgenieCreateTeam,
  opsgenieUpdateTeam,
  opsgenieDeleteTeam,
  opsgenieListTeamMembers,
  opsgenieAddTeamMember,
  opsgenieRemoveTeamMember,
  opsgenieGetTeamLogs,
  opsgenieListTeamRoles,
  opsgenieCreateTeamRole,
  opsgenieGetTeamRole,
  opsgenieUpdateTeamRole,
  opsgenieDeleteTeamRole,
  opsgenieListRoutingRules,
  opsgenieCreateRoutingRule,
  opsgenieGetRoutingRule,
  opsgenieUpdateRoutingRule,
  opsgenieDeleteRoutingRule,
  opsgenieChangeRoutingRuleOrder,
  opsgenieListUsers,
  opsgenieGetUser,
  opsgenieCreateUser,
  opsgenieUpdateUser,
  opsgenieDeleteUser,
  opsgenieListUserEscalations,
  opsgenieListUserTeams,
  opsgenieListUserSchedules,
  opsgenieListContacts,
  opsgenieCreateContact,
  opsgenieGetContact,
  opsgenieUpdateContact,
  opsgenieDeleteContact,
  opsgenieEnableContact,
  opsgenieDisableContact,
  opsgenieListNotificationRules,
  opsgenieCreateNotificationRule,
  opsgenieGetNotificationRule,
  opsgenieUpdateNotificationRule,
  opsgenieDeleteNotificationRule,
  opsgenieEnableNotificationRule,
  opsgenieDisableNotificationRule,
  opsgenieChangeNotificationRuleOrder,
  opsgenieListNotificationRuleSteps,
  opsgenieCreateNotificationRuleStep,
  opsgenieGetNotificationRuleStep,
  opsgenieUpdateNotificationRuleStep,
  opsgenieDeleteNotificationRuleStep,
  opsgenieEnableNotificationRuleStep,
  opsgenieDisableNotificationRuleStep,
  opsgenieListCustomRoles,
  opsgenieCreateCustomRole,
  opsgenieGetCustomRole,
  opsgenieUpdateCustomRole,
  opsgenieDeleteCustomRole,
  opsgenieListForwardingRules,
  opsgenieCreateForwardingRule,
  opsgenieGetForwardingRule,
  opsgenieUpdateForwardingRule,
  opsgenieDeleteForwardingRule,
  opsgenieListEscalations,
  opsgenieGetEscalation,
  opsgenieCreateEscalation,
  opsgenieUpdateEscalation,
  opsgenieDeleteEscalation,
  opsgenieListIntegrations,
  opsgenieGetIntegration,
  opsgenieCreateIntegration,
  opsgenieUpdateIntegration,
  opsgenieDeleteIntegration,
  opsgenieEnableIntegration,
  opsgenieDisableIntegration,
  opsgenieAuthenticateIntegration,
  opsgenieListMaintenance,
  opsgenieGetMaintenance,
  opsgenieCreateMaintenance,
  opsgenieUpdateMaintenance,
  opsgenieDeleteMaintenance,
  opsgenieCancelMaintenance,
  opsgenieListServices,
  opsgenieGetService,
  opsgenieCreateService,
  opsgenieUpdateService,
  opsgenieDeleteService,
  opsgenieListAlertPolicies,
  opsgenieListNotificationPolicies,
  opsgenieCreatePolicy,
  opsgenieGetPolicy,
  opsgenieUpdatePolicy,
  opsgenieDeletePolicy,
  opsgenieEnablePolicy,
  opsgenieDisablePolicy,
  opsgenieChangePolicyOrder,
  opsgenieListHeartbeats,
  opsgenieGetHeartbeat,
  opsgenieCreateHeartbeat,
  opsgenieUpdateHeartbeat,
  opsgenieDeleteHeartbeat,
  opsgeniePingHeartbeat,
  opsgenieEnableHeartbeat,
  opsgenieDisableHeartbeat,
  opsgenieGetAccountInfo,
};

const AUTH = 'opsgenieApiKey' as const;

export const opsgenieTools = [
  {
    name: 'opsgenieCreateAlert',
    description: 'Create an alert with responders and priority.',
    tool: opsgenieCreateAlert,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['page', 'incident', 'trigger', 'fire'],
  },
  {
    name: 'opsgenieListAlerts',
    description: 'List alerts with search query.',
    tool: opsgenieListAlerts,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['pages', 'queue'],
  },
  {
    name: 'opsgenieGetAlert',
    description: 'Get one alert.',
    tool: opsgenieGetAlert,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['page', 'fetch'],
  },
  {
    name: 'opsgenieDeleteAlert',
    description: 'Delete an alert.',
    tool: opsgenieDeleteAlert,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['remove'],
  },
  {
    name: 'opsgenieCountAlerts',
    description: 'Count alerts matching a query.',
    tool: opsgenieCountAlerts,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['total', 'stats'],
  },
  {
    name: 'opsgenieAcknowledgeAlert',
    description: 'Acknowledge an alert.',
    tool: opsgenieAcknowledgeAlert,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['ack', 'seen'],
  },
  {
    name: 'opsgenieUnacknowledgeAlert',
    description: 'Unacknowledge an alert.',
    tool: opsgenieUnacknowledgeAlert,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['unack', 'reopen'],
  },
  {
    name: 'opsgenieSnoozeAlert',
    description: 'Snooze an alert until a time.',
    tool: opsgenieSnoozeAlert,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['mute', 'delay'],
  },
  {
    name: 'opsgenieCloseAlert',
    description: 'Close an alert.',
    tool: opsgenieCloseAlert,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['resolve', 'done'],
  },
  {
    name: 'opsgenieAssignAlert',
    description: 'Assign an alert owner.',
    tool: opsgenieAssignAlert,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['owner', 'delegate'],
  },
  {
    name: 'opsgenieEscalateAlert',
    description: 'Escalate to next rule set.',
    tool: opsgenieEscalateAlert,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['page', 'next'],
  },
  {
    name: 'opsgenieAddAlertNote',
    description: 'Add a note to an alert.',
    tool: opsgenieAddAlertNote,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['comment', 'timeline'],
  },
  {
    name: 'opsgenieListAlertNotes',
    description: 'List alert notes.',
    tool: opsgenieListAlertNotes,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['comments'],
  },
  {
    name: 'opsgenieAddTags',
    description: 'Add tags to an alert.',
    tool: opsgenieAddTags,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['label'],
  },
  {
    name: 'opsgenieRemoveTags',
    description: 'Remove tags from an alert.',
    tool: opsgenieRemoveTags,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['untag'],
  },
  {
    name: 'opsgenieAddDetails',
    description: 'Add custom details to an alert.',
    tool: opsgenieAddDetails,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['fields', 'context'],
  },
  {
    name: 'opsgenieRemoveDetails',
    description: 'Remove detail keys.',
    tool: opsgenieRemoveDetails,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['fields'],
  },
  {
    name: 'opsgenieAddResponder',
    description: 'Add a responder to an alert.',
    tool: opsgenieAddResponder,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['page', 'notify'],
  },
  {
    name: 'opsgenieAddTeam',
    description: 'Route an alert to a team.',
    tool: opsgenieAddTeam,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['handoff'],
  },
  {
    name: 'opsgenieUpdatePriority',
    description: 'Change alert priority.',
    tool: opsgenieUpdatePriority,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['severity', 'p1'],
  },
  {
    name: 'opsgenieUpdateMessage',
    description: 'Update alert message.',
    tool: opsgenieUpdateMessage,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['title', 'edit'],
  },
  {
    name: 'opsgenieUpdateDescription',
    description: 'Update alert description.',
    tool: opsgenieUpdateDescription,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['edit'],
  },
  {
    name: 'opsgenieExecuteCustomAction',
    description: 'Run a custom alert action.',
    tool: opsgenieExecuteCustomAction,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['runbook', 'webhook'],
  },
  {
    name: 'opsgenieListAlertLogs',
    description: 'List alert activity logs.',
    tool: opsgenieListAlertLogs,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['history', 'audit'],
  },
  {
    name: 'opsgenieListAlertRecipients',
    description: 'List who was notified.',
    tool: opsgenieListAlertRecipients,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['paged', 'notified'],
  },
  {
    name: 'opsgenieListAlertAttachments',
    description: 'List alert attachments.',
    tool: opsgenieListAlertAttachments,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['files'],
  },
  {
    name: 'opsgenieDeleteAlertAttachment',
    description: 'Delete an alert attachment.',
    tool: opsgenieDeleteAlertAttachment,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['file', 'remove'],
  },
  {
    name: 'opsgenieGetAlertRequestStatus',
    description: 'Poll async alert request.',
    tool: opsgenieGetAlertRequestStatus,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['poll', 'job'],
  },
  {
    name: 'opsgenieCreateSavedSearch',
    description: 'Save an alert search.',
    tool: opsgenieCreateSavedSearch,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['filter', 'view'],
  },
  {
    name: 'opsgenieListSavedSearches',
    description: 'List saved searches.',
    tool: opsgenieListSavedSearches,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['filters', 'views'],
  },
  {
    name: 'opsgenieGetSavedSearch',
    description: 'Get one saved search.',
    tool: opsgenieGetSavedSearch,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['filter', 'fetch'],
  },
  {
    name: 'opsgenieUpdateSavedSearch',
    description: 'Update a saved search.',
    tool: opsgenieUpdateSavedSearch,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['filter', 'edit'],
  },
  {
    name: 'opsgenieDeleteSavedSearch',
    description: 'Delete a saved search.',
    tool: opsgenieDeleteSavedSearch,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['filter', 'remove'],
  },
  {
    name: 'opsgenieCreateIncident',
    description: 'Create an incident.',
    tool: opsgenieCreateIncident,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['major', 'outage', 'war-room'],
  },
  {
    name: 'opsgenieListIncidents',
    description: 'List incidents.',
    tool: opsgenieListIncidents,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['majors', 'outages'],
  },
  {
    name: 'opsgenieGetIncident',
    description: 'Get one incident.',
    tool: opsgenieGetIncident,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['major', 'fetch'],
  },
  {
    name: 'opsgenieDeleteIncident',
    description: 'Delete an incident.',
    tool: opsgenieDeleteIncident,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['remove'],
  },
  {
    name: 'opsgenieCloseIncident',
    description: 'Close an incident.',
    tool: opsgenieCloseIncident,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['resolve', 'mitigate'],
  },
  {
    name: 'opsgenieResolveIncident',
    description: 'Mark an incident resolved.',
    tool: opsgenieResolveIncident,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['fixed', 'done'],
  },
  {
    name: 'opsgenieGetIncidentRequestStatus',
    description: 'Poll async incident request.',
    tool: opsgenieGetIncidentRequestStatus,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['poll', 'job'],
  },
  {
    name: 'opsgenieListSchedules',
    description: 'List on-call schedules.',
    tool: opsgenieListSchedules,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['rotas'],
  },
  {
    name: 'opsgenieGetSchedule',
    description: 'Get one schedule.',
    tool: opsgenieGetSchedule,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['rota', 'fetch'],
  },
  {
    name: 'opsgenieCreateSchedule',
    description: 'Create a schedule.',
    tool: opsgenieCreateSchedule,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['rota', 'new'],
  },
  {
    name: 'opsgenieUpdateSchedule',
    description: 'Update a schedule.',
    tool: opsgenieUpdateSchedule,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['rota', 'edit'],
  },
  {
    name: 'opsgenieDeleteSchedule',
    description: 'Delete a schedule.',
    tool: opsgenieDeleteSchedule,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['rota', 'remove'],
  },
  {
    name: 'opsgenieGetScheduleTimeline',
    description: 'Get schedule timeline.',
    tool: opsgenieGetScheduleTimeline,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['calendar', 'coverage'],
  },
  {
    name: 'opsgenieListRotations',
    description: 'List schedule rotations.',
    tool: opsgenieListRotations,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['shifts'],
  },
  {
    name: 'opsgenieCreateRotation',
    description: 'Create a rotation.',
    tool: opsgenieCreateRotation,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['shift', 'roster'],
  },
  {
    name: 'opsgenieGetRotation',
    description: 'Get one rotation.',
    tool: opsgenieGetRotation,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['shift', 'fetch'],
  },
  {
    name: 'opsgenieUpdateRotation',
    description: 'Update a rotation.',
    tool: opsgenieUpdateRotation,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['shift', 'edit'],
  },
  {
    name: 'opsgenieDeleteRotation',
    description: 'Delete a rotation.',
    tool: opsgenieDeleteRotation,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['shift', 'remove'],
  },
  {
    name: 'opsgenieListOverrides',
    description: 'List schedule overrides.',
    tool: opsgenieListOverrides,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['swaps', 'cover'],
  },
  {
    name: 'opsgenieCreateOverride',
    description: 'Create an on-call override.',
    tool: opsgenieCreateOverride,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['swap', 'cover'],
  },
  {
    name: 'opsgenieGetOverride',
    description: 'Get one override.',
    tool: opsgenieGetOverride,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['swap', 'fetch'],
  },
  {
    name: 'opsgenieUpdateOverride',
    description: 'Update an override.',
    tool: opsgenieUpdateOverride,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['swap', 'edit'],
  },
  {
    name: 'opsgenieDeleteOverride',
    description: 'Delete an override.',
    tool: opsgenieDeleteOverride,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['swap', 'remove'],
  },
  {
    name: 'opsgenieGetOnCalls',
    description: 'Who is on call now.',
    tool: opsgenieGetOnCalls,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['oncall', 'pager', 'duty'],
  },
  {
    name: 'opsgenieListOnCalls',
    description: 'On-call across all schedules.',
    tool: opsgenieListOnCalls,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['oncall', 'roster'],
  },
  {
    name: 'opsgenieGetNextOnCalls',
    description: 'Next on-call participants.',
    tool: opsgenieGetNextOnCalls,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['upcoming', 'handoff'],
  },
  {
    name: 'opsgenieExportSchedule',
    description: 'Export schedule as .ics.',
    tool: opsgenieExportSchedule,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['calendar', 'ical'],
  },
  {
    name: 'opsgenieListTeams',
    description: 'List teams.',
    tool: opsgenieListTeams,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['groups'],
  },
  {
    name: 'opsgenieGetTeam',
    description: 'Get one team.',
    tool: opsgenieGetTeam,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['group', 'fetch'],
  },
  {
    name: 'opsgenieCreateTeam',
    description: 'Create a team.',
    tool: opsgenieCreateTeam,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['group', 'provision'],
  },
  {
    name: 'opsgenieUpdateTeam',
    description: 'Update a team.',
    tool: opsgenieUpdateTeam,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['group', 'rename'],
  },
  {
    name: 'opsgenieDeleteTeam',
    description: 'Delete a team.',
    tool: opsgenieDeleteTeam,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['group', 'remove'],
  },
  {
    name: 'opsgenieListTeamMembers',
    description: 'List team members.',
    tool: opsgenieListTeamMembers,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['people', 'roster'],
  },
  {
    name: 'opsgenieAddTeamMember',
    description: 'Add a team member.',
    tool: opsgenieAddTeamMember,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['invite', 'join'],
  },
  {
    name: 'opsgenieRemoveTeamMember',
    description: 'Remove a team member.',
    tool: opsgenieRemoveTeamMember,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['kick', 'leave'],
  },
  {
    name: 'opsgenieGetTeamLogs',
    description: 'List team activity logs.',
    tool: opsgenieGetTeamLogs,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['audit', 'history'],
  },
  {
    name: 'opsgenieListTeamRoles',
    description: 'List team roles.',
    tool: opsgenieListTeamRoles,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['rbac'],
  },
  {
    name: 'opsgenieCreateTeamRole',
    description: 'Create a team role.',
    tool: opsgenieCreateTeamRole,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['rbac', 'grant'],
  },
  {
    name: 'opsgenieGetTeamRole',
    description: 'Get one team role.',
    tool: opsgenieGetTeamRole,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['rbac', 'fetch'],
  },
  {
    name: 'opsgenieUpdateTeamRole',
    description: 'Update a team role.',
    tool: opsgenieUpdateTeamRole,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['rbac', 'edit'],
  },
  {
    name: 'opsgenieDeleteTeamRole',
    description: 'Delete a team role.',
    tool: opsgenieDeleteTeamRole,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['rbac', 'remove'],
  },
  {
    name: 'opsgenieListRoutingRules',
    description: 'List team routing rules.',
    tool: opsgenieListRoutingRules,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['route', 'conditions'],
  },
  {
    name: 'opsgenieCreateRoutingRule',
    description: 'Create a routing rule.',
    tool: opsgenieCreateRoutingRule,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['route', 'notify'],
  },
  {
    name: 'opsgenieGetRoutingRule',
    description: 'Get one routing rule.',
    tool: opsgenieGetRoutingRule,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['route', 'fetch'],
  },
  {
    name: 'opsgenieUpdateRoutingRule',
    description: 'Update a routing rule.',
    tool: opsgenieUpdateRoutingRule,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['route', 'edit'],
  },
  {
    name: 'opsgenieDeleteRoutingRule',
    description: 'Delete a routing rule.',
    tool: opsgenieDeleteRoutingRule,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['route', 'remove'],
  },
  {
    name: 'opsgenieChangeRoutingRuleOrder',
    description: 'Reorder a routing rule.',
    tool: opsgenieChangeRoutingRuleOrder,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['route', 'priority'],
  },
  {
    name: 'opsgenieListUsers',
    description: 'List users.',
    tool: opsgenieListUsers,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['people', 'responders'],
  },
  {
    name: 'opsgenieGetUser',
    description: 'Get one user.',
    tool: opsgenieGetUser,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['person', 'fetch'],
  },
  {
    name: 'opsgenieCreateUser',
    description: 'Invite/create a user.',
    tool: opsgenieCreateUser,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['onboard', 'provision'],
  },
  {
    name: 'opsgenieUpdateUser',
    description: 'Update a user.',
    tool: opsgenieUpdateUser,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['person', 'edit'],
  },
  {
    name: 'opsgenieDeleteUser',
    description: 'Delete a user.',
    tool: opsgenieDeleteUser,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['offboard', 'remove'],
  },
  {
    name: 'opsgenieListUserEscalations',
    description: 'List user escalations.',
    tool: opsgenieListUserEscalations,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['policies'],
  },
  {
    name: 'opsgenieListUserTeams',
    description: 'List user teams.',
    tool: opsgenieListUserTeams,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['memberships'],
  },
  {
    name: 'opsgenieListUserSchedules',
    description: 'List user schedules.',
    tool: opsgenieListUserSchedules,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['rotas'],
  },
  {
    name: 'opsgenieListContacts',
    description: 'List user contact methods.',
    tool: opsgenieListContacts,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['email', 'sms', 'phone'],
  },
  {
    name: 'opsgenieCreateContact',
    description: 'Add a contact method.',
    tool: opsgenieCreateContact,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['phone', 'notify'],
  },
  {
    name: 'opsgenieGetContact',
    description: 'Get one contact.',
    tool: opsgenieGetContact,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['fetch'],
  },
  {
    name: 'opsgenieUpdateContact',
    description: 'Update a contact.',
    tool: opsgenieUpdateContact,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['edit'],
  },
  {
    name: 'opsgenieDeleteContact',
    description: 'Delete a contact.',
    tool: opsgenieDeleteContact,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['remove'],
  },
  {
    name: 'opsgenieEnableContact',
    description: 'Enable a contact.',
    tool: opsgenieEnableContact,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['activate'],
  },
  {
    name: 'opsgenieDisableContact',
    description: 'Disable a contact.',
    tool: opsgenieDisableContact,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['mute', 'pause'],
  },
  {
    name: 'opsgenieListNotificationRules',
    description: 'List notification rules.',
    tool: opsgenieListNotificationRules,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['routing', 'preferences'],
  },
  {
    name: 'opsgenieCreateNotificationRule',
    description: 'Create a notification rule.',
    tool: opsgenieCreateNotificationRule,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['routing', 'schedule'],
  },
  {
    name: 'opsgenieGetNotificationRule',
    description: 'Get one notification rule.',
    tool: opsgenieGetNotificationRule,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['fetch'],
  },
  {
    name: 'opsgenieUpdateNotificationRule',
    description: 'Update a notification rule.',
    tool: opsgenieUpdateNotificationRule,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['edit'],
  },
  {
    name: 'opsgenieDeleteNotificationRule',
    description: 'Delete a notification rule.',
    tool: opsgenieDeleteNotificationRule,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['remove'],
  },
  {
    name: 'opsgenieEnableNotificationRule',
    description: 'Enable a notification rule.',
    tool: opsgenieEnableNotificationRule,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['activate'],
  },
  {
    name: 'opsgenieDisableNotificationRule',
    description: 'Disable a notification rule.',
    tool: opsgenieDisableNotificationRule,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['mute'],
  },
  {
    name: 'opsgenieChangeNotificationRuleOrder',
    description: 'Reorder a notification rule.',
    tool: opsgenieChangeNotificationRuleOrder,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['priority'],
  },
  {
    name: 'opsgenieListNotificationRuleSteps',
    description: 'List rule steps.',
    tool: opsgenieListNotificationRuleSteps,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['escalation', 'delay'],
  },
  {
    name: 'opsgenieCreateNotificationRuleStep',
    description: 'Add a rule step.',
    tool: opsgenieCreateNotificationRuleStep,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['contact', 'delay'],
  },
  {
    name: 'opsgenieGetNotificationRuleStep',
    description: 'Get one rule step.',
    tool: opsgenieGetNotificationRuleStep,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['fetch'],
  },
  {
    name: 'opsgenieUpdateNotificationRuleStep',
    description: 'Update a rule step.',
    tool: opsgenieUpdateNotificationRuleStep,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['edit'],
  },
  {
    name: 'opsgenieDeleteNotificationRuleStep',
    description: 'Delete a rule step.',
    tool: opsgenieDeleteNotificationRuleStep,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['remove'],
  },
  {
    name: 'opsgenieEnableNotificationRuleStep',
    description: 'Enable a rule step.',
    tool: opsgenieEnableNotificationRuleStep,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['activate'],
  },
  {
    name: 'opsgenieDisableNotificationRuleStep',
    description: 'Disable a rule step.',
    tool: opsgenieDisableNotificationRuleStep,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['mute'],
  },
  {
    name: 'opsgenieListCustomRoles',
    description: 'List custom user roles.',
    tool: opsgenieListCustomRoles,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['rbac'],
  },
  {
    name: 'opsgenieCreateCustomRole',
    description: 'Create a custom role.',
    tool: opsgenieCreateCustomRole,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['rbac', 'grant'],
  },
  {
    name: 'opsgenieGetCustomRole',
    description: 'Get one custom role.',
    tool: opsgenieGetCustomRole,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['rbac', 'fetch'],
  },
  {
    name: 'opsgenieUpdateCustomRole',
    description: 'Update a custom role.',
    tool: opsgenieUpdateCustomRole,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['rbac', 'edit'],
  },
  {
    name: 'opsgenieDeleteCustomRole',
    description: 'Delete a custom role.',
    tool: opsgenieDeleteCustomRole,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['rbac', 'remove'],
  },
  {
    name: 'opsgenieListForwardingRules',
    description: 'List alert forwarding rules.',
    tool: opsgenieListForwardingRules,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['federation', 'accounts'],
  },
  {
    name: 'opsgenieCreateForwardingRule',
    description: 'Create a forwarding rule.',
    tool: opsgenieCreateForwardingRule,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['federate', 'route'],
  },
  {
    name: 'opsgenieGetForwardingRule',
    description: 'Get one forwarding rule.',
    tool: opsgenieGetForwardingRule,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['fetch'],
  },
  {
    name: 'opsgenieUpdateForwardingRule',
    description: 'Update a forwarding rule.',
    tool: opsgenieUpdateForwardingRule,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['edit'],
  },
  {
    name: 'opsgenieDeleteForwardingRule',
    description: 'Delete a forwarding rule.',
    tool: opsgenieDeleteForwardingRule,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['remove'],
  },
  {
    name: 'opsgenieListEscalations',
    description: 'List escalation policies.',
    tool: opsgenieListEscalations,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['policies', 'paging'],
  },
  {
    name: 'opsgenieGetEscalation',
    description: 'Get one escalation.',
    tool: opsgenieGetEscalation,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['policy', 'fetch'],
  },
  {
    name: 'opsgenieCreateEscalation',
    description: 'Create an escalation policy.',
    tool: opsgenieCreateEscalation,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['policy', 'chain'],
  },
  {
    name: 'opsgenieUpdateEscalation',
    description: 'Update an escalation.',
    tool: opsgenieUpdateEscalation,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['policy', 'edit'],
  },
  {
    name: 'opsgenieDeleteEscalation',
    description: 'Delete an escalation.',
    tool: opsgenieDeleteEscalation,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['policy', 'remove'],
  },
  {
    name: 'opsgenieListIntegrations',
    description: 'List integrations.',
    tool: opsgenieListIntegrations,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['sources', 'vendors'],
  },
  {
    name: 'opsgenieGetIntegration',
    description: 'Get one integration.',
    tool: opsgenieGetIntegration,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['source', 'fetch'],
  },
  {
    name: 'opsgenieCreateIntegration',
    description: 'Create an integration.',
    tool: opsgenieCreateIntegration,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['source', 'onboard'],
  },
  {
    name: 'opsgenieUpdateIntegration',
    description: 'Update an integration.',
    tool: opsgenieUpdateIntegration,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['source', 'edit'],
  },
  {
    name: 'opsgenieDeleteIntegration',
    description: 'Delete an integration.',
    tool: opsgenieDeleteIntegration,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['source', 'remove'],
  },
  {
    name: 'opsgenieEnableIntegration',
    description: 'Enable an integration.',
    tool: opsgenieEnableIntegration,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['activate'],
  },
  {
    name: 'opsgenieDisableIntegration',
    description: 'Disable an integration.',
    tool: opsgenieDisableIntegration,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['pause'],
  },
  {
    name: 'opsgenieAuthenticateIntegration',
    description: 'Authenticate integration key.',
    tool: opsgenieAuthenticateIntegration,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['verify', 'health'],
  },
  {
    name: 'opsgenieListMaintenance',
    description: 'List maintenance windows.',
    tool: opsgenieListMaintenance,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['mute', 'change-freeze'],
  },
  {
    name: 'opsgenieGetMaintenance',
    description: 'Get one maintenance window.',
    tool: opsgenieGetMaintenance,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['fetch'],
  },
  {
    name: 'opsgenieCreateMaintenance',
    description: 'Create a maintenance window.',
    tool: opsgenieCreateMaintenance,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['mute', 'deploy'],
  },
  {
    name: 'opsgenieUpdateMaintenance',
    description: 'Update a maintenance window.',
    tool: opsgenieUpdateMaintenance,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['edit'],
  },
  {
    name: 'opsgenieDeleteMaintenance',
    description: 'Delete a maintenance window.',
    tool: opsgenieDeleteMaintenance,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['remove'],
  },
  {
    name: 'opsgenieCancelMaintenance',
    description: 'Cancel active maintenance early.',
    tool: opsgenieCancelMaintenance,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['stop', 'end'],
  },
  {
    name: 'opsgenieListServices',
    description: 'List services.',
    tool: opsgenieListServices,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['components', 'ownership'],
  },
  {
    name: 'opsgenieGetService',
    description: 'Get one service.',
    tool: opsgenieGetService,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['component', 'fetch'],
  },
  {
    name: 'opsgenieCreateService',
    description: 'Create a service.',
    tool: opsgenieCreateService,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['component', 'onboard'],
  },
  {
    name: 'opsgenieUpdateService',
    description: 'Update a service.',
    tool: opsgenieUpdateService,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['component', 'edit'],
  },
  {
    name: 'opsgenieDeleteService',
    description: 'Delete a service.',
    tool: opsgenieDeleteService,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['component', 'remove'],
  },
  {
    name: 'opsgenieListAlertPolicies',
    description: 'List alert policies.',
    tool: opsgenieListAlertPolicies,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['dedup', 'filter'],
  },
  {
    name: 'opsgenieListNotificationPolicies',
    description: 'List notification policies.',
    tool: opsgenieListNotificationPolicies,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['routing', 'suppress'],
  },
  {
    name: 'opsgenieCreatePolicy',
    description: 'Create a policy.',
    tool: opsgenieCreatePolicy,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['rule', 'automate'],
  },
  {
    name: 'opsgenieGetPolicy',
    description: 'Get one policy.',
    tool: opsgenieGetPolicy,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['rule', 'fetch'],
  },
  {
    name: 'opsgenieUpdatePolicy',
    description: 'Update a policy.',
    tool: opsgenieUpdatePolicy,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['rule', 'edit'],
  },
  {
    name: 'opsgenieDeletePolicy',
    description: 'Delete a policy.',
    tool: opsgenieDeletePolicy,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['rule', 'remove'],
  },
  {
    name: 'opsgenieEnablePolicy',
    description: 'Enable a policy.',
    tool: opsgenieEnablePolicy,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['activate'],
  },
  {
    name: 'opsgenieDisablePolicy',
    description: 'Disable a policy.',
    tool: opsgenieDisablePolicy,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['pause'],
  },
  {
    name: 'opsgenieChangePolicyOrder',
    description: 'Reorder a policy.',
    tool: opsgenieChangePolicyOrder,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['priority'],
  },
  {
    name: 'opsgenieListHeartbeats',
    description: 'List heartbeat monitors.',
    tool: opsgenieListHeartbeats,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['deadman', 'cron', 'health'],
  },
  {
    name: 'opsgenieGetHeartbeat',
    description: 'Get one heartbeat.',
    tool: opsgenieGetHeartbeat,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['deadman', 'fetch'],
  },
  {
    name: 'opsgenieCreateHeartbeat',
    description: 'Create a heartbeat monitor.',
    tool: opsgenieCreateHeartbeat,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['deadman', 'watchdog'],
  },
  {
    name: 'opsgenieUpdateHeartbeat',
    description: 'Update a heartbeat.',
    tool: opsgenieUpdateHeartbeat,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['deadman', 'edit'],
  },
  {
    name: 'opsgenieDeleteHeartbeat',
    description: 'Delete a heartbeat.',
    tool: opsgenieDeleteHeartbeat,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['deadman', 'remove'],
  },
  {
    name: 'opsgeniePingHeartbeat',
    description: 'Send a heartbeat ping.',
    tool: opsgeniePingHeartbeat,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['deadman', 'cron', 'keepalive'],
  },
  {
    name: 'opsgenieEnableHeartbeat',
    description: 'Enable a heartbeat.',
    tool: opsgenieEnableHeartbeat,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['activate'],
  },
  {
    name: 'opsgenieDisableHeartbeat',
    description: 'Disable a heartbeat.',
    tool: opsgenieDisableHeartbeat,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['pause'],
  },
  {
    name: 'opsgenieGetAccountInfo',
    description: 'Get account info; verifies the key.',
    tool: opsgenieGetAccountInfo,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['whoami', 'health', 'plan'],
  },
];
