// @ts-nocheck
import {
  intercomCreateContact,
  intercomGetContact,
  intercomUpdateContactA,
  intercomUpdateContact,
  intercomDeleteContact,
  intercomArchiveContact,
  intercomUnarchiveContact,
  intercomBlockContact,
  intercomMergeLeadAndUser,
  intercomSearchContacts,
  intercomListContacts,
  intercomShowContactByExternalId,
  intercomDeleteVisitor,
  intercomRetrieveVisitor,
  intercomCreateNote,
  intercomListNotes,
  intercomRetrieveNote,
  intercomAttachContactToCompany,
  intercomDetachContactFromCompany,
  intercomListContactCompanies,
  intercomListContactSegments,
  intercomAddTagToContact,
  intercomDetachContactFromTag,
  intercomRemoveTagFromContact,
  intercomListContactTags,
  intercomAddContactSubscription,
  intercomRemoveContactSubscription,
  intercomListContactSubscriptions,
} from './contacts.js';
import {
  intercomCreateOrUpdateCompany,
  intercomRetrieveCompanies,
  intercomRetrieveCompanyById,
  intercomUpdateCompany,
  intercomDeleteCompany,
  intercomListCompanies,
  intercomScrollCompanies,
  intercomListCompanyContacts,
  intercomListCompanySegments,
  intercomListCompanyNotes,
} from './companies.js';
import {
  intercomCreateConversation,
  intercomGetConversation,
  intercomListConversations,
  intercomSearchConversations,
  intercomReplyToConversation,
  intercomCloseConversation,
  intercomReopenConversation,
  intercomAssignConversation,
  intercomAttachContactToConversation,
  intercomAttachTagToConversation,
  intercomDetachTagFromConversation,
} from './conversations.js';
import {
  intercomCreateTicket,
  intercomEnqueueCreateTicket,
  intercomGetTicket,
  intercomUpdateTicket,
  intercomDeleteTicket,
  intercomSearchTickets,
  intercomReplyTicket,
  intercomCreateTicketType,
  intercomGetTicketType,
  intercomListTicketTypes,
  intercomUpdateTicketType,
  intercomCreateTicketTypeAttribute,
  intercomUpdateTicketTypeAttribute,
  intercomListTicketStates,
  intercomAttachTagToTicket,
  intercomDetachTagFromTicket,
} from './tickets.js';
import {
  intercomCreateCollection,
  intercomRetrieveCollection,
  intercomListCollections,
  intercomUpdateCollection,
  intercomDeleteCollection,
  intercomCreateHelpCenterSection,
  intercomListHelpCenterSections,
  intercomListHelpCenters,
  intercomRetrieveHelpCenter,
  intercomCreateArticle,
  intercomRetrieveArticle,
  intercomListArticles,
  intercomUpdateArticle,
  intercomDeleteArticle,
  intercomSearchArticles,
  intercomCreateInternalArticle,
  intercomRetrieveInternalArticle,
  intercomListInternalArticles,
  intercomUpdateInternalArticle,
  intercomDeleteInternalArticle,
  intercomSearchInternalArticles,
  intercomCreateExternalPage,
  intercomGetExternalPage,
  intercomListExternalPages,
  intercomUpdateExternalPage,
  intercomDeleteExternalPage,
  intercomCreateContentImportSource,
  intercomGetContentImportSource,
  intercomListContentImportSources,
  intercomUpdateContentImportSource,
  intercomDeleteContentImportSource,
  intercomListNewsItems,
} from './articles.js';
import {
  intercomCreateDataEvent,
  intercomListDataEvents,
  intercomCreateEventSummaries,
  intercomCreateDataAttribute,
  intercomUpdateDataAttribute,
  intercomListDataAttributes,
  intercomCreateDataExport,
  intercomRetrieveDataExportJob,
  intercomCancelDataExport,
  intercomDownloadDataExport,
  intercomRetrieveJobStatus,
  intercomGetCounts,
  intercomGetCustomObjectInstance,
} from './data.js';
import {
  intercomIdentifyAdmin,
  intercomListAdmins,
  intercomRetrieveAdmin,
  intercomSetAdminAway,
  intercomSetAnAdminAway,
  intercomListActivityLogs,
  intercomListAwayStatusReasons,
  intercomListTeams,
  intercomRetrieveTeam,
  intercomListMacros,
  intercomRetrieveMacro,
  intercomListCalls,
  intercomListCallsWithTranscripts,
  intercomShowCall,
  intercomShowCallTranscript,
  intercomRegisterFinVoiceCall,
} from './admins.js';
import { intercomCreateTag, intercomFindTag, intercomListTags, intercomDeleteTag } from './tags.js';
import { intercomListSegments, intercomRetrieveSegment } from './segments.js';
import { intercomListSubscriptionTypes } from './subscriptions.js';

export {
  intercomCreateContact,
  intercomGetContact,
  intercomUpdateContactA,
  intercomUpdateContact,
  intercomDeleteContact,
  intercomArchiveContact,
  intercomUnarchiveContact,
  intercomBlockContact,
  intercomMergeLeadAndUser,
  intercomSearchContacts,
  intercomListContacts,
  intercomShowContactByExternalId,
  intercomDeleteVisitor,
  intercomRetrieveVisitor,
  intercomCreateNote,
  intercomListNotes,
  intercomRetrieveNote,
  intercomAttachContactToCompany,
  intercomDetachContactFromCompany,
  intercomListContactCompanies,
  intercomListContactSegments,
  intercomAddTagToContact,
  intercomDetachContactFromTag,
  intercomRemoveTagFromContact,
  intercomListContactTags,
  intercomAddContactSubscription,
  intercomRemoveContactSubscription,
  intercomListContactSubscriptions,
  intercomCreateOrUpdateCompany,
  intercomRetrieveCompanies,
  intercomRetrieveCompanyById,
  intercomUpdateCompany,
  intercomDeleteCompany,
  intercomListCompanies,
  intercomScrollCompanies,
  intercomListCompanyContacts,
  intercomListCompanySegments,
  intercomListCompanyNotes,
  intercomCreateConversation,
  intercomGetConversation,
  intercomListConversations,
  intercomSearchConversations,
  intercomReplyToConversation,
  intercomCloseConversation,
  intercomReopenConversation,
  intercomAssignConversation,
  intercomAttachContactToConversation,
  intercomAttachTagToConversation,
  intercomDetachTagFromConversation,
  intercomCreateTicket,
  intercomEnqueueCreateTicket,
  intercomGetTicket,
  intercomUpdateTicket,
  intercomDeleteTicket,
  intercomSearchTickets,
  intercomReplyTicket,
  intercomCreateTicketType,
  intercomGetTicketType,
  intercomListTicketTypes,
  intercomUpdateTicketType,
  intercomCreateTicketTypeAttribute,
  intercomUpdateTicketTypeAttribute,
  intercomListTicketStates,
  intercomAttachTagToTicket,
  intercomDetachTagFromTicket,
  intercomCreateCollection,
  intercomRetrieveCollection,
  intercomListCollections,
  intercomUpdateCollection,
  intercomDeleteCollection,
  intercomCreateHelpCenterSection,
  intercomListHelpCenterSections,
  intercomListHelpCenters,
  intercomRetrieveHelpCenter,
  intercomCreateArticle,
  intercomRetrieveArticle,
  intercomListArticles,
  intercomUpdateArticle,
  intercomDeleteArticle,
  intercomSearchArticles,
  intercomCreateInternalArticle,
  intercomRetrieveInternalArticle,
  intercomListInternalArticles,
  intercomUpdateInternalArticle,
  intercomDeleteInternalArticle,
  intercomSearchInternalArticles,
  intercomCreateExternalPage,
  intercomGetExternalPage,
  intercomListExternalPages,
  intercomUpdateExternalPage,
  intercomDeleteExternalPage,
  intercomCreateContentImportSource,
  intercomGetContentImportSource,
  intercomListContentImportSources,
  intercomUpdateContentImportSource,
  intercomDeleteContentImportSource,
  intercomListNewsItems,
  intercomCreateDataEvent,
  intercomListDataEvents,
  intercomCreateEventSummaries,
  intercomCreateDataAttribute,
  intercomUpdateDataAttribute,
  intercomListDataAttributes,
  intercomCreateDataExport,
  intercomRetrieveDataExportJob,
  intercomCancelDataExport,
  intercomDownloadDataExport,
  intercomRetrieveJobStatus,
  intercomGetCounts,
  intercomGetCustomObjectInstance,
  intercomIdentifyAdmin,
  intercomListAdmins,
  intercomRetrieveAdmin,
  intercomSetAdminAway,
  intercomSetAnAdminAway,
  intercomListActivityLogs,
  intercomListAwayStatusReasons,
  intercomListTeams,
  intercomRetrieveTeam,
  intercomListMacros,
  intercomRetrieveMacro,
  intercomListCalls,
  intercomListCallsWithTranscripts,
  intercomShowCall,
  intercomShowCallTranscript,
  intercomRegisterFinVoiceCall,
  intercomCreateTag,
  intercomFindTag,
  intercomListTags,
  intercomDeleteTag,
  intercomListSegments,
  intercomRetrieveSegment,
  intercomListSubscriptionTypes,
};

const AUTH = 'intercomCredentials' as const;

export const intercomTools = [
  {
    name: 'intercomCreateContact',
    description: 'Create a new contact (user or lead) in the Intercom workspace.',
    tool: intercomCreateContact,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['user', 'lead', 'add', 'new'],
  },
  {
    name: 'intercomGetContact',
    description: 'Fetch the details of a single contact by Intercom ID.',
    tool: intercomGetContact,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['user', 'lead', 'profile', 'fetch'],
  },
  {
    name: 'intercomUpdateContactA',
    description: 'Update a contact by Intercom ID, optionally attaching companies afterwards.',
    tool: intercomUpdateContactA,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['user', 'lead', 'edit', 'modify'],
  },
  {
    name: 'intercomUpdateContact',
    description: 'Update a contact name, email, role, attributes, or subscription flags.',
    tool: intercomUpdateContact,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['user', 'lead', 'edit', 'modify'],
  },
  {
    name: 'intercomDeleteContact',
    description: 'Permanently delete a contact from the Intercom workspace.',
    tool: intercomDeleteContact,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['user', 'lead', 'remove'],
  },
  {
    name: 'intercomArchiveContact',
    description: 'Archive a single contact by ID.',
    tool: intercomArchiveContact,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['user', 'lead', 'hide'],
  },
  {
    name: 'intercomUnarchiveContact',
    description: 'Unarchive (restore) a previously archived contact by ID.',
    tool: intercomUnarchiveContact,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['user', 'lead', 'restore'],
  },
  {
    name: 'intercomBlockContact',
    description: 'Block a contact; their conversations are archived too.',
    tool: intercomBlockContact,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['user', 'lead', 'spam', 'ban'],
  },
  {
    name: 'intercomMergeLeadAndUser',
    description: 'Merge a lead contact into a user contact. The lead is permanently removed.',
    tool: intercomMergeLeadAndUser,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['combine', 'duplicate', 'dedupe'],
  },
  {
    name: 'intercomSearchContacts',
    description: 'Search contacts with field/operator filters, e.g. role equals user.',
    tool: intercomSearchContacts,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['find', 'query', 'filter', 'lookup'],
  },
  {
    name: 'intercomListContacts',
    description: 'List all contacts (users and leads) with cursor pagination.',
    tool: intercomListContacts,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['users', 'leads', 'browse'],
  },
  {
    name: 'intercomShowContactByExternalId',
    description: 'Fetch a contact by your external ID. Users only, not leads.',
    tool: intercomShowContactByExternalId,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['user', 'lookup', 'find'],
  },
  {
    name: 'intercomDeleteVisitor',
    description: 'Permanently delete a visitor record from the workspace.',
    tool: intercomDeleteVisitor,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['remove', 'anonymous'],
  },
  {
    name: 'intercomRetrieveVisitor',
    description: 'Fetch a visitor profile, location, and activity by your user ID.',
    tool: intercomRetrieveVisitor,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['anonymous', 'lookup', 'profile'],
  },
  {
    name: 'intercomCreateNote',
    description: 'Add a note to a single contact.',
    tool: intercomCreateNote,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['comment', 'memo', 'annotate'],
  },
  {
    name: 'intercomListNotes',
    description: 'Fetch notes associated with a contact.',
    tool: intercomListNotes,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['comments', 'memos', 'history'],
  },
  {
    name: 'intercomRetrieveNote',
    description: 'Fetch a single note by note ID.',
    tool: intercomRetrieveNote,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['comment', 'memo', 'fetch'],
  },
  {
    name: 'intercomAttachContactToCompany',
    description: 'Associate a contact with a company.',
    tool: intercomAttachContactToCompany,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['link', 'assign', 'add'],
  },
  {
    name: 'intercomDetachContactFromCompany',
    description: 'Remove a company association from a contact.',
    tool: intercomDetachContactFromCompany,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['unlink', 'remove'],
  },
  {
    name: 'intercomListContactCompanies',
    description: 'Fetch companies associated with a contact.',
    tool: intercomListContactCompanies,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['accounts', 'organizations'],
  },
  {
    name: 'intercomListContactSegments',
    description: 'Fetch segments associated with a contact.',
    tool: intercomListContactSegments,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['groups', 'filters'],
  },
  {
    name: 'intercomAddTagToContact',
    description: 'Attach a tag to a contact for categorization.',
    tool: intercomAddTagToContact,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['label', 'categorize'],
  },
  {
    name: 'intercomDetachContactFromTag',
    description: 'Remove a tag from a contact.',
    tool: intercomDetachContactFromTag,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['untag', 'label', 'remove'],
  },
  {
    name: 'intercomRemoveTagFromContact',
    description: 'Remove a tag from a specific contact, returning the removed tag.',
    tool: intercomRemoveTagFromContact,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['untag', 'label', 'remove'],
  },
  {
    name: 'intercomListContactTags',
    description: 'Fetch all tags attached to a contact.',
    tool: intercomListContactTags,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['labels', 'categories'],
  },
  {
    name: 'intercomAddContactSubscription',
    description: 'Opt a contact in or out of a subscription type.',
    tool: intercomAddContactSubscription,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['consent', 'opt-in', 'opt-out', 'email'],
  },
  {
    name: 'intercomRemoveContactSubscription',
    description: 'Remove a subscription type from a contact.',
    tool: intercomRemoveContactSubscription,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['consent', 'unsubscribe', 'remove'],
  },
  {
    name: 'intercomListContactSubscriptions',
    description: 'Fetch opted-in and opted-out subscription types for a contact.',
    tool: intercomListContactSubscriptions,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['consent', 'preferences'],
  },
  {
    name: 'intercomCreateOrUpdateCompany',
    description: 'Create a company by company_id, or update it when it already exists.',
    tool: intercomCreateOrUpdateCompany,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['account', 'organization', 'upsert'],
  },
  {
    name: 'intercomRetrieveCompanies',
    description: 'Fetch companies filtered by name, company_id, tag, or segment.',
    tool: intercomRetrieveCompanies,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['accounts', 'find', 'filter'],
  },
  {
    name: 'intercomRetrieveCompanyById',
    description: 'Fetch a single company by Intercom ID.',
    tool: intercomRetrieveCompanyById,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['account', 'fetch', 'profile'],
  },
  {
    name: 'intercomUpdateCompany',
    description: 'Update a company by Intercom ID. company_id cannot be changed.',
    tool: intercomUpdateCompany,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['account', 'edit', 'modify'],
  },
  {
    name: 'intercomDeleteCompany',
    description: 'Delete a single company.',
    tool: intercomDeleteCompany,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['account', 'remove'],
  },
  {
    name: 'intercomListCompanies',
    description: 'List companies sorted by recent activity, paginated.',
    tool: intercomListCompanies,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['accounts', 'browse'],
  },
  {
    name: 'intercomScrollCompanies',
    description: 'Iterate all companies efficiently via the scroll API for huge datasets.',
    tool: intercomScrollCompanies,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['accounts', 'export', 'bulk', 'iterate'],
  },
  {
    name: 'intercomListCompanyContacts',
    description: 'Fetch all contacts belonging to a company.',
    tool: intercomListCompanyContacts,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['users', 'members', 'people'],
  },
  {
    name: 'intercomListCompanySegments',
    description: 'Fetch segments that a company belongs to.',
    tool: intercomListCompanySegments,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['groups', 'filters'],
  },
  {
    name: 'intercomListCompanyNotes',
    description: 'Fetch notes added to a company record.',
    tool: intercomListCompanyNotes,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['comments', 'memos'],
  },
  {
    name: 'intercomCreateConversation',
    description:
      'Start a contact-initiated style conversation with a message from a user or contact.',
    tool: intercomCreateConversation,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['message', 'chat', 'new'],
  },
  {
    name: 'intercomGetConversation',
    description: 'Retrieve a conversation with messages and details. Prefer this for full context.',
    tool: intercomGetConversation,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['chat', 'thread', 'transcript', 'fetch'],
  },
  {
    name: 'intercomListConversations',
    description: 'List conversations with cursor pagination. No filtering; use search instead.',
    tool: intercomListConversations,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['chats', 'inbox', 'browse'],
  },
  {
    name: 'intercomSearchConversations',
    description: 'Search conversations by state, dates, assignees, tags, and more.',
    tool: intercomSearchConversations,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['find', 'query', 'filter'],
  },
  {
    name: 'intercomReplyToConversation',
    description: 'Send an admin reply (comment or note) to a conversation. Reply before closing.',
    tool: intercomReplyToConversation,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['answer', 'respond', 'message'],
  },
  {
    name: 'intercomCloseConversation',
    description: 'Close (resolve) a conversation, optionally with a closing message.',
    tool: intercomCloseConversation,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['resolve', 'finish', 'done'],
  },
  {
    name: 'intercomReopenConversation',
    description: 'Reopen a closed conversation, optionally with a message.',
    tool: intercomReopenConversation,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['resume', 'restart', 'open'],
  },
  {
    name: 'intercomAssignConversation',
    description: 'Assign a conversation to an admin or a team.',
    tool: intercomAssignConversation,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['delegate', 'route', 'handoff'],
  },
  {
    name: 'intercomAttachContactToConversation',
    description: 'Add a contact participant to a conversation as an admin.',
    tool: intercomAttachContactToConversation,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['invite', 'participant', 'add'],
  },
  {
    name: 'intercomAttachTagToConversation',
    description: 'Attach a tag to a conversation.',
    tool: intercomAttachTagToConversation,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['label', 'categorize'],
  },
  {
    name: 'intercomDetachTagFromConversation',
    description: 'Remove a tag from a conversation.',
    tool: intercomDetachTagFromConversation,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['untag', 'label', 'remove'],
  },
  {
    name: 'intercomCreateTicket',
    description: 'Create a support ticket for contacts with type, attributes, and assignment.',
    tool: intercomCreateTicket,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['issue', 'request', 'case', 'new'],
  },
  {
    name: 'intercomEnqueueCreateTicket',
    description: 'Enqueue ticket creation for async processing with validation first.',
    tool: intercomEnqueueCreateTicket,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['issue', 'async', 'background', 'bulk'],
  },
  {
    name: 'intercomGetTicket',
    description: 'Fetch a ticket with state, type, attributes, and contacts.',
    tool: intercomGetTicket,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['issue', 'fetch', 'details'],
  },
  {
    name: 'intercomUpdateTicket',
    description: 'Update ticket attributes, state, assignment, sharing, or snooze.',
    tool: intercomUpdateTicket,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['issue', 'edit', 'modify', 'assign'],
  },
  {
    name: 'intercomDeleteTicket',
    description: 'Permanently delete a ticket.',
    tool: intercomDeleteTicket,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['issue', 'remove'],
  },
  {
    name: 'intercomSearchTickets',
    description: 'Search tickets by state, dates, assignees, or custom attributes.',
    tool: intercomSearchTickets,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['issues', 'find', 'query', 'filter'],
  },
  {
    name: 'intercomReplyTicket',
    description: 'Reply to a ticket as an admin (comment/note) or on behalf of a contact.',
    tool: intercomReplyTicket,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['answer', 'respond', 'comment'],
  },
  {
    name: 'intercomCreateTicketType',
    description: 'Create a ticket type defining structure and workflow for tickets.',
    tool: intercomCreateTicketType,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['category', 'template', 'schema'],
  },
  {
    name: 'intercomGetTicketType',
    description: 'Fetch a ticket type with attributes and states.',
    tool: intercomGetTicketType,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['category', 'template', 'fetch'],
  },
  {
    name: 'intercomListTicketTypes',
    description: 'List all ticket types in the workspace.',
    tool: intercomListTicketTypes,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['categories', 'templates'],
  },
  {
    name: 'intercomUpdateTicketType',
    description: 'Update a ticket type name, description, category, icon, or archive flag.',
    tool: intercomUpdateTicketType,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['category', 'edit', 'rename'],
  },
  {
    name: 'intercomCreateTicketTypeAttribute',
    description: 'Add a custom attribute field to a ticket type.',
    tool: intercomCreateTicketTypeAttribute,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['field', 'custom', 'schema'],
  },
  {
    name: 'intercomUpdateTicketTypeAttribute',
    description: 'Update a ticket type attribute description, visibility, or requirements.',
    tool: intercomUpdateTicketTypeAttribute,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['field', 'edit'],
  },
  {
    name: 'intercomListTicketStates',
    description: 'Fetch all ticket states including archived ones.',
    tool: intercomListTicketStates,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['statuses', 'workflow'],
  },
  {
    name: 'intercomAttachTagToTicket',
    description: 'Attach a tag to a ticket.',
    tool: intercomAttachTagToTicket,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['label', 'categorize'],
  },
  {
    name: 'intercomDetachTagFromTicket',
    description: 'Remove a tag from a ticket.',
    tool: intercomDetachTagFromTicket,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['untag', 'label', 'remove'],
  },
  {
    name: 'intercomCreateCollection',
    description: 'Create a help center collection, optionally nested or translated.',
    tool: intercomCreateCollection,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['help-center', 'folder', 'category'],
  },
  {
    name: 'intercomRetrieveCollection',
    description: 'Fetch a single help center collection by ID.',
    tool: intercomRetrieveCollection,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['help-center', 'fetch'],
  },
  {
    name: 'intercomListCollections',
    description: 'List help center collections, most recently updated first.',
    tool: intercomListCollections,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['help-center', 'browse'],
  },
  {
    name: 'intercomUpdateCollection',
    description: 'Update a help center collection name, description, or parent.',
    tool: intercomUpdateCollection,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['help-center', 'edit', 'rename'],
  },
  {
    name: 'intercomDeleteCollection',
    description: 'Delete a help center collection.',
    tool: intercomDeleteCollection,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['help-center', 'remove'],
  },
  {
    name: 'intercomCreateHelpCenterSection',
    description: 'Create a help center section inside a collection for organizing articles.',
    tool: intercomCreateHelpCenterSection,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['help-center', 'subsection', 'category'],
  },
  {
    name: 'intercomListHelpCenterSections',
    description: 'List help center sections, most recently updated first.',
    tool: intercomListHelpCenterSections,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['help-center', 'browse'],
  },
  {
    name: 'intercomListHelpCenters',
    description: 'List all help centers in the workspace.',
    tool: intercomListHelpCenters,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['help-center', 'sites'],
  },
  {
    name: 'intercomRetrieveHelpCenter',
    description: 'Fetch a single help center by ID.',
    tool: intercomRetrieveHelpCenter,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['help-center', 'fetch'],
  },
  {
    name: 'intercomCreateArticle',
    description: 'Create a help center article as draft or published.',
    tool: intercomCreateArticle,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['docs', 'knowledge', 'post', 'new'],
  },
  {
    name: 'intercomRetrieveArticle',
    description: 'Fetch a single article with statistics.',
    tool: intercomRetrieveArticle,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['docs', 'fetch'],
  },
  {
    name: 'intercomListArticles',
    description: 'List articles, most recently updated first.',
    tool: intercomListArticles,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['docs', 'browse'],
  },
  {
    name: 'intercomUpdateArticle',
    description: 'Update an article title, body, state, author, or parent.',
    tool: intercomUpdateArticle,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['docs', 'edit'],
  },
  {
    name: 'intercomDeleteArticle',
    description: 'Delete a single article.',
    tool: intercomDeleteArticle,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['docs', 'remove'],
  },
  {
    name: 'intercomSearchArticles',
    description: 'Search articles by phrase, state, and help center.',
    tool: intercomSearchArticles,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['docs', 'find', 'query'],
  },
  {
    name: 'intercomCreateInternalArticle',
    description: 'Create an internal team knowledge article.',
    tool: intercomCreateInternalArticle,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['docs', 'internal', 'wiki', 'new'],
  },
  {
    name: 'intercomRetrieveInternalArticle',
    description: 'Fetch a single internal article by ID.',
    tool: intercomRetrieveInternalArticle,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['docs', 'internal', 'fetch'],
  },
  {
    name: 'intercomListInternalArticles',
    description: 'List internal articles with cursor pagination.',
    tool: intercomListInternalArticles,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['docs', 'internal', 'browse'],
  },
  {
    name: 'intercomUpdateInternalArticle',
    description: 'Update an internal article title, body, author, or owner.',
    tool: intercomUpdateInternalArticle,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['docs', 'internal', 'edit'],
  },
  {
    name: 'intercomDeleteInternalArticle',
    description: 'Permanently delete an internal article.',
    tool: intercomDeleteInternalArticle,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['docs', 'internal', 'remove'],
  },
  {
    name: 'intercomSearchInternalArticles',
    description: 'Search internal articles, optionally within a folder.',
    tool: intercomSearchInternalArticles,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['docs', 'internal', 'find'],
  },
  {
    name: 'intercomCreateExternalPage',
    description:
      'Ingest an external page into the Fin content library (upserts on source plus external ID).',
    tool: intercomCreateExternalPage,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['fin', 'ai', 'knowledge', 'docs'],
  },
  {
    name: 'intercomGetExternalPage',
    description: 'Fetch an external page with content and AI availability.',
    tool: intercomGetExternalPage,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['fin', 'ai', 'fetch'],
  },
  {
    name: 'intercomListExternalPages',
    description: 'List external pages in the Fin content library.',
    tool: intercomListExternalPages,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['fin', 'ai', 'browse'],
  },
  {
    name: 'intercomUpdateExternalPage',
    description: 'Update an API-created external page content, metadata, or availability.',
    tool: intercomUpdateExternalPage,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['fin', 'ai', 'edit'],
  },
  {
    name: 'intercomDeleteExternalPage',
    description: 'Delete an external page from the content library and AI answers.',
    tool: intercomDeleteExternalPage,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['fin', 'ai', 'remove'],
  },
  {
    name: 'intercomCreateContentImportSource',
    description: 'Create a container for external pages ingested into Fin.',
    tool: intercomCreateContentImportSource,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['fin', 'ai', 'source', 'crawl'],
  },
  {
    name: 'intercomGetContentImportSource',
    description: 'Fetch a content import source by ID.',
    tool: intercomGetContentImportSource,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['fin', 'ai', 'fetch'],
  },
  {
    name: 'intercomListContentImportSources',
    description: 'List content import sources for the workspace.',
    tool: intercomListContentImportSources,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['fin', 'ai', 'browse'],
  },
  {
    name: 'intercomUpdateContentImportSource',
    description: 'Update a content import source URL, sync behavior, or status.',
    tool: intercomUpdateContentImportSource,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['fin', 'ai', 'edit'],
  },
  {
    name: 'intercomDeleteContentImportSource',
    description: 'Delete a content import source and all its external pages. Permanent.',
    tool: intercomDeleteContentImportSource,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['fin', 'ai', 'remove'],
  },
  {
    name: 'intercomListNewsItems',
    description: 'Fetch news items posted in the workspace.',
    tool: intercomListNewsItems,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['announcements', 'updates', 'feed'],
  },
  {
    name: 'intercomCreateDataEvent',
    description: 'Track a user activity event with optional metadata. Duplicates are ignored.',
    tool: intercomCreateDataEvent,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['track', 'analytics', 'activity'],
  },
  {
    name: 'intercomListDataEvents',
    description: 'List events for a customer from the last 90 days.',
    tool: intercomListDataEvents,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['track', 'history', 'activity'],
  },
  {
    name: 'intercomCreateEventSummaries',
    description: 'Bulk set event counts with first/last timestamps for a user.',
    tool: intercomCreateEventSummaries,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['track', 'aggregate', 'bulk'],
  },
  {
    name: 'intercomCreateDataAttribute',
    description: 'Define a custom data attribute for contacts or companies.',
    tool: intercomCreateDataAttribute,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['field', 'custom', 'schema'],
  },
  {
    name: 'intercomUpdateDataAttribute',
    description: 'Update a data attribute description, archive flag, or writability.',
    tool: intercomUpdateDataAttribute,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['field', 'edit'],
  },
  {
    name: 'intercomListDataAttributes',
    description: 'List data attributes for contacts or companies.',
    tool: intercomListDataAttributes,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['fields', 'schema', 'browse'],
  },
  {
    name: 'intercomCreateDataExport',
    description: 'Start an async message-engagement data export job for a time range.',
    tool: intercomCreateDataExport,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['export', 'download', 'report'],
  },
  {
    name: 'intercomRetrieveDataExportJob',
    description: 'Check a data export job status and download URL. Jobs expire after two days.',
    tool: intercomRetrieveDataExportJob,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['export', 'status', 'download'],
  },
  {
    name: 'intercomCancelDataExport',
    description: 'Cancel an active data export job.',
    tool: intercomCancelDataExport,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['export', 'stop', 'abort'],
  },
  {
    name: 'intercomDownloadDataExport',
    description: 'Download a completed export as gzipped CSV (base64, capped).',
    tool: intercomDownloadDataExport,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['export', 'file', 'csv'],
  },
  {
    name: 'intercomRetrieveJobStatus',
    description: 'Check an async bulk job status, e.g. from enqueued ticket creation.',
    tool: intercomRetrieveJobStatus,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['queue', 'background', 'progress'],
  },
  {
    name: 'intercomGetCounts',
    description:
      'Get entity counts: app totals, conversation states, or per-tag/segment/user breakdowns.',
    tool: intercomGetCounts,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['stats', 'totals', 'metrics'],
  },
  {
    name: 'intercomGetCustomObjectInstance',
    description: 'Fetch a custom object instance by your external ID.',
    tool: intercomGetCustomObjectInstance,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['custom', 'order', 'record', 'lookup'],
  },
  {
    name: 'intercomIdentifyAdmin',
    description: 'Identify the authorized admin and workspace. Start here to resolve IDs.',
    tool: intercomIdentifyAdmin,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['me', 'whoami', 'profile'],
  },
  {
    name: 'intercomListAdmins',
    description: 'Fetch teammates with inbox seats, away state, and teams.',
    tool: intercomListAdmins,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['teammates', 'agents', 'staff'],
  },
  {
    name: 'intercomRetrieveAdmin',
    description: 'Fetch a single admin by ID.',
    tool: intercomRetrieveAdmin,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['teammate', 'agent', 'fetch'],
  },
  {
    name: 'intercomSetAdminAway',
    description: 'Set an admin away, optionally reassigning new replies and giving a reason.',
    tool: intercomSetAdminAway,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['status', 'offline', 'vacation'],
  },
  {
    name: 'intercomSetAnAdminAway',
    description: 'Set an admin away for the inbox with reassignment control.',
    tool: intercomSetAnAdminAway,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['status', 'offline', 'vacation'],
  },
  {
    name: 'intercomListActivityLogs',
    description: 'Audit log of admin actions in a time window.',
    tool: intercomListActivityLogs,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['audit', 'history', 'security'],
  },
  {
    name: 'intercomListAwayStatusReasons',
    description: 'List away status reasons including deleted ones.',
    tool: intercomListAwayStatusReasons,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['status', 'labels'],
  },
  {
    name: 'intercomListTeams',
    description: 'List teams with members and assignment config.',
    tool: intercomListTeams,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['groups', 'departments', 'inbox'],
  },
  {
    name: 'intercomRetrieveTeam',
    description: 'Fetch a single team by ID.',
    tool: intercomRetrieveTeam,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['group', 'fetch'],
  },
  {
    name: 'intercomListMacros',
    description: 'List saved replies (macros), newest first, with cursor pagination.',
    tool: intercomListMacros,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['canned', 'replies', 'templates'],
  },
  {
    name: 'intercomRetrieveMacro',
    description: 'Fetch a single saved reply by ID when visible to you.',
    tool: intercomRetrieveMacro,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['canned', 'template', 'fetch'],
  },
  {
    name: 'intercomListCalls',
    description: 'List phone calls with pagination.',
    tool: intercomListCalls,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['phone', 'voice', 'history'],
  },
  {
    name: 'intercomListCallsWithTranscripts',
    description: 'Fetch calls with transcripts for up to 20 conversations.',
    tool: intercomListCallsWithTranscripts,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['phone', 'transcript', 'recordings'],
  },
  {
    name: 'intercomShowCall',
    description: 'Fetch a single call with recording and transcript URLs.',
    tool: intercomShowCall,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['phone', 'fetch', 'details'],
  },
  {
    name: 'intercomShowCallTranscript',
    description: 'Get a call transcript as text. Long transcripts are truncated.',
    tool: intercomShowCallTranscript,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['phone', 'transcript', 'text'],
  },
  {
    name: 'intercomRegisterFinVoiceCall',
    description: 'Register an external voice call for Fin analysis and tracking.',
    tool: intercomRegisterFinVoiceCall,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['phone', 'fin', 'ai', 'external'],
  },
  {
    name: 'intercomCreateTag',
    description: 'Create or update a tag, optionally tagging users and companies.',
    tool: intercomCreateTag,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['label', 'categorize', 'new'],
  },
  {
    name: 'intercomFindTag',
    description: 'Fetch a tag by ID.',
    tool: intercomFindTag,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['label', 'fetch', 'lookup'],
  },
  {
    name: 'intercomListTags',
    description: 'Fetch all workspace tags.',
    tool: intercomListTags,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['labels', 'browse'],
  },
  {
    name: 'intercomDeleteTag',
    description: 'Permanently delete a tag from the workspace.',
    tool: intercomDeleteTag,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['label', 'remove'],
  },
  {
    name: 'intercomListSegments',
    description: 'List segments for filtering and categorizing contacts.',
    tool: intercomListSegments,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['groups', 'filters', 'browse'],
  },
  {
    name: 'intercomRetrieveSegment',
    description: 'Fetch a single segment by ID with optional contact count.',
    tool: intercomRetrieveSegment,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['group', 'fetch'],
  },
  {
    name: 'intercomListSubscriptionTypes',
    description: 'List subscription types with consent mode and translations.',
    tool: intercomListSubscriptionTypes,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['consent', 'preferences', 'opt-in'],
  },
];
