// @ts-nocheck
import {
    slackSendMessage,
    slackUpdateMessage,
    slackDeleteMessage,
    slackScheduleMessage,
    slackListScheduledMessages,
    slackDeleteScheduledMessage,
    slackGetMessagePermalink,
    slackSendMeMessage,
    slackSendEphemeralMessage,
    slackListUnreadChannelMessages,
    slackGetUnreadMessagesFromUser,
} from './messages.js';
import {
    slackListAllChannels,
    slackFindChannels,
    slackListConversations,
    slackGetConversationInfo,
    slackGetConversationMembers,
    slackGetConversationHistory,
    slackGetConversationReplies,
    slackCreateChannel,
    slackArchiveChannel,
    slackUnarchiveChannel,
    slackCloseDm,
    slackJoinConversation,
    slackLeaveConversation,
    slackRenameConversation,
    slackSetConversationTopic,
    slackSetConversationPurpose,
    slackMarkConversationRead,
    slackInviteUsersToChannel,
    slackRemoveUserFromConversation,
    slackOpenDm,
} from './conversations.js';
import {
    slackAdminSearchConversations,
    slackAdminCreateConversation,
    slackDeleteChannel,
    slackConvertChannelToPrivate,
    slackInviteUserToChannelAdmin,
    slackGetConversationPrefs,
    slackSetConversationPrefs,
    slackGetChannelWorkspaces,
    slackSetChannelWorkspaces,
    slackListChannelIdpGroups,
} from './admin-conversations.js';
import {
    slackListUsers,
    slackFindUsers,
    slackFindUserByEmail,
    slackGetUserInfo,
    slackGetUserProfile,
    slackSetUserProfile,
    slackGetUserPresence,
    slackSetUserPresence,
    slackEndDnd,
    slackEndSnooze,
    slackSetDndDuration,
    slackGetDndStatus,
    slackGetTeamDndStatus,
    slackDeleteUserPhoto,
    slackSetUserPhoto,
    slackGetUserIdentity,
    slackGetBotInfo,
} from './users.js';
import {
    slackAddEnterpriseUserToWorkspace,
    slackInviteUserToWorkspace,
    slackRemoveUserFromWorkspace,
    slackSetAdminUser,
    slackSetWorkspaceOwner,
    slackResetUserSessions,
    slackListWorkspaceUsers,
} from './admin-users.js';
import {
    slackGetTeamInfo,
    slackGetTeamProfile,
    slackListAuthTeams,
    slackListAvailableWorkspaces,
    slackCreateEnterpriseTeam,
    slackListEnterpriseTeams,
    slackListWorkspaceAdmins,
    slackListWorkspaceOwners,
    slackGetWorkspaceSettings,
    slackSetWorkspaceName,
    slackSetWorkspaceDescription,
    slackSetWorkspaceIcon,
    slackSetWorkspaceDefaultChannels,
} from './teams.js';
import {
    slackListFiles,
    slackGetFileInfo,
    slackDeleteFile,
    slackDeleteFileComment,
    slackShareFilePublicUrl,
    slackRevokeFilePublicUrl,
    slackDownloadFile,
    slackUploadFile,
    slackAddRemoteFile,
    slackGetRemoteFile,
    slackUpdateRemoteFile,
    slackRemoveRemoteFile,
    slackShareRemoteFile,
    slackListRemoteFiles,
} from './files.js';
import {
    slackAddReaction,
    slackRemoveReaction,
    slackGetReactions,
    slackListUserReactions,
    slackAddStar,
    slackRemoveStar,
    slackListStarredItems,
    slackPinItem,
    slackUnpinItem,
    slackListPinnedItems,
} from './reactions-stars-pins.js';
import {
    slackCreateReminder,
    slackGetReminder,
    slackListReminders,
    slackDeleteReminder,
} from './reminders.js';
import {
    slackSearchAll,
    slackSearchMessages,
    slackAssistantSearch,
    slackGetSearchInfo,
} from './search.js';
import {
    slackStartCall,
    slackGetCallInfo,
    slackUpdateCallInfo,
    slackEndCall,
    slackAddCallParticipants,
    slackRemoveCallParticipants,
} from './calls.js';
import {
    slackCreateCanvas,
    slackEditCanvas,
    slackDeleteCanvas,
    slackLookupCanvasSections,
} from './canvas.js';
import {
    slackCreateList,
    slackCreateListItem,
    slackGetListItem,
    slackListListItems,
    slackUpdateList,
    slackUpdateListItem,
    slackDeleteListItem,
    slackDeleteListItems,
    slackSetListAccess,
    slackDeleteListAccess,
} from './slack-lists.js';
import {
    slackCreateUserGroup,
    slackUpdateUserGroup,
    slackUpdateUserGroupMembers,
    slackListUserGroups,
    slackListUserGroupMembers,
    slackEnableUserGroup,
    slackDisableUserGroup,
} from './usergroups.js';
import {
    slackAddEmoji,
    slackAddEmojiAlias,
    slackRenameEmoji,
    slackRemoveEmoji,
    slackListCustomEmojis,
    slackListAdminEmoji,
} from './emoji.js';
import {
    slackListApprovedApps,
    slackListAppRequests,
    slackListRestrictedApps,
    slackRestrictApp,
} from './admin-apps.js';
import {
    slackListApprovedInvites,
    slackListDeniedInvites,
    slackListPendingInvites,
} from './admin-invites.js';
import {
    slackReadAuditLogs,
    slackGetAuditActions,
    slackGetAuditSchemas,
    slackGetScimConfig,
} from './audit.js';
import {
    slackCustomizeUnfurl,
    slackApiTest,
    slackTestAuth,
    slackWhoAmI,
    slackRtmConnect,
} from './misc.js';

export {
    slackSendMessage,
    slackUpdateMessage,
    slackDeleteMessage,
    slackScheduleMessage,
    slackListScheduledMessages,
    slackDeleteScheduledMessage,
    slackGetMessagePermalink,
    slackSendMeMessage,
    slackSendEphemeralMessage,
    slackListUnreadChannelMessages,
    slackGetUnreadMessagesFromUser,
    slackListAllChannels,
    slackFindChannels,
    slackListConversations,
    slackGetConversationInfo,
    slackGetConversationMembers,
    slackGetConversationHistory,
    slackGetConversationReplies,
    slackCreateChannel,
    slackArchiveChannel,
    slackUnarchiveChannel,
    slackCloseDm,
    slackJoinConversation,
    slackLeaveConversation,
    slackRenameConversation,
    slackSetConversationTopic,
    slackSetConversationPurpose,
    slackMarkConversationRead,
    slackInviteUsersToChannel,
    slackRemoveUserFromConversation,
    slackOpenDm,
    slackAdminSearchConversations,
    slackAdminCreateConversation,
    slackDeleteChannel,
    slackConvertChannelToPrivate,
    slackInviteUserToChannelAdmin,
    slackGetConversationPrefs,
    slackSetConversationPrefs,
    slackGetChannelWorkspaces,
    slackSetChannelWorkspaces,
    slackListChannelIdpGroups,
    slackListUsers,
    slackFindUsers,
    slackFindUserByEmail,
    slackGetUserInfo,
    slackGetUserProfile,
    slackSetUserProfile,
    slackGetUserPresence,
    slackSetUserPresence,
    slackEndDnd,
    slackEndSnooze,
    slackSetDndDuration,
    slackGetDndStatus,
    slackGetTeamDndStatus,
    slackDeleteUserPhoto,
    slackSetUserPhoto,
    slackGetUserIdentity,
    slackGetBotInfo,
    slackAddEnterpriseUserToWorkspace,
    slackInviteUserToWorkspace,
    slackRemoveUserFromWorkspace,
    slackSetAdminUser,
    slackSetWorkspaceOwner,
    slackResetUserSessions,
    slackListWorkspaceUsers,
    slackGetTeamInfo,
    slackGetTeamProfile,
    slackListAuthTeams,
    slackListAvailableWorkspaces,
    slackCreateEnterpriseTeam,
    slackListEnterpriseTeams,
    slackListWorkspaceAdmins,
    slackListWorkspaceOwners,
    slackGetWorkspaceSettings,
    slackSetWorkspaceName,
    slackSetWorkspaceDescription,
    slackSetWorkspaceIcon,
    slackSetWorkspaceDefaultChannels,
    slackListFiles,
    slackGetFileInfo,
    slackDeleteFile,
    slackDeleteFileComment,
    slackShareFilePublicUrl,
    slackRevokeFilePublicUrl,
    slackDownloadFile,
    slackUploadFile,
    slackAddRemoteFile,
    slackGetRemoteFile,
    slackUpdateRemoteFile,
    slackRemoveRemoteFile,
    slackShareRemoteFile,
    slackListRemoteFiles,
    slackAddReaction,
    slackRemoveReaction,
    slackGetReactions,
    slackListUserReactions,
    slackAddStar,
    slackRemoveStar,
    slackListStarredItems,
    slackPinItem,
    slackUnpinItem,
    slackListPinnedItems,
    slackCreateReminder,
    slackGetReminder,
    slackListReminders,
    slackDeleteReminder,
    slackSearchAll,
    slackSearchMessages,
    slackAssistantSearch,
    slackGetSearchInfo,
    slackStartCall,
    slackGetCallInfo,
    slackUpdateCallInfo,
    slackEndCall,
    slackAddCallParticipants,
    slackRemoveCallParticipants,
    slackCreateCanvas,
    slackEditCanvas,
    slackDeleteCanvas,
    slackLookupCanvasSections,
    slackCreateList,
    slackCreateListItem,
    slackGetListItem,
    slackListListItems,
    slackUpdateList,
    slackUpdateListItem,
    slackDeleteListItem,
    slackDeleteListItems,
    slackSetListAccess,
    slackDeleteListAccess,
    slackCreateUserGroup,
    slackUpdateUserGroup,
    slackUpdateUserGroupMembers,
    slackListUserGroups,
    slackListUserGroupMembers,
    slackEnableUserGroup,
    slackDisableUserGroup,
    slackAddEmoji,
    slackAddEmojiAlias,
    slackRenameEmoji,
    slackRemoveEmoji,
    slackListCustomEmojis,
    slackListAdminEmoji,
    slackListApprovedApps,
    slackListAppRequests,
    slackListRestrictedApps,
    slackRestrictApp,
    slackListApprovedInvites,
    slackListDeniedInvites,
    slackListPendingInvites,
    slackReadAuditLogs,
    slackGetAuditActions,
    slackGetAuditSchemas,
    slackGetScimConfig,
    slackCustomizeUnfurl,
    slackApiTest,
    slackTestAuth,
    slackWhoAmI,
    slackRtmConnect,
};

const R = 'slackToken' as const;

function t(tool: any, scope: 'read' | 'write' | 'delete', name?: string) {
    return { name: name ?? tool?.name ?? 'unknown', description: tool?.description ?? '', tool, requiredAuth: R, scope };
}

export const slackTools = [
    t(slackSendMessage, 'write', 'slackSendMessage'),
    t(slackUpdateMessage, 'write', 'slackUpdateMessage'),
    t(slackDeleteMessage, 'delete', 'slackDeleteMessage'),
    t(slackScheduleMessage, 'write', 'slackScheduleMessage'),
    t(slackListScheduledMessages, 'read', 'slackListScheduledMessages'),
    t(slackDeleteScheduledMessage, 'delete', 'slackDeleteScheduledMessage'),
    t(slackGetMessagePermalink, 'read', 'slackGetMessagePermalink'),
    t(slackSendMeMessage, 'write', 'slackSendMeMessage'),
    t(slackSendEphemeralMessage, 'write', 'slackSendEphemeralMessage'),
    t(slackListUnreadChannelMessages, 'read', 'slackListUnreadChannelMessages'),
    t(slackGetUnreadMessagesFromUser, 'read', 'slackGetUnreadMessagesFromUser'),
    t(slackListAllChannels, 'read', 'slackListAllChannels'),
    t(slackFindChannels, 'read', 'slackFindChannels'),
    t(slackListConversations, 'read', 'slackListConversations'),
    t(slackGetConversationInfo, 'read', 'slackGetConversationInfo'),
    t(slackGetConversationMembers, 'read', 'slackGetConversationMembers'),
    t(slackGetConversationHistory, 'read', 'slackGetConversationHistory'),
    t(slackGetConversationReplies, 'read', 'slackGetConversationReplies'),
    t(slackCreateChannel, 'write', 'slackCreateChannel'),
    t(slackArchiveChannel, 'write', 'slackArchiveChannel'),
    t(slackUnarchiveChannel, 'write', 'slackUnarchiveChannel'),
    t(slackCloseDm, 'write', 'slackCloseDm'),
    t(slackJoinConversation, 'write', 'slackJoinConversation'),
    t(slackLeaveConversation, 'write', 'slackLeaveConversation'),
    t(slackRenameConversation, 'write', 'slackRenameConversation'),
    t(slackSetConversationTopic, 'write', 'slackSetConversationTopic'),
    t(slackSetConversationPurpose, 'write', 'slackSetConversationPurpose'),
    t(slackMarkConversationRead, 'write', 'slackMarkConversationRead'),
    t(slackInviteUsersToChannel, 'write', 'slackInviteUsersToChannel'),
    t(slackRemoveUserFromConversation, 'delete', 'slackRemoveUserFromConversation'),
    t(slackOpenDm, 'write', 'slackOpenDm'),
    t(slackAdminSearchConversations, 'read', 'slackAdminSearchConversations'),
    t(slackAdminCreateConversation, 'write', 'slackAdminCreateConversation'),
    t(slackDeleteChannel, 'delete', 'slackDeleteChannel'),
    t(slackConvertChannelToPrivate, 'write', 'slackConvertChannelToPrivate'),
    t(slackInviteUserToChannelAdmin, 'write', 'slackInviteUserToChannelAdmin'),
    t(slackGetConversationPrefs, 'read', 'slackGetConversationPrefs'),
    t(slackSetConversationPrefs, 'write', 'slackSetConversationPrefs'),
    t(slackGetChannelWorkspaces, 'read', 'slackGetChannelWorkspaces'),
    t(slackSetChannelWorkspaces, 'write', 'slackSetChannelWorkspaces'),
    t(slackListChannelIdpGroups, 'read', 'slackListChannelIdpGroups'),
    t(slackListUsers, 'read', 'slackListUsers'),
    t(slackFindUsers, 'read', 'slackFindUsers'),
    t(slackFindUserByEmail, 'read', 'slackFindUserByEmail'),
    t(slackGetUserInfo, 'read', 'slackGetUserInfo'),
    t(slackGetUserProfile, 'read', 'slackGetUserProfile'),
    t(slackSetUserProfile, 'write', 'slackSetUserProfile'),
    t(slackGetUserPresence, 'read', 'slackGetUserPresence'),
    t(slackSetUserPresence, 'write', 'slackSetUserPresence'),
    t(slackEndDnd, 'write', 'slackEndDnd'),
    t(slackEndSnooze, 'write', 'slackEndSnooze'),
    t(slackSetDndDuration, 'write', 'slackSetDndDuration'),
    t(slackGetDndStatus, 'read', 'slackGetDndStatus'),
    t(slackGetTeamDndStatus, 'read', 'slackGetTeamDndStatus'),
    t(slackDeleteUserPhoto, 'delete', 'slackDeleteUserPhoto'),
    t(slackSetUserPhoto, 'write', 'slackSetUserPhoto'),
    t(slackGetUserIdentity, 'read', 'slackGetUserIdentity'),
    t(slackGetBotInfo, 'read', 'slackGetBotInfo'),
    t(slackAddEnterpriseUserToWorkspace, 'write', 'slackAddEnterpriseUserToWorkspace'),
    t(slackInviteUserToWorkspace, 'write', 'slackInviteUserToWorkspace'),
    t(slackRemoveUserFromWorkspace, 'delete', 'slackRemoveUserFromWorkspace'),
    t(slackSetAdminUser, 'write', 'slackSetAdminUser'),
    t(slackSetWorkspaceOwner, 'write', 'slackSetWorkspaceOwner'),
    t(slackResetUserSessions, 'write', 'slackResetUserSessions'),
    t(slackListWorkspaceUsers, 'read', 'slackListWorkspaceUsers'),
    t(slackGetTeamInfo, 'read', 'slackGetTeamInfo'),
    t(slackGetTeamProfile, 'read', 'slackGetTeamProfile'),
    t(slackListAuthTeams, 'read', 'slackListAuthTeams'),
    t(slackListAvailableWorkspaces, 'read', 'slackListAvailableWorkspaces'),
    t(slackCreateEnterpriseTeam, 'write', 'slackCreateEnterpriseTeam'),
    t(slackListEnterpriseTeams, 'read', 'slackListEnterpriseTeams'),
    t(slackListWorkspaceAdmins, 'read', 'slackListWorkspaceAdmins'),
    t(slackListWorkspaceOwners, 'read', 'slackListWorkspaceOwners'),
    t(slackGetWorkspaceSettings, 'read', 'slackGetWorkspaceSettings'),
    t(slackSetWorkspaceName, 'write', 'slackSetWorkspaceName'),
    t(slackSetWorkspaceDescription, 'write', 'slackSetWorkspaceDescription'),
    t(slackSetWorkspaceIcon, 'write', 'slackSetWorkspaceIcon'),
    t(slackSetWorkspaceDefaultChannels, 'write', 'slackSetWorkspaceDefaultChannels'),
    t(slackListFiles, 'read', 'slackListFiles'),
    t(slackGetFileInfo, 'read', 'slackGetFileInfo'),
    t(slackDeleteFile, 'delete', 'slackDeleteFile'),
    t(slackDeleteFileComment, 'delete', 'slackDeleteFileComment'),
    t(slackShareFilePublicUrl, 'write', 'slackShareFilePublicUrl'),
    t(slackRevokeFilePublicUrl, 'write', 'slackRevokeFilePublicUrl'),
    t(slackDownloadFile, 'read', 'slackDownloadFile'),
    t(slackUploadFile, 'write', 'slackUploadFile'),
    t(slackAddRemoteFile, 'write', 'slackAddRemoteFile'),
    t(slackGetRemoteFile, 'read', 'slackGetRemoteFile'),
    t(slackUpdateRemoteFile, 'write', 'slackUpdateRemoteFile'),
    t(slackRemoveRemoteFile, 'delete', 'slackRemoveRemoteFile'),
    t(slackShareRemoteFile, 'write', 'slackShareRemoteFile'),
    t(slackListRemoteFiles, 'read', 'slackListRemoteFiles'),
    t(slackAddReaction, 'write', 'slackAddReaction'),
    t(slackRemoveReaction, 'delete', 'slackRemoveReaction'),
    t(slackGetReactions, 'read', 'slackGetReactions'),
    t(slackListUserReactions, 'read', 'slackListUserReactions'),
    t(slackAddStar, 'write', 'slackAddStar'),
    t(slackRemoveStar, 'delete', 'slackRemoveStar'),
    t(slackListStarredItems, 'read', 'slackListStarredItems'),
    t(slackPinItem, 'write', 'slackPinItem'),
    t(slackUnpinItem, 'delete', 'slackUnpinItem'),
    t(slackListPinnedItems, 'read', 'slackListPinnedItems'),
    t(slackCreateReminder, 'write', 'slackCreateReminder'),
    t(slackGetReminder, 'read', 'slackGetReminder'),
    t(slackListReminders, 'read', 'slackListReminders'),
    t(slackDeleteReminder, 'delete', 'slackDeleteReminder'),
    t(slackSearchAll, 'read', 'slackSearchAll'),
    t(slackSearchMessages, 'read', 'slackSearchMessages'),
    t(slackAssistantSearch, 'read', 'slackAssistantSearch'),
    t(slackGetSearchInfo, 'read', 'slackGetSearchInfo'),
    t(slackStartCall, 'write', 'slackStartCall'),
    t(slackGetCallInfo, 'read', 'slackGetCallInfo'),
    t(slackUpdateCallInfo, 'write', 'slackUpdateCallInfo'),
    t(slackEndCall, 'write', 'slackEndCall'),
    t(slackAddCallParticipants, 'write', 'slackAddCallParticipants'),
    t(slackRemoveCallParticipants, 'delete', 'slackRemoveCallParticipants'),
    t(slackCreateCanvas, 'write', 'slackCreateCanvas'),
    t(slackEditCanvas, 'write', 'slackEditCanvas'),
    t(slackDeleteCanvas, 'delete', 'slackDeleteCanvas'),
    t(slackLookupCanvasSections, 'read', 'slackLookupCanvasSections'),
    t(slackCreateList, 'write', 'slackCreateList'),
    t(slackCreateListItem, 'write', 'slackCreateListItem'),
    t(slackGetListItem, 'read', 'slackGetListItem'),
    t(slackListListItems, 'read', 'slackListListItems'),
    t(slackUpdateList, 'write', 'slackUpdateList'),
    t(slackUpdateListItem, 'write', 'slackUpdateListItem'),
    t(slackDeleteListItem, 'delete', 'slackDeleteListItem'),
    t(slackDeleteListItems, 'delete', 'slackDeleteListItems'),
    t(slackSetListAccess, 'write', 'slackSetListAccess'),
    t(slackDeleteListAccess, 'delete', 'slackDeleteListAccess'),
    t(slackCreateUserGroup, 'write', 'slackCreateUserGroup'),
    t(slackUpdateUserGroup, 'write', 'slackUpdateUserGroup'),
    t(slackUpdateUserGroupMembers, 'write', 'slackUpdateUserGroupMembers'),
    t(slackListUserGroups, 'read', 'slackListUserGroups'),
    t(slackListUserGroupMembers, 'read', 'slackListUserGroupMembers'),
    t(slackEnableUserGroup, 'write', 'slackEnableUserGroup'),
    t(slackDisableUserGroup, 'write', 'slackDisableUserGroup'),
    t(slackAddEmoji, 'write', 'slackAddEmoji'),
    t(slackAddEmojiAlias, 'write', 'slackAddEmojiAlias'),
    t(slackRenameEmoji, 'write', 'slackRenameEmoji'),
    t(slackRemoveEmoji, 'delete', 'slackRemoveEmoji'),
    t(slackListCustomEmojis, 'read', 'slackListCustomEmojis'),
    t(slackListAdminEmoji, 'read', 'slackListAdminEmoji'),
    t(slackListApprovedApps, 'read', 'slackListApprovedApps'),
    t(slackListAppRequests, 'read', 'slackListAppRequests'),
    t(slackListRestrictedApps, 'read', 'slackListRestrictedApps'),
    t(slackRestrictApp, 'write', 'slackRestrictApp'),
    t(slackListApprovedInvites, 'read', 'slackListApprovedInvites'),
    t(slackListDeniedInvites, 'read', 'slackListDeniedInvites'),
    t(slackListPendingInvites, 'read', 'slackListPendingInvites'),
    t(slackReadAuditLogs, 'read', 'slackReadAuditLogs'),
    t(slackGetAuditActions, 'read', 'slackGetAuditActions'),
    t(slackGetAuditSchemas, 'read', 'slackGetAuditSchemas'),
    t(slackGetScimConfig, 'read', 'slackGetScimConfig'),
    t(slackCustomizeUnfurl, 'write', 'slackCustomizeUnfurl'),
    t(slackApiTest, 'read', 'slackApiTest'),
    t(slackTestAuth, 'read', 'slackTestAuth'),
    t(slackWhoAmI, 'read', 'slackWhoAmI'),
    t(slackRtmConnect, 'write', 'slackRtmConnect'),
];
