// @ts-nocheck
import {
  slackSendMessage,
  slackUpdateMessage,
  slackDeleteMessage,
  slackScheduleMessage,
  slackListScheduledMessages,
  slackDeleteScheduledMessage,
  slackGetMessagePermalink,
  slackSendMeMessage,
  slackSendEphemeralMessage,
  slackListUnreadChannelMessages,
  slackGetUnreadMessagesFromUser,
} from './messages.js';
import {
  slackListAllChannels,
  slackFindChannels,
  slackListConversations,
  slackGetConversationInfo,
  slackGetConversationMembers,
  slackGetConversationHistory,
  slackGetConversationReplies,
  slackCreateChannel,
  slackArchiveChannel,
  slackUnarchiveChannel,
  slackCloseDm,
  slackJoinConversation,
  slackLeaveConversation,
  slackRenameConversation,
  slackSetConversationTopic,
  slackSetConversationPurpose,
  slackMarkConversationRead,
  slackInviteUsersToChannel,
  slackRemoveUserFromConversation,
  slackOpenDm,
} from './conversations.js';
import {
  slackAdminSearchConversations,
  slackAdminCreateConversation,
  slackDeleteChannel,
  slackConvertChannelToPrivate,
  slackInviteUserToChannelAdmin,
  slackGetConversationPrefs,
  slackSetConversationPrefs,
  slackGetChannelWorkspaces,
  slackSetChannelWorkspaces,
  slackListChannelIdpGroups,
} from './admin-conversations.js';
import {
  slackListUsers,
  slackFindUsers,
  slackFindUserByEmail,
  slackGetUserInfo,
  slackGetUserProfile,
  slackSetUserProfile,
  slackGetUserPresence,
  slackSetUserPresence,
  slackEndDnd,
  slackEndSnooze,
  slackSetDndDuration,
  slackGetDndStatus,
  slackGetTeamDndStatus,
  slackDeleteUserPhoto,
  slackSetUserPhoto,
  slackGetUserIdentity,
  slackGetBotInfo,
} from './users.js';
import {
  slackAddEnterpriseUserToWorkspace,
  slackInviteUserToWorkspace,
  slackRemoveUserFromWorkspace,
  slackSetAdminUser,
  slackSetWorkspaceOwner,
  slackResetUserSessions,
  slackListWorkspaceUsers,
} from './admin-users.js';
import {
  slackGetTeamInfo,
  slackGetTeamProfile,
  slackListAuthTeams,
  slackListAvailableWorkspaces,
  slackCreateEnterpriseTeam,
  slackListEnterpriseTeams,
  slackListWorkspaceAdmins,
  slackListWorkspaceOwners,
  slackGetWorkspaceSettings,
  slackSetWorkspaceName,
  slackSetWorkspaceDescription,
  slackSetWorkspaceIcon,
  slackSetWorkspaceDefaultChannels,
} from './teams.js';
import {
  slackListFiles,
  slackGetFileInfo,
  slackDeleteFile,
  slackDeleteFileComment,
  slackShareFilePublicUrl,
  slackRevokeFilePublicUrl,
  slackDownloadFile,
  slackUploadFile,
  slackAddRemoteFile,
  slackGetRemoteFile,
  slackUpdateRemoteFile,
  slackRemoveRemoteFile,
  slackShareRemoteFile,
  slackListRemoteFiles,
} from './files.js';
import {
  slackAddReaction,
  slackRemoveReaction,
  slackGetReactions,
  slackListUserReactions,
  slackAddStar,
  slackRemoveStar,
  slackListStarredItems,
  slackPinItem,
  slackUnpinItem,
  slackListPinnedItems,
} from './reactions-stars-pins.js';
import {
  slackCreateReminder,
  slackGetReminder,
  slackListReminders,
  slackDeleteReminder,
} from './reminders.js';
import {
  slackSearchAll,
  slackSearchMessages,
  slackAssistantSearch,
  slackGetSearchInfo,
} from './search.js';
import {
  slackStartCall,
  slackGetCallInfo,
  slackUpdateCallInfo,
  slackEndCall,
  slackAddCallParticipants,
  slackRemoveCallParticipants,
} from './calls.js';
import {
  slackCreateCanvas,
  slackEditCanvas,
  slackDeleteCanvas,
  slackLookupCanvasSections,
} from './canvas.js';
import {
  slackCreateList,
  slackCreateListItem,
  slackGetListItem,
  slackListListItems,
  slackUpdateList,
  slackUpdateListItem,
  slackDeleteListItem,
  slackDeleteListItems,
  slackSetListAccess,
  slackDeleteListAccess,
} from './slack-lists.js';
import {
  slackCreateUserGroup,
  slackUpdateUserGroup,
  slackUpdateUserGroupMembers,
  slackListUserGroups,
  slackListUserGroupMembers,
  slackEnableUserGroup,
  slackDisableUserGroup,
} from './usergroups.js';
import {
  slackAddEmoji,
  slackAddEmojiAlias,
  slackRenameEmoji,
  slackRemoveEmoji,
  slackListCustomEmojis,
  slackListAdminEmoji,
} from './emoji.js';
import {
  slackListApprovedApps,
  slackListAppRequests,
  slackListRestrictedApps,
  slackRestrictApp,
} from './admin-apps.js';
import {
  slackListApprovedInvites,
  slackListDeniedInvites,
  slackListPendingInvites,
} from './admin-invites.js';
import {
  slackReadAuditLogs,
  slackGetAuditActions,
  slackGetAuditSchemas,
  slackGetScimConfig,
} from './audit.js';
import {
  slackCustomizeUnfurl,
  slackApiTest,
  slackTestAuth,
  slackWhoAmI,
  slackRtmConnect,
} from './misc.js';

export {
  slackSendMessage,
  slackUpdateMessage,
  slackDeleteMessage,
  slackScheduleMessage,
  slackListScheduledMessages,
  slackDeleteScheduledMessage,
  slackGetMessagePermalink,
  slackSendMeMessage,
  slackSendEphemeralMessage,
  slackListUnreadChannelMessages,
  slackGetUnreadMessagesFromUser,
  slackListAllChannels,
  slackFindChannels,
  slackListConversations,
  slackGetConversationInfo,
  slackGetConversationMembers,
  slackGetConversationHistory,
  slackGetConversationReplies,
  slackCreateChannel,
  slackArchiveChannel,
  slackUnarchiveChannel,
  slackCloseDm,
  slackJoinConversation,
  slackLeaveConversation,
  slackRenameConversation,
  slackSetConversationTopic,
  slackSetConversationPurpose,
  slackMarkConversationRead,
  slackInviteUsersToChannel,
  slackRemoveUserFromConversation,
  slackOpenDm,
  slackAdminSearchConversations,
  slackAdminCreateConversation,
  slackDeleteChannel,
  slackConvertChannelToPrivate,
  slackInviteUserToChannelAdmin,
  slackGetConversationPrefs,
  slackSetConversationPrefs,
  slackGetChannelWorkspaces,
  slackSetChannelWorkspaces,
  slackListChannelIdpGroups,
  slackListUsers,
  slackFindUsers,
  slackFindUserByEmail,
  slackGetUserInfo,
  slackGetUserProfile,
  slackSetUserProfile,
  slackGetUserPresence,
  slackSetUserPresence,
  slackEndDnd,
  slackEndSnooze,
  slackSetDndDuration,
  slackGetDndStatus,
  slackGetTeamDndStatus,
  slackDeleteUserPhoto,
  slackSetUserPhoto,
  slackGetUserIdentity,
  slackGetBotInfo,
  slackAddEnterpriseUserToWorkspace,
  slackInviteUserToWorkspace,
  slackRemoveUserFromWorkspace,
  slackSetAdminUser,
  slackSetWorkspaceOwner,
  slackResetUserSessions,
  slackListWorkspaceUsers,
  slackGetTeamInfo,
  slackGetTeamProfile,
  slackListAuthTeams,
  slackListAvailableWorkspaces,
  slackCreateEnterpriseTeam,
  slackListEnterpriseTeams,
  slackListWorkspaceAdmins,
  slackListWorkspaceOwners,
  slackGetWorkspaceSettings,
  slackSetWorkspaceName,
  slackSetWorkspaceDescription,
  slackSetWorkspaceIcon,
  slackSetWorkspaceDefaultChannels,
  slackListFiles,
  slackGetFileInfo,
  slackDeleteFile,
  slackDeleteFileComment,
  slackShareFilePublicUrl,
  slackRevokeFilePublicUrl,
  slackDownloadFile,
  slackUploadFile,
  slackAddRemoteFile,
  slackGetRemoteFile,
  slackUpdateRemoteFile,
  slackRemoveRemoteFile,
  slackShareRemoteFile,
  slackListRemoteFiles,
  slackAddReaction,
  slackRemoveReaction,
  slackGetReactions,
  slackListUserReactions,
  slackAddStar,
  slackRemoveStar,
  slackListStarredItems,
  slackPinItem,
  slackUnpinItem,
  slackListPinnedItems,
  slackCreateReminder,
  slackGetReminder,
  slackListReminders,
  slackDeleteReminder,
  slackSearchAll,
  slackSearchMessages,
  slackAssistantSearch,
  slackGetSearchInfo,
  slackStartCall,
  slackGetCallInfo,
  slackUpdateCallInfo,
  slackEndCall,
  slackAddCallParticipants,
  slackRemoveCallParticipants,
  slackCreateCanvas,
  slackEditCanvas,
  slackDeleteCanvas,
  slackLookupCanvasSections,
  slackCreateList,
  slackCreateListItem,
  slackGetListItem,
  slackListListItems,
  slackUpdateList,
  slackUpdateListItem,
  slackDeleteListItem,
  slackDeleteListItems,
  slackSetListAccess,
  slackDeleteListAccess,
  slackCreateUserGroup,
  slackUpdateUserGroup,
  slackUpdateUserGroupMembers,
  slackListUserGroups,
  slackListUserGroupMembers,
  slackEnableUserGroup,
  slackDisableUserGroup,
  slackAddEmoji,
  slackAddEmojiAlias,
  slackRenameEmoji,
  slackRemoveEmoji,
  slackListCustomEmojis,
  slackListAdminEmoji,
  slackListApprovedApps,
  slackListAppRequests,
  slackListRestrictedApps,
  slackRestrictApp,
  slackListApprovedInvites,
  slackListDeniedInvites,
  slackListPendingInvites,
  slackReadAuditLogs,
  slackGetAuditActions,
  slackGetAuditSchemas,
  slackGetScimConfig,
  slackCustomizeUnfurl,
  slackApiTest,
  slackTestAuth,
  slackWhoAmI,
  slackRtmConnect,
};

const R = 'slackToken' as const;

function t(tool: any, scope: 'read' | 'write' | 'delete', name?: string, keywords: string[] = []) {
  return {
    name: name ?? tool?.name ?? 'unknown',
    description: tool?.description ?? '',
    tool,
    requiredAuth: R,
    scope,
    keywords,
  };
}

export const slackTools = [
  t(slackSendMessage, 'write', 'slackSendMessage', ['post', 'dm', 'channel']),
  t(slackUpdateMessage, 'write', 'slackUpdateMessage', ['edit']),
  t(slackDeleteMessage, 'delete', 'slackDeleteMessage', ['remove']),
  t(slackScheduleMessage, 'write', 'slackScheduleMessage', ['send-later', 'later']),
  t(slackListScheduledMessages, 'read', 'slackListScheduledMessages', ['scheduled', 'pending']),
  t(slackDeleteScheduledMessage, 'delete', 'slackDeleteScheduledMessage', ['cancel', 'unschedule']),
  t(slackGetMessagePermalink, 'read', 'slackGetMessagePermalink', ['link', 'url', 'share']),
  t(slackSendMeMessage, 'write', 'slackSendMeMessage', ['action']),
  t(slackSendEphemeralMessage, 'write', 'slackSendEphemeralMessage', [
    'private',
    'whisper',
    'temporary',
  ]),
  t(slackListUnreadChannelMessages, 'read', 'slackListUnreadChannelMessages', [
    'unread',
    'inbox',
    'catchup',
  ]),
  t(slackGetUnreadMessagesFromUser, 'read', 'slackGetUnreadMessagesFromUser', [
    'unread',
    'dm',
    'inbox',
  ]),
  t(slackListAllChannels, 'read', 'slackListAllChannels', ['browse']),
  t(slackFindChannels, 'read', 'slackFindChannels', ['search', 'lookup']),
  t(slackListConversations, 'read', 'slackListConversations', ['channels', 'dms']),
  t(slackGetConversationInfo, 'read', 'slackGetConversationInfo', ['details', 'metadata']),
  t(slackGetConversationMembers, 'read', 'slackGetConversationMembers', ['members', 'who']),
  t(slackGetConversationHistory, 'read', 'slackGetConversationHistory', [
    'messages',
    'read',
    'history',
  ]),
  t(slackGetConversationReplies, 'read', 'slackGetConversationReplies', ['thread', 'replies']),
  t(slackCreateChannel, 'write', 'slackCreateChannel', ['new', 'group']),
  t(slackArchiveChannel, 'write', 'slackArchiveChannel', ['close', 'read-only']),
  t(slackUnarchiveChannel, 'write', 'slackUnarchiveChannel', ['restore', 'reopen']),
  t(slackCloseDm, 'write', 'slackCloseDm', ['hide', 'dismiss']),
  t(slackJoinConversation, 'write', 'slackJoinConversation', []),
  t(slackLeaveConversation, 'write', 'slackLeaveConversation', ['exit', 'quit']),
  t(slackRenameConversation, 'write', 'slackRenameConversation', ['rename']),
  t(slackSetConversationTopic, 'write', 'slackSetConversationTopic', ['header', 'subject']),
  t(slackSetConversationPurpose, 'write', 'slackSetConversationPurpose', ['goal', 'description']),
  t(slackMarkConversationRead, 'write', 'slackMarkConversationRead', ['mark-read']),
  t(slackInviteUsersToChannel, 'write', 'slackInviteUsersToChannel', ['add', 'invite']),
  t(slackRemoveUserFromConversation, 'delete', 'slackRemoveUserFromConversation', [
    'kick',
    'remove',
  ]),
  t(slackOpenDm, 'write', 'slackOpenDm', ['dm', 'direct', 'chat']),
  t(slackAdminSearchConversations, 'read', 'slackAdminSearchConversations', [
    'admin',
    'enterprise',
  ]),
  t(slackAdminCreateConversation, 'write', 'slackAdminCreateConversation', ['admin']),
  t(slackDeleteChannel, 'delete', 'slackDeleteChannel', ['admin', 'remove', 'permanent']),
  t(slackConvertChannelToPrivate, 'write', 'slackConvertChannelToPrivate', ['admin']),
  t(slackInviteUserToChannelAdmin, 'write', 'slackInviteUserToChannelAdmin', ['admin', 'invite']),
  t(slackGetConversationPrefs, 'read', 'slackGetConversationPrefs', ['admin', 'settings']),
  t(slackSetConversationPrefs, 'write', 'slackSetConversationPrefs', ['admin', 'permissions']),
  t(slackGetChannelWorkspaces, 'read', 'slackGetChannelWorkspaces', ['admin', 'shared']),
  t(slackSetChannelWorkspaces, 'write', 'slackSetChannelWorkspaces', ['admin', 'share']),
  t(slackListChannelIdpGroups, 'read', 'slackListChannelIdpGroups', ['admin', 'sso']),
  t(slackListUsers, 'read', 'slackListUsers', ['members', 'directory', 'people']),
  t(slackFindUsers, 'read', 'slackFindUsers', ['search', 'lookup']),
  t(slackFindUserByEmail, 'read', 'slackFindUserByEmail', ['lookup']),
  t(slackGetUserInfo, 'read', 'slackGetUserInfo', ['profile', 'details']),
  t(slackGetUserProfile, 'read', 'slackGetUserProfile', ['profile']),
  t(slackSetUserProfile, 'write', 'slackSetUserProfile', ['edit']),
  t(slackGetUserPresence, 'read', 'slackGetUserPresence', ['online', 'status', 'active', 'away']),
  t(slackSetUserPresence, 'write', 'slackSetUserPresence', ['status']),
  t(slackEndDnd, 'write', 'slackEndDnd', ['available', 'notifications']),
  t(slackEndSnooze, 'write', 'slackEndSnooze', ['available']),
  t(slackSetDndDuration, 'write', 'slackSetDndDuration', ['snooze', 'mute', 'notifications']),
  t(slackGetDndStatus, 'read', 'slackGetDndStatus', ['availability']),
  t(slackGetTeamDndStatus, 'read', 'slackGetTeamDndStatus', ['availability']),
  t(slackDeleteUserPhoto, 'delete', 'slackDeleteUserPhoto', ['avatar', 'picture', 'remove']),
  t(slackSetUserPhoto, 'write', 'slackSetUserPhoto', ['avatar', 'picture']),
  t(slackGetUserIdentity, 'read', 'slackGetUserIdentity', ['login', 'me']),
  t(slackGetBotInfo, 'read', 'slackGetBotInfo', ['bot', 'app']),
  t(slackAddEnterpriseUserToWorkspace, 'write', 'slackAddEnterpriseUserToWorkspace', [
    'admin',
    'add',
  ]),
  t(slackInviteUserToWorkspace, 'write', 'slackInviteUserToWorkspace', [
    'admin',
    'invite',
    'email',
  ]),
  t(slackRemoveUserFromWorkspace, 'delete', 'slackRemoveUserFromWorkspace', [
    'admin',
    'remove',
    'deactivate',
  ]),
  t(slackSetAdminUser, 'write', 'slackSetAdminUser', ['admin', 'promote']),
  t(slackSetWorkspaceOwner, 'write', 'slackSetWorkspaceOwner', ['admin', 'owner']),
  t(slackResetUserSessions, 'write', 'slackResetUserSessions', ['admin', 'logout', 'security']),
  t(slackListWorkspaceUsers, 'read', 'slackListWorkspaceUsers', ['admin']),
  t(slackGetTeamInfo, 'read', 'slackGetTeamInfo', ['workspace', 'info']),
  t(slackGetTeamProfile, 'read', 'slackGetTeamProfile', ['fields', 'custom']),
  t(slackListAuthTeams, 'read', 'slackListAuthTeams', ['admin']),
  t(slackListAvailableWorkspaces, 'read', 'slackListAvailableWorkspaces', []),
  t(slackCreateEnterpriseTeam, 'write', 'slackCreateEnterpriseTeam', ['admin', 'create']),
  t(slackListEnterpriseTeams, 'read', 'slackListEnterpriseTeams', ['admin']),
  t(slackListWorkspaceAdmins, 'read', 'slackListWorkspaceAdmins', ['admin']),
  t(slackListWorkspaceOwners, 'read', 'slackListWorkspaceOwners', ['admin', 'owner']),
  t(slackGetWorkspaceSettings, 'read', 'slackGetWorkspaceSettings', ['admin', 'settings']),
  t(slackSetWorkspaceName, 'write', 'slackSetWorkspaceName', ['admin', 'rename']),
  t(slackSetWorkspaceDescription, 'write', 'slackSetWorkspaceDescription', ['admin']),
  t(slackSetWorkspaceIcon, 'write', 'slackSetWorkspaceIcon', ['admin', 'logo']),
  t(slackSetWorkspaceDefaultChannels, 'write', 'slackSetWorkspaceDefaultChannels', [
    'admin',
    'defaults',
  ]),
  t(slackListFiles, 'read', 'slackListFiles', ['browse', 'documents', 'uploads']),
  t(slackGetFileInfo, 'read', 'slackGetFileInfo', ['details', 'metadata', 'comments']),
  t(slackDeleteFile, 'delete', 'slackDeleteFile', ['remove']),
  t(slackDeleteFileComment, 'delete', 'slackDeleteFileComment', ['remove']),
  t(slackShareFilePublicUrl, 'write', 'slackShareFilePublicUrl', ['share', 'link', 'public']),
  t(slackRevokeFilePublicUrl, 'write', 'slackRevokeFilePublicUrl', ['unshare', 'private']),
  t(slackDownloadFile, 'read', 'slackDownloadFile', ['save', 'export']),
  t(slackUploadFile, 'write', 'slackUploadFile', ['share', 'snippet', 'post']),
  t(slackAddRemoteFile, 'write', 'slackAddRemoteFile', ['drive', 'dropbox', 'link']),
  t(slackGetRemoteFile, 'read', 'slackGetRemoteFile', []),
  t(slackUpdateRemoteFile, 'write', 'slackUpdateRemoteFile', ['edit']),
  t(slackRemoveRemoteFile, 'delete', 'slackRemoveRemoteFile', ['unlink', 'remove']),
  t(slackShareRemoteFile, 'write', 'slackShareRemoteFile', ['share']),
  t(slackListRemoteFiles, 'read', 'slackListRemoteFiles', []),
  t(slackAddReaction, 'write', 'slackAddReaction', ['emoji', 'react']),
  t(slackRemoveReaction, 'delete', 'slackRemoveReaction', ['emoji', 'remove']),
  t(slackGetReactions, 'read', 'slackGetReactions', ['emoji']),
  t(slackListUserReactions, 'read', 'slackListUserReactions', ['emoji']),
  t(slackAddStar, 'write', 'slackAddStar', ['save', 'favorite', 'bookmark']),
  t(slackRemoveStar, 'delete', 'slackRemoveStar', ['unsave', 'unfavorite', 'remove']),
  t(slackListStarredItems, 'read', 'slackListStarredItems', ['saved', 'favorites']),
  t(slackPinItem, 'write', 'slackPinItem', []),
  t(slackUnpinItem, 'delete', 'slackUnpinItem', ['remove']),
  t(slackListPinnedItems, 'read', 'slackListPinnedItems', ['pins']),
  t(slackCreateReminder, 'write', 'slackCreateReminder', ['remind', 'later', 'todo']),
  t(slackGetReminder, 'read', 'slackGetReminder', []),
  t(slackListReminders, 'read', 'slackListReminders', []),
  t(slackDeleteReminder, 'delete', 'slackDeleteReminder', ['cancel', 'remove']),
  t(slackSearchAll, 'read', 'slackSearchAll', ['find', 'lookup']),
  t(slackSearchMessages, 'read', 'slackSearchMessages', ['find', 'query']),
  t(slackAssistantSearch, 'read', 'slackAssistantSearch', ['find', 'semantic']),
  t(slackGetSearchInfo, 'read', 'slackGetSearchInfo', []),
  t(slackStartCall, 'write', 'slackStartCall', ['huddle', 'voice', 'video', 'meeting']),
  t(slackGetCallInfo, 'read', 'slackGetCallInfo', []),
  t(slackUpdateCallInfo, 'write', 'slackUpdateCallInfo', ['edit']),
  t(slackEndCall, 'write', 'slackEndCall', ['hangup', 'leave']),
  t(slackAddCallParticipants, 'write', 'slackAddCallParticipants', ['invite']),
  t(slackRemoveCallParticipants, 'delete', 'slackRemoveCallParticipants', ['kick', 'remove']),
  t(slackCreateCanvas, 'write', 'slackCreateCanvas', ['doc', 'note', 'new']),
  t(slackEditCanvas, 'write', 'slackEditCanvas', ['edit']),
  t(slackDeleteCanvas, 'delete', 'slackDeleteCanvas', ['remove']),
  t(slackLookupCanvasSections, 'read', 'slackLookupCanvasSections', ['find']),
  t(slackCreateList, 'write', 'slackCreateList', ['tracker', 'table', 'todo', 'new']),
  t(slackCreateListItem, 'write', 'slackCreateListItem', ['add', 'row', 'task']),
  t(slackGetListItem, 'read', 'slackGetListItem', ['row', 'read']),
  t(slackListListItems, 'read', 'slackListListItems', ['rows', 'read']),
  t(slackUpdateList, 'write', 'slackUpdateList', ['edit']),
  t(slackUpdateListItem, 'write', 'slackUpdateListItem', ['edit', 'row']),
  t(slackDeleteListItem, 'delete', 'slackDeleteListItem', ['remove', 'row']),
  t(slackDeleteListItems, 'delete', 'slackDeleteListItems', ['bulk', 'remove']),
  t(slackSetListAccess, 'write', 'slackSetListAccess', ['share', 'permissions']),
  t(slackDeleteListAccess, 'delete', 'slackDeleteListAccess', ['unshare', 'remove']),
  t(slackCreateUserGroup, 'write', 'slackCreateUserGroup', [
    'team',
    'subteam',
    'handle',
    'mention',
  ]),
  t(slackUpdateUserGroup, 'write', 'slackUpdateUserGroup', ['edit']),
  t(slackUpdateUserGroupMembers, 'write', 'slackUpdateUserGroupMembers', ['members', 'edit']),
  t(slackListUserGroups, 'read', 'slackListUserGroups', ['teams']),
  t(slackListUserGroupMembers, 'read', 'slackListUserGroupMembers', ['members']),
  t(slackEnableUserGroup, 'write', 'slackEnableUserGroup', ['restore']),
  t(slackDisableUserGroup, 'write', 'slackDisableUserGroup', ['archive']),
  t(slackAddEmoji, 'write', 'slackAddEmoji', ['custom', 'upload', 'new']),
  t(slackAddEmojiAlias, 'write', 'slackAddEmojiAlias', ['alias']),
  t(slackRenameEmoji, 'write', 'slackRenameEmoji', ['rename']),
  t(slackRemoveEmoji, 'delete', 'slackRemoveEmoji', ['delete', 'remove']),
  t(slackListCustomEmojis, 'read', 'slackListCustomEmojis', ['browse']),
  t(slackListAdminEmoji, 'read', 'slackListAdminEmoji', ['admin']),
  t(slackListApprovedApps, 'read', 'slackListApprovedApps', ['admin', 'allowlist']),
  t(slackListAppRequests, 'read', 'slackListAppRequests', ['admin', 'pending']),
  t(slackListRestrictedApps, 'read', 'slackListRestrictedApps', ['admin', 'blocked']),
  t(slackRestrictApp, 'write', 'slackRestrictApp', ['admin', 'block']),
  t(slackListApprovedInvites, 'read', 'slackListApprovedInvites', ['admin']),
  t(slackListDeniedInvites, 'read', 'slackListDeniedInvites', ['admin']),
  t(slackListPendingInvites, 'read', 'slackListPendingInvites', ['admin']),
  t(slackReadAuditLogs, 'read', 'slackReadAuditLogs', ['admin', 'audit', 'logs', 'security']),
  t(slackGetAuditActions, 'read', 'slackGetAuditActions', ['admin']),
  t(slackGetAuditSchemas, 'read', 'slackGetAuditSchemas', ['admin']),
  t(slackGetScimConfig, 'read', 'slackGetScimConfig', ['admin', 'provisioning', 'sso']),
  t(slackCustomizeUnfurl, 'write', 'slackCustomizeUnfurl', ['preview', 'link']),
  t(slackApiTest, 'read', 'slackApiTest', ['ping', 'connectivity', 'debug']),
  t(slackTestAuth, 'read', 'slackTestAuth', ['debug', 'token']),
  t(slackWhoAmI, 'read', 'slackWhoAmI', ['identity', 'me', 'login']),
  t(slackRtmConnect, 'write', 'slackRtmConnect', ['websocket', 'realtime', 'events']),
];
