// @ts-nocheck
import {
  hubspotAddAssetAssociation,
  hubspotCreateCampaign,
  hubspotCreateCampaigns,
  hubspotDeleteCampaign,
  hubspotDeleteCampaignsBatch,
  hubspotFetchRevenue,
  hubspotGetCampaign,
  hubspotGetCampaignMetrics,
  hubspotGetCampaigns,
  hubspotGetContactIds,
  hubspotListAssets,
  hubspotReadBudget,
  hubspotRemoveAssetAssociation,
  hubspotSearchCampaigns,
  hubspotUpdateCampaign,
  hubspotUpdateCampaigns,
} from './campaigns.js';
import {
  hubspotAddTokenToEventTemplate,
  hubspotCreateEventTemplateForApp,
  hubspotCreateTimelineEvent,
  hubspotCreateTimelineEventsBatch,
  hubspotDeleteTimelineEventTemplate,
  hubspotGetEventTemplate,
  hubspotListEventTemplates,
  hubspotRemoveTokenFromEventTemplate,
  hubspotRenderEventDetailTemplate,
  hubspotRenderEventHeaderOrDetailAsHtml,
  hubspotRetrieveTimelineEventByIds,
  hubspotUpdateEventTemplate,
  hubspotUpdateTokenOnEventTemplate,
} from './timeline.js';
import {
  hubspotArchiveBatchOfFeedbackSubmissions,
  hubspotArchiveFeedbackSubmission,
  hubspotCreateBatchOfFeedbackSubmissions,
  hubspotCreateFeedbackSubmission,
  hubspotListFeedbackSubmissions,
  hubspotMergeFeedbackSubmissions,
  hubspotReadBatchFeedbackSubmissionsByIdOrProperty,
  hubspotReadFeedbackSubmissionById,
  hubspotSearchFeedbackSubmissions,
  hubspotUpdateBatchFeedbackSubmissions,
  hubspotUpdateFeedbackSubmission,
} from './feedback.js';
import {
  hubspotArchiveBatchOfLineItems,
  hubspotArchiveLineItem,
  hubspotCreateLineItem,
  hubspotCreateLineItems,
  hubspotDeleteLineItemsGdpr,
  hubspotMergeLineItems,
  hubspotReadBatchOfLineItemsByIdOrPropertyValues,
  hubspotRetrieveLineItemById,
  hubspotRetrieveLineItems,
  hubspotSearchLineItemsByCriteria,
  hubspotUpdateLineItem,
  hubspotUpdateLineItems,
} from './line-items.js';
import {
  hubspotArchiveBatchOfObjects,
  hubspotArchiveCrmObjectById,
  hubspotCreateBatchOfObjects,
  hubspotCreateCrmObjectFromNl,
  hubspotCreateCrmObjectWithProperties,
  hubspotMergeObjects,
  hubspotPartiallyUpdateCrmObjectById,
  hubspotPermanentlyDeleteContactViaGdpr,
  hubspotReadApageOfObjectsByType,
  hubspotReadBatchOfCrmObjectsByIdOrPropertyValues,
  hubspotReadCrmObjectById,
  hubspotSearchCrmObjectsByCriteria,
  hubspotUpdateBatchOfObjectsByIdorPropertyValues,
} from './generic.js';
import {
  hubspotArchiveBatchOfProperties,
  hubspotArchivePropertyByObjectTypeAndName,
  hubspotArchivePropertyGroup,
  hubspotCreateAndReturnANewPropertyGroup,
  hubspotCreateBatchOfProperties,
  hubspotCreatePropertyForSpecifiedObjectType,
  hubspotListContactProperties,
  hubspotReadACrmPropertyByName,
  hubspotReadAllPropertiesForObjectType,
  hubspotReadBatchCrmObjectProperties,
  hubspotReadPropertyGroup,
  hubspotReadPropertyGroupsForObjectType,
  hubspotUpdateCrmProperty,
  hubspotUpdatePropertyGroup,
} from './properties.js';
import {
  hubspotArchiveBatchOfQuotes,
  hubspotArchiveQuote,
  hubspotBatchUpdateQuotes,
  hubspotCreateBatchOfQuotes,
  hubspotCreateQuoteObject,
  hubspotGetQuote,
  hubspotListQuotes,
  hubspotMergeQuotes,
  hubspotReadBatchOfQuotesByPropertyValues,
  hubspotSearchQuotesByCriteria,
  hubspotUpdateQuote,
} from './quotes.js';
import {
  hubspotArchiveCompanies,
  hubspotArchiveCompany,
  hubspotBatchReadCompaniesByProperties,
  hubspotCreateCompanies,
  hubspotCreateCompany,
  hubspotDeleteCompanyGdpr,
  hubspotGetCompany,
  hubspotListCompanies,
  hubspotMergeCompanies,
  hubspotSearchCompanies,
  hubspotUpdateCompanies,
  hubspotUpdateCompany,
} from './companies.js';
import {
  hubspotArchiveContact,
  hubspotArchiveContacts,
  hubspotCreateContact,
  hubspotCreateContactFromNl,
  hubspotCreateContacts,
  hubspotDeleteContactGdpr,
  hubspotListContacts,
  hubspotMergeContacts,
  hubspotReadContact,
  hubspotReadContacts,
  hubspotSearchContactsByCriteria,
  hubspotUpdateContact,
  hubspotUpdateContacts,
  hubspotUpsertContacts,
} from './contacts.js';
import {
  hubspotArchiveDeals,
  hubspotCreateDeal,
  hubspotCreateDealFromNl,
  hubspotCreateDeals,
  hubspotDeleteDealGdpr,
  hubspotGetDeal,
  hubspotGetDeals,
  hubspotListDeals,
  hubspotMergeDeals,
  hubspotRemoveDeal,
  hubspotSearchDeals,
  hubspotUpdateDeal,
  hubspotUpdateDeals,
} from './deals.js';
import {
  hubspotArchiveEmail,
  hubspotArchiveEmails,
  hubspotCreateEmail,
  hubspotCreateEmails,
  hubspotGetEmails,
  hubspotListEmails,
  hubspotMergeEmails,
  hubspotReadEmail,
  hubspotSearchEmails,
  hubspotUpdateEmail,
  hubspotUpdateEmails,
} from './emails.js';
import {
  hubspotArchiveProduct,
  hubspotArchiveProducts,
  hubspotCreateProduct,
  hubspotCreateProducts,
  hubspotGetProduct,
  hubspotGetProducts,
  hubspotListProducts,
  hubspotMergeProducts,
  hubspotSearchProducts,
  hubspotUpdateProduct,
  hubspotUpdateProducts,
} from './products.js';
import {
  hubspotArchiveTicket,
  hubspotArchiveTickets,
  hubspotCreateTicket,
  hubspotCreateTickets,
  hubspotGetTicket,
  hubspotGetTickets,
  hubspotListTickets,
  hubspotMergeTickets,
  hubspotSearchTickets,
  hubspotUpdateTicket,
  hubspotUpdateTickets,
} from './tickets.js';
import {
  hubspotAuditPipelineChanges,
  hubspotCreatePipeline,
  hubspotCreatePipelineStage,
  hubspotDeletePipeline,
  hubspotDeletePipelineStage,
  hubspotGetPipelineById,
  hubspotGetPipelineStageAudit,
  hubspotReplaceAllPropertiesOfPipeline,
  hubspotReplacePipelineStageProperties,
  hubspotRetrieveAllPipelinesForSpecifiedObjectType,
  hubspotRetrievePipelineStageById,
  hubspotRetrievePipelineStages,
  hubspotUpdatePipeline,
  hubspotUpdatePipelineStage,
} from './pipelines.js';
import {
  hubspotCancelImport,
  hubspotFetchImportErrorDetails,
  hubspotGetActiveImportsList,
  hubspotGetImportRecordInformation,
  hubspotStartImport,
} from './imports.js';
import {
  hubspotCloneMarketingEmail,
  hubspotCreateAbTestVariation,
  hubspotCreateANewMarketingEmail,
  hubspotCreateOrUpdateDraftVersion,
  hubspotDeleteMarketingEmail,
  hubspotGetAbEmailVariation,
  hubspotGetAggregatedStatisticIntervals,
  hubspotGetAggregatedStatistics,
  hubspotGetAllMarketingEmailsForAHubspotAccount,
  hubspotGetMarketingEmailDraft,
  hubspotGetMarketingEmailRevision,
  hubspotGetMarketingEmailRevisions,
  hubspotGetTheDetailsOfASpecifiedMarketingEmail,
  hubspotListEmailEvents,
  hubspotPublishMarketingEmail,
  hubspotResetDraft,
  hubspotRestoreEmailRevision,
  hubspotRestoreMarketingEmailRevision,
  hubspotUpdateAMarketingEmail,
} from './marketing-emails.js';
import {
  hubspotConfigureCallingExtensionSettings,
  hubspotDeleteCallingExtensionSettings,
  hubspotFetchRecordingSettings,
  hubspotRetrieveCallingSettingsForApp,
  hubspotSetCallRecordingSettings,
  hubspotUpdateCallingAppRecordingSettings,
  hubspotUpdateCallingExtensionSettings,
} from './calling.js';
import {
  hubspotCreateAssociation,
  hubspotCreateObjectAssociation,
  hubspotListAssociationTypes,
  hubspotListObjectAssociations,
  hubspotReadAssociationsBatch,
  hubspotRemoveAssociation,
  hubspotRemoveAssociationFromSchema,
} from './associations.js';
import {
  hubspotCreateEngagement,
  hubspotCreateMeeting,
  hubspotCreateNote,
  hubspotCreateTask,
  hubspotDeleteCall,
  hubspotDeleteMeeting,
  hubspotDeleteNote,
  hubspotDeleteTask,
  hubspotGetEngagement,
  hubspotListCallDispositions,
  hubspotListCompanyActivities,
  hubspotListCompanyCalls,
  hubspotListCompanyMeetings,
  hubspotListContactNotes,
  hubspotListContactTasks,
  hubspotListDealActivities,
  hubspotListDealMeetings,
  hubspotListRecentlyModifiedEngagements,
} from './engagements.js';
import {
  hubspotCreateList,
  hubspotGetCrmList,
  hubspotGetRecordListMemberships,
  hubspotGetSegmentMembers,
} from './lists.js';
import {
  hubspotCreateObjectSchema,
  hubspotDeleteSchema,
  hubspotPurgeSchema,
  hubspotRetrieveAllObjectSchemas,
  hubspotRetrieveObjectSchema,
  hubspotUpdateObjectSchema,
} from './schemas.js';
import {
  hubspotCreateWorkflow,
  hubspotDeleteWorkflow,
  hubspotEnrollContactInWorkflow,
  hubspotGetWorkflowById,
  hubspotGetWorkflowRevision,
  hubspotGetWorkflows,
  hubspotUpdateWorkflow,
} from './workflows.js';
import {
  hubspotDeleteVideoConferencingAppSettings,
  hubspotRetrieveVideoConferenceSettingsById,
  hubspotUpdateVideoConferenceAppSettings,
} from './video.js';
import {
  hubspotGetAccountInfo,
  hubspotListAuditLogs,
  hubspotListGrantedScopes,
  hubspotWhoAmI,
} from './account.js';
import {
  hubspotGetBlogPost,
  hubspotListConversationThreads,
  hubspotListSequences,
  hubspotListSitePages,
} from './content.js';
import {
  hubspotRetrieveOwnerByIdOrUserId,
  hubspotRetrieveOwners,
  hubspotRetrievePageOfCrmOwners,
} from './owners.js';

export {
  hubspotAddAssetAssociation,
  hubspotCreateCampaign,
  hubspotCreateCampaigns,
  hubspotDeleteCampaign,
  hubspotDeleteCampaignsBatch,
  hubspotFetchRevenue,
  hubspotGetCampaign,
  hubspotGetCampaignMetrics,
  hubspotGetCampaigns,
  hubspotGetContactIds,
  hubspotListAssets,
  hubspotReadBudget,
  hubspotRemoveAssetAssociation,
  hubspotSearchCampaigns,
  hubspotUpdateCampaign,
  hubspotUpdateCampaigns,
};
export {
  hubspotAddTokenToEventTemplate,
  hubspotCreateEventTemplateForApp,
  hubspotCreateTimelineEvent,
  hubspotCreateTimelineEventsBatch,
  hubspotDeleteTimelineEventTemplate,
  hubspotGetEventTemplate,
  hubspotListEventTemplates,
  hubspotRemoveTokenFromEventTemplate,
  hubspotRenderEventDetailTemplate,
  hubspotRenderEventHeaderOrDetailAsHtml,
  hubspotRetrieveTimelineEventByIds,
  hubspotUpdateEventTemplate,
  hubspotUpdateTokenOnEventTemplate,
};
export {
  hubspotArchiveBatchOfFeedbackSubmissions,
  hubspotArchiveFeedbackSubmission,
  hubspotCreateBatchOfFeedbackSubmissions,
  hubspotCreateFeedbackSubmission,
  hubspotListFeedbackSubmissions,
  hubspotMergeFeedbackSubmissions,
  hubspotReadBatchFeedbackSubmissionsByIdOrProperty,
  hubspotReadFeedbackSubmissionById,
  hubspotSearchFeedbackSubmissions,
  hubspotUpdateBatchFeedbackSubmissions,
  hubspotUpdateFeedbackSubmission,
};
export {
  hubspotArchiveBatchOfLineItems,
  hubspotArchiveLineItem,
  hubspotCreateLineItem,
  hubspotCreateLineItems,
  hubspotDeleteLineItemsGdpr,
  hubspotMergeLineItems,
  hubspotReadBatchOfLineItemsByIdOrPropertyValues,
  hubspotRetrieveLineItemById,
  hubspotRetrieveLineItems,
  hubspotSearchLineItemsByCriteria,
  hubspotUpdateLineItem,
  hubspotUpdateLineItems,
};
export {
  hubspotArchiveBatchOfObjects,
  hubspotArchiveCrmObjectById,
  hubspotCreateBatchOfObjects,
  hubspotCreateCrmObjectFromNl,
  hubspotCreateCrmObjectWithProperties,
  hubspotMergeObjects,
  hubspotPartiallyUpdateCrmObjectById,
  hubspotPermanentlyDeleteContactViaGdpr,
  hubspotReadApageOfObjectsByType,
  hubspotReadBatchOfCrmObjectsByIdOrPropertyValues,
  hubspotReadCrmObjectById,
  hubspotSearchCrmObjectsByCriteria,
  hubspotUpdateBatchOfObjectsByIdorPropertyValues,
};
export {
  hubspotArchiveBatchOfProperties,
  hubspotArchivePropertyByObjectTypeAndName,
  hubspotArchivePropertyGroup,
  hubspotCreateAndReturnANewPropertyGroup,
  hubspotCreateBatchOfProperties,
  hubspotCreatePropertyForSpecifiedObjectType,
  hubspotListContactProperties,
  hubspotReadACrmPropertyByName,
  hubspotReadAllPropertiesForObjectType,
  hubspotReadBatchCrmObjectProperties,
  hubspotReadPropertyGroup,
  hubspotReadPropertyGroupsForObjectType,
  hubspotUpdateCrmProperty,
  hubspotUpdatePropertyGroup,
};
export {
  hubspotArchiveBatchOfQuotes,
  hubspotArchiveQuote,
  hubspotBatchUpdateQuotes,
  hubspotCreateBatchOfQuotes,
  hubspotCreateQuoteObject,
  hubspotGetQuote,
  hubspotListQuotes,
  hubspotMergeQuotes,
  hubspotReadBatchOfQuotesByPropertyValues,
  hubspotSearchQuotesByCriteria,
  hubspotUpdateQuote,
};
export {
  hubspotArchiveCompanies,
  hubspotArchiveCompany,
  hubspotBatchReadCompaniesByProperties,
  hubspotCreateCompanies,
  hubspotCreateCompany,
  hubspotDeleteCompanyGdpr,
  hubspotGetCompany,
  hubspotListCompanies,
  hubspotMergeCompanies,
  hubspotSearchCompanies,
  hubspotUpdateCompanies,
  hubspotUpdateCompany,
};
export {
  hubspotArchiveContact,
  hubspotArchiveContacts,
  hubspotCreateContact,
  hubspotCreateContactFromNl,
  hubspotCreateContacts,
  hubspotDeleteContactGdpr,
  hubspotListContacts,
  hubspotMergeContacts,
  hubspotReadContact,
  hubspotReadContacts,
  hubspotSearchContactsByCriteria,
  hubspotUpdateContact,
  hubspotUpdateContacts,
  hubspotUpsertContacts,
};
export {
  hubspotArchiveDeals,
  hubspotCreateDeal,
  hubspotCreateDealFromNl,
  hubspotCreateDeals,
  hubspotDeleteDealGdpr,
  hubspotGetDeal,
  hubspotGetDeals,
  hubspotListDeals,
  hubspotMergeDeals,
  hubspotRemoveDeal,
  hubspotSearchDeals,
  hubspotUpdateDeal,
  hubspotUpdateDeals,
};
export {
  hubspotArchiveEmail,
  hubspotArchiveEmails,
  hubspotCreateEmail,
  hubspotCreateEmails,
  hubspotGetEmails,
  hubspotListEmails,
  hubspotMergeEmails,
  hubspotReadEmail,
  hubspotSearchEmails,
  hubspotUpdateEmail,
  hubspotUpdateEmails,
};
export {
  hubspotArchiveProduct,
  hubspotArchiveProducts,
  hubspotCreateProduct,
  hubspotCreateProducts,
  hubspotGetProduct,
  hubspotGetProducts,
  hubspotListProducts,
  hubspotMergeProducts,
  hubspotSearchProducts,
  hubspotUpdateProduct,
  hubspotUpdateProducts,
};
export {
  hubspotArchiveTicket,
  hubspotArchiveTickets,
  hubspotCreateTicket,
  hubspotCreateTickets,
  hubspotGetTicket,
  hubspotGetTickets,
  hubspotListTickets,
  hubspotMergeTickets,
  hubspotSearchTickets,
  hubspotUpdateTicket,
  hubspotUpdateTickets,
};
export {
  hubspotAuditPipelineChanges,
  hubspotCreatePipeline,
  hubspotCreatePipelineStage,
  hubspotDeletePipeline,
  hubspotDeletePipelineStage,
  hubspotGetPipelineById,
  hubspotGetPipelineStageAudit,
  hubspotReplaceAllPropertiesOfPipeline,
  hubspotReplacePipelineStageProperties,
  hubspotRetrieveAllPipelinesForSpecifiedObjectType,
  hubspotRetrievePipelineStageById,
  hubspotRetrievePipelineStages,
  hubspotUpdatePipeline,
  hubspotUpdatePipelineStage,
};
export {
  hubspotCancelImport,
  hubspotFetchImportErrorDetails,
  hubspotGetActiveImportsList,
  hubspotGetImportRecordInformation,
  hubspotStartImport,
};
export {
  hubspotCloneMarketingEmail,
  hubspotCreateAbTestVariation,
  hubspotCreateANewMarketingEmail,
  hubspotCreateOrUpdateDraftVersion,
  hubspotDeleteMarketingEmail,
  hubspotGetAbEmailVariation,
  hubspotGetAggregatedStatisticIntervals,
  hubspotGetAggregatedStatistics,
  hubspotGetAllMarketingEmailsForAHubspotAccount,
  hubspotGetMarketingEmailDraft,
  hubspotGetMarketingEmailRevision,
  hubspotGetMarketingEmailRevisions,
  hubspotGetTheDetailsOfASpecifiedMarketingEmail,
  hubspotListEmailEvents,
  hubspotPublishMarketingEmail,
  hubspotResetDraft,
  hubspotRestoreEmailRevision,
  hubspotRestoreMarketingEmailRevision,
  hubspotUpdateAMarketingEmail,
};
export {
  hubspotConfigureCallingExtensionSettings,
  hubspotDeleteCallingExtensionSettings,
  hubspotFetchRecordingSettings,
  hubspotRetrieveCallingSettingsForApp,
  hubspotSetCallRecordingSettings,
  hubspotUpdateCallingAppRecordingSettings,
  hubspotUpdateCallingExtensionSettings,
};
export {
  hubspotCreateAssociation,
  hubspotCreateObjectAssociation,
  hubspotListAssociationTypes,
  hubspotListObjectAssociations,
  hubspotReadAssociationsBatch,
  hubspotRemoveAssociation,
  hubspotRemoveAssociationFromSchema,
};
export {
  hubspotCreateEngagement,
  hubspotCreateMeeting,
  hubspotCreateNote,
  hubspotCreateTask,
  hubspotDeleteCall,
  hubspotDeleteMeeting,
  hubspotDeleteNote,
  hubspotDeleteTask,
  hubspotGetEngagement,
  hubspotListCallDispositions,
  hubspotListCompanyActivities,
  hubspotListCompanyCalls,
  hubspotListCompanyMeetings,
  hubspotListContactNotes,
  hubspotListContactTasks,
  hubspotListDealActivities,
  hubspotListDealMeetings,
  hubspotListRecentlyModifiedEngagements,
};
export {
  hubspotCreateList,
  hubspotGetCrmList,
  hubspotGetRecordListMemberships,
  hubspotGetSegmentMembers,
};
export {
  hubspotCreateObjectSchema,
  hubspotDeleteSchema,
  hubspotPurgeSchema,
  hubspotRetrieveAllObjectSchemas,
  hubspotRetrieveObjectSchema,
  hubspotUpdateObjectSchema,
};
export {
  hubspotCreateWorkflow,
  hubspotDeleteWorkflow,
  hubspotEnrollContactInWorkflow,
  hubspotGetWorkflowById,
  hubspotGetWorkflowRevision,
  hubspotGetWorkflows,
  hubspotUpdateWorkflow,
};
export {
  hubspotDeleteVideoConferencingAppSettings,
  hubspotRetrieveVideoConferenceSettingsById,
  hubspotUpdateVideoConferenceAppSettings,
};
export { hubspotGetAccountInfo, hubspotListAuditLogs, hubspotListGrantedScopes, hubspotWhoAmI };
export {
  hubspotGetBlogPost,
  hubspotListConversationThreads,
  hubspotListSequences,
  hubspotListSitePages,
};
export { hubspotRetrieveOwnerByIdOrUserId, hubspotRetrieveOwners, hubspotRetrievePageOfCrmOwners };

export const hubspotTools = [
  {
    name: 'hubspotAddAssetAssociation',
    description: hubspotAddAssetAssociation.description!,
    tool: hubspotAddAssetAssociation,
    requiredAuth: 'hubspotToken' as const,
    scope: 'write' as const,
    keywords: ['attach', 'link', 'attachment', 'relationship'],
  },
  {
    name: 'hubspotAddTokenToEventTemplate',
    description: hubspotAddTokenToEventTemplate.description!,
    tool: hubspotAddTokenToEventTemplate,
    requiredAuth: 'hubspotToken' as const,
    scope: 'write' as const,
    keywords: ['attach', 'link', 'variable'],
  },
  {
    name: 'hubspotArchiveBatchOfFeedbackSubmissions',
    description: hubspotArchiveBatchOfFeedbackSubmissions.description!,
    tool: hubspotArchiveBatchOfFeedbackSubmissions,
    requiredAuth: 'hubspotToken' as const,
    scope: 'delete' as const,
    keywords: ['trash'],
  },
  {
    name: 'hubspotArchiveBatchOfLineItems',
    description: hubspotArchiveBatchOfLineItems.description!,
    tool: hubspotArchiveBatchOfLineItems,
    requiredAuth: 'hubspotToken' as const,
    scope: 'delete' as const,
    keywords: ['trash'],
  },
  {
    name: 'hubspotArchiveBatchOfObjects',
    description: hubspotArchiveBatchOfObjects.description!,
    tool: hubspotArchiveBatchOfObjects,
    requiredAuth: 'hubspotToken' as const,
    scope: 'delete' as const,
    keywords: ['trash'],
  },
  {
    name: 'hubspotArchiveBatchOfProperties',
    description: hubspotArchiveBatchOfProperties.description!,
    tool: hubspotArchiveBatchOfProperties,
    requiredAuth: 'hubspotToken' as const,
    scope: 'delete' as const,
    keywords: ['trash'],
  },
  {
    name: 'hubspotArchiveBatchOfQuotes',
    description: hubspotArchiveBatchOfQuotes.description!,
    tool: hubspotArchiveBatchOfQuotes,
    requiredAuth: 'hubspotToken' as const,
    scope: 'delete' as const,
    keywords: ['trash', 'proposal'],
  },
  {
    name: 'hubspotArchiveCompanies',
    description: hubspotArchiveCompanies.description!,
    tool: hubspotArchiveCompanies,
    requiredAuth: 'hubspotToken' as const,
    scope: 'delete' as const,
    keywords: ['trash'],
  },
  {
    name: 'hubspotArchiveCompany',
    description: hubspotArchiveCompany.description!,
    tool: hubspotArchiveCompany,
    requiredAuth: 'hubspotToken' as const,
    scope: 'delete' as const,
    keywords: ['trash', 'account', 'organization'],
  },
  {
    name: 'hubspotArchiveContact',
    description: hubspotArchiveContact.description!,
    tool: hubspotArchiveContact,
    requiredAuth: 'hubspotToken' as const,
    scope: 'delete' as const,
    keywords: ['trash', 'person'],
  },
  {
    name: 'hubspotArchiveContacts',
    description: hubspotArchiveContacts.description!,
    tool: hubspotArchiveContacts,
    requiredAuth: 'hubspotToken' as const,
    scope: 'delete' as const,
    keywords: ['trash', 'person'],
  },
  {
    name: 'hubspotArchiveCrmObjectById',
    description: hubspotArchiveCrmObjectById.description!,
    tool: hubspotArchiveCrmObjectById,
    requiredAuth: 'hubspotToken' as const,
    scope: 'delete' as const,
    keywords: ['trash'],
  },
  {
    name: 'hubspotArchiveDeals',
    description: hubspotArchiveDeals.description!,
    tool: hubspotArchiveDeals,
    requiredAuth: 'hubspotToken' as const,
    scope: 'delete' as const,
    keywords: ['trash', 'opportunity'],
  },
  {
    name: 'hubspotArchiveEmail',
    description: hubspotArchiveEmail.description!,
    tool: hubspotArchiveEmail,
    requiredAuth: 'hubspotToken' as const,
    scope: 'delete' as const,
    keywords: ['trash', 'message'],
  },
  {
    name: 'hubspotArchiveEmails',
    description: hubspotArchiveEmails.description!,
    tool: hubspotArchiveEmails,
    requiredAuth: 'hubspotToken' as const,
    scope: 'delete' as const,
    keywords: ['trash', 'message'],
  },
  {
    name: 'hubspotArchiveFeedbackSubmission',
    description: hubspotArchiveFeedbackSubmission.description!,
    tool: hubspotArchiveFeedbackSubmission,
    requiredAuth: 'hubspotToken' as const,
    scope: 'delete' as const,
    keywords: ['trash'],
  },
  {
    name: 'hubspotArchiveLineItem',
    description: hubspotArchiveLineItem.description!,
    tool: hubspotArchiveLineItem,
    requiredAuth: 'hubspotToken' as const,
    scope: 'delete' as const,
    keywords: ['trash'],
  },
  {
    name: 'hubspotArchiveProduct',
    description: hubspotArchiveProduct.description!,
    tool: hubspotArchiveProduct,
    requiredAuth: 'hubspotToken' as const,
    scope: 'delete' as const,
    keywords: ['trash', 'catalog item'],
  },
  {
    name: 'hubspotArchiveProducts',
    description: hubspotArchiveProducts.description!,
    tool: hubspotArchiveProducts,
    requiredAuth: 'hubspotToken' as const,
    scope: 'delete' as const,
    keywords: ['trash', 'catalog item'],
  },
  {
    name: 'hubspotArchivePropertyByObjectTypeAndName',
    description: hubspotArchivePropertyByObjectTypeAndName.description!,
    tool: hubspotArchivePropertyByObjectTypeAndName,
    requiredAuth: 'hubspotToken' as const,
    scope: 'delete' as const,
    keywords: ['trash', 'field', 'attribute'],
  },
  {
    name: 'hubspotArchivePropertyGroup',
    description: hubspotArchivePropertyGroup.description!,
    tool: hubspotArchivePropertyGroup,
    requiredAuth: 'hubspotToken' as const,
    scope: 'delete' as const,
    keywords: ['trash', 'field', 'attribute'],
  },
  {
    name: 'hubspotArchiveQuote',
    description: hubspotArchiveQuote.description!,
    tool: hubspotArchiveQuote,
    requiredAuth: 'hubspotToken' as const,
    scope: 'delete' as const,
    keywords: ['trash', 'proposal'],
  },
  {
    name: 'hubspotArchiveTicket',
    description: hubspotArchiveTicket.description!,
    tool: hubspotArchiveTicket,
    requiredAuth: 'hubspotToken' as const,
    scope: 'delete' as const,
    keywords: ['trash', 'support case'],
  },
  {
    name: 'hubspotArchiveTickets',
    description: hubspotArchiveTickets.description!,
    tool: hubspotArchiveTickets,
    requiredAuth: 'hubspotToken' as const,
    scope: 'delete' as const,
    keywords: ['trash', 'support case'],
  },
  {
    name: 'hubspotAuditPipelineChanges',
    description: hubspotAuditPipelineChanges.description!,
    tool: hubspotAuditPipelineChanges,
    requiredAuth: 'hubspotToken' as const,
    scope: 'read' as const,
    keywords: ['logs', 'history', 'funnel'],
  },
  {
    name: 'hubspotBatchReadCompaniesByProperties',
    description: hubspotBatchReadCompaniesByProperties.description!,
    tool: hubspotBatchReadCompaniesByProperties,
    requiredAuth: 'hubspotToken' as const,
    scope: 'write' as const,
    keywords: ['bulk'],
  },
  {
    name: 'hubspotBatchUpdateQuotes',
    description: hubspotBatchUpdateQuotes.description!,
    tool: hubspotBatchUpdateQuotes,
    requiredAuth: 'hubspotToken' as const,
    scope: 'write' as const,
    keywords: ['bulk', 'proposal'],
  },
  {
    name: 'hubspotCancelImport',
    description: hubspotCancelImport.description!,
    tool: hubspotCancelImport,
    requiredAuth: 'hubspotToken' as const,
    scope: 'write' as const,
    keywords: ['abort', 'stop', 'upload', 'migration'],
  },
  {
    name: 'hubspotCloneMarketingEmail',
    description: hubspotCloneMarketingEmail.description!,
    tool: hubspotCloneMarketingEmail,
    requiredAuth: 'hubspotToken' as const,
    scope: 'write' as const,
    keywords: ['duplicate', 'copy', 'message'],
  },
  {
    name: 'hubspotConfigureCallingExtensionSettings',
    description: hubspotConfigureCallingExtensionSettings.description!,
    tool: hubspotConfigureCallingExtensionSettings,
    requiredAuth: 'hubspotToken' as const,
    scope: 'write' as const,
    keywords: ['setup'],
  },
  {
    name: 'hubspotCreateAbTestVariation',
    description: hubspotCreateAbTestVariation.description!,
    tool: hubspotCreateAbTestVariation,
    requiredAuth: 'hubspotToken' as const,
    scope: 'write' as const,
    keywords: ['new', 'add'],
  },
  {
    name: 'hubspotCreateAndReturnANewPropertyGroup',
    description: hubspotCreateAndReturnANewPropertyGroup.description!,
    tool: hubspotCreateAndReturnANewPropertyGroup,
    requiredAuth: 'hubspotToken' as const,
    scope: 'write' as const,
    keywords: ['add', 'field', 'attribute'],
  },
  {
    name: 'hubspotCreateANewMarketingEmail',
    description: hubspotCreateANewMarketingEmail.description!,
    tool: hubspotCreateANewMarketingEmail,
    requiredAuth: 'hubspotToken' as const,
    scope: 'write' as const,
    keywords: ['add', 'message'],
  },
  {
    name: 'hubspotCreateAssociation',
    description: hubspotCreateAssociation.description!,
    tool: hubspotCreateAssociation,
    requiredAuth: 'hubspotToken' as const,
    scope: 'write' as const,
    keywords: ['new', 'add', 'link', 'relationship'],
  },
  {
    name: 'hubspotCreateBatchOfFeedbackSubmissions',
    description: hubspotCreateBatchOfFeedbackSubmissions.description!,
    tool: hubspotCreateBatchOfFeedbackSubmissions,
    requiredAuth: 'hubspotToken' as const,
    scope: 'write' as const,
    keywords: ['new', 'add'],
  },
  {
    name: 'hubspotCreateBatchOfObjects',
    description: hubspotCreateBatchOfObjects.description!,
    tool: hubspotCreateBatchOfObjects,
    requiredAuth: 'hubspotToken' as const,
    scope: 'write' as const,
    keywords: ['new', 'add'],
  },
  {
    name: 'hubspotCreateBatchOfProperties',
    description: hubspotCreateBatchOfProperties.description!,
    tool: hubspotCreateBatchOfProperties,
    requiredAuth: 'hubspotToken' as const,
    scope: 'write' as const,
    keywords: ['new', 'add'],
  },
  {
    name: 'hubspotCreateBatchOfQuotes',
    description: hubspotCreateBatchOfQuotes.description!,
    tool: hubspotCreateBatchOfQuotes,
    requiredAuth: 'hubspotToken' as const,
    scope: 'write' as const,
    keywords: ['new', 'add', 'proposal'],
  },
  {
    name: 'hubspotCreateCampaign',
    description: hubspotCreateCampaign.description!,
    tool: hubspotCreateCampaign,
    requiredAuth: 'hubspotToken' as const,
    scope: 'write' as const,
    keywords: ['new', 'add', 'initiative'],
  },
  {
    name: 'hubspotCreateCampaigns',
    description: hubspotCreateCampaigns.description!,
    tool: hubspotCreateCampaigns,
    requiredAuth: 'hubspotToken' as const,
    scope: 'write' as const,
    keywords: ['new', 'add', 'initiative'],
  },
  {
    name: 'hubspotCreateCompanies',
    description: hubspotCreateCompanies.description!,
    tool: hubspotCreateCompanies,
    requiredAuth: 'hubspotToken' as const,
    scope: 'write' as const,
    keywords: ['new', 'add'],
  },
  {
    name: 'hubspotCreateCompany',
    description: hubspotCreateCompany.description!,
    tool: hubspotCreateCompany,
    requiredAuth: 'hubspotToken' as const,
    scope: 'write' as const,
    keywords: ['new', 'add', 'account', 'organization'],
  },
  {
    name: 'hubspotCreateContact',
    description: hubspotCreateContact.description!,
    tool: hubspotCreateContact,
    requiredAuth: 'hubspotToken' as const,
    scope: 'write' as const,
    keywords: ['new', 'add', 'person'],
  },
  {
    name: 'hubspotCreateContactFromNl',
    description: hubspotCreateContactFromNl.description!,
    tool: hubspotCreateContactFromNl,
    requiredAuth: 'hubspotToken' as const,
    scope: 'write' as const,
    keywords: ['new', 'add', 'person'],
  },
  {
    name: 'hubspotCreateContacts',
    description: hubspotCreateContacts.description!,
    tool: hubspotCreateContacts,
    requiredAuth: 'hubspotToken' as const,
    scope: 'write' as const,
    keywords: ['new', 'add', 'person'],
  },
  {
    name: 'hubspotCreateCrmObjectFromNl',
    description: hubspotCreateCrmObjectFromNl.description!,
    tool: hubspotCreateCrmObjectFromNl,
    requiredAuth: 'hubspotToken' as const,
    scope: 'write' as const,
    keywords: ['new', 'add'],
  },
  {
    name: 'hubspotCreateCrmObjectWithProperties',
    description: hubspotCreateCrmObjectWithProperties.description!,
    tool: hubspotCreateCrmObjectWithProperties,
    requiredAuth: 'hubspotToken' as const,
    scope: 'write' as const,
    keywords: ['new', 'add'],
  },
  {
    name: 'hubspotCreateDeal',
    description: hubspotCreateDeal.description!,
    tool: hubspotCreateDeal,
    requiredAuth: 'hubspotToken' as const,
    scope: 'write' as const,
    keywords: ['new', 'add', 'opportunity'],
  },
  {
    name: 'hubspotCreateDealFromNl',
    description: hubspotCreateDealFromNl.description!,
    tool: hubspotCreateDealFromNl,
    requiredAuth: 'hubspotToken' as const,
    scope: 'write' as const,
    keywords: ['new', 'add', 'opportunity'],
  },
  {
    name: 'hubspotCreateDeals',
    description: hubspotCreateDeals.description!,
    tool: hubspotCreateDeals,
    requiredAuth: 'hubspotToken' as const,
    scope: 'write' as const,
    keywords: ['new', 'add', 'opportunity'],
  },
  {
    name: 'hubspotCreateEmail',
    description: hubspotCreateEmail.description!,
    tool: hubspotCreateEmail,
    requiredAuth: 'hubspotToken' as const,
    scope: 'write' as const,
    keywords: ['new', 'add', 'message'],
  },
  {
    name: 'hubspotCreateEmails',
    description: hubspotCreateEmails.description!,
    tool: hubspotCreateEmails,
    requiredAuth: 'hubspotToken' as const,
    scope: 'write' as const,
    keywords: ['new', 'add', 'message'],
  },
  {
    name: 'hubspotCreateEngagement',
    description: hubspotCreateEngagement.description!,
    tool: hubspotCreateEngagement,
    requiredAuth: 'hubspotToken' as const,
    scope: 'write' as const,
    keywords: ['new', 'add', 'activity'],
  },
  {
    name: 'hubspotCreateEventTemplateForApp',
    description: hubspotCreateEventTemplateForApp.description!,
    tool: hubspotCreateEventTemplateForApp,
    requiredAuth: 'hubspotToken' as const,
    scope: 'write' as const,
    keywords: ['new', 'add'],
  },
  {
    name: 'hubspotCreateFeedbackSubmission',
    description: hubspotCreateFeedbackSubmission.description!,
    tool: hubspotCreateFeedbackSubmission,
    requiredAuth: 'hubspotToken' as const,
    scope: 'write' as const,
    keywords: ['new', 'add'],
  },
  {
    name: 'hubspotCreateLineItem',
    description: hubspotCreateLineItem.description!,
    tool: hubspotCreateLineItem,
    requiredAuth: 'hubspotToken' as const,
    scope: 'write' as const,
    keywords: ['new', 'add'],
  },
  {
    name: 'hubspotCreateLineItems',
    description: hubspotCreateLineItems.description!,
    tool: hubspotCreateLineItems,
    requiredAuth: 'hubspotToken' as const,
    scope: 'write' as const,
    keywords: ['new', 'add'],
  },
  {
    name: 'hubspotCreateList',
    description: hubspotCreateList.description!,
    tool: hubspotCreateList,
    requiredAuth: 'hubspotToken' as const,
    scope: 'write' as const,
    keywords: ['new', 'add', 'segment', 'audience'],
  },
  {
    name: 'hubspotCreateMeeting',
    description: hubspotCreateMeeting.description!,
    tool: hubspotCreateMeeting,
    requiredAuth: 'hubspotToken' as const,
    scope: 'write' as const,
    keywords: ['new', 'add', 'call slot'],
  },
  {
    name: 'hubspotCreateNote',
    description: hubspotCreateNote.description!,
    tool: hubspotCreateNote,
    requiredAuth: 'hubspotToken' as const,
    scope: 'write' as const,
    keywords: ['new', 'add', 'memo'],
  },
  {
    name: 'hubspotCreateObjectAssociation',
    description: hubspotCreateObjectAssociation.description!,
    tool: hubspotCreateObjectAssociation,
    requiredAuth: 'hubspotToken' as const,
    scope: 'write' as const,
    keywords: ['new', 'add', 'link', 'relationship'],
  },
  {
    name: 'hubspotCreateObjectSchema',
    description: hubspotCreateObjectSchema.description!,
    tool: hubspotCreateObjectSchema,
    requiredAuth: 'hubspotToken' as const,
    scope: 'write' as const,
    keywords: ['new', 'add'],
  },
  {
    name: 'hubspotCreateOrUpdateDraftVersion',
    description: hubspotCreateOrUpdateDraftVersion.description!,
    tool: hubspotCreateOrUpdateDraftVersion,
    requiredAuth: 'hubspotToken' as const,
    scope: 'write' as const,
    keywords: ['new', 'add'],
  },
  {
    name: 'hubspotCreatePipeline',
    description: hubspotCreatePipeline.description!,
    tool: hubspotCreatePipeline,
    requiredAuth: 'hubspotToken' as const,
    scope: 'write' as const,
    keywords: ['new', 'add', 'funnel'],
  },
  {
    name: 'hubspotCreatePipelineStage',
    description: hubspotCreatePipelineStage.description!,
    tool: hubspotCreatePipelineStage,
    requiredAuth: 'hubspotToken' as const,
    scope: 'write' as const,
    keywords: ['new', 'add', 'funnel'],
  },
  {
    name: 'hubspotCreateProduct',
    description: hubspotCreateProduct.description!,
    tool: hubspotCreateProduct,
    requiredAuth: 'hubspotToken' as const,
    scope: 'write' as const,
    keywords: ['new', 'add', 'catalog item'],
  },
  {
    name: 'hubspotCreateProducts',
    description: hubspotCreateProducts.description!,
    tool: hubspotCreateProducts,
    requiredAuth: 'hubspotToken' as const,
    scope: 'write' as const,
    keywords: ['new', 'add', 'catalog item'],
  },
  {
    name: 'hubspotCreatePropertyForSpecifiedObjectType',
    description: hubspotCreatePropertyForSpecifiedObjectType.description!,
    tool: hubspotCreatePropertyForSpecifiedObjectType,
    requiredAuth: 'hubspotToken' as const,
    scope: 'write' as const,
    keywords: ['new', 'add', 'field', 'attribute'],
  },
  {
    name: 'hubspotCreateQuoteObject',
    description: hubspotCreateQuoteObject.description!,
    tool: hubspotCreateQuoteObject,
    requiredAuth: 'hubspotToken' as const,
    scope: 'write' as const,
    keywords: ['new', 'add', 'proposal'],
  },
  {
    name: 'hubspotCreateTask',
    description: hubspotCreateTask.description!,
    tool: hubspotCreateTask,
    requiredAuth: 'hubspotToken' as const,
    scope: 'write' as const,
    keywords: ['new', 'add', 'todo'],
  },
  {
    name: 'hubspotCreateTicket',
    description: hubspotCreateTicket.description!,
    tool: hubspotCreateTicket,
    requiredAuth: 'hubspotToken' as const,
    scope: 'write' as const,
    keywords: ['new', 'add', 'support case'],
  },
  {
    name: 'hubspotCreateTickets',
    description: hubspotCreateTickets.description!,
    tool: hubspotCreateTickets,
    requiredAuth: 'hubspotToken' as const,
    scope: 'write' as const,
    keywords: ['new', 'add', 'support case'],
  },
  {
    name: 'hubspotCreateTimelineEvent',
    description: hubspotCreateTimelineEvent.description!,
    tool: hubspotCreateTimelineEvent,
    requiredAuth: 'hubspotToken' as const,
    scope: 'write' as const,
    keywords: ['new', 'add', 'activity feed'],
  },
  {
    name: 'hubspotCreateTimelineEventsBatch',
    description: hubspotCreateTimelineEventsBatch.description!,
    tool: hubspotCreateTimelineEventsBatch,
    requiredAuth: 'hubspotToken' as const,
    scope: 'write' as const,
    keywords: ['new', 'add', 'activity feed'],
  },
  {
    name: 'hubspotCreateWorkflow',
    description: hubspotCreateWorkflow.description!,
    tool: hubspotCreateWorkflow,
    requiredAuth: 'hubspotToken' as const,
    scope: 'write' as const,
    keywords: ['new', 'add'],
  },
  {
    name: 'hubspotDeleteCall',
    description: hubspotDeleteCall.description!,
    tool: hubspotDeleteCall,
    requiredAuth: 'hubspotToken' as const,
    scope: 'delete' as const,
    keywords: ['remove', 'trash', 'phone log'],
  },
  {
    name: 'hubspotDeleteCallingExtensionSettings',
    description: hubspotDeleteCallingExtensionSettings.description!,
    tool: hubspotDeleteCallingExtensionSettings,
    requiredAuth: 'hubspotToken' as const,
    scope: 'delete' as const,
    keywords: ['remove', 'trash'],
  },
  {
    name: 'hubspotDeleteCampaign',
    description: hubspotDeleteCampaign.description!,
    tool: hubspotDeleteCampaign,
    requiredAuth: 'hubspotToken' as const,
    scope: 'delete' as const,
    keywords: ['remove', 'trash', 'initiative'],
  },
  {
    name: 'hubspotDeleteCampaignsBatch',
    description: hubspotDeleteCampaignsBatch.description!,
    tool: hubspotDeleteCampaignsBatch,
    requiredAuth: 'hubspotToken' as const,
    scope: 'delete' as const,
    keywords: ['remove', 'trash', 'initiative'],
  },
  {
    name: 'hubspotDeleteCompanyGdpr',
    description: hubspotDeleteCompanyGdpr.description!,
    tool: hubspotDeleteCompanyGdpr,
    requiredAuth: 'hubspotToken' as const,
    scope: 'delete' as const,
    keywords: ['remove', 'trash', 'account', 'organization'],
  },
  {
    name: 'hubspotDeleteContactGdpr',
    description: hubspotDeleteContactGdpr.description!,
    tool: hubspotDeleteContactGdpr,
    requiredAuth: 'hubspotToken' as const,
    scope: 'delete' as const,
    keywords: ['remove', 'trash', 'person'],
  },
  {
    name: 'hubspotDeleteDealGdpr',
    description: hubspotDeleteDealGdpr.description!,
    tool: hubspotDeleteDealGdpr,
    requiredAuth: 'hubspotToken' as const,
    scope: 'delete' as const,
    keywords: ['remove', 'trash', 'opportunity'],
  },
  {
    name: 'hubspotDeleteLineItemsGdpr',
    description: hubspotDeleteLineItemsGdpr.description!,
    tool: hubspotDeleteLineItemsGdpr,
    requiredAuth: 'hubspotToken' as const,
    scope: 'delete' as const,
    keywords: ['remove', 'trash'],
  },
  {
    name: 'hubspotDeleteMarketingEmail',
    description: hubspotDeleteMarketingEmail.description!,
    tool: hubspotDeleteMarketingEmail,
    requiredAuth: 'hubspotToken' as const,
    scope: 'delete' as const,
    keywords: ['remove', 'trash', 'message'],
  },
  {
    name: 'hubspotDeleteMeeting',
    description: hubspotDeleteMeeting.description!,
    tool: hubspotDeleteMeeting,
    requiredAuth: 'hubspotToken' as const,
    scope: 'delete' as const,
    keywords: ['remove', 'trash', 'call slot'],
  },
  {
    name: 'hubspotDeleteNote',
    description: hubspotDeleteNote.description!,
    tool: hubspotDeleteNote,
    requiredAuth: 'hubspotToken' as const,
    scope: 'delete' as const,
    keywords: ['remove', 'trash', 'memo'],
  },
  {
    name: 'hubspotDeletePipeline',
    description: hubspotDeletePipeline.description!,
    tool: hubspotDeletePipeline,
    requiredAuth: 'hubspotToken' as const,
    scope: 'delete' as const,
    keywords: ['remove', 'trash', 'funnel'],
  },
  {
    name: 'hubspotDeletePipelineStage',
    description: hubspotDeletePipelineStage.description!,
    tool: hubspotDeletePipelineStage,
    requiredAuth: 'hubspotToken' as const,
    scope: 'delete' as const,
    keywords: ['remove', 'trash', 'funnel'],
  },
  {
    name: 'hubspotDeleteSchema',
    description: hubspotDeleteSchema.description!,
    tool: hubspotDeleteSchema,
    requiredAuth: 'hubspotToken' as const,
    scope: 'delete' as const,
    keywords: ['remove', 'trash'],
  },
  {
    name: 'hubspotDeleteTask',
    description: hubspotDeleteTask.description!,
    tool: hubspotDeleteTask,
    requiredAuth: 'hubspotToken' as const,
    scope: 'delete' as const,
    keywords: ['remove', 'trash', 'todo'],
  },
  {
    name: 'hubspotDeleteTimelineEventTemplate',
    description: hubspotDeleteTimelineEventTemplate.description!,
    tool: hubspotDeleteTimelineEventTemplate,
    requiredAuth: 'hubspotToken' as const,
    scope: 'delete' as const,
    keywords: ['remove', 'trash', 'activity feed'],
  },
  {
    name: 'hubspotDeleteVideoConferencingAppSettings',
    description: hubspotDeleteVideoConferencingAppSettings.description!,
    tool: hubspotDeleteVideoConferencingAppSettings,
    requiredAuth: 'hubspotToken' as const,
    scope: 'delete' as const,
    keywords: ['remove', 'trash'],
  },
  {
    name: 'hubspotDeleteWorkflow',
    description: hubspotDeleteWorkflow.description!,
    tool: hubspotDeleteWorkflow,
    requiredAuth: 'hubspotToken' as const,
    scope: 'delete' as const,
    keywords: ['remove', 'trash'],
  },
  {
    name: 'hubspotEnrollContactInWorkflow',
    description: hubspotEnrollContactInWorkflow.description!,
    tool: hubspotEnrollContactInWorkflow,
    requiredAuth: 'hubspotToken' as const,
    scope: 'write' as const,
    keywords: ['subscribe', 'person'],
  },
  {
    name: 'hubspotFetchImportErrorDetails',
    description: hubspotFetchImportErrorDetails.description!,
    tool: hubspotFetchImportErrorDetails,
    requiredAuth: 'hubspotToken' as const,
    scope: 'read' as const,
    keywords: ['lookup', 'upload', 'migration'],
  },
  {
    name: 'hubspotFetchRecordingSettings',
    description: hubspotFetchRecordingSettings.description!,
    tool: hubspotFetchRecordingSettings,
    requiredAuth: 'hubspotToken' as const,
    scope: 'read' as const,
    keywords: ['lookup'],
  },
  {
    name: 'hubspotFetchRevenue',
    description: hubspotFetchRevenue.description!,
    tool: hubspotFetchRevenue,
    requiredAuth: 'hubspotToken' as const,
    scope: 'read' as const,
    keywords: ['lookup'],
  },
  {
    name: 'hubspotGetAbEmailVariation',
    description: hubspotGetAbEmailVariation.description!,
    tool: hubspotGetAbEmailVariation,
    requiredAuth: 'hubspotToken' as const,
    scope: 'read' as const,
    keywords: ['lookup', 'fetch', 'message'],
  },
  {
    name: 'hubspotGetAccountInfo',
    description: hubspotGetAccountInfo.description!,
    tool: hubspotGetAccountInfo,
    requiredAuth: 'hubspotToken' as const,
    scope: 'read' as const,
    keywords: ['lookup', 'fetch'],
  },
  {
    name: 'hubspotGetActiveImportsList',
    description: hubspotGetActiveImportsList.description!,
    tool: hubspotGetActiveImportsList,
    requiredAuth: 'hubspotToken' as const,
    scope: 'read' as const,
    keywords: ['lookup', 'fetch', 'upload', 'migration'],
  },
  {
    name: 'hubspotGetAggregatedStatisticIntervals',
    description: hubspotGetAggregatedStatisticIntervals.description!,
    tool: hubspotGetAggregatedStatisticIntervals,
    requiredAuth: 'hubspotToken' as const,
    scope: 'read' as const,
    keywords: ['lookup', 'fetch'],
  },
  {
    name: 'hubspotGetAggregatedStatistics',
    description: hubspotGetAggregatedStatistics.description!,
    tool: hubspotGetAggregatedStatistics,
    requiredAuth: 'hubspotToken' as const,
    scope: 'read' as const,
    keywords: ['lookup', 'fetch'],
  },
  {
    name: 'hubspotGetAllMarketingEmailsForAHubspotAccount',
    description: hubspotGetAllMarketingEmailsForAHubspotAccount.description!,
    tool: hubspotGetAllMarketingEmailsForAHubspotAccount,
    requiredAuth: 'hubspotToken' as const,
    scope: 'read' as const,
    keywords: ['lookup', 'fetch', 'message'],
  },
  {
    name: 'hubspotGetBlogPost',
    description: hubspotGetBlogPost.description!,
    tool: hubspotGetBlogPost,
    requiredAuth: 'hubspotToken' as const,
    scope: 'read' as const,
    keywords: ['lookup', 'fetch', 'article'],
  },
  {
    name: 'hubspotGetCampaign',
    description: hubspotGetCampaign.description!,
    tool: hubspotGetCampaign,
    requiredAuth: 'hubspotToken' as const,
    scope: 'read' as const,
    keywords: ['lookup', 'fetch', 'initiative'],
  },
  {
    name: 'hubspotGetCampaignMetrics',
    description: hubspotGetCampaignMetrics.description!,
    tool: hubspotGetCampaignMetrics,
    requiredAuth: 'hubspotToken' as const,
    scope: 'read' as const,
    keywords: ['lookup', 'fetch', 'initiative'],
  },
  {
    name: 'hubspotGetCampaigns',
    description: hubspotGetCampaigns.description!,
    tool: hubspotGetCampaigns,
    requiredAuth: 'hubspotToken' as const,
    scope: 'read' as const,
    keywords: ['lookup', 'fetch', 'initiative'],
  },
  {
    name: 'hubspotGetCompany',
    description: hubspotGetCompany.description!,
    tool: hubspotGetCompany,
    requiredAuth: 'hubspotToken' as const,
    scope: 'read' as const,
    keywords: ['lookup', 'fetch', 'account', 'organization'],
  },
  {
    name: 'hubspotGetContactIds',
    description: hubspotGetContactIds.description!,
    tool: hubspotGetContactIds,
    requiredAuth: 'hubspotToken' as const,
    scope: 'read' as const,
    keywords: ['lookup', 'fetch', 'person'],
  },
  {
    name: 'hubspotGetCrmList',
    description: hubspotGetCrmList.description!,
    tool: hubspotGetCrmList,
    requiredAuth: 'hubspotToken' as const,
    scope: 'read' as const,
    keywords: ['lookup', 'fetch', 'segment', 'audience'],
  },
  {
    name: 'hubspotGetDeal',
    description: hubspotGetDeal.description!,
    tool: hubspotGetDeal,
    requiredAuth: 'hubspotToken' as const,
    scope: 'read' as const,
    keywords: ['lookup', 'fetch', 'opportunity'],
  },
  {
    name: 'hubspotGetDeals',
    description: hubspotGetDeals.description!,
    tool: hubspotGetDeals,
    requiredAuth: 'hubspotToken' as const,
    scope: 'read' as const,
    keywords: ['lookup', 'fetch', 'opportunity'],
  },
  {
    name: 'hubspotGetEmails',
    description: hubspotGetEmails.description!,
    tool: hubspotGetEmails,
    requiredAuth: 'hubspotToken' as const,
    scope: 'read' as const,
    keywords: ['lookup', 'fetch', 'message'],
  },
  {
    name: 'hubspotGetEngagement',
    description: hubspotGetEngagement.description!,
    tool: hubspotGetEngagement,
    requiredAuth: 'hubspotToken' as const,
    scope: 'read' as const,
    keywords: ['lookup', 'fetch', 'activity'],
  },
  {
    name: 'hubspotGetEventTemplate',
    description: hubspotGetEventTemplate.description!,
    tool: hubspotGetEventTemplate,
    requiredAuth: 'hubspotToken' as const,
    scope: 'read' as const,
    keywords: ['lookup', 'fetch'],
  },
  {
    name: 'hubspotGetImportRecordInformation',
    description: hubspotGetImportRecordInformation.description!,
    tool: hubspotGetImportRecordInformation,
    requiredAuth: 'hubspotToken' as const,
    scope: 'read' as const,
    keywords: ['lookup', 'fetch', 'upload', 'migration'],
  },
  {
    name: 'hubspotGetMarketingEmailDraft',
    description: hubspotGetMarketingEmailDraft.description!,
    tool: hubspotGetMarketingEmailDraft,
    requiredAuth: 'hubspotToken' as const,
    scope: 'read' as const,
    keywords: ['lookup', 'fetch', 'message'],
  },
  {
    name: 'hubspotGetMarketingEmailRevision',
    description: hubspotGetMarketingEmailRevision.description!,
    tool: hubspotGetMarketingEmailRevision,
    requiredAuth: 'hubspotToken' as const,
    scope: 'read' as const,
    keywords: ['lookup', 'fetch', 'message'],
  },
  {
    name: 'hubspotGetMarketingEmailRevisions',
    description: hubspotGetMarketingEmailRevisions.description!,
    tool: hubspotGetMarketingEmailRevisions,
    requiredAuth: 'hubspotToken' as const,
    scope: 'read' as const,
    keywords: ['lookup', 'fetch', 'message'],
  },
  {
    name: 'hubspotGetPipelineById',
    description: hubspotGetPipelineById.description!,
    tool: hubspotGetPipelineById,
    requiredAuth: 'hubspotToken' as const,
    scope: 'read' as const,
    keywords: ['lookup', 'fetch', 'funnel'],
  },
  {
    name: 'hubspotGetPipelineStageAudit',
    description: hubspotGetPipelineStageAudit.description!,
    tool: hubspotGetPipelineStageAudit,
    requiredAuth: 'hubspotToken' as const,
    scope: 'read' as const,
    keywords: ['lookup', 'fetch', 'funnel'],
  },
  {
    name: 'hubspotGetProduct',
    description: hubspotGetProduct.description!,
    tool: hubspotGetProduct,
    requiredAuth: 'hubspotToken' as const,
    scope: 'read' as const,
    keywords: ['lookup', 'fetch', 'catalog item'],
  },
  {
    name: 'hubspotGetProducts',
    description: hubspotGetProducts.description!,
    tool: hubspotGetProducts,
    requiredAuth: 'hubspotToken' as const,
    scope: 'read' as const,
    keywords: ['lookup', 'fetch', 'catalog item'],
  },
  {
    name: 'hubspotGetQuote',
    description: hubspotGetQuote.description!,
    tool: hubspotGetQuote,
    requiredAuth: 'hubspotToken' as const,
    scope: 'read' as const,
    keywords: ['lookup', 'fetch', 'proposal'],
  },
  {
    name: 'hubspotGetRecordListMemberships',
    description: hubspotGetRecordListMemberships.description!,
    tool: hubspotGetRecordListMemberships,
    requiredAuth: 'hubspotToken' as const,
    scope: 'read' as const,
    keywords: ['lookup', 'fetch', 'segment', 'audience'],
  },
  {
    name: 'hubspotGetSegmentMembers',
    description: hubspotGetSegmentMembers.description!,
    tool: hubspotGetSegmentMembers,
    requiredAuth: 'hubspotToken' as const,
    scope: 'read' as const,
    keywords: ['lookup', 'fetch'],
  },
  {
    name: 'hubspotGetTheDetailsOfASpecifiedMarketingEmail',
    description: hubspotGetTheDetailsOfASpecifiedMarketingEmail.description!,
    tool: hubspotGetTheDetailsOfASpecifiedMarketingEmail,
    requiredAuth: 'hubspotToken' as const,
    scope: 'read' as const,
    keywords: ['lookup', 'fetch', 'message'],
  },
  {
    name: 'hubspotGetTicket',
    description: hubspotGetTicket.description!,
    tool: hubspotGetTicket,
    requiredAuth: 'hubspotToken' as const,
    scope: 'read' as const,
    keywords: ['lookup', 'fetch', 'support case'],
  },
  {
    name: 'hubspotGetTickets',
    description: hubspotGetTickets.description!,
    tool: hubspotGetTickets,
    requiredAuth: 'hubspotToken' as const,
    scope: 'read' as const,
    keywords: ['lookup', 'fetch', 'support case'],
  },
  {
    name: 'hubspotGetWorkflowById',
    description: hubspotGetWorkflowById.description!,
    tool: hubspotGetWorkflowById,
    requiredAuth: 'hubspotToken' as const,
    scope: 'read' as const,
    keywords: ['lookup', 'fetch'],
  },
  {
    name: 'hubspotGetWorkflowRevision',
    description: hubspotGetWorkflowRevision.description!,
    tool: hubspotGetWorkflowRevision,
    requiredAuth: 'hubspotToken' as const,
    scope: 'read' as const,
    keywords: ['lookup', 'fetch'],
  },
  {
    name: 'hubspotGetWorkflows',
    description: hubspotGetWorkflows.description!,
    tool: hubspotGetWorkflows,
    requiredAuth: 'hubspotToken' as const,
    scope: 'read' as const,
    keywords: ['lookup', 'fetch'],
  },
  {
    name: 'hubspotListAssets',
    description: hubspotListAssets.description!,
    tool: hubspotListAssets,
    requiredAuth: 'hubspotToken' as const,
    scope: 'read' as const,
    keywords: ['browse', 'attachment'],
  },
  {
    name: 'hubspotListAssociationTypes',
    description: hubspotListAssociationTypes.description!,
    tool: hubspotListAssociationTypes,
    requiredAuth: 'hubspotToken' as const,
    scope: 'read' as const,
    keywords: ['browse', 'link', 'relationship'],
  },
  {
    name: 'hubspotListAuditLogs',
    description: hubspotListAuditLogs.description!,
    tool: hubspotListAuditLogs,
    requiredAuth: 'hubspotToken' as const,
    scope: 'read' as const,
    keywords: ['browse'],
  },
  {
    name: 'hubspotListCallDispositions',
    description: hubspotListCallDispositions.description!,
    tool: hubspotListCallDispositions,
    requiredAuth: 'hubspotToken' as const,
    scope: 'read' as const,
    keywords: ['browse', 'phone log'],
  },
  {
    name: 'hubspotListCompanies',
    description: hubspotListCompanies.description!,
    tool: hubspotListCompanies,
    requiredAuth: 'hubspotToken' as const,
    scope: 'read' as const,
    keywords: ['browse'],
  },
  {
    name: 'hubspotListCompanyActivities',
    description: hubspotListCompanyActivities.description!,
    tool: hubspotListCompanyActivities,
    requiredAuth: 'hubspotToken' as const,
    scope: 'read' as const,
    keywords: ['browse', 'account', 'organization'],
  },
  {
    name: 'hubspotListCompanyCalls',
    description: hubspotListCompanyCalls.description!,
    tool: hubspotListCompanyCalls,
    requiredAuth: 'hubspotToken' as const,
    scope: 'read' as const,
    keywords: ['browse', 'account', 'organization', 'phone log'],
  },
  {
    name: 'hubspotListCompanyMeetings',
    description: hubspotListCompanyMeetings.description!,
    tool: hubspotListCompanyMeetings,
    requiredAuth: 'hubspotToken' as const,
    scope: 'read' as const,
    keywords: ['browse', 'account', 'organization', 'call slot'],
  },
  {
    name: 'hubspotListContactNotes',
    description: hubspotListContactNotes.description!,
    tool: hubspotListContactNotes,
    requiredAuth: 'hubspotToken' as const,
    scope: 'read' as const,
    keywords: ['browse', 'person', 'memo'],
  },
  {
    name: 'hubspotListContactProperties',
    description: hubspotListContactProperties.description!,
    tool: hubspotListContactProperties,
    requiredAuth: 'hubspotToken' as const,
    scope: 'read' as const,
    keywords: ['browse', 'person'],
  },
  {
    name: 'hubspotListContacts',
    description: hubspotListContacts.description!,
    tool: hubspotListContacts,
    requiredAuth: 'hubspotToken' as const,
    scope: 'read' as const,
    keywords: ['browse', 'person'],
  },
  {
    name: 'hubspotListContactTasks',
    description: hubspotListContactTasks.description!,
    tool: hubspotListContactTasks,
    requiredAuth: 'hubspotToken' as const,
    scope: 'read' as const,
    keywords: ['browse', 'person', 'todo'],
  },
  {
    name: 'hubspotListConversationThreads',
    description: hubspotListConversationThreads.description!,
    tool: hubspotListConversationThreads,
    requiredAuth: 'hubspotToken' as const,
    scope: 'read' as const,
    keywords: ['browse'],
  },
  {
    name: 'hubspotListDealActivities',
    description: hubspotListDealActivities.description!,
    tool: hubspotListDealActivities,
    requiredAuth: 'hubspotToken' as const,
    scope: 'read' as const,
    keywords: ['browse', 'opportunity'],
  },
  {
    name: 'hubspotListDealMeetings',
    description: hubspotListDealMeetings.description!,
    tool: hubspotListDealMeetings,
    requiredAuth: 'hubspotToken' as const,
    scope: 'read' as const,
    keywords: ['browse', 'opportunity', 'call slot'],
  },
  {
    name: 'hubspotListDeals',
    description: hubspotListDeals.description!,
    tool: hubspotListDeals,
    requiredAuth: 'hubspotToken' as const,
    scope: 'read' as const,
    keywords: ['browse', 'opportunity'],
  },
  {
    name: 'hubspotListEmailEvents',
    description: hubspotListEmailEvents.description!,
    tool: hubspotListEmailEvents,
    requiredAuth: 'hubspotToken' as const,
    scope: 'read' as const,
    keywords: ['browse', 'message'],
  },
  {
    name: 'hubspotListEmails',
    description: hubspotListEmails.description!,
    tool: hubspotListEmails,
    requiredAuth: 'hubspotToken' as const,
    scope: 'read' as const,
    keywords: ['browse', 'message'],
  },
  {
    name: 'hubspotListEventTemplates',
    description: hubspotListEventTemplates.description!,
    tool: hubspotListEventTemplates,
    requiredAuth: 'hubspotToken' as const,
    scope: 'read' as const,
    keywords: ['browse'],
  },
  {
    name: 'hubspotListFeedbackSubmissions',
    description: hubspotListFeedbackSubmissions.description!,
    tool: hubspotListFeedbackSubmissions,
    requiredAuth: 'hubspotToken' as const,
    scope: 'read' as const,
    keywords: ['browse'],
  },
  {
    name: 'hubspotListGrantedScopes',
    description: hubspotListGrantedScopes.description!,
    tool: hubspotListGrantedScopes,
    requiredAuth: 'hubspotToken' as const,
    scope: 'read' as const,
    keywords: ['browse'],
  },
  {
    name: 'hubspotListObjectAssociations',
    description: hubspotListObjectAssociations.description!,
    tool: hubspotListObjectAssociations,
    requiredAuth: 'hubspotToken' as const,
    scope: 'read' as const,
    keywords: ['browse', 'link', 'relationship'],
  },
  {
    name: 'hubspotListProducts',
    description: hubspotListProducts.description!,
    tool: hubspotListProducts,
    requiredAuth: 'hubspotToken' as const,
    scope: 'read' as const,
    keywords: ['browse', 'catalog item'],
  },
  {
    name: 'hubspotListQuotes',
    description: hubspotListQuotes.description!,
    tool: hubspotListQuotes,
    requiredAuth: 'hubspotToken' as const,
    scope: 'read' as const,
    keywords: ['browse', 'proposal'],
  },
  {
    name: 'hubspotListRecentlyModifiedEngagements',
    description: hubspotListRecentlyModifiedEngagements.description!,
    tool: hubspotListRecentlyModifiedEngagements,
    requiredAuth: 'hubspotToken' as const,
    scope: 'read' as const,
    keywords: ['browse', 'activity'],
  },
  {
    name: 'hubspotListSequences',
    description: hubspotListSequences.description!,
    tool: hubspotListSequences,
    requiredAuth: 'hubspotToken' as const,
    scope: 'read' as const,
    keywords: ['browse', 'cadence'],
  },
  {
    name: 'hubspotListSitePages',
    description: hubspotListSitePages.description!,
    tool: hubspotListSitePages,
    requiredAuth: 'hubspotToken' as const,
    scope: 'read' as const,
    keywords: ['browse', 'webpage'],
  },
  {
    name: 'hubspotListTickets',
    description: hubspotListTickets.description!,
    tool: hubspotListTickets,
    requiredAuth: 'hubspotToken' as const,
    scope: 'read' as const,
    keywords: ['browse', 'support case'],
  },
  {
    name: 'hubspotMergeCompanies',
    description: hubspotMergeCompanies.description!,
    tool: hubspotMergeCompanies,
    requiredAuth: 'hubspotToken' as const,
    scope: 'write' as const,
    keywords: ['combine', 'deduplicate'],
  },
  {
    name: 'hubspotMergeContacts',
    description: hubspotMergeContacts.description!,
    tool: hubspotMergeContacts,
    requiredAuth: 'hubspotToken' as const,
    scope: 'write' as const,
    keywords: ['combine', 'deduplicate', 'person'],
  },
  {
    name: 'hubspotMergeDeals',
    description: hubspotMergeDeals.description!,
    tool: hubspotMergeDeals,
    requiredAuth: 'hubspotToken' as const,
    scope: 'write' as const,
    keywords: ['combine', 'deduplicate', 'opportunity'],
  },
  {
    name: 'hubspotMergeEmails',
    description: hubspotMergeEmails.description!,
    tool: hubspotMergeEmails,
    requiredAuth: 'hubspotToken' as const,
    scope: 'write' as const,
    keywords: ['combine', 'deduplicate', 'message'],
  },
  {
    name: 'hubspotMergeFeedbackSubmissions',
    description: hubspotMergeFeedbackSubmissions.description!,
    tool: hubspotMergeFeedbackSubmissions,
    requiredAuth: 'hubspotToken' as const,
    scope: 'write' as const,
    keywords: ['combine', 'deduplicate'],
  },
  {
    name: 'hubspotMergeLineItems',
    description: hubspotMergeLineItems.description!,
    tool: hubspotMergeLineItems,
    requiredAuth: 'hubspotToken' as const,
    scope: 'write' as const,
    keywords: ['combine', 'deduplicate'],
  },
  {
    name: 'hubspotMergeObjects',
    description: hubspotMergeObjects.description!,
    tool: hubspotMergeObjects,
    requiredAuth: 'hubspotToken' as const,
    scope: 'write' as const,
    keywords: ['combine', 'deduplicate'],
  },
  {
    name: 'hubspotMergeProducts',
    description: hubspotMergeProducts.description!,
    tool: hubspotMergeProducts,
    requiredAuth: 'hubspotToken' as const,
    scope: 'write' as const,
    keywords: ['combine', 'deduplicate', 'catalog item'],
  },
  {
    name: 'hubspotMergeQuotes',
    description: hubspotMergeQuotes.description!,
    tool: hubspotMergeQuotes,
    requiredAuth: 'hubspotToken' as const,
    scope: 'write' as const,
    keywords: ['combine', 'deduplicate', 'proposal'],
  },
  {
    name: 'hubspotMergeTickets',
    description: hubspotMergeTickets.description!,
    tool: hubspotMergeTickets,
    requiredAuth: 'hubspotToken' as const,
    scope: 'write' as const,
    keywords: ['combine', 'deduplicate', 'support case'],
  },
  {
    name: 'hubspotPartiallyUpdateCrmObjectById',
    description: hubspotPartiallyUpdateCrmObjectById.description!,
    tool: hubspotPartiallyUpdateCrmObjectById,
    requiredAuth: 'hubspotToken' as const,
    scope: 'write' as const,
    keywords: ['patch', 'edit'],
  },
  {
    name: 'hubspotPermanentlyDeleteContactViaGdpr',
    description: hubspotPermanentlyDeleteContactViaGdpr.description!,
    tool: hubspotPermanentlyDeleteContactViaGdpr,
    requiredAuth: 'hubspotToken' as const,
    scope: 'delete' as const,
    keywords: ['erase', 'person'],
  },
  {
    name: 'hubspotPublishMarketingEmail',
    description: hubspotPublishMarketingEmail.description!,
    tool: hubspotPublishMarketingEmail,
    requiredAuth: 'hubspotToken' as const,
    scope: 'write' as const,
    keywords: ['send', 'release', 'message'],
  },
  {
    name: 'hubspotPurgeSchema',
    description: hubspotPurgeSchema.description!,
    tool: hubspotPurgeSchema,
    requiredAuth: 'hubspotToken' as const,
    scope: 'delete' as const,
    keywords: ['erase'],
  },
  {
    name: 'hubspotReadACrmPropertyByName',
    description: hubspotReadACrmPropertyByName.description!,
    tool: hubspotReadACrmPropertyByName,
    requiredAuth: 'hubspotToken' as const,
    scope: 'read' as const,
    keywords: ['lookup', 'fetch', 'field', 'attribute'],
  },
  {
    name: 'hubspotReadAllPropertiesForObjectType',
    description: hubspotReadAllPropertiesForObjectType.description!,
    tool: hubspotReadAllPropertiesForObjectType,
    requiredAuth: 'hubspotToken' as const,
    scope: 'read' as const,
    keywords: ['lookup', 'fetch'],
  },
  {
    name: 'hubspotReadApageOfObjectsByType',
    description: hubspotReadApageOfObjectsByType.description!,
    tool: hubspotReadApageOfObjectsByType,
    requiredAuth: 'hubspotToken' as const,
    scope: 'read' as const,
    keywords: ['lookup', 'fetch'],
  },
  {
    name: 'hubspotReadAssociationsBatch',
    description: hubspotReadAssociationsBatch.description!,
    tool: hubspotReadAssociationsBatch,
    requiredAuth: 'hubspotToken' as const,
    scope: 'read' as const,
    keywords: ['lookup', 'fetch', 'link', 'relationship'],
  },
  {
    name: 'hubspotReadBatchCrmObjectProperties',
    description: hubspotReadBatchCrmObjectProperties.description!,
    tool: hubspotReadBatchCrmObjectProperties,
    requiredAuth: 'hubspotToken' as const,
    scope: 'read' as const,
    keywords: ['lookup', 'fetch'],
  },
  {
    name: 'hubspotReadBatchFeedbackSubmissionsByIdOrProperty',
    description: hubspotReadBatchFeedbackSubmissionsByIdOrProperty.description!,
    tool: hubspotReadBatchFeedbackSubmissionsByIdOrProperty,
    requiredAuth: 'hubspotToken' as const,
    scope: 'read' as const,
    keywords: ['lookup', 'fetch', 'field', 'attribute'],
  },
  {
    name: 'hubspotReadBatchOfCrmObjectsByIdOrPropertyValues',
    description: hubspotReadBatchOfCrmObjectsByIdOrPropertyValues.description!,
    tool: hubspotReadBatchOfCrmObjectsByIdOrPropertyValues,
    requiredAuth: 'hubspotToken' as const,
    scope: 'read' as const,
    keywords: ['lookup', 'fetch', 'field', 'attribute'],
  },
  {
    name: 'hubspotReadBatchOfLineItemsByIdOrPropertyValues',
    description: hubspotReadBatchOfLineItemsByIdOrPropertyValues.description!,
    tool: hubspotReadBatchOfLineItemsByIdOrPropertyValues,
    requiredAuth: 'hubspotToken' as const,
    scope: 'read' as const,
    keywords: ['lookup', 'fetch', 'field', 'attribute'],
  },
  {
    name: 'hubspotReadBatchOfQuotesByPropertyValues',
    description: hubspotReadBatchOfQuotesByPropertyValues.description!,
    tool: hubspotReadBatchOfQuotesByPropertyValues,
    requiredAuth: 'hubspotToken' as const,
    scope: 'read' as const,
    keywords: ['lookup', 'fetch', 'proposal', 'field'],
  },
  {
    name: 'hubspotReadBudget',
    description: hubspotReadBudget.description!,
    tool: hubspotReadBudget,
    requiredAuth: 'hubspotToken' as const,
    scope: 'read' as const,
    keywords: ['lookup', 'fetch'],
  },
  {
    name: 'hubspotReadContact',
    description: hubspotReadContact.description!,
    tool: hubspotReadContact,
    requiredAuth: 'hubspotToken' as const,
    scope: 'read' as const,
    keywords: ['lookup', 'fetch', 'person'],
  },
  {
    name: 'hubspotReadContacts',
    description: hubspotReadContacts.description!,
    tool: hubspotReadContacts,
    requiredAuth: 'hubspotToken' as const,
    scope: 'read' as const,
    keywords: ['lookup', 'fetch', 'person'],
  },
  {
    name: 'hubspotReadCrmObjectById',
    description: hubspotReadCrmObjectById.description!,
    tool: hubspotReadCrmObjectById,
    requiredAuth: 'hubspotToken' as const,
    scope: 'read' as const,
    keywords: ['lookup', 'fetch'],
  },
  {
    name: 'hubspotReadEmail',
    description: hubspotReadEmail.description!,
    tool: hubspotReadEmail,
    requiredAuth: 'hubspotToken' as const,
    scope: 'read' as const,
    keywords: ['lookup', 'fetch', 'message'],
  },
  {
    name: 'hubspotReadFeedbackSubmissionById',
    description: hubspotReadFeedbackSubmissionById.description!,
    tool: hubspotReadFeedbackSubmissionById,
    requiredAuth: 'hubspotToken' as const,
    scope: 'read' as const,
    keywords: ['lookup', 'fetch'],
  },
  {
    name: 'hubspotReadPropertyGroup',
    description: hubspotReadPropertyGroup.description!,
    tool: hubspotReadPropertyGroup,
    requiredAuth: 'hubspotToken' as const,
    scope: 'read' as const,
    keywords: ['lookup', 'fetch', 'field', 'attribute'],
  },
  {
    name: 'hubspotReadPropertyGroupsForObjectType',
    description: hubspotReadPropertyGroupsForObjectType.description!,
    tool: hubspotReadPropertyGroupsForObjectType,
    requiredAuth: 'hubspotToken' as const,
    scope: 'read' as const,
    keywords: ['lookup', 'fetch', 'field', 'attribute'],
  },
  {
    name: 'hubspotRemoveAssetAssociation',
    description: hubspotRemoveAssetAssociation.description!,
    tool: hubspotRemoveAssetAssociation,
    requiredAuth: 'hubspotToken' as const,
    scope: 'delete' as const,
    keywords: ['detach', 'unlink', 'attachment', 'link'],
  },
  {
    name: 'hubspotRemoveAssociation',
    description: hubspotRemoveAssociation.description!,
    tool: hubspotRemoveAssociation,
    requiredAuth: 'hubspotToken' as const,
    scope: 'delete' as const,
    keywords: ['detach', 'unlink', 'link', 'relationship'],
  },
  {
    name: 'hubspotRemoveAssociationFromSchema',
    description: hubspotRemoveAssociationFromSchema.description!,
    tool: hubspotRemoveAssociationFromSchema,
    requiredAuth: 'hubspotToken' as const,
    scope: 'delete' as const,
    keywords: ['detach', 'unlink', 'link', 'relationship'],
  },
  {
    name: 'hubspotRemoveDeal',
    description: hubspotRemoveDeal.description!,
    tool: hubspotRemoveDeal,
    requiredAuth: 'hubspotToken' as const,
    scope: 'delete' as const,
    keywords: ['detach', 'unlink', 'opportunity'],
  },
  {
    name: 'hubspotRemoveTokenFromEventTemplate',
    description: hubspotRemoveTokenFromEventTemplate.description!,
    tool: hubspotRemoveTokenFromEventTemplate,
    requiredAuth: 'hubspotToken' as const,
    scope: 'delete' as const,
    keywords: ['detach', 'unlink', 'variable'],
  },
  {
    name: 'hubspotRenderEventDetailTemplate',
    description: hubspotRenderEventDetailTemplate.description!,
    tool: hubspotRenderEventDetailTemplate,
    requiredAuth: 'hubspotToken' as const,
    scope: 'read' as const,
    keywords: ['preview'],
  },
  {
    name: 'hubspotRenderEventHeaderOrDetailAsHtml',
    description: hubspotRenderEventHeaderOrDetailAsHtml.description!,
    tool: hubspotRenderEventHeaderOrDetailAsHtml,
    requiredAuth: 'hubspotToken' as const,
    scope: 'read' as const,
    keywords: ['preview'],
  },
  {
    name: 'hubspotReplaceAllPropertiesOfPipeline',
    description: hubspotReplaceAllPropertiesOfPipeline.description!,
    tool: hubspotReplaceAllPropertiesOfPipeline,
    requiredAuth: 'hubspotToken' as const,
    scope: 'write' as const,
    keywords: ['overwrite', 'funnel'],
  },
  {
    name: 'hubspotReplacePipelineStageProperties',
    description: hubspotReplacePipelineStageProperties.description!,
    tool: hubspotReplacePipelineStageProperties,
    requiredAuth: 'hubspotToken' as const,
    scope: 'write' as const,
    keywords: ['overwrite', 'funnel'],
  },
  {
    name: 'hubspotResetDraft',
    description: hubspotResetDraft.description!,
    tool: hubspotResetDraft,
    requiredAuth: 'hubspotToken' as const,
    scope: 'write' as const,
    keywords: ['recover'],
  },
  {
    name: 'hubspotRestoreEmailRevision',
    description: hubspotRestoreEmailRevision.description!,
    tool: hubspotRestoreEmailRevision,
    requiredAuth: 'hubspotToken' as const,
    scope: 'write' as const,
    keywords: ['recover', 'revert', 'message'],
  },
  {
    name: 'hubspotRestoreMarketingEmailRevision',
    description: hubspotRestoreMarketingEmailRevision.description!,
    tool: hubspotRestoreMarketingEmailRevision,
    requiredAuth: 'hubspotToken' as const,
    scope: 'write' as const,
    keywords: ['recover', 'revert', 'message'],
  },
  {
    name: 'hubspotRetrieveAllObjectSchemas',
    description: hubspotRetrieveAllObjectSchemas.description!,
    tool: hubspotRetrieveAllObjectSchemas,
    requiredAuth: 'hubspotToken' as const,
    scope: 'read' as const,
    keywords: ['lookup', 'fetch'],
  },
  {
    name: 'hubspotRetrieveAllPipelinesForSpecifiedObjectType',
    description: hubspotRetrieveAllPipelinesForSpecifiedObjectType.description!,
    tool: hubspotRetrieveAllPipelinesForSpecifiedObjectType,
    requiredAuth: 'hubspotToken' as const,
    scope: 'read' as const,
    keywords: ['lookup', 'fetch', 'funnel'],
  },
  {
    name: 'hubspotRetrieveCallingSettingsForApp',
    description: hubspotRetrieveCallingSettingsForApp.description!,
    tool: hubspotRetrieveCallingSettingsForApp,
    requiredAuth: 'hubspotToken' as const,
    scope: 'read' as const,
    keywords: ['lookup', 'fetch'],
  },
  {
    name: 'hubspotRetrieveLineItemById',
    description: hubspotRetrieveLineItemById.description!,
    tool: hubspotRetrieveLineItemById,
    requiredAuth: 'hubspotToken' as const,
    scope: 'read' as const,
    keywords: ['lookup', 'fetch'],
  },
  {
    name: 'hubspotRetrieveLineItems',
    description: hubspotRetrieveLineItems.description!,
    tool: hubspotRetrieveLineItems,
    requiredAuth: 'hubspotToken' as const,
    scope: 'read' as const,
    keywords: ['lookup', 'fetch'],
  },
  {
    name: 'hubspotRetrieveObjectSchema',
    description: hubspotRetrieveObjectSchema.description!,
    tool: hubspotRetrieveObjectSchema,
    requiredAuth: 'hubspotToken' as const,
    scope: 'read' as const,
    keywords: ['lookup', 'fetch'],
  },
  {
    name: 'hubspotRetrieveOwnerByIdOrUserId',
    description: hubspotRetrieveOwnerByIdOrUserId.description!,
    tool: hubspotRetrieveOwnerByIdOrUserId,
    requiredAuth: 'hubspotToken' as const,
    scope: 'read' as const,
    keywords: ['lookup', 'fetch', 'rep'],
  },
  {
    name: 'hubspotRetrieveOwners',
    description: hubspotRetrieveOwners.description!,
    tool: hubspotRetrieveOwners,
    requiredAuth: 'hubspotToken' as const,
    scope: 'read' as const,
    keywords: ['lookup', 'fetch', 'user', 'rep'],
  },
  {
    name: 'hubspotRetrievePageOfCrmOwners',
    description: hubspotRetrievePageOfCrmOwners.description!,
    tool: hubspotRetrievePageOfCrmOwners,
    requiredAuth: 'hubspotToken' as const,
    scope: 'read' as const,
    keywords: ['lookup', 'fetch', 'webpage', 'user'],
  },
  {
    name: 'hubspotRetrievePipelineStageById',
    description: hubspotRetrievePipelineStageById.description!,
    tool: hubspotRetrievePipelineStageById,
    requiredAuth: 'hubspotToken' as const,
    scope: 'read' as const,
    keywords: ['lookup', 'fetch', 'funnel'],
  },
  {
    name: 'hubspotRetrievePipelineStages',
    description: hubspotRetrievePipelineStages.description!,
    tool: hubspotRetrievePipelineStages,
    requiredAuth: 'hubspotToken' as const,
    scope: 'read' as const,
    keywords: ['lookup', 'fetch', 'funnel'],
  },
  {
    name: 'hubspotRetrieveTimelineEventByIds',
    description: hubspotRetrieveTimelineEventByIds.description!,
    tool: hubspotRetrieveTimelineEventByIds,
    requiredAuth: 'hubspotToken' as const,
    scope: 'read' as const,
    keywords: ['lookup', 'fetch', 'activity feed'],
  },
  {
    name: 'hubspotRetrieveVideoConferenceSettingsById',
    description: hubspotRetrieveVideoConferenceSettingsById.description!,
    tool: hubspotRetrieveVideoConferenceSettingsById,
    requiredAuth: 'hubspotToken' as const,
    scope: 'read' as const,
    keywords: ['lookup', 'fetch'],
  },
  {
    name: 'hubspotSearchCampaigns',
    description: hubspotSearchCampaigns.description!,
    tool: hubspotSearchCampaigns,
    requiredAuth: 'hubspotToken' as const,
    scope: 'read' as const,
    keywords: ['query', 'find', 'initiative'],
  },
  {
    name: 'hubspotSearchCompanies',
    description: hubspotSearchCompanies.description!,
    tool: hubspotSearchCompanies,
    requiredAuth: 'hubspotToken' as const,
    scope: 'read' as const,
    keywords: ['query', 'find'],
  },
  {
    name: 'hubspotSearchContactsByCriteria',
    description: hubspotSearchContactsByCriteria.description!,
    tool: hubspotSearchContactsByCriteria,
    requiredAuth: 'hubspotToken' as const,
    scope: 'read' as const,
    keywords: ['query', 'find', 'person'],
  },
  {
    name: 'hubspotSearchCrmObjectsByCriteria',
    description: hubspotSearchCrmObjectsByCriteria.description!,
    tool: hubspotSearchCrmObjectsByCriteria,
    requiredAuth: 'hubspotToken' as const,
    scope: 'read' as const,
    keywords: ['query', 'find'],
  },
  {
    name: 'hubspotSearchDeals',
    description: hubspotSearchDeals.description!,
    tool: hubspotSearchDeals,
    requiredAuth: 'hubspotToken' as const,
    scope: 'read' as const,
    keywords: ['query', 'find', 'opportunity'],
  },
  {
    name: 'hubspotSearchEmails',
    description: hubspotSearchEmails.description!,
    tool: hubspotSearchEmails,
    requiredAuth: 'hubspotToken' as const,
    scope: 'read' as const,
    keywords: ['query', 'find', 'message'],
  },
  {
    name: 'hubspotSearchFeedbackSubmissions',
    description: hubspotSearchFeedbackSubmissions.description!,
    tool: hubspotSearchFeedbackSubmissions,
    requiredAuth: 'hubspotToken' as const,
    scope: 'read' as const,
    keywords: ['query', 'find'],
  },
  {
    name: 'hubspotSearchLineItemsByCriteria',
    description: hubspotSearchLineItemsByCriteria.description!,
    tool: hubspotSearchLineItemsByCriteria,
    requiredAuth: 'hubspotToken' as const,
    scope: 'read' as const,
    keywords: ['query', 'find'],
  },
  {
    name: 'hubspotSearchProducts',
    description: hubspotSearchProducts.description!,
    tool: hubspotSearchProducts,
    requiredAuth: 'hubspotToken' as const,
    scope: 'read' as const,
    keywords: ['query', 'find', 'catalog item'],
  },
  {
    name: 'hubspotSearchQuotesByCriteria',
    description: hubspotSearchQuotesByCriteria.description!,
    tool: hubspotSearchQuotesByCriteria,
    requiredAuth: 'hubspotToken' as const,
    scope: 'read' as const,
    keywords: ['query', 'find', 'proposal'],
  },
  {
    name: 'hubspotSearchTickets',
    description: hubspotSearchTickets.description!,
    tool: hubspotSearchTickets,
    requiredAuth: 'hubspotToken' as const,
    scope: 'read' as const,
    keywords: ['query', 'find', 'support case'],
  },
  {
    name: 'hubspotSetCallRecordingSettings',
    description: hubspotSetCallRecordingSettings.description!,
    tool: hubspotSetCallRecordingSettings,
    requiredAuth: 'hubspotToken' as const,
    scope: 'write' as const,
    keywords: ['configure', 'phone log'],
  },
  {
    name: 'hubspotStartImport',
    description: hubspotStartImport.description!,
    tool: hubspotStartImport,
    requiredAuth: 'hubspotToken' as const,
    scope: 'write' as const,
    keywords: ['begin', 'launch', 'upload', 'migration'],
  },
  {
    name: 'hubspotUpdateAMarketingEmail',
    description: hubspotUpdateAMarketingEmail.description!,
    tool: hubspotUpdateAMarketingEmail,
    requiredAuth: 'hubspotToken' as const,
    scope: 'write' as const,
    keywords: ['edit', 'modify', 'message'],
  },
  {
    name: 'hubspotUpdateBatchFeedbackSubmissions',
    description: hubspotUpdateBatchFeedbackSubmissions.description!,
    tool: hubspotUpdateBatchFeedbackSubmissions,
    requiredAuth: 'hubspotToken' as const,
    scope: 'write' as const,
    keywords: ['edit', 'modify'],
  },
  {
    name: 'hubspotUpdateBatchOfObjectsByIdorPropertyValues',
    description: hubspotUpdateBatchOfObjectsByIdorPropertyValues.description!,
    tool: hubspotUpdateBatchOfObjectsByIdorPropertyValues,
    requiredAuth: 'hubspotToken' as const,
    scope: 'write' as const,
    keywords: ['edit', 'modify', 'field', 'attribute'],
  },
  {
    name: 'hubspotUpdateCallingAppRecordingSettings',
    description: hubspotUpdateCallingAppRecordingSettings.description!,
    tool: hubspotUpdateCallingAppRecordingSettings,
    requiredAuth: 'hubspotToken' as const,
    scope: 'write' as const,
    keywords: ['edit', 'modify'],
  },
  {
    name: 'hubspotUpdateCallingExtensionSettings',
    description: hubspotUpdateCallingExtensionSettings.description!,
    tool: hubspotUpdateCallingExtensionSettings,
    requiredAuth: 'hubspotToken' as const,
    scope: 'write' as const,
    keywords: ['edit', 'modify'],
  },
  {
    name: 'hubspotUpdateCampaign',
    description: hubspotUpdateCampaign.description!,
    tool: hubspotUpdateCampaign,
    requiredAuth: 'hubspotToken' as const,
    scope: 'write' as const,
    keywords: ['edit', 'modify', 'initiative'],
  },
  {
    name: 'hubspotUpdateCampaigns',
    description: hubspotUpdateCampaigns.description!,
    tool: hubspotUpdateCampaigns,
    requiredAuth: 'hubspotToken' as const,
    scope: 'write' as const,
    keywords: ['edit', 'modify', 'initiative'],
  },
  {
    name: 'hubspotUpdateCompanies',
    description: hubspotUpdateCompanies.description!,
    tool: hubspotUpdateCompanies,
    requiredAuth: 'hubspotToken' as const,
    scope: 'write' as const,
    keywords: ['edit', 'modify'],
  },
  {
    name: 'hubspotUpdateCompany',
    description: hubspotUpdateCompany.description!,
    tool: hubspotUpdateCompany,
    requiredAuth: 'hubspotToken' as const,
    scope: 'write' as const,
    keywords: ['edit', 'modify', 'account', 'organization'],
  },
  {
    name: 'hubspotUpdateContact',
    description: hubspotUpdateContact.description!,
    tool: hubspotUpdateContact,
    requiredAuth: 'hubspotToken' as const,
    scope: 'write' as const,
    keywords: ['edit', 'modify', 'person'],
  },
  {
    name: 'hubspotUpdateContacts',
    description: hubspotUpdateContacts.description!,
    tool: hubspotUpdateContacts,
    requiredAuth: 'hubspotToken' as const,
    scope: 'write' as const,
    keywords: ['edit', 'modify', 'person'],
  },
  {
    name: 'hubspotUpdateCrmProperty',
    description: hubspotUpdateCrmProperty.description!,
    tool: hubspotUpdateCrmProperty,
    requiredAuth: 'hubspotToken' as const,
    scope: 'write' as const,
    keywords: ['edit', 'modify', 'field', 'attribute'],
  },
  {
    name: 'hubspotUpdateDeal',
    description: hubspotUpdateDeal.description!,
    tool: hubspotUpdateDeal,
    requiredAuth: 'hubspotToken' as const,
    scope: 'write' as const,
    keywords: ['edit', 'modify', 'opportunity'],
  },
  {
    name: 'hubspotUpdateDeals',
    description: hubspotUpdateDeals.description!,
    tool: hubspotUpdateDeals,
    requiredAuth: 'hubspotToken' as const,
    scope: 'write' as const,
    keywords: ['edit', 'modify', 'opportunity'],
  },
  {
    name: 'hubspotUpdateEmail',
    description: hubspotUpdateEmail.description!,
    tool: hubspotUpdateEmail,
    requiredAuth: 'hubspotToken' as const,
    scope: 'write' as const,
    keywords: ['edit', 'modify', 'message'],
  },
  {
    name: 'hubspotUpdateEmails',
    description: hubspotUpdateEmails.description!,
    tool: hubspotUpdateEmails,
    requiredAuth: 'hubspotToken' as const,
    scope: 'write' as const,
    keywords: ['edit', 'modify', 'message'],
  },
  {
    name: 'hubspotUpdateEventTemplate',
    description: hubspotUpdateEventTemplate.description!,
    tool: hubspotUpdateEventTemplate,
    requiredAuth: 'hubspotToken' as const,
    scope: 'write' as const,
    keywords: ['edit', 'modify'],
  },
  {
    name: 'hubspotUpdateFeedbackSubmission',
    description: hubspotUpdateFeedbackSubmission.description!,
    tool: hubspotUpdateFeedbackSubmission,
    requiredAuth: 'hubspotToken' as const,
    scope: 'write' as const,
    keywords: ['edit', 'modify'],
  },
  {
    name: 'hubspotUpdateLineItem',
    description: hubspotUpdateLineItem.description!,
    tool: hubspotUpdateLineItem,
    requiredAuth: 'hubspotToken' as const,
    scope: 'write' as const,
    keywords: ['edit', 'modify'],
  },
  {
    name: 'hubspotUpdateLineItems',
    description: hubspotUpdateLineItems.description!,
    tool: hubspotUpdateLineItems,
    requiredAuth: 'hubspotToken' as const,
    scope: 'write' as const,
    keywords: ['edit', 'modify'],
  },
  {
    name: 'hubspotUpdateObjectSchema',
    description: hubspotUpdateObjectSchema.description!,
    tool: hubspotUpdateObjectSchema,
    requiredAuth: 'hubspotToken' as const,
    scope: 'write' as const,
    keywords: ['edit', 'modify'],
  },
  {
    name: 'hubspotUpdatePipeline',
    description: hubspotUpdatePipeline.description!,
    tool: hubspotUpdatePipeline,
    requiredAuth: 'hubspotToken' as const,
    scope: 'write' as const,
    keywords: ['edit', 'modify', 'funnel'],
  },
  {
    name: 'hubspotUpdatePipelineStage',
    description: hubspotUpdatePipelineStage.description!,
    tool: hubspotUpdatePipelineStage,
    requiredAuth: 'hubspotToken' as const,
    scope: 'write' as const,
    keywords: ['edit', 'modify', 'funnel'],
  },
  {
    name: 'hubspotUpdateProduct',
    description: hubspotUpdateProduct.description!,
    tool: hubspotUpdateProduct,
    requiredAuth: 'hubspotToken' as const,
    scope: 'write' as const,
    keywords: ['edit', 'modify', 'catalog item'],
  },
  {
    name: 'hubspotUpdateProducts',
    description: hubspotUpdateProducts.description!,
    tool: hubspotUpdateProducts,
    requiredAuth: 'hubspotToken' as const,
    scope: 'write' as const,
    keywords: ['edit', 'modify', 'catalog item'],
  },
  {
    name: 'hubspotUpdatePropertyGroup',
    description: hubspotUpdatePropertyGroup.description!,
    tool: hubspotUpdatePropertyGroup,
    requiredAuth: 'hubspotToken' as const,
    scope: 'write' as const,
    keywords: ['edit', 'modify', 'field', 'attribute'],
  },
  {
    name: 'hubspotUpdateQuote',
    description: hubspotUpdateQuote.description!,
    tool: hubspotUpdateQuote,
    requiredAuth: 'hubspotToken' as const,
    scope: 'write' as const,
    keywords: ['edit', 'modify', 'proposal'],
  },
  {
    name: 'hubspotUpdateTicket',
    description: hubspotUpdateTicket.description!,
    tool: hubspotUpdateTicket,
    requiredAuth: 'hubspotToken' as const,
    scope: 'write' as const,
    keywords: ['edit', 'modify', 'support case'],
  },
  {
    name: 'hubspotUpdateTickets',
    description: hubspotUpdateTickets.description!,
    tool: hubspotUpdateTickets,
    requiredAuth: 'hubspotToken' as const,
    scope: 'write' as const,
    keywords: ['edit', 'modify', 'support case'],
  },
  {
    name: 'hubspotUpdateTokenOnEventTemplate',
    description: hubspotUpdateTokenOnEventTemplate.description!,
    tool: hubspotUpdateTokenOnEventTemplate,
    requiredAuth: 'hubspotToken' as const,
    scope: 'write' as const,
    keywords: ['edit', 'modify', 'variable'],
  },
  {
    name: 'hubspotUpdateVideoConferenceAppSettings',
    description: hubspotUpdateVideoConferenceAppSettings.description!,
    tool: hubspotUpdateVideoConferenceAppSettings,
    requiredAuth: 'hubspotToken' as const,
    scope: 'write' as const,
    keywords: ['edit', 'modify'],
  },
  {
    name: 'hubspotUpdateWorkflow',
    description: hubspotUpdateWorkflow.description!,
    tool: hubspotUpdateWorkflow,
    requiredAuth: 'hubspotToken' as const,
    scope: 'write' as const,
    keywords: ['edit', 'modify'],
  },
  {
    name: 'hubspotUpsertContacts',
    description: hubspotUpsertContacts.description!,
    tool: hubspotUpsertContacts,
    requiredAuth: 'hubspotToken' as const,
    scope: 'write' as const,
    keywords: ['person'],
  },
  {
    name: 'hubspotWhoAmI',
    description: hubspotWhoAmI.description!,
    tool: hubspotWhoAmI,
    requiredAuth: 'hubspotToken' as const,
    scope: 'read' as const,
    keywords: ['identity'],
  },
];
