// @ts-nocheck
import {
  digitalOceanCreateDroplet,
  digitalOceanDeleteDroplet,
  digitalOceanListDroplets,
  digitalOceanRetrieveDroplet,
} from './droplets.js';
import {
  digitalOceanCreateDomain,
  digitalOceanCreateDomainRecord,
  digitalOceanDeleteDomain,
  digitalOceanDeleteDomainRecord,
  digitalOceanListDomainRecords,
  digitalOceanListDomains,
  digitalOceanRetrieveDomain,
  digitalOceanRetrieveDomainRecord,
  digitalOceanUpdateDomainRecord,
} from './domains.js';
import {
  digitalOceanCreateFirewall,
  digitalOceanDeleteFirewall,
  digitalOceanListFirewalls,
} from './firewalls.js';
import {
  digitalOceanCreateCustomImage,
  digitalOceanDeleteImage,
  digitalOceanListImages,
  digitalOceanListSnapshots,
  digitalOceanRetrieveImage,
} from './images.js';
import {
  digitalOceanCreateDatabaseCluster,
  digitalOceanDeleteDatabaseCluster,
  digitalOceanListDatabaseOptions,
  digitalOceanListDatabases,
} from './databases.js';
import {
  digitalOceanCreateKubernetesCluster,
  digitalOceanListKubernetesClusters,
} from './kubernetes.js';
import {
  digitalOceanCreateLoadBalancer,
  digitalOceanDeleteLoadBalancer,
  digitalOceanListLoadBalancers,
} from './load-balancers.js';
import {
  digitalOceanCreateVolume,
  digitalOceanDeleteVolume,
  digitalOceanListVolumes,
} from './volumes.js';
import {
  digitalOceanCreateSshKey,
  digitalOceanDeleteSshKey,
  digitalOceanListSshKeys,
} from './ssh-keys.js';
import {
  digitalOceanCreateTag,
  digitalOceanDeleteTag,
  digitalOceanListTags,
  digitalOceanRetrieveTag,
  digitalOceanTagResource,
  digitalOceanUntagResource,
} from './tags.js';
import {
  digitalOceanCreateVpc,
  digitalOceanDeleteVpc,
  digitalOceanListVpcs,
  digitalOceanRetrieveVpc,
  digitalOceanUpdateVpc,
} from './vpcs.js';
import { digitalOceanListApps } from './apps.js';

export {
  digitalOceanCreateDroplet,
  digitalOceanDeleteDroplet,
  digitalOceanListDroplets,
  digitalOceanRetrieveDroplet,
  digitalOceanCreateDomain,
  digitalOceanCreateDomainRecord,
  digitalOceanDeleteDomain,
  digitalOceanDeleteDomainRecord,
  digitalOceanListDomainRecords,
  digitalOceanListDomains,
  digitalOceanRetrieveDomain,
  digitalOceanRetrieveDomainRecord,
  digitalOceanUpdateDomainRecord,
  digitalOceanCreateFirewall,
  digitalOceanDeleteFirewall,
  digitalOceanListFirewalls,
  digitalOceanCreateCustomImage,
  digitalOceanDeleteImage,
  digitalOceanListImages,
  digitalOceanListSnapshots,
  digitalOceanRetrieveImage,
  digitalOceanCreateDatabaseCluster,
  digitalOceanDeleteDatabaseCluster,
  digitalOceanListDatabaseOptions,
  digitalOceanListDatabases,
  digitalOceanCreateKubernetesCluster,
  digitalOceanListKubernetesClusters,
  digitalOceanCreateLoadBalancer,
  digitalOceanDeleteLoadBalancer,
  digitalOceanListLoadBalancers,
  digitalOceanCreateVolume,
  digitalOceanDeleteVolume,
  digitalOceanListVolumes,
  digitalOceanCreateSshKey,
  digitalOceanDeleteSshKey,
  digitalOceanListSshKeys,
  digitalOceanCreateTag,
  digitalOceanDeleteTag,
  digitalOceanListTags,
  digitalOceanRetrieveTag,
  digitalOceanTagResource,
  digitalOceanUntagResource,
  digitalOceanCreateVpc,
  digitalOceanDeleteVpc,
  digitalOceanListVpcs,
  digitalOceanRetrieveVpc,
  digitalOceanUpdateVpc,
  digitalOceanListApps,
};

const auth = { requiredAuth: 'digitalOceanApiKey' as const };

export const digitalOceanTools = [
  {
    name: 'digitalOceanCreateDroplet',
    description: digitalOceanCreateDroplet.description!,
    tool: digitalOceanCreateDroplet,
    ...auth,
    scope: 'write' as const,
    keywords: ['vm', 'virtual machine', 'server', 'provision'],
  },
  {
    name: 'digitalOceanListDroplets',
    description: digitalOceanListDroplets.description!,
    tool: digitalOceanListDroplets,
    ...auth,
    scope: 'read' as const,
    keywords: ['vms', 'servers', 'inventory'],
  },
  {
    name: 'digitalOceanRetrieveDroplet',
    description: digitalOceanRetrieveDroplet.description!,
    tool: digitalOceanRetrieveDroplet,
    ...auth,
    scope: 'read' as const,
    keywords: ['vm details', 'server info'],
  },
  {
    name: 'digitalOceanDeleteDroplet',
    description: digitalOceanDeleteDroplet.description!,
    tool: digitalOceanDeleteDroplet,
    ...auth,
    scope: 'delete' as const,
    keywords: ['remove vm', 'destroy', 'terminate server'],
  },
  {
    name: 'digitalOceanCreateDomain',
    description: digitalOceanCreateDomain.description!,
    tool: digitalOceanCreateDomain,
    ...auth,
    scope: 'write' as const,
    keywords: ['dns', 'add domain', 'zone'],
  },
  {
    name: 'digitalOceanListDomains',
    description: digitalOceanListDomains.description!,
    tool: digitalOceanListDomains,
    ...auth,
    scope: 'read' as const,
    keywords: ['dns', 'zones'],
  },
  {
    name: 'digitalOceanRetrieveDomain',
    description: digitalOceanRetrieveDomain.description!,
    tool: digitalOceanRetrieveDomain,
    ...auth,
    scope: 'read' as const,
    keywords: ['dns', 'zone file'],
  },
  {
    name: 'digitalOceanDeleteDomain',
    description: digitalOceanDeleteDomain.description!,
    tool: digitalOceanDeleteDomain,
    ...auth,
    scope: 'delete' as const,
    keywords: ['dns', 'remove domain'],
  },
  {
    name: 'digitalOceanCreateDomainRecord',
    description: digitalOceanCreateDomainRecord.description!,
    tool: digitalOceanCreateDomainRecord,
    ...auth,
    scope: 'write' as const,
    keywords: ['dns record', 'a record', 'cname', 'mx', 'txt'],
  },
  {
    name: 'digitalOceanListDomainRecords',
    description: digitalOceanListDomainRecords.description!,
    tool: digitalOceanListDomainRecords,
    ...auth,
    scope: 'read' as const,
    keywords: ['dns records'],
  },
  {
    name: 'digitalOceanRetrieveDomainRecord',
    description: digitalOceanRetrieveDomainRecord.description!,
    tool: digitalOceanRetrieveDomainRecord,
    ...auth,
    scope: 'read' as const,
    keywords: ['dns record details'],
  },
  {
    name: 'digitalOceanUpdateDomainRecord',
    description: digitalOceanUpdateDomainRecord.description!,
    tool: digitalOceanUpdateDomainRecord,
    ...auth,
    scope: 'write' as const,
    keywords: ['edit dns', 'modify record'],
  },
  {
    name: 'digitalOceanDeleteDomainRecord',
    description: digitalOceanDeleteDomainRecord.description!,
    tool: digitalOceanDeleteDomainRecord,
    ...auth,
    scope: 'delete' as const,
    keywords: ['remove dns record'],
  },
  {
    name: 'digitalOceanCreateFirewall',
    description: digitalOceanCreateFirewall.description!,
    tool: digitalOceanCreateFirewall,
    ...auth,
    scope: 'write' as const,
    keywords: ['security group', 'network rules', 'cloud firewall'],
  },
  {
    name: 'digitalOceanListFirewalls',
    description: digitalOceanListFirewalls.description!,
    tool: digitalOceanListFirewalls,
    ...auth,
    scope: 'read' as const,
    keywords: ['security groups'],
  },
  {
    name: 'digitalOceanDeleteFirewall',
    description: digitalOceanDeleteFirewall.description!,
    tool: digitalOceanDeleteFirewall,
    ...auth,
    scope: 'delete' as const,
    keywords: ['remove firewall'],
  },
  {
    name: 'digitalOceanCreateCustomImage',
    description: digitalOceanCreateCustomImage.description!,
    tool: digitalOceanCreateCustomImage,
    ...auth,
    scope: 'write' as const,
    keywords: ['custom iso', 'import image', 'os image'],
  },
  {
    name: 'digitalOceanListImages',
    description: digitalOceanListImages.description!,
    tool: digitalOceanListImages,
    ...auth,
    scope: 'read' as const,
    keywords: ['os images', 'distributions'],
  },
  {
    name: 'digitalOceanRetrieveImage',
    description: digitalOceanRetrieveImage.description!,
    tool: digitalOceanRetrieveImage,
    ...auth,
    scope: 'read' as const,
    keywords: ['image details'],
  },
  {
    name: 'digitalOceanDeleteImage',
    description: digitalOceanDeleteImage.description!,
    tool: digitalOceanDeleteImage,
    ...auth,
    scope: 'delete' as const,
    keywords: ['remove image', 'delete snapshot image'],
  },
  {
    name: 'digitalOceanListSnapshots',
    description: digitalOceanListSnapshots.description!,
    tool: digitalOceanListSnapshots,
    ...auth,
    scope: 'read' as const,
    keywords: ['backups', 'droplet snapshots', 'volume snapshots'],
  },
  {
    name: 'digitalOceanCreateDatabaseCluster',
    description: digitalOceanCreateDatabaseCluster.description!,
    tool: digitalOceanCreateDatabaseCluster,
    ...auth,
    scope: 'write' as const,
    keywords: ['postgres', 'postgresql', 'mysql', 'managed database', 'db cluster'],
  },
  {
    name: 'digitalOceanListDatabases',
    description: digitalOceanListDatabases.description!,
    tool: digitalOceanListDatabases,
    ...auth,
    scope: 'read' as const,
    keywords: ['db clusters', 'managed databases'],
  },
  {
    name: 'digitalOceanDeleteDatabaseCluster',
    description: digitalOceanDeleteDatabaseCluster.description!,
    tool: digitalOceanDeleteDatabaseCluster,
    ...auth,
    scope: 'delete' as const,
    keywords: ['remove database', 'destroy db'],
  },
  {
    name: 'digitalOceanListDatabaseOptions',
    description: digitalOceanListDatabaseOptions.description!,
    tool: digitalOceanListDatabaseOptions,
    ...auth,
    scope: 'read' as const,
    keywords: ['db engines', 'db versions', 'db sizes'],
  },
  {
    name: 'digitalOceanCreateKubernetesCluster',
    description: digitalOceanCreateKubernetesCluster.description!,
    tool: digitalOceanCreateKubernetesCluster,
    ...auth,
    scope: 'write' as const,
    keywords: ['doks', 'k8s', 'node pool'],
  },
  {
    name: 'digitalOceanListKubernetesClusters',
    description: digitalOceanListKubernetesClusters.description!,
    tool: digitalOceanListKubernetesClusters,
    ...auth,
    scope: 'read' as const,
    keywords: ['doks', 'k8s clusters'],
  },
  {
    name: 'digitalOceanCreateLoadBalancer',
    description: digitalOceanCreateLoadBalancer.description!,
    tool: digitalOceanCreateLoadBalancer,
    ...auth,
    scope: 'write' as const,
    keywords: ['lb', 'traffic distribution'],
  },
  {
    name: 'digitalOceanListLoadBalancers',
    description: digitalOceanListLoadBalancers.description!,
    tool: digitalOceanListLoadBalancers,
    ...auth,
    scope: 'read' as const,
    keywords: ['lbs'],
  },
  {
    name: 'digitalOceanDeleteLoadBalancer',
    description: digitalOceanDeleteLoadBalancer.description!,
    tool: digitalOceanDeleteLoadBalancer,
    ...auth,
    scope: 'delete' as const,
    keywords: ['remove lb'],
  },
  {
    name: 'digitalOceanCreateVolume',
    description: digitalOceanCreateVolume.description!,
    tool: digitalOceanCreateVolume,
    ...auth,
    scope: 'write' as const,
    keywords: ['block storage', 'disk', 'ssd'],
  },
  {
    name: 'digitalOceanListVolumes',
    description: digitalOceanListVolumes.description!,
    tool: digitalOceanListVolumes,
    ...auth,
    scope: 'read' as const,
    keywords: ['block storage', 'disks'],
  },
  {
    name: 'digitalOceanDeleteVolume',
    description: digitalOceanDeleteVolume.description!,
    tool: digitalOceanDeleteVolume,
    ...auth,
    scope: 'delete' as const,
    keywords: ['remove volume', 'delete disk'],
  },
  {
    name: 'digitalOceanCreateSshKey',
    description: digitalOceanCreateSshKey.description!,
    tool: digitalOceanCreateSshKey,
    ...auth,
    scope: 'write' as const,
    keywords: ['ssh public key', 'add key'],
  },
  {
    name: 'digitalOceanListSshKeys',
    description: digitalOceanListSshKeys.description!,
    tool: digitalOceanListSshKeys,
    ...auth,
    scope: 'read' as const,
    keywords: ['ssh public keys'],
  },
  {
    name: 'digitalOceanDeleteSshKey',
    description: digitalOceanDeleteSshKey.description!,
    tool: digitalOceanDeleteSshKey,
    ...auth,
    scope: 'delete' as const,
    keywords: ['remove ssh key'],
  },
  {
    name: 'digitalOceanCreateTag',
    description: digitalOceanCreateTag.description!,
    tool: digitalOceanCreateTag,
    ...auth,
    scope: 'write' as const,
    keywords: ['label', 'new label'],
  },
  {
    name: 'digitalOceanListTags',
    description: digitalOceanListTags.description!,
    tool: digitalOceanListTags,
    ...auth,
    scope: 'read' as const,
    keywords: ['labels'],
  },
  {
    name: 'digitalOceanRetrieveTag',
    description: digitalOceanRetrieveTag.description!,
    tool: digitalOceanRetrieveTag,
    ...auth,
    scope: 'read' as const,
    keywords: ['label details'],
  },
  {
    name: 'digitalOceanDeleteTag',
    description: digitalOceanDeleteTag.description!,
    tool: digitalOceanDeleteTag,
    ...auth,
    scope: 'delete' as const,
    keywords: ['remove label', 'untag all'],
  },
  {
    name: 'digitalOceanTagResource',
    description: digitalOceanTagResource.description!,
    tool: digitalOceanTagResource,
    ...auth,
    scope: 'write' as const,
    keywords: ['label resource', 'apply tag'],
  },
  {
    name: 'digitalOceanUntagResource',
    description: digitalOceanUntagResource.description!,
    tool: digitalOceanUntagResource,
    ...auth,
    scope: 'write' as const,
    keywords: ['remove label', 'detach tag'],
  },
  {
    name: 'digitalOceanCreateVpc',
    description: digitalOceanCreateVpc.description!,
    tool: digitalOceanCreateVpc,
    ...auth,
    scope: 'write' as const,
    keywords: ['private network', 'virtual private cloud'],
  },
  {
    name: 'digitalOceanListVpcs',
    description: digitalOceanListVpcs.description!,
    tool: digitalOceanListVpcs,
    ...auth,
    scope: 'read' as const,
    keywords: ['private networks'],
  },
  {
    name: 'digitalOceanRetrieveVpc',
    description: digitalOceanRetrieveVpc.description!,
    tool: digitalOceanRetrieveVpc,
    ...auth,
    scope: 'read' as const,
    keywords: ['vpc details', 'network info'],
  },
  {
    name: 'digitalOceanUpdateVpc',
    description: digitalOceanUpdateVpc.description!,
    tool: digitalOceanUpdateVpc,
    ...auth,
    scope: 'write' as const,
    keywords: ['rename vpc', 'edit network'],
  },
  {
    name: 'digitalOceanDeleteVpc',
    description: digitalOceanDeleteVpc.description!,
    tool: digitalOceanDeleteVpc,
    ...auth,
    scope: 'delete' as const,
    keywords: ['remove vpc', 'delete network'],
  },
  {
    name: 'digitalOceanListApps',
    description: digitalOceanListApps.description!,
    tool: digitalOceanListApps,
    ...auth,
    scope: 'read' as const,
    keywords: ['app platform', 'deployments'],
  },
];
