// @ts-nocheck
import {
  createContact,
  getContact,
  getFundAccount,
  getSettlementRecon,
  getTransferReversals,
  listFundAccounts,
  listFundValidations,
  updateContact,
} from './payouts.js';
import {
  createCustomer,
  fetchAllCustomers,
  getCustomer,
  listCustomerTokens,
  updateCustomer,
} from './customers.js';
import {
  cancelInvoice,
  createInvoice,
  deleteInvoice,
  fetchAllInvoices,
  fetchInvoiceById,
  issueInvoice,
  sendInvoiceNotification,
  updateInvoice,
} from './invoices.js';
import {
  cancelPaymentLink,
  createItem,
  createPaymentLink,
  deleteItem,
  fetchAllPaymentLinks,
  fetchPaymentLink,
  getItem,
  listItems,
  notifyPaymentLink,
  updateItem,
  updatePaymentLink,
} from './items-links.js';
import {
  createOrder,
  fetchAllPayments,
  fetchAllRefundsForPayment,
  fetchOrderById,
  fetchOrders,
  fetchPaymentsByOrder,
  fetchRefunds,
  listDisputes,
  listPaymentDowntimes,
  updateOrder,
} from './orders.js';

export {
  createOrder,
  fetchOrders,
  fetchOrderById,
  updateOrder,
  fetchPaymentsByOrder,
  fetchAllPayments,
  fetchAllRefundsForPayment,
  fetchRefunds,
  listDisputes,
  listPaymentDowntimes,
  createCustomer,
  getCustomer,
  updateCustomer,
  fetchAllCustomers,
  listCustomerTokens,
  createInvoice,
  fetchAllInvoices,
  fetchInvoiceById,
  updateInvoice,
  deleteInvoice,
  issueInvoice,
  cancelInvoice,
  sendInvoiceNotification,
  createItem,
  getItem,
  listItems,
  updateItem,
  deleteItem,
  createPaymentLink,
  fetchPaymentLink,
  fetchAllPaymentLinks,
  updatePaymentLink,
  cancelPaymentLink,
  notifyPaymentLink,
  createContact,
  getContact,
  updateContact,
  getFundAccount,
  listFundAccounts,
  listFundValidations,
  getTransferReversals,
  getSettlementRecon,
};

const auth = 'razorpayCredentials' as const;

type Scope = 'read' | 'write' | 'delete';
function entry(
  name: string,
  description: string,
  toolRef: any,
  scope: Scope,
  keywords: string[] = [],
): {
  name: string;
  description: string;
  tool: any;
  requiredAuth: typeof auth;
  scope: Scope;
  keywords: string[];
} {
  return { name, description, tool: toolRef, requiredAuth: auth, scope, keywords };
}

export const razorpayTools = [
  entry(
    'razorpayCreateAnOrder',
    'Creates an order before collecting payment.',
    createOrder,
    'write',
    ['orders', 'payment', 'purchase', 'checkout'],
  ),
  entry('razorpayFetchOrders', 'Lists orders with filters and pagination.', fetchOrders, 'read', [
    'order',
    'payment',
    'purchase',
  ]),
  entry('razorpayFetchOrdersById', 'Reads one order by ID.', fetchOrderById, 'read', [
    'order',
    'payment',
  ]),
  entry('razorpayUpdateOrder', 'Updates order metadata notes.', updateOrder, 'write', [
    'orders',
    'payment',
  ]),
  entry(
    'razorpayFetchPaymentsByOrder',
    'Lists all payment attempts for an order.',
    fetchPaymentsByOrder,
    'read',
    ['payment', 'payments', 'order', 'transaction'],
  ),
  entry(
    'razorpayFetchAllPayments',
    'Lists payments newest-first with filters.',
    fetchAllPayments,
    'read',
    ['payment', 'transaction', 'transactions'],
  ),
  entry(
    'razorpayFetchAllRefundsForAPayment',
    'Lists refunds for one payment.',
    fetchAllRefundsForPayment,
    'read',
    ['refund', 'refunds', 'payment', 'reimburse'],
  ),
  entry('razorpayFetchRefunds', 'Lists all refunds with filters.', fetchRefunds, 'read', [
    'refund',
    'reimburse',
    'payment',
  ]),
  entry('razorpayListDisputes', 'Lists chargebacks/fraud disputes.', listDisputes, 'read', [
    'dispute',
    'chargeback',
    'fraud',
    'chargebacks',
  ]),
  entry(
    'razorpayListPaymentDowntimes',
    'Lists active payment-method downtimes.',
    listPaymentDowntimes,
    'read',
    ['downtime', 'outage', 'payment', 'status'],
  ),
  entry(
    'razorpayCreateCustomer',
    'Registers a customer for future transactions.',
    createCustomer,
    'write',
    ['customers', 'client', 'user'],
  ),
  entry('razorpayGetCustomer', 'Reads one customer by ID.', getCustomer, 'read', [
    'customers',
    'client',
  ]),
  entry('razorpayUpdateCustomer', 'Updates customer name/email/contact.', updateCustomer, 'write', [
    'customers',
    'client',
  ]),
  entry(
    'razorpayFetchAllCustomers',
    'Lists customers with pagination.',
    fetchAllCustomers,
    'read',
    ['customer', 'client', 'user'],
  ),
  entry(
    'razorpayListCustomerTokens',
    'Lists saved payment methods for a customer.',
    listCustomerTokens,
    'read',
    ['customer', 'token', 'tokens', 'card', 'saved'],
  ),
  entry(
    'razorpayCreateInvoice',
    'Creates a draft invoice with line items.',
    createInvoice,
    'write',
    ['invoices', 'bill', 'bills', 'billing'],
  ),
  entry('razorpayFetchAllInvoices', 'Lists invoices with filters.', fetchAllInvoices, 'read', [
    'invoice',
    'bill',
    'bills',
    'billing',
  ]),
  entry(
    'razorpayFetchInvoiceById',
    'Reads one invoice with full details.',
    fetchInvoiceById,
    'read',
    ['invoices', 'bill', 'billing'],
  ),
  entry('razorpayUpdateInvoice', 'Updates a draft invoice.', updateInvoice, 'write', [
    'invoices',
    'bill',
  ]),
  entry('razorpayDeleteInvoice', 'Permanently deletes a draft invoice.', deleteInvoice, 'delete', [
    'invoices',
    'bill',
    'remove',
  ]),
  entry(
    'razorpayIssueAnInvoice',
    'Issues a draft invoice to the customer.',
    issueInvoice,
    'write',
    ['invoices', 'bill', 'send'],
  ),
  entry('razorpayCancelInvoice', 'Cancels an issued unpaid invoice.', cancelInvoice, 'write', [
    'invoices',
    'bill',
    'void',
  ]),
  entry(
    'razorpaySendOrResendNotification',
    'Sends invoice notification by email/SMS.',
    sendInvoiceNotification,
    'write',
    ['invoice', 'notify', 'email', 'sms', 'remind'],
  ),
  entry('razorpayCreateItem', 'Creates a reusable invoicing item.', createItem, 'write', [
    'items',
    'product',
    'sku',
    'catalog',
  ]),
  entry('razorpayGetItem', 'Reads one item by ID.', getItem, 'read', ['items', 'product']),
  entry('razorpayListItems', 'Lists the item catalog with filters.', listItems, 'read', [
    'item',
    'product',
    'products',
    'catalog',
  ]),
  entry('razorpayUpdateItem', 'Updates item name/description/amount.', updateItem, 'write', [
    'items',
    'product',
  ]),
  entry('razorpayDeleteItem', 'Deletes an item unused by invoices.', deleteItem, 'delete', [
    'items',
    'product',
    'remove',
  ]),
  entry(
    'razorpayCreatePaymentLink',
    'Creates a shareable payment URL.',
    createPaymentLink,
    'write',
    ['payment', 'link', 'links', 'url', 'upi', 'collect'],
  ),
  entry('razorpayFetchAPaymentLink', 'Reads one payment link by ID.', fetchPaymentLink, 'read', [
    'payment',
    'links',
    'url',
  ]),
  entry(
    'razorpayFetchAllPaymentLinks',
    'Lists payment links with filters.',
    fetchAllPaymentLinks,
    'read',
    ['payment', 'link', 'url'],
  ),
  entry(
    'razorpayUpdatePaymentLink',
    'Updates link reference/expiry/settings.',
    updatePaymentLink,
    'write',
    ['payment', 'links', 'url'],
  ),
  entry(
    'razorpayCancelPaymentLink',
    'Cancels an active payment link.',
    cancelPaymentLink,
    'write',
    ['payment', 'links', 'url', 'void'],
  ),
  entry(
    'razorpayNotifyPaymentLink',
    'Sends link notification by SMS/email.',
    notifyPaymentLink,
    'write',
    ['payment', 'notify', 'sms', 'email', 'remind'],
  ),
  entry('razorpayCreateContact', 'Adds a RazorpayX payout contact.', createContact, 'write', [
    'contacts',
    'payout',
    'beneficiary',
    'vendor',
  ]),
  entry('razorpayGetContact', 'Reads one payout contact.', getContact, 'read', [
    'contacts',
    'payout',
    'beneficiary',
  ]),
  entry('razorpayUpdateContact', 'Updates payout contact details.', updateContact, 'write', [
    'contacts',
    'payout',
    'beneficiary',
  ]),
  entry('razorpayGetFundAccount', 'Reads one payout destination.', getFundAccount, 'read', [
    'fund',
    'payout',
    'bank',
    'destination',
    'account',
    'contact',
    'contacts',
  ]),
  entry(
    'razorpayListFundAccounts',
    'Lists payout destinations with filters.',
    listFundAccounts,
    'read',
    ['fund', 'payout', 'bank', 'destinations', 'contact', 'contacts'],
  ),
  entry(
    'razorpayListFundValidations',
    'Lists bank-account validations.',
    listFundValidations,
    'read',
    ['fund', 'bank', 'verify', 'validation', 'payout'],
  ),
  entry(
    'razorpayGetTransferReversals',
    'Lists Route transfer reversals.',
    getTransferReversals,
    'read',
    ['transfer', 'reversal', 'refund', 'route', 'payout'],
  ),
  entry(
    'razorpayGetSettlementRecon',
    'Fetches the settlement recon report.',
    getSettlementRecon,
    'read',
    ['settlement', 'settlements', 'reconciliation', 'payout', 'report'],
  ),
];
