// @ts-nocheck
import {
    createContact,
    getContact,
    getFundAccount,
    getSettlementRecon,
    getTransferReversals,
    listFundAccounts,
    listFundValidations,
    updateContact,
} from './payouts.js';
import {
    createCustomer,
    fetchAllCustomers,
    getCustomer,
    listCustomerTokens,
    updateCustomer,
} from './customers.js';
import {
    cancelInvoice,
    createInvoice,
    deleteInvoice,
    fetchAllInvoices,
    fetchInvoiceById,
    issueInvoice,
    sendInvoiceNotification,
    updateInvoice,
} from './invoices.js';
import {
    cancelPaymentLink,
    createItem,
    createPaymentLink,
    deleteItem,
    fetchAllPaymentLinks,
    fetchPaymentLink,
    getItem,
    listItems,
    notifyPaymentLink,
    updateItem,
    updatePaymentLink,
} from './items-links.js';
import {
    createOrder,
    fetchAllPayments,
    fetchAllRefundsForPayment,
    fetchOrderById,
    fetchOrders,
    fetchPaymentsByOrder,
    fetchRefunds,
    listDisputes,
    listPaymentDowntimes,
    updateOrder,
} from './orders.js';

export {
    createOrder,
    fetchOrders,
    fetchOrderById,
    updateOrder,
    fetchPaymentsByOrder,
    fetchAllPayments,
    fetchAllRefundsForPayment,
    fetchRefunds,
    listDisputes,
    listPaymentDowntimes,
    createCustomer,
    getCustomer,
    updateCustomer,
    fetchAllCustomers,
    listCustomerTokens,
    createInvoice,
    fetchAllInvoices,
    fetchInvoiceById,
    updateInvoice,
    deleteInvoice,
    issueInvoice,
    cancelInvoice,
    sendInvoiceNotification,
    createItem,
    getItem,
    listItems,
    updateItem,
    deleteItem,
    createPaymentLink,
    fetchPaymentLink,
    fetchAllPaymentLinks,
    updatePaymentLink,
    cancelPaymentLink,
    notifyPaymentLink,
    createContact,
    getContact,
    updateContact,
    getFundAccount,
    listFundAccounts,
    listFundValidations,
    getTransferReversals,
    getSettlementRecon,
};

const auth = 'razorpayCredentials' as const;

type Scope = 'read' | 'write' | 'delete';
function entry(name: string, description: string, toolRef: any, scope: Scope): { name: string; description: string; tool: any; requiredAuth: typeof auth; scope: Scope } {
    return { name, description, tool: toolRef, requiredAuth: auth, scope };
}

export const razorpayTools = [
    entry('razorpayCreateAnOrder', 'Creates an order before collecting payment.', createOrder, 'write'),
    entry('razorpayFetchOrders', 'Lists orders with filters and pagination.', fetchOrders, 'read'),
    entry('razorpayFetchOrdersById', 'Reads one order by ID.', fetchOrderById, 'read'),
    entry('razorpayUpdateOrder', 'Updates order metadata notes.', updateOrder, 'write'),
    entry('razorpayFetchPaymentsByOrder', 'Lists all payment attempts for an order.', fetchPaymentsByOrder, 'read'),
    entry('razorpayFetchAllPayments', 'Lists payments newest-first with filters.', fetchAllPayments, 'read'),
    entry('razorpayFetchAllRefundsForAPayment', 'Lists refunds for one payment.', fetchAllRefundsForPayment, 'read'),
    entry('razorpayFetchRefunds', 'Lists all refunds with filters.', fetchRefunds, 'read'),
    entry('razorpayListDisputes', 'Lists chargebacks/fraud disputes.', listDisputes, 'read'),
    entry('razorpayListPaymentDowntimes', 'Lists active payment-method downtimes.', listPaymentDowntimes, 'read'),
    entry('razorpayCreateCustomer', 'Registers a customer for future transactions.', createCustomer, 'write'),
    entry('razorpayGetCustomer', 'Reads one customer by ID.', getCustomer, 'read'),
    entry('razorpayUpdateCustomer', 'Updates customer name/email/contact.', updateCustomer, 'write'),
    entry('razorpayFetchAllCustomers', 'Lists customers with pagination.', fetchAllCustomers, 'read'),
    entry('razorpayListCustomerTokens', 'Lists saved payment methods for a customer.', listCustomerTokens, 'read'),
    entry('razorpayCreateInvoice', 'Creates a draft invoice with line items.', createInvoice, 'write'),
    entry('razorpayFetchAllInvoices', 'Lists invoices with filters.', fetchAllInvoices, 'read'),
    entry('razorpayFetchInvoiceById', 'Reads one invoice with full details.', fetchInvoiceById, 'read'),
    entry('razorpayUpdateInvoice', 'Updates a draft invoice.', updateInvoice, 'write'),
    entry('razorpayDeleteInvoice', 'Permanently deletes a draft invoice.', deleteInvoice, 'delete'),
    entry('razorpayIssueAnInvoice', 'Issues a draft invoice to the customer.', issueInvoice, 'write'),
    entry('razorpayCancelInvoice', 'Cancels an issued unpaid invoice.', cancelInvoice, 'write'),
    entry('razorpaySendOrResendNotification', 'Sends invoice notification by email/SMS.', sendInvoiceNotification, 'write'),
    entry('razorpayCreateItem', 'Creates a reusable invoicing item.', createItem, 'write'),
    entry('razorpayGetItem', 'Reads one item by ID.', getItem, 'read'),
    entry('razorpayListItems', 'Lists the item catalog with filters.', listItems, 'read'),
    entry('razorpayUpdateItem', 'Updates item name/description/amount.', updateItem, 'write'),
    entry('razorpayDeleteItem', 'Deletes an item unused by invoices.', deleteItem, 'delete'),
    entry('razorpayCreatePaymentLink', 'Creates a shareable payment URL.', createPaymentLink, 'write'),
    entry('razorpayFetchAPaymentLink', 'Reads one payment link by ID.', fetchPaymentLink, 'read'),
    entry('razorpayFetchAllPaymentLinks', 'Lists payment links with filters.', fetchAllPaymentLinks, 'read'),
    entry('razorpayUpdatePaymentLink', 'Updates link reference/expiry/settings.', updatePaymentLink, 'write'),
    entry('razorpayCancelPaymentLink', 'Cancels an active payment link.', cancelPaymentLink, 'write'),
    entry('razorpayNotifyPaymentLink', 'Sends link notification by SMS/email.', notifyPaymentLink, 'write'),
    entry('razorpayCreateContact', 'Adds a RazorpayX payout contact.', createContact, 'write'),
    entry('razorpayGetContact', 'Reads one payout contact.', getContact, 'read'),
    entry('razorpayUpdateContact', 'Updates payout contact details.', updateContact, 'write'),
    entry('razorpayGetFundAccount', 'Reads one payout destination.', getFundAccount, 'read'),
    entry('razorpayListFundAccounts', 'Lists payout destinations with filters.', listFundAccounts, 'read'),
    entry('razorpayListFundValidations', 'Lists bank-account validations.', listFundValidations, 'read'),
    entry('razorpayGetTransferReversals', 'Lists Route transfer reversals.', getTransferReversals, 'read'),
    entry('razorpayGetSettlementRecon', 'Fetches the settlement recon report.', getSettlementRecon, 'read'),
];
