// @ts-nocheck
import {
  supabaseAlphaCreateApiKey,
  supabaseAlphaDeleteApiKey,
  supabaseAlphaUpdateApiKey,
  supabaseGetProjectApiKey,
  supabaseGetProjectApiKeys,
  supabaseGetProjectLegacyApiKeys,
  supabaseUpdateApiKey,
  supabaseUpdateProjectLegacyApiKeys,
} from './api-keys.js';
import {
  supabaseAlphaDeleteThirdPartyAuthIntegration,
  supabaseAlphaGetThirdPartyIntegration,
  supabaseAlphaListThirdPartyAuthIntegrations,
  supabaseCreateSsoProvider,
  supabaseCreateThirdPartyAuthIntegration,
  supabaseDeleteSsoProvider,
  supabaseGetAuthConfig,
  supabaseGetsProjectSAuthConfig,
  supabaseGetSsoProvider,
  supabaseListSsoProviders,
  supabaseUpdateProjectAuthConfig,
  supabaseUpdateSsoProvider,
} from './auth.js';
import {
  supabaseApplyAMigration,
  supabaseGetMigration,
  supabaseListMigrationHistory,
  supabasePatchMigration,
  supabaseUpsertMigration,
} from './migrations.js';
import {
  supabaseBetaActivateCustomHostname,
  supabaseBetaActivateVanitySubdomain,
  supabaseBetaCheckVanitySubdomainAvailability,
  supabaseBetaGetProjectCustomHostnameConfig,
  supabaseBetaGetVanitySubdomainConfig,
  supabaseDeleteCustomHostnameConfig,
  supabaseDeleteProjectVanitySubdomain,
  supabaseUpdateProjectCustomHostname,
  supabaseVerifyCustomHostnameDns,
} from './domains.js';
import { supabaseBetaAuthorizeUserThroughOauth, supabaseExchangeOauthToken } from './oauth.js';
import {
  supabaseBetaCreateReadReplica,
  supabaseBetaEnableDatabaseWebhooks,
  supabaseBetaRemoveReadReplica,
} from './replicas.js';
import {
  supabaseBetaGetProjectNetworkBans,
  supabaseBetaGetProjectNetworkRestrictions,
  supabaseBetaRemoveNetworkBans,
  supabaseBetaUpdateProjectNetworkRestrictions,
  supabasePatchNetworkRestrictions,
} from './network.js';
import {
  supabaseBetaGetProjectPgsodiumConfig,
  supabaseBetaGetProjectSslEnforcementConfig,
  supabaseBetaRunSqlQuery,
  supabaseCreateLoginRole,
  supabaseDeleteLoginRoles,
  supabaseGenerateTypescriptTypes,
  supabaseGetDatabaseMetadata,
  supabaseGetJitAccessConfig,
  supabaseGetPerformanceAdvisors,
  supabaseGetProjectLogs,
  supabaseGetProjectPgbouncerConfig,
  supabaseGetProjectPostgresConfig,
  supabaseGetProjectPostgrestConfig,
  supabaseGetProjectSupavisorConfig,
  supabaseGetSecurityAdvisors,
  supabaseGetTableSchemas,
  supabaseListBackups,
  supabaseListTables,
  supabaseRestorePitrBackup,
  supabaseRunReadOnlyQuery,
  supabaseSelectFromTable,
  supabaseUpdateDatabasePassword,
  supabaseUpdateJitAccessConfig,
  supabaseUpdatePgsodiumConfig,
  supabaseUpdateProjectPostgresConfig,
  supabaseUpdateProjectPostgrestConfig,
  supabaseUpdateProjectSupavisorConfig,
  supabaseUpdateSslEnforcementConfig,
} from './database.js';
import {
  supabaseBetaUpgradeProjectPostgresVersion,
  supabaseCreateAProject,
  supabaseDeleteProject,
  supabaseDisableProjectReadonly,
  supabaseGetHealth,
  supabaseGetProject,
  supabaseGetProjectReadonlyModeStatus,
  supabaseGetProjectUpgradeEligibility,
  supabaseGetProjectUpgradeStatus,
  supabaseGetsProjectSServiceHealthStatus,
  supabaseListAllProjects,
  supabaseUpdateProject,
} from './projects.js';
import {
  supabaseCountActionRuns,
  supabaseCreateDatabaseBranch,
  supabaseDeleteAllBranches,
  supabaseDeleteDatabaseBranch,
  supabaseDisablePreviewBranching,
  supabaseGetActionRun,
  supabaseGetActionRunLogs,
  supabaseGetBranch,
  supabaseGetDatabaseBranchConfig,
  supabaseListBranches,
  supabaseListDatabaseBranches,
  supabaseMergeBranch,
  supabasePushBranch,
  supabaseResetDatabaseBranch,
  supabaseUpdateBranch,
  supabaseUpdateDatabaseBranchConfig,
} from './branches.js';
import {
  supabaseCreateBulkSecrets,
  supabaseDeleteSecrets,
  supabaseListProjectSecrets,
  supabaseListSecrets,
} from './secrets.js';
import {
  supabaseCreateFunction,
  supabaseDeleteEdgeFunction,
  supabaseDeleteFunction,
  supabaseDeployFunction,
  supabaseGetFunction,
  supabaseGetFunctionBody,
  supabaseInvokeEdgeFunction,
  supabaseListFunctions,
  supabaseUpdateAFunction,
  supabaseUpdateFunctions,
} from './functions.js';
import {
  supabaseCreateOrganization,
  supabaseGetAvailableRegions,
  supabaseGetOrganization,
  supabaseListAllOrganizations,
  supabaseListOrganizationMembers,
} from './organizations.js';
import {
  supabaseCreateProjectSigningKey,
  supabaseGetLegacySigningKey,
  supabaseGetProjectSigningKeys,
} from './signing-keys.js';
import {
  supabaseGetResumableUploadBaseOptions,
  supabaseGetResumableUploadOptions,
  supabaseHandleResumableUploadSignOptions,
  supabaseHandleResumableUploadSignOptionsWithId,
  supabaseListBuckets,
} from './storage.js';
import { supabaseGetSqlSnippet, supabaseListSqlSnippets } from './snippets.js';

export {
  supabaseAlphaCreateApiKey,
  supabaseAlphaDeleteApiKey,
  supabaseAlphaUpdateApiKey,
  supabaseGetProjectApiKey,
  supabaseGetProjectApiKeys,
  supabaseGetProjectLegacyApiKeys,
  supabaseUpdateApiKey,
  supabaseUpdateProjectLegacyApiKeys,
};
export {
  supabaseAlphaDeleteThirdPartyAuthIntegration,
  supabaseAlphaGetThirdPartyIntegration,
  supabaseAlphaListThirdPartyAuthIntegrations,
  supabaseCreateSsoProvider,
  supabaseCreateThirdPartyAuthIntegration,
  supabaseDeleteSsoProvider,
  supabaseGetAuthConfig,
  supabaseGetsProjectSAuthConfig,
  supabaseGetSsoProvider,
  supabaseListSsoProviders,
  supabaseUpdateProjectAuthConfig,
  supabaseUpdateSsoProvider,
};
export {
  supabaseApplyAMigration,
  supabaseGetMigration,
  supabaseListMigrationHistory,
  supabasePatchMigration,
  supabaseUpsertMigration,
};
export {
  supabaseBetaActivateCustomHostname,
  supabaseBetaActivateVanitySubdomain,
  supabaseBetaCheckVanitySubdomainAvailability,
  supabaseBetaGetProjectCustomHostnameConfig,
  supabaseBetaGetVanitySubdomainConfig,
  supabaseDeleteCustomHostnameConfig,
  supabaseDeleteProjectVanitySubdomain,
  supabaseUpdateProjectCustomHostname,
  supabaseVerifyCustomHostnameDns,
};
export { supabaseBetaAuthorizeUserThroughOauth, supabaseExchangeOauthToken };
export {
  supabaseBetaCreateReadReplica,
  supabaseBetaEnableDatabaseWebhooks,
  supabaseBetaRemoveReadReplica,
};
export {
  supabaseBetaGetProjectNetworkBans,
  supabaseBetaGetProjectNetworkRestrictions,
  supabaseBetaRemoveNetworkBans,
  supabaseBetaUpdateProjectNetworkRestrictions,
  supabasePatchNetworkRestrictions,
};
export {
  supabaseBetaGetProjectPgsodiumConfig,
  supabaseBetaGetProjectSslEnforcementConfig,
  supabaseBetaRunSqlQuery,
  supabaseCreateLoginRole,
  supabaseDeleteLoginRoles,
  supabaseGenerateTypescriptTypes,
  supabaseGetDatabaseMetadata,
  supabaseGetJitAccessConfig,
  supabaseGetPerformanceAdvisors,
  supabaseGetProjectLogs,
  supabaseGetProjectPgbouncerConfig,
  supabaseGetProjectPostgresConfig,
  supabaseGetProjectPostgrestConfig,
  supabaseGetProjectSupavisorConfig,
  supabaseGetSecurityAdvisors,
  supabaseGetTableSchemas,
  supabaseListBackups,
  supabaseListTables,
  supabaseRestorePitrBackup,
  supabaseRunReadOnlyQuery,
  supabaseSelectFromTable,
  supabaseUpdateDatabasePassword,
  supabaseUpdateJitAccessConfig,
  supabaseUpdatePgsodiumConfig,
  supabaseUpdateProjectPostgresConfig,
  supabaseUpdateProjectPostgrestConfig,
  supabaseUpdateProjectSupavisorConfig,
  supabaseUpdateSslEnforcementConfig,
};
export {
  supabaseBetaUpgradeProjectPostgresVersion,
  supabaseCreateAProject,
  supabaseDeleteProject,
  supabaseDisableProjectReadonly,
  supabaseGetHealth,
  supabaseGetProject,
  supabaseGetProjectReadonlyModeStatus,
  supabaseGetProjectUpgradeEligibility,
  supabaseGetProjectUpgradeStatus,
  supabaseGetsProjectSServiceHealthStatus,
  supabaseListAllProjects,
  supabaseUpdateProject,
};
export {
  supabaseCountActionRuns,
  supabaseCreateDatabaseBranch,
  supabaseDeleteAllBranches,
  supabaseDeleteDatabaseBranch,
  supabaseDisablePreviewBranching,
  supabaseGetActionRun,
  supabaseGetActionRunLogs,
  supabaseGetBranch,
  supabaseGetDatabaseBranchConfig,
  supabaseListBranches,
  supabaseListDatabaseBranches,
  supabaseMergeBranch,
  supabasePushBranch,
  supabaseResetDatabaseBranch,
  supabaseUpdateBranch,
  supabaseUpdateDatabaseBranchConfig,
};
export {
  supabaseCreateBulkSecrets,
  supabaseDeleteSecrets,
  supabaseListProjectSecrets,
  supabaseListSecrets,
};
export {
  supabaseCreateFunction,
  supabaseDeleteEdgeFunction,
  supabaseDeleteFunction,
  supabaseDeployFunction,
  supabaseGetFunction,
  supabaseGetFunctionBody,
  supabaseInvokeEdgeFunction,
  supabaseListFunctions,
  supabaseUpdateAFunction,
  supabaseUpdateFunctions,
};
export {
  supabaseCreateOrganization,
  supabaseGetAvailableRegions,
  supabaseGetOrganization,
  supabaseListAllOrganizations,
  supabaseListOrganizationMembers,
};
export {
  supabaseCreateProjectSigningKey,
  supabaseGetLegacySigningKey,
  supabaseGetProjectSigningKeys,
};
export {
  supabaseGetResumableUploadBaseOptions,
  supabaseGetResumableUploadOptions,
  supabaseHandleResumableUploadSignOptions,
  supabaseHandleResumableUploadSignOptionsWithId,
  supabaseListBuckets,
};
export { supabaseGetSqlSnippet, supabaseListSqlSnippets };

export const supabaseTools = [
  {
    name: 'supabaseAlphaCreateApiKey',
    description: supabaseAlphaCreateApiKey.description!,
    tool: supabaseAlphaCreateApiKey,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'write' as const,
    keywords: ['credential'],
  },
  {
    name: 'supabaseAlphaDeleteApiKey',
    description: supabaseAlphaDeleteApiKey.description!,
    tool: supabaseAlphaDeleteApiKey,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'delete' as const,
    keywords: ['credential'],
  },
  {
    name: 'supabaseAlphaDeleteThirdPartyAuthIntegration',
    description: supabaseAlphaDeleteThirdPartyAuthIntegration.description!,
    tool: supabaseAlphaDeleteThirdPartyAuthIntegration,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'delete' as const,
    keywords: ['authentication'],
  },
  {
    name: 'supabaseAlphaGetThirdPartyIntegration',
    description: supabaseAlphaGetThirdPartyIntegration.description!,
    tool: supabaseAlphaGetThirdPartyIntegration,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'read' as const,
    keywords: [],
  },
  {
    name: 'supabaseAlphaListThirdPartyAuthIntegrations',
    description: supabaseAlphaListThirdPartyAuthIntegrations.description!,
    tool: supabaseAlphaListThirdPartyAuthIntegrations,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'read' as const,
    keywords: ['authentication'],
  },
  {
    name: 'supabaseAlphaUpdateApiKey',
    description: supabaseAlphaUpdateApiKey.description!,
    tool: supabaseAlphaUpdateApiKey,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'write' as const,
    keywords: ['credential'],
  },
  {
    name: 'supabaseApplyAMigration',
    description: supabaseApplyAMigration.description!,
    tool: supabaseApplyAMigration,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'write' as const,
    keywords: ['run', 'schema change'],
  },
  {
    name: 'supabaseBetaActivateCustomHostname',
    description: supabaseBetaActivateCustomHostname.description!,
    tool: supabaseBetaActivateCustomHostname,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'write' as const,
    keywords: [],
  },
  {
    name: 'supabaseBetaActivateVanitySubdomain',
    description: supabaseBetaActivateVanitySubdomain.description!,
    tool: supabaseBetaActivateVanitySubdomain,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'write' as const,
    keywords: [],
  },
  {
    name: 'supabaseBetaAuthorizeUserThroughOauth',
    description: supabaseBetaAuthorizeUserThroughOauth.description!,
    tool: supabaseBetaAuthorizeUserThroughOauth,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'read' as const,
    keywords: [],
  },
  {
    name: 'supabaseBetaCheckVanitySubdomainAvailability',
    description: supabaseBetaCheckVanitySubdomainAvailability.description!,
    tool: supabaseBetaCheckVanitySubdomainAvailability,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'write' as const,
    keywords: [],
  },
  {
    name: 'supabaseBetaCreateReadReplica',
    description: supabaseBetaCreateReadReplica.description!,
    tool: supabaseBetaCreateReadReplica,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'write' as const,
    keywords: [],
  },
  {
    name: 'supabaseBetaEnableDatabaseWebhooks',
    description: supabaseBetaEnableDatabaseWebhooks.description!,
    tool: supabaseBetaEnableDatabaseWebhooks,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'write' as const,
    keywords: ['postgres'],
  },
  {
    name: 'supabaseBetaGetProjectCustomHostnameConfig',
    description: supabaseBetaGetProjectCustomHostnameConfig.description!,
    tool: supabaseBetaGetProjectCustomHostnameConfig,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'read' as const,
    keywords: ['postgres instance', 'settings'],
  },
  {
    name: 'supabaseBetaGetProjectNetworkBans',
    description: supabaseBetaGetProjectNetworkBans.description!,
    tool: supabaseBetaGetProjectNetworkBans,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'write' as const,
    keywords: ['postgres instance', 'ip', 'blocklist'],
  },
  {
    name: 'supabaseBetaGetProjectNetworkRestrictions',
    description: supabaseBetaGetProjectNetworkRestrictions.description!,
    tool: supabaseBetaGetProjectNetworkRestrictions,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'read' as const,
    keywords: ['postgres instance', 'ip'],
  },
  {
    name: 'supabaseBetaGetProjectPgsodiumConfig',
    description: supabaseBetaGetProjectPgsodiumConfig.description!,
    tool: supabaseBetaGetProjectPgsodiumConfig,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'read' as const,
    keywords: ['postgres instance', 'encryption key', 'settings'],
  },
  {
    name: 'supabaseBetaGetProjectSslEnforcementConfig',
    description: supabaseBetaGetProjectSslEnforcementConfig.description!,
    tool: supabaseBetaGetProjectSslEnforcementConfig,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'read' as const,
    keywords: ['postgres instance', 'tls', 'settings'],
  },
  {
    name: 'supabaseBetaGetVanitySubdomainConfig',
    description: supabaseBetaGetVanitySubdomainConfig.description!,
    tool: supabaseBetaGetVanitySubdomainConfig,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'read' as const,
    keywords: ['settings'],
  },
  {
    name: 'supabaseBetaRemoveNetworkBans',
    description: supabaseBetaRemoveNetworkBans.description!,
    tool: supabaseBetaRemoveNetworkBans,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'delete' as const,
    keywords: ['ip', 'blocklist'],
  },
  {
    name: 'supabaseBetaRemoveReadReplica',
    description: supabaseBetaRemoveReadReplica.description!,
    tool: supabaseBetaRemoveReadReplica,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'write' as const,
    keywords: [],
  },
  {
    name: 'supabaseBetaRunSqlQuery',
    description: supabaseBetaRunSqlQuery.description!,
    tool: supabaseBetaRunSqlQuery,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'write' as const,
    keywords: ['execution'],
  },
  {
    name: 'supabaseBetaUpdateProjectNetworkRestrictions',
    description: supabaseBetaUpdateProjectNetworkRestrictions.description!,
    tool: supabaseBetaUpdateProjectNetworkRestrictions,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'write' as const,
    keywords: ['postgres instance', 'ip'],
  },
  {
    name: 'supabaseBetaUpgradeProjectPostgresVersion',
    description: supabaseBetaUpgradeProjectPostgresVersion.description!,
    tool: supabaseBetaUpgradeProjectPostgresVersion,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'write' as const,
    keywords: ['database'],
  },
  {
    name: 'supabaseCountActionRuns',
    description: supabaseCountActionRuns.description!,
    tool: supabaseCountActionRuns,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'read' as const,
    keywords: ['tally', 'workflow', 'executions'],
  },
  {
    name: 'supabaseCreateAProject',
    description: supabaseCreateAProject.description!,
    tool: supabaseCreateAProject,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'write' as const,
    keywords: ['new', 'add', 'postgres instance'],
  },
  {
    name: 'supabaseCreateBulkSecrets',
    description: supabaseCreateBulkSecrets.description!,
    tool: supabaseCreateBulkSecrets,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'write' as const,
    keywords: ['new', 'add', 'batch'],
  },
  {
    name: 'supabaseCreateDatabaseBranch',
    description: supabaseCreateDatabaseBranch.description!,
    tool: supabaseCreateDatabaseBranch,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'write' as const,
    keywords: ['new', 'add', 'postgres', 'preview environment'],
  },
  {
    name: 'supabaseCreateFunction',
    description: supabaseCreateFunction.description!,
    tool: supabaseCreateFunction,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'write' as const,
    keywords: ['new', 'add', 'edge routine'],
  },
  {
    name: 'supabaseCreateLoginRole',
    description: supabaseCreateLoginRole.description!,
    tool: supabaseCreateLoginRole,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'write' as const,
    keywords: ['new', 'add', 'cli access'],
  },
  {
    name: 'supabaseCreateOrganization',
    description: supabaseCreateOrganization.description!,
    tool: supabaseCreateOrganization,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'write' as const,
    keywords: ['new', 'add', 'team account'],
  },
  {
    name: 'supabaseCreateProjectSigningKey',
    description: supabaseCreateProjectSigningKey.description!,
    tool: supabaseCreateProjectSigningKey,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'write' as const,
    keywords: ['new', 'add', 'postgres instance', 'credential'],
  },
  {
    name: 'supabaseCreateSsoProvider',
    description: supabaseCreateSsoProvider.description!,
    tool: supabaseCreateSsoProvider,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'write' as const,
    keywords: ['new', 'add', 'single sign-on'],
  },
  {
    name: 'supabaseCreateThirdPartyAuthIntegration',
    description: supabaseCreateThirdPartyAuthIntegration.description!,
    tool: supabaseCreateThirdPartyAuthIntegration,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'write' as const,
    keywords: ['new', 'add', 'authentication'],
  },
  {
    name: 'supabaseDeleteAllBranches',
    description: supabaseDeleteAllBranches.description!,
    tool: supabaseDeleteAllBranches,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'delete' as const,
    keywords: ['remove', 'drop'],
  },
  {
    name: 'supabaseDeleteCustomHostnameConfig',
    description: supabaseDeleteCustomHostnameConfig.description!,
    tool: supabaseDeleteCustomHostnameConfig,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'delete' as const,
    keywords: ['remove', 'drop', 'settings'],
  },
  {
    name: 'supabaseDeleteDatabaseBranch',
    description: supabaseDeleteDatabaseBranch.description!,
    tool: supabaseDeleteDatabaseBranch,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'delete' as const,
    keywords: ['remove', 'drop', 'postgres', 'preview environment'],
  },
  {
    name: 'supabaseDeleteEdgeFunction',
    description: supabaseDeleteEdgeFunction.description!,
    tool: supabaseDeleteEdgeFunction,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'delete' as const,
    keywords: ['remove', 'drop'],
  },
  {
    name: 'supabaseDeleteFunction',
    description: supabaseDeleteFunction.description!,
    tool: supabaseDeleteFunction,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'delete' as const,
    keywords: ['remove', 'drop', 'edge routine'],
  },
  {
    name: 'supabaseDeleteLoginRoles',
    description: supabaseDeleteLoginRoles.description!,
    tool: supabaseDeleteLoginRoles,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'delete' as const,
    keywords: ['remove', 'drop', 'cli access'],
  },
  {
    name: 'supabaseDeleteProject',
    description: supabaseDeleteProject.description!,
    tool: supabaseDeleteProject,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'delete' as const,
    keywords: ['remove', 'drop', 'postgres instance'],
  },
  {
    name: 'supabaseDeleteProjectVanitySubdomain',
    description: supabaseDeleteProjectVanitySubdomain.description!,
    tool: supabaseDeleteProjectVanitySubdomain,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'delete' as const,
    keywords: ['remove', 'drop', 'postgres instance'],
  },
  {
    name: 'supabaseDeleteSecrets',
    description: supabaseDeleteSecrets.description!,
    tool: supabaseDeleteSecrets,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'delete' as const,
    keywords: ['remove', 'drop'],
  },
  {
    name: 'supabaseDeleteSsoProvider',
    description: supabaseDeleteSsoProvider.description!,
    tool: supabaseDeleteSsoProvider,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'delete' as const,
    keywords: ['remove', 'drop', 'single sign-on'],
  },
  {
    name: 'supabaseDeployFunction',
    description: supabaseDeployFunction.description!,
    tool: supabaseDeployFunction,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'write' as const,
    keywords: ['publish', 'ship', 'edge routine'],
  },
  {
    name: 'supabaseDisablePreviewBranching',
    description: supabaseDisablePreviewBranching.description!,
    tool: supabaseDisablePreviewBranching,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'delete' as const,
    keywords: ['turn off'],
  },
  {
    name: 'supabaseDisableProjectReadonly',
    description: supabaseDisableProjectReadonly.description!,
    tool: supabaseDisableProjectReadonly,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'write' as const,
    keywords: ['turn off', 'postgres instance', 'read-only mode'],
  },
  {
    name: 'supabaseExchangeOauthToken',
    description: supabaseExchangeOauthToken.description!,
    tool: supabaseExchangeOauthToken,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'write' as const,
    keywords: ['swap tokens', 'credential'],
  },
  {
    name: 'supabaseGenerateTypescriptTypes',
    description: supabaseGenerateTypescriptTypes.description!,
    tool: supabaseGenerateTypescriptTypes,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'read' as const,
    keywords: ['produce'],
  },
  {
    name: 'supabaseGetActionRun',
    description: supabaseGetActionRun.description!,
    tool: supabaseGetActionRun,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'read' as const,
    keywords: ['fetch', 'retrieve', 'lookup', 'workflow'],
  },
  {
    name: 'supabaseGetActionRunLogs',
    description: supabaseGetActionRunLogs.description!,
    tool: supabaseGetActionRunLogs,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'read' as const,
    keywords: ['fetch', 'retrieve', 'lookup', 'workflow'],
  },
  {
    name: 'supabaseGetAuthConfig',
    description: supabaseGetAuthConfig.description!,
    tool: supabaseGetAuthConfig,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'read' as const,
    keywords: ['fetch', 'retrieve', 'lookup', 'authentication'],
  },
  {
    name: 'supabaseGetAvailableRegions',
    description: supabaseGetAvailableRegions.description!,
    tool: supabaseGetAvailableRegions,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'read' as const,
    keywords: ['fetch', 'retrieve', 'lookup'],
  },
  {
    name: 'supabaseGetBranch',
    description: supabaseGetBranch.description!,
    tool: supabaseGetBranch,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'read' as const,
    keywords: ['fetch', 'retrieve', 'lookup', 'preview environment'],
  },
  {
    name: 'supabaseGetDatabaseBranchConfig',
    description: supabaseGetDatabaseBranchConfig.description!,
    tool: supabaseGetDatabaseBranchConfig,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'read' as const,
    keywords: ['fetch', 'retrieve', 'lookup', 'postgres'],
  },
  {
    name: 'supabaseGetDatabaseMetadata',
    description: supabaseGetDatabaseMetadata.description!,
    tool: supabaseGetDatabaseMetadata,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'write' as const,
    keywords: ['fetch', 'retrieve', 'lookup', 'postgres'],
  },
  {
    name: 'supabaseGetFunction',
    description: supabaseGetFunction.description!,
    tool: supabaseGetFunction,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'read' as const,
    keywords: ['fetch', 'retrieve', 'lookup', 'edge routine'],
  },
  {
    name: 'supabaseGetFunctionBody',
    description: supabaseGetFunctionBody.description!,
    tool: supabaseGetFunctionBody,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'read' as const,
    keywords: ['fetch', 'retrieve', 'lookup', 'edge routine'],
  },
  {
    name: 'supabaseGetHealth',
    description: supabaseGetHealth.description!,
    tool: supabaseGetHealth,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'read' as const,
    keywords: ['fetch', 'retrieve', 'lookup', 'status'],
  },
  {
    name: 'supabaseGetJitAccessConfig',
    description: supabaseGetJitAccessConfig.description!,
    tool: supabaseGetJitAccessConfig,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'read' as const,
    keywords: ['fetch', 'retrieve', 'lookup', 'settings'],
  },
  {
    name: 'supabaseGetLegacySigningKey',
    description: supabaseGetLegacySigningKey.description!,
    tool: supabaseGetLegacySigningKey,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'read' as const,
    keywords: ['fetch', 'retrieve', 'lookup', 'credential'],
  },
  {
    name: 'supabaseGetMigration',
    description: supabaseGetMigration.description!,
    tool: supabaseGetMigration,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'read' as const,
    keywords: ['fetch', 'retrieve', 'lookup', 'schema change'],
  },
  {
    name: 'supabaseGetOrganization',
    description: supabaseGetOrganization.description!,
    tool: supabaseGetOrganization,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'read' as const,
    keywords: ['fetch', 'retrieve', 'lookup', 'team account'],
  },
  {
    name: 'supabaseGetPerformanceAdvisors',
    description: supabaseGetPerformanceAdvisors.description!,
    tool: supabaseGetPerformanceAdvisors,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'read' as const,
    keywords: ['fetch', 'retrieve', 'lookup'],
  },
  {
    name: 'supabaseGetProject',
    description: supabaseGetProject.description!,
    tool: supabaseGetProject,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'read' as const,
    keywords: ['fetch', 'retrieve', 'lookup', 'postgres instance'],
  },
  {
    name: 'supabaseGetProjectApiKey',
    description: supabaseGetProjectApiKey.description!,
    tool: supabaseGetProjectApiKey,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'read' as const,
    keywords: ['fetch', 'retrieve', 'lookup', 'postgres instance'],
  },
  {
    name: 'supabaseGetProjectApiKeys',
    description: supabaseGetProjectApiKeys.description!,
    tool: supabaseGetProjectApiKeys,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'read' as const,
    keywords: ['fetch', 'retrieve', 'lookup', 'postgres instance'],
  },
  {
    name: 'supabaseGetProjectLegacyApiKeys',
    description: supabaseGetProjectLegacyApiKeys.description!,
    tool: supabaseGetProjectLegacyApiKeys,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'read' as const,
    keywords: ['fetch', 'retrieve', 'lookup', 'postgres instance'],
  },
  {
    name: 'supabaseGetProjectLogs',
    description: supabaseGetProjectLogs.description!,
    tool: supabaseGetProjectLogs,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'read' as const,
    keywords: ['fetch', 'retrieve', 'lookup', 'postgres instance'],
  },
  {
    name: 'supabaseGetProjectPgbouncerConfig',
    description: supabaseGetProjectPgbouncerConfig.description!,
    tool: supabaseGetProjectPgbouncerConfig,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'read' as const,
    keywords: ['fetch', 'retrieve', 'lookup', 'postgres instance'],
  },
  {
    name: 'supabaseGetProjectPostgresConfig',
    description: supabaseGetProjectPostgresConfig.description!,
    tool: supabaseGetProjectPostgresConfig,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'read' as const,
    keywords: ['fetch', 'retrieve', 'lookup', 'database'],
  },
  {
    name: 'supabaseGetProjectPostgrestConfig',
    description: supabaseGetProjectPostgrestConfig.description!,
    tool: supabaseGetProjectPostgrestConfig,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'read' as const,
    keywords: ['fetch', 'retrieve', 'lookup', 'settings'],
  },
  {
    name: 'supabaseGetProjectReadonlyModeStatus',
    description: supabaseGetProjectReadonlyModeStatus.description!,
    tool: supabaseGetProjectReadonlyModeStatus,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'read' as const,
    keywords: ['fetch', 'retrieve', 'lookup', 'postgres instance'],
  },
  {
    name: 'supabaseGetProjectSigningKeys',
    description: supabaseGetProjectSigningKeys.description!,
    tool: supabaseGetProjectSigningKeys,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'read' as const,
    keywords: ['fetch', 'retrieve', 'lookup', 'postgres instance'],
  },
  {
    name: 'supabaseGetProjectSupavisorConfig',
    description: supabaseGetProjectSupavisorConfig.description!,
    tool: supabaseGetProjectSupavisorConfig,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'read' as const,
    keywords: ['fetch', 'retrieve', 'lookup', 'postgres instance'],
  },
  {
    name: 'supabaseGetProjectUpgradeEligibility',
    description: supabaseGetProjectUpgradeEligibility.description!,
    tool: supabaseGetProjectUpgradeEligibility,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'read' as const,
    keywords: ['fetch', 'retrieve', 'lookup', 'postgres instance'],
  },
  {
    name: 'supabaseGetProjectUpgradeStatus',
    description: supabaseGetProjectUpgradeStatus.description!,
    tool: supabaseGetProjectUpgradeStatus,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'read' as const,
    keywords: ['fetch', 'retrieve', 'lookup', 'postgres instance'],
  },
  {
    name: 'supabaseGetResumableUploadBaseOptions',
    description: supabaseGetResumableUploadBaseOptions.description!,
    tool: supabaseGetResumableUploadBaseOptions,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'read' as const,
    keywords: ['fetch', 'retrieve', 'lookup'],
  },
  {
    name: 'supabaseGetResumableUploadOptions',
    description: supabaseGetResumableUploadOptions.description!,
    tool: supabaseGetResumableUploadOptions,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'read' as const,
    keywords: ['fetch', 'retrieve', 'lookup'],
  },
  {
    name: 'supabaseGetSecurityAdvisors',
    description: supabaseGetSecurityAdvisors.description!,
    tool: supabaseGetSecurityAdvisors,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'read' as const,
    keywords: ['fetch', 'retrieve', 'lookup'],
  },
  {
    name: 'supabaseGetsProjectSAuthConfig',
    description: supabaseGetsProjectSAuthConfig.description!,
    tool: supabaseGetsProjectSAuthConfig,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'read' as const,
    keywords: ['fetch', 'retrieve', 'lookup', 'postgres instance'],
  },
  {
    name: 'supabaseGetsProjectSServiceHealthStatus',
    description: supabaseGetsProjectSServiceHealthStatus.description!,
    tool: supabaseGetsProjectSServiceHealthStatus,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'read' as const,
    keywords: ['fetch', 'retrieve', 'lookup', 'postgres instance'],
  },
  {
    name: 'supabaseGetSqlSnippet',
    description: supabaseGetSqlSnippet.description!,
    tool: supabaseGetSqlSnippet,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'read' as const,
    keywords: ['fetch', 'retrieve', 'lookup', 'query'],
  },
  {
    name: 'supabaseGetSsoProvider',
    description: supabaseGetSsoProvider.description!,
    tool: supabaseGetSsoProvider,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'read' as const,
    keywords: ['fetch', 'retrieve', 'lookup', 'single sign-on'],
  },
  {
    name: 'supabaseGetTableSchemas',
    description: supabaseGetTableSchemas.description!,
    tool: supabaseGetTableSchemas,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'write' as const,
    keywords: ['fetch', 'retrieve', 'lookup', 'relation'],
  },
  {
    name: 'supabaseHandleResumableUploadSignOptions',
    description: supabaseHandleResumableUploadSignOptions.description!,
    tool: supabaseHandleResumableUploadSignOptions,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'read' as const,
    keywords: ['preflight'],
  },
  {
    name: 'supabaseHandleResumableUploadSignOptionsWithId',
    description: supabaseHandleResumableUploadSignOptionsWithId.description!,
    tool: supabaseHandleResumableUploadSignOptionsWithId,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'read' as const,
    keywords: ['preflight'],
  },
  {
    name: 'supabaseInvokeEdgeFunction',
    description: supabaseInvokeEdgeFunction.description!,
    tool: supabaseInvokeEdgeFunction,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'write' as const,
    keywords: ['call', 'trigger'],
  },
  {
    name: 'supabaseListAllOrganizations',
    description: supabaseListAllOrganizations.description!,
    tool: supabaseListAllOrganizations,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'read' as const,
    keywords: ['browse', 'enumerate'],
  },
  {
    name: 'supabaseListAllProjects',
    description: supabaseListAllProjects.description!,
    tool: supabaseListAllProjects,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'read' as const,
    keywords: ['browse', 'enumerate'],
  },
  {
    name: 'supabaseListBackups',
    description: supabaseListBackups.description!,
    tool: supabaseListBackups,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'read' as const,
    keywords: ['browse', 'enumerate'],
  },
  {
    name: 'supabaseListBranches',
    description: supabaseListBranches.description!,
    tool: supabaseListBranches,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'read' as const,
    keywords: ['browse', 'enumerate'],
  },
  {
    name: 'supabaseListBuckets',
    description: supabaseListBuckets.description!,
    tool: supabaseListBuckets,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'read' as const,
    keywords: ['browse', 'enumerate'],
  },
  {
    name: 'supabaseListDatabaseBranches',
    description: supabaseListDatabaseBranches.description!,
    tool: supabaseListDatabaseBranches,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'read' as const,
    keywords: ['browse', 'enumerate', 'postgres'],
  },
  {
    name: 'supabaseListFunctions',
    description: supabaseListFunctions.description!,
    tool: supabaseListFunctions,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'read' as const,
    keywords: ['browse', 'enumerate'],
  },
  {
    name: 'supabaseListMigrationHistory',
    description: supabaseListMigrationHistory.description!,
    tool: supabaseListMigrationHistory,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'read' as const,
    keywords: ['browse', 'enumerate', 'schema change'],
  },
  {
    name: 'supabaseListOrganizationMembers',
    description: supabaseListOrganizationMembers.description!,
    tool: supabaseListOrganizationMembers,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'read' as const,
    keywords: ['browse', 'enumerate', 'team account'],
  },
  {
    name: 'supabaseListProjectSecrets',
    description: supabaseListProjectSecrets.description!,
    tool: supabaseListProjectSecrets,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'read' as const,
    keywords: ['browse', 'enumerate', 'postgres instance'],
  },
  {
    name: 'supabaseListSecrets',
    description: supabaseListSecrets.description!,
    tool: supabaseListSecrets,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'read' as const,
    keywords: ['browse', 'enumerate'],
  },
  {
    name: 'supabaseListSqlSnippets',
    description: supabaseListSqlSnippets.description!,
    tool: supabaseListSqlSnippets,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'read' as const,
    keywords: ['browse', 'enumerate', 'query'],
  },
  {
    name: 'supabaseListSsoProviders',
    description: supabaseListSsoProviders.description!,
    tool: supabaseListSsoProviders,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'read' as const,
    keywords: ['browse', 'enumerate', 'single sign-on'],
  },
  {
    name: 'supabaseListTables',
    description: supabaseListTables.description!,
    tool: supabaseListTables,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'write' as const,
    keywords: ['browse', 'enumerate'],
  },
  {
    name: 'supabaseMergeBranch',
    description: supabaseMergeBranch.description!,
    tool: supabaseMergeBranch,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'write' as const,
    keywords: ['combine', 'preview environment'],
  },
  {
    name: 'supabasePatchMigration',
    description: supabasePatchMigration.description!,
    tool: supabasePatchMigration,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'write' as const,
    keywords: ['edit', 'schema change'],
  },
  {
    name: 'supabasePatchNetworkRestrictions',
    description: supabasePatchNetworkRestrictions.description!,
    tool: supabasePatchNetworkRestrictions,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'write' as const,
    keywords: ['edit', 'ip'],
  },
  {
    name: 'supabasePushBranch',
    description: supabasePushBranch.description!,
    tool: supabasePushBranch,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'write' as const,
    keywords: ['preview environment'],
  },
  {
    name: 'supabaseResetDatabaseBranch',
    description: supabaseResetDatabaseBranch.description!,
    tool: supabaseResetDatabaseBranch,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'write' as const,
    keywords: ['wipe', 'restore defaults', 'postgres', 'preview environment'],
  },
  {
    name: 'supabaseRestorePitrBackup',
    description: supabaseRestorePitrBackup.description!,
    tool: supabaseRestorePitrBackup,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'write' as const,
    keywords: ['recover', 'point-in-time recovery', 'snapshot'],
  },
  {
    name: 'supabaseRunReadOnlyQuery',
    description: supabaseRunReadOnlyQuery.description!,
    tool: supabaseRunReadOnlyQuery,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'write' as const,
    keywords: ['execute'],
  },
  {
    name: 'supabaseSelectFromTable',
    description: supabaseSelectFromTable.description!,
    tool: supabaseSelectFromTable,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'read' as const,
    keywords: ['query rows', 'relation'],
  },
  {
    name: 'supabaseUpdateAFunction',
    description: supabaseUpdateAFunction.description!,
    tool: supabaseUpdateAFunction,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'write' as const,
    keywords: ['edit', 'modify', 'patch', 'edge routine'],
  },
  {
    name: 'supabaseUpdateApiKey',
    description: supabaseUpdateApiKey.description!,
    tool: supabaseUpdateApiKey,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'write' as const,
    keywords: ['edit', 'modify', 'patch', 'credential'],
  },
  {
    name: 'supabaseUpdateBranch',
    description: supabaseUpdateBranch.description!,
    tool: supabaseUpdateBranch,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'write' as const,
    keywords: ['edit', 'modify', 'patch', 'preview environment'],
  },
  {
    name: 'supabaseUpdateDatabaseBranchConfig',
    description: supabaseUpdateDatabaseBranchConfig.description!,
    tool: supabaseUpdateDatabaseBranchConfig,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'write' as const,
    keywords: ['edit', 'modify', 'patch', 'postgres'],
  },
  {
    name: 'supabaseUpdateDatabasePassword',
    description: supabaseUpdateDatabasePassword.description!,
    tool: supabaseUpdateDatabasePassword,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'write' as const,
    keywords: ['edit', 'modify', 'patch', 'postgres'],
  },
  {
    name: 'supabaseUpdateFunctions',
    description: supabaseUpdateFunctions.description!,
    tool: supabaseUpdateFunctions,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'write' as const,
    keywords: ['edit', 'modify', 'patch'],
  },
  {
    name: 'supabaseUpdateJitAccessConfig',
    description: supabaseUpdateJitAccessConfig.description!,
    tool: supabaseUpdateJitAccessConfig,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'write' as const,
    keywords: ['edit', 'modify', 'patch', 'settings'],
  },
  {
    name: 'supabaseUpdatePgsodiumConfig',
    description: supabaseUpdatePgsodiumConfig.description!,
    tool: supabaseUpdatePgsodiumConfig,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'write' as const,
    keywords: ['edit', 'modify', 'patch', 'encryption key'],
  },
  {
    name: 'supabaseUpdateProject',
    description: supabaseUpdateProject.description!,
    tool: supabaseUpdateProject,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'write' as const,
    keywords: ['edit', 'modify', 'patch', 'postgres instance'],
  },
  {
    name: 'supabaseUpdateProjectAuthConfig',
    description: supabaseUpdateProjectAuthConfig.description!,
    tool: supabaseUpdateProjectAuthConfig,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'write' as const,
    keywords: ['edit', 'modify', 'patch', 'postgres instance'],
  },
  {
    name: 'supabaseUpdateProjectCustomHostname',
    description: supabaseUpdateProjectCustomHostname.description!,
    tool: supabaseUpdateProjectCustomHostname,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'write' as const,
    keywords: ['edit', 'modify', 'patch', 'postgres instance'],
  },
  {
    name: 'supabaseUpdateProjectLegacyApiKeys',
    description: supabaseUpdateProjectLegacyApiKeys.description!,
    tool: supabaseUpdateProjectLegacyApiKeys,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'write' as const,
    keywords: ['edit', 'modify', 'patch', 'postgres instance'],
  },
  {
    name: 'supabaseUpdateProjectPostgresConfig',
    description: supabaseUpdateProjectPostgresConfig.description!,
    tool: supabaseUpdateProjectPostgresConfig,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'write' as const,
    keywords: ['edit', 'modify', 'patch', 'database'],
  },
  {
    name: 'supabaseUpdateProjectPostgrestConfig',
    description: supabaseUpdateProjectPostgrestConfig.description!,
    tool: supabaseUpdateProjectPostgrestConfig,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'write' as const,
    keywords: ['edit', 'modify', 'patch', 'settings'],
  },
  {
    name: 'supabaseUpdateProjectSupavisorConfig',
    description: supabaseUpdateProjectSupavisorConfig.description!,
    tool: supabaseUpdateProjectSupavisorConfig,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'write' as const,
    keywords: ['edit', 'modify', 'patch', 'postgres instance'],
  },
  {
    name: 'supabaseUpdateSslEnforcementConfig',
    description: supabaseUpdateSslEnforcementConfig.description!,
    tool: supabaseUpdateSslEnforcementConfig,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'write' as const,
    keywords: ['edit', 'modify', 'patch', 'tls'],
  },
  {
    name: 'supabaseUpdateSsoProvider',
    description: supabaseUpdateSsoProvider.description!,
    tool: supabaseUpdateSsoProvider,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'write' as const,
    keywords: ['edit', 'modify', 'patch', 'single sign-on'],
  },
  {
    name: 'supabaseUpsertMigration',
    description: supabaseUpsertMigration.description!,
    tool: supabaseUpsertMigration,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'write' as const,
    keywords: ['save', 'schema change'],
  },
  {
    name: 'supabaseVerifyCustomHostnameDns',
    description: supabaseVerifyCustomHostnameDns.description!,
    tool: supabaseVerifyCustomHostnameDns,
    requiredAuth: 'supabaseAccessToken' as const,
    scope: 'write' as const,
    keywords: ['reverify', 'confirm'],
  },
];
