// @ts-nocheck
import {
  jfrogPing,
  jfrogGetVersion,
  jfrogGetStorageInfo,
  jfrogGetLicense,
  jfrogGetRepositoryStorageSummary,
} from './system.js';
import {
  jfrogListRepositories,
  jfrogGetRepository,
  jfrogCreateRepository,
  jfrogUpdateRepository,
  jfrogDeleteRepository,
  jfrogListReplications,
  jfrogGetReplication,
  jfrogSaveReplication,
  jfrogDeleteReplication,
} from './repositories.js';
import {
  jfrogGetItemInfo,
  jfrogListFolder,
  jfrogGetFileStats,
  jfrogGetItemProperties,
  jfrogSetItemProperties,
  jfrogDeleteItemProperties,
  jfrogDeployArtifact,
  jfrogDownloadArtifact,
  jfrogDeleteArtifact,
  jfrogCopyArtifact,
  jfrogMoveArtifact,
} from './artifacts.js';
import {
  jfrogSearchAql,
  jfrogSearchArtifact,
  jfrogSearchArchive,
  jfrogSearchPattern,
  jfrogSearchGavc,
  jfrogSearchByProperty,
  jfrogSearchByChecksum,
  jfrogSearchLatestVersion,
  jfrogSearchByDate,
  jfrogSearchNotDownloaded,
} from './search.js';
import {
  jfrogListBuilds,
  jfrogGetBuild,
  jfrogGetBuildNumber,
  jfrogUploadBuildInfo,
  jfrogPromoteBuild,
  jfrogDeleteBuilds,
  jfrogListDockerTags,
  jfrogListDockerRepositories,
} from './builds.js';
import {
  jfrogListUsers,
  jfrogGetUser,
  jfrogSaveUser,
  jfrogDeleteUser,
  jfrogChangePassword,
  jfrogListGroups,
  jfrogGetGroup,
  jfrogSaveGroup,
  jfrogDeleteGroup,
  jfrogListPermissionTargets,
  jfrogGetPermissionTarget,
  jfrogSavePermissionTarget,
  jfrogDeletePermissionTarget,
  jfrogGetApiKey,
  jfrogCreateApiKey,
  jfrogRegenerateApiKey,
  jfrogRevokeApiKey,
  jfrogCreateArtifactoryToken,
} from './security.js';
import {
  jfrogCreateAccessToken,
  jfrogGetAccessToken,
  jfrogRefreshAccessToken,
  jfrogRevokeAccessToken,
  jfrogListProjects,
  jfrogGetProject,
  jfrogAssignProjectUser,
  jfrogAssignProjectGroup,
  jfrogRemoveProjectUser,
  jfrogRemoveProjectGroup,
  jfrogListWebhooks,
  jfrogGetWebhook,
  jfrogCreateWebhook,
  jfrogUpdateWebhook,
  jfrogDeleteWebhook,
  jfrogTestWebhook,
} from './platform.js';

export {
  jfrogPing,
  jfrogGetVersion,
  jfrogGetStorageInfo,
  jfrogGetLicense,
  jfrogGetRepositoryStorageSummary,
  jfrogListRepositories,
  jfrogGetRepository,
  jfrogCreateRepository,
  jfrogUpdateRepository,
  jfrogDeleteRepository,
  jfrogListReplications,
  jfrogGetReplication,
  jfrogSaveReplication,
  jfrogDeleteReplication,
  jfrogGetItemInfo,
  jfrogListFolder,
  jfrogGetFileStats,
  jfrogGetItemProperties,
  jfrogSetItemProperties,
  jfrogDeleteItemProperties,
  jfrogDeployArtifact,
  jfrogDownloadArtifact,
  jfrogDeleteArtifact,
  jfrogCopyArtifact,
  jfrogMoveArtifact,
  jfrogSearchAql,
  jfrogSearchArtifact,
  jfrogSearchArchive,
  jfrogSearchPattern,
  jfrogSearchGavc,
  jfrogSearchByProperty,
  jfrogSearchByChecksum,
  jfrogSearchLatestVersion,
  jfrogSearchByDate,
  jfrogSearchNotDownloaded,
  jfrogListBuilds,
  jfrogGetBuild,
  jfrogGetBuildNumber,
  jfrogUploadBuildInfo,
  jfrogPromoteBuild,
  jfrogDeleteBuilds,
  jfrogListDockerTags,
  jfrogListDockerRepositories,
  jfrogListUsers,
  jfrogGetUser,
  jfrogSaveUser,
  jfrogDeleteUser,
  jfrogChangePassword,
  jfrogListGroups,
  jfrogGetGroup,
  jfrogSaveGroup,
  jfrogDeleteGroup,
  jfrogListPermissionTargets,
  jfrogGetPermissionTarget,
  jfrogSavePermissionTarget,
  jfrogDeletePermissionTarget,
  jfrogGetApiKey,
  jfrogCreateApiKey,
  jfrogRegenerateApiKey,
  jfrogRevokeApiKey,
  jfrogCreateArtifactoryToken,
  jfrogCreateAccessToken,
  jfrogGetAccessToken,
  jfrogRefreshAccessToken,
  jfrogRevokeAccessToken,
  jfrogListProjects,
  jfrogGetProject,
  jfrogAssignProjectUser,
  jfrogAssignProjectGroup,
  jfrogRemoveProjectUser,
  jfrogRemoveProjectGroup,
  jfrogListWebhooks,
  jfrogGetWebhook,
  jfrogCreateWebhook,
  jfrogUpdateWebhook,
  jfrogDeleteWebhook,
  jfrogTestWebhook,
};

const AUTH = 'jfrogCredentials' as const;

export const jfrogTools = [
  {
    name: 'jfrogPing',
    description: 'Ping Artifactory; returns OK when reachable.',
    tool: jfrogPing,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['health', 'connectivity', 'status'],
  },
  {
    name: 'jfrogGetVersion',
    description: 'Get Artifactory version, license type, and add-ons.',
    tool: jfrogGetVersion,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['server', 'edition'],
  },
  {
    name: 'jfrogGetStorageInfo',
    description: 'Get storage summary: space, counts, file-store status.',
    tool: jfrogGetStorageInfo,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['capacity', 'disk', 'usage'],
  },
  {
    name: 'jfrogGetLicense',
    description: 'Get Artifactory license details and expiry.',
    tool: jfrogGetLicense,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['subscription', 'entitlement'],
  },
  {
    name: 'jfrogGetRepositoryStorageSummary',
    description: 'Get storage summary for one repository.',
    tool: jfrogGetRepositoryStorageSummary,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['capacity', 'repo', 'usage'],
  },
  {
    name: 'jfrogListRepositories',
    description: 'List repositories with type and package filters.',
    tool: jfrogListRepositories,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['repos', 'registries'],
  },
  {
    name: 'jfrogGetRepository',
    description: 'Get full configuration of one repository.',
    tool: jfrogGetRepository,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['repo', 'settings', 'fetch'],
  },
  {
    name: 'jfrogCreateRepository',
    description: 'Create or fully replace a repository.',
    tool: jfrogCreateRepository,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['repo', 'new', 'setup'],
  },
  {
    name: 'jfrogUpdateRepository',
    description: 'Partially update a repository configuration.',
    tool: jfrogUpdateRepository,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['repo', 'edit', 'patch'],
  },
  {
    name: 'jfrogDeleteRepository',
    description: 'Delete a repository and its content.',
    tool: jfrogDeleteRepository,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['repo', 'remove'],
  },
  {
    name: 'jfrogListReplications',
    description: 'List replication configurations.',
    tool: jfrogListReplications,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['sync', 'mirror'],
  },
  {
    name: 'jfrogGetReplication',
    description: 'Get replication config of one repository.',
    tool: jfrogGetReplication,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['sync', 'schedule'],
  },
  {
    name: 'jfrogSaveReplication',
    description: 'Create or update a repository replication config.',
    tool: jfrogSaveReplication,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['sync', 'mirror', 'schedule'],
  },
  {
    name: 'jfrogDeleteReplication',
    description: 'Delete a repository replication config.',
    tool: jfrogDeleteReplication,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['sync', 'remove'],
  },
  {
    name: 'jfrogGetItemInfo',
    description: 'Get file or folder info: checksums, size, children.',
    tool: jfrogGetItemInfo,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['artifact', 'metadata', 'fetch'],
  },
  {
    name: 'jfrogListFolder',
    description: 'List folder children with deep traversal options.',
    tool: jfrogListFolder,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['browse', 'contents', 'directory'],
  },
  {
    name: 'jfrogGetFileStats',
    description: 'Get file download statistics and usage.',
    tool: jfrogGetFileStats,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['downloads', 'analytics'],
  },
  {
    name: 'jfrogGetItemProperties',
    description: 'Get metadata properties of a file or folder.',
    tool: jfrogGetItemProperties,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['metadata', 'labels', 'tags'],
  },
  {
    name: 'jfrogSetItemProperties',
    description: 'Attach metadata properties to a file or folder.',
    tool: jfrogSetItemProperties,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['metadata', 'label', 'tagging'],
  },
  {
    name: 'jfrogDeleteItemProperties',
    description: 'Delete metadata properties from an item.',
    tool: jfrogDeleteItemProperties,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['metadata', 'untag', 'remove'],
  },
  {
    name: 'jfrogDeployArtifact',
    description: 'Deploy a text-based artifact with checksums.',
    tool: jfrogDeployArtifact,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['upload', 'publish', 'push'],
  },
  {
    name: 'jfrogDownloadArtifact',
    description: 'Download a small artifact base64-encoded.',
    tool: jfrogDownloadArtifact,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['fetch', 'pull', 'retrieve'],
  },
  {
    name: 'jfrogDeleteArtifact',
    description: 'Delete a file or folder from a repository.',
    tool: jfrogDeleteArtifact,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['remove', 'artifact'],
  },
  {
    name: 'jfrogCopyArtifact',
    description: 'Copy a file or folder to another repo path.',
    tool: jfrogCopyArtifact,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['duplicate', 'promote', 'clone'],
  },
  {
    name: 'jfrogMoveArtifact',
    description: 'Move a file or folder to another repo path.',
    tool: jfrogMoveArtifact,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['relocate', 'promote', 'transfer'],
  },
  {
    name: 'jfrogSearchAql',
    description: 'Search with Artifactory Query Language.',
    tool: jfrogSearchAql,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['query', 'find'],
  },
  {
    name: 'jfrogSearchArtifact',
    description: 'Quick search artifacts by file name.',
    tool: jfrogSearchArtifact,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['find', 'lookup', 'filename'],
  },
  {
    name: 'jfrogSearchArchive',
    description: 'Search inside archive files by entry name.',
    tool: jfrogSearchArchive,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['jar', 'zip', 'entries'],
  },
  {
    name: 'jfrogSearchPattern',
    description: 'Search artifacts by Ant-style path pattern.',
    tool: jfrogSearchPattern,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['glob', 'layout', 'wildcard'],
  },
  {
    name: 'jfrogSearchGavc',
    description: 'Search Maven artifacts by GAVC coordinates.',
    tool: jfrogSearchGavc,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['maven', 'coordinates', 'pom'],
  },
  {
    name: 'jfrogSearchByProperty',
    description: 'Search artifacts by metadata properties.',
    tool: jfrogSearchByProperty,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['labels', 'tags', 'filter'],
  },
  {
    name: 'jfrogSearchByChecksum',
    description: 'Find artifacts by md5/sha1/sha256 checksum.',
    tool: jfrogSearchByChecksum,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['hash', 'digest', 'identify'],
  },
  {
    name: 'jfrogSearchLatestVersion',
    description: 'Resolve the latest artifact version by coordinates.',
    tool: jfrogSearchLatestVersion,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['newest', 'maven', 'release'],
  },
  {
    name: 'jfrogSearchByDate',
    description: 'Search artifacts by created/modified/downloaded range.',
    tool: jfrogSearchByDate,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['stale', 'cleanup', 'range'],
  },
  {
    name: 'jfrogSearchNotDownloaded',
    description: 'Find artifacts never downloaded since a time.',
    tool: jfrogSearchNotDownloaded,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['unused', 'stale', 'cleanup'],
  },
  {
    name: 'jfrogListBuilds',
    description: 'List all builds with build-info links.',
    tool: jfrogListBuilds,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['ci', 'runs'],
  },
  {
    name: 'jfrogGetBuild',
    description: 'List all runs of one build.',
    tool: jfrogGetBuild,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['ci', 'numbers', 'history'],
  },
  {
    name: 'jfrogGetBuildNumber',
    description: 'Get full build-info of one build run.',
    tool: jfrogGetBuildNumber,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['ci', 'details', 'provenance'],
  },
  {
    name: 'jfrogUploadBuildInfo',
    description: 'Publish build-info JSON for a build run.',
    tool: jfrogUploadBuildInfo,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['ci', 'publish', 'metadata'],
  },
  {
    name: 'jfrogPromoteBuild',
    description: 'Promote a build to a target repository.',
    tool: jfrogPromoteBuild,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['release', 'staging', 'copy'],
  },
  {
    name: 'jfrogDeleteBuilds',
    description: 'Delete build runs, optionally with artifacts.',
    tool: jfrogDeleteBuilds,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['ci', 'retention', 'cleanup'],
  },
  {
    name: 'jfrogListDockerTags',
    description: 'List tags of a Docker image.',
    tool: jfrogListDockerTags,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['container', 'image', 'versions'],
  },
  {
    name: 'jfrogListDockerRepositories',
    description: 'List Docker image repositories (catalog).',
    tool: jfrogListDockerRepositories,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['container', 'registry', 'images'],
  },
  {
    name: 'jfrogListUsers',
    description: 'List Artifactory users.',
    tool: jfrogListUsers,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['accounts', 'members'],
  },
  {
    name: 'jfrogGetUser',
    description: 'Get one Artifactory user.',
    tool: jfrogGetUser,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['account', 'fetch'],
  },
  {
    name: 'jfrogSaveUser',
    description: 'Create or replace a user.',
    tool: jfrogSaveUser,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['account', 'provision'],
  },
  {
    name: 'jfrogDeleteUser',
    description: 'Delete an Artifactory user.',
    tool: jfrogDeleteUser,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['account', 'remove'],
  },
  {
    name: 'jfrogChangePassword',
    description: 'Change a user password.',
    tool: jfrogChangePassword,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['credentials', 'rotation', 'reset'],
  },
  {
    name: 'jfrogListGroups',
    description: 'List Artifactory groups.',
    tool: jfrogListGroups,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['teams', 'roles'],
  },
  {
    name: 'jfrogGetGroup',
    description: 'Get one group with members.',
    tool: jfrogGetGroup,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['team', 'fetch'],
  },
  {
    name: 'jfrogSaveGroup',
    description: 'Create or replace a group.',
    tool: jfrogSaveGroup,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['team', 'provision'],
  },
  {
    name: 'jfrogDeleteGroup',
    description: 'Delete a group.',
    tool: jfrogDeleteGroup,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['team', 'remove'],
  },
  {
    name: 'jfrogListPermissionTargets',
    description: 'List permission targets.',
    tool: jfrogListPermissionTargets,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['acl', 'access'],
  },
  {
    name: 'jfrogGetPermissionTarget',
    description: 'Get one permission target with principals.',
    tool: jfrogGetPermissionTarget,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['acl', 'audit', 'fetch'],
  },
  {
    name: 'jfrogSavePermissionTarget',
    description: 'Create or replace a permission target.',
    tool: jfrogSavePermissionTarget,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['acl', 'grant'],
  },
  {
    name: 'jfrogDeletePermissionTarget',
    description: 'Delete a permission target.',
    tool: jfrogDeletePermissionTarget,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['acl', 'revoke'],
  },
  {
    name: 'jfrogGetApiKey',
    description: 'Get the caller API key.',
    tool: jfrogGetApiKey,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['legacy', 'credential'],
  },
  {
    name: 'jfrogCreateApiKey',
    description: 'Create an API key for the caller.',
    tool: jfrogCreateApiKey,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['legacy', 'generate'],
  },
  {
    name: 'jfrogRegenerateApiKey',
    description: 'Rotate the caller API key.',
    tool: jfrogRegenerateApiKey,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['legacy', 'rotation'],
  },
  {
    name: 'jfrogRevokeApiKey',
    description: 'Revoke the caller API key.',
    tool: jfrogRevokeApiKey,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['legacy', 'delete'],
  },
  {
    name: 'jfrogCreateArtifactoryToken',
    description: 'Create a scoped token via Artifactory API.',
    tool: jfrogCreateArtifactoryToken,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['oauth', 'scoped', 'ci'],
  },
  {
    name: 'jfrogCreateAccessToken',
    description: 'Create a scoped access token (JSON API).',
    tool: jfrogCreateAccessToken,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['oauth', 'scoped', 'ci'],
  },
  {
    name: 'jfrogGetAccessToken',
    description: 'Get access token metadata by ID.',
    tool: jfrogGetAccessToken,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['oauth', 'audit', 'fetch'],
  },
  {
    name: 'jfrogRefreshAccessToken',
    description: 'Refresh a refreshable token pair.',
    tool: jfrogRefreshAccessToken,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['oauth', 'renew'],
  },
  {
    name: 'jfrogRevokeAccessToken',
    description: 'Revoke an access token by ID.',
    tool: jfrogRevokeAccessToken,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['oauth', 'delete'],
  },
  {
    name: 'jfrogListProjects',
    description: 'List Platform projects.',
    tool: jfrogListProjects,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['workspaces', 'teams'],
  },
  {
    name: 'jfrogGetProject',
    description: 'Get one project by key.',
    tool: jfrogGetProject,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['workspace', 'fetch'],
  },
  {
    name: 'jfrogAssignProjectUser',
    description: 'Assign a user to a project with roles.',
    tool: jfrogAssignProjectUser,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['member', 'rbac', 'grant'],
  },
  {
    name: 'jfrogAssignProjectGroup',
    description: 'Assign a group to a project with roles.',
    tool: jfrogAssignProjectGroup,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['team', 'rbac', 'grant'],
  },
  {
    name: 'jfrogRemoveProjectUser',
    description: 'Remove a user from a project.',
    tool: jfrogRemoveProjectUser,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['member', 'unassign'],
  },
  {
    name: 'jfrogRemoveProjectGroup',
    description: 'Remove a group from a project.',
    tool: jfrogRemoveProjectGroup,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['team', 'unassign'],
  },
  {
    name: 'jfrogListWebhooks',
    description: 'List Event webhook subscriptions.',
    tool: jfrogListWebhooks,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['events', 'notifications'],
  },
  {
    name: 'jfrogGetWebhook',
    description: 'Get one webhook subscription.',
    tool: jfrogGetWebhook,
    requiredAuth: AUTH,
    scope: 'read' as const,
    keywords: ['event', 'fetch'],
  },
  {
    name: 'jfrogCreateWebhook',
    description: 'Create an Event webhook subscription.',
    tool: jfrogCreateWebhook,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['event', 'notify', 'subscribe'],
  },
  {
    name: 'jfrogUpdateWebhook',
    description: 'Replace a webhook subscription config.',
    tool: jfrogUpdateWebhook,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['event', 'edit'],
  },
  {
    name: 'jfrogDeleteWebhook',
    description: 'Delete a webhook subscription.',
    tool: jfrogDeleteWebhook,
    requiredAuth: AUTH,
    scope: 'delete' as const,
    keywords: ['event', 'unsubscribe'],
  },
  {
    name: 'jfrogTestWebhook',
    description: 'Send a test event to a webhook.',
    tool: jfrogTestWebhook,
    requiredAuth: AUTH,
    scope: 'write' as const,
    keywords: ['event', 'verify', 'ping'],
  },
];
